### ISSUE TITLE
[Config Support]: Control When Snapshots are Taken

### ISSUE THREAD

**Issue by weswitt** [blakeblackshear/frigate#6083]
### Describe the problem you are having

i have a camera at my front gate that i'm using to detect cars arriving and leaving. i have arriving working, but i'm having problems getting leaving to work because of when frigate takes the snapshot. i have three zone and track the car moving through the three zones. this seems to work but frigate is detecting the car when it is seen in the first zone. i need to get a snapshot when the car enters the third zone.  actually it would be best to have a unique snapshot for the object as it enters each zone as this would provide the best flexibility.  so my question is how can i get frigate to provide what i need?

![image](https://user-images.githubusercontent.com/15125944/232151509-a60c5cda-ec16-4741-8061-03ebf3405c85.png)

### Version

0.12.0 beta

### Frigate config file

```yaml
cameras:
  #
  # front gate camera
  #
  front_gate:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_gate
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
    objects:
      track:
        - car
    motion:
      mask:
        - 0,614,1920,570,1920,0,0,0
        - 0,1080,331,961,464,908,623,851,812,770,877,711,826,680,734,656,0,650
        - 1920,1080,1601,1080,1617,976,1636,888,1635,798,1657,732,1723,685,1834,649,1920,623
        - 719,655,841,691,861,738,660,839,0,1080,0,649
    zones:
      gate_road:
        coordinates: 1498,732,1423,640,767,656,854,675,870,729,833,754,760,807,1633,806
      gate_house:
        coordinates: 734,810,360,951,40,1080,1597,1080,1632,835
      gate_exit:
        coordinates: 1507,679,1699,685,1772,649,1776,575,1483,575
```

### Relevant log output

```shell
{
    "before": {
        "id": "1681502111.239496-hfx8bs",
        "camera": "front_gate",
        "frame_time": 1681502119.095172,
        "snapshot_time": 1681502113.441749,
        "label": "car",
        "sub_label": null,
        "top_score": 0.8826363682746887,
        "false_positive": false,
        "start_time": 1681502111.239496,
        "end_time": null,
        "score": 0.7269008755683899,
        "box": [1199, 335, 1788, 687],
        "area": 207328,
        "ratio": 1.6732954545454546,
        "region": [575, 0, 1907, 1332],
        "stationary": false,
        "motionless_count": 2,
        "position_changes": 1,
        "current_zones": [],
        "entered_zones": ["gate_house", "gate_road"],
        "has_clip": true,
        "has_snapshot": true
    },
    "after": {
        "id": "1681502111.239496-hfx8bs",
        "camera": "front_gate",
        "frame_time": 1681502119.239772,
        "snapshot_time": 1681502113.441749,
        "label": "car",
        "sub_label": null,
        "top_score": 0.8826363682746887,
        "false_positive": false,
        "start_time": 1681502111.239496,
        "end_time": null,
        "score": 0.8082897067070007,
        "box": [1256, 342, 1824, 674],
        "area": 188576,
        "ratio": 1.7108433734939759,
        "region": [628, 0, 1920, 1292],
        "stationary": false,
        "motionless_count": 3,
        "position_changes": 1,
        "current_zones": ["gate_exit"],
        "entered_zones": ["gate_house", "gate_road", "gate_exit"],
        "has_clip": true,
        "has_snapshot": true
    },
    "type": "update"
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

detector is an nvidia gpu
