### ISSUE TITLE
[Config Support]: Person Misclassification

### ISSUE THREAD

**Issue by victorlee115** [blakeblackshear/frigate#6090]
### Describe the problem you are having

<img width="430" alt="image" src="https://user-images.githubusercontent.com/126674491/232208582-97b966f8-3d94-4b92-a5f5-fa339dd4ac8a.png">

A misclassification of a person. What config changes can I make to prevent this from happening? Setting a max_area wouldn't work because a person can be of that size (a person lying down).

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
camera_19:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_19
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1440
      fps: 15
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 1440
      quality: 100
    objects:
      filters:
        person:
          min_area: 27000
    motion:
      contour_area: 15
      mask:
        - 1897,89,2509,89,2504,42,1897,40
```

### Relevant log output

```shell
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe
