### ISSUE TITLE
[Camera Support]: Go2rtc shows errors for 2 of 7 Unifi cameras

### ISSUE THREAD

**Issue by Perkinje** [blakeblackshear/frigate#6106]
### Describe the problem you are having

I'm converting over to using go2rtc. I have 7 Unifi cameras (2 instants, 1 flex, 2 doorbell and 2 pros). The pros will not work. Go2rtc shows a non-specific error and the feeds show no frames received.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.92
  port: 1883

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

database:
  path: /db/frigate.db

logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.edgetpu: warning

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti

birdseye:
  enabled: True
  mode: objects
  quality: 12

objects:
  track:
    - person
    - dog
    - car
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.6
      threshold: 0.8
    dog:
      min_area: 5000
      max_area: 100000
      min_score: 0.6
      threshold: 0.79

record:
  enabled: True
  events:
    pre_capture: 20
    post_capture: 30
    objects:
      - person
      - dog
      - package
    retain:
     default: 12
     mode: motion
     objects:
       person: 15

snapshots:
  enabled: True
  bounding_box: True
  crop: True
  retain:
    default: 10
    objects:
      person: 30

detect:
  fps: 5
  width: 1280
  height: 720
  max_disappeared: 30
  stationary:
    interval: 15
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

live:
  height: 720
  quality: 10

cameras:
  Package:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Package
          roles:
            - detect
    detect:
      width: 1600
      height: 1200
    snapshots:
      enabled: True
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 80

  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell
          roles:
            - detect
    detect: 
      width: 1600
      height: 1200
    snapshots:
      enabled: True
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 80

  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Living_Room
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      threshold: 25
      mask:
        - 1211,0,1211,280,696,271,681,26
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  Office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Office
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          roles:
            - detect
    record:
      events:
        required_zones:
          - street
          - drive
    snapshots:
      required_zones:
        - street
        - drive
    detect:
      width: 1920
      height: 1080
    zones:
      drive:
        coordinates: 1729,1080,1316,168,401,179,120,484,0,698,0,939,0,1080
        objects:
          - person
          - car
      street:
        coordinates: 1305,141,1663,195,1648,130,1614,107,1506,85,1095,76,899,65,760,71,566,89,274,121,35,163,23,231,554,150,892,143
        objects:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  Backyard_Upper_Deck:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard_Upper_Deck
          roles:
            - detect
    record:
      events:
        required_zones:
          - hot_tub
    snapshots:
      required_zones:
        - hot_tub
    detect:
      width: 1920
      height: 1080
    zones:
      hot_tub:
        coordinates: 722,897,745,758,731,752,582,775,519,796,466,931
        objects:
          - person
          - dog
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  Basement:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/Basement
            roles:
              - detect
      detect:
        width: 1920
        height: 1080
      mqtt:
        timestamp: False
        bounding_box: False
        crop: True
        height: 500
go2rtc:
  streams:
    Package:
      - rtspx://192.168.1.1:7441/***
    Doorbell:
      - rtspx://192.168.1.1:7441/***
    Living_Room:
      - rtspx://192.168.1.1:7441/***
    Office:
      - rtspx://192.168.1.1:7441/***
    Driveway:
      - rtspx://192.168.1.1:7441/***
    Backyard_Upper_Deck:
      - rtspx://192.168.1.1:7441/***
    Basement:
      - rtspx://192.168.1.1:7441/***
```

### Relevant log output

```shell
2023-04-16 19:34:27.476336783  [INFO] Preparing go2rtc config...
2023-04-16 19:34:27.743284601  [INFO] Starting go2rtc...
2023-04-16 19:34:27.804766503  19:34:27.804 INF go2rtc version 1.2.0 linux/amd64
2023-04-16 19:34:27.804948259  19:34:27.804 INF [api] listen addr=:1984
2023-04-16 19:34:27.805132916  19:34:27.805 INF [rtsp] listen addr=:8554
2023-04-16 19:34:27.805616473  19:34:27.805 INF [srtp] listen addr=:8443
2023-04-16 19:34:27.805756607  19:34:27.805 INF [webrtc] listen addr=:8555
2023-04-16 19:34:28.786666426  19:34:28.786 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error=EOF url=rtspx://192.168.1.1:7441/***
2023-04-16 19:34:28.808008998  19:34:28.807 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error=EOF url=rtspx://192.168.1.1:7441/***
2023-04-16 19:34:28.829933721  19:34:28.829 WRN [rtsp] error="source 0 error: EOF" stream=Driveway
2023-04-16 19:34:28.841279456  19:34:28.841 WRN [rtsp] error="source 0 error: EOF" stream=Backyard_Upper_Deck
```

### FFprobe output from your camera

```shell
ffprobe doesn't finish
```

### Frigate stats

```json
{"Backyard_Upper_Deck":{"camera_fps":0.0,"capture_pid":352,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":990,"pid":332,"process_fps":0.0,"skipped_fps":0.0},"Basement":{"camera_fps":5.0,"capture_pid":356,"detection_enabled":1,"detection_fps":6.9,"ffmpeg_pid":372,"pid":334,"process_fps":5.1,"skipped_fps":0.0},"Doorbell":{"camera_fps":5.0,"capture_pid":339,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":360,"pid":327,"process_fps":5.0,"skipped_fps":0.0},"Driveway":{"camera_fps":0.0,"capture_pid":347,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":992,"pid":331,"process_fps":0.0,"skipped_fps":0.0},"Living_Room":{"camera_fps":5.0,"capture_pid":342,"detection_enabled":1,"detection_fps":5.1,"ffmpeg_pid":354,"pid":328,"process_fps":5.0,"skipped_fps":0.0},"Office":{"camera_fps":5.1,"capture_pid":345,"detection_enabled":1,"detection_fps":12.3,"ffmpeg_pid":362,"pid":329,"process_fps":5.1,"skipped_fps":0.0},"Package":{"camera_fps":5.3,"capture_pid":336,"detection_enabled":1,"detection_fps":2.1,"ffmpeg_pid":341,"pid":325,"process_fps":5.3,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.5"},"1":{"cpu":"0.0","mem":"0.0"},"1005":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"4.0","mem":"2.2"},"118":{"cpu":"0.0","mem":"0.1"},"122":{"cpu":"0.0","mem":"0.1"},"123":{"cpu":"0.0","mem":"0.1"},"124":{"cpu":"0.0","mem":"0.1"},"125":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.3","mem":"0.6"},"306":{"cpu":"0.3","mem":"0.1"},"307":{"cpu":"5.3","mem":"0.8"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"5.0","mem":"0.8"},"315":{"cpu":"1.7","mem":"0.7"},"32":{"cpu":"0.0","mem":"0.0"},"323":{"cpu":"0.0","mem":"0.1"},"325":{"cpu":"2.3","mem":"0.8"},"326":{"cpu":"0.0","mem":"0.1"},"327":{"cpu":"1.0","mem":"0.8"},"328":{"cpu":"0.7","mem":"0.8"},"329":{"cpu":"3.0","mem":"0.8"},"330":{"cpu":"0.0","mem":"0.1"},"331":{"cpu":"0.0","mem":"0.7"},"332":{"cpu":"0.0","mem":"0.7"},"333":{"cpu":"0.0","mem":"0.1"},"334":{"cpu":"5.3","mem":"0.8"},"335":{"cpu":"0.0","mem":"0.2"},"336":{"cpu":"2.3","mem":"0.7"},"339":{"cpu":"2.7","mem":"0.7"},"340":{"cpu":"0.0","mem":"0.1"},"341":{"cpu":"5.0","mem":"1.0"},"342":{"cpu":"2.3","mem":"0.7"},"345":{"cpu":"2.7","mem":"0.7"},"347":{"cpu":"0.3","mem":"0.7"},"350":{"cpu":"0.0","mem":"0.1"},"352":{"cpu":"0.0","mem":"0.7"},"354":{"cpu":"5.7","mem":"1.1"},"356":{"cpu":"2.7","mem":"0.7"},"359":{"cpu":"0.0","mem":"0.1"},"360":{"cpu":"6.0","mem":"1.0"},"362":{"cpu":"6.0","mem":"1.1"},"372":{"cpu":"6.3","mem":"1.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"4.0","mem":"0.2"},"981":{"cpu":"0.0","mem":"0.0"},"99":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"8189.3","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":26.4,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":8.92,"pid":307},"coral2":{"detection_start":0.0,"inference_speed":8.51,"pid":310}},"gpu_usages":{"amd-vaapi":{"gpu":"1.67 %","mem":"34.00 %"}},"service":{"last_updated":1681699161,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":1055.8,"mount_type":"tmpfs","total":1073.7,"used":18.0},"/media/frigate/clips":{"free":22077173.6,"mount_type":"cifs","total":28217877.2,"used":6140703.6},"/media/frigate/recordings":{"free":22077173.6,"mount_type":"cifs","total":28217877.2,"used":6140703.6},"/tmp/cache":{"free":1958.8,"mount_type":"tmpfs","total":2000.0,"used":41.2}},"temperatures":{},"uptime":293,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G3 Pro and G4 Pro
