### ISSUE TITLE
[Support]: Storage Volumes Changing Names

### ISSUE THREAD

**Issue by FigJam23** [blakeblackshear/frigate#6108]
Hello,

I'm having an issue with my Frigate Configuration setup on Docker, and I'm hoping someone could help me out. Here's the rundown of the problem:

I'm running the latest version of Ubuntu Desktop, with Frigate up and running.
Initially, I set the storage camera recording address to my second 2TB HDD, and everything worked fine.
However, after I rebooted my machine, Frigate created a new directory called "storage", and changed my original storage folder under "media/user/storage/
To media/user/storage1 and creates a new storage folder
Now, Frigate is writing to this new storage folder, which is filling up my OS HDD (250GB) instead of my storage HDD (2TB).
I'm not sure what caused this change in behavior, and I'm not sure how to fix it.
Here's my docker-compose.yaml config file:

```

version: '3.9'
services:
frigate:
container_name: frigate
privileged: true
restart: unless-stopped
image: ghcr.io/blakeblackshear/frigate:stable
shm_size: "550mb"
devices:
- /dev/bus/usb:/dev/bus/usb
- /dev/apex_0:/dev/apex_0
- /dev/apex_1:/dev/apex_1
- /dev/nvidia0:/dev/nvidia0
volumes:
- /etc/localtime:/etc/localtime:ro
- /mnt/hubfiles/frigate/frigate.yml:/config/config.yml
- /media/mike/Storage/frigate_media:/media/frigate
- /home/your_user_id/frigate:/db
- type: tmpfs
target: /tmp/cache
tmpfs:
size: 1000000000
ports:
- "5000:5000"
- "1935:1935"
- "8554:8554"
environment:
- NVIDIA_VISIBLE_DEVICES=all
- NVIDIA_DRIVER_CAPABILITIES=all


```
I'm thinking that this issue might be related to how the volumes are configured. Perhaps the new "storage" directory is not being properly mounted to my internal sata storage HDD. If anyone could help me diagnose and resolve this issue, I would be very grateful.

Thank you very much for your time.

### Frigate config file
```
mqtt:
  host: 192.168.1.44
  port: 1883
  user: mqtt
  password: Jdfhjyfg
  
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects
  
#database: 
#  path: /media/NAS/cctv/frigate/frigate.db
  
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 90
    objects:
      person: 30
ffmpeg:

  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
    
rtmp:
  enabled: false
  
go2rtc:
  streams:
    360cam:
      - rtsp://admin:Jusfgggh@192.168.1.66:554/MediaInput/h264
      - "ffmpeg:back#video=h264"
    front_entry:
      - rtsp://admin:Jdsfgh3p@192.168.1.226:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_entry#video=h264#audio=aac"
    front_deck:
      - rtsp://admin:Jugghh@192.168.1.30:554/Streaming/channels/201
    driveway_cam:
      - rtsp://admin:Juffff33p@192.168.1.30:554/Streaming/channels/101   
    back_shed:
      - rtsp://admin:Jggggj33p@192.168.1.30:554/Streaming/channels/301   
    sand_pit:
      - rtsp://admin:Juhhhf@192.168.1.30:554/Streaming/channels/401      
      

###################################################################################            
cameras:
  front_entry:
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://admin:Juggg3ggp@192.168.1.226:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect  
           
        - path: rtsp://admin:ggJusgfffg@192.168.1.226:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record 
    motion:
      mask:    
        - 1920,632,1874,713,1889,658,1820,448,1725,448,1657,459,1577,531,1513,580,1389,575,1281,691,1310,798,1515,989,1649,1080,1920,1080
        - 1531,0,1890,40,1859,207,1506,202   
    detect:
      width: 1920
      height: 1080
      fps: 5   
    objects:
      filters:
        person:
          mask:
            - 354,219,343,25,524,0,743,0,747,133
            - 270,314,32,393,0,270,0,140,221,69        
      track:
        - person
        - dog
        - cat   

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      crop: true
      retain:
        default: 20
        objects:
          person: 30

###############################################################################################################################
      
  front_deck:
    ui:
      order: 3
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://admin:Jffg3p@192.168.1.30:554/Streaming/channels/202 
          roles:
            - detect
    
        - path: rtsp://admin:Jvfffp@192.168.1.30:554/Streaming/channels/201 
          roles:
            - record 
    motion:
      mask:   
        - 0,2160,838,2160,0,441,0,1287
        - 818,845,1242,399,1272,222,1444,367,1563,246,1738,79,2272,205,2573,348,2622,288,2369,0,2021,0,863,0,439,653
        - 2788,508,3009,212,3273,315,3453,616,3428,776,3453,1057,3330,1161,2842,737
    detect:
      width: 3840
      height: 2160
      fps: 5   
    objects:
      track:
        - person
        - cat   
 
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      crop: true
      retain:
        default: 20
        objects:
          person: 30
 
 #####################################################################################################################################                     
  driveway_cam:
    ui:
      order: 0
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://admin:Juhggh3p@192.168.1.30:554/Streaming/channels/102
          roles:
            - detect  
        - path: rtsp://admin:Juffgghp@192.168.1.30:554/Streaming/channels/101
          roles:
            - record   
    motion:
      mask:  
        - 2758,293,2859,734,2558,1225,2770,1188,3172,1099,3258,1008,3554,981,3801,932,3840,720,3808,25,2470,0
        - 3350,2115,3266,1797,3458,1400,3700,1287,3732,1028,2080,1686,1844,2132
        - 463,1439,180,914,670,609,527,500,0,855,0,1910,387,2075
        - 2253,471,2095,392,2194,288,2285,187,2391,271,2455,510     
    record:
      events:
        required_zones:
          - cars
          - all       
    zones:  
      cars:
        coordinates: 2364,641,1693,929,2154,1043,2265,1526,1738,2160,3840,2160,3840,705,2923,572,2371,370,2179,424
        objects:
          - car
      all:
        coordinates: 1614,0,0,0,0,2160,3840,2160,3840,1513,3810,0
        objects:   
          - person
          - cat  
                                                               
    detect:
      width: 3840
      height: 2160
      fps: 5
    objects:
      track:
        - person
        - car
        - cat   
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      crop: true
      retain:
        default: 20
        objects:
          person: 30
 ####################################################################################################################################################  
  back_shed:
    ui:
      order: 4
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://admin:Juffdf3p@192.168.1.30:554/Streaming/channels/302
          roles:
            - detect
        - path: rtsp://admin:Juddghjj33p@192.168.1.30:554/Streaming/channels/301
          roles:
            - record         
    motion:
      mask:    
        - 0,2160,2662,2160,2450,2031,2100,1821,1637,1678,1294,1380,1089,1361,826,1410,641,1163,478,1084,25,1296                                     
    detect:
      width: 3840
      height: 2160
      fps: 5
    objects:
      track:
        - person
        - cat   

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      crop: true
      retain:
        default: 20
        objects:
          person: 30
##########################################################################################################################################################          
  sand_pit:
    ui:
      order: 5  
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://admin:Jusfftgggddp@192.168.1.30:554/Streaming/channels/402
          roles:
            - detect
        - path: rtsp://admin:Jusfdffghhjjj3p@192.168.1.30:554/Streaming/channels/401
          roles:
            - record        
    motion:
      mask:    
        - 463,2160,148,1336,254,1230,227,993,498,619,870,537,882,656,1181,626,1420,1107,744,1333,1144,2122
        - 1447,190,2568,192,3138,200,2677,377,2844,688,3207,774,3384,907,3522,1104,3808,1430,3603,2026,2864,2105,1678,951,1701,490,1814,454,1430,375
        - 483,587,905,513,914,668,1400,624,1432,249,468,350                                  
    detect:
      width: 3840
      height: 2160
      fps: 5 
    objects:
      track:
        - person
        - car
        - cat   

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      crop: true
      retain:
        default: 20
        objects:
          person: 30
###########################################################################################################################          



  360cam:
    ui:
      order: 6
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://admin:Jushddjhffp@192.168.1.66:554/MediaInput/h264
          roles:
            - detect
            - record        
    motion:
 
                            
    detect:
      width: 1920
      height: 1080
      fps: 5 
    objects:
      track:
        - person
    
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      crop: true
      retain:
        default: 20
        objects:
          person: 30
          
         
 #####################################################################################################################################         
#testing
#####################################################################################################################################
```
