### ISSUE TITLE
[Support]: go2rtc dashboard error 404

### ISSUE THREAD

**Issue by Allkorolev** [blakeblackshear/frigate#6152]
### Describe the problem you are having

Good afternoon, there is a link to go2rtc dashboard in the System tab.
When I click on it, I get a 404 error, tell me how to fix it? Everything is configured in the config according to the documentation

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: mqttpsw


ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  
go2rtc:
  streams:
    # Cam_kalitka
    rtsp_cam_kalitka:
      - rtsp://10.10.0.49:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
      #- "ffmpeg:rtsp_cam_kalitka#video=h264"
      #- "ffmpeg:rtsp_cam_kalitka#video=mjpeg"

    # Cam_vorota
    rtsp_cam_vorota:
      - rtsp://10.10.0.142:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
      #- "ffmpeg:rtsp_cam_vorota#video=h264"

    # Cam_viezd
    rtsp_cam_viezd:
      - rtsp://10.10.0.150:554/user=admin_password=nVr1w7FD_channel=1_stream=0.sdp?real_stream
      #- "ffmpeg:rtsp_cam_viezd#video=h264"

    # Cam_dom_vhod
    rtsp_cam_dom_vhod:
      - rtsp://10.10.0.141:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
      #- "ffmpeg:rtsp_cam_dom_vhod#video=h264"
  webrtc:
    candidates:
      - 10.10.0.3:8555
      - stun:8555
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

-
