### ISSUE TITLE
[Config Support]: MQTT not running at all??

### ISSUE THREAD

**Issue by dennis071nl** [blakeblackshear/frigate#6157]
### Describe the problem you are having

My insrtance is running, docker based on server A, HAOS on server B. I would like to integrate it within my node red flows (addon on HAOS). 

I cannot get the connection through MQTT, there are no signs that mqtt is even started in frigate. i included the mqtt settings in the config of frigate. 

### Version

0.12.0-DA3E197 go2rtc dashboard

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 192.168.2.175
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  #client_id: frigate
  # Optional: 'user'
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: 'mqttfrigate'
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: '%%%%%%%%%'
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  voordeur: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:%%%%%%%%@192.168.2.25:554/Streaming/channels/101 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    motion:
      mask:
        - 0,346,128,0,86,231,0,338,0,263,0,333,0,152,0,0,131,0
        - 972,441,864,391,793,428,791,462,791,588,780,720
        - 1280,674,1229,686,1191,676,1146,669,1101,663,1044,658,969,648,841,610,853,580,869,551,888,498,944,444,984,462,1054,489,1103,512,1157,536,1218,562,1259,584
        
    record:
      enabled: True
      events:
        retain:
          default: 10
  tuinhek: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.111:554/user=admin&password=%%%%%%%%%%&channel=1&stream=0.sdp# <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - bicycle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    motion:
      mask:
        - 591,720,1280,720,1280,0,589,617,580,539,579,456,581,388,582,320,576,229,596,624,1280,0,568,0,564,0
    record:
      enabled: True
      events:
        retain:
          default: 10
# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets


ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-vaapi
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic
```

### Relevant log output

```shell
2023-04-19 10:38:31.354577001  [INFO] Starting Frigate...
2023-04-19 10:38:34.946116082  [2023-04-19 10:38:34] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-19 10:38:35.043699627  [2023-04-19 10:38:35] peewee_migrate                 INFO    : Starting migrations
2023-04-19 10:38:35.056928885  [2023-04-19 10:38:35] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-19 10:38:35.082624274  [2023-04-19 10:38:35] frigate.app                    INFO    : Output process started: 292
2023-04-19 10:38:35.093333506  [2023-04-19 10:38:35] frigate.app                    INFO    : Camera processor started for voordeur: 295
2023-04-19 10:38:35.101050833  [2023-04-19 10:38:35] frigate.app                    INFO    : Camera processor started for tuinhek: 297
2023-04-19 10:38:35.113535663  [2023-04-19 10:38:35] frigate.app                    INFO    : Capture process started for voordeur: 299
2023-04-19 10:38:35.126608645  [2023-04-19 10:38:35] frigate.app                    INFO    : Capture process started for tuinhek: 300
2023-04-19 10:38:35.136103824  [2023-04-19 10:38:35] detector.cpu                   INFO    : Starting detection process: 291
2023-04-19 10:38:35.136116455  [2023-04-19 10:38:35] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
