### ISSUE TITLE
[Support]: False positives and masks

### ISSUE THREAD

**Issue by SunnyM-ha** [blakeblackshear/frigate#6162]
### Describe the problem you are having

I have a couple of cases of recurring false positives, I've tried adding masks to block out those areas but still seem to get spammed notifications. Any help on how I could change my config to eliminate those would be much appreciated.

I've included screenshots here : https://imgur.com/a/9NEHWM2 

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.3
  user: xxx
  password: xxx

detectors: 
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

cameras:

  front:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.3:8554/front
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1280
      fps: 1
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 30
    motion:
      mask:
        - 1867,1246,1385,1258,1387,1202,1878,1197

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.3:8554/driveway
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1280
      fps: 1
    objects:
      track:
        - person
#        - car
        - dog
    snapshots:
      enabled: true
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 30
    motion:
      mask:
      - 1867,1246,1385,1258,1387,1202,1878,1197

  back:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.6/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1280
      fps: 1
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 30
    motion:
      mask:
      - 1867,1246,1319,1280,1571,446,1852,456

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.3:8554/garage
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1280
      fps: 1
    objects:
      track:
        - person
    snapshots:
      enabled: true
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 30
    motion:
      mask:
      - 1867,1246,1385,1258,1387,1202,1878,1197
      - 698,808,742,1147,482,1132,502,801
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","bit_rate":"128000","codec_long_name":"PCMA-law/G.711A-law"}]}}]
```

### Frigate stats

```json
not sure how to get this in HomeAssistant?
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

WyzeCam V3

### Any other information that may be helpful

Ubuntu linux running HA-Supervised and Frigate installed via HACS
