### ISSUE TITLE
Can't start Frigate 12 [Support]: 

### ISSUE THREAD

**Issue by dnestico** [blakeblackshear/frigate#6168]
### Describe the problem you are having

I am trying to upgrade to the new frigate 12 in Unraid but am receiving this error, please help.

### Version

Frigate 12

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate:5000/api/config/schema

mqtt:
  host: 192.168.2.176
  user: mqtt
  password: mqtt
  port: 1883
  topic_prefix: frigate
  stats_interval: 
    60
  
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error
    frigate.app: error
    frigate.edgetpu: error

ui:
  use_experimental: true

detectors:
  coral:
    type: edgetpu
    device: usb
 
rtmp:
  enabled: false

cameras:
  porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.2.44/live
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    motion:
      improve_contrast: true
      mask:
        - 1403,664,1450,351,1473,0,1920,0,1920,1080,1324,1080
        - 0,504,169,469,441,392,377,0,0,0
        - 192,669,269,835,210,926,30,772,84,620
        - 540,586,627,798,663,968,573,1010,271,960,195,511
        -  548,745,648,657,862,703,897,883,784,929,625,937
    zones:
      porch_deck:
        coordinates: 448,1080,502,1022,602,1008,710,797,891,877,1130,782,1157,586,1392,763,1310,1080
        objects:
          - person
        filters:
          person:
            threshold: 0.78
      porch_stairs:
        coordinates: 578,999,512,1080,139,1080,218,979
        objects:
          - person
        filters:
          person:
            threshold: 0.75
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
        pre_capture: 5
        post_capture: 10
        required_zones:
          - porch_deck
          - porch_stairs
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
      timestamp: false
      retain:
        default: 7 
      required_zones:
        - porch_deck
        - porch_stairs
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.2.30/live
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        car:
          threshold: 0.8
          mask:
            - 496,167,974,217,1075,420,1107,720,1280,720,1280,0,0,0,0,720,309,720,328,466,400,216
        person:
          mask:
            - 0,0,0,0,1280,0,1280,720,1167,720,991,255,411,202,343,495,290,720,0,720
          threshold: 0.8
    motion:
      mask:
        - 570,379,682,0,0,0,0,1080,459,1080
        - 443,1080,546,420,816,429,1446,399,1689,1080,1920,1080,1920,0,0,0,0,1080
    zones:
      driveway_path:
        coordinates: 874,1080,827,398,542,393,417,1080
        objects:
          - person
#          - dog
#          - cat
        filters:
          person:
            threshold: 0.8
#          dog:
#            threshold: 0.8
#          cat:
#            threshold: 0.8
      driveway_pavement:
        coordinates: 1670,1080,1437,441,817,431,846,1080
        objects:
          - person
#          - dog
#          - cat
        filters:
          person:
            threshold: 0.8
#          dog:
#            threshold: 0.8
#          cat:
#            threshold: 0.8
      driveway_car:
        coordinates: 1390,403,1423,613,817,601,809,382
        objects:
          - car
        filters:
          car:
            threshold: 0.7
    record:
      enabled: true
      retain: 
        days: 7
        mode: motion
      events:
        retain:
          default: 7
        pre_capture: 5
        post_capture: 10
        required_zones:
          - driveway_pavement
          - driveway_path
          - driveway_car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 7
      required_zones:
        - driveway_pavement
        - driveway_path
        - driveway_car
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.2.31/live
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    motion:
      improve_contrast: true
      mask:
        - 719,0,716,523,643,1080,0,1080,0,0
        - 723,205,1272,200,1253,0,707,0
        - 1627,971,1920,842,1920,1080,1204,1080
    zones:
      garage_floor:
        coordinates: 762,1080,1184,1080,1657,975,1407,621,1261,420,729,422
        objects:
          - person
          - dog
        filters:
          person:
            threshold: 0.75
          dog:
            threshold: 0.8
      garage_car:
        coordinates: 1357,546,1437,699,771,764,753,574
        objects:
          - car
        filters:
          car:
            threshold: 0.8
    record:
      enabled: true
      retain: 
        days: 7
        mode: motion
      events:
        retain:
          default: 7
        pre_capture: 5
        post_capture: 10
        required_zones:
          - garage_car
          - garage_floor
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 7
      required_zones:
        - garage_car
        - garage_floor
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true

  luna:
    ffmpeg:
      inputs:
        - path: rtsp://rtspcam:admin@192.168.2.105/live
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - mouse
      filters:
        dog:
          threshold: 0.7
        mouse:
          threshold: 0.7
        person:
          threshold: 0.8
#    motion:
#      mask:
#        - 1252,720,1242,671,1100,665,1100,720
    record:
      enabled: true
      retain: 
        days: 7
        mode: motion
      events:
        retain:
          default: 7
        pre_capture: 5
        post_capture: 10
#        required_zones:
#          -
    snapshots:
        enabled: true
        bounding_box: true
        crop: false
        timestamp: false
        retain:
          default: 7
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true
```

### Relevant log output

```shell
docker run
  -d
  --name='frigate'
  --net='bridge'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="NesticoUnraid"
  -e HOST_CONTAINERNAME="frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='(removed)'
  -e 'PLUS_API_KEY'='(removed)'
  -e 'LIBVA_DRIVER_NAME'='iHD'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '5000:5000/tcp'
  -p '8554:8554/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -p '1984:1984/tcp'
  -v '/mnt/user/appdata/frigate':'/config':'rw'
  -v '/mnt/user/Media/frigate':'/media/frigate':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/bus/usb'
  --device='/dev/dri/renderD128'
  --shm-size=256mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=100000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:stable'
6916755f771289648d319fc2d2cad21e6f52880ab52b3457f379eefd203ceb4a
docker: Error response from daemon: driver failed programming external connectivity on endpoint frigate (e3baba98d8174d240fd5f5d980a6f9992b030bf97c0cbd9f51c28df1f8d16f14): Error starting userland proxy: listen tcp4 0.0.0.0:8555: bind: address already in use.

The command failed.
```

### FFprobe output from your camera

```shell
none
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Wyze Cam V2's and V3's

### Any other information that may be helpful

It worked great before Frigate 12 so just trying to upgrade on docker unraid.
