### ISSUE TITLE
[Support]: Invalid data found when processing input

### ISSUE THREAD

**Issue by marcocunha** [blakeblackshear/frigate#6175]
### Describe the problem you are having

Before I give up using Frigate I would like to ask you if you might spot a problem in my Frigate setup. The weird part here is that it works sometimes. (Although the majority of the time it doesn't)

I am using Frigate as a docker container (using the latest version) and this is my docker file:

```
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    # profiles:
      # - donotstart #do not start service
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SELF_HOME_DIR}/frigate/config/config.yml:/config/config.yml
      - "/Volumes/macOS Data/frigate/media:/media/frigate"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    env_file:
      - .env
```

But this is what I get when I access the Frigate dashboard:

![image](https://user-images.githubusercontent.com/11181679/233344126-7133cf60-d7f3-4052-b028-7e7307ecfe2d.png)

Now the weird part is that if I access Frigate > Config > go2rtc dashboard and click on that stream I can see the video.

Hardware that I am using:
- Mac mini late 2012
- Hikvision cameras

Any thoughts about this? I am more than happy to share more information if needed.

Thanks

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
go2rtc:
  streams:
    Garage_High:
      - ffmpeg:rtsp://user:password@ip_of_my_camera:554/cam/realmonitor?channel=1&subtype=0
    Garage_Low:
      - ffmpeg:rtsp://user:password@ip_of_my_camera:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 192.168.1.146:8555
      - stun:8555

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  Garage:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/Garage_High
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://127.0.0.1:8554/Garage_Low
          roles:
            - detect
    detect:
      width: 352 # <---- update for your camera's resolution
      height: 288 # <---- update for your camera's resolution
      fps: 5
    snapshots:
      required_zones:
        - Garage_Calcada
    record:
      events:
        required_zones:
          - Garage_Calcada
    mqtt:
      required_zones:
        - Garage_Calcada
    zones:
      Garage_Calcada:
        coordinates: 122,35,330,288,88,288,76,37
        objects:
          - person
          - car
        filters:
          person:
            # min_area: 5000
            # max_area: 100000
            threshold: 0.7
    motion:
      mask:
        - 122,39,352,288,352,0,123,0
    # Only include the "Garage" camera in Birdseye view when objects are detected
    birdseye:
      mode: objects
```

### Relevant log output

```shell
Frigate Logs:
2023-04-20 10:55:04.836074256 [2023-04-20 10:55:04] frigate.video ERROR : Garage: Unable to read frames from ffmpeg process.2023-04-20 10:55:04.837979760 [2023-04-20 10:55:04] frigate.video ERROR : Garage: ffmpeg process is not running. exiting capture thread...
(...)
2023-04-20 11:05:11.337481403 [2023-04-20 11:05:11] watchdog.Garage ERROR : Ffmpeg process crashed unexpectedly for Garage.2023-04-20 11:05:11.337691952 [2023-04-20 11:05:11] watchdog.Garage ERROR : The following ffmpeg logs include the last 100 lines prior to exit.2023-04-20 11:05:11.338025731 [2023-04-20 11:05:11] ffmpeg.Garage.detect ERROR : rtsp://127.0.0.1:8554/Garage_Low: Invalid data found when processing input

Go2RTC logs:
2023-04-20 11:22:51.057361184  11:22:51.057 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
```

### FFprobe output from your camera

```shell
libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5636e5e28140] method DESCRIBE failed: 404 Not Found
rtsp://user:password@ip_of_my_camera:554/cam/realmonitor?channel=1: Server returned 404 Not Found
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2125G0-IMS
