### ISSUE TITLE
[Support]: WebUI not playing video files

### ISSUE THREAD

**Issue by SchoolGuy** [blakeblackshear/frigate#6210]
### Describe the problem you are having

I have video files that play perfectly fine with VLC locally however in the WebUI, they refuse to play with the following error:

![grafik](https://user-images.githubusercontent.com/15035141/233836389-115be580-d9e0-4065-b4d7-64223b90be1e.png),

### Version

0.12.0

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: mosquitto.mqtt.svc.cluster.local
record:
  enabled: True
  retain:
    days: 90
    mode: motion
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 90
      mode: all
cameras:
  garten_dolly:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://<IP>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=viewer&password=<removed>
          roles:
            - record
            - rtmp
        - path: http://<IP>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=viewer&password=<removed>
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 920,0,919,47,357,46,357,0
  garten_igel:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<removed>@<IP>:554/h264_stream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    detect:
      width: 1280
      height: 720
  garten_vogel:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<removed>@<IP>:554/h264_stream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    record:
      retain:
        mode: motion
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 231,24,233,58,9,58,11,23
```

### Relevant log output

```shell
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
videojs-seek-buttons-fa3a5bd5.js:31:1499
MouseEvent.mozPressure sollte nicht mehr verwendet werden. Verwenden Sie PointerEvent.pressure stattdessen. videojs-seek-buttons-fa3a5bd5.js:33:5970
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
videojs-seek-buttons-fa3a5bd5.js:31:1499
Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable. videojs-seek-buttons-fa3a5bd5.js:61
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.5"},"1":{"cpu":"0.0","mem":"0.0"},"113":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.2"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"139":{"cpu":"0.0","mem":"0.1"},"148":{"cpu":"0.0","mem":"0.2"},"15":{"cpu":"0.0","mem":"0.0"},"165":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"187":{"cpu":"0.0","mem":"0.0"},"220":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"427":{"cpu":"0.3","mem":"0.5"},"433":{"cpu":"0.0","mem":"0.1"},"434":{"cpu":"8.0","mem":"0.7"},"436":{"cpu":"0.7","mem":"0.6"},"442":{"cpu":"10.7","mem":"0.7"},"443":{"cpu":"0.0","mem":"0.4"},"444":{"cpu":"0.0","mem":"0.6"},"445":{"cpu":"0.0","mem":"0.1"},"446":{"cpu":"0.7","mem":"0.6"},"447":{"cpu":"2.0","mem":"0.6"},"450":{"cpu":"0.0","mem":"0.6"},"453":{"cpu":"0.0","mem":"0.4"},"455":{"cpu":"2.3","mem":"0.6"},"459":{"cpu":"21.0","mem":"0.3"},"461":{"cpu":"0.0","mem":"0.1"},"462":{"cpu":"140.7","mem":"0.6"},"470":{"cpu":"2.3","mem":"0.2"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.2"},"9026":{"cpu":"0.0","mem":"0.0"},"9034":{"cpu":"0.0","mem":"0.1"},"9039":{"cpu":"0.0","mem":"0.0"},"9041":{"cpu":"1.0","mem":"0.2"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"2.3","mem":"1.1"},"MiB":{"cpu":"8431.3","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":4.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":29.8,"pid":434}},"garten_dolly":{"camera_fps":5.1,"capture_pid":447,"detection_enabled":1,"detection_fps":4.2,"ffmpeg_pid":459,"pid":442,"process_fps":5.0,"skipped_fps":0.0},"garten_igel":{"camera_fps":0.0,"capture_pid":450,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":9034,"pid":444,"process_fps":0.0,"skipped_fps":0.0},"garten_vogel":{"camera_fps":5.0,"capture_pid":455,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":462,"pid":446,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1682254988,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":1067.7,"mount_type":"tmpfs","total":1073.7,"used":6.0},"/media/frigate/clips":{"free":7606469.4,"mount_type":"btrfs","total":12001578.3,"used":4394202.5},"/media/frigate/recordings":{"free":7606469.4,"mount_type":"btrfs","total":12001578.3,"used":4394202.5},"/tmp/cache":{"free":383917.7,"mount_type":"overlay","total":478095.1,"used":93127.7}},"temperatures":{},"uptime":16176,"version":"0.12.0-da3e197"}}
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

iCSee

### Any other information that may be helpful

The install method is the official Helmchart and not the HassOS Addon.

The camera recording I am trying to see is the following:

https://green-backyard.com/collections/watch-on-smartphone-tablet-pc/products/outdoor-poe-wired-ip-bird-box-camera/

The only thing about the exact model I am able to tell you is that the app is from iCSee: https://icseeapp.com/
