### ISSUE TITLE
[Support]: No audio in WebRTC Card when using Frigate's go2rtc, yes audio with dedicated go2rtc

### ISSUE THREAD

**Issue by dbuezas** [blakeblackshear/frigate#6214]
### Describe the problem you are having

* When I configure go2rtc via frigate, I do get audio inside the Frigtate UI, but the WebRTC card never even shows the sound icon. I tested also the re-streamed url in vlc and get the same result.
* When I do this via the go2rtc Add-on instead, I get audio in the WebRTC cardbut there is no webrtc option iniside the frigate UI (only jsmpeg) and no audio.

### Version

0.12.0-da3e197, Add-On

### Frigate config file

```yaml
go2rtc: # I remove this wand put it in go2rtc.yaml when using the go2rtc Add-On
  streams:
    dafang3: 
      - rtsp://192.168.178.100:8554/unicast
    camarablanca:
      - rtsp://admin:xxxxxxx@192.168.178.27
mqtt:
  host: homeassistant.local
  user: frigate
  password: fripass
  topic_prefix: frigate
  client_id: frigate

cameras:
  dafang3:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/dafang3
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1600
      height: 900
      fps: 5
  camarablanca:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/camarablanca
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5

record:
  enabled: True
  retain:
    days: 7
    mode: active_objects

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  height: 900
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
objects:
  track:
    - person
    - cat
    - dog

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
can't find anything relevant
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1600x900
FPS: 25/1

Audio:

Codec: PCM mu-law / G.711 mu-law
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Xiaomi Dafang3 with "Xiaomi-Dafang-Hacks"

### Any other information that may be helpful

The same applies to the other camera (a cheap Chinese PLZ cam)

**Comment by NickM-27** [comment]
what does your webrtc-card config look like when setting up the card pointed at frigate:1984 ?

**Comment by dbuezas** [comment]
Hi @NickM-27 👋 

It looks like this:
```yaml
type: custom:webrtc-camera
url: rtsp://127.0.0.1:8554/dafang3
muted: false
intersection: 0
ui: true
# and some unrelated entries for plz
```

IIRC, it was exactly the same as `rtsp://homeassistant.local:8554/dafang3`.

**Comment by dbuezas** [comment]
And the integration was localhost I think (I picked what WebRTC Camera suggested for frigate)

**Comment by NickM-27** [comment]
You shouldn't use the RTSP url, for `url` you should just use the name of the camera 
`url: dafang3`

**Comment by dbuezas** [comment]
Oh wow! thank you, this works fine! how did I miss this!
And to grab the stream from VLC? (to watch from my tv)

**Comment by NickM-27** [comment]
You should use the rtsp link for VLC

**Comment by dbuezas** [comment]
That one `rtsp://homeassistant.local:8554/camera1` barely works in vlc now. I get 1 frame every 20 seconds and no sound. 
With the dedicated go2rtc addon it works well. Any tips fo that?

**Comment by NickM-27** [comment]
I don't see camera1 in your config so I don't know how that works at all.

**Comment by dbuezas** [comment]
Ok, sorry for that, I meant `dafang3` or `camarablanca`. I would like to use the re-streamed stream, as one of them tends to crash if more than one client is connected.

**Comment by NickM-27** [comment]
I'm assuming you've enabled port 8554? The only possible difference between frigate and go2rtc addon assuming identical config is that the addon has a newer version of go2rtc, can you confirm?

**Comment by dbuezas** [comment]
Correct, I enabled port 8554 and made a PR to the docs that is half wrong #6208 (i wrote that that was required for the WebRTC card)

I now checked that the go2rtc versions do doffer:
* Go2rtc addon: 1.4.0 
* frigate's go2rtc: 1.2.0

**Comment by NickM-27** [comment]
Then you should override the go2rtc from the container

**Comment by dbuezas** [comment]
That sounds like it would solve it all, but I'm on HomeAssistant OS with the frigate AddOn. Is it still possible to do it?
Thabks

**Comment by NickM-27** [comment]
Yes, just download the file to /config called go2rtc and make sure it has execute permissions

**Comment by NickM-27** [comment]
Well, we weren't talking about audio before, that's a separate issue. Does the stream play as expected?

**Comment by dbuezas** [comment]
The no-audio issue was here as well: https://github.com/blakeblackshear/frigate/issues/6214#issuecomment-1519176557
The stream plays but it is choppier than in the browser. And it seems to make frigate crash a lot too (I think this may have been the case before when using the go2rtc addon separately already)

**Comment by NickM-27** [comment]
By default frigate only asks for aac audio in the query. You need to use ?video&audio at the end of the RTSP url to get other types of audio in the restream

**Comment by dbuezas** [comment]
What I mean is that I used to get the camera audio to play in VLC when I was using the go2rtc AddOn. 🤷 
Anyway, I now reverted to the built in go2rtc v1.20 and made it reencode the audio as AAC and it looks like everything is working fine.
```
go2rtc:
  streams:
    dafang3:
      - "ffmpeg:rtsp://192.168.178.100:8554/unicast#video=copy#audio=pcmu"
```

BTW it looks like go2rtc v1.4 made frigate crash because it got out of RAM
![image](https://user-images.githubusercontent.com/777196/234066281-781e2852-a8eb-4a51-9aaf-76d9a44d17fb.png)

Thanks for your guidance.
