### ISSUE TITLE
[Config Support]: No Zones entities/devices showing up in Home Assistant

### ISSUE THREAD

**Issue by AndLindemann** [blakeblackshear/frigate#6216]
### Describe the problem you are having

I defined two zones for one of my cameras to detect if persons are entering specific parts of the property, however I don't get any sensors for the zones in Home Assistant. 
I looked through the MQTT messages being posted and it doesn't seem like Frigate is sending anything meaningful for these zones via MQTT, hence thinking this is more a core frigate issue than one with the HA integration.

The documentation suggests I should probably see sensors/binary_sensors in HA for these Zones in the same way as I see occupancy sensors for the cameras. But that isn't the case on my end. I only see the camera devices in HA and each camera device has a number of the usual occupancy sensors for the different objects. But there is no entities or devices related to the zones.

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: ip_addr
  user: user
  password: xyz

detectors:
  coral:
    type: edgetpu
    device: usb

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  #threshold: 30
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  #contour_area: 40
  #delta_alpha: 0.15

snapshots:
  enabled: True

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: motion

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - warning
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti

cameras:
  garten:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garten
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,33,173,25,175,0,0,0
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog
        - bird

  gartentor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gartentor
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,33,173,25,175,0,0,0
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog
        - bird

  stall:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/stall
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,33,173,25,175,0,0,0
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bird

  gehege:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gehege
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,33,173,25,175,0,0,0
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - cat
        - dog
        - bird

  klingel:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/klingel
          roles:
            - detect
            - record
    zones:
      vorgarten:
        coordinates: 0,720,960,720,960,549,816,513,733,491,562,440,198,481,64,559
      weg:
        coordinates: 564,438,456,414,410,344,377,326,236,335,150,478,313,465
    motion:
      mask:
        - 960,341,0,312,0,0,960,0
        - 775,539,577,494,506,469,496,430,612,358,679,315,752,311,821,390
    detect:
      width: 960
      height: 720
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog
        - bird

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

go2rtc:
  streams:
    klingel:
      - rtspx://10.0.10.62:7441/xyz
    garten:
      - rtspx://10.0.10.62:7441/xyz
    gartentor:
      - rtspx://10.0.10.62:7441/xyz
    gehege:
      - rtspx://10.0.10.62:7441/xyz
    stall:
      - rtspx://10.0.10.62:7441/xyz
  webrtc:
    candidates:
      - ....:....
```

### Relevant log output

```shell
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
