### ISSUE TITLE
Fixed web port of 5000 conflicts with synology

### ISSUE THREAD

**Issue by scstraus** [blakeblackshear/frigate#622]
Hi, 

What are the chances of bringing back the web port option? I run on a synology under docker and unfortunately the main UI and API of synology is also running on default port 5000. Many of their mobile apps do not work properly if they cannot access this port, try as I might. A different default port would have been much easier.

**Comment by farnots** [comment]
@scstraus Would love to have the possibility to change the frigate port. In the meantime you cand changes the synology one to bind to another port, all apps will work great with a change of port

**Comment by scstraus** [comment]
Not surveillance station mobile app I’m afraid.  I fought with it a long time before giving up and going back to defaults.

**Comment by blakeblackshear** [comment]
Can you use docker to change the port? Here is how you would do it in Compose:
```yaml
version: '3.6'
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: blakeblackshear/frigate:0.8.0-beta2-amd64
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - <path_to_config>:/config
      - <path_to_directory_for_clips>:/media/frigate/clips
      - <path_to_directory_for_recordings>:/media/frigate/recordings
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5001:5000'
      - '1935:1935' # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: 'password'
```
