### ISSUE TITLE
[Support]: Recording ERROR - retained recordings must be deleted.

### ISSUE THREAD

**Issue by Signal-Engineer** [blakeblackshear/frigate#6221]
### Describe the problem you are having

I have recently set up recording on my camera configs and find that after restarting Frigate, some camera clips are recorded and can be viewed in the frigate UI but eventually (after an hour or two) the recordings fail and nothing is visible in the UI, just an error message that advises that recording is not set up in the camera config. The frigate.record debug log shows that .mp4 clips are being saved from the cache to storage. I've now changed to the frigate.record debug log and attach these logs later.

Also possibly related. The storage information on the UI Storage page consistently shows approx 6GB storage used out of 10GB, even after completely deleting all the files in the frigate/media folders. Is this correct?

Recording of events (snapshots) works OK, no problems there. These are all catalogued and visible from the UI.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.x.x.x
  user: xxx
  password: xxx

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: info
  logs:
    frigate.storage: debug

go2rtc:
  streams:
    driveway:
      - rtsp://admin:xxxx@192.x.x.x:554/h264Preview_01_main
    terrace:
      - rtsp://admin:xxxx6@192.x.x.x:554/h264Preview_01_main
      - ffmpeg:terrace#audio=opus
    side_path:
      - rtsp://admin:xxxx@192.x.x.x:554/h264Preview_01_main
    garage:
      - rtsp://admin:xxxx@192.x.x.x:554/h264Preview_01_main
    hockey_pitch_new:
      - rtsp://admin:xxxx@192.x.x.x:554/h264Preview_01_main
      - ffmpeg:hockey_pitch_new#audio=opus
  webrtc:
    candidates:
      - 192.x.x.x:8555
      - stun:8555
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  
cameras:
  hockey_pitch_new:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hockey_pitch_new
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:xxxx@192.x.x.x:554/h264Preview_01_main
          roles: 
            - record    
    motion:
      mask:
        - 2304,0,2304,788,1919,657,1675,541,1435,468,1281,372,993,250,801,221,554,151,0,240,0,0
        - 0,554,561,528,567,269,436,160,0,160
        - 0,247,331,254,323,0,0,0
        - 1185,445,1352,519,1470,573,1614,631,1762,676,1861,733,1826,1009,1143,1265,0,1296,0,871,1092,759,826,324,1012,362
    rtmp:
      enabled: false
    detect:
      width: 2304
      height: 1296
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
    objects:
      track:
        - car
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.x.x.x:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:123456@192.168.0.54:554/h264Preview_01_main
          roles: 
            - record  
    motion:
      mask:
        - 1280,0,1280,306,985,201,697,128,0,0,389,0,448,0,493,0
        - 0,245,390,182,381,0,0,0
    zones:
      zone_0:
        coordinates: 317,157,790,155,1082,160,975,101,737,87,473,41
        objects:
          - car
          - person
          - dog
      zone_1:
        coordinates: 303,578,1280,580,1280,315,1235,205,288,198
        objects:
          - person
          - dog
    rtmp:
      enabled: false
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 20
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
    objects:
      track:
        - person
        - car
        - dog
      filters:
        car:
          mask: 
            - 1280,258,1280,585,327,582,286,263
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
  
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.x.x.x:554/h264Preview_01_main
          roles:
            - detect
            - record  
    motion:
      mask:  
        - 1280,0,1280,336,953,307,820,133,693,336,0,523,0,0,493,0
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask: 
            - 212,427,262,418,258,359,210,361
    rtmp:
      enabled: false
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
    
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
side_path:
    ffmpeg:
      inputs:
        - path: rtsp://admin:1xxxx@192.x.x.x:554/h264Preview_01_main
          roles:
            - detect            
            - record  
    motion:
      mask:
        - 1180,0,1042,211,1003,209,736,232,0,496,0,0,448,0,493,0
    rtmp:
      enabled: false
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
```

### Relevant log output

```shell
2023-04-23 20:55:43.795758920  [2023-04-23 21:55:43] frigate.storage                DEBUG   : hockey_pitch_new has a bandwidth of 0 MB/hr.
2023-04-23 20:55:43.795764192  [2023-04-23 21:55:43] frigate.storage                DEBUG   : driveway has a bandwidth of 0 MB/hr.
2023-04-23 20:55:43.795765815  [2023-04-23 21:55:43] frigate.storage                DEBUG   : garage has a bandwidth of 714.31 MB/hr.
2023-04-23 20:55:43.795767180  [2023-04-23 21:55:43] frigate.storage                DEBUG   : side_path has a bandwidth of 0 MB/hr.
2023-04-23 20:55:43.795769493  [2023-04-23 21:55:43] frigate.storage                DEBUG   : Default camera bandwidths: {'hockey_pitch_new': {'needs_refresh': True, 'bandwidth': 0}, 'driveway': {'needs_refresh': True, 'bandwidth': 0}, 'garage': {'needs_refresh': True, 'bandwidth': 714.31}, 'side_path': {'needs_refresh': True, 'bandwidth': 0}}.
2023-04-23 20:55:43.795770872  [2023-04-23 21:55:43] frigate.storage                DEBUG   : Storage cleanup check: 714.31 hourly with remaining storage: 357.4.
2023-04-23 20:55:43.795772178  [2023-04-23 21:55:43] frigate.storage                DEBUG   : Starting storage cleanup.
2023-04-23 20:55:43.806135023  [2023-04-23 21:55:43] frigate.storage                ERROR   : Could not clear 714.31 currently 5.9, retained recordings must be deleted.
2023-04-23 20:55:43.808736326  [2023-04-23 21:55:43] frigate.storage                DEBUG   : Expiring 3 recordings
```

### FFprobe output from your camera

```shell
garage
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1280x720
FPS: 20/1

driveway
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x360
FPS: 8/1

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1280x720
FPS: 20/1

hockey_pitch_new
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2304x1296
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Frigate stats

```json
DETECTORS
coral
P-ID	Inference Speed	CPU %	Memory %
283	9.43 ms	0.0%	1.3%
GPUS
VAINFO
intel-qsv
GPU %	Memory %
3.1 %	- %
CAMERAS
Hockey Pitch New
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	307	5	6.7%	1.0%
Capture	295	5	3.3%	1.1%
Detect	288	0 (0 skipped)	0.7%	1.7%
Driveway
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	27603	5	2.3%	0.6%
Capture	297	5	1.0%	1.0%
Detect	289	0 (0 skipped)	0.7%	1.3%
Garage
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	311	5.1	3.3%	0.6%
Capture	299	5.1	1.0%	1.0%
Detect	290	0 (0 skipped)	0.7%	1.3%
Side Path
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	318	5	4.0%	0.6%
Capture	303	5	1.0%	1.0%
Detect	292	0 (0 skipped)	0.7%	1.3%
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Swann NHD806 x3, Reolink RLC810A x1

### Any other information that may be helpful

If I can provide any other helpful diagnostic information, please let me know.
