### ISSUE TITLE
[Config Support]: RTSP UDP only cameras using go2rtc

### ISSUE THREAD

**Issue by joskfg** [blakeblackshear/frigate#6222]
### Describe the problem you are having

I'm migrating from frigate 0.11 to 0.12 and my cameras are UDP only support.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  input_args: preset-rtsp-udp

go2rtc:
  frontal:
    - rtsp://:@192.168.86.24:554/onvif1#input=rtsp/udp
  trastero:
    - rtsp://:@192.168.86.25:554/onvif1#input=rtsp/udp

cameras:
  frontal:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontal?video=copy
```

### Relevant log output

```shell
2023-04-23 23:34:39.013052694  [2023-04-24 01:34:39] frigate.video                  ERROR   : frontal: Unable to read frames from ffmpeg process.
2023-04-23 23:34:39.015000446  [2023-04-24 01:34:39] frigate.video                  ERROR   : frontal: Unable to read frames from ffmpeg process.
2023-04-23 23:34:39.015477088  [2023-04-24 01:34:39] frigate.video                  ERROR   : frontal: Unable to read frames from ffmpeg process.
2023-04-23 23:34:39.033716531  [2023-04-24 01:34:39] frigate.video                  ERROR   : frontal: Unable to read frames from ffmpeg process.
2023-04-23 23:34:39.035306639  [2023-04-24 01:34:39] frigate.video                  ERROR   : frontal: ffmpeg process is not running. exiting capture thread...
2023-04-23 23:34:39.069027691  [2023-04-24 01:34:39] frigate.video                  ERROR   : trastero: Unable to read frames from ffmpeg process.
2023-04-23 23:34:39.070278563  [2023-04-24 01:34:39] frigate.video                  ERROR   : trastero: ffmpeg process is not running. exiting capture thread...
2023-04-23 23:34:48.677496017  [2023-04-24 01:34:48] watchdog.frontal               ERROR   : Ffmpeg process crashed unexpectedly for frontal.
2023-04-23 23:34:48.692482244  [2023-04-24 01:34:48] watchdog.frontal               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"2.0","mem":"3.4"},"120":{"cpu":"0.0","mem":"0.3"},"137":{"cpu":"0.0","mem":"0.2"},"138":{"cpu":"0.0","mem":"0.2"},"139":{"cpu":"0.0","mem":"0.2"},"141":{"cpu":"0.0","mem":"0.2"},"15":{"cpu":"0.0","mem":"0.0"},"18":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"294":{"cpu":"0.3","mem":"2.1"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.3"},"301":{"cpu":"0.0","mem":"2.3"},"302":{"cpu":"0.0","mem":"2.3"},"306":{"cpu":"0.0","mem":"0.9"},"307":{"cpu":"0.0","mem":"2.2"},"308":{"cpu":"0.0","mem":"2.2"},"309":{"cpu":"0.7","mem":"2.2"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"0.0","mem":"0.9"},"311":{"cpu":"1.0","mem":"2.2"},"315":{"cpu":"0.0","mem":"0.9"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"824":{"cpu":"0.0","mem":"0.1"},"877":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.4"},"901":{"cpu":"0.3","mem":"0.1"},"902":{"cpu":"8.9","mem":"0.7"},"903":{"cpu":"8.9","mem":"0.8"},"95":{"cpu":"0.0","mem":"0.1"},"MiB":{"cpu":"2331.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"0.33,"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":301}},"frontal":{"camera_fps":0.0,"capture_pid":309,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":891,"pid":307,"process_fps":0.0,"skipped_fps":0.0},"gpu_usages":{"rpi-v4l2m2m":{"gpu":-1,"mem":-1}},"service":{"last_updated":1682293751,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":1987.9,"mount_type":"tmpfs","total":1988.6,"used":0.7},"/media/frigate/clips":{"free":37998.4,"mount_type":"ext4","total":62255.1,"used":21686.9},"/media/frigate/recordings":{"free":37998.4,"mount_type":"ext4","total":62255.1,"used":21686.9},"/tmp/cache":{"free":1988.6,"mount_type":"tmpfs","total":1988.6,"used":0.0}},"temperatures":{},"uptime":903,"version":"0.12.0-da3e197"},"trastero":{"camera_fps":0.0,"capture_pid":311,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":892,"pid":308,"process_fps":0.0,"skipped_fps":0.0}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

After checking the frigate source code and after checking the go2rtc configuration file I've found this:

```
api:
  origin: '*'
ffmpeg:
  rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg
    -rtsp_transport tcp -i {input}
frontal:
- ffmpeg:rtsp://:@192.168.86.24:554/onvif1#input=rtsp/udp
log:
  format: text
rtsp:
  default_query: mp4
webrtc:
  candidates:
  - 192.168.86.99:8555
  - stun:8555
```

So it is trying to use TCP transport, so it is the reason for the failure.

This command works in local
```
ffplay rtsp://:@192.168.86.25:554/onvif1 -loglevel debug -rtsp_transport udp
```

Checking https://github.com/blakeblackshear/frigate/blob/161e7b3fd75a9065fa6cbba082746b22708ed38f/docker/rootfs/usr/local/go2rtc/create_config.py I see the default behaviour is to set in as TCP, but I cannot se it to UDP.

There is not an easy way to change it to UDP.

Workaraound, replace all the ffmpeg config:
```
ffmpeg:
  rtsp: -fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport udp -i {input}
```
