### ISSUE TITLE
[HW Accel Support]: Issues with "preset-record-ubiquiti" in combination with "preset-rpi-64-h264"

### ISSUE THREAD

**Issue by htilly** [blakeblackshear/frigate#6228]
### Describe the problem you are having

When using preset for ubiquiti it seems impossible to add hwaccel_args for rpi4.
Tried both options below but all breaks the Unifi stream. 

Any suggestions? Or is this combination not possible?

ffmpeg:
#  hwaccel_args: preset-rpi-64-h264
#  hwaccel_args: -c:v h264_v4l2m2m
  output_args:
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: x.x.x.x
  port: 1883
  user: mqtt
  password: _password_
  topic_prefix: frigate
  client_id: frigate

ffmpeg:
#  hwaccel_args: preset-rpi-64-h264
#  hwaccel_args: -c:v h264_v4l2m2m
  output_args:
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti # recommend using go2rtc instead

record:
  enabled: true
  retain:
    days: 0
  events:
    retain:
      default: 10


detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  #width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  #height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
#  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
#  max_disappeared: 25



snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  crop: True
  # Optional: height to resize the snapshot to (default: original size)
  height: 500
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
      car: 15

cameras:

  altan:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/altan

          roles:
            - detect
            - record
            - rtmp

    detect:
      width: 1024 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5

    mqtt:
      enabled: True
      timestamp: false
      bounding_box: false
      crop: True
      quality: 100
      height: 500

  tradgard:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tradgard
          roles:
            - detect
            - record
            - rtmp

    detect:
      width: 1024 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5

    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

  doorbell:
    motion:
      mask: 
        - 0,380,0,469,394,405,422,385,413,332
        - 443,0,516,185,755,152,960,139,960,0
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
            - record
            - rtmp

    detect:
      width: 960 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5

    mqtt:
      enabled: True
      timestamp: false
      bounding_box: false
      crop: True
      quality: 100
      height: 500

go2rtc:
  streams:
    doorbell:
     - rtspx://x.x.x.x:7441/asdfghjkl
    altan:
     - rtspx://x.x.x.x:7441/asdfghjkl 

    tradgard:
     - rtspx://x.x.x.x:7441/asdfghjkl

    bird:
     - rtsp://x.x.x.x/user=xxx&password=yyy
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      #- /dev/dri/card0:/dev/dri/card0
      #- /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/frigate/config:/config
      - /config/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: '__xxxxx__'
```

### Relevant log output

```shell
frigate    | 2023-04-24 13:30:39.924167677  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable
frigate    | 2023-04-24 13:30:39.924723121  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   :     Last message repeated 13 times
frigate    | 2023-04-24 13:30:39.926221138  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   : [h264_v4l2m2m @ 0x559fc9ad80] V4L2 capture poll unexpected timeout: events=0x106
frigate    | 2023-04-24 13:30:39.926842896  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   : [h264_v4l2m2m @ 0x559fc9ad80] Poll thinks src Q has space; none found
frigate    | 2023-04-24 13:30:39.927388470  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   : [h264_v4l2m2m @ 0x559fc9ad80] V4L2 capture poll unexpected timeout: events=0x106
frigate    | 2023-04-24 13:30:39.928091358  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   : [h264_v4l2m2m @ 0x559fc9ad80] Poll thinks src Q has space; none found
frigate    | 2023-04-24 13:30:39.929182838  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   : Finishing stream 1:0 without any data written to it.
frigate    | 2023-04-24 13:30:39.929938300  [2023-04-24 13:30:39] ffmpeg.altan.detect            ERROR   : [swscaler @ 0x559ff430d0] deprecated pixel format used, make sure you did set range correctly
frigate    | 2023-04-24 13:30:40.027067513  [2023-04-24 13:30:40] watchdog.tradgard              ERROR   : Ffmpeg process crashed unexpectedly for tradgard.
frigate    | 2023-04-24 13:30:40.032348229  [2023-04-24 13:30:40] watchdog.tradgard              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2023-04-24 13:30:40.044488418  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable
frigate    | 2023-04-24 13:30:40.045449898  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   :     Last message repeated 2 times
frigate    | 2023-04-24 13:30:40.045989824  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   : [segment @ 0x559b0ecfa0] Non-monotonous DTS in output stream 0:1; previous: 730513, current: 728548; changing to 730514. This may result in incorrect timestamps in the output file.
frigate    | 2023-04-24 13:30:40.046985082  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   : [aac @ 0x559b11d4e0] Queue input is backward in time
frigate    | 2023-04-24 13:30:40.047982506  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   : [segment @ 0x559b0ecfa0] Non-monotonous DTS in output stream 0:1; previous: 730514, current: 729572; changing to 730515. This may result in incorrect timestamps in the output file.
frigate    | 2023-04-24 13:30:40.049067523  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   : [segment @ 0x559b0ecfa0] Non-monotonous DTS in output stream 0:1; previous: 730596, current: 727604; changing to 730597. This may result in incorrect timestamps in the output file.
frigate    | 2023-04-24 13:30:40.050383207  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable
frigate    | 2023-04-24 13:30:40.051384354  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   :     Last message repeated 2 times
frigate    | 2023-04-24 13:30:40.052038075  [2023-04-24 13:30:40] ffmpeg.tradgard.detect         ERROR   : [segment @ 0x559b0ecfa0] Non-monotonous DTS in output stream 0:1; previous: 730597, current: 728628; changing to 730598. This may result in incorrect timestamps in the output file.
```

### FFprobe output from your camera

```shell
...
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

UniFi UVC-G3-AF
