### ISSUE TITLE
Camera feeds not good after migrating to 0.8

### ISSUE THREAD

**Issue by yayitazale** [blakeblackshear/frigate#623]
I just migrated to 0.8 following all the steps of the docs with a fresh config file. I have configured the hwaccel_args with same parameters of the 0.7 and the ffmpeg input and output parameters are on by default. My CPU is a Pentium Gold 5600 and I'm passing the /dev/dri to the container.

On 0.7 everything was fine but on 0.8 the webui is showing 0 fps per camera and on hass using the rtmp this is what I see:

![imagen](https://user-images.githubusercontent.com/6462849/105969339-6cac9300-6088-11eb-9989-a461ca9a988a.png)

This is my config for ffmpeg:

```
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel fatal
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for clips streams (default: shown below)
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
```

And this is the config for the camera:

```
  oficina:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.XX:554/ch0_0.h264
          roles:
            - detect
            - rtmp
        - path: rtsp://192.168.1.XX:554/ch1_0.h264
          roles:
            - clips
            - record
    width: 1080
    height: 720
    fps: 5
    detect:
      enabled: True
    clips:
      enabled: True
    record:
      enabled: True
    rtmp:
      enabled: True
```

What I'm doing wrong?

Thanks
