### ISSUE TITLE
[Support]: Help with false positives 

### ISSUE THREAD

**Issue by palinf** [blakeblackshear/frigate#6233]
### Describe the problem you are having

I have trouble avoiding false positive with my car.
I think it is mainly due to the angle of the camera getting the reflexion of the glass roof: the leaves, sun and shades makes the algorithm detect changes. Even if the car is not moving. The detection usually commonly last for 12h

I can't apply the guide here: https://docs.frigate.video/guides/stationary_objects/
as I have not enough space for defining an entry zone.

Any other configuration I could reliably use to avoid these false positive ?

![Screenshot 2023-04-24 at 18 47 34](https://user-images.githubusercontent.com/10100366/234062917-06a5b538-8e9f-458e-8ee0-88d6c116175a.png)

### Version

0.12.0-da3e197

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb


motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
#  threshold: 25
  threshold: 15
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
#  contour_area: 30
  contour_area: 15





mqtt:
  host: mqtt.fdl
  user: mqtt
  password: mqtt

objects:
  track:
    - person
    - bycycle
    - car
    - motorcycle
    - boat
    - bird
    - cat
    - dog
    - horse
    - suitcase
    - cell phone
  filters:
    person:
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7


record:
  enabled: True
  retain:
    days: 30
    mode: all
  events:
#    objects:
#      - person
    retain:
      default: 30

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128


cameras:
  camera_buanderie:
    ffmpeg:
      inputs:
        - path: rtsp://camwifilannoire.fdl/12
          roles:
            - detect
              #            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 640
      height: 352
      fps: 5
    snapshots:
      enabled: True
    record:
      enabled: True
    rtmp:
      enabled: False


  camera_remise:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@camremise.fdl:554/h264Preview_01_sub

          roles:
            - detect
              #            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: True
    record:
      enabled: True
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - car
        - bycycle
        - bird
        - cat
        - dog
      # filters:
      #   person:
      #     min_score: 0.5
      #     threshold: 0.7
      #   car:
      #     min_score: 0.5
      #     threshold: 0.7

#
  camera_parking:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xx@camN.fdl:554/h264Preview_01_sub
          roles:
            - detect
              #            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    record:
      enabled: True
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - car
        - bycycle
        - bird
        - cat
        - dog
      filters:
           car:
             min_score: 0.5
             threshold: 0.7
             min_area: 60000
             
      #   person:
      #     min_score: 0.5
      #     threshold: 0.7




  camera_terrasse:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M

      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac


      inputs:
        - path: rtsp://admin:xxx@camTerrasse.fdl:554/h264Preview_01_sub
          roles:
            - detect

    detect:
#      width: 2304
#      height: 1296
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: True
    record:
      enabled: True
      
    rtmp:
      enabled: False
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Frigate stats

```json
{"camera_buanderie":{"camera_fps":5.1,"capture_pid":241,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":249,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"camera_parking":{"camera_fps":7.2,"capture_pid":246,"detection_enabled":1,"detection_fps":7.5,"ffmpeg_pid":258,"pid":238,"process_fps":6.7,"skipped_fps":0.0},"camera_remise":{"camera_fps":5.2,"capture_pid":242,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":256,"pid":236,"process_fps":5.2,"skipped_fps":0.0},"camera_terrasse":{"camera_fps":5.1,"capture_pid":248,"detection_enabled":1,"detection_fps":3.4,"ffmpeg_pid":269,"pid":239,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.2"},"1":{"cpu":"0.0","mem":"0.0"},"107":{"cpu":"0.0","mem":"0.1"},"111":{"cpu":"79.7","mem":"5.1"},"122":{"cpu":"0.0","mem":"0.4"},"138":{"cpu":"0.0","mem":"0.5"},"139":{"cpu":"0.0","mem":"0.2"},"16":{"cpu":"0.0","mem":"0.0"},"18":{"cpu":"0.0","mem":"0.0"},"220":{"cpu":"0.0","mem":"2.1"},"226":{"cpu":"1.3","mem":"0.3"},"227":{"cpu":"33.9","mem":"2.9"},"228":{"cpu":"1.7","mem":"2.5"},"232":{"cpu":"0.7","mem":"2.4"},"235":{"cpu":"0.0","mem":"0.6"},"236":{"cpu":"0.7","mem":"2.4"},"238":{"cpu":"5.6","mem":"2.5"},"239":{"cpu":"2.3","mem":"2.5"},"240":{"cpu":"0.0","mem":"0.6"},"241":{"cpu":"1.0","mem":"2.3"},"242":{"cpu":"1.3","mem":"2.3"},"244":{"cpu":"0.0","mem":"1.1"},"246":{"cpu":"2.3","mem":"2.3"},"248":{"cpu":"1.0","mem":"2.3"},"249":{"cpu":"8.6","mem":"1.2"},"25":{"cpu":"0.0","mem":"0.0"},"251":{"cpu":"0.0","mem":"0.6"},"256":{"cpu":"9.3","mem":"1.3"},"258":{"cpu":"8.3","mem":"1.3"},"259":{"cpu":"0.0","mem":"0.5"},"26":{"cpu":"0.0","mem":"0.0"},"269":{"cpu":"9.6","mem":"1.2"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"33":{"cpu":"0.0","mem":"0.0"},"3903":{"cpu":"0.0","mem":"0.0"},"3937":{"cpu":"23.5","mem":"0.6"},"3938":{"cpu":"0.0","mem":"0.1"},"3945":{"cpu":"0.7","mem":"0.1"},"42":{"cpu":"0.0","mem":"0.0"},"43":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"0.0","mem":"0.0"},"94":{"cpu":"0.0","mem":"0.5"},"MiB":{"cpu":"1908.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":10.9,"detectors":{"coral":{"detection_start":1682355135.232332,"inference_speed":70.66,"pid":227}},"gpu_usages":{"intel-vaapi":{"gpu":"0.44 %","mem":"- %"}},"service":{"last_updated":1682355139,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":1901.2,"mount_type":"tmpfs","total":1907.3,"used":6.1},"/media/frigate/clips":{"free":1735676.4,"mount_type":"exfat","total":2000333.4,"used":264657.0},"/media/frigate/recordings":{"free":1735676.4,"mount_type":"exfat","total":2000333.4,"used":264657.0},"/tmp/cache":{"free":1907.0,"mount_type":"tmpfs","total":1907.3,"used":0.4}},"temperatures":{},"uptime":1704,"version":"0.12.0-da3e197"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink - Model RLC-410-5MP FW: v3.0.0.136_20121100

**Comment by palinf** [comment]
Ok, then I have issues with my other camera since they are not recording when stationary object.
Nevertheless what would my configuration need to be to stop recording when an object is stationary ?

I used:
```
      stationary:
        max_frames:
          objects:
            car: 1500
``` 
That I understand like: disables stationary object tracking after 1500 frames. But it is not doing anything.
