### ISSUE TITLE
[Config Support]: How to enable 24/7 recording for a single camera

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#6235]
### Describe the problem you are having

I looked through the configuration file and don't see any options on a specific camera to enable only record 24/7 on that camera.

### Version

Frigate (Full Access) Beta (0.12.0)

### Frigate config file

```yaml
?
```

### Relevant log output

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
all of the docs have `NOTE: can be overridden at the camera level` and so you just apply that same config to the camera

```yaml
cameras:
  my_camera_24_7:
    ffmpeg:
      ...
    record:
      enabled: true
      retain:
        days: X
```
