### ISSUE TITLE
[Config Support]: Other detected objects?

### ISSUE THREAD

**Issue by aaronouthier** [blakeblackshear/frigate#6238]
### Describe the problem you are having

I am wondering if objects other than people can be detected/reported?
I can't find any mention of what objects are valid, or how to specify them in the Docs.

### Version

:stable

### Frigate config file

```yaml
mqtt:
  host: 10.10.1.254
  user: REDACTED
  password: REDACTED

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

record:
  enabled: True
  events:
    retain:
      default: 50

cameras:
  DoorCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@10.10.1.250:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720

  PackageCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@10.10.1.251:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720

  RatCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@10.10.4.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720

  GateCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@10.10.4.14:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720

  TrailerCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@10.10.4.12:554/stream1
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720

  ShedCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@10.10.4.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by ehn** [comment]
You can find the list of object models here: https://docs.frigate.video/configuration/objects

**Comment by NickM-27** [comment]
You define what objects are tracked using 

```yaml
objects:
  track:
    - person
    - dog
    - ...
```
