### ISSUE TITLE
[Config Support]: Snapshots have a lower resolution than stream

### ISSUE THREAD

**Issue by johndoe0815** [blakeblackshear/frigate#6240]
### Describe the problem you are having

My Tapo C100 camera has two streams:
1080P (1920x1080) stream: rtsp://username:password@IP Address:554/stream1
360P (640x360) stream: rtsp://username:password@IP Address:554/stream2

So i use stream 2 for detection and stream 1 for recording.
What I do not understand is why screenshots that are taken by Frigate have a resolution of only 1280x768, as there is no place in the config where I specifically maintained a resolution. As per the docs I only see a manual setting for the detect (which is anyways only 360P for me), and one for MQTT, but I am talking about the files that I do load directly from the Frigate add-on.
As they are, besides low resolution, also quite blurry (looking ligh high compression), I was looking for a way to get the screenshots in full hd (plus probably lower compression), according to what the camera also delivers as output.
The video recording however comes out with 1920x1080, so this is only a matter of the snapshots, which for some reason have a lower resolution. How can I change this?

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.99
  user: myuser
  password: mypassword
  
cameras:
  tapo_c100_1:
    ffmpeg:
      inputs:
        - path: rtsp://mytapo:mypass@192.168.178.98:554/stream1 
          roles:
            - record
        - path: rtsp://mytapo:mypass@192.168.178.98:554/stream2 
          roles:
            - detect
            
motion:
  mask:    
    - 0,45,475,45,475,0,0,0 

record:
  enabled: True
  events:
    objects:
      - person
    retain:
      default: 7
    
snapshots:
  enabled: True
  retain:
    default: 5
    objects:
      person: 7
```

### Relevant log output

```shell
nothing.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
