### ISSUE TITLE
[Config Support]: Objects detected in zones that should be filtered out

### ISSUE THREAD

**Issue by raintonr** [blakeblackshear/frigate#6255]
### Describe the problem you are having

![image](https://user-images.githubusercontent.com/3794098/234340181-c16b171d-25fc-44e1-90ff-0adaa8235ab4.png)

In this image zones are as follows (see config file):

- Yellow = lawn_west
- Violet = driveway_top
- Blue = parking_side
- Mustard = terrace_north

None of the zone outlines are drawn in bold which I believe means Frigate thinks there are no objects in each zone. Which is odd as then it also shows 2 target boxes - a `car` and a `person` which are certainly within a defined zone.

If I have understood the documentation correctly, the labelled car should fall within the `parking_side` zone, and as that zone has an object override (`objects: [cat, cow, dog, horse, person, sheep]`) this should not trigger events. Well, not unless it also passed through the `driveway_top` zone for example, which would be fine as that would signify a vehicle arriving.

However, Frigate has created a new event for this car and has not identified it as in the `parking_side` zone. This is from the events list:

![image](https://user-images.githubusercontent.com/3794098/234346705-2946b776-9624-4d5d-9b8c-e3e33cc7e571.png)

Note there is no zone on the event, nor is the car labelled. Why has this event been created?

From what I can tell I could use a `required_zones` setting in the camera recording config and list only `lawn_west`, `driveway_top` & `terrace_north` but this would not be ideal as I only want to ignore vehicles in the `parking_side` zone - I do want events for all other targets (like dogs & people) in that zone.

Another thing I don't understand is that in order to prevent false positives on the `terrace_north` and  `parking_side` zones I have added a filter for `person` with `min_area: 5000`. However, looking at the above there is a `person` with 60% score clearly within the `terrace_north` zone. Why is this target being shown in debug when it's area is clearly less than the `min_area` filter?

I just stepped out of this door, walked through the `terrace_north` and `parking_side` zones and back. This caused 3 new events to be created:

![image](https://user-images.githubusercontent.com/3794098/234347717-f9f9b17f-9d9d-4187-a65c-93c8bba761c5.png)

- The first event 'In progress' must be from the false positive potted plant bottom right of the debug image.
- The second event is correct. There is a snapshot and recording of myself.
- The third event must also be from the false positive potted plant bottom right of the debug image but somehow was ended when a 'real' person (myself) was seen?
- The fourth event is from the car (as above).

What I *think* (and am only guessing) is going on is that the `car` & `person` filters on the zones are preventing these targets from being identified and placed in those zones. However, these objects are still considered positives globally in the frame and can therefore cause an event to be created. This is super confusing and if this behaviour is by design think the documentation needs work to clarify this.

I will attempt to address this by placing *all* the zones for this camera in the `required_zones` section and see if that works.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
logger:
    default: info
    logs:
      frigate.event: info
  
  mqtt:
    host: 10.1.1.30
    stats_interval: 300
  
  detectors:
    coral1:
      type: edgetpu
      device: pci:0
  
  objects:
    track: [bicycle, car, cat, cow, dog, horse, motorcycle, person, sheep]
    filters:
      # Default filters to ignore super tiny stuff
      bicycle:
        min_area: 1000
      car:
        min_area: 1000
      cat:
        min_area: 1000
      cow:
        min_area: 1000
      dog:
        min_area: 1000
      horse:
        min_area: 1000
      motorcycle:
        min_area: 1000
      person:
        min_area: 1000
      sheep:
        min_area: 1000
  
  birdseye:
    enabled: false
      
  motion:
    improve_contrast: true
  
  ffmpeg:
    hwaccel_args: preset-intel-qsv-h264
  
  snapshots:
    enabled: True
  
  record:
    enabled: True
    # Record all motion seen and keep for 30 days
    retain:
      days: 30
      mode: motion
    events:
      retain:
        default: 30
  
  rtmp:
    enabled: False
  
  cameras:
    porch_intercom:
      mqtt:
        enabled: False
      ffmpeg:
        inputs:
          - path: rtsp://xxx:xxx@10.1.3.60:554/Streaming/Channels/2
            roles:
              - detect
          - path: rtsp://xxx:xxx@10.1.3.60:554/Streaming/Channels/1
            roles:
              - record
      detect:
        width: 704
        height: 576
      motion:
        mask:
          # Timestamp mm:ss
          - 592,450,631,450,631,460,592,460
          # Sky
          - 704,0,704,340,441,354,223,305,123,322,0,312,0,0
      zones:
        terrace_north:
          coordinates: 434,383,704,404,704,576,455,576,147,576,0,576,0,409,39,418,109,524,224,503,341,446
          # Don't track vehicles
          objects: [cat, cow, dog, horse, person, sheep]
          filters:  
            person:
              min_area: 5000
        parking_side:
          coordinates: 222,513,344,466,224,379,62,381,31,454,89,531
          # Don't track vehicles
          objects: [cat, cow, dog, horse, person, sheep]
          filters:
            person:
              min_area: 5000
        driveway_top:
          coordinates: 209,341,108,343,73,377,234,380
        lawn_west:
          coordinates: 144,339,0,315,0,408,33,427,78,367,112,350
    gate_intercom:
      mqtt:
        enabled: False
      ffmpeg:
        inputs:
          - path: rtsp://xxx:xxx@10.1.3.61:554/Streaming/Channels/2
            roles:
              - detect
          - path: rtsp://xxx:xxx@10.1.3.61:554/Streaming/Channels/1
            roles:
              - record
      detect:
        width: 704
        height: 576
      motion:
        mask:
          # Timestamp mm:ss
          - 592,450,631,450,631,460,592,460
          # Sky + #2
          - 0,0,704,0,704,314,561,418,413,370,341,309,0,226
      zones:
        road:
          coordinates: 363,382,497,450,532,444,536,411,361,350
        gate_outside:
          coordinates: 328,380,529,487,496,576,195,377
        gate_inside:
          coordinates: 496,576,0,576,0,0,185,0,195,377
      objects:
        mask:
          # Right hand side fence
          - 704,0,549,0,556,325,517,576,704,576
    csw1:
      mqtt:
        enabled: False
      ffmpeg:
        inputs:
          - path: rtsp://xxx:xxx@10.1.3.62:554/Streaming/Channels/2
            roles:
              - detect
          - path: rtsp://xxx:xxx@10.1.3.62:554/Streaming/Channels/1
            roles:
              - record
      detect:
        width: 640
        height: 480
      motion:
        mask:
          # Timestamp mm:ss
          - 584,442,623,442,623,452,584,452
          # Sky
          - 640,0,640,172,445,28,368,14,79,61,97,147,98,293,120,480,0,480,0,0
      zones:
        lawn_south:
          coordinates: 98,480,640,480,640,246,434,58,384,28,87,108        
    csw2:
      mqtt:
        enabled: False
      ffmpeg:
        inputs:
          - path: rtsp://xxx:xxx@10.1.3.63:554/Streaming/Channels/2
            roles:
              - detect
          - path: rtsp://xxx:xxx@10.1.3.63:554/Streaming/Channels/1
            roles:
              - record
      detect:
        width: 640
        height: 480
      motion:
        mask:
          # Timestamp mm:ss
          - 584,442,623,442,623,452,584,452
          # Sky
          - 119,110,292,87,483,80,640,99,640,0,0,0,0,155
      zones:
        lawn_south:
          coordinates: 0,480,0,170,312,110,640,390,640,480
        lawn_west:
          coordinates: 640,119,503,104,267,117,640,405
    csw3:
      mqtt:
        enabled: False
      record:
        events:
          required_zones: [lawn_west, driveway_top]
      snapshots:
        required_zones: [lawn_west, driveway_top]
      ffmpeg:
        inputs:
          - path: rtsp://xxx:xxx@10.1.3.66:554/Streaming/Channels/2
            roles:
              - detect
          - path: rtsp://xxx:xxx@10.1.3.66:554/Streaming/Channels/1
            roles:
              - record
      detect:
        width: 640
        height: 480
      motion:
        mask:
          # Timestamp mm:ss
          - 584,442,623,442,623,452,584,452
          # Sky
          - 72,75,177,0,0,0,0,166
      zones:
        lawn_west:
          coordinates: 488,480,0,480,0,211,93,80,194,0,404,0,591,119    
        driveway_top:
          coordinates: 531,28,423,11,465,42,542,39
    cgw:
      mqtt:
        enabled: False
      ffmpeg:
        inputs:
          - path: rtsp://xxx:xxx@10.1.3.65:554/Streaming/Channels/2
            roles:
              - detect
          - path: rtsp://xxx:xxx@10.1.3.65:554/Streaming/Channels/1
            roles:
              - record
      detect:
        width: 640
        height: 480
      motion:
        mask:
          # Timestamp mm:ss
          - 584,442,623,442,623,452,584,452
          # Sky
          - 640,0,0,0,0,46,308,26,423,60,528,108,640,253
      zones:
        driveway_top:
          coordinates: 0,480,474,480,559,276,532,229,257,100,0,154
        gate_inside:
          coordinates: 491,114,452,99,419,121,296,108,528,208
        lawn_by_road:
          coordinates: 640,480,640,302,608,229,527,123,486,107,558,265,466,480
        lawn_west:
          coordinates: 284,40,201,32,16,69,16,149,128,115,247,97,346,114,431,122,441,101
    cse:
      mqtt:
        enabled: False
      record:
        events:
          required_zones: [lawn_east]
      snapshots:
        required_zones: [lawn_east]
      ffmpeg:
        inputs:
          - path: rtsp://xxx:xxx@10.1.3.67:554/Streaming/Channels/2
            roles:
              - detect
          - path: rtsp://xxx:xxx@10.1.3.67:554/Streaming/Channels/1
            roles:
              - record
      detect:
        width: 640
        height: 480
      motion:
        mask:
          # Timestamp mm:ss
          - 584,442,623,442,623,452,584,452
          # Sky
          - 640,0,0,0,0,70,276,123,640,210
      zones:
        lawn_east:
          coordinates: 0,480,640,480,640,290,398,205,219,151,58,144        
      # Don't track vehicles
      objects:
        track: [cat, cow, dog, horse, person, sheep]
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
{"cgw":{"camera_fps":6.1,"capture_pid":340,"detection_enabled":1,"detection_fps":0.3,"ffmpeg_pid":393,"pid":317,"process_fps":6.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.0"},"111":{"cpu":"7.0","mem":"2.4"},"117":{"cpu":"0.0","mem":"0.2"},"125":{"cpu":"0.0","mem":"0.1"},"126":{"cpu":"0.0","mem":"0.1"},"127":{"cpu":"0.0","mem":"0.2"},"128":{"cpu":"0.0","mem":"0.2"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"1.0"},"288":{"cpu":"0.7","mem":"0.1"},"289":{"cpu":"1.7","mem":"1.4"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"2.0","mem":"1.2"},"30":{"cpu":"0.0","mem":"0.0"},"309":{"cpu":"0.0","mem":"0.2"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"0.7","mem":"1.3"},"311":{"cpu":"0.7","mem":"1.2"},"312":{"cpu":"0.0","mem":"0.2"},"313":{"cpu":"1.3","mem":"1.2"},"314":{"cpu":"0.0","mem":"0.2"},"315":{"cpu":"4.7","mem":"1.2"},"316":{"cpu":"8.6","mem":"1.3"},"317":{"cpu":"1.0","mem":"1.3"},"318":{"cpu":"0.0","mem":"0.2"},"319":{"cpu":"1.3","mem":"1.3"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"0.7","mem":"1.1"},"321":{"cpu":"0.0","mem":"0.2"},"324":{"cpu":"1.0","mem":"1.1"},"325":{"cpu":"2.0","mem":"0.6"},"328":{"cpu":"0.0","mem":"0.2"},"329":{"cpu":"1.3","mem":"1.1"},"330":{"cpu":"1.0","mem":"1.1"},"332":{"cpu":"0.0","mem":"0.2"},"333":{"cpu":"1.0","mem":"1.1"},"335":{"cpu":"2.0","mem":"0.6"},"340":{"cpu":"1.0","mem":"1.1"},"350":{"cpu":"1.3","mem":"0.4"},"351":{"cpu":"1.0","mem":"1.1"},"353":{"cpu":"1.0","mem":"0.6"},"358":{"cpu":"1.3","mem":"0.4"},"367":{"cpu":"1.3","mem":"0.6"},"372":{"cpu":"1.3","mem":"0.6"},"393":{"cpu":"1.0","mem":"0.6"},"394":{"cpu":"1.3","mem":"0.6"},"399":{"cpu":"1.3","mem":"0.4"},"40":{"cpu":"0.0","mem":"0.0"},"401":{"cpu":"0.3","mem":"0.4"},"402":{"cpu":"1.0","mem":"0.5"},"4224":{"cpu":"0.0","mem":"0.0"},"4231":{"cpu":"0.0","mem":"0.0"},"434":{"cpu":"1.7","mem":"0.4"},"44":{"cpu":"0.0","mem":"0.0"},"444":{"cpu":"1.3","mem":"0.4"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"5314.0","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"cse":{"camera_fps":6.1,"capture_pid":351,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":394,"pid":319,"process_fps":6.1,"skipped_fps":0.0},"csw1":{"camera_fps":6.1,"capture_pid":329,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":367,"pid":313,"process_fps":6.1,"skipped_fps":0.0},"csw2":{"camera_fps":6.1,"capture_pid":330,"detection_enabled":1,"detection_fps":1.8,"ffmpeg_pid":353,"pid":315,"process_fps":6.1,"skipped_fps":0.0},"csw3":{"camera_fps":6.1,"capture_pid":333,"detection_enabled":1,"detection_fps":5.7,"ffmpeg_pid":372,"pid":316,"process_fps":6.1,"skipped_fps":0.0},"detection_fps":7.8,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":8.45,"pid":289}},"gate_intercom":{"camera_fps":5.1,"capture_pid":324,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":335,"pid":311,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"intel-qsv":{"gpu":"2.56 %","mem":"- %"}},"porch_intercom":{"camera_fps":5.0,"capture_pid":320,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":325,"pid":310,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1682440706,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":68.2,"mount_type":"tmpfs","total":75.5,"used":7.3},"/media/frigate/clips":{"free":271180.3,"mount_type":"xfs","total":274743.7,"used":3563.4},"/media/frigate/recordings":{"free":271180.3,"mount_type":"xfs","total":274743.7,"used":3563.4},"/tmp/cache":{"free":81.6,"mount_type":"tmpfs","total":100.0,"used":18.4}},"temperatures":{"apex_0":48.3},"uptime":1968,"version":"0.12.0-da3e197"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe
