### ISSUE TITLE
[Support]: MQTT not working - frigate.comms.mqtt .. Unable to publish ... client is not connected

### ISSUE THREAD

**Issue by v-kabanov** [blakeblackshear/frigate#6265]
### Describe the problem you are having

Latest frigate image is running in docker under fresh debian 11 stable and mosquitto 2.0.11 installed on the same host with default configuration. MQTT tests are succeeding both from linux bash and in homeassistant which is running under docker on the same machine. Frigate connects to cameras and feeds data into HA, but keeps logging errors "frigate.comms.mqtt ERROR: Unable to publish ... client is not connected".
Tried to set host to 'localhost' and '127.0.0.1', increase log verbosity "frigate.mqtt: debug" and "frigate.comms.mqtt: debug" and globally, connect anonymously and with password, configuring mosquitto to allow connections from network, but nothing changes and the only message in the log from mqtt is that same error, no other information as though it never attempts to actually connect at all.
Mosquitto logs show connections from HA, but not from frigate.
Notably documentation recommends setting log level for "frigate.mqtt", but errors are coming from "frigate.comms.mqtt".

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 127.0.0.1
  port: 1883
  stats_interval: 60

database:
  path: /db/frigate.db

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.comms.mqtt: debug
    frigate.mqtt: debug

cameras:
```

### Relevant log output

```shell
2023-04-26 22:59:56.822427434  [2023-04-26 22:59:56] frigate.comms.mqtt             ERROR   : Unable to publish to frontyard/motion: client is not connected
2023-04-26 22:59:59.001069343  [2023-04-26 22:59:59] frigate.comms.mqtt             ERROR   : Unable to publish to carport/motion: client is not connected
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.5-0+deb11u1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://10.0.0.10:554/Streaming/Channels/102':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.241000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 704x576, 25 fps, 24.92 tbr, 90k tbn, 50 tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
You can't use localhost or 127.0.0.1 because frigate is not running on host mode, so host is inside the frigate container and not the host device.

**Comment by NickM-27** [comment]
HA container uses host mode by default. 

> Is there a work around?

just use your actual devices IP instead of localhost

**Comment by v-kabanov** [comment]
Thanks heaps for the quick responses, issue closed.

**Comment by joekerna** [comment]
I've run into the same problem:
Mosquitto (non docker) on host with IP 192.168.178.27
Frigate in docker container.

When I set 

```
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 192.168.178.27
  # Optional: port (default: shown below)
  port: 1883
```
I still get the 

> client is not connected

error
