### ISSUE TITLE
[Config Support]:  laggy stream with reolink

### ISSUE THREAD

**Issue by Se7enair** [blakeblackshear/frigate#6266]
### Describe the problem you are having

Frigate is throwing errors if I connecting to streams.
The streams are not playing lagfree. Sometime there are short lags, sometimes the stream jumps a few seconds.
Especially on my dashboard the stream is lagging a lot. In a browser its better, but not fluid.
I tried MSE and webrtc.
I use a ReolinkRLC-410W and a Reolink RLC-542WA. Both connect via LAN. (there was a time I needed wifi)
Records are fine as Long as they are there. Sometimes when there is to much Action the records do Not exist 

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: redacted
  user: redacted
  password: redacted
go2rtc:
  rtsp:
    username: "redacted"
    password: "redacted"
  streams:
    gartentuere:
      - ffmpeg:http://redacted/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted#video=copy#audio=aac#audio=opus
    hof:
      - ffmpeg:http://redacted/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted#video=copy#audio=aac#audio=opus
  webrtc:
    candidates:
      - frigate_ip:8555
      - stun:8555
# ffmpeg:
#   input_args:
#     # - preset-http-reolink
#     - -avoid_negative_ts
#     - make_zero
#     - -fflags
#     - +genpts+discardcorrupt
#     - -flags
#     - low_delay
#     - -strict
#     - experimental
#     - -analyzeduration
#     - 1000M
#     - -probesize
#     - 1000M
#     - -rw_timeout
#     - "5000000"
  output_args:
    record: preset-record-generic-audio-copy
#     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
cameras:
  gartentuere:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gartentuere?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      max_disappeared: 100
      width: 2560
      height: 1440
      stationary:
        max_frames:
          default: 500
    objects:
        track:
          - person
          - bicycle
        filters:
          car:
            mask:
              - 211,725,1284,442,1302,94,1287,0,33,0,94,235
    motion:
      mask:
        - 1093,1384,1101,1302,30,1297,22,1378
      threshold: 50
      contour_area: 150
    zones:  
      einfahrt:
        coordinates: 644,189,320,544,290,869,1213,1139,2560,1440,2560,0,1204,0
      tuere:
        coordinates: 0,1440,1628,1440,1626,1104,222,583
    snapshots:
      enabled: true
      crop: false
      retain:
        default: 30
        objects:
          person: 40
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 12
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 15
  hof:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hof?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      max_disappeared: 100
      width: 2560
      height: 1920
      fps: 7
      stationary:
        max_frames:
          default: 500
    zones:  
      einfahrt:
        coordinates: 0,1485,438,1920,1924,1920,2081,1811,2560,860,1617,163,0,357
      strasse:
        coordinates: 0,0,0,366,899,176,1585,163,2131,222,2249,0
    objects:
        track:
          - person
          - car
          - bicycle
        filters:
          car:
            mask:
              - 0,1334,836,1075,810,601,459,126,0,237
    motion:
      threshold: 50
      contour_area: 150
    snapshots:
      enabled: true
      crop: false
      retain:
        default: 30
        objects:
          person: 40
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 12
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 15
            car: 3

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
2023-04-26 16:25:13.380739769  [INFO] Preparing go2rtc config...
2023-04-26 16:25:13.744571750  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-04-26 16:25:13.794229057  [INFO] Starting go2rtc...
2023-04-26 16:25:13.949117651  16:25:13.948 INF go2rtc version 1.2.0 linux/amd64
2023-04-26 16:25:13.949121226  16:25:13.948 INF [api] listen addr=:1984
2023-04-26 16:25:13.949125293  16:25:13.948 INF [rtsp] listen addr=:8554
2023-04-26 16:25:13.949127582  16:25:13.948 INF [srtp] listen addr=:8443
2023-04-26 16:25:13.949129550  16:25:13.948 INF [webrtc] listen addr=:8555
2023-04-26 16:25:23.409075339  [INFO] Starting go2rtc healthcheck service...
2023-04-26 16:26:33.069742494  16:26:33.069 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:40846->173.194.76.127:19302: i/o timeout"
2023-04-26 16:26:48.545794866  16:26:48.544 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:59263->173.194.76.127:19302: i/o timeout"
2023-04-26 16:30:39.932662602  16:30:39.932 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:46779->173.194.76.127:19302: i/o timeout"
2023-04-26 16:31:14.253733216  16:31:14.253 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-04-26 16:33:19.523022083  16:33:19.522 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-04-26 16:34:16.590368175  16:34:16.590 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:38560->108.177.15.127:19302: i/o timeout"
2023-04-26 16:34:47.683982297  16:34:47.683 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-04-26 16:36:02.151051598  16:36:02.150 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
```

### Frigate stats

```json
cpu_usages	
1	
cpu	"0.0"
mem	"0.0"
14	
cpu	"0.0"
mem	"0.0"
15	
cpu	"0.0"
mem	"0.0"
23	
cpu	"0.0"
mem	"0.0"
24	
cpu	"0.0"
mem	"0.0"
25	
cpu	"0.0"
mem	"0.0"
26	
cpu	"0.0"
mem	"0.0"
27	
cpu	"0.0"
mem	"0.0"
28	
cpu	"0.0"
mem	"0.0"
29	
cpu	"0.0"
mem	"0.0"
30	
cpu	"0.0"
mem	"0.0"
31	
cpu	"0.0"
mem	"0.0"
39	
cpu	"0.0"
mem	"0.0"
41	
cpu	"0.0"
mem	"0.0"
76	
cpu	"0.0"
mem	"0.0"
79	
cpu	"0.0"
mem	"0.0"
83	
cpu	"0.0"
mem	"0.0"
93	
cpu	"3.0"
mem	"0.1"
109	
cpu	"0.0"
mem	"0.0"
110	
cpu	"18.0"
mem	"1.6"
118	
cpu	"0.0"
mem	"0.0"
123	
cpu	"0.0"
mem	"0.0"
124	
cpu	"0.7"
mem	"0.0"
125	
cpu	"0.7"
mem	"0.0"
126	
cpu	"0.0"
mem	"0.0"
271	
cpu	"0.0"
mem	"0.2"
277	
cpu	"0.0"
mem	"0.0"
278	
cpu	"0.0"
mem	"0.4"
279	
cpu	"1.0"
mem	"0.3"
283	
cpu	"0.3"
mem	"0.3"
284	
cpu	"1.0"
mem	"0.4"
286	
cpu	"0.0"
mem	"0.1"
289	
cpu	"3.0"
mem	"0.3"
290	
cpu	"0.0"
mem	"0.1"
291	
cpu	"7.0"
mem	"0.3"
293	
cpu	"0.0"
mem	"0.1"
299	
cpu	"22.7"
mem	"0.2"
302	
cpu	"26.0"
mem	"0.3"
306	
cpu	"3.7"
mem	"0.1"
307	
cpu	"4.0"
mem	"0.1"
3870	
cpu	"0.0"
mem	"0.0"
3924	
cpu	"0.0"
mem	"0.0"
3929	
cpu	"6.2"
mem	"0.1"
3931	
cpu	"0.0"
mem	"0.0"
%Cpu(s):	
cpu	"id,"
mem	"0.5"
MiB	
cpu	"7501.9"
mem	"avail"
PID	
cpu	"%CPU"
mem	"%MEM"
Tasks:	
cpu	"stopped,"
mem	"0"
top	
cpu	"users,"
mem	"load"
detection_fps	0
detectors	
coral	
detection_start	0
inference_speed	8.03
pid	278
gartentuere	
camera_fps	5.1
capture_pid	289
detection_enabled	1
detection_fps	0
ffmpeg_pid	299
pid	283
process_fps	5.1
skipped_fps	0
hof	
camera_fps	7
capture_pid	291
detection_enabled	1
detection_fps	0
ffmpeg_pid	302
pid	284
process_fps	7
skipped_fps	0
service	
last_updated	1682520254
latest_version	"unknown"
storage	
/dev/shm	
free	522.1
mount_type	"tmpfs"
total	536.9
used	14.8
/media/frigate/clips	
free	3488.8
mount_type	"ext4"
total	84044.2
used	76286.6
/media/frigate/recordings	
free	3488.8
mount_type	"ext4"
total	84044.2
used	76286.6
/tmp/cache	
free	994.2
mount_type	"tmpfs"
total	1000
used	5.8
temperatures	{}
uptime	1140
version	"0.12.0-da3e197"
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

It is running on docker inside a LXC within proxmox.

**Comment by NickM-27** [comment]
Would be curious to see an ffprobe from the cameras, I'd say most likely this is a camera issue. Reolink cameras don't have great rtsp or http-flv realization and those older reolink cameras don't have the iframe interval and constant frame rate options which would make the stream better. On my reolink cameras the iframe interval is all over the place and not consistent

**Comment by Se7enair** [comment]
camera "gartentuere"

```
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

camera "hof"

```
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

**Comment by NickM-27** [comment]
see if you can run this command on the streams, it will give their iframe timings

```
ffprobe -loglevel error -select_streams v:0 -show_entries packet=pts_time,flags -of csv=print_section=0 -i STREAM_URL | awk -F',' '/K/ {print $1}'  
```

**Comment by Se7enair** [comment]
"gartentuere"
```
[1] 2181012
[2] 2181013
[3] 2181014
[4] 2181015
[2]   Done                    app=bcs
[3]-  Done                    stream=channel0_main.bcs
[4]+  Done                    user=frigate
frigate@frigate:~# Command 'ffprobe' not found, but can be installed with:
```

"hof"
```
[1] 2181211
[2] 2181212
[3] 2181213
[4] 2181214
[2]   Done                    app=bcs
[3]-  Done                    stream=channel0_main.bcs
[4]+  Done                    user=admin
frigate@frigate:~# Command 'ffprobe' not found, but can be installed with:
```

Is this what you are asking for?

**Comment by NickM-27** [comment]
No, you need to run this inside the container or have ffprobe installed wherever you are running this

**Comment by Se7enair** [comment]
My bad, where in the LXC not in Docker.
But it throws a 5XX Server Error reply. What is the correct stream url for this? At the moment I am using the same url from frigat. Without any annotations

ffprobe -loglevel error -select_streams v:0 -show_entries packet=pts_time,flags -of csv=print_section=0 -i http://10.0.30.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password | awk -F',' '/K/ {print $1}'  

"gartentuere"
```
[1] 3888
[2] 3889
[3] 3890
[4] 3891
[2]   Done                    app=bcs
[3]-  Done                    stream=channel0_main.bcs
[4]+  Done                    user=frigate
root@e5ec848769f2:/opt/frigate# http://10.0.30.21/flv?port=1935: Server returned 5XX Server Error reply
```

**Comment by NickM-27** [comment]
I'd suggest just using it with `rtsp://127.0.0.1:8554/gartentuere?video=copy&audio=aac`

**Comment by Se7enair** [comment]
I dont get it

```
[1] 6186
root@e5ec848769f2:/opt/frigate# [rtsp @ 0x558fddfdb740] method SETUP failed: 461 Unsupported transport
N/A,__
0.252000,K_
0.335000,__
0.419000,__
0.503000,__
0.587000,__
0.754000,__
0.838000,__
0.921000,__
1.005000,__
1.089000,__
1.256000,__
1.340000,__
1.424000,__
1.508000,__
1.591000,__
1.759000,__
...
...
```

**Comment by NickM-27** [comment]
that's the data we are looking for. which camera is that and what about the other one?

**Comment by Se7enair** [comment]
gartentuere
```
[1] 6863
root@e5ec848769f2:/opt/frigate# [rtsp @ 0x55de5970c740] method SETUP failed: 461 Unsupported transport
N/A,K_
0.083000,__
0.167000,__
0.251000,__
0.335000,__
0.502000,__
0.586000,__
0.669000,__
0.753000,__
0.837000,__
1.004000,__
1.088000,__
1.172000,__
1.256000,__
1.339000,__
1.507000,__
1.590000,__
1.674000,__
1.758000,__
1.842000,__
2.009000,K_
2.093000,__
2.177000,__
2.260000,__
2.344000,__
```
hof
```
[1] 6707
root@e5ec848769f2:/opt/frigate# [rtsp @ 0x562680b03740] method SETUP failed: 461 Unsupported transport
N/A,__
0.080000,__
0.160000,__
0.320000,__
0.400000,__
0.480000,__
0.560000,__
0.640000,__
0.800000,__
0.880000,__
0.960000,__
1.040000,__
1.120000,__
1.280000,__
1.360000,__
1.439000,__
1.519000,__
1.599000,__
1.759000,__
1.839000,__
1.919000,K_
1.999000,__
````

**Comment by NickM-27** [comment]
Seems like a very odd iframe interval every 8th of a second, more frequent than you would want. Do your cameras have any options for this under stream? You can see examples here https://docs.frigate.video/configuration/camera_specific#reolink-cameras

**Comment by Se7enair** [comment]
There are no settings so far.

I guess the camera is not really suitable for a lag free stream?

**Comment by NickM-27** [comment]
Reolink cameras are less expensive decent cameras but their stream implementation definitely leaves performance to be desired.

**Comment by Se7enair** [comment]
And the other question, why are the recordings fluent?

**Comment by NickM-27** [comment]
> So if there isnt a option to set the iframe, then there is no chance for improvements?

You could ask reolink for a firmware that has better RTSP, they've given me a firmware for my doorbell and 511wa that improved the RTSP stream

**Comment by NickM-27** [comment]
> And the other question, why are the recordings fluent?

Because they use different viewers, different underlying display, etc

**Comment by Se7enair** [comment]
> > So if there isnt a option to set the iframe, then there is no chance for improvements?
> 
> You could ask reolink for a firmware that has better RTSP, they've given me a firmware for my doorbell and 511wa that improved the RTSP stream

Found another firmware
```
0.084000,__
0.167000,__
0.251000,__
0.335000,__
0.418000,__
0.502000,__
0.586000,__
0.670000,__
0.753000,K_
0.837000,__
````

**Comment by NickM-27** [comment]
Is it performing any better? Seems to be same iframe interval

**Comment by Se7enair** [comment]
it seems so. Will test with more action in front of the camera tomorrow.

The interval is slightly bigger. 83-84 instead of 80

**Comment by Se7enair** [comment]
So directly inside frigate the stream seems to be somewhat stable.
On my dashboard its still something around 2-3 frames per second.

I wrote a ticket at the reolink support. Maybe there is a better firmware. Will share the answer here. 

Till then I will have a look for other cameras. Which seems not to expensive compared to reolink. Especially because I dont need the wifi anymore. (first I changed from a raspi to something bigger, then installed a extra wifi ap and then installed 60m ethernet  cable because I thought all my problems are related to a bad connection. It became better with every step, but never perfect)

**Comment by Se7enair** [comment]
Reolink send me a new firmware for the 542. It seems that this enables to controll the iframe size and als set a constant rate. As mentioned in the documentation. Will test it the next days.
If everything looks good I will share the firmware. Maybe we can add this then to the docs.

For the 410W we are discussing. Maybe they dont have a suitable firmware.

**Comment by NickM-27** [comment]
We already mention in the docs the advice to get better firmware. Frigate docs won't be hosting firmware for cameras to be clear, there are other repos that handle that. 

Sounds good 👍

**Comment by Se7enair** [comment]
Interesting, if I check the rtsp from camera directly I get this for hof (new firmware with iframe setting)
```
N/A
0.999722
1.999433
3.511267
4.510978
5.510700
6.510422
7.510133
8.509844
9.509567
10.509267
11.508978
```

and this for gartentuere
```
N/A
2.010000
4.019000
6.029000
8.038000
10.048000
12.058000
14.067000
16.076989
18.085989
20.095989
```
the frigate restream is producing the values we talked about yesterday. So the restream seems to be a problem?
Does the frigate site shows the direct stream and eg frigate card in homeassistant the restream?

**Comment by Se7enair** [comment]
> We already mention in the docs the advice to get better firmware. Frigate docs won't be hosting firmware for cameras to be clear, there are other repos that handle that.
> 
> Sounds good 👍

thought about hosting it here. but I will share it to the mentioned repos

**Comment by NickM-27** [comment]
iframe interval being set requires transcoding the stream which I don't believe is being done so not sure

**Comment by Se7enair** [comment]
so my target will be, to find correct frigate settings which brings me the correct iframe interval to the restream?

**Comment by NickM-27** [comment]
frigate settings shouldn't affect iframe interval unless you are doing transcoding. In my tests go2rtc restream and original stream from my reolink cameras have identical iframe

**Comment by Se7enair** [comment]
but why is the iframe interval this much different to the original stream? and does this still explain my problems?

the new firmware does not really improved the situation

**Comment by NickM-27** [comment]
you could try without `ffmpeg:` and see if there is a difference. 

My guess is that the ffprobe script I put above is just reporting the wrong values given the other characters that are shown that I have not seen.

**Comment by Se7enair** [comment]
Ok all the other log entries are back.

So both cameras have iframe setting of 1sec. camera hof has fixed frame rate. nothing really changed in the logs.

So what to do now?

**Comment by NickM-27** [comment]
If you want logs without any errors, reolink isn't the way to go

**Comment by Se7enair** [comment]
So everything is related to Reolink?

**Comment by NickM-27** [comment]
That's what it seems to me, my reolinks behave similarly across the span of a day. Meanwhile my loryta and hikvision cameras I've been testing never have any issues.

**Comment by Se7enair** [comment]
Thought there is a setting which helps.

For now, the camera with iframe settings AND fixed frame interval seems to produce only connection errors with webrtc.

```
2023-05-02 21:27:12.723237340  21:27:12.723 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:57930->173.194.76.127:19302: i/o timeout"
2023-05-02 21:42:39.172402321  21:42:39.172 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:44373->173.194.76.127:19302: i/o timeout"
2023-05-02 21:42:54.658231423  21:42:54.658 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:38681->173.194.76.127:19302: i/o timeout"
2023-05-03 07:11:11.191482078  07:11:11.191 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:51490->173.194.76.127:19302: i/o timeout"
2023-05-03 07:47:04.213559918  07:47:04.213 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:54254->173.194.76.127:19302: i/o timeout"
2023-05-03 08:21:15.288255656  08:21:15.288 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:38134->173.194.76.127:19302: i/o timeout"
2023-05-03 08:23:15.905973387  08:23:15.905 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:20 > error="write udp 172.18.0.2:57606->108.177.15.127:19302: i/o timeout"
```
thats ok, because the stream is still working.

The other camera with iframe setting, but without fixed frame interval seems to produce more errors.

**Comment by Se7enair** [comment]
```
  streams:
    gartentuere:
      - "ffmpeg:http://10.0.30.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password" 
    gartentuere_sub:
      - "ffmpeg:http://10.0.30.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"
    hof:
      - "ffmpeg:http://10.0.30.28/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password" 
    hof_sub:
      - "ffmpeg:http://10.0.30.28/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"
cameras:
  gartentuere:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gartentuere?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gartentuere_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
   
  hof:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hof?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hof_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
           
```

With this setup and updated firmwares I only have warning with some connection problems with webrtc. But in reality I do not encounter any problems.
