### ISSUE TITLE
[Support]: Files and folders have the wrong timestamps

### ISSUE THREAD

**Issue by clowncracker** [blakeblackshear/frigate#6271]
### Describe the problem you are having

The files recorded to my storage have the wrong timestamps in the file names.  Example:

Folder structure is 2023-04-26/17/front_door/06.56.mp4

However, this timestamp is for 10:06:56AM PST.  How can I get the file and folder names to coincide with the actual timestamps of the recordings?

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: xxxx
  user: xxxx
  password: xxxx

go2rtc:
  streams:
    front_door:
      - rtsp://xxxx:xxxx@xxxx:xxxx/h264Preview_01_main

cameras:
  front_door: 
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
          record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      retain:
        default: 14
    zones:
      entryway:
        coordinates: 2560,1920,2560,1681,2173,1506,1928,1579,1593,1321,934,1342,481,1288,321,1319,0,1319,0,1920
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell
