### ISSUE TITLE
Parked car constant high detection fps

### ISSUE THREAD

**Issue by madmic1314** [blakeblackshear/frigate#629]
Have my front camera setup to detect motion, people & cars. Once there has been motion (of any type) it's running at =>18fps constantly thinking there is motion on the cars. I've checked the motion box in the web console and there isn't anything showing there.

If I stop the system and start it again it's ok until motion is there, then back into this.

Front camera is the one playing up - Garage camera is same model and working ok with motion being detected and then going back to 0 one motion has stopped. Side camera (same brand, slightly different model) is working fine also. Config is pretty much identical for each camera.

I'm using the sub-channel at 640 x 360. But it does it on the main stream also. I've turned the motion threshold up but can't seem to find a suitable value - 25 will pickup cars & people, but do the high fps. If I turn this to 100 it detects the cars, but not a person. Tried many other values can can't find the sweet spot.

Running beta 0.8.0 version. Does any ideas?

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: core-mosquitto.local.hass.io
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ********
  password: ************
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
    - '-hwaccel_output_format'
    - yuv420p
cameras:
  front:
    ffmpeg:
      inputs:
        - path: 'rtsp://*******:********@192.168.999.999:554/Streaming/Channels/102'
          roles:
            - detect
    width: 640
    height: 360
    motion:
      threshold: 25
      mask:
        - '444,161,497,104,472,40,419,0,639,0,639,86,639,153,604,207,534,189'
        - '0,360,266,360,223,122,126,97,109,50,67,41,39,48,39,30,65,0,0,0'
    fps: 5
    best_image_timeout: 60
    rtmp:
      enabled: false
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask:
            - '444,161,497,104,472,40,419,0,639,0,639,86,639,153,604,207,534,189'
            - '0,360,266,360,223,122,126,97,109,50,67,41,39,48,39,30,65,0,0,0'
        car:
          mask:
            - '640,360,640,0,424,0,510,87,497,130,434,163,120,71,77,0,6,0,12,360'
  garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://*******:********@192.168.999.999:554/Streaming/Channels/102'
          roles:
            - detect
    width: 640
    height: 360
    motion:
      mask:
        - '514,0,639,0,640,183,470,201,479,134,513,76'
        - '221,65,217,0,0,0,0,106,0,360,210,360,229,268,190,198,259,88'
    fps: 5
    best_image_timeout: 60
    rtmp:
      enabled: false
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - motorcycle
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask:
            - '514,0,639,0,640,183,470,201,479,134,513,76'
            - '221,65,217,0,0,0,0,106,0,360,210,360,229,268,190,198,259,88'
        motorcycle:
          mask:
            - '0,0,205,0,205,146,408,151,413,0,640,0,640,360,0,360'
  side:
    ffmpeg:
      inputs:
        - path: 'rtsp://*******:********@192.168.999.999:554/Streaming/Channels/102'
          roles:
            - detect
    width: 640
    height: 360
    motion:
      mask:
        - '0,360,0,0,224,0,227,210,167,360'
        - '264,25,272,9,285,22,279,39,262,39'
        - '584,231,566,191,560,137,571,0,639,0,639,283,608,263'
    fps: 5
    best_image_timeout: 60
    rtmp:
      enabled: false
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask:
            - '0,360,0,0,224,0,227,210,167,360'
            - '584,231,566,191,560,137,571,0,639,0,639,283,608,263'
        cat:
          mask:
            - '0,360,0,0,299,0,298,56,258,204,227,210,167,360'
            - '450,360,422,310,342,71,348,23,462,118,556,174,565,0,633,0,640,360'
logger:
  default: info
  logs:
    frigate.mqtt: error
```

(apologies for the code formatting, can't seem to make it work properly)
