### ISSUE TITLE
[Camera Support]: Rotate stream in go2rtc

### ISSUE THREAD

**Issue by caublet** [blakeblackshear/frigate#6293]
### Describe the problem you are having

I'm unable to rotate using web2rtc

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
go2rtc:
  streams:
    Side:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.23:554/Streaming/Channels/1
      - "ffmpeg:Side#audio=aac"
    Side_Rotated:
      - "ffmpeg:Side#video=h264#rotate=90"
    Back:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.24:554/Streaming/Channels/1
      - "ffmpeg:Back#audio=aac"
    Ssol:
      - ffmpeg:rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.21:554/Streaming/Channels/1
      - "ffmpeg:Ssol#audio=aac"
    Ssolfenetre:
      - ffmpeg:rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.25:554/Streaming/Channels/1
      - "ffmpeg:Ssolfenetre#audio=aac"
################################################
  webrtc:
    candidates:
      - 192.168.1.15:8555
      - stun:8555
      - 192.168.1.12
##################### CAMERAS ###################
cameras:
  Side:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Side_Rotated
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: Side_Rotated
    detect:
      fps: 10
    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_score: 0.4
          threshold: 0.65
        cat:
          min_score: 0.4
          threshold: 0.65
        car:
          min_score: 0.4
          threshold: 0.65
      mask:
        - 85,508,260,440,249,506,420,454,418,412,614,452,626,495,845,438,1118,348,1280,281,1280,0,0,0,0,572,0,720,77,720 #everything else
        - 1280,461,1280,522,1008,600,805,640,590,669,618,552,770,529,1196,409,1230,334,1280,316 #CloseToHouse
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - parking
          - sidedoor
          - walkway       
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 60
      required_zones:
        - parking
        - sidedoor
        - walkway     
    zones:
      parking:
        coordinates: 88,496,255,423,254,509,312,493,327,675,87,659
        objects:
          - car
          - person
        filters:
          person:
            min_score: 0.2
            threshold: 0.45
          car:
            min_score: 0.2
            threshold: 0.45
      sidedoor:
        coordinates: 534,605,536,581,624,566,600,666,341,668,339,607
        objects:
          - person
        filters:
          person:
            min_score: 0.35
            threshold: 0.50
          car:
            min_score: 0.35
            threshold: 0.50
      walkway:
        coordinates: 630,561,641,553,804,519,1280,385,1280,273,1067,357,822,440,630,484,625,455,319,485,332,600,522,601,538,581
        objects:
          - person
          - cat
    motion:
      improve_contrast: True
      #threshold: 25
      mask:
        - 85,508,260,440,249,506,420,454,418,412,614,452,626,495,845,438,1118,348,1280,281,1280,0,0,0,0,572,0,720,77,720 #everything else
        - 1280,461,1280,522,1008,600,805,640,590,669,618,552,770,529,1196,409,1230,334,1280,316 #CloseToHouse
#########################################################################
  Back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Back
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 10
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.4
          threshold: 0.65
        cat:
          min_score: 0.4
          threshold: 0.65
      mask:
        - 1280,0,1280,720,1161,720,581,720,968,662,1102,641,1083,469,1029,292,992,194,852,99,676,0
        - 0,0,0,720,114,720,172,281,237,122,342,165,393,129,425,62,661,152,683,0
        - 897,467,1015,454,1008,373,969,285,915,202,846,158,788,167,776,247,816,367 #pool
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - deck
          - door
          - poolgate
          - shed
          - walkway
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 60
      required_zones:
          - deck
          - door
          - poolgate
          - shed
          - walkway
    zones:
      deck:
        coordinates: 155,510,626,587,611,266,296,163,244,371,180,351
        objects:
          - person
          - cat
      backdoor:
        coordinates: 181,317,246,358,284,207,224,178
        objects:
          - person
      poolgate:
        coordinates: 821,564,1112,535,1099,441,815,482
        objects:
          - person
      shed:
        coordinates: 964,663,1092,638,1086,565,1022,560,743,596,754,694
        objects:
          - person
          - cat
        filters:
          person:
            min_score: 0.2
            threshold: 0.5
      bbq:
        coordinates: 485,720,476,581,225,545,214,720
        objects:
          - person
          - cat
      walkway:
        coordinates: 393,106,272,70,290,0,500,0,472,217,380,192
        objects:
          - person
          - cat
    motion:
      improve_contrast: True
      mask:
        - 1280,0,1280,720,1161,720,581,720,968,662,1102,641,1083,469,1029,292,992,194,852,99,676,0
        - 0,0,0,720,114,720,172,281,237,122,342,165,393,129,425,62,661,152,683,0
        - 897,467,1015,454,1008,373,969,285,915,202,846,158,788,167,776,247,816,367 #pool
#########################################################################
  Ssol:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Ssol
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 10
    objects:
      track:
        - person
        - cat
      filters:
        cat:
          min_score: 0.4
          threshold: 0.65
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - litter
          - plancher
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 60
      required_zones:
          - litter
          - plancher
    zones:
      litter:
        coordinates: 678,300,753,720,1171,720,1035,305
        objects:
          - cat
      plancher:
        coordinates: 1280,720,0,720,0,0,925,0,994,325,1280,361
        objects:
          - person
    motion:
      mask:
        - 929,52,936,0,1280,0,1280,352,866,355,929,88,761,85,760,50
#########################################################################
  Ssolfenetre:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Ssolfenetre
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 10
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.4
          threshold: 0.65
        cat:
          min_score: 0.4
          threshold: 0.65
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - fenetre
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 60
      required_zones:
          - fenetre
    zones:
      fenetre:
        coordinates: 926,14,882,359,1192,438,1248,95
        objects:
          - person
    motion:
      mask:
        - 45,621,507,623,503,669,44,667
################  MQTT #######################

mqtt:
  host: 192.168.1.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: BLANKED
  password: BLANKED
  stats_interval: 60

#database:
#  The path to store the SQLite DB (default: shown below)
#  path: /media/frigate/frigate.db
#  path: /db/frigate.db

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous
#  quality: 10

detectors:
  coral_pci:
    type: edgetpu
    device: ""

ffmpeg:
  hwaccel_args: preset-nvidia-h264
#  hwaccel_args: -c:v hevc_cuvid
#  output_args: 
#    record: preset-record-generic-audio-aac
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#    record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -strftime 1 -c:v h264_nvenc -b:v 4M
#    detect: -f rawvideo -pix_fmt yuv420p

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
#  default: info
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: info
```

### Relevant log output

```shell
l
```

### FFprobe output from your camera

```shell
l
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Anpviz IPC-D352VU-S

### Any other information that may be helpful

#rotate=90 is ignored.. camera is not rotated...

**Comment by NickM-27** [comment]
You need to follow the docs of go2rtc. You need to have `#video=h264` in the stream otherwise it will not do video decoding and the `#rotate` arg is ignored

you also need to call the camera something different or else the rotated stream will be ignored

```
go2rtc:
  streams:
    Side:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.23:554/Streaming/Channels/1
      - "ffmpeg:Side#audio=aac"
    Side_Rotated:
      - "ffmpeg:Side#video=h264#rotate=90"
```
