### ISSUE TITLE
[Config Support]:  Retain days

### ISSUE THREAD

**Issue by jtsarnas76** [blakeblackshear/frigate#6307]
### Describe the problem you are having

Working great except retain days. I 've set it to 3 days for both events and snapshots but keeps going forever.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.136
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxxx
  password: xxxxxxxxx
  
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

logger:
  default: info
  logs:
    frigate.event: debug

detect:
  width: 640
  height: 384
  fps: 10

objects:
  track:
    - person
    - car
  filters:
    person:
      min_area: 4000
      max_area: 100000
      threshold: 0.6
      min_score: 0.5
    car:
      min_area: 10000
      max_area: 120000
      threshold: 0.7  
      min_score: 0.5

record:
  enabled: true
  retain:
    days: 2
    mode: active_objects
  
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    required_zones:
      - inside_back
      - outside_back
      - inside_front
      - outside_front
    retain:
      default: 2
      mode: active_objects
      objects:
        person: 2
        car: 2

snapshots:
  enabled: True
  bounding_box: False
  timestamp: False
  crop: True
  height: 500
  required_zones:
    - inside_back
    - outside_back
    - inside_front
    - outside_front
  retain:
    default: 3
    objects: 
      person: 3
      car: 3

rtmp:
  enabled: False

go2rtc:
  streams: 
    Front: 
      - rtsp://xxxxxxxx:xxxxxxxx@192.168.1.190:554/stream1
    Front_sub: 
      - rtsp://xxxxxxxx:xxxxxxxx@192.168.1.190:554/stream2
    Back: 
      - rtsp://xxxxxxxx:xxxxxxxx@192.168.1.49:554/stream1
    Back_sub: 
      - rtsp://xxxxxxxx:xxxxxxxx@192.168.1.49:554/stream2
  webrtc:
    candidates:
      - 192.168.1.136:8555
      - stun:8555
      
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back?video=all&audio=all
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Back_sub?video=all&audio=all
          roles:
            - detect
    live:
      stream_name: Back
    zones:
      inside_back:
        coordinates: 509,360,531,88,393,93,277,360
        objects: 
          - person
      outside_back:
        coordinates: 428,0,273,360,0,360,262,0
        objects: 
          - person
          - car

  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front?video=all&audio=all
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_sub?video=all&audio=all
          roles:
            - detect
    live:
      stream_name: Front
    zones:  
      inside_front:
        coordinates: 367,160,306,129,312,77,331,38,366,36,395,0,416,0,459,0,493,0,548,24,586,59,545,108,528,215,522,293,337,216
        objects: 
          - person
      outside_front:
        coordinates: 0,257,46,222,78,188,121,152,163,166,212,128,235,46,263,0,0,0
        objects: 
          - person
          - car
    motion:
      mask:   
        - 68,89,117,85,146,65,178,50,224,31,244,0,199,0,138,0,58,0,33,71
        - 89,358,146,384,339,384,358,342,353,315,350,277,352,197,364,158,313,129,261,100,203,157,170,179,143,141,92,182,36,244,82,299
```

### Relevant log output

```shell
2023-04-28 16:36:08.534504702  [INFO] Starting Frigate...
2023-04-28 16:36:10.260909055  [2023-04-28 16:36:10] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-28 16:36:10.303907767  [2023-04-28 16:36:10] peewee_migrate                 INFO    : Starting migrations
2023-04-28 16:36:10.310627763  [2023-04-28 16:36:10] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-28 16:36:10.335330307  [2023-04-28 16:36:10] detector.coral                 INFO    : Starting detection process: 289
2023-04-28 16:36:12.996732857  [2023-04-28 16:36:10] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-04-28 16:36:12.996741293  [2023-04-28 16:36:10] frigate.app                    INFO    : Output process started: 291
2023-04-28 16:36:12.996748328  [2023-04-28 16:36:10] frigate.app                    INFO    : Camera processor started for back: 298
2023-04-28 16:36:12.996750892  [2023-04-28 16:36:10] frigate.app                    INFO    : Camera processor started for front: 300
2023-04-28 16:36:12.996768789  [2023-04-28 16:36:10] frigate.app                    INFO    : Capture process started for back: 301
2023-04-28 16:36:12.996889802  [2023-04-28 16:36:10] frigate.app                    INFO    : Capture process started for front: 305
2023-04-28 16:36:13.006715260  [2023-04-28 16:36:12] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Frigate stats

```json
{"back":{"camera_fps":15.1,"capture_pid":301,"detection_enabled":1,"detection_fps":8.7,"ffmpeg_pid":313,"pid":298,"process_fps":15.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"108":{"cpu":"5.3","mem":"1.8"},"115":{"cpu":"0.0","mem":"0.2"},"116":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.3","mem":"1.0"},"288":{"cpu":"0.7","mem":"0.1"},"289":{"cpu":"0.0","mem":"1.4"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"2.3","mem":"1.1"},"297":{"cpu":"0.0","mem":"0.2"},"298":{"cpu":"2.7","mem":"1.1"},"299":{"cpu":"0.0","mem":"0.2"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"2.3","mem":"1.1"},"301":{"cpu":"3.3","mem":"1.1"},"302":{"cpu":"0.0","mem":"0.2"},"305":{"cpu":"3.3","mem":"1.1"},"31":{"cpu":"0.0","mem":"0.0"},"313":{"cpu":"7.0","mem":"0.5"},"314":{"cpu":"7.0","mem":"0.5"},"32":{"cpu":"0.0","mem":"0.0"},"335":{"cpu":"0.7","mem":"0.4"},"336":{"cpu":"1.0","mem":"0.4"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"712":{"cpu":"0.0","mem":"0.0"},"745":{"cpu":"0.0","mem":"0.0"},"751":{"cpu":"0.3","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"3.7","mem":"0.2"},"MiB":{"cpu":"2526.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":15.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":12.54,"pid":289}},"front":{"camera_fps":15.1,"capture_pid":305,"detection_enabled":1,"detection_fps":6.7,"ffmpeg_pid":314,"pid":300,"process_fps":15.1,"skipped_fps":0.0},"gpu_usages":{"intel-qsv":{"gpu":"1.63 %","mem":"- %"}},"service":{"last_updated":1682689244,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":132.0,"mount_type":"tmpfs","total":134.2,"used":2.2},"/media/frigate/clips":{"free":180853.2,"mount_type":"ext4","total":234039.4,"used":41223.1},"/media/frigate/recordings":{"free":180853.2,"mount_type":"ext4","total":234039.4,"used":41223.1},"/tmp/cache":{"free":997.1,"mount_type":"tmpfs","total":1000.0,"used":2.9}},"temperatures":{},"uptime":274,"version":"0.12.0-da3e197"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
