### ISSUE TITLE
[HW Accel Support]: QNAP NVIDIA GeForce GTX 1050 Ti not accepting device driver "nvidia"

### ISSUE THREAD

**Issue by gklank** [blakeblackshear/frigate#6310]
### Describe the problem you are having

Hi,

the QNAP docker-compose is not accepting the device driver nvidia:
---------------------------------
docker-compose up -d
Starting frigate-15 ... error

ERROR: for frigate-15  Cannot start service frigate: could not select device driver "nvidia" with capabilities: [[gpu]]

ERROR: for frigate  Cannot start service frigate: could not select device driver "nvidia" with capabilities: [[gpu]]
ERROR: Encountered errors while bringing up the project.
--------------------------------

Is there any idea or possibility to get this fixed?

Regards

Gerhard

### Version

image: ghcr.io/blakeblackshear/frigate:0.12.0-beta10

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.250
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60

logger:
  default: info
  logs:
    frigate.event: debug

detectors:
  coral:
    type: edgetpu
    device: usb
  #cpu1:
    #type: cpu

cameras:
  Garage-2:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.213:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://user:password@192.168.1.213:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: false
    detect:
      #width: 1280
      #height: 720
      width: 1920
      height: 1080
      fps: 10
      max_disappeared: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 65000
          max_area: 24000000
          min_score: 0.5
          threshold: 0.7
        cat:
          min_area: 1700
          max_area: 60000
          min_score: 0.5
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
      required_zones:
        - zone_garage_hauptbereich
    record:
      enabled: true
      retain:
        days: 3
        #mode: motion wenn spaeter mal auch die Katzen erkannt werden, dann ist hier motion meine Wahl
        mode: all
      events:
        retain:
          default: 7
          #mode: active_objects wenn spaeter mal auch die Katzen erkannt werden, dann ist active_objects meine Wahl
          mode: motion
        pre_capture: 10
        post_capture: 15
        required_zones:
          - zone_garage_hauptbereich
    zones:
      zone_garage_hauptbereich:
        coordinates: 0,987,1920,988,1920,403,1495,265,536,302,423,281,0,408
    motion:
      mask:
        - 0,0,0,400,674,368,672,0

  Tuer-2:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.214:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://user:password@192.168.1.214:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: false
#2560x1920 kann die Kamera
    detect:
      #width: 1280
      #height: 720
      width: 1920
      height: 1080
      fps: 10
      max_disappeared: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 65000
          max_area: 24000000
          min_score: 0.5
          threshold: 0.7
          #mask:
            #- 137,81,354,720,0,720,0,81
        cat:
          #min_area: 1000
          min_area: 500
          max_area: 60000
          min_score: 0.5
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
      required_zones:
        - zone_tuer_hauptbereich
    record:
      enabled: true
      retain:
        days: 3
        #mode: motion wenn spaeter mal auch die Katzen erkannt werden, dann ist hier motion meine Wahl
        mode: all
      events:
        retain:
          default: 7
          #mode: active_objects wenn spaeter mal auch die Katzen erkannt werden, dann ist active_objects meine Wahl
          mode: motion
        pre_capture: 10
        post_capture: 15
        required_zones:
          - zone_tuer_hauptbereich
    zones:
      zone_tuer_hauptbereich:
        coordinates: 584,1080,1920,1080,1920,377,532,302,253,350
    motion:
      mask:
        - 1920,371,1920,0,1816,0
        - 1678,387,1656,0,464,0,483,319
        - 0,1080,628,1080,232,245,0,210

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  #enabled: True
  enabled: false
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate-15
    hostname: frigate-5
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta10
    privileged: true
    shm_size: '100m'
    network_mode: bridge
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/nvidia0
      - /dev/dri/renderD128
      - /dev/dri/card0
    environment:
      - TZ=Europe/Berlin
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,gpu
      - CUDA_VERSION="11.7"
    volumes:
      - /share/GK2/Frigate2/config:/config
      - /share/GK2/Frigate2/dri:/dev/dri
      - /share/GK2/Frigate2/media:/media/frigate
      - /share/CACHEDEV1_DATA/.qpkg/NVIDIA_GPU_DRV/usr:/usr/local/nvidia:rw
      - /share/CACHEDEV1_DATA/.qpkg/NVIDIA_GPU_DRV/cuda-11.7:/usr/local/cuda
      - /share/GK2/Frigate2:/srv/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 75000000 ## 75MB, good for 3 1080p cameras with 10s of cache each, this depends on your setup.
    ports:
      - 1935:1935
      - 5000:5000
      - 8554:8554
      - 8555:8555
      - 8555:8555/udp
    restart: unless-stopped
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC-511WA

### Any other information that may be helpful

HW: QNAP TS-473
OS: QTS 5.0.1.2376
docker-compose version 1.29.2, build 1ca12643
