### ISSUE TITLE
[Config Support]: Performance problem with WebRTC stream

### ISSUE THREAD

**Issue by NormKOALA** [blakeblackshear/frigate#6323]
### Describe the problem you are having

Could you explain to me where I have a [mistake](https://github.com/AlexxIT/go2rtc/issues/398) in the config?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.173
  user: user
  password: pass

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  rtsp:
    username: "user"
    password: "pass"
  streams:
    Hall_Camera:
      - rtsp://user:pass@192.168.1.120:554/stream1
      - "ffmpeg:Hall_Camera"
    Hall_Camera_Sub:
      - rtsp://user:pass@192.168.1.120:554/stream2
      - "ffmpeg:Hall_Camera_Sub"

    Livingroom_Camera:
      - rtsp://user:pass@192.168.1.121:554/stream1
      - "ffmpeg:Livingroom__Camera"
    Livingroom_Camera_Sub:
      - rtsp://user:pass@192.168.1.121:554/stream2
      - "ffmpeg:Livingroom_Camera_Sub"

    Facade_Camera:
      - rtsp://user:pass@192.168.1.122:554/h264Preview_01_main
      - "ffmpeg:Facade_Camera"
    Facade_Camera_Sub:
      - rtsp://user:pass@192.168.1.122:554/h264Preview_01_sub
      - "ffmpeg:Facade_Camera_Sub"
  webrtc:
    candidates:
      - 192.168.1.173:8555
      - stun:8555

cameras:
  Hall_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        # - path: rtsp://127.0.0.1:8554/Hall_Camera_Sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #   - detect
        - path: rtsp://127.0.0.1:8554/Hall_Camera
          input_args: preset-rtsp-restream
          roles:
          - detect
          - record
    detect:
      enabled: true
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2 # days
    record:
      enabled: true
      events:
        retain:
          default: 2 # days
    motion:
      mask:
      - 788,0,808,398,1015,391,1020,0,1920,0,1920,1080,0,1080,0,0
    live:
      stream_name: Hall_Camera_Sub


  Livingroom_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Livingroom_Camera
          input_args: preset-rtsp-restream
          roles:
          - detect
    detect:
      enabled: false
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person
    live:
      stream_name: Livingroom_Camera_Sub


  Facade_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Facade_Camera_Sub
          input_args: preset-rtsp-restream
          roles:
          - detect
        - path: rtsp://127.0.0.1:8554/Facade_Camera
          input_args: preset-rtsp-restream
          roles:
          - record
    detect:
      enabled: true
      max_disappeared: 25
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
      - person
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2 # days
    record:
      enabled: true
      events:
        retain:
          default: 2 # days
    motion:
      mask:
      - 819,272,1377,268,2111,314,2560,750,2560,0,0,0,0,386,251,347
    live:
      stream_name: Facade_Camera_Sub

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  logs:
    frigate.edgetpu: debug
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by blakeblackshear** [comment]
I think you can remove all of the second entries with ffmpeg for your go2rtc streams. I don't think they are doing anything.

```yaml 
- "ffmpeg:Hall_Camera"
```

Did you follow the guide in our docs for setting up go2rtc? I'm curious if there is something in the docs that led you to believe that was the right config.

**Comment by NormKOALA** [comment]
Thank you for your response.
1. I removed all rows like `- "ffmpeg:Hall_Camera"`, but all got worse. All streams using WebRTC crash the system immediately.

#### Current config:
```yaml
mqtt:
  host: 192.168.1.173
  user: user
  password: pass

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  rtsp:
    username: "user"
    password: "pass"
  streams:
    Hall_Camera:
      - rtsp://user:pass@192.168.1.120:554/stream1
      # - "ffmpeg:Hall_Camera#audio=opus"
    Hall_Camera_Sub:
      - rtsp://user:pass@192.168.1.120:554/stream2
      # - "ffmpeg:Hall_Camera_Sub#audio=opus"

    Livingroom_Camera:
      - rtsp://user:pass@192.168.1.121:554/stream1
      # - "ffmpeg:Livingroom_Camera#audio=opus"
    Livingroom_Camera_Sub:
      - rtsp://user:pass@192.168.1.121:554/stream2
      # - "ffmpeg:Livingroom_Camera_Sub#audio=opus"

    Facade_Camera:
      - rtsp://user:pass@192.168.1.122:554/h264Preview_01_main
      # - "ffmpeg:Facade_Camera#audio=opus"
    Facade_Camera_Sub:
      - rtsp://user:pass@192.168.1.122:554/h264Preview_01_sub
      # - "ffmpeg:Facade_Camera_Sub#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.173:8555
      - stun:8555

cameras:
  Hall_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        # - path: rtsp://127.0.0.1:8554/Hall_Camera_Sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #   - detect
        - path: rtsp://127.0.0.1:8554/Hall_Camera
          input_args: preset-rtsp-restream
          roles:
          - detect
          - record
    detect:
      enabled: true
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2 # days
    record:
      enabled: true
      events:
        retain:
          default: 2 # days
    motion:
      mask:
      - 788,0,808,398,1015,391,1020,0,1920,0,1920,1080,0,1080,0,0
    # live:
    #   stream_name: Hall_Camera_Sub


  Livingroom_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Livingroom_Camera
          input_args: preset-rtsp-restream
          roles:
          - detect
    detect:
      enabled: false
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person
    # live:
    #   stream_name: Livingroom_Camera_Sub


  Facade_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Facade_Camera_Sub
          input_args: preset-rtsp-restream
          roles:
          - detect
        - path: rtsp://127.0.0.1:8554/Facade_Camera
          input_args: preset-rtsp-restream
          roles:
          - record
    detect:
      enabled: true
      max_disappeared: 25
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
      - person
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2 # days
    record:
      enabled: true
      events:
        retain:
          default: 2 # days
    motion:
      mask:
      - 819,272,1377,268,2111,314,2560,750,2560,0,0,0,0,386,251,347
    # live:
    #   stream_name: Facade_Camera_Sub

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  logs:
    frigate.edgetpu: debug

```

2. Yes, and The documentation contains the following

<img width="729" alt="Screenshot 2023-04-30 202722" src="https://user-images.githubusercontent.com/70369365/235350502-90ab544a-f4fe-43a4-87b1-659114eb7cee.png">

Clicking on the [here](url) follows to the below example

<img width="730" alt="Screenshot 2023-04-30 203129" src="https://user-images.githubusercontent.com/70369365/235350662-464e5e59-cac7-4d12-9dc7-4eccb4ab1d1a.png">

So, How we can understand that `- "ffmpeg:rtsp_cam#audio=opus"` doesn't have role in `Reduce Connections To Camera`
