### ISSUE TITLE
[Support]: Could not write config file, be sure that Frigate has write permission on the config file.

### ISSUE THREAD

**Issue by FS1961** [blakeblackshear/frigate#6326]
### Describe the problem you are having

Love the new interface/version 12 with direct config editing support. However, I can't update via Frigate and must use ssh to edit and update the file.

Obviously, I'm missing something.  I don't have a user named Frigate but I'm assuming it has something to do with file permissions?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.82
  user: mqtt
  password: haosmqtt

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

cameras:
  Dining: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.59:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
   
  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.36:554/play1.sdp          # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
   
  Front-door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.28:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,127,0,352,226,352,242,327,206,83
        - 640,352,640,218,506,318,356,352,240,331,227,352
    zones:
      entry_doors:
        coordinates: 293,318,513,302,574,63,285,27
             
  Drive-way: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t22!@192.168.178.55:554/h264  # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
    motion:
    zones:
      driveway_area:
        coordinates: 469,117,596,360,226,360,224,115
      front_entrance:
        coordinates: 224,112,463,105,442,0,211,0
      
  Patio: # <------ Name the camera.
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t22!@192.168.178.74:554/h264  # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
 
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  events:
    retain:
      default: 10
```

### Relevant log output

```shell
None.
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Not a camera issue

### Any other information that may be helpful

Running on standalone Ubuntu box.
