### ISSUE TITLE
[Support]: Connection refused while connecting to upstream

### ISSUE THREAD

**Issue by HHUBSS** [blakeblackshear/frigate#6330]
### Describe the problem you are having

I have this error "connection refuse while connecting to upstream" status. Viewing all the clips and recording is taking too much time.

![5](https://user-images.githubusercontent.com/89816305/235365949-6c53b556-07ac-473e-a93b-94f3e0b603af.png)

And then I got this upstream error timeout after awhile

![4](https://user-images.githubusercontent.com/89816305/235366016-69847a90-7ccb-4970-9e4a-e9d894f33f58.png)

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.2
  port: 1883
  user: [removed]
  password: [removed]

detect:
  width: 640
  height: 480
  fps: 5
      
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 60
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
        
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 60
    objects:
      person: 60
      cat: 60
      dog: 60
      bird: 60
      car: 60
      motorcycle: 60
          
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb
      
go2rtc:
  streams:
    living:
      - rtsp://[removed]:[removed]@192.168.50.100:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    living_sub:
      - rtsp://[removed]:[removed]@192.168.50.100:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
    rooftop:
      - rtsp://[removed]:[removed]@192.168.50.101:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    rooftop_sub:
      - rtsp://[removed]:[removed]@192.168.50.101:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
    front:
      - rtsp://[removed]:[removed]@192.168.50.102:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front_sub:
      - rtsp://[removed]:[removed]@192.168.50.102:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
    parking:
      - rtsp://[removed]:[removed]@192.168.50.103:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    parking_sub:
      - rtsp://[removed]:[removed]@192.168.50.103:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1

ui:
  live_mode: webrtc
  
live:
  height: 640
  quality: 1

rtmp:
  enabled: false

cameras:
  living:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/living
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: living_sub
    objects:
      track:
        - person
        - cat
    motion:
      mask: 0,56,216,55,215,21,0,21
    zones:
      living_zone:
        coordinates: 462,480,468,182,480,21,394,0,258,0,244,58,115,61,0,60,0,135,0,480
        objects:
          - person
          - cat

  rooftop:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rooftop_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/rooftop
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: rooftop_sub
    record:
      events:
        required_zones:
          - rooftop_area
    snapshots:
      required_zones:
        - rooftop_area
    objects:
      track:
        - person
        - cat
        - bird
        - dog
    motion:
      mask: 272,253,0,250,0,145,0,0,442,0,640,0,640,480,515,480,471,275,369,264,372,205,276,192
    zones:
      rooftop_area:
        coordinates: 518,480,477,268,370,254,366,181,274,188,253,236,220,237,0,247,0,480
        objects:
          - person
          - cat
          - dog
                      
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: front_sub
    record:
      events:
        required_zones:
          - front_house
          - planters
          - garage
    snapshots:
      required_zones:
        - front_house
        - planters
        - garage
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
    motion:
      mask: 0,217,0,0,199,0,350,0,447,0,640,0,640,67,640,182,419,204,0,458,0,480
    zones:
      front_house:
        coordinates: 239,480,291,439,360,384,413,331,445,294,479,252,414,246,274,345,83,480
        objects:
          - person
          - car
          - motorcycle
          - dog
      planters:
        coordinates: 552,480,473,459,494,262,405,369,289,480
        objects:
          - person
          - cat
          - dog
      garage:
        coordinates: 489,242,529,194,590,219,576,380,548,480,475,459
        objects:
          - person
          - cat
          - dog  
            
  parking:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/parking_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/parking
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: parking_sub
    record:
      events:
        required_zones:
          - garage
    snapshots:
      required_zones:
        - garage
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        - 477,0,481,91,228,81,215,0
        - 0,24,217,24,219,48,0,46
    zones:
      garage:
        coordinates: 478,480,480,89,249,86,221,98,213,34,0,167,0,480,62,480
        objects:
          - person
          - cat
          - dog
```

### Relevant log output

```shell
2023-05-01 01:17:44.524773391  [INFO] Starting Frigate...
2023-05-01 01:18:00.724789915  [2023-05-01 01:18:00] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-01 01:18:00.767938071  [2023-05-01 01:18:00] peewee_migrate                 INFO    : Starting migrations
2023-05-01 01:18:00.938109754  [2023-05-01 01:18:00] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-01 01:18:01.345573325  [2023-05-01 01:18:01] detector.coral                 INFO    : Starting detection process: 578
2023-05-01 01:18:01.486003700  [2023-05-01 01:18:01] frigate.app                    INFO    : Output process started: 580
2023-05-01 01:18:04.092234356  [2023-05-01 01:18:01] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-01 01:18:04.182577837  [2023-05-01 01:18:01] frigate.app                    INFO    : Camera processor started for living: 583
2023-05-01 01:18:04.182641052  [2023-05-01 01:18:04] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-01 01:18:04.182687006  [2023-05-01 01:18:01] frigate.app                    INFO    : Camera processor started for rooftop: 584
2023-05-01 01:18:04.182741909  [2023-05-01 01:18:01] frigate.app                    INFO    : Camera processor started for front: 585
2023-05-01 01:18:04.182784689  [2023-05-01 01:18:01] frigate.app                    INFO    : Camera processor started for parking: 586
2023-05-01 01:18:04.182839487  [2023-05-01 01:18:01] frigate.app                    INFO    : Capture process started for living: 587
2023-05-01 01:18:04.182887462  [2023-05-01 01:18:01] frigate.app                    INFO    : Capture process started for rooftop: 591
2023-05-01 01:18:04.182929731  [2023-05-01 01:18:01] frigate.app                    INFO    : Capture process started for front: 595
2023-05-01 01:18:04.182987496  [2023-05-01 01:18:01] frigate.app                    INFO    : Capture process started for parking: 599
```

### FFprobe output from your camera

```shell
No response
```

### Frigate stats

```json
No response
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

HIKVISION
