### ISSUE TITLE
[Config Support]: Substream with different aspect ratio

### ISSUE THREAD

**Issue by tavicu** [blakeblackshear/frigate#6343]
### Describe the problem you are having

Hi.

I have more Dahua cameras and the main stream have an aspect ratio of 16:9 but the substream have 4:3 (640x480).

I have tried following the instructions from this issue (https://github.com/blakeblackshear/frigate/issues/416) to change the aspect ratio of the output but once I set it it's starting to throw errors and it's not working anymore.

By default in config file at detect is 640x360 because I have others camera too that have that resolution as output.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic

detect:
  enabled: False
  width: 640
  height: 360
  fps: 5
  max_disappeared: 25

live:
  height: 360
  quality: 8

go2rtc:
  webrtc:
    candidates:
      - SERVER_IP:8555
      - stun:8555
  streams:
    camera1:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.100.10:554/cam/realmonitor?channel=1&subtype=0

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.100.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: False
      width: 640
      height: 480
```

### This is how I tried setting up the config file:
```
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.100.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      output_args:
        detect: '-vf scale=853:480 -f rawvideo -pix_fmt yuv420p'
        rtmp: '-aspect 853:480 -c copy -f flv'
    detect:
      enabled: False
      width: 853
      height: 480
```

**FFprobe main stream:**
```
Input #0, rtsp, from 'rtsp://xxx:xxx@192.168.100.10:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0, 28, 1/90000: Video: h264 (Baseline), 1 reference frame, yuv420p(progressive, left), 2560x1440, 0/1, 10 fps, 20 tbr, 90k tbn
  Stream #0:1, 37, 1/8000: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

**FFprobe sub stream:**
```
Input #0, rtsp, from 'rtsp://xxx:xxx@192.168.100.10:554/cam/realmonitor?channel=1&subtype=1':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0, 15, 1/90000: Video: h264 (Main), 1 reference frame, yuv420p(progressive, left), 640x480, 0/1, 2.50 fps, 20 tbr, 90k tbn
  Stream #0:1, 83, 1/8000: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Relevant log output

```shell
frigate          | 2023-05-01 22:15:07.018968646  [2023-05-01 22:15:07] ffmpeg.camera1.detect          ERROR   : Multiple -filter, -af or -vf options specified for stream 0, only the last option '-filter:v scale=853:480' will be used.
frigate          | 2023-05-01 22:15:07.018976073  [2023-05-01 22:15:07] ffmpeg.camera1.detect          ERROR   : Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
frigate          | 2023-05-01 22:15:07.018981203  [2023-05-01 22:15:07] ffmpeg.camera1.detect          ERROR   : Error reinitializing filters!
frigate          | 2023-05-01 22:15:07.018987098  [2023-05-01 22:15:07] ffmpeg.camera1.detect          ERROR   : Failed to inject frame into filter network: Function not implemented
frigate          | 2023-05-01 22:15:07.019137748  [2023-05-01 22:15:07] ffmpeg.camera1.detect          ERROR   : Error while processing the decoded data for stream #0:0



frigate          | 2023-05-01 22:06:01.524728014  [2023-05-01 22:06:01] frigate.http                   ERROR   : Exception on /camera1/latest.jpg [GET]
frigate          | 2023-05-01 22:06:01.524738407  Traceback (most recent call last):
frigate          | 2023-05-01 22:06:01.524744631    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
frigate          | 2023-05-01 22:06:01.524755105      response = self.full_dispatch_request()
frigate          | 2023-05-01 22:06:01.524761440    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
frigate          | 2023-05-01 22:06:01.524769182      rv = self.handle_user_exception(e)
frigate          | 2023-05-01 22:06:01.524774565    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
frigate          | 2023-05-01 22:06:01.524806855      rv = self.dispatch_request()
frigate          | 2023-05-01 22:06:01.524812366    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
frigate          | 2023-05-01 22:06:01.524862230      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate          | 2023-05-01 22:06:01.524867563    File "/opt/frigate/frigate/http.py", line 875, in latest_frame
frigate          | 2023-05-01 22:06:01.524872958      frame = current_app.detected_frames_processor.get_current_frame(
frigate          | 2023-05-01 22:06:01.524877968    File "/opt/frigate/frigate/object_processing.py", line 889, in get_current_frame
frigate          | 2023-05-01 22:06:01.524909066      return self.camera_states[camera].get_current_frame(draw_options)
frigate          | 2023-05-01 22:06:01.524914456    File "/opt/frigate/frigate/object_processing.py", line 389, in get_current_frame
frigate          | 2023-05-01 22:06:01.524919674      frame_copy = cv2.cvtColor(frame_copy, cv2.COLOR_YUV2BGR_I420)
frigate          | 2023-05-01 22:06:01.524926265  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:108: error: (-215:Assertion failed) sz.width % 2 == 0 && sz.height % 3 == 0 in function 'CvtHelper'
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You need to use the detect config to override the size. I see you are setting it at the global level but it is also defined differently at the camera level which overrides the global config

**Comment by tavicu** [comment]
> You need to use the detect config to override the size. I see you are setting it at the global level but it is also defined differently at the camera level which overrides the global config

I have multiple cameras and the global one is for the other cameras.
At the camera level I have set the resolution for Dahua camera, which is different.

I have tried it to change only the size for the camera to the new aspect ration but then it will throw error when is trying to create latest.jpg and the feed is showing wrong.

```
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.100.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: False
      width: 853
      height: 480
```

Logs:
```
frigate          | 2023-05-01 23:08:39.776628005  [2023-05-01 23:08:39] frigate.http                   ERROR   : Exception on /camera1/latest.jpg [GET]
frigate          | 2023-05-01 23:08:39.776632318  Traceback (most recent call last):
frigate          | 2023-05-01 23:08:39.776634664    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
frigate          | 2023-05-01 23:08:39.776639187      response = self.full_dispatch_request()
frigate          | 2023-05-01 23:08:39.776641620    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
frigate          | 2023-05-01 23:08:39.776644560      rv = self.handle_user_exception(e)
frigate          | 2023-05-01 23:08:39.776646656    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
frigate          | 2023-05-01 23:08:39.776661785      rv = self.dispatch_request()
frigate          | 2023-05-01 23:08:39.776664013    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
frigate          | 2023-05-01 23:08:39.776680937      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate          | 2023-05-01 23:08:39.776683015    File "/opt/frigate/frigate/http.py", line 875, in latest_frame
frigate          | 2023-05-01 23:08:39.776685026      frame = current_app.detected_frames_processor.get_current_frame(
frigate          | 2023-05-01 23:08:39.776686961    File "/opt/frigate/frigate/object_processing.py", line 889, in get_current_frame
frigate          | 2023-05-01 23:08:39.776698862      return self.camera_states[camera].get_current_frame(draw_options)
frigate          | 2023-05-01 23:08:39.776701009    File "/opt/frigate/frigate/object_processing.py", line 389, in get_current_frame
frigate          | 2023-05-01 23:08:39.776703021      frame_copy = cv2.cvtColor(frame_copy, cv2.COLOR_YUV2BGR_I420)
frigate          | 2023-05-01 23:08:39.776705365  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:108: error: (-215:Assertion failed) sz.width % 2 == 0 && sz.height % 3 == 0 in function 'CvtHelper'
```

Live feed:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/172068/235522552-b2c66baf-4cac-4681-8f5e-7f077e1e3903.png">

**Comment by NickM-27** [comment]
What do the nginx logs say for the latest.jpg call when it fails.

**Comment by tavicu** [comment]
I was able to solve it.
Looking at the last error message it seems the width must odd number, so I have set the width to 854 and now it's working :)

Guess last night was too late and didn't catch it ...

So the final config is like this in case anyone is having this problem:
```
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.100.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: False
      width: 854
      height: 480
```

Thank you for your help Nick.
