### ISSUE TITLE
[Support]: Recordings not working in some cases

### ISSUE THREAD

**Issue by rananna** [blakeblackshear/frigate#6352]
### object recording not working after boot with detect disabled in frigate.yml and manualy enabling detect recording and snapshots

I have been struggling to get object detection working for my setup.
I have seven cameras, a mixture of tapo and reolink and two coral detectors running on a 800 G3 mini. [https://support.hp.com/ca-en/document/c05371240](url).
the issue is that some cameras are working fine, and other identical cameras were not recording on any detection events. Static images were generated only.

I stumbled across the reason for the issue:
It turned out that the cameras that didn't work did not have detection enabled in the config.yml file, and I was manually enabling detect, recordings and clips from the UI, and this wasn't working.
HOWEVER, if you enable detection in the config file,  and reboot, the cameras start recording!
It appears that there may be a bug associated with enabling detection after a boot.

my config file is attached

    

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# randy's configuration 2
mqtt:
    host: 192.168.1.21
    user: "mqtt-user"
    password: "redacted"
    topic_prefix: frigate
    client_id: frigate

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
 
  #hwaccel_args: -hwaccel qsv -hwaccel_output_format nv12 -c:v h264_qsv

  #input_args: preset-rtsp-generic



  input_args:
    - preset-rtsp-generic
  output_args:
 
    detect: -f rawvideo -pix_fmt yuv420p
  #  record: preset-record-generic
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
 # 
 # input_args: preset-rtsp-generic -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -timeout 5000000 -use_wallclock_as_timestamps 1
  #output_args:
   # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
   
 # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -an

# birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

detectors:
  coral1:
    type: edgetpu
    device: usb
  coral2:
    type: edgetpu
    device: pci:0

#Global Object Settings
objects:
  track:
    - person
    - dog
    - cat
detect:
  stationary:
    interval: 0
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
    
go2rtc:
  streams:
    patio:
      - rtsp://rananna:redacted@192.168.1.205:554/stream1
      - "ffmpeg:rtsp://rananna:redacted@192.168.1.205:554/stream1#video=copy#audio=copy#audio=opus"
    patio_sub:
      - rtsp://rananna:redacted@192.168.1.205:554/stream2
    deck:
      #- http://192.168.1.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.31:554//h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"
      
      
    deck_sub:
     # - http://192.168.1.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.31:554//h264Preview_01_sub
    front:
      #- http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.30:554//h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"
     # - rtsp://admin:redacted@192.168.1.30:554//h264Preview_01_main
    front_sub:
     # - http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.30:554//h264Preview_01_sub
     # - rtsp://admin:redacted192.168.1.30:554//h264Preview_01_sub
    shed:
      - rtsp://rananna:redacted@192.168.1.26:554/stream1
      - "ffmpeg:rtsp://rananna:redacted@192.168.1.26:554/stream1#video=copy#audio=copy#audio=opus"
    shed_sub:
      - rtsp://rananna:redacted@192.168.1.26:554/stream2
    back:
      - http://192.168.1.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
     # - rtsp://admin:redacted@192.168.1.33:554//h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"
    back_sub:
      #- http://192.168.1.33/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.33:554//h264Preview_01_sub
    office:
     # - http://192.168.1.34/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.34:554//h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"
    office_sub:
     
      - rtsp://admin:redacted@192.168.1.34:554//h264Preview_01_sub
    kitchen:
      - rtsp://rananna:redacted@192.168.1.28:554/stream1
      - "ffmpeg:rtsp://rananna:redacted@192.168.1.28:554/stream1#video=copy#audio=copy#audio=opus"
    kitchen_sub:
      - rtsp://rananna:redacted@192.168.1.28:554/stream2


    livingroom:
      #- http://192.168.1.39/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.39:554//h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"
    livingroom_sub:
      #- http://192.168.1.39/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
      - rtsp://admin:redacted@192.168.1.39:554//h264Preview_01_sub
cameras:
  patio:

    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-copy      
      inputs:
        - path: rtsp://192.168.1.184:8554/patio_sub?video=copy
          input_args: preset-rtsp-restream 
          roles:
            - detect
        - path: rtsp://192.168.1.184:8554/patio?video=copy&audio=aac
          input_args: preset-rtsp-restream 

          roles:
            - record
    live:
      stream_name: patio
    best_image_timeout: 60
    rtmp:
      enabled: False

    detect:
      enabled: true
      width: 640
      height: 360
      fps: 1
    objects:
      track:
        - person
        - dog
        - cat 
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10



    


  deck:
    live:
      stream_name: deck
    best_image_timeout: 60
    rtmp:
      enabled: False
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-copy        
      inputs:
        - path: rtsp://192.168.1.184:8554/deck_sub?video=copy 
          input_args: preset-rtsp-restream 
          roles:
            - detect
        - path: rtsp://192.168.1.184:8554/deck?video=copy&audio=AAC
          input_args: preset-rtsp-restream 
          roles:
            - record


    detect:
      enabled: true
      width: 896
      height: 512
      fps: 4
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10

   
  front:
    live:
      stream_name: front
    best_image_timeout: 60
    rtmp:
      enabled: False
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-copy   
      inputs:
        - path: rtsp://192.168.1.184:8554/front_sub?video=copy
          input_args: preset-rtsp-restream 
          roles:
            - detect
        - path: rtsp://192.168.1.184:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream 

          roles:
            - record


    detect:
      enabled: true
      width: 896
      height: 512
      fps: 4
    objects:
      track:
        - person
        - dog
        - cat 
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10

    

  shed:
    live:
      stream_name: shed
    best_image_timeout: 60
    rtmp:
      enabled: False
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-copy   
      inputs:
        - path: rtsp://192.168.1.184:8554/shed_sub?video=copy
          input_args: preset-rtsp-restream 
          roles:
            - detect
        - path: rtsp://192.168.1.184:8554/shed?video=copy&audio=aac
          input_args: preset-rtsp-restream 

          roles:
            - record


    detect:
      enabled: true
      width: 640
      height: 360
      fps: 1
    objects:
      track:
        - person
        - dog
        - cat 
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10



  back:
    live:
      stream_name: back
    best_image_timeout: 60
    rtmp:
      enabled: False
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-copy   
      inputs:
        - path: rtsp://192.168.1.184:8554/back_sub?video=copy
          input_args: preset-rtsp-restream 
          roles:
            - detect
        - path: rtsp://192.168.1.184:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream 

          roles:
            - record


    detect:
      enabled: true
      width: 896
      height: 512
      fps: 4
    objects:
      track:
        - person
        - dog
        - cat 
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10


  office:
    live:
      stream_name: office
    best_image_timeout: 60
    rtmp:
      enabled: False
      
    ffmpeg:    
      output_args: 
        record: preset-record-generic-audio-copy   

      inputs:
        - path: rtsp://192.168.1.184:8554/office_sub?video=copy
          input_args: preset-rtsp-restream 
          roles:
            - detect
        - path: rtsp://192.168.1.184:8554/office?video=copy&audio=aac
          input_args: preset-rtsp-restream 
          roles:
            - record


    detect:
      enabled: true
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10

  kitchen:
    live:
      stream_name: kitchen
    best_image_timeout: 60
    rtmp:
      enabled: False
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-copy   
      inputs:
        - path: rtsp://192.168.1.184:8554/kitchen_sub?video=copy
          input_args: preset-rtsp-restream 
          roles:
            - detect
        - path: rtsp://192.168.1.184:8554/kitchen?video=copy&audio=aac
          input_args: preset-rtsp-restream 

          roles:
            - record


    detect:
      enabled: true
      width: 640
      height: 360
      fps: 1
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10


 

  livingroom:
    live:
      stream_name: livingroom
    best_image_timeout: 60
    rtmp:
      enabled: False

    ffmpeg:

      output_args: 
        record: preset-record-generic-audio-copy   
      inputs:
        - path:  rtsp://192.168.1.184:8554/livingroom_sub?video=copy
          input_args: preset-rtsp-restream 
          #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
          roles:
            - detect
            
        - path:  rtsp://192.168.1.184:8554/livingroom?video=copy&audio=aac
          input_args: preset-rtsp-restream 

         # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
          roles:
            - record



    detect:
      enabled: true
      width: 896
      height: 512
      fps: 4
    objects:
      track:
        - person

    record:
      enabled: true
      retain:
        days: 1
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects        
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
```

### Relevant log output

```shell
2023-05-02 14:28:27.052942056  [INFO] Starting Frigate...
2023-05-02 14:28:28.561451776  [2023-05-02 14:28:28] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-02 14:28:28.639520088  [2023-05-02 14:28:28] peewee_migrate                 INFO    : Starting migrations
2023-05-02 14:28:28.644038824  [2023-05-02 14:28:28] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-02 14:28:28.663064737  [2023-05-02 14:28:28] detector.coral1                INFO    : Starting detection process: 288
2023-05-02 14:28:28.669454684  [2023-05-02 14:28:28] frigate.app                    INFO    : Output process started: 293
2023-05-02 14:28:28.676807684  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for patio: 300
2023-05-02 14:28:28.681549658  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for deck: 303
2023-05-02 14:28:28.689363092  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for front: 304
2023-05-02 14:28:28.692709882  [2023-05-02 14:28:28] detector.coral2                INFO    : Starting detection process: 290
2023-05-02 14:28:28.692713887  [2023-05-02 14:28:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2023-05-02 14:28:28.696688177  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for shed: 319
2023-05-02 14:28:28.701448732  [2023-05-02 14:28:28] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-02 14:28:28.702108265  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for back: 320
2023-05-02 14:28:28.709664889  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for office: 322
2023-05-02 14:28:28.714813394  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for kitchen: 324
2023-05-02 14:28:28.719882449  [2023-05-02 14:28:28] frigate.app                    INFO    : Camera processor started for livingroom: 325
2023-05-02 14:28:28.724677514  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for patio: 327
2023-05-02 14:28:28.729684227  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for deck: 330
2023-05-02 14:28:28.734726016  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for front: 332
2023-05-02 14:28:28.739863893  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for shed: 337
2023-05-02 14:28:28.748719162  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for back: 340
2023-05-02 14:28:28.755695992  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for office: 351
2023-05-02 14:28:28.765427610  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for kitchen: 364
2023-05-02 14:28:28.770800123  [2023-05-02 14:28:28] frigate.app                    INFO    : Capture process started for livingroom: 368
2023-05-02 14:28:31.305841093  [2023-05-02 14:28:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-02 14:28:31.311003070  [2023-05-02 14:28:31] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-02 14:28:31.818342788  [2023-05-02 14:28:31] frigate.video                  ERROR   : patio: Unable to read frames from ffmpeg process.
2023-05-02 14:28:31.818902978  [2023-05-02 14:28:31] frigate.video                  ERROR   : patio: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":352,"width":640}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

reolink rlc-410w

### Any other information that may be helpful

none
