### ISSUE TITLE
[Support]: Some events are fast forward

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#6355]
### Describe the problem you are having

Hey
I recently saw have some events with fast forward 
For example 1:30 minute event finished after 3 sec. I aware to fast forward choice and the video always 1X

If I go to different event from same camera everything will be normal

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.187
  user: "mqttuser"
  password: "***"

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 15
  mode: objects

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

go2rtc:
  streams:
    LivingRoom:
      - rtsp://admin:***@192.168.1.103:8554/Streaming/Channels/101
      - "ffmpeg:LivingRoom#audio=opus"
    LivingRoom_sub:
      - rtsp://admin:***@192.168.1.103:8554/Streaming/Channels/102
cameras:
LivingRoom:
   ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
          - path:  rtsp://127.0.0.1:8554/LivingRoom_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
          - path: rtsp://127.0.0.1:8554/LivingRoom?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
   detect:
     width: 1920
     height: 1080
     fps: 5
   rtmp:
     enabled: false

   objects:
     track:
       - person
       - dog
     filters:
       person:
         threshold: 0.70
       dog:
         threshold: 0.70

   snapshots:
     enabled: true
     timestamp: false
     bounding_box: false
     crop: False
     height: 900
     retain:
       default: 14

   record:
     enabled: true
     retain:
       days: 4
     events:
       pre_capture: 30
       post_capture: 30
       objects:
         - person
       retain:
         default: 14
   motion:
     mask:
       - 1221,174,1512,327,1591,99,1316,0,1290,0,1260,0
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

amcrest
