### ISSUE TITLE
[Support]: unable to access streams in google home app via Hass

### ISSUE THREAD

**Issue by tungmeister** [blakeblackshear/frigate#6368]
### Describe the problem you are having

I'm trying to access my camera streams via the google home app - I have Frigate running in docker on Unraid connected to home assistant using the integration and then the cameras exposed to google. I can see the preview of the streams in the google home app when on my local network but they won't play and when remote I don't get the previews at all. Not sure if this is go2rtc issue or where the problem lies. I've tried opening 8555 to the docker container but this has made no difference. 
I also have the rtsptowebrtc integration setup in hass pointing at go2rtc on the frigate docker container (without this i don't  even get the local previews)
Any help anyone could give would be appreciated!

### Version

12

### Frigate config file

```yaml
go2rtc:
  streams:
    Drive: 
      - ffmpeg:rtsp://admin:l0caladm1n@10.0.0.110:554/Streaming/Channels/101/
      - "ffmpeg:Drive#audio=opus"
    Drive_Left: 
      - rtsp://admin:xxxx@10.0.0.100:554/Streaming/Channels/101/
      - "ffmpeg:Drive_Left#audio=opus"
    Garden: 
      - rtsp://admin:xxxx@10.0.0.222:554/Streaming/Channels/101/
      - "ffmpeg:Garden#audio=opus"
  webrtc:
    candidates:
      - 10.0.0.10:8555
      - stun:8555
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

N/A
