### ISSUE TITLE
[Support]: webrtc slow to load/sometimes doesnt load

### ISSUE THREAD

**Issue by kirsch33** [blakeblackshear/frigate#6369]
### Describe the problem you are having

i want webrtc to be the default/only configured stream from my cameras. i *think* i have everything setup correctly (and indeed around 50% of the time, webrtc loads and plays just fine) but the frigate-hass-card seem to display the jsmpeg stream for some time until webrtc 'kicks in'. the native Frigate web server sometimes will load webrtc, jsmpeg is pretty much instant and even MSE is pretty quick. 

here is my frigate config:
```yaml
mqtt:
  host: HASS_HOST_IP
  port: 1883
  user: homeassistant
  password: pass

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /trt-models/yolov7x-640.trt
  width: 640
  height: 640
  input_tensor: nchw
  input_pixel_format: rgb

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    back: 
      - rtsp://user:pass@CAM_BACK_IP:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:back#audio=opus"
    front: 
      - rtsp://user:pass@CAM_FRONT_IP:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front#audio=opus"
  webrtc:
    candidates:
      - FRIGATE_HOST_IP:8555
      - stun:8555

cameras:
  back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://FRIGATE_HOST_IP:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    best_image_timeout: 1800
    zones:
      back_yard:
        coordinates: 0,1080,1117,1080,1349,925,1699,601,1656,484,1730,384,1381,218,1455,157,883,0,747,0,533,56,225,161,0,295
        objects:
          - person
    mqtt:
      required_zones:
        - back_yard

  front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://FRIGATE_HOST_IP:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      filters:
        car:
          mask:
            - 395,144,671,62,959,0,0,0,0,356,173,247
            - 1293,152,1648,243,1920,355,1920,0,1584,0,1358,47,1077,119
            - 0,1080,1920,1080,1920,612,1420,416,1136,322,906,265,737,241,511,341,258,477,0,647
    best_image_timeout: 1800
    zones:
      front_yard:
        coordinates: 0,1080,1339,1080,1553,875,1792,444,1844,179,1426,90,1178,166,872,291,438,513,0,824
        objects:
          - person
      front_driveway:
        coordinates: 1148,150,1012,133,692,247,929,262,1063,294,1266,177
        objects:
          - car
    mqtt:
      required_zones:
        - front_yard
        - front_driveway

birdseye:
  enabled: True
  width: 1920
  height: 1080
  mode: continuous

record:
  enabled: True
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    required_zones:
      - back_yard
      - front_yard
      - front_driveway

snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 45

objects:
  track:
    - person
    - car
  filters:
    person:
      max_area: 80000
      min_score: 0.50
      threshold: 0.65
    car:
      max_area: 120000
      min_score: 0.50
      threshold: 0.65
    dog:
      min_score: 0.50
      threshold: 0.65

detect:
  width: 1920
  height: 1080
  fps: 5
  max_disappeared: 25
  stationary:
    threshold: 50

motion:
  contour_area: 100

ui:
  live_mode: webrtc
  use_experimental: false

live:
  height: 1080
```

i run Frigate thru DOcker, and here is my docker-compose.yml

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    network_mode: host
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-tensorrt
    runtime: nvidia
    shm_size: "100mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/docks/frigate/config.yml:/config/config.yml
      - /var/docks/frigate/tensorrt_models:/trt-models
      - /nvr:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment: 
      - PLUS_API_KEY=key
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```

im not sure really where to start in tracking this down. is it a frigate issue, go2rtc issue, or network issue on my end?

### Version

12

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Amcrest
