### ISSUE TITLE
[Support]: WebRTC feed fails to load

### ISSUE THREAD

**Issue by Coder84619** [blakeblackshear/frigate#6371]
### Describe the problem you are having

The webRTC feed in the Frigate console never loads. MSE and jsmpeg are almost instant. Frigate is a Docker container on an Ubuntu 22.04 VM, on Proxmox 7.4. I changed camera iframe interval from 4x FPS to 1x FPS and it didn't help. Going into the RTC console doesn't want to stream the feed either. 

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# ~/docker/frigate/config.yml

ui:
  use_experimental: false
  live_mode: mse

record:
  expire_interval: 10

ffmpeg:
  hwaccel_args: preset-vaapi 

detectors:
  coral:
    type: edgetpu
    device: pci

logger:
  default: info

rtmp:
  enabled: false

live:
  height: 720
  quality: 1

birdseye:
  enabled: True
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: continuous

go2rtc:
  streams:
    garage:
      - rtsp://:554/cam/realmonitor?channel=1&subtype=0
    garage_sub:
      - rtsp://:554/cam/realmonitor?channel=1&subtype=2
    webrtc:
      candidates:
        - 10.13.2.213:8555
        - stun:8555

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:                 
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.4
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 30
    record:
      enabled: True
      retain: 
        days: 45
        mode: motion
      events:
        retain:
          default: 5 
          mode: motion 
        pre_capture: 10
        post_capture: 30
```

### Relevant log output

```shell
No errors in any GUI accessible logs.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1520,"width":2688}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

IPC-T5442T-ZE
