### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by TheEmpty** [blakeblackshear/frigate#6415]
### Describe the problem you are having

My "Garage" and "Kitchen" cameras recordings are not viewable on the UI. 

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: hostremoved
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: public
  stats_interval: 60
detectors:
   coral:
     type: edgetpu
     device: usb
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
objects:
  track:
    - cat
    - dog
    # outside
    # - bear
    # - person
    # - bicycle
    # - car
    # - motorcycle
    # - bus
snapshots:
  enabled: True
  crop: True
record:
  enabled: True
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 3
cameras:
  bedroom:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        # lower res
        - path: rtsp://admin:passwordremoved@hostremoved:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # high res
        - path: rtsp://admin:passwordremoved@hostremoved:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
    detect:
      width: 2560
      height: 1440
      fps: 10
  garage:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        # lower res
        - path: rtsp://admin:passwordremoved@hostremoved:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # high res
        - path: rtsp://admin:passwordremoved@hostremoved:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
    detect:
      width: 2560
      height: 1440
      fps: 10
  kitchen:
    birdseye:
      mode: objects
    ffmpeg:
      inputs:
        # lower res
        - path: rtsp://admin:passwordremoved@hostremoved:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # high res
        - path: rtsp://admin:passwordremoved@hostremoved:544/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
    detect:
      width: 2560
      height: 1440
      fps: 10
```

### Relevant log output

```shell
$ docker-compose logs -f frigate | grep garage
frigate                 | [2023-03-30 05:18:45] frigate.app                    INFO    : Camera processor started for garage: 225
frigate                 | [2023-03-30 05:18:45] frigate.app                    INFO    : Capture process started for garage: 230
frigate                 | [2023-03-30 05:18:51] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
frigate                 | [2023-03-30 05:18:51] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
frigate                 | [2023-03-30 05:19:05] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
frigate                 | [2023-03-30 05:19:05] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate                 | [2023-03-30 05:19:05] ffmpeg.garage.detect           ERROR   : rtsp://admin:reomved/cam/realmonitor?channel=1&subtype=1: Invalid data found when processing input
frigate                 | [2023-03-30 05:19:10] frigate.app                    INFO    : Camera processor started for garage: 227
frigate                 | [2023-03-30 05:19:10] frigate.app                    INFO    : Capture process started for garage: 233
...
...
frigate                 | [2023-03-31 16:51:47] frigate.app                    INFO    : Camera processor started for garage: 224
frigate                 | [2023-03-31 16:51:47] frigate.app                    INFO    : Capture process started for garage: 229
frigate                 | [2023-03-31 16:52:12] frigate.app                    INFO    : Camera processor started for garage: 228
frigate                 | [2023-03-31 16:52:12] frigate.app                    INFO    : Capture process started for garage: 233
frigate                 | [2023-03-31 16:52:38] frigate.app                    INFO    : Camera processor started for garage: 225
frigate                 | [2023-03-31 16:52:38] frigate.app                    INFO    : Capture process started for garage: 231
frigate                 | [2023-03-31 16:53:03] frigate.app                    INFO    : Camera processor started for garage: 226
frigate                 | [2023-03-31 16:53:03] frigate.app                    INFO    : Capture process started for garage: 232
frigate                 | [2023-03-31 16:53:28] frigate.app                    INFO    : Camera processor started for garage: 226
frigate                 | [2023-03-31 16:53:28] frigate.app                    INFO    : Capture process started for garage: 232
frigate                 | [2023-03-31 16:53:54] frigate.app                    INFO    : Camera processor started for garage: 225
frigate                 | [2023-03-31 16:53:54] frigate.app                    INFO    : Capture process started for garage: 230
frigate                 | [2023-03-31 16:54:20] frigate.app                    INFO    : Camera processor started for garage: 219
frigate                 | [2023-03-31 16:54:20] frigate.app                    INFO    : Capture process started for garage: 227
frigate                 | [2023-03-31 16:54:45] frigate.app                    INFO    : Camera processor started for garage: 223
frigate                 | [2023-03-31 16:54:45] frigate.app                    INFO    : Capture process started for garage: 227
frigate                 | [2023-03-31 16:55:11] frigate.app                    INFO    : Camera processor started for garage: 225
frigate                 | [2023-03-31 16:55:11] frigate.app                    INFO    : Capture process started for garage: 229
frigate                 | [2023-03-31 16:55:36] frigate.app                    INFO    : Camera processor started for garage: 223
frigate                 | [2023-03-31 16:55:36] frigate.app                    INFO    : Capture process started for garage: 231
frigate                 | [2023-03-31 16:56:01] frigate.app                    INFO    : Camera processor started for garage: 226
frigate                 | [2023-03-31 16:56:01] frigate.app                    INFO    : Capture process started for garage: 230
frigate                 | [2023-03-31 16:56:27] frigate.app                    INFO    : Camera processor started for garage: 227
frigate                 | [2023-03-31 16:56:27] frigate.app                    INFO    : Capture process started for garage: 232
frigate                 | [2023-03-31 16:56:52] frigate.app                    INFO    : Camera processor started for garage: 224
frigate                 | [2023-03-31 16:56:52] frigate.app   
...
                 
some interesting ones filtered on error,

frigate                 | [2023-05-06 20:21:45] ffmpeg.garage.record_rtmp      ERROR   : 
frigate                 | [2023-05-06 20:21:55] ffmpeg.garage.record_rtmp      ERROR   : [rtsp @ 0x55f21ad46e40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate                 | [2023-05-06 20:21:55] ffmpeg.garage.record_rtmp      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
frigate                 | [2023-05-06 20:21:55] ffmpeg.garage.record_rtmp      ERROR   : [flv @ 0x55f21ad62b00] dimensions not set
frigate                 | [2023-05-06 20:21:55] ffmpeg.garage.record_rtmp      ERROR   : Could not write header for output file #1 (incorrect codec parameters ?): Invalid argument
frigate                 | [2023-05-06 20:21:55] ffmpeg.garage.record_rtmp      ERROR   : Error initializing output stream 1:1 -- 
frigate                 | [2023-05-06 20:21:55] ffmpeg.garage.record_rtmp      ERROR   : 
frigate                 | [2023-05-06 20:22:15] ffmpeg.garage.record_rtmp      ERROR   : [rtsp @ 0x563b9d2c1e40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate                 | [2023-05-06 20:22:15] ffmpeg.garage.record_rtmp      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

...

frigate                 | [2023-05-06 02:14:14] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
frigate                 | [2023-05-06 02:14:14] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
frigate                 | [2023-05-06 02:14:14] ffmpeg.garage.record_rtmp      ERROR   : [aac @ 0x55da48c696c0] Queue input is backward in time
frigate                 | [2023-05-06 02:14:14] ffmpeg.garage.record_rtmp      ERROR   :     Last message repeated 2 times
frigate                 | [2023-05-06 02:14:14] ffmpeg.garage.record_rtmp      ERROR   : [segment @ 0x55da48c68000] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate                 | [2023-05-06 02:14:14] ffmpeg.garage.record_rtmp      ERROR   : [flv @ 0x55da48c65a80] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```

### Frigate stats

```json
{
  "bedroom": {
    "camera_fps": 10.1,
    "capture_pid": 229,
    "detection_fps": 10,
    "pid": 222,
    "process_fps": 10.1,
    "skipped_fps": 0
  },
  "detection_fps": 10,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 7.8,
      "pid": 266215
    }
  },
  "garage": {
    "camera_fps": 7.9,
    "capture_pid": 230,
    "detection_fps": 0,
    "pid": 225,
    "process_fps": 7.9,
    "skipped_fps": 0
  },
  "kitchen": {
    "camera_fps": 10.1,
    "capture_pid": 232,
    "detection_fps": 0,
    "pid": 228,
    "process_fps": 10.1,
    "skipped_fps": 0
  },
  "service": {
    "latest_version": "0.12.0",
    "storage": {
      "/dev/shm": {
        "free": 221.3,
        "mount_type": "tmpfs",
        "total": 256,
        "used": 34.7
      },
      "/media/frigate/clips": {
        "free": 415645.4,
        "mount_type": "ext4",
        "total": 527295.6,
        "used": 84789.8
      },
      "/media/frigate/recordings": {
        "free": 415645.4,
        "mount_type": "ext4",
        "total": 527295.6,
        "used": 84789.8
      },
      "/tmp/cache": {
        "free": 994.1,
        "mount_type": "tmpfs",
        "total": 1000,
        "used": 5.9
      }
    },
    "temperatures": {},
    "uptime": 1135733,
    "version": "0.11.1-2eada21"
  }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I see detection_fps is 0 for garage and kitchen cameras. I'm not sure why though since CPU still has headroom and from my understanding coral should be able to handle more than 1 camera. I'm on `blakeblackshear/frigate:stable`, UI stating `0.11.1-2eada21`

all three are the same camera model: https://www.amazon.com/gp/product/B095XCGKTF/
