### ISSUE TITLE
[Support]: new release for go2rtc 1.5.0

### ISSUE THREAD

**Issue by prometheanfire** [blakeblackshear/frigate#6417]
### Describe the problem you are having

I have a camera that's accessible via https with a self signed cert, unfortunately the bundled go2rtc does not support the httpx protocol just added in gortc-1.5.0 https://github.com/AlexxIT/go2rtc/issues/343

Is there a chance we can get a release?

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: "mosquitto.home-assistant.svc"
  port: 1883
  user: mqtt
  password: ""
go2rtc:
  streams:
    reolink:
      - httpx://1.2.3.4/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=lolnope&password=lolnope
      - "ffmpeg:reolink#audio=opus"
    reolink_sub:
      - httpx://1.2.3.4/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=lolnope&password=lolnope

cameras:
  # Define at least one camera
  back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: False
      width: 2560
      height: 1920
```

### Relevant log output

```shell
│ 2023-05-07 03:25:16.731736921  03:25:16.731 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: httpx://1.2.3.4/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=lolnope&password=lolnope │
│ 2023-05-07 03:25:16.731751606  03:25:16.731 WRN [rtsp] error="source 0 error: unsupported scheme: httpx://1.2.3.4/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=lolnope&password=lolnope" stream=reolink_sub         │
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell PoE - DB_566128M5MP_P
