### ISSUE TITLE
Masks don't appear to work in 8.0

### ISSUE THREAD

**Issue by mattheys** [blakeblackshear/frigate#643]
I upgraded to 8.0 final from RC3 yesterday and I've had a lot of notifications for areas that should be masked off.

This is my config

```
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.90:8554/garage
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    motion:
       mask: 0,0,0,1080,444,1080,864,274,870,180,1050,190,1135,255,1132,292,1496,840,1707,1079,1920,1080,1920,0
    fps: 5
    snapshots:
      timestamp: False
      bounding_box: True
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
    rtmp:
      enabled: True
```

This is what was detected
![image](https://user-images.githubusercontent.com/10292436/106125128-ad251300-6153-11eb-91ef-f15ea009412e.png)

And this should be my mask
![image](https://user-images.githubusercontent.com/10292436/106125248-d5147680-6153-11eb-841e-bc4194cd7aec.png)
