### ISSUE TITLE
[Support]: Homeassistant Object camera resolution

### ISSUE THREAD

**Issue by Nornode** [blakeblackshear/frigate#6434]
### Describe the problem you are having

For the dedicated (entities) object cameras it looks like the resolution is limited or degraded from the detected stream.

How do I improve(increase) the resolution of the detected objects so they are stored in the home-assistant dedicated cameras?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.CC.RR

objects:
  track:
   - person
   - car
   - bicycle
   - cat
   - dog

snapshots:
  enabled: True
  bounding_box: True
  crop: False
  retain:
    default: 10
    objects:
      person: 20
      car: 20

timestamp_style:
  position: "bl"
  effect: shadow

record:
  enabled: True
  retain:
    days: 3
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    retain:
      default: 10
      mode: active_objects
      objects:
        person: 20

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false
  mode: continuous


ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner 
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  # hwaccel_args: preset-rpi-64-h264

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: http://192.168.XX.YY:8080
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - "1"
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c libx264 -an
        rtmp: -c libx264 -an -f flv
    detect:
      fps: 5
      stationary:
        interval: 10
  
  
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.WW.AA:554/h264?username=abc&password=123
          roles:
            - detect
            - rtmp
            - record
    live:
      height: 1080
    motion:
      mask:
      - 250,299,50,399,0,240,0,98,143,0,1183,0,1177,121,800,144,725,154,429,234
    objects:
      mask:
        - 97,386,32,99,183,0,1183,0,1177,121,725,154,429,234
        - 1344,378,1440,599,1536,970,1710,577,1764,244,1523,82,1359,28
    zones:
      entrance:
        coordinates: 1307,681,1374,1080,411,1080,307,922,510,669
      frontyard:
        coordinates: 451,658,296,903,181,706,120,585,70,456,245,337,430,243,657,187,1192,163,1210,372,1239,375,1247,653
      garage-door:
        coordinates: 1340,377,1349,22,1525,84,1801,258,1719,662,1580,1009,1532,1080,1467,1080,1300,387
      garbage:
        coordinates: 1261,24,1257,147,1187,155,1184,24
      driveway-boarder:
        coordinates: 730,163,655,186,1183,159,1175,136
    detect:
      width: 1920
      height: 1080
      fps: 5
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Ampviz - MC400L-Y-EN-L_AF_V0_BU_Y_EN-DH-H5_L V2.3.15 

### Any other information that may be helpful

Homeassistant Integration version:
4.0.0/0.12.0-da3e197 - Installed through HACS
