### ISSUE TITLE
[HW Accel Support]: Missing libnvidia-ml.so

### ISSUE THREAD

**Issue by royaltongue** [blakeblackshear/frigate#6446]
### Describe the problem you are having

Hi again,

I have my NVIDIA GTX 1080 set up and configured properly, and it is recognized in other Docker Containers, like Plex. Regardless, I completely removed all NVIDIA packages using `apt-get purge *nvidia*`, `apt autoremove`, and `apt autoclean`, rebooted, then followed the [installation instructions for CUDA from NVIDIA's website](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/) and [some additional setup from the OMV forum](https://forum.openmediavault.org/index.php?thread/38013-howto-nvidia-hardware-transcoding-on-omv-5-in-a-plex-docker-container/&postID=313378#post313378_)

Even after all of this, `nvidia-smi` throws the error `NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.` when run within the Frigate container. 
When run from the host system, or from within the Plex container, this is returned:
```
Mon May  8 19:09:57 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080         Off| 00000000:01:00.0 Off |                  N/A |
| 30%   44C    P0               36W / 180W|      0MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

I also read about changing ldconfig, but I already had the recommended settings. Here is my nvidia-container-run config.toml either way:
```
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"
accept-nvidia-visible-devices-envvar-when-unprivileged = true
#accept-nvidia-visible-devices-as-volume-mounts = false

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-toolkit.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
#user = "root:video"
ldconfig = "/sbin/ldconfig.real"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
log-level = "info"

# Specify the runtimes to consider. This list is processed in order and the PATH
# searched for matching executables unless the entry is an absolute path.
runtimes = [
    "docker-runc",
    "runc",
]
```

Also, here is the output of `sudo dpkg -l | grep nvidia`:
```
ii  glx-alternative-nvidia                1.2.1~deb11u1                  amd64        allows the selection of NVIDIA as GLX provider
ii  libegl-nvidia0:amd64                  530.30.02-1                    amd64        NVIDIA binary EGL library
ii  libgl1-nvidia-glvnd-glx:amd64         530.30.02-1                    amd64        NVIDIA binary OpenGL/GLX library (GLVND variant)
ii  libglx-nvidia0:amd64                  530.30.02-1                    amd64        NVIDIA binary GLX library
ii  libnvidia-allocator1:amd64            530.30.02-1                    amd64        NVIDIA allocator runtime library
ii  libnvidia-compiler:amd64              530.30.02-1                    amd64        NVIDIA runtime compiler library
ii  libnvidia-container-tools             1.13.1-1                       amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64            1.13.1-1                       amd64        NVIDIA container runtime library
ii  libnvidia-eglcore:amd64               530.30.02-1                    amd64        NVIDIA binary EGL core libraries
ii  libnvidia-encode1:amd64               530.30.02-1                    amd64        NVENC Video Encoding runtime library
ii  libnvidia-fbc1:amd64                  530.30.02-1                    amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-glcore:amd64                530.30.02-1                    amd64        NVIDIA binary OpenGL/GLX core libraries
ii  libnvidia-ml1:amd64                   530.30.02-1                    amd64        NVIDIA Management Library (NVML) runtime library
ii  libnvidia-nvvm4:amd64                 530.30.02-1                    amd64        NVIDIA NVVM
ii  libnvidia-opticalflow1:amd64          530.30.02-1                    amd64        NVIDIA Optical Flow runtime library
ii  libnvidia-ptxjitcompiler1:amd64       530.30.02-1                    amd64        NVIDIA PTX JIT Compiler
ii  nvidia-alternative                    530.30.02-1                    amd64        allows the selection of NVIDIA as GLX provider
ii  nvidia-container-runtime              3.13.0-1                       all          NVIDIA container runtime
ii  nvidia-container-toolkit              1.13.1-1                       amd64        NVIDIA Container toolkit
ii  nvidia-container-toolkit-base         1.13.1-1                       amd64        NVIDIA Container Toolkit Base
ii  nvidia-cuda-mps                       530.30.02-1                    amd64        NVIDIA CUDA Multi Process Service (MPS)
ii  nvidia-detect                         530.30.02-1                    amd64        NVIDIA GPU detection utility
ii  nvidia-docker2                        2.13.0-1                       all          nvidia-docker CLI wrapper
ii  nvidia-driver                         530.30.02-1                    amd64        NVIDIA metapackage
ii  nvidia-driver-bin                     530.30.02-1                    amd64        NVIDIA driver support binaries
ii  nvidia-driver-libs:amd64              530.30.02-1                    amd64        NVIDIA metapackage (OpenGL/GLX/EGL/GLES libraries)
ii  nvidia-egl-common                     530.30.02-1                    amd64        NVIDIA binary EGL driver - common files
ii  nvidia-egl-icd:amd64                  530.30.02-1                    amd64        NVIDIA EGL installable client driver (ICD)
ii  nvidia-installer-cleanup              20151021+13                    amd64        cleanup after driver installation with the nvidia-installer
ii  nvidia-kernel-common                  20151021+13                    amd64        NVIDIA binary kernel module support files
ii  nvidia-kernel-dkms                    530.30.02-1                    amd64        NVIDIA binary kernel module DKMS source
ii  nvidia-kernel-support                 530.30.02-1                    amd64        NVIDIA binary kernel module support files
ii  nvidia-legacy-check                   530.30.02-1                    amd64        check for NVIDIA GPUs requiring a legacy driver
ii  nvidia-libopencl1:amd64               530.30.02-1                    amd64        NVIDIA OpenCL ICD Loader library
ii  nvidia-modprobe                       530.30.02-1                    amd64        utility to load NVIDIA kernel modules and create device nodes
ii  nvidia-opencl-common                  530.30.02-1                    amd64        NVIDIA OpenCL driver - common files
ii  nvidia-opencl-icd:amd64               530.30.02-1                    amd64        NVIDIA OpenCL installable client driver (ICD)
ii  nvidia-settings                       530.30.02-1                    amd64        tool for configuring the NVIDIA graphics driver
ii  nvidia-smi                            530.30.02-1                    amd64        NVIDIA System Management Interfaceii  nvidia-support                        20151021+13                    amd64        NVIDIA binary graphics driver support files
ii  nvidia-vdpau-driver:amd64             530.30.02-1                    amd64        Video Decode and Presentation API for Unix - NVIDIA driver
ii  nvidia-xconfig                        530.30.02-1                    amd64        deprecated X configuration tool for non-free NVIDIA drivers
ii  xserver-xorg-video-nvidia             530.30.02-1                    amd64        NVIDIA binary Xorg driver
```

I'm not positive that I did the ffprobe command properly, please let me know if it isn't right

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
go2rtc:
  front_camera:
      - http://192.168.1.253/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=[redacted]
      - "ffmpeg:reolink#audio=opus"
  back_camera:
      - http://192.168.1.254/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=[redacted]
      - "ffmpeg:reolink#audio=opus"

cameras:
  front_camera:
    ffmpeg:
      inputs:
         - path: rtsp://192.168.1.24:8554/front_camera?video=copy&audio=aac
           input_args: preset-rtsp-restream
  back_camera:
      ffmpeg:
        inputs:
          - path: rtsp://192.168.1.24:8554/back_camera?video=copy&audio=aac
            input_args: preset-rtsp-restream

logger:
  default: info
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    shm_size: "256mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${dcs}/frigate/config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    restart: unless-stopped
```

### Relevant log output

```
2023-05-08 19:09:59.642013862  [2023-05-08 19:09:59] frigate.util                   ERROR   : Unable to poll nvidia GPU stats: 
2023-05-08 19:10:11.212163049  [2023-05-08 19:10:11] watchdog.back_camera           ERROR   : Ffmpeg process crashed unexpectedly for back_camera.
```

### FFprobe output from your camera

```shell
root@6fd5c822e9f1:/opt/frigate# ffprobe http://192.168.1.253/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=[redacted]
[1] 1894
[2] 1895
[3] 1896
[4] 1897
[2]   Done                    app=bcs
root@6fd5c822e9f1:/opt/frigate# ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[http @ 0x55b115300a80] HTTP error 500 Internal Server Error
http://192.168.1.253/flv?port=1935: Server returned 5XX Server Error reply
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC-520

### Any other information that may be helpful

OS is OpenMediaVault 6.3.8-1 (Shaitan) with kernel `Linux 5.19.0-0.deb11.2-amd64`

**Comment by NickM-27** [comment]
Maybe try adding the libnvidia-ml.so to the docker compose volumes mapping. In any case, this seems to be an issue isolated to something specific as many users on the 10 series haven't run into this issue.

**Comment by royaltongue** [comment]
With a bit of digging, I was able to come across [this comment on the nvidia-docker issue tracker](https://github.com/NVIDIA/nvidia-docker/issues/107#issuecomment-351688990), which explains how to specify the file location for these `.so` files. Once I confirmed they were there, I added `/usr/lib/x86_64-linux-gnu/` to `/etc/ld.so.conf.d/nvidia.conf`, and mapped it in my stack to make it permanent,

After re-upping Frigate, I accessed the shell and ran `ldconfig`. After that, `nvidia-smi` returned successfully

**Comment by royaltongue** [comment]
Just in case anyone else runs into this issue:

My frigate.yml:
```
version: '3.8'
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    shm_size: "256mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${dcs}/frigate/config:/config
      - ${dcs}/frigate/etc/ld.so.conf.d:/etc/ld.so.conf.d
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    restart: unless-stopped
```

The contents of `/etc/ld.so.conf.d/nvidia.conf`:
```
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
```

My Frigate config:
```
mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000

go2rtc:
    streams:
        front_camera: http://192.168.1.253/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=[redacted]
        back_camera: http://192.168.1.254/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=[redacted]
    webrtc:
      candidates:
        - 192.168.1.24:8555
        - stun:8555
      
cameras:
  front_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_camera
          input_args: preset-rtsp-generic
  back_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_camera
          input_args: preset-rtsp-generic
```

And to confirm that Frigate is using the GPU, running `nvidia-smi` on the host machine shows one ffmpeg process per camera:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080         Off| 00000000:01:00.0 Off |                  N/A |
| 37%   54C    P2               41W / 180W|    330MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   1663312      C   ffmpeg                                      164MiB |
|    0   N/A  N/A   1663315      C   ffmpeg                                      164MiB |
+---------------------------------------------------------------------------------------+
```
