### ISSUE TITLE
[HW Accel Support]: preset-vaapi not working on Ubuntu 22.04 with Raptor Lake

### ISSUE THREAD

**Issue by lifeandfate1** [blakeblackshear/frigate#6448]
### Describe the problem you are having

I have a Intel NUC Pro 13 bare metal Ubuntu Server 22.04 host running Frigate. When using preset-vaapi on a Raptor Lake i5-1340P, I have no feed and am getting ffmpeg errors. I've tested without ffmpeg and the feed works without issue.

I have updated the intel drivers on the host and am currently running 23.1.4-601

https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-legacy.html#step-1-add-package-repository

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: ####
  user: mqtt
  password: ####

database:
  path: /db/frigate.db

snapshots:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    driveway: 
      - rtsp://####:####@####:8554/h264Preview_01_main#input=rtsp/udp
      - "ffmpeg:driveway#audio=opus"
    driveway_sub: 
      - rtsp://####:####@####:8554/h264Preview_01_sub#input=rtsp/udp
      - "ffmpeg:driveway_sub#audio=opus"
    #doorbell: 
    #  - rtsp://####:####@####:8554/h264Preview_01_main#input=rtsp/udp
    #  - "ffmpeg:doorbell#audio=opus"
    #doorbell_sub: 
    #  - rtsp://####:####@####:8554/h264Preview_01_sub#input=rtsp/udp
    #  - "ffmpeg:doorbell_sub#audio=opus"
  webrtc:
    candidates:
      - ####:8555

cameras:
  Driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 7
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
    zones:
      driveway_zone:
        coordinates: 0,243,0,512,828,512,896,254,632,189,493,156,343,124,233,100,179,84,30,142,44,170
    motion:
      mask:
        - 0,0,73,0,67,131,0,146
        - 437,0,608,39,646,40,628,167,515,140,348,110,296,109,229,91,181,65
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
  #Doorbell:
  #  ffmpeg:
  #    output_args:
  #      record: preset-record-generic-audio-copy
  #    inputs:
  #      - path: rtsp://127.0.0.1:8554/doorbell
  #        input_args: preset-rtsp-restream-low-latency
  #        roles:
  #          - record
  #      - path: rtsp://127.0.0.1:8554/doorbell_sub
  #        input_args: preset-rtsp-restream-low-latency
  #        roles:
  #          - detect
  #  detect:
  #    width: 896
  #    height: 512
  #    fps: 7
  #  record:
  #    enabled: True
  #    retain:
  #      days: 5
  #      mode: motion
  #    events:
  #      retain:
  #        default: 10
  #        mode: active_objects
  #  objects:
  #    track:
  #      - person
  #  mqtt:
  #    timestamp: False
  #    bounding_box: False
  #    crop: True
  #    quality: 100
  #    height: 1000
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: "frigate"
    hostname: "frigate"
    restart: "unless-stopped"
    image: "ghcr.io/blakeblackshear/frigate:stable"
    depends_on:
       - mosquitto-mqtt
    shm_size: "96mb"
    privileged: true
  #  cap_add:
  #    - CAP_PERFMON
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
      - "/dev/dri:/dev/dri"
      - "/dev/dri/card0:/dev/dri/card0"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/appdata/frigate/config/config.yml:/config/config.yml"
      - "/appdata/frigate/db:/db"
      - "/mnt/recordings:/media/frigate"
    tmpfs:
      - "/tmp/cache:exec,size=1G"
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984/udp" # go2rtc api
    env_file:
      - frigate.env
    labels:
      homepage.group: "Home Control"
      homepage.name: "Frigate"
      homepage.icon: "frigate-light.png"
      homepage.href: "https://####"
      homepage.description: "Local NVR" 
      traefik.enable: "true"
      traefik.http.routers.frigate.entrypoints: "http"
      traefik.http.routers.frigate.rule: "Host(`####`)"
      traefik.http.middlewares.frigate-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.frigate.middlewares: "frigate-https-redirect"
      traefik.http.routers.frigate-secure.entrypoints: "https"
      traefik.http.routers.frigate-secure.rule: "Host(`####`)"
      traefik.http.routers.frigate-secure.tls: "true"
      traefik.http.routers.frigate-secure.service: "frigate"
      traefik.http.services.frigate.loadbalancer.server.port: "5000"
      traefik.docker.network: "docker"
```

### Relevant log output

```shell
2023-05-09 00:44:49.424652491  [2023-05-09 00:44:49] watchdog.Driveway              ERROR   : Ffmpeg process crashed unexpectedly for Driveway.
2023-05-09 00:44:49.424668786  [2023-05-09 00:44:49] watchdog.Driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-09 00:44:49.424690480  [2023-05-09 00:44:49] ffmpeg.Driveway.detect         ERROR   : [AVHWDeviceContext @ 0x55a486abf1c0] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
2023-05-09 00:44:49.424711346  [2023-05-09 00:44:49] ffmpeg.Driveway.detect         ERROR   : [AVHWDeviceContext @ 0x55a486abf1c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
2023-05-09 00:44:49.424735882  [2023-05-09 00:44:49] ffmpeg.Driveway.detect         ERROR   : Device creation failed: -5.
2023-05-09 00:44:49.424756941  [2023-05-09 00:44:49] ffmpeg.Driveway.detect         ERROR   : [h264 @ 0x55a486999280] No device available for decoder: device type vaapi needed for codec h264.
2023-05-09 00:44:49.424779768  [2023-05-09 00:44:49] ffmpeg.Driveway.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Input/output error
2023-05-09 00:44:54.030847449  [2023-05-09 00:44:54] frigate.video                  ERROR   : Driveway: Unable to read frames from ffmpeg process.
2023-05-09 00:44:54.030895650  [2023-05-09 00:44:54] frigate.video                  ERROR   : Driveway: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC-811A

### Any other information that may be helpful

I've looked through issue [6365](https://github.com/blakeblackshear/frigate/issues/6365) on Adler Lake HW acceleration and which is why I upgraded the host drivers.

I have no ffmpeg issues with Jellyfin when using HW transcoding I'm only getting an issue with Frigate.
