### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by BeFygo** [blakeblackshear/frigate#6451]
### Describe the problem you are having

The folder structure for the recordings seem 2 hours off.
The event time on frigate webpage looks just fine.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
#  host: mqtt://192.168.X.X:1883
  host: 192.168.X.X
  port: 1883
  user: MQTT
  password: XXXXX
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

detectors:
  cpu1:
    type: cpu

#ffmpeg:
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p 
#  output_args:
#    record: preset-record-generic-audio-aac

go2rtc:
#  rtsp:
#    username: "XXXX"
#    password: "XXXX"
  streams:
    deurbel_main:
      - http://192.168.X.XXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXX&password=XXXXX
      - "ffmpeg:reolink#audio=opus"
    deurbel_sub:
      - http://192.168.X.XXX/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=XXXX&password=XXXXX



cameras:
  huis_voor_2:
    ffmpeg: 
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:

#http stream
        - path: http://192.168.X.XXX/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=XXX&password=XXXX
#          input_args: preset-http-reolink
          roles:
            - detect
#            - rtmp
        - path: http://192.168.X.XXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXXX
#          input_args: preset-http-reolink
          roles:
            - record


    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7

    motion:
      mask:
        - 640,0,640,151,640,210,541,151,214,0

    objects:
      track:
        - person
        - cat
        - dog

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
#      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 150


    record:
      enabled: True
      retain:
        days: 70
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 70
            cat: 70
            person: 70

  deurbel:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p 
 
      inputs:



##HTTP test

        - path: rtsp://127.0.0.1:8554/deurbel_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deurbel_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - rtmp

    live:
      stream_name: rtsp_deurbel_sub

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7

    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        - 143,218,469,223,439,260,381,273,336,304,141,313

    zones:
      aanloop:
        coordinates: 590,480,341,315,150,317,183,480
      auto_zone:
        coordinates: 420,250,573,272,534,444,314,315

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
#      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 150


    record:
      enabled: True
      retain:
        days: 70
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
          objects:
            dog: 70
            cat: 70
            person: 70
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Reolink RLC510 & doorbell

### Any other information that may be helpful

![frigate events time correct](https://user-images.githubusercontent.com/72655961/237019173-cb59af55-9159-44e5-8272-2106d250e360.JPG)
![frigate recording 2 hours off](https://user-images.githubusercontent.com/72655961/237019177-584ca7fd-8161-49ea-9ca9-7e0ac3c9b8fc.JPG)
