### ISSUE TITLE
[Detector Support]: Nvidia TensorRT Model Generation 'Stuck' - GTX 1660 Super

### ISSUE THREAD

**Issue by jtmoss3991** [blakeblackshear/frigate#6455]
### Describe the problem you are having

Hi all,

I am new to Frigate. I have an Ubuntu 22.04.02 VM on Proxmox with a GTX 1660 Super passed through. It's already successful in Plex hardware transcoding in my tests, so I know it's working in some capacity. Plus, I've confirmed Frigate is using it for hardware acceleration on my cameras (see nvidia-smi below)

```
root@media:/home/media# lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] (rev a1)
01:00.1 Audio device: NVIDIA Corporation TU116 High Definition Audio Controller (rev a1)
01:00.2 USB controller: NVIDIA Corporation TU116 USB 3.1 Host Controller (rev a1)
01:00.3 Serial bus controller: NVIDIA Corporation TU116 USB Type-C UCSI Controller (rev a1)
```

I've followed the docs to generate the TensorRT models but it gets stuck as shown in the log output box.

I confirmed the CUDA version is 11+ and drivers are >=450.80.02, and nvidia-container-runtime is installed. Also that the GPU appears to be supported in general.

```
root@media:/home/media# nvidia-smi
Tue May  9 17:41:20 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 43%   43C    P2    38W / 125W |   1117MiB /  6144MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     19255      C   ffmpeg                            415MiB |
|    0   N/A  N/A     19256      C   ffmpeg                            415MiB |
|    0   N/A  N/A     21300      C   ffmpeg                            283MiB |
+-----------------------------------------------------------------------------+
```

I've tried specifying certain models and setting `USE_FP16` to false as shown in the docs but I end up in the same situation.

Here are details of the Nvidia components that I have installed.

```
libnvidia-cfg1-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed,auto-removable]
libnvidia-compute-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed,automatic]
libnvidia-container-tools/bionic,now 1.13.1-1 amd64 [installed,automatic]
libnvidia-container1/bionic,now 1.13.1-1 amd64 [installed,automatic]
libnvidia-decode-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed,automatic]
libnvidia-encode-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed]
nvidia-container-runtime/bionic,now 3.13.0-1 all [installed]
nvidia-container-toolkit-base/bionic,now 1.13.1-1 amd64 [installed,automatic]
nvidia-container-toolkit/bionic,now 1.13.1-1 amd64 [installed,automatic]
nvidia-dkms-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed,auto-removable]
nvidia-docker2/bionic,now 2.12.0-1 all [installed,upgradable to: 2.13.0-1]
nvidia-kernel-common-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed,auto-removable]
nvidia-kernel-source-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed,auto-removable]
nvidia-utils-515-server/jammy-updates,jammy-security,now 515.105.01-0ubuntu0.22.04.1 amd64 [installed]
```

I also shut down Plex and Frigate containers while trying to run this to remove that as a potential cause.

Lastly, I've tried searching Github and on Google but am not coming up with a resolution to this. Do you guys have any ideas to help?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  enabled: False
database:
  path: /db/frigate.db
cameras:
  Driveway01:
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:redacted@172.16.102.91:554
          roles:
            - detect
    detect:
      enabled: False
      width: 3840
      height: 2160
  Backyard01:
    ui:
      order: 3
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:redacted@172.16.102.90:554
          roles:
            - detect
    detect:
      enabled: False
      width: 3840
      height: 2160
  Frontdoor01:
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:redacted@172.16.102.92:554
          roles:
            - detect
    detect:
      enabled: False
      width: 2560
      height: 1920
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "137mb" # update for your cameras based on calculation above
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [video,compute,utility]
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-web/frigate/config.yml:/config/config.yml
      - /docker-web/frigate:/db
      - /mnt/nvr:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      #- "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nvr.loadbalancer.server.port=5000"
      - "traefik.http.routers.nvr.entrypoints=websecure"
      - "traefik.http.routers.nvr-insecure.entrypoints=websecure"
      - "traefik.http.routers.nvr-insecure.rule=Host(`nvr.redacted.com`) || Host(`nvr.redacted.com`)"
      - "traefik.http.routers.nvr.rule=Host(`nvr.redacted.com `) || Host(`nvr.redacted.com`)"
      - "traefik.http.routers.nvr.tls=true"
    environment:
      FRIGATE_RTSP_PASSWORD: "redacted"
    networks:
        - traefik_proxy_net
      
networks:
  traefik_proxy_net:
    name: "traefik_proxy_net"
    driver: bridge
```

### Relevant log output

```shell
root@media:/docker-web/frigate# docker run --gpus=all --rm -it -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:22.07-py3 /tensorrt_models.sh

=====================
== NVIDIA TensorRT ==
=====================

NVIDIA Release 22.07 (build 40077977)
NVIDIA TensorRT Version 8.4.1
Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

https://developer.nvidia.com/tensorrt

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

To install Python sample dependencies, run /opt/tensorrt/python/python_setup.sh

To install the open-source samples corresponding to this TensorRT release version
run /opt/tensorrt/install_opensource.sh.  To build the open source parsers,
plugins, and samples for current top-of-tree on master or a different branch,
run /opt/tensorrt/install_opensource.sh -b <branch>
See https://github.com/NVIDIA/TensorRT for more information.

+ CUDA_HOME=/usr/local/cuda
+ LD_LIBRARY_PATH=/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
+ OUTPUT_FOLDER=/tensorrt_models
+ echo 'Generating the following TRT Models: yolov4-tiny-288,yolov4-tiny-416,yolov7-tiny-416'
Generating the following TRT Models: yolov4-tiny-288,yolov4-tiny-416,yolov7-tiny-416
+ mkdir -p /tensorrt_models
+ pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (22.1.2)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.7 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.1.2
    Uninstalling pip-22.1.2:
      Successfully uninstalled pip-22.1.2
Successfully installed pip-23.1.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pip install onnx==1.9.0 protobuf==3.20.3
Collecting onnx==1.9.0
  Downloading onnx-1.9.0-cp38-cp38-manylinux2010_x86_64.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 12.4 MB/s eta 0:00:00
Collecting protobuf==3.20.3
  Downloading protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 36.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.8/dist-packages (from onnx==1.9.0) (1.23.0)
Collecting six (from onnx==1.9.0)
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.8/dist-packages (from onnx==1.9.0) (4.2.0)
Installing collected packages: six, protobuf, onnx
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.21.2
    Uninstalling protobuf-4.21.2:
      Successfully uninstalled protobuf-4.21.2
Successfully installed onnx-1.9.0 protobuf-3.20.3 six-1.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ git clone --depth 1 https://github.com/yeahme49/tensorrt_demos.git /tensorrt_demos
Cloning into '/tensorrt_demos'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 118 (delta 13), reused 60 (delta 5), pack-reused 0
Receiving objects: 100% (118/118), 192.06 MiB | 2.00 MiB/s, done.
Resolving deltas: 100% (13/13), done.
Updating files: 100% (109/109), done.
+ cd /tensorrt_demos/plugins
+ make all
computes: 75
NVCCFLAGS: -gencode arch=compute_75,code=[sm_75,compute_75]
nvcc -ccbin g++ -I"/usr/local/cuda/include" -I"/usr/local/TensorRT-7.1.3.4/include" -I"/usr/local/include" -I"plugin" -gencode arch=compute_75,code=[sm_75,compute_75] -Xcompiler -fPIC -c -o yolo_layer.o yolo_layer.cu
yolo_layer.h(89): warning #997-D: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

yolo_layer.h(89): warning #997-D: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

g++ -shared -o libyolo_layer.so yolo_layer.o -L"/usr/local/cuda/lib64" -L"/usr/local/TensorRT-7.1.3.4/lib" -L"/usr/local/lib" -Wl,--start-group -lnvinfer -lnvparsers -lnvinfer_plugin -lcudnn -lcublas -lnvToolsExt -lcudart -lrt -ldl -lpthread -Wl,--end-group
+ cp libyolo_layer.so /tensorrt_models/libyolo_layer.so
+ cd /tensorrt_demos/yolo
+ ./download_yolo.sh
yolov3-tiny.cfg                                               100%[==============================================================================================================================================>]   1.87K  --.-KB/s    in 0s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
