### ISSUE TITLE
[Config Support]: MQTT Network issue

### ISSUE THREAD

**Issue by treb33** [blakeblackshear/frigate#6456]
### Describe the problem you are having

I'm trying to set up MQTT but it's, for me, I think a bit complicated. 
**My network:**
NAS: 192.168.0.50
Home Assistant Supervised: VM on NAS: 192.x.x.80
MQTT on Docker: 192.168.0.50:1883 (networkmode: host)
Zigbee2MQTT on Docker: 192.168.0.50:8099 (networkmode: host)
Frigate on docker: 192.168.0.50:5050 (5000 for NAS) networkmode: bride

Frigate can connect to MQTT if MQTT networkmode is set to bridge, mqtt ip set to docker IP 172.x.x.x., the sensors are available in Home Assisstant but cannot connect if its set to host.
When i change MQTT and Zigbee2MQTT netwerkmode to bridge Home Assistant cannot connect.

How can I get Frigate and MQTT to work? 

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.0.50
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

database:
  path: /media/frigate/frigate.db

logger:
  default: debug
  logs:
    frigate.event: debug


detect:
  width: 1280
  height: 720
  fps: 5


record:
  enabled: True
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 365


#snapshots:
#  enabled: True
#  timestamp: True
#  retain:
#    default: 30


cameras:
  Slaapkamer_****:
    ffmpeg:
      inputs:
        - path: rtsp://****:****@192.168.0.130:554/stream1
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi

    detect:
      enabled: true
      width: 1280
      height: 720


  Slaapkamer_****:
    ffmpeg:
      inputs:
        - path: rtsp://****:****@192.168.0.245:554/stream1
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

  Voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://****:****@192.168.0.29:8554/Streaming/Channels/101
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
```

### Relevant log output

```shell
2023-05-09 22:14:03.012038347  [2023-05-09 22:14:03] frigate.comms.mqtt             ERROR   : Unable to publish to Voordeur/all: client is not connected
2023-05-09 22:14:04.016091636  [2023-05-09 22:14:04] frigate.comms.mqtt             ERROR   : Unable to publish to Slaapkamer_****/all: client is not connected
2023-05-09 22:14:04.744780575  172.17.0.1 - - [09/May/2023:22:14:04 +0200] "GET /api/stats HTTP/1.1" 200 2627 "-" "HomeAssistant/2023.5.2 aiohttp/3.8.4 Python/3.10" "-"
2023-05-09 22:14:05.809912605  [2023-05-09 22:14:05] frigate.comms.mqtt             ERROR   : Unable to publish to Slaapkamer_****/all: client is not connected
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

CPU (no coral)
