### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by RNation0001** [blakeblackshear/frigate#6462]
### Describe the problem you are having

ok im working to migrate from frigate inside HA to a standalone frigate running inside ubuntu with docker compose. i have it up and running however for some reason even though i have a 1tb harddrive  its only showing 102.63 gb free under the storage tab. id like to use most of the hard drive as this is all this machine is going to be for. 

### Version

SYSTEM 0.12.0-DA3E197

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rnation0001/docker-compose/frigate/config/config.yml:/config/config.yml
      - /home/rnation0001/docker-compose/frigate/media:/media/frigate
#      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
#        target: /tmp/cache
#       tmpfs:
#         size: 6000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "Zxcvbn#1"
```

### Relevant log output

```shell
logs look good
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

kinda new to docker but learning
