### ISSUE TITLE
[Camera Support]: cameras that go through NVR have different failures sometime they work fine

### ISSUE THREAD

**Issue by yanivf38** [blakeblackshear/frigate#6465]
### Describe the problem you are having

I have 4 cameras two connected directly to my router and the other two connected through NVR. Ideally, I want all 4 to go through the NVR as it will record 24hrs, while frigate will record only the detected clips.

The issue that I'm having is that the recordings that go through the NVR sometime produce clips but most of the times they fail. What else is interesting is that they also produce 30min clips, which have no motion during that period.

The configuration is identical for all 4 cameras.

The cameras that are connected to the NVR which have the problem are garage and deck

### Version

 0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.224
  port: 1883

  topic_prefix: frigate
  client_id: frigate

  user: _user_
  password: _password_
  stats_interval: 20

birdseye:
  enabled: True
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi #preset-intel-qsv-h264 #preset-vaapi #NVR doesn't reecord with preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-copy # see: https://deploy-preview-4055--frigate-docs.netlify.app/configuration/ffmpeg_presets/

go2rtc:
  streams:
  #MAIN STREAM (HIGH RES)
    front_door: 
      - rtsp://192.168.1.151/user=_user__password=_password__channel=1_stream=0.sdp #0.sdp == high rest 1.sdp == low res
      - ffmpeg:front_door#audio=opus#audio=aac
    front_pathway: 
      - rtsp://192.168.1.152/user=_user__password=_password__channel=1_stream=0.sdp
      - ffmpeg:front_pathway#audio=opus#audio=aac
    garage: 
      - rtsp://192.168.1.102/user=yanivcameras_password=_password__channel=1_stream=0.sdp
      - ffmpeg:garage#audio=opus#audio=aac
    deck: 
      - rtsp://192.168.1.102/user=yanivcameras_password=_password__channel=2_stream=0.sdp
      - ffmpeg:deck#audio=opus#audio=aac
      

   #SUB STREAM (LOW RES)
    front_door_lowres:
      - rtsp://192.168.1.151/user=_user__password=_password__channel=1_stream=1.sdp
    front_pathway_lowres: 
      - rtsp://192.168.1.152/user=_user__password=_password__channel=1_stream=1.sdp
    garage_lowres: 
      - rtsp://192.168.1.102/user=yanivcameras_password=_password__channel=1_stream=1.sdp
    deck_lowres: 
      - rtsp://192.168.1.102/user=yanivcameras_password=_password__channel=2_stream=1.sdp           
    
detectors:
  coral:
   type: edgetpu
   device: usb

cameras:
  front_door: # <-------- Camera name
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/front_door_lowres
          input_args: preset-rtsp-restream
          roles:
            - detect                   
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 704,0,704,33,448,29,454,0
    zones:
      frontDoorPathway:
        coordinates: 0,480,200,304,150,0,612,0,574,480
      #shared zones
      frontPathway:
        coordinates: 0,480,200,304,150,0,612,0,574,480
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      required_zones: []
      retain:
        default: 10
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: []
        retain:
          default: 10
          mode: motion

  front_pathway: # <-------- Camera name
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_pathway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/front_pathway_lowres
          input_args: preset-rtsp-restream
          roles:
            - detect          
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 181,187,233,164,270,143,296,124,293,98,280,74,260,58,233,44,192,39,144,46,95,78,71,110,98,201
        - 463,25,462,0,704,0,704,32
    zones:
      pathwayPathway:
        coordinates: 0,480,0,446,217,251,421,122,597,153,568,480
      #shared zones
      frontPathway:
        coordinates: 0,480,0,446,217,251,421,122,597,153,568,480
      frontYard:
        coordinates: 0,428,0,127,46,98,423,123
      driveway:
        coordinates: 56,104,370,48,618,58,599,161
      neighbourJack:
        coordinates: 613,0,490,4,446,27,360,49,608,60
      street:
        coordinates: 366,46,408,35,456,22,499,0,0,0,0,125        
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      required_zones: []
      retain:
        default: 10
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: []
        retain:
          default: 10
          mode: motion

  garage: # <-------- Camera name
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/garage_lowres
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 704,52,704,23,456,24,455,51
    zones:
      pathwayPathway:
        coordinates: 81,202,76,163,23,116,0,119,0,212
      frontYard:
        coordinates: 0,90,345,72,443,120,265,141,131,161,76,172
      driveway:
        coordinates: 0,209,76,173,462,134,704,260,704,480,0,480
      street:
        coordinates: 247,41,410,39,704,118,704,256
      neighbourCarlos:
        coordinates: 704,0,519,0,501,58,704,120
      neighbourKathy:
        coordinates: 324,72,310,0,186,0,190,76
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      required_zones: []
      retain:
        default: 10
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: []
        retain:
          default: 10
          mode: motion

  deck: # <-------- Camera name
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/deck
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/deck_lowres
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 704,0,704,194,522,134,512,175,333,179,0,247,0,0
        - 704,305,704,480,576,480
    zones:
      backyardDeck:
        coordinates: 0,480,0,249,345,166,510,175,517,131,704,195,704,297,571,480
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      required_zones: []
      retain:
        default: 10
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: []
        retain:
          default: 10
          mode: motion
```

### Relevant log output

```shell
<CONFIG>
...... Many lines of -
2023-05-11 06:13:48.617397122  [2023-05-10 23:13:48] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/deck-20230510231325.mp4
...... Many lines of -
2023-05-11 16:22:30.518315248  [2023-05-11 09:22:30] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/garage-20230511092216.mp4

<GO2RTC>
2023-05-11 02:05:07.127476644  19:05:07.126 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error=EOF url=ffmpeg:deck#audio=opus#audio=aac
2023-05-11 02:05:08.599018769  19:05:08.598 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.30.33.2:50444->192.168.1.102:554: i/o timeout" url=rtsp://192.168.1.102/user=_user__password=_password__channel=2_stream=0.sdp
2023-05-11 02:05:17.410995041  19:05:17.410 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error=EOF url=ffmpeg:deck#audio=opus#audio=aac
2023-05-11 02:05:22.541834649  19:05:22.541 WRN [rtsp] error="codecs not match: H264" stream=deck
```

### FFprobe output from your camera

```shell
not sure how to do that
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

XMEye
