### ISSUE TITLE
[Config Support]: Trying to find the best config to detect a car from a sky view

### ISSUE THREAD

**Issue by MrDrew514** [blakeblackshear/frigate#6468]
### Describe the problem you are having

I've been trying to play with the config to have a decent detection from a car in a driveway but it's inconsistent. Detection starts (Blue rectangle) then it stops after a few seconds spamming my events (even with the stationnary config set) . Is there any way I could handle detecting my car, (stationnary or not) from that camera? Any help is welcome, thank you.

here is my camera view

![image](https://github.com/blakeblackshear/frigate/assets/82120740/222bf24d-9b78-4c26-acb5-109532bcf741)

which generates non-stop spam

![image](https://github.com/blakeblackshear/frigate/assets/82120740/aebdf05e-df59-49f4-bbd5-e2c8cc03c3b0)

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
ptz:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/ptz 
          input_args: preset-rtsp-restream
          roles:
            - detect
      
    detect:
      stationary:
        interval: 0
        threshold: 10

    record:
      enabled: True
      events:
        retain:
          default: 5
    objects:
      track:
        - person
        - dog
        - car
      filters:
        car:
          min_area: 1000
          max_area: 1000000
          min_score: 0.2
          threshold: 0.3
    snapshots:
        # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
```

### Relevant log output

```shell
None
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB
