### ISSUE TITLE
[Config Support]: Frigate not recording sound with go2rtc/reolink. Live sound is fine.

### ISSUE THREAD

**Issue by Moondevil-ha** [blakeblackshear/frigate#6471]
### Describe the problem you are having

As detailed above, none of my recordings have sound since upgrading to .12 and changing from rtmp to rtsp restreaming. Live sound is fine in both Frigate HA card and the Frigate integration, it's just not recording. Have I done something stupid?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# frigate.yml
mqtt:
  host: 192.168.1.248
  user: mqtt-user
  password: ****
  
#birdseye:
  # Optional: Enable birdseye view (default: shown below)
#  enabled: False
  # Optional: Width of the output resolution (default: shown below)
#  width: 1280
  # Optional: Height of the output resolution (default: shown below)
#  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
#  mode: continuous
    
go2rtc:
  streams:
  #  rtsp_cam: # <- for RTSP streams
  #    - rtsp://192.168.1.5:554/live0 # <- stream which supports video & aac audio
  #    - "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Back_Garden: # <- for other streams
      - http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=****  # <- stream which supports video & aac audio
      - "ffmpeg:Back_Garden#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Sideway:
      - http://192.168.1.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=**** 
      - "ffmpeg:Sideway#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Front_Yard:
      - http://192.168.1.8/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=**** 
      - "ffmpeg:Front_Yard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)


cameras:
  Back_Garden:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
    #    - -hwaccel
    #    - vaapi
    #    - -hwaccel_device
    #    - /dev/dri/renderD128
    #    - -hwaccel_output_format
    #    - yuv420p
        #- -c:v 
        #- h264_cuvid
    #  input_args:
    #    - -avoid_negative_ts
    #    - make_zero
    #    #- live_flv
    #    - -fflags
    #    - genpts+discardcorrupt
    #    - -flags
    #    - low_delay
    #    - -strict
    #    - experimental
    #    - -analyzeduration
    #    - 1000M
    #    - -probesize
    #    - 1000M
    #    - -rw_timeout
    #    - "5000000"
    #  output_args:
    #    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Garden?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75

    snapshots:
      enabled: True
      timestamp: True
    record:
      # Optional: Enable recording (default: shown below)
      enabled: True
      # Optional: Number of days to retain recordings regardless of events (default: shown below)
      # NOTE: This should be set to 0 and retention should be defined in events section below
      #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
        #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 5
          mode: all
          # Optional: Per object retention days
          objects:
            person: 15
    motion:
      mask:
        - 0,410,710,390,876,1158,379,1920,0,1920
        - 2560,234,1891,214,2560,633
  Sideway:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
    #    - -hwaccel
    #    - vaapi
    #    - -hwaccel_device
    #    - /dev/dri/renderD128
    #    - -hwaccel_output_format
    #    - yuv420p
        #- -c:v 
        #- h264_cuvid
    #  input_args:
    #    - -avoid_negative_ts
    #    - make_zero
    #    #- live_flv
    #    - -fflags
    #    - genpts+discardcorrupt
    #    - -flags
    #    - low_delay
    #    - -strict
    #    - experimental
    #    - -analyzeduration
    #    - 1000M
    #    - -probesize
    #    - 1000M
    #    - -rw_timeout
    #    - "5000000"
    #  output_args:
    #    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      
      inputs:
        - path: rtsp://127.0.0.1:8554/Sideway?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1440
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
          mask:
            - 2389,1440,1588,818,1233,519,2560,0,2560,1440

    snapshots:
      enabled: True
      timestamp: True
    record:
      # Optional: Enable recording (default: shown below)
      enabled: True
      # Optional: Number of days to retain recordings regardless of events (default: shown below)
      # NOTE: This should be set to 0 and retention should be defined in events section below
      #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
        #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 5
          mode: all
          # Optional: Per object retention days
          objects:
            person: 15
    motion:
      mask:
        - 2389,1440,1588,818,1233,519,2560,0,2560,1440
    
  Front_Yard:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
    #    - -hwaccel
    #    - vaapi
    #    - -hwaccel_device
    #    - /dev/dri/renderD128
    #    - -hwaccel_output_format
    #    - yuv420p
        #- -c:v 
        #- h264_cuvid
    #  input_args:
    #    - -avoid_negative_ts
    #    - make_zero
    #    #- live_flv
    #    - -fflags
    #    - genpts+discardcorrupt
    #    - -flags
    #    - low_delay
    #    - -strict
    #    - experimental
    #    - -analyzeduration
    #    - 1000M
    #    - -probesize
    #    - 1000M
    #    - -rw_timeout
    #    - "5000000"
    #  output_args:
    #    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Yard?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
  
    snapshots:
      enabled: True
      timestamp: True
    record:
            # Optional: Enable recording (default: shown below)
      enabled: True
            # Optional: Number of days to retain recordings regardless of events (default: shown below)
            # NOTE: This should be set to 0 and retention should be defined in events section below
            #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
            # Optional: Event recording settings
      events:
              # Optional: Maximum length of time to retain video during long events. (default: shown below)
              # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
              #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
              # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
              # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
              # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
              # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
                # Required: Default retention days (default: shown below)
          default: 5
          mode: all
                # Optional: Per object retention days
          objects:
            person: 15

detectors:
  coral_pci:
    type: edgetpu
    device: pci
  coral_usb:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
2023-05-12 13:02:35.804762323  [INFO] Starting Frigate...
2023-05-12 13:02:37.895470369  [2023-05-12 14:02:37] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-12 13:02:37.953339806  [2023-05-12 14:02:37] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-05-12 13:02:37.955786105  [2023-05-12 14:02:37] peewee_migrate                 INFO    : Starting migrations
2023-05-12 13:02:37.985969773  [2023-05-12 14:02:37] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-12 13:02:38.024952610  [2023-05-12 14:02:38] frigate.app                    INFO    : Output process started: 302
2023-05-12 13:02:38.031049741  [2023-05-12 14:02:38] frigate.app                    INFO    : Camera processor started for Back_Garden: 305
2023-05-12 13:02:38.043097102  [2023-05-12 14:02:38] frigate.app                    INFO    : Camera processor started for Sideway: 309
2023-05-12 13:02:38.050003168  [2023-05-12 14:02:38] frigate.app                    INFO    : Camera processor started for Front_Yard: 313
2023-05-12 13:02:38.050811569  [2023-05-12 14:02:38] detector.coral_pci             INFO    : Starting detection process: 299
2023-05-12 13:02:38.050817140  [2023-05-12 14:02:38] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-05-12 13:02:38.060286719  [2023-05-12 14:02:38] frigate.app                    INFO    : Capture process started for Back_Garden: 326
2023-05-12 13:02:38.062862782  [2023-05-12 14:02:38] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-12 13:02:38.077398357  [2023-05-12 14:02:38] frigate.app                    INFO    : Capture process started for Sideway: 329
2023-05-12 13:02:38.084306676  [2023-05-12 14:02:38] frigate.app                    INFO    : Capture process started for Front_Yard: 331
2023-05-12 13:02:40.869415814  [2023-05-12 14:02:38] detector.coral_usb             INFO    : Starting detection process: 300
2023-05-12 13:02:40.869757200  [2023-05-12 14:02:38] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-12 13:02:40.881539020  [2023-05-12 14:02:40] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

I have 2 Coral, one PCIe, one USB. Configuration migrated from 11, which was using rtmp restream and WebRTC.

Unsure why live sound is working, whilst record is not.
