### ISSUE TITLE
[Support]: Clips/Recordings do not play inside home assistant Media tab

### ISSUE THREAD

**Issue by Thorvarium** [blakeblackshear/frigate#6474]
### Describe the problem you are having

Clips/Recordings do not play inside home assistant Media tab, but play inside frigate addon

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.xx
  port: 1883
  user: 'frigate'
  password: 'XXXX'
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@192.168.x.xxx:554/1/h264major
          roles:
            - rtmp
        - path: rtsp://admin:XXXXXX@192.168.x.xxx:554/1/h264minor
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
detectors:
  cpu1:
    type: cpu
    num_threads: 3
record:
  enabled: True
  retain:
    days: 2
    mode: all 
  events:
    retain:
      default: 10
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
ffprobe version 2023-05-11-git-ceb050427c-essentials_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  7.100 / 58.  7.100
  libavcodec     60. 11.100 / 60. 11.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.100 /  9.  8.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, rtsp, from 'rtsp://*:*@192.168.x.xxx:554/1/h264minor':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

https://www.amazon.com/gp/product/B09PB2FM2F/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

### Any other information that may be helpful

video: https://photos.app.goo.gl/eiC1w8pg2zgMcrR79
