### ISSUE TITLE
[Support]: Unable to get Frigate to attach to camera at all

### ISSUE THREAD

**Issue by buteomont** [blakeblackshear/frigate#6475]
### Describe the problem you are having

I am trying to set up Frigate on a dedicated Intel NUC with a PCIe Coral card. I intend to use it to monitor 7 cameras of various types.

I loaded Ubuntu 22.04 and then followed the (very good) instructions at https://www.digimoot.com/frigate-nvr-linux-manual-install/ to set up Frigate.  So far, I can get it to run, but it won't connect to any cameras.

I've distilled the configuration down to what I think is the bare minimum that should work.  There's only one camera; a 640x480 ESP32-cam which sends a simple MJPEG stream. It has no userid or password. I also tried an RTSP camera with the same results.

Also, the web UI does not load.  The browser just spins for a while and then gives an error.

Almost immediately I get these errors:

```
ERROR   : pumpcam: Unable to read frames from ffmpeg process.
ERROR   : pumpcam: ffmpeg process is not running. exiting capture thread...

ERROR   : Ffmpeg process crashed unexpectedly for pumpcam.
ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
ERROR   : [tcp @ 0x5607d685ba80] Connection to tcp://10.10.6.16:80 failed: Connection timed out
ERROR   : http://10.10.6.16/?action=stream: Connection timed out
ERROR   : pumpcam: Unable to read frames from ffmpeg process.
ERROR   : pumpcam: ffmpeg process is not running. exiting capture thread...
```
I can connect to the camera without problems in a web browser, so I know the URL is correct.  I tried an RTSP camera with the same results.

I'm sure I have something configured incorrectly, but danged if I can figure out what it is.

### Version

stable

### Frigate config file

```yaml
-----docker-compose.yml------
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate.yml:/config/config.yml:ro
#     - ./media/:/media/frigate
      - /mnt/footage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds
#    environment:
#      FRIGATE_RTSP_PASSWORD: password



-----frigate.yml ------
mqtt:
  host: 10.10.6.15
#  user: mqtt-user
#  password: password
 
cameras:
  # Required: name of the camera
  pumpcam:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
        - path: http://10.10.6.16/?action=stream
          # Required: list of roles for this stream. valid values are: detect,record,clips,rtmp
          # NOTICE: In addition to assigning the record, clips, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
#            - rtmp
#        - path: rtsp://userid:pass@10.10.6.23:554/12
#          roles:
#            - clips
#        # Optional: stream specific global args (default: inherit)
#          global_args:
#          # Optional: stream specific hwaccel args (default: inherit)
#          hwaccel_args:
#          # Optional: stream specific input args (default: inherit)
#          input_args:
#      # Optional: camera specific global args (default: inherit)
#      global_args:
#      # Optional: camera specific hwaccel args (default: inherit)
#      hwaccel_args:
#      # Optional: camera specific input args (default: inherit)
#      input_args:
#      # Optional: camera specific output args (default: inherit)
#      output_args:
 
#    # Required: width of the frame for the input with the detect role
#    width: 2560
#    # Required: height of the frame for the input with the detect role
#    height: 1920
#    # Optional: desired fps for your camera for the input with the detect role
#    # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
#    #       Frigate will attempt to autodetect if not specified.
##    fps: 5
# 
#    # Optional: camera level motion config
#    motion:
#      # Optional: motion mask
#      # NOTE: see docs for more detailed info on creating masks
#      # mask: 0,900,1080,900,1080,1920,0,1920
# 
#    # Optional: timeout for highest scoring image before allowing it
#    # to be replaced by a newer image. (default: shown below)
#    best_image_timeout: 60
# 
#    # Optional: zones for this camera
#    zones:
#      # Required: name of the zone
#      # NOTE: This must be different than any camera names, but can match with another zone on another
#      #       camera.
#      driveway:
#        # Required: List of x,y coordinates to define the polygon of the zone.
#        # NOTE: Coordinates can be generated at https://www.image-map.net/
#        coordinates: 516,1546,1750,1876,129,1450,157,1162,2549,1255,2544,1893,1904,1904,1766,1879
#        # Optional: Zone level object filters.
#        # NOTE: The global and camera filters are applied upstream.
#        filters:
#          person:
#            min_area: 5000
#            max_area: 100000
#            threshold: 0.7
#      street:
#        # Required: List of x,y coordinates to define the polygon of the zone.
#        # NOTE: Coordinates can be generated at https://www.image-map.net/
#        coordinates: 137,1085,1596,835
#        # Optional: Zone level object filters.
#        # NOTE: The global and camera filters are applied upstream.
#        filters:
#          person:
#            min_area: 5000
#            max_area: 100000
#            threshold: 0.7
# 
#    # Optional: Camera level detect settings
#    detect:
#      # Optional: enables detection for the camera (default: True)
#      # This value can be set via MQTT and will be updated in startup based on retained value
#      enabled: True
#      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
#      max_disappeared: 25
# 
#    # Optional: save clips configuration
#    clips:
#      # Required: enables clips for the camera (default: shown below)
#      # This value can be set via MQTT and will be updated in startup based on retained value
#      enabled: False
#      # Optional: Number of seconds before the event to include in the clips (default: shown below)
#      pre_capture: 5
#      # Optional: Number of seconds after the event to include in the clips (default: shown below)
#      post_capture: 5
#      # Optional: Objects to save clips for. (default: all tracked objects)
#      objects:
#        - person
#      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
#      required_zones: []
#      # Optional: Camera override for retention settings (default: global values)
#      retain:
#        # Required: Default retention days (default: shown below)
#        default: 10
#        # Optional: Per object retention days
#        objects:
#          person: 15
# 
#    # Optional: 24/7 recording configuration
#    record:
#      # Optional: Enable recording (default: global setting)
#      enabled: False
#      # Optional: Number of days to retain (default: global setting)
#      retain_days: 30
# 
#    # Optional: RTMP re-stream configuration
#    rtmp:
#      # Required: Enable the live stream (default: True)
#      enabled: True
# 
#    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
#    snapshots:
#      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
#      # This value can be set via MQTT and will be updated in startup based on retained value
#      enabled: False
#      # Optional: print a timestamp on the snapshots (default: shown below)
#      timestamp: False
#      # Optional: draw bounding box on the snapshots (default: shown below)
#      bounding_box: False
#      # Optional: crop the snapshot (default: shown below)
#      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
#      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
#      required_zones: []
#      # Optional: Camera override for retention settings (default: global values)
#      retain:
#        # Required: Default retention days (default: shown below)
#        default: 10
#        # Optional: Per object retention days
#        objects:
#          person: 15
 
#    # Optional: Configuration for the jpg snapshots published via MQTT
#    mqtt:
#      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
#      # NOTE: Only applies to publishing image data to MQTT via 'frigate///snapshot'.
#      # All other messages will still be published.
#      enabled: True
#      # Optional: print a timestamp on the snapshots (default: shown below)
#      timestamp: True
#      # Optional: draw bounding box on the snapshots (default: shown below)
#      bounding_box: True
#      # Optional: crop the snapshot (default: shown below)
#      crop: True
#      # Optional: height to resize the snapshot to (default: shown below)
#      height: 270
#      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
#      required_zones: []
# 
#    # Optional: Camera level object filters config.
#    objects:
#      track:
#        - person
#        - car
#      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
#      # Checks based on the bottom center of the bounding box of the object.
#      # NOTE: This mask is COMBINED with the object type specific mask below
#      mask: 0,0,1000,0,1000,200,0,200
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          min_score: 0.5
#          threshold: 0.7
#          # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
#          # Checks based on the bottom center of the bounding box of the object
#          mask: 0,0,1000,0,1000,200,0,200
```

### Relevant log output

```shell
$ sudo docker-compose up
[sudo] password for david: 
[+] Running 1/0
 ✔ Container frigate  Recreated                                                                                                       0.1s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2023-05-12 14:26:51.374022822  [INFO] Preparing go2rtc config...
frigate  | 2023-05-12 14:26:51.378807544  [INFO] Starting Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-05-12 14:26:51.382866309  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-05-12 14:26:51.727182486  [INFO] Starting go2rtc...
frigate  | 2023-05-12 14:26:51.855534322  14:26:51.855 INF go2rtc version 1.2.0 linux/amd64
frigate  | 2023-05-12 14:26:51.856122487  14:26:51.855 INF [api] listen addr=:1984
frigate  | 2023-05-12 14:26:51.856384458  14:26:51.856 INF [rtsp] listen addr=:8554
frigate  | 2023-05-12 14:26:51.856648341  14:26:51.856 INF [srtp] listen addr=:8443
frigate  | 2023-05-12 14:26:51.856962995  14:26:51.856 INF [webrtc] listen addr=:8555
frigate  | 2023-05-12 14:26:53.009889062  [2023-05-12 14:26:53] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
frigate  | 2023-05-12 14:26:53.033413097  [2023-05-12 14:26:53] peewee_migrate                 INFO    : Starting migrations
frigate  | 2023-05-12 14:26:53.041259995  [2023-05-12 14:26:53] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | 2023-05-12 14:26:53.056786880  [2023-05-12 14:26:53] detector.cpu                   INFO    : Starting detection process: 292
frigate  | 2023-05-12 14:26:53.064797532  [2023-05-12 14:26:53] frigate.app                    INFO    : Output process started: 294
frigate  | 2023-05-12 14:26:53.064809496  [2023-05-12 14:26:53] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2023-05-12 14:26:53.066828422  [2023-05-12 14:26:53] frigate.app                    INFO    : Camera processor started for pumpcam: 297
frigate  | 2023-05-12 14:26:53.073869291  [2023-05-12 14:26:53] frigate.app                    INFO    : Capture process started for pumpcam: 299
frigate  | 2023-05-12 14:26:58.114398424  [2023-05-12 14:26:58] frigate.video                  ERROR   : pumpcam: Unable to read frames from ffmpeg process.
frigate  | 2023-05-12 14:26:58.114883864  [2023-05-12 14:26:58] frigate.video                  ERROR   : pumpcam: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-05-12 14:27:01.378218935  [INFO] Starting go2rtc healthcheck service...
frigate  | 2023-05-12 14:27:13.106313327  [2023-05-12 14:27:13] watchdog.pumpcam               ERROR   : Ffmpeg process crashed unexpectedly for pumpcam.
frigate  | 2023-05-12 14:27:13.106670237  [2023-05-12 14:27:13] watchdog.pumpcam               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-05-12 14:27:13.107327242  [2023-05-12 14:27:13] ffmpeg.pumpcam.detect          ERROR   : [tcp @ 0x5607d685ba80] Connection to tcp://10.10.6.16:80 failed: Connection timed out
frigate  | 2023-05-12 14:27:13.107702532  [2023-05-12 14:27:13] ffmpeg.pumpcam.detect          ERROR   : http://10.10.6.16/?action=stream: Connection timed out
frigate  | 2023-05-12 14:27:18.136203236  [2023-05-12 14:27:18] frigate.video                  ERROR   : pumpcam: Unable to read frames from ffmpeg process.
frigate  | 2023-05-12 14:27:18.136800151  [2023-05-12 14:27:18] frigate.video                  ERROR   : pumpcam: ffmpeg process is not running. exiting capture thread...
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Running 1/1
 ✔ Container frigate  Stopped                                                                                                         8.1s 
canceled
$
```

### FFprobe output from your camera

```shell
$ ffprobe http://10.10.6.16/?action=stream
ffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mpjpeg, from 'http://10.10.6.16/?action=stream':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x480, 25 tbr, 25 tbn, 25 tbc
$
```

### Frigate stats

```json
I don't know enough about Frigate yet to know what this is.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Raspberry Pi Zero W camera (mjpeg, no security)

**Comment by Bettman66** [comment]
You must first convert the stream with go2rtc.
go2rtc only works from version 0.12.0

config.yml:

`go2rtc:`
`  streams:`
`    doorbell: ffmpeg:http://10.10.6.16/?action=stream#video=h264#raw=-pix_fmt yuv420p`

`  doorbell:`
`    ffmpeg:`
`      inputs:`
`        - path: rtsp://127.0.0.1:8554/doorbell`
`          input_args: preset-rtsp-restream`
`          roles:`
`            - record`

**Comment by NickM-27** [comment]
Go2rtc is not required.

**Comment by buteomont** [comment]
I'll give it a shot. I've never heard of go2rtc, I'm assuming it is a protocol translator of some kind? Is it needed just for mjpeg streams?  I've tried several of my other cameras (mostly rtsp/onvif) but got the same failure.

**Comment by NickM-27** [comment]
It does a lot, our docs cover it decently and their docs cover it more. https://github.com/AlexxIT/go2rtc

It is built into frigate 0.12

**Comment by buteomont** [comment]
I tried the go2rtc just as you showed but could not get it to start without configuration errors, no matter how I changed it:

```
frigate  | 2023-05-13 09:04:54.156140719  *************************************************************
frigate  | 2023-05-13 09:04:54.156147379  ***    Your config file is not valid!                     ***
frigate  | 2023-05-13 09:04:54.156151389  ***    Please check the docs at                           ***
frigate  | 2023-05-13 09:04:54.156153917  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2023-05-13 09:04:54.156175237  *************************************************************
frigate  | 2023-05-13 09:04:54.156178163  *************************************************************
frigate  | 2023-05-13 09:04:54.156181822  ***    Config Validation Errors                           ***
frigate  | 2023-05-13 09:04:54.156218073  *************************************************************
frigate  | 2023-05-13 09:04:54.156220473  'ffmpeg'
frigate  | 2023-05-13 09:04:54.157199968  Traceback (most recent call last):
frigate  | 2023-05-13 09:04:54.157204620    File "/opt/frigate/frigate/app.py", line 351, in start
frigate  | 2023-05-13 09:04:54.157206780      self.init_config()
frigate  | 2023-05-13 09:04:54.157209315    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate  | 2023-05-13 09:04:54.157211420      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2023-05-13 09:04:54.157213877    File "/opt/frigate/frigate/config.py", line 1072, in parse_file
frigate  | 2023-05-13 09:04:54.157215851      return cls.parse_obj(config)
frigate  | 2023-05-13 09:04:54.157218250    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
frigate  | 2023-05-13 09:04:54.157221023    File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
frigate  | 2023-05-13 09:04:54.157223544    File "pydantic/main.py", line 1076, in pydantic.main.validate_model
frigate  | 2023-05-13 09:04:54.157227996    File "pydantic/fields.py", line 886, in pydantic.fields.ModelField.validate
frigate  | 2023-05-13 09:04:54.157230446    File "pydantic/fields.py", line 1021, in pydantic.fields.ModelField._validate_mapping_like
frigate  | 2023-05-13 09:04:54.157277432    File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
frigate  | 2023-05-13 09:04:54.157280832    File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
frigate  | 2023-05-13 09:04:54.157299529    File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
frigate  | 2023-05-13 09:04:54.157302710    File "pydantic/fields.py", line 1151, in pydantic.fields.ModelField._apply_validators
frigate  | 2023-05-13 09:04:54.157305617    File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
frigate  | 2023-05-13 09:04:54.157308207    File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
frigate  | 2023-05-13 09:04:54.157326575    File "/opt/frigate/frigate/config.py", line 632, in __init__
frigate  | 2023-05-13 09:04:54.157329502      if len(config["ffmpeg"]["inputs"]) == 1:
frigate  | 2023-05-13 09:04:54.157331699  KeyError: 'ffmpeg'
frigate  | 2023-05-13 09:04:54.157334085  
frigate  | 2023-05-13 09:04:54.157337266  *************************************************************
frigate  | 2023-05-13 09:04:54.157339958  ***    End Config Validation Errors                       ***
frigate  | 2023-05-13 09:04:54.157364427  *************************************************************
```


So I gave up and started from scratch. I erased my docker-compose and replaced it with [the one in the installation guide](https://docs.frigate.video/frigate/installation#docker), with bare minimal customizations for my network:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/david/docker-compose/frigate/config/frigate.yml:/config/config.yml
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

I then ditched my _frigate.yml_ and replaced it with the minimal version in the docs under [Getting Started](https://docs.frigate.video/guides/getting_started#step-1-add-a-detect-stream), again with minimal changes to match one of my RTSP cameras this time:

```
mqtt:
  enabled: False

cameras:
  backyardcam: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.10.6.187/user=admin_password=(mypass)_channel=1_stream=0.sdp # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
```

The configuration errors are gone, but now I'm back to the original problem; the camera gives errors and the web console does not load:

```
frigate  | 2023-05-14 02:24:35.427145167  [2023-05-14 02:24:35] frigate.app                    INFO    : Camera processor started for backyardcam: 293
frigate  | 2023-05-14 02:24:35.434165698  [2023-05-14 02:24:35] frigate.app                    INFO    : Capture process started for backyardcam: 295
frigate  | 2023-05-14 02:24:40.471962033  [2023-05-14 02:24:40] frigate.video                  ERROR   : backyardcam: Unable to read frames from ffmpeg process.
frigate  | 2023-05-14 02:24:40.472228663  [2023-05-14 02:24:40] frigate.video                  ERROR   : backyardcam: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-05-14 02:24:44.121739839  [INFO] Starting go2rtc healthcheck service...
frigate  | 2023-05-14 02:24:55.462227930  [2023-05-14 02:24:55] watchdog.backyardcam           ERROR   : Ffmpeg process crashed unexpectedly for backyardcam.
frigate  | 2023-05-14 02:24:55.462547401  [2023-05-14 02:24:55] watchdog.backyardcam           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-05-14 02:24:55.462816844  [2023-05-14 02:24:55] ffmpeg.backyardcam.detect      ERROR   : [tcp @ 0x55ef2e525140] Connection to tcp://10.10.6.187:554?timeout=5000000 failed: Connection timed out
frigate  | 2023-05-14 02:24:55.462998687  [2023-05-14 02:24:55] ffmpeg.backyardcam.detect      ERROR   : rtsp://10.10.6.187/user=admin_password=(mypass)_channel=1_stream=0.sdp: Connection timed out
```

I feel that the problem lies with _ffmpeg_ somehow.  I also feel that _go2rtc_ is not necessary, as it would have been mentioned in the _installation_ or _getting started_ docs if it were.
I also feel very frustrated.
