### ISSUE TITLE
[Support]: Frigate HACS Integration (ConfigEntries object has no attribute)

### ISSUE THREAD

**Issue by glbwell0** [blakeblackshear/frigate#6478]
### Describe the problem you are having

I installed a few updates recently -then my Frigate automations stopped working. No configuration files have been changed for several weeks. Frigate still launches successfully. But, the HACS integration for Frigate is not loading with the following. I appreciate your help!!!

------
Logger: homeassistant.config_entries
Source: custom_components/frigate/init.py:275
Integration: Frigate ([documentation](https://github.com/blakeblackshear/frigate), [issues](https://github.com/blakeblackshear/frigate-hass-integration/issues))
First occurred: 3:40:38 PM (2 occurrences)
Last logged: 3:41:05 PM

Error setting up entry ccab4aaf-frigate:5000 for frigate
-------
Traceback (most recent call last): 
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup 
     result = await component.async_setup_entry(hass, self) 
  File "/config/custom_components/frigate/__init__.py", line 275, in async_setup_entry
     hass.config_entries.async_setup_platforms(entry, PLATFORMS) 

AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### Version

Current

### Frigate config file

```yaml
mqtt:
  host: homeassistant
  user: mosquitto
  password: M0squ!tt0
  topic_prefix: frigate

cameras:
  Front_Door:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.21:554/live/main
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 14
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.22:554/live/main
          roles:
            - detect
            - clips
    zones:
      driveway:
        coordinates: 0,480,640,480,640,351,640,147,424,44,0,38
      driveway_top:
        coordinates: 530,480,640,480,640,351,640,125,424,44,200,61
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 14
  Back_Deck:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.23:554/live/main
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      mask:
        - 598,375,640,372,640,273,619,267
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    zones:
      Backyard:
        coordinates: 0,0,0,250,447,135,440,0
        objects:
          - person
      Deck:
        coordinates: 0,234,0,480,640,480,640,0,476,0,467,87
        objects:
          - person
  Hot_Tub:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.24:554/live/main
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14

record:
  enabled: True
  retain:
    days: 0
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    required_zones: []
    retain:
      default: 14
      mode: active_objects

objects:
  filters:
    person:
      min_score: 0.3
      
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
    
snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: true
  crop: True
  retain:
    default: 14
```

### Relevant log output

```shell
Logger: homeassistant.config_entries
Source: custom_components/frigate/init.py:275
Integration: Frigate ([documentation](https://github.com/blakeblackshear/frigate), [issues](https://github.com/blakeblackshear/frigate-hass-integration/issues))
First occurred: 3:40:38 PM (2 occurrences)
Last logged: 3:41:05 PM

Error setting up entry ccab4aaf-frigate:5000 for frigate
-------
Traceback (most recent call last): 
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup 
     result = await component.async_setup_entry(hass, self) 
  File "/config/custom_components/frigate/__init__.py", line 275, in async_setup_entry
     hass.config_entries.async_setup_platforms(entry, PLATFORMS) 

AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

### FFprobe output from your camera

```shell
Run at the Terminal???  I got  "ffprobe: command not found"
All cameras are working fine and they are properly detecting objects.  It's the HACS integration that won't load.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

uncertain

### Any other information that may be helpful

Thank you -I appreciate your help!
