### ISSUE TITLE
[Support]: Constant errors in HA Core logs - Cannot connect to host

### ISSUE THREAD

**Issue by ostracizado** [blakeblackshear/frigate#6479]
### Describe the problem you are having

I can't access HTTP API. Even with the port: 5000 defined in the add-on configuration.

Can't say I've noticed the error affecting the essencial functionalities of Frigate, as all cameras are working; but that's why I find it strange.
I can't seem to be able to access: http://ccab4aaf-frigate:5000/

And the HA Core's log is filled with those errors.
![core-log](https://github.com/blakeblackshear/frigate/assets/78053830/e8f85ceb-c82a-4911-9214-9c6c21f64b52)

### Version

0.12

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.100
  user: mqtt-user
  password: password
logger:
  default: debug


  
ffmpeg:
  hwaccel_args: preset-vaapi
  
  
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    outside_front:
      - rtsp://outsidefront:password@192.168.2.133:554/stream1
 #   outsidefront_sub:
 #     - rtsp://outsidefront:password@192.168.2.133:554/stream2

    outside_back:
      - rtsp://outsideback:password@192.168.2.249:554/stream1
 #   outsideback_sub:
 #     - rtsp://outsideback:password@192.168.2.249:554/stream2

    outside_gate:
      - rtsp://outsidegate:password@192.168.2.18:554/stream1
 #   outside_gate_sub:
 #     - rtsp://outsidegate:password@192.168.2.18:554/stream2

cameras:    
  outside_front:
    ffmpeg:
      inputs:
  #      - path: rtsp://127.0.0.1:8554/outside_front_sub #sd 640x360 - stream2
  #        input_args: preset-rtsp-restream
  #        roles:
  #          - detect
        - path: rtsp://127.0.0.1:8554/outside_front #hd 1920x1080 - stream1 2k 2304x1296
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      required_zones:
        - zone_0
        - zone_1
    objects:
      track:
        - person
        - dog
        - cat
    #  filters:
    #    person:
    #      min_score: 0.7
    #      threshold: 0.8
    #      min_area: 10000
    record:
      enabled: True
      retain: 
        days: 2
      events:
        required_zones:
          - zone_0
          - zone_1
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
    zones:
      zone_0:
        coordinates: 886,634,1004,1080,0,1080,0,604
        objects:
          - person
          - dog
        filters:
          person:
            min_area: 2000
          cat:
            max_area: 10000
      zone_1:
        coordinates: 0,930,0,517,188,527,175,923
        objects:
          - person
          - dog
        filters:
          person:
            min_area: 8000
            threshold: 0.7
    motion:
      improve_contrast: true
      mask:
        - 0,69,616,63,612,0,0,0  
        - 878,569,1073,557,1114,817,1168,1030,1043,1042
        - 925,697,1920,797,1920,0,919,0,707,0,228,0

  outside_back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_back?video=copy&audio=aac #hd 1920x1080 - stream1 2k 2304x1296
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - zone_0
        - zone_1
    objects:
      track:
        - person
        - dog
        - cat
      #filters:
      #  person:
      #    min_score: 0.7
      #    threshold: 0.8
          #min_area: 700
    zones:
      zone_0:
        coordinates: 1079,1080,1315,868,1406,766,1500,890,1616,886,1618,754,1370,587,1040,640,0,740,0,1080 
        objects:
          - person
          - dog   
          - cat        
      zone_1:
        coordinates: 1315,583,429,471,0,478,0,583,0,748
        objects:
          - person
          - dog
          - cat    
    motion:
      improve_contrast: true
      mask:
        - 0,69,616,63,612,0,0,0
        - 1386,520,0,392,0,0,175,0,435,0,671,0,1061,0,1920,0,1920,413,1920,496,1920,591,1920,841
        - 1920,0,677,0,293,0,260,67,354,213,862,321,1221,498,1244,516,1252,545,1315,545,1292,534,1345,541,1506,701,1920,734
        - 81,569,97,608,119,574
        - 522,540,503,574,488,540
  outside_gate:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_gate #hd 1920x1080 - stream1 2k 2304x1296
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
    #  stationary:
    #    interval: 10
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - zone_0
        - zone_1
        - zone_2
      #crop: True
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 2 
      events:
        retain:
          default: 4
          mode: active_objects 
        required_zones:
         - zone_0
         - zone_1
         - zone_2
        pre_capture: 3
        post_capture: 10 
    objects:
      track:
        - person
        - dog
        - cat
        - car
      #filters:
      #  person:
      #    min_score: 0.7
      #    threshold: 0.8
          #min_area: 700
    motion:
      improve_contrast: true 
      #mask:
      #  - 0,69,39,0,217,205,443,0,843,0,1004,179,955,575,701,782,0,671
      #  - 1105,0,862,0,975,193,1091,187
      #  - 1528,0,1439,124,1341,116,1353,0
      #  - 1504,228,1510,154,1512,0,1616,0,1548,295,1418,278
      #  - 0,69,616,63,612,0,0,0
    zones:
      zone_0:
        coordinates: 0,784,795,784,1073,471,1920,465,1920,1080,0,1080
        objects:
          - person
          - dog
          - cat
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 4000 
      zone_1:
        coordinates: 1920,498,1026,443,902,431,1103,130,1920,146,1920,486
        objects:
          - person
          - dog
          - cat
          - car
        filters:
          dog:
            min_area: 5000
          cat:
            max_area: 4000 
          person:
            mask: 
              - 1622,0,1530,282,1488,270,1530,22
      tree:
        coordinates: 1595,0,1536,285,1477,276,1512,0
      zone_2:
        coordinates: 1445,0,1075,0,1067,158,1453,134
        objects:
          - person
          - dog
          - cat
          - car
```

### Relevant log output

```shell
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.10', 5000)]
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Server disconnected
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')
```

### FFprobe output from your camera

```shell
Outside_front:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280}]}}]

Outside_back:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]

Outside_gate:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo C310
