### ISSUE TITLE
[Support]: Error occurred when attempting to maintain recording cache

### ISSUE THREAD

**Issue by gcortes** [blakeblackshear/frigate#6482]
### Describe the problem you are having

I've been watching the log after turning off go2rtc the last two days and it have been essentially error free. When I checked this morning, it was flooded with a repeating error on multiple cameras. It's happening about every ten seconds. I restarted Frigate and the errors have stopped for two hours now. This may just a fluke. I'm letting you know in case you see this error again.

## Update

The log was error free for about ten hours, possibly less. When I checked it just now, it's streaming errors again. The begining of the log has rolled off. There hundreds of this error:

```
2023-05-13 19:20:36.916002521  Exception occurred during processing of request from ('127.0.0.1', 52822)
2023-05-13 19:20:36.919538387  Traceback (most recent call last):
2023-05-13 19:20:36.925236222    File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
2023-05-13 19:20:36.925242186      self.process_request(request, client_address)
2023-05-13 19:20:36.930977661    File "/usr/lib/python3.9/socketserver.py", line 665, in process_request
2023-05-13 19:20:36.930980564      t.start()
2023-05-13 19:20:36.931384079    File "/usr/lib/python3.9/threading.py", line 874, in start
2023-05-13 19:20:36.931386848      _start_new_thread(self._bootstrap, ())
2023-05-13 19:20:36.932052463  RuntimeError: can't start new thread
```

Later in the log, it goes back to the errors originally documented. I did another restart and it's back to normal. 

## Update 2
It's been three days since I last restarted Frigate. I haven't seen any errors. Everything seems to be running normal.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.185
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: curt
  password: redacted
#  password: {FRIGATE_MQTT_PASSWORD}
  stats_interval: 60

birdseye:
  enabled: False
  #mode: continuous

detectors:
  # cpu1:
  #   type: cpu
  #   num_threads: 3
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3
 
#go2rtc:
#  streams:
#    drive_way:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
#    drive_way_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
#    north_yard:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/102
#    north_yard_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/101
#    back_door:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/102
#    back_door_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/101
#    south_yard:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/102
#    south_yard_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/101
#    front_porch:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/102
#    front_porch_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/101
#    back_yard:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/102
#    back_yard_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/101
#    garage:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/102
#    garage_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/101
#    living_room:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/102
#    living_room_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/101

cameras:
  drive_way:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/drive_way_sub
#        - path: rtsp://10.0.0.143:8554/drive_way_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/drive_way
#        - path: rtsp://10.0.0.143:8554/drive_way
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 201,242,306,239,418,241,548,241,640,239,640,133,640,0,230,0,0,0,0,62,0,172,69,171,120,183
            - 0,327,0,283,69,278,112,270,143,279,158,311,150,354,106,374,32,425
        car:
          mask:
            - 488,237,547,227,560,262,640,315,640,480,503,480
            - 0,118,0,218,40,415,155,347,296,259,341,212,324,121,497,141,640,135,640,0,0,0            
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - near_driveway
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,365,51,346,21,224,32,184,151,131,228,123,353,114,442,114,545,121,640,121,640,0,0,0
    zones:
      near_driveway:
        coordinates: 138,358,163,327,144,271,206,263,287,292,367,311,496,343,604,480,213,480,50,480,36,406
        objects:
          - person
          - car
    record:
      enabled: True
      retain: 
        days: 0
      events:
        required_zones:
          - near_driveway
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  north_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/north_yard_sub
#        - path: rtsp://10.0.0.143:8554/north_yard_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/north_yard
#        - path: rtsp://10.0.0.143:8554/north_yard
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - north_yard_walk
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 144,0,205,480,0,480,0,0
        - 422,480,338,299,340,258,241,139,215,80,220,0,640,0,640,480
    zones:
      north_yard_walk:
        coordinates: 420,480,338,299,338,253,304,206,270,164,243,127,224,79,213,0,149,0,154,169,210,480
        objects:
          - person
    record:
      enabled: True
      retain: 
        days: 0
      events:
        required_zones:
          - north_yard_walk
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  back_door:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/back_door_sub
#        - path: rtsp://10.0.0.143:8554/back_door_sub
#          input_args: preset-rtsp-restream

          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/back_door
#        - path: rtsp://10.0.0.143:8554/back_door
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - back_door_isolation
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,0,402,0,640,0,640,117,515,142,31,235,229,187,67,229,101,480,0,480
    zones:
      back_door_isolation:
        coordinates: 73,456,31,235,345,169,523,150,560,225,559,332,560,436
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  south_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/south_yard_sub
#        - path: rtsp://10.0.0.143:8554/south_yard_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/south_yard
#        - path: rtsp://10.0.0.143:8554/south_yard
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 523,0,640,0,640,117,640,480,532,480,400,480,407,191,525,88
        - 0,0,0,480,113,313,68,169,221,102,386,55,378,0
    zones:
      south_yard_isolation:
        coordinates: 63,480,128,278,111,210,304,139,410,149,406,233,370,332,408,480
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/front_porch_sub
#        - path: rtsp://10.0.0.143:8554/front_porch_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/front_porch
#        - path: rtsp://10.0.0.143:8554/front_porch
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 0,0,188,0,640,0,640,31,524,79,449,97,346,202,188,326,0,457    
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - front_porch_walk
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
         - 0,0,402,0,640,0,640,24,549,10,384,77,408,187,305,225,278,122,116,220,0,299
    zones:
      front_porch_walk:
        coordinates: 414,480,472,376,554,166,619,159,619,322,607,480
        objects:
          - person        
    record:
      enabled: True
      retain: 
        days: 0
      events:
        required_zones:
          - front_porch_walk
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/back_yard_sub
#        - path: rtsp://10.0.0.143:8554/back_yard_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/back_yard
#        - path: rtsp://10.0.0.143:8554/back_yard
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 77,0,402,0,640,0,640,117,640,274,640,454,640,480,360,480,246,325,182,223,99,96
        - 98,403,56,140,48,0,0,0,0,327,0,480,122,480
    zones:
      back_yard_isolation:
        coordinates: 183,480,74,205,51,114,103,96,195,244,261,338,353,480
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/garage_sub
#        - path: rtsp://10.0.0.143:8554/garage_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/garage
#        - path: rtsp://10.0.0.143:8554/garage
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: False
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,239,94,188,247,137,538,118,539,0,0,0
    zones:
      garage_isolation:
        coordinates: 198,149,0,233,0,480,542,480,565,345,578,245,589,59
    record:
      enabled: False
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/living_room_sub
#        - path: rtsp://10.0.0.143:8554/living_room_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/living_room
#        - path: rtsp://10.0.0.143:8554/living_room
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: False
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: false
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,144,228,145,220,24,0,22
        - 552,0,552,61,413,63,414,0
    zones:
      living_room_isolation:
        coordinates: 147,480,0,301,228,145,500,97,589,103,559,332,562,480
    record:
      enabled: False
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15
```

### Relevant log output

```shell
2023-05-13 09:04:09.972389855  [2023-05-13 09:04:09] frigate.record                 WARNING : Unable to keep up with recording segments in cache for back_yard. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:09.973206393  [2023-05-13 09:04:09] frigate.record                 WARNING : Unable to keep up with recording segments in cache for front_porch. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:09.974184404  [2023-05-13 09:04:09] frigate.record                 WARNING : Unable to keep up with recording segments in cache for north_yard. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:09.974628292  [2023-05-13 09:04:09] frigate.record                 WARNING : Unable to keep up with recording segments in cache for south_yard. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:10.715306386  [2023-05-13 09:04:10] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-05-13 09:04:10.715541822  [2023-05-13 09:04:10] frigate.record                 ERROR   : list index out of range
2023-05-13 09:04:14.976308354  [2023-05-13 09:04:14] frigate.record                 WARNING : Unable to keep up with recording segments in cache for drive_way. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:14.979552522  [2023-05-13 09:04:14] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-05-13 09:04:14.979709213  [2023-05-13 09:04:14] frigate.record                 ERROR   : list index out of range
2023-05-13 09:04:19.976994320  [2023-05-13 09:04:19] frigate.record                 WARNING : Unable to keep up with recording segments in cache for back_yard. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:19.977743970  [2023-05-13 09:04:19] frigate.record                 WARNING : Unable to keep up with recording segments in cache for front_porch. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:19.978474738  [2023-05-13 09:04:19] frigate.record                 WARNING : Unable to keep up with recording segments in cache for north_yard. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:19.978889309  [2023-05-13 09:04:19] frigate.record                 WARNING : Unable to keep up with recording segments in cache for south_yard. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:20.786233832  [2023-05-13 09:04:20] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-05-13 09:04:20.791377215  [2023-05-13 09:04:20] frigate.record                 ERROR   : list index out of range
2023-05-13 09:04:24.978931067  [2023-05-13 09:04:24] frigate.record                 WARNING : Unable to keep up with recording segments in cache for drive_way. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-05-13 09:04:24.981272734  [2023-05-13 09:04:24] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-05-13 09:04:24.981473281  [2023-05-13 09:04:24] frigate.record                 ERROR   : list index out of range
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:
I have eight camera that all the same brand and model
Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: 6/1

Stream 1:
Return Code: 0

Video:
```

### Frigate stats

```json
I don't know how to find this
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision model: DS-2CD2043G0-I

### Any other information that may be helpful

The storage overview for Recording and Snapshots shows 115.61 GB used with a total of 224.14 GB
