### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by eyeseesharp** [blakeblackshear/frigate#6484]
### Describe the problem you are having

Folder creation in the /media/recordings folder is hours ahead of current time

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  # TODO - change to your MQTT settings
  host: 172.18.0.2
  user:
  password:

ffmpeg:
  # TODO - This is the Hardware Acceleration for Intel-based CPUs (<10th Generation) via Quicksync
  # check that this fits your use case - https://docs.frigate.video/configuration/hardware_acceleration
  #hwaccel_args: -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  #hwaccel_args: preset-intel-qsv-h265
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
  # -hwaccel vaapi -hwaccel_device /dev/dri/card0

detectors:
  coral:
    type: edgetpu
    device: usb
    #model:
     # path: "/custom_model.tflite"

objects:
 track:
   - person
   - dog
   - bicycle
   - bird
   - cat
   - shoe
   

cameras:
  # You can create multiple cameras, by adding additional blocks after this camera
  # customise the camera name (camera_one) as you wish.
  dining_room:
    ffmpeg:
      # I use two streams for Frigate. A lower quality one for detection and a higher quality for recording.
      # Adjust as is neccessary for your use case.
      inputs:
        # TODO - replace with your rtsp stream
        - path: rtsp://{user}:{pass}@10.0.0.39:88/videoMain
          roles:
            - record
    detect:
      # TODO - ensure these values are correct for your detect stream. In my case, this is the low quality rtsp stream.
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    record:
      enabled: True
      # Keeps all recordings for two days
      retain:
        days: 7
      # Keeps event based recordings for ten days
      events:
        retain:
          default: 10
  living_room:
    ffmpeg:
      # I use two streams for Frigate. A lower quality one for detection and a higher quality for recording.
      # Adjust as is neccessary for your use case.
      inputs:
        # TODO - replace with your rtsp stream
        - path: rtsp://{user}:{pass}@10.0.0.9:88/videoMain
          roles:
            - record
    detect:
      # TODO - ensure these values are correct for your detect stream. In my case, this is the low quality rtsp stream.
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    record:
      enabled: True
      # Keeps all recordings for two days
      retain:
        days: 7
      # Keeps event based recordings for ten days
      events:
        retain:
          default: 10
  family_room:
    ffmpeg:
      # I use two streams for Frigate. A lower quality one for detection and a higher quality for recording.
      # Adjust as is neccessary for your use case.
      inputs:
        # TODO - replace with your rtsp stream
        - path: rtsp://{user}:{pass}@10.0.0.27:88/videoMain
          roles:
            - record
    detect:
      # TODO - ensure these values are correct for your detect stream. In my case, this is the low quality rtsp stream.
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    record:
      enabled: True
      # Keeps all recordings for two days
      retain:
        days: 7
      # Keeps event based recordings for ten days
      events:
        retain:
          default: 10
  kitchen:
    ffmpeg:
      # I use two streams for Frigate. A lower quality one for detection and a higher quality for recording.
      # Adjust as is neccessary for your use case.
      inputs:
        # TODO - replace with your rtsp stream
        - path: rtsp://{user}:{pass}@10.0.0.45:88/videoMain
          roles:
            - record
    detect:
      # TODO - ensure these values are correct for your detect stream. In my case, this is the low quality rtsp stream.
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    record:
      enabled: True
      # Keeps all recordings for two days
      retain:
        days: 7
      # Keeps event based recordings for ten days
      events:
        retain:
          default: 10
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@10.0.0.44:88/videoMain
          roles:
            - record
            - detect
    motion:
      threshold: 25
      mask:
       - 355,0,0,0,0,36,358,33
       - 264,845,417,871,437,717,291,704
       - 241,0,222,115,280,239,389,315,479,358,628,341,719,328,793,306,882,256,902,0
       - 1920,346,1920,179,1920,0,1807,0,1652,0,1611,31,1634,97,1729,157,1807,253 
    detect:
      width: 1920
      height: 1080
      fps: 15
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 10
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://{user}:{pass}@10.0.0.17
          roles:
            - record
            - detect
    motion:
      threshold: 3
      mask:
       - 1051,1761,1069,1821,469,1821,466,1761
       - 1066,421,1081,486,1099,594,1118,697,1124,734,1138,883,1141,969,1125,1221,1192,1216,1201,975,1213,1202,1270,1194,1262,980,1300,981,1362,918,1348,773,1399,746,1466,724,1493,694,1466,672,1425,558,1356,425,1234,354,1170,330,1128,329
       - 551,903,878,896,869,998,550,1003
       - 1447,875,1515,913,1501,992,1447,992,1380,965,1383,893
       - 1117,1653,1536,1585,1536,1331,1515,1185,1399,1193,1266,1179,1135,1204
       - 908,576,915,651,909,725,893,761,845,749,812,679,821,612
       - 489,615,576,579,587,612,561,677,512,729,467,715
    detect:
      width: 1536
      height: 2048
      fps: 15
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 10
```

### Relevant log output

```shell
Screenshot
```

### Frigate stats

```json
{"backyard":{"camera_fps":15.2,"capture_pid":318,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":329,"pid":303,"process_fps":15.2,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"10.4"},"1":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"9.3","mem":"1.8"},"110":{"cpu":"0.0","mem":"0.0"},"117":{"cpu":"0.0","mem":"0.1"},"1337":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"1387":{"cpu":"0.3","mem":"0.0"},"1395":{"cpu":"0.3","mem":"0.0"},"1398":{"cpu":"0.3","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"0.5"},"287":{"cpu":"1.0","mem":"0.1"},"288":{"cpu":"0.0","mem":"0.7"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"4.0","mem":"0.6"},"296":{"cpu":"0.7","mem":"0.6"},"297":{"cpu":"0.0","mem":"0.1"},"298":{"cpu":"1.0","mem":"0.6"},"299":{"cpu":"0.7","mem":"0.6"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.1"},"301":{"cpu":"0.7","mem":"0.6"},"302":{"cpu":"0.0","mem":"0.1"},"303":{"cpu":"2.0","mem":"0.6"},"304":{"cpu":"2.3","mem":"0.9"},"305":{"cpu":"2.3","mem":"0.6"},"306":{"cpu":"0.0","mem":"0.1"},"307":{"cpu":"1.7","mem":"0.6"},"31":{"cpu":"0.0","mem":"0.0"},"311":{"cpu":"2.3","mem":"0.6"},"312":{"cpu":"6.3","mem":"0.4"},"315":{"cpu":"1.7","mem":"0.6"},"316":{"cpu":"0.0","mem":"0.1"},"318":{"cpu":"11.3","mem":"0.6"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"6.0","mem":"0.4"},"321":{"cpu":"15.3","mem":"0.6"},"326":{"cpu":"0.0","mem":"0.1"},"329":{"cpu":"26.9","mem":"0.5"},"331":{"cpu":"8.6","mem":"0.4"},"332":{"cpu":"0.0","mem":"0.1"},"333":{"cpu":"6.0","mem":"0.4"},"335":{"cpu":"29.6","mem":"0.6"},"39":{"cpu":"0.0","mem":"0.0"},"47":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"97":{"cpu":"0.0","mem":"0.1"},"MiB":{"cpu":"13176.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"load","mem":"average:"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.38,"pid":288}},"dining_room":{"camera_fps":5.1,"capture_pid":305,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":320,"pid":296,"process_fps":5.1,"skipped_fps":0.0},"doorbell":{"camera_fps":15.0,"capture_pid":321,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":335,"pid":304,"process_fps":15.0,"skipped_fps":0.0},"family_room":{"camera_fps":5.0,"capture_pid":311,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":331,"pid":299,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"14.88 %","mem":"- %"}},"kitchen":{"camera_fps":5.0,"capture_pid":315,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":333,"pid":301,"process_fps":5.0,"skipped_fps":0.0},"living_room":{"camera_fps":5.1,"capture_pid":307,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":312,"pid":298,"process_fps":5.1,"skipped_fps":0.0},"service":{"last_updated":1684028333,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":252.0,"mount_type":"tmpfs","total":268.4,"used":16.4},"/media/frigate/clips":{"free":3699757.7,"mount_type":"ext4","total":3936820.7,"used":37006.9},"/media/frigate/recordings":{"free":3699757.7,"mount_type":"ext4","total":3936820.7,"used":37006.9},"/tmp/cache":{"free":423942.3,"mount_type":"overlay","total":502392.6,"used":52855.0}},"temperatures":{},"uptime":454,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I have ensured my docker-compose file has - /etc/localtime:/etc/localtime:ro and the timezone on my machine is correct.

I have also tried setting environment variable for my timezone, to no avail. The debug timestamp in the webviewer shows correct time.

However, the folder name with the date is ahead, and all events in the viewer also show up ahead, by about 4 hours.

You can see in image below, it created the 14th on the 13th. The last file in the 13th is actually 4 hours behind as well.

Not sure where else to go so I am posting here
![image](https://github.com/blakeblackshear/frigate/assets/48740390/84aaf462-965e-4a41-a8d8-5f2d43ca39bb)
