### ISSUE TITLE
[Config Support]: v12.x possibly causing HA core to crash

### ISSUE THREAD

**Issue by xbmcnut** [blakeblackshear/frigate#6485]
### Describe the problem you are having

 It appears as though the Frigate add-on crashes and then for some reason, that crashes the deCONZ add-on and then HA core crashes too all the way to the point where I can’t even ping HA any more so the ability to SSH and check or restart anything has gone.

This has happened about 5~6 times over the last 12 months on two different hardware platforms, with the last three events happening in the past 7 days on my new 12th gen Core i5 Beelink SEi12. In typically ‘smoke detector battery warning’ fashion, the last two episodes happened at 0400 and 0200. :slightly_frowning_face: The previous hardware was an Intel NUC with a 5th gen core i7.

The only way to recover HA is to force shutdown the hardware and reboot. Arghh!!!

I have an Uptime Kuma monitor on my Synology NAS that polls the MQTT topic `frigate/available` and checks for the payload `online` which is the only way I get notified something has failed. I've since added another monitor to ping HA itself.

I have disabled Frigate for now as I have things like my hot water managed via HA and when HA fails and we have no water, I start walking with a limp!

### Version

12

### Frigate config file

```yaml
## https://docs.frigate.video/configuration/index#full-configuration-reference ##
## Full configuration File ##
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.app: debug

mqtt:
  host: 10.0.1.100

detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: false

birdseye:
  enabled: True
  width: 1280  
  height: 720
  quality: 8
  mode: objects # motion
 
ffmpeg:
  hwaccel_args: preset-vaapi #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

detect:
  width: 1280 # <---- update for your camera's resolution
  height: 720 # <---- update for your camera's resolution
  fps: 6

record: # <----- Enable recording
  enabled: True
  events:
    #max_seconds: 300 # default value = 300
    pre_capture: 2 # default = 5
    post_capture: 5
    objects:
      - person
      - cat
    required_zones: []
    retain:
      default: 7 # default = 10

snapshots: # <----- Enable snapshots
  enabled: True
  bounding_box: True 
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height:    

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "bl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d.%m.%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255 # default = 255
    green: 255 # default = 255
    blue: 255 # default = 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2 # default = 2
  # Optional: Effect of lettering (default: shown below)
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid

go2rtc:
  streams:
    driveway_frigate:
      - rtsp://username:password@10.0.30.14:554/Streaming/Channels/103 #(3rd stream h.264, 720p, 6fps)
    entry_frigate:
      - rtsp://username:password@10.0.30.12:554/Streaming/Channels/103
    path_frigate:
      - rtsp://username:password@10.0.30.13:554/cam/realmonitor?channel=1&subtype=02 #(3rd stream h.264, 720p, 6fps)
    deck_frigate:
      - rtsp://username:password@10.0.30.11:554/cam/realmonitor?channel=1&subtype=02
    spa_frigate:
      - rtsp://username:password@10.0.30.15:554/Streaming/Channels/103
    backyard_frigate:
      - rtsp://username:password@10.0.30.7:554/Streaming/Channels/103

##################    
#### DRIVEWAY ####
##################  

cameras:
  driveway_frigate: # <------ Name the camera    
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_frigate # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record           
    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25
      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30    
      mask:
        - 1280,282,1219,234,1144,210,982,159,886,117,819,132,592,720,1280,720
        - 601,0,510,73,0,103,0,0
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - cat
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 250000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8 
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 540
      # Optional: jpeg encode quality (default: shown below)
      quality: 90
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

  entry_frigate: # <------ Name the camera    
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entry_frigate # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record             
    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25
      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30        
      mask:    
        - 0,575,733,325,669,0,0,0
        - 709,361,969,347,947,131,691,141
        - 1280,264,1280,720,1053,720,1001,290              
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - cat
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 10000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 225000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 540
      # Optional: jpeg encode quality (default: shown below)
      quality: 90
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

  path_frigate: # <------ Name the camera    
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/path_frigate # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record             
    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25
      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30        
      mask:    
        - 1035,0,985,569,617,687,385,291,369,0
        - 1243,70,1246,31,961,29,959,69         
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - cat
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 150000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 540
      # Optional: jpeg encode quality (default: shown below)
      quality: 90
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

  deck_frigate: # <------ Name the camera    
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_frigate # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record             
    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25
      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30        
      mask:  
        - 724,0,1280,0,1280,402,834,202,802,172,673,135,536,66,329,78,300,0
        - 1280,720,1280,590,1186,621,1156,720   
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 150000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 540
      # Optional: jpeg encode quality (default: shown below)
      quality: 90
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

  spa_frigate: # <------ Name the camera    
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/spa_frigate # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record             
    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25
      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30        
      mask:
        - 666,94,492,117,330,152,0,254,0,169,0,93,0,0,63,0,158,0,332,0,942,0,897,140
        - 1220,0,1216,150,1068,124,1073,0
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 150000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.85
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 540
      # Optional: jpeg encode quality (default: shown below)
      quality: 90
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

  backyard_frigate: # <------ Name the camera    
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_frigate # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record             
    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25
      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30        
      mask:
        - 1280,0,1280,190,1198,185,1173,202,1023,193,742,181,521,251,507,476,259,561,0,620,0,0,783,0
        - 46,720,424,720,427,674,45,675
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - cat
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 225000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 540
      # Optional: jpeg encode quality (default: shown below)
      quality: 90
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
```

### Relevant log output

```shell
Nothing relevant. Here are the last few entries of the HA log before it stopped working.
11/05/2023	14:06:29	Error	homeassistant	user	homeassistant	[36m2023-05-11 14:06:28.876 DEBUG (MainThread) [custom_components.frigate] Finished fetching frigate data in 3.708 seconds (success: True)[0m
11/05/2023	14:06:21	Error	homeassistant	user	homeassistant	[36m2023-05-11 14:06:20.876 DEBUG (MainThread) [custom_components.frigate] Finished fetching frigate data in 3.708 seconds (success: True)[0m
11/05/2023	14:06:13	Error	homeassistant	user	homeassistant	[36m2023-05-11 14:06:12.878 DEBUG (MainThread) [custom_components.frigate] Finished fetching frigate data in 3.710 seconds (success: True)[0m
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
