### ISSUE TITLE
[HW Accel Support]: CPU usage and power draw higher after installing nvidia GPU

### ISSUE THREAD

**Issue by ColColonCleaner** [blakeblackshear/frigate#6489]
### Describe the problem you are having

Running Frigate on Unraid via the docker container. The unraid server is on an old 4790K which doesn't have hardware decoding, so I got an old GTX1050Ti for that.
Hooked it up and passed the GPU through to frigate, and now the CPU usage is higher than it was previously and the power draw has also increased by another 75 watts. CPU usage increased from about 25% on average to 35% on average, instead of decreasing.
I see the ffmpeg processes when running nvidia-smi from unraid's terminal, one for each camera, and I see the GPU is being utilized at 10-11%.
Wondering what I did so incorrectly to get worse CPU usage and power draw after adding hardware acceleration.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: <redacted>
  port: <redacted>
  topic_prefix: frigate
  client_id: frigate
  user: <redacted>
  password: <redacted>
  stats_interval: 60

logger:
  default: debug

database:
  path: /media/frigate/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false
  width: 1920
  height: 1080
  quality: 5
  mode: objects

live:
  height: 1080
  quality: 8

record:
  enabled: true
  retain:
    days: 15
    mode: motion
  events:    
    pre_capture: 10
    post_capture: 20
    required_zones: [property]
    retain:
      default: 15
      mode: motion
      objects:
        person: 30

snapshots:
  enabled: true
  clean_copy: True
  timestamp: true
  bounding_box: true
  required_zones: [property]
  retain:
    default: 365

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 4
  effect: shadow

rtmp:
  enabled: false

model:
  path: /config/mobiledet_320x320_edgetpu.tflite
  #path: /config/yolo7_320.tflite
  labelmap_path: /labelmap.txt
  width: 320
  height: 320

motion:
  threshold: 50
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  improve_contrast: true
  mqtt_off_delay: 5

objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - bird
    - cat
    - dog
    - horse
    - sheep
    - bear

  filters:
    car:
      min_score: 0.5
      min_ratio: 1.0
      threshold: 0.7
    person:
      #min_area: 5000
      #max_area: 100000
      #min_ratio: 0.5
      max_ratio: 1.0
      min_score: 0.5
      threshold: 0.76

detect:
  width: 3840
  height: 2160
  fps: 15
  enabled: True
  max_disappeared: 150
  stationary:
    interval: 0
    threshold: 150

go2rtc:
  streams:
    side_door_cam:
      - rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - "ffmpeg:rtsp_cam#audio=opus"
    front_door_cam:
      - rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - "ffmpeg:rtsp_cam#audio=opus"
    backyard_cam:
      - rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - "ffmpeg:rtsp_cam#audio=opus"
  webrtc:
    candidates:
      - <redacted>

cameras:
  side_door_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_door_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 3840
      height: 2160
    birdseye:
      mode: objects
    motion:
      mask:
        - 3840,0,3840,1065,3143,692,2630,464,2154,314,1721,209,1512,183,1260,171,678,354,212,544,0,587,0,0,399,0
    zones:
      property:
          coordinates: 0,2160,3840,2160,3840,1111,2932,625,1867,249,1280,169,765,325,596,372,0,638
      front_yard:
          coordinates: 207,573,816,335,923,369,1060,497,264,818
      deck:
          coordinates: 0,2160,3058,2160,3139,1855,1766,963,1048,549,266,887
      side_door:
          coordinates: 863,2160,2226,1469,1969,1236,1800,1094,1546,980,1370,965,466,1465
      driveway:
          coordinates: 3840,2052,3840,1160,3795,1139,3198,773,2585,511,2145,342,1736,247,1436,195,787,373,1022,437,1517,711
    objects:
      filters:
        car:
          min_area: 100000
          mask:
            - 1757,0,999,0,473,0,0,0,0,566,811,247
        person:
          min_area: 150000
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 90
      required_zones: [property]
  front_door_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 3840
      height: 2160
      #width: 704
      #height: 480
    birdseye:
      mode: objects
    zones:
      property:
        coordinates: 743,874,144,1149,0,1407,0,2160,3840,2160,3840,1232,3303,1039,2851,904,2525,825,2152,754,1990,694,1542,587
      front_yard:
        coordinates: 0,1500,383,1322,580,1196,830,1060,1056,923,1439,778,1988,770,2751,944,3840,1301,3840,2160,0,2160
      front_door:
        coordinates: 1239,1244,0,1935,0,2160,2577,2160,3716,1439,1940,856
    objects:
      filters:
        car:
          min_area: 100000
          max_area: 1000000
          mask:
            - 1807,0,2347,0,3840,0,3840,594,3253,390,2528,262,1721,188,1015,183,535,233,93,200,630,0,1184,0
        person:
          min_area: 150000
          mask:
            - 0,1027,127,1065,224,917,144,680,0,684
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 90
      required_zones: [property]
  backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 3840
      height: 2160
      #width: 704
      #height: 480
    birdseye:
      mode: objects
    motion:
      mask:
        - 3840,0,3840,630,3745,554,3507,435,3331,319,3051,190,2884,119,2532,45,2478,0
        - 3840,2160,3017,2160,3084,2059,3267,1736,3519,1443,3840,1039
        - 0,0,461,0,502,95,516,309,0,480
    zones:
      property:
        coordinates: 3840,2160,3614,468,3372,333,3051,195,2887,126,2706,86,2532,57,2228,67,1424,171,533,361,0,578,0,2160
      garage_driveway:
        coordinates: 0,1201,1760,568,980,252,0,580
      driveway:
        coordinates: 0,1201,1760,568,980,252,0,580
      backyard:
        coordinates: 3840,2160,3559,454,3312,321,2839,117,2423,93,2392,371,1182,673,254,965,0,1122,0,2160
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 90
      required_zones: [property]
    objects:
      filters:
        person:
          min_area: 20000
          mask:
            - 0,0,461,0,502,95,516,309,0,480
        car:
          min_area: 20000
          mask:
            - 0,0,461,0,502,95,516,309,0,480

environment_vars:
  PLUS_API_KEY: "<redacted>"
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='eth2'
  --ip='<redacted>'
  --privileged=true
  -e TZ="<redacted>"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="NAS-T"
  -e HOST_CONTAINERNAME="frigate"
  -e 'TCP_PORT_5000'='5000'
  -e 'TCP_PORT_8554'='8554'
  -e 'FRIGATE_RTSP_PASSWORD'='<redacted>'
  -e 'PLUS_API_KEY'='<redacted>'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-19bb7700-f9b0-4884-cc1b-cd118a5c4f9b'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'TCP_PORT_8555'='8555'
  -e 'UDP_PORT_8555'='8555'
  -e 'TCP_PORT_1984'='1984'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -v '/mnt/user/Frigate/config':'/config':'rw'
  -v '/mnt/user/Frigate/media/':'/media/frigate':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/bus/usb/004/'
  --gpus=all
  --shm-size=512mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=100000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:stable'
```

### Relevant log output

```shell
Issue isn't related to errors, more about efficiency. I was expecting to see less CPU usage after installing a dedicated GPU for encoding/decoding but the CPU is being hit harder now than it was before the install.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Amcrest IP8M-T2599EW
