### ISSUE TITLE
[Config Support]: docker compose 

### ISSUE THREAD

**Issue by thetravellor** [blakeblackshear/frigate#6494]
### Describe the problem you are having

How can I configure frigate to use my second graphics card?

It always uses the first card, no matter what I do.

Also it seems that the ffmpeg processes do get executed by the nvidia card, but differently to the documentation I see this from nvidia-smi when run natively from Ubuntu.

### Version

0.13.0-E3B9998

### Frigate config file

```yaml
docker-compose,yml

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
#    image: ghcr.io/blakeblackshear/frigate:master-d6c9538-tensorrt
    image: ghcr.io/blakeblackshear/frigate:dev-e3b9998-tensorrt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #              device_ids: ['0']
              count: 2
              capabilities: [gpu]
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
        #      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/renderD129 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /data/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "<masked>"

config.yml

# yaml-language-server: $schema=http://192.168.2.232:5000/api/config/schema
mqtt:
  host: automation
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: zigbee2mqtt
  password: <masked>
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  # height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  # required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
      dog: 2
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
#timestamp_style:
#  # Optional: Position of the timestamp (default: shown below)
#  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
#  position: "tl"
#  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
#  #           Additional Examples:
#  #             german: "%d.%m.%Y %H:%M:%S"
#  format: "%d/%m/%Y %H:%M:%S"
#  # Optional: Color of font
#  color:
#    # All Required when color is specified (default: shown below)
#    red: 255
#    green: 255
#    blue: 255
#  # Optional: Line thickness of font (default: shown below)
#  thickness: 2
#  # Optional: Effect of lettering (default: shown below)
#  #      t    None (No effect),
#  #           "solid" (solid background in inverse color of font)
#  #           "shadow" (shadow for font)
#  #effect: "solid"
cameras:
  door:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #      input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=1&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=1&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
  front:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=3&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=3&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
  driveway:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=4&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=4&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
    objects:
      track:
        - person
        - dog
        - cat
        - car
    zones:
      garageentrance:
        coordinates: 506,576,161,576,122,253,269,232,392,214,590,437
      parking:
        coordinates: 272,21,379,0,494,60,517,90,497,121,433,109,402,107,353,99,262,97
  dogs:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=2&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=2&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
    objects:
      track:
        - person
        - dog
        - cat
  backyard_left:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=6&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=6&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
  backyard_right:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=8&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=8&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
  laundry:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=7&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=7&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
  alfresco:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      #input_args:
      #  - -c:v
      #  - h264_cuvid    
      inputs:
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=5&subtype=0
        input_args: preset-rtsp-generic
        roles:
          - record
      - path: rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=5&subtype=1
        input_args: preset-rtsp-generic
        roles: 
          - detect
    detect:
      width: 704
      height: 576
go2rtc:
  streams:
    front:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=3&subtype=0
    alfresco:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=5&subtype=0
    driveway:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=4&subtype=0
    door:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=1&subtype=0
    laundry:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=7&subtype=0
    dogs:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=2&subtype=0
    backyard_left:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=6&subtype=0
    backyard_right:
      - rtsp://admin:<masked>@nvr:554/cam/realmonitor?channel=8&subtype=0
```

### Relevant log output

```shell
VAINFO OUTPUT
Return Code: 3

Process Error:

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

### Frigate stats

```json
{"alfresco":{"camera_fps":5.0,"capture_pid":670,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":688,"pid":623,"process_fps":5.0,"skipped_fps":0.0},"backyard_left":{"camera_fps":5.1,"capture_pid":647,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":657,"pid":618,"process_fps":5.1,"skipped_fps":0.0},"backyard_right":{"camera_fps":5.0,"capture_pid":654,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":666,"pid":619,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"18":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.1"},"97":{"cpu":"14.9","cpu_average":"4","mem":"1.6"},"99":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"116":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"141":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"142":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"143":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"144":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"149":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"172":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"199":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"231":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"265":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"294":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"335":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"370":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"591":{"cpu":"0.0","cpu_average":"0","mem":"0.5"},"594":{"cpu":"0.0","cpu_average":"1","mem":"0.7"},"603":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"604":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"606":{"cpu":"5.0","cpu_average":"1","mem":"0.6"},"610":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"611":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"612":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"614":{"cpu":"0.0","cpu_average":"3","mem":"0.6"},"615":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"616":{"cpu":"4.9","cpu_average":"0","mem":"0.6"},"617":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"618":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"619":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"620":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"621":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"623":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"624":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"625":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"628":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"631":{"cpu":"4.9","cpu_average":"1","mem":"0.3"},"632":{"cpu":"4.9","cpu_average":"0","mem":"0.6"},"633":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"634":{"cpu":"4.9","cpu_average":"3","mem":"0.7"},"637":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"640":{"cpu":"4.9","cpu_average":"2","mem":"0.7"},"645":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"646":{"cpu":"0.0","cpu_average":"1","mem":"0.1"},"647":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"648":{"cpu":"4.9","cpu_average":"2","mem":"0.7"},"649":{"cpu":"0.0","cpu_average":"1","mem":"0.1"},"654":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"655":{"cpu":"4.9","cpu_average":"1","mem":"0.1"},"657":{"cpu":"4.9","cpu_average":"3","mem":"0.7"},"661":{"cpu":"4.9","cpu_average":"1","mem":"0.1"},"662":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"663":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"666":{"cpu":"0.0","cpu_average":"2","mem":"0.7"},"669":{"cpu":"4.9","cpu_average":"1","mem":"0.1"},"670":{"cpu":"0.0","cpu_average":"0","mem":"0.6"},"671":{"cpu":"0.0","cpu_average":"2","mem":"0.7"},"672":{"cpu":"0.0","cpu_average":"0","mem":"0.0"},"688":{"cpu":"4.9","cpu_average":"2","mem":"0.7"},"689":{"cpu":"0.0","cpu_average":"1","mem":"0.1"},"694":{"cpu":"0.0","cpu_average":"1","mem":"0.1"},"695":{"cpu":"0.0","cpu_average":"1","mem":"0.1"},"1715":{"cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.92,"pid":604}},"dogs":{"camera_fps":5.1,"capture_pid":637,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":648,"pid":616,"process_fps":5.1,"skipped_fps":0.0},"door":{"camera_fps":5.0,"capture_pid":625,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":631,"pid":611,"process_fps":5.0,"skipped_fps":0.0},"driveway":{"camera_fps":5.0,"capture_pid":632,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":640,"pid":614,"process_fps":5.0,"skipped_fps":0.0},"front":{"camera_fps":5.1,"capture_pid":628,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":634,"pid":612,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"NVIDIA GeForce GTX 980":{"gpu":"0.0%","mem":"1.48%"}},"laundry":{"camera_fps":5.0,"capture_pid":663,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":671,"pid":621,"process_fps":5.0,"skipped_fps":0.0},"processes":{"go2rtc":{"pid":89},"logger":{"pid":591},"recording":{"pid":594}},"service":{"last_updated":1684148450,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":259.7,"mount_type":"tmpfs","total":268.4,"used":8.7},"/media/frigate/clips":{"free":530407.2,"mount_type":"ext4","total":1967864.1,"used":1337420.2},"/media/frigate/recordings":{"free":530407.2,"mount_type":"ext4","total":1967864.1,"used":1337420.2},"/tmp/cache":{"free":960.7,"mount_type":"tmpfs","total":1000.0,"used":39.3}},"temperatures":{},"uptime":692,"version":"0.13.0-e3b9998"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Ubuntu 20.04 

nvidia-smi
Mon May 15 20:54:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 17%   54C    P2    56W / 195W |    782MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   30C    P8    17W / 195W |      8MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2991      G   /usr/lib/xorg/Xorg                  8MiB |
|    0   N/A  N/A      3499      G   /usr/bin/gnome-shell                2MiB |
|    0   N/A  N/A   1325554      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1325557      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1325563      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1325571      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1325580      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1325590      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1325595      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1325612      C   ffmpeg                             95MiB |
|    1   N/A  N/A      2991      G   /usr/lib/xorg/Xorg                  3MiB |
+-----------------------------------------------------------------------------+

**Comment by thetravellor** [comment]
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":0,"width":0}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":0,"width":0}]}}]

**Comment by thetravellor** [comment]
2023-05-15 20:49:06.235118688  [INFO] Preparing Frigate...
2023-05-15 20:49:06.242280291  [INFO] Moving db from '/media/frigate/frigate.db' to the '/config' dir...
2023-05-15 20:49:08.627695283  copied '/media/frigate/frigate.db' -> '/config/frigate.db'
2023-05-15 20:49:08.627706533  removed '/media/frigate/frigate.db'
2023-05-15 20:49:08.628374789  [INFO] Starting Frigate...
2023-05-15 20:49:10.216753667  [2023-05-15 20:49:10] frigate.app                    INFO    : Starting Frigate (0.13.0-e3b9998)
2023-05-15 20:49:10.216822101  [2023-05-15 20:49:10] frigate.app                    INFO    : Creating directory: /config/model_cache
2023-05-15 20:49:10.275077800  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : Starting migrations
2023-05-15 20:49:10.293820596  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : Migrate "013_create_timeline_table"
2023-05-15 20:49:10.293923551  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : sql ('CREATE TABLE IF NOT EXISTS "timeline" ("timestamp" DATETIME NOT NULL, "camera" VARCHAR(20) NOT NULL, "source" VARCHAR(20) NOT NULL, "source_id" VARCHAR(30), "class_type" VARCHAR(50) NOT NULL, "data" JSON)',)
2023-05-15 20:49:10.294038491  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : sql ('CREATE INDEX IF NOT EXISTS "timeline_camera" ON "timeline" ("camera")',)
2023-05-15 20:49:10.294240841  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : sql ('CREATE INDEX IF NOT EXISTS "timeline_source" ON "timeline" ("source")',)
2023-05-15 20:49:10.294431455  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : sql ('CREATE INDEX IF NOT EXISTS "timeline_source_id" ON "timeline" ("source_id")',)
2023-05-15 20:49:10.294894699  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : Done 013_create_timeline_table
2023-05-15 20:49:10.297669156  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : Migrate "014_event_updates_for_fp"
2023-05-15 20:49:10.297748565  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : add_column ('event', 'score', <FloatField: Event.score>)
2023-05-15 20:49:10.298142387  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : add_column ('event', 'model_hash', <CharField: Event.model_hash>)
2023-05-15 20:49:10.298555165  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : add_column ('event', 'detector_type', <CharField: Event.detector_type>)
2023-05-15 20:49:10.298893217  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : add_column ('event', 'model_type', <CharField: Event.model_type>)
2023-05-15 20:49:10.299163917  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : drop_not_null ('event', 'area')
2023-05-15 20:49:10.785705692  [2023-05-15 20:49:10] peewee_migrate.logs            INFO    : drop_not_null ('event', 'false_positive')
2023-05-15 20:49:11.361163621  [2023-05-15 20:49:11] peewee_migrate.logs            INFO    : apply_default ('event', 'false_positive', <BooleanField: Event.false_positive>)
2023-05-15 20:49:11.403932695  [2023-05-15 20:49:11] peewee_migrate.logs            INFO    : Done 014_event_updates_for_fp
2023-05-15 20:49:12.655034033  [2023-05-15 20:49:12] peewee_migrate.logs            INFO    : Migrate "015_event_refactor"
2023-05-15 20:49:12.655315573  [2023-05-15 20:49:12] peewee_migrate.logs            INFO    : drop_not_null ('event', 'top_score')
2023-05-15 20:49:13.035051250  [2023-05-15 20:49:13] peewee_migrate.logs            INFO    : drop_not_null ('event', 'score')
2023-05-15 20:49:13.369344841  [2023-05-15 20:49:13] peewee_migrate.logs            INFO    : drop_not_null ('event', 'region')
2023-05-15 20:49:13.718750283  [2023-05-15 20:49:13] peewee_migrate.logs            INFO    : drop_not_null ('event', 'box')
2023-05-15 20:49:14.053171763  [2023-05-15 20:49:14] peewee_migrate.logs            INFO    : drop_not_null ('event', 'area')
2023-05-15 20:49:14.386214457  [2023-05-15 20:49:14] peewee_migrate.logs            INFO    : drop_not_null ('event', 'ratio')
2023-05-15 20:49:14.727860517  [2023-05-15 20:49:14] peewee_migrate.logs            INFO    : add_column ('event', 'data', <JSONField: Event.data>)
2023-05-15 20:49:15.186542433  [2023-05-15 20:49:15] peewee_migrate.logs            INFO    : Done 015_event_refactor
2023-05-15 20:49:16.424992479  [2023-05-15 20:49:16] peewee_migrate.logs            INFO    : Migrate "016_sublabel_increase"
2023-05-15 20:49:16.425236246  [2023-05-15 20:49:16] peewee_migrate.logs            INFO    : change_column ('event', 'sub_label', <CharField: Event.sub_label>)
2023-05-15 20:49:16.804633026  [2023-05-15 20:49:16] peewee_migrate.logs            INFO    : Done 016_sublabel_increase
2023-05-15 20:49:18.028227216  [2023-05-15 20:49:18] frigate.app                    INFO    : Recording process started: 594
2023-05-15 20:49:18.030412802  [2023-05-15 20:49:18] frigate.app                    INFO    : go2rtc process pid: 89
2023-05-15 20:49:18.032956439  [2023-05-15 20:49:18] frigate.record.record          INFO    : recording_manager: exiting subprocess
2023-05-15 20:49:18.070030034  [2023-05-15 20:49:18] detector.coral                 INFO    : Starting detection process: 604
2023-05-15 20:49:18.074964404  [2023-05-15 20:49:18] frigate.app                    INFO    : Output process started: 606
2023-05-15 20:49:18.076630325  [2023-05-15 20:49:18] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-15 20:49:18.083250546  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for door: 611
2023-05-15 20:49:18.090259213  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for front: 612
2023-05-15 20:49:18.097841441  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for driveway: 614
2023-05-15 20:49:18.102721577  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for dogs: 616
2023-05-15 20:49:18.108443694  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for backyard_left: 618
2023-05-15 20:49:18.113238935  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for backyard_right: 619
2023-05-15 20:49:18.118478181  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for laundry: 621
2023-05-15 20:49:18.124890687  [2023-05-15 20:49:18] frigate.app                    INFO    : Camera processor started for alfresco: 623
2023-05-15 20:49:18.129659512  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for door: 625
2023-05-15 20:49:18.135588532  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for front: 628
2023-05-15 20:49:18.141116598  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for driveway: 632
2023-05-15 20:49:18.146466746  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for dogs: 637
2023-05-15 20:49:18.152124863  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for backyard_left: 647
2023-05-15 20:49:18.157888534  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for backyard_right: 654
2023-05-15 20:49:18.166686811  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for laundry: 663
2023-05-15 20:49:18.173090770  [2023-05-15 20:49:18] frigate.app                    INFO    : Capture process started for alfresco: 670
2023-05-15 20:49:20.861378735  [2023-05-15 20:49:20] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found

**Comment by NickM-27** [comment]
the docker docs show how to specify the GPU https://docs.docker.com/compose/gpu-support/#access-specific-devices

**Comment by thetravellor** [comment]
No, that does not work.

If I change it to device_ids: ['1'], it still uses 0.

                                                                              
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2991      G   /usr/lib/xorg/Xorg                  8MiB |
|    0   N/A  N/A      3499      G   /usr/bin/gnome-shell                2MiB |
|    0   N/A  N/A   1566310      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1566315      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1566321      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1566328      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1566336      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1566347      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1566354      C   ffmpeg                             95MiB |
|    0   N/A  N/A   1566369      C   ffmpeg                             95MiB |
|    1   N/A  N/A      2991      G   /usr/lib/xorg/Xorg                  3MiB |
+-----------------------------------------------------------------------------+

**Comment by NickM-27** [comment]
You'll likely also need to set the env variable `NVIDIA_VISIBLE_DEVICES: 1`

**Comment by thetravellor** [comment]
Set that in .env and restarted the container, still using Card 0.

**Comment by NickM-27** [comment]
Okay, then you can try making your hwaccel_args `-hwaccel cuda -hwaccel_output_format cuda -gpu 1`

**Comment by thetravellor** [comment]
May I ask what the correct yaml syntax is?

I tried:

` 
door:
    ffmpeg:
      hwaccel_args:
        #      hwaccel_args: preset-nvidia-h264
      input_args:
        - hwaccel cuda
        - hwaccel_output_format cuda
        - gpu 1
        - -c:v
        - h264_cuvid
`

And now it just crashes frigate

**Comment by thetravellor** [comment]
> the docker docs show how to specify the GPU https://docs.docker.com/compose/gpu-support/#access-specific-devices

I have followed that specific guide, it does not work.

**Comment by NickM-27** [comment]
there's a lot wrong with this:
1. you should not be putting -c:v 
2. these are supposed to be hwaccel args, not input args
3. you can't create a list like that.

It should just be

```
` ``
door:
    ffmpeg:
      hwaccel_args: -hwaccel cuda -hwaccel_output_format cuda -gpu 1
```
```
