### ISSUE TITLE
[Camera Support]: Lorex Doorbell Stops Functioning When Setup To Use Go2RTC

### ISSUE THREAD

**Issue by liamstears** [blakeblackshear/frigate#6512]
### Describe the problem you are having

I have the Lorex Doorbell, when setup normally it works perfectly fine but for some reason when setup with Go2RTC and WebRTC the doorbell function stops working. The doorbell itself shows a green flashing light indicating the microphone is being used. Opening the Lorex app and clicking the "talk" button it says the microphone is already in use. This means button pushes on the doorbell do nothing. When setup normally though it functions as normal. I can only assume that when setup using Go2RTC that it accesses the microphone in some other way causing a conflict? I hope this can be looked into and will provide any information I can to assist and will try any suggestions given to me...

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: *REDACTED*
  user: *REDACTED*
  password: *REDACTED*
detectors:
  coral_pci:
    type: edgetpu
    device: pci
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    doorbell: 
      - rtsp://*REDACTED*/cam/realmonitor?channel=1&subtype=0
    driveway: 
      - rtsp://*REDACTED*/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:driveway#audio=aac"
  webrtc:
    candidates:
      - *REDACTED*:8555
cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1920
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: motion
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1440
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 30
          mode: motion
```

### Relevant log output

```shell
Logs show no errors.
```

### FFprobe output from your camera

```shell
Metadata:
    title           : Media Server
  Duration: N/A, start: 0.120000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Lorex 2K Wired Video Doorbell B451AJDB-EG
