### ISSUE TITLE
ffmpeg No new recording segments were created for in the last 120s. restarting the ffmpeg record process...

### ISSUE THREAD

**Issue by mikey6283** [blakeblackshear/frigate#6521]
### Describe the problem you are having

  After finally updating to go2rtc. The Frigate ui has all cameras but I am unable to obtain or see recordings as i continuously get these error which i am unable to solve. I can see some events on  the camera. Recordings state "No Recordings Found

Make sure you have enabled the record role in your configuration for the BackGarden camera." I have record enabled in my config ?
I have trawled various issues on github page without finding a solution.

Any help would be appreciated

### Version

0.12.00 -DA3F197

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.xx.xxx:5000/api/config/schema



detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db

record:
  expire_interval: 20

ui:
  live_mode: mse
go2rtc:
  streams:
    koipond: ffmpeg:rtsp://admin:Koipond1@xxxxxxxxx:554/h264Preview_01_main
      - "ffmpeg:koipond#audio=opus"
    koipond_sub: ffmpeg:rtsp://admin:Koipond1@xxxxxxx:554/h264Preview_01_sub
    front: ffmpeg:rtsp://admin:Front1@1xxxxxxxx:554/h264Preview_01_main
      - "ffmpeg:front#audio=opus"
    front_sub: ffmpeg:rtsp://admin:Front1@xxxxxx:554/h264Preview_01_sub
    garage: ffmpeg:rtsp://admin:Garage1@xxxxxx/h264Preview_01_main
      - "ffmpeg:garage#audio=opus"
    garage_sub: ffmpeg:rtsp://admin:Garage1@xxxxxx/h264Preview_01_sub
    BackGarden: ffmpeg:rtsp://admin:BackGarden1@xxxxx:554/h264Preview_01_main
      - "ffmpeg:garage#audio=opus"
    BackGarden_sub: ffmpeg:rtsp://admin:BackGarden1@10.10.75.26/h264Preview_01_sub    
cameras:
  koipond:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/koipond?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/koipond_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
```

### Relevant log output

```shell
023-05-17 17:22:52.022933929  [2023-05-17 17:22:52] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-17 17:22:52.057106631  [2023-05-17 17:22:52] watchdog.garage                ERROR   : No new recording segments were created for garage in the last 120s. restarting the ffmpeg record process...
2023-05-17 17:22:52.057591034  [2023-05-17 17:22:52] watchdog.garage                INFO    : Terminating the existing ffmpeg process...
2023-05-17 17:22:52.057592956  [2023-05-17 17:22:52] watchdog.garage                INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-17 17:23:01.875137365  [2023-05-17 17:23:01] watchdog.front                 ERROR   : No new recording segments were created for front in the last 120s. restarting the ffmpeg record process...
2023-05-17 17:23:01.875140727  [2023-05-17 17:23:01] watchdog.front                 INFO    : Terminating the existing ffmpeg process...
2023-05-17 17:23:01.875142401  [2023-05-17 17:23:01] watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-17 17:23:01.893359621  [2023-05-17 17:23:01] watchdog.BackGarden            ERROR   : No new recording segments were created for BackGarden in the last 120s. restarting the ffmpeg record process...
2023-05-17 17:23:01.893363086  [2023-05-17 17:23:01] watchdog.BackGarden            INFO    : Terminating the existing ffmpeg process...
2023-05-17 17:23:01.893364942  [2023-05-17 17:23:01] watchdog.BackGarden            INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-17 17:23:02.033683923  [2023-05-17 17:23:02] watchdog.koipond               ERROR   : No new recording segments were created for koipond in the last 120s. restarting the ffmpeg record process...
2023-05-17 17:23:02.033853003  [2023-05-17 17:23:02] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-17 17:23:02.033855390  [2023-05-17 17:23:02] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-17 17:23:02.064172662  [2023-05-17 17:23:02] watchdog.garage                ERROR   : No new recording segments were created for garage in the last 120s. restarting the ffmpeg record process...
2023-05-17 17:23:02.064333344  [2023-05-17 17:23:02] watchdog.garage                INFO    : Terminating the existing ffmpeg process...
2023-05-17 17:23:02.064336006  [2023-05-17 17:23:02] watchdog.garage                INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
Tried the link in the ui FFprobe no joy.
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink 410 & 520

**Comment by NickM-27** [comment]
I also noticed you are using the rtsp stream from reolink which is not recommended, it is recommended to use http-flv

**Comment by mikey6283** [comment]
I have reset to http://   I cannot get to Frigate Ui errors. 
`# yaml-language-server: $schema=http://192.168.55.15:5000/api/config/schema


mqtt:
  host: 192.168.55.51
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db

record:
  expire_interval: 20
go2rtc:
  streams:
    garage:
      - http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Garage1
      - "ffmpeg:garage#audio=opus"
    garage_sub:
      - http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Garage1

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-http-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video=copy
          input_args: preset-http-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 10

[_frigate_logs (6).txt](https://github.com/blakeblackshear/frigate/files/11501782/_frigate_logs.6.txt)

**Comment by NickM-27** [comment]
Those are nginx logs not frigate logs, would need to see frigate logs from the frigate webUI

**Comment by mikey6283** [comment]
Frigate webui does not open with the http://, this is the problem i have had since setting up this new update. i'll included  logs from frigate docker ? How can i obtain frigate logs?
`023-05-17 22:05:08.261432523  192.168.55.15 - - [17/May/2023:22:05:08 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.3 aiohttp/3.8.4 Python/3.10" "-"
2023-05-17 22:05:13.261010361  2023/05/17 22:05:13 [error] 127#127: *738 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.15, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.55.51:5000"
2023-05-17 22:05:13.261047143  192.168.55.15 - - [17/May/2023:22:05:13 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.3 aiohttp/3.8.4 Python/3.10" "-"
2023-05-17 22:05:18.261437191  2023/05/17 22:05:18 [error] 127#127: *738 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.15, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.55.51:5000"
2023-05-17 22:05:18.261484286  192.168.55.15 - - [17/May/2023:22:05:18 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.3 aiohttp/3.8.4 Python/3.10" "-"
2023-05-17 22:05:23.261239047  2023/05/17 22:05:23 [error] 127#127: *738 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.15, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.55.51:5000"
2023-05-17 22:05:23.261292627  192.168.55.15 - - [17/May/2023:22:05:23 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.3 aiohttp/3.8.4 Python/3.10" "-"
2023-05-17 22:05:28.260820749  2023/05/17 22:05:28 [error] 127#127: *738 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.15, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.55.51:5000"
2023-05-17 22:05:28.260839534  192.168.55.15 - - [17/May/2023:22:05:28 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.3 aiohttp/3.8.4 Python/3.10" "-"
2023-05-17 22:05:33.260494128  2023/05/17 22:05:33 [error] 127#127: *738 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.15, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.55.51:5000"
2023-05-17 22:05:33.260542180  192.168.55.15 - - [17/May/2023:22:05:33 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.3 aiohttp/3.8.4 Python/3.10" "-"
2023-05-17 22:05:38.260612599  2023/05/17 22:05:38 [error] 127#127: *738 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.15, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.55.51:5000"
2023-05-17 22:05:38.260633547  192.168.55.15 - - [17/May/2023:22:05:38 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.3 aiohttp/3.8.4 Python/3.10" "-"  I  see in these logs reference to HomeAssistant. i don't no why?

**Comment by NickM-27** [comment]
that's because you are using `input_args: preset-http-restream` which is incorrect, that is only used if you are using the http stream direclty in frigate

**Comment by mikey6283** [comment]
I appreciate your time and effort in  helping so  I reverted back to http// and the following are the errors  i am getting from Frigate UI  and these are the error that i am getting. I noticed on the system  page that  it stated that i have to:
[Hardware acceleration has not been setup, see the docs to setup hardware acceleration.](https://docs.frigate.video/configuration/hardware_acceleration)![Screenshot 2023-05-18 at 10 10 28]
(https://github.com/blakeblackshear/frigate/assets/88946206/e487f330-6428-421b-b2d7-37fd75cf29a9)

` # yaml-language-server: $schema=http://192.168.55.51:5000/api/config/schema

mqtt:
  host: 192.168.55.51
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db

record:
  expire_interval: 20


go2rtc:
  streams:
    reolink:
      - http://xxxxxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Koipond1
      - "ffmpeg:koipond#audio=opus"
    reolink_sub:
      - http://xxxxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Koipond1

cameras:
  koipond:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/koipond?video=copy&audio=opus
          input_args: preset-rstp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/koipond_sub?video=copy
          input_args: preset-rstp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 10
`-05-18 10:05:58.315235343  [2023-05-18 10:05:58] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-18 10:05:58.315236919  [2023-05-18 10:05:58] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-18 10:05:58.317475458  [2023-05-18 10:05:58] frigate.video                  ERROR   : koipond: Unable to read frames from ffmpeg process.
2023-05-18 10:05:58.317793972  [2023-05-18 10:05:58] frigate.video                  ERROR   : koipond: ffmpeg process is not running. exiting capture thread...
2023-05-18 10:06:08.321246824  [2023-05-18 10:06:08] watchdog.koipond               ERROR   : Ffmpeg process crashed unexpectedly for koipond.
2023-05-18 10:06:08.321337681  [2023-05-18 10:06:08] watchdog.koipond               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-18 10:06:08.321537988  [2023-05-18 10:06:08] ffmpeg.koipond.detect          ERROR   : [rtsp @ 0x55ce80acbb40] method DESCRIBE failed: 404 Not Found
2023-05-18 10:06:08.321588554  [2023-05-18 10:06:08] ffmpeg.koipond.detect          ERROR   : rtsp://127.0.0.1:8554/koipond_sub?video=copy: Server returned 404 Not Found
2023-05-18 10:06:08.336009422  [2023-05-18 10:06:08] watchdog.koipond               ERROR   : No new recording segments were created for koipond in the last 120s. restarting the ffmpeg record process...
2023-05-18 10:06:08.336583569  [2023-05-18 10:06:08] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-18 10:06:08.336586451  [2023-05-18 10:06:08] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-18 10:06:08.338265225  [2023-05-18 10:06:08] frigate.video                  ERROR   : koipond: Unable to read frames from ffmpeg process.
2023-05-18 10:06:08.338511315  [2023-05-18 10:06:08] frigate.video                  ERROR   : koipond: ffmpeg process is not running. exiting capture thread...
2023-05-18 10:06:18.343003056  [2023-05-18 10:06:18] watchdog.koipond               ERROR   : Ffmpeg process crashed unexpectedly for koipond.
2023-05-18 10:06:18.343255538  [2023-05-18 10:06:18] watchdog.koipond               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-18 10:06:18.343258252  [2023-05-18 10:06:18] ffmpeg.koipond.detect          ERROR   : [rtsp @ 0x55d6ffed7b40] method DESCRIBE failed: 404 Not Found
2023-05-18 10:06:18.343260176  [2023-05-18 10:06:18] ffmpeg.koipond.detect          ERROR   : rtsp://127.0.0.1:8554/koipond_sub?video=copy: Server returned 404 Not Found
2023-05-18 10:06:18.361791820  [2023-05-18 10:06:18] watchdog.koipond               ERROR   : No new recording segments were created for koipond in the last 120s. restarting the ffmpeg record process...
2023-05-18 10:06:18.361795377  [2023-05-18 10:06:18] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-18 10:06:18.361797059  [2023-05-18 10:06:18] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-18 10:06:18.364064029  [2023-05-18 10:06:18] frigate.video                  ERROR   : koipond: Unable to read frames from ffmpeg process.
2023-05-18 10:06:18.364337569  [2023-05-18 10:06:18] frigate.video                  ERROR   : koipond: ffmpeg process is not running. exiting capture thread...
2023-05-18 10:06:28.373098616  [2023-05-18 10:06:28] watchdog.koipond               ERROR   : Ffmpeg process crashed unexpectedly for koipond.
2023-05-18 10:06:28.373102334  [2023-05-18 10:06:28] watchdog.koipond               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-18 10:06:28.373104130  [2023-05-18 10:06:28] ffmpeg.koipond.detect          ERROR   : [rtsp @ 0x5627944e7b40] method DESCRIBE failed: 404 Not Found
2023-05-18 10:06:28.373105916  [2023-05-18 10:06:28] ffmpeg.koipond.detect          ERROR   : rtsp://127.0.0.1:8554/koipond_sub?video=copy: Server returned 404 Not Found
2023-05-18 10:06:28.387861598  [2023-05-18 10:06:28] watchdog.koipond               ERROR   : No new recording segments were created for koipond in the last 120s. restarting the ffmpeg record process...
2023-05-18 10:06:28.387865159  [2023-05-18 10:06:28] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-18 10:06:28.387866869  [2023-05-18 10:06:28] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-18 10:06:28.391209794  [2023-05-18 10:06:28] frigate.video                  ERROR   : koipond: Unable to read frames from ffmpeg process.
2023-05-18 10:06:28.391580634  [2023-05-18 10:06:28] frigate.video                  ERROR   : koipond: ffmpeg process is not running. exiting capture thread...
2023-05-18 10:06:38.394181855  [2023-05-18 10:06:38] watchdog.koipond               ERROR   : Ffmpeg process crashed unexpectedly for koipond.
2023-05-18 10:06:38.394185513  [2023-05-18 10:06:38] watchdog.koipond               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-18 10:06:38.394187301  [2023-05-18 10:06:38] ffmpeg.koipond.detect          ERROR   : [rtsp @ 0x556d4dac4b40] method DESCRIBE failed: 404 Not Found
2023-05-18 10:06:38.394189004  [2023-05-18 10:06:38] ffmpeg.koipond.detect          ERROR   : rtsp://127.0.0.1:8554/koipond_sub?video=copy: Server returned 404 Not Found
2023-05-18 10:06:38.408521870  [2023-05-18 10:06:38] watchdog.koipond               ERROR   : No new recording segments were created for koipond in the last 120s. restarting the ffmpeg record process...
2023-05-18 10:06:38.408525751  [2023-05-18 10:06:38] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-18 10:06:38.408527457  [2023-05-18 10:06:38] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-18 10:06:38.410664144  [2023-05-18 10:06:38] frigate.video                  ERROR   : koipond: Unable to read frames from ffmpeg process.
2023-05-18 10:06:38.411003793  [2023-05-18 10:06:38] frigate.video                  ERROR   : koipond: ffmpeg process is not running. exiting capture thread...
2023-05-18 10:06:48.414973782  [2023-05-18 10:06:48] watchdog.koipond               ERROR   : Ffmpeg process crashed unexpectedly for koipond.
2023-05-18 10:06:48.414977156  [2023-05-18 10:06:48] watchdog.koipond               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-18 10:06:48.414978912  [2023-05-18 10:06:48] ffmpeg.koipond.detect          ERROR   : [rtsp @ 0x5591f7acdb40] method DESCRIBE failed: 404 Not Found
2023-05-18 10:06:48.414980577  [2023-05-18 10:06:48] ffmpeg.koipond.detect          ERROR   : rtsp://127.0.0.1:8554/koipond_sub?video=copy: Server returned 404 Not Found
2023-05-18 10:06:48.428960946  [2023-05-18 10:06:48] watchdog.koipond               ERROR   : No new recording segments were created for koipond in the last 120s. restarting the ffmpeg record process...
2023-05-18 10:06:48.429452057  [2023-05-18 10:06:48] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-18 10:06:48.429454765  [2023-05-18 10:06:48] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-18 10:06:48.431507652  [2023-05-18 10:06:48] frigate.video                  ERROR   : koipond: Unable to read frames from ffmpeg process.
2023-05-18 10:06:48.431808395  [2023-05-18 10:06:48] frigate.video                  ERROR   : koipond: ffmpeg process is not running. exiting capture thread...
2023-05-18 10:06:58.435519355  [2023-05-18 10:06:58] watchdog.koipond               ERROR   : Ffmpeg process crashed unexpectedly for koipond.
2023-05-18 10:06:58.435523056  [2023-05-18 10:06:58] watchdog.koipond               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-18 10:06:58.435524792  [2023-05-18 10:06:58] ffmpeg.koipond.detect          ERROR   : [rtsp @ 0x5592a5a8bb40] method DESCRIBE failed: 404 Not Found
2023-05-18 10:06:58.435526493  [2023-05-18 10:06:58] ffmpeg.koipond.detect          ERROR   : rtsp://127.0.0.1:8554/koipond_sub?video=copy: Server returned 404 Not Found
2023-05-18 10:06:58.449646123  [2023-05-18 10:06:58] watchdog.koipond               ERROR   : No new recording segments were created for koipond in the last 120s. restarting the ffmpeg record process...
2023-05-18 10:06:58.449649923  [2023-05-18 10:06:58] watchdog.koipond               INFO    : Terminating the existing ffmpeg process...
2023-05-18 10:06:58.449651547  [2023-05-18 10:06:58] watchdog.koipond               INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-18 10:06:58.451118537  [2023-05-18 10:06:58] frigate.video                  ERROR   : koipond: Unable to read frames from ffmpeg process.
2023-05-18 10:06:58.451345770  [2023-05-18 10:06:58] frigate.video                  ERROR   : koipond: ffmpeg process is not running. exiting capture thread...

**Comment by blakeblackshear** [comment]
You are using a path of `rtsp://127.0.0.1:8554/koipond_sub?video=copy` which tells Frigate to pull a stream named `koipond_sub` from go2rtc, but you dont have a stream named `koipond_sub` in your go2rtc streams. That's why you are getting a 404 not found error.

```yaml
go2rtc:
  streams:
    reolink:
      - http://xxxxxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Koipond1
      - "ffmpeg:koipond#audio=opus"
    reolink_sub:
      - http://xxxxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Koipond1
```

You should update your go2rtc config to be:
```yaml
go2rtc:
  streams:
    koipond:
      - http://xxxxxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Koipond1
      - "ffmpeg:koipond#audio=opus"
    koipond_sub:
      - http://xxxxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Koipond1
```
