### ISSUE TITLE
[Support]: Docker Compose - Unable to start Frigate

### ISSUE THREAD

**Issue by rosstroha** [blakeblackshear/frigate#6535]
### Describe the problem you are having

I am unable to start Frigate from docker compose. It freezes when first starting via docker compose.

The container just hangs when starting, preventing other containers in the compose file from starting.

I started commenting out certain portions of `docker-compose.yml` and found that the container will start if I remove:
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              count: 1
              capabilities: [gpu]
```

Unfortunately it hangs when trying to get log output via `docker logs frigate`

docker-compose:
```
   frigate:
     container_name: frigate
     privileged: true 
     restart: unless-stopped
     image: ghcr.io/blakeblackshear/frigate:stable
     shm_size: "200mb"
     devices:
       - /dev/dri/renderD128:/dev/dri/renderD128
       - /dev/dri/card0:/dev/dri/card0
       - /dev/bus/usb:/dev/bus/usb
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /<local dir>:/config/config.yml
       - /media/nas/frigate:/media/frigate
       - type: tmpfs # Optional: 8GB of memory, reduces SSD/SD Card wear
         target: /tmp/cache
         tmpfs:
           size: 8000000000
     ports:
       - "5000:5000"
       - "8554:8554" # RTSP feeds
       - "8555:8555/udp" # WebRTC over udp
       - "8555:8555/tcp" # WebRTC over tcp
     environment:
       FRIGATE_RTSP_PASSWORD: "removed"
       NVIDIA_VISIBLE_DEVICES: all
       NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
         #runtime: nvidia
     deploy:
       resources:
         reservations:
           devices:
             - capabilities: [gpu]
               driver: nvidia
               count: 1
```

### Version

0.12

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a
