### ISSUE TITLE
[Detector Support]: usb coral not detected

### ISSUE THREAD

**Issue by andrewzah** [blakeblackshear/frigate#6537]
### Describe the problem you are having

My coral USB is not detected.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com
cameras:
  x:
    ffmpeg:
      inputs:
        - path: rtsp://x:x@x.x.x.x:554/h264Preview_01_main
database:
  path: /db/frigate.db
detectors:
  coral:
    type: edgetpu
    device: usb
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    # 2023-05-18
    image: ghcr.io/blakeblackshear/frigate:stable
    environment:
      FRIGATE_MQTT_USER: "mqtt"
      FRIGATE_MQTT_PASSWORD: "mqtt"
      FRIGATE_MQTT_RTSP_USER: "rtsp"
      FRIGATE_MQTT_RTSP_PASSWORD: "rtsp"
    volumes:
      - "~/docker/services/frigate/config.yml:/config/config.yml:rw"
      - "~/docker/data/frigate/storage/:/media/frigate/:rw"
      - "~/docker/data/frigate/db/:/db/:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - type: "tmpfs"
        target: "/tmp/cache"
        tmpfs:
          size: 1000000000
    restart: 'unless-stopped'
    #cap_add:
    #  - CAP_PERFMON
    privileged: true
    ports:
      - "5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
```

### Relevant log output

```shell
frigate  | 2023-05-19 03:44:20.831427668  [2023-05-19 03:44:20] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
frigate  | 2023-05-19 03:44:20.832122235  Traceback (most recent call last):
frigate  | 2023-05-19 03:44:20.832134115    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
frigate  | 2023-05-19 03:44:20.832145716      delegate = Delegate(library, options)
frigate  | 2023-05-19 03:44:20.832147976    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
frigate  | 2023-05-19 03:44:20.832148996      raise ValueError(capture.message)
frigate  | 2023-05-19 03:44:20.832157526  ValueError
frigate  | 2023-05-19 03:44:20.832158256  
frigate  | 2023-05-19 03:44:20.832159216  During handling of the above exception, another exception occurred:
frigate  | 2023-05-19 03:44:20.832159876  
frigate  | 2023-05-19 03:44:20.832160676  Traceback (most recent call last):
frigate  | 2023-05-19 03:44:20.832161696    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2023-05-19 03:44:20.832162466      self.run()
frigate  | 2023-05-19 03:44:20.832163416    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2023-05-19 03:44:20.832175246      self._target(*self._args, **self._kwargs)
frigate  | 2023-05-19 03:44:20.832177006    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
frigate  | 2023-05-19 03:44:20.832178156      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2023-05-19 03:44:20.832184096    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
frigate  | 2023-05-19 03:44:20.832185126      self.detect_api = create_detector(detector_config)
frigate  | 2023-05-19 03:44:20.832186196    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
frigate  | 2023-05-19 03:44:20.832187126      return api(detector_config)
frigate  | 2023-05-19 03:44:20.832189086    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
frigate  | 2023-05-19 03:44:20.832190726      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
frigate  | 2023-05-19 03:44:20.832191886    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
frigate  | 2023-05-19 03:44:20.832192876      raise ValueError('Failed to load delegate from {}\n{}'.format(
frigate  | 2023-05-19 03:44:20.832193816  ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I'm running Proxmox (`pve-manager/7.2-3/c743d6c1 (running kernel: 5.15.30-2-pve)`), with an LXC running AlmaLinux 8.7 (in the RHEL/centos family), which is running docker.

I have tried mounting both `/dev/bus/usb` as a volume, and as a device mapping. I have run the container with `privileged: true`.

For lsusb on the proxmox host and the docker host, the output looks like:
```
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 18d1:9302 Google Inc.
```
for lsusb **in the container**:
```
Bus 001 Device 001: ID 1d6b:0002 Linux 5.15.30-2-pve xhci-hcd xHCI Host Controller
Bus 001 Device 004: ID 18d1:9302  
```

On the proxmox host, I installed the runtime and pycoral library from [the coral docs](https://coral.ai/docs/accelerator/get-started/#1-install-the-edge-tpu-runtime) and udev rules. And reinserted the USB and rebooted the proxmox host machine.
```
# cat /etc/udev/rules.d/99-edgetpu-accelerator.rules 
SUBSYSTEM=="usb",ATTRS{idVendor}=="1a6e",ATTRS{idProduct}=="089a",GROUP="plugdev"
SUBSYSTEM=="usb",ATTRS{idVendor}=="18d1",ATTRS{idProduct}=="9302",GROUP="plugdev
```
I also ran the coral example demo successfully.
```
python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
```
and for my lxc.conf:
```
# cat /etc/pve/lxc/101.conf
...
lxc.cgroup.devices.allow: c188:* rwm
lxc.cgroup2.devices.allow: c189:* rwm
lxc.cgroup.devices.allow: c226:* rwm
lxc.mount.entry: /dev/bus/usb/001 dev/bus/usb/001 none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.mount.auto: cgroup:rw
lxc.cgroup2.devices.allow: a
```

in the container:
```
# ls -la /dev/bus/usb/001/004 
crw-rw---- 1 nobody nogroup 189, 3 May 19 03:42 /dev/bus/usb/001/004
```
