### ISSUE TITLE
WARNING : Unable to create clip for backyard and event 1611878221.375039-x750pm. There were no cache files for this event.

### ISSUE THREAD

**Issue by Chick3nFingDing** [blakeblackshear/frigate#654]
Getting these errors and no clips are saving:

`frigate.events                 WARNING : Unable to create clip for backyard and event 1611878221.375039-x750pm. There were no cache files for this event.`

```
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: 'rtsp://10.10.0.54:8554/unicast'
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5
    motion:
      mask:
        - '638,0,902,0,1280,0,1280,279,982,270,811,270,427,290,437,208,489,179'
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      crop: false
      retain:
        default: 10
        objects:
          person: 15
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
```
