### ISSUE TITLE
Resize cameras in the Birdseye View

### ISSUE THREAD

**Issue by tyzbit** [blakeblackshear/frigate#6556]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to resize individual cameras in the BirdsEye view. I've found #1926 searching through issues and this seems very adjacent to it. I saw the response that this happens on the backend, but perhaps the backend can be tricked by scaling the cameras' views before they are rendered. Just a thought.

**Describe the solution you'd like**
In the configuration for the cameras under the new `birdseye` section, there would be another setting called `scaling` that would be a multiplier for both the width and height. A `float` would give the most granularity, but even an `integer` would unlock some powerful configurations.

The user would enter a number to scale the video in both width and height. For example, if each video feed in BirdsEye happens to render in the canvas at 640x360, if you entered `scaling: 2` for one camera, that camera would render at 1280x720 and thus be twice the size of all of the other cameras. If you only did that with one camera, instead of a normal 3x3 configuration, one camera could be 2x2 in the top left and the rest could fill in each of the last space in rows one and two and then there would be a normal 1x3 in the bottom row.

Like this:
| Camera 1 | Camera 1 | Camera2 |
|----------|-----------|--------|
| Camera 1 | Camera 1 | Camera3 |
| Camera 4 | Camera5 | Camera6 |

**Describe alternatives you've considered**
The already existing feature of switching to cameras with motion automatically fulfills some of the need of being able to see a camera in more detail, but relies on Frigate detecting something of interest and cannot show you the other feeds while one is selected.

**Potential pitfalls**
If users have cameras with different aspect ratios, it would be tedious to figure out the right scaling. Then again, I honestly don't know what BirdsEye looks like without matching ratios, maybe it's something that could help that situation.

**Additional context**
This is an example of a configuration that would be possible by scaling the feeds (found randomly on a search engine):
![video feeds](http://blog.camerasecuritynow.com/wp-content/uploads/2014/11/pss-view.jpg)
The (simplified) config for this would be 
```
cam1:
  birdseye:
    order: 1
    scaling: 1
cam2:
  birdseye:
    order: 2
    scaling: 1
cam3:
  birdseye:
    order: 3
    scaling: 1
cam4:
  birdseye:
    order: 4
    scaling: 0.5
cam5:
  birdseye:
    order: 5
    scaling: 0.5
cam6:
  birdseye:
    order: 6
    scaling: 0.5
cam7:
  birdseye:
    order: 7
    scaling: 0.5
  ```
