### ISSUE TITLE
Ability to specify multiple storage locations

### ISSUE THREAD

**Issue by GrinchUA** [blakeblackshear/frigate#6557]
I would like to be able to use multiple ways to store records.
It will be useful when there are several disks on the device.

It would also be nice to be able to change the storage location for each camera.

**Comment by blakeblackshear** [comment]
We should probably just adjust the storage folders so camera is at the top level so this can be done with docker mounts easily.

**Comment by HIhnen** [comment]
> We should probably just adjust the storage folders so camera is at the top level so this can be done with docker mounts easily.

That would be perfect to distribute the recordings over multiple SSDs in a mini PC.
Please do so. 👍

**Comment by awisur** [comment]
This would greatly improve speed and usability when having several cameras with lots of activity.

**Comment by thunderwolf66102** [comment]
Keep running into sporadic 'dropped segments'  despite disks/raid and hardware seemingly being up to the task.  This may help.  Could a separate record maintainer be run for each storage area as well?

**Comment by NickM-27** [comment]
it's very unlikely if your hardware is up to the task for it to be anything directly related to the recordings maintainer. That error can happen for any number of different reasons

**Comment by NickM-27** [comment]
> I would like to record on my NVMe device, and then move the recordings after like 1 day to my HDD's as archive.

this is not what this feature request is aiming at solving. And this use case can already be done using a filesystem like fuse.fs on the host, I have a setup that works exactly this way

**Comment by supercom32** [comment]
I would also like to add that this problem gets exacerbated the more cameras you have in service. Specifically, the retention time of all cameras decreases, the more cameras you bring online. This is especially true for SSD setups where SSD size is usually much more limited than conventional HDDs. Being able to specify multiple locations would eliminate this problem.

**Comment by SamMousa** [comment]
> Being able to specify multiple locations would eliminate this problem.

You could use something like mergerfs: https://github.com/trapexit/mergerfs

It'll allow you to spread the load over your disks without Frigate being aware; it allows for different strategies to spread the files across disks as well.

**Comment by NickM-27** [comment]
If it was possible this issue would be closed as completed. For now the only way to do this is to create a virtual file system using something like mergefs or fuse.fs

**Comment by jpoet** [comment]
> If it was possible this issue would be closed as completed. For now the only way to do this is to create a virtual file system using something like mergefs or fuse.fs

I am willing to work on this, but am brand new to Frigate. Is there a "developer" doc somewhere that describes how the pieces fit together?

I am thinking that the best way would to be specify a recording location as part of each camera configuration. This location would be relative to RECORD_DIR (aka BASE_DIR/recordings):
```
cameras:
  name_of_your_camera:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp
          roles:
            - detect
        - path: rtsp://10.0.10.10:554/high_res_stream # <----- Add stream you want to record from
          roles:
            - record
    detect: ...
    record: # <----- Enable recording
      enabled: True
      storage: some/path
    motion: ...
```
Then the various utilities that do things like disk cleanup would need to be modified to recursively look at the tree under RECORD_DIR.

Thoughts?
