### ISSUE TITLE
[Support]: Frigate ffmpeg process getting "out of memory" killed

### ISSUE THREAD

**Issue by rb2k** [blakeblackshear/frigate#6560]
### Describe the problem you are having

I don't really expect a response, but I thought I'd document some of the stuff I'm currently poking at just in case someone else ends up searching and wants to add something :)

As you can see in the [full dmesg output](https://gist.github.com/rb2k/3e09ff3e9d622eca52e24fc69a2c367b), I am seeing a frigate ffmpeg process getting killed relatively regularily. Somewhere between 30 min and 2 hours:

```
[Sun May 21 02:34:34 2023] Memory cgroup out of memory: Killed process 7572 (ffmpeg) total-vm:8929920kB, anon-rss:7281508kB, file-rss:64828kB, shmem-rss:0kB, UID:0 pgtables:14824kB oom_score_adj:0
[Sun May 21 04:45:34 2023] Memory cgroup out of memory: Killed process 22660 (ffmpeg) total-vm:8807968kB, anon-rss:7180680kB, file-rss:65044kB, shmem-rss:0kB, UID:0 pgtables:14616kB oom_score_adj:0
[Sun May 21 05:13:43 2023] Memory cgroup out of memory: Killed process 24629 (ffmpeg) total-vm:8766436kB, anon-rss:7081188kB, file-rss:65316kB, shmem-rss:0kB, UID:0 pgtables:14432kB oom_score_adj:0
[Sun May 21 06:47:12 2023] Memory cgroup out of memory: Killed process 29536 (ffmpeg) total-vm:9096000kB, anon-rss:7025192kB, file-rss:65060kB, shmem-rss:0kB, UID:0 pgtables:14380kB oom_score_adj:0
[Sun May 21 08:27:32 2023] Memory cgroup out of memory: Killed process 9657 (ffmpeg) total-vm:9072060kB, anon-rss:6997752kB, file-rss:65432kB, shmem-rss:0kB, UID:0 pgtables:14336kB oom_score_adj:0
[Sun May 21 08:29:00 2023] Memory cgroup out of memory: Killed process 5386 (ffmpeg) total-vm:9120396kB, anon-rss:7035984kB, file-rss:65172kB, shmem-rss:0kB, UID:0 pgtables:14396kB oom_score_adj:0
```

One interesting thing to note is that I've been having issues with one of my cameras (the "side_yard_frigate" is a wyze cam through "docker-wyze-bridge"). It usually shows up without frames at the moment.

A ps aux at a random point in time shows this:
```
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    212    76 ?        Ss   May20   0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
root        15  0.0  0.0    212    68 ?        S    May20   0:00 s6-supervise s6-linux-init-shutdownd
root        16  0.0  0.0    200     4 ?        Ss   May20   0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C 
root        24  0.0  0.0    212    60 ?        S    May20   0:00 s6-supervise s6rc-oneshot-runner
root        25  0.0  0.0    212    68 ?        S    May20   0:00 s6-supervise s6rc-fdholder
root        26  0.0  0.0    212    68 ?        S    May20   0:00 s6-supervise frigate
root        27  0.0  0.0    212    64 ?        S    May20   0:00 s6-supervise frigate-log
root        28  0.0  0.0    212    64 ?        S    May20   0:00 s6-supervise go2rtc
root        29  0.0  0.0    212    64 ?        S    May20   0:00 s6-supervise go2rtc-healthcheck
root        30  0.0  0.0    212    64 ?        S    May20   0:00 s6-supervise go2rtc-log
root        31  0.0  0.0    212    64 ?        S    May20   0:00 s6-supervise nginx
root        32  0.0  0.0    212    68 ?        S    May20   0:00 s6-supervise nginx-log
root        41  0.0  0.0    524   172 ?        Ss   May20   0:00 /package/admin/s6-2.11.3.0/command/s6-fdholderd -1 -i data/rules
root        42  0.0  0.0    188     4 ?        Ss   May20   0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access
nobody      80  0.0  0.0    276   112 ?        Ss   May20   0:00 s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx
nobody      81  0.0  0.0    280   136 ?        Ss   May20   0:00 s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate
nobody      82  0.0  0.0    276   112 ?        Ss   May20   0:00 s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc
root        89 13.9  0.0 728452 28164 ?        Ssl  May20 133:14 /usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml
root        97  0.0  0.0   3892  2864 ?        Ss   May20   0:00 bash ./run.user go2rtc-healthcheck
root        98  3.5  0.3 3416788 232884 ?      Ssl  May20  33:44 python3 -u -m frigate
root       117  0.0  0.0 581680 13168 ?        Ss   May20   0:00 nginx: master process nginx
root       134  0.0  0.0 647788  5892 ?        Sl   May20   0:01 nginx: worker process
root       135  0.0  0.0 647924  6072 ?        Sl   May20   0:00 nginx: worker process
root       136  0.0  0.0 647788  5944 ?        Sl   May20   0:00 nginx: worker process
root       138  0.0  0.0 647788  4856 ?        Sl   May20   0:00 nginx: worker process
root       153  0.0  0.0 647788  4856 ?        Sl   May20   0:00 nginx: worker process
root       185  0.0  0.0 647788  4856 ?        Sl   May20   0:00 nginx: worker process
root       227  0.0  0.0 647788  4856 ?        Sl   May20   0:00 nginx: worker process
root       272  0.0  0.0 647788  4856 ?        Sl   May20   0:00 nginx: worker process
root       310  0.0  0.0 647788  4860 ?        Sl   May20   0:00 nginx: worker process
root       336  0.0  0.0 647788  4860 ?        Sl   May20   0:00 nginx: worker process
root       361  0.0  0.0 647788  4860 ?        Sl   May20   0:00 nginx: worker process
root       403  0.0  0.0 647788  4860 ?        Sl   May20   0:00 nginx: worker process
root       562  1.0  0.0 130484 31640 ?        Ss   02:01   5:49 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root       570  0.0  0.1 1123672 78412 ?       S    May20   0:09 frigate.logger
root       576  0.2  0.0  14256 10236 ?        S    May20   2:50 /usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(47)
root       577  0.3  0.1 1482920 107620 ?      Sl   May20   3:22 frigate.detector.coral
root       579  1.6  0.1 1872472 97928 ?       Sl   May20  15:45 frigate.output
root       582  0.0  0.0 126820 22092 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -f mpegts -s 960x720 -code
root       583  0.4  0.1 2008480 108156 ?      Sl   May20   3:57 frigate.process:garage_frigate
root       587  0.4  0.1 2003416 102468 ?      Sl   May20   4:08 frigate.process:attic_upstairs_frigate
root       588  0.4  0.1 2007584 107828 ?      Sl   May20   4:18 frigate.process:frontdoor_frigate
root       589  0.0  0.0 126820 20008 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -c
root       590  0.6  0.1 2004900 104956 ?      Sl   May20   6:01 frigate.process:outdoor_pool_right_frigate
root       591  0.0  0.0 126820 21332 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -f mpegts -s 960x720 -code
root       592  0.6  0.1 2005144 105524 ?      Sl   May20   6:06 frigate.process:outdoor_pool_left_frigate
root       593  0.8  0.1 2005316 105892 ?      Sl   May20   8:05 frigate.process:street_frigate
root       594  0.0  0.0 126820 21332 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -code
root       595  0.0  0.1 2028204 128656 ?      Sl   May20   0:43 frigate.process:side_yard_frigate
root       596  0.0  0.0 126820 22184 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -code
root       597  1.2  0.1 2024304 125032 ?      Sl   May20  11:44 frigate.process:sqwrlcam_frigate
root       598  1.0  0.1 1542660 95520 ?       Sl   May20   9:56 frigate.capture:garage_frigate
root       599  0.0  0.0 126820 18672 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -code
root       602  2.5  0.1 1544816 100948 ?      Sl   May20  24:20 frigate.capture:attic_upstairs_frigate
root       606  1.0  0.1 1542660 96292 ?       Sl   May20   9:39 frigate.capture:frontdoor_frigate
root       607  0.0  0.0 126820 19768 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -c
root       613  0.9  0.1 1542228 94652 ?       Sl   May20   9:05 frigate.capture:outdoor_pool_right_frigate
root       617  0.0  0.0 126820 21940 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -c
root       620  0.9  0.1 1542228 94608 ?       Sl   May20   9:12 frigate.capture:outdoor_pool_left_frigate
root       624  0.0  0.0 126820 20468 ?        Ss   May20   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -co
root       627  0.9  0.1 1542228 94652 ?       Sl   May20   9:16 frigate.capture:street_frigate
root       644  0.2  0.1 1541776 102728 ?      Sl   May20   2:46 frigate.capture:side_yard_frigate
root       652  2.7  0.1 1544816 107244 ?      Sl   May20  26:09 frigate.capture:sqwrlcam_frigate
root      5356  4.4  0.2 1858932 188592 ?      Ssl  02:34  24:07 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root      8048  0.5  0.0 130244 34900 ?        Ss   10:19   0:25 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root      8771  2.0  0.2 1841848 133616 ?      Ssl  10:25   1:21 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     18895  0.0  0.0   2576   936 pts/0    Ss   11:30   0:00 sh
root     18973  0.0  0.0   2488   912 ?        S    11:30   0:00 sleep 30s
root     19043  0.3  0.0   7104  2980 ?        S    11:30   0:00 top -b -n 2
root     19069  0.0  0.0   6496  1504 pts/0    R+   11:30   0:00 ps aux
root     32607  4.6  0.2 2197164 195188 ?      Ssl  09:28   5:43 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     32690  1.6  0.2 1646912 133596 ?      Ssl  02:01   9:14 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     32691  1.5  0.1 1706276 122608 ?      Ssl  02:01   8:45 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     32692  1.3  0.1 1706256 125920 ?      Ssl  02:01   7:44 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     32693  1.4  0.1 1638812 127600 ?      Ssl  02:01   8:01 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     32698  1.3  0.0 131252 31280 ?        Ss   02:01   7:35 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     32700  0.8  0.0 130396 30568 ?        Ss   02:01   4:51 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
root     32701  0.8  0.0 130952 31724 ?        Ss   02:01   5:05 ffmpeg -hide_banner -loglevel error -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -h
```

From here and the overview page, I can't see any of the cameras actually using much more than the others.

The next thing I'm trying to do is removing 'hwaccel' as just as shot in the dark.
This setup as been pretty stable for me through most of the 12 betas. I am not quite sure what changed recently.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
# Optional: detectors configuration
# USB Coral devices will be auto detected with CPU fallback
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb

# Required: mqtt configuration
mqtt:
  # Required: host name
  host: [...]
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: mqtt
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}. 
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: [...]

record:
  enabled: true
  retain:
    days: 14
    mode: motion
  events:
    retain:
      default: 14
      mode: motion
      objects:
        person: 30

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args:
    - -hide_banner
    - -loglevel
    - error
  # hwaccel_args: preset-vaapi

model:
  labelmap:
    15: animal # bird
    16: animal # cat
    17: animal # dog
    18: animal # horse
    19: animal # sheep
    22: animal # bear

# Optional: Global object filters for all cameras.
# NOTE: can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - animal
  filters:
    person:
      threshold: 0.80

go2rtc:
  streams:
    garage_frigate:
      - rtsp://[...]/h264Preview_01_main
    attic_upstairs_frigate:
      - rtsp://[...]/ch0_0.h264
    frontdoor_frigate:
      - http://[...]/flv?port=1935&app=bcs&stream=channel0_main.bcs&[...]
      - ffmpeg:reolink#audio=opus
    frontdoor_frigate_sub:
      - http://192.168.1.78/flv?port=1935[...]
    outdoor_pool_right_frigate:
      - rtsp://[...]:554/h264Preview_01_main
    outdoor_pool_left_frigate:
      - rtsp://[...]:554/h264Preview_01_main
    street_frigate:
      - rtsp://[...]:554/h264Preview_01_main
    side_yard_frigate:
      - rtsp://[...]:28554/side-yard-cam
    sqwrlcam_frigate:
      - rtsp://[...]/ch0_0.h264
cameras:
  garage_frigate:
    ffmpeg:
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://[...]:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/garage_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      fps: 5
      height: 672
      width: 896
    record:
      events:
        retain:
          mode: motion

  attic_upstairs_frigate:
    motion:
      contour_area: 125
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/attic_upstairs_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 5
      height: 1080
      width: 1920
    record:
      events:
        retain:
          mode: motion

  frontdoor_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frontdoor_frigate_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://localhost:8554/frontdoor_frigate?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      fps: 5
      height: 672
      width: 896
    record:
      events:
        retain:
          mode: motion

  outdoor_pool_right_frigate:
    motion:
      contour_area: 40
      mask:
        - 231,284,147,261,38,232,0,244,0,347,42,375
        - 640,42,434,25,408,126,481,207,640,235
        - 127,54,366,23,402,79
    ffmpeg:
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://[...]:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/outdoor_pool_right_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      fps: 7
      height: 480
      width: 640
    record:
      events:
        retain:
          mode: motion


  outdoor_pool_left_frigate:
    motion:
      contour_area: 40
      mask:
        - 528,0,493,122,200,75,61,85,0,41,0,0
    ffmpeg:
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://[...]:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/outdoor_pool_left_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      fps: 7
      height: 480
      width: 640
    record:
      events:
        retain:
          mode: motion

  street_frigate:
    motion:
      contour_area: 40
    ffmpeg:
      inputs:
        - path: rtsp://[...]:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/street_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      fps: 7
      height: 480
      width: 640
    record:
      events:
        retain:
          mode: motion

  side_yard_frigate:
    motion:
      contour_area: 40
      mask:
        - 1920,1080,1920,805,1854,794,1758,918,1747,1080
        - 1449,402,1158,334,1082,245,1109,146,1140,25,1261,0,1467,0,1539,22,1584,108,1672,216,1602,358,1691,461,1581,433
        - 204,1080,0,1080,0,0,370,0,682,0,632,278

    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/side_yard_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 5
      height: 1080
      width: 1920
    record:
      events:
        retain:
          mode: motion
  sqwrlcam_frigate:
    ffmpeg:
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://localhost:8554/sqwrlcam_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      threshold: 40
      mask:
        - 1282,0,1920,0,1920,385,1528,461,561,585,491,764,449,1080,0,1080,0,457,0,157,0,0
    detect:
      fps: 5
      height: 1080
      width: 1920
    record:
      events:
        retain:
          mode: motion


timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
```

### Relevant log output

```shell
[Sun May 21 08:29:00 2023] Memory cgroup out of memory: Killed process 5386 (ffmpeg) total-vm:9120396kB, anon-rss:7035984kB, file-rss:65172kB, shmem-rss:0kB, UID:0 pgtables:14396kB oom_score_adj:0
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://u:p@ip:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000313, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 59.94 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"attic_upstairs_frigate":{"camera_fps":5.0,"capture_pid":602,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":5356,"pid":587,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"1":{"cpu":"0.0","mem":"0.0"},"117":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"138":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"153":{"cpu":"0.0","mem":"0.1"},"16":{"cpu":"0.0","mem":"0.0"},"185":{"cpu":"0.0","mem":"0.1"},"18895":{"cpu":"0.0","mem":"0.0"},"20385":{"cpu":"4.7","mem":"2.2"},"21113":{"cpu":"0.0","mem":"0.0"},"21127":{"cpu":"1.3","mem":"0.4"},"21134":{"cpu":"0.0","mem":"0.0"},"21137":{"cpu":"0.3","mem":"0.0"},"21148":{"cpu":"0.0","mem":"0.0"},"227":{"cpu":"0.0","mem":"0.1"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"272":{"cpu":"0.0","mem":"0.1"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"0.0","mem":"0.1"},"32":{"cpu":"0.0","mem":"0.0"},"32690":{"cpu":"1.3","mem":"1.6"},"32691":{"cpu":"1.3","mem":"1.5"},"32692":{"cpu":"1.3","mem":"1.5"},"32693":{"cpu":"1.3","mem":"1.5"},"32698":{"cpu":"1.3","mem":"0.4"},"32700":{"cpu":"0.7","mem":"0.4"},"32701":{"cpu":"1.0","mem":"0.4"},"336":{"cpu":"0.0","mem":"0.1"},"361":{"cpu":"0.0","mem":"0.1"},"403":{"cpu":"0.0","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"5356":{"cpu":"4.3","mem":"2.2"},"562":{"cpu":"1.0","mem":"0.4"},"570":{"cpu":"0.0","mem":"0.9"},"576":{"cpu":"0.3","mem":"0.1"},"577":{"cpu":"2.0","mem":"1.3"},"579":{"cpu":"1.3","mem":"1.2"},"582":{"cpu":"0.0","mem":"0.3"},"583":{"cpu":"0.3","mem":"1.3"},"587":{"cpu":"0.3","mem":"1.2"},"588":{"cpu":"0.3","mem":"1.3"},"589":{"cpu":"0.0","mem":"0.2"},"590":{"cpu":"0.3","mem":"1.3"},"591":{"cpu":"0.0","mem":"0.3"},"592":{"cpu":"0.3","mem":"1.3"},"593":{"cpu":"0.7","mem":"1.3"},"594":{"cpu":"0.0","mem":"0.3"},"595":{"cpu":"0.0","mem":"1.5"},"596":{"cpu":"0.0","mem":"0.3"},"597":{"cpu":"5.0","mem":"1.5"},"598":{"cpu":"1.0","mem":"1.1"},"599":{"cpu":"0.0","mem":"0.2"},"602":{"cpu":"2.3","mem":"1.2"},"606":{"cpu":"0.7","mem":"1.1"},"607":{"cpu":"0.0","mem":"0.2"},"613":{"cpu":"1.0","mem":"1.1"},"617":{"cpu":"0.0","mem":"0.3"},"620":{"cpu":"0.7","mem":"1.1"},"624":{"cpu":"0.0","mem":"0.2"},"627":{"cpu":"1.0","mem":"1.1"},"644":{"cpu":"0.0","mem":"1.2"},"652":{"cpu":"2.3","mem":"1.3"},"80":{"cpu":"0.0","mem":"0.0"},"8048":{"cpu":"1.0","mem":"0.4"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"8771":{"cpu":"2.0","mem":"1.6"},"89":{"cpu":"14.0","mem":"0.3"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"4.3","mem":"3.0"},"Tasks:":{"cpu":"stopped,","mem":"0.0"}},"detection_fps":6.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.26,"pid":577}},"frontdoor_frigate":{"camera_fps":5.0,"capture_pid":606,"detection_enabled":1,"detection_fps":1.8,"ffmpeg_pid":8771,"pid":588,"process_fps":5.0,"skipped_fps":0.0},"garage_frigate":{"camera_fps":5.0,"capture_pid":598,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":32690,"pid":583,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"amd-vaapi":{"gpu":"5.00 %","mem":"65.27 %"}},"outdoor_pool_left_frigate":{"camera_fps":7.0,"capture_pid":620,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":32693,"pid":592,"process_fps":7.0,"skipped_fps":0.0},"outdoor_pool_right_frigate":{"camera_fps":7.1,"capture_pid":613,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":32692,"pid":590,"process_fps":7.1,"skipped_fps":0.0},"service":{"last_updated":1684683690,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":2127.7,"mount_type":"tmpfs","total":2147.5,"used":19.8},"/media/frigate/clips":{"free":324434.1,"mount_type":"fuse.shfs","total":1024208.5,"used":699071.4},"/media/frigate/recordings":{"free":324434.1,"mount_type":"fuse.shfs","total":1024208.5,"used":699071.4},"/tmp/cache":{"free":33376.1,"mount_type":"tmpfs","total":33392.4,"used":16.3}},"temperatures":{},"uptime":57939,"version":"0.12.0-da3e197"},"side_yard_frigate":{"camera_fps":0.0,"capture_pid":644,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":21127,"pid":595,"process_fps":0.2,"skipped_fps":0.0},"sqwrlcam_frigate":{"camera_fps":5.1,"capture_pid":652,"detection_enabled":1,"detection_fps":4.9,"ffmpeg_pid":20385,"pid":597,"process_fps":5.1,"skipped_fps":0.0},"street_frigate":{"camera_fps":7.2,"capture_pid":627,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":32691,"pid":593,"process_fps":7.2,"skipped_fps":0.0}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink / 1 wyze
