### ISSUE TITLE
[Support]: Birdsview in restream mse mode keeps stuttering/buffering

### ISSUE THREAD

**Issue by xnr13** [blakeblackshear/frigate#6562]
### Describe the problem you are having

I have a problem with birdsview restream in mse mode (player?) that works perfectly fine on single camera live feeds, but has issues in birdsview mode. No matter how few cameras i activate, it seems that the mse player constantly runs out of data and is buffering trying to get more. Note: jsmpeg and webrtc are not affected and work well in all cases, both for single-camera view and in birdsview. In birdsview, browser dev console has a lot of calls to a cached "loading" spinners, but actually i think that's a consequence, not the cause.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  enabled: False

record:
  enabled: True
  retain:
    days: 365
    mode: motion

snapshots:
  enabled: True
  retain:
    default: 365

birdseye:
  enabled: True
  restream: True
  width: 1920
  height: 1080
  mode: continuous

go2rtc:
  streams:
    Camera1: 
      - http://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
      - "ffmpeg:Camera1#audio=opus"
    Camera1_sub: 
      - http://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}

cameras:
  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera1?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Camera1_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      Driveway:
        coordinates: 0,480,640,480,640,0,0,0

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy


detect:
  enabled: True
  width: 640
  height: 480

motion:
  mask: 470,0,470,50,168,50,168,0

ui:
  live_mode: mse
```

### Relevant log output

```shell
2023-05-21 20:42:14.923963976  [INFO] Starting Frigate...
2023-05-21 20:42:15.673137255  [2023-05-21 20:42:15] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-21 20:42:15.687117465  [2023-05-21 20:42:15] peewee_migrate                 INFO    : Starting migrations
2023-05-21 20:42:15.690298241  [2023-05-21 20:42:15] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-21 20:42:15.697993489  [2023-05-21 20:42:15] detector.cpu                   INFO    : Starting detection process: 432
2023-05-21 20:42:15.698937906  [2023-05-21 20:42:15] frigate.app                    INFO    : Output process started: 434
2023-05-21 20:42:15.700252374  [2023-05-21 20:42:15] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-05-21 20:42:15.702081607  [2023-05-21 20:42:15] frigate.app                    INFO    : Camera processor started for Camera1: 437
2023-05-21 20:42:15.705070236  [2023-05-21 20:42:15] frigate.app                    INFO    : Capture process started for Camera1: 439
```

### FFprobe output from your camera

```shell
ffprobe version 4.1.10-0+deb10u1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flv, from 'http://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=edited':
  Metadata:
    displayWidth    : 2560
    displayHeight   : 1920
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 29 fps, 30 tbr, 1k tbn
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"Camera1":{"camera_fps":5.1,"capture_pid":439,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":444,"pid":437,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.4"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"0.3","mem":"0.4"},"114":{"cpu":"0.0","mem":"0.1"},"133":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"14":{"cpu":"0.0","mem":"0.0"},"143":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"157":{"cpu":"0.0","mem":"0.0"},"176":{"cpu":"0.0","mem":"0.0"},"186":{"cpu":"0.0","mem":"0.0"},"199":{"cpu":"0.0","mem":"0.0"},"23":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"39":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"426":{"cpu":"0.0","mem":"0.2"},"431":{"cpu":"0.3","mem":"0.0"},"432":{"cpu":"0.0","mem":"0.3"},"434":{"cpu":"10.3","mem":"0.3"},"437":{"cpu":"0.3","mem":"0.3"},"438":{"cpu":"0.0","mem":"0.1"},"439":{"cpu":"0.7","mem":"0.3"},"443":{"cpu":"6.3","mem":"0.2"},"444":{"cpu":"8.3","mem":"0.1"},"450":{"cpu":"1.3","mem":"0.1"},"555":{"cpu":"0.0","mem":"0.0"},"574":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"5.3","mem":"0.1"},"95":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"27454.0","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":36.73,"pid":432}},"service":{"last_updated":1684691027,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":100.6,"mount_type":"tmpfs","total":104.9,"used":4.2},"/media/frigate/clips":{"free":202679.4,"mount_type":"ext4","total":240891.4,"used":25900.9},"/media/frigate/recordings":{"free":202679.4,"mount_type":"ext4","total":240891.4,"used":25900.9},"/tmp/cache":{"free":992.7,"mount_type":"tmpfs","total":1000.0,"used":7.3}},"temperatures":{},"uptime":92,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-520

### Any other information that may be helpful

Updated question, because copied wrong config
