### ISSUE TITLE
[Support]: Frigate Integration stopped working after upgrading Home Assistant to 2023.05.X

### ISSUE THREAD

**Issue by Bhgp-git** [blakeblackshear/frigate#6568]
### Describe the problem you are having

The integration stopped working after updating to home assistant 2023.05.X. I have already tried mutiple versions (2023.05.01 and the latest 2023.05.03). It works again after downgrading to 2023.04.X.

The addon is working perfectly even though the integration isn't. I have already tried to restart and reinstall the integration without success.

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.ABC.XYZ
  user: addons
  password: XXX

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic-audio-aac

rtmp:
  enabled: False

cameras:
  Front_Door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://ABC@192.168.XXX/live # <----- Update for your camera
          roles:
            - detect
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 2.5
    motion:
      mask:
        - 1920,1080,1920,0,639,0,637,622,675,617,670,1080
    snapshots: # <----- Enable snapshots
      enabled: True
  Terrasse: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://ABC@192.168.XXX/live # <----- Update for your camera
          roles:
            - detect
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 2.5
    motion:
      mask:
        - 1389,1000,1512,1005,1524,704,1530,391,1447,0,1920,0,1920,962,1920,1080,1387,1080
        - 93,711,321,332,459,158,670,76,979,0,769,0,692,0,410,0,0,0,0,479,0,932
    snapshots: # <----- Enable snapshots
      enabled: True
  Keller: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://ABC@192.168.XXX/live # <----- Update for your camera
          roles:
            - detect
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 2.5
    snapshots: # <----- Enable snapshots
      enabled: False
  3D-Printer: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://ABC@192.168.XXX/live # <----- Update for your camera
          roles:
            - detect
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 2.5
    snapshots: # <----- Enable snapshots
      enabled: False
```

### Relevant log output

```shell
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/frigate/__init__.py:235
Integration: Frigate (documentation, issues)
First occurred: 09:11:53 (3 occurrences)
Last logged: 13:14:23

Error setting up entry ccab4aaf-frigate-fa:5000 for frigate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/frigate/__init__.py", line 235, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Not relevant

### Any other information that may be helpful

I was also getting a DNS error from the integration before reinstalling. Now I am not receiving it anymore
