### ISSUE TITLE
[Config Support]: Zoom recorded output

### ISSUE THREAD

**Issue by Anujan** [blakeblackshear/frigate#6589]
### Describe the problem you are having

I'm trying to zoom my camera while recording and I'm getting the following ffmpeg errors. Any help would be appreciated

### Version

0.12.0-da3e197

### Frigate config file

```yaml
---
mqtt:
  host: 172.17.0.1
  user: homeassistant
  password: "{FRIGATE_MQTT_PASSWORD}"
birdseye:
  enabled: true
  mode: continuous
cameras:
  front-porch:
    enabled: false
    ffmpeg:
      output_args: >
        -vf "segment, scale=2*iw:-1, crop=iw/2:ih/2" -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an
      inputs:
        - path: rtsp://172.17.0.1:8554/front-porch
          roles:
            - detect
            - record
  myla-cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://172.17.0.1:8554/myla-cam
          roles:
            - record
record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 30
      mode: motion
```

### Relevant log output

```shell
frigate  | 2023-05-23 16:51:46.607250952  [2023-05-23 16:51:46] watchdog.myla-cam              ERROR   : Ffmpeg process crashed unexpectedly for myla-cam.
frigate  | 2023-05-23 16:51:46.608602513  [2023-05-23 16:51:46] watchdog.myla-cam              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-05-23 16:51:46.608614972  [2023-05-23 16:51:46] ffmpeg.myla-cam.detect         ERROR   : [Parsed_segment_0 @ 0x55c2677ac880] Neither timestamps nor durations nor counts supplied.
frigate  | 2023-05-23 16:51:46.608622354  [2023-05-23 16:51:46] ffmpeg.myla-cam.detect         ERROR   : [AVFilterGraph @ 0x55c2676d0ac0] Error initializing filter 'segment'
frigate  | 2023-05-23 16:51:46.608636366  [2023-05-23 16:51:46] ffmpeg.myla-cam.detect         ERROR   : Error reinitializing filters!
frigate  | 2023-05-23 16:51:46.608679249  [2023-05-23 16:51:46] ffmpeg.myla-cam.detect         ERROR   : Failed to inject frame into filter network: Invalid argument
frigate  | 2023-05-23 16:51:46.608686110  [2023-05-23 16:51:46] ffmpeg.myla-cam.detect         ERROR   : Error while processing the decoded data for stream #0:0
frigate  | 2023-05-23 16:51:46.798115202  [2023-05-23 16:51:46] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
