### ISSUE TITLE
[Support]: Watching a clip before segments are moved should not make the clip permanently unavailable

### ISSUE THREAD

**Issue by zerkms** [blakeblackshear/frigate#6591]
### Describe the problem you are having

I started using Frigate several days ago, and so far - I love it!

Yet, sometimes Frigate does not save the clip for the event

```
sqlite> select id, label, datetime(start_time, 'unixepoch') from event where not has_clip;
1684643917.439834-ibpvt3|car|2023-05-21 04:38:32
1684729851.453507-nclvhz|person|2023-05-22 04:30:46
1684731678.988898-1theto|car|2023-05-22 05:01:13
1684735222.814856-r17b5d|person|2023-05-22 06:00:17
1684893514.028145-kwbxnl|car|2023-05-24 01:58:29
```

I actually witnessed the latest one `2023-05-24 01:58:29`: I was watching the debug screen - and the car was driving on the road. It was correctly labelled as a car, the event was created, the snapshot captured, yet the clip hasn't been saved.

I record all the motion, and the motion-recorded video is there and available to be watched.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: <redacted>
  user: <redacted>
  password: <redacted>


cameras:
  garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://<redacted>
          roles:
            - detect
        - path: rtsp://<redacted>
          roles:
            - record
    zones:
      street:
        coordinates: 1280,0,1280,291,0,328,0,0
      driveway:
        coordinates: 0,720,1280,720,1280,285,0,327

detect:
  enabled: True
  width: 1280
  height: 720
  fps: 4
  stationary:
    interval: 60
    max_frames:
      default: 400

motion:
  contour_area: 22
  frame_height: 120
  mask:
    - 0,0,380,0,380,32,0,32           # timestamp

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - cat
    - dog
  filters:
    person:
      min_score: 0.3
      threshold: 0.4
      min_area: 6500
      max_area: 197000
      mask:
        - 305,350,305,415,0,415,0,350     # our letter box
        - 1280,0,1280,90,1204,90,1204,0   # right neighbours car park (triggers false person)
    car:
      min_score: 0.3
      threshold: 0.4
      min_area: 5000
      mask:
        - 1280,0,1280,245,1080,245,1080,0 # right neighbours park and right our side park
        - 142,0,0,0,0,110,141,88          # left neihghbours park
    bicycle:
      min_score: 0.1
      threshold: 0.1
    motorcycle:
      min_score: 0.1
      threshold: 0.1
    bus:
      min_score: 0.1
      threshold: 0.1
    cat:
      min_score: 0.1
      threshold: 0.1
      max_area: 170000
    dog:
      min_score: 0.4
      threshold: 0.55

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 60
      mode: all
    required_zones:
      - driveway
      - street

snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 60
```

### Relevant log output

```shell
Around time when it happened - there is no anything logged (but I run the instance with default logging settings)
```

### FFprobe output from your camera

```shell
$ ffprobe rtsp://admin:Vtldtl12@192.168.1.64/Streaming/channels/102
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://<redacted>':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.250000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 4 fps, 20 tbr, 90k tbn
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.0"},"1":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"1.0","mem":"2.0"},"110":{"cpu":"0.0","mem":"0.0"},"117":{"cpu":"0.0","mem":"0.2"},"1222":{"cpu":"0.0","mem":"0.0"},"1259":{"cpu":"0.0","mem":"0.0"},"1275":{"cpu":"0.3","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.3"},"136":{"cpu":"0.0","mem":"0.3"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"283":{"cpu":"0.0","mem":"1.0"},"289":{"cpu":"0.7","mem":"0.1"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.0","mem":"1.3"},"292":{"cpu":"1.0","mem":"1.2"},"295":{"cpu":"1.7","mem":"1.2"},"296":{"cpu":"0.0","mem":"0.2"},"297":{"cpu":"3.3","mem":"1.1"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"0.0","mem":"0.2"},"302":{"cpu":"17.6","mem":"0.8"},"308":{"cpu":"0.7","mem":"0.3"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"90":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"6020.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":85.13,"pid":290}},"garage":{"camera_fps":4.1,"capture_pid":297,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":302,"pid":295,"process_fps":4.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"0.42 %","mem":"- %"}},"service":{"last_updated":1684894464,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":266.3,"mount_type":"tmpfs","total":268.4,"used":2.1},"/media/frigate/clips":{"free":152438.5,"mount_type":"ext4","total":2535374.4,"used":2258344.0},"/media/frigate/recordings":{"free":152438.5,"mount_type":"ext4","total":2535374.4,"used":2258344.0},"/tmp/cache":{"free":997.3,"mount_type":"tmpfs","total":1000.0,"used":2.7}},"temperatures":{},"uptime":766,"version":"0.12.0-da3e197"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hilook ipc-t250h
