### ISSUE TITLE
[Support]: mqtt event was sent, but it's not in sqlite or the UI

### ISSUE THREAD

**Issue by zerkms** [blakeblackshear/frigate#6593]
### Describe the problem you are having

I have received a bogus MQTT message to the `frigate/events` topic:

```yaml
  payload_json:
    before:
      id: 1684920219.692261-h8rbd9
      camera: garage
      frame_time: 1684920219.692261
      snapshot_time: 0
      label: car
      sub_label: null
      top_score: 0
      false_positive: true
      start_time: 1684920219.692261
      end_time: null
      score: 0.546875
      box:
        - 0
        - 26
        - 1279
        - 719
      area: 886347
      ratio: 1.8455988455988457
      region:
        - 0
        - 0
        - 1608
        - 1608
      stationary: false
      motionless_count: 0
      position_changes: 0
      current_zones: []
      entered_zones: []
      has_clip: false
      has_snapshot: false
    after:
      id: 1684920219.692261-h8rbd9
      camera: garage
      frame_time: 1684920219.932542
      snapshot_time: 1684920219.932542
      label: car
      sub_label: null
      top_score: 0.546875
      false_positive: false
      start_time: 1684920219.692261
      end_time: null
      score: 0.55859375
      box:
        - 3
        - 14
        - 1279
        - 719
      area: 899580
      ratio: 1.8099290780141843
      region:
        - 0
        - 0
        - 1644
        - 1644
      stationary: false
      motionless_count: 1
      position_changes: 0
      current_zones:
        - driveway
      entered_zones:
        - driveway
      has_clip: false
      has_snapshot: false
    type: new
```

and the corresponding end:

```yaml
  payload_json:
    before:
      id: 1684920219.692261-h8rbd9
      camera: garage
      frame_time: 1684920219.932542
      snapshot_time: 1684920219.932542
      label: car
      sub_label: null
      top_score: 0.546875
      false_positive: false
      start_time: 1684920219.692261
      end_time: null
      score: 0.55859375
      box:
        - 3
        - 14
        - 1279
        - 719
      area: 899580
      ratio: 1.8099290780141843
      region:
        - 0
        - 0
        - 1644
        - 1644
      stationary: false
      motionless_count: 1
      position_changes: 0
      current_zones:
        - driveway
      entered_zones:
        - driveway
      has_clip: false
      has_snapshot: false
    after:
      id: 1684920219.692261-h8rbd9
      camera: garage
      frame_time: 1684920219.932542
      snapshot_time: 1684920219.932542
      label: car
      sub_label: null
      top_score: 0.546875
      false_positive: false
      start_time: 1684920219.692261
      end_time: 1684920225.178389
      score: 0.55859375
      box:
        - 3
        - 14
        - 1279
        - 719
      area: 899580
      ratio: 1.8099290780141843
      region:
        - 0
        - 0
        - 1644
        - 1644
      stationary: false
      motionless_count: 1
      position_changes: 0
      current_zones:
        - driveway
      entered_zones:
        - driveway
      has_clip: false
      has_snapshot: false
    type: end
```

yet, it does not exist in the UI and sqlite:

```
sqlite> select id, datetime(start_time, 'unixepoch') from event order by start_time desc limit 3;
1684920348.9328-gbjaog|2023-05-24 09:25:43
1684920088.177847-hahwkj|2023-05-24 09:21:23
1684919308.939562-zf7rgc|2023-05-24 09:08:23
```

This looks like a bug.

In the logs (which is with all default settings), there are no entries around the event `start_time` time (only http requests from the clients).

### Version

0.12.0-da3e197

### Frigate config file

```yaml
irrelevant
```

### Relevant log output

```shell
<no>
```

### FFprobe output from your camera

```shell
irrelevant
```

### Frigate stats

```json
irrelevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

irrelevant

**Comment by zerkms** [comment]
> This can happen if there was another event at the same time for another object with the same label.

As you can see from sqlite query - there is no.

```
sqlite> select id, datetime(start_time, 'unixepoch'), datetime(end_time, 'unixepoch') from event order by start_time desc limit 4;
1684924640.818469-hvufd2|2023-05-24 10:37:15|2023-05-24 10:37:39
1684920348.9328-gbjaog|2023-05-24 09:25:43|2023-05-24 09:26:02
1684920088.177847-hahwkj|2023-05-24 09:21:23|2023-05-24 09:21:41
1684919308.939562-zf7rgc|2023-05-24 09:08:23|2023-05-24 09:08:45
```

> This can also happen if your config has required zones. It's totally possible for an event to exist but not be saved due to settings.

Not for this config though (?):

```yaml
cameras:
  garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: <redacted>
          roles:
            - detect
        - path: <redacted>
          roles:
            - record
    zones:
      street:
        coordinates: 1280,0,1280,291,0,328,0,0
      driveway:
        coordinates: 0,720,1280,720,1280,285,0,327

detect:
  enabled: True
  width: 1280
  height: 720
  fps: 4
  stationary:
    interval: 60
    max_frames:
      default: 400

motion:
  contour_area: 22
  frame_height: 120
  mask:
    - 0,0,380,0,380,32,0,32           # timestamp

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - cat
    - dog
  filters:
    person:
      min_score: 0.3
      threshold: 0.4
      min_area: 6500
      max_area: 173000
      mask:
        - 305,350,305,415,0,415,0,350     # our letter box
        - 1280,0,1280,90,1204,90,1204,0   # right neighbours car park (triggers false person)
    car:
      min_score: 0.3
      threshold: 0.4
      min_area: 5000
      mask:
        - 1280,0,1280,245,1080,245,1080,0 # right neighbours park and right our side park
        - 142,0,0,0,0,110,141,88          # left neihghbours park
    bicycle:
      min_score: 0.1
      threshold: 0.1
    motorcycle:
      min_score: 0.1
      threshold: 0.1
    bus:
      min_score: 0.1
      threshold: 0.1
    cat:
      min_score: 0.1
      threshold: 0.1
      max_area: 170000
    dog:
      min_score: 0.4
      threshold: 0.55

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 60
      mode: all

snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 60

```
