### ISSUE TITLE
[Config Support]: Moved from VM to HA yellow - Proxy won't run

### ISSUE THREAD

**Issue by FS1961** [blakeblackshear/frigate#6603]
### Describe the problem you are having

Moved my HA config from a Virtualbox VM to HA Yellow. Everything seems to be working correctly except the Frigate Proxy won't run.

### Version

Proxy version 1.3

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.82
  user: mqtt
  password: haosmqtt

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  Dining: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.59:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
   
  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.36:554/play1.sdp          # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
   
  Front-door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.28:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    motion:
      mask:
        - 431,720,0,720,0,313,271,239
    zones:
      entry_doors:
        coordinates: 749,86,756,159,979,192,987,542,541,720,403,111       
  Drive-way: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t22!@192.168.178.55:554/h264  # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
    motion:
    zones:
      parkplatz:
        coordinates: 1247,532,1735,522,1926,551,2192,506,2560,786,2560,1440,906,1440,896,577
      entry:
        coordinates: 1764,0,1733,522,1008,569,959,0
      
  Patio: # <------ Name the camera.
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t22!@192.168.178.74:554/h264  # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution

  Garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.52:554/h264Preview_01_main # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  events:
    retain:
      default: 10
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Frigate Proxy
 Proxy addon for Frigate
-----------------------------------------------------------
 Add-on version: 1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (aarch64 / yellow)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[06:40:33] INFO: Starting NGinx...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

PCIe

### Any other information that may be helpful

Tried removing and reinstalling the HA add-on, integration, etc. No joy. Oddly the custom Frigate card works. Just can't get the Proxy running in the sidebar.

Ports exposed on Frigate server:
8554
5000
8555
8555
1935
1984

Ports exposed on HA Yellow:
8123
