### ISSUE TITLE
[Support]: The clip video recording doesn't stop after the object(person) disappears

### ISSUE THREAD

**Issue by t0ny-peng** [blakeblackshear/frigate#6604]
### Describe the problem you are having

Today I found a camera recording that last almost one and a half hour. Upon watching the video, it seems that the object `person` is only detected at the first minute of the video, and the rest are all (almost) static images. 

<img width="563" alt="image" src="https://github.com/blakeblackshear/frigate/assets/4816327/a72ff8cb-2ae0-438e-9bf1-984855511d94">

The other problem is that in the Home Assistant entity history, I am not able to see the `person` event occurred at 8:53PM at all. Seems the detection is not synced to Home assistant?

<img width="331" alt="image" src="https://github.com/blakeblackshear/frigate/assets/4816327/1d62e4c0-1113-49f6-b1b7-009e4f19b0bc">

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  fps: 5
  enabled: True

objects:
  track:
    - person
    - cat

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: True
  retain:
    days: 60
    mode: motion
  events:
    retain:
      default: 120
      mode: active_objects

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True

cameras:
  Backyard_1:
    ffmpeg:
      inputs:
        # 8M stream
        - path: XXX
          roles:
            - record
            - rtmp
        # Sub stream
        - path: XXX
          roles:
            - detect
    motion:
      mask:
        - 0,0,640,0,640,42,403,79,279,114,0,314
    detect:
      width: 640
      height: 480
    objects:
      filters:
        person:
          threshold: 0.75
          min_area: 5000
```

### Relevant log output

```shell
No relative log around that time
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"857:482","height":2160,"width":3840}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"857:482","height":480,"width":640}]}}]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua unknown model
