### ISSUE TITLE
[Camera Support]: How to restream using go2rtc and camera udp?

### ISSUE THREAD

**Issue by boyphongsakorn** [blakeblackshear/frigate#6607]
### Describe the problem you are having

i see at go2rtc doc can set input as [rtsp/udp](https://github.com/AlexxIT/go2rtc#:~:text=template%20(ex.%20%23-,input%3Drtsp/udp,-will%20change%20RTSP )
but um.... nothing on screen
Did I do that right?
or go2rtc in frigate is not work with udp?

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.31.227
  user: mqtt
  password: team1556th

environment_vars:
  TZ: Asia/Bangkok

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    sfh_camera:
      - rtsp://admin:xxxxxxxxx@xxx.xxx.xx.xxx:10554/udp/av0_0
      - "ffmpeg:sfh_camera#input=rtsp/udp#video=h264#audio=aac"
    sfh_camera_sub:
      - rtsp://admin:xxxxxxxxx@xxx.xxx.xx.xxx:10554/udp/av0_1
      - "ffmpeg:sfh_camera_sub#input=rtsp/udp#video=h264#audio=aac"
  webrtc:
    candidates:
      - xxx.xxx.xx.xxx:9005

cameras:
  sfh_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sfh_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sfh_camera_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - motorcycle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 2

record:
  enabled: true
  retain:
    days: 7
    mode: all

birdseye:
  enabled: True
  mode: motion

ui:
  live_mode: mse
  timezone: asia/bangkok
```

### Relevant log output

```shell
2023-05-25 07:17:43.009327296  07:17:43.009 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error=EOF url=rtsp://admin:team1556th@192.168.31.109:10554/udp/av0_0
2023-05-25 07:17:43.698492918  07:17:43.698 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error=EOF url=rtsp://admin:team1556th@192.168.31.109:10554/udp/av0_1

2023-05-25 07:19:34.243035490  [2023-05-25 07:19:34] ffmpeg.sfh_camera.detect       ERROR   : rtsp://127.0.0.1:8554/sfh_camera_sub?video=copy&audio=aac: Invalid data found when processing input
2023-05-25 07:19:34.246798416  [2023-05-25 07:19:34] ffmpeg.sfh_camera.record       ERROR   : rtsp://127.0.0.1:8554/sfh_camera?video=copy&audio=aac: Invalid data found when processing input
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:team1556th@192.168.31.109:10554/udp/av0_0':
  Metadata:
    title           : streamed by the VSTARCAM RTSP server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 2304x1296, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Frigate stats

```json
// 20230525141917
// http://xxx.xxx.xx.xxx:xxxx/api/stats

{
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "17": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "32": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "41": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "42": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "80": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "81": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "82": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "89": {
      "cpu": "3.3",
      "mem": "0.0"
    },
    "97": {
      "cpu": "0.7",
      "mem": "0.4"
    },
    "98": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "116": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "134": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "135": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "136": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "138": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "148": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "165": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "195": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "225": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "268": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "310": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "343": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "364": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "571": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "577": {
      "cpu": "0.3",
      "mem": "0.0"
    },
    "578": {
      "cpu": "319.7",
      "mem": "0.2"
    },
    "580": {
      "cpu": "0.3",
      "mem": "0.1"
    },
    "583": {
      "cpu": "10.0",
      "mem": "0.2"
    },
    "584": {
      "cpu": "0.7",
      "mem": "0.1"
    },
    "585": {
      "cpu": "7.7",
      "mem": "0.1"
    },
    "586": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "587": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "590": {
      "cpu": "1.0",
      "mem": "0.1"
    },
    "591": {
      "cpu": "2.3",
      "mem": "0.4"
    },
    "594": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "595": {
      "cpu": "2.7",
      "mem": "0.4"
    },
    "597": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "603": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "605": {
      "cpu": "2.0",
      "mem": "0.0"
    },
    "607": {
      "cpu": "0.3",
      "mem": "0.0"
    },
    "608": {
      "cpu": "3.0",
      "mem": "0.4"
    },
    "610": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "615": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "617": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "619": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "630": {
      "cpu": "8.7",
      "mem": "0.0"
    },
    "631": {
      "cpu": "42.0",
      "mem": "0.1"
    },
    "3002": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "3010": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "3023": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "3026": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "3038": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "3046": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "0.1"
    },
    "MiB": {
      "cpu": "20229.9",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "1"
    },
    "top": {
      "cpu": "users,",
      "mem": "load"
    }
  },
  "detection_fps": 14.0,
  "detectors": {
    "cpu": {
      "detection_start": 1684999154.410697,
      "inference_speed": 76.46,
      "pid": 578
    }
  },
  "dw_camera": {
    "camera_fps": 5.1,
    "capture_pid": 594,
    "detection_enabled": 1,
    "detection_fps": 7.0,
    "ffmpeg_pid": 608,
    "pid": 585,
    "process_fps": 2.6,
    "skipped_fps": 0.0
  },
  "ff_camera": {
    "camera_fps": 5.1,
    "capture_pid": 590,
    "detection_enabled": 1,
    "detection_fps": 0.0,
    "ffmpeg_pid": 595,
    "pid": 584,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "fh_camera": {
    "camera_fps": 5.1,
    "capture_pid": 587,
    "detection_enabled": 1,
    "detection_fps": 7.0,
    "ffmpeg_pid": 591,
    "pid": 583,
    "process_fps": 1.8,
    "skipped_fps": 0.0
  },
  "gpu_usages": {
    "NVIDIA GeForce GT 1030": {
      "gpu": "3 %",
      "mem": "11.1 %"
    }
  },
  "service": {
    "last_updated": 1684999157,
    "latest_version": "0.12.0",
    "storage": {
      "/dev/shm": {
        "free": 54.1,
        "mount_type": "tmpfs",
        "total": 67.1,
        "used": 13.0
      },
      "/media/frigate/clips": {
        "free": 831830.9,
        "mount_type": "zfs",
        "total": 1597552.9,
        "used": 765722.0
      },
      "/media/frigate/recordings": {
        "free": 831830.9,
        "mount_type": "zfs",
        "total": 1597552.9,
        "used": 765722.0
      },
      "/tmp/cache": {
        "free": 831830.9,
        "mount_type": "overlay",
        "total": 871895.1,
        "used": 40064.3
      }
    },
    "temperatures": {
      
    },
    "uptime": 624,
    "version": "0.12.0-da3e197"
  },
  "sfh_camera": {
    "camera_fps": 0.0,
    "capture_pid": 603,
    "detection_enabled": 1,
    "detection_fps": 0.0,
    "ffmpeg_pid": 3038,
    "pid": 586,
    "process_fps": 0.0,
    "skipped_fps": 0.0
  }
}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Vstarcam CS662
