### ISSUE TITLE
[Support]: Debian Legacy IPTables

### ISSUE THREAD

**Issue by eximo84** [blakeblackshear/frigate#6619]
### Describe the problem you are having

Been using Frigate for a while, no problems.  Recently i deployed fail2ban docker and as part of that setup i needed to switch from nftables to legacy-iptables as the string matching for fail2ban isnt supported on fail2ban,  I did this with update-alternatives as outlined here: https://wiki.debian.org/nftables.

After doing this i noticed frigate was down, after trying to recreate the container i got the following error

`Error response from daemon: driver failed programming external connectivity on endpoint frigate (LONG ID NUMBER): (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5855 -j DNAT --to-destination 172.19.0.3:8555 ! -i br-c4773f431cb5: iptables: no chain/target/match by that name.`

After setting the update-alternatives back to nftables frigate can start fine and is working again - however my fail2ban no longer works.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# Global Settings
mqtt:
  host: IP
detectors:
  coral1:
    type: edgetpu
    device: pci
snapshots:
  enabled: true
record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 10

#go2rtc Cemera Streams
go2rtc:
  streams:
    bedroom:
      - rtsp://user:pass@IP/stream1
    bedroom_sub:
      - rtsp://user:pass@IP/stream2
    dining_room:
      - rtsp://user:pass@IP/stream1
    dining_room_sub:
      - rtsp://user:pass@IP/stream2
    meadow:
      - rtsp://IP/ch0_0.h264
  webrtc:
    candidates:
      - HOSTIP:8555
      - stun:8555


#Camera Settings
cameras:
# Bedroom Camera Tapo C110
  bedroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    detect:
      width: 640
      height: 360
      fps: 15
    objects:
      track:
        - person
        - car
      filters:
        person:
          threshold: 0.70
        car:
          mask:
            # Trees and Main Road to avoid non important cars
            - 640,0,640,230,491,215,310,218,108,259,108,360,0,360,0,0
    motion:
      mask:
        # Trees and Main Road
        - 640,0,640,230,491,215,310,218,108,259,108,360,0,360,0,0
    zones:
      parking_area:
        coordinates: 485,351,435,304,544,286,422,231,290,266,321,360
        objects:
          - person
      car_park:
        coordinates: 520,286,640,253,640,236,472,220,434,228
      garden:
        coordinates: 284,281,0,360,640,360,640,257,439,310,463,342,323,360
        objects:
          - person
# Dining Room Camera Tapo C110
  dining_room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/dining_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dining_room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    detect:
      width: 640
      height: 360
      fps: 15
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.76
    motion:
      mask:
        - 640,166,640,0,0,0,0,155,119,109,170,147
# Meadow Camera YiHome 1080p
  meadow:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/meadow
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
```

### Relevant log output

```shell
Error response from daemon: driver failed programming external connectivity on endpoint frigate (LONG ID NUMBER): (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5855 -j DNAT --to-destination 172.19.0.3:8555 ! -i br-c4773f431cb5: iptables: no chain/target/match by that name.
```

### FFprobe output from your camera

```shell
n/a - not a camera issue
```

### Frigate stats

```json
{"bedroom":{"camera_fps":15.1,"capture_pid":312,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":324,"pid":295,"process_fps":15.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.8"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"8.3","mem":"1.0"},"119":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"139":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"283":{"cpu":"0.0","mem":"0.5"},"289":{"cpu":"1.0","mem":"0.1"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.0","mem":"0.7"},"292":{"cpu":"2.7","mem":"0.6"},"295":{"cpu":"2.7","mem":"0.6"},"298":{"cpu":"2.7","mem":"0.6"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.1"},"301":{"cpu":"0.7","mem":"0.6"},"31":{"cpu":"0.0","mem":"0.0"},"312":{"cpu":"2.7","mem":"0.5"},"313":{"cpu":"0.0","mem":"0.1"},"316":{"cpu":"2.7","mem":"0.5"},"317":{"cpu":"0.0","mem":"0.1"},"319":{"cpu":"1.3","mem":"0.5"},"32":{"cpu":"0.0","mem":"0.0"},"322":{"cpu":"0.0","mem":"0.1"},"324":{"cpu":"22.7","mem":"0.3"},"325":{"cpu":"22.0","mem":"0.3"},"337":{"cpu":"0.7","mem":"0.1"},"338":{"cpu":"0.7","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"597":{"cpu":"91.0","mem":"0.4"},"80":{"cpu":"0.0","mem":"0.0"},"807":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"840":{"cpu":"0.3","mem":"0.0"},"842":{"cpu":"0.0","mem":"0.0"},"848":{"cpu":"0.7","mem":"0.0"},"89":{"cpu":"4.3","mem":"0.1"},"MiB":{"cpu":"7978.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":2.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":9.05,"pid":290}},"dining_room":{"camera_fps":15.1,"capture_pid":316,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":325,"pid":298,"process_fps":15.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"3.63 %","mem":"- %"}},"meadow":{"camera_fps":2.7,"capture_pid":319,"detection_enabled":1,"detection_fps":2.0,"ffmpeg_pid":597,"pid":301,"process_fps":2.7,"skipped_fps":0.0},"service":{"last_updated":1685084410,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":64.1,"mount_type":"tmpfs","total":67.1,"used":3.0},"/media/frigate/clips":{"free":680391.6,"mount_type":"btrfs","total":4000652.8,"used":3316332.1},"/media/frigate/recordings":{"free":680391.6,"mount_type":"btrfs","total":4000652.8,"used":3316332.1},"/tmp/cache":{"free":998.2,"mount_type":"tmpfs","total":1000.0,"used":1.8}},"temperatures":{"apex_0":43.3},"uptime":487,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Mixed

### Camera make and model

Various - Not a camera issue
