### ISSUE TITLE
[Support]: GET'ting larger clips via API fails

### ISSUE THREAD

**Issue by der--flo** [blakeblackshear/frigate#6620]
### Describe the problem you are having

Hi Guys, im running a python script as service which reacts to events, downloads the clips and pushes it to S3 for off-site storage. That script also runs once per night to download the full recordings per camera for the previous day and pushes it to S3. Works all fine, exept for larger daily recordings clips. Getting thoses clips from frigate borks out on a slower connection (~50Mbit's up via tailscale) after 300 - 600 MB. (The clip i was testing with is above 2GB) Looks like Frigate is removing the temp. clip to soon:

```
$ curl -vvv http://100.90.142.59:5000/api/carport/start/1684965600/end/1685051999/clip.mp4 -O
*   Trying 100.90.142.59...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 100.90.142.59 (100.90.142.59) port 5000 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /api/carport/start/1684965600/end/1685051999/clip.mp4 HTTP/1.1
> Host: 100.90.142.59:5000
> User-Agent: curl/7.61.1
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:50 --:--:--     0< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Fri, 26 May 2023 07:18:54 GMT
< Content-Type: video/mp4
< Content-Length: 2697249050
< Last-Modified: Fri, 26 May 2023 07:18:54 GMT
< Connection: keep-alive
< Cache-Control: no-cache
< ETag: "64705d5e-a0c4c11a"
< Accept-Ranges: bytes
< 
{ [953 bytes data]
 23 2572M   23  609M    0     0  3902k      0  0:11:14  0:02:40  0:08:34 5780k* transfer closed with 2056730665 bytes remaining to read
 23 2572M   23  610M    0     0  3905k      0  0:11:14  0:02:40  0:08:34 5793k
* Closing connection 0
curl: (18) transfer closed with 2056730665 bytes remaining to read
```
With debug in frigate i can see:

nginx
```
2023-05-26 09:20:44.483693947  2023/05/26 09:20:44 [alert] 134#134: *117 sendfile() reported that "/tmp/cache/clip_carport_1684965600-1685051999.mp4" was truncated at 640518385 while sending response to client, client: 172.17.0.1, server: , request: "GET /api/carport/start/1684965600/end/1685051999/clip.mp4 HTTP/1.1", upstream: "http://127.0.0.1:5001/carport/start/1684965600/end/1685051999/clip.mp4", host: "100.90.142.59:5000"
```

frigate
```
2023-05-26 09:18:04.646843032  [2023-05-26 09:18:04] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera", "t1"."path", "t1"."start_time", "t1"."end_time", "t1"."duration", "t1"."motion", "t1"."objects", "t1"."segment_size" FROM "recordings" AS "t1" WHERE (((("t1"."start_time" BETWEEN ? AND ?) OR ("t1"."end_time" BETWEEN ? AND ?)) OR (("t1"."start_time" < ?) AND ("t1"."end_time" > ?))) AND ("t1"."camera" = ?)) ORDER BY "t1"."start_time" ASC', [1684965600, 1685051999, 1684965600, 1685051999, 1684965600, 1685051999, 'carport'])

2023-05-26 09:19:44.424698955  [2023-05-26 09:19:44] frigate.record                 DEBUG   : Checking tmp clip /tmp/cache/clip_carport_1684965600-1685051999.mp4.

2023-05-26 09:20:44.426363628  [2023-05-26 09:20:44] frigate.record                 DEBUG   : Checking tmp clip /tmp/cache/clip_carport_1684965600-1685051999.mp4.

2023-05-26 09:20:44.426786508  [2023-05-26 09:20:44] frigate.record                 DEBUG   : Deleting tmp clip.
```

Requesting the file localy via a gigabit connections works without problems:

```
time curl -vvv http://192.168.0.21:5000/api/carport/start/1684965600/end/1685051999/clip.mp4 -O                                                                                                                            ok 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.0.21:5000...
* Connected to 192.168.0.21 (192.168.0.21) port 5000 (#0)
> GET /api/carport/start/1684965600/end/1685051999/clip.mp4 HTTP/1.1
> Host: 192.168.0.21:5000
> User-Agent: curl/8.0.1
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:49 --:--:--     0< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Fri, 26 May 2023 07:38:32 GMT
< Content-Type: video/mp4
< Content-Length: 2697249050
< Last-Modified: Fri, 26 May 2023 07:38:32 GMT
< Connection: keep-alive
< Cache-Control: no-cache
< ETag: "647061f8-a0c4c11a"
< Accept-Ranges: bytes
< 
{ [14205 bytes data]
100 2572M  100 2572M    0     0  35.0M      0  0:01:13  0:01:13 --:--:--  108M
* Connection #0 to host 192.168.0.21 left intact
curl -vvv  -O  0,28s user 3,01s system 4% cpu 1:13,32 total
```

Looks to me like frigate is removing the temp. clip after about 2,5 Minutes, is there maybe a config setting for this behavior ?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.42
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: XXXXX

objects:
  track:
    - person
    - dog
    - cat

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: debug

birdseye:
  enabled: false

go2rtc:
  streams:
    carport:
      - rtsp://carport:xxxxx@192.168.0.76:554/stream1
    terrassegr:
      - rtsp://terrassegr:xxxxx@192.168.0.77:554/stream1
    terrassekl:
      - rtsp://terrassekl:xxxxx@192.168.0.78:554/stream1
ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    snapshots:
      enabled: false
      required_zones:
        - einfahrt
    record:
      enabled: true
      retain:
        days: 3 
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
        required_zones:
          - einfahrt
    objects:
      filters:
        person:
          mask:
            - 397,978,497,910,407,765,351,784
            - 1971,1440,2560,1419,2560,943,2285,836
    zones:
      einfahrt:
        coordinates: 230,1440,1944,1440,1444,475,717,513,388,891
        objects:
          - person
          - cat
          - dog
    motion:
      mask:
        - 2182,988,2457,855,2215,655,1984,823
        - 606,258,1746,223,1302,0,0,0,0,60,591,60
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
      
  terrassegr:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrassegr
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    snapshots:
      enabled: false
    record:
      enabled: true
      retain:
        days: 3 
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
        required_zones:
          - terrasse_gr
    zones:
      terrasse_gr:
        coordinates: 1786,1440,1726,654,1415,636,1077,375,994,100,807,195,432,1440
        objects:
          - person
    motion:
      mask:
        - 624,710,1004,79,988,0,0,0,0,1440,531,1440
        - 1686,131,1694,645,1468,667,1395,201
        - 1425,578,1332,414,1236,447,1291,645
        - 1778,961,1764,814,1645,825,1650,959
        - 1808,1440,1803,1320,1643,1323,1659,1440

  terrassekl:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrassekl
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 2560
      height: 1440
    snapshots:
      enabled: false
    record:
      enabled: true
      retain:
        days: 3 
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
        required_zones:
          - terrasse_kl
    zones:
      terrasse_kl:
        coordinates: 1049,1440,1470,1337,1416,841,1419,705,1212,717,604,722,300,1267
        objects:
          - person
    motion:
      mask:
        - 267,1271,321,1144,243,1095,550,686,1419,725,1411,0,0,0,0,958,0,1133,0,1223,0,1440,798,1440


ui:
  live_mode: mse
  timezone: Europe/Berlin
  strftime_fmt: "%d.%m.%Y %H:%M"
```

### Relevant log output

```shell
see above
```

### FFprobe output from your camera

```shell
should not be relevant
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo 320's
