### ISSUE TITLE
[Support]:   Can we have a basic docker-compose.yml  file

### ISSUE THREAD

**Issue by gzcwnk** [blakeblackshear/frigate#6621]
### Describe the problem you are having

Unable to get frigate container to boot, need a lot simpler documentation please

All I get is a constant reboot,

root@docker1:/var/lib/docker/frigate# docker ps
CONTAINER ID   IMAGE                                    COMMAND   CREATED          STATUS         PORTS                                                                     NAMES
d629339958e9   ghcr.io/blakeblackshear/frigate:stable   "/init"   15 minutes ago   Up 5 seconds   0.0.0.0:1935->1935/tcp, 0.0.0.0:5000->5000/tcp, 8554-8555/tcp, 8555/udp   frigate
root@docker1:/var/lib/docker/frigate#

### Version

wont run so no web ui

### Frigate config file

```yaml
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/lib/docker/frigate/etc/config.yml:/config/config.yml
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
root@docker1:/var/lib/docker/frigate#

I assume config.yml is meant 6to be a file not a directory but docker makes a directory
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

none yet
