### ISSUE TITLE
[Support]: Cannot run latest versions with podman

### ISSUE THREAD

**Issue by sotiris-bos** [blakeblackshear/frigate#6628]
### Describe the problem you are having

```
podman-compose -f docker-compose.yml up -d
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.4.2
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=frigate', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
recreating: ...
** excluding:  set()
podman stop -t 10 frigate
frigate
exit code: 0
podman rm frigate
frigate
exit code: 0
podman pod rm pod_frigate
ef4ebb9576c592247d65fcd8d2e390aaf7d073790b502ea141f57dcfbf557158
exit code: 0
recreating: done


podman pod create --name=pod_frigate --infra=false --share=
4d55edc558c176d9d2edfd5f388fc758e0c7847a0fc1bccf89c8deaa48456666
exit code: 0
podman run --name=frigate -d --pod=pod_frigate --label io.podman.compose.config-hash=7fdc098ade1ce69fad9b47d288d2f64318f7f26ba7f2364c34aa4e80084408e0 --label io.podman.compose.project=frigate --label io.podman.compose.version=1.0.4 --label PODMAN_SYSTEMD_UNIT=podman-compose@frigate.service --label com.docker.compose.project=frigate --label com.docker.compose.project.working_dir=/root/podman/frigate --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=frigate -e FRIGATE_RTSP_PASSWORD=password -v /etc/localtime:/etc/localtime:ro -v /var/lib/docker/volumes/frigate/config.yml:/config/config.yml:ro -v /tank/cctv:/media/frigate --tmpfs /tmp/cache:size=1000000000 --network host --shm-size 64mb --privileged --restart always ghcr.io/blakeblackshear/frigate:0.12.0
Error: OCI runtime error: crun: error executing hook `/usr/bin/nvidia-container-runtime-hook` (exit code: 1)
exit code: 126
podman start frigate
Error: OCI runtime error: unable to start container "a727984be1a7e80e9f3eea19d2ddaa2347f3c174068c42cf45a9995c754ab4d1": crun: error executing hook `/usr/bin/nvidia-container-runtime-hook` (exit code: 1)
exit code: 125

```

I cannot run the latest version (any version > 0.11.0) under podman. I have no NVIDIA hardware installed in the system, nor do I have any NVIDIA-related settings in my compose file.

### Version

Latest

### Frigate config file

```yaml
mqtt:
  host: REDACTED
  user: REDACTED
  password: REDACTED

detectors:
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1

cameras:
  Main_Entrance:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@REDACTED/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:REDACTED@REDACTED/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 90
        mode: all
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua
