### ISSUE TITLE
[Support]:  If possible can someone help with getting this running on Debian11 with podman?  thankyou

### ISSUE THREAD

**Issue by gzcwnk** [blakeblackshear/frigate#6629]
### Describe the problem you are having

trying to run frigate on Debian11 and podman.

I get this error,

I manually created a network called frigate but it didnt help much.

root@podman1:/var/lib/containers/containers/frigate# podman-compose up -d
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.0.1
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 2941, in main
    podman_compose.run()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1421, in run
    self._parse_compose_file()
  File "/usr/local/lib/python3.9/dist-packages/podman_compose.py", line 1568, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: frigate
root@podman1:/var/lib/containers/containers/frigate# podman networks ls
Error: unrecognized command `podman networks`
Try 'podman --help' for more information.
root@podman1:/var/lib/containers/containers/frigate# podman networks lspodman network ls
Error: unrecognized command `podman networks`
Try 'podman --help' for more information.
root@podman1:/var/lib/containers/containers/frigate# podman network ls
NAME             VERSION  PLUGINS
podman           0.4.0    ptp,portmap,firewall
frigate          0.4.0    bridge,portmap,firewall,tuning
frigate_default  0.4.0    bridge,portmap,firewall,tuning
root@podman1:/var/lib/containers/containers/frigate#

### Version

image: ghcr.io/blakeblackshear/frigate:stable

### Frigate config file

```yaml
version: "3.3"
services:
  frigate:
    container_name: frigate
    #privileged: true # this may not be necessary for all setups
    networks:
       - frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    #  - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #  - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/frigate/etc/config.yml:/config/config.yml
      - /var/lib/docker/frigate/storage:/media/frigate
      #- type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #  target: /tmp/cache
      #  tmpfs:
      #    size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

root@podman1:/var/lib/containers/containers/frigate# more etc/config.yml
mqtt:
  #host: mqtt.server.com #Please replace with a valid mqtt broker
  host:  192.168.31.181
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2 #replace wi
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720

root@podman1:/var/lib/containers/containers/frigate#
