### ISSUE TITLE
[Config Support]: Cant Stop FFMPEG from crashing on Wyze Cams

### ISSUE THREAD

**Issue by pdobrien3** [blakeblackshear/frigate#6633]
### Describe the problem you are having

I am using WZ Mini Hacks on two Wyze Cameras (https://github.com/gtxaspec/wz_mini_hacks).  Initially, I was having problems with the image blurring and seeing a lot of artifacts.  I have been able to fix the image issue with the Frigate restream.  My audio is not in sync but the picture is perfect.  Now I am dealing with constant FFMPEG crashes in the logs and have tried everything I can think of to fix it.  The cameras are on WiFi but I am certain I have a strong stream.  Just trying to figure out if my config is right so I can take it out of the equation and look elswhere.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.xx.xxx
  user: mqttuser
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  width: 640
  height: 360
  quality: 1
  mode: motion

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 14

logger:
  default: info
database:
  path: /db/frigate.db

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 60
    post_capture: 60
    objects:
      - person
    required_zones: []
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 14
go2rtc:
  streams:
    two_camera: 
      - "ffmpeg:rtsp://user:pass@192.168.xx.xxx:8554/video1_unicast#video=h264#audio=aac"
      - "ffmpeg:two_camera#audio=opus"
    one_camera: 
      - "ffmpeg:rtsp://user:pass@192.168.xx.xxx:8554/video1_unicast#video=h264#audio=aac"
      - "ffmpeg:one_camera#audio=opus"

  webrtc:
    candidates:
      - 192.168.xx.xxx:8555
      - stun:8555
    
cameras:
  two_camera:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        detect: -dn -an -sn -f rawvideo -pix_fmt yuv420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video2_unicast
          input_args: preset-rtsp-udp
          roles:
            - detect
        - path: rtsp://localhost:8554/two_camera
          input_args: preset-rtsp-restream
          roles:
            - record          
    detect:
      width: 640 
      height: 360 
      fps: 5
      max_disappeared: 25
      stationary:
        interval: 10
        threshold: 60
    best_image_timeout: 30
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.6
          threshold: 0.65
    motion:
      contour_area: 16
      threshold: 20
      mask:
        - 640,330,640,360,461,360,460,332
        - 0,164,68,144,75,190,0,217
      improve_contrast: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500

  one_camera:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        detect: -dn -an -sn -f rawvideo -pix_fmt yuv420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video2_unicast
          input_args: preset-rtsp-udp
          roles:
            - detect
        - path: rtsp://localhost:8554/one_camera
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
      max_disappeared: 35
      stationary:
        interval: 10
        threshold: 60
    best_image_timeout: 30
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.6
          threshold: 0.65 
    motion:
      contour_area: 15
      threshold: 20 
      mask:
        - 640,330,640,360,435,360,440,329
      improve_contrast: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
```

### Relevant log output

```shell
I just restarted the container so I will post these when they come up but there isn't anything significant.  Usually something about to recordings for 120 seconds, then ffmpeg exiting gracefully.  Sometimes something about timestamps being unset and being deprecated in the future.
```

### Frigate stats

```json
{"three_camera":{"camera_fps":6.0,"capture_pid":456,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":467,"pid":442,"process_fps":6.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"146":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"165":{"cpu":"0.0","mem":"0.0"},"188":{"cpu":"0.0","mem":"0.0"},"217":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"2666":{"cpu":"0.0","mem":"0.0"},"2691":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"426":{"cpu":"0.0","mem":"0.2"},"432":{"cpu":"1.0","mem":"0.0"},"433":{"cpu":"5.3","mem":"0.3"},"434":{"cpu":"1.7","mem":"0.3"},"438":{"cpu":"8.3","mem":"0.3"},"439":{"cpu":"0.0","mem":"0.1"},"440":{"cpu":"19.3","mem":"0.3"},"441":{"cpu":"0.0","mem":"0.1"},"442":{"cpu":"2.0","mem":"0.3"},"443":{"cpu":"1.7","mem":"0.3"},"444":{"cpu":"0.0","mem":"0.1"},"445":{"cpu":"1.3","mem":"0.3"},"446":{"cpu":"1.0","mem":"0.3"},"447":{"cpu":"0.0","mem":"0.1"},"450":{"cpu":"1.0","mem":"0.3"},"451":{"cpu":"1.7","mem":"0.1"},"452":{"cpu":"0.0","mem":"0.1"},"456":{"cpu":"1.3","mem":"0.3"},"461":{"cpu":"0.0","mem":"0.1"},"464":{"cpu":"2.0","mem":"0.1"},"465":{"cpu":"1.0","mem":"0.3"},"466":{"cpu":"3.0","mem":"0.1"},"467":{"cpu":"1.3","mem":"0.1"},"476":{"cpu":"1.3","mem":"0.3"},"479":{"cpu":"1.7","mem":"0.2"},"486":{"cpu":"2.7","mem":"0.1"},"487":{"cpu":"3.0","mem":"0.1"},"488":{"cpu":"1.3","mem":"0.2"},"491":{"cpu":"1.7","mem":"0.1"},"494":{"cpu":"2.0","mem":"0.1"},"543":{"cpu":"96.0","mem":"0.3"},"560":{"cpu":"107.0","mem":"0.3"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"20.3","mem":"0.1"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"6.0","mem":"0.6"},"MiB":{"cpu":"27027.3","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.8,"detectors":{"coral":{"detection_start":0.0,"inference_speed":13.35,"pid":433}},"one_camera":{"camera_fps":5.0,"capture_pid":476,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":488,"pid":445,"process_fps":5.0,"skipped_fps":0.0},"four_camera":{"camera_fps":6.1,"capture_pid":446,"detection_enabled":1,"detection_fps":0.8,"ffmpeg_pid":451,"pid":438,"process_fps":6.0,"skipped_fps":0.0},"five_camera":{"camera_fps":6.1,"capture_pid":450,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":464,"pid":440,"process_fps":6.1,"skipped_fps":0.0},"two_camera":{"camera_fps":5.1,"capture_pid":465,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":479,"pid":443,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"intel-qsv":{"gpu":"1.16 %","mem":"- %"},"intel-vaapi":{"gpu":"1.32 %","mem":"- %"}},"service":{"last_updated":1685193339,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":263.9,"mount_type":"tmpfs","total":268.4,"used":4.5},"/media/frigate/clips":{"free":3544413.4,"mount_type":"ext4","total":3936818.8,"used":192349.3},"/media/frigate/recordings":{"free":3544413.4,"mount_type":"ext4","total":3936818.8,"used":192349.3},"/tmp/cache":{"free":986.9,"mount_type":"tmpfs","total":1000.0,"used":13.1}},"temperatures":{},"uptime":2577,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by pdobrien3** [comment]
one thing that is confusing to me is that even though my ffprobe for the cameras claim H.264 with AAC audio, I couldn't get a good stream with out the ffmpeg restream encoding to H.264 with AAC Audio.

`[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
`

Also, I am not sure if I should be using `hwaccel_args: preset-intel-qsv-h264` or `hwaccel_args: preset-vaapi`

Here is the VAINFO:

`{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:Inteli965driverforIntel(R)Skylake-2.4.1nvainfo:SupportedprofileandentrypointsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointStatsnVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointStatsnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointStatsnVAProfileH264MultiviewHigh:tVAEntrypointVLDnVAProfileH264MultiviewHigh:tVAEntrypointEncSlicenVAProfileH264StereoHigh:tVAEntrypointVLDnVAProfileH264StereoHigh:tVAEntrypointEncSlicenVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileNone:tVAEntrypointVideoProcnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlice"}`

**Comment by NickM-27** [comment]
It is not recommended to use wyze cameras & go2rtc restream with frigate cameras section as wyze cams do not work well. Using different ffmpeg args should help with the other issues you were seeing.

I'd suggest using preset-vaapi as generally I've seen it to be more stable.

**Comment by pdobrien3** [comment]
i have no idea what ffmpeg args to use. i have looked everywhere on the internet and cant find a stable config. any idea?

**Comment by NickM-27** [comment]
maybe try UDP instead of TCP

**Comment by pdobrien3** [comment]
any hint on how to do that?

**Comment by NickM-27** [comment]
https://docs.frigate.video/configuration/camera_specific#udp-only-cameras

**Comment by pdobrien3** [comment]
auh, just in the frigate config. pretty sure i have tried that but will try again and get back

**Comment by pdobrien3** [comment]
so, use that preset for both detect and record?

**Comment by pdobrien3** [comment]
so with this:

```
  two_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-udp
      output_args:
        detect: -dn -an -sn -f rawvideo -pix_fmt yuv420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video2_unicast
          roles:
            - detect
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video1_unicast
          roles:
            - record          
```

Now I see this:

```
ERROR   : [h264 @ 0x5613561d4580] non-existing PPS 0 referenced
ERROR   :     Last message repeated 1 times
ERROR   : [h264 @ 0x5613561d4580] decode_slice_header error
ERROR   : [h264 @ 0x5613561d4580] no frame!
ERROR   : [h264 @ 0x5613561d4580] non-existing PPS 0 referenced
ERROR   :     Last message repeated 1 times
ERROR   : [h264 @ 0x5613561d4580] decode_slice_header error
ERROR   : [h264 @ 0x5613561d4580] no frame!
ERROR   : [h264 @ 0x5613561d4580] non-existing PPS 0 referenced
ERROR   :     Last message repeated 1 times
ERROR   : [h264 @ 0x5613561d4580] decode_slice_header error
ERROR   : [h264 @ 0x5613561d4580] no frame!
ERROR   : [h264 @ 0x5613561d4580] non-existing PPS 0 referenced

```

**Comment by NickM-27** [comment]
Yeah, wyze cams have very poor implementation of rtsp so perhaps there are some ffmpeg args which will correct its problems better but in this case ffmpeg is not receiving frames.

**Comment by pdobrien3** [comment]
any suggestions?

**Comment by pdobrien3** [comment]
So, this actually loads without errors and I think is using udp:
 ```
two_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -timeout 30000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -dn -an -f rawvideo -pix_fmt yuv420p
        record: -dn -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:v copy -codec:a aac -b:a 24k -ac 1 
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video2_unicast
          roles:
            - detect
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video1_unicast
          roles:
            - record
```
The video is very pixelated on the bottom half though.  When using my Frigate restream config settings, I am guessing it is actually encoding it to H.264 even though my ffprobes indicate an H.264 stream?  Am I not getting a true H.264 stream without re-encoding?  Anyway to fix that in the input/output args?

**Comment by NickM-27** [comment]
Yes it looks like reencoding is the only way you have found success. You could add #hardware to the end of the go2rtc encoding configs to help boost the performance of encoding

**Comment by pdobrien3** [comment]
I will let that config go for a while and see how it works out.  I actually found something on the internet that says the Wyze cameras are H.265 streams when using the wz_mini hacks.  Any docs on setting args for H.265 streams or Frigate really doesnt do well with H.265?

**Comment by NickM-27** [comment]
The args are exactly the same, preset-vaapi works with both

**Comment by pdobrien3** [comment]
but that is for using ffmpeg encoding?  I was talking more along the lines of using the native wz_mini stream

**Comment by NickM-27** [comment]
It is for decoding streams which is always done for detect stream, regardless of what stream is being used as the source for it. It's unclear what you expect to be different with h.265 besides that

**Comment by pdobrien3** [comment]
the record stream is where i am seeing pixilation .  wz_mini allows for two streams

**Comment by g8keeperzuul** [comment]
I have a Wyze cam with wz_mini and recently upgraded from Frigate 0.11 to 0.12 (Docker image)
Now ffmpeg consistently crashes and restarts after consuming all RAM and CPU.
The error message upon crash is  "<camera> exceeded fps limit. Exiting ffmpeg... Waiting for ffmpeg to exit gracefully... " (which it doesn't do). The ffmpeg process crashes in waves of restarts.
I reduced my config to a single Wyze camera, no detection, no resizing or re-encoding, just record the stream as is. 
The wireless Wyze cam was never rock solid, but this problem is new with Frigate 0.12 with no other hardware or software changes.  The ffmpeg presets are used (input_args: preset-rtsp-restream, output_args: record: preset-record-generic-audio-copy)

**Comment by g8keeperzuul** [comment]
> I will let that config go for a while and see how it works out. I actually found something on the internet that says the Wyze cameras are H.265 streams when using the wz_mini hacks. Any docs on setting args for H.265 streams or Frigate really doesnt do well with H.265?

No - my wz_mini is outputting h.264:
According to ffprobe:
Input #0, rtsp, from 'rtsp://10.0.0.174:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 3.055478, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 960x540, 25 fps, 10 tbr, 90k tbn, 50 tbc

**Comment by NickM-27** [comment]
You need to show your config

**Comment by g8keeperzuul** [comment]
Relevant Frigate config.yml:
```
go2rtc:
  rtsp:
    listen: ":8554" 
  streams:
    # Camera details can be obtained via: $ (ffplay|ffprobe) rtsp://10.0.0.174:8554/unicast
    wyzec2_d8d9_camera_only_stream: rtsp://10.0.0.174:8554/unicast        # 1280x720@25fps (stream 0.0: H.264; stream 0.1: mp3 44100 Hz mono) --> configured for 960x540@10fps, no audio [911.07 MB/hr]
  api:
    listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  webrtc:
    listen: ":8555"  # address of your local server and port (TCP/UDP)    
  log:
    level: info  # default level (trace, debug, info, warn, error, fatal)

cameras:  
  wyzec2_d8d9: # <------ Wyze V2 camera with wz_mini_hacks    
    ffmpeg: # https://docs.frigate.video/configuration/ffmpeg_presets  
      # Preset details: https://github.com/blakeblackshear/frigate/blob/master/frigate/ffmpeg_presets.py    
      inputs:        
        - path: rtsp://127.0.0.1:8554/wyzec2_d8d9_camera_only_stream
          roles:
           - detect
           - record       
          input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic
    motion: # Optional: A mask specifies areas to ignore any motion, however if any motion is detected, then the entire frame is used for object detection        
      # https://docs.frigate.video/configuration/masks#further-clarification
      mask:
      # 1280x720:
      # - 1280,0,1280,720,1113,720,1111,536,1038,529,499,589,0,558,0,0
      # 960x540:
        - 0,0,960,0,960,540,810,540,833,332,631,343,581,376,472,399,0,374
    detect: # Optional: Detect objects
      enabled: False # even if true, can still be disabled via UI
      # Using a lesser resolution/framerate can be seen in debug mode
      # !! ALL zones and masks are resolution dependent !!
      # ANY change from the original size transmitted by the camera will involve non-trivial processing! https://github.com/blakeblackshear/frigate/issues/3860
      width: 960
      height: 540    
      # width: 1280
      # height: 720
      fps: 5
      stationary: # defaults
        interval: 0 # frequency (in frames) for running detection on stationary objects
        threshold: 50 # number of frames an object needs to remain relatively still before it is considered stationary        
    objects: # Optional: List of pre-trained objects to enable detection on (default is just person)
      track:
        - person
        - cat
        - dog    
    snapshots: 
      enabled: False
    record:
      enabled: True      
      retain:
        days: 3
        mode: all  # all | motion | active_objects      
    birdseye:  # Include this camera in composite view
      enabled: False
```

**Comment by NickM-27** [comment]
As has been said, go2rtc restream doesn't work well frigate and it's recommended to have frigate cameras section connect directly to the wyze camera.

**Comment by g8keeperzuul** [comment]
OK, will try configuring Frigate cameras to use the camera stream directly, and avoid go2rtc.

What is the purpose of go2rtc? Is it just to reduce the number of separate connections directly to the camera and instead serve those observers from Frigate instead? Looks like go2rtc can perform some video transcoding as well, although in my case I don't think I need to do that since camera already serves h.264 via rtsp.

**Comment by pdobrien3** [comment]
@g8keeperzuul if you can get direct streams into frigate without artifacts I would be very much appreciate knowing how you did it. Are you using wz_mini?

**Comment by g8keeperzuul** [comment]
The Wyze cameras V2 with wz_mini has great features and is definitely good on the value-for-money scale, but it is not robust. In part this is due to the nature of streaming video over wireless - expect artifacts - dropped frames and heavy pixelation is not uncommon.  Processing those streams in Frigate is not stable either.  I think, in part, the instability of the video stream causes ffmpeg crashes in Frigate resulting in lost video segments and missed events.
```
2023-06-09 07:26:51.163062639 [2023-06-09 07:26:51] frigate.video ERROR : wyzec2_d8d9: Unable to read frames from ffmpeg process.  
2023-06-09 07:26:51.163345645 [2023-06-09 07:26:51] frigate.video ERROR : wyzec2_d8d9: ffmpeg process is not running. exiting capture thread...  
2023-06-09 07:26:53.499541331 [2023-06-09 07:26:53] watchdog.wyzec2_d8d9 ERROR : Ffmpeg process crashed unexpectedly for wyzec2_d8d9.  
2023-06-09 07:26:53.499918244 [2023-06-09 07:26:53] watchdog.wyzec2_d8d9 ERROR : The following ffmpeg logs include the last 100 lines prior to exit.  
2023-06-09 07:26:53.499978031 [2023-06-09 07:26:53] ffmpeg.wyzec2_d8d9.detect ERROR : rtsp://10.0.0.174:8554/unicast: Connection timed out  
2023-06-09 07:26:53.500167114 [2023-06-09 07:26:53] ffmpeg.wyzec2_d8d9.detect ERROR : Last message repeated 1 times 
```
I also see plenty of opencv crashes:
```
[2023-06-09 08:23:45] frigate.http                   ERROR   : Exception on /wyzec2_d8d9/latest.jpg [GET] 

2023-06-09 08:23:45.516722609  Traceback (most recent call last): 
2023-06-09 08:23:45.516728746    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app 
2023-06-09 08:23:45.516733974      response = self.full_dispatch_request() 
2023-06-09 08:23:45.516739778    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request 
2023-06-09 08:23:45.516744469      rv = self.handle_user_exception(e) 
2023-06-09 08:23:45.516750038    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request 
2023-06-09 08:23:45.516754427      rv = self.dispatch_request() 
2023-06-09 08:23:45.516759671    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request 
2023-06-09 08:23:45.516764671      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) 
2023-06-09 08:23:45.516769650    File "/opt/frigate/frigate/http.py", line 896, in latest_frame 
2023-06-09 08:23:45.516774588      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA) 
2023-06-09 08:23:45.516780347  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize' 
```

**Comment by DaCeige** [comment]
I'm having pretty decent luck using these settings.  I ditched the dual streams and went with a single stream.  Only problem is occasionally it'll glitch out the bottom of the stream and cause green overlays, messes up the birds eye view, etc.

Posting these so others can build on them on hopefully get a decently working solution.

I am running go2rtc version 1.5.  Not sure if that matters.  

I found on another post how to use #raw in the go2rtc streams to define all the options... I currently have the settings from that other post which was on a reolink camera iirc.  Was stable for the last day before artifacts... but I think I'm on to something here. 

you can see all the options in use by looking at ps, or ps > list.txt ... or I was using at the time nvtop and a really wide monitor.

```
go2rtc:
  webrtc:
    candidates:
      - pubip:8555  # if you have static public IP-address
  streams:
    test2_cam:
      - ffmpeg:rtsp://username:password@192.168.1.146:554/live#video=copy#audio=copy#raw= -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
      - "ffmpeg:test2_cam#audio=aac"
      # - ffmpeg:rtsp://username:password@192.168.1.146:8554/video1_unicast#video=copy
      # - ffmpeg:rtsp://username:password@192.168.1.146:8554/video1_unicast#video=copy#input=rtsp/udp
      # - ffmpeg:rtsp://username:password@192.168.1.146:8554/video1_unicast#video=copy#input=input=-timeout 5000000
      # - ffmpeg:rtsp://username:password@192.168.1.146:8554/video1_unicast#video=copy#input=rtsp/udp#input=-timeout 5000000
    # test2_cam_detect:
    #   - ffmpeg:rtsp://username:password@192.168.1.146:8554/video2_unicast#video=copy#input=rtsp/udp
cameras:
  test2_cam:
    ffmpeg:
      hwaccel_args: ' '
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/test2_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        # - path: rtsp://127.0.0.1:8554/test2_cam_detect
        #   input_args: preset-rtsp-restream
        #   roles:
            - detect
    detect:
      # width: 1280
      # height: 720
      width: 1920
      height: 1080
      fps: 5
    ui:
      order: 16
```
