### ISSUE TITLE
[Support]: possible to append to a ffmpeg preset

### ISSUE THREAD

**Issue by vajonam** [blakeblackshear/frigate#6663]
### Describe the problem you are having

is it possible to append to a preset ? 

`input_args: preset-rtsp-restream`

I have tried
```
input_args: 
  - preset-rtsp-restream
  - -extra_hw_frames 5
```

### Version

0.1.2

### Frigate config file

```yaml
cameras:
  doorbell: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
          record: preset-record-generic
      inputs:
        - path: rtsp://ip_camera08:554/live/0/SUB # <----- The stream you want to use for detection

          roles:
            - detect
        - path: rtsp://frigate:8554/doorbell #rtsp://frigate:8554/doorbell # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280  # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 8.0
```
```


### Relevant log output

```shell
None.
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Amrecst
