### ISSUE TITLE
[Support]: Frigate + home assistant lose the "recording" settings after restart.

### ISSUE THREAD

**Issue by inode-** [blakeblackshear/frigate#6664]
### Describe the problem you are having

I've had a frigate set up on one system with home assistant integration on another for a while now.

Everything works fine, but I noticed an anomaly. Let's assume that I have triggers on the home assistant to enable or disable recording whether he is at home or not.

In case frigate is restarted for any reason, after the restart it "losts" the state it was in and starts again to be in recording mode even if I had disabled recording on the home assistant.

Non ho trovato nessun modo per dire a frigate "chiedi a home assistant" in che stato deve essere il recording e il motion dopo un riavvio.

Thank you

### Version

4.0.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.40
  port: 1883
  user: mosquittouser
  password: x


detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 1920 # <---- update for your camera's resolution
  height: 1080 # <---- update for your camera's resolution

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac



rtmp:
  enabled: true # <-- RTMP should be disabled if your stream is not H264

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car

record:
  enabled: True
  events:
    retain:
      default: 30

motion:
  threshold: 25
  contour_area: 30
  frame_height: 50
  improve_contrast: False

birdseye:
  enabled: True
  width: 1280
  height: 720
  mode: objects

snapshots:
  enabled: False
  timestamp: False
  bounding_box: False
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15



cameras:
  retro: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x@192.168.0.20:8554/unicast # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record
  lato: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x@192.168.0.21:8554/unicast # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record
              #       objects:
              #          filters:
              #          person:
              # mask:
              #   - 856,0,0,0,0,684


  fronte: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x@192.168.0.22:8554/unicast # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record
              #zones:
              #      fronte_zona:
              ##    objects:
              #filters:
              #person:
              #mask:
              #- 1920,0,1920,245,1650,0

  garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x@192.168.0.23:8554/unicast # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record

  salotto: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x@192.168.0.24:8554/unicast # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record

  soffitta: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.26/unicast # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record

  cucina: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.25/unicast # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record


  taverna: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.11/ch0_0.h264 # <----- Update for your camera

          roles:
            - detect
            - rtmp
            - record
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

yi
