### ISSUE TITLE
[Support]: birdseye in continuous mode does not honour the UI camera order

### ISSUE THREAD

**Issue by vtacquet** [blakeblackshear/frigate#6667]
### Describe the problem you are having

using Birdseye in continuous mode does not honour the UI camera order
in Cameras view the order is working perfectly

### Version

0.13.0-AE0ABA4

### Frigate config file

```yaml
...
birdseye:
  enabled: True
  mode: continuous
...
cameras:
  door:
    ui:
      order: 1
...
  front:
    ui:
      order: 2
...
  driveway:
    ui:
      order: 3
...
  back:
    ui:
      order: 4
...
  side:
    ui:
      order: 5
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
no relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Doorbird + Reolink RLC-511WA

### Any other information that may be helpful

cameras (correct order):
![CleanShot 2023-06-01 at 11 17 42](https://github.com/blakeblackshear/frigate/assets/5128967/e813f53c-b97a-4eb0-9776-8b340d888333)

birdsey (wrong order):
![CleanShot 2023-06-01 at 11 16 50](https://github.com/blakeblackshear/frigate/assets/5128967/b20767ab-80f3-4ab9-9916-3aa329646d7a)
