### ISSUE TITLE
Google coral accelerator usb

### ISSUE THREAD

**Issue by mmaaligema** [blakeblackshear/frigate#6675]
### Describe the problem you are having

Hello !
I have bought myself a google coral accelerator which I want to insert into my raspberry 4 usb.
Do I have to configure it before use?
What do I enter in the friogate.yml file under detectors?
Should I record detectors:
                                    coral:
                                         type: edgetpu
                                          device: usb

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password
  stats_interval: 60
  
detectors:
  cpu:
    type: cpu
    num_threads: 2

cameras:
  olle:
    ffmpeg:
      output_args:
        rtmp: -c:v copy -c:a aac -f flv
      
      inputs:
        - path: rtsp://admin:Clarence4321@192.168.1.7:554/Streaming/Channels/103
          roles:
            - detect
            - record

    record:
      enabled: true
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
      
    objects:
      track:
        - person
        - car
        - bicycle
        - cat
        - dog
  husvagn:
    ffmpeg:
      output_args:
        rtmp: -c:v copy -c:a aac -f flv
        
      inputs:
        - path: rtsp://admin:Clarence1974?!8@192.168.1.64:554/Streaming/channels/103
          roles:
            - detect
            - record
    record:
      enabled: True
    snapshots:
      enabled: True
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
      
    objects:
      track:
        - person
        - car
        - bicycle
        - cat
        - dog
```

### docker-compose file or Docker CLI command

```yaml
now
```

### Relevant log output

```shell
don t now
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

now
