### ISSUE TITLE
Reolink trackmix poe

### ISSUE THREAD

**Issue by mmaaligema** [blakeblackshear/frigate#6676]
### Describe the problem you are having

Hur skriver jag en rätt frigate.yml file om jag vil ha min reolink trackmix poe att fungera i frigate nvr i home assistant ?
132 / 5 000
Översättningsresultat
Översättningsresultat
Hello !

How do I write a correct frigate.yml file if I want my reoloink trackmix poe to work in frigate nvr in home assistant?

### Version

0.12.0

### Frigate config file

```yaml
cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.8:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.8:8554/reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### docker-compose file or Docker CLI command

```yaml
now
```

### Relevant log output

```shell
?
```

### FFprobe output from your camera

```shell
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Reolink trackmix poe

### Any other information that may be helpful

https://reolink.com/ch/product/reolink-trackmix-poe/

**Comment by NickM-27** [comment]
The recommended reolink configuration is in the docs https://docs.frigate.video/configuration/camera_specific#reolink-cameras

**Comment by lehnen** [comment]
The recommanded reolink configuration from the doc's did not work for me on my Reolink trackmix poe.
I could grab the stream via rtsp://<username>:<password>@<reolink ip>:554/h264Preview_01_main

**Comment by harisk73** [comment]
> The recommended reolink configuration from the doc's did not work for me on my Reolink trackmix poe. I could grab the stream via `rtsp://<username>:<password>@<reolink ip>:554/h264Preview_01_main`

Can you please post your complete working configuration?

**Comment by lehnen** [comment]
@harisk73 sure:
```
mqtt:
  host: <mqtt host ip>
  user: hass
  password: mosquitto

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: continuous

record:
  enabled: True
  events:
    retain:
      default: 14
      mode: active_objects

detect:
  width: 1080
  height: 720
  #fps: 5
  enabled: True
  max_disappeared: 25

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_score: 0.68
      threshold: 0.78

go2rtc:
  streams:
    garten:
      - ffmpeg:rtsp://<user>:<password>@<ip address of camera>:554
      - "ffmpeg:garten#video=h264#audio=aac"
    garten_sub:
      - ffmpeg:rtsp://<user>:<password>@<ip address of camera>:554/h264Preview_01_main
      - "ffmpeg:garten#video=h264#audio=aac"

cameras:
  garten: 
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garten 
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garten_sub
          roles:
            - detect
 ```
