### ISSUE TITLE
[Config Support]: Unable to un-mute sound in live view and no sound in recordings 

### ISSUE THREAD

**Issue by simondrake** [blakeblackshear/frigate#6677]
### Describe the problem you are having

Since upgrading to Frigate 0.12, sound hasn't been working in my recordings. I've also tried getting the live sound to work, but it shows the muted symbol with no way for me to un-mute it.

![image](https://github.com/blakeblackshear/frigate/assets/62928647/5ec4f767-1162-4dba-9018-4219b389607f)

For the recordings, I've tried `preset-record-generic-audio-copy`, `preset-record-generic-audio-aac` and `-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac` (which I was using before upgrading), but none seem to work.

**Note:** My config file will show inconsistencies as I am trying different things, on different cameras, to see what works.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    front_door:
      - rtsp://****:****@192.168.30.102/Streaming/Channels/101
    side_garden:
      - rtsp://****:****@192.168.30.102/Streaming/Channels/201
      - "ffmpeg:back#audio=aac"
    back_garden:
      - rtsp://****:****@192.168.30.102/Streaming/Channels/301
    drive:
      - rtsp://****:****@192.168.30.150/Streaming/Channels/101
      - "ffmpeg:back#audio=aac"

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    # hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        # record: preset-record-generic-audio-copy
    detect:
      enabled: True
      width: 1280
      height: 720
    snapshots:
      enabled: True
      timestamp: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10
  side_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_garden
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    # hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      output_args:
        record: preset-record-generic-audio-aac
        # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        # record: preset-record-generic-audio-copy
    detect:
      enabled: True
      width: 1280
      height: 720
    snapshots:
      enabled: True
      timestamp: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    # hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      output_args:
        record: preset-record-generic-audio-aac
        # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        # record: preset-record-generic-audio-copy
    detect:
      enabled: True
      width: 1280
      height: 720
    snapshots:
      enabled: True
      timestamp: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10
  drive:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drive
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    # hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      output_args:
        # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        record: preset-record-generic-audio-copy
    detect:
      enabled: True
      width: 1280
      height: 720
    snapshots:
      enabled: True
      timestamp: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10

mqtt:
  enabled: True
  host: mosquitto
  user: ****
  password: &&&&


objects:
  track:
    - person
    - car

birdseye:
  enabled: False
  restream: True
  width: 1280
  height: 820
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
2023-06-01 13:07:11.569271789  [INFO] Preparing go2rtc config...
2023-06-01 13:07:11.825558407  [INFO] Starting go2rtc...
2023-06-01 13:07:11.898471725  13:07:11.898 INF go2rtc version 1.2.0 linux/amd64
2023-06-01 13:07:11.898732273  13:07:11.898 INF [api] listen addr=:1984
2023-06-01 13:07:11.899011507  13:07:11.898 INF [rtsp] listen addr=:8554
2023-06-01 13:07:11.899280129  13:07:11.899 INF [srtp] listen addr=:8443
2023-06-01 13:07:11.899499882  13:07:11.899 INF [webrtc] listen addr=:8555
2023-06-01 13:07:12.535637178  13:07:12.535 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#audio=aac
2023-06-01 13:07:12.647030326  13:07:12.646 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#audio=aac
2023-06-01 13:07:21.561195184  [INFO] Starting go2rtc healthcheck service...
2023-06-01 13:07:55.537497312  13:07:55.537 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#audio=aac
2023-06-01 13:08:17.327595611  13:08:17.327 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#audio=aac
2023-06-01 13:08:36.627655706  13:08:36.626 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#audio=aac
2023-06-01 13:09:20.872879079  13:09:20.872 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#audio=aac
2023-06-01 13:09:51.144401766  13:09:51.144 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#audio=aac
```

### Frigate stats

```json
{"back_garden":{"camera_fps":5.1,"capture_pid":308,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":325,"pid":298,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"103":{"cpu":"2.3","mem":"2.7"},"116":{"cpu":"0.0","mem":"0.2"},"1346":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.1"},"138":{"cpu":"0.0","mem":"0.1"},"1382":{"cpu":"0.0","mem":"0.0"},"139":{"cpu":"0.0","mem":"0.1"},"1392":{"cpu":"0.0","mem":"0.0"},"140":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.3","mem":"1.0"},"287":{"cpu":"0.3","mem":"0.1"},"288":{"cpu":"0.3","mem":"1.4"},"289":{"cpu":"1.7","mem":"1.2"},"29":{"cpu":"0.0","mem":"0.0"},"296":{"cpu":"0.3","mem":"1.2"},"297":{"cpu":"1.0","mem":"1.2"},"298":{"cpu":"1.0","mem":"1.2"},"299":{"cpu":"0.7","mem":"1.2"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"3.0","mem":"1.1"},"301":{"cpu":"0.0","mem":"0.2"},"304":{"cpu":"3.0","mem":"1.1"},"305":{"cpu":"0.0","mem":"0.2"},"308":{"cpu":"3.0","mem":"1.1"},"309":{"cpu":"52.3","mem":"0.6"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"54.0","mem":"0.6"},"311":{"cpu":"0.0","mem":"0.2"},"312":{"cpu":"2.6","mem":"1.1"},"316":{"cpu":"0.0","mem":"0.2"},"32":{"cpu":"0.0","mem":"0.0"},"323":{"cpu":"47.4","mem":"0.6"},"325":{"cpu":"49.3","mem":"0.6"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"5.6","mem":"0.2"},"96":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"6241.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":13.76,"pid":288}},"drive":{"camera_fps":5.1,"capture_pid":312,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":323,"pid":299,"process_fps":5.1,"skipped_fps":0.0},"front_door":{"camera_fps":5.1,"capture_pid":300,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":309,"pid":296,"process_fps":5.1,"skipped_fps":0.0},"service":{"last_updated":1685625377,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":126.6,"mount_type":"tmpfs","total":134.2,"used":7.6},"/media/frigate/clips":{"free":84027.8,"mount_type":"ext4","total":491104.4,"used":382054.6},"/media/frigate/recordings":{"free":84027.8,"mount_type":"ext4","total":491104.4,"used":382054.6},"/tmp/cache":{"free":985.4,"mount_type":"tmpfs","total":1000.0,"used":14.6}},"temperatures":{},"uptime":545,"version":"0.12.0-da3e197"},"side_garden":{"camera_fps":5.0,"capture_pid":304,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":310,"pid":297,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
