### ISSUE TITLE
[Support]: Plain text password in syslog file

### ISSUE THREAD

**Issue by jrkoiter** [blakeblackshear/frigate#6684]
### Describe the problem you are having

Frigate is leaking the plain text password as configured in a camera's path attribute to the syslog:

Config snippet:
```
go2rtc:
  streams:
    cam1:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.104:554/cam/realmonitor?channel=1&subtype=0
``` 

Produces the following syslog entry where `PASSWORD_REDACTED` is the actual password:
```
Jun  1 19:37:47 d3 daemon.info docker-compose[3080297]:  frigate  | 2023-06-01 19:37:47.236713582  19:37:47.236 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="dial tcp 10.1.0.108:554: i/o timeout" url=rtsp://frigate:PASSWORD_REDACTED@10.0.0.108:554/cam/realmonitor?channel=1&subtype=0
```
  

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.5
  port: 2883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60
motion:
  threshold: 25
  frame_alpha: 0.2
objects:
  track:
    - person
snapshots:
  retain:
    default: 7
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 5
  stationary:
    max_frames:
      default: 3000
      objects:
        person: 1000
go2rtc:
  streams:
    cam1:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.104:554/cam/realmonitor?channel=1&subtype=0
    cam7:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/cam/realmonitor?channel=1&subtype=0
    cam2:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.107:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:cam2#audio=opus"
    cam3:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:cam3#audio=opus"
    cam4:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.105:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:cam4#audio=opus"
    cam5:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/cam/realmonitor?channel=1&subtype=0
    cam6:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.109:554/cam/realmonitor?channel=1&subtype=0
cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1 # 'rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.104:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            #- rtmp
            - record
    detect:
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
    objects:
      track:
        - person
        - bicycle
        - car
      filters:
        car:
          max_area: 120000
    motion:
      mask:
        - 1839,35,1435,32,1440,86,1841,86
    zones:
      oprit:
        coordinates: 0,1080,1708,1080,1880,473,1004,371,499,202,143,236,290,439,0,509
        objects:
          - person
          - bicycle
          - car
  cam7:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam7 # 'rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            #- rtmp
            - record
    detect:
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
    motion:
      mask:
        - 1839,35,1435,32,1440,86,1841,86
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2 # 'rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.107:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            #- rtmp
            - record
    detect:
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
    motion:
      mask:
        - 1839,35,1435,32,1440,86,1841,86
  cam3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3 # 'rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            #- rtmp
            - record
    detect:
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
    motion:
      mask:
        - 1839,35,1435,32,1440,86,1841,86
  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4 # 'rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.105:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            #- rtmp
            - record
    detect:
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
    motion:
      mask:
        - 1839,35,1435,32,1440,86,1841,86
  cam5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam5 # 'rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            #- rtmp
            - record
    detect:
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
    motion:
      mask:
        - 1839,35,1435,32,1440,86,1841,86
  cam6:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam6 # 'rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.0.109:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
            #- rtmp
            - record
    detect:
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
    motion:
      mask:
        - 1839,35,1435,32,1440,86,1841,86
ffmpeg:
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - info
  hwaccel_args: preset-intel-qsv-h264
  # hwaccel_args:
  #   - -hwaccel
  #   - qsv
  #   - -qsv_device
  #   - /dev/dri/renderD128
  #   - -c:v
  #   - h264_qsv
  output_args:
    detect: -vf hwdownload,format=nv12 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac
detectors:
  coral_pci:
    type: edgetpu
    device: pci
birdseye:
  enabled: False
# logger:
#   default: debug
```

### Relevant log output

```shell
Jun  1 19:37:47 d3 daemon.info docker-compose[3080297]:  frigate  | 2023-06-01 19:37:47.236713582  19:37:47.236 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="dial tcp 10.1.0.108:554: i/o timeout" url=rtsp://frigate:PASSWORD_REDACTED@10.0.0.108:554/cam/realmonitor?channel=1&subtype=0
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dahua
