### ISSUE TITLE
[Detector Support]: Tensorrt model generation error

### ISSUE THREAD

**Issue by pomigun** [blakeblackshear/frigate#6689]
### Describe the problem you are having

Hi, i managed too install frigate with tensorrt a long time ago, i changed hardware recently and to make sure everything work i tried to generate a new models but encountered an error following the indications on documentations.

when pip is going to be upgrade this error show up:
`ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: '/usr/local/lib/python3.8/dist-packages/pip-22.1.2.dist-info/'` and the generation is quickly ended after that.

I'm not sure if i'm doing something wrong here.
i'm running frigate on a proxmox lxc, driver up to date and everything was alright before while running with the old trt models.

### Version

0.12.0-tensorrt

### Frigate config file

```yaml
mqtt :
  host: [IP]
  user: [USER]
  password: [PASSWORD]
ffmpeg:
  hwaccel_args: preset-nvidia-h264
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /trt-models/yolov7-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
go2rtc:
  streams:
    Oeil_De_Sauron:
      - rtsp://[USER]:[PASSWORD]@[IP]/h264Preview_01_main
      - "ffmpeg:back#audio=aac"
    Oeil_De_Sauron_Sub:
      - rtsp://[USER]:[PASSWORD]@[IP]/h264Preview_01_sub
    Oeil_De_Moscou:
      - rtsp://[USER]:[PASSWORD]@[IP]/h264Preview_01_main
      - "ffmpeg:back#audio=aac"
    Oeil_De_Moscou_Sub:
      - rtsp://[USER]:[PASSWORD]_@[IP]/h264Preview_01_sub
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
cameras:
  Oeil_De_Sauron:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://localhost:8554/Oeil_De_Sauron?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/Oeil_De_Sauron_Sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
    record:
      events:
        objects:
          - person
          - car
    snapshots:
      retain:
        objects:
          person: 7
          car: 7
    zones:
      rue:
        coordinates: 1205,843,1392,0,578,0,795,847
      porche:
        coordinates: 797,850,1194,851,1321,1080,731,1080
  Oeil_De_Moscou:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://localhost:8554/Oeil_De_Moscou?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/Oeil_De_Moscou_Sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - dog
    record:
      events:
        objects:
          - cat
          - dog
    snapshots:
      retain:
        objects:
          person: 0
timestamp_style:
  position: tl
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
detect:
  width: 1920
  height: 1080
  fps: 10
  stationary:
    interval: 5
    threshold: 50
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
motion:
  threshold: 15
snapshots:
  enabled: True
  clean_copy: True
  timestamp: false
  bounding_box: True
  crop: false
  required_zones: []
  retain:
    default: 7
birdseye:
  enabled: True
  mode: continuous
live:
  height: 720
  quality: 10
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-tensorrt
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "142mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate-config:/config
      - frigate-media:/media/frigate
      - frigate-trt:/trt-models
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8555:8555"
    environment:
      YOLO_MODELS: yolo7-640
      FRIGATE_RTSP_PASSWORD: [PASSWORD]

volumes:
    frigate-media:
        external: true
    frigate-trt:
    frigate-config:
```

### Relevant log output

```shell
sudo docker run --gpus=all --rm -it -e YOLO_MODELS=yolov7-640 -e USE_FP16=False -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:22.07-py3 /tensorrt_models.sh

=====================
== NVIDIA TensorRT ==
=====================

NVIDIA Release 22.07 (build 40077977)
NVIDIA TensorRT Version 8.4.1
Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

https://developer.nvidia.com/tensorrt

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

To install Python sample dependencies, run /opt/tensorrt/python/python_setup.sh

To install the open-source samples corresponding to this TensorRT release version
run /opt/tensorrt/install_opensource.sh.  To build the open source parsers,
plugins, and samples for current top-of-tree on master or a different branch,
run /opt/tensorrt/install_opensource.sh -b <branch>
See https://github.com/NVIDIA/TensorRT for more information.

+ CUDA_HOME=/usr/local/cuda
+ LD_LIBRARY_PATH=/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
+ OUTPUT_FOLDER=/tensorrt_models
+ echo 'Generating the following TRT Models: yolov7-640'
Generating the following TRT Models: yolov7-640
+ mkdir -p /tensorrt_models
+ pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (22.1.2)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 51.0 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.1.2
    Uninstalling pip-22.1.2:
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: '/usr/local/lib/python3.8/dist-packages/pip-22.1.2.dist-info/'

+ git clone --depth 1 https://github.com/yeahme49/tensorrt_demos.git /tensorrt_demos
Cloning into '/tensorrt_demos'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 118 (delta 13), reused 60 (delta 5), pack-reused 0
Receiving objects: 100% (118/118), 192.06 MiB | 18.09 MiB/s, done.
Resolving deltas: 100% (13/13), done.
Updating files: 100% (109/109), done.
+ cd /tensorrt_demos/plugins
+ make all
computes: 52
NVCCFLAGS: -gencode arch=compute_52,code=[sm_52,compute_52]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

Other
