### ISSUE TITLE
Show object masks in debug live view

### ISSUE THREAD

**Issue by robertoprubio** [blakeblackshear/frigate#6698]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to display objects filters at UI

I have defined some objects -> filters -> person -> mask but there's no way to display it in the UI.

Please, add the option to display it at UI -> Camera -> Debug

Example of the config.yml

```
cameras:
  camera_1:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/recibidor
          roles:
            - record
            - detect
    objects:
      filters:
        person:
          mask:
            - 629,506,617,877,503,875,521,623
            - 1750,0,1740,75,1661,66,1661,0

```
