### ISSUE TITLE
[Detector Support]: Running frigate:stable-tensorrt on ARM64 Nvidia Jetson Nano 2GB Developer Kit with TensorRT detector

### ISSUE THREAD

**Issue by damsma** [blakeblackshear/frigate#6700]
### Describe the problem you are having

I want to run frigate:stable-tensorrt on Jetson 2GB with ARM64 CPU (same as the Raspberry PI 4).

The Docker image 'frigate:stable-tensorrt' does not support the platform linux/arm64/v8
but 'frigate:stable' does support it, however - it does not provide TensorRT support.

I already successfully converted the models, this issue is the last step for me to run Frigate with TensorRT support.

Any chance enabling the platform for this container?
Or is it somehow possible to install the dependencies manually in the standard frigate:stable container?

### Version

stable-tensorrt 0.12.0-tensorrt master-da3e197-tensorrt

### Frigate config file

```yaml
mqtt:
  host: host.local
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.111.111/media/video1
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate-tensorrt --gpus all --restart=unless-stopped --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000  --shm-size=512m  -v /docker_config/frigate/data:/media/frigate -v /docker_config/frigate/trt-models:/trt-models -v /docker_config/frigate/config:/config -v /etc/localtime:/etc/localtime:ro -e FRIGATE_RTSP_PASSWORD='xxx' -p 5000:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp ghcr.io/blakeblackshear/frigate:stable-tensorrt
```

### Relevant log output

```shell
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

root@jetson-2gb:/# docker logs -f frigate-tensorrt
exec /init: exec format error
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Dev Board

### Any other information that may be helpful

Here is how i converted the models, the method from the [official documentation](https://docs.frigate.video/configuration/detectors) is not supported on the Jetson Nano 2GB, because the docker container brings an error, on the Jetson Nano 2GB i was able to run it directly on Jetpack.

```shell
mkdir trt-models
wget https://github.com/blakeblackshear/frigate/raw/master/docker/tensorrt_models.sh
chmod +x tensorrt_models.sh
```

but then instead of
```shell
docker run --gpus=all --rm -it -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:22.07-py3 /tensorrt_models.sh
```

do the following;
i had to adapt the script:

```shell
nano tensorrt_models.sh
```

```shell
#!/bin/bash

set -euxo pipefail

CUDA_HOME=/usr/local/cuda
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
OUTPUT_FOLDER=/tensorrt_models
echo "Generating the following TRT Models: ${YOLO_MODELS:="yolov4-tiny-288,yolov4-tiny-416,yolov7-tiny-416"}"

# Create output folder
mkdir -p ${OUTPUT_FOLDER}

# Install packages
pip install --upgrade pip && pip install onnx==1.9.0 protobuf==3.19.6

# Clone tensorrt_demos repo
git clone --depth 1 https://github.com/yeahme49/tensorrt_demos.git /tensorrt_demos

# Build libyolo
cd /tensorrt_demos/plugins && make all
cp libyolo_layer.so ${OUTPUT_FOLDER}/libyolo_layer.so

# Download yolo weights
cd /tensorrt_demos/yolo && ./download_yolo.sh

# Build trt engine
cd /tensorrt_demos/yolo

for model in ${YOLO_MODELS//,/ }
do
    OPENBLAS_CORETYPE=CORTEXA57 python3 yolo_to_onnx.py -m ${model}
    OPENBLAS_CORETYPE=CORTEXA57 python3 onnx_to_tensorrt.py -m ${model}
    cp /tensorrt_demos/yolo/${model}.trt ${OUTPUT_FOLDER}/${model}.trt;
done

cp /tensorrt_models/*.trt trt-models/
``` 

also add some enviroment variables at the end of the file

```shell
nano ~/.bashrc
```

```shell

# Add this to your .bashrc file
export CUDA_HOME=/usr/local/cuda
# Adds the CUDA compiler to the PATH
export PATH=$CUDA_HOME/bin:$PATH
# Adds the libraries
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

export PYTHONPATH=/usr/lib/python3.6/dist-packages:$PYTHONPATH

export OPENBLAS_CORETYPE=CORTEXA57
``` 
exit and reopen the console, cd into the dir where the script is and run the script

```shell
./tensorrt_models.sh
```

### additional information

It was all done on this official image for the Nano 2GB

[jetson-nano-2gb-jp461-sd-card-image.zip](https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/jp_4.6.1_b110_sd_card/jetson_nano_2gb/jetson-nano-2gb-jp461-sd-card-image.zip)

this means it runs on Ubuntu 18.04.6 LTS
and JetPack 4.6.1, which includes TensorRT 8.2.1, cuDNN 8.2.1, CUDA 10.2

which cannot be updated on the 2GB version (there is a 4GB version with Ubuntu 20 and CUDA 11 support).

the [official Frigate documentation](https://docs.frigate.video/configuration/detectors) stats, that only CUDA 11.x series is supported, we will see if it works then.
