### ISSUE TITLE
[Config Support]: help with updating config from beta 12 to stable 12 with http stream and go2rtc

### ISSUE THREAD

**Issue by paultanger** [blakeblackshear/frigate#6702]
### Describe the problem you are having

Hi, I need some help updating my config from a beta version of 12 that was running fine, to the stable version of 12 with go2rtc setup. I've read the docs a couple times and tried different configurations, but I can't figure out how to get a combination of h264 streams, and a http mjpeg stream working.  The h264 streams are working, but the http stream is not.

This is what was working in my beta config file:
```
      inputs:
        - path: rtsp://localhost:8554/pi-cam
          roles:
            - detect
            - record
        - path: http://user:pass@ip:port/
          roles:
            - restream
   restream:
      enabled: true
      video_encoding: h264
```

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# this just the relevant parts of the config file..
# I replaced user and pass and pi
ffmpeg:
  hwaccel_args: preset-nvidia-h264 # for nvidia
go2rtc:
  streams:
    pi-cam: 
      - "ffmpeg:http://user:pass@ip:port#video=h264#hardware" 
cameras:
  front:
    ui:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
  pi-cam:
    ui:
      order: 3
    timestamp_style:
      position: "tr"
      color:
        red: 255
        green: 255
        blue: 255
    ffmpeg:
      #hwaccel_args: mjpeg_cuvid ???
      inputs:
        # - path: rtsp://localhost:8554/pi-cam ?? or use IP?
        - path: rtsp://127.0.0.1:8554/pi-cam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
```

### Relevant log output

```shell
2023-06-04 15:40:22.023015415  [2023-06-04 15:40:22] ffmpeg.pi-cam.detect           ERROR   : rtsp://127.0.0.1:8554/pi-cam: Invalid data found when processing input
```

```shell
2023-06-04 15:45:51.835984065  15:45:51.835 ERR [exec] timeout url="exec:ffmpeg -hide_banner -v error -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 2 -fflags nobuffer -flags low_delay -i http://user:pass@ip:port -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/f1a58da90ac8b975c4ad9f9fad3cdfa0"
2023-06-04 15:45:51.836233792  15:45:51.835 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error=timeout url=ffmpeg:http://user:pass@ip:port#video=h264#hardware
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

PCIe
