### ISSUE TITLE
[Support]: Cant concatenate a custom mp4 file to a recording using recording_clip method

### ISSUE THREAD

**Issue by SantiagoGrossi** [blakeblackshear/frigate#6703]
### Describe the problem you are having

Hello. I am trying to concatenate a custom mp4 file to every recording clip pulled from the api using the followind code

 for clip in recordings:
        playlist_lines.append(f"file '{clip.path}'")
        # if this is the starting clip, add an inpoint
        if clip.start_time < start_ts:
            playlist_lines.append(f"inpoint {int((start_ts - clip.start_time))}")
        # if this is the ending clip, add an outpoint
        if clip.end_time > end_ts:
            playlist_lines.append(f"outpoint {int(((end_ts+3) - clip.start_time))}")

    playlist_lines.append(f"file '../../media/frigate/srEnd2.mp4'")

The problem is that vlc and others dont get right the outpoint i think, for my case end_ts should be max 10 seconds and srEnd2.mp4 is always 3s, thats why end_ts+3.  but vlc and others players set the outpoint to random values closest to minutes than seconds 

i dont know what is happening, did anybody tried this before? metadata of srEnd2.mp4 not correctly?

Thanks!!!

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.28
  user: publico
  password: 12sgrossi34
record:
  enabled: True
  retain_days: 7
  events:
    retain:
      default: 7

snapshots:
  enabled: True
  bounding_box: True
  crop: false
  retain:
    default: 7
 
 
cameras:
  frontyard:
    ffmpeg:
      inputs:
        - path: camerapath
          roles:
            - rtmp
            - record
      hwaccel_args: preset-vaapi
    rtmp:
      enabled: False
    detect:
        enabled: False
  nueva:
    ffmpeg:
      output_args:
          record: preset-record-generic-audio-aac
      inputs:
        - path: camerapath
          roles:
            - rtmp
            - record
      hwaccel_args: preset-vaapi
    rtmp:
      enabled: False
    detect:
        enabled: False
  otra:
      ffmpeg:
        output_args:
          record: preset-record-generic-audio-aac
        inputs:
          - path:camerapath
            roles:
              - rtmp
              - record
        hwaccel_args: preset-vaapi
      rtmp:
        enabled: False
      detect:
        enabled: False
  patio:
      ffmpeg:
        inputs:
          - path: camerapath
            roles:
              - rtmp
              - record
        hwaccel_args: preset-vaapi
      rtmp:
        enabled: False
      detect:
        enabled: False
  otracamara:
      ffmpeg:
        inputs:
          - path: camerapath
            roles:
              - rtmp
              - record
        hwaccel_args: preset-vaapi
      rtmp:
        enabled: False
      detect:
        enabled: False
  otracamarita:
      ffmpeg:
        inputs:
          - path: camerapath
            roles:
              - rtmp
              - record
        hwaccel_args: preset-vaapi
      rtmp:
        enabled: False
      detect:
        enabled: False
```

### Relevant log output

```shell
nothing here
```

### FFprobe output from your camera

```shell
Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1280x720
FPS: 25/1
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision ds-2cv1012g0-id21
