### ISSUE TITLE
[Support]: MQTT Frigate spamming log - New connections

### ISSUE THREAD

**Issue by theunclebobbyb** [blakeblackshear/frigate#6718]
### Describe the problem you are having

Is it normal for Frigate to be constantly creating new connections with my mqtt broker? Frigate does this non stop and I want to make sure its not an issue. My mqtt events sometimes don't get logged in my home assistant logbook so I'm looking into possible issues with my setup and ran across this. 

![image](https://github.com/blakeblackshear/frigate/assets/65047160/c9d750a2-a85b-484e-b82a-0dd4fadd5bbe)

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 10.10.88.10

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac
    
    
go2rtc:
  streams:
    Wahoo-House-Front:
      - rtsp://172.30.0.5:7447/6333ab58e4b042ee37865a9f_0
    Wahoo-House-Back:
      - rtsp://172.30.0.5:7447/6338897ee4b0e266ae3c47b7_0
    Weston-Shop-Back:
      - rtsp://172.30.0.5:7447/63388a22e4b0e266ae3c47cb_0
    Weston-Shop-Front:
      - rtsp://172.30.0.5:7447/63388a3ae4b0e266ae3c47e5_0

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1

cameras:
  Wahoo-House-Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Wahoo-House-Front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: True
      events:
        required_zones:
          - front_driveway
          - front_yard
          - front_road
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
    snapshots:
      enabled: True
    motion:
      improve_contrast: True
      mask:
        - 600,0,496,169,414,313,298,310,303,176,178,159,212,0
        - 0,0,331,0,332,87,0,87
        - 666,266,858,247,934,150,786,0,646,0,603,150
        - 0,0,140,0,185,131,203,273,128,332,0,376
        - 569,101,1195,121,1190,0,703,0
    objects:
      track:
        - person
        - dog
        - car
      filters:
        car:
          mask: 
            - 266,1080,1920,1080,1920,374,819,215,0,535
            - 1182,0,924,112,711,99,798,0
        person:
          mask: 
            - 401,957,417,957,478,982,529,1009,638,1001,786,1080,907,1080,1076,1080,1380,1007,1333,773,1414,525,921,409,334,698
            - 1182,0,924,112,711,99,798,0
    zones:
      front_yard:
        coordinates: 797,238,563,199,490,199,427,195,379,189,304,181,187,219,113,253,0,370,0,505,140,537
        objects:
          - person
          - dog
          - car
        filters:
          person:
            threshold: 0.5
      front_driveway:
        coordinates: 1920,416,1718,381,1300,320,898,222,849,233,397,330,37,557,24,663,238,1080,1920,1080
        objects:
          - person
          - dog
      front_road:
        coordinates: 1508,0,1036,0,908,0,875,0,770,0,604,0,372,70,0,194,0,253,271,190,478,126,680,141,889,132,860,207,1920,358,1920,0,1844,0
        objects:
          - car
          - person
  Wahoo-House-Back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Wahoo-House-Back
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: True
      events:
        required_zones:
          - backyard_pool
          - backyard
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          mask:
            - 672,467,692,414,686,377,634,348,586,372,549,408,547,461
            - 1442,334,1519,331,1507,239,1439,247
    motion:
      mask:
        - 1140,309,986,302,806,291,630,260,629,339,493,351,377,420,156,436,0,454,0,0,788,0,855,0,926,0,983,0,1045,0,1198,0,1920,0,1920,233,1510,182,1385,254,1321,270
        - 1920,775,1920,404,1847,358,1714,374,1588,426,1497,578,1609,700
        - 1097,257,1046,335,1031,417,971,417,932,256
    zones:
      backyard_pool:
        coordinates: 561,800,705,764,851,726,970,655,963,643,992,616,962,554,879,491,606,457,414,460,226,505,52,598,21,700,107,762,251,791,353,807
        objects:
          - person
          - dog
          - cat
      backyard_near_pool:
        coordinates: 624,1080,1186,854,1028,747,920,744,993,657,1249,654,1247,493,1002,453,885,395,888,511,949,549,977,561,996,610,963,676,895,730,667,799,608,805,518,814,413,819
        objects:
          - person
      backyard:
        coordinates: 908,426,1006,449,1244,461,1283,490,1102,841,627,1019,278,814,0,691,0,1080,1895,1080,1920,511,1920,402,1920,303,1702,285,1550,226,1452,231,1398,269,1239,262,1201,272,638,326,352,411,0,471,0,659,345,471,402,458,692,446
        objects:
          - person
          - dog
          - cat
  Weston-Shop-Back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Weston-Shop-Back
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: True
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
    objects:
      track:
        - person
    snapshots:
      enabled: True
    motion:
        mask:
            - 0,0,328,0,328,83,0,78
  Weston-Shop-Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Weston-Shop-Front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: True
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
    objects:
      track:
        - person
    snapshots:
      enabled: True
    motion:
        mask:
            - 0,0,328,0,328,83,0,78
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

UBNT
