### ISSUE TITLE
[Support]: No Space left on the device

### ISSUE THREAD

**Issue by denveronly** [blakeblackshear/frigate#6721]
### Describe the problem you are having

Hello all,
Im running frigate on Unraid in docker container.
Container space is way more i can use. Frigate Media is a separate Unraid Share which has tonns of space. Despite that i fall in to abnormal operation with no space left

Docker has 500Gib to deal with only 8 Gib Filled
![image](https://github.com/blakeblackshear/frigate/assets/66441516/f2ed61c3-bd34-4aec-b7d5-db2b3a9a65bc)
![image](https://github.com/blakeblackshear/frigate/assets/66441516/f6dfee4a-8083-44b2-ab99-808783078a50)

Docker saves in Media Share which has tonns of space.
![image](https://github.com/blakeblackshear/frigate/assets/66441516/8e5c953a-ecad-4c95-aa9c-bc94ac658b4d)

Why am i facing such problem?

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.101
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: mqtt
  # Optional: user
  user: mqtt
  password: mqtt

go2rtc:
  streams:
    dahuatop:
      - rtsp://lmonitor?channel=1&subtype=0
    dahuatop_sub:
      - rtsp://cam/realmonitor?channel=1&subtype=1
    door:
      - rtsp://realmonitor?channel=1&subtype=0
    door_sub:
      - rtsp:///realmonitor?channel=1&subtype=1
    palubagarage:
      - rtsp:///Streaming/channels/1302
    ellinggarage:
      - rtsp://
    palubawater:
      - rtsp://h264Preview_01_main
    palubawater_sub:
      - rtsp:///h264Preview_01_sub

detectors:
  coral:
    type: edgetpu
    device: usb
    
birdseye: 
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: objects
  restream: True

objects:
  filters:
    person:
      min_score: 0.76
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.77
      min_area: 4000 
    car: 
      min_score: 0.75
  track:
    - person
    - car



# snapshots:
#   enabled: true
#   retain:
#     # Required: Default retention days (default: shown below)
#     default: 14
#     # Optional: Per object retention days
#     objects:
#       person: 14

cameras:

  PalubaGarage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/palubagarage
          input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://Streaming/channels/1302
          roles:
              - record    
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 1280,83,1280,371,1280,720,1120,720,915,720,925,373,947,76
        - 0,720,0,587,0,383,110,361,332,269,514,219,637,426,733,581,735,720
        - 183,304,365,251,373,111,360,0,129,0
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 665,505,603,720,363,684,536,415
            - 347,720,647,720,689,526,502,421
            - 913,458,906,322,821,318,821,467
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 900
        
      
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp:///Streaming/channels/1402
          roles:
            - detect

        - path: rtsp://Streaming/channels/1401
          roles:
              - record
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask:
        - 706,68,1232,68,1225,27,704,29
    objects:
      filters:
        person:
          mask:
            - 407,44,415,138,287,131,289,46 
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1200
  

  Paluba:
    ffmpeg:
      inputs:
        - path: rtsp://Streaming/channels/1502
          roles:
            - detect

        - path: rtsp://Streaming/channels/1501
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 1280,0,809,0,781,48,1280,136
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.65
          threshold: 0.75
          min_area: 9000 
          mask:
            - 315,495,285,438,270,395,263,341,283,308,315,301,359,302,375,366,384,465,371,521
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1200


  TerracePaluba:
    ffmpeg:
      inputs:
        - path: rtsp://Streaming/channels/702
          roles:
            - detect

        - path: rtsp:///Streaming/channels/701
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask:
        - 844,62,1253,63,1246,25,849,23
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 671,502,565,672,354,579,382,190
            - 620,261,648,356,594,361,569,259
            - 563,245,587,388,494,395,455,258
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1200


          
  PalubaWater:
    ffmpeg:
      inputs:
        - path: rtsp://
          input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1200
      

        

####
  TerraceSlidingDoor:
    ffmpeg:
      inputs:
        - path: rtsp:///Streaming/channels/602
          roles:
            - detect

        - path: rtsp:///Streaming/channels/601
          roles:
            - record

    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask:
        - 0,135,422,81,424,49,0,0
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 756,0,758,106,656,114,649,0
            - 1053,105,1043,196,977,172,998,94
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1200
          



###
  # EllingGarage:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - detect

  #           - record
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 7
  #   objects:
  #     track:
  #       - person
      
  #     filters:
  #       person:
  #         min_score: 0.65
  #         threshold: 0.75
  #         mask:
  #           - 381,425,421,541,128,508,159,337
  #           - 1123,460,1150,632,127,515,146,339
  #   snapshots:
  #     enabled: true
  #     timestamp: true
  #     bounding_box: true
  #     retain: 
  #       default: 2
  #   record:
  #     enabled: True
  #     events:
  #       retain:
  #         default: 7
  #   mqtt:
  #     timestamp: False
  #     bounding_box: False
  #     crop: True
  #     height: 1200

### CAMERA ENTRAANCE DOOR

  Door:
    ffmpeg:
      inputs:
        - path: rtsp://
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.6
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
          min_area: 2000
        



    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
      required_zones:
        - near
    
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1200
    zones:
      near:
        coordinates: 1101,720,769,310,38,241,0,720
          
###GARAGE INSIDE
        
  Garageinside:
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - detect
 
        - path: rtsp://
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1200
      
##DAHUATOP
  DahuaTOP:
    ffmpeg:
      inputs:
        - path: rtsp://
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 2048
      height: 1152
      fps: 20
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      events:
        retain:
          default: 7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 2000
```

### Relevant log output

```shell
2023-06-06 22:47:40.989499989  [2023-06-06 22:47:40] frigate.record                 WARNING : Unable to keep up with recording segments in cache for Garageinside. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-06-06 22:47:40.989503562  [2023-06-06 22:47:40] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-06-06 22:47:40.989505202  [2023-06-06 22:47:40] frigate.record                 ERROR   : list index out of range
2023-06-06 22:47:45.758347500  [2023-06-06 22:47:45] ffmpeg.Paluba.record           ERROR   : av_interleaved_write_frame(): No space left on device
2023-06-06 22:47:45.758351199  [2023-06-06 22:47:45] ffmpeg.Paluba.record           ERROR   : [segment @ 0x55da8728ae00] Failure occurred when ending segment '/tmp/cache/Paluba-20230606224736.mp4'
2023-06-06 22:47:45.758353119  [2023-06-06 22:47:45] ffmpeg.Paluba.record           ERROR   : Error writing trailer of /tmp/cache/Paluba-%Y%m%d%H%M%S.mp4: No space left on device
2023-06-06 22:47:45.758399111  [2023-06-06 22:47:45] watchdog.Paluba                INFO    : Terminating the existing ffmpeg process...
2023-06-06 22:47:45.758511130  [2023-06-06 22:47:45] watchdog.Paluba                INFO    : Waiting for ffmpeg to exit gracefully...
2023-06-06 22:47:45.988180570  [2023-06-06 22:47:45] frigate.record                 WARNING : Unable to keep up with recording segments in cache for Garage. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-06-06 22:47:45.989978516  [2023-06-06 22:47:45] frigate.record                 WARNING : Unable to keep up with recording segments in cache for Paluba. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-06-06 22:47:45.991164217  [2023-06-06 22:47:45] frigate.record                 WARNING : Unable to keep up with recording segments in cache for PalubaGarage. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-06-06 22:47:45.991474027  [2023-06-06 22:47:45] frigate.record                 WARNING : Unable to keep up with recording segments in cache for PalubaWater. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-06-06 22:47:45.992575660  [2023-06-06 22:47:45] frigate.record                 WARNING : Unable to keep up with recording segments in cache for TerracePaluba. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-06-06 22:47:46.066887838  [2023-06-06 22:47:46] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/DahuaTOP-20230606224736.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f48593c6c0] moov atom not found\n/tmp/cache/DahuaTOP-20230606224736.mp4: Invalid data found when processing input\n'
```

### FFprobe output from your camera

```shell
ok
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua, Hik
