### ISSUE TITLE
[Support]: Failed - Network error when downloading clip / Failed - No file when downloading snapshot

### ISSUE THREAD

**Issue by DNA99** [blakeblackshear/frigate#6723]
### Describe the problem you are having

When I click on the download button to download clip, I get the "Failed - Network error" and when I select download snapshot, I get the "Failed - No file" error.

### Version

Frigate (0.12.0-da3e197)

### Frigate config file

```yaml
mqtt:
  host: 12.10.1.22
  user: MYID
  password: MYPASSWORD

cameras:
  VTO:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Pa55word@12.10.1.2:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:Pa55word@12.10.1.2:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 800
      height: 480
      fps: 7
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
    record:
      enabled: true

detectors:
  cpu1:
    type: cpu
    num_threads: 4
  coral1:
    type: edgetpu
    device: pci:0
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
How do I do this?
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dahua
