### ISSUE TITLE
[Support]: Recording too late 

### ISSUE THREAD

**Issue by tidde88** [blakeblackshear/frigate#6728]
### Describe the problem you are having

The camera at the entrance detects a person and takes a snapshot and the recording is too late. Sometimes 20-30 seconds after the photo.

### Version

12.0

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    Eingang: 
      - rtsp://XXXXXX@XXXXX:554/h264Preview_01_main
    Eingang_sub: 
      - rtsp://XXXXXX@XXXXXXX:554/h264Preview_01_sub
    Terasse: 
      - rtsp://XXXXXX@XXXXXX:554/h264Preview_01_main
    Terasse_sub: 
      - rtsp://XXXXXX@XXXXX554/h264Preview_01_sub

cameras:
  Eingang:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Eingang_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    live:
      quality: 4
    objects:
      track:
        - person
    snapshots:
      enabled: true
      quality: 100
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
    motion:
      mask:
      - 155,127,300,0,0,0,0,35,0,244
      - 206,0,434,0,440,67,203,73
  Terasse:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Terasse?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Terasse_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    live:
      quality: 4
    objects:
      track:
        - person
    snapshots:
      enabled: true
      quality: 100
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        pre_capture: 10
        post_capture: 10
    motion:
      mask:
       - 0,97,640,108,640,0,0,0
```

### Relevant log output

```shell
2023-06-07 12:28:29.214417741  [INFO] Starting Frigate...
2023-06-07 12:28:30.471230060  [2023-06-07 12:28:30] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-06-07 12:28:30.493437325  [2023-06-07 12:28:30] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-06-07 12:28:30.499966166  [2023-06-07 12:28:30] peewee_migrate                 INFO    : Starting migrations
2023-06-07 12:28:31.054461702  [2023-06-07 12:28:31] peewee_migrate                 INFO    : There is nothing to migrate
2023-06-07 12:28:31.101261744  [2023-06-07 12:28:31] frigate.app                    INFO    : Output process started: 289
2023-06-07 12:28:31.109307759  [2023-06-07 12:28:31] frigate.app                    INFO    : Camera processor started for Eingang: 291
2023-06-07 12:28:31.122322984  [2023-06-07 12:28:31] frigate.app                    INFO    : Camera processor started for Terasse: 292
2023-06-07 12:28:31.132166415  [2023-06-07 12:28:31] detector.ov                    INFO    : Starting detection process: 288
2023-06-07 12:28:31.134200292  [2023-06-07 12:28:31] frigate.app                    INFO    : Capture process started for Eingang: 295
2023-06-07 12:28:31.149929250  [2023-06-07 12:28:31] frigate.app                    INFO    : Capture process started for Terasse: 299
2023-06-07 12:28:31.251703930  [35mE: [xLinkUsb] [    911251] [frigate.detecto] usb_find_device_with_bcd:266	Library has not been initialized when loaded[0m
2023-06-07 12:28:31.252342079  [35mE: [xLinkUsb] [    911252] [frigate.detecto] usb_find_device_with_bcd:266	Library has not been initialized when loaded[0m
2023-06-07 12:28:31.472396473  [2023-06-07 12:28:31] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-06-07 12:28:31.472399964  [2023-06-07 12:28:31] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-06-07 12:28:31.472404692  [2023-06-07 12:28:31] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### FFprobe output from your camera

```shell
ffprobe rtsp://XXXXXXX@XXXXXX:554/h264Preview_01_main
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://XXXXXX@XXXXX:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.001250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 30 fps, 30 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"Eingang":{"camera_fps":7.1,"capture_pid":295,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":300,"pid":291,"process_fps":7.1,"skipped_fps":0.0},"Terasse":{"camera_fps":7.1,"capture_pid":299,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":305,"pid":292,"process_fps":7.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.5"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"0.7","mem":"0.9"},"113":{"cpu":"0.0","mem":"0.1"},"118":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"0.5"},"287":{"cpu":"0.3","mem":"0.1"},"288":{"cpu":"0.0","mem":"2.6"},"289":{"cpu":"0.3","mem":"0.6"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"0.7","mem":"0.6"},"292":{"cpu":"0.7","mem":"0.6"},"295":{"cpu":"1.0","mem":"0.5"},"296":{"cpu":"0.0","mem":"0.1"},"299":{"cpu":"1.0","mem":"0.5"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"2.0","mem":"0.3"},"303":{"cpu":"0.0","mem":"0.1"},"305":{"cpu":"2.0","mem":"0.4"},"307":{"cpu":"0.0","mem":"0.1"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"1.7","mem":"0.1"},"312":{"cpu":"1.0","mem":"0.1"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"455":{"cpu":"0.0","mem":"0.0"},"473":{"cpu":"0.0","mem":"0.0"},"479":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"92":{"cpu":"8.0","mem":"0.1"},"MiB":{"cpu":"7866.9","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"ov":{"detection_start":0.0,"inference_speed":11.12,"pid":288}},"gpu_usages":{"intel-vaapi":{"gpu":"0.86 %","mem":"- %"}},"service":{"last_updated":1686141061,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":132.3,"mount_type":"tmpfs","total":134.2,"used":1.9},"/media/frigate/clips":{"free":2809872.0,"mount_type":"nfs4","total":3936788.4,"used":926862.0},"/media/frigate/recordings":{"free":2809872.0,"mount_type":"nfs4","total":3936788.4,"used":926862.0},"/tmp/cache":{"free":991.3,"mount_type":"tmpfs","total":1000.0,"used":8.7}},"temperatures":{},"uptime":150,"version":"0.12.0-da3e197"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC 510WA
