### ISSUE TITLE
[Support]: Problem to play events on Android Phones with Chorme

### ISSUE THREAD

**Issue by Snobs76** [blakeblackshear/frigate#6736]
### Describe the problem you are having

Hello,

I updated my working Docker Installation to 12:stable. Now I cant view the event recordings at any of our Samsung phone either S20 or S21. Event videos with chrome browser at pc is still working. How can I fix that issue to view that files at my phones again:

GET /vod/event/1686205761.294728-1zu3f8/seg-1-v1.ts the url request from phone looks correct

BR
Sascha

### Version

12:stable

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.x
  user: my_secret_user
  password: "{FRIGATE_MQTT_PASSWORD}"

detectors:
  coral:
    type: edgetpu

ffmpeg:
  hwaccel_args: preset-intel-qsv-h265

live:
  height: 768

objects:
  track:
    - person
    - umbrella
    - car
    - bicycle
    - motorcycle
    - cat
    - dog

record:
  enabled: True
  expire_interval: 240
  retain:
    mode: motion
  events:
    objects:
      - person
      - car
      - umbrella
      - bicycle
      - motorcycle
      - cat
      - dog
    required_zones: []
    retain:
      default: 21
      mode: active_objects
      objects: 
        cat: 7
        dog: 7

snapshots:
  enabled: True

birdseye:
  enabled: True
  width: 1024
  height: 768
  quality: 2
  mode: objects

#restream:
#  force_audio: false
#  video_encoding: "copy"

cameras:
  Camera_1:
  # E1 Outdoor
    enabled: True
    ffmpeg:
      input_args: preset-http-reolink
      #input_args: preset-rtsp-udp
      #input_args: preset-rtsp-generic
      
      inputs:
      #  - path: http://192.168.x.x/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
      #    roles:
      #      - detect
        - path: http://192.168.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
      #  - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.x.x:554/h264Preview_01_main

          roles:
              #- restream
            - rtmp
            - record
            - detect

    detect:
      width: 1024
      height: 768
      fps: 5

    motion:
      mask:
        - 272,768,444,768,677,690,649,603,595,586,580,611,546,622,500,620,449,664,330,657,299,658,238,692
        - 1024,0,1024,241,971,253,868,107,849,32,913,35,915,0
```

### Relevant log output

```shell
GET /vod/event/1686205761.294728-1zu3f8/seg-1-v1.ts
```

### FFprobe output from your camera

```shell
/
```

### Frigate stats

```json
{"Camera_1":{"camera_fps":5.0,"capture_pid":423,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":431,"pid":422,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"4.3"},"1":{"cpu":"0.0","mem":"0.0"},"108":{"cpu":"0.0","mem":"0.0"},"113":{"cpu":"0.0","mem":"0.6"},"120":{"cpu":"0.0","mem":"0.0"},"124":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"130":{"cpu":"0.0","mem":"0.0"},"131":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"18":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"33":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"410":{"cpu":"0.0","mem":"0.2"},"416":{"cpu":"0.0","mem":"0.0"},"417":{"cpu":"0.0","mem":"0.3"},"418":{"cpu":"0.0","mem":"0.3"},"422":{"cpu":"0.0","mem":"0.3"},"423":{"cpu":"0.7","mem":"0.3"},"425":{"cpu":"0.0","mem":"0.0"},"43":{"cpu":"0.0","mem":"0.0"},"431":{"cpu":"2.3","mem":"0.1"},"432":{"cpu":"0.0","mem":"0.0"},"634":{"cpu":"0.0","mem":"0.0"},"644":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"85":{"cpu":"0.0","mem":"0.0"},"97":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"9435.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.56,"pid":417}},"gpu_usages":{"intel-qsv":{"gpu":"1.09 %","mem":"- %"}},"service":{"last_updated":1686207095,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":266.6,"mount_type":"tmpfs","total":268.4,"used":1.8},"/media/frigate/clips":{"free":14047.4,"mount_type":"zfs","total":75161.9,"used":61114.5},"/media/frigate/recordings":{"free":14047.4,"mount_type":"zfs","total":75161.9,"used":61114.5},"/tmp/cache":{"free":497.1,"mount_type":"tmpfs","total":500.0,"used":2.9}},"temperatures":{},"uptime":418,"version":"0.12.0-da3e197"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink E1 Outdoor
