### ISSUE TITLE
[Support]: Disk space usage 

### ISSUE THREAD

**Issue by shawwellpete** [blakeblackshear/frigate#6738]
### Describe the problem you are having

Hi guys, 

Thank you first for a great product. This is a minor problem but I have not found a solution despite searching.

I continuous streams onto an external HDD. On older versions of frigate, after a reboot, if the HDD was not switched on Frigate would not start. It seems that on recent versions, if the HDD is not connected, Frigate continues to work and save footage somewhere onto the root drive on the machine that hosts docker and Frigate. This happened recently and I noticed the the internal hard drive had nearly filled up. 

I am trying to clean this video from the hard drive but have no idea where it is installed.

Running a df - h command suggests that the data mayhave been stored in var/lib/docker/overlay2 

![image](https://github.com/blakeblackshear/frigate/assets/74064242/c39db2af-f8bd-4623-b92e-e8d563ed423d)

I have run docker system prune -a -f which reduced  the disk usage a bit but there is still 146gb being used.

There is a chance this disk use is nothing to do with Frigate but it seemed to happen when the external HDD was not powered on after a reboot so I'm guessing it is linked.

Any suggestions would be welcome, thank you.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.11
  user: homeassistant
  password: ****

#database:
  #path: /frigate.db

#https://blakeblackshear.github.io/frigate/configuration/advanced#logger
#logger:
  #default: debug #info

detectors:
  coral:
    type: edgetpu
    device: usb
go2rtc:
  streams:
    back:
      - rtsp://admin:***@192.168.1.24:554/ 
    back_sub:
      - rtsp://admin:***@192.168.1.22:554//h264Preview_01_sub 


cameras: 
  front: #REOLINK RLC-810A 
    ffmpeg: 
      inputs: 
        - path: rtsp://admin:***@192.168.1.22:554//h264Preview_01_sub 
          roles: 
            - rtmp 
        - path: rtsp://admin:***@192.168.1.22:554/          
          roles: 
            - detect 
            - record 
  gate: #REOLINK RLC-820A  
    ffmpeg: 
      inputs: 
        - path: rtsp://admin:***@192.168.1.21:554//h264Preview_01_sub 
          roles: 
            - rtmp 
        - path: rtsp://admin:***@192.168.1.21:554/           
          roles:  
            - detect 
            - record 

  side: #REOLINK RLC-810A  
    ffmpeg: 
      inputs: 
        - path: rtsp://admin:****@192.168.1.23:554//h264Preview_01_sub 
          roles: 

            - rtmp 
        - path: rtsp://*?**:010800@192.168.1.23:554/           
          roles:  
            - detect 
            - record 
  back: #REOLINK RLC-820A  
    ffmpeg: 
      inputs: 
        - path: rtsp://admin:****@192.168.1.24:554//h264Preview_01_sub 
          roles: 

            - rtmp 
        - path: rtsp://admin:****@192.168.1.24:554/           
          roles:  
            - detect 
            - record


detect:
  width: 2560
  height: 1440
  fps: 5

objects:
  track:
    - person
    - dog
    - car
  filters: 
    person: 
      # Optional: minimum width*height of the bounding box for the detected object (default: 0) 
      min_area: 8000 
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000) 
      #max_area: 100000 
      # Optional: minimum score for the object to initiate tracking (default: 0.5) 
      #min_score: 0.5 
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7) 
      threshold: 0.8
birdseye: 
  enabled: True 
  width: 2560 
  height: 1440 
  quality: 8 
  mode: continuous #objects #motion 
record: 
  enabled: True 
  retain:
    days: 30
  events: 
    pre_capture: 3 ##update June from 10 22
    post_capture: 5 ####UPDATED from 10 Jun22
    retain: 
      default: 20


snapshots: 
  enabled: True 
  timestamp: True 
  bounding_box: True 
  crop: True 
  retain: 
    default: 60 
rtmp: 
  enabled: True 

timestamp_style: 
  format: "%m.%d.%Y %H:%M:%S"
ffmpeg: 
  global_args: -hide_banner -loglevel warning #panic #info 
  hwaccel_args: 
    -hwaccel qsv -qsv_device /dev/dri/renderD128 
  #input_args: #https://ffmpeg.org/ffmpeg-formats.html 
    #-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 
  output_args: 
    #detect: -f rawvideo -pix_fmt yuv420p 
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy #-an removed to hear sound 
    #rtmp: -c copy -f flv
```

### Relevant log output

```shell
no relevant log
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

REOLINK RLC-810A
