### ISSUE TITLE
Mask function not working correctly.

### ISSUE THREAD

**Issue by sheminasalam** [blakeblackshear/frigate#674]
I have put a mask in both in motion and object filter for a camera of mine but this is not working.

The following is my config.
```
cameras:
  front_left_cam:
    ffmpeg:
      inputs:
        - path: >-
            rtsp:///cam/realmonitor?channel=8&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
    rtmp:
      enabled: false
    fps: 5
    height: 288
    width: 352
    motion:
      mask: >-
        64,288,59,142,145,108,168,54,274,25,308,45,331,47,327,129,282,214,281,288,352,288,352,0,0,0,0,234,0,288
    best_image_timeout: 30
    snapshots:
      height: 550
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.4
          max_area: 10000
          threshold: 0.6
          mask:
            - >-
              64,288,59,142,145,108,168,54,274,25,308,45,331,47,327,129,282,214,281,288,352,288,352,0,0,0,0,234,0,288
```
This is the mask as shown from the web UI
![image](https://user-images.githubusercontent.com/45196177/106372357-da143880-6394-11eb-8e90-2b0ae363e8c0.png)

You can clearly see that the bottom left corner is completely masked off both motion and detection but still the detection happens. Here is a snapshot.

![image](https://user-images.githubusercontent.com/45196177/106372384-016b0580-6395-11eb-83e7-cae1052cdbe2.png)

Please advise if there is any issue with my config

**Comment by blakeblackshear** [comment]
Are you certain you restarted frigate after updating your config? That looks right.

Unrelated, but I did notice that your snapshot height is set to 550. Since those are created from the detect stream, it will just scale the 288x352 image without improving the clarity.

**Comment by sheminasalam** [comment]
Yes I have restarted frigate many times after updating config. There was also other issues with this camera. i,e it was detecting the car as a person and I reconfigured the area size of the person filter and put an end to it. but this still continues.

thanks for tip about snapshot size. I have also noticed that. Will look into that.

**Comment by blakeblackshear** [comment]
Can you update your snapshot config to the following and attach the image as is next time it happens?
```yaml
    snapshots:
      enabled: True
      bounding_box: True
```

That should save the frame exactly as frigate sees it in the clips directory.
