### ISSUE TITLE
[Support]: Motion detected in the wrong zone

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#6751]
### Describe the problem you are having

I created 2 zones (sidewalk and driveway). I set up driveway to detect only people while sidewalk to detect cars.
What is happening now is that a car stopped on the driveway keep detected as car even without any motion or sometime with someone walking on the sidewalk
You can see from the screeshot that the zone for the event is sidewalk
Check the video too
I am also using the blueprint automation and getting car notification when the car is on the driveway zone,  ( I tried removing drive_way zone from the trigger zone and then I get notifications for car see screenshot)

### Version

0.11.1-2eada21

### Frigate config file

```yaml
# frigate.yml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: caha.duckdns.org
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: xxx
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
rtmp:
  enabled: false

#motion:
#  contour_area: 100
#  delta_alpha: 0.2
#  frame_alpha: 0.2
#  frame_height: 80
#  threshold: 25
  
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  
cameras:
  driveway:
    zones:
      sidewalk:
        coordinates: 114,64,231,43,366,36,425,39,474,50,521,80,553,84,529,51,414,16,302,12,167,21,147,34
        objects:
          - car
      drive_way:
        coordinates: 274,47,441,62,508,76,562,189,550,260,562,286,429,352,0,352,30,207,108,66
        objects:
          - person

    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 114,64,231,43,368,39,415,42,474,50,521,80,553,84,529,51,414,16,302,12,167,21,147,34
          threshold: 0.58
          min_area: 3200
#          max_area: 30320
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@192.168.6.140/2
          roles:
            - detect
        - path: rtsp://xx:xx@192.168.6.140/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 7  
    motion:
      mask:
        - 0,0,181,0,100,81,0,304
        - 640,0,473,0,489,65,571,100,640,191    
        - 234,14,399,18,504,45,464,0,161,1,151,27
    record:
      enabled: true
      retain:
        days: 0
      events:
        required_zones:
          - drive_way
          - sidewalk
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - drive_way
        - sidewalk
      timestamp: True      
      retain:
        default: 7


################################################ 
  front_porch_camera:
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@192.168.6.141/2
          roles:
            - detect
        - path: rtsp://xx:xx@192.168.6.141/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 5  
    motion:
      mask:
        - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: True      
      retain:
        default: 7
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.3 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --enable-chromaprint --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libbs2b --enable-libcdio --enable-libdrm --enable-libjack --enable-libjxl --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libilbc --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-libplacebo --enable-librsvg --enable-librav1e --enable-librubberband --enable-libsmbclient --enable-version3 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libshaderc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://xx:xx@192.168.6.140/2':
  Metadata:
    title           : 11
  Duration: N/A, start: 0.100000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 640x352, 20 fps, 10 tbr, 90k tbn
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Chortau

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/75389943/5f5d8f7b-4c78-4e9b-961a-b155a14e14a3)
![image](https://github.com/blakeblackshear/frigate/assets/75389943/4e540338-6de3-4799-846e-2c836f0d1031)

![image](https://github.com/blakeblackshear/frigate/assets/75389943/5c41f416-8255-4f69-adc4-1d2f0f3fa157)

https://github.com/blakeblackshear/frigate/assets/75389943/de49b8f6-6c06-480f-af45-574d93351484

![image](https://github.com/blakeblackshear/frigate/assets/75389943/3a418944-8a9f-49e7-896d-48e5f4205d2f)

![image](https://github.com/blakeblackshear/frigate/assets/75389943/c3947569-c774-4b59-ac19-fa7680bfbdcb)
