### ISSUE TITLE
[Support]: New storage page reports incorrect used values

### ISSUE THREAD

**Issue by severick** [blakeblackshear/frigate#6757]
### Describe the problem you are having

On the new storage page, it is reporting incorrect values for. 

![image](https://github.com/blakeblackshear/frigate/assets/5041356/294b6560-25c5-40c6-9c4a-19ee62e1f76d)
![image](https://github.com/blakeblackshear/frigate/assets/5041356/cca43d3e-cf42-4812-b15e-a24e0d8fd55b)

### Version

0.12.0-da3e197

### Frigate config file

```yaml
cameras:
  front_yard:
    rtmp:
      enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_DAHUA_USER}:{FRIGATE_DAHUA_PASS}@192.168.10.201
          roles:
            - detect
            - rtmp
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 2688
      height: 1520
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
    motion:
      mask:
              - 860,357,1530,341,1920,356,2293,455,2688,679,2688,557,2688,420,2041,308,1169,188,954,203,1372,275,175,348,140,463

  driveway:
    rtmp:
      enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_DAHUA_USER}:{FRIGATE_DAHUA_PASS}@192.168.10.202 
          roles:
            - detect
            - rtmp
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 2688
      height: 1520
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
    motion:
      mask:    
        - 0,567,670,451,1497,357,2474,321,2688,264,2688,0,0,0
    snapshots:
      enabled: True 


database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    front_yard:
      - rtsp://{FRIGATE_DAHUA_USER}:{FRIGATE_DAHUA_PASS}@192.168.10.201:554/live0
      - "ffmpeg:front_yard#audio=opus"
    driveway:
      - rtsp://{FRIGATE_DAHUA_USER}:{FRIGATE_DAHUA_PASS}@192.168.10.202:554/live0
      - "ffmpeg:driveway#audio=opus"

  webrtc:
    candidates:
      - 192.168.10.120:8555
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.7"},"1":{"cpu":"0.0","mem":"0.0"},"106":{"cpu":"0.0","mem":"0.0"},"107":{"cpu":"5.3","mem":"1.1"},"116":{"cpu":"0.0","mem":"0.1"},"124":{"cpu":"0.3","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"283":{"cpu":"0.0","mem":"0.5"},"289":{"cpu":"0.0","mem":"0.1"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"3.0","mem":"0.7"},"292":{"cpu":"0.7","mem":"0.6"},"30":{"cpu":"0.0","mem":"0.0"},"306":{"cpu":"3.3","mem":"0.6"},"307":{"cpu":"0.0","mem":"0.1"},"308":{"cpu":"4.7","mem":"0.6"},"309":{"cpu":"0.0","mem":"0.1"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"4.0","mem":"0.6"},"312":{"cpu":"4.0","mem":"0.6"},"315":{"cpu":"52.3","mem":"0.7"},"316":{"cpu":"0.0","mem":"0.1"},"32":{"cpu":"0.0","mem":"0.0"},"322":{"cpu":"52.7","mem":"0.7"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"435":{"cpu":"0.0","mem":"0.0"},"532":{"cpu":"0.0","mem":"0.0"},"536":{"cpu":"0.0","mem":"0.0"},"538":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"3313.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"load","mem":"average:"}},"detection_fps":16.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.17,"pid":290}},"driveway":{"camera_fps":5.1,"capture_pid":312,"detection_enabled":1,"detection_fps":11.3,"ffmpeg_pid":322,"pid":308,"process_fps":5.1,"skipped_fps":0.0},"front_yard":{"camera_fps":5.1,"capture_pid":310,"detection_enabled":1,"detection_fps":5.3,"ffmpeg_pid":315,"pid":306,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"service":{"last_updated":1686346518,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":114.7,"mount_type":"tmpfs","total":134.2,"used":19.5},"/media/frigate/clips":{"free":9088243.5,"mount_type":"cifs","total":9192941.4,"used":104697.9},"/media/frigate/recordings":{"free":9088243.5,"mount_type":"cifs","total":9192941.4,"used":104697.9},"/tmp/cache":{"free":980.3,"mount_type":"tmpfs","total":1000.0,"used":19.7}},"temperatures":{"apex_0":47.55},"uptime":70,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

2 x Dahua T5442T

### Any other information that may be helpful

Docker compose file
```
version: '3'

services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
     - /dev/bus/usb:/dev/bus/usb
     - /dev/apex_0:/dev/apex_0
     - /dev/dri/renderD128
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /shared/frigate/config.yaml:/config/config.yml
     - /shared/frigate/storage:/media/frigate
     - /home/severick/docker/frigate/db:/db
     - type: tmpfs
       target: /tmp/cache
       tmpfs:
         size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "1984:1984"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_DAHUA_USER: user
      FRIGATE_DAHUA_PASS: password
