### ISSUE TITLE
[Config Support]: HA integration plays video at Detect FPS

### ISSUE THREAD

**Issue by LaUr3nTiU** [blakeblackshear/frigate#6767]
### Describe the problem you are having

I have 2 streams for each of my cameras, coming in through channels 101 and 102 each.

The 101 stream is a 4K video with 25 FPS, while the 102 stream is a 720p video with 6 FPS.

The issue that I am facing is that even if I run **go2rtc** with the 101 channels, in HA I end up with the lower resolution/FPS stream. When changing the Detect FPS in the frigate config file, I end up with the updated values for the **sensor.front_yard_camera_fps sensor** in HA (tried 6, 9, 15). I assume this shouldn't be the case, since the 101 stream is not the detect stream, but the record stream.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.2
  user: mqtt-user
  password: mqtt-password

detectors:
  coral:
    type: edgetpu
    device: pci:0

birdseye:
  enabled: False
  quality: 8
  mode: continuous

detect:
  width: 1280
  height: 720
  fps: 9
  enabled: True
  stationary:
    interval: 0
    threshold: 50

record:
  enabled: True
  retain:
    days: 1
    mode: all 
  events:
    pre_capture: 1
    post_capture: 1
    objects:
      - person
      - cat
    retain:
      default: 1
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 2
    objects:
      person: 3

ffmpeg:
  #hwaccel_args: preset-vaapi
  #input_args: -rtsp_transport tcp
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    front_yard:
      - rtsp://user:pass@192.168.1.41:554/Streaming/Channels/101
    main_yard:
      - rtsp://user:pass@192.168.1.42:554/Streaming/Channels/101
    back_yard:
      - rtsp://user:pass@192.168.1.43:554/Streaming/Channels/101
    side_yard:
      - rtsp://user:pass@192.168.1.44:554/Streaming/Channels/101
  webrtc:
    candidates:
      - frigate.local:8555
      - stun:8555

objects:
  filters:
    person:
      min_area: 500
      max_area: 50000000
      min_score: 0.5
      threshold: 0.7

motion:
    threshold: 25
    contour_area: 30
    delta_alpha: 0.2
    frame_alpha: 0.2
    frame_height: 50
    #improve_contrast: True

cameras:
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.41:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@192.168.1.41:554/Streaming/Channels/102
          roles:
            - detect
    objects:
      track:
        - person
        - cat
    ui:
      order: 0
    zones:
      front_yard_street:
        coordinates: 279,0,188,80,72,233,0,356,0,453,65,362,195,252,364,127,582,0
        objects:
          - person
      front_yard_far:
        coordinates: 171,311,52,415,21,632,146,687
        objects:
          - person
          - cat
      front_yard_mid:
        coordinates: 338,720,397,175,162,315,139,681
        objects:
          - person
          - cat
      front_yard_near:
        coordinates: 1280,720,1280,0,757,0,386,176,327,720
        objects:
          - person
          - cat
    motion:
      mask:
        - 240,0,0,0,0,335,61,237,145,114
  main_yard:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.42:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@192.168.1.42:554/Streaming/Channels/102
          roles:
            - detect
    objects:
      track:
        - person
        - cat
    ui:
      order: 1
    zones:
      main_yard_far:
        coordinates: 651,127,422,80,164,166,194,304
        objects:
          - person
          - cat
      main_yard_near:
        coordinates: 977,231,1280,365,1280,720,369,720,190,290,647,125
        objects:
          - person
          - cat
    motion:
     mask:
      - 95,0,562,0,572,80,417,57,123,153
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.43:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@192.168.1.43:554/Streaming/Channels/102
          roles:
            - detect
    objects:
      track:
      - person
      - cat
    ui:
      order: 2
    zones:
      back_yard_outside:
        coordinates: 566,229,1226,720,1280,720,1280,336,674,0,435,0,239,0
        objects:
          - person
          - cat
      back_yard_far:
        coordinates: 200,312,467,206,326,94,155,143
        objects:
          - person
          - cat
      back_yard_mid:
        coordinates: 286,549,199,310,458,202,687,381
        objects:
          - person
          - cat
      back_yard_near:
        coordinates: 675,375,1105,720,360,720,269,543
        objects:
          - person
          - cat
        filters:
          person:
            min_area: 500
            max_area: 5000000
            min_score: 0.5
            threshold: 0.7
    motion:
      mask:
        - 1280,0,1280,192,855,0
  side_yard:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.44:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@192.168.1.44:554/Streaming/Channels/102
          roles:
            - detect
    objects:
      track:
      - person
      - cat
    ui:
      order: 3
    zones:
      side_yard_far:
        coordinates: 123,511,285,259,110,259,21,378
        objects:
          - person
          - cat
      side_yard_mid:
        coordinates: 583,283,330,673,118,505,273,258
        objects:
          - person
          - cat
      side_yard_near:
        coordinates: 534,720,1019,720,1151,329,565,277,321,672
        objects:
          - person
          - cat
    motion:
      mask:
        - 0,0,311,0,99,255,33,339,0,297
```

### Relevant log output

```shell
sensor.front_yard_camera_fps shows 6, 9, 15 FPS (depending on the value set in Detect FPS). This shouldn't be the case, as go2rtc points to a different stream instead.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe
