### ISSUE TITLE
[Config Support]: How to use preset options with custom options

### ISSUE THREAD

**Issue by wilcomir** [blakeblackshear/frigate#6777]
### Describe the problem you are having

It is not clear to me how the various options interact in the config file. As an example, let's take ffmpeg input_args:

1. if I setup the input_args to something at top level, i.e. [1] in config file, and then add an entry in the camera, are the settings from the camera appended to the top level, or is the top level overridden?
2. Is it possible to merge presets and custom settings? as an example, the syntax in [2] in the config file does not work for me

### Version

0.12.1

### Frigate config file

```yaml
# [1]
fmpeg:
  input_args: preset-rtsp-restream

# [2]
cameras:
  my_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/my_camera
          input_args:
            - preset-rtsp-restream
            - correct_ts_overflow 0
```

### Relevant log output

```shell
not applicable
```

### Frigate stats

```json
not applicable
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
