### ISSUE TITLE
[Support]: Star entire date range?

### ISSUE THREAD

**Issue by sagargp** [blakeblackshear/frigate#6783]
### Describe the problem you are having

I would like to star every single recording in a specific date range. Right now the best way I can do this is select the date range in the Events tab, and manually star each event. This is pretty time-consuming. Is there a better way that I'm not aware of?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: mqtt

birdseye:
  enabled: true
  mode: continuous

cameras:
  garage:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: "{FRIGATE_GARAGE_URL}"
          roles:
            - detect
            - rtmp
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
  front_room:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: "{FRIGATE_FRONT_ROOM_URL}"
          roles:
            - detect
            - rtmp
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
  cat_tree:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: "{FRIGATE_CAT_TREE_URL}"
          roles:
            - detect
            - rtmp
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
  dining_room:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: "{FRIGATE_DINING_ROOM_URL}"
          roles:
            - rtmp
            - record
        - path: "{FRIGATE_DINING_ROOM_URL_HIRES}"
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 352
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat

detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 10

record:
  enabled: true
  retain:
    mode: motion
  events:
    pre_capture: 5
    post_capture: 10
    retain:
      default: 3650
      mode: active_objects

# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: -c:v h264_cuvid
  # Optional: global input args (default: shown below)
  # input_args: -c:v h264_cuvid -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    # for no audio (default)
    # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # encodes audio
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Mixed
