### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by HuggiesHA** [blakeblackshear/frigate#6804]
### Describe the problem you are having

Can the new Network Storage option in the new HA release be used for frigate media?

I am able to add my NAS share drive as a storage option on the new HA release, so could this be used to send frigate media and not my pi SD card?

can this be added to the config or an option in the frigate app

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
    host: 192.168.20.93
    port: 1883
    user: mqttuser
    password: mqttuser

cameras:
  Garage:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:r0mf@192.168.20.82:554/profile2
          roles:
            - detect
            - snapshots
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      retain:
       default: 1
    record:
      enabled: True
      retain:
        days: 0
    objects:
      track:
        - person
  Kitchen:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:R0@192.168.20.129/live
          roles:
            - detect
            - snapshots
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      retain:
       default: 1
    record:
      enabled: True
      retain:
        days: 0
    objects:
      track:
        - person
  LivingRoom:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://Administrator:Bru@192.168.20.161/stream1
          roles:
            - detect
            - snapshots
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      retain:
       default: 1
    record:
      enabled: True
      retain:
        days: 0
    objects:
      track:
        - person
```

### Relevant log output

```shell
Na
```

### FFprobe output from your camera

```shell
Na
```

### Frigate stats

```json
Na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo
