### ISSUE TITLE
[Support]: Unable to keep up with recording segments in cache for <camera> in 0.13 dev

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#6808]
### Describe the problem you are having

The maintainer is unable to keep up with moving recording segments to disk with a lot of cameras, even with only motion recording enabled.

### Version

0.13.0-FF1B5C8

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 90
    mode: motion
  events:
    pre_capture: 2
    post_capture: 2

snapshots:
  enabled: true
  retain:
    default: 90

logger:
  logs:
    frigate.record: debug

<33 cameras>
```

### Relevant log output

https://github.com/blakeblackshear/frigate/issues/6636#issuecomment-1592017428

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

https://gist.github.com/ccutrer/3d7663df79eefaf044d5e15cca796da8

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Mostly Hikvision

### Any other information that may be helpful

33 cameras at the moment (all mentioned in that log as having dropped segments). Most running at 4Mbps. I may have just not been paying attention, but I don't remember seeing it with the early 0.12+ dev versions, before the maintainer was introduced. Setting to motion recording had been sufficient to keep things happy. I'd blame it on "it's raining outside today, so there's a lot more motion". But what's really odd to me is that theater and theater_front are in that list of having dropped (a lot of) recording segments. I know for a fact that that room is inside, has no windows, no lights have come on, and the door has not been opened all day (or anytime in the past 7 days). So it shouldn't have thought it needed to keep any of those segments. There are a few segments saved in the log for those cameras, but I assume that's just the startup "frames just started, _everything_ is considered motion".

This was originally discussed at https://github.com/blakeblackshear/frigate/issues/6636#issuecomment-1592017428, but now splitting to a separate issue specifically for 0.13 dev.
