### ISSUE TITLE
[Support]: use telegram notification without Home Assistant Integration

### ISSUE THREAD

**Issue by mmmint** [blakeblackshear/frigate#6816]
### Describe the problem you are having

There is no infromation regarding telegram notification without HA Integration.
Is the right way to sort this out, to just use the http API and check for events, then fire up telegram on a separate daemon?

Thanks, 
Marc

### Version

Frigate (0.12.1-367d724)

### Frigate config file

```yaml

logger:
  logs:
    frigate.mqtt: debug

mqtt:
  enabled: True
  host: localhost
  user: mqttuser
  password: mqttpass

birdseye:
  enabled: True
  mode: continuous

snapshots:
  enabled: True
  clean_copy: True

cameras:
  camera_front:
    ui:
      order: 1
    birdseye:
      order: 3
    ffmpeg:
      hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128
      inputs:
        - path: rtsp://user:pass@192.168.1.2:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://user:pass@192.168.1.2/live
          roles:
            - record
    detect:
      enabled: True
      width: 1200
      height: 536
    record:
      enabled: True
      events:
        retain:
          default: 10
    motion:
      mask:
        - 45,264,387,428,619,339,748,218,737,80,725,0,483,0,419,0,26,0
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Annke
