### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by rykr** [blakeblackshear/frigate#6820]
### Describe the problem you are having

Frigate keeps seeing my pool slide as a person.  I assumed since it *never* moves that it would not trigger but it does
<img width="637" alt="Screenshot 2023-06-15 at 4 46 09 PM" src="https://github.com/blakeblackshear/frigate/assets/108892/e9545bd9-2c10-4ba9-b303-1f4deda49c87">

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.200
record:
  enabled: True
  events:
    objects:
      - person
      - dog
      - car
      - truck
      - bicycle
      - motorcycle
      - horse  
snapshots:
  enabled: True
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

go2rtc:
  streams:
    pool_rear_main: 
      - http://192.168.1.113/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=111111
      - "ffmpeg:pool_rear#audio=opus"
    pool_rear_sub: 
      - http://192.168.1.113/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=111111
    pool_main: 
      - http://192.168.1.164/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=111111
      - "ffmpeg:pool#audio=opus"
    pool_sub: 
      - http://192.168.1.164/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=111111
cameras:
  pool_rear:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:111111@192.168.1.113:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:111111@192.168.1.113:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - car
        - truck
        - bicycle
        - motorcycle
        - horse       
  pool:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:111111@192.168.1.164:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:111111@192.168.1.164:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog            
    detect:
      width: 640
      height: 480
      fps: 7
      
  kitchen:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.41/live0
          input_args: preset-rtsp-restream
          roles:
            - record
```

### Relevant log output

```shell
None
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

Other
