### ISSUE TITLE
[Support]: odd behavior with DEVICE: GPU in openvino using yolo

### ISSUE THREAD

**Issue by doctorttt** [blakeblackshear/frigate#6821]
### Describe the problem you are having

I observed a weird behavior with the ```device: GPU``` setting under openvino using yolo models. Not sure if this is a bug or just normal behavior. 

**Here is what I have:** a 12900k cpu with an igpu and a nvidia 4060ti. Both igpu and discrete gpu are passed through to Frigate successfully, and I'm on Unraid. I confirmed the passthrough by flipping between ```preset-vaapi``` and ```preset-nvidia-h264``` in hardware acceleration. For each flip (and reloaded the config.yml), I could see the igpu working under intel_gpu_top or nvidia gpu working under nvidia-smi.

**Here is what I observed:** In this case where I have both igpu and nvidia gpu passed through to Frigate, when you set ```device: GPU``` frigate will try to use my nvidia gpu for openvino and frigate won't start (error is easily reproduceable). As far as I know, openvino is really for Intel graphic? As soon as I removed the nvidia gpu passthrough to frigate entirely, ```device: GPU``` picked up my intel igpu and openvino with yolo worked immediately, confirmed through intel_gpu_top showing a line called frigate.detecto (this is for sure openvino)

![image](https://github.com/blakeblackshear/frigate/assets/132242705/3af8daac-94a9-4efc-a5ab-aa0d657098b3)

**Here is one implication:** for example, if I were to use my nvidia gpu for hardware acceleration, openvino with yolo would pick up the cpu for detection processing with ```device: AUTO``` setting (and not the igpu). As noted above, ```device: GPU``` won't work in openvino when I have an nvidia gpu and frigate will not start in this specific scenario. 

A logical question is since I have an nvidia gpu, why am I not using tensorrt for detection? This is because I reported an issue about three weeks ago that frigate's latest-tensorrt docker image with 22.07-py3 doesn't work with my nvidia 4060ti. it will need to be 22.09-py3 or above. Oh well.....

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /custom-openvino-model/yolov8s.xml

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /custom-openvino-model/coco_80cl.txt

ffmpeg:
  global_args: -hide_banner
  hwaccel_args: preset-vaapi #preset-nvidia-h264 
  input_args: preset-rtsp-restream
  output_args: 
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    detect: -f rawvideo -pix_fmt yuv420p -an
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest and Hikvision
