### ISSUE TITLE
[Support]: Database and all recordings apparently deleted after updating docker image

### ISSUE THREAD

**Issue by kc2zgu** [blakeblackshear/frigate#6827]
### Describe the problem you are having

I had about a week of events recorded with Frigate on a stable docker image, and today switched between a few different newer development images. At some point in this process my entire database and all recorded files got deleted. Is this expected or normal? Does the database format change frequently? Is it supposed to preserve recorded events when it does?

### Version

0.13.0-b668102

### Frigate config file

```yaml
record:
  enabled: True
  retain:
    mode: motion
  events:
    pre_capture: 3
    post_capture: 5
    retain:
      default: 1080 <- this should not delete anything for several years as far as I know
      mode: active_objects
```

### Relevant log output

```shell
nothing relevant
```

### FFprobe output from your camera

```shell
why does this matter
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

irrelevant
