### ISSUE TITLE
CPU consumption rise with 0.12.1 update for TAPO C310 camera

### ISSUE THREAD

**Issue by MagoPoza** [blakeblackshear/frigate#6831]
### Describe the problem you are having

I have 2 tapo cameras configured on a raspberry PI4 with 8GB of RAM with coral. One C310 and another C320WS. I adjusted the settings with version 0.12.0 and got 33% CPU consumption on each one.
With the 0.12.1 update, CPU usage on the C320WS tapo dropped to 17% (excellent), but on the C310 without touching any of the settings it increased to 47%.

### Version

0.12.1

### Frigate config file

```yaml
# mqtt
mqtt:
  host: 192.168.x.xxx
  user: xxxxx
  password: xxxxxxx

# Declarar coral
detectors:
  coral:
    type: edgetpu
    device: usb

# Activar aceleración de hardware
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

# Declarar cámaras
go2rtc:
  streams:
    camara_entrada:
      - rtsp://user:password@192.168.x.xx:554/stream1
    camara_entrada_2:
      - rtsp://user:password@192.168.x.xx:554/stream1
  
  webrtc: 
    candidates: 
      - 192.168.x.xx:8555 

# Configuración cámara 1
cameras:
  camara_entrada:
    ffmpeg:
      input_args: preset-rtsp-generic
      output_args: 
        record: preset-record-generic
      inputs:
        - path: rtsp://user:password@192.168.x.xx:554/stream1
          roles:
            - record
            - detect
    detect: 
      width: 1280
      height: 720
      
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle 

      filters:
        person:
          min_area: 3000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
        car:
          mask:
            - 1280,0,1280,720,864,720,470,602,757,0
        motorcycle:
          mask:
            - 1280,0,1280,720,864,720,470,602,757,0
    motion:
      mask:
        - 1280,0,1280,59,1132,0

    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 1
        objects:
          person: 10

    zones:
      zona_matriculas:
        coordinates: 31,235,550,320,642,0,194,0
        objects:
          - car
          - motorcycle

# Configuración cámara 2

  camara_entrada_2:
    ffmpeg:
      input_args: preset-rtsp-generic
      output_args: 
        record: preset-record-generic
      inputs:
        - path: rtsp://user:password@192.168.x.xx:554/stream1
          roles:
            - record
            - detect
    detect: 
      width: 1280
      height: 720
      
    objects:
      track:
        - person
        - car
        - bicycle 

      filters:
        person:
          min_area: 2800
          max_area: 300000
          min_score: 0.5
          threshold: 0.7
        bicycle :
          mask:
            - 126,327,831,224,866,0,116,0
        car:
          mask:
            - 697,0,687,213,120,237,130,0

    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 1
```

### Relevant log output

```shell
nothing relevant
```

### FFprobe output from your camera

```shell
nothing relevant
```

### Frigate stats

```json
nothing relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo C310
