### ISSUE TITLE
Setting database location in Home Assistant OS

### ISSUE THREAD

**Issue by bigmak40** [blakeblackshear/frigate#6834]
### Describe the problem you are having

In the latest release of Home Assistant, native network shares were added. I would like to move my Frigate storage off to another piece of hardware and configured a network share at /media/frigate. Using the command line I verified that read/write permissions are present.

The issue that I am having is that the database shows as being locked and read only. In searching online, I found tips on how to adjust the location of the database for docker installations of Frigate as this is a known issue when the database is on a network share. However, when installing via Home Assistant you don't have the ability to customize any of the docker commands.

Looking for tips on how to set the location of the frigate.db for my current install in a custom location, not on the network. Thanks.

### Version

0.12.1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate-fa:5000/api/config/schema

mqtt:
  host: 192.168.
  port: 1883
  client_id: frigate
  user: 
  password: 

birdseye:
  enabled: True
  mode: continuous

snapshots:
  enabled: True

detectors:
  coral_1:
    type: edgetpu
    device: usb

cameras:
  driveway_east:
    ffmpeg:
      inputs:
        - path: rtsp://@192.168./live
          roles:
            - detect
            - rtmp
    motion:
      mask:
        # pinwheel
        - 782,220,823,220,823,181,782,181
        # palm tree
        - 829,36,1021,108,1015,187,892,194,818,143
        # timestamp
        - 1243,26,1243,60,962,59,961,23
    objects:
      filters:
        person:
          # pinwheel
          mask: 782,220,823,220,821,181,782,182
    zones:
      driveway:
        coordinates: 0,720,1280,720,1280,69,1014,72,1018,187,934,183,749,157,536,139,305,197,0,306
    
  abc:
    ffmpeg:
      inputs:
        - path: rtsp://192.168./live0
          roles:
            - rtmp
            - detect
    detect:
      enabled: False

  def:
    ffmpeg:
      inputs:
        - path: rtsp://192.168./live0
          roles:
            - rtmp
            - detect
    detect:
      enabled: False
```

### Relevant log output

```shell
2023-06-18 11:16:07.789815132  database is locked
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
