### ISSUE TITLE
[Support]: Frigate says initializing, then Retrying Setup in a loop.

### ISSUE THREAD

**Issue by jgdf42** [blakeblackshear/frigate#6836]
### Describe the problem you are having

I updated some things on my system and now Frigate will not start. When I go to /hassio/addon/ccab4aaf_frigate/info/ and try to start Frigate, it says Port '8555' is already in use by something else on the host.

### Version

4.0.0 in HCS. 0.12.1 is listed when I go to /hassio/addon/ccab4aaf_frigate/info

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.30
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: horse138
  stats_interval: 60
cameras:
  lorexobs:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000
      inputs:
        - path: rtsp://viewer:password@192.168.1.96:554/live
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - cat
    detect:
      width: 1024
      height: 768
      fps: 5
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 10
    record:
      enabled: True
      events:
        retain:
          default: 10    
    zones:
      backyard:
        coordinates: 346,506,680,505,679,269,347,264
      backyard_2:
        coordinates: 689,506,1024,506,1024,267,686,266
      driveway:
        coordinates: 684,251,1024,253,1024,0,686,0
      front_door:
        coordinates: 0,768,341,768,340,528,0,526
      garage:
        coordinates: 346,250,679,252,679,0,347,0
      patio:
        coordinates: 0,506,342,506,340,263,0,262
      side_door:
        coordinates: 344,0,344,251,0,247,0,0
    motion:
      mask:
        - 264,35,275,50,258,56,87,57,85,40,91,23,92,48,57,48,58,25
        - 605,0,681,0,682,32,682,66,641,78,567,56,343,58,341,0
        - 686,94,1024,84,1024,0,684,0
        - 0,334,338,319,344,265,0,264
        - 610,290,603,306,434,307,429,292
        - 688,509,770,393,883,345,997,268,982,512,1024,508,1024,320,1024,165,1024,260,921,263,689,264
        - 95,547,264,546,269,562,95,561
        - 340,524,340,768,255,768,303,534
        - 39,628,85,622,93,588,43,596
        - 689,365,685,324,680,268,592,257,552,255,507,265,636,321,634,368,575,418,578,501,683,502
        - 0,267,123,278,74,74,96,46,103,0,56,0,29,0,0,0,0,0
        - 347,768,1024,768,1024,514,346,512
        - 149,398,209,385,211,331,140,328
        - 206,497,268,499,286,460,222,455
```

### Relevant log output

```shell
2023-06-18 16:56:25.811 DEBUG (MainThread) [custom_components.frigate] Finished fetching frigate data in 4.104 seconds (success: False)
2023-06-18 16:57:49.809 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name has no usable address]
```

### FFprobe output from your camera

```shell
n/a - frigate will not start
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

virtual camera via obs

### Any other information that may be helpful

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest
