### ISSUE TITLE
[Support]: Re-sizing detect resolution

### ISSUE THREAD

**Issue by klingon888** [blakeblackshear/frigate#6860]
### Describe the problem you are having

I'm using hwaccel preset-vaapi and openvino as the detector on an Intel N100.

For detection, I need to resize the main stream to a lower resolution as the sub stream is only 640x480. I've tried both options below. Is one preferable to the other in terms of CPU/GPU usage or quality assuming I dont need the webrtc features offered by go2rtc?

Option1:
```
go2rtc:
  streams:
    front_reolink:
      - http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password
      - "ffmpeg:front_reolink#audio=opus"
    front_reolink_sub:
      - "ffmpeg:front_reolink#video=h264#width=1280#height=960#raw=-fpsmax 10#hardware=vaapi"
```

Option 2:
```
  front_reolink:
    ffmpeg:
      inputs:
        - path: http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 960
```

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink doorbell
