### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by rykr** [blakeblackshear/frigate#6866]
### Describe the problem you are having

Using tensor flow RT.  Getting very strange false positives.  Surely it's more accurate than this?  I thought if something did not move it would not be flagged as a person.  Here is cushion between two seats around our pool.  I watched the clip and it never moves and yet it is 72% sure it's a person.
![snapshot-1687301832 62025-ojzu5e](https://github.com/blakeblackshear/frigate/assets/108892/bb85f614-1257-49c4-a8a5-5bddbcf7a574)

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.200
record:
  enabled: True
  events:
    objects:
      - person
      - dog
      - car
      - truck
      - bicycle
      - motorcycle
      - horse  
snapshots:
  enabled: True
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

go2rtc:
  streams:
    pool_rear_main: 
      - http://192.168.1.113/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=111111
      - "ffmpeg:pool_rear#audio=opus"
    pool_rear_sub: 
      - http://192.168.1.113/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=111111
    pool_main: 
      - http://192.168.1.164/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=111111
      - "ffmpeg:pool#audio=opus"
    pool_sub: 
      - http://192.168.1.164/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=111111
cameras:
  pool_rear:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:111111@192.168.1.113:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:111111@192.168.1.113:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - car
        - truck
        - bicycle
        - motorcycle
        - horse       
  pool:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:111111@192.168.1.164:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:111111@192.168.1.164:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog       
      filters:
        person:
          mask:
            - 247,95,239,118,203,117,202,77     
    detect:
      width: 640
      height: 480
      fps: 7
      
  kitchen:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.41/live0
          input_args: preset-rtsp-restream
          roles:
            - record
```

### Relevant log output

```shell
No log output around that time.
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:111111@192.168.1.164:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_sub
  Duration: N/A, start: 0.004125, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 30 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Reolink R510-A
