### ISSUE TITLE
[Bug]: I believe commit d81dd60 broke object detection on OpenVINO

### ISSUE THREAD

**Issue by Steve-Tech** [blakeblackshear/frigate#6867]
### Describe the problem you are having

Whenever there is any motion detected by the cameras, the camera process crashes with `ValueError: could not broadcast input array from shape (148,150) into shape (148,148)`.

### Version

0.13.0-0f1cf67

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.14
  user: mqtt
  password: password

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@172.16.0.2/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://username:password@172.16.0.2/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 0,182,94,201,343,106,436,0,0,0
    zones:
      front_door:
        coordinates: 1280,720,1280,0,1118,0,1027,311,820,720,842,594,487,477,0,554,0,720
      front_verandah:
        coordinates: 0,720,786,720,832,589,267,395,0,261
      driveway:
        coordinates: 747,163,813,159,818,230,773,288,825,389,457,300
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        car:
          mask:
            - 752,290,899,190,1280,172,1280,720,0,720,0,0,973,0,991,0,982,71,1010,70,1041,86,1055,119,966,132,937,67,724,43,635,82,537,240
        cat:
          mask:
            - 0,0,1280,0,1280,720,933,720,935,502,740,274,828,146,418,282,0,174
        dog:
          mask:
            - 0,0,1280,0,1280,720,933,720,935,502,740,274,828,146,418,282,0,174
    ui:
      order: 0
  back:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@172.16.0.3/Streaming/Channels/101
          roles:
            - record   
        - path: rtsp://username:password@172.16.0.3/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 0,48,402,48,402,0,0,0
    zones:
      back_verandah:
        coordinates: 0,40,0,720,1280,720,1280,583,512,191,505,40
      back_gate:
        coordinates: 815,0,896,0,869,115,781,95
      back_yard:
        coordinates: 517,0,1280,160,1280,552,524,170
    ui:
      order: 1

go2rtc:
  streams:
    front:
      - rtsp://username:password@172.16.0.2:554/Streaming/Channels/102
    back:
      - rtsp://username:password@172.16.0.3:554/Streaming/Channels/102
  webrtc:
    candidates:
      - 192.168.0.104:8555
      - stun:8555

snapshots:
  enabled: True

record:
  enabled: True
  retain:
    days: 7
    mode: motion

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy

timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"

ui:
  date_style: medium

objects:
  track:
    - person
    - cat
    - dog

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant log output

```shell
2023-06-21 11:26:59.835809663  [INFO] Preparing Frigate...
2023-06-21 11:26:59.844349093  [INFO] Starting Frigate...
2023-06-21 11:27:02.180630012  [2023-06-21 11:27:02] frigate.app                    INFO    : Starting Frigate (0.13.0-0f1cf67)
2023-06-21 11:27:02.224467942  [2023-06-21 11:27:02] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-06-21 11:27:02.232758763  [2023-06-21 11:27:02] peewee_migrate.logs            INFO    : Starting migrations
2023-06-21 11:27:02.327541502  [2023-06-21 11:27:02] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-06-21 11:27:03.949344901  [2023-06-21 11:27:03] frigate.app                    INFO    : Recording process started: 1742
2023-06-21 11:27:03.954425290  [2023-06-21 11:27:03] frigate.app                    INFO    : go2rtc process pid: 89
2023-06-21 11:27:03.995127720  [2023-06-21 11:27:03] frigate.app                    INFO    : Output process started: 1753
2023-06-21 11:27:04.001214017  [2023-06-21 11:27:03] frigate.app                    INFO    : Camera processor started for front: 1756
2023-06-21 11:27:04.005405416  [2023-06-21 11:27:03] detector.ov                    INFO    : Starting detection process: 1751
2023-06-21 11:27:04.013107217  [2023-06-21 11:27:04] frigate.app                    INFO    : Camera processor started for back: 1757
2023-06-21 11:27:04.020762592  [2023-06-21 11:27:04] frigate.app                    INFO    : Capture process started for front: 1758
2023-06-21 11:27:04.036430971  [2023-06-21 11:27:04] frigate.app                    INFO    : Capture process started for back: 1760
2023-06-21 11:27:04.720789381  [2023-06-21 11:27:04] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-06-21 11:27:04.721613150  [2023-06-21 11:27:04] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-06-21 11:27:04.721620197  [2023-06-21 11:27:04] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2023-06-21 11:27:12.501007256  frame.shape: (1080, 1280)
2023-06-21 11:27:12.501016749  region: (997, 570, 1147, 720)
2023-06-21 11:27:12.502042798  Process camera_processor:back:
2023-06-21 11:27:12.506775937  Traceback (most recent call last):
2023-06-21 11:27:12.506783043    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-06-21 11:27:12.506786620      self.run()
2023-06-21 11:27:12.506790420    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-06-21 11:27:12.506800957      self._target(*self._args, **self._kwargs)
2023-06-21 11:27:12.506805027    File "/opt/frigate/frigate/video.py", line 482, in track_camera
2023-06-21 11:27:12.506833730      process_frames(
2023-06-21 11:27:12.506837540    File "/opt/frigate/frigate/video.py", line 807, in process_frames
2023-06-21 11:27:12.506841720      detect(
2023-06-21 11:27:12.506845373    File "/opt/frigate/frigate/video.py", line 552, in detect
2023-06-21 11:27:12.506849420      tensor_input = create_tensor_input(frame, model_config, region)
2023-06-21 11:27:12.506853004    File "/opt/frigate/frigate/video.py", line 101, in create_tensor_input
2023-06-21 11:27:12.506883647      cropped_frame = yuv_region_2_bgr(frame, region)
2023-06-21 11:27:12.506887700    File "/opt/frigate/frigate/util.py", line 567, in yuv_region_2_bgr
2023-06-21 11:27:12.506892477      yuv_cropped_frame = yuv_crop_and_resize(frame, region)
2023-06-21 11:27:12.506896194    File "/opt/frigate/frigate/util.py", line 333, in yuv_crop_and_resize
2023-06-21 11:27:12.506915154      yuv_cropped_frame[
2023-06-21 11:27:12.506919357  ValueError: could not broadcast input array from shape (148,150) into shape (148,148)
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://username:password@172.16.0.3/Streaming/Channels/102':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 1280x720 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 32000 Hz, mono, fltp
```

### Frigate stats

```json
{"back":{"camera_fps":5.0,"capture_pid":1760,"detection_enabled":1,"detection_fps":12.19,"ffmpeg_pid":1777,"pid":1757,"process_fps":1.09,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.0/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"104":{"cmdline":"python3 -u -m frigate","cpu":"2.6","cpu_average":"4","mem":"0.1"},"116":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"132":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"133":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"134":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"135":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"153":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"164":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"172":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"173":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"174":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"175":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"177":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"187":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"198":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"209":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"212":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"213":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"214":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"223":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"237":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"249":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"250":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"251":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"254":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"270":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"286":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"287":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"288":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"299":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"316":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"323":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"324":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"936":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"956":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"976":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1001":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1032":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1045":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1061":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1092":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1117":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1134":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1167":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1230":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1237":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1252":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1280":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1305":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1740":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1742":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"1","mem":"0.1"},"1750":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(39)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"1751":{"cmdline":"frigate.detector.ov  ","cpu":"0.0","cpu_average":"1","mem":"0.2"},"1753":{"cmdline":"frigate.output       ","cpu":"0.3","cpu_average":"0","mem":"0.1"},"1756":{"cmdline":"frigate.process:front","cpu":"4.3","cpu_average":"2","mem":"0.1"},"1757":{"cmdline":"","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1758":{"cmdline":"frigate.capture:front","cpu":"2.0","cpu_average":"1","mem":"0.1"},"1759":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1760":{"cmdline":"frigate.capture:back ","cpu":"2.0","cpu_average":"1","mem":"0.1"},"1763":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1767":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-0f1cf67 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://username:password@172.16.0.2/Streaming/Channels/102 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.5","cpu_average":"11","mem":"0.1"},"1770":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1777":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-0f1cf67 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://username:password@172.16.0.3/Streaming/Channels/102 -r 5 -vf fps=5,scale_cuda=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.2","cpu_average":"10","mem":"0.1"},"1778":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-0f1cf67 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://username:password@172.16.0.2/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front-%Y%m%d%H%M%S.mp4","cpu":"1.4","cpu_average":"1","mem":"0.0"},"1781":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-0f1cf67 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://username:password@172.16.0.3/Streaming/Channels/101 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/back-%Y%m%d%H%M%S.mp4","cpu":"1.4","cpu_average":"1","mem":"0.0"},"1875":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":12.19,"detectors":{"ov":{"detection_start":0.0,"inference_speed":34.3,"pid":1751}},"front":{"camera_fps":5.1,"capture_pid":1758,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1767,"pid":1756,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"Quadro P600":{"gpu":"1.0%","mem":"15.04%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":1740},"recording":{"pid":1742}},"service":{"last_updated":1687310908,"latest_version":"unknown","storage":{"/dev/shm":{"free":528.9,"mount_type":"tmpfs","total":536.9,"used":8.0},"/media/frigate/clips":{"free":1728645.8,"mount_type":"ext4","total":1967846.1,"used":139163.6},"/media/frigate/recordings":{"free":1728645.8,"mount_type":"ext4","total":1967846.1,"used":139163.6},"/tmp/cache":{"free":990.4,"mount_type":"tmpfs","total":1000.0,"used":9.6}},"temperatures":{},"uptime":84,"version":"0.13.0-0f1cf67"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision HiLook IPC-T281H-MU

### Any other information that may be helpful

I'm using build `dev-0f1cf67` since d81dd60 didn't finish building.
