### ISSUE TITLE
[Detector Support]: Dogs are always detected cats when using TensorRT detector

### ISSUE THREAD

**Issue by cliffburdick** [blakeblackshear/frigate#6876]
### Describe the problem you are having

All dogs are being recognized as cats. I'm using the yolov7-tiny-416 model, and see this:

![image](https://github.com/blakeblackshear/frigate/assets/30670611/97d56c29-a4bc-40e6-9cfe-8fa706d1765c)

So far it has not identified any dogs yet.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat
    - motorcycle
    - horse
    - bicycle

record:
  enabled: True
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 3
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - cat
      - dog
      - car
      - motorcycle
      - bicycle

    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 15
        car: 7
        motorcycle: 7
        bicycle: 7
        dog: 15
        cat: 15

cameras:
  lwb: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.170:554 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 0
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50
    motion:
      mask:
        - 1920,0,1920,139,1267,132,1270,0
        - 0,350,197,53,883,156,262,754,62,729
    zones:
      front_and_street:
        coordinates: 1428,161,922,150,739,411,651,480,490,560,517,632,478,707,342,821,373,881,234,1013,258,1080,1920,1080,1920,251
        objects:
          - person
          - car
          - cat
          - bicycle
          - dog
          - motorcycle

  uwb: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.172:554 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 0
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50
    motion:
      mask:
        - 1994,0,2001,130,2636,141,2638,0
    zones:
      driveway_and_street:
        coordinates:  391,0,1868,0,1968,137,2358,127,2375,261,2238,527,2575,657,2688,1520,0,1520,0,277
        objects:
          - person
          - car
          - bicycle
          - cat
          - dog
          - motorcycle
  porch: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.171:554 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 0
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50
    motion:
      mask:
        - 1654,0,2688,0,2688,143,1656,154
    zones:
      porch_and_lawn:
        coordinates: 2688,0,2381,244,2315,347,1945,261,1618,244,1178,187,931,267,735,0,0,0,0,1520,2688,1520
        objects:
          - person
          - car
          - bicycle
          - cat
          - dog
          - motorcycle
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
      #    image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/cb/frigate/frigate.yml:/config/config.yml
      - /mnt/media/frigate:/media/frigate
      - /home/cb/frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "co99sype"
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant log output

```shell
none
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)
