### ISSUE TITLE
Reolink RTSP stream pass/fail on startup

### ISSUE THREAD

**Issue by dapowers87** [blakeblackshear/frigate#688]
Hi,

I have been having an issue of whenever I start up Frigate in HA, the odds are that I will get errors like:

```
[h264 @ 0x55a6bcc76d00] error while decoding MB 43 4, bytestream -25
[h264 @ 0x55a6bcc76d00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55a6bcc76d00] error while decoding MB 0 3, bytestream 451572
[h264 @ 0x55a6bcc76d00] error while decoding MB 69 9, bytestream -25
```

If I restart Frigate over and over, eventually it will load fine and I won't get any errors.

Here is my config:

```
detectors:
  coral:
    type: cpu
mqtt:
  host: core-mosquitto.local.hass.io
  user: frigate
  password: frigate
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - qsv
    - '-qsv_device'
    - /dev/dri/renderD128
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://XX:XX@192.168.1.XX:554/h264Preview_01_main'
          roles:
            - detect
            - clips
    width: 2560
    height: 1920
    fps: 10
    objects:
      track:
        - person
        - car
    motion:
      mask:
        - '2560,698,2560,0,2470,0,1778,0,843,0,0,0,0,671,1112,603'
    clips:
      enabled: true
      pre_capture: 10
      post_capture: 15
      objects:
        - person
        - car
      retain:
        default: 10
        objects:
          person: 15
```

Any ideas why this is happening randomly? I tried the input_args listed for Reolink on https://blakeblackshear.github.io/frigate/configuration/cameras but it would give me the following error repeating:

```
ffmpeg.garage.detect           ERROR   : Option rw_timeout not found.
frigate.video                  INFO    : garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage: ffmpeg process is not running. exiting capture thread...
```
I'm on Home Assistant's version 1.6 of Frigate.
