### ISSUE TITLE
[BUG]: Frigate deleted old videos from disk, but database not updated.

### ISSUE THREAD

**Issue by tarangill** [blakeblackshear/frigate#6881]
### Describe the problem you are having

I am saving previous **180** **days** of recordings from 8 different cameras. I have about 60 TB of space!

Until about late March, I was using an old version of frigate that saved recordings in the old format of yyyy/mm/dd.

In late march I updated to `0.12.0-da3e197` and it auto-migrated the database.

Everything was fine until about a week ago (around June 12), when my storage ran out of space. At this point I Frigate was saving Recordings from December 12. I was expecting Frigate to delete the oldest recordings. However, Frigate deleted all the recordings that were saved in old format, i.e. until late march!

I can live with that. However, the issue is, the database has not updated. When I click on a camera, it shows option to view recordings from December 12, but obviously that does not work. How can I remove these old entries from the db?

### Version

0.12.0-da3e197

### Frigate config file

```yaml
database:
  path: /db/frigate.db
  
mqtt:
  host: mqtt
  user: mosquitto
  password: hunter12

detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    #num_threads: 3

model:
  path: /mymodels-cctv/edgetpu_model.tflite
  labelmap_path: /mymodels-cctv/labelmap.txt
  width: 340
  height: 340
#  input_tensor: "nhwc"
#  input_pixel_format: "bgr"

go2rtc:
#  log:
#    exec: trace
  ffmpeg:
    frigatedefaults: "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1"
  streams:
    driveway: ffmpeg:rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.5:554/stream0
    front-yard: ffmpeg:rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.10:554/stream0
    doorbell: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.11:554/h265Preview_01_main
    patio: ffmpeg:rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.2:554/stream0
    deck: ffmpeg:rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.9:554/stream0
    back-court: ffmpeg:rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.3:554/stream0
    left-alley: ffmpeg:rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.4:554/stream0
    right-alley: ffmpeg:rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.8:554/stream0
    # left-alley_detect:
    #   - rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.10:554/Streaming/Channels/2

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 3840 
  # Optional: Height of the output resolution (default: shown below)
  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  mode: continuous


# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel info -threads 1
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  # hwaccel_args: preset-intel-qsv-h265
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 1 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic-audio-copy
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic


record:
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 180
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    #max_seconds: 600
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
      - bicycle
      - motorcycle
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    #required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 14
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30

# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
#live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
#  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8


timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "bl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%Y-%m-%d %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "solid"

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 10
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True 
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 50

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    # - car
    # - motorcycle
    # - bicycle
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  # mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 50
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 24000000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.65
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.80
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      # mask: 0,0,1000,0,1000,200,0,200

# Required
cameras:
    # # Required: name of the camera
  driveway:
  #   # Required: ffmpeg settings for the camera
    ffmpeg:
  #     # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.5:554/stream2
          roles:
            - rtmp
            - detect
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.5:554/stream0
          roles:
            - record
    record:
      events:
        required_zones:
          # - driveway_entry
          - my_driveway
    snapshots:
      required_zones:
        - my_driveway
    zones:
      # driveway_entry:
      #   coordinates: 355,137,621,151,611,108,504,98,326,98,89,112,49,170 
      #   objects:
      #     - car 
      #     - bicycle
      #     - motorcycle
      my_driveway:
        coordinates: 0,495,0,1080,873,1080,1920,1080,1920,395,1602,281,839,232,137,303 
        objects:
          - person
    ui:
      order: 0  

  front-yard:
   # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.10:554/stream2
          roles:
            - rtmp
            - detect
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.10:554/stream0
          roles:
            - record
    record:
      events:
        required_zones:
          # - driveway_entry
          - my_frontyard
    snapshots:
      required_zones:
        - my_frontyard
    zones:
      my_frontyard:
        coordinates: 0,405,0,1080,1920,1080,1920,873,1334,232,440,172 
        objects:
          - person
    ui:
      order: 1 

  patio:
  #  # Required: ffmpeg settings for the camera
   ffmpeg:
  #    # Required: A list of input streams for the camera. See documentation for more information.
     inputs:
       - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.2:554/stream2
         roles:
           - rtmp
           - detect
       - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.2:554/stream0
         roles:
           - record
   ui:
     order: 2 

  doorbell:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.11:554/h264Preview_01_sub
          roles:
            - rtmp
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
    ui:
      order: 3 

  deck:
  #   # Required: ffmpeg settings for the camera
    ffmpeg:
  #     # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.9:554/stream2
          roles:
            - rtmp
            - detect
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.9:554/stream0
          roles:
            - record
    ui:
      order: 4 

  # Required: name of the camera
  back-court:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.3:554/stream2
          roles:
            - rtmp
            - detect
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.3:554/stream0
          roles:
            - record
    ui:
      order: 5 
  
  # Required: name of the camera
  left-alley:
      # Required: ffmpeg settings for the camera
    ffmpeg:
        # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.4:554/stream2
          roles:
            - rtmp
            - detect
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.4:554/stream0
          input_args: preset-rtsp-restream
          roles:
            - record
    ui:
      order: 6

  right-alley:
  #   # Required: ffmpeg settings for the camera
    ffmpeg:
  #     # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.8:554/stream2
          roles:
            - rtmp
            - detect
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.5.5.8:554/stream0
          roles:
            - record
    ui:
      order: 7
```

### Relevant log output

```shell
None.
```

### FFprobe output from your camera

```shell
None.
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Doesn't matter.

### Any other information that may be helpful

None.
