### ISSUE TITLE
[Support]: Proxy addon not loading

### ISSUE THREAD

**Issue by Martynhsmith** [blakeblackshear/frigate#6884]
### Describe the problem you are having

I have frigate working lovely in it's own docker container  on http://192.168.0.8:5000/logs
I can browse to it - I'm getting detections and recordings

But I'm trying to use the friate proxy addon on hassio

And the log fills up with - [13:17:20] INFO: Starting NGinx...
nginx: [emerg] invalid host in upstream "http://192.168.0.8:5000" in /etc/nginx/includes/upstream.conf:2

### Version

SYSTEM 0.12.1-367D724

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  host: 192.168.0.60
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-sunnybank
  password: not
  stats_interval: 300

record:
  expire_interval: 10

go2rtc:
  streams:
    Garden_c:
      - rtsp://192.168.0.37/:8091/user=ha&password=not&channel=1&stream=0.sdp?
    Garden_sub:
      - rtsp://192.168.0.37/:8091/user=ha&password=not&channel=1&stream=1.sdp?
    Frontdoor_c:
      - rtsp://192.168.0.36/:8091/user=ha&password=not&channel=1&stream=0.sdp?
    Frontdoor_sub:
      - rtsp://192.168.0.36/:8091/user=ha&password=not&channel=1&stream=1.sdp?




timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "br"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

cameras:
  Frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Frontdoor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Frontdoor_c
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:                 
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - bird
        - car
      filters:
        person:
          min_score: 0.4
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - Frontdoor_in
        - Frontdoor_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      Frontdoor_in:
        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
        objects:
          - person
          - dog
          - cat
          - bicycle
          - car
      Frontdoor_whole_area:
        coordinates: 404,0,640,54,640,480,640,480,640,358,640,480,261,480,0,480,0,225,138,39
        objects:
          - person
          - cat
          - dog
          - bicycle  
          - bird
          - car
    motion:
      mask:
        - 397,480,640,480,640,442,392,438,367,443,382,457
      threshold: 20
      contour_area: 15
    record:
      enabled: True
      retain: 
        days: 2 
        #mode: active_objects 
      events:
        retain:
          default: 5 
          mode: motion 
        pre_capture: 3 
        post_capture: 10  

 
  Garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Garden_c
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
        person:
          min_score: 0.4
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - Garden-all
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      Garden-all:
        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
        objects:
        - person
        - dog
        - cat
        - bird
        - mouse
    motion:
      mask:
        - 23,480,333,480,333,442,26,440
      threshold: 20
      contour_area: 15
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  

  
detectors: 
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  enabled: True
  restream: False
  width: 1280 
  height: 720
  quality: 1
  mode: objects

live:
  height: 640
  quality: 1
```

### Relevant log output

```shell
[13:17:20] INFO: Starting NGinx...
nginx: [emerg] invalid host in upstream "http://192.168.0.8:5000" in /etc/nginx/includes/upstream.conf:2
[13:17:21] INFO: Starting NGinx...
nginx: [emerg] invalid host in upstream "http://192.168.0.8:5000" in /etc/nginx/includes/upstream.conf:2
[13:17:22] INFO: Starting NGinx...
nginx: [emerg] invalid host in upstream "http://192.168.0.8:5000" in /etc/nginx/includes/upstream.conf:2
[13:17:23] INFO: Starting NGinx...
nginx: [emerg] invalid host in upstream "http://192.168.0.8:5000" in /etc/nginx/includes/upstream.conf:2
[13:17:24] INFO: Starting NGinx...
nginx: [emerg] invalid host in upstream "http://192.168.0.8:5000" in /etc/nginx/includes/upstream.conf:2
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1944,"width":2592}]}}]
```

### Frigate stats

```json
How do I do this?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

https://www.anpvizsecurity.com/products-detail-149743
