### ISSUE TITLE
[Config Support]: Invalid Syntax in go2rtc config

### ISSUE THREAD

**Issue by cbuxton5200** [blakeblackshear/frigate#6885]
### Describe the problem you are having

In my GO2RTC log file I am getting this error message:
2023-06-22 09:26:44.921468796  09:26:44.921 WRN [app] read config error="yaml: unmarshal errors:\n  line 26: cannot unmarshal !!map into string"

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.15
  user: mqtt
  password: mqtt

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  logs:
    frigate.object_detection: debug
    ffmpeg.wificam.detect: critical
    watchdog.upstairscam: critical
    watchdog.doorcam: critical
    watchdog.wificam: critical

go2rtc:
  streams:
    doorcam:
      - rtsp://192.168.1.153/streaming/channels/101
      - "ffmpeg:doorcam#audio=opus"
    upstairscam:
      - rtsp://192.168.1.150/live0.264
    backcam:
      - rtsp://192.168.1.152/Streaming/Channels/101
      - "ffmpeg:backcam#audio=opus"
    backcam_sub:
      - rtsp://192.168.1.152/Streaming/Channels/102
    frontcam:
      - rtsp://192.168.1.151/cam/realmonitor?channel=1&subtype=0
    frontcam_sub:
      - rtsp://192.168.1.151/cam/realmonitor?channel=1&subtype=2
    wificam:
      - rtsp://192.168.1.65/ch0_0.h264
  webrtc:
    candidates:
      - stun: 8555

ui:
  live_mode: webrtc

cameras:
  doorcam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.0.6:8554/doorcam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 600
      height: 800
      fps: 4
    record:
      enabled: true
      events:
        pre_capture: 10
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
      timestamp: true
      crop: true
      retain:
        default: 14
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
      height: 800
    zones:
      frontentry:
        coordinates: 600,471,600,800,0,800,0,579
    objects:
      track:
        - person
  
  frontcam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.0.6:8554/frontcam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.0.6:8554/frontcam
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    motion:
      mask: "781,80,775,184,330,270,298,128"
    record:
      enabled: true
      events:
        pre_capture: 10
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
      timestamp: true
      crop: true
      retain:
        default: 14
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
      height: 800
    zones:
      driveway:
        coordinates: 997,316,1454,420,1065,1080,304,1080,131,741
    objects:
      track:
        - person
        - car
        - bicycle
        - cat
        - dog
        - bird
    live:
      stream_name: frontcam_sub
  
  backcam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.0.6:8554/backcam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.0.6:8554/backcam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 536
      fps: 4
    record:
      enabled: true
      events:
        pre_capture: 10
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
      timestamp: true
      crop: true
      retain:
        default: 14
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
      height: 800
    zones:
      deck:
        coordinates: 1379,248,1036,347,1219,536,1633,536,1677,364
    objects:
      track:
        - person
        - cat
        - dog
        - bus
        - bird
    live:
      stream_name: backcam_sub
  
  upstairscam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.6:8554/upstairscam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 2304
      height: 1296
      fps: 8
    record:
      enabled: true
      events:
        pre_capture: 10
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
      timestamp: true
      crop: true
      retain:
        default: 14
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
      height: 800
    objects:
      track:
        - person
        - cat
  
  wificam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.6:8554/wificam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
      events:
        pre_capture: 10
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: true
      timestamp: true
      crop: true
      retain:
        default: 14
    mqtt:
      timestamp: false
      bounding_box: false
      quality: 100
      height: 800
    objects:
      track:
        - person
        - cat
```

### Relevant log output

```shell
2023-06-22 09:26:44.921468796  09:26:44.921 WRN [app] read config error="yaml: unmarshal errors:\n  line 26: cannot unmarshal !!map into string"
```

### Frigate stats

```json
{
    "backcam": {
        "camera_fps": 4.1,
        "capture_pid": 670,
        "detection_enabled": 1,
        "detection_fps": 1.8,
        "ffmpeg_pid": 686,
        "pid": 656,
        "process_fps": 4.1,
        "skipped_fps": 0
    },
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "17": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "89": {
            "cpu": "14.3",
            "mem": "0.1"
        },
        "97": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "98": {
            "cpu": "5.3",
            "mem": "0.9"
        },
        "115": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "134": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "135": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "136": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "137": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "142": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "156": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "178": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "208": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "242": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "281": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "318": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "358": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "393": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "424": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "641": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "647": {
            "cpu": "0.3",
            "mem": "0.0"
        },
        "648": {
            "cpu": "0.0",
            "mem": "0.3"
        },
        "649": {
            "cpu": "2.7",
            "mem": "0.3"
        },
        "653": {
            "cpu": "0.7",
            "mem": "0.3"
        },
        "654": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "655": {
            "cpu": "1.0",
            "mem": "0.3"
        },
        "656": {
            "cpu": "0.7",
            "mem": "0.3"
        },
        "657": {
            "cpu": "1.7",
            "mem": "0.3"
        },
        "658": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "659": {
            "cpu": "0.7",
            "mem": "0.3"
        },
        "660": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "661": {
            "cpu": "0.7",
            "mem": "0.3"
        },
        "662": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "665": {
            "cpu": "4.7",
            "mem": "0.3"
        },
        "668": {
            "cpu": "1.7",
            "mem": "0.4"
        },
        "669": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "670": {
            "cpu": "2.0",
            "mem": "0.3"
        },
        "671": {
            "cpu": "10.0",
            "mem": "0.5"
        },
        "676": {
            "cpu": "9.6",
            "mem": "0.3"
        },
        "677": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "686": {
            "cpu": "3.3",
            "mem": "0.5"
        },
        "690": {
            "cpu": "4.3",
            "mem": "0.3"
        },
        "692": {
            "cpu": "2.7",
            "mem": "0.1"
        },
        "694": {
            "cpu": "18.6",
            "mem": "0.6"
        },
        "700": {
            "cpu": "3.7",
            "mem": "0.1"
        },
        "701": {
            "cpu": "8.0",
            "mem": "0.5"
        },
        "1369": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "1387": {
            "cpu": "0.3",
            "mem": "0.0"
        },
        "1392": {
            "cpu": "0.3",
            "mem": "0.0"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0.0"
        }
    },
    "detection_fps": 1.8,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 9.84,
            "pid": 648
        }
    },
    "doorcam": {
        "camera_fps": 4.1,
        "capture_pid": 661,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 668,
        "pid": 653,
        "process_fps": 4.1,
        "skipped_fps": 0
    },
    "frontcam": {
        "camera_fps": 6.1,
        "capture_pid": 665,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 671,
        "pid": 655,
        "process_fps": 6.1,
        "skipped_fps": 0
    },
    "gpu_usages": {
        "NVIDIA GeForce GTX 1630": {
            "gpu": "2 %",
            "mem": "19.1 %"
        }
    },
    "service": {
        "last_updated": 1687444357,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 521.5,
                "mount_type": "tmpfs",
                "total": 536.9,
                "used": 15.4
            },
            "/media/frigate/clips": {
                "free": 570752,
                "mount_type": "ext4",
                "total": 786423.1,
                "used": 175647.8
            },
            "/media/frigate/recordings": {
                "free": 570752,
                "mount_type": "ext4",
                "total": 786423.1,
                "used": 175647.8
            },
            "/tmp/cache": {
                "free": 2092.3,
                "mount_type": "tmpfs",
                "total": 2147.5,
                "used": 55.2
            }
        },
        "temperatures": {},
        "uptime": 352,
        "version": "0.12.1-367d724"
    },
    "upstairscam": {
        "camera_fps": 8.1,
        "capture_pid": 676,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 694,
        "pid": 657,
        "process_fps": 8.1,
        "skipped_fps": 0
    },
    "wificam": {
        "camera_fps": 5,
        "capture_pid": 690,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 701,
        "pid": 659,
        "process_fps": 5,
        "skipped_fps": 0
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
