### ISSUE TITLE
missing public endpoints for videos in documentation

### ISSUE THREAD

**Issue by mario-tux** [blakeblackshear/frigate#689]
Trying to extend my notification automation to include video I discovered that the endpoint in subject is missing in documentation and examples. Or at least I can't find it in https://blakeblackshear.github.io/frigate/usage/api and https://blakeblackshear.github.io/frigate/usage/home-assistant. 

I've found the endpoint in a bug report thread: `HA_URL/api/frigate/notifications/<event-id>/<camera>/clip.mp4`

Other three things:
- I'm not sure to understand why the missing endpoint includes the camera name: is there a possibile conflict?
- I suggest to include an example of HA automation with video;
- I was not able to use the example with the keyword 'conditions' from https://blakeblackshear.github.io/frigate/usage/home-assistant: HA doesn't accept it. Is the syntax right?!

**Comment by HITChris** [comment]
Documentation is always a work in progress right. The example yaml looks fine to me but I'd suggest double checking how it is formatted on your end (proper indentation, tabs replaced with spaces, etc.). HA's validation errors should indicate exactly where the problem(s) lie.

**Comment by mario-tux** [comment]
> The example yaml looks fine to me but I'd suggest double checking how it is formatted on your end (proper indentation, tabs replaced with spaces, etc.). HA's validation errors should indicate exactly where the problem(s) lie.

copy&paste in `automations.yaml` of the example doesn't validate:
```
- id: '161217989799555'
  alias: When a person enters a zone named yard
  trigger:
    platform: mqtt
    topic: frigate/events
  conditions:
    - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    - "{{ 'yard' in trigger.payload_json['after']['entered_zones'] }}"
  action:
    - service: notify.mobile_app_pixel_3
      data_template:
        message: "A {{trigger.payload_json['after']['label']}} has entered the yard."
        data:
          image: "https://url.com/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/thumbnail.jpg"
          tag: "{{trigger.payload_json['after']['id']}}"
```

VSCode already signals the error during editing:
![image](https://user-images.githubusercontent.com/4376789/106720848-4052c280-6604-11eb-8997-ac100b967c38.png)

Upon validation request the following error appears: `Invalid config for [automation]: [conditions] is an invalid option for [automation]. Check: automation->conditions.`

The classic conditions construction validates on all the fronts:
![image](https://user-images.githubusercontent.com/4376789/106721329-d25acb00-6604-11eb-8de7-d6ead89d08c0.png)

I'm using HA `core-2021.1.5`.
