### ISSUE TITLE
[Detector Support]: Question on OpenVINO modes

### ISSUE THREAD

**Issue by tdashmike** [blakeblackshear/frigate#6903]
### Describe the problem you are having

How do I know if the OpenVINO detector is using the CPU or GPU?

### Version

0.12.1-367d724

### Frigate config file

```yaml
ffmpeg:
  input_args:
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
    - -timeout
    - 60M
    #- -use_wallclock_as_timestamps
    #- 1
  hwaccel_args: preset-intel-qsv-h264

mqtt:
  enabled: False

go2rtc:
  ffmpeg:
    inarg: "-avoid_negative_ts make_zero -fflags +genpts+igndts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -timeout 5000000 -i {input}"
  streams:
    STUDY:
      - ffmpeg:rtsp://192.168.xxx.xxx:554/ch0_0.h264#video=copy#input=inarg
  webrtc:
    candidates:
      - 192.168.xx.xx:8555
      - stun:8555

cameras:
  STUDY: # <------ Name the camera
    ui:
      order: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/STUDY # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: True

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 31
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    required_zones: []
    retain:
      default: 31
      mode: motion

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: True
  stationary:
    interval: 0
    threshold: 50

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - cat
    - car
    - bear
    - bird
    - bicycle
    - bus

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
```

### docker-compose file or Docker CLI command

```yaml
docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  --shm-size=256m \
  -v /path/to/your/storage:/media/frigate \
  -v /path/to/your/config.yml:/config/config.yml \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='password' \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  ghcr.io/blakeblackshear/frigate:stable
```

### Relevant log output

```shell
2023-06-24 02:52:34.240518497  [INFO] Starting Frigate...
2023-06-24 02:52:36.282334193  [2023-06-24 02:52:36] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-06-24 02:52:36.414539281  [2023-06-24 02:52:36] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-06-24 02:52:36.440414332  [2023-06-24 02:52:36] peewee_migrate                 INFO    : Starting migrations
2023-06-24 02:52:36.447738929  [2023-06-24 02:52:36] peewee_migrate                 INFO    : There is nothing to migrate
2023-06-24 02:52:36.471513005  [2023-06-24 02:52:36] detector.ov                    INFO    : Starting detection process: 432
2023-06-24 02:52:36.478905904  [2023-06-24 02:52:36] frigate.app                    INFO    : Output process started: 433
2023-06-24 02:52:36.480955454  [2023-06-24 02:52:36] frigate.app                    INFO    : Camera processor started for STUDY: 437
2023-06-24 02:52:36.488603361  [2023-06-24 02:52:36] frigate.app                    INFO    : Camera 
2023-06-24 02:52:36.549596175  [2023-06-24 02:52:36] frigate.app                    INFO    : Capture process started for STUDY: 452
2023-06-24 02:52:45.386264205  [2023-06-24 02:52:45] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-06-24 02:52:45.386454196  [2023-06-24 02:52:45] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-06-24 02:52:45.386604881  [2023-06-24 02:52:45] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

In my config file I specified GPU but I think it's using the CPU instead.

<img width="476" alt="image" src="https://github.com/blakeblackshear/frigate/assets/19343200/59037efb-323b-4cda-b6ec-1cc7b40e5c0c">
