### ISSUE TITLE
[Config Support]: Unable to launch Container due to NVidia error

### ISSUE THREAD

**Issue by mclouse93** [blakeblackshear/frigate#6926]
### Describe the problem you are having

I've installed a handful of docker containers but for whatever reason, this one is giving me a lot of trouble. I'm trying to install this using docker-compose via Portainer. I USED to have a NVidia GPU for Plex Transcoding but I've since removed the GPU entirely. I BELIEVE at this point that I've removed all relevant nvidia processes from my server. Whenever I go to deploy the container, I get an error pertaining to the nvidia-container-cli. I am unable to do any hardware acceleration as I have an AMD CPU and no longer have a GPU in the server. I am waiting on my coral TPU, which is why I excluded the devices portion of the config entirely. I just wanted to play around with it while I waited for the coral to arrive, but I can't even get the container to launch.

I researched what the 'libnvidia-ml.so.1' is and it is for the Nvidia-SMI for when a running GPU is on the system, which is not the case. I'm not sure why I'm getting this error considering I'm not using an NVidia GPU.

I am no linux expert and I apologize if I missed important information. Feel free to ask anything and I will do my best to answer any and all questions. Thanks for your time!

### Version

N/A

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-uuid-d24bda17-c76d-4fa7-aebd-5d3fb183c2a4/Config/Frigate/config:/config.yml
      - /srv/dev-disk-by-uuid-f9f2b29c-9ea5-4c72-81c4-d7554ee7dccd/Frigate:/media
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ""
```

### Relevant log output

```shell
failed to deploy a stack: Network frigate_default Creating Network frigate_default Created Container frigate Creating Container frigate Created Container frigate Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #1: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Linux 5.10.0-0.deb10.16-amd64 x86_64
AMD CPU
NO Coral at this time. Waiting for it to arrive
NO GPU
Running OMV 5 using Portainer to manage containers. (I know this isn't recommended)
