### ISSUE TITLE
Newly added cameras not showing up in MQTT[Config Support]: 

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#6937]
### Describe the problem you are having

I've recently added two new cameras.

Neither are showing up in my MQTT server.

Please can you take a look at my config an point out my error?

The cameras are named 'west' and 'turning circle north'.

<img width="379" alt="image" src="https://github.com/blakeblackshear/frigate/assets/42817627/7d7674eb-968c-4d99-a411-f221d5c24e4a">

Both cameras are showing up in Frigate and in all other respects seem to be working as expected.

### Version

12.0

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.105
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60





go2rtc:
  streams:
    driveway:
      - rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=0
    turning_circle:
      - rtsp://admin:password@10.0.1.40:554/cam/realmonitor?channel=1&subtype=0
    car_park:
      - rtsp://admin:password@10.0.1.42:554/cam/realmonitor?channel=1&subtype=0
    south_terrace:
      - rtsp://admin:password@10.0.1.52:554/cam/realmonitor?channel=1&subtype=0
    garage_south:
      - rtsp://admin:password@10.0.1.22:554/cam/realmonitor?channel=1&subtype=0
    east:
      - rtsp://admin:password@10.0.1.56:554/11
    east_terrace:
      - rtsp://admin:password@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0
    courtyard:
      - rtsp://admin:password@10.0.1.54:554/cam/realmonitor?channel=1&subtype=0
    greenhouse:
      - rtsp://admin:password@10.0.1.55:554/cam/realmonitor?channel=1&subtype=0
    rear_garden:
      - rtsp://admin:password@10.0.1.229:554/cam/realmonitor?channel=1&subtype=0
    turning_circle_north:
      - rtsp://admin:password@10.0.1.246:554/cam/realmonitor?channel=1&subtype=0
    west:
      - rtsp://admin:password@10.0.1.51:554/cam/realmonitor?channel=1&subtype=0

    


database:
  path: /media/frigate/clips/frigate.db

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record


#### Testing with file ####
      # inputs:
      #   - path: /media/frigate/driveway.mp4
      #     input_args: -re -stream_loop -1 -fflags +genpts
      #     roles:
      #       - detect
      #       - rtmp


    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 20
      # stationary:
      #   interval: 0
      #   threshold: 50
    objects:
      track:
        - car
      filters:
        # person:
        #   threshold: 0.5
        #   min_score: 0.8
        car:
          threshold: 0.6
          min_score: 0.6
          min_area: 800
    motion:
      mask:
        - 704,0,704,88,0,68,0,0
        - 0,576,704,576,704,209,0,174
      threshold: 30  

      # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      contour_area: 28

      # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
      # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
      # Too low and a fast moving person wont be detected as motion.
      # Default is 0.2
      delta_alpha: 0.4

      # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
      # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
      # Low values will cause things like moving shadows to be detected as motion for longer.
      # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
      # Default is 0.2
      frame_alpha: 0.22

      # Optional: Height of the resized motion frame  (default: 50)
      # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
      # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
      # Default is 50
      frame_height: 55

    zones: 
      # left:
      #   coordinates: 0,92,0,136,132,139,120,94
      # # left:
      # #   coordinates: 50,93,50,134,241,142,236,112
      # middle:
      #   coordinates: 258,152,449,165,454,125,254,100
      # right:
      #   coordinates: 704,145,704,206,459,169,456,119zones:
      left:
        coordinates: 0,92,0,136,250,146,252,107
      middle:
        coordinates: 258,152,449,165,454,125,254,100
      right:
        coordinates: 672,143,671,205,459,169,456,119
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  turning_circle: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.40:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.40:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record


#### Testing with file ####
      # inputs:
      #   - path: /media/frigate/turning_circle.mp4
      #     input_args: -re -stream_loop -1 -fflags +genpts
      #     roles:
      #       - detect
      #       - rtmp

      
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 0
        threshold: 20
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
        car:
          threshold: 0.6
          min_score: 0.7
          mask:
            - 355,267,423,256,428,215,356,216
          min_area: 1200
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 0,0,0,171,355,196,355,257,438,259,437,220,640,201,640,0
    zones:
      tc_east:
        coordinates: 0,480,187,480,186,269,185,189,0,187
      tc_middle:
        coordinates: 190,480,399,480,399,198,182,190
      tc_west:
        coordinates: 640,480,404,480,405,194,640,197
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        # required_zones:
        #   - tc_east
        #   - tc_west
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  car_park:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.42:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.42:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record

### Testing with file ####
      # inputs:
      #   - path: /media/frigate/carpark.mp4
      #     input_args: -re -stream_loop -1 -fflags +genpts
      #     roles:
      #       - detect
      #       - rtmp


    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 0
        threshold: 20
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.6
          min_score: 0.7
        car:
          threshold: 0.6
          min_score: 0.75
          mask:
            - 280,160,348,209,403,125,408,99,301,90,279,103         
        dog:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 640,0,0,0,0,39,187,21,326,29,280,89,288,172,447,346,493,139
    zones:
      carpark_middle:
        coordinates: 302,139,279,100,180,94,131,138
      carpark_south:
        coordinates: 640,480,0,480,0,211,110,143,297,144
      top_of_drive:
        coordinates: 254,39,304,49,303,88,191,88
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        required_zones:
          - carpark_north
          - carpark_south
          - top_of_drive
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  south_terrace: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.52:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.52:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.6
          mask:
            - 640,101,640,197,130,217,0,255,0,107
            - 640,480,640,340,509,275,350,480,411,480
        dog:
          threshold: 0.5
          min_score: 0.55
    motion:
      mask:
        - 640,0,640,236,315,227,0,207,0,0
    zones:
      rear_lawn:
        coordinates: 640,266,640,480,335,480,195,264,191,235
      terrace:
        coordinates: 345,480,0,480,0,273,126,231,191,228
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - terrace
          - rear_lawn
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  garage_south: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.22:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
        dog:
          threshold: 0.5
          min_score: 0.6
        cat:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 0,74,610,68,640,183,640,0,0,0
    zones:
      south:
        coordinates: 203,79,258,87,327,78,640,107,640,352,0,352,0,119,126,92

    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - south
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.56:554/12
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.56:554/11
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 1920,210,1920,0,793,0,743,0,752,38,802,50,1083,130
      # threshold: 15
    # zones:
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east_terrace: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.5
          min_score: 0.6
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
        dog:
          threshold: 0.5
          min_score: 0.6
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
        cat:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 640,0,0,0,0,158,0,157,640,152
      # threshold: 15
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  courtyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.54:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.54:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        # - car
        - cat
        - dog
      filters:
        person:
          threshold: 0.7
          min_score: 0.65
        # car:
        #   # threshold: 0.5
        #   min_score: 0.7
        #   mask:
        #     - 250,119,260,196,181,207,179,127
        cat:
          min_score: 0.5
        dog:
          min_score: 0.5
    motion:
      mask:
        - 401,95,511,232,318,219,304,82
        - 640,0,640,40,282,45,291,148,219,160,215,54,0,95,0,0
    zones:
      courtyd:
        coordinates: 431,70,542,177,580,216,640,221,640,480,336,480,319,222,508,227,398,72
      terrace:
        coordinates: 0,158,0,117,222,93,223,110,236,165,191,480,0,480
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  greenhouse: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.55:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.55:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - cat
        - dog
        - person
      filters:
        cat:
          threshold: 0.6
          min_score: 0.65
        dog:
          threshold: 0.5
          min_score: 0.7
        person:
          threshold: 0.6
          min_score: 0.75
          mask:
            - 94,314,64,323,67,273,88,269
    motion:
      mask:
        - 0,195,704,198,704,0,0,0,0,0
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  west: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.51:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.51:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 0
        threshold: 20
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
        car:
          threshold: 0.6
          min_score: 0.7
          #mask:
          #  - 355,267,423,256,428,215,356,216
          #min_area: 1200
        dog:
          threshold: 0.5
          min_score: 0.7
        cat:
          threshold: 0.5
          min_score: 0.7
    zones:
      car_park_spaces:
        coordinates: 704,576,704,376,241,403,223,576
      garage_apron:
        coordinates: 301,187,272,389,32,371,102,197
      grass_bank:
        coordinates: 704,197,704,28,191,0,107,176
      car_park_driveway:
        coordinates: 704,233,704,415,260,397,300,213
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  rear_garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.229:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.229:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  turning_circle_north: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.1.246:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.246:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record     
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 0
        threshold: 20
    objects:
      track:
        - person
        - car
        - dog
        - horse
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
        car:
          threshold: 0.6
          min_score: 0.7
          #mask:
          #  - 355,267,423,256,428,215,356,216
          #min_area: 1200
        dog:
          threshold: 0.5
          min_score: 0.7
        horse:
          threshold: 0.5
          min_score: 0.7
    zones:
      stable:
        coordinates: 415,139,463,160,473,117,431,103
      tc_driveway:
        coordinates: 91,132,0,212,0,119,67,73
      front_door:
        coordinates: 570,576,634,486,616,459,571,500,526,529
      circle:
        coordinates: 148,121,338,121,468,147,526,170,578,204,638,255,704,366,516,553,415,419,384,369,449,363,493,336,496,267,445,205,369,182,128,175,84,196,48,280,337,367,483,576,195,576,51,436,0,379,0,251,86,137
    record:
      enabled: True
      retain:
        days: 5
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100
```

### Relevant log output

```shell
2023-06-28 06:33:03.369050319  [INFO] Starting Frigate...
2023-06-28 06:33:04.532901885  [2023-06-28 07:33:04] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-06-28 06:33:04.662854984  [2023-06-28 07:33:04] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-06-28 06:33:04.663308253  [2023-06-28 07:33:04] peewee_migrate                 INFO    : Starting migrations
2023-06-28 06:33:04.666692247  [2023-06-28 07:33:04] peewee_migrate                 INFO    : There is nothing to migrate
2023-06-28 06:33:04.688982100  [2023-06-28 07:33:04] frigate.app                    INFO    : Output process started: 227
2023-06-28 06:33:04.703017852  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for driveway: 233
2023-06-28 06:33:04.712604282  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for turning_circle: 235
2023-06-28 06:33:04.713686018  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for car_park: 236
2023-06-28 06:33:04.720051554  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for south_terrace: 238
2023-06-28 06:33:04.728158003  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for garage_south: 239
2023-06-28 06:33:04.742185757  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for east: 241
2023-06-28 06:33:04.759368680  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for east_terrace: 243
2023-06-28 06:33:04.765230243  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for courtyard: 245
2023-06-28 06:33:04.772310451  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for greenhouse: 246
2023-06-28 06:33:04.778543984  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for west: 248
2023-06-28 06:33:04.791713647  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for rear_garden: 249
2023-06-28 06:33:04.807372145  [2023-06-28 07:33:04] frigate.app                    INFO    : Camera processor started for turning_circle_north: 252
2023-06-28 06:33:04.812720835  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for driveway: 254
2023-06-28 06:33:04.818974229  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for turning_circle: 257
2023-06-28 06:33:04.829927683  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for car_park: 259
2023-06-28 06:33:04.841409280  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for south_terrace: 262
2023-06-28 06:33:04.857993876  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for garage_south: 267
2023-06-28 06:33:04.887492284  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for east: 279
2023-06-28 06:33:04.913734778  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for east_terrace: 303
2023-06-28 06:33:04.928554772  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for courtyard: 307
2023-06-28 06:33:04.953071380  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for greenhouse: 318
2023-06-28 06:33:04.981049002  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for west: 322
2023-06-28 06:33:04.994245775  [2023-06-28 07:33:04] frigate.app                    INFO    : Capture process started for rear_garden: 330
2023-06-28 06:33:05.008687667  [2023-06-28 07:33:05] frigate.app                    INFO    : Capture process started for turning_circle_north: 336
2023-06-28 06:33:07.848349502  [2023-06-28 07:33:04] detector.coral                 INFO    : Starting detection process: 226
2023-06-28 06:33:07.848353283  [2023-06-28 07:33:04] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-06-28 06:33:07.856144857  [2023-06-28 07:33:07] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
