### ISSUE TITLE
[Support]: Frigate's camera feed has 10 seconds delay when setup a go2rtc stream

### ISSUE THREAD

**Issue by kcgan** [blakeblackshear/frigate#6943]
### Describe the problem you are having

I have a Frigate NVR container running in Windows Docker Desktop. 

I set up a go2rtc stream for Ezviz OutPro 2K C3TN camera. I have to use this setting - ffmpeg:rtsp://admin:xxxx@192.168.xx.xxx:554/H.264/cam/realmonitor?channel=1&subtype=2#video=copy#audio=copy#audio=aac in order to work. However, there are about 10 seconds delay on Frigate's camera feed. Such delay did not occur when I just used the camera's RTSP URL as the camera input in Frigate config.

Is there anything I can do to alleviate this problem?

### Version

0.12.1-367D724

### Frigate config file

```yaml
go2rtc:
  streams:
    porch_frigate_ezvizcam:
      - "ffmpeg:rtsp://admin:xxxx@192.168.xx.xxx:554/H.264/cam/realmonitor?channel=1&subtype=2#video=copy#audio=copy#audio=aac"

cameras:
  porch_frigate_ezvizcam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/porch_frigate_ezvizcam
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Ezviz OutPro 2K C3TN

**Comment by NickM-27** [comment]
Is there a reason you are using `ffmpeg` vs just rtsp connection?

**Comment by kcgan** [comment]
> Is there a reason you are using `ffmpeg` vs just rtsp connection?

Following errors will occur if I just use rstp connection:
```
go2rtc:
  streams:
    porch_frigate_ezvizcam:
      - "rtsp://admin:xxxx@192.168.xx.xxx:554/H.264"
      - "ffmpeg:porch_frigate_ezvizcam#audio=aac"

```

```
2023-06-29 00:33:47.163903246  [2023-06-29 00:33:47] ffmpeg.porch_frigate_ezvizcam.detect ERROR   : [h264 @ 0x555b171a0e00] no frame!
2023-06-29 00:33:47.164012946  [2023-06-29 00:33:47] ffmpeg.porch_frigate_ezvizcam.detect ERROR   : [h264 @ 0x555b171a0e00] missing picture in access unit with size 1144
2023-06-29 00:33:47.164116846  [2023-06-29 00:33:47] ffmpeg.porch_frigate_ezvizcam.detect ERROR   : [h264 @ 0x555b171a0e00] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
2023-06-29 00:33:47.164215746  [2023-06-29 00:33:47] ffmpeg.porch_frigate_ezvizcam.detect ERROR   : [h264 @ 0x555b171a0e00] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
```
