### ISSUE TITLE
[HW Accel Support]: Strange situation - need to use different video cards for hw decoding vs encoding.

### ISSUE THREAD

**Issue by aaronouthier** [blakeblackshear/frigate#6964]
### Describe the problem you are having

I have both an Intel 915 integrated graphics, and an Nvidia GT 1030. The Nvidia can decode my cameras just fine, but the card itself has no support for hardware encoding at all. The built-in intel is complaining about my Amcrest 410 doorbell not supporting h.264 codec profile 66 or some such thing. Since it is a doorbell, there are very few settings I can change there.

Is it possible, and if so, what is involved in using the GT1030 for accelerated decoding, and the intel for hw accelerated encoding.

### Version

0.12.1-367d724

### Frigate config file

```yaml
database:
  path: /media/frigate/frigate.db

mqtt:
  enabled: True
  host: a.b.c.d
  port: 1883
  user: [Redacted]
  password: [Redacted]

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True

cameras:
  1_Doorbell: # <------ Name the camera
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://[redacted]@e.f.g.h:554/ # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: False
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128
      - /dev/dri/renderD129
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
#    environment:
#      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
--- hwaccel_args: preset-vaapi ---
frigate  | 2023-06-29 22:11:18.306679980  [2023-06-29 22:11:18] ffmpeg.1_Doorbell.detect       ERROR   : [h264 @ 0x555f2195b080] Failed setup for format vaapi: hwaccel initialis
ation returned error.
frigate  | 2023-06-29 22:11:18.306681709  [2023-06-29 22:11:18] ffmpeg.1_Doorbell.detect       ERROR   : Impossible to convert between the formats supported by the filter 'Parse
d_fps_0' and the filter 'auto_scale_0'
frigate  | 2023-06-29 22:11:18.306683125  [2023-06-29 22:11:18] ffmpeg.1_Doorbell.detect       ERROR   : Error reinitializing filters!
frigate  | 2023-06-29 22:11:18.306684600  [2023-06-29 22:11:18] ffmpeg.1_Doorbell.detect       ERROR   : Failed to inject frame into filter network: Function not implemented
frigate  | 2023-06-29 22:11:18.306686041  [2023-06-29 22:11:18] ffmpeg.1_Doorbell.detect       ERROR   : Error while processing the decoded data for stream #0:0
frigate  | 2023-06-29 22:11:20.290291468  [2023-06-29 22:11:20] frigate.video                  ERROR   : 1_Doorbell: Unable to read frames from ffmpeg process.
frigate  | 2023-06-29 22:11:20.290535460  [2023-06-29 22:11:20] frigate.video                  ERROR   : 1_Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-06-29 22:11:28.312638753  [2023-06-29 22:11:28] watchdog.1_Doorbell            ERROR   : Ffmpeg process crashed unexpectedly for 1_Doorbell.
frigate  | 2023-06-29 22:11:28.312815376  [2023-06-29 22:11:28] watchdog.1_Doorbell            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-06-29 22:11:28.312817575  [2023-06-29 22:11:28] ffmpeg.1_Doorbell.detect       ERROR   : [h264 @ 0x55a0fba91180] No support for codec h264 profile 66.
frigate  | 2023-06-29 22:11:28.312925513  [2023-06-29 22:11:28] ffmpeg.1_Doorbell.detect       ERROR   : [h264 @ 0x55a0fba91180] Failed setup for format vaapi: hwaccel initialis
ation returned error.
frigate  | 2023-06-29 22:11:28.312927759  [2023-06-29 22:11:28] ffmpeg.1_Doorbell.detect       ERROR   : Impossible to convert between the formats supported by the filter 'Parse
d_fps_0' and the filter 'auto_scale_0'
frigate  | 2023-06-29 22:11:28.313000422  [2023-06-29 22:11:28] ffmpeg.1_Doorbell.detect       ERROR   : Error reinitializing filters!
frigate  | 2023-06-29 22:11:28.313087272  [2023-06-29 22:11:28] ffmpeg.1_Doorbell.detect       ERROR   : Failed to inject frame into filter network: Function not implemented
frigate  | 2023-06-29 22:11:28.313172574  [2023-06-29 22:11:28] ffmpeg.1_Doorbell.detect       ERROR   : Error while processing the decoded data for stream #0:0
frigate  | 2023-06-29 22:11:30.194656820  [2023-06-29 22:11:30] frigate.video                  ERROR   : 1_Doorbell: Unable to read frames from ffmpeg process.
frigate  | 2023-06-29 22:11:30.194766102  [2023-06-29 22:11:30] frigate.video                  ERROR   : 1_Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-06-29 22:11:38.319635777  [2023-06-29 22:11:38] watchdog.1_Doorbell            ERROR   : Ffmpeg process crashed unexpectedly for 1_Doorbell.
frigate  | 2023-06-29 22:11:38.319639703  [2023-06-29 22:11:38] watchdog.1_Doorbell            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-06-29 22:11:38.322739027  [2023-06-29 22:11:38] ffmpeg.1_Doorbell.detect       ERROR   : [h264 @ 0x55b7e86b6800] No support for codec h264 profile 66.
frigate  | 2023-06-29 22:11:38.322742168  [2023-06-29 22:11:38] ffmpeg.1_Doorbell.detect       ERROR   : [h264 @ 0x55b7e86b6800] Failed setup for format vaapi: hwaccel initialis
ation returned error.
frigate  | 2023-06-29 22:11:38.322744076  [2023-06-29 22:11:38] ffmpeg.1_Doorbell.detect       ERROR   : Impossible to convert between the formats supported by the filter 'Parse
d_fps_0' and the filter 'auto_scale_0'
--- end ---

--- hwaccel_args: preset-nvidia-h264 ---
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service nginx successfully started
frigate  | 2023-06-29 22:15:16.277220683  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-06-29 22:15:16.540461669  [INFO] Starting go2rtc...
frigate  | 2023-06-29 22:15:16.606527615  22:15:16.605 INF go2rtc version 1.2.0 linux/amd64
frigate  | 2023-06-29 22:15:16.606531228  22:15:16.606 INF [api] listen addr=:1984
frigate  | 2023-06-29 22:15:16.606533305  22:15:16.606 INF [rtsp] listen addr=:8554
frigate  | 2023-06-29 22:15:16.606535106  22:15:16.606 INF [srtp] listen addr=:8443
frigate  | 2023-06-29 22:15:16.606536925  22:15:16.606 INF [webrtc] listen addr=:8555
frigate  | 2023-06-29 22:15:17.368812022  [2023-06-29 22:15:17] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
frigate  | 2023-06-29 22:15:17.382279119  [2023-06-29 22:15:17] peewee_migrate                 INFO    : Starting migrations
frigate  | 2023-06-29 22:15:17.386880917  [2023-06-29 22:15:17] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | 2023-06-29 22:15:17.405353852  [2023-06-29 22:15:17] frigate.app                    INFO    : Output process started: 226
frigate  | 2023-06-29 22:15:17.410590956  [2023-06-29 22:15:17] frigate.app                    INFO    : Camera processor started for 1_Doorbell: 229
frigate  | 2023-06-29 22:15:17.422280287  [2023-06-29 22:15:17] frigate.app                    INFO    : Capture process started for 1_Doorbell: 230
frigate  | 2023-06-29 22:15:19.204920451  [2023-06-29 22:15:19] frigate.video                  ERROR   : 1_Doorbell: Unable to read frames from ffmpeg process.
frigate  | 2023-06-29 22:15:19.205188135  [2023-06-29 22:15:19] frigate.video                  ERROR   : 1_Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-06-29 22:15:20.223661747  [2023-06-29 22:15:17] detector.coral                 INFO    : Starting detection process: 225
frigate  | 2023-06-29 22:15:20.223665497  [2023-06-29 22:15:17] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate  | 2023-06-29 22:15:20.227784302  [2023-06-29 22:15:20] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate  | 2023-06-29 22:15:26.191246143  [INFO] Starting go2rtc healthcheck service...
frigate  | 2023-06-29 22:15:37.454528566  [2023-06-29 22:15:37] watchdog.1_Doorbell            ERROR   : Ffmpeg process crashed unexpectedly for 1_Doorbell.
frigate  | 2023-06-29 22:15:37.454828712  [2023-06-29 22:15:37] watchdog.1_Doorbell            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-06-29 22:15:37.455031458  [2023-06-29 22:15:37] ffmpeg.1_Doorbell.detect       ERROR   : [AVHWDeviceContext @ 0x55b39321c7c0] Cannot load libcuda.so.1
frigate  | 2023-06-29 22:15:37.455204462  [2023-06-29 22:15:37] ffmpeg.1_Doorbell.detect       ERROR   : [AVHWDeviceContext @ 0x55b39321c7c0] Could not dynamically load CUDA
frigate  | 2023-06-29 22:15:37.455377268  [2023-06-29 22:15:37] ffmpeg.1_Doorbell.detect       ERROR   : Device creation failed: -1.
frigate  | 2023-06-29 22:15:37.455546756  [2023-06-29 22:15:37] ffmpeg.1_Doorbell.detect       ERROR   : [h264 @ 0x55b393219f00] No device available for decoder: device type cud
a needed for codec h264.
frigate  | 2023-06-29 22:15:37.455715063  [2023-06-29 22:15:37] ffmpeg.1_Doorbell.detect       ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not per
mitted
frigate  | 2023-06-29 22:15:39.206206170  [2023-06-29 22:15:39] frigate.video                  ERROR   : 1_Doorbell: Unable to read frames from ffmpeg process.
frigate  | 2023-06-29 22:15:39.206577879  [2023-06-29 22:15:39] frigate.video                  ERROR   : 1_Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-06-29 22:15:47.458440954  [2023-06-29 22:15:47] watchdog.1_Doorbell            ERROR   : Ffmpeg process crashed unexpectedly for 1_Doorbell.
frigate  | 2023-06-29 22:15:47.458444646  [2023-06-29 22:15:47] watchdog.1_Doorbell            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-06-29 22:15:47.461335735  [2023-06-29 22:15:47] ffmpeg.1_Doorbell.detect       ERROR   : [AVHWDeviceContext @ 0x560f098727c0] Cannot load libcuda.so.1
frigate  | 2023-06-29 22:15:47.461450939  [2023-06-29 22:15:47] ffmpeg.1_Doorbell.detect       ERROR   : [AVHWDeviceContext @ 0x560f098727c0] Could not dynamically load CUDA
frigate  | 2023-06-29 22:15:47.461692490  [2023-06-29 22:15:47] ffmpeg.1_Doorbell.detect       ERROR   : Device creation failed: -1.
frigate  | 2023-06-29 22:15:47.461695356  [2023-06-29 22:15:47] ffmpeg.1_Doorbell.detect       ERROR   : [h264 @ 0x560f096c3e00] No device available for decoder: device type cud
a needed for codec h264.
frigate  | 2023-06-29 22:15:47.461697084  [2023-06-29 22:15:47] ffmpeg.1_Doorbell.detect       ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not per
mitted
frigate  | 2023-06-29 22:15:49.215260708  [2023-06-29 22:15:49] frigate.video                  ERROR   : 1_Doorbell: Unable to read frames from ffmpeg process.
frigate  | 2023-06-29 22:15:49.215481202  [2023-06-29 22:15:49] frigate.video                  ERROR   : 1_Doorbell: ffmpeg process is not running. exiting capture thread...
--- end ---
```

### FFprobe output from your camera

```shell
-bash: ffprobe: command not found
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Multiple Amcrest models. Only 410 doorbell config'd currently.

### Any other information that may be helpful

On my Proxmox host, I blacklisted my video and audio kernel modules, and ran 'update-initramfs -k all -u', before restarting. Both the GT1030 and the Intel graphics appear to be correctly forwarded into the VM via iommu.
