### ISSUE TITLE
[Config Support]: cannot view recordings of debug api stream in web UI

### ISSUE THREAD

**Issue by illivanillie** [blakeblackshear/frigate#6971]
### Describe the problem you are having

I cannot view the recordings of my debug stream in the web ui. The files do exist as mp4 in the media folder and can be played. Message: „ The media could not be loaded, either because the server or network failed or because the format is not supported.“.
Cameras:
 - debug_cam_seitentor
 - debug_cam_terrasse

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.178.72
  port: 1883
  user: mqtt
  password: x
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog

motion: 
  # The value should be between 1 and 255.
  threshold: 30
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 15
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: false
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 2
go2rtc:
  streams:
    #sub for 24h recording
    debug_seitentor:
      - http://192.168.178.72:5000/api/Seitentor?motion=1
    rlnk_sub:
      - http://192.168.178.58/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=x
    rlnk_main:
      - http://192.168.178.58/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=x
      - http_mjpeg:rlnk_main#video=h265
    rlnk_ext:
      - http://192.168.178.58/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=x
    stream_terrasse_rtc_sub_h264:
      - rtsp://admin:x@192.168.178.58:554/h264Preview_01_sub
    #sub for 24h recording
    stream_seitentor_rtc_sub_h264:
      - rtsp://admin:x@192.168.178.65:554/h264Preview_01_sub
cameras:
  #1
  #direct rlnk stream
  kamera_terrasse_frigate_ai:
    ffmpeg:
      inputs:
        - path: rtsp://admin:x@192.168.178.58:554/h265Preview_01_main
#        - path: rtsp://192.168.178.72:8554/rlnk_main
          hwaccel_args: preset-nvidia-h265
          input_args: preset-rtsp-udp
          roles:
            - record
            - detect
    detect: 
      enabled: true
      width: 4608 # <---- update for your camera's resolution
      height: 1728 # <---- update for your camera's resolution
      fps: 6
    record:
      enabled: true
      retain:
        days: 2
        mode: active_objects
    motion:
      mask:
        - 576,394,744,296,1114,122,1448,0,2930,0,3207,105,3479,230,3781,373,3981,499,4100,612,4608,1009,4608,0,0,0,0,917
        - 4462,1454,4608,1323,4608,1728,4333,1728
        - 0,1728,0,1075,759,1728
    birdseye:
      enabled: false
  #2
  #sub for 24h recording
  #stream_terrasse_rtc_sub_h264
  Kamera_Terrasse_Frigate:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.72:8554/stream_terrasse_rtc_sub_h264
          hwaccel_args: preset-nvidia-h264
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
    #MASKED!!
    detect: 
      enabled: true
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
    motion:
      mask:
        - 194,133,250,102,370,42,485,0,976,0,1072,33,1162,73,1220,105,1325,166,1364,210,1381,200,1536,329,1536,0,0,0,0,307
        - 1536,576,1536,433,1494,474,1449,576
        - 0,576,0,354,246,576
    zones:
      zone_rasen:
        coordinates: 527,526,775,576,1056,524,1295,437,1486,353,1388,207,1228,172,930,120,680,124,420,177,326,446
  #3
  #  #direct rlnk stream
  kamera_seitentor_frigate_ai: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:x@192.168.178.65:554/h265Preview_01_main
          hwaccel_args: preset-nvidia-h265
          input_args: preset-rtsp-udp
          roles:
            - record
            - detect
    detect: 
      enabled: true
      width: 4608 # <---- update for your camera's resolution
      height: 1728 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 2
        mode: active_objects
    motion:
      mask:
        - 0,1728,0,0,1445,0,1015,239,1096,320,1072,355,971,284,711,717,567,648,337,1054,1547,1586,815,1407,1299,1728
        - 2977,1646,3476,1499,4608,1018,4608,860,4414,552,3446,0,4608,0,4608,1728,2273,1728
    birdseye:
      enabled: false
  #4
  #sub for 24h recording
  #stream_seitentor_rtc_sub_h264
  Kamera_Seitentor_Frigate:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.72:8554/stream_seitentor_rtc_sub_h264
          hwaccel_args: preset-nvidia-h264
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
    #MASKED!!
    detect: 
      enabled: true
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
    motion:
      mask:
        - 114,356,498,528,265,462,466,576,0,576,0,0,192,0,1159,0,1308,91,1397,138,1469,189,1515,267,1536,340,1311,439,1054,529,824,576,1536,576,1536,198,1536,0,1187,0,486,0,344,79,367,105,353,113,322,88,269,178,233,238,185,215
  debug_cam_seitentor:
    ffmpeg:
      inputs:
        - path: http://192.168.178.72:5000/api/Kamera_Seitentor_Frigate?motion=1&bbox=1&fps=15
          hwaccel_args: preset-nvidia-h264
          input_args: preset-http-mjpeg-generic
          roles:
            - record
            - detect
    detect: 
      enabled: false
      width: 960 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    birdseye:
      enabled: false
  debug_cam_terrasse:
    ffmpeg:
      inputs:
        - path: http://192.168.178.72:5000/api/Kamera_Terrasse_Frigate?motion=1&bbox=1&fps=15
          hwaccel_args: preset-nvidia-h264
          input_args: preset-http-mjpeg-generic
          roles:
            - record
            - detect
    detect: 
      enabled: false
      width: 960 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    birdseye:
      enabled: false
#  http_cam:
#    ffmpeg:
#      inputs:
#        - path: http://192.168.178.58/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=x
#          hwaccel_args: preset-nvidia-h264
#          input_args: preset-http-reolink
#          roles: 
#            - record
#    record:
#      enabled: true
#      retain:
#        days: 2
#        mode: all #ÄNDERN!!

  #TEST
  #sub for 24h recording
  #stream_terrasse_rtc_sub_h264

#  rlnk_main:
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.178.72:8554/rlnk_main
#          hwaccel_args: preset-nvidia-h265
#          input_args: preset-rtsp-generic
#          roles:
#            - record
#            - detect
#    #MASKED!!
#    detect: 
#      enabled: true
#      width: 4608 # <---- update for your camera's resolution
#      height: 1728 # <---- update for your camera's resolution
#    record:
#      enabled: true
#      retain:
#        days: 2
#        mode: all #ÄNDERN!!

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
birdseye:
  enabled: True
  mode: motion
  quality: 8
  restream: true
```

### Relevant log output

```shell
none.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Using a nvidia GPU
