### ISSUE TITLE
[Config Support]:  go2rtc casting to Nest Hub Max issues

### ISSUE THREAD

**Issue by haroldboom** [blakeblackshear/frigate#6972]
### Describe the problem you are having

Hi all,

I recently converted my config to use go2rtc and it all works the same as usual however I cant cast any higher resolution than 2560x1440 to my Nest Hub Max.

I have a simple automation in HA that when a person is detected it casts the camera feed to my Nest Hub Max. However since moving to go2rtc it will only work when the resolution of the camera is set to 1440 max. Any higher resolution and it just displays a black screen. It also behaves differently when it loads, is it using WebRTC now instead of jsmpeg to cast?

Is there anyway to send a lower resolution to the Nest Hub Max via cast? Or alternatively cast as jsmpeg to it?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: redacted
  user: mqtt
  password: mqtt

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'

go2rtc:
  streams:
    Porch:
      - rtsp://redacted@10.0.0.3:554/Streaming/Channels/101
    Driveway:
      - rtsp://redacted@10.0.0.4:554/Streaming/Channels/101
    Front_Yard:
      - rtsp://redacted@10.0.0.10:554/Streaming/Channels/101
    Laundry_Stairs:
      - rtsp://redacted@10.0.0.5:554/Streaming/Channels/101
    Backyard:
      - rtsp://redacted@10.0.0.6:554/Streaming/Channels/101
    Decking:
      - rtsp://redacted@10.0.0.7:554/Streaming/Channels/101
    Veggie_Garden:
      - rtsp://redacted@10.0.0.8:554/Streaming/Channels/101
    Garage:
      - rtsp://redacted@10.0.0.9:554/Streaming/Channels/101
      
  webrtc:
    candidates:
      - redacted internal ip:8555
      - redacted external dns:8555
cameras:
  Porch:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 0

  Driveway:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        person:
          threshold: 0.7
        car:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 1

  Front_Yard:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Yard
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 2

  Laundry_Stairs:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Laundry_Stairs
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 3

  Backyard:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 4

  Decking:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Decking
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 5

  Veggie_Garden:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Veggie_Garden
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 6

  Garage:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 7

record:
  enabled: true
  events:
    retain:
      default: 30

rtmp:
  enabled: False

birdseye:
  enabled: True
  mode: continuous

logger:
  default: info

timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

HA Automation

alias: Porch Show on Nest Max
description: ""
trigger:
  - type: occupied
    platform: device
    device_id: 2b3e5569b84e13645a4737bffddb951b
    entity_id: binary_sensor.porch_all_occupancy
    domain: binary_sensor
condition:
  - condition: state
    entity_id: alarm_control_panel.hpgw_b0c5ca3981c6_area_1
    state: disarmed
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.nesthubmax16f2
    data:
      media_content_id: media-source://camera/camera.porch
      media_content_type: application/vnd.apple.mpegurl
    metadata:
      title: null
      thumbnail: /api/camera_proxy/camera.porch
      media_class: video
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://camera
  - wait_for_trigger:
      - type: not_occupied
        platform: device
        device_id: 2b3e5569b84e13645a4737bffddb951b
        entity_id: binary_sensor.porch_all_occupancy
        domain: binary_sensor
        for:
          hours: 0
          minutes: 0
          seconds: 0
    timeout:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.nesthubmax16f2
mode: single
