### ISSUE TITLE
[Detector Support]: Running 2 Frigate containers. How to set up 2 USB Coral TPUs

### ISSUE THREAD

**Issue by indo419** [blakeblackshear/frigate#6980]
### Describe the problem you are having

How do we set up config.yml to connect 2 Frigate containers on same Ubuntu machine to 2 USB Coral TPUs.  I was not able to share 1 TPU with 2 containers.  Can this be done with 2 TPUs?

detectors:
  coral:
    type: edgetpu
    device: usb      <- can we specify specific USB ports here or is it even required?

Also, can hardware acceleration be shared among 2 Frigate containers?

We have Intel i7 processor with on chip graphics (Dell 9020) and a Nvidia Quadro K1200 PCIe card installed

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False


#logger:
#  # Optional: default log level (default: shown below)
#  default: debug


detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu
#    num_threads: 3
#  cpu2:
#    type: cpu
#    num_threads: 3
#  cpu3:
#    type: cpu
#    num_threads: 3
#  cpu4:
#    type: cpu
#    num_threads: 3

birdseye:
  enabled: True
  restream: False
  width: 1280
  height: 720
  quality: 8        # 1 is the highest quality, and 31 is the lowest.
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects


detect:
  enabled: True
  width: 640 # <---- update for your camera's resolution
  height: 480 # <---- update for your camera's resolution
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
#    max_frames:
#      default: 3000
#      objects:
#        person: 1000


record:
  enabled: True
  expire_interval: 180
  retain:
    days: 10
    mode: motion    # all, motion, and active_objects
  events:
    pre_capture: 5
    post_capture: 5
    objects:    # track all opbjects
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - cat
      - dog
      - bird
#    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        person: 20
        car: 20
        bicycle: 20
        motorcycle: 20
        bus: 20
        cat: 20
        dog: 20
        bird: 20


snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
#  height: 175
#  required_zones: []
  retain:
    default: 10
    objects:
      person: 30
      car: 30
      bicycle: 30
      motorcycle: 30
      bus: 30
      cat: 30
      dog: 30
      bird: 30



timestamp_style:
  position: "tr"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 100
  thickness: 1
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "shadow"



cameras:
```

### docker-compose file or Docker CLI command

```yaml
sudo docker run -d --name frigate1 --privileged --restart=unless-stopped --env=TZ=America/Los_Angeles --mount type=tmpfs,target=/tmp/cache,tmpfs-size=5000000000 --shm-size=256m -v /NVR_Data/frigate_media1:/media/frigate -v /NVR_Data/frigate_conf/config1.yml:/config/config.yml -v /etc/localtime:/etc/localtime:ro -e FRIGATE_RTSP_PASSWORD='xxxxx' -p 5100:5000 -p 8654:8554 -p 8655:8555/tcp -p 8655:8555/udp ghcr.io/blakeblackshear/frigate:stable

sudo docker run -d --name frigate2 --privileged --restart=unless-stopped --env=TZ=America/Los_Angeles --mount type=tmpfs,target=/tmp/cache,tmpfs-size=5000000000 --shm-size=256m -v /NVR_Data/frigate_media2:/media/frigate -v /NVR_Data/frigate_conf/config2.yml:/config/config.yml -v /etc/localtime:/etc/localtime:ro -e FRIGATE_RTSP_PASSWORD='xxxxx' -p 5200:5000 -p 8754:8554 -p 8755:8555/tcp -p 8755:8555/udp ghcr.io/blakeblackshear/frigate:stable
```

### Relevant log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

**Comment by NickM-27** [comment]
> I was not able to share 1 TPU with 2 containers. 

Right, this is not possible as corals can only be connected to by a single process.

> Can this be done with 2 TPUs?

Yes, just specify the coral to use by using 

```
detectors:
  coral:
    type: edgetpu
    device: usb:0 # <- use 1 for the other coral
```
