### ISSUE TITLE
Unable to view time on phone

### ISSUE THREAD

**Issue by siri10086** [blakeblackshear/frigate#6988]
![22](https://github.com/blakeblackshear/frigate/assets/61342291/5ac0a11c-72b1-4cce-adb3-033ed327c661)
![11](https://github.com/blakeblackshear/frigate/assets/61342291/48dad316-acf1-4e1a-bb45-0cdd953951ae)
Unable to view time on phone

**Comment by NickM-27** [comment]
this is most likely due to the fact that you have configured the `long` form for time. If you don't use that then it shows up on the phone without issues

**Comment by siri10086** [comment]
> this is most likely due to the fact that you have configured the `long` form for time. If you don't use that then it shows up on the phone without issues

I haven't configured time for long forms, and I don't know where to configure it

**Comment by NickM-27** [comment]
Interesting, I didn't think that was the default. Maybe the issue is test size related. Anyway, if you want to you can configure it in the UI config:

```
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: False
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
```

**Comment by siri10086** [comment]
> Interesting, I didn't think that was the default. Maybe the issue is test size related. Anyway, if you want to you can configure it in the UI config:
> 
> ```
> ui:
>   # Optional: Set the default live mode for cameras in the UI (default: shown below)
>   live_mode: mse
>   # Optional: Set a timezone to use in the UI (default: use browser local time)
>   # timezone: America/Denver
>   # Optional: Use an experimental recordings / camera view UI (default: shown below)
>   use_experimental: False
>   # Optional: Set the time format used.
>   # Options are browser, 12hour, or 24hour (default: shown below)
>   time_format: browser
>   # Optional: Set the date style for a specified length.
>   # Options are: full, long, medium, short
>   # Examples:
>   #    short: 2/11/23
>   #    medium: Feb 11, 2023
>   #    full: Saturday, February 11, 2023
>   # (default: shown below).
>   date_style: short
>   # Optional: Set the time style for a specified length.
>   # Options are: full, long, medium, short
>   # Examples:
>   #    short: 8:14 PM
>   #    medium: 8:15:22 PM
>   #    full: 8:15:22 PM Mountain Standard Time
>   # (default: shown below).
>   time_style: medium
> ```

I have set the UI, which is only useful for computer browsers. However, when viewed by the browser on my phone, only the date and no time are available

**Comment by sinamics** [comment]
This is by design, due to the fact that it will be stretched over two lines on devices smaller than 410px wide. 
https://github.com/blakeblackshear/frigate/pull/5097#pullrequestreview-1249080866

however, i will see if i can come up with an acceptable solution.

**Comment by NickM-27** [comment]
@sinamics yeah that was my understanding as well, I think in the case of xs we may want to at least show the time on a second line

**Comment by sinamics** [comment]
ah, i see now that OP is refering to the acutal time. I was refering to the `- 3d ago ( 10s )` part. 
It should not be any limitation on the actual time.  @siri10086 could you post the `ui:` part of your config.yml, and the frigate version you using?

Im not able to reproduce the time behaviour.

**Comment by siri10086** [comment]
> ah, i see now that OP is refering to the acutal time. I was refering to the `- 3d ago ( 10s )` part. It should not be any limitation on the actual time. @siri10086 could you post the `ui:` part of your config.yml, and the frigate version you using?
> 
> Im not able to reproduce the time behaviour.

Frigate (0.12.1-367d724)

detectors:
  coral:
    type: edgetpu
    device: usb
    

mqtt:

  host: 192.168.0.1
  user: root
  password: xxxxxxxx

   
objects:
  track:
    - person

  filters:
    person:
      min_area: 10000
      min_score: 0.55

      
go2rtc:
  streams:
    fristcamera: 
      - rtsp://admin:xxxxx@192.168.88.41:554/h264/ch1/main/av_stream/ 
      - "ffmpeg:rtsp_cam#audio=opus" 
    ketingcamera: 
      - rtsp://admin:xxxxx@192.168.88.59:554/h264/ch1/main/av_stream/ 
      - "ffmpeg:rtsp_cam#audio=opus" 

  webrtc: 
    candidates:
      - 192.168.88.88:8556
      - stun:8555

cameras:
  fristcamera:
    ffmpeg:
      inputs:
        
        - path: rtsp://admin:xxxxx@192.168.88.41:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
            - rtmp
        
      output_args:
        record: preset-record-generic-audio-aac
        

    objects:
      filters:
        object_0:
          mask:
            - 424,354,513,322,486,0,381,0
        person:
          mask:
            - 424,354,513,322,486,0,381,0
    motion: 
      mask:
        - 283,189,404,357,499,329,477,0,366,0,233,0,0,0,0,720,380,720
        - 1217,699,1218,670,959,670,959,699
    zones:
      zone_dianti:
        coordinates: 784,376,804,422,840,459,890,506,951,563,1101,0,800,0
    snapshots:
      
      enabled: True
      
      clean_copy: True
      
      timestamp: False
      
      crop: False

    
    mqtt:
      
      enabled: True
     
      timestamp: False
      
      bounding_box: True
     
      crop: False
     
      quality: 100

    record:
      
      
      enabled: True
      
      expire_interval: 60
      
      retain:
        
        days: 0

        mode: all
     
      events:
       
        pre_capture: 2
       
        post_capture: 5
        
        objects:
          - person

        retain:
          
          default: 180
          mode: motion
          objects:
            person: 180

  ketingcamera:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://admin:xxxxx@192.168.88.59:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
            - rtmp

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False

      crop: False


    mqtt:

      enabled: True

      timestamp: False
 
      bounding_box: True

      crop: False
      
      quality: 100
      
    
    record:
      
      
      enabled: True
      
      expire_interval: 60
      
      retain:
        
        days: 0
        
        mode: all
      
      events:
       
        pre_capture: 2
        
        post_capture: 5
        
        objects:
          - person
        retain:
          
          default: 180

          mode: motion
          objects:
            person: 180

**Comment by siri10086** [comment]
> ah, i see now that OP is refering to the acutal time. I was refering to the `- 3d ago ( 10s )` part. It should not be any limitation on the actual time. @siri10086 could you post the `ui:` part of your config.yml, and the frigate version you using?
> 
> Im not able to reproduce the time behaviour.

Frigate (0.12.1-367d724)

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.0.1
  user: root
  password: xxxxxxxx

objects:
  track:
    - person

  filters:
    person:
      min_area: 10000
      min_score: 0.55

go2rtc:
  streams:
    fristcamera:
      - rtsp://admin:xxxxx@192.168.88.41:554/h264/ch1/main/av_stream/
      - "ffmpeg:rtsp_cam#audio=opus"
    ketingcamera:
      - rtsp://admin:xxxxx@192.168.88.59:554/h264/ch1/main/av_stream/
      - "ffmpeg:rtsp_cam#audio=opus"

  webrtc:
    candidates:
      - 192.168.88.88:8556
      - stun:8555

cameras:
  fristcamera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxx@192.168.88.41:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
            - rtmp

      output_args:
        record: preset-record-generic-audio-aac

    objects:
      filters:
        object_0:
          mask:
            - 424,354,513,322,486,0,381,0
        person:
          mask:
            - 424,354,513,322,486,0,381,0
    motion:
      mask:
        - 283,189,404,357,499,329,477,0,366,0,233,0,0,0,0,720,380,720
        - 1217,699,1218,670,959,670,959,699
    zones:
      zone_dianti:
        coordinates: 784,376,804,422,840,459,890,506,951,563,1101,0,800,0
    snapshots:
      enabled: True

      clean_copy: True

      timestamp: False

      crop: False

    mqtt:
      enabled: True

      timestamp: False

      bounding_box: True

      crop: False

      quality: 100

    record:
      enabled: True

      expire_interval: 60

      retain:
        days: 0

        mode: all

      events:
        pre_capture: 2

        post_capture: 5

        objects:
          - person

        retain:
          default: 180
          mode: motion
          objects:
            person: 180

  ketingcamera:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://admin:xxxxx@192.168.88.59:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
            - rtmp

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False

      crop: False

    mqtt:
      enabled: True

      timestamp: False

      bounding_box: True

      crop: False

      quality: 100

    record:
      enabled: True

      expire_interval: 60

      retain:
        days: 0

        mode: all

      events:
        pre_capture: 2

        post_capture: 5

        objects:
          - person
        retain:
          default: 180

          mode: motion
          objects:
            person: 180

**Comment by siri10086** [comment]
Frigate (0.12.1-367d724)
There is still only a date on the phone, but no time.
[config.txt](https://github.com/blakeblackshear/frigate/files/11953025/config.txt)
![222](https://github.com/blakeblackshear/frigate/assets/61342291/2c9c0940-e9a6-4e3a-a386-53bd85e9c440)

**Comment by sinamics** [comment]
Im still unable to re-produce this issue. Tested on chrome, firefox, edge. 
The only thing i can think of is your phone's locale or language settings.

@siri10086 Could you try to set the `time_format: 24hour` or `12hour` in config.yml instead of browser and see if that makes any diffrence?

**Comment by siri10086** [comment]
> Im still unable to re-produce this issue. Tested on chrome, firefox, edge. The only thing i can think of is your phone's locale or language settings.
> 
> @siri10086 Could you try to set the `time_format: 24hour` or `12hour` in config.yml instead of browser and see if that makes any diffrence?

First of all, thank you very much for your test and answer. I am using an Apple phone, and the phone area in China is in Chinese. Previously, the time can be seen normally on the Frigate (0.11.1-2EADA21) version of the phone. Now, after setting it to 12 hours or 24 hours, I still can't see the time on my phone, even if I don't set the UI by default.

**Comment by sinamics** [comment]
Could you please inform about which model of iPhone and browser you are currently using? Additionally, it would be very helpful if you could try accessing Frigate with a different browser for testing purposes. Unfortunately, I don't have an iPhone readily available for testing at the moment.

Also your phone`s timezone and other date/time settings would be highly appreciated.

**Comment by siri10086** [comment]
iPhone 11 Pro
Browser tested with Safari and Chrome with the same results

**Comment by siri10086** [comment]
I found that switching to an Android phone is normal and you can see the time

**Comment by sinamics** [comment]
> I found that switching to an Android phone is normal and you can see the time

thx for reporting. I will try to locate an iphone and conduct further testing.

**Comment by sinamics** [comment]
so my conclusion is that some older IOS devices does not support timeStyle in `Intl.DateTimeFormat`.
it was itrodused in Safari 2021-04-26 accourding to this site:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

When I remove the timeStyle attribute from the Intl.DateTimeFormat configuration object, the output is missing the time part.

and as i understand, any 3rd party browser in IOS is required to use the same WebKit rendering engine as Safari due to Apple's App Store Guidelines, hence the issue will also occur in chrome or any other browser. 
`2.5.6 Apps that browse the web must use the appropriate WebKit framework and WebKit JavaScript.`
https://developer.apple.com/app-store/review/guidelines/

@siri10086 if my assumption is correct, it might work if you add a custom strftime_fmt in config.yml.
Could you try to modify you config:

```yml
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  #live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: True
  strftime_fmt: '%d.%m.%Y, %H:%M:%S'
```

if this wont work, i will try to create a fallback function to handle devices with lack of timeStyle support.

**Comment by siri10086** [comment]
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  #live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: True
  strftime_fmt: '%d.%m.%Y, %H:%M:%S'

Setting the UI still doesn't work, and even the computer and phone display Invalid time. I don't think it's due to the old iOS device. I tested it repeatedly with the latest iPhone 14 Pro Max and it still doesn't show the time.


![WechatIMG36974](https://github.com/blakeblackshear/frigate/assets/61342291/952aa2a3-5b2f-4510-8bbf-6368f7cb7a54)
![22](https://github.com/blakeblackshear/frigate/assets/61342291/731f7d72-b223-4a2e-a2ae-d4edbc484b02)

**Comment by sinamics** [comment]
That's odd. I will need an iphone so i can test this myself.

**Comment by siri10086** [comment]
I also think it's strange, or as you said,try to create a fallback function to handle devices with lack of timeStyle support.

**Comment by sinamics** [comment]
@siri10086 could you try to add your timezone as well. If the timezone is applied it will not use Intl.DateTimeFormat function at all. 
```yml
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  #live_mode: mse
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: True
  strftime_fmt: '%d.%m.%Y, %H:%M:%S'
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: America/Denver
````
