### ISSUE TITLE
ffmpeg proces is not running

### ISSUE THREAD

**Issue by imzenreally** [blakeblackshear/frigate#699]
this is driving me nuts - if this isn't the right forum please let me know - i have tried all the basic configs as well as the specific input_args for a reolink but try as i might i keep getting the following errors

i am running this from my home assistant server

```
frigate.video                  INFO    : Office: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Office: ffmpeg process is not running. exiting capture thread...
ffmpeg.Office.detect           ERROR   : rtsp://bunny:REDACTED@XXX.XXX.XXX.XXX:554/live: Invalid data found when processing input
```

here is my config - i kept it as simple as possible

```yaml
detectors:
  coral:
    type: cpu
mqtt:
  host: 192.168.0.121
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: REDACTED
ffmpeg: {}
cameras:
  Office:
    ffmpeg:
      inputs:
        - path: 'rtsp://bunny:REDACTED@XXX.XXX.XXX.XXX:554/live:'
          roles:
            - detect
    width: 1920
    height: 1080
```
