### ISSUE TITLE
[Config Support]: unable to exclude objects from detection, or set detection threshold for individual cameras

### ISSUE THREAD

**Issue by d3relict** [blakeblackshear/frigate#6995]
### Describe the problem you are having

I'm unable to exclude certain objects from specific camera detection, nor am I able to set the threshold for object types individually, causing a lot of false positives.

example:
![image](https://github.com/blakeblackshear/frigate/assets/10184571/ec202a66-7dbb-4df6-9fc2-4fccffe1c6c3)
another would be my child being detected as a cat, but i'd avoid posting photos of her publicly. :)

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt: [redacted]

go2rtc: [redacted]

cameras:
  Nursery:
    ffmpeg:
      input_args:
        - -flags
        - low_delay
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/nursery_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nursery_2
          roles:
            - detect
    zones:
      bed:
        coordinates: 0,0, 640,0, 640,360, 0,360
        objects:
          - person
        filters:
          person:
            threshold: 0.75
          cat:
            min_area: 1
            max_area: 1
            threshold: 1
    detect:
      width: 640
      height: 360
      fps: 15

objects:
  track:
    - person
    - car
    - cat
  filters:
    cat:
      min_score: 0.40
      threshold: 0.65
    
birdseye:
  enabled: false
```

### Relevant log output

```shell
none
```

### Frigate stats

```json
{"BackyardEast":{"camera_fps":10.0,"capture_pid":450,"detection_enabled":1,"detection_fps":27.2,"ffmpeg_pid":455,"pid":442,"process_fps":10.0,"skipped_fps":0.0},"Carport":{"camera_fps":10.0,"capture_pid":454,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":460,"pid":444,"process_fps":10.0,"skipped_fps":0.0},"Deck":{"camera_fps":10.0,"capture_pid":459,"detection_enabled":1,"detection_fps":0.6,"ffmpeg_pid":471,"pid":445,"process_fps":10.0,"skipped_fps":0.0},"Gate":{"camera_fps":10.0,"capture_pid":472,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":484,"pid":447,"process_fps":10.0,"skipped_fps":0.0},"Nursery":{"camera_fps":15.2,"capture_pid":482,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":54723,"pid":449,"process_fps":15.2,"skipped_fps":0.0},"cpu_usages":{"1":{"cpu":"0.0","mem":"0.0"},"103300":{"cpu":"0.0","mem":"0.1"},"103305":{"cpu":"0.3","mem":"0.3"},"103313":{"cpu":"0.0","mem":"0.3"},"110":{"cpu":"0.0","mem":"0.1"},"111":{"cpu":"3.7","mem":"22.5"},"119":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.2"},"135":{"cpu":"0.0","mem":"0.2"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.2"},"148":{"cpu":"0.0","mem":"0.2"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"169":{"cpu":"0.0","mem":"0.2"},"204":{"cpu":"0.0","mem":"1.3"},"24":{"cpu":"0.0","mem":"0.0"},"243":{"cpu":"0.0","mem":"0.2"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"430":{"cpu":"0.0","mem":"2.8"},"436":{"cpu":"0.3","mem":"0.3"},"437":{"cpu":"4.3","mem":"3.5"},"439":{"cpu":"1.3","mem":"3.5"},"442":{"cpu":"14.0","mem":"5.1"},"443":{"cpu":"0.0","mem":"0.3"},"444":{"cpu":"0.7","mem":"4.3"},"445":{"cpu":"1.7","mem":"4.1"},"446":{"cpu":"0.0","mem":"0.5"},"447":{"cpu":"0.7","mem":"4.7"},"448":{"cpu":"0.0","mem":"0.3"},"449":{"cpu":"1.0","mem":"4.1"},"450":{"cpu":"2.0","mem":"3.5"},"451":{"cpu":"0.0","mem":"0.4"},"454":{"cpu":"1.3","mem":"3.5"},"455":{"cpu":"5.7","mem":"1.9"},"458":{"cpu":"0.0","mem":"1.7"},"459":{"cpu":"1.7","mem":"3.5"},"460":{"cpu":"6.0","mem":"2.0"},"471":{"cpu":"6.0","mem":"2.1"},"472":{"cpu":"1.7","mem":"3.5"},"473":{"cpu":"0.3","mem":"1.1"},"481":{"cpu":"0.3","mem":"1.4"},"482":{"cpu":"1.3","mem":"3.6"},"484":{"cpu":"6.0","mem":"2.1"},"490":{"cpu":"0.0","mem":"1.2"},"495":{"cpu":"0.3","mem":"1.1"},"54699":{"cpu":"0.7","mem":"1.2"},"54708":{"cpu":"1.0","mem":"1.1"},"54723":{"cpu":"1.0","mem":"1.4"},"54725":{"cpu":"0.0","mem":"1.0"},"54726":{"cpu":"0.0","mem":"1.2"},"54727":{"cpu":"1.3","mem":"1.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"6.7","mem":"1.0"},"Tasks:":{"cpu":"stopped,","mem":"0.0"}},"detection_fps":27.8,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.73,"pid":437}},"service":{"last_updated":1688288777,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":258.0,"mount_type":"tmpfs","total":268.4,"used":10.4},"/media/frigate/clips":{"free":2466748.5,"mount_type":"fuse.mergerfs","total":8509726.0,"used":5610179.2},"/media/frigate/recordings":{"free":2466748.5,"mount_type":"fuse.mergerfs","total":8509726.0,"used":5610179.2},"/tmp/cache":{"free":520.1,"mount_type":"tmpfs","total":536.9,"used":16.8}},"temperatures":{},"uptime":62312,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
I see a number of issuers here in the config. 

1. Your input_args are very incomplete and that is overriding the default args that frigate needs, I'd highly suggest just removing that from the config entirely.
2. You are setting the threshold and other filters at the zone level which is wrong, you should be setting them at the `objects -> filters` level (globally or per camera).
3. Other than that, it is not clear what you mean by being unable to set it per camera.

**Comment by d3relict** [comment]
hey @NickM-27, thanks for the prompt reply.

1: i'll remove the input settings, this is a leftover from the pre-go2rtc version, this allowed me to have low latency over rtmp.

2: i was following the official documentation, which has a config file that defines the threshold on a zone level for a camera, and there are no other examples how to do for per-camera.
```
    zones:
      # Required: name of the zone
      # NOTE: This must be different than any camera names, but can match with another zone on another
      #       camera.
      front_steps:
        # Required: List of x,y coordinates to define the polygon of the zone.
        # NOTE: Presence in a zone is evaluated only based on the bottom center of the objects bounding box.
        coordinates: 545,1077,747,939,788,805
        # Optional: List of objects that can trigger this zone (default: all tracked objects)
        objects:
          - person
        # Optional: Zone level object filters.
        # NOTE: The global and camera filters are applied upstream.
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
```

3: this is what i mean: i failed to find a documentation example on how to set these per-camera. i'd like to achieve to be able to disable certain objects from detection on zone or camera level, for example, there is no need to find cats in my daughters bed, or to have a car detected on an elevated walkway.

can you please provide or point me to examples that help me achieve this?

**Comment by NickM-27** [comment]
Right but that still sets it at the zone level. All of the fields are override-able at the camera level, so it would be:

```yaml
cameras:
  your_camera:
    ffmpeg:
      ...
    objects:
      track:
        - car
      filters:
        car:
          min_area: 1000
          mask:
            - 1191,172,1493,181,1487,137,1195,135
```

**Comment by d3relict** [comment]
i'll make the proposed changes, thank you.
am i able to avoid looking for certain objects in certain zones?
the published config at https://docs.frigate.video/configuration/ seems to suggest this.

**Comment by NickM-27** [comment]
> am i able to avoid looking for certain objects in certain zones? the published config at https://docs.frigate.video/configuration/ seems to suggest this.

yes

**Comment by d3relict** [comment]
how? this is the part i also failed to set. as an example, i'd like to avoid detecting cats in the nursery. how can that be achieved?
as you can see i had this in my original config:
```
    zones:
      bed:
        coordinates: 0,0, 640,0, 640,360, 0,360
        objects:
          - person
        filters:
          person:
            threshold: 0.75
          cat:
            min_area: 1
            max_area: 1
            threshold: 1
```
the only objects present are 'person', but i still got false positives for 'cat', even after i set the min and max areas to 1.

**Comment by d3relict** [comment]
now i'm confused. i can avoid, but i should not?

> - am i able to avoid looking for certain objects in certain zones?
> - yes

> - you should not be putting these filters at the zone level

also, in the config, there is a single zone, which covers the entire frame, there is nothing outside it, and i was getting detections in the zone, not somewhere else.

can you please clarify?

**Comment by NickM-27** [comment]
if you don't want to detect `cat` on this camera at all then you should not have the object enabled in `object -> track`

> now i'm confused. i can avoid, but i should not?

you do this by simply setting what objects to track in the zone. Applying filters to `cat` for the zone is the wrong way to do this.

**Comment by d3relict** [comment]
but cat is not in the list of objects, and was still detected in the zone. the filter was a desperate attempt to get rid of false positives.
```
zones:
      bed:
        coordinates: 0,0, 640,0, 640,360, 0,360
        objects:
          - person
```
