### ISSUE TITLE
rmtp stream is black

### ISSUE THREAD

**Issue by clemi2408** [blakeblackshear/frigate#700]
Hi Frigate Team,

i am using

Image	blakeblackshear/frigate:0.8.1-aarch64@sha256:7cbf7430a97e1aec5585d83b7dff13832f49c6fa46569b0a5c42c8818985f0bc

And want to access my camera Stream via rtmp.

I use camera url:

rtmp://192.168.2.2/live/front_door

But if i load the url in vlc the video is just black.

Preview in webinterface working properly after using 0.8.1

Regards
Clem

**Comment by blakeblackshear** [comment]
Please provide the information requested in the issue template. Config, logs, etc

**Comment by clemi2408** [comment]
```
version: '3.6'
services:
  nvr01:
    container_name: nvr01
    depends_on:
     - "mqtt01"
    restart: always
    privileged: true
    image: blakeblackshear/frigate:0.8.1-aarch64
    extra_hosts:
     - "nvr:192.168.2.24"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/frigate/config:/config
      - ./data/frigate/clips:/media/frigate/clips
      - ./data/frigate/recordings:/media/frigate/recordings
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935'
    environment:
      FRIGATE_NVR_HOST: 'nvr'
      FRIGATE_NVR_PORT: '554'
      FRIGATE_NVR_USER: 'admin'
      FRIGATE_NVR_PASSWORD: 'xxxxx'
      FRIGATE_CAM1: 'h264Preview_01_sub'

  mqtt01:
    container_name: mqtt01
    restart: always
    privileged: true
    image: eclipse-mosquitto:2.0.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mqtt/messages:/mosquitto/messages
      - ./data/mqtt/log:/mosquitto/logging
      - ./data/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '1883:1883'
      - '9001:9001'
```

config.yml

```
mqtt:
  host: 192.168.2.2
  
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_NVR_USER}:{FRIGATE_NVR_PASSWORD}@{FRIGATE_NVR_HOST}:{FRIGATE_NVR_PORT}/{FRIGATE_CAM1}
          roles:
            - clips
            - rtmp
            - detect
    width: 640
    height: 352
    fps: 1
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
    snapshots:
      enabled: True
      timestamp: False
      crop: False
    zones:  
      zone_1_1:
        coordinates: 640,87,640,352,258,352,215,187,200,85,192,0

detectors:
  cpu1:
    type: cpu
    
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m     
  input_args:
    - -stimeout
    - '5000000'
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'

```
logger:
  default: info


sorry for the late response.

the url pattern rtmp://$host/live/$camName 
seems right.

<img width="969" alt="grafik" src="https://user-images.githubusercontent.com/35063751/107068213-9e3c0180-67e0-11eb-86b2-0dad21e293c2.png">
