### ISSUE TITLE
High CPU Usage on cameras with a lot of motion

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#7000]
On dev as of this morning, CPU usage is _much_ better for idle cameras. What surprises me is that on cameras with even a small amount of motion how much CPU usage goes up. It's not object detection - I have 4x corals, and they're all staying under 20ms inference speed (usually under 10ms). So my guess is it's either the object tracking code, or the motion region merging and prep-to-send-to-object-detection code. Given the recent mentions of avoid casts in numpy, I'm curious if similar optimizations are to be had in this section of the pipeline. See this `py-spy top` capture of a semi-active camera, run over 30-60s:

<img width="618" alt="Screenshot 2023-07-02 at 11 24 20 AM" src="https://github.com/blakeblackshear/frigate/assets/191320/05458d12-e010-42b0-b1a9-285dbace32b9">

Besides the obligatory wait at the top, there are several methods using a significant chunk of CPU above improved_motion.py.

**Comment by NickM-27** [comment]
to be clear, having corals does not mean the object detection is not using CPU, the regions still have to be resized to the model size and depending on what model you are running it may also need to have the pixel format changed as well.

**Comment by ccutrer** [comment]
Right. Indeed. And I'm not saying they're _has_ to be optimizations here. It could be as good as it's going to get. I've just been impressed with how much @blakeblackshear improved the motion detector, and was hoping he could at least take a look at the other parts of process_frames after motion detection, but before the IPC to the object detector (but also including the create_tensor_input) for similar optimizations.

Full flame graph attached. Seems like a significant chunk is in match_and_update in norfair_tracker.py, particularly frigate_distance function. 

![profile](https://github.com/blakeblackshear/frigate/assets/191320/798ccf49-41be-4ce8-be92-c3c5b507c212)

**Comment by NickM-27** [comment]
I was just wanting to clarify that the assumption coral == no cpu usage for object detection isn't necessarily accurate, lots of motion will potentially lead to lots of regions and that can be part of the equation.

**Comment by gigabyte-1000** [comment]
kindof off-topic but can we disable the "cpu is very slow 1077ms" message in the frigate ui (I know the cpu is very slow), it distracts from important messages like when a camera goes down.

![Image](https://github.com/user-attachments/assets/d8b780a8-5dfe-4eed-bb21-996c62f8b810)

**Comment by NickM-27** [comment]
With detection that slow your object detection is basically not functioning. There's a reason those messages are shown, we only show them when they indicate major problems.

**Comment by gigabyte-1000** [comment]
> With detection that slow your object detection is basically not functioning. There's a reason those messages are shown, we only show them when they indicate major problems.

I managed to get detection working very well during the day, around 90% accuracy, after properly setting up zones, motion masks, and object masks. Bounding boxes display correctly over people, and object tracking/lifespan features are functioning as expected.

I’m using the camera substreams for detections since the main 1080p stream produced black frames, but that’s not a big issue since substreams are typically used for this purpose anyway. Overall, I’m very satisfied with the results, especially across four cameras. CPU usage spikes to around 80% when an object snapshot is sent to the detector, but normally it stays in the idle range of 17–19% range when simply monitoring for motion.

From what I can tell, the system’s response time hovers near 900 ms (orange) and occasionally reaches 1000 ms (red). That’s still within an acceptable range — I haven’t noticed any negative impact on object detection performance, at least during daytime operation.

**Comment by NickM-27** [comment]
Your understanding is incorrect. At 1 second inference time you are going to have a high amount of skipped fps as even 5 detect fps for a single camera is not sustainable and frigate will skip frames and object tracking will not function well.

**Comment by gigabyte-1000** [comment]
> Your understanding is incorrect. At 1 second inference time you are going to have a high amount of skipped fps as even 5 detect fps for a single camera is not sustainable and frigate will skip frames and object tracking will not function well.

Sorry I mistyped, not 1000 ms, it's 100ms (0.1 second) to 200ms (0.2 second)

![Image](https://github.com/user-attachments/assets/ce79ccf2-9c69-41f8-9394-3ccf361b0846)

**Comment by AnotherRandomTech** [comment]
Seconding the above from @gigabyte-1000 . We attempted to run a system with multiple Google Corals via a PCIe card on a Dell PowerEdge T440. There are a total of approximately 90 cameras on the system with a dual CPU design.

Our worst offender for high motion events that was causing issues is a camera on a second story facing a large tree that caused multiple motion events from the debug view.
 
Setting a continued/motion only recording with a high motion threshold dropped our CPU use significantly for all our HikVision cameras. The motion events will also show up in the cameras timeline so you appear to still be able to scrub through and see events if needed.

<img width="698" height="664" alt="Image" src="https://github.com/user-attachments/assets/e904675d-31ad-4922-8cc2-21dd27659988" />

Recording Settings:
```
# Sets record Schedule. This records motion for 7 days
## Frigate will also delete recordings if the storage has less than 2 hours of record time
record:
  enabled: true
  expire_interval: 60 ## Reduces Disk IO load by waiting 60 minutes before removal
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 7
      mode: motion
  detections:
    retain:
      days: 7
      mode: motion
```

Camera Settings:
```
  E4000S01HIKCM111:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:asecurepassword@10.66.40.57:554/Streaming/channels/102
        roles:
        - detect
      - path: rtsp://admin:asecurepassword@10.66.40.57:554/Streaming/channels/101
        roles:
        - record
    motion:
      mask: 0,0,1,0,1,0.168,0,0.161
      threshold: 50
```
