### ISSUE TITLE
[Camera Support]: Audio in live stream

### ISSUE THREAD

**Issue by hmjgriffon1** [blakeblackshear/frigate#7001]
### Describe the problem you are having

Trying to get audio to work in webrtc. audio is working in MSE. Camera audio is set to AAC. 

I've tried adding "ffmpeg:rtsp_cam#audio=opus" and "ffmpeg:rtsp_cam#audio=pcmu" and "ffmpeg:rtsp_cam#audio=pcma" to the camera's go2rtc stream config as detailed here. https://docs.frigate.video/configuration/live/ no audio, speaker is grayed out in the video stream.

### Version

0.12.1-367D724

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  enabled: true
  host: 10.0.0.3 #Please replace with a valid mqtt broker
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: (redacted)
  password: (redacted)

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: objects
  restream: false

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 5
    post_capture: 10
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

go2rtc:
  streams:
    living_room:
      - ffmpeg:rtsp://admin:password@10.0.0.7:554/Streaming/Channels/101
      - "ffmpeg:living_room#audio=aac"
    living_room_sub:
      - ffmpeg:rtsp://admin:password@10.0.0.7:554/Streaming/Channels/102
      - "ffmpeg:living_room#audio=aac"
    office:
      - rtsp://admin:password@10.0.0.12:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    office_sub:
      - rtsp://admin:password@10.0.0.12:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
  webrtc:
    candidates:
      - 10.0.0.2:8555
      - stun:8555

cameras:
  living_room:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:password@10.0.0.7:554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - record 
        - path: rtsp://admin:password@10.0.0.7:554/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 4
    objects:
      track:
        - person
        - dog

  office:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://10.0.0.2:8554/office
          input_args: preset-rtsp-restream
          roles:
            - record 
        - path: rtsp://10.0.0.2:8554/office_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
```

### Relevant log output

```shell
no errors in the log.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":480,"width":704},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua  IPC-HDW5231R-Z
