### ISSUE TITLE
[Config Support]: Go2rtc log WRN [app] read config error="yaml: unmarshal errors:\n  line 41: cannot unmarshal !!map into string"

### ISSUE THREAD

**Issue by bubba925** [blakeblackshear/frigate#7002]
### Describe the problem you are having

go2rtc logs show a warning on line 41 and I cannot figure out what is causing the error. My config is a bit long as I am just starting with Frigate and have been learning as I go but everything seems to be working fine so I might just be able to ignore the warning? The error seems to stay on line 41 even if I add things above line 41.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: xxx
  port: 1883
  topic_prefix: frigate
  user: xxx
  password: 'xxx'
  stats_interval: 60
detectors:
  coral_pci:
    type: edgetpu
    device: pci
go2rtc:
  streams:
    reolink: 
      - http://xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx
      - "ffmpeg:reolink#audio=opus"
    reolink_sub: 
      - http://xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx
    kitchen:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:kitchen#audio=opus"
    kitchen_sub:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=2
    front_south:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_south#audio=opus"
    front_south_sub:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=2
    garage:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:garage#audio=opus"
    garage_sub:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=2
    front_north:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_north#audio=opus"
    front_north_sub:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=2
    backyard:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:backyard#audio=opus"
    backyard_sub:
      - rtsp://xxx:xxx@xxx:554/cam/realmonitor?channel=1&subtype=2
  webrtc:
    candidates:
      - xxx:8555
      - stun: 8555
snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones:
    - front_door
    - street_south
    - driveway_south
    - front_yard_south
    - street_north
    - driveway_north
    - front_yard_north
    - back_deck
    - back_yard
    - garage_area
  retain:
    default: 15
objects:
  filters:
    person:
      min_score: 0.6
      threshold: 0.8
      min_area: 300
cameras:
  doorbell:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxx:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:8554/reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          min_area: 500
    live:
      stream_name: reolink
    motion:
      mask:
        - 362,480,640,480,640,450,360,454
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        required_zones:
          - front_door
        retain:
          default: 15
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - person
          - dog
          - cat
          - car
    zones:
      front_door:
        coordinates: 640,274,573,295,518,278,479,290,471,180,538,234,640,146,640,0,302,0,0,0,0,480,640,480
        objects:
          - person
          - dog
          - cat
    mqtt:
      crop: false
      required_zones:
        - front_door
  kitchen:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxx:8554/kitchen?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:8554/kitchen_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 3
        mode: all
  front_south:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxx:8554/front_south?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:8554/front_south_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bird
      filters:
        person:
          min_area: 350
    zones:
      street_south:
        coordinates: 938,166,960,127,839,89,657,56,568,38,467,35,309,31,204,37,0,71,0,126,382,96,653,110
        objects:
          - person
          - dog
          - cat
          - bird
      driveway_south:
        coordinates: 419,720,0,720,0,174,399,154
        objects:
          - car
          - person
          - dog
          - cat
          - bird
      front_yard_south:
        coordinates: 407,144,391,345,398,428,1280,720,1280,431,1070,249,754,177
        objects:
          - car
          - person
          - dog
          - cat
          - bird
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        required_zones:
          - street_south
          - driveway_south
          - front_yard_south
        retain:
          default: 15
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - person
          - dog
          - cat
          - car
    mqtt:
      crop: false
      required_zones:
        - street_south
        - driveway_south
        - front_yard_south
  front_north:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxx:8554/front_north?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:8554/front_north_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bird
      filters:
        person:
          min_area: 350
    zones:
      street_north:
        coordinates: 535,80,918,98,1144,147,1135,129,1031,92,913,69,708,32,500,21,311,39,0,102,0,147,341,82
        objects:
          - person
          - dog
          - cat
          - bird
      driveway_north:
        coordinates: 658,720,1169,674,1132,569,1280,355,891,130,426,120
        objects:
          - car
          - person
          - dog
          - cat
          - bird
      front_yard_north:
        coordinates: 641,720,0,720,0,194,425,121
        objects:
          - car
          - person
          - dog
          - cat
          - bird
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        required_zones:
          - street_north
          - driveway_north
          - front_yard_north
        retain:
          default: 15
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - person
          - dog
          - cat
          - car
    mqtt:
      crop: false
      required_zones:
        - street_north
        - driveway_north
        - front_yard_north
  garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxx:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:8554/garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    zones:
      garage_area:
        coordinates: 1280,720,0,720,0,147,0,0,194,0,1280,0,1280,166
        objects:
          - person
          - cat
          - dog
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 15
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - person
          - dog
          - cat
  backyard:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxx:8554/backyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:8554/backyard_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bird
    zones:
      back_yard:
        coordinates: 1280,720,233,720,197,191,760,197,1280,340
        objects:
          - car
          - dog
          - person
          - cat
          - bird
      back_deck:
        coordinates: 189,0,658,0,961,0,1039,31,1019,183,658,121,196,101
        objects:
          - person
          - dog
          - cat
          - bird
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 15
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - person
          - dog
          - cat
          - car
birdseye:
  enabled: true
  mode: continuous
database:
  path: /config/frigate/frigate.db
```

### Relevant log output

```shell
2023-07-02 15:23:50.614436606  [INFO] Preparing go2rtc config...
2023-07-02 15:23:51.153024514  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-07-02 15:23:51.196707163  [INFO] Starting go2rtc...
2023-07-02 15:23:51.298145101  15:23:51.298 INF go2rtc version 1.2.0 linux/amd64
2023-07-02 15:23:51.298492658  15:23:51.298 INF [api] listen addr=:1984
2023-07-02 15:23:51.299002095  15:23:51.298 INF [rtsp] listen addr=:8554
2023-07-02 15:23:51.299514344  15:23:51.299 INF [srtp] listen addr=:8443
2023-07-02 15:23:51.299704882  15:23:51.299 WRN [app] read config error="yaml: unmarshal errors:\n  line 41: cannot unmarshal !!map into string"
2023-07-02 15:23:51.299813118  15:23:51.299 INF [webrtc] listen addr=:8555
2023-07-02 15:24:00.617177299  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe
