### ISSUE TITLE
[Config Support]: Nvidia + h265 + h264 for ffmpeg

### ISSUE THREAD

**Issue by agrieco** [blakeblackshear/frigate#7003]
### Describe the problem you are having

Previously I had my nvidia card working to do the heavy lifting of ffmpeg.   Along the way though this has stopped working and I'm getting ready to add a handful more cameras.

My environment is proxmox + frigate on a docker.  I'm certain this is working properly as I can execute the nvidia-smi command inside the frigate container and see the card (with no ffmpeg processes).  

My environment is complex in that I have both h264 and h265 cameras.

Can you please help clarify the appropriate config lines to have the nvidia do the ffmpeg processing.

### Version

0.12.1-367D724

### Frigate config file

```yaml
# yaml-language-server: $schema=http://<hass IP>:5000/api/config/schema

database:
  path: /db/frigate.db


logger:
  # Optional: default log level (default: shown below)
  default: debug

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-nvidia-h264 preset-nvidia-h265 preset-nvidia-mjpeg
#  output_args:
#     record: preset-record-generic-audio
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

mqtt:
  host: <hass IP>
  user: <myuser>
  password: <mypass>

rtmp:
  enabled: False

motion:
  threshold: 25
  contour_area: 30

record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 14

snapshots:
  enabled: True
  timestamp: True
  bounding_box: False
  crop: False
  height: 175
  retain:
    default: 10
    objects:
      person: 30

objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car


detectors:
  coral1:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    driveway: # <- for RTSP streams
      - rtsp://<credentials>@<camera ip>1:554//h265Preview_01_main # <- stream which supports video & aac audio
      - "ffmpeg:driveway#video=h264#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    driveway_sub:
      - rtsp://<credentials>@<camera ip>1:554//h264Preview_01_sub # <- stream which supports video & aac audio
      - "ffmpeg:driveway#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    backdeck: # <- for RTSP streams
      - rtsp://<credentials>@<camera ip>0:554//h265Preview_01_main # <- stream which supports video & aac audio
      - "ffmpeg:backdeck#video=h264#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    backdeck_sub:
      - rtsp://<credentials>@<camera ip>0:554//h264Preview_01_sub # <- stream which supports video & aac audio
      - "ffmpeg:backdeck#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    sideyard:
      - rtsp://<camera IP>:8554/temp
    frontyard:
      - rtsp://<camera IP>:8554/front-yard
    lakesideyard:
      - rtsp://<camera IP>:8554/lake-side-yard
  rtsp:
    listen: ":8554"    # RTSP Server TCP port, default - 8554
    #username: "admin"  # optional, default - disabled
    #password: "pass"   # optional, default - disabled
cameras:
  driveway:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
       width: 3840
       height: 2160
       fps: 10
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
  backdeck:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backdeck?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
       width: 3840
       height: 2160
       fps: 10
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

  FrontYard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          hwaccel_args: preset-nvidia-h264
          roles:
            - detect
            - record
    motion:
        threshold: 10
        contour_area: 25
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    detect:
      width: 1920
      height: 1080
      fps: 5

  SideYard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sideyard?video=copy
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    detect:
      width: 1920
      height: 1080
      fps: 5

  LakeFront:
    ffmpeg:
      inputs:
        - path: rtsp://<camera IP>:8554/lake-front
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1920
      height: 1080
      fps: 5

  LakeBack:
    ffmpeg:
      inputs:
        - path: rtsp://<camera IP>:8554/lake-back-yard
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1920
      height: 1080
      fps: 5

  Boat:
    ffmpeg:
      inputs:
        - path: rtsp://<camera IP>:8554/boat
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1920
      height: 1080
      fps: 5

  Lakesideyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lakesideyard
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
    motion:
        threshold: 10
        contour_area: 25
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    detect:
      width: 1920
      height: 1080
      fps: 5



  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://<camera IP>:8554/garage
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1920
      height: 1080
      fps: 5

  Kitchen-cam:
    ffmpeg:
      inputs:
        - path: rtsp://<camera IP>:8554/kitchen-cam
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
# nvidia-smi
Sun Jul  2 20:42:33 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P4            On   | 00000000:81:00.0 Off |                    0 |
| N/A   40C    P0    24W /  75W |   3285MiB /  7680MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
