### ISSUE TITLE
[Config Support]: Motion masks ignored now I am using go2rtc for stream ?

### ISSUE THREAD

**Issue by 2Belette** [blakeblackshear/frigate#7007]
### Describe the problem you are having

I am using motion masks to reduce where I want to track motions and this was working perfectly before I use go2rtc for the live stream.

I only modified / added the go2rtc for the streams and kept the rest similar so I don't understand why my motion masks are now ignored.

### Version

0.12.1

### Frigate config file

```yaml
record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 5
      mode: active_objects

go2rtc:
  streams:
    main_entrance:
        - rtsp://admin:blabla@10.10.10.1:554/media/video0

cameras:
  main_entrance:
    ffmpeg:
      inputs:
        - path: rtsp://admin:blabla@10.10.10.1:554/media/video0
          roles:
            - detect
    motion:
      mask:
        - 0,1162,803,951,1853,415,2050,377,2560,451,2560,0,0,0
```

### Relevant log output

```shell
Not applicable
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
