### ISSUE TITLE
FFMPEG hwaccel_args extra keys not allowed

### ISSUE THREAD

**Issue by SteveEdson** [blakeblackshear/frigate#701]
The following config:

```yaml
cameras:
  front:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
```

Results in the error:

```
frigate    | Error parsing config: extra keys not allowed @ data['cameras']['front']['ffmpeg']['hwaccel_args']
frigate    |  * Starting nginx nginx
frigate    |    ...done.
```

On Frigate `0.8.1`. I used the config example from here: https://blakeblackshear.github.io/frigate/configuration/optimizing

**Comment by blakeblackshear** [comment]
I'm guessing the part of your config immediately after this snippet is indented one level too far. Can you post more of your config?

**Comment by tapontikes** [comment]
Same error here, happened after I updated. Here's my config.

detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
mqtt:
  host: ''
  port: 1883
  user: ''
  password: '
ffmpeg: {}
cameras:
  floor2:
    ffmpeg:
      hwaccel_args:
        - '-hwaccel'
        - vaapi
        - '-hwaccel_device'
        - /dev/dri/renderD128
        - '-hwaccel_output_format'
        - yuv420p
      input: 'rtsp://'
    fps: 5
    snapshots:
      show_timestamp: false
      draw_zones: false
      draw_bounding_boxes: true
    objects:
      track:
        - person
web_port: 5000
save_clips:
  clips_dir: /media/frigate

**Comment by blakeblackshear** [comment]
@tapontikes your config is clearly from an old version. 0.8.0 had lots of breaking changes in the config. Please see the documentation.

**Comment by NearlCrews** [comment]
I'd rebuild the config from scratch if you're migrating from the 0.7.X to the 0.8.X builds. I went through the same and it took 15 minutes total. It's much easier than trying to convert the configuration.

**Comment by blakeblackshear** [comment]
@SteveEdson try moving those `hwaccel_args` to the global level rather than the camera level: https://blakeblackshear.github.io/frigate/configuration/index#ffmpeg

**Comment by jaburges** [comment]
Can you confirm this is correct, as based on the docs it looks correct, but i'm getting the same error @blakeblackshear 
```yaml
cameras:
  living_room:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid     
      inputs:
        - path: rtsp://some.stream
          roles:
            - record
            - rtmp
```

**Comment by blakeblackshear** [comment]
Move them under the input entries. The docs are inaccurate on camera level params. The next version fixes this.

**Comment by jaburges** [comment]
ah cool, thank you :)

**Comment by jaburges** [comment]
hmmm - that doesnt seem to work either?

I've tried:
```yaml
cameras:
  living_room:
    ffmpeg:     
      inputs:
        - path: rtsp://some.stream
          roles:
            - record
            - rtmp
          input_args:
            - -c:v
            - h264_cuvid
```
and
```yaml
cameras:
  living_room:
    ffmpeg:     
      inputs:
        - path: rtsp://some.stream
          roles:
            - record
            - rtmp
      input_args:
        - -c:v
        - h264_cuvid
```

**Comment by blakeblackshear** [comment]
The first one of those two should work. What error message are you getting?

**Comment by jaburges** [comment]
some progress - but seeing this:
```Error parsing config: extra keys not allowed @ data['cameras']['driveway']['ffmpeg']['inputs'][0]['output_args']```

```yaml
  driveway:
    ffmpeg:   
      inputs:
        - path: rtsp://stream1
          roles:
            - rtmp 
          input_args:
            - -c:v
            - h264_cuvid    
          output_args:          
            - -filter:v
            - fps=fps=5                           
        - path: rtsp://stream2
          roles:
            - detect
            - clips   
```

**Comment by jaburges** [comment]
also (committing the cardinal sin of adding another question) but with the nvidia docker, do I not need to specify hwaccels?

**Comment by blakeblackshear** [comment]
I see. That config is different than what you posted. `output_args` are allowed at the camera level. They can't be specified at the input level because they are role specific. The defaults are [here](https://blakeblackshear.github.io/frigate/configuration/index#ffmpeg)

Try this (i guessed at your desired output args for the rtmp role, but these may not work):

```yaml
  driveway:
    ffmpeg:   
      inputs:
        - path: rtsp://stream1
          roles:
            - rtmp 
          input_args:
            - -c:v
            - h264_cuvid                         
        - path: rtsp://stream2
          roles:
            - detect
            - clips
      output_args:
        rtmp: -f flv -filter:v fps=fps=5
```      

> also (committing the cardinal sin of adding another question) but with the nvidia docker, do I not need to specify hwaccels?

You do need to specify hwaccels so ffmpeg knows to use the GPU.

**Comment by jaburges** [comment]
Ah my fault, i read [this](https://blakeblackshear.github.io/frigate/configuration/nvdec) wrong: 
```yaml
  output_args:
    - -filter:v
    - fps=fps=5
```    
Think i need to more reading on FFMPEG! 

right now
```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - cuda
```   
doesn't seem to invoke the GPU
``ffmpeg -hwaccels`` shows `cuda`
