### ISSUE TITLE
[Support]: Camera Issues

### ISSUE THREAD

**Issue by Infernoken76** [blakeblackshear/frigate#7015]
### Describe the problem you are having

Full crash of streams incoming to Frigate on Home Assistant OS...
And cannot get the streams to work anymore in Frigate, tried everything, only a full system reboot solved the issue...

- Reloading frigate did not solve the problem...
- Reloading Home Assistant did not solve the problem...
- Only a full reboot of my system  (Intel NUC running HAOS) did work...

All streams could still be viewed in Home Assistant Devices 

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.231
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: **********
  password: **********
  stats_interval: 60

#detectors:
#  cpu1:
#    type: cpu

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

environment_vars:
  LIBVA_DRIVER_NAME: iHD

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: True
  mode: continuous
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720

cameras:
  dahua:
    ffmpeg:
      inputs:
        - path: rtsp://admin:**********@192.168.1.22:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://admin:**********@192.168.1.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    record: 
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 704,0,704,160,515,125,235,125,0,185,0,0
        - 614,205,546,113,205,113,121,205
    detect:
      width: 704 
      height: 576 
      fps: 7
    snapshots:
      enabled: True
      retain:
        default: 21
    objects:
      track:
        - person
        - car
  YCAM:
    ffmpeg:
      inputs:
        - path: rtsp://admin:**********@192.168.1.20/live/1/h264.sdp
          roles:
            - detect
        - path: rtsp://admin:**********@192.168.1.20/live/0/h264.sdp
          roles:
            - record
    record: 
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 300,0,300,30,0,30,0,0
    detect:
      width: 640 
      height: 360 
      fps: 6
    snapshots:
      enabled: True
      retain:
        default: 21
    objects:
      track:
        - person
  Reolink1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:**********@192.168.1.23:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:**********@192.168.1.23:554/h264Preview_01_main
          roles:
            - record
    record: 
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 640,0,640,30,435,30,435,0
    detect:
      width: 640 
      height: 360 
      fps: 7
    snapshots:
      enabled: True
      retain:
        default: 21
    objects:
      track:
        - person
  Reolink2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:**********@192.168.1.24:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:**********@192.168.1.24:554/h264Preview_01_main
          roles:
            - record
    record: 
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 640,0,640,30,435,30,435,0
    detect:
      width: 640 
      height: 360 
      fps: 7
    snapshots:
      enabled: True
      retain:
        default: 21
    objects:
      track:
        - person
  Reolink3:
    ffmpeg:
      inputs:
        - path: rtsp://admin:**********@192.168.1.25:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:**********@192.168.1.25:554/h264Preview_01_main
          roles:
            - record
    record: 
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 640,0,640,30,435,30,435,0
    detect:
      width: 640 
      height: 360 
      fps: 7
    snapshots:
      enabled: True
      retain:
        default: 21
    objects:
      track:
        - person
  Reolink4:
    ffmpeg:
      inputs:
        - path: rtsp://admin:**********@192.168.1.26:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:**********@192.168.1.26:554/h264Preview_01_main
          roles:
            - record
    record: 
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 640,0,640,30,435,30,435,0
    detect:
      width: 640 
      height: 360 
      fps: 7
    snapshots:
      enabled: True
      retain:
        default: 21
    objects:
      track:
        - person
```

### Relevant log output

```shell

WRONG LOG FILE...  WILL NEED TO REPOST IF ISSUE REOCCURS
```

### FFprobe output from your camera

```shell
DAHUA CAMERA:

[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"7/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"857:482","height":576,"width":704},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMA-law/G.711A-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","display_aspect_ratio":"857:482","height":2160,"width":3840},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMA-law/G.711A-law"}]}}]

YCAM CAMERA:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]

REOLINK CAMERA'S: (4 in total)

[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"7/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

DAHUA IPC-HDW4831EM-ASE, Y-CAM CUBE 1080P, REOLINK E1 PRO
