### ISSUE TITLE
[Camera Support]: Issues With Uniview Camera

### ISSUE THREAD

**Issue by justinmomnium** [blakeblackshear/frigate#7031]
### Describe the problem you are having

I am unable to get Uniview camera recording and clips to play in iOS. They will work fine on Chrome on Windows, haven't been able to test on Android.

The error you get is either a blank playback window, or "The media playback was aborted due to a corruption problem or because the media used features your browser did not support".

I've played with all the settings I can think of, including changing the camera output to a low bitrate, which would have some success but not all the time.

I'm unable to test it on Android.

Using one of the configurations below (global ffmpeg settings) I was able to get clips to 'play', but recorded clips were 20 seconds long but would only have say, 2-3 seconds of content (i.e. at 15 seconds in, the timestamp on the video has only increased by 1 second).

It works fine with an RTSP Stream from a Eufy camera. I don't know why - I've compared bitrates/codecs etc on VLC RTSP Streaming as well, and no dice. The only difference I can see in FFPROBE output is that the Eufy camera reports the resolution of the stream, and the Uniview cameras do not. I've also attached mediainfo comparisons.

Also, I haven't got any new events to play, but they were working through Home Assistant push notifications, as in, when they would open the browser the clip would play. But that's proxied from Frigate via HAS, not Frigate direct. It's important to note that playback of recordings or clips in the Home Assistant app, or browser, do not work - it is only the direct links from HAS that bypass the HAS App/Frigate app that work on IOS.

Broken Camera:
```
root@228a935b530f:/media/frigate/recordings/2023-07-04/13# mediainfo Camera1/09.46.mp4
General
Complete name                            : Camera1/09.46.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 1 009 KiB
Duration                                 : 9 s 974 ms
Overall bit rate                         : 829 kb/s
Movie name                               : VCP IPC Realtime stream
Writing application                      : Lavf59.27.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 9 s 974 ms
Bit rate                                 : 827 kb/s
Width                                    : 2 592 pixels
Height                                   : 1 944 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Variable
Frame rate                               : 15.039 FPS
Minimum frame rate                       : 1.883 FPS
Maximum frame rate                       : 111.304 FPS
Original frame rate                      : 15.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.011
Stream size                              : 1 006 KiB (100%)
Color range                              : Full
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC
```

Working camera:
```
root@228a935b530f:/media/frigate/recordings/2023-07-04/13# mediainfo Camera3/09.45.mp4
General
Complete name                            : Camera3/09.45.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 461 KiB
Duration                                 : 11 s 118 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 340 kb/s
Movie name                               : H.264 Video,leco stream
Writing application                      : Lavf59.27.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 11 s 118 ms
Bit rate mode                            : Variable
Bit rate                                 : 338 kb/s
Maximum bit rate                         : 1 111 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 17.450 FPS
Minimum frame rate                       : 9.121 FPS
Maximum frame rate                       : 15 360.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.009
Stream size                              : 458 KiB (99%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC
```

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.114
  port: 1883
  user: mqtt
  password: mqtt

cameras:
  Camera1: 
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.66:554/media/video0
          roles:
            - record
            - detect
    detect:
      enabled: True 
      width: 1920 
      height: 1080
    objects:
      track:
        - person
        - car
        - truck
        - dog
        - cat      
  Camera2: 
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.231:554/media/video0
          roles:
            - record
            - detect      
      #output_args: 
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an -c:v libx264 -profile:v high -level 4.2
    detect:
      enabled: True 
      width: 1920 
      height: 1080
    objects:
      track:
        - person
        - car
        - truck
        - dog
        - cat     
  # Garage: 
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.221:554/media/video1
  #         roles:
  #           - record      
  #       - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.221:554/media/video2
  #         roles:
  #           - detect      
  #   detect:
  #     enabled: True 
  #     width: 720
  #     height: 576 
  #   objects:
  #     track:
  #       - person
  #       - car
  #       - truck
  #       - dog
  #       - cat     
  # Backyard: 
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.131:554/media/video1
  #         roles:
  #           - record      
  #       - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.131:554/media/video2
  #         roles:
  #           - detect      
  #   detect:
  #     enabled: True 
  #     width: 3840
  #     height: 2160 
  #   objects:
  #     track:
  #       - person
  #       - car
  #       - truck
  #       - dog
  #       - cat      
  # Under_House: 
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.218:554/media/video1
  #         roles:
  #           - record      
  #       - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.1.218:554/media/video2
  #         roles:
  #           - detect      
  #   detect:
  #     enabled: True 
  #     width: 3840
  #     height: 2160 
  #   objects:
  #     track:
  #       - person
  #       - car
  #       - truck
  #       - dog
  #       - cat        
  Camera3: 
    ffmpeg:
      inputs:
        - path: rtsp://admin@192.168.1.228/live0
          roles:
            #- detect
            - record
    detect:
      enabled: False 
      width: 1920 
      height: 1080 
    objects:
      track:
        - person
        - dog          
record:
  enabled: True
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 5
      mode: active_objects
      objects:
        person: 5
        car: 5
        dog: 5                

#ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  #global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  #hwaccel_args: []
  # Optional: global input args (default: shown below)
  #input_args: -c copy -f flv
  # Optional: global output args
  #output_args:
    # Optional: output args for detect streams (default: shown below)
    #detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    #record: -f segment -segment_time 10 -strftime 1 -vf "scale=2592:1944"
    #record: -segment_time 10 -vf "scale=2592:1944"
    #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an -c:v copy
```

### Relevant log output

```shell
CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:49.549530473  172.18.0.1 - - [04/Jul/2023:13:23:49 +0000] "GET /recording/Camera1/2023-07-04/23 HTTP/1.1" 200 6641 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:49.631796792  172.18.0.1 - - [04/Jul/2023:13:23:49 +0000] "GET /api/config HTTP/1.1" 200 10777 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:49.759326254  172.18.0.1 - - [04/Jul/2023:13:23:49 +0000] "GET /api/Camera1/recordings?before=1688479199&after=1688475600 HTTP/1.1" 200 2179 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:49.763072799  172.18.0.1 - - [04/Jul/2023:13:23:49 +0000] "GET /api/Camera1/recordings/summary?timezone=Australia%2FBrisbane HTTP/1.1" 200 107 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:49.845894518  172.18.0.1 - - [04/Jul/2023:13:23:49 +0000] "GET /api/events?before=1688479199&after=1688392800&camera=Camera1&has_clip=1&include_thumbnails=0&limit=5000 HTTP/1.1" 200 3 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:49.869557537  172.18.0.1 - - [04/Jul/2023:13:23:49 +0000] "GET /vod/2023-07/04/23/Camera1/Australia,Brisbane/master.m3u8 HTTP/1.1" 200 163 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:50.018081497  172.18.0.1 - - [04/Jul/2023:13:23:50 +0000] "GET /vod/2023-07/04/23/Camera1/Australia,Brisbane/index-v1.m3u8 HTTP/1.1" 200 249 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:54.783189055  172.18.0.1 - - [04/Jul/2023:13:23:54 +0000] "GET /vod/2023-07/04/23/Camera1/Australia,Brisbane/seg-1-v1.ts HTTP/1.1" 200 1008056 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:54.931740879  172.18.0.1 - - [04/Jul/2023:13:23:54 +0000] "GET /vod/2023-07/04/23/Camera1/Australia,Brisbane/master.m3u8 HTTP/1.1" 200 165 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:54.981108724  172.18.0.1 - - [04/Jul/2023:13:23:54 +0000] "GET /vod/2023-07/04/23/Camera1/Australia,Brisbane/index-v1.m3u8 HTTP/1.1" 200 253 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:55.132262654  172.18.0.1 - - [04/Jul/2023:13:23:55 +0000] "GET /vod/2023-07/04/23/Camera1/Australia,Brisbane/seg-1-v1.ts HTTP/1.1" 200 1008056 "http://192.168.1.233:5000/recording/Camera1/2023-07-04/23" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1" "-"
frigate  | 2023-07-04 13:23:56.050409151  172.18.0.1 - - [04/Jul/2023:13:23:56 +0000] "GET /api/stats HTTP/1.1" 200 2685 "-" "HomeAssistant/2023.6.3 aiohttp/3.8.4 Python/3.11" "-"
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":0,"width":0},{"avg_frame_rate":"0/0"}]}}]
```

### Frigate stats

```json
{"Camera1":{"camera_fps":5.1,"capture_pid":300,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":313,"pid":295,"process_fps":5.1,"skipped_fps":0.0},"Camera2":{"camera_fps":4.4,"capture_pid":304,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":315,"pid":297,"process_fps":4.4,"skipped_fps":0.0},"Camera3":{"camera_fps":5.0,"capture_pid":306,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":311,"pid":298,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.0"},"113":{"cpu":"1.3","mem":"2.2"},"119":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.2"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"283":{"cpu":"0.0","mem":"1.0"},"289":{"cpu":"0.3","mem":"0.1"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.0","mem":"1.3"},"291":{"cpu":"1.3","mem":"1.2"},"295":{"cpu":"0.3","mem":"1.2"},"296":{"cpu":"0.0","mem":"0.2"},"297":{"cpu":"1.0","mem":"1.2"},"298":{"cpu":"0.3","mem":"1.2"},"299":{"cpu":"0.0","mem":"0.2"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"2.0","mem":"1.2"},"301":{"cpu":"0.0","mem":"0.2"},"304":{"cpu":"2.3","mem":"1.2"},"306":{"cpu":"2.0","mem":"1.2"},"31":{"cpu":"0.0","mem":"0.0"},"311":{"cpu":"5.0","mem":"0.8"},"313":{"cpu":"29.7","mem":"1.0"},"314":{"cpu":"0.0","mem":"0.3"},"315":{"cpu":"328.7","mem":"16.5"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"693":{"cpu":"0.0","mem":"0.0"},"718":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"83":{"cpu":"0.0","mem":"0.0"},"91":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"4751.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"6.28,"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":240.42,"pid":290}},"service":{"last_updated":1688477071,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":4284.4,"mount_type":"tmpfs","total":4295.0,"used":10.6},"/media/frigate/clips":{"free":422761.7,"mount_type":"9p","total":511352.8,"used":88591.1},"/media/frigate/recordings":{"free":422761.7,"mount_type":"9p","total":511352.8,"used":88591.1},"/tmp/cache":{"free":992.9,"mount_type":"tmpfs","total":1000.0,"used":7.1}},"temperatures":{},"uptime":235,"version":"0.12.1-367d724"}}
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Uniview - Various

### Any other information that may be helpful

I'll pay for you to help me fix it lol.
