### ISSUE TITLE
[Config Support]: Changing DB location

### ISSUE THREAD

**Issue by hmjgriffon1** [blakeblackshear/frigate#7032]
### Describe the problem you are having

trying to change the frigate.db location to SSD. I followed the document here https://docs.frigate.video/frigate/installation/#common-docker-compose-storage-configurations
not sure what I am doing wrong.

### Version

0.12.1-367D724

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m>
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hmjgriffon/frigate/config/config.yml:/config/config.yml
      - /media/frigate:/media/frigate
      - /home/hmjgriffon/frigate:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    database:
      path: /db/frigate.db
```

### Relevant log output

```shell
root@frigate:/home/hmjgriffon/frigate# docker-compose -f frigate.yml up
ERROR: The Compose file './frigate.yml' is invalid because:
Unsupported config option for services.frigate: 'database'
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
