### ISSUE TITLE
[Config Support]: Object not registering as in zone

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#7044]
### Describe the problem you are having

I think this is only in 0.13, but I've noticed I have a _lot_ of events with None zones, but that are clearly within a zone. An example event:
![snapshot-1688592783 340751-jssqkz](https://github.com/blakeblackshear/frigate/assets/191320/1fe6f39d-32cd-4138-aeb9-d242e4e2c891)
The zones for this camera:
![latest](https://github.com/blakeblackshear/frigate/assets/191320/d91abb1d-5b43-43fa-b1e8-45f9edcab324)
(actual config below)

### Version

0.13.0-83EDF95

### Frigate config file

```yaml
detect:
  width: 1280
  height: 720
  fps: 6
  max_disappeared: 18
  stationary:
    interval: 12

objects:
  track:
    - person
    - dog
    - cat

cameras:
  entry:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entry
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entry_third
          roles:
            - detect
    motion:
      mask:
        - 360,52,421,52,421,72,360,72 # timestamp
    zones:
      entry_zone:
        coordinates: 846,720,1147,416,937,218,722,62,246,295,452,720
      great_zone:
        coordinates: 134,68,457,720,150,720
      porch_zone:
        coordinates: 754,0,1148,0,1258,70,1105,339,941,201,740,66
    objects:
      filters:
        cat:
          max_area: 15000
        dog:
          max_area: 20000
        person:
          min_area: 2500
          max_area: 80000
          mask:
            - 287,354,234,398,221,348
            - 1280,247,1280,720,880,720 # rug wall (catches false positives with bench)
```

### Relevant log output

```shell
(none)
```

### Frigate stats

https://gist.github.com/ccutrer/dfe6806ce31c1aba1ac917381603dcca

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

I have several examples with several cameras. But I also have plenty of examples of events that _are_ properly tagged as in that zone (i.e. 
![snapshot-1688592868 084358-nyyuw7](https://github.com/blakeblackshear/frigate/assets/191320/df196a47-167b-468e-b85f-300a5f91c235). Am I misunderstanding some logic that an object will show up as an event immediately, but requires some number of frames in a certain zone before being assigned part of that zone?
