### ISSUE TITLE
[Support]: Sub_Label not updating

### ISSUE THREAD

**Issue by AriaGen** [blakeblackshear/frigate#7045]
### Describe the problem you are having

So, I understand that this may not be a frigate issue, but I can't seem to get double-take to update the sub_label, I've tried various config's for double-take and understand that the original repository has been abandoned. I believe I found a command I could run to manually test but that doesn't seem to get me anywhere. So I'm wondering if it's something to do with my frigate setup.

TIA, for any advise to point me in the right direction.

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci
mqtt:
  enabled: True
  host: 192.168.1.250
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: Schooter@13
  stats_interval: 30
#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - qsv
#    - -qsv_device
#    - /dev/dri/renderD128

cameras:
  Front_Door_Frigate: 
    ffmpeg:
        inputs:
        - path: rtsp://admin:Scooter03@192.168.1.250:8554/9c76133b06ef_live
          roles:
            - detect
        - path: rtsp://admin:Scooter03@192.168.1.250:8554/9c76133b06ef_live
          roles:
            - rtmp
        - path: rtsp://admin:Scooter03@192.168.1.250:8554/9c76133b06ef_live
          roles:
            - record
        output_args:
          record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 30
    objects:
      track:
        - person
      #  - car
      filters:
        person:
           min_area: 20000
           max_area: 400000
           threshold: 0.65
        car:
           min_area: 200000
           max_area: 500000
           threshold: 0.65
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        objects:
          - person
        required_zones:
          - driveway_door_zone
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 3
      required_zones:
        - driveway_door_zone
#    motion:
#      mask:
#        - 1280,0,1280,720,1122,720,1059,524,970,565,671,252,577,145,759,0
#        - 0,720,0,0,524,0
    zones:
      driveway_door_zone:
         coordinates: 0,1080,1540,1080,1523,839,1134,838,377,743,0,892
         objects:
           - person
          #ķ - car
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
  Driveway_Frigate: 
    ffmpeg:
        inputs:
        - path: rtsp://Frigate:Frigate01@192.168.1.200:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://Frigate:Frigate01@192.168.1.200:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
        - path: rtsp://Frigate:Frigate01@192.168.1.200:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 24
    objects:
      track:
        - person
        - umbrella
        - bicycle
      #  - car
      filters:
        person:
           min_area: 5000
           max_area: 300000
           threshold: 0.65
        umbrella:
           min_area: 5000
           max_area: 400000
           threshold: 0.65
        bicycle:
           min_area: 5000
           max_area: 400000
           threshold: 0.65
        car:
           min_area: 2000
           max_area: 500000
           threshold: 0.50
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        objects:
          - person
          - umbrella
          - bicycle
        required_zones:
          - driveway_zone
          - pathway_zone
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 3
      required_zones:
        - driveway_zone
        - pathway_zone
#    motion:
#      mask:
#        - 1280,0,1280,720,1122,720,1059,524,970,565,671,252,577,145,759,0
#        - 0,720,0,0,524,0
    zones:
      driveway_zone:
         coordinates: 101,677,903,687,891,614,634,388,566,268,408,126
         objects:
           - person
          # - car
      pathway_zone:
         coordinates: 692,0,1082,418,1049,496,969,519,489,0
         objects:
           - person
           - bicycle
      driveway_entrance_zone:
         coordinates: 617,198,597,261,435,138,479,72
        # objects:
        #   - car
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

  Hallway_Frigate: 
    ffmpeg:
        inputs:
        - path: rtsp://admin:Scooter03@192.168.1.250:8554/54e019a903b0_live
          roles:
            - detect
        - path: rtsp://admin:Scooter03@192.168.1.250:8554/54e019a903b0_live
          roles:
            - rtmp
        - path: rtsp://admin:Scooter03@192.168.1.250:8554/54e019a903b0_live
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 30
    objects:
      track:
        - cat
      filters:
        cat:
           min_area: 10000
           max_area: 20000
           threshold: 0.65
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
      events:
        objects:
          - cat
        required_zones:
          - hallway_zone
        retain:
          default: 10
          mode: active_objects
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 3
      required_zones:
        - hallway_zone
    zones:
      hallway_zone:
         coordinates: 571,1080,1232,1080,797,747,680,383,499,397
         #objects:
         #  - cat
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

# Optional: birdseye configuration
birdseye:
  enabled: True
  restream: True
  width: 1280 
  height: 720
  quality: 1
  mode: objects
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"Driveway_Frigate":{"camera_fps":24.0,"capture_pid":311,"detection_enabled":1,"detection_fps":10.4,"ffmpeg_pid":319,"pid":297,"process_fps":24.0,"skipped_fps":0.0},"Front_Door_Frigate":{"camera_fps":29.9,"capture_pid":309,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1060,"pid":295,"process_fps":29.9,"skipped_fps":0.0},"Hallway_Frigate":{"camera_fps":30.1,"capture_pid":313,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1194,"pid":308,"process_fps":30.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"0.0","mem":"0.0"},"1060":{"cpu":"12.0","mem":"0.6"},"109":{"cpu":"5.0","mem":"1.3"},"119":{"cpu":"0.0","mem":"0.1"},"1194":{"cpu":"30.9","mem":"0.6"},"132":{"cpu":"0.0","mem":"0.0"},"133":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"1604":{"cpu":"0.0","mem":"0.0"},"1608":{"cpu":"0.3","mem":"0.0"},"1612":{"cpu":"0.3","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"0.7"},"288":{"cpu":"0.7","mem":"0.1"},"289":{"cpu":"0.3","mem":"0.9"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"6.3","mem":"0.8"},"294":{"cpu":"0.0","mem":"0.1"},"295":{"cpu":"3.7","mem":"0.8"},"297":{"cpu":"2.7","mem":"0.8"},"30":{"cpu":"0.0","mem":"0.0"},"308":{"cpu":"4.0","mem":"0.8"},"309":{"cpu":"14.0","mem":"0.8"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"0.0","mem":"0.1"},"311":{"cpu":"5.6","mem":"0.7"},"312":{"cpu":"0.0","mem":"0.1"},"313":{"cpu":"14.0","mem":"0.8"},"319":{"cpu":"17.6","mem":"0.3"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"0.3","mem":"0.3"},"332":{"cpu":"0.3","mem":"0.1"},"335":{"cpu":"3.7","mem":"0.2"},"338":{"cpu":"0.7","mem":"0.2"},"40":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"0.0","mem":"0.1"},"88":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"3256.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":10.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.37,"pid":289}},"service":{"last_updated":1688594552,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":255.4,"mount_type":"tmpfs","total":268.4,"used":13.0},"/media/frigate/clips":{"free":478044.8,"mount_type":"fuse.shfs","total":999716.5,"used":521671.6},"/media/frigate/recordings":{"free":478044.8,"mount_type":"fuse.shfs","total":999716.5,"used":521671.6},"/tmp/cache":{"free":96.4,"mount_type":"tmpfs","total":100.0,"used":3.6}},"temperatures":{"apex_0":63.3},"uptime":1124,"version":"0.12.1-367d724"}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Amcrest
