### ISSUE TITLE
[Bug]: "Mask & Zone creator" doesn't work

### ISSUE THREAD

**Issue by TheTerrasque** [blakeblackshear/frigate#7050]
### Describe the problem you are having

When I start clicking the image in Mask & Zone creator nothing happens. In the browser console there's an error. 

Tested on Chrome, Firefox and Edge (last is without any browser addons)

### Version

Frigate (0.12.1-367d724) - Docker

### Frigate config file

```yaml
mqtt:
  host: xxx
  user: xxx
  password: xxx
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://Camera2/stream2
          roles:
            - detect
        - path: rtsp://Camera2/stream1
          roles:
            - record
  catdoor:
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
    ffmpeg:
      inputs:
        - path: rtsp://Camera1/stream2
          roles:
            - detect
            - record
detectors:
  tensorrt:
    type: tensorrt
    device: 0 
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
record:
  enabled: True

objects:
  track:
    - person
    - cat
    - car

detect:
  width: 640
  height: 360
  stationary:
    interval: 10

motion:
  contour_area: 30
  threshold: 40
```

### Relevant log output

```shell
Chrome & Edge browser console:

CameraMap-0e4b28dd.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'reduce')
    at Object.clickfalse (CameraMap-0e4b28dd.js:14:459)
    at HTMLDivElement.Gn (index-40e1e50b.js:1:4930)

Firefox browser console:

Uncaught TypeError: e is undefined  CameraMap-0e4b28dd.js:14:457
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x360
FPS: 15/1

Audio:

Codec: PCM A-law / G.711 A-law
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo C200
