### ISSUE TITLE
[Support]: Docker portainer: No space left on device

### ISSUE THREAD

**Issue by hardtosay123** [blakeblackshear/frigate#7056]
### Describe the problem you are having

The frigate that i am running in Orange Pi 5B armbian ubuntu without using `armnn` or `rknpu2`. Because i do not know how to implement `armnn` or `rknpu2`.

The below is the docker compose using portainer:
```yml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "117mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/toshiba1tb/cctv/gdrive/config.yml:/config/config.yml
      - /mnt/toshiba1tb/cctv/gdrive/frigate:/media/frigate
      - /mnt/toshiba1tb/cctv/gdrive/frigate-db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
``` 

The mount point of `/mnt/toshiba1tb` is a toshiba's HDD, no a SSD.

Normally it will run without error, all the allday recording and detected events will be saved. If occurs no space left on the device will be resulting the detected events will not be saved but the allday recordings will remain to be saved.

How i solve the `OSError: [Errno 28] No space left on device: '/media/frigate/clips/Home-1688658942.390635-0xn22b.jpg'` error? Because i need the detected events to be continued working and save the events.

If want some more information, ask me to provide that. thank you~

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 10.8.0.1
  port: 1883
  user: ******
  password: *******

detectors:
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2

database:
  path: /db/frigate.db

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 16
  mode: continuous

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 10
    threshold: 50

objects:
  track:
    - person

record:
  enabled: True
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: motion
      objects:
        person: 10

snapshots:
  enabled: True
  retain:
    default: 10
    objects:
      person: 10

rtmp:
  enabled: False

# go2rtc:
  # streams:
    # Garage:
      # - "ffmpeg:rtsp://******:*******@192.168.0.102:554"
    # Home:
      # - "ffmpeg:rtsp://******:*******@192.168.0.104:554"
  #   Garage_Sub:
  #     - "ffmpeg:rtsp://******:*******@192.168.0.102:554/H.264#video=h264#audio=opus"
  #   Home_Sub:
  #     - "ffmpeg:rtsp://******:*******@192.168.0.104:554/H.264#video=h264#audio=opus"
  # webrtc:
  #   candidates:
  #     - 192.168.0.120:8555
  #     - stun:8555

timestamp_style:
  position: "bl"
  format: "%Y-%m-%d %H:%M:%S"

cameras:
  Garage:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://******:******@192.168.0.102:554
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
        # - path: rtsp://127.0.0.1:8554/Garage_Sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
        - cat
        - dog
        - bus
    record:
      enabled: True
      events:
        objects:
          - person
          - car
          - motorcycle
          - bicycle
          - cat
          - dog
          - bus
        retain:
          default: 10
          mode: motion
          objects:
            person: 10
            car: 10
            motorcycle: 10
            bicycle: 10
            cat: 10
            dog: 10
            bus: 10
    snapshots:
      enabled: True
      retain:
        default: 10
        objects:
          person: 10
          car: 10
          motorcycle: 10
          bicycle: 10
          cat: 10
          dog: 10
          bus: 10
    ui:
      order: 0
      dashboard: True
    live:
      stream_name: Garage
  Home:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://******:******@192.168.0.104:554
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
        # - path: rtsp://127.0.0.1:8554/Home_Sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    ui:
      order: 1
      dashboard: True
    live:
      stream_name: Home

ui:
  live_mode: mse
  timezone: Asia/Kuala_Lumpur
  time_format: 24hour
  date_style: full
  time_style: full
  # DateTime Format
  # Year-Month-Date Hour(12hour):Minute:Second AM/PM Timezone  = "%Y-%m-%d %I:%M:%S %p %z"
  # Year-Month-Date Hour(24hour):Minute:Second Timezone  = "%Y-%m-%d %H:%M:%S %z"
  strftime_fmt: "%Y-%m-%d %H:%M:%S %z"

telemetry:
  version_check: True
```

### Relevant log output

```shell
2023-07-06 23:55:39.301360362  [INFO] Starting Frigate...
2023-07-06 23:55:40.875800368  [2023-07-06 23:55:40] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-07-06 23:55:40.915277362  [2023-07-06 23:55:40] peewee_migrate                 INFO    : Starting migrations
2023-07-06 23:55:40.922895857  [2023-07-06 23:55:40] peewee_migrate                 INFO    : There is nothing to migrate
2023-07-06 23:55:40.959717271  [2023-07-06 23:55:40] detector.cpu1                  INFO    : Starting detection process: 444
2023-07-06 23:55:40.959860185  [2023-07-06 23:55:40] detector.cpu2                  INFO    : Starting detection process: 446
2023-07-06 23:55:40.965568005  [2023-07-06 23:55:40] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-07-06 23:55:40.966538947  [2023-07-06 23:55:40] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-07-06 23:55:40.970014387  [2023-07-06 23:55:40] frigate.app                    INFO    : Output process started: 448
2023-07-06 23:55:40.983125747  [2023-07-06 23:55:40] frigate.app                    INFO    : Camera processor started for Garage: 451
2023-07-06 23:55:41.017288082  [2023-07-06 23:55:40] frigate.app                    INFO    : Camera processor started for Home: 452
2023-07-06 23:55:41.020277906  [2023-07-06 23:55:41] frigate.app                    INFO    : Capture process started for Garage: 454
2023-07-06 23:55:41.023333937  [2023-07-06 23:55:41] frigate.app                    INFO    : Capture process started for Home: 455
2023-07-06 23:56:01.301717154  Exception in thread detected_frames_processor:
2023-07-06 23:56:01.301732029  Traceback (most recent call last):
2023-07-06 23:56:01.301735529    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-07-06 23:56:01.302120814      self.run()
2023-07-06 23:56:01.302132189    File "/opt/frigate/frigate/object_processing.py", line 910, in run
2023-07-06 23:56:01.302257020      camera_state.update(
2023-07-06 23:56:01.302261687    File "/opt/frigate/frigate/object_processing.py", line 531, in update
2023-07-06 23:56:01.302366976      c(self.name, removed_obj, frame_time)
2023-07-06 23:56:01.302371060    File "/opt/frigate/frigate/object_processing.py", line 694, in end
2023-07-06 23:56:01.302496183      with open(
2023-07-06 23:56:01.302524474  OSError: [Errno 28] No space left on device: '/media/frigate/clips/Home-1688658942.390635-0xn22b.jpg'
```

### FFprobe output from your camera

```shell
# Camera Garage : EZVIZ C8W PRO
[hevc_rkmpp @ 0x55af779c60] Decoder noticed an info change (2304x1296), format=0
[rtsp @ 0x55af775200] max delay reached. need to consume packet
[rtsp @ 0x55af775200] RTP: missed 32 packets
Input #0, rtsp, from 'rtsp://*******:*******@192.168.0.102:554':                                         
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p, 2304x1296, 30 fps, 30 tbr, 90k tbn, 90k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

# Camera Home : EZVIZ C6N 4MP
[hevc_rkmpp @ 0x557d841c60] Decoder noticed an info change (1920x1080), format=0
Input #0, rtsp, from 'rtsp://*******:*******@192.168.0.104:554':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p, 1920x1080, 15 fps, 15 tbr, 90k tbn, 90k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"Garage":{"camera_fps":5.1,"capture_pid":454,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":463,"pid":451,"process_fps":5.1,"skipped_fps":0.0},"Home":{"camera_fps":5.1,"capture_pid":455,"detection_enabled":1,"detection_fps":10.1,"ffmpeg_pid":462,"pid":452,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"1066":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"3.0","mem":"1.1"},"111":{"cpu":"0.0","mem":"0.0"},"117":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"152":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"177":{"cpu":"0.0","mem":"0.0"},"2190":{"cpu":"0.0","mem":"0.0"},"2229":{"cpu":"0.0","mem":"0.0"},"2233":{"cpu":"1.3","mem":"0.0"},"2235":{"cpu":"0.0","mem":"0.0"},"228":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"437":{"cpu":"0.0","mem":"0.5"},"44":{"cpu":"0.0","mem":"0.0"},"443":{"cpu":"0.3","mem":"0.1"},"444":{"cpu":"14.7","mem":"0.6"},"446":{"cpu":"13.3","mem":"0.6"},"448":{"cpu":"0.0","mem":"0.6"},"451":{"cpu":"2.0","mem":"0.7"},"452":{"cpu":"7.0","mem":"0.6"},"453":{"cpu":"0.0","mem":"0.2"},"454":{"cpu":"3.0","mem":"0.5"},"455":{"cpu":"3.0","mem":"0.5"},"461":{"cpu":"0.0","mem":"0.2"},"462":{"cpu":"50.3","mem":"0.6"},"463":{"cpu":"55.7","mem":"0.6"},"464":{"cpu":"0.0","mem":"0.2"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.1"},"MiB":{"cpu":"14200.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"3.26,"}},"detection_fps":10.6,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":34.1,"pid":444},"cpu2":{"detection_start":0.0,"inference_speed":32.85,"pid":446}},"service":{"last_updated":1688660482,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":111.8,"mount_type":"tmpfs","total":122.7,"used":10.9},"/media/frigate/clips":{"free":598520.4,"mount_type":"vfat","total":999958.8,"used":401438.4},"/media/frigate/recordings":{"free":598520.4,"mount_type":"vfat","total":999958.8,"used":401438.4},"/tmp/cache":{"free":998.6,"mount_type":"tmpfs","total":1000.0,"used":1.4}},"temperatures":{},"uptime":1541,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

EZVIZ C8W PRO, EZVIZ C6N 4MP
