### ISSUE TITLE
[Config Support]: Increasing Memory Usage

### ISSUE THREAD

**Issue by teunaldo** [blakeblackshear/frigate#7079]
### Describe the problem you are having

Memory is increasing slowly to the max of the machine.
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/75abd081-4ed8-4160-9399-9df23b5115fe)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.9
  user: user1
  password: xxxxx
  
database:
  path: /config/frigate.db

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    Voordeur:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/101
      - "ffmpeg:rtsp_cam#audio=opus"
    Straat:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/201
      - "ffmpeg:rtsp_cam#audio=opus"
    Zij-ingang:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/301
      - "ffmpeg:rtsp_cam#audio=opus"
    Binnen:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/401
      - "ffmpeg:rtsp_cam#audio=opus"
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/edgetpu_model.tflite"
      labelmap_path: /labelmap.txt

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
      - dog
      - bird
      - spider
  
birdseye:
  enabled: True
  mode: continuous

cameras:
  Voordeur: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Voordeur # <----- Update for your camera
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1600 # <---- update for your camera's resolution
      height: 1200 # <---- update for your camera's resolution
  Straat: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Straat # <----- Update for your camera
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1600 # <---- update for your camera's resolution
      height: 1200 # <---- update for your camera's resolution
    motion:
      mask: 239,554,481,589,468,484,558,398,1600,541,1600,0,0,0,0,341,179,358
  Zij-ingang: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Zij-ingang # <----- Update for your camera
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1600 # <---- update for your camera's resolution
      height: 1200 # <---- update for your camera's resolution
    motion:
      mask: 37,0,146,308,828,206,1223,368,1191,547,1410,682,1449,575,1600,524,1600,0
  Binnen: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Binnen # <----- Update for your camera
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1600 # <---- update for your camera's resolution
      height: 1200 # <---- update for your camera's resolution
telemetry:
  version_check: True
```

### Relevant log output

```shell
Go2RTC log:
2023-07-07 13:14:12.650968860  [INFO] Preparing go2rtc config...
2023-07-07 13:14:12.854588762  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-07-07 13:14:12.854593148  [INFO] Starting go2rtc...
2023-07-07 13:14:12.927431918  13:14:12.926 INF go2rtc version 1.5.0 linux/amd64
2023-07-07 13:14:12.927436087  13:14:12.926 INF [api] listen addr=:1984
2023-07-07 13:14:12.927437472  13:14:12.926 INF [rtsp] listen addr=:8554
2023-07-07 13:14:12.927441279  13:14:12.927 INF [srtp] listen addr=:8443
2023-07-07 13:14:12.927443013  13:14:12.927 INF [webrtc] listen addr=:8555/tcp
2023-07-07 13:14:22.664119154  [INFO] Starting go2rtc healthcheck service...

2023-07-07 13:14:12.664118783  [INFO] Starting Frigate...
2023-07-07 13:14:13.653415605  [2023-07-07 13:14:13] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-07-07 13:14:13.678678322  [2023-07-07 13:14:13] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-07-07 13:14:13.688413981  [2023-07-07 13:14:13] peewee_migrate                 INFO    : Starting migrations
2023-07-07 13:14:13.693139384  [2023-07-07 13:14:13] peewee_migrate                 INFO    : There is nothing to migrate
2023-07-07 13:14:13.712077041  [2023-07-07 13:14:13] frigate.app                    INFO    : Output process started: 217
2023-07-07 13:14:13.724264961  [2023-07-07 13:14:13] frigate.app                    INFO    : Camera processor started for Voordeur: 221
2023-07-07 13:14:13.728787751  [2023-07-07 13:14:13] frigate.app                    INFO    : Camera processor started for Straat: 224
2023-07-07 13:14:13.738281439  [2023-07-07 13:14:13] frigate.app                    INFO    : Camera processor started for Zij-ingang: 226
2023-07-07 13:14:13.750100307  [2023-07-07 13:14:13] frigate.app                    INFO    : Camera processor started for Binnen: 227
2023-07-07 13:14:13.752659787  [2023-07-07 13:14:13] frigate.app                    INFO    : Capture process started for Voordeur: 229
2023-07-07 13:14:13.762317309  [2023-07-07 13:14:13] frigate.app                    INFO    : Capture process started for Straat: 231
2023-07-07 13:14:13.771724068  [2023-07-07 13:14:13] frigate.app                    INFO    : Capture process started for Zij-ingang: 234
2023-07-07 13:14:13.783929617  [2023-07-07 13:14:13] frigate.app                    INFO    : Capture process started for Binnen: 236
2023-07-07 13:14:16.528039966  [2023-07-07 13:14:13] detector.coral                 INFO    : Starting detection process: 216
2023-07-07 13:14:16.528043901  [2023-07-07 13:14:13] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-07-07 13:14:16.531572844  [2023-07-07 13:14:16] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
this can happen with some devices and qsv, I'd suggest trying preset-vaapi instead

**Comment by NickM-27** [comment]
your config is also incorrect

```
go2rtc:
  streams:
    Voordeur:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/101
      - "ffmpeg:rtsp_cam#audio=opus"
    Straat:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/201
      - "ffmpeg:rtsp_cam#audio=opus"
    Zij-ingang:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/301
      - "ffmpeg:rtsp_cam#audio=opus"
    Binnen:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/401
      - "ffmpeg:rtsp_cam#audio=opus"
```

`rtsp_cam` is supposed to be changed to reference the stream name

**Comment by teunaldo** [comment]
> your config is also incorrect
> 
> ```
> go2rtc:
>   streams:
>     Voordeur:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/101
>       - "ffmpeg:rtsp_cam#audio=opus"
>     Straat:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/201
>       - "ffmpeg:rtsp_cam#audio=opus"
>     Zij-ingang:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/301
>       - "ffmpeg:rtsp_cam#audio=opus"
>     Binnen:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/401
>       - "ffmpeg:rtsp_cam#audio=opus"
> ```
> 
> `rtsp_cam` is supposed to be changed to reference the stream name

All of the camera's are seperate streams. 
It is a camera which gives different angles.

How should this fit in my config?

**Comment by teunaldo** [comment]
> your config is also incorrect
> 
> ```
> go2rtc:
>   streams:
>     Voordeur:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/101
>       - "ffmpeg:rtsp_cam#audio=opus"
>     Straat:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/201
>       - "ffmpeg:rtsp_cam#audio=opus"
>     Zij-ingang:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/301
>       - "ffmpeg:rtsp_cam#audio=opus"
>     Binnen:
>       - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/401
>       - "ffmpeg:rtsp_cam#audio=opus"
> ```
> 
> `rtsp_cam` is supposed to be changed to reference the stream name

Too bad. Changed this, but memory usage is still increasing.

**Comment by teunaldo** [comment]
> this can happen with some devices and qsv, I'd suggest trying preset-vaapi instead

Too bad. The memory usage is still increasing

I connected to the console of the container, and executed "top". It looks like the memory usage is coming from buff/cache.
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/03101e96-1ac4-49d1-92df-91b95c6c10d7)

Will that give some ideas?

**Comment by NickM-27** [comment]
> How should this fit in my config?

you need to change `rtsp_cam` to be the name of the stream, it does not know what rtsp_cam is

> Too bad. The memory usage is still increasing

the values you are showing right now are not unreasonable or abnormal for memory usage especially when using go2rtc and memory increasing is not weird in general for linux. We would need to see info once memory usage is higher

**Comment by teunaldo** [comment]
How should this fit in my config?

you need to change rtsp_cam to be the name of the stream, it does not know what rtsp_cam is

I'm a bit confused.
How do I do this for the 4 streams? I can't name them all rtsp_cam or rtsp_cam_sub

**Comment by NickM-27** [comment]
this is all you need to do:

```
go2rtc:
  streams:
    Voordeur:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/101
      - "ffmpeg:Voordeur#audio=opus"
    Straat:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/201
      - "ffmpeg:Straat#audio=opus"
    Zij-ingang:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/301
      - "ffmpeg:Zij-ingang#audio=opus"
    Binnen:
      - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/401
      - "ffmpeg:Binnen#audio=opus"
```

**Comment by teunaldo** [comment]
> 
So it needs to be:

go2rtc:
  streams:
      rtsp_cam:
        Voordeur:
          - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/101
          - "ffmpeg:Voordeur#audio=opus"
        Straat:
          - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/201
          - "ffmpeg:Straat#audio=opus"
        Zij-ingang:
          - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/301
          - "ffmpeg:Zij-ingang#audio=opus"
        Binnen:
          - rtsp://admin:xxxxx@192.168.2.234:554/Streaming/channels/401
          - "ffmpeg:Binnen#audio=opus"

**Comment by NickM-27** [comment]
it needs to be exactly what I put, if you are doing it right you will not have `rtsp_cam` which is the whole point of what I was saying... rtsp_cam is meant to be replaced with the name of the stream

**Comment by teunaldo** [comment]
> it needs to be exactly what I put, if you are doing it right you will not have `rtsp_cam` which is the whole point of what I was saying... rtsp_cam is meant to be replaced with the name of the stream

aaah check! Wasn't looking at the audio=opus line. I misread

**Comment by teunaldo** [comment]
Memory usage has increased to around 5GB of usage now for the container.
The top command gives the following information:
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/353a6d17-b97f-4bff-8a6a-5473bb351678)


I also get this error like 4/5 times this evening:

```
2023-07-07 20:40:04.719916606  [2023-07-07 20:40:04] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2023-07-07 20:40:04.719919816  [2023-07-07 20:40:04] root                           INFO    : Waiting for detection process to exit gracefully...
2023-07-07 20:40:34.750106155  [2023-07-07 20:40:34] root                           INFO    : Detection process didnt exit. Force killing...
2023-07-07 20:40:34.764333150  [2023-07-07 20:40:34] root                           INFO    : Detection process has exited...
2023-07-07 20:40:34.773334982  [2023-07-07 20:40:34] detector.coral                 INFO    : Starting detection process: 16904
2023-07-07 20:40:37.584418887  [2023-07-07 20:40:34] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-07-07 20:40:37.591946316  [2023-07-07 20:40:37] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

**Comment by teunaldo** [comment]
On the host I also get errors:
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/84a5e60f-ef8d-4055-a798-ad7aeeb247ce)

**Comment by teunaldo** [comment]
Now it is using 9.7G for the container.
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/f60949a0-c3ff-4578-bbf3-f2880d2a7a4d)
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/e893e910-a630-4c12-9437-bcccd2c4c13d)

**Comment by NickM-27** [comment]
So the problem is none of the here are using much RAM so it's not clear what is. In any case the detection stuck is worth looking at first. 

I'd try using a different port, different cable with the coral to see if the detection stuck can be fixed

**Comment by teunaldo** [comment]
Hi,

I fixed the detection stuck issue. 
This was happening because of running Frigate in a VM on Proxmox.
Seems that GPU passthrough has a lot of issues with this. 

I now moved to a LXC, and the issue is gone. 
However, if I look at the memory usage of the docker container, it is still increasing.
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/571333fd-b247-4c3f-81b7-21f1e6029707)
After a restart of Frigate, the memory usage is around 700MB again
Strange thing is: If I look at the LXC in Proxmox, the memory usage is stable
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/1da8cff0-308e-4e85-a574-209b5ab296ed)

Also the host itself gives a stable memory usage
![afbeelding](https://github.com/blakeblackshear/frigate/assets/59298151/6b346978-efa4-4bbf-bde3-255a8f578a5b)

So I'm curious which memory is used in this case since it seems that no system memory is used? And is this correct, or a bug?

**Comment by mdkeil** [comment]
Same issue after upgrading from v11 to v12.1. Frigate Docker Container consumed ~12GB RAM after 12hours.. Now, I limited the container to 4GB. You can see a massive increasing memory usage after sunset. 

The aggregate IO-write is corresponding with the memory usage (until 4GB Memory Limit was reached)

vaapi hwaccel with AMD Radeon RX 550

![portainer_frigate](https://github.com/blakeblackshear/frigate/assets/8126652/0e0dd146-6301-41e4-bce1-4157915b384f)
![frigate_memory](https://github.com/blakeblackshear/frigate/assets/8126652/a7d098bf-d94f-4e4b-a7e7-a7d105e814e6)

```
mqtt:
  host: 192.168.1.2
  user: mosquitto
  password: **********

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args:
    -avoid_negative_ts make_zero
    -fflags nobuffer+genpts+discardcorrupt
    -flags low_delay
    -strict experimental
    -analyzeduration 1000M
    -probesize 1000M
    -rw_timeout 5000000
    -f live_flv

  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: False

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

go2rtc:
  streams:
   front:
      - ffmpeg:rtmp://192.168.1.15/bcs/channel0_ext.bcs?channel=0&stream=2&user=frigate&password=**********
   back:
      - ffmpeg:rtmp://192.168.1.16/bcs/channel0_ext.bcs?channel=0&stream=2&user=frigate&password=**********

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtmp://192.168.1.15/bcs/channel0_main.bcs?channel=0&stream=0&user=frigate&password=**********
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 7
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        person:
          mask:
            - 252,186,406,178,471,104,585,138,556,463,516,467,510,512,896,512,896,0,0,0,0,382
        car:
          mask:
            - 252,186,406,178,471,104,585,138,556,463,516,467,510,512,896,512,896,0,0,0,0,382
        dog:
          mask:
            - 252,186,406,178,471,104,585,138,556,463,516,467,510,512,896,512,896,0,0,0,0,382
        cat:
          mask:
            - 252,186,406,178,471,104,585,138,556,463,516,467,510,512,896,512,896,0,0,0,0,382
    motion:
      improve_contrast: False
      threshold: 25
      contour_area: 30
      mask:
        - 252,186,406,178,471,104,585,138,556,463,516,467,510,512,896,512,896,0,0,0,0,382
        - 513,152,453,188,442,257,541,262,542,181
        - 363,512,315,466,241,452,152,469,96,512
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - car
          - dog
          - cat

  back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtmp://192.168.1.16/bcs/channel0_main.bcs?channel=0&stream=0&user=frigate&password=**********
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bird
      filters:
        person:
          mask:
            - 896,0,896,119,801,91,562,60,369,64,277,68,297,473,383,472,381,512,0,512,0,0
            - 852,169,896,213,857,262,803,220
        dog:
          mask:
            - 896,0,896,119,801,91,562,60,369,64,277,68,297,473,383,472,381,512,0,512,0,0
        cat:
          mask:
            - 896,0,896,119,801,91,562,60,369,64,277,68,297,473,383,472,381,512,0,512,0,0
        bird:
          mask:
            - 896,0,896,119,801,91,562,60,369,64,277,68,297,473,383,472,381,512,0,512,0,0
    motion:
      improve_contrast: False
      mask:
        - 896,0,896,119,801,91,562,60,369,64,277,68,297,473,383,472,381,512,0,512,0,0
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - dog         
          - cat
          - bird
``` 

```
2023-08-17 08:30:18.788481007  [INFO] Starting Frigate...
2023-08-17 08:30:19.652012236  [2023-08-17 08:30:19] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-17 08:30:19.680884630  [2023-08-17 08:30:19] peewee_migrate                 INFO    : Starting migrations
2023-08-17 08:30:19.684208731  [2023-08-17 08:30:19] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-17 08:30:19.695723012  [2023-08-17 08:30:19] detector.coral                 INFO    : Starting detection process: 577
2023-08-17 08:30:22.375931297  [2023-08-17 08:30:19] frigate.app                    INFO    : Output process started: 579
2023-08-17 08:30:22.376096908  [2023-08-17 08:30:19] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-08-17 08:30:22.376190043  [2023-08-17 08:30:19] frigate.app                    INFO    : Camera processor started for front: 585
2023-08-17 08:30:22.376296222  [2023-08-17 08:30:19] frigate.app                    INFO    : Camera processor started for back: 586
2023-08-17 08:30:22.376415526  [2023-08-17 08:30:19] frigate.app                    INFO    : Capture process started for front: 588
2023-08-17 08:30:22.376531534  [2023-08-17 08:30:19] frigate.app                    INFO    : Capture process started for back: 591
2023-08-17 08:30:22.385210150  [2023-08-17 08:30:22] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

```
2023-08-17 08:30:18.787870461  [INFO] Preparing go2rtc config...
2023-08-17 08:30:19.059676650  [INFO] Starting go2rtc...
2023-08-17 08:30:19.124703942  08:30:19.124 INF go2rtc version 1.2.0 linux/amd64
2023-08-17 08:30:19.124867128  08:30:19.124 INF [api] listen addr=:1984
2023-08-17 08:30:19.125032759  08:30:19.125 INF [rtsp] listen addr=:8554
2023-08-17 08:30:19.125207878  08:30:19.125 INF [srtp] listen addr=:8443
2023-08-17 08:30:19.125334947  08:30:19.125 INF [webrtc] listen addr=:8555
2023-08-17 08:30:28.789250355  [INFO] Starting go2rtc healthcheck service...
```

**Comment by NickM-27** [comment]
@mdkeil I'd suggest using the reolink recommended setup in the docs https://docs.frigate.video/configuration/camera_specific#reolink-cameras

also, general memory stats are not that useful, we need specific info from htop or other programs to show what process or file is using the memory

**Comment by martinj9320** [comment]
I have the same issue. Memory usage is constantly increasing until about 500 MB of 16 GB are left. In my case the high usage also comes from "buff/cache".

![grafik](https://github.com/blakeblackshear/frigate/assets/64349124/e7bcba18-9b2a-436f-ae58-f2496564610e)

Version:

0.12.1-367d724


Frigate config file:
```
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  log:
    exec: trace
  streams:
    Turbinenhaus:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.100:554/ch1/main
    Turbinenhaus_gedreht:
      - "ffmpeg:Turbinenhaus#video=h264#rotate=90#hardware"
    Rechenreiniger:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.101:554/ch1/main
    Muehlenhof:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.102:554/ch1/main
    Werkstatt:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.103:554/ch1/main

detectors:
  coral:
    type: edgetpu
    device: pci

birdseye:
  mode: continuous
  restream: true

objects:
  track:
    - person
    - car

record:
  enabled: true
  retain:
    days: 0
  events:
    pre_capture: 20
    post_capture: 20
    objects:
      - person
      - car
    retain:
      default: 14
      mode: active_objects

cameras:
  Turbinenhaus:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Turbinenhaus_gedreht
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1080
      height: 1920
    live:
      stream_name: Turbinenhaus_gedreht

  Rechenreiniger:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Rechenreiniger
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080

  Muehlenhof:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Muehlenhof
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 3840
      height: 2160

  Werkstatt:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Werkstatt
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
```

docker-compose file:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "218mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config.yml:/config/config.yml
      - /root/frigate/media/:/media/frigate
      - /root/frigate/go2rtc:/config/go2rtc
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_USER: user
      FRIGATE_RTSP_PASSWORD: password
```

The logs don't show any errors. I was previously running `go2rtc` `v1.3.1` because hardware transpose wasn't supported with the integrated version and upgraded to `v1.5.0` because apparently this has solved issues with high memory usage for others, though unfortunatly not for me.
