### ISSUE TITLE
[Config Support]: Integration doesn't recive anything

### ISSUE THREAD

**Issue by dowermyr** [blakeblackshear/frigate#7083]
### Describe the problem you are having

the entities in the integration says it's working, but they never change state. And I can't toggle the settings like recording etc.

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.195:1883
  user: mqtt-user
  password: xxxxxx
  topic_prefix: frigate
  client_id: frigate
  
cameras:
  garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://tapo-frigate:p2Gulda!@192.168.1.199:554/stream1
          roles:
            - record
        - path: rtsp://tapo-frigate:p2Gulda!@192.168.1.199:554/stream2
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person  
        - cat
        
      filters:
        person:
          threshold: 0.78

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    motion:
      mask:
        - 0,52,0,0,821,0,826,57
```

### Relevant log output

```shell
No errors in log
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
