### ISSUE TITLE
[Support]: dashboard Integration not working on iOS, but android and PC 

### ISSUE THREAD

**Issue by MStapelfeldt** [blakeblackshear/frigate#7085]
### Describe the problem you are having

I have a tile on my dashboard, which is working great on droid and PC, but I can't display the camera output on iOS. This is kinda strange, because I can view the camera itself in HA.
This is the camera output on dashboard 
![IMG_0017](https://github.com/blakeblackshear/frigate/assets/6480145/8001bca1-f826-4af6-9e6a-f7f7debcc5c7)
And this is frigate
![IMG_0018](https://github.com/blakeblackshear/frigate/assets/6480145/e3fce225-308d-4648-bb6d-1304deed8a59)
With android
![Screenshot_20230707-184110](https://github.com/blakeblackshear/frigate/assets/6480145/b1c1481e-ddad-42a2-b5eb-8ae62fdd27f6)

My card yaml:
```yaml
                      type: picture-elements
                      camera_view: live
                      camera_image: camera.fri_haustuer_cam
                      elements: 
                          - type: icon
                            icon: mdi:eye
                            hold_action:
                              action: none
                            tap_action:
                              action: more-info
                            entity: camera.fri_haustuer_cam
                            style:
                              bottom: 5%
                              left: 5%
                              color: white
                              opacity: 0.5
                              transform: scale(1.5, 1.5)
```
I hope someone can help me or point to right direction because I'm using same card for 3 other cameras with ptz function which also don't work. (This code is only the most easy one to copy).

Best regards 

### Version

SYSTEM 0.12.1-367D724

### Frigate config file

```yaml
fri_haustuer_cam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.76:8554/tuer
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Go2rtc from tuya

### Any other information that may be helpful

Only in iOS devices, iPad and iPhone. PC and droid working perfectly

**Comment by NickM-27** [comment]
You should post this issue on home assistant frontend repo, this is not a frigate issue.

**Comment by NickM-27** [comment]
It displays on the frigate webpage as expected. It doesn't work in the HA dashboard, this would be an ha issue.

**Comment by MStapelfeldt** [comment]
But the same camera, different entity also works on ha. So for me it might be an issue with the entity or stream provided by frigate.
See this picture and code
![IMG_0022](https://github.com/blakeblackshear/frigate/assets/6480145/42dc984f-adf3-46e4-983c-8ad5420f9117)
```
views:
  - title: Home
    type: panel
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: picture-elements
            camera_view: live
            camera_image: camera.terasse_mainstream
            elements: []
          - type: picture-elements
            camera_view: live
            camera_image: camera.fri_terasse_cam
            elements: []
          - type: picture-entity
            entity: camera.fri_terasse_cam

```
Picture-elements from onvif works, picture-entity from frigate also. Picture-elements from frigate doesn't work...  I know there are many ways and flags to configure the streams coming in and out. I was hoping this could be done by setting up output_args for the camera to display it.
But I will also ask at ha Forum.
