### ISSUE TITLE
[Support]: Detection problem

### ISSUE THREAD

**Issue by lorenzomartini1** [blakeblackshear/frigate#7086]
### Describe the problem you are having

Hello there!
I have a problem with Frigate object detection: during sunset, it gives me this:
![IMG_7389](https://github.com/blakeblackshear/frigate/assets/35630216/4fbec32e-8e20-47d2-9556-e19ba507019b)
Every day… now I have lot of events like this only this evening…
I use mask in that area

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: internal-net.domain.it
  port: 1883
  user: user
  password: pw

detect:
  enabled: true
  width: 960
  height: 540
  fps: 10
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 60

cameras:
  retro_alto:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.59/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
          roles:
            - record
            - detect
    zones:
      viottolino:
        coordinates: 0,222,222,198,266,249,340,244,356,202,675,189,960,199,960,129,754,118,596,114,226,123,0,152
      campo:
        coordinates: 133,28,132,0,960,0,960,128,625,111,303,124,0,153,0,21
      giardino:
        coordinates: 0,540,661,540,672,510,960,509,960,209,361,199,359,251,263,259,208,201,0,216

  porta_vista_nord:
    ffmpeg:
        inputs:
          - path: rtmp://192.168.1.55/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
            roles:
              - record
              - detect
    zones:
      giardino:
        coordinates: 329,292,517,300,518,107,586,114,593,77,476,66,436,38,281,43,0,179,0,540,239,540
      pavimento:
        coordinates: 519,112,598,108,641,295,652,415,669,487,673,504,661,540,222,540,322,300,516,306
      ingresso:
        coordinates: 615,176,640,359,665,502,696,490,714,496,717,484,736,456,873,116,888,79,837,26,634,0
      viottolino:
        coordinates: 500,0,566,0,561,66,498,62
              
  porta_vista_sud:
    ffmpeg:
      inputs:
          - path: rtmp://192.168.1.73/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
            roles:
              - record
              - detect
    zones:
      giardino:
        coordinates: 772,508,960,509,960,212,791,105,621,103
      ingresso:
        coordinates: 0,91,0,540,357,540,281,395,206,46
      tettoia:
        coordinates: 778,540,612,540,357,540,283,379,330,258,416,103,438,85,606,67

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 7
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 10

ffmpeg:
  hwaccel_args:
#    - -hwaccel
#   - vaapi
#   - -hwaccel_device
#   - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
#   - -fflags
#   - nobuffer
#   - -flags
#   - low_delay
#   - -strict
#   - experimental
#   - -fflags
#   - +genpts+discardcorrupt
#   - -rw_timeout
#   - "5000000"
#   - -use_wallclock_as_timestamps
#   - "1" 
  output_args:
    record: preset-record-generic-audio-aac
    
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "solid"
  
live:
  height: 480
  quality: 8
    
birdseye:
  enabled: True
  width: 1280
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink
