### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by dcgrove** [blakeblackshear/frigate#712]
Hello, I am getting an error stating "database is locked".  My clips, config, and recordings folders are all mapped to a samba share on an openmediavault NAS that is mounted via my fstab file to "/media/10tbextsmb/". This config works fine when the docker bind mounts are pointed to a local hard drive for testing. I have added the path to my database file in my config as the docs state, but can't seem to get past this. I have used the path below, and "/media/10tbextsmb/bigserver/frigate/clips/frigate.db" as the path in the config. 

Config:
```
mqtt:
  host: 192.168.1.205
  port: 1883
  user: clayton
  password: XXXXXXX
database: 
  path: /media/frigate/clips/frigate.db
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtmp://192.168.1.19/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - clips
        - path: 'rtmp://192.168.1.19/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
    width:  640
    height: 480
    fps:  7
    motion:
      mask:
        - 256,97,640,111,640,0,316,0,0,0,0,189,0,355
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - truck
    - cat
    - dog    
```

Docker Command:
```
clayton@bigserver:~$ sudo docker run --rm --name frigate8 --privileged --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 -v /dev/bus/usb:/dev/bus/usb -v /media/10tbextsmb/bigserver/frigate/clips:/media/frigate/clips -v /media/10tbextsmb/bigserver/frigate/recordings:/media/frigate/recordings -v /media/10tbextsmb/bigserver/frigate/config:/config:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:0.8.1-amd64
 * Starting nginx nginx
   ...done.
frigate.app                    WARNING : Camera driveway has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera driveway has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
database is locked
```
