### ISSUE TITLE
Latest frigate has inaccurate object detection

### ISSUE THREAD

**Issue by ljmerza** [blakeblackshear/frigate#713]
On the latest frigate, I've noticed the object detection isn't as accurate. I have `person` and `dog` set to detect and now after the big update, a `person` will get labeled as a `dog`. Unfortunately, I can't adjust the `threshold` because they are the same. If I walk into my kitchen, there's a 50/50 chance it'll label me as a `dog` or a `person` and both will be with about 78% accuracy.

```
frigate:
    image: blakeblackshear/frigate:0.8.1-amd64
    container_name: frigate
    privileged: true
    restart: always
    volumes:
      - /home/me/frigate/config:/config
      - /media/me/clips:/clips
      - /media/me/recordings:/recordings
      - /etc/localtime:/etc/localtime:ro
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/apex_0:/dev/apex_0
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 100000000
```

```
logger:
  default: debug

detectors:
  coral1:
    type: edgetpu
    device: pci

mqtt:
  host: ip_mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate

snapshots:
  retain:
    default: 10

clips:
  max_seconds: 300
  retain:
    default: 10

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

objects:
  track:
    - person
    - dog

cameras:
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://creds@ip:port/kitchen
          roles:
            - detect
            - clips
    width: 1280
    height: 720
    clips:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
```

camera is the wyze cam v2 with the RTSP firmware but this happens on all my cameras:

```
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x564732802f00] method SETUP failed: 461 Unsupported transport
[rtsp @ 0x564732802f00] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://url':
  Metadata:
    title           : Blue Iris
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```
