### ISSUE TITLE
[Config Support]: High CPU Usage With Substream

### ISSUE THREAD

**Issue by cliffburdick** [blakeblackshear/frigate#7130]
### Describe the problem you are having

I was previously capturing all 3 of my cameras at 4K for detections+recording. I read in the documentation that this was bad and it's better to make substreams. I looked at my CPU usage prior to the change, and it was about 10% on 3 cores, or 30% total for frigate.process/detector. After updating my config file to use the 720P substream my camera was sending for detection, I'm now seeing my steady CPU usage at about 200% on 3 cores: 
```
 93.7   0.6   4:05.69 frigate.process
 75.5   0.6   0:59.66 frigate.process
 24.2   5.2   0:45.99 frigate.detecto
 ```

Should I go back to using 4K detections or did I do something wrong?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat
    - motorcycle
    - horse
    - bicycle

record:
  enabled: True
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 3
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - cat
      - dog
      - car
      - motorcycle
      - bicycle

    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 15
        car: 7
        motorcycle: 7
        bicycle: 7
        dog: 15
        cat: 15

cameras:
  lower_wb: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac        
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass!@192.168.1.170:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass!@192.168.1.170:554 # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 0
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50              
    record:
      enabled: True
      events:
        retain:
          default: 10
    motion:
      mask:    
        - 1920,0,1920,139,1267,132,1270,0  
        - 0,350,197,53,883,156,262,754,62,729    
    zones:  
      front_and_street:
        coordinates: 1428,161,922,150,739,411,651,480,490,560,517,632,478,707,342,821,373,881,234,1013,258,1080,1920,1080,1920,251
        objects:
          - person
          - car
          - cat
          - bicycle
          - dog
          - motorcycle
            
  upper_wb: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac        
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass!@192.168.1.172:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass!@192.168.1.172:554 # <----- The stream you want to use for detection
          roles:
            - record            
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 0
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50 
    record:
      enabled: True
      events:
        retain:
          default: 10                
    motion:
      mask:    
        - 1994,0,2001,130,2636,141,2638,0
    zones:  
      driveway_and_street:
        coordinates:  391,0,1868,0,1968,137,2358,127,2375,261,2238,527,2575,657,2688,1520,0,1520,0,277
        objects:
          - person
          - car
          - bicycle
          - cat
          - dog
          - motorcycle
  porch: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac        
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass@192.168.1.171:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect      
        - path: rtsp://admin:pass@192.168.1.171:554 # <----- The stream you want to use for detection
          roles:
            - record
    record:
      enabled: True
      events:
        retain:
          default: 10            
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 0
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50        
    motion:
      mask:    
        - 1654,0,2688,0,2688,143,1656,154
    zones:  
      porch_and_lawn:
        coordinates: 2688,0,2381,244,2315,347,1945,261,1618,244,1178,187,931,267,735,0,0,0,0,1520,2688,1520
        objects:
          - person
          - car
          - bicycle
          - cat
          - dog
          - motorcycle
```

### Relevant log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other
