### ISSUE TITLE
[Camera Support]: Have any special configuration for Reolink POE Doorbell ?

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#7131]
### Describe the problem you are having

I success figured out memory leak from Reolink Doorbell

I wonder if someone else facing with that issue?
And
Which configuration I need ? 

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
Doorbell:
      - rtsp://admin:123@192.168.1.142:554/h264Preview_01_main
      - "ffmpeg:Doorbell#audio=opus"
    Doorbell_sub:
      - rtsp://admin:123@192.168.1.142:554/h264Preview_01_sub

#################################################Doorbell########################################
  Doorbell:
   ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
          - path:  rtsp://127.0.0.1:8554/Doorbell_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
          - path: rtsp://127.0.0.1:8554/Doorbell?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record

   timestamp_style:
    position: "tl"
    format: "%A, %d %B %Y %H:%M:%S"
    thickness: 1
    effect: solid

   detect:
      width: 1920
      height: 1080
      fps: 13
      max_disappeared: 100
      stationary:
       interval: 10
       threshold: 200

   snapshots:
     enabled: true
     timestamp: true
     bounding_box: false
     crop: true
     height: 1080
     retain:
       default: 60
       
   record:
     enabled: true
     retain:
       days: 30
     events:
       pre_capture: 50
       post_capture: 50
       objects:
         - person
         - cat
         - dog
       retain:
         default: 30

#   motion:
#     threshold: 70
#     improve_contrast: True
#     mask:
#       - 422,0,0,0,0,325
#       - 276,237,973,31,868,0,277,159
#       - 759,39,773,89,707,190,417,253,332,168
#       - 1280,116,1280,29,1179,30,1177,122
   motion:
    mask:
      - 1187,499,1180,622,876,610,858,483
      - 1236,403,1215,552,0,578,0,380
    threshold: 50
    improve_contrast: True
   objects:
     track:
       - person
       - dog
       - cat
     filters:
       person:
         threshold: 0.70
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"10/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink POE Doorbell
