### ISSUE TITLE
[Config Support]: best way to remove audio from non-recordings/livestreams cameras. Home assistant is muting my device audio when the camera starts

### ISSUE THREAD

**Issue by SpartanTech** [blakeblackshear/frigate#7132]
### Describe the problem you are having

When I use a frigate camera in home assistance picture glance card live view, the audio on my PC or phone stops. The picture glance card does not support audio but I think somehow still triggers the phone and PC operating system to mute other streams because it detects that that camera has audio.

What is the best way to disable audio on my stream? I would prefer to have the recordings keep the audio but anything live not have the audio. The audio is opus 1600 I believe. Should I modify and set up a go-to RTC stream? Or should I set up a separate camera entity, using hardware resources, that strips out audio?

Ultimately I think it's a bug the picture glance card, but no one is willing to help there.

### Version

Latest stable 12.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.147
  user: mqtt
  password: pss
  client_id: frigate
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: False
#ffmpeg y:
 # input_args: -stimeout 5000000 -avoid_negative_ts make_zero
  #input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000>
  #disable below if system unresponsive
#  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    Doorbell:
      - rtsp://root:adcvideo@192.168.1.171:554/live.sdp?channel=1&subtype=1
      #- "ffmpeg:rtsp://root:adcvideo@192.168.1.171:554/live.sdp#video=copy#audio=copy#audio=aac"
      - "ffmpeg:rtsp://root:adcvideo@192.168.1.171:554/live.sdp#video=copy"
      #- "ffmpeg:Doorbell#audio=pcmu/16000"
    Outdoor1:
      - rtsp://root:adcvideo@192.168.1.173:554/live.sdp?channel=1&subtype=1
    Outdoor2:
      - rtsp://root:adcvideo@192.168.1.174:554/live.sdp?channel=1&subtype=1
#birdseye:
#  enabled: True
#  restream: True
#  mode: continuous
detectors:
#  cpu1:
#    type: cpu
#    num_threads: 3
  coral:
    type: edgetpu
    device: pci:0
rtmp:
  enabled: false
detect:
  fps: 5
  #Added to stop motion sensor staying on too long. Remove to default of 25 if detect issues
  #max_disappeared: 15
live:
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 10
#detectors:
#  coral:
#   type: edgetpu
#    device: usb
cameras:
  Doorbell:
    birdseye:
      enabled: True
    ffmpeg:
#      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a pcmu
        rtmp: preset-record-mjpeg
      inputs:
        #- path: rtsp://root:adcvideo@192.168.1.171:554/live2.sdp
        - path: rtsp://root:adcvideo@192.168.1.171:554/live2.sdp
          #input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://root:adcvideo@192.168.1.171:554/live.sdp
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      #output_args:
      #  record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      ##height: 768
    motion:
      #Default .2
      #frame_alpha: 0.25
      #lower res mask
      #mask:
      #  - 640,0,640,167,441,152,439,115,246,84,152,27,157,0
      #  - 0,360,150,305,160,0,0,0
      mask:
        - 1280,0,1280,204,888,241,455,153,420,112,331,0,405,0
        - 0,720,206,720,216,0,0,0
    objects:
      track:
        - person
        - car
    zones:
#Lower Res Zones
#      Area_Of_Interest:
#        coordinates: 640,360,0,360,0,0,432,0,451,224,506,225,640,243
#      Driveway:
#        coordinates: 451,283,611,247,516,227,449,227
#      Entry:
#        coordinates: 0,360,494,360,445,313,432,0,0,0
#      ParkingSpot:
#        coordinates: 448,248,570,238,546,183,442,189
#      PreEntry:
#        coordinates: 424,294,494,360,640,360,640,305,521,274
#      Street:
#        coordinates: 439,219,443,0,640,0,640,238,507,228
#      Yard:
#        coordinates: 517,271,640,302,640,239
      Area_Of_Interest:
        coordinates: 1280,720,0,720,0,0,865,0,905,434,1000,433,1280,463
      Driveway:
        coordinates: 896,573,1230,485,1065,451,887,464
      Entry:
        coordinates: 0,720,980,720,861,612,848,0,0,0
      ParkingSpot:
        coordinates: 891,481,1119,472,1116,366,890,365
      PreEntry:
        coordinates: 850,589,987,720,1280,720,1280,615,1035,549
      Street:
        coordinates: 893,397,1105,412,1280,422,1280,469,891,422
      Yard:
        coordinates: 1044,536,1280,594,1280,489,1233,484
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 8
        mode: active_objects
      events:
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 10
        required_zones:
          - Area_Of_Interest
        retain:
          default: 30
          mode: active_objects
    snapshots: # <----- Enable snapshots
      required_zones:
        - Area_Of_Interest
      enabled: True
      timestamp: True
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 720
  Outdoor1:
    enabled: true
    mqtt:
      timestamp: False
      bounding_box: False 
      crop: True
      quality: 100
      height: 720
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://root:adcvideo@192.168.1.173:554/live2.sdp
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://root:adcvideo@192.168.1.173:554/live.sdp
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
    motion:
      #Default .2
      #frame_alpha: 0.25
      mask:
        - 526,342,983,355,1280,295,1280,0,0,0,0,485,0,242
        - 136,712,280,708,280,685,140,690

    zones:
      Area_Of_Interest:
        coordinates: 339,451,736,459,1280,421,1280,720,0,720,0,435
      Driveway:
        coordinates: 511,520,957,501,1280,628,1280,720,915,720,559,720,561,720
      Sidewalk:
        coordinates: 700,472,934,456,1280,421,1280,456,953,500,495,517,250,507,0,480,0,445,464,464
      Street:
        coordinates: 140,690,510,461,887,455,1280,419,1280,359,584,360,0,343
    objects:
      filters:
        person:
          mask: 947,355,989,347,995,310,960,307
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 8
        mode: motion
      events:
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 10
        required_zones:
          - Area_Of_Interest
        retain:
          default: 30
          mode: active_objects
    snapshots: # <----- Enable snapshots
      enabled: True
      timestamp: True
      required_zones: 
        - Driveway
  Outdoor2:
    enabled: true
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://root:adcvideo@192.168.1.174:554/live2.sdp
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://root:adcvideo@192.168.1.174:554/live.sdp
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
    motion:
      #Default .2
      #frame_alpha: 0.25
      mask:
        - 1280,0,1280,280,1148,321,668,301,219,263,0,260,0,0
    zones:
      Area_Of_Interest:
        coordinates: 0,720,755,720,1280,720,1280,393,778,391,258,369,0,353
      Sidewalk:
        coordinates: 0,414,781,456,1280,448,1280,416,769,416,267,393,0,374
      Street:
        coordinates: 1280,0,0,0,0,364,340,380,843,386,1280,378
      Yard:
        coordinates: 1280,720,1280,457,591,453,34,406,0,427,0,720
      Driveway:
        coordinates: 129,367,0,423,0,357
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 8
        mode: motion
      events:
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 10
        required_zones:
          - Area_Of_Interest
        retain:
          default: 30
          mode: active_objects
    snapshots: # <----- Enable snapshots
      enabled: True
      timestamp: True
```

### Relevant log output

```shell
None
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

Audio from camera mutes my device audio instantly with picture glance card, also mute my audio when playing directly from frigate, but that's okay. Just trying to solve a brief glance at my dashboard pausing my entire viewing device.
