### ISSUE TITLE
[Config Support]: Driveway cam constantly detecting objects and recording constantly as result

### ISSUE THREAD

**Issue by lygris** [blakeblackshear/frigate#7136]
### Describe the problem you are having

I have a driveway camera and it essentially records 24/7 because it detects objects constantly. By constantly i mean it is seeing reflections in cars and randomly thinks a mailbox is 15 different people stacking bounding boxes overtop each other. Tried playing around with the settings this morning but I didn't have much success. I attempted to do the 2 zone config per the docs and changing the motion threshold but neither seemed to help.

### Version

0.12.1-367D724

### Frigate config file

```yaml
# yaml-language-server: $schema=http://x.x.x.43:5000/api/config/schema
mqtt: 
  host: x.x.x.25
  user: -----------------
  password: -------------------
detectors:
  coral:
    type: edgetpu
    device: pci
birdseye:
  enabled: True
  mode: objects
  quality: 8
ffmpeg:
  # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # output_args:
  #   record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  #   rtmp: -c copy -f flv
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 5 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 50
go2rtc:
  streams:
    Front-Door:
      - rtsp://fakeuser:fakepass@x.x.x.88:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - "ffmpeg:Front-Door#audio=opus"
    Living-Room:
      - rtsp://x.x.x.202/live0
      - "ffmpeg:Living-Room#audio=opus"
    Garage:
      - rtsp://x.x.x.246/live0
      - "ffmpeg:Garage#audio=opus"
    Garage-Doorbell:
      - rtsp://x.x.x.38:8554/garage-doorbell
      - "ffmpeg:Garage-Doorbell#audio=opus"
    Laundry-Room:
      - rtsp://x.x.x.245/live0
      - "ffmpeg:Laundry-Room#audio=opus"
    # Entryway:
    #   - rtsp://x.x.x.222/live0
    #   - "ffmpeg:Entryway#audio=opus"
    Kitchen:
      - rtsp://x.x.x.173/live0
      - "ffmpeg:Kitchen#audio=opus"
    Backyard:
      - rtsp://fakeuser:fakepass@10.0.0.252/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Backyard#audio=opus"
    Backyard-2:
      - rtsp://fakeuser:fakepass@x.x.x.189:80/videoMain
      - "ffmpeg:Backyard-2#audio=opus"
    Driveway:
      - rtsp://fakeuser:fakepass@10.0.0.253/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Driveway#audio=opus"
cameras:
  Living-Room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Living-Room # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog      
    motion:
      mask:
        - 1920,0,1920,63,1378,55,1372,0
  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 1920,0,1920,63,1378,55,1372,0
  Garage-Doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage-Doorbell # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 1920,1044,1920,1080,1167,1080,1165,1046
        - 1920,0,1920,497,491,502,0,373,0,0
  Front-Door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Door # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 1920,0,1920,795,1399,782,1249,642,801,509,577,411,552,685,0,818,0,0
  Laundry-Room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Laundry-Room # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1920,0,1920,63,1378,55,1372,0
  # Entryway:
  #   ffmpeg:
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/Entryway # <--- the name here must match the name of the camera in restream
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - detect
  #   objects:
  #     track:
  #       - person
  #       - dog
  #   motion:
  #     mask:
  #       - 1920,0,1920,63,1378,55,1372,0
  Kitchen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1920,0,1920,63,1378,55,1372,0
  # Bedroom:
  #   ffmpeg:
  #     input_args:
  #       - -c:v
  #       - h264_cuvid
  #       - -c:a
  #       - aac
  #     inputs:
  #       - path: rtsp://x.x.x.167/live0
  #         roles:
  #           - detect
  #           - rtmp
  #           - record
  #   detect:
  #     enabled: True
  #     max_disappeared: 45
  #   objects:
  #     track:
  #       - person
  #       - dog
  #   record:
  #     enabled: True
  #   motion:
  #     mask:
  #       - 1244,14,1244,35,920,33,920,10
  Backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1920,0,0,0,0,303,590,119,1471,83,1920,341
        - 1920,1080,1920,844,1765,889,1619,1080
        - 887,401,1018,399,1014,197,882,193
  Backyard-2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard-2 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,207,0,0,0,0,462,0,454,46
  Driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      filters:
        car:
          mask:
            - 749,0,1920,0,1920,300,1075,231,792,243,745,287,627,314,0,879,0,0
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 857,0,622,0,0,0,0,854,493,442,750,232,1920,253,1920,0
    zones:
      parked_cars:
        coordinates: 0,1080,1381,1080,1062,285,742,284,743,216,598,0,0,0
        objects:
          - person
          - motorcycle
          - dog
      everything_else:
        coordinates: 1920,0,1920,1080,1370,1080,1075,297,755,269,710,0
        objects:
          - car
          - motorcycle
          - dog
          - person
snapshots:
  enabled: true
record:
  enabled: true
  retain:
    days: 0
  events:
    pre_capture: 10
    post_capture: 20
    retain:
      mode: active_objects
      default: 7
      objects:
        person: 7
        dog: 3
        car: 3
        motorcycle: 3
```

### Relevant log output

```shell
none
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

M.2
