### ISSUE TITLE
[Camera Support]: Having some issues with Uniview NVR

### ISSUE THREAD

**Issue by Iceman248** [blakeblackshear/frigate#7141]
### Describe the problem you are having

I cannot get audio to work no matter which options I try, but more importantly, I cannot view the WebRTC stream and the MSE stream only shows me static image of camera feed as it seems to pause immediately upon playback and hitting play button doesn't do anything.

Also, none of the recordings can be played. I was able to manually pull a file off of the computer Frigate is on and play the file with my computer, but anytime I try to play recordings, circle just spins. Snapshots can be viewed though.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False
go2rtc:
  streams:
    front:
      - rtsp://user:password@192.168.1.200:554/unicast/c2/s0/live
    front_sub:
      - rtsp://user:password@192.168.1.200:554/unicast/c2/s1/live
  webrtc:
    candidates:
      - 191.168.1.10:8555
      - stun:8555
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
snapshots:
  enabled: True
  crop: False
  retain:
    default: 30
detect:
  stationary:
    interval: 0
objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - cat
    - dog
    - bear
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 10
    retain:
      default: 30
      mode: motion
birdseye:
  enabled: true
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
     record: preset-record-generic
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant log output

```shell
N/A, no errors shown in logs.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Uniview NVR302-16S2-P16 (NVR)/IPC3615ER3-ADUPF28M (Cam)/IPC3614LE-ADF28K (Cam)

**Comment by NickM-27** [comment]
> I cannot get audio to work no matter which options I try

Your cameras are not sending audio so naturally it won't work until that is fixed

> I cannot view the WebRTC stream and the MSE stream only shows me static image of camera feed as it seems to pause immediately upon playback and hitting play button doesn't do anything.
>
> Also, none of the recordings can be played.

These are most likely related. 

looks like you have a typo in your webrtc candidate list `191.168.1.10:8555`

**Comment by Iceman248** [comment]
I had to turn the audio off on the cameras, otherwise Frigate would just error and I got nothing.

I don't know how I didn't see that typo. Ugh. MSE still pauses and even though WebRTC works now, it only gives me 1 frame every 2 seconds, so it's unwatchable. I can view RTSP feed through go2rtc just fine.

I tried playing previous recordings again, but still no playback.

**Comment by NickM-27** [comment]
> I had to turn the audio off on the cameras, otherwise Frigate would just error and I got nothing.

well, there is on way to help without that information and without the errors

> MSE still pauses and even though WebRTC works now, it only gives me 1 frame every 2 seconds, so it's unwatchable. I can view RTSP feed through go2rtc just fine.

can you elaborate, where are you watching the rtsp feed in go2rtc (what method is being used)?

> I tried playing previous recordings again, but still no playback.

any errors in the browser or frigate? otherwise you'll need to use chrome://media-internals/

**Comment by Iceman248** [comment]
I wanted to get the rest working right, so for now I just mentioned the audio, but it wasn't important at the moment.

From the links page in go2rtc, I can use the 3 RTSP options to watch with my media player software and they all work fine.

No errors seen in Frigate, browser doesn't say anything. The media-internals from Chrome gives me this. It was really long, trimmed a piece out.

```
{
    "properties": {
      "render_id": 4178,
      "player_id": 1,
      "pipeline_state": "kStopped"
    },
    "events": [
      {
        "time": 0,
        "key": "pipeline_state",
        "value": "kStopping"
      },
      {
        "time": 0.03099966049194336,
        "key": "pipeline_state",
        "value": "kStopped"
      }
    ]
  },
  {
    "properties": {
      "render_id": 4249,
      "player_id": 65,
      "created": "2023-07-12 21:07:25.160 UTC",
      "event": "kWebMediaPlayerDestroyed",
      "url": "go2rtc"
    },
    "events": [
      {
        "time": 0,
        "key": "created",
        "value": "2023-07-12 21:07:25.160 UTC"
      },
      {
        "time": 0.013000011444091797,
        "key": "event",
        "value": "kWebMediaPlayerCreated"
      },
      {
        "time": 0.04500007629394531,
        "key": "url",
        "value": "go2rtc"
      },
      {
        "time": 66527.62099981308,
        "key": "event",
        "value": "kWebMediaPlayerDestroyed"
      }
    ]
  },
  {
    "properties": {
      "render_id": 4249,
      "player_id": 66,
      "created": "2023-07-12 21:10:13.894 UTC",
      "event": "kWebMediaPlayerDestroyed",
      "url": "go2rtc"
    },
    "events": [
      {
        "time": 0,
        "key": "created",
        "value": "2023-07-12 21:10:13.894 UTC"
      },
      {
        "time": 0.013000011444091797,
        "key": "event",
        "value": "kWebMediaPlayerCreated"
      },
      {
        "time": 0.04500007629394531,
        "key": "url",
        "value": "go2rtc"
      },
      {
        "time": 21954.555000305176,
        "key": "event",
        "value": "kWebMediaPlayerDestroyed"
      }
    ]
  },
  {
    "properties": {
      "render_id": 4249,
      "player_id": 67,
      "created": "2023-07-12 21:10:19.808 UTC",
      "origin_url": "http://192.168.1.10:5000/",
      "kFrameUrl": "http://192.168.1.10:5000/cameras/front",
      "kFrameTitle": "Frigate",
      "url": "blob:http://192.168.1.10:5000/1ec17bd2-782a-436d-8ef9-5b3a0fac585f",
      "kTextTracks": [],
      "info": "Effective playback rate changed from 2 to 1",
      "kRendererName": "RendererImpl",
      "pipeline_state": "kStopped",
      "kVideoTracks": [
        {
          "alpha mode": "is_opaque",
          "codec": "h264",
          "coded size": "2560x1440",
          "color space": {
            "matrix": "BT709",
            "primaries": "BT709",
            "range": "LIMITED",
            "transfer": "BT709"
          },
          "encryption scheme": "Unencrypted",
          "has extra data": false,
          "hdr metadata": "unset",
          "natural size": "2560x1440",
          "orientation": "0°",
          "profile": "h264 main",
          "visible rect": "0,0 2560x1440"
        }
      ],
      "kAudioTracks": [
        {
          "bytes per channel": 2,
          "bytes per frame": 2,
          "channel layout": "MONO",
          "channels": 1,
          "codec": "aac",
          "codec delay": 0,
          "discard decoder delay": false,
          "encryption scheme": "Unencrypted",
          "has extra data": false,
          "profile": "unknown",
          "sample format": "Signed 16-bit",
          "samples per second": 16000,
          "seek preroll": "0us"
        }
      ],
      "kIsAudioDecryptingDemuxerStream": false,
      "kAudioDecoderName": "FFmpegAudioDecoder",
      "kIsPlatformAudioDecoder": false,
      "debug": "(Log limit reached. Further similar entries may be suppressed): Bytestream with audio frame PTS 512000us and DTS 512000us indicated the frame is not a random access point (key frame). All audio frames are expected to be key frames for the current audio codec.",
      "kIsVideoDecryptingDemuxerStream": false,
      "kVideoDecoderName": "D3D11VideoDecoder",
      "kIsPlatformVideoDecoder": true,
      "duration": "unknown",
      "dimensions": "2560x1440",
      "kResolution": "2560x1440",
      "warning": "Failed to reconcile encoded audio times with decoded output.",
      "event": "kWebMediaPlayerDestroyed",
      "pipeline_buffering_state": {
        "for_suspended_start": false,
        "state": "BUFFERING_HAVE_ENOUGH"
      },
      "video_buffering_state": {
        "state": "BUFFERING_HAVE_ENOUGH"
      },
      "kVideoPlaybackRoughness": 93.078,
      "kVideoPlaybackFreezing": 0.030034,
      "kFramerate": 28
    },
    "events": [
      {
        "time": 0,
        "key": "created",
        "value": "2023-07-12 21:10:19.808 UTC"
      },
      {
        "time": 0.10900020599365234,
        "key": "origin_url",
        "value": "http://192.168.1.10:5000/"
      },
      {
        "time": 0.11300039291381836,
        "key": "kFrameUrl",
        "value": "http://192.168.1.10:5000/cameras/front"
      },
      {
        "time": 0.11600017547607422,
        "key": "kFrameTitle",
        "value": "Frigate"
      },
      {
```

**Comment by NickM-27** [comment]
The media internals that are shown here are not from the recordings playback, that is what is needed to debug that.

As far as the other things, it seems like the camera is returning bad data which the browser is having difficulty playing back. I'd first suggest using ffmpeg in the go2rtc streams

```
go2rtc:
  streams:
    front:
      - "ffmpeg:rtsp://user:password@192.168.1.200:554/unicast/c2/s0/live#video=copy#audio=aac"
    front_sub:
      - "ffmpeg:rtsp://user:password@192.168.1.200:554/unicast/c2/s1/live#video=copy"
```

**Comment by Iceman248** [comment]
Thanks. That did fix the MSE/WebRTC streaming, but now the detect won't work.

```
2023-07-12 18:50:30.781400509  [2023-07-12 18:50:30] frigate.video                  ERROR   : front: Unable to read frames from ffmpeg process.
2023-07-12 18:50:30.781930101  [2023-07-12 18:50:30] frigate.video                  ERROR   : front: ffmpeg process is not running. exiting capture thread...
2023-07-12 18:50:40.889113580  [2023-07-12 18:50:40] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-07-12 18:50:40.889220217  [2023-07-12 18:50:40] frigate.record                 ERROR   : list index out of range
2023-07-12 18:50:45.681184718  [2023-07-12 18:50:45] watchdog.front                 ERROR   : Ffmpeg process crashed unexpectedly for front.
2023-07-12 18:50:45.681489743  [2023-07-12 18:50:45] watchdog.front                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-07-12 18:50:45.681604576  [2023-07-12 18:50:45] ffmpeg.front.detect            ERROR   : rtsp://127.0.0.1:8554/front_sub: Invalid data found when processing input
```

**Comment by NickM-27** [comment]
is there a reason you are using go2rtc with detect? doesn't seem like the stream is being used anywhere else so there is no benefit

**Comment by Iceman248** [comment]
I'm not sure what you mean by that.

**Comment by NickM-27** [comment]
The sub stream is defined for go2rtc

```
    front_sub:
      - rtsp://user:password@192.168.1.200:554/unicast/c2/s1/live
```

but it is only used for `detect`

there is no benefit in this setup unless the front_sub is being used outside frigate as well. Otherwise, you might as well just have frigate connect directly to the stream

**Comment by Iceman248** [comment]
One camera it actually works fine all around, but the first one I tried, detect won't work in Frigate. NVR same, cameras not exact same model though.

**Comment by Iceman248** [comment]
> The sub stream is defined for go2rtc
> 
> ```
>     front_sub:
>       - rtsp://user:password@192.168.1.200:554/unicast/c2/s1/live
> ```
> 
> but it is only used for `detect`
> 
> there is no benefit in this setup unless the front_sub is being used outside frigate as well. Otherwise, you might as well just have frigate connect directly to the camera

I've just seen it like this referenced somewhere as a guide, makes sense though unless there were issues getting it to work right straight from the camera.

**Comment by NickM-27** [comment]
Right, but there is no reason to use it that way if it is not being used elsewhere; restreaming does use a decent amount of CPU after all so it is not free

**Comment by Iceman248** [comment]
I use `input_args: preset-rtsp-restream` when using it how it is right now. What would I use if straight from camera?

**Comment by NickM-27** [comment]
`preset-rtsp-generic`

**Comment by Iceman248** [comment]
Okay, audio working fine now, too. The only thing I saw not working that I am used to working is that WebRTC streams don't have audio, but MSE ones do.

**Comment by NickM-27** [comment]
This should get audio in webrtc working

```
go2rtc:
  streams:
    front:
      - "ffmpeg:rtsp://user:password@192.168.1.200:554/unicast/c2/s0/live#video=copy#audio=aac#audio=opus"
```

> Also, I normally have copy, but with AAC with FFMPEG, should I set it to AAC?

no keep it at copy, aac is what you want
