### ISSUE TITLE
[Support]: Cars are not detected in IR mode

### ISSUE THREAD

**Issue by lucasteligioridis** [blakeblackshear/frigate#7145]
### Describe the problem you are having

First of all thanks for Frigate, this is pretty awesome and so far I'm loving it!

I just setup a new camera in my garage that points to 2 vehicles which I mainly want to use for object detection on the cars and do some presence / occupancy detection on the existence of those cars.

During the day or really when there is a light on in the garage frigate just does what it does and detects them correctly. But being a garage 95% of the time the lights are off so I'm relying on infrared on the cameras. Unfortunately it doesn't seem to detect them well if at all, sometimes it picks up randomly but its fairly inconsistent and mostly just doesn't detect.

Keeping in mind I am focused on "stationary" detection here for occupancy validation. I have seen the mode for `motion` which doesn't seem to exist in `detect` configuration:

```yaml
motion:
  improve_contrast: False
```

Here is the settings I have for this camera in detect mode following the guide on some sane defaults:
```yaml
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 10
        threshold: 50
```

Is this just a case of infrared models not really trained here or is there something else I can do or configuration I can add? I tried a series of different permutations already:
1. Used all 3 different camera stream quality modes (4k, 720p and 320p)
2. Changed the min_ratio and thresholds to basically 0 to see if that would at least pick up
3. Played around with zoning and masking.

Essentially none of the above really made a difference, as soon as there is any form of light in the room, it immediately detects as I would expect. Any help here is greatly appreciated :) 

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: <redacted>

ffmpeg:
  output_args:
    record: preset-record-ubiquiti

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    garage_cctv:
      - rtspx://<redacted>
    garage_cctv_low:
      - rtspx://<redacted>?video=copy

detect:
  enabled: True
  fps: 5

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True
  timestamp: False
  bounding_box: False
  crop: False
  retain:
    default: 14

cameras:
  garage_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      events:
        objects:
          - person
          - car
        required_zones:
          - person
          - car_left
          - car_right

    snapshots:
      required_zones:
        - car_left
        - car_right

    zones:
      person:
        coordinates: 0,720,1280,720,1280,153,0,135
        objects:
          - person

      car_left:
        coordinates: 368,156,198,193,0,376,0,590,0,720,113,720,294,720,617,720,624,517,632,422,622,200
        objects:
          - car

      car_right:
        coordinates: 1280,720,1280,651,1280,408,1224,293,1029,185,748,192,671,258,754,720
        objects:
          - car

    objects:
      track:
        - person
        - car
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1512,"width":2688},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "17": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "32": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "41": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "42": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "79": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "81": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "82": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "89": {
      "cpu": "7.0",
      "mem": "0.1"
    },
    "97": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "98": {
      "cpu": "1.7",
      "mem": "0.6"
    },
    "112": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "134": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "135": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "136": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "142": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "152": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "156": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "172": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "198": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "230": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "281": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "320": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "362": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "394": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "419": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "459": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "501": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "546": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "602": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "646": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "698": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "726": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "752": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "777": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "805": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1002": {
      "cpu": "0.0",
      "mem": "0.2"
    },
    "1008": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1009": {
      "cpu": "0.7",
      "mem": "0.4"
    },
    "1011": {
      "cpu": "2.0",
      "mem": "0.3"
    },
    "1017": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1018": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1019": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1020": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1021": {
      "cpu": "0.0",
      "mem": "0.3"
    },
    "1022": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1023": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1024": {
      "cpu": "0.0",
      "mem": "0.3"
    },
    "1025": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1026": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1027": {
      "cpu": "7.3",
      "mem": "0.3"
    },
    "1028": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1029": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1030": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1033": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1034": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1037": {
      "cpu": "10.3",
      "mem": "0.1"
    },
    "1038": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1039": {
      "cpu": "2.7",
      "mem": "0.2"
    },
    "1042": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1043": {
      "cpu": "1.3",
      "mem": "0.3"
    },
    "1046": {
      "cpu": "10.7",
      "mem": "0.1"
    },
    "1050": {
      "cpu": "1.3",
      "mem": "0.3"
    },
    "1051": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1053": {
      "cpu": "1.7",
      "mem": "0.1"
    },
    "1054": {
      "cpu": "10.0",
      "mem": "0.1"
    },
    "1058": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "1059": {
      "cpu": "10.3",
      "mem": "0.1"
    },
    "1060": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1064": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1068": {
      "cpu": "1.7",
      "mem": "0.1"
    },
    "1069": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1072": {
      "cpu": "11.3",
      "mem": "0.2"
    },
    "1083": {
      "cpu": "1.0",
      "mem": "0.1"
    },
    "1084": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1086": {
      "cpu": "15.7",
      "mem": "0.1"
    },
    "1091": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "1092": {
      "cpu": "14.3",
      "mem": "0.1"
    },
    "1095": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "1098": {
      "cpu": "1.7",
      "mem": "0.1"
    },
    "2587": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "2612": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "2620": {
      "cpu": "0.3",
      "mem": "0.0"
    },
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "0.3"
    },
    "MiB": {
      "cpu": "13582.3",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "0"
    },
    "top": {
      "cpu": "users,",
      "mem": "load"
    }
  },
  "detection_fps": 2.5,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 7.89,
      "pid": 1009
    }
  },
  "garage_cctv": {
    "camera_fps": 5.1,
    "capture_pid": 1084,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1092,
    "pid": 1028,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "service": {
    "last_updated": 1689249402,
    "latest_version": "0.12.1",
    "storage": {
      "/dev/shm": {
        "free": 252.6,
        "mount_type": "tmpfs",
        "total": 268.4,
        "used": 15.9
      },
      "/media/frigate/clips": {
        "free": 28757594.7,
        "mount_type": "fuse.shfs",
        "total": 79994978.3,
        "used": 51237383.6
      },
      "/media/frigate/recordings": {
        "free": 28757594.7,
        "mount_type": "fuse.shfs",
        "total": 79994978.3,
        "used": 51237383.6
      },
      "/tmp/cache": {
        "free": 45,
        "mount_type": "tmpfs",
        "total": 100,
        "used": 55
      }
    },
    "temperatures": {},
    "uptime": 688,
    "version": "0.12.1-367d724"
  }
}
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G4 Instant
