### ISSUE TITLE
[Config Support]: No 2 ways audio on DMSS when camera is in Frigate

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#7147]
### Describe the problem you are having

I'm using DMSS application to use the 2 ways audio .

When I'm adding the camera to frigate ,
I'm not able to open the Microphone when using the app - return message "can't enable audio to stream ".

When i'm removing it from Frigate -  it works .
The strange thing  is when I open the camera stream using VLC as:
```
rtsp://avic:xxxxx@192.168.1.92/cam/realmonitor?channel=1&subtype=0
```
2 ways audio on the app working perfectly so that proves it coming from frigate .

Dahua Cube Camera K42.

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.113
  port: 1883

database:
  path: /db/frigate.db


go2rtc:
  streams:
    salon_desk: # <- for RTSP streams
      - rtsp://hauser:getindD1978@192.168.1.92/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio

  webrtc:
    candidates:
      - 192.168.1.3:8555
      - stun:8555

cameras:

  salon_desk:
    live:
      stream_name: salon_desk

    birdseye:
      mode: objects

    ffmpeg:  
      output_args:
        record: preset-record-generic-audio-copy
      global_args: -hide_banner -loglevel warning
      hwaccel_args: preset-vaapi
      inputs:
          - path: rtsp://127.0.0.1:8554/salon_desk
            input_args: preset-rtsp-restream
            roles:
            - record
            - detect 
            - restream
    objects:
      track:
        - person
        - dog
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100   
      height: 500

    detect:
      height: 1080
      width: 1920
      fps: 5      

    snapshots:
      enabled: True
      timestamp: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        objects:
          person: 15

    record:
    
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        pre_capture: 3
        post_capture: 3      
        retain:
          default: 7
          mode: active_objects
    motion:
      mask:
        - 1920,0,1920,389,1271,261,999,230,970,306,885,351,525,333,355,364,150,246,0,181,0,80,0,0
```

### Relevant log output

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
