### ISSUE TITLE
[Camera Support]: Unifi camera not streaming in HomeAssistant

### ISSUE THREAD

**Issue by lucasteligioridis** [blakeblackshear/frigate#7151]
### Describe the problem you are having

When trying to open a stream via HomeAssistant entity, I can see the camera entity for my inputs, but when I click to open it the stream is never active. It only ever has a thumbnail showing the last still image and eventually it just errors with a time out" error.

I am actually wondering if I've configured my Unifi cameras correctly in frigate / something to do with my go2rtc config?
I have a feeling perhaps my input/output args are not set correctly? 

Any help or direction would be appreciated :) 

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: <redacted>

ffmpeg:
  output_args:
    record: preset-record-ubiquiti

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    doorbell_cctv:
      - rtspx://<redacted>:7441/<redacted>
    doorbell_cctv_low:
      - rtspx://<redacted>:7441/<redacted>?video=copy
    doorbell_cctv_package:
      - rtspx://<redacted>:7441/<redacted>
    frontyard_cctv:
      - rtspx://<redacted>:7441/<redacted>
    frontyard_cctv_low:
      - rtspx://<redacted>:7441/<redacted>?video=copy
    carport_cctv:
      - rtspx://<redacted>:7441/<redacted>
    carport_cctv_low:
      - rtspx://<redacted>:7441/<redacted>?video=copy
    backyard_cctv:
      - rtspx://<redacted>:7441/<redacted>
    backyard_cctv_low:
      - rtspx://<redacted>:7441/<redacted>?video=copy
    shed_cctv:
      - rtspx://<redacted>:7441/<redacted>
    shed_cctv_low:
      - rtspx://<redacted>:7441/<redacted>?video=copy
    backdoor_cctv:
      - rtspx://<redacted>:7441/<redacted>
    backdoor_cctv_low:
      - rtspx://<redacted>:7441/<redacted>?video=copy
    garage_cctv:
      - rtspx://<redacted>:7441/<redacted>
    garage_cctv_low:
      - rtspx://<redacted>:7441/<redacted>?video=copy
 
detect:
  enabled: True
  fps: 5

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True
  timestamp: False
  bounding_box: False
  crop: False
  retain:
    default: 14

cameras:
  doorbell_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 960
      height: 720

    record:
      events:
        objects:
          - person
        required_zones:
          - porch

    snapshots:
      required_zones:
      - porch

    motion:
      mask:
        - 0,0,960,0,960,158,0,349

    zones:
      porch:
        coordinates: 0,720,0,469,0,349,960,326,960,720
        objects:
          - person

    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 1060,341,841,294,373,273,416,0,1039,0

  doorbell_cctv_package:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_cctv_package
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

  frontyard_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720

    motion:
      mask:
        - 1280,0,1280,223,833,73,755,0

    zones:
      path:
        coordinates: 564,720,537,461,587,382,845,347,820,300,563,314,463,364,378,497,271,720
        objects:
          - person
      yard:
        coordinates: 203,720,243,720,460,344,607,305,790,318,796,270,679,115,555,32,315,44,261,253,0,531,0,720
        objects:
          - person
          - animal

    objects:
      track:
        - bicycle
        - animal
        - person

  carport_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/carport_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      quality: 100

    detect:
      width: 1280
      height: 720

    record:
      events:
        objects:
          - person
          - car
        required_zones:
          - driveway
          - driveway_vehicle_left
          - driveway_vehicle_right

    snapshots:
      required_zones:
        - driveway
        - driveway_vehicle_left
        - driveway_vehicle_right


    motion:
      mask:
        - 449,0,1280,0,428,0,0,0,0,131

    zones:
      driveway:
        coordinates: 134,413,0,720,1107,720,891,81,774,70
        objects:
          - person
          - car
      driveway_vehicle_left:
        coordinates: 134,619,610,352,455,227,57,397
        objects:
          - car
      driveway_vehicle_right:
        coordinates: 57,720,925,720,1023,468,1013,395,843,367,661,345,109,624
        objects:
          - car

    objects:
      track:
        - bicycle
        - animal
        - car
        - person
      filters:
        car:
          mask:
            - 689,70,646,0,0,0,0,122,0,240
            - 1280,0,1280,720,1089,720,1043,720,998,345,901,115,1010,0

  backyard_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720

    motion:
      mask:
        - 0,0,843,0,1062,252,0,325
        - 1280,720,1280,0,1098,0,1001,720

    zones:
      yard:
        coordinates: 478,456,590,369,708,270,990,231,977,356,875,467,723,720,261,720
        objects:
          - person
          - animal
      path:
        coordinates: 939,720,1012,446,1056,247,1005,252,975,376,889,458,828,590,737,720
        objects:
          - person

    objects:
      track:
        - person
        - animal


  shed_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shed_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/shed_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720

    motion:
      mask:
        - 0,229,1280,82,1280,0,564,0,0,0

    zones:
      path:
        coordinates: 1280,720,1280,255,1078,149,889,720
        objects:
          - person
      yard:
        coordinates: 349,720,296,591,199,450,144,479,0,567,0,229,235,182,663,155,1034,165,840,720
        objects:
          - person
          - animal

    objects:
      track:
        - person
        - animal

  backdoor_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backdoor_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backdoor_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720

    motion:
      mask:
        - 0,0,670,0,0,699

    zones:
      porch:
        coordinates: 1093,720,1112,590,1159,387,1165,153,946,214,840,478,642,720
        objects:
          - person

    objects:
      track:
        - person
        - animal

  garage_cctv:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_cctv
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_cctv_low
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      events:
        objects:
          - person
          - car
        required_zones:
          - person
          - car_left
          - car_right

    snapshots:
      required_zones:
        - car_left
        - car_right

    zones:
      person:
        coordinates: 0,720,1280,720,1280,153,0,135
        objects:
          - person

      car_left:
        coordinates: 368,156,198,193,0,376,0,590,0,720,113,720,294,720,617,720,624,517,632,422,622,200
        objects:
          - car

      car_right:
        coordinates: 1280,720,1280,651,1280,408,1224,293,1029,185,748,192,671,258,754,720
        objects:
          - car

    objects:
      track:
        - person
        - car

```

### Relevant log output

```shell
not relevant, or not really sure which output to provide
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1512,"width":2688},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{
  "backdoor_cctv": {
    "camera_fps": 5.1,
    "capture_pid": 1067,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1089,
    "pid": 1027,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "backyard_cctv": {
    "camera_fps": 5,
    "capture_pid": 1050,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1061,
    "pid": 1024,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "carport_cctv": {
    "camera_fps": 5,
    "capture_pid": 1043,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1056,
    "pid": 1022,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "16": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "32": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "41": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "42": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "79": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "81": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "82": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "89": {
      "cpu": "5.3",
      "mem": "0.1"
    },
    "102": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "104": {
      "cpu": "3.7",
      "mem": "0.5"
    },
    "117": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "134": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "135": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "136": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "137": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "138": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "143": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "154": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "177": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "196": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "223": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "256": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "293": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "336": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "379": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "427": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "473": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "514": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "561": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "606": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "659": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "700": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "746": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "786": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "831": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1002": {
      "cpu": "0.0",
      "mem": "0.2"
    },
    "1008": {
      "cpu": "0.7",
      "mem": "0.0"
    },
    "1009": {
      "cpu": "0.0",
      "mem": "0.3"
    },
    "1011": {
      "cpu": "2.0",
      "mem": "0.3"
    },
    "1017": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1018": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1019": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1020": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1021": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1022": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1023": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1024": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1025": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1026": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1027": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1028": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1029": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "1030": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1031": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1034": {
      "cpu": "0.7",
      "mem": "0.3"
    },
    "1037": {
      "cpu": "10.3",
      "mem": "0.1"
    },
    "1038": {
      "cpu": "1.3",
      "mem": "0.3"
    },
    "1039": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1043": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1046": {
      "cpu": "11.0",
      "mem": "0.1"
    },
    "1050": {
      "cpu": "1.7",
      "mem": "0.3"
    },
    "1051": {
      "cpu": "0.0",
      "mem": "0.2"
    },
    "1056": {
      "cpu": "11.0",
      "mem": "0.1"
    },
    "1058": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1061": {
      "cpu": "11.0",
      "mem": "0.1"
    },
    "1065": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1066": {
      "cpu": "11.0",
      "mem": "0.1"
    },
    "1067": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1083": {
      "cpu": "1.0",
      "mem": "0.3"
    },
    "1089": {
      "cpu": "12.6",
      "mem": "0.1"
    },
    "1092": {
      "cpu": "15.6",
      "mem": "0.1"
    },
    "25137": {
      "cpu": "4.3",
      "mem": "0.2"
    },
    "25149": {
      "cpu": "1.7",
      "mem": "0.1"
    },
    "25893": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "25894": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "25895": {
      "cpu": "1.7",
      "mem": "0.1"
    },
    "25896": {
      "cpu": "1.0",
      "mem": "0.1"
    },
    "25897": {
      "cpu": "1.0",
      "mem": "0.1"
    },
    "25898": {
      "cpu": "1.3",
      "mem": "0.1"
    },
    "30922": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30926": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30932": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30937": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30943": {
      "cpu": "0.3",
      "mem": "0.1"
    },
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "0.3"
    },
    "MiB": {
      "cpu": "13243.5",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "0"
    },
    "top": {
      "cpu": "users,",
      "mem": "load"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 8.49,
      "pid": 1009
    }
  },
  "doorbell_cctv": {
    "camera_fps": 5.1,
    "capture_pid": 1030,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1037,
    "pid": 1018,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "doorbell_cctv_package": {
    "camera_fps": 5,
    "capture_pid": 1034,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 25137,
    "pid": 1019,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "frontyard_cctv": {
    "camera_fps": 5.1,
    "capture_pid": 1038,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1046,
    "pid": 1021,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "garage_cctv": {
    "camera_fps": 5.1,
    "capture_pid": 1083,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1092,
    "pid": 1029,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "service": {
    "last_updated": 1689286981,
    "latest_version": "0.12.1",
    "storage": {
      "/dev/shm": {
        "free": 252.2,
        "mount_type": "tmpfs",
        "total": 268.4,
        "used": 16.3
      },
      "/media/frigate/clips": {
        "free": 28743481.5,
        "mount_type": "fuse.shfs",
        "total": 79994978.3,
        "used": 51251496.7
      },
      "/media/frigate/recordings": {
        "free": 28743481.5,
        "mount_type": "fuse.shfs",
        "total": 79994978.3,
        "used": 51251496.7
      },
      "/tmp/cache": {
        "free": 74.9,
        "mount_type": "tmpfs",
        "total": 100,
        "used": 25.1
      }
    },
    "temperatures": {},
    "uptime": 30896,
    "version": "0.12.1-367d724"
  },
  "shed_cctv": {
    "camera_fps": 5.1,
    "capture_pid": 1058,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 1066,
    "pid": 1026,
    "process_fps": 5.1,
    "skipped_fps": 0
  }
}
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G4 Pro and Unifi G4 Instant
