### ISSUE TITLE
[Support]: Best way to stream a sub stream to a Nest Hub?

### ISSUE THREAD

**Issue by haroldboom** [blakeblackshear/frigate#7152]
### Describe the problem you are having

Hi all,
I currently have a simple automation to display a camera live feed to my Nest Hub Max when the camera detects occupancy.  This works about 70% of the time however, sometimes the stream fails to load? (dashcast pops up and then dissipears) or the Nest Hub crashes and reboots.

Before switching go2rtc I would stream the camera to the nest no problem but I believe this was just images updated every second. My current setup is to have the substreams configured in go2rtc but not setup as a camera and I use the restream on HomeAssistant addon WebRTC with the inbuilt DashCast function to display the single sub stream on the Nest. I am unable to use the main stream as it is 4k and wont display on the Nest Hub.

So my question is, is DashCast the best practice for what I am trying to do or is there a better way that might load fast or stop the Nest from crashing.

I was thinking I could add another camera to my config with no detect role and hide it from the UI and then use the native casting in HA to send the substream camera to the Nest Hub when the main stream detects occupancy but I would still need to have a -record role I believe (which shouldn't do anything without a detect role with my config).

Or do I add a Generic Camera to HA with the inbuilt integration?

Or do I use; 
- service: media_player.play_media
      data:
        entity_id: media_player.nest_hub_max
        media_content_id: rtsp://redacted@10.0.0.3:554/Streaming/Channels/102
        media_content_type: video/mp4

What would be best practice with the least lag time to load and less stress on the Nest Hub. The sub streams are 640x480,

Hopefully this makes sense! Let me know what you guys think.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: redacted
  user: mqtt
  password: mqtt

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'

go2rtc:
  streams:
    Porch:
      - rtsp://redacted@10.0.0.3:554/Streaming/Channels/101
    Porch_sub:
      - rtsp://redacted@10.0.0.3:554/Streaming/Channels/102 #this is what I am trying to stream to Nest Hub
    Driveway:
      - rtsp://redacted@10.0.0.4:554/Streaming/Channels/101
    Front_Yard:
      - rtsp://redacted@10.0.0.10:554/Streaming/Channels/101
    Laundry_Stairs:
      - rtsp://redacted@10.0.0.5:554/Streaming/Channels/101
    Backyard:
      - rtsp://redacted@10.0.0.6:554/Streaming/Channels/101
    Decking:
      - rtsp://redacted@10.0.0.7:554/Streaming/Channels/101
    Veggie_Garden:
      - rtsp://redacted@10.0.0.8:554/Streaming/Channels/101
    Garage:
      - rtsp://redacted@10.0.0.9:554/Streaming/Channels/101
      
  webrtc:
    candidates:
      - redacted internal ip:8555
      - redacted external dns:8555
cameras:
  Porch:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 0

  Driveway:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        person:
          threshold: 0.7
        car:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 1

  Front_Yard:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Yard
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.75
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 2

  Laundry_Stairs:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Laundry_Stairs
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 3

  Backyard:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 4

  Decking:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Decking
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 5

  Veggie_Garden:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Veggie_Garden
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 6

  Garage:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    ui:
      order: 7

record:
  enabled: true
  events:
    retain:
      default: 30

rtmp:
  enabled: False

birdseye:
  enabled: True
  mode: continuous

logger:
  default: info

timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Hikvision 4k
