### ISSUE TITLE
[Support]: Frigate Recordings Sometimes Last Hours

### ISSUE THREAD

**Issue by leacho73** [blakeblackshear/frigate#7160]
### Describe the problem you are having

The odd recording that happens following a detection can sometime record and show 'in progress' for hours on end. Whilst most recordings are clipped correctly - I find that the recordings stretching into hours sometimes contain multiple detections and make it hard to view what's actually happened.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: <redacted>
  user: <redacted>
  password: <redacted>
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'
 
detectors:
  coral:
    type: edgetpu
    device: usb

#Global Object Settings
objects:
  track:
    - person
    - car
    - lorry
    - sheep
    - cat
    - dog
  filters:
    person:
      min_area: 5000
      max_area: 100000

cameras:
  front_garden:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/101
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640 
      height: 360 
      fps: 5
    snapshots:
      enabled: True
      required_zones:
        - track_and_drive
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10    
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
          - lorry
          - sheep
          - cat
          - dog
        required_zones:
          - track_and_drive
    mqtt:
      required_zones:
        - track_and_drive
    zones:
      track_and_drive:
        coordinates: 445,0,399,0,373,25,354,38,319,54,269,65,246,72,213,88,190,102,161,121,124,148,83,170,65,196,52,216,44,228,0,293,0,331,66,302,88,360,509,360,531,316,600,178,493,142,492,0
        objects:
          - person
          - car
          - lorry
          - sheep
          - dog
          - cat
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
  back_garden_office:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/101
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/101
          roles:
            - detect
    detect:
      width: 1920 
      height: 1080 
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - sheep
      filters:
        person:
          threshold: 0.8
          min_area: 5000
          max_area: 100000
    snapshots:
      enabled: True
      required_zones:
        - back_garden_office_zone
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - sheep
          - cat
        required_zones:
          - back_garden_office_zone
    mqtt:
      required_zones:
        - back_garden_office_zone
    zones:
      back_garden_office_zone:
        coordinates: 731,565,631,1080,726,1080,802,1080,905,1080,1007,1080,1114,1080,1195,1080,1276,1080,1305,1049,1313,1028,1205,913,1222,833,1234,771,1242,738,1256,674,1267,639,1290,578,1306,502,1311,455,1296,424,1246,394,1214,374,1195,340,1174,308,1164,282,1140,238,1146,218,1153,185,1143,145,1119,144,1061,133,1052,112,1052,76,1039,76,995,74,948,74,926,112,923,145,914,170,888,176,836,177,794,176,732,202,677,214,644,245,619,290,613,339,636,380,643,439,671,599,645,652,565,715,459,812,357,902,294,1011,354,1080,648,1080
        objects:
          - person
          - sheep
          - dog
          - cat
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
  back_garden_back_door:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/101
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/101
          roles:
            - detect
    detect:
      width: 1920 
      height: 1080 
      fps: 5
    objects:
      track:
        - person
        - sheep
        - dog
        - cat
      filters:
        person:
          threshold: 0.8
          min_area: 5000
          max_area: 100000
    snapshots:
      enabled: True
      required_zones:
        - back_garden_back_door_zone
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - sheep
          - cat
        required_zones:
          - back_garden_back_door_zone
    mqtt:
      required_zones:
        - back_garden_back_door_zone
    zones:
      back_garden_back_door_zone:
        coordinates: 1416,1080,1408,1030,1397,1001,1389,965,1371,899,1366,843,1344,740,1324,696,1333,650,1383,619,1458,632,1512,701,1564,764,1589,848,1607,906,1620,974,1640,1056,1755,1080,1832,1031,1896,970,1891,893,1890,818,1920,726,1920,659,1881,584,1831,559,1758,515,1661,463,1584,443,1453,425,1370,417,1294,404,1240,402,1212,401,1138,418,1128,649,984,705,852,481,788,444,743,401,664,351,578,296,525,293,493,307,438,331,392,342,336,358,293,382,283,417,315,456,336,477,381,484,420,527,445,584,465,625,426,683,363,719,402,803,424,867,583,1080,971,1080,1275,1080
        objects:
          - person
          - sheep
          - dog
          - cat
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
  inside_garage:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/101
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://<redacted>@<redacted>/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640 
      height: 360 
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.8
          min_area: 5000
          max_area: 100000
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
```

### Relevant log output

```shell
no logged events
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision - Various
