### ISSUE TITLE
[Config Support]: No audio for webrtc with Reolink camera

### ISSUE THREAD

**Issue by silentnyte** [blakeblackshear/frigate#7161]
### Describe the problem you are having

I am sure that I have something configured wrong but I am not able to get audio to play from the Frigate dashboard with webrtc selected. When I select mse the audio works.

### Version

0.12.1-367D724

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.40:15000/api/config/schema

mqtt:
  host: 192.168.1.42
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  #user: '{FRIGATE_MQTT_USER}'
  #password: '{FRIGATE_MQTT_PASSWORD}'

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264 #preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy #preset-record-generic

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  format: "%Y/%m/%d %H:%M:%S"

detect:
  width: 640
  height: 360
  fps: 7

record:
  enabled: True
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 10

snapshots:
  enabled: True

motion:
  mask:
    #date/time
    - 205,335,205,360,0,360,0,335

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog

birdseye:
  enabled: False

go2rtc:
  streams:
    driveway_camera:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.2.101:554//h264Preview_01_main
      - "ffmpeg:driveway_camera#audio=opus"
    backyard_camera:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.2.102:554//h264Preview_01_main
      - "ffmpeg:backyard_camera#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.40:25555
      #- stun:25555

cameras:
  driveway_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.2.101:554//h264Preview_01_sub
          roles:
            - detect
            #- rtmp

    motion:
      mask:
        #date/time
        - 205,335,205,360,0,360,0,335
        #road
        - 0,0,0,65,80,40, 160,25, 260,10, 325,20,400,25,500,60,580,90,640,0

    objects:
      filters:
        car:
          mask:
            - 0,0,0,360,640,360,640,0,500,0,500,90,400,90,325,60,325,0

    zones:
      driveway_zone_entrance:
        coordinates: 400,25,500,60,500,90,400,90,325,60,325,20
        objects:
          - car
      driveway_zone_upper:
        coordinates: 135,105,400,360,640,360,640,130,500,90,400,90,325,60,250,80
        objects:
          - person
          - dog
      driveway_zone_lower_north:
        coordinates: 260,10,325,20,325,60,250,80,160,25
        objects:
          - person
      driveway_zone_lower_south:
        coordinates: 80,40,160,25,250,80,135,105
        objects:
          - person
      driveway_zone_sideyard:
        coordinates: 0,65,0,185,165,140,80,40
        objects:
          - person

  backyard_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.2.102:554//h264Preview_01_sub
          roles:
            - detect
            #- rtmp
            
    motion:
      mask:
        #date/time
        - 205,335,205,360,0,360,0,335

    objects:
      track:
        - person
        - dog
      mask:
        - 40,160,160,160,160,120,40,120
```

### Relevant log output

```shell
2023-07-14 15:33:25.785416139  [INFO] Starting Frigate...
2023-07-14 15:33:26.805040278  [2023-07-14 11:33:26] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-07-14 15:33:26.829361168  [2023-07-14 11:33:26] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-07-14 15:33:26.831779028  [2023-07-14 11:33:26] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-07-14 15:33:26.833454452  [2023-07-14 11:33:26] peewee_migrate                 INFO    : Starting migrations
2023-07-14 15:33:26.836992111  [2023-07-14 11:33:26] peewee_migrate                 INFO    : There is nothing to migrate
2023-07-14 15:33:26.852533898  [2023-07-14 11:33:26] detector.ov                    INFO    : Starting detection process: 285
2023-07-14 15:33:26.853255157  [2023-07-14 11:33:26] frigate.app                    INFO    : Output process started: 287
2023-07-14 15:33:26.855757851  [2023-07-14 11:33:26] frigate.app                    INFO    : Camera processor started for driveway_camera: 289
2023-07-14 15:33:26.858817745  [2023-07-14 11:33:26] frigate.app                    INFO    : Camera processor started for backyard_camera: 290
2023-07-14 15:33:26.861908036  [2023-07-14 11:33:26] frigate.app                    INFO    : Capture process started for driveway_camera: 291
2023-07-14 15:33:26.864830851  [2023-07-14 11:33:26] frigate.app                    INFO    : Capture process started for backyard_camera: 293
2023-07-14 15:33:27.226066302  [2023-07-14 11:33:27] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-07-14 15:33:27.226069574  [2023-07-14 11:33:27] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-07-14 15:33:27.226073396  [2023-07-14 11:33:27] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### Frigate stats

```json
{"backyard_camera":{"camera_fps":7.0,"capture_pid":293,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":298,"pid":290,"process_fps":7.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.6"},"1":{"cpu":"0.0","mem":"0.0"},"108":{"cpu":"5.6","mem":"0.5"},"117":{"cpu":"0.0","mem":"0.0"},"124":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"1969":{"cpu":"0.0","mem":"0.0"},"2008":{"cpu":"0.3","mem":"0.0"},"2014":{"cpu":"0.3","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"278":{"cpu":"0.0","mem":"0.3"},"28":{"cpu":"0.0","mem":"0.0"},"284":{"cpu":"0.0","mem":"0.0"},"285":{"cpu":"0.0","mem":"1.2"},"287":{"cpu":"1.0","mem":"0.3"},"289":{"cpu":"1.0","mem":"0.3"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"1.3","mem":"0.3"},"291":{"cpu":"1.7","mem":"0.3"},"293":{"cpu":"1.3","mem":"0.3"},"297":{"cpu":"0.0","mem":"0.0"},"298":{"cpu":"2.0","mem":"0.1"},"30":{"cpu":"0.0","mem":"0.0"},"303":{"cpu":"0.0","mem":"0.0"},"307":{"cpu":"2.7","mem":"0.1"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"326":{"cpu":"4.3","mem":"0.1"},"336":{"cpu":"4.3","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"83":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"27.2","mem":"0.1"},"94":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"1366.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"ov":{"detection_start":0.0,"inference_speed":17.43,"pid":285}},"driveway_camera":{"camera_fps":7.0,"capture_pid":291,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":307,"pid":289,"process_fps":7.0,"skipped_fps":0.0},"gpu_usages":{"intel-qsv":{"gpu":"0.46 %","mem":"- %"}},"service":{"last_updated":1689350037,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":65.2,"mount_type":"tmpfs","total":67.1,"used":1.9},"/media/frigate/clips":{"free":3980057.0,"mount_type":"zfs","total":4138125.0,"used":158068.0},"/media/frigate/recordings":{"free":3980057.0,"mount_type":"zfs","total":4138125.0,"used":158068.0},"/tmp/cache":{"free":161293.5,"mount_type":"overlay","total":171097.8,"used":9804.3}},"temperatures":{},"uptime":1231,"version":"0.12.1-367d724"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)
