### ISSUE TITLE
[Config Support]: No Audio in events video

### ISSUE THREAD

**Issue by moskovskiy82** [blakeblackshear/frigate#7168]
### Describe the problem you are having

No Audio in events video.
The stream from go2rtc got one and there is audio in the camera view of frigate. But no audio is being recorded in the events video although have followed the FAQ section and added 

  output_args:
    record: preset-record-generic-audio-aac

Opening using VLC the rtsp stream from go2rtc - i get the following for audio

MPEG AAC Audio (mp4a)
Audio
Stereo
8000Hz
32bit

### Version

12.1

### Frigate config file

```yaml
Partially skipped other configs


logger:
  default: error

detectors:
  coral:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args:
    - '-avoid_negative_ts'
    - make_zero
    - '-fflags'
    - nobuffer
    - '-flags'
    - low_delay
    - '-strict'
    - experimental
    - '-fflags'
    - +genpts+discardcorrupt
    - '-rw_timeout'
    - '5000000'

    roads:
      - "rtsp://SOME_URL"
      - "ffmpeg:roads#audio=aac"

cameras:
  roads:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/roads?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
```

### Relevant log output

```shell
Nothing

2023-07-15 14:44:49.043773065  [INFO] Starting Frigate...
2023-07-15 14:44:50.627339533  [2023-07-15 14:44:50] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe
