### ISSUE TITLE
Nothing being published to MQTT

### ISSUE THREAD

**Issue by unclebacon-live** [blakeblackshear/frigate#717]
I hope this isn't a repeat issue and is probably user error but I just can't get anything to publish to MQTT and therefore get no automations in HA:
```
detectors:
  coral:
    type: cpu
mqtt:
  host: <local ip of HA with Mosquitto addon installed>
  port: 1883
  stats_interval: 60
ffmpeg: {}
cameras:
  front:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://***:***@<camera ip>:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    width: 1280
    height: 720
    fps: 5
    best_image_timeout: 60
    detect:
      enabled: true
      max_disappeared: 10
    rtmp:
      enabled: false
    snapshots:
      enabled: false
      timestamp: true
      bounding_box: true
      crop: true
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
...
logger:
  default: debug
  logs:
    frigate.mqtt: debug
```

The log shows that MQTT is connected:
`frigate.mqtt                   INFO    : MQTT connected`

But even with the logs set for debug I get nothing more from `frigate.mqtt` even when an event is captured. The event just gets posted to `peewee.sqliteq` with all the data and thumbnail.

Appreciate any help!
