### ISSUE TITLE
Cannot send snapshot with mosquito 

### ISSUE THREAD

**Issue by luke2023** [blakeblackshear/frigate#7173]
### Describe the problem you are having

Hi, I am using frigate in home assistant , I can get snapshots and events with people’s public server , but I can only get events with my own mosquito server. I tried to send snapshot to public server ,node red  and to mosquito, so I confirmed that my broker can send large files.

### Version

Latest home’s assistant addon

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mqttgo.io
  
cameras:
  tapo_c200_1_hd: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      stream you want to use for
          roles:
            - detect
        - path: record from
          roles:
            - record
    

      
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
         default: 3
         mode: active_objects
    snapshots: # <----- Enable snapshots
      enabled: True
```

### Relevant log output

```shell
No error or Mqtt logs
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
