### ISSUE TITLE
[Config Support]: Object detection boxes in birdseye

### ISSUE THREAD

**Issue by turboc1208** [blakeblackshear/frigate#7175]
### Describe the problem you are having

I am just getting started out with frigate.  Is it possible to get the object detection boxes to show in the object detection mode of birdseye?

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.2.20
  port: 1883
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  #user: mqtt_user
  #password: password
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  #tls_insecure: false
  stats_interval: 60

detectors:
  # Required: name of the detector
  Coral:
    # Required: type of the detector
    # Frigate provided types include 'cpu', 'edgetpu', and 'openvino' (default: shown below)
    # Additional detector types can also be plugged in.
    # Detectors may require additional configuration.
    # Refer to the Detectors configuration page for more information.
    type: edgetpu

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

# Optional: logger verbosity settings
logger:
  default: info
  logs:
    frigate.event: debug

# Optional: set environment variables
environment_vars:
  EXAMPLE_VAR: value

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic
  output_args:
    # Optional: output args for detect streams (default: shown below)
#    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic


snapshots:
  enabled: False
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 175
  required_zones: []
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

# Optional: Restream configuration
go2rtc:
  streams:
    sunroom: rtsp://admin:plough@192.168.2.31:554/h264Preview_01_main
    sunroom2: rtsp://admin:plough@192.168.2.31:554/h264Preview_01_sub
    hvac: rtsp://admin:plough@192.168.2.30:554/h264Preview_01_main
    hvac2: rtsp://admin:plough@192.168.2.30:554/h264Preview_01_sub
    #shed: rtsp://admin:plough@192.168.2.34:554/h264Preview_01_main
    driveway: rtsp://admin:Plough@192.168.2.37:554/h264Preview_01_main
    driveway2: rtsp://admin:Plough@192.168.2.37:554/h264Preview_01_sub
    doorbell: rtsp://admin:Plough@192.168.2.41:554/h264Preview_01_main
    doorbell2: rtsp://admin:Plough@192.168.2.41:554/h264Preview_01_sub
    drivewaygate: rtsp://admin:plough@192.168.2.39:554/h264Preview_01_main
    drivewaygate2: rtsp://admin:plough@192.168.2.39:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.2.25:8555
      - stun:8555

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - bicycle
    - motorcycle
    - bus
    - boat
# Optional: jsmpeg stream configuration for WebUI
#live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
#  stream_name: main
#  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "solid"

detect:
  enabled: True
  width: 640
  height: 480
  fps: 5
 
# Required
cameras:
  # Required: name of the camera
  driveway:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway2
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      enabled: True
#      width: 640
#      height: 480
    motion:
      mask:
        - 0,720,322,720,304,657,233,616,186,549,82,550,43,211,166,80,169,0,0,0
        - 1280,181,1280,0,171,0,170,57
    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - car
          - bicycle
          - motorcycle
          - bus
          - boat
        retain:
          default: 10
    live:
      stream_name: driveway
  drivewaygate:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/drivewaygate
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drivewaygate2
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      width: 640
#      height: 480
#      enabled: True
    motion:
      mask:
        - 1259,354,1224,0,1280,0,1280,720,1194,720
        - 0,330,149,321,430,370,604,384,603,333,1280,250,1235,55,224,53,0,50
    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - car
          - bicycle
          - motorcycle
          - bus
          - boat
        retain:
          default: 10
    live:
      stream_name: drivewaygate
  sunroom:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/sunroom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sunroom2
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      enabled: true
#      width: 640
#      height: 480
    motion:
      mask:
        - 0,82,830,55,1280,183,1280,0,0,0
        - 1280,181,1280,0,171,0,170,57
    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - car
          - bicycle
          - motorcycle
          - bus
          - boat
        retain:
          default: 10
    live:
      stream_name: sunrooom
  hvac:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/hvac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hvac2
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      enabled: true
#      width: 640
#      height: 480
    motion:
      mask:
        - 452,52,860,64,1280,148,1280,0,0,0,0,119,106,83,356,32
        - 1280,181,1280,0,171,0,170,57
    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - car
          - bicycle
          - motorcycle
          - bus
          - boat
        retain:
          default: 10
    live:
      stream_name: hvac
  doorbell:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell2
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      enabled: true
#      width: 640
#      height: 480
    motion:
      mask:
        - 0,122,94,144,211,106,472,79,493,149,469,404,499,480,640,480,640,0,0,0
        - 1280,181,1280,0,171,0,170,57
    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - car
          - bicycle
          - motorcycle
          - bus
          - boat
        retain:
          default: 10
    live:
      stream_name: doorbell
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  use_experimental: False
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"

birdseye:
  enabled: True
  mode: objects

# Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant log output

```shell
none
```

### Frigate stats

```json
{
"cpu_usages": {
"1": {
"cpu": "0.0",
"mem": "0.0"
},
"15": {
"cpu": "0.0",
"mem": "0.0"
},
"16": {
"cpu": "0.0",
"mem": "0.0"
},
"24": {
"cpu": "0.0",
"mem": "0.0"
},
"25": {
"cpu": "0.0",
"mem": "0.0"
},
"26": {
"cpu": "0.0",
"mem": "0.0"
},
"27": {
"cpu": "0.0",
"mem": "0.0"
},
"28": {
"cpu": "0.0",
"mem": "0.0"
},
"29": {
"cpu": "0.0",
"mem": "0.0"
},
"30": {
"cpu": "0.0",
"mem": "0.0"
},
"31": {
"cpu": "0.0",
"mem": "0.0"
},
"32": {
"cpu": "0.0",
"mem": "0.0"
},
"41": {
"cpu": "0.0",
"mem": "0.0"
},
"42": {
"cpu": "0.0",
"mem": "0.0"
},
"80": {
"cpu": "0.0",
"mem": "0.0"
},
"81": {
"cpu": "0.0",
"mem": "0.0"
},
"82": {
"cpu": "0.0",
"mem": "0.0"
},
"101": {
"cpu": "17.6",
"mem": "0.1"
},
"109": {
"cpu": "0.0",
"mem": "0.0"
},
"110": {
"cpu": "2.9",
"mem": "0.5"
},
"117": {
"cpu": "0.0",
"mem": "0.0"
},
"134": {
"cpu": "0.0",
"mem": "0.0"
},
"135": {
"cpu": "0.0",
"mem": "0.0"
},
"136": {
"cpu": "0.0",
"mem": "0.0"
},
"137": {
"cpu": "0.0",
"mem": "0.0"
},
"282": {
"cpu": "0.0",
"mem": "0.0"
},
"288": {
"cpu": "0.3",
"mem": "0.0"
},
"289": {
"cpu": "0.0",
"mem": "0.0"
},
"291": {
"cpu": "0.7",
"mem": "0.1"
},
"294": {
"cpu": "0.7",
"mem": "0.0"
},
"295": {
"cpu": "0.0",
"mem": "0.0"
},
"296": {
"cpu": "0.7",
"mem": "0.0"
},
"297": {
"cpu": "0.7",
"mem": "0.0"
},
"298": {
"cpu": "0.0",
"mem": "0.0"
},
"299": {
"cpu": "0.7",
"mem": "0.0"
},
"301": {
"cpu": "0.0",
"mem": "0.0"
},
"303": {
"cpu": "1.0",
"mem": "0.0"
},
"305": {
"cpu": "0.0",
"mem": "0.0"
},
"306": {
"cpu": "1.0",
"mem": "0.0"
},
"308": {
"cpu": "0.7",
"mem": "0.0"
},
"311": {
"cpu": "0.0",
"mem": "0.0"
},
"312": {
"cpu": "1.0",
"mem": "0.0"
},
"313": {
"cpu": "4.6",
"mem": "0.1"
},
"314": {
"cpu": "0.0",
"mem": "0.1"
},
"319": {
"cpu": "0.0",
"mem": "0.0"
},
"322": {
"cpu": "3.9",
"mem": "0.1"
},
"323": {
"cpu": "5.2",
"mem": "0.1"
},
"327": {
"cpu": "0.0",
"mem": "0.0"
},
"332": {
"cpu": "1.0",
"mem": "0.0"
},
"333": {
"cpu": "1.6",
"mem": "0.0"
},
"334": {
"cpu": "4.6",
"mem": "0.1"
},
"341": {
"cpu": "1.3",
"mem": "0.0"
},
"347": {
"cpu": "0.3",
"mem": "0.0"
},
"350": {
"cpu": "1.0",
"mem": "0.0"
},
"1893": {
"cpu": "73.9",
"mem": "92.0"
},
"2167": {
"cpu": "0.0",
"mem": "0.0"
},
"2172": {
"cpu": "0.3",
"mem": "0.0"
},
"%Cpu(s):": {
"cpu": "id,",
"mem": "13.0"
},
"MiB": {
"cpu": "33.8",
"mem": "avail"
},
"PID": {
"cpu": "%CPU",
"mem": "%MEM"
},
"Tasks:": {
"cpu": "stopped,",
"mem": "0"
},
"top": {
"cpu": "users,",
"mem": "load"
}
},
"detection_fps": 0,
"detectors": {
"Coral": {
"detection_start": 0,
"inference_speed": 8.83,
"pid": 289
}
},
"doorbell": {
"camera_fps": 105.6,
"capture_pid": 314,
"detection_enabled": 1,
"detection_fps": 0,
"ffmpeg_pid": 1893,
"pid": 301,
"process_fps": 100.9,
"skipped_fps": 0
},
"driveway": {
"camera_fps": 5,
"capture_pid": 303,
"detection_enabled": 1,
"detection_fps": 0,
"ffmpeg_pid": 313,
"pid": 294,
"process_fps": 5,
"skipped_fps": 0
},
"drivewaygate": {
"camera_fps": 5,
"capture_pid": 306,
"detection_enabled": 1,
"detection_fps": 0,
"ffmpeg_pid": 322,
"pid": 296,
"process_fps": 5,
"skipped_fps": 0
},
"gpu_usages": {
"intel-vaapi": {
"gpu": "4.66 %",
"mem": "- %"
}
},
"hvac": {
"camera_fps": 5,
"capture_pid": 312,
"detection_enabled": 1,
"detection_fps": 0,
"ffmpeg_pid": 334,
"pid": 299,
"process_fps": 5,
"skipped_fps": 0
},
"service": {
"last_updated": 1689468315,
"latest_version": "0.12.1",
"storage": {
"/dev/shm": {
"free": 519.4,
"mount_type": "tmpfs",
"total": 524.3,
"used": 4.9
},
"/media/frigate/clips": {
"free": 84152.3,
"mount_type": "ext4",
"total": 105089.3,
"used": 15551.4
},
"/media/frigate/recordings": {
"free": 84152.3,
"mount_type": "ext4",
"total": 105089.3,
"used": 15551.4
},
"/tmp/cache": {
"free": 821.2,
"mount_type": "tmpfs",
"total": 1000,
"used": 178.8
}
},
"temperatures": {},
"uptime": 1815,
"version": "0.12.1-367d724"
},
"sunroom": {
"camera_fps": 5.1,
"capture_pid": 308,
"detection_enabled": 1,
"detection_fps": 0,
"ffmpeg_pid": 323,
"pid": 297,
"process_fps": 5.1,
"skipped_fps": 0
}
}
// 20230715194517
// http://192.168.2.25:5000/api/stats
​
{
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "16": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
