### ISSUE TITLE
Clips not being saved

### ISSUE THREAD

**Issue by dcgrove** [blakeblackshear/frigate#718]
Hello, everything is working except clip saving. My config, docker command, debug output from the web UI, and terminal output are below. 

Docker Command:
```
sudo docker run --rm --name frigate8 --privileged --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 -v /dev/bus/usb:/dev/bus/usb -v /media/10tbextsmb/bigserver/frigate/clips:/media/frigate/clips -v /media/10tbextsmb/bigserver/frigate/recordings:/media/frigate/recordings -v /mnt/tvshows/frigate/database:/media/frigate/database -v /media/10tbextsmb/bigserver/frigate/config:/config:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:0.8.1-amd64
```
config.yml
```
mqtt:
  host: 192.168.1.205
  port: 1883
  user: clayton
  password: XXXXXXX
database: 
  path: /media/frigate/database/frigate.db
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtmp://192.168.1.19/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - clips
        - path: 'rtmp://192.168.1.19/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
    width:  640
    height: 480
    fps:  7
    motion:
      mask:
        - 256,97,640,111,640,0,316,0,0,0,0,189,0,355
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - truck
    - cat
    - dog    
```

Debug Lob:
```
{
  "data": {
    "cameras": {
      "driveway": {
        "best_image_timeout": 60,
        "clips": {
          "enabled": true,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "detect": {
          "enabled": true,
          "max_disappeared": 14
        },
        "ffmpeg_cmds": [
          {
            "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.1.19/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=liza2056 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway-%Y%m%d%H%M%S.mp4",
            "roles": [
              "clips"
            ]
          },
          {
            "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.1.19/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=liza2056 -r 7 -f rawvideo -pix_fmt yuv420p pipe:",
            "roles": [
              "detect"
            ]
          }
        ],
        "fps": 7,
        "frame_shape": [
          480,
          640
        ],
        "height": 480,
        "motion": {
          "contour_area": 100,
          "delta_alpha": 0.2,
          "frame_alpha": 0.2,
          "frame_height": 80,
          "mask": [
            "256,97,640,111,640,0,316,0,0,0,0,189,0,355"
          ],
          "threshold": 25
        },
        "mqtt": {
          "bounding_box": true,
          "crop": true,
          "enabled": true,
          "height": 270,
          "timestamp": true
        },
        "name": "driveway",
        "objects": {
          "filters": {
            "car": {
              "mask": null,
              "max_area": 24000000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "cat": {
              "mask": null,
              "max_area": 24000000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "dog": {
              "mask": null,
              "max_area": 24000000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 24000000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "truck": {
              "mask": null,
              "max_area": 24000000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "track": [
            "person",
            "car",
            "truck",
            "cat",
            "dog"
          ]
        },
        "record": {
          "enabled": false,
          "retain_days": 30
        },
        "rtmp": {
          "enabled": true
        },
        "snapshots": {
          "bounding_box": false,
          "crop": false,
          "enabled": true,
          "height": null,
          "retain": {
            "default": 10,
            "objects": {}
          },
          "timestamp": false
        },
        "width": 640,
        "zones": {}
      }
    },
    "clips": {
      "max_seconds": 300,
      "retain": {
        "default": 10,
        "objects": {}
      },
      "tmpfs_cache_size": ""
    },
    "database": {
      "path": "/media/frigate/database/frigate.db"
    },
    "detectors": {
      "coral": {
        "device": "usb",
        "num_threads": 3,
        "type": "edgetpu"
      }
    },
    "environment_vars": {},
    "logger": {
      "default": "INFO",
      "logs": {}
    },
    "model": {
      "height": 320,
      "width": 320
    },
    "mqtt": {
      "client_id": "frigate",
      "host": "192.168.1.205",
      "port": 1883,
      "stats_interval": 60,
      "topic_prefix": "frigate",
      "user": "clayton"
    },
    "snapshots": {
      "retain": {
        "default": 10,
        "objects": {}
      }
    }
  },
  "status": "loaded"
}
```

Terminal Output:
```
frigate.events                 WARNING : Unable to create clip for driveway and event 1612470831.039399-09vqg9. There were no cache files for this event.
ffmpeg.driveway.clips          ERROR   : Option rtsp_transport not found.
watchdog.driveway              INFO    : Terminating the existing ffmpeg process...
watchdog.driveway              INFO    : Waiting for ffmpeg to exit gracefully...
ffmpeg.driveway.clips          ERROR   : Option rtsp_transport not found.
watchdog.driveway              INFO    : Terminating the existing ffmpeg process...
watchdog.driveway              INFO    : Waiting for ffmpeg to exit gracefully...
ffmpeg.driveway.clips          ERROR   : Option rtsp_transport not found.
watchdog.driveway              INFO    : Terminating the existing ffmpeg process...
watchdog.driveway              INFO    : Waiting for ffmpeg to exit gracefully...
frigate.events                 WARNING : Unable to create clip for driveway and event 1612470856.618348-xkz2a3. There were no cache files for this event.
ffmpeg.driveway.clips          ERROR   : Option rtsp_transport not found.
watchdog.driveway              INFO    : Terminating the existing ffmpeg process...
watchdog.driveway              INFO    : Waiting for ffmpeg to exit gracefully...
```

**Comment by blakeblackshear** [comment]
The issue is that you aren't using the input args for rtmp on the second input. Try this to apply the args to both inputs:
```yaml
mqtt:
  host: 192.168.1.205
  port: 1883
  user: clayton
  password: XXXXXXX
database: 
  path: /media/frigate/database/frigate.db
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtmp://192.168.1.19/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - clips
        - path: 'rtmp://192.168.1.19/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - detect
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
    width:  640
    height: 480
    fps:  7
    motion:
      mask:
        - 256,97,640,111,640,0,316,0,0,0,0,189,0,355
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - truck
    - cat
    - dog    
```

**Comment by dcgrove** [comment]
Thanks, I got this error when trying the file above. 
```
Error parsing config: extra keys not allowed @ data['cameras']['driveway']['ffmpeg']['input_args']
```

config:
```
mqtt:
  host: 192.168.1.205
  port: 1883
  user: clayton
  password: XXXXXXX
database: 
  path: /media/frigate/database/frigate.db
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtmp://192.168.1.19/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - clips
        - path: 'rtmp://192.168.1.19/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - detect
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
    width:  640
    height: 480
    fps:  7
    motion:
      mask:
        - 256,97,640,111,640,0,316,0,0,0,0,189,0,355
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - truck
    - cat
    - dog  
```

**Comment by blakeblackshear** [comment]
Oops. I though that was possible, but looks like I have an inconsistency in the docs.

try this:
```yaml
mqtt:
  host: 192.168.1.205
  port: 1883
  user: clayton
  password: XXXXXXX
database: 
  path: /media/frigate/database/frigate.db
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtmp://192.168.1.19/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - clips
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
        - path: 'rtmp://192.168.1.19/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=liza2056'
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
    width:  640
    height: 480
    fps:  7
    motion:
      mask:
        - 256,97,640,111,640,0,316,0,0,0,0,189,0,355
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - truck
    - cat
    - dog    
```
