### ISSUE TITLE
[Config Support]: Camera enteties are unavailable

### ISSUE THREAD

**Issue by Serhioromano** [blakeblackshear/frigate#7184]
### Describe the problem you are having

I've set up a camera. Camera works fine. I can see live and recordings and snippets. But in HA all entities are unafailable.

![2023-07-16_21-47-27](https://github.com/blakeblackshear/frigate/assets/650741/67be0780-9b79-48d0-9ff7-230e78508b70)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.123
  port: 1883
  user: mqtt
  password: mqtt
  client_id: frigate
  
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    objects:
      - person
    retain:
      default: 7
      mode: active_objects

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True
  retain:
    default: 10

cameras:
  my_office:
    ffmpeg:
      inputs:
        - path: rtsp://admin:123@192.168.1.24/Stream/Channels/102
          roles:
            - detect
            - record
    snapshots:
      required_zones:
        - zone_0
    record:
      events:
        required_zones:
          - zone_0
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 15
    motion:
      mask:
        - 92,115,205,183,276,158,418,0,640,0,640,360,0,360,0,218
    zones:
      zone_0:
        coordinates: 365,0,348,125,245,213,143,170,86,0
```

### Relevant log output

```shell
All logs looks fine. I do not know what logs to place here exactly.
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.0"},"1":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"1.0","mem":"0.5"},"118":{"cpu":"0.0","mem":"0.0"},"122":{"cpu":"0.0","mem":"0.0"},"123":{"cpu":"0.0","mem":"0.0"},"124":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"14":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"1706":{"cpu":"0.0","mem":"0.0"},"1728":{"cpu":"0.0","mem":"0.0"},"1731":{"cpu":"0.0","mem":"0.0"},"1735":{"cpu":"0.0","mem":"0.0"},"23":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"39":{"cpu":"0.0","mem":"0.0"},"403":{"cpu":"0.0","mem":"0.2"},"409":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"410":{"cpu":"0.0","mem":"0.3"},"411":{"cpu":"0.3","mem":"0.3"},"413":{"cpu":"0.7","mem":"0.3"},"414":{"cpu":"1.0","mem":"0.3"},"419":{"cpu":"0.0","mem":"0.1"},"421":{"cpu":"0.0","mem":"0.1"},"422":{"cpu":"24.6","mem":"0.2"},"76":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"83":{"cpu":"0.0","mem":"0.0"},"92":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"15567.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":354.57,"pid":410}},"my_office":{"camera_fps":15.0,"capture_pid":414,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":422,"pid":413,"process_fps":15.0,"skipped_fps":0.0},"service":{"last_updated":1689522924,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":133.2,"mount_type":"tmpfs","total":134.2,"used":1.0},"/media/frigate/clips":{"free":536814.2,"mount_type":"zfs","total":536870.9,"used":56.8},"/media/frigate/recordings":{"free":536814.2,"mount_type":"zfs","total":536870.9,"used":56.8},"/tmp/cache":{"free":997.1,"mount_type":"tmpfs","total":1000.0,"used":2.9}},"temperatures":{},"uptime":1656,"version":"0.12.1-367d724"}}
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

I've set up a camera. Camera works fine. I can see live and recordings and snipets. But in HA all entities are unafailable.

![2023-07-16_21-47-27](https://github.com/blakeblackshear/frigate/assets/650741/67be0780-9b79-48d0-9ff7-230e78508b70)

I suspect that it is connected to MQTT but I do not know how to debug it. I think there is no connection somehow. But I tested and i can connect to MQTT from command line.
