### ISSUE TITLE
[Config Support]: My Rasp Pi2b support 0.12?

### ISSUE THREAD

**Issue by yuhuanfan** [blakeblackshear/frigate#7191]
### Describe the problem you are having

Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
前端版本： 20230705.1 - latest

32bit system 
Frigate NVR (Full Access) 0.10.1
 And can you check my config file,it`s work fine.
Go2rtc(1.6)>>>>Frigate (0.10.1)
Something optimize?

### Version

0.10.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.157
  port: 1883
  user: yuhuanfan
  password: password
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 10

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects

detectors:
  cpu1:
    type: cpu
    num_threads: 3

cameras:
  camera_1:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_mmal
      inputs:
        - path: rtsp://192.168.10.157:8554/rtmp
          roles:
            - record
            - detect
    rtmp:
      enabled: False
      
    detect:
      fps: 5

    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 14
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
    
    snapshots:
      enabled: True

    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.30
          threshold: 0.50
          mask:
            - 493,0,534,388,591,335,563,0
            - 1222,675,1226,699,913,699,914,676
            - 1280,0,1280,720,1007,720,1116,0
            - 315,720,148,720,0,307,0,0,458,0,490,260
          
    zones:
      1105:
        coordinates: 1280,720,1280,0,815,0,752,260,576,271,498,0,0,0,0,720
        objects:
          - person
        filters:
          person:
            min_score: 0.30
            threshold: 0.50

      1103:
        coordinates: 766,0,548,0,574,266,782,257
        objects:
          - person
        filters:
          person:
            min_score: 0.30
            threshold: 0.50
 

    timestamp_style:
      position: "bl"
      format: "%H:%M:%S"
      color:
        red: 255
        green: 255
        blue: 255
      thickness: 5
      effect: "shadow"
    
    motion:
      threshold: 30
      mask:
        - 1222,675,1226,699,913,699,914,676
        - 1280,0,1280,720,1007,720,1116,0
        - 315,720,148,720,0,307,0,0,458,0,490,260
```

### Relevant log output

```shell
empty
```

### Frigate stats

```json
working good
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
