### ISSUE TITLE
Notable difference in CPU consumption in tapo C320WS

### ISSUE THREAD

**Issue by MagoPoza** [blakeblackshear/frigate#7209]
### Describe the problem you are having

I have bought 3 TAPO C320WS cameras, the hardware version of all three is 2.0.
In one of them I have updated the firmware to version 1.0.5 Build 230316 Rel.55457n, in the other 2 I have kept it in version 1.0.4 Build 221031 Rel.40874n.
The ones I've kept on version 1.0.4 have 13-14% CPU consumption (excellent), but the camera I've updated to version 1.0.5 has shot CPU consumption to 39-43%.
In all of them I use the same configuration.

![Cámaras](https://github.com/blakeblackshear/frigate/assets/63115455/4f8fd995-fd43-4a17-bf58-a9a8cb06b7bf)

### Version

0.12.1

### Frigate config file

```yaml
# mqtt
mqtt:
  host: 192.168.x.xxx
  user: xxxxx
  password: xxxxxxx

# Declarar coral
detectors:
  coral:
    type: edgetpu
    device: usb

# Activar aceleración de hardware
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

# Declarar cámaras
go2rtc:
  streams:
    camara_entrada:
      - rtsp://user:password@192.168.x.xx:554/stream1
    camara_entrada_2:
      - rtsp://user:password@192.168.x.xx:554/stream1
    camara_patio:
      - rtsp://user:password@192.168.x.xx:554/stream1
    camara_patio_2:
      - rtsp://user:password@192.168.x.xx:554/stream1
    camara_lateral_derecho:
      - rtsp://user:password@192.168.x.xx:554/stream1
  
  webrtc: 
    candidates: 
      - 192.168.x.xx:8555 

# Configuración cámara entrada 1
cameras:
  camara_entrada:
    ffmpeg:
      input_args: -c:v h264_v4l2m2m
      output_args: 
        record: preset-record-generic
      inputs:
        - path: rtsp://user:password@192.168.x.xx:554/stream1
          roles:
            - record
            - detect
    detect: 
      width: 1280
      height: 720
      
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle 

      filters:
        person:
          min_area: 3000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
        car:
          mask:
            - 1280,0,1280,720,864,720,470,602,757,0
        motorcycle:
          mask:
            - 1280,0,1280,720,864,720,470,602,757,0
    motion:
      mask:
        - 1280,0,1280,59,1132,0

    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 1
        objects:
          person: 10

    zones:
      zona_matriculas:
        coordinates: 31,235,550,320,642,0,194,0
        objects:
          - car
          - motorcycle

# Configuración cámara entrada 2

  camara_entrada_2:
    ffmpeg:
      input_args: preset-rtsp-generic
      output_args: 
        record: preset-record-generic
      inputs:
        - path: rtsp://user:password@192.168.x.xx:554/stream1
          roles:
            - record
            - detect
    detect: 
      width: 1280
      height: 720
      
    objects:
      track:
        - person
        - car
        - bicycle 

      filters:
        person:
          min_area: 2800
          max_area: 300000
          min_score: 0.5
          threshold: 0.7
        bicycle :
          mask:
            - 126,327,831,224,866,0,116,0
        car:
          mask:
            - 697,0,687,213,120,237,130,0

    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 1
        objects:
          person: 10

# Configuración cámara patio

  camara_patio:
    ffmpeg:
      input_args: preset-rtsp-generic
      output_args: 
        record: preset-record-generic
      inputs:
        - path: rtsp://user:password@192.168.x.xx:554/stream1
          roles:
            - record
            - detect
    detect: 
      width: 1280
      height: 720
      
    objects:
      track:
        - person

    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 1
        objects:
          person: 10

# Configuración cámara patio 2

  camara_patio_2:
    ffmpeg:
      input_args: preset-rtsp-generic
      output_args: 
        record: preset-record-generic
      inputs:
        - path: rtsp://user:password@192.168.x.xx:554/stream1
          roles:
            - record
            - detect
    detect: 
      width: 1280
      height: 720
      
    objects:
      track:
        - person

    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 1
        objects:
          person: 10

# Configuración cámara lateral derecho

  camara_lateral_derecho:
    ffmpeg:
      input_args: preset-rtsp-generic
      output_args: 
        record: preset-record-generic
      inputs:
        - path: rtsp://user:password@192.168.x.xx:554/stream1
          roles:
            - record
            - detect
    detect: 
      width: 1280
      height: 720
      
    objects:
      track:
        - person

    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 1
        objects:
          person: 10
```

### Relevant log output

```shell
nothing relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
