### ISSUE TITLE
[Camera Support]: IPD-E2A5L18 Strange Onvif error

### ISSUE THREAD

**Issue by exalented** [blakeblackshear/frigate#7218]
### Describe the problem you are having

1. I am trying to get PTZ working
2. Video streams work fine.
3. My camera is on a different subnet (however I've used a tcp/udp proxy as well as iptables to communicate over a VPN)
4. Frigate hangs the webui when I try to use ptz buttons and throws this weird error from the docker container regarding OnvifVersion?
5. Onvier on Android works fine for controlling PTZ.
6. I wrote my own 'pan.sh' which POSTs to `'http://'$addr':'$port'/form/setPTZCfg'` in order to achieve PTZ.

### Version

0.13.0-83006ee or image: ghcr.io/blakeblackshear/frigate:dev-83006ee-tensorrt

### Relevant Frigate config file keys

```yaml
onvif:                                                        
    host: 10.0.0.5                                       
    port: 8999                                                
    user: admin                                            
    password: "password"

logger:                                                                              # 
    Optional: default log level (default: shown below)                               
    default: debug                                                                     # Optional: module by module log level configuration                               
    logs:                                                                                
        frigate.mqtt: debug
```

### Relevant log output

```shell
frigate  | time time  [time] zeep.xsd.schema
DEBUG   : register_type('{http://www.onvif.org/ver10/schema}OnvifVersion', <zeep.xsd.dynamic_types.OnvifVersion object at 0x7f4830c71bb0>)
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{"IPD-E2A5L18":{"camera_fps":5.0,"capture_pid":754,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":759,"pid":751,"process_fps":5.0,"skipped_fps":0.0},"ELP-1881":{"camera_fps":0.0,"capture_pid":757,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1406,"pid":752,"process_fps":0.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.1"},"139":{"cpu":"0.0","mem":"0.0"},"1394":{"cpu":"0.0","mem":"0.0"},"140":{"cpu":"0.0","mem":"0.0"},"141":{"cpu":"0.0","mem":"0.0"},"1411":{"cpu":"0.0","mem":"0.0"},"1413":{"cpu":"0.0","mem":"0.0"},"142":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"155":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"177":{"cpu":"0.0","mem":"0.0"},"211":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"247":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"292":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"341":{"cpu":"0.0","mem":"0.0"},"378":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"415":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"436":{"cpu":"0.0","mem":"0.0"},"458":{"cpu":"0.0","mem":"0.0"},"495":{"cpu":"0.0","mem":"0.0"},"531":{"cpu":"0.0","mem":"0.0"},"720":{"cpu":"0.0","mem":"1.1"},"732":{"cpu":"0.0","mem":"1.3"},"741":{"cpu":"0.0","mem":"0.1"},"742":{"cpu":"0.0","mem":"1.3"},"747":{"cpu":"0.0","mem":"1.3"},"750":{"cpu":"0.0","mem":"0.3"},"751":{"cpu":"0.0","mem":"1.2"},"752":{"cpu":"0.0","mem":"1.2"},"753":{"cpu":"0.0","mem":"0.1"},"754":{"cpu":"0.3","mem":"1.2"},"757":{"cpu":"0.0","mem":"1.2"},"759":{"cpu":"3.7","mem":"0.2"},"762":{"cpu":"0.0","mem":"0.1"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.1"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"0.0","mem":"2.7"},"MiB":{"cpu":"6705.3","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":24.79,"pid":742}},"service":{"last_updated":1689751385,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":64.7,"mount_type":"tmpfs","total":67.1,"used":2.4},"/media/frigate/clips":{"free":99472.3,"mount_type":"ext4","total":983206.4,"used":833715.0},"/media/frigate/recordings":{"free":99472.3,"mount_type":"ext4","total":983206.4,"used":833715.0},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":718,"version":"0.13.0-83006ee"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Jidtech IPD-E2A5L18 PTZ POE 20X (don't buy this camera)
