### ISSUE TITLE
[Support]: Mask creator in debug mode doesn't do anything

### ISSUE THREAD

**Issue by duro** [blakeblackshear/frigate#7240]
### Describe the problem you are having

I have tried this on my Ubuntu Desktop running Firefox, and my mac running Chrome. Same behavior. When I load the mask creator, and I click on the video frame, I see no points drawn, nor any config change. Here is a video if it helps:

https://www.loom.com/share/e05f6fd409b44964b75e307461e382ae?sid=6a125145-f320-46ff-b584-474d1f2ed297

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: homeassistant.lan
  user: frigate
  password: XXXXX

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
  camera1: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://admin:XXXXX@192.168.2.10:554/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2592 # <---- update for your camera's resolution
      height: 1944 # <---- update for your camera's resolution
  camera2: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://admin:XXXXXX@192.168.2.11:554/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2592 # <---- update for your camera's resolution
      height: 1944 # <---- update for your camera's resolution
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW-28MM and IP5M-B1186EW-28MM

### Any other information that may be helpful

https://www.loom.com/share/e05f6fd409b44964b75e307461e382ae?sid=6a125145-f320-46ff-b584-474d1f2ed297
