### ISSUE TITLE
[Detector Support]: Not getting close to 100fps detection rate with coral

### ISSUE THREAD

**Issue by jordankoehn** [blakeblackshear/frigate#7247]
### Describe the problem you are having

The docs state 'With an inference speed of 10, your Coral will top out at 1000/10=100, or 100 frames per second'.  I'm not seeing this in practice. Taking 16 [mp4 files](https://viratdata.org/) that have continually active motion, downsampling them to 5fps before loading in frigate, and setting detection fps to 5, you'd expect a solid 16*5=80fps of processing. Here is my results

| Num Corals | Max Process fps | Avg Process fps | Max Skipped fps | Avg Skipped fps | Max detection fps | Avg detection fps | Max Inference Speed | Avg Inference Speed | Max CPU | Avg CPU | Max GPU | Avg GPU | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1  | 4.6 | 2.38 | 4.2 | 2.19 | 145 | 135 | 6.75 | 6.59 | 81.9 | 77 | 1.25 | 0.95 |
| 2  | 5.0 | 3.6 | 3.4 | 1.05 | 272 | 236 | 7.04 | 6.65 | 89.5 | 84.68 | 1.2 | 0.83 |
| 3  | 5.4 | 4.34 | 1.9 | 0.32 | 373 | 308 | 7.91 | 7.13 | 95 | 88.6 | 1.24 | 0.83 |

it seems that "detection fps" correlates pretty closely with this 1000/${inference time} number. However, it's hard to tell where that detection fps is being used if the max/avg process fps is so low. 2.38*16 = 38.08 fps for one coral. 38.08 != 135. I'd expect a 5fps avg process fps in all cases. Any ideas?

### Version

0.13.0-91AADB6

### Frigate config file

```yaml
mqtt:
  enabled: False

birdseye:
  enabled: False
  width: 1920
  height: 1080
  quality: 1
  mode: continuous

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
#  max_disappeared: 300 # 30 seconds
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
#    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
#    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
#      default: 3000
      # Optional: Object specific values
#      objects:
#        person: 10000

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
  coral3:
    type: edgetpu
    device: pci:2

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic-audio-copy

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  #mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
#      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
#      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0,0,1000,0,1000,200,0,200
    car:
      min_score: 0.5
      threshold: 0.7

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
#  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 1
    # Optional: Per object retention days
    objects:
      person: 1
      car: 1

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: False
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 5
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 5
        car: 5

cameras:
  VIRAT_S_010002_05_000397_000420:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010002_05_000397_000420.mp4
          roles:
            - detect

  VIRAT_S_010207_05_001013_001038:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010207_05_001013_001038.mp4
          roles:
            - detect

  VIRAT_S_010207_04_000929_000954:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010207_04_000929_000954.mp4
          roles:
            - detect

  VIRAT_S_010002_07_000522_000547:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010002_07_000522_000547.mp4
          roles:
            - detect

  VIRAT_S_010204_03_000606_000632:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010204_03_000606_000632.mp4
          roles:
            - detect

  VIRAT_S_010207_08_001308_001332:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010207_08_001308_001332.mp4
          roles:
            - detect

  VIRAT_S_010208_08_000807_000831:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010208_08_000807_000831.mp4
          roles:
            - detect

  VIRAT_S_010204_10_001372_001395:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010204_10_001372_001395.mp4
          roles:
            - detect

  VIRAT_S_010207_09_001484_001510:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010207_09_001484_001510.mp4
          roles:
            - detect

  VIRAT_S_010002_06_000441_000467:
    ffmpeg:
      input_args: -re -stream_loop -1
      inputs:
        - path: /input/VIRAT_S_010002_06_000441_000467.mp4
          roles:
            - detect
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:dev-91aadb6
    shm_size: "4096mb"
    devices:
      - /dev/dri/renderD128
      - /dev/apex_0
      - /dev/apex_1
      - /dev/apex_2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tmp/config:/config
      - /mnt/data/viratDataset/videos_5fps:/input:ro
      - type: tmpfs # Optional: 5GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    ports:
      - "5000:5000"
      - "1936:1935"
      - "8554:8554" # RTSP feeds
    restart: no
```

### Relevant log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe
