### ISSUE TITLE
[Support]: Events and recordings not being saved when using go2rtc

### ISSUE THREAD

**Issue by ttopholm** [blakeblackshear/frigate#7251]
### Describe the problem you are having

Hi, 

I have a reolink RLC-511WA, and followed the guide here: https://docs.frigate.video/configuration/camera_specific#reolink-cameras

I can see the stream live, and it detects fine in frigate, but the recording doesn't work, when I look in the look it says the following:  

`Event does not have recordings: 1689966525.154536-tezilr`

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.xx.xx

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    skur_main: 
      - http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx
      - "ffmpeg:skur_main#audio=opus"
    skur_sub: 
      - http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xx&password=xxx



cameras:
  Skur: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/skur_sub?video=copy # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/skur?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480
      fps: 7
    record:
      enabled: True
    snapshots:
      enabled: True
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    objects:
      track:
      - person
      - car
      - dog
      - cat
```

### Relevant log output

```shell
2023-07-21 21:09:05.559611344  [2023-07-21 21:09:05] frigate.http                   ERROR   : No recordings found for the requested time range
2023-07-21 21:09:05.622948873  [2023-07-21 21:09:05] frigate.http                   ERROR   : Event does not have recordings: 1689966525.154536-tezilr
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

RLC-511WA

**Comment by NickM-27** [comment]
First thing I'd suggest trying is moving to `ffmpeg:` for the entire go2rtc config and see if that makes a difference.

**Comment by ttopholm** [comment]
@NickM-27 can you explain what you mean ;-)

**Comment by NickM-27** [comment]
```yaml
go2rtc:
  streams:
    skur_main: 
      - "ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xx&password=xx#video=copy#audio=copy#audio=opus"
    skur_sub: 
      - "ffmpeg:http://192.168.xx.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xx&password=xxx"
```
