### ISSUE TITLE
[Config Support]: HA plays back the wrong recording time frame

### ISSUE THREAD

**Issue by peveleigh** [blakeblackshear/frigate#7260]
### Describe the problem you are having

If I try playing back a recording through Home Assistant, it plays back the wrong time frame.

For example, if I follow this path: 

HA > Media > Frigate > Recordings > Camera1 > 2023-07-23 > 09:00

The video that plays back starts at 08:31 and ends at 09:31.

If I try and play the same recording directly through Frigate instead, it starts at 09:01 and ends at 10:01.

It's worth noting my timezone is UTC-3:30. This is set correctly in HA and hence HA shows the correct time.

### Version

0.12.1-367d724

### Frigate config file

```yaml
# detectors:
  # coral:
    # type: edgetpu
    # device: usb

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

mqtt:
  host: 192.168.X.XX
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hass
  password: XXXX

database:
  path: /config/frigate.db

record:
  enabled: True
  retain:
    days: 20

snapshots:
  enabled: True

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.X.XX:8554/camera.driveway_ss
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.X.XX:8554/camera.driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 704
      height: 480
            

  front_walkway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.X.XX:8554/camera.front_walkway_ss
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.X.XX:8554/camera.front_walkway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 704
      height: 480

  garage_side:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.X.XX:8554/camera.garage_side
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720            

  garage_inside:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.X.XX:8554/camera.garage_inside
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080           
      
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.X.XX:8554/camera.living_room
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
