### ISSUE TITLE
Frigate 1.6 on HA 2021.2.1 - protection mode: off

### ISSUE THREAD

**Issue by vinz486** [blakeblackshear/frigate#727]
Hi,
rebooted my RPI4 8gb with HA 64bit 2021.2.

On usb there is a Conbee2 zigbee adapter and a Coral usb unit.

Frigate has not started:

```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera fricam has clips assigned to an input, but clips is not enabled.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
detector.coral                 INFO    : Starting detection process: 37
frigate.app                    INFO    : Camera processor started for fricam: 40
frigate.app                    INFO    : Capture process started for fricam: 41
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.mqtt                   INFO    : MQTT connected
frigate.mqtt                   INFO    : Turning off detection for fricam via mqtt
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate.watchdog               INFO    : Detection appears to have stopped. Restarting frigate
frigate.app                    INFO    : Stopping...
frigate.object_processing      INFO    : Exiting object processor...
frigate.record                 INFO    : Exiting recording maintenance...
frigate.events                 INFO    : Exiting event processor...
frigate.events                 INFO    : Exiting event cleanup...
frigate.watchdog               INFO    : Exiting watchdog...
frigate.stats                  INFO    : Exiting watchdog...
root                           INFO    : Waiting for detection process to exit gracefully...
watchdog.fricam                INFO    : Terminating the existing ffmpeg process...
```

Integration config is:

``` 
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: home-assistant
  user: mqtt
  password: mqtt
ffmpeg:
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m
cameras:
  fricam:
    ffmpeg:
      inputs:
        - path: 'rtsp://aaa:aaa@192.168.1.6:5554/h264_pcm.sdp'
          roles:
            - clips
            - rtmp
            - detect
    width: 640
    height: 480
    fps: 25
objects:
  track:
    - person
    - dog
``` 

What's happened?
