### ISSUE TITLE
[HELP] - Mapping Coral M2 Dual Edge TPU to docker container

### ISSUE THREAD

**Issue by jaburges** [blakeblackshear/frigate#728]
Hey folks,
Unraid user (no apt-get) 
Trying to map the pci device (M2 Dual Edge Coral TPU) to docker

According to this I need the Apex package 
https://coral.ai/docs/m2/get-started/#2a-on-linux

However can't install it EDIT (removed reference to other issue - weird that it linked that from an emoji!) 
Any ideas?

**Comment by thundergreen** [comment]
for running pcie just like this:

```
version: '3.6'
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: blakeblackshear/frigate:0.8.0-beta2-amd64
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/hassio/homeassistant/:/config
      - /usr/share/hassio/media/frigate/clips:/media/frigate/clips
      - /usr/share/hassio/media/frigate/recordings:/media/frigate/recordings
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: 'password'
```
you just want to expose all /dev to docker
```
      - /dev:/dev
```

my config looks then like:


```
detectors:
  coral:
    type: edgetpu
    device: pci
    ... etc
```
