### ISSUE TITLE
[Support]: MQTT Events being sent every minute despite nothing in frame

### ISSUE THREAD

**Issue by Normanras** [blakeblackshear/frigate#7281]
### Describe the problem you are having

This happens at least once a day and not always on the same camera. But if an object triggers Frigate to send an MQTT payload, even after the person has left the frame, MQTT payload continues to get sent every minute. 

While I can understand if there is a lag between real life and frigate sending the payload, this will continue to 20-30 minutes or until I either restart the docker container and/or restart Frigate from the web UI. 

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: {{ mqtt-ip-address }}
  port: 1883
  client_id: frigate
  user: {{ mqtt-user }}
  password: {{ mqtt-password }}

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 640
  height: 480
  enabled: True

birdseye:
  enabled: True
  mode: objects
  quality: 5

objects:
  track:
    - person
    - dog
    - cat
    - bear
    - horse

record:
  enabled: False
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 5
    post_capture: 5

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 30

rtmp:
  enabled: False

live:
  quality: 5

cameras:
  cam1:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      inputs:
        - path: rtsp://USER:PASS*@IPADDRESS:554/h264Preview_01_main
          roles:
            - detect
    zones:
      z1:
        coordinates: 640,480,181,480,159,251,78,222,26,223,109,170,640,225
      z2:
        coordinates: 640,0,640,217,547,173,313,160,108,162,328,0
      z3:
        coordinates: 0,148,224,0,354,0,0,239
      z4:
        coordinates: 237,0,0,0,0,157
      z5:
        coordinates: 154,256,112,233,69,216,27,228,0,242,0,480,225,480
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True

  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASS*@IPADDRESS:554/h264Preview_01_main
          roles:
            - detect
    zones:
      z1:
        coordinates: 263,480,640,480,640,0,480,0,356,136,406,195,322,271
      z2:
        coordinates: 341,123,288,267,178,480,0,480,0,0,479,0
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True

  cam3:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASS*@IPADDRESS:554/h264Preview_01_main
          roles:
            - detect
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
```

### Relevant log output

```shell
I've attached a screenshot of the MQTT timestamps using debug nodes in node-red.
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://USER:PASS*@IPADDRESS:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000188, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn, 90k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 820a

### Any other information that may be helpful

Debug screenshot in Nodered showing the MQTT payload being sent every minute. 

![Screenshot 2023-07-24 at 4 18 11 PM](https://github.com/blakeblackshear/frigate/assets/44226464/176b2371-0cf9-47e9-b3e2-845c74e69010)
