### ISSUE TITLE
[Support]: No area name on motion

### ISSUE THREAD

**Issue by lorenzomartini1** [blakeblackshear/frigate#7286]
### Describe the problem you are having

Hello everyone, I got this event this morning... why the "person" (even if is a cat) has no area name?

![gatto](https://github.com/blakeblackshear/frigate/assets/35630216/07fde5e2-99b0-450e-910c-418b6fef5aab)
![gatto2](https://github.com/blakeblackshear/frigate/assets/35630216/5b2f1b54-2a11-45c0-af9d-c9b1d19d300f)

I have areas designed for all the camera, so I expect to have at least one...

![giardino](https://github.com/blakeblackshear/frigate/assets/35630216/77a4f0e8-4ba5-4760-bc46-8dba709438a5)
![masks](https://github.com/blakeblackshear/frigate/assets/35630216/59d83b41-643e-46e4-bdf7-53c55695bcc5)

I got the same for this and other frames:

![asssa](https://github.com/blakeblackshear/frigate/assets/35630216/84d746e4-3f31-4f43-aa1a-12dda71dd410)
![asssb](https://github.com/blakeblackshear/frigate/assets/35630216/0b4a7244-789f-4b67-ba0f-80977ac73113)

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: host
  port: port
  user: user
  password: pw

detect:
  enabled: true
  width: 960
  height: 540
  fps: 5
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu

go2rtc:
  streams:
    retro_alto: 
      - http://192.168.1.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:retro_alto#audio=opus"
    retro_alto_sub: 
      - http://192.168.1.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
    porta_vista_nord: 
      - http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:porta_vista_nord#audio=opus"
    porta_vista_nord_sub: 
      - http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
    porta_vista_sud: 
      - http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:porta_vista_sud#audio=opus"
    porta_vista_sud_sub: 
      - http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!

cameras:
  porta_vista_nord:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/porta_vista_nord?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porta_vista_nord_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
      # filters:
      #   person:
      #     min_area: 3500
      #     max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.68
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.7
    zones:
      giardino:
        coordinates: 329,292,517,300,518,107,586,114,593,77,476,66,436,38,281,43,0,179,0,540,239,540
      ingresso:
        coordinates: 615,176,640,359,313,372,245,540,755,540,746,460,873,116,888,79,837,26,634,0
      pavimento:
        coordinates: 519,101,601,96,641,295,646,358,318,355,322,300,516,306
      viottolino:
        coordinates: 500,0,566,0,561,66,498,62
    motion:
      mask:
        - 649,490,960,487,960,540,651,540,647,540
      threshold: 40
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  # porta_vista_nord:
  #   ffmpeg:
  #       inputs:
  #         - path: rtmp://192.168.1.55/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #           roles:
  #             - record
  #             - detect
  #   zones:
  #     giardino:
  #       coordinates: 329,292,517,300,518,107,586,114,593,77,476,66,436,38,281,43,0,179,0,540,239,540
  #     pavimento:
  #       coordinates: 519,112,598,108,641,295,652,415,669,487,673,504,661,540,222,540,322,300,516,306
  #     ingresso:
  #       coordinates: 615,176,640,359,665,502,696,490,714,496,717,484,736,456,873,116,888,79,837,26,634,0
  #     viottolino:
  #       coordinates: 500,0,566,0,561,66,498,62
  #   motion:
  #     mask:
  #       - 632,365,817,316,734,502,536,505
  #     threshold: 40
              
  porta_vista_sud:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/porta_vista_sud?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porta_vista_sud_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
      # filters:
      #   person:
      #     min_area: 3500
      #     max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.7 # 0.6
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.75 # 0.7
    zones:
      giardino:
        coordinates: 784,540,960,540,960,212,791,105,621,103
      ingresso:
        coordinates: 0,91,0,540,294,540,776,540,746,414,431,405,389,400,328,371,206,46
        filters:
          persons:
            min_area: 15000
      tettoia:
        coordinates: 750,425,639,430,552,425,405,417,283,379,330,258,416,103,438,85,606,67
        filters:
          persons:
            min_score: 0.75
            threshold: 0.8
    motion:
      mask:
        - 654,540,960,540,960,493,647,491
        - 346,540,572,540,520,158,449,119,424,66,322,248,235,24,109,48
        - 682,98,741,112,734,54,690,44
        - 602,0,656,0,648,43,596,44
      threshold: 40
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  # porta_vista_sud:
  #   ffmpeg:
  #     inputs:
  #         - path: rtmp://192.168.1.73/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #           roles:
  #             - record
  #             - detect
  #   zones:
  #     giardino:
  #       coordinates: 772,508,960,509,960,212,791,105,621,103
  #     ingresso:
  #       coordinates: 0,91,0,540,357,540,281,395,206,46
  #     tettoia:
  #       coordinates: 778,540,612,540,357,540,283,379,330,258,416,103,438,85,606,67
  #   motion:
  #     mask:
  #       - 224,379,313,513,353,540,459,519,529,498,468,398,427,368,378,363,320,352,277,356
  #     threshold: 40

  retro_alto:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/retro_alto?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/retro_alto_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      campo:
        coordinates: 960,0,960,126,626,119,298,133,0,155,0,0
      giardino:
        coordinates: 0,540,960,540,960,209,361,199,373,290,271,291,208,201,0,216
        filters:
          person:
            min_area: 1000
      viottolino:
        coordinates: 0,222,222,208,288,285,368,291,356,202,675,189,960,199,960,139,756,128,593,124,230,130,0,151
      viottolinoesposta:
        coordinates: 245,208,349,207,375,281,278,282
        filters:
          person:
            min_area: 1000
    motion:
      mask:
        - 643,540,882,540,960,540,960,496,634,496
      threshold: 20
      contour_area: 20
    objects:
      filters:
        person:
          min_score: 0.4
          threshold: 0.5
          min_area: 1000
      track:
        - person
        - bicycle
        - motorcycle
        - car
        - cat
        - dog
      # filters:
      #   person:
      #     #min_area: 3500
      #     #max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.5 # 0.6
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.6 # 0.7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  # retro_alto:
  #   ffmpeg:
  #     inputs:
  #       - path: rtmp://192.168.1.59/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #         roles:
  #           - record
  #           - detect
  #   zones:
  #     campo:
  #       coordinates: 133,28,132,0,960,0,960,140,625,131,300,145,0,166,0,21
  #     giardino:
  #       coordinates: 0,540,661,540,672,510,960,509,960,209,361,199,373,290,280,285,208,201,0,216
  #     viottolino:
  #       coordinates: 0,222,222,198,288,285,368,291,356,202,675,189,960,199,960,139,756,128,593,124,225,133,0,162
  #     viottolino_esposta:
  #       coordinates: 190,126,357,113,380,278,263,286
  #   motion:
  #     mask:
  #       - 750,399,869,402,860,334,768,338
  #     threshold: 40

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 7
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 6
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 6
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 10

# motion:
#     delta_alpha: 0.2
#     frame_alpha: 0.3
#     contour_area: 0

motion:
  mqtt_off_delay: 0

objects:
  filters:
    person:
      min_score: 0.6
      threshold: 0.8
      max_area: 100000

ffmpeg:
  hwaccel_args:
#    - -hwaccel
#   - vaapi
#   - -hwaccel_device
#   - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
#   - -fflags
#   - nobuffer
#   - -flags
#   - low_delay
#   - -strict
#   - experimental
#   - -fflags
#   - +genpts+discardcorrupt
#   - -rw_timeout
#   - "5000000"
#   - -use_wallclock_as_timestamps
#   - "1" 
  output_args:
    record: preset-record-generic-audio-aac
    
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "solid"
  
live:
  height: 480
  quality: 8
    
birdseye:
  enabled: True
  width: 1280
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560}]}}]
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.1"},"1":{"cpu":"0.0","mem":"0.0"},"113":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.2"},"143":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"162":{"cpu":"0.0","mem":"0.1"},"17":{"cpu":"0.0","mem":"0.0"},"192":{"cpu":"0.0","mem":"0.1"},"227":{"cpu":"0.0","mem":"0.2"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"261":{"cpu":"0.0","mem":"0.1"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"426":{"cpu":"0.0","mem":"0.2"},"432":{"cpu":"0.3","mem":"0.0"},"433":{"cpu":"0.0","mem":"0.3"},"435":{"cpu":"0.0","mem":"0.3"},"437":{"cpu":"0.0","mem":"0.3"},"439":{"cpu":"0.7","mem":"0.3"},"442":{"cpu":"0.3","mem":"0.3"},"443":{"cpu":"1.0","mem":"0.3"},"444":{"cpu":"0.7","mem":"0.3"},"445":{"cpu":"1.0","mem":"0.3"},"448":{"cpu":"1.3","mem":"0.3"},"452":{"cpu":"0.0","mem":"0.2"},"453":{"cpu":"1.3","mem":"0.3"},"464":{"cpu":"0.0","mem":"0.0"},"470":{"cpu":"0.0","mem":"0.2"},"471":{"cpu":"0.0","mem":"0.2"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"30.2","mem":"0.1"},"89164":{"cpu":"3.0","mem":"0.3"},"89168":{"cpu":"2.3","mem":"0.4"},"89202":{"cpu":"2.7","mem":"0.3"},"90320":{"cpu":"7.6","mem":"0.2"},"90321":{"cpu":"7.0","mem":"0.2"},"90349":{"cpu":"7.3","mem":"0.2"},"96701":{"cpu":"0.0","mem":"0.0"},"96752":{"cpu":"0.0","mem":"0.0"},"96753":{"cpu":"6.7","mem":"0.0"},"96757":{"cpu":"0.3","mem":"0.0"},"96759":{"cpu":"0.3","mem":"0.0"},"97":{"cpu":"2.3","mem":"1.3"},"98":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"10731.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":53.89,"pid":433},"cpu2":{"detection_start":0.0,"inference_speed":52.85,"pid":435},"cpu3":{"detection_start":0.0,"inference_speed":58.22,"pid":437}},"gpu_usages":{"intel-vaapi":{"gpu":"6.69 %","mem":"- %"}},"porta_vista_nord":{"camera_fps":5.1,"capture_pid":445,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":89202,"pid":442,"process_fps":5.1,"skipped_fps":0.0},"porta_vista_sud":{"camera_fps":5.1,"capture_pid":448,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":89164,"pid":443,"process_fps":5.1,"skipped_fps":0.0},"retro_alto":{"camera_fps":5.0,"capture_pid":453,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":89168,"pid":444,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1690272760,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":58.8,"mount_type":"tmpfs","total":67.1,"used":8.3},"/media/frigate/clips":{"free":855148.3,"mount_type":"ext4","total":1966309.9,"used":1011203.0},"/media/frigate/recordings":{"free":855148.3,"mount_type":"ext4","total":1966309.9,"used":1011203.0},"/tmp/cache":{"free":984.5,"mount_type":"tmpfs","total":1000.0,"used":15.5}},"temperatures":{},"uptime":60206,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 520A
