### ISSUE TITLE
[Support]: Recorded Video Stutters

### ISSUE THREAD

**Issue by halexh** [blakeblackshear/frigate#7294]
### Describe the problem you are having

Playing back recorded video (whether its in the browser, or through VLC, or wherever) stutters based on the difference between the FPS and the I Frame Interval. However, this only happens on recordings. Viewing the live stream of the video shows no stuttering.

The FPS is set at 30. If I increase the I Frame Interval from 30, to say, 150, the stuttering only happens every 5 seconds (150/30=5). The strange thing here (to me at least) is that this only is viewable in the recordings, and not the live stream. To me, that rules out a network issue, or a camera issue, and perhaps something to do with frigate saving the video?

The frigate container is running on a i5-12600k. Issue happens whether I set the camera to encode in h264 or h265. If I set it to use h264 and update my frigate config to utilize `preset-intel-qsv-h264`, I still get the same issue.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  Front:
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp:/<redacted>@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    record:
      enabled: true

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view
  enabled: True
  # Optional: Restream birdseye via RTSP
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  width: 1920
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1520,"width":2688}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"6/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1080,"width":1920}]}}]
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-T5442T-ZEB
