### ISSUE TITLE
[HW Accel Support]: NVIDIA passthrough, CUDA_ERROR_NOT_SUPPORTED: operation not supported

### ISSUE THREAD

**Issue by b-neufeld** [blakeblackshear/frigate#7295]
### Describe the problem you are having

I can't get hardware working on a new Frigate install. I have made every attempt to search Github, reddit, Google etc. but keep coming up with the errors in the logs below. 

Setup is non-standard: TrueNAS Scale 22.12.3.2, running a Ubuntu 22.04 VM, running Docker. I have successfully passed both the Coral TPU and NVIDIA GeForce RTX 2080 to the Ubuntu VM & Docker container, but am struggling to get Frigate to utilize the GPU. 

If I remove hwaccel_args from the Frigate config, I don't have any issues. 

The full error log is below, but the concerning sequence is: 

* [AVHWDeviceContext @ 0x55ed80e84400] cu->cuCtxCreate(&hwctx->cuda_ctx, desired_flags, hwctx->internal->cuda_device) failed -> CUDA_ERROR_NOT_SUPPORTED: operation not supported
* Device creation failed: -542398533.
* [h264 @ 0x55ed80eb5540] No device available for decoder: device type cuda needed for codec h264.
* Device setup failed for decoder on input stream #0:0 : Generic error in an external library

### Version

0.12.1-367D724

### Frigate config file

```yaml
# mqtt 
mqtt:   
  host: 172.16.1.99
  port: 1883
  enabled: true
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

# https://docs.frigate.video/configuration/cameras
cameras:   
  front_door:     
    ffmpeg:       
      inputs:         
        - path: rtsp://viewer:password@172.16.1.72:554/stream1           
          roles:             
            - detect   
      hwaccel_args: preset-nvidia-h264
    detect:       
      enabled: false
      width: 1280       
      height: 720

# https://docs.frigate.video/configuration/detectors/
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/edgetpu_model.tflite"
```

### docker-compose file or Docker CLI command

```yaml
# instructions: https://docs.frigate.video/frigate/installation#docker
version: "3.9"
services:
  frigate:
    container_name: frigate
    user: "0:0" # confirmed this is needed, otherwise video doesn't load. Gets the same error as trying to enable hwaccel...hmmm
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above. 64 should be good for 2 cameras. 
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      # trying to uncomment this and see if it malkes a diff. 830am July 26
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      # added 830 am July 26
      - /dev/dri/card1:/dev/dri/card1 # lspci, then checking /dev/dri/by-path shows NVIDIA is card1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vesta/containerdata/frigate/config.yml:/config/config.yml
      - /mnt/vesta/containerdata/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    # this is just for intel GPU stats, which I'm not using. 
    #cap_add: # supports enabling hardware acceleration. Not sure if it will work with a VM but...
    #  - CAP_PERFMON
    # v this is needed to get the NVIDIA card passed through. 
    deploy:    # https://docs.frigate.video/configuration/hardware_acceleration/
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant log output

```shell
... {startup}
2023-07-26 08:16:20.325151587  [2023-07-26 08:16:17] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-07-26 08:16:20.386119476  [2023-07-26 08:16:20] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-07-26 08:16:21.556127190  172.22.0.1 - - [26/Jul/2023:08:16:21 -0600] "GET /api/stats HTTP/1.1" 200 2255 "-" "HomeAssistant/2023.7.3 aiohttp/3.8.5 Python/3.11" "-"
2023-07-26 08:16:23.752676931  [INFO] Starting go2rtc healthcheck service...
2023-07-26 08:16:29.554647225  172.22.0.1 - - [26/Jul/2023:08:16:29 -0600] "GET /api/stats HTTP/1.1" 200 2223 "-" "HomeAssistant/2023.7.3 aiohttp/3.8.5 Python/3.11" "-"
2023-07-26 08:16:37.099657625  [2023-07-26 08:16:37] watchdog.front_door            ERROR   : Ffmpeg process crashed unexpectedly for front_door.
2023-07-26 08:16:37.100008330  [2023-07-26 08:16:37] watchdog.front_door            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-07-26 08:16:37.100316911  [2023-07-26 08:16:37] ffmpeg.front_door.detect       ERROR   : [AVHWDeviceContext @ 0x55ebc7559240] cu->cuCtxCreate(&hwctx->cuda_ctx, desired_flags, hwctx->internal->cuda_device) failed -> CUDA_ERROR_NOT_SUPPORTED: operation not supported
2023-07-26 08:16:37.100525777  [2023-07-26 08:16:37] ffmpeg.front_door.detect       ERROR   : Device creation failed: -542398533.
2023-07-26 08:16:37.100700688  [2023-07-26 08:16:37] ffmpeg.front_door.detect       ERROR   : [h264 @ 0x55ebc74a7bc0] No device available for decoder: device type cuda needed for codec h264.
2023-07-26 08:16:37.100873388  [2023-07-26 08:16:37] ffmpeg.front_door.detect       ERROR   : Device setup failed for decoder on input stream #0:0 : Generic error in an external library
2023-07-26 08:16:37.548233216  172.22.0.1 - - [26/Jul/2023:08:16:37 -0600] "GET /api/stats HTTP/1.1" 200 2255 "-" "HomeAssistant/2023.7.3 aiohttp/3.8.5 Python/3.11" "-"
2023-07-26 08:16:39.580900079  [2023-07-26 08:16:39] frigate.video                  ERROR   : front_door: Unable to read frames from ffmpeg process.
2023-07-26 08:16:39.580955587  [2023-07-26 08:16:39] frigate.video                  ERROR   : front_door: Unable to read frames from ffmpeg process.
2023-07-26 08:16:39.581121974  [2023-07-26 08:16:39] frigate.video                  ERROR   : front_door: ffmpeg process is not running. exiting capture thread...
... {most of this repeats over and over}
```

### FFprobe output from your camera

```shell
brahm@juno:/dev/dri$ ffprobe rtsp://viewer:password@172.16.1.72:554/stream1
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://viewer:password@172.16.1.72:554/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1280x720, 15 fps, 15 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Tapo C200

### Any other information that may be helpful

On the Frigate system page I can see my Coral under Detectors and NVIDIA GeForce RTX 2080 under GPUs. 

When I click "vainfo" I get the following: 
```
{"return_code":3,"stderr":"error:XDG_RUNTIME_DIRisinvalidornotsetintheenvironment.nerror:can'tconnecttoXserver!nlibvainfo:VA-APIversion1.17.0nlibvainfo:Tryingtoopen/usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.sonlibvainfo:va_openDriver()returns-1nvaInitializefailedwitherrorcode-1(unknownlibvaerror),exit","stdout":""}
```
... But my understanding is that vainfo is a diagnostic for Intel integrated graphics and not an NVIDIA card (please correct if I'm wrong). 

`nvidia-smi` output is the same on the Ubuntu VM and on the Frigate container: 
```
Wed Jul 26 10:21:39 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080        On  | 00000000:00:08.0 Off |                  N/A |
|  0%   42C    P8              10W / 215W |      1MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

Output of `ffmpeg -decoders | grep h264` on Frigate container showing decoder is available:
```
root@5b5c954f8435:/opt/frigate# ffmpeg -decoders | grep h264
ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
 VFS..D h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 decoder wrapper (codec h264)
 V....D h264_qsv             H264 video (Intel Quick Sync Video acceleration) (codec h264)
 V....D libopenh264          OpenH264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
```

Output of `ffmpeg -hwaccels` shows cuda available in container:
```
root@5b5c954f8435:/opt/frigate# ffmpeg -hwaccels
ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Hardware acceleration methods:
cuda
vaapi
qsv
drm
opencl
vulkan
```

`lspci` on Ubuntu VM showing passthrough:
```
brahm@juno:/dev/dri$ lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:02.0 VGA compatible controller: Red Hat, Inc. QXL paravirtual graphic card (rev 05)
00:03.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 03)
00:04.0 USB controller: NEC Corporation uPD720200 USB 3.0 Host Controller (rev 03)
00:05.0 Communication controller: Red Hat, Inc. Virtio console
00:06.0 SCSI storage controller: Red Hat, Inc. Virtio block device
00:07.0 Serial bus controller: NVIDIA Corporation TU104 USB Type-C UCSI Controller (rev a1)
00:08.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2080] (rev a1)
00:09.0 Audio device: NVIDIA Corporation TU104 HD Audio Controller (rev a1)
00:0a.0 USB controller: NVIDIA Corporation TU104 USB 3.1 Host Controller (rev a1)
00:0b.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon
```

`/dev/dri/by_path ls -l` showing NVIDIA GPU in slot 8 is mapped to /card1 and /renderD128. I did a `chmod 777` on this folder as a troubleshooting idea on a similar Jellyfin issue from a few years ago. Didn't appear to have any effect. 
```
brahm@juno:/dev/dri/by-path$ ls -l
total 0
lrwxrwxrwx 1 root root  8 Jul 24 19:20 pci-0000:00:02.0-card -> ../card0
lrwxrwxrwx 1 root root  8 Jul 24 19:20 pci-0000:00:08.0-card -> ../card1
lrwxrwxrwx 1 root root 13 Jul 24 19:20 pci-0000:00:08.0-render -> ../renderD128
```

Any ideas are appreciated!
