### ISSUE TITLE
how to define no specific region

### ISSUE THREAD

**Issue by jalbstmeijer** [blakeblackshear/frigate#73]
Ho do I define to use the full image to detect and mark persons?

I now use:

```
    regions:
      - size: -1
        x_offset: 0
        y_offset: 0
        min_person_area: 5000
        threshold: 0.5
```
and this detects persons, but does not mark the detected person with a square.
