### ISSUE TITLE
[Support]: System crashes - cause could be go2rtc related

### ISSUE THREAD

**Issue by jordankoehn** [blakeblackshear/frigate#7315]
### Describe the problem you are having

I've been having full crashes for months and I think I've finally got some logs to show for it. These crashes cause a full system lock up requiring a smart switch to reboot the server.

Originally, upgrading go2rtc to 1.5.0 via the config helped a lot, I no longer had 2+ crashes daily. It reduced to maybe twice per week. But lately, even after upgrading go2rtc from 1.5.0 to 1,6.2, I'm back to having ~2 crashes daily. I reinstalled my OS (endevorous) yesterday. I happened to leave a display plugged in overnight and also set up VictoriaMetrics logging so I actually have data to show now.

### Version

0.13.0-6801981

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  port: 1883
  user: hass
  password: REDACTED

birdseye:
  enabled: false
  width: 1920
  height: 1080
  quality: 1
  mode: continuous

detect:
  enabled: true
  fps: 10

detectors:
  coral:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    Doorbell:
    - rtsp://admin:REDACTED@192.168.86.247:554/h264_stream
    Backyard:
    - rtsp://admin:REDACTED@192.168.86.240:554/cam/realmonitor?channel=1&subtype=0

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

cameras:
  Doorbell:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Doorbell
        roles:
        - detect
        - record
    detect:
      width: 1536
      height: 2048
    motion:
      mask:
      - 0,0,1536,0,1536,1136,573,1102,86,1144,95,1243,430,1366,278,1436,790,1652,1536,1526,1536,2048,0,2048
    objects:
      filters:
        person:
          mask:
          - 1536,0,0,0,0,967,380,1014,407,1051,728,1092,1536,1125
          - 0,1190,427,1362,138,2048,0,2048
          - 1536,2048,1041,2048,1293,1422,1536,1416

  Backyard:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Backyard
        roles:
        - record
        - detect
    detect:
      width: 2592 #704
      height: 1944 #480
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
    motion:
      mask:
      - 2592,37,0,30,0,676,113,591,1032,471,1858,483,2592,586
      - 261,1944,2592,1944,2180,857,1613,724,889,814,144,1108
  
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
#    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
    - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 10
#  max_seconds: 300
```

### Relevant log output

```shell
Frigate log output at the system crash

2023-07-28 08:36:28.103259945  08:36:28.103 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="RTSP wrong input" url=rtsp://admin:REDACTED@192.168.86.247:554/h264_stream
2023-07-28 08:36:40.571627138  [2023-07-28 08:36:40] watchdog.Doorbell              INFO    : Doorbell exceeded fps limit. Exiting ffmpeg...
2023-07-28 08:36:40.571862294  [2023-07-28 08:36:40] watchdog.Doorbell              INFO    : Waiting for ffmpeg to exit gracefully...
2023-07-28 08:37:14.565083365  [2023-07-28 08:37:14] watchdog.Doorbell              INFO    : FFmpeg did not exit. Force killing...
2023-07-28 08:37:14.571260668  [2023-07-28 08:37:14] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
2023-07-28 08:37:14.571396983  [2023-07-28 08:37:14] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...

Printed to my system display (from dmesg?)
Out of memory: Killed process 9992 (frigate.capture) total-vm:16895484kb, anon-rss:14399096kb, file-rss:0kb, shmem-rss:4668kb, UID:0 pgtables:28664kb oom_score_adj:0
```

### FFprobe output from your camera

```shell
ffprobe version n6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.1.1 (GCC) 20230429
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[rtsp @ 0x5580ac42f740] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://admin:XLGOPX@192.168.86.247:554/h264_stream':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1536x2048, 10 fps, 10 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{
    "Backyard": {
        "camera_fps": 10.1,
        "capture_pid": 403,
        "detection_enabled": 1,
        "detection_fps": 0.0,
        "ffmpeg_pid": 413,
        "pid": 387,
        "process_fps": 10.1,
        "skipped_fps": 0.0
    },
    "Doorbell": {
        "camera_fps": 10.1,
        "capture_pid": 399,
        "detection_enabled": 1,
        "detection_fps": 0.0,
        "ffmpeg_pid": 409,
        "pid": 382,
        "process_fps": 10.1,
        "skipped_fps": 0.0
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "14": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "23": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "39": {
            "cmdline": "/package/admin/s6-2.11.3.0/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "44": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "77": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "79": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "92": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "2.1",
            "cpu_average": "2",
            "mem": "0.1"
        },
        "106": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "114": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "4.1",
            "cpu_average": "1",
            "mem": "1.0"
        },
        "121": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "144": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "147": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "148": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "149": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "364": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "366": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.0",
            "cpu_average": "1",
            "mem": "0.7"
        },
        "375": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(41)",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "376": {
            "cmdline": "frigate.detector.coral",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "377": {
            "cmdline": "frigate.output       ",
            "cpu": "2.1",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "382": {
            "cmdline": "frigate.process:Doorbell",
            "cpu": "2.1",
            "cpu_average": "1",
            "mem": "0.6"
        },
        "385": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1536x2048 -i pipe: -f mpegts -s 540x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "387": {
            "cmdline": "frigate.process:Backyard",
            "cpu": "3.1",
            "cpu_average": "2",
            "mem": "0.6"
        },
        "398": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2592x1944 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "399": {
            "cmdline": "frigate.capture:Doorbell",
            "cpu": "5.2",
            "cpu_average": "5",
            "mem": "0.5"
        },
        "403": {
            "cmdline": "frigate.capture:Backyard",
            "cpu": "10.4",
            "cpu_average": "8",
            "mem": "0.6"
        },
        "409": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.0-6801981 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Doorbell-%Y%m%d%H%M%S.mp4 -r 10 -vf vpp_qsv=framerate=10:w=1536:h=2048:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "8.3",
            "cpu_average": "6",
            "mem": "0.3"
        },
        "413": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -user_agent FFmpeg Frigate/0.13.0-6801981 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Backyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Backyard-%Y%m%d%H%M%S.mp4 -r 10 -vf vpp_qsv=framerate=10:w=2592:h=1944:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "10.4",
            "cpu_average": "10",
            "mem": "0.4"
        },
        "2445": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 0.0,
    "detectors": {
        "coral": {
            "detection_start": 0.0,
            "inference_speed": 6.79,
            "pid": 376
        }
    },
    "gpu_usages": {
        "intel-qsv": {
            "gpu": "4.43%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 92
        },
        "logger": {
            "pid": 364
        },
        "recording": {
            "pid": 366
        }
    },
    "service": {
        "last_updated": 1690549369,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 157.0,
                "mount_type": "tmpfs",
                "total": 170.0,
                "used": 13.0
            },
            "/media/frigate/clips": {
                "free": 83582.9,
                "mount_type": "ext4",
                "total": 449581.0,
                "used": 343089.1
            },
            "/media/frigate/recordings": {
                "free": 83582.9,
                "mount_type": "ext4",
                "total": 449581.0,
                "used": 343089.1
            },
            "/tmp/cache": {
                "free": 465.7,
                "mount_type": "tmpfs",
                "total": 476.8,
                "used": 11.2
            }
        },
        "temperatures": {
            "apex_0": 37.3
        },
        "uptime": 1044,
        "version": "0.13.0-6801981"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Nelly NSC-DB2

### Any other information that may be helpful

Here's a deep dive on this camera. I have it blocked from the internet and access it via it's rstp stream https://seanblanchfield.com/2022/05/ezviz-db1-doorbell-deepdive-homeassistant

I bought it before the new amcrest doorbell was released

Here is my system stats leading up to the crash, where you can see ram usage taking a nosedive
![image](https://github.com/blakeblackshear/frigate/assets/25444954/55be9e06-4b83-4468-a6fa-8bd155d9b493)

**Comment by NickM-27** [comment]
I would suggest setting go2rtc to use ffmpeg for that doorbell

```yaml
go2rtc:
  streams:
    Doorbell:
    - "ffmpeg:rtsp://admin:REDACTED@192.168.86.247:554/h264_stream"
```
