### ISSUE TITLE
[Support]: Home Assistant frigate camera entity show motion but no event in Frigate UI

### ISSUE THREAD

**Issue by lorenzomartini1** [blakeblackshear/frigate#7316]
### Describe the problem you are having

In my Home Assistant platform I use the `camera.cameraname_person` entity to show last person detected. I also use the `binary_sensor.cameraname_person_occupancy` for getting last change (when the motion sensor become off (?)).
I see something from entitites of 3 minutes ago, but in frigate I don't see any corresponding event of what I see in Home Assistant.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: #
  port: #
  user: #
  password: #

detect:
  enabled: true
  width: 640 #960
  height: 480 #540
  fps: 10 #5
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 50
  stationary:
    interval: 0
    threshold: 300 # 150 = 30 secondi # old 50 # dopo 30 secondi (150/5 fps = 30) un oggetto fermo viene considerato "stazionario"
    max_frames:
      default: 1800 # 900 = 3 minuti # dopo aver capito che è un oggetto stazionario, registra nell'evento al massimo 3 minuti

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu

go2rtc:
  streams:
    retro_alto: 
      - http://192.168.1.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:retro_alto#audio=opus"
    retro_alto_sub: 
      - http://192.168.1.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
    porta_vista_nord: 
      - http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:porta_vista_nord#audio=opus"
    porta_vista_nord_sub: 
      - http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
    porta_vista_sud: 
      - http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:porta_vista_sud#audio=opus"
    porta_vista_sud_sub: 
      - http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!

cameras:
  porta_vista_nord:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/porta_vista_nord?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porta_vista_nord_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
      # filters:
      #   person:
      #     min_area: 3500
      #     max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.68
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.7
    zones:
      giardino:
        coordinates: 196,371,222,263,342,266,339,91,396,101,400,0,383,0,376,52,331,58,328,0,0,0,0,179,0,480,78,480
      ingresso:
        coordinates: 403,204,427,330,216,304,87,480,567,480,573,446,527,378,582,90,586,43,430,0
      pavimento:
        coordinates: 349,98,395,101,422,204,431,313,210,311,232,268,353,263
      viottolino:
        coordinates: 332,0,384,0,378,59,330,55
    motion:
      mask:
        - 444,480,448,449,640,448,640,480
      threshold: 25
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  # porta_vista_nord:
  #   ffmpeg:
  #       inputs:
  #         - path: rtmp://192.168.1.55/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #           roles:
  #             - record
  #             - detect
  #   zones:
  #     giardino:
  #       coordinates: 329,292,517,300,518,107,586,114,593,77,476,66,436,38,281,43,0,179,0,540,239,540
  #     pavimento:
  #       coordinates: 519,112,598,108,641,295,652,415,669,487,673,504,661,540,222,540,322,300,516,306
  #     ingresso:
  #       coordinates: 615,176,640,359,665,502,696,490,714,496,717,484,736,456,873,116,888,79,837,26,634,0
  #     viottolino:
  #       coordinates: 500,0,566,0,561,66,498,62
  #   motion:
  #     mask:
  #       - 632,365,817,316,734,502,536,505
  #     threshold: 40
              
  porta_vista_sud:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/porta_vista_sud?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porta_vista_sud_sub?video=copy
          input_args: preset-rtsp-restream
        # - path: /media/frigate/clip.mp4
        #   input_args: -re -stream_loop -1 -fflags +genpts          
          roles:
            - detect
    objects:
      track:
        - person
      # filters:
      #   person:
      #     min_area: 3500
      #     max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.7 # 0.6
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.75 # 0.7
    zones:
      giardino:
        coordinates: 520,480,640,480,640,193,537,99,418,96
      ingresso:
        coordinates: 0,91,0,480,295,480,520,480,498,403,451,398,389,400,222,411,75,48
        filters:
          persons:
            min_area: 15000
      tettoia:
        coordinates: 500,395,389,396,200,387,300,83,416,92
        filters:
          persons:
            min_score: 0.75
            threshold: 0.8
    motion:
      mask:
        - 445,480,640,480,640,454,442,455
        - 173,445,403,433,341,193,338,102,280,78,210,254,126,30,54,42
        - 457,87,493,100,505,50,466,48
        - 394,0,444,0,441,42,402,44
      threshold: 25
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  # porta_vista_sud:
  #   ffmpeg:
  #     inputs:
  #         - path: rtmp://192.168.1.73/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #           roles:
  #             - record
  #             - detect
  #   zones:
  #     giardino:
  #       coordinates: 772,508,960,509,960,212,791,105,621,103
  #     ingresso:
  #       coordinates: 0,91,0,540,357,540,281,395,206,46
  #     tettoia:
  #       coordinates: 778,540,612,540,357,540,283,379,330,258,416,103,438,85,606,67
  #   motion:
  #     mask:
  #       - 224,379,313,513,353,540,459,519,529,498,468,398,427,368,378,363,320,352,277,356
  #     threshold: 40

  retro_alto:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/retro_alto?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/retro_alto_sub?video=copy
          input_args: preset-rtsp-restream
        # - path: /media/frigate/clip.mp4
        #   input_args: -re -stream_loop -1 -fflags +genpts          
          roles:
            - detect
    zones:
      campo:
        coordinates: 640,0,640,123,441,120,191,124,0,147,0,0
      giardino:
        coordinates: 167,263,362,282,368,414,606,411,640,391,640,480,0,480,0,258
        filters:
          person:
            min_area: 2000 #4000
            threshold: 0.6
      viottolino:
        coordinates: 0,187,138,168,178,244,250,253,232,200,245,156,640,161,640,123,508,118,335,110,153,121,0,151
      viottolinoesposta:
        coordinates: 153,180,234,180,250,250,180,244
        # filters:
        #   person:
        #     min_area: 1000
      spazzatura:
        coordinates: 377,406,590,402,563,272,372,284
        filters:
          person:
            threshold: 0.75
    record:
      events:
        required_zones:
          - campo
          - giardino
          - viottolino
          - viottolinoesposta
          - spazzatura
    snapshots:
      required_zones:
        - campo
        - giardino
        - viottolino
        - viottolinoesposta
        - spazzatura
    motion:
      mask:
        - 142,167,171,270,0,263,0,178
        - 563,271,583,389,640,381,640,173,597,156,393,156,248,159,226,203,268,269,345,280
        - 640,480,640,457,444,449,444,480
      threshold: 20
      contour_area: 20
      improve_contrast: true
    detect:
      max_disappeared: 20 # 20 = 2 secondi # 10
    objects:
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 1500
          max_area: 18000
          # min_score: 0.1
          # threshold: 0.2
          # min_area: 0
      track:
        - person
        - bicycle
        - motorcycle
        - car
        - cat
        - dog
      # filters:
      #   person:
      #     #min_area: 3500
      #     #max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.5 # 0.6
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.6 # 0.7
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  # retro_alto:
  #   ffmpeg:
  #     inputs:
  #       - path: rtmp://192.168.1.59/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #         roles:
  #           - record
  #           - detect
  #   zones:
  #     campo:
  #       coordinates: 133,28,132,0,960,0,960,140,625,131,300,145,0,166,0,21
  #     giardino:
  #       coordinates: 0,540,661,540,672,510,960,509,960,209,361,199,373,290,280,285,208,201,0,216
  #     viottolino:
  #       coordinates: 0,222,222,198,288,285,368,291,356,202,675,189,960,199,960,139,756,128,593,124,225,133,0,162
  #     viottolino_esposta:
  #       coordinates: 190,126,357,113,380,278,263,286
  #   motion:
  #     mask:
  #       - 750,399,869,402,860,334,768,338
  #     threshold: 40

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 14
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 6
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 6
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 10

# motion:
#     delta_alpha: 0.2
#     frame_alpha: 0.3
#     contour_area: 0

motion:
  mqtt_off_delay: 0

objects:
  filters:
    person:
      # min_score: 0.2
      # threshold: 0.3
      # min_area: 0
      # max_area: 24000000
      min_score: 0.6
      threshold: 0.8
      max_area: 60000
      min_area: 1200

ffmpeg:
  hwaccel_args:
#    - -hwaccel
#   - vaapi
#   - -hwaccel_device
#   - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
#   - -fflags
#   - nobuffer
#   - -flags
#   - low_delay
#   - -strict
#   - experimental
#   - -fflags
#   - +genpts+discardcorrupt
#   - -rw_timeout
#   - "5000000"
#   - -use_wallclock_as_timestamps
#   - "1" 
  output_args:
    record: preset-record-generic-audio-aac
    
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "solid"
  
live:
  height: 480
  quality: 8
    
birdseye:
  enabled: True
  width: 1280
  height: 960
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 4
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

none
