### ISSUE TITLE
[Detector Support]: Coral Detection Stuck, Killed, Doesn't Come Back

### ISSUE THREAD

**Issue by Sammy1Am** [blakeblackshear/frigate#7323]
### Describe the problem you are having

Had Frigate up and running on an Unraid system with an M.2 PCIe Coral TPU working fine; weeks at a time with no restarts.  Recently moved from Unraid to Ubuntu Server 23, and installed another M.2 NVMe drive in my server.

Since the move, Frigate seems to start up and run fine for a little while, but after several hours (like 4-12ish) `frigate.watchdog` says that detection appears to be stuck (see logs), attempts to stop it, fails, force kills it (maybe?) and then Frigate can no longer detect the TPU.  This causes Frigate to exit, the docker container restarts, but when it restarts it's unable to find the TPU and immediately fails again.

Each time Frigate restarts, the kernel log shows:
```
apex 0000:01:00.0: Error in device open cb: -110
apex 0000:01:00.0: RAM did not enable within timeout (12000 ms)
```

Restarting the server resolves the problem for another several hours.

There are a couple power-saving options that potentially can lead to the "RAM did not enable" error, but I attempted fixing those without success.  As far I can can tell there aren't any other system events happening when the detection appears to get stuck, so it seems to be an issue within the Frigate/Coral area.

- Has something changed in a recent version of Frigate that would make rolling back worth a try (and how far back can I go with my current database, config, etc.)?
- Is force-killing the detection process somehow rendering the TPU unavailable, or does the TPU become unavailable first and force-killing the process just doesn't fix it?
- This is maybe more a Coral AI question, but is there some way to manually reset/restart the TPU driver or device without restarting the whole server?  This isn't really a solution per se, but might help indicate what's breaking in the first place.

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
  coral1:
    type: edgetpu
    device: pci:0
```

### docker-compose file or Docker CLI command

```yaml
Frigate:
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/appdata/frigate/config.yml:/config/config.yml:ro
      - /mnt/appdata/frigate/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - /mnt/appdata/frigate:/db
      - /mnt/storage/security/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
      tf0:
        aliases:
          - frigate.docc
```

### Relevant log output

```shell
{"log":"2023-07-28 18:00:15.801793561  ::ffff:172.22.0.135 - - [28/Jul/2023:18:00:15 -0700] \"GET /api/events/1690592411.799732-8g0wm6/snapshot.jpg HTTP/1.1\" 200 119330 \"-\" \"python-requests/2.31.0\" \"-\"\n","stream":"stdout","time":"2023-07-29T01:00:15.801877756Z"}
{"log":"2023-07-28 18:19:38.490017284  [2023-07-28 18:19:38] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...\n","stream":"stdout","time":"2023-07-29T01:19:38.490309693Z"}
{"log":"2023-07-28 18:19:38.490288843  [2023-07-28 18:19:38] root                           INFO    : Waiting for detection process to exit gracefully...\n","stream":"stdout","time":"2023-07-29T01:19:38.490425141Z"}
{"log":"2023-07-28 18:20:08.517789509  [2023-07-28 18:20:08] root                           INFO    : Detection process didnt exit. Force killing...\n","stream":"stdout","time":"2023-07-29T01:20:08.518009193Z"}
{"log":"2023-07-28 18:20:21.429011839  [2023-07-28 18:20:21] root                           INFO    : Detection process has exited...\n","stream":"stdout","time":"2023-07-29T01:20:21.429250761Z"}
{"log":"2023-07-28 18:20:21.456607959  [2023-07-28 18:20:21] detector.coral1                INFO    : Starting detection process: 8809\n","stream":"stdout","time":"2023-07-29T01:20:21.456723214Z"}
{"log":"2023-07-28 18:20:34.354616936  [2023-07-28 18:20:33] frigate.record                 WARNING : Unable to keep up with recording segments in cache for backyard. Keeping the 5 most recent segments out of 6 and discarding the rest...\n","stream":"stdout","time":"2023-07-29T01:20:34.354845645Z"}
{"log":"2023-07-28 18:20:34.355008379  [2023-07-28 18:20:21] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0\n","stream":"stdout","time":"2023-07-29T01:20:34.355168739Z"}
{"log":"2023-07-28 18:20:34.355399193  Process detector:coral1:\n","stream":"stdout","time":"2023-07-29T01:20:34.355541953Z"}
{"log":"2023-07-28 18:20:34.355410670  [2023-07-28 18:20:34] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.\n","stream":"stdout","time":"2023-07-29T01:20:34.355574268Z"}




apex 0000:01:00.0: Error in device open cb: -110
apex 0000:01:00.0: RAM did not enable within timeout (12000 ms)
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2
