### ISSUE TITLE
[Support]: wss is getting 404 errors in browser console

### ISSUE THREAD

**Issue by TheBlueKingLP** [blakeblackshear/frigate#7327]
### Describe the problem you are having

I am getting 404 errors in the browser console and I believe my 2 way audio is not working due to this

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: core-mosquitto
  port: 1883
  topic_prefix: <redacted>
  client_id: <redacted>
  user: <redacted>
  password: "<redacted>"

  stats_interval: 60

database:
  path: /config/frigate/frigate.db

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  input_args: preset-rtsp-restream
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy

detect:
  width: 2560
  height: 1920
  fps: 5
  stationary:
    interval: 0
    threshold: 50

record:
  enabled: True
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 15
    post_capture: 60
    objects:
      - person
      - dog
      - cat
    retain:
      default: 30
      mode: motion
      objects:
        person: 60

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  retain:
    default: 60
    objects:
      person: 180

go2rtc:
  ffmpeg:
    bin: ffmpeg
    volume: '-af "volume=20dB"'
  streams:
    doorbell:
      - rtsp://<redacted>:<redacted>@10.43.22.84:554/h264Preview_01_main

live:
  height: 2560
  quality: 1





cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=copy
          roles:
            - detect
            - record
            - rtmp

    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 2560
      quality: 70
  
ui:
  live_mode: webrtc
  use_experimental: False
  date_style: full
  time_style: full

telemetry:
  version_check: True
```

### Relevant log output

```shell
WebSocket connection to 'wss://<domain redacted>/api/frigate/frigate/mse/api/ws?src=doorbell&authSig=<auth redacted>' failed: 
onconnect @ live-go2rtc-0795a62f.js:1
(anonymous) @ live-go2rtc-0795a62f.js:1
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]

FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1920
FPS: 20/1

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell PoE
