### ISSUE TITLE
[Support]: Events with snapshot but no Clip/Video

### ISSUE THREAD

**Issue by madman2021** [blakeblackshear/frigate#7331]
### Describe the problem you are having

For whatever reason I seem to get a lot of events that have no clips.
![image](https://github.com/blakeblackshear/frigate/assets/2904531/5eebe729-33cf-4b9a-86b8-dae029c1e2a7)

In then makes the event as no clip so hides the clip, this is also confirmed in the logs saying it was not found.
![image](https://github.com/blakeblackshear/frigate/assets/2904531/ad6ed106-5980-45fc-90e0-a942641806c6)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: "mqtt"
go2rtc:
  streams:
    reolink: 
      - http://192.168.0.253/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=WowSuchPasswordMuchHack
      - "ffmpeg:reolink#audio=opus"
motion:
  delta_alpha: 0.2
  threshold: 30
  contour_area: 40
cameras:
  Door: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
        mask:    
          - 877,792,990,780,1049,769,1125,776,1191,789,1208,925,1053,1238,824,1222,783,1023
          - 1884,0,1851,50,1805,162,1780,292,1784,445,0,516,0,0    
          - 2560,0,2560,695,2372,596,2345,634,2281,604,2213,609,2179,610,2124,590,2017,580,1900,558,1837,536,1805,505,1784,463,1757,394,1790,365,1816,275,1787,227,1795,155,1876,0    
          - 1148,1584,1796,1686,2067,1697,2162,1235,2507,1236,2326,998,2387,930,2289,692,2099,836,2094,925,2047,692,1721,535,1576,571,1533,599,1440,557,1410,607,1371,685,1362,728,1369,800,1358,916,1216,1347
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
    zones:  
      zone_0:
       coordinates: 0,1920,1008,1920,2560,1920,2560,846,1531,692,777,700,0,560
  Right:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://admin:wowanotherrealpasswordthatisnotfakeatall@192.168.201.30/H265/ch1/main/av_stream
          roles:
            - detect
    detect:
      width: 3072
      height: 1728
    zones:  
      zone_0:
        coordinates:
          1344,1356,1583,1276,1731,1322,1773,1728,2142,1728,1985,1521,2693,1262,2743,971,2263,906,0,919,0,1239
    motion:
      mask:    
        - 1708,1275,1756,1728,0,1728,0,1228
        - 3072,1728,3072,967,2692,1076,2603,1007,2534,948,2516,853,2449,832,2368,941,2220,987,2070,1107,2088,1216,2085,1268,1990,1305,1974,1501,2150,1728
        - 2618,886,2935,948,3072,978,3072,0,0,0,0,848
  Left:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://admin:wowrealpasswordreallycool@192.168.201.31/H265/ch1/main/av_stream
          roles:
            - detect
    detect:
      width: 3072
      height: 1728
    motion:
      mask:    
      - 0,1728,1752,1728,3072,1728,3072,1412,1545,1335,1527,1225,1443,1113,1237,1067,1098,1145,1002,1041,918,1021,836,1230,619,1213,557,1115,433,1097,383,1149,0,1076
      - 0,141,0,1059,1387,990,3072,1075,3072,909,3072,0,0,0
    zones:  
      zone_0:
        coordinates: 2926,1621,2992,1123,791,1030,98,1083,869,1332
detect:
  enabled: true
record:
  enabled: true
  retain:
    days: 1
    mode: active_objects
  events:
    retain:
      default: 1
      mode: active_objects
snapshots:
  enabled: true
  retain:
    default: 1
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /trt-models/yolov4-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
objects:
  track:
    - person
    - motorcycle
telemetry:
  version_check: true
logger:
  default: debug
```

### Relevant log output

```shell
Too long making a pastebin
https://pastebin.com/eF686dJL
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"},{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560}]}}]
```

### Frigate stats

```json
{"Door":{"camera_fps":5.0,"capture_pid":441,"detection_enabled":1,"detection_fps":9.9,"ffmpeg_pid":3349,"pid":435,"process_fps":5.0,"skipped_fps":0.0},"Left":{"camera_fps":5.0,"capture_pid":447,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":463,"pid":439,"process_fps":5.0,"skipped_fps":0.0},"Right":{"camera_fps":5.1,"capture_pid":444,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":464,"pid":437,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.5"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"2.0","mem":"3.8"},"117":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.3"},"135":{"cpu":"0.0","mem":"0.3"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.0"},"139":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"155":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"175":{"cpu":"0.0","mem":"0.0"},"203":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"3349":{"cpu":"5.6","mem":"1.6"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"424":{"cpu":"0.0","mem":"1.1"},"429":{"cpu":"0.3","mem":"0.1"},"430":{"cpu":"2.7","mem":"6.9"},"432":{"cpu":"2.0","mem":"1.3"},"435":{"cpu":"10.6","mem":"1.6"},"436":{"cpu":"0.0","mem":"0.3"},"437":{"cpu":"0.7","mem":"1.3"},"438":{"cpu":"0.0","mem":"0.4"},"439":{"cpu":"0.7","mem":"1.3"},"440":{"cpu":"0.0","mem":"0.4"},"441":{"cpu":"5.0","mem":"1.4"},"444":{"cpu":"5.0","mem":"1.3"},"447":{"cpu":"5.0","mem":"1.3"},"457":{"cpu":"0.0","mem":"0.1"},"463":{"cpu":"13.0","mem":"1.7"},"464":{"cpu":"12.6","mem":"1.7"},"4956":{"cpu":"0.0","mem":"0.0"},"4972":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"4.3","mem":"0.2"},"97":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"11028.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":9.9,"detectors":{"tensorrt":{"detection_start":0.0,"inference_speed":3.24,"pid":430}},"gpu_usages":{"NVIDIA GeForce GTX 1080 Ti":{"gpu":"3 %","mem":"13.0 %"}},"service":{"last_updated":1690685656,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":241.9,"mount_type":"tmpfs","total":268.4,"used":26.6},"/media/frigate/clips":{"free":13094.6,"mount_type":"ext4","total":52520.5,"used":36724.8},"/media/frigate/recordings":{"free":13094.6,"mount_type":"ext4","total":52520.5,"used":36724.8},"/tmp/cache":{"free":990.0,"mount_type":"tmpfs","total":1000.0,"used":10.0}},"temperatures":{},"uptime":8756,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink,annke
