### ISSUE TITLE
[Support]: numpy has no attribute bool

### ISSUE THREAD

**Issue by mrplow** [blakeblackshear/frigate#7343]
### Describe the problem you are having

#7319 updated numpy from 1.23 to numpy, 1.25.

The 1.20 numpy release notes that np.bool will be deprecated and results in warnings in 1.23 and is fully deprecated in 1.24.
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

I believe this is the reason my frigate not starting and looping with the following logs, I'm a bit surprised no one has report this yet.

I get these errors running dev-b42e995-tensorrt or later, dev-f8c0f74-tensorrt works fine.

### Version

b42e995

### Frigate config file

```yaml
mqtt:
  host: <redacted>
  user: <redacted>
  password: <redacted>

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true

go2rtc:
  streams:
    frontyardrecord: #Loryta IPC-T5442TM-AS-LED S2 - V2.840.15OG00D.0.R.220818
    - ffmpeg:rtsp://<redacted>:<redacted>@192.168.1.154:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:frontyardrecord#audio=opus#audio=copy
    frontyardstream: #Loryta IPC-T5442TM-AS-LED S2 - V2.840.15OG00D.0.R.220818
    - ffmpeg:rtsp://<redacted>:<redacted>@192.168.1.154:554/cam/realmonitor?channel=1&subtype=2
    - ffmpeg:frontyardstream#audio=opus#audio=copy
    frontdoor: #Reolink RLC-810A - IPC_523128M8MP - v3.1.0.956_22041503
    - ffmpeg:http://192.168.1.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<redacted>&password=<redacted>
    - ffmpeg:frontdoor#audio=opus#audio=copy
    backleft: #Reolink Duo PoE - IPC_528B174MP - v3.0.0.1388_22100600
    - ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<redacted>&password=<redacted>
    - ffmpeg:backleft#audio=opus#audio=copy
    backright:
    - ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=<redacted>&password=<redacted>
    - ffmpeg:backright#audio=opus#audio=copy
    inside: #Amcrest IP2M-841B - V2.420.AC00.18.R
    - rtsp://<redacted>:<redacted>@192.168.1.153:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:inside#audio=opus#audio=copy

cameras:
  frontyard:
    timestamp_style:
      position: tl
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path:
         rtsp://<redacted>:<redacted>@192.168.1.154:554/cam/realmonitor?channel=1&subtype=2
        input_args: preset-rtsp-generic
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/frontyardrecord?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: frontyardstream
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - bear
      - bird
      - car
      - cat
      - dog
      - person
      filters:
        car:
          min_area: 1000
          mask:
          - 1076,0,821,0,821,93,1112,149
        person:
          mask:
          - 466,460,466,621,365,621,365,460
          - 313,162,313,278,227,278,227,162
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000

  inside:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/inside?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
    birdseye:
      enabled: false
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 1
        mode: all
    onvif:
      host: 192.168.1.153
      port: 80
      user: <redacted>
      password: <redacted>

  frontdoor:
    timestamp_style:
      position: tr
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/frontdoor?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - detect
        - record
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - bear
      - bird
      - car
      - cat
      - dog
      - person
      filters:
        car:
          mask:
          - 1280,0,1280,720,0,720,0,239,333,201,370,112,659,113,699,0
          - 0,0,282,0,282,87,0,87
        bird:
          mask:
          - 862,121,1129,124,1069,692,745,668
          - 588,27,733,27,733,283,588,283
        bear:
          min_area: 5000
          mask:
          - 862,121,1129,124,1069,692,745,668
        person:
          min_area: 5000
          mask:
          - 862,121,1129,124,1069,692,745,668
        cat:
          mask:
          - 862,121,1129,124,1069,692,745,668
        dog:
          mask:
          - 862,121,1129,124,1069,692,745,668
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000

  backleft:
    timestamp_style:
      position: tl
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/backleft?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - detect
        - record
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask:
      - 1280,720,1280,290,534,384,496,720
    objects:
      track:
      - bear
      - bird
      - cat
      - dog
      - person
      filters:
        bear:
          mask:
          - 1280,720,1280,290,534,384,496,720
        bird:
          max_area: 10000
          mask:
          - 1280,720,1280,290,534,384,496,720
        car:
          mask:
          - 1280,720,1280,290,534,384,496,720
        cat:
          mask:
          - 1280,720,1280,290,534,384,496,720
        dog:
          mask:
          - 1280,720,1280,290,534,384,496,720
        person:
          min_area: 10000
          mask:
          - 1280,720,1280,290,534,384,496,720
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000

  backright:
    timestamp_style:
      position: tr
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/backright?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - detect
        - record
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask:
      - 0,242,0,720,854,720,303,237
    objects:
      track:
      - bear
      - bird
      - cat
      - dog
      - person
      filters:
        bear:
          min_area: 2500
          mask:
          - 0,242,0,720,854,720,303,237
        bird:
          max_area: 10000
          min_area: 800
          mask:
          - 0,242,0,720,854,720,303,237
          - 314,74,315,111,281,112,277,75
        car:
          mask:
          - 0,242,0,720,854,720,303,237
        cat:
          mask:
          - 0,242,0,720,854,720,303,237
        dog:
          mask:
          - 0,242,0,720,854,720,303,237
        person:
          min_area: 10000
          mask:
          - 0,242,0,720,854,720,303,237
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7x-320.trt
  labelmap_path: /config/model_cache/tensorrt/coco_91cl.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
  model_type: yolox

record:
  enabled: true
  retain:
    days: 12
    mode: all
  events:
    retain:
      default: 20
      mode: active_objects
      objects:
        dog: 12
        cat: 12
        car: 12

objects:
  track:
  - bear
  - bird
  - car
  - cat
  - dog
  - person
  filters:
    person:
      threshold: 0.85
    bear:
      threshold: 0.8
    bird:
      threshold: 0.8
    car:
      threshold: 0.8
    cat:
      threshold: 0.8
    dog:
      threshold: 0.8

birdseye:
  enabled: true
  mode: continuous

timestamp_style:
  format: '%Y-%m-%d %l:%M:%S %p'
  effect: shadow

telemetry:
  stats:
    amd_gpu_stats: false
    intel_gpu_stats: false
    network_bandwidth: false
```

### Relevant log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service trt-model-prepare: starting
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2023-07-31 00:12:18.630486252  [INFO] Preparing go2rtc config...
frigate  | No models to convert.
frigate  | s6-rc: info: service trt-model-prepare successfully started
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2023-07-31 00:12:18.652016697  [INFO] Preparing Frigate...
frigate  | 2023-07-31 00:12:18.652282034  [INFO] Starting NGINX...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-07-31 00:12:18.692479565  [INFO] Starting Frigate...
frigate  | 2023-07-31 00:12:18.865058195  [INFO] Starting go2rtc...
frigate  | 2023-07-31 00:12:18.936172171  00:12:18.936 INF go2rtc version 1.6.2 linux/amd64
frigate  | 2023-07-31 00:12:18.936434130  00:12:18.936 INF [api] listen addr=0.0.0.0:1984
frigate  | 2023-07-31 00:12:18.936720256  00:12:18.936 INF [rtsp] listen addr=0.0.0.0:8554
frigate  | 2023-07-31 00:12:18.936875300  00:12:18.936 INF [webrtc] listen addr=0.0.0.0:8555/tcp
frigate  | 2023-07-31 00:12:18.937261273  00:12:18.937 INF [srtp] listen addr=0.0.0.0:8443
frigate  | 2023-07-31 00:12:19.858440739  [2023-07-31 00:12:19] frigate.app                    INFO    : Starting Frigate (0.13.0-eaf7078)
frigate  | 2023-07-31 00:12:20.250064003  2023/07/31 00:12:20 [error] 195#195: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.10, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.1.10:5000"
frigate  | 2023-07-31 00:12:23.391528766  [2023-07-31 00:12:23] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2023-07-31 00:12:23.394861094  [2023-07-31 00:12:23] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2023-07-31 00:12:23.990986064  [2023-07-31 00:12:23] frigate.app                    INFO    : Recording process started: 358
frigate  | 2023-07-31 00:12:23.993714706  [2023-07-31 00:12:23] frigate.app                    INFO    : go2rtc process pid: 103
frigate  | 2023-07-31 00:12:24.034088799  [2023-07-31 00:12:24] frigate.app                    INFO    : Output process started: 370
frigate  | 2023-07-31 00:12:24.039261817  [2023-07-31 00:12:24] detector.tensorrt              INFO    : Starting detection process: 368
frigate  | 2023-07-31 00:12:24.054923935  [2023-07-31 00:12:24] frigate.app                    INFO    : Camera processor started for frontyard: 377
frigate  | 2023-07-31 00:12:24.104207739  [2023-07-31 00:12:24] frigate.app                    INFO    : Camera processor started for inside: 380
frigate  | 2023-07-31 00:12:24.104376520  [2023-07-31 00:12:24] frigate.app                    INFO    : Camera processor started for frontdoor: 382
frigate  | 2023-07-31 00:12:24.104378714  [2023-07-31 00:12:24] frigate.app                    INFO    : Camera processor started for backleft: 385
frigate  | 2023-07-31 00:12:24.104938720  [2023-07-31 00:12:24] frigate.app                    INFO    : Camera processor started for backright: 389
frigate  | 2023-07-31 00:12:24.113054923  [2023-07-31 00:12:24] frigate.app                    INFO    : Capture process started for frontyard: 391
frigate  | 2023-07-31 00:12:24.121488390  [2023-07-31 00:12:24] frigate.app                    INFO    : Capture process started for inside: 395
frigate  | 2023-07-31 00:12:24.128882375  [2023-07-31 00:12:24] frigate.app                    INFO    : Capture process started for frontdoor: 398
frigate  | 2023-07-31 00:12:24.137170018  [2023-07-31 00:12:24] frigate.app                    INFO    : Capture process started for backleft: 406
frigate  | 2023-07-31 00:12:24.145449884  [2023-07-31 00:12:24] frigate.app                    INFO    : Capture process started for backright: 412
frigate  | 2023-07-31 00:12:24.389869298  [2023-07-31 00:12:24] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 151 MiB
frigate  | 2023-07-31 00:12:24.545603688  [2023-07-31 00:12:24] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 319, GPU 553 (MiB)
frigate  | 2023-07-31 00:12:24.550067625  [2023-07-31 00:12:24] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 320, GPU 563 (MiB)
frigate  | 2023-07-31 00:12:24.562051824  [2023-07-31 00:12:24] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +150, now: CPU 0, GPU 150 (MiB)
frigate  | 2023-07-31 00:12:24.562399147  /usr/local/lib/python3.9/dist-packages/tensorrt/__init__.py:166: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
frigate  | 2023-07-31 00:12:24.562401081    bool: np.bool,
frigate  | 2023-07-31 00:12:24.562698954  Process detector:tensorrt:
frigate  | 2023-07-31 00:12:24.563235171  Traceback (most recent call last):
frigate  | 2023-07-31 00:12:24.563291860    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2023-07-31 00:12:24.563293322      self.run()
frigate  | 2023-07-31 00:12:24.563294461    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2023-07-31 00:12:24.563295525      self._target(*self._args, **self._kwargs)
frigate  | 2023-07-31 00:12:24.563297369    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate  | 2023-07-31 00:12:24.563306826      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2023-07-31 00:12:24.563308062    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate  | 2023-07-31 00:12:24.563309712      self.detect_api = create_detector(detector_config)
frigate  | 2023-07-31 00:12:24.563310877    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2023-07-31 00:12:24.563311914      return api(detector_config)
frigate  | 2023-07-31 00:12:24.563313064    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 221, in __init__
frigate  | 2023-07-31 00:12:24.563323864      self.input_shape = self._get_input_shape()
frigate  | 2023-07-31 00:12:24.563336483    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 99, in _get_input_shape
frigate  | 2023-07-31 00:12:24.563353447      trt.nptype(self.engine.get_binding_dtype(binding)),
frigate  | 2023-07-31 00:12:24.563354620    File "/usr/local/lib/python3.9/dist-packages/tensorrt/__init__.py", line 166, in nptype
frigate  | 2023-07-31 00:12:24.563355619      bool: np.bool,
frigate  | 2023-07-31 00:12:24.563356792    File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 313, in __getattr__
frigate  | 2023-07-31 00:12:24.563357797      raise AttributeError(__former_attrs__[attr])
frigate  | 2023-07-31 00:12:24.563358890  AttributeError: module 'numpy' has no attribute 'bool'.
frigate  | 2023-07-31 00:12:24.563361012  `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
frigate  | 2023-07-31 00:12:24.563367988  The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
frigate  | 2023-07-31 00:12:24.563369109      https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
frigate  | 2023-07-31 00:12:24.563492577  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f8fcff9b940>
frigate  | 2023-07-31 00:12:24.563494070  Traceback (most recent call last):
frigate  | 2023-07-31 00:12:24.563495209    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__
frigate  | 2023-07-31 00:12:24.563496162      if self.outputs is not None:
frigate  | 2023-07-31 00:12:24.563497253  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
frigate  | 2023-07-31 00:12:28.629541276  [INFO] Starting go2rtc healthcheck service...
frigate  | 2023-07-31 00:12:29.289186412  [2023-07-31 00:12:29] frigate.video                  ERROR   : frontdoor: Unable to read frames from ffmpeg process.
frigate  | 2023-07-31 00:12:29.289319882  [2023-07-31 00:12:29] frigate.video                  ERROR   : frontdoor: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-07-31 00:12:44.180177643  [2023-07-31 00:12:44] watchdog.frontdoor             ERROR   : Ffmpeg process crashed unexpectedly for frontdoor.
frigate  | 2023-07-31 00:12:44.180181891  [2023-07-31 00:12:44] watchdog.frontdoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-07-31 00:12:44.180196783  [2023-07-31 00:12:44] ffmpeg.frontdoor.detect        ERROR   : rtsp://127.0.0.1:8554/frontdoor?video=copy&audio=aac: Invalid data found when processing input
frigate  | 2023-07-31 00:12:44.455013618  [2023-07-31 00:12:44] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-07-31 00:12:44.463633496  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2023-07-31 00:12:44.520487532  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2023-07-31 00:12:44.523367084  [2023-07-31 00:12:44] frigate.app                    INFO    : Stopping...
frigate  | 2023-07-31 00:12:44.528264752  [2023-07-31 00:12:44] frigate.events.cleanup         INFO    : Exiting event cleanup...
frigate  | 2023-07-31 00:12:44.530101024  [2023-07-31 00:12:44] frigate.stats                  INFO    : Exiting stats emitter...
frigate  | 2023-07-31 00:12:44.530105632  [2023-07-31 00:12:44] frigate.ptz.autotrack          INFO    : Exiting autotracker...
frigate  | 2023-07-31 00:12:44.530107064  [2023-07-31 00:12:44] frigate.watchdog               INFO    : Exiting watchdog...
frigate  | 2023-07-31 00:12:44.530108427  [2023-07-31 00:12:44] frigate.record.cleanup         INFO    : Exiting recording cleanup...
frigate  | 2023-07-31 00:12:44.537412555  [2023-07-31 00:12:44] frigate.object_processing      INFO    : Exiting object processor...
frigate  | 2023-07-31 00:12:44.537416480  [2023-07-31 00:12:44] frigate.storage                INFO    : Exiting storage maintainer...
frigate  | 2023-07-31 00:12:45.019338641  [2023-07-31 00:12:45] frigate.comms.ws               INFO    : Exiting websocket client...
frigate  | 2023-07-31 00:12:45.470206127  [2023-07-31 00:12:45] frigate.events.maintainer      INFO    : Exiting event processor...
frigate  | 2023-07-31 00:12:45.470715243  [2023-07-31 00:12:45] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate  | 2023-07-31 00:12:45.473119348  [2023-07-31 00:12:45] watchdog.frontyard             INFO    : Terminating the existing ffmpeg process...
frigate  | 2023-07-31 00:12:45.473303002  [2023-07-31 00:12:45] watchdog.inside                INFO    : Terminating the existing ffmpeg process...
frigate  | 2023-07-31 00:12:45.473551669  [2023-07-31 00:12:45] watchdog.inside                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2023-07-31 00:12:45.473654119  [2023-07-31 00:12:45] watchdog.frontyard             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2023-07-31 00:12:45.473923387  [2023-07-31 00:12:45] watchdog.backright             INFO    : Terminating the existing ffmpeg process...
frigate  | 2023-07-31 00:12:45.473925946  [2023-07-31 00:12:45] watchdog.backright             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2023-07-31 00:12:45.474064665  [2023-07-31 00:12:45] watchdog.frontdoor             INFO    : Terminating the existing ffmpeg process...
frigate  | 2023-07-31 00:12:45.474116638  [2023-07-31 00:12:45] watchdog.frontdoor             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2023-07-31 00:12:45.474429520  [2023-07-31 00:12:45] watchdog.backleft              INFO    : Terminating the existing ffmpeg process...
frigate  | 2023-07-31 00:12:45.474587695  [2023-07-31 00:12:45] watchdog.backleft              INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2023-07-31 00:12:45.537223841  [2023-07-31 00:12:45] watchdog.frontyard             INFO    : Terminating the existing ffmpeg process...
frigate  | 2023-07-31 00:12:45.537227742  [2023-07-31 00:12:45] watchdog.frontyard             INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2023-07-31 00:12:45.650061799  [2023-07-31 00:12:45] frigate.output                 INFO    : exiting output process...
frigate  | 2023-07-31 00:12:46.112865563  [2023-07-31 00:12:46] frigate.video                  INFO    : frontdoor: exiting subprocess
frigate  | 2023-07-31 00:12:46.316765122  [2023-07-31 00:12:46] frigate.video                  INFO    : inside: exiting subprocess
frigate  | 2023-07-31 00:12:49.872725273  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 28 leaked shared_memory objects to clean up at shutdown
frigate  | 2023-07-31 00:12:49.872728948    warnings.warn('resource_tracker: There appear to be %d '
frigate  | 2023-07-31 00:12:49.874925626  [INFO] Service Frigate exited with code 0 (by signal 0)
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service trt-model-prepare: stopping
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service trt-model-prepare successfully stopped
frigate  | 2023-07-31 00:12:49.876982258  exit with signal: terminated
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2023-07-31 00:12:49.882069423  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A
