### ISSUE TITLE
[Support]: Stuck at "In progress"

### ISSUE THREAD

**Issue by uilton-oliveira** [blakeblackshear/frigate#7350]
### Describe the problem you are having

"In progress" stuck behind a mask (in some cases it stay stuck for hours...)
![image](https://github.com/blakeblackshear/frigate/assets/7059651/6cff1389-feb5-4885-b85d-7babae119451)

Image with mask hidden:
![image](https://github.com/blakeblackshear/frigate/assets/7059651/85eeb79d-a9a0-4c1f-af74-9e9a92c0b5fd)

Mask shown:
![image](https://github.com/blakeblackshear/frigate/assets/7059651/eee6f0d8-b3ac-49ee-b563-fc7ff3aea852)

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  enabled: False
go2rtc:
  streams:
    gate:
      - "ffmpeg:rtsp://10.0.0.184:554/user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}&channel=1&stream=0.sdp?#video=h264#audio=opus#audio=aac"
    gate_sub:
      - rtsp://10.0.0.184:554/user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}&channel=1&stream=1.sdp?
    front:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.101:554/stream1#video=copy#audio=opus#audio=aac"
    front_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.101:554/stream2
  webrtc:
    candidates:
      - 10.0.0.108:8555
      - stun:8555
cameras:
  gate:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gate
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 800
      height: 448
    motion:
      mask:
        - 800,0,800,54,540,33,269,38,272,0
        - 280,0,0,0,0,267,45,266,50,192,284,183
  front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
    motion:
      mask:
        - 464,88,616,360,640,360,640,360,640,360,640,0,587,0
        - 0,0,0,46,237,45,235,0
birdseye:
  enabled: True
  mode: continuous
ffmpeg:
  hwaccel_args: preset-vaapi
rtmp:
  enabled: false
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
objects:
  track:
    - person
    - cat
    - dog
database:
  # The path to store the SQLite DB (default: shown below)
  path: /db/frigate.db
record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
    pre_capture: 10
    post_capture: 15
```

### Relevant log output

```shell
No relevant log was found...
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://10.0.0.184:554/':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuvj420p(pc), 2560x1440, 10 fps, 10 tbr, 90k tbn, 10 tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "16": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "89": {
            "cpu": "3.0",
            "mem": "0.0"
        },
        "97": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "98": {
            "cpu": "1.3",
            "mem": "0.3"
        },
        "117": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "134": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "135": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "136": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "137": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "145": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "173": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "213": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "250": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "273": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "283": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "305": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "335": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "364": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "411": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "448": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "481": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "513": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "537": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "582": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "608": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "838": {
            "cpu": "3.7",
            "mem": "0.0"
        },
        "858": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "863": {
            "cpu": "0.3",
            "mem": "0.0"
        },
        "864": {
            "cpu": "1.7",
            "mem": "0.7"
        },
        "865": {
            "cpu": "0.7",
            "mem": "0.1"
        },
        "869": {
            "cpu": "8.7",
            "mem": "0.1"
        },
        "870": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "871": {
            "cpu": "0.7",
            "mem": "0.1"
        },
        "872": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "873": {
            "cpu": "0.7",
            "mem": "0.1"
        },
        "876": {
            "cpu": "0.3",
            "mem": "0.1"
        },
        "877": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "879": {
            "cpu": "2.0",
            "mem": "0.1"
        },
        "886": {
            "cpu": "2.7",
            "mem": "0.1"
        },
        "889": {
            "cpu": "1.3",
            "mem": "0.0"
        },
        "892": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "893": {
            "cpu": "83.7",
            "mem": "0.2"
        },
        "2376": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "2390": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "2402": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.2"
        },
        "MiB": {
            "cpu": "59340.4",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top": {
            "cpu": "load",
            "mem": "average:"
        }
    },
    "detection_fps": 4.9,
    "detectors": {
        "ov": {
            "detection_start": 0,
            "inference_speed": 7.87,
            "pid": 864
        }
    },
    "front": {
        "camera_fps": 5.1,
        "capture_pid": 876,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 886,
        "pid": 871,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "gate": {
        "camera_fps": 5,
        "capture_pid": 873,
        "detection_enabled": 1,
        "detection_fps": 4.9,
        "ffmpeg_pid": 879,
        "pid": 869,
        "process_fps": 5,
        "skipped_fps": 0
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "0.59 %",
            "mem": "- %"
        }
    },
    "service": {
        "last_updated": 1690899537,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 132.1,
                "mount_type": "tmpfs",
                "total": 134.2,
                "used": 2.2
            },
            "/media/frigate/clips": {
                "free": 1212886.3,
                "mount_type": "exfat",
                "total": 2000380,
                "used": 787493.7
            },
            "/media/frigate/recordings": {
                "free": 1212886.3,
                "mount_type": "exfat",
                "total": 2000380,
                "used": 787493.7
            },
            "/tmp/cache": {
                "free": 1835765.3,
                "mount_type": "ext4",
                "total": 1967317.5,
                "used": 31542.4
            }
        },
        "temperatures": {},
        "uptime": 895,
        "version": "0.12.0-da3e197"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

besder ptz ip 8mp, 4k
