### ISSUE TITLE
[Config Support]: help with optimizing global settings

### ISSUE THREAD

**Issue by mariomare22** [blakeblackshear/frigate#7365]
### Describe the problem you are having

Hello,

I would like to optimize this config file with global settings;

as you can see most of the config is repeated twice (for each camera) and it's totally the same.

How can I shrink it? what options do I have for global args?

Thank you

Mario

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: mqtt.home
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: mqtt_password


snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True

cameras:
  sala:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://cam1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=webuser&password=Streaming
          roles:
            - record
            - rtmp
        - path: http://cam1/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=webuser&password=Streaming
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 7

    objects:
     # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      filters:
        person:
          min_score: 0.8

    record:
      enabled: True
      retain:
        days: 2
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 5
          mode: active_objects

    motion:

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 720
      retain:
        default: 10
        objects:
          person: 15

  elisa:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://cam2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=webuser&password=Streaming
          roles:
            - record
            - rtmp
        - path: http://cam2/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=webuser&password=Streaming
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 7

    objects:
     # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      filters:
        person:
          min_score: 0.8

    record:
      enabled: True
      retain:
        days: 2
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 5
          mode: active_objects

    motion:

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 720
      retain:
        default: 10
        objects:
          person: 15
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
