### ISSUE TITLE
[Support]: frigate:dev-00b9a49 [ERROR] Trying to migrate the db path from '/media/frigate/frigate.db' to the '/config' dir, but '/config' is not a mountpoint, please mount the '/config' dir

### ISSUE THREAD

**Issue by johnvprcam24573455623** [blakeblackshear/frigate#7372]
### Describe the problem you are having

I wanted to test frigate:dev-00b9a49, however I get this error:

`[ERROR] Trying to migrate the db path from '/media/frigate/frigate.db' to the '/config' dir, but '/config' is not a mountpoint, please mount the '/config' dir`

It works fine with frigate:stable

### Version

frigate:dev-00b9a49

### Frigate config file

```yaml
### Docker compose
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    mem_limit: "3g"   
#    image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:dev-00b9a49

    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config.yml:/config/config.yml 
      - /media/frigate:/media/frigate
      - /home/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
          
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # Birdseye In v 0.12
    environment:
      FRIGATE_RTSP_PASSWORD: XXXXX


--------------------
Frigate

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    wcam1:
      - "rtsp://10.10.40.211:8554/1080p?mp4"
    wcam1_sub:  
      - "rtsp://10.10.40.211:8554/360p?mp4"

cameras:
  wcam1:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/wcam1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wcam1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant log output

```shell
2023-08-02 21:37:36.744934216  [ERROR] Trying to migrate the db path from '/media/frigate/frigate.db' to the '/config' dir, but '/config' is not a mountpoint, please mount the '/config' dir

s6-rc: info: service legacy-services successfully started
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

wyze
