### ISSUE TITLE
Exception in thread detected_frames_processor crashes Frigate

### ISSUE THREAD

**Issue by walthowd** [blakeblackshear/frigate#739]
**Describe the bug**

Frigate fails with a traceback when trying to write snapshot when camera fails to provide frame. 

```
2021-02-06T16:50:33.756896300-06:00 Exception in thread detected_frames_processor:
2021-02-06T16:50:33.756935869-06:00 Traceback (most recent call last):
2021-02-06T16:50:33.756988878-06:00   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-02-06T16:50:33.759500490-06:00     self.run()
2021-02-06T16:50:33.759529123-06:00   File "/opt/frigate/frigate/object_processing.py", line 529, in run
2021-02-06T16:50:33.760811407-06:00     camera_state.update(frame_time, current_tracked_objects, motion_boxes, regions)
2021-02-06T16:50:33.760839298-06:00   File "/opt/frigate/frigate/object_processing.py", line 367, in update
2021-02-06T16:50:33.762106158-06:00     c(self.name, removed_obj, frame_time)
2021-02-06T16:50:33.762130292-06:00   File "/opt/frigate/frigate/object_processing.py", line 465, in end
2021-02-06T16:50:33.762355787-06:00     j.write(jpg_bytes)
2021-02-06T16:50:33.762396006-06:00 TypeError: a bytes-like object is required, not 'NoneType'
```

**Version of frigate**
0.8.1-amd64

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
cameras: 
  garage: 
    ffmpeg: 
      inputs:
        - path: "rtsp://view:camera-password@192.168.1.73:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
        - path: "rtsp://view:camera-password@192.168.1.73:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - clips
            - record
            - rtmp
    fps: 5
    height: 480
    width: 704 
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    snapshots:
      enabled: true
      bounding_box: true
      crop: true
      retain:
        default: 30
  backporch: 
    ffmpeg: 
      inputs:
        - path: "rtsp://view:camera-password@192.168.1.118:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
        - path: "rtsp://view:camera-password@192.168.1.118:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - clips
            - record
            - rtmp
    fps: 5
    height: 480
    width: 704 
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    snapshots:
      enabled: true
      bounding_box: true
      crop: true
      retain:
        default: 30
  sideyard: 
    ffmpeg: 
      inputs:
        - path: "rtsp://view:camera-password@192.168.1.127:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
        - path: "rtsp://view:camera-password@192.168.1.127:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - clips
            - record
            - rtmp
    fps: 5
    height: 480
    width: 704 
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    snapshots:
      enabled: true
      bounding_box: true
      crop: true
      retain:
        default: 30
  backyard-nw: 
    ffmpeg: 
      inputs:
        - path: "rtsp://view:camera-password@192.168.1.208:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
        - path: "rtsp://view:camera-password@192.168.1.208:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - clips
            - record
            - rtmp
    fps: 5
    height: 480
    width: 704 
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    snapshots:
      enabled: true
      bounding_box: true
      crop: true
      retain:
        default: 30
  backyard: 
    ffmpeg: 
      inputs:
        - path: "rtsp://view:camera-password@192.168.1.71:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
        - path: "rtsp://view:camera-password@192.168.1.71:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - clips
            - record
            - rtmp
    fps: 5
    height: 480
    width: 704 
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    snapshots:
      enabled: true
      bounding_box: true
      crop: true
      retain:
        default: 30
  driveway: 
    ffmpeg: 
      inputs:
        - path: "rtsp://view:camera-password@192.168.1.150:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
        - path: "rtsp://view:camera-password@192.168.1.150:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - clips
            - record
            - rtmp
    fps: 5
    height: 480
    width: 704 
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    objects: 
      filters:
        car:
          mask:
            - 385,142,704,131,704,0,364,0,0,0,0,213
      track: 
        - person
        - car
        - truck
    snapshots:
      enabled: true
      bounding_box: true
      crop: true
      retain:
        default: 30
    motion:
      mask:
        - 385,142,704,131,704,0,364,0,0,0,0,213
  doorbell: 
    ffmpeg: 
      inputs:
        - path: "rtsp://admin:HFMMFC@192.168.1.48:554/h264/ch01/sub/av_stream"
          roles:
            - detect
        - path: "rtsp://admin:HFMMFC@192.168.1.48:554/h264/ch01/main/av_stream"
          roles:
            - clips
#            - rtmp
            - record
    fps: 10
    height: 512
    width: 384
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    objects: 
      filters:
        person:
          mask:
            - 0,295,0,0,384,0,384,332,157,313
      track: 
        - person
    motion:
      mask:
        - 0,295,0,0,384,0,384,332,157,313
    snapshots:
      enabled: true
      bounding_box: true
      crop: true
      retain:
        default: 30

database:
  path: /config/frigate.db

detectors: 
  coral: 
    device: usb
    type: edgetpu

ffmpeg: 
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
  hwaccel_args: 
    - "-hwaccel"
    - vaapi
    - "-hwaccel_device"
    - /dev/dri/renderD128
    - "-hwaccel_output_format"
    - yuv420p

mqtt: 
  host: "192.168.1.124"
  password: mqtt-password
  topic_prefix: frigate
  user: homeassistant

objects: 
  track: 
    - person

clips: 
  max_seconds: 300
  retain:
    default: 30

logger:
  default: info 
  logs:
    frigate.mqtt: error
```

**Logs**
```
2021-02-06T16:47:46.123196172-06:00 [h264 @ 0x55f10e69ad00] error while decoding MB 9 22, bytestream -7
2021-02-06T16:50:33.738140484-06:00 frigate.object_processing      WARNING : Unable to create jpg because frame 1612651831.114191 is not in the cache
2021-02-06T16:50:33.738700094-06:00 frigate.object_processing      WARNING : Unable to create jpg because frame 1612651831.114191 is not in the cache
2021-02-06T16:50:33.756896300-06:00 Exception in thread detected_frames_processor:
2021-02-06T16:50:33.756935869-06:00 Traceback (most recent call last):
2021-02-06T16:50:33.756988878-06:00   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-02-06T16:50:33.759500490-06:00     self.run()
2021-02-06T16:50:33.759529123-06:00   File "/opt/frigate/frigate/object_processing.py", line 529, in run
2021-02-06T16:50:33.760811407-06:00     camera_state.update(frame_time, current_tracked_objects, motion_boxes, regions)
2021-02-06T16:50:33.760839298-06:00   File "/opt/frigate/frigate/object_processing.py", line 367, in update
2021-02-06T16:50:33.762106158-06:00     c(self.name, removed_obj, frame_time)
2021-02-06T16:50:33.762130292-06:00   File "/opt/frigate/frigate/object_processing.py", line 465, in end
2021-02-06T16:50:33.762355787-06:00     j.write(jpg_bytes)
2021-02-06T16:50:33.762396006-06:00 TypeError: a bytes-like object is required, not 'NoneType'
```

**Frigate debug stats**
![Screenshot from 2021-02-08 10-21-22](https://user-images.githubusercontent.com/864569/107247983-796da700-69f7-11eb-9906-fde7ee8ff2b9.png)

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[rtsp @ 0x55c17bb42080] max delay reached. need to consume packet
[rtsp @ 0x55c17bb42080] RTP: missed 3 packets
[h264 @ 0x55c17bb45d80] error while decoding MB 26 103, bytestream -5
[h264 @ 0x55c17bb45d80] concealing 3101 DC, 3101 AC, 3101 MV errors in P frame
Input #0, rtsp, from 'rtsp://view:viewDub11@192.168.1.73:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.040000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2592x1944, 20 fps, 20 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

```

**Computer Hardware**
 - OS: Ubuntu 18.03
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Amcrest
 - Model: IP5M-B1186EW-28MM
 - Resolution: 2592x1944
 - FPS: 20
