### ISSUE TITLE
[Support]: Recording starts to late.

### ISSUE THREAD

**Issue by therealeldaria** [blakeblackshear/frigate#7409]
### Describe the problem you are having

I noticed that the clips start about 10-30 seconds after the detection event.
So in the snapshot one can see the subject, but in the video the event already passed.

When trying to troubleshoot I found that:
- The OSD timestamp added by frigate to the snapshot is about 10-30 seconds after the OSD time of the camera.
![image](https://github.com/blakeblackshear/frigate/assets/10135582/f484aa48-82de-47a4-b27d-7a51e3797d0d)

- The OSD Time of the camera when the clip starts, are a few seconds after the OSD time of Frigate on the snapshot. 
![image](https://github.com/blakeblackshear/frigate/assets/10135582/e7cbda9e-539f-4ea6-b027-7638211a8e60)

- The cameras are synced using NTP, I also verified with ssh that they have the same time as HassOS.

- The detection sub stream and the main recording stream are almost synced, only off about 3s.
![image](https://github.com/blakeblackshear/frigate/assets/10135582/00f148f9-2aea-43f0-b5e4-005d9eeb53b0)

- I saw in some other thread that i-frames could be a reason so I configured the camera to have iframe 1x the FPS, this should be an iframe every second.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
    host: <redacted>
    topic_prefix: frigate
    client_id: frigate
    user: frigate
    password: <redacted>
    stats_interval: 60

detectors:
    coral:
        type: edgetpu
        device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    frontporch:
      - rtsp://<redacted>:<redacted>@192.168.9.42:554//h264Preview_01_main
    frontporch_sub:
      - rtsp://<redacted>:<redacted>@192.168.9.42:554//h264Preview_01_sub

cameras:
    FrontPorch:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/frontporch_sub
                  input_args: preset-rtsp-restream
                  roles:
                      - detect
                - path: rtsp://127.0.0.1:8554/frontporch
                  roles:
                      - record
            output_args:
              record: preset-record-generic-audio-aac
        detect:
            width: 640
            height: 480
            fps: 4
        motion:
          mask:
            - 0,383,64,321,174,201,222,149,374,27,523,76,484,103,599,138,640,0,0,0

objects:
    track:
        - person
        - cat
        - dog

record:
    enabled: True
    events:
        retain:
            default: 14
            mode: active_objects

snapshots:
    enabled: True
    timestamp: True
    retain:
        default: 30
```

### Relevant log output

```shell
No logs for this.
```

### FFprobe output from your camera

```shell
[
  {
    "return_code": 0,
    "stderr": "",
    "stdout": {
      "programs": [],
      "streams": [
        {
          "avg_frame_rate": "4/1",
          "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
          "height": 480,
          "width": 640
        },
        {
          "avg_frame_rate": "0/0",
          "codec_long_name": "AAC(AdvancedAudioCoding)"
        }
      ]
    }
  },
  {
    "return_code": 0,
    "stderr": "",
    "stdout": {
      "programs": [],
      "streams": [
        {
          "avg_frame_rate": "20/1",
          "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
          "height": 1920,
          "width": 2560
        },
        {
          "avg_frame_rate": "0/0",
          "codec_long_name": "AAC(AdvancedAudioCoding)"
        }
      ]
    }
  }
]
```

### Frigate stats

```json
{
  "FrontPorch": {
    "camera_fps": 4,
    "capture_pid": 244,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 258,
    "pid": 238,
    "process_fps": 4,
    "skipped_fps": 0
  },
  "cpu_usages": {
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "0.2"
    },
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "100": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "111": {
      "cpu": "3.0",
      "mem": "7.1"
    },
    "122": {
      "cpu": "0.0",
      "mem": "0.3"
    },
    "132": {
      "cpu": "0.0",
      "mem": "0.6"
    },
    "134": {
      "cpu": "0.0",
      "mem": "0.7"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "16": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "219": {
      "cpu": "0.0",
      "mem": "2.0"
    },
    "225": {
      "cpu": "0.3",
      "mem": "0.3"
    },
    "226": {
      "cpu": "0.0",
      "mem": "2.7"
    },
    "228": {
      "cpu": "0.3",
      "mem": "2.3"
    },
    "233": {
      "cpu": "0.0",
      "mem": "1.1"
    },
    "235": {
      "cpu": "0.3",
      "mem": "2.4"
    },
    "236": {
      "cpu": "0.7",
      "mem": "2.3"
    },
    "237": {
      "cpu": "0.0",
      "mem": "0.4"
    },
    "238": {
      "cpu": "0.3",
      "mem": "2.4"
    },
    "239": {
      "cpu": "0.0",
      "mem": "1.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "240": {
      "cpu": "0.3",
      "mem": "2.1"
    },
    "241": {
      "cpu": "0.0",
      "mem": "0.4"
    },
    "242": {
      "cpu": "0.3",
      "mem": "2.1"
    },
    "244": {
      "cpu": "0.7",
      "mem": "2.1"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "256": {
      "cpu": "1.0",
      "mem": "1.3"
    },
    "257": {
      "cpu": "1.3",
      "mem": "1.3"
    },
    "258": {
      "cpu": "1.3",
      "mem": "1.4"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "264": {
      "cpu": "0.7",
      "mem": "0.6"
    },
    "266": {
      "cpu": "0.3",
      "mem": "0.6"
    },
    "267": {
      "cpu": "3.7",
      "mem": "0.7"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "32": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "40": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "42": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "77": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "7830": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "7857": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "7860": {
      "cpu": "0.3",
      "mem": "0.1"
    },
    "80": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "83": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "89": {
      "cpu": "11.3",
      "mem": "0.5"
    },
    "MiB": {
      "cpu": "1883.2",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "0"
    },
    "top": {
      "cpu": "users,",
      "mem": "load"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 9.33,
      "pid": 226
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "0.51 %",
      "mem": "- %"
    }
  },
  "service": {
    "last_updated": 1691400873,
    "latest_version": "0.12.1",
    "storage": {
      "/dev/shm": {
        "free": 2036.4,
        "mount_type": "tmpfs",
        "total": 2039.7,
        "used": 3.3
      },
      "/media/frigate/clips": {
        "free": 1052376,
        "mount_type": "nfs4",
        "total": 1099511.6,
        "used": 47135.6
      },
      "/media/frigate/recordings": {
        "free": 1052376,
        "mount_type": "nfs4",
        "total": 1099511.6,
        "used": 47135.6
      },
      "/tmp/cache": {
        "free": 2014.9,
        "mount_type": "tmpfs",
        "total": 2039.7,
        "used": 24.7
      }
    },
    "temperatures": {},
    "uptime": 5227,
    "version": "0.12.1-367d724"
  }
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Frigate: Wired
Camera: Wireless

### Camera make and model

Reolink E1 Outdoor

### Any other information that may be helpful

HassOS is running in a Proxmox VM.
It is currently the only VM running there.
System is a HP ProDesk 600 G4 DM i5t
USB PCI device and Host GPU is passed through to HassOS for Coral and Intel GPU.
