### ISSUE TITLE
[Detector Support]: High CPU Usage

### ISSUE THREAD

**Issue by NickBeswick** [blakeblackshear/frigate#7416]
### Describe the problem you are having

Coral running with high CPU

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.86.xx
  user: mqtt_user
  password: xx

detectors:
  coral:
    type: edgetpu
    device: usb
  
    
go2rtc:
  streams:
    Car_camera:
      - rtsp://xx:xx@192.168.86.xx:554/stream1
    Garden_Camera_1:
      - rtsp://xx:xx@192.168.86.xx:8554/Streaming/Channels/101
    Garden_Camera_2: 
      - rtsp://xx:xx@192.168.86.xx:8554/Streaming/Channels/101
   
cameras:
  
  Car_Camera: 
    ffmpeg:
      inputs:
         - path: rtsp://127.0.0.1:8554/Car_camera
           roles:
            - detect
    
    snapshots: # <----- Enable snapshots
      enabled: True

      
    detect:
      width: 1920
      height: 1080 
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle

        
    record:
      enabled: True
      events:
        retain:
         default: 5


##################################################
        
  Garden_Camera_1: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden_Camera_1
          roles:
            - detect

    snapshots: # <----- Enable snapshots
      enabled: True
            
    detect:
      width: 2304
      height: 1296 
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle
        
    record:
      enabled: True
      events:
        retain:
         default: 5    
      
##################################################      
      
  Garden_Camera_2: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden_Camera_2
          roles:
            - detect

    snapshots: # <----- Enable snapshots
      enabled: True
      
    detect:
      width: 2304
      height: 1296 
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle
        
    record:
      enabled: True
      events:
        retain:
         default: 5
```

### docker-compose file or Docker CLI command

```yaml
As per installation instructions
```

### Relevant log output

```shell
/
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Need advise on setup to reduce Coral CPU load
