### ISSUE TITLE
[Support]: frigate and stream service

### ISSUE THREAD

**Issue by stevetheman1031** [blakeblackshear/frigate#7418]
### Describe the problem you are having

Hello I'm getting an error when using the default integration stream: camera.play_stream. I'm getting the error `failed to call service camera.play_stream camera.livingroomcam does not support play stream service`

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 10.10.0.3
  user: frigate
  password: frigate

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu


cameras:
  LivingroomCam: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://10.10.0.3:8554/Living_room_cam # rtsp://10.10.0.36/h264
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:a aac -codec:v copy
    record: # <----- Enable recording
      enabled: True
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 15
    motion:
      mask:
        - 1280,51,0,34,0,0,1280,0


  DoorCam: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://admin:adminEAOTSD@10.10.0.109:554/h264/ch01/main/av_stream
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:a aac -codec:v copy
    record: # <----- Enable recording
      enabled: True
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 29.970030
    motion:
      mask:
        - 0,0,1280,0,1252,269,0,279
        - 1280,720,1280,0,939,0,970,720
        - 40,720,0,0,374,0,370,720
    objects:
      track:
        - person
```

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:268
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:05:29 AM (11 occurrences)
Last logged: 1:54:01 AM

[140662417425216] Error handling message: camera.doorcam does not support play stream service (unknown_error) DawsonTab from 10.10.0.20 (Mozilla/5.0 (Linux; Android 11; SM-T738U Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Safari/537.36 Home Assistant/2023.7.5-10506 (Android 11; SM-T738U))[140661845607232] Error handling message: camera.doorcam does not support play stream service (unknown_error) Dawson from 10.10.0.101 (Mozilla/5.0 (Linux; Android 13; SM-S918U Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.138 Mobile Safari/537.36 Home Assistant/2023.7.5-10506 (Android 13; SM-S918U))[140661900782912] Error handling message: camera.livingroomcam does not support play stream service (unknown_error) DawsonTab from 10.10.0.20 (Mozilla/5.0 (Linux; Android 11; SM-T738U Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Safari/537.36 Home Assistant/2023.7.5-10506 (Android 11; SM-T738U))[140661770759360] Error handling message: camera.livingroomcam does not support play stream service (unknown_error) DawsonTab from 10.10.0.20 (Mozilla/5.0 (Linux; Android 11; SM-T738U Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Safari/537.36 Home Assistant/2023.7.5-10506 (Android 11; SM-T738U))
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

Service used
```shell
service: camera.play_stream
data: 
  format: hls 
  media_player: media_player.living_room_display 
target: 
  entity_id: camera.livingroomcam
```
Stream from go2rtc
```shell
streams:
    Living_room_cam:
      - rtsp://10.10.0.36/h264
```
Adding the camera directly using the go2rtc address and a still frame url does get me a valid cast but is supper laggy
