### ISSUE TITLE
[Detector Support]: Spider as person detected

### ISSUE THREAD

**Issue by StefanW86** [blakeblackshear/frigate#7435]
### Describe the problem you are having

I have reolink cameras running with frigate. At the moment frigatew detects a spider as person. But only at night with infrarot light is on.
The issue occurs at camera "seite"
I uploaded a pictutre for the wrong detection.
https://ibb.co/42kpBMV

### Version

 0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.221
  user: mqtt
  password: mqttt

record:
  enabled: True
  events:
    retain:
      default: 5
    objects:
      - car
      - person

snapshots:
  enabled: True

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
    - car
    - dog
    - bicycle

go2rtc:
  streams:
    vorne:
      - http://192.168.178.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=nvr&password=a2H!sz296MG3
      - "ffmpeg:front#audio=opus"
    seite:
      - http://192.168.178.48/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=nvr&password=a2H!sz296MG3
      - "ffmpeg:front#audio=opus"
    hinten:
      - http://192.168.178.49/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=nvr&password=a2H!sz296MG3
      - "ffmpeg:front#audio=opus"
  webrtc:
    candidates:
      - 192.168.178.222:8555
      - stun:8555

cameras:
  vorne:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/vorne?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
        - 108,720,633,502,986,313,1045,287,1171,212,1280,307,1280,0,0,0,0,720
  seite:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/seite?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
        - 0,720,0,0,575,0,890,0,843,337,580,329,263,720
    objects:
      track:
        - person
        - bicycle

  hinten:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/hinten?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
      - 434,0,1280,0,1280,333,1093,197,441,213
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
