### ISSUE TITLE
[Support]: Detector event does not have the right timestamp

### ISSUE THREAD

**Issue by frjol** [blakeblackshear/frigate#7448]
### Describe the problem you are having

First of all, thank you a great product you provide and the support it comes with it. 

I have a specific event that does not correspond to the right timestamp on my Front camera. 
It usually work pretty well, but I noticed Yesterday that my back to work detection was placed like 2 hours prior to my actual arrival. 
The people detection was about 2h earlier but the car detection was OK at the right time.

I have nothing relevant in the logs.

My event People detection is at 6:24:29 PM (1h42m 16s)
![image](https://github.com/blakeblackshear/frigate/assets/4422813/eec0c1df-78d0-408a-bd47-f0e57567d45c)
My actual arrival is at 8:04:17 (car detection)

My guess is that the detection lasted for 1h42m16s because of the rain and the light reflection motion.
I sometime see _detection in progress_ longer that the actual event.

I downloaded the file and the ffprobe did not output anything special other that the duration is 14m55s. 
It's about 14min of constant motion (cars passing) then my arrival. 
You can clearly see that the first 12 min are from the beginning but the last 3min are closer to the arrival time (it becomes dark all of the sudden).

The detection seems off since the beginning and the end is somehow stitched. 
The file looks like this to me.
[6:24:29pm + 12min | --time gap-- | (8:04:17 car detection + 17s, outside this recording) Last detection part where I'm in it ]

Maybe I can tweak my configuration to avoid _in progress_ detection when having a lot of motion. Not quite sure how to do that in that scenario. It's worth to mentioned that I have a motion mask that covers the top road where the cars are passing. They're still detected for some reason. 

Feel free to ask me more details if needed.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: <snip>
  port: <snip>
  user: <snip>
  password: <snip>
  client_id: frigate
go2rtc: # restream config
  username: <snip>
  password: <snip>
  streams:
    back_cam:
      - rtsp://<snip>
    front_cam:
      - rtsp://<snip>
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_cam
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - 0,517,679,440,1422,354,1416,322,1450,246,1597,180,1584,0,0,0
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
  back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_cam
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - 1745,40,1920,39,1920,0,1742,0
        - 1920,131,1688,97,1478,144,976,366,1100,1080,1920,1080
        - 0,0,74,0,74,71,0,74
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
record:
  enabled: True
  retain:
    days: 15
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
birdseye:
  enabled: False
  mode: continuous
# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - cat
    - dog
    - bird
timestamp_style:
  position: "tl"
  format: "%Y/%m/%d %H:%M:%S"
```

### Relevant log output

```shell
2023-08-10 07:31:44.920713449  [INFO] Starting Frigate...
2023-08-10 07:31:46.002550551  [2023-08-10 07:31:46] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-10 07:31:46.023030684  [2023-08-10 07:31:46] peewee_migrate                 INFO    : Starting migrations
2023-08-10 07:31:46.027250298  [2023-08-10 07:31:46] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-10 07:31:46.040386642  [2023-08-10 07:31:46] detector.cpu                   INFO    : Starting detection process: 289
2023-08-10 07:31:46.045094239  [2023-08-10 07:31:46] frigate.app                    INFO    : Output process started: 291
2023-08-10 07:31:46.045405672  [2023-08-10 07:31:46] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-08-10 07:31:46.045904375  [2023-08-10 07:31:46] frigate.app                    INFO    : Camera processor started for front: 293
2023-08-10 07:31:46.049878960  [2023-08-10 07:31:46] frigate.app                    INFO    : Camera processor started for back: 294
2023-08-10 07:31:46.054228106  [2023-08-10 07:31:46] frigate.app                    INFO    : Capture process started for front: 295
2023-08-10 07:31:46.058925654  [2023-08-10 07:31:46] frigate.app                    INFO    : Capture process started for back: 297
```

### FFprobe output from your camera

```shell
ffprobe version n6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.1.1 (GCC) 20230429
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[rtsp @ 0x564a617ed800] max delay reached. need to consume packet
[rtsp @ 0x564a617ed800] RTP: missed 1 packets
[h264 @ 0x564a617f72c0] error while decoding MB 108 63, bytestream -11
[h264 @ 0x564a617f72c0] concealing 541 DC, 541 AC, 541 MV errors in P frame
[rtsp @ 0x564a617ed800] max delay reached. need to consume packet
[rtsp @ 0x564a617ed800] RTP: missed 1 packets
[h264 @ 0x564a617f72c0] error while decoding MB 20 49, bytestream -5
[h264 @ 0x564a617f72c0] concealing 2309 DC, 2309 AC, 2309 MV errors in P frame
[rtsp @ 0x564a617ed800] max delay reached. need to consume packet
[rtsp @ 0x564a617ed800] RTP: missed 1 packets
[h264 @ 0x564a617f72c0] error while decoding MB 87 54, bytestream -5
[h264 @ 0x564a617f72c0] concealing 1642 DC, 1642 AC, 1642 MV errors in P frame
[rtsp @ 0x564a617ed800] max delay reached. need to consume packet
[rtsp @ 0x564a617ed800] RTP: missed 1 packets
Input #0, rtsp, from '<snip>':
  Metadata:
    title           : Stream
  Duration: N/A, start: -0.996778, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
```

### Frigate stats

```json
{
    "back":
    {
        "camera_fps": 5.4,
        "capture_pid": 297,
        "detection_enabled": 1,
        "detection_fps": 3.7,
        "ffmpeg_pid": 310,
        "pid": 294,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "cpu_usages":
    {
        "%Cpu(s):":
        {
            "cpu": "id,",
            "mem": "0.2"
        },
        "1":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "117":
        {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "134":
        {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "135":
        {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "136":
        {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "137":
        {
            "cpu": "0.0",
            "mem": "0.3"
        },
        "15":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "16":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "282":
        {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "288":
        {
            "cpu": "0.3",
            "mem": "0.1"
        },
        "289":
        {
            "cpu": "91.7",
            "mem": "0.7"
        },
        "29":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "291":
        {
            "cpu": "0.3",
            "mem": "0.6"
        },
        "293":
        {
            "cpu": "0.7",
            "mem": "0.9"
        },
        "294":
        {
            "cpu": "1.7",
            "mem": "0.9"
        },
        "295":
        {
            "cpu": "3.0",
            "mem": "0.6"
        },
        "297":
        {
            "cpu": "2.7",
            "mem": "0.6"
        },
        "30":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "301":
        {
            "cpu": "0.0",
            "mem": "0.4"
        },
        "302":
        {
            "cpu": "13.0",
            "mem": "0.5"
        },
        "303":
        {
            "cpu": "0.0",
            "mem": "0.4"
        },
        "31":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "310":
        {
            "cpu": "39.3",
            "mem": "0.6"
        },
        "32":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41746":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41761":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "88":
        {
            "cpu": "1.7",
            "mem": "0.2"
        },
        "96":
        {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "98":
        {
            "cpu": "0.7",
            "mem": "1.9"
        },
        "MiB":
        {
            "cpu": "9723.0",
            "mem": "avail"
        },
        "PID":
        {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:":
        {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top":
        {
            "cpu": "users,",
            "mem": "load"
        }
    },
    "detection_fps": 3.7,
    "detectors":
    {
        "cpu":
        {
            "detection_start": 0.0,
            "inference_speed": 119.7,
            "pid": 289
        }
    },
    "front":
    {
        "camera_fps": 5.0,
        "capture_pid": 295,
        "detection_enabled": 1,
        "detection_fps": 0.0,
        "ffmpeg_pid": 302,
        "pid": 293,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "service":
    {
        "last_updated": 1691768464,
        "latest_version": "0.12.1",
        "storage":
        {
            "/dev/shm":
            {
                "free": 126.7,
                "mount_type": "tmpfs",
                "total": 134.2,
                "used": 7.5
            },
            "/media/frigate/clips":
            {
                "free": 5097.3,
                "mount_type": "ext4",
                "total": 125424.4,
                "used": 113908.6
            },
            "/media/frigate/recordings":
            {
                "free": 5097.3,
                "mount_type": "ext4",
                "total": 125424.4,
                "used": 113908.6
            },
            "/tmp/cache":
            {
                "free": 1995.8,
                "mount_type": "tmpfs",
                "total": 2000.0,
                "used": 4.2
            }
        },
        "temperatures": {},
        "uptime": 101358,
        "version": "0.12.1-367d724"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

RaspberryPi camera with MediaMTX RTSP server

### Any other information that may be helpful

I'm running the image in Docker compose on a Manjaro installation.
Wired connection for the Frigate server. Wifi between the camera and router (very close)

The camera is a Raspberry Pi Zero 2 W with Camera module V2 running MediaMTX rtsp server https://github.com/bluenviron/mediamtx

**Comment by frjol** [comment]
Thanks for your quick reply. It's very much appreciated.

>This is going to be due to a false positive. For now you need to catch it in progress and look using the debug live view to see what is being detected as a person (but isn't)

I'll check that when it happens. I'll take a look again at the false positive page for the moment.

> this is actively discouraged in the docs, motion masks are not meant to be used on areas where objects actually occur and will not stop objects from being detected

I miss understood the phrasing of that. It seemed to be the way to go.

>First, Frigate uses motion detection as a first line check to see if there is anything happening in the frame worth checking with object detection.
Once motion is detected, it tries to group up nearby areas of motion together in hopes of identifying a rectangle in the image that will capture the area worth inspecting. These are the red "motion boxes" you see in the debug viewer.

I don't see any example for the Object Filter Masks here https://docs.frigate.video/configuration/masks

I figured I could add this to block the detection on the street. Which will overlap on the motion detection mask.

```
objects:
  filters:
    car:
      mask:
        - 0,517,679,440,1422,354,1416,322,1450,246,1597,180,1584,0,0,0
    person:
      mask:
        - 0,517,679,440,1422,354,1416,322,1450,246,1597,180,1584,0,0,0
```

I guess that would help long detection but not in the area where I want them when it's raining with light.
It's a first step for the moment and should reduce the noise of detection. 

Let me know if you have something about the sticking recording for the detection over the long period. I would be glad to help if possible.
