### ISSUE TITLE
Birdseye not utilizing the whole screen with 6 cameras

### ISSUE THREAD

**Issue by hcjohhny** [blakeblackshear/frigate#7460]
### Describe the problem you are having

Birdseye not utilizing the whole screen with 6 cameras. No matter what resolution i give it in the frigate config, it's the same. Is there a way to utilize the whole screen.

Cheers.

### Version

SYSTEM 0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 
  user: MQTT
  password: 

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi 


birdseye:
  enabled: True
  mode: continuous
  width: 1920
  height: 1080
  quality: 3

objects:
  track:
    - person
    - cat
    
record:
  enabled: True
  events:
    retain:
      default: 10
      mode: active_objects
      objects:
        person: 5
        cat: 2
rtmp:
      enabled: False 

go2rtc:
  streams:
    PTZ:
      - rtsp://admin:UPQVQE@192.168.1.:554/streaming/channels/102
    Rear_Garage:
      - rtsp://admin:PCWQXP@192.168.1.:554/streaming/channels/102
    Bed_Side_Rear:
      - rtsp://admin:MGBZQP@192.168.1.:554/streaming/channels/102
    Backyard:
      - rtsp://admin:IIPMUI@192.168.1.:554/streaming/channels/102
    Front_Garage:
      - rtsp://admin:QIMPHD@192.168.1.:554/streaming/channels/102
    Bed_Window:
      - rtsp://admin:XTOYZW@192.168.1.:554/streaming/channels/102

  webrtc:
    candidates:
      - 192.168.1.48:8555
      - stun:8555


cameras:
  
  PTZ:
    ffmpeg: 
      inputs:
        - path: rtsp://admin:UPQVQE@192.168.1.:554/h.264
          roles:
            - record

    motion:
      mask:
        - 452,720,432,658,85,649,32,720
        - 201,720,1196,720,1089,628,669,662,391,448,212,447
        - 0,377,1280,358,1280,0,0,0        
    
  Rear_Garage:
    ffmpeg: 
      inputs:
        - path: rtsp://admin:PCWQXP@192.168.1.:554/h.264
          roles:
            - record


  Bed_Side_Rear:
    ffmpeg: 
      inputs:
        - path: rtsp://admin:MGBZQP@192.168.1.:554/h.264
          roles:
            - record
  

  Backyard:
    ffmpeg: 
      inputs:
        - path: rtsp://admin:IIPMUI@192.168.1.:554/h.264
          roles:
            - record




  Front_Garage:
    ffmpeg: 
      inputs:
        - path: rtsp://admin:QIMPHD@192.168.1.:554/h.264
          roles:
            - record

    motion:
      mask:
         - 39,644,500,635,498,720,41,720
         - 192,720,404,149,578,144,653,694
         - 0,164,1280,139,1280,0,0,0        


  Bed_Window:
    ffmpeg: 
      inputs:
        - path: rtsp://admin:XTOYZW@192.168.1.:554/h.264
          roles:
            - record

    motion:
      mask:
        - 464,720,450,630,43,635,21,720
        - 1280,720,1280,539,1201,498,884,720
        - 142,303,553,254,993,322,998,187,1280,260,1280,0,936,0,639,0,110,52
```

### Relevant log output

```shell
Not sure
```

### Frigate stats

```json
Not sure
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

4 cameras take up the whole screen
  
![PXL_20230811_232716841](https://github.com/blakeblackshear/frigate/assets/122139521/2c0c4e2f-e52d-4140-8984-25dc604bdb87)

6 cameras don't use whole screen
![pxl 2](https://github.com/blakeblackshear/frigate/assets/122139521/c586bb77-8604-4deb-ba5c-0f445b832c32)
