### ISSUE TITLE
[Config Support]: Stream of camera with added sound, stores video with no sound

### ISSUE THREAD

**Issue by brujoand** [blakeblackshear/frigate#7464]
### Describe the problem you are having

I've got a bunch of different cameras, 2 of them have no sound (bassenget, hagen) , the rest have sound.

So when setting up the go2rtc streams I made sure to copy the sound streams from nearby cameras into these two soundless cameras. This works great for watching the streams, but recorded events have no sound for these two specific cameras. 

Shouldn't the recording be simple dumps from the go2rtc stream? 

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
              coral:
                type: edgetpu
                device: pci
            mqtt:
              host: emqx.data.svc.cluster.local
              topic_prefix: frigate
              user: mqtt
              password: "{FRIGATE_MQTT_PASSWORD}"
            database:
              path: /data/frigate.db
            birdseye:
              enabled: True
              restream: True
              mode: objects
            go2rtc:
              streams:
                bassenget:
                  - "{FRIGATE_BASSENGET}"
                  - "ffmpeg:inngang#audio=opus"
                hagen:
                  - "{FRIGATE_HAGEN}"
                  - "ffmpeg:baksiden#audio=opus"
                homelab:
                  - "{FRIGATE_HOMELAB}"
                  - "ffmpeg:homelab#audio=opus"
                stua:
                  - "{FRIGATE_STUA}"
                  - "ffmpeg:stua#audio=opus"
                veien:
                  - "{FRIGATE_VEIEN}"
                  - "ffmpeg:veien#audio=opus"
                inngang:
                  - "{FRIGATE_INNGANG}"
                  - "ffmpeg:inngang#audio=opus"
                baksiden:
                  - "{FRIGATE_BAKSIDEN}"
                  - "ffmpeg:baksiden#audio=opus"
              webrtc:
                candidates:
                  - 10.30.0.5:8555
                  - stun:8555
            objects:
              track:
                - bil
                - person
                - skapning
                - katt
              filters:
                person:
                  threshold: 0.75
                skapning:
                  threshold: 0.75
            detect:
              height: 720
              width: 1280
              fps: 5
              max_disappeared: 25
            snapshots:
              enabled: true
              timestamp: true
              retain:
                default: 14
            record:
              enabled: true
              retain:
                days: 1
                mode: all
              events:
                pre_capture: 3
                post_capture: 3
                retain:
                  mode: active_objects
                  default: 7
            model:
              labelmap:
                2: bil
                5: bil
                7: bil
                15: skapning
                16: katt
                17: skapning
                18: skapning
                19: skapning
                20: skapning
                22: skapning
            rtmp:
              enabled: False
            ffmpeg:
              input_args: -rtsp_transport tcp -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -timeout 5000000 -strict experimental
              output_args:
                record: preset-record-generic-audio-copy
              hwaccel_args: preset-vaapi
            cameras:
              bassenget:
                ffmpeg:
                  inputs:
                    - path: rtsp://127.0.0.1:8554/bassenget
                      roles:
                        - detect
                        - record
                motion:
                  mask:
                    - 591,274,1082,350,1148,443,1100,720,1280,720,1280,0,416,0,416,162,581,188
              hagen:
                ffmpeg:
                  inputs:
                    - path: rtsp://127.0.0.1:8554/hagen
                      roles:
                        - detect
                        - record
                motion:
                  mask:
                    - 125,220,361,245,373,0,0,0
                    - 1085,0,1080,331,863,323,870,0
                    - 1280,517,1152,429,1280,433,1280,101,1150,107
              homelab:
                ffmpeg:
                  inputs:
                    - path: rtsp://127.0.0.1:8554/homelab
                      roles:
                        - detect
                        - record
              stua:
                ffmpeg:
                  inputs:
                    - path: rtsp://127.0.0.1:8554/stua
                      roles:
                        - record
                        - detect
              veien:
                ffmpeg:
                  inputs:
                    - path: rtsp://127.0.0.1:8554/veien
                      roles:
                        - detect
                        - record
                objects:
                  filters:
                    bil:
                      mask:
                        - 1920,1080,0,1080,0,696,1471,137,1526,0,1920,0
                zones:
                  veien_inn:
                    coordinates: 771,393,746,0,340,0,271,170,362,566
                    objects:
                      - bil
                      - person
                  veien_ut:
                    coordinates: 1447,155,1450,0,762,0,777,372
                    objects:
                      - bil
                      - person
                  trampoline:
                    coordinates: 183,1080,840,1080,1097,541,694,471,50,752
                motion:
                  mask:
                    - 393,628,348,426,1270,135,1534,0,0,0,0,1080
                    - 1920,1080,1920,0,1757,0,1530,378,1618,1080
                detect:
                  height: 1080
                  width: 1920
                  fps: 5
                  max_disappeared: 25
              inngang:
                ffmpeg:
                  inputs:
                    - path: rtsp://127.0.0.1:8554/inngang
                      roles:
                        - detect
                        - record
                motion:
                  mask:
                    - 1138,348,1137,0,595,0,530,222
                    - 0,720,292,620,185,353,0,332
                    - 610,89,609,0,0,0,0,325
                zones:
                  parkering:
                    coordinates: 0,720,420,720,818,282,811,0,0,0
                    objects:
                      - bil
                      - person
              baksiden:
                ffmpeg:
                  inputs:
                    - path: rtsp://127.0.0.1:8554/baksiden
                      roles:
                        - detect
                        - record
```

### Relevant log output

```shell
2023-08-13 09:34:17.704011717  [INFO] Starting Frigate...
2023-08-13 09:34:18.615185257  [2023-08-13 09:34:18] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-13 09:34:18.643436974  [2023-08-13 09:34:18] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-08-13 09:34:18.644490790  [2023-08-13 09:34:18] peewee_migrate                 INFO    : Starting migrations
2023-08-13 09:34:18.650252698  [2023-08-13 09:34:18] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-13 09:34:18.659838341  [2023-08-13 09:34:18] detector.coral                 INFO    : Starting detection process: 579
2023-08-13 09:34:18.670947038  [2023-08-13 09:34:18] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-08-13 09:34:18.676550662  [2023-08-13 09:34:18] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-08-13 09:34:18.678575241  [2023-08-13 09:34:18] frigate.app                    INFO    : Output process started: 581
2023-08-13 09:34:18.678657984  [2023-08-13 09:34:18] frigate.app                    INFO    : Camera processor started for bassenget: 587
2023-08-13 09:34:18.678696194  [2023-08-13 09:34:18] frigate.app                    INFO    : Camera processor started for hagen: 599
2023-08-13 09:34:18.678721180  [2023-08-13 09:34:18] frigate.app                    INFO    : Camera processor started for homelab: 601
2023-08-13 09:34:18.678741523  [2023-08-13 09:34:18] frigate.app                    INFO    : Camera processor started for stua: 602
2023-08-13 09:34:18.678759983  [2023-08-13 09:34:18] frigate.app                    INFO    : Camera processor started for veien: 604
2023-08-13 09:34:18.678776874  [2023-08-13 09:34:18] frigate.app                    INFO    : Camera processor started for inngang: 606
2023-08-13 09:34:18.681339861  [2023-08-13 09:34:18] frigate.app                    INFO    : Camera processor started for baksiden: 607
2023-08-13 09:34:18.684362234  [2023-08-13 09:34:18] frigate.app                    INFO    : Capture process started for bassenget: 609
2023-08-13 09:34:18.687405688  [2023-08-13 09:34:18] frigate.app                    INFO    : Capture process started for hagen: 613
2023-08-13 09:34:18.690876241  [2023-08-13 09:34:18] frigate.app                    INFO    : Capture process started for homelab: 617
2023-08-13 09:34:18.694692539  [2023-08-13 09:34:18] frigate.app                    INFO    : Capture process started for stua: 623
2023-08-13 09:34:18.698851076  [2023-08-13 09:34:18] frigate.app                    INFO    : Capture process started for veien: 629
2023-08-13 09:34:18.704241596  [2023-08-13 09:34:18] frigate.app                    INFO    : Capture process started for inngang: 644
2023-08-13 09:34:18.708328277  [2023-08-13 09:34:18] frigate.app                    INFO    : Capture process started for baksiden: 651
```

### Frigate stats

```json
{"baksiden":{"camera_fps":5.1,"capture_pid":651,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":657,"pid":607,"process_fps":5.1,"skipped_fps":0.0},"bassenget":{"camera_fps":5.1,"capture_pid":609,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":614,"pid":587,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"1154":{"cpu":"0.0","mem":"0.0"},"1252":{"cpu":"0.0","mem":"0.0"},"1262":{"cpu":"0.3","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"147":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"174":{"cpu":"0.0","mem":"0.0"},"207":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"250":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"286":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"330":{"cpu":"0.0","mem":"0.0"},"358":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"572":{"cpu":"0.0","mem":"0.2"},"578":{"cpu":"1.0","mem":"0.0"},"579":{"cpu":"2.7","mem":"0.3"},"581":{"cpu":"5.3","mem":"0.3"},"587":{"cpu":"0.3","mem":"0.3"},"588":{"cpu":"0.0","mem":"0.1"},"599":{"cpu":"0.7","mem":"0.3"},"600":{"cpu":"0.0","mem":"0.1"},"601":{"cpu":"1.0","mem":"0.3"},"602":{"cpu":"37.2","mem":"0.3"},"603":{"cpu":"0.0","mem":"0.1"},"604":{"cpu":"1.0","mem":"0.3"},"605":{"cpu":"0.0","mem":"0.1"},"606":{"cpu":"1.0","mem":"0.3"},"607":{"cpu":"1.0","mem":"0.3"},"608":{"cpu":"0.0","mem":"0.1"},"609":{"cpu":"2.0","mem":"0.3"},"612":{"cpu":"0.0","mem":"0.1"},"613":{"cpu":"2.7","mem":"0.3"},"614":{"cpu":"6.6","mem":"0.3"},"617":{"cpu":"2.7","mem":"0.3"},"618":{"cpu":"0.0","mem":"0.1"},"620":{"cpu":"7.3","mem":"0.3"},"623":{"cpu":"2.3","mem":"0.3"},"624":{"cpu":"12.0","mem":"0.2"},"625":{"cpu":"5.6","mem":"0.2"},"629":{"cpu":"4.0","mem":"0.3"},"641":{"cpu":"8.3","mem":"0.2"},"644":{"cpu":"2.7","mem":"0.3"},"645":{"cpu":"10.3","mem":"0.2"},"651":{"cpu":"3.0","mem":"0.3"},"654":{"cpu":"9.3","mem":"0.2"},"657":{"cpu":"9.3","mem":"0.2"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"32.2","mem":"0.1"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"21.3","mem":"0.7"},"MiB":{"cpu":"26410.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":1.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.74,"pid":579}},"gpu_usages":{"intel-vaapi":{"gpu":"22.12 %","mem":"- %"}},"hagen":{"camera_fps":5.1,"capture_pid":613,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":620,"pid":599,"process_fps":5.1,"skipped_fps":0.0},"homelab":{"camera_fps":5.1,"capture_pid":617,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":625,"pid":601,"process_fps":5.1,"skipped_fps":0.0},"inngang":{"camera_fps":5.1,"capture_pid":644,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":654,"pid":606,"process_fps":5.1,"skipped_fps":0.0},"service":{"last_updated":1691919353,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":1056.2,"mount_type":"tmpfs","total":1073.7,"used":17.5},"/media/frigate/clips":{"free":13958814.0,"mount_type":"nfs4","total":23662049.6,"used":9703235.6},"/media/frigate/recordings":{"free":13958814.0,"mount_type":"nfs4","total":23662049.6,"used":9703235.6},"/tmp/cache":{"free":106197.5,"mount_type":"overlay","total":233493.2,"used":115360.4}},"temperatures":{"apex_0":47.05},"uptime":95,"version":"0.12.1-367d724"},"stua":{"camera_fps":5.0,"capture_pid":623,"detection_enabled":1,"detection_fps":1.0,"ffmpeg_pid":641,"pid":602,"process_fps":5.0,"skipped_fps":0.0},"veien":{"camera_fps":5.0,"capture_pid":629,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":645,"pid":604,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

k8s, not docker compose.

**Comment by NickM-27** [comment]
You are giving the other cameras opus audio streams. By default frigate only asks go2rtc for AAC streams. 

You need to add `?video&audio` to the end of those 2 restream urls to request video and opus audio.

**Comment by brujoand** [comment]
Thanks, that does the trick 👍

**Comment by brujoand** [comment]
One caveat though. I had to reconfigure the go2rtc streams that needed to borrow audio like so:
```
            go2rtc:
              streams:
                bassenget:
                  - "{FRIGATE_BASSENGET}"
                  - "ffmpeg:inngang#audio=opus#audio=aac"
                hagen:
                  - "{FRIGATE_HAGEN}"
                  - "ffmpeg:baksiden#audio=opus#audio=aac"
```
This adds both the opus and. aac audio to these stream. This way I get to use opus for webrtc and aac for stored events so they can be played back in the browser on macOS.
