### ISSUE TITLE
[Config Support]: Objects Tracked in Live View but Not Recorded in Events

### ISSUE THREAD

**Issue by 503Dev** [blakeblackshear/frigate#7465]
### Describe the problem you are having

When viewing the camera live view feed with debug enabled I can see that my two model classes are being detected in the stream and the objects are identified and the bounding box is drawn as expected however in the Events page, no recording or event is triggered for these objects.

I am using a custom tensorrt model and I made sure that the labelmap.txt is mapped, I am confident that is correct as the model works in the live view.  I made sure to add my custom classes to the object -> track in configuration.

### Version

0.12.1-367d724)

### Frigate config file

```yaml
mqtt:
  host: 192.168.68.190
  user: mqtt
  password: password

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /trt-models/racv3.trt
  labelmap_path: /trt-models/labelmap.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
#  labelmap:
#   1: mapa
#   2: person

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - mapa
    - person
#  filters:
#    person:
#      min_area: 1000
#      max_area: 100000
#      min_score: 0.3
#      threshold: 0.4
#    cat:
#      min_area: 0
#      min_score: 0.05
#      threshold: 1.5
#    dog:
#      min_area: 0
#      min_score: 0.05
#      threshold: 1.5


ffmpeg:
  hwaccel_args: preset-nvidia-h264
#  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt 
  output_args:
    record: preset-record-generic-audio-copy

birdseye:
  enabled: True
  mode: motion

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5

cameras:
  sala: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://zero:password@192.168.68.50:554/live/ch0 # <----- Update for your camera
          roles:
            - record
        - path: rtsp://zero:password@192.168.68.50:554/live/ch1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 768 # <---- update for your camera's resolution
      height: 432 # <---- update for your camera's resolution
      fps: 15
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 10
        mode: active_objects
    motion:
      mask:
        - 45,0,213,0,224,61,88,151
        - 768,0,747,120,277,41,261,0
#    zones:

#    zones:
#      couch_left:
#        coordinates: 181,210,172,77,351,0,675,0,733,95,268,334
#      couch_right:
#        coordinates: 417,720,851,720,1186,720,1280,537,1280,426,1161,305,852,657,650,483,394,667

  entrada: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://zero:password@192.168.68.51:554/live/ch0 # <----- Update for your camera
#          output_args: preset-record-generic-audio-copy
          roles:
            - record
        - path: rtsp://zero:password@192.168.68.51:554/live/ch1 # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 768 # <---- update for your camera's resolution
      height: 432 # <---- update for your camera's resolution
      fps: 15
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 10
        mode: active_objects
    motion:
      mask:
        - 768,0,522,0,523,22,768,23

  cocina: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://zero:password@192.168.68.52:554/live/ch0 # <----- Update for your camera
          roles:
            - record
        - path: rtsp://zero:password@192.168.68.52:554/live/ch1 # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 768 # <---- update for your camera's resolution
      height: 432 # <---- update for your camera's resolution
      fps: 15
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 10
        mode: active_objects
    motion:
      mask:
        - 525,23,526,0,768,0,768,25
```

### Relevant log output

```shell
N/A no errors, model loads ok
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

I can see the inference speed and resource usage marking as expected in the system page.
The model was trained exactly as the original tensorrt via the darknet Yolo models and converted to onnx -> tensorrt with the docker using the same code in tensorrt sh file.
