### ISSUE TITLE
[Config Support]: Setting `strftime_fmt` without `timezone` results in error in FireFox browser

### ISSUE THREAD

**Issue by ZionFox** [blakeblackshear/frigate#7472]
### Describe the problem you are having

In the config YML, trying to take advantage of using ISO 8601 date format `"%Y-%m-%d"` exposed the issue that using the `strftime_fmt` property of the global `UI` just returns "Invalid Time" for event timestamps.

The Events UI page shows "Invalid Time" no matter what is used in the format string. From the entire date-time formatted, to just time, or just the year as `"%Y"`. Setting it to empty string doesn't return "Invalid Time", but does present default which seems to be `"%Y/%m/%d, %H:%M:%S"`.

Interestingly though, the parent `timestamp_style`'s `format` property works as expected.

-------
### Expected results:
The time formatted accordingly, based on the hints and link provided in the main configuration file under documentation.

-------
### Actual results:
Event Timestamp returns "Invalid Time" for events no matter what the string is, unless it's empty, which it then returns to default.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

record:
  events:
    pre_capture: 10
    post_capture: 10
  retain:
    days: 10
    mode: motion

cameras:
  Fox-Garden:
    ffmpeg:
      inputs:
        - path: rtsp://ipcamera/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://ipcamera/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      events:
        retain:
          default: 14
          mode: active_objects
          objects:
            cat: 2
            bird: 2
    objects:
      track:
        - person
        - "sports ball"
        - cat
        - dog
        - bird
    zones:  
      garden_path:
        coordinates: 461,699,85,699,90,0,257,0,223,530,742,549,740,476,879,489,892,649
      lawn:
        coordinates: 272,0,535,0,826,132,872,487,745,482,755,560,211,536,236,193
      walls:
        coordinates: 1134,327,1166,588,886,646,866,403,827,132,537,0,1033,0
    motion:
      mask:
        - 1280,720,1249,720,1235,529,1167,212,1096,0,1280,0
    ui:
      order: 2

  Fox-Front:
    ffmpeg:
      inputs:
        - path: rtsp://ipcamera/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://ipcamera/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      events:
        retain:
          default: 14
          mode: active_objects
          objects:
            cat: 2
            dog: 2
            bird: 2
            car: 4
    objects:
      track:
        - person
        - car
        - bycicle
        - motorcycle
        - cat
        - dog
        - bird
    zones:
      home_path:
        coordinates: 521,720,290,565,114,720
      near_pavement:
        coordinates: 273,555,0,340,0,183,1280,669,1280,720,512,720
      road:
        coordinates: 125,36,0,60,0,171,342,316,1280,664,1280,166,1132,114,774,50,412,23
      far_pavement:
        coordinates: 939,57,764,34,577,21,379,21,253,22,140,28,0,53,33,33,189,0,920,0,1102,31,1280,88,1280,151,1102,92
    motion:
      mask:
        - 0,0
    ui:
      order: 0

ui:
  use_experimental: false
  date_style: short
  time_style: medium
  strftime_fmt: "%Y-%m-%d %H:%M:%S"

timestamp_style:
  position: tl
  format: "%Y-%m-%d %H:%M:%S"
  effect: shadow
```

### Relevant log output

```shell
No output related to this issue.
```

### Frigate stats

```json
{"Fox-Front":{"camera_fps":5.1,"capture_pid":299,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":312,"pid":295,"process_fps":5.1,"skipped_fps":0.0},"Fox-Garden":{"camera_fps":5.1,"capture_pid":296,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":303,"pid":293,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"0.0","mem":"0.4"},"110":{"cpu":"0.0","mem":"0.1"},"111":{"cpu":"4.3","mem":"4.5"},"117":{"cpu":"0.0","mem":"0.3"},"134":{"cpu":"0.0","mem":"0.2"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.2"},"1409":{"cpu":"0.0","mem":"0.0"},"1424":{"cpu":"0.3","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.3","mem":"2.1"},"287":{"cpu":"0.7","mem":"0.3"},"288":{"cpu":"0.0","mem":"2.6"},"289":{"cpu":"3.0","mem":"2.4"},"29":{"cpu":"0.0","mem":"0.0"},"293":{"cpu":"2.0","mem":"2.4"},"294":{"cpu":"0.0","mem":"1.0"},"295":{"cpu":"2.0","mem":"2.4"},"296":{"cpu":"7.3","mem":"2.2"},"297":{"cpu":"0.0","mem":"1.7"},"299":{"cpu":"7.6","mem":"2.2"},"30":{"cpu":"0.0","mem":"0.0"},"302":{"cpu":"0.0","mem":"1.0"},"303":{"cpu":"27.6","mem":"1.4"},"31":{"cpu":"0.0","mem":"0.0"},"312":{"cpu":"27.9","mem":"1.4"},"313":{"cpu":"5.0","mem":"1.2"},"316":{"cpu":"5.3","mem":"1.2"},"32":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"44":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"2650.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"1.74,"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":129.45,"pid":288}},"gpu_usages":{"rpi-v4l2m2m":{"gpu":-1,"mem":-1}},"service":{"last_updated":1692016962,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":63.0,"mount_type":"tmpfs","total":67.1,"used":4.1},"/media/frigate/clips":{"free":10518.8,"mount_type":"ext4","total":30460.2,"used":18680.4},"/media/frigate/recordings":{"free":10518.8,"mount_type":"ext4","total":30460.2,"used":18680.4},"/tmp/cache":{"free":994.7,"mount_type":"tmpfs","total":1000.0,"used":5.3}},"temperatures":{},"uptime":841,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Installed solo onto DietPi v8.20.1. Not integrated into any HA instance.
