### ISSUE TITLE
[Support]: Possible to notify when a camera is not online?

### ISSUE THREAD

**Issue by JohnNeville** [blakeblackshear/frigate#7473]
### Describe the problem you are having

I am not sure if this is possible but I didn't see anything in Home Assistant or within the Frigate documentation. 

Is it possible to identify when the camera feed is offline(pretty much any time the UI shows "No frames have been received, check error logs"). Ideally I would want to alert on this so I can diagnose the problem. 

Obviously I want to find out the root cause of my connection issues but I have a device that is unfortunately running somewhat of a flaky firmware and is also on wifi so sometimes it just glitches out even though it is pingable and technically responds. 

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 172.16.65.109
  topic_prefix: frigate
  client_id: frigate

detectors:
  coral_pci_1:
    type: edgetpu
    device: pci:0
  coral_pci_2:
    type: edgetpu
    device: pci:1

record:
  enabled: true

  retain:
    days: 2
    mode: all

  events:
    retain:
      default: 14
      mode: active_objects

      objects:
        person: 90

snapshots:
  enabled: True
  timestamp: true
  bounding_box: true
  retain: 
    default: 14

ffmpeg:

  output_args:
      record: preset-record-generic-audio-copy


ui:
  live_mode: webrtc


go2rtc:
  streams:
    ##############
    # Storage
    ##############
    # Main
    storage_camera_wide_main:
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.21:554/h264Preview_01_main
      - "ffmpeg:storage_camera_wide_main#video=h265#audio=opus"
    storage_camera_wide_sub: 
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.21:554/h264Preview_01_sub
      - "ffmpeg:storage_camera_wide_sub#video=h264#audio=opus#hardware"
    # Zoom
    storage_camera_zoom_main: 
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.21:554/h264Preview_02_main
      - "ffmpeg:storage_camera_zoom_main#video=h265#audio=opus"
    storage_camera_zoom_sub: 
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.21:554/h264Preview_02_sub
      - "ffmpeg:storage_camera_zoom_sub#video=h264#audio=opus#hardware"

    ##############
    ## Driveway
    ##############
    driveway_floodlight_camera:
      - rtsp://admin:{FRIGATE_DAHUA_PASSWORD}@172.16.30.23:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif
      #- onvif://admin:{FRIGATE_DAHUA_PASSWORD}@172.16.30.23?subtype=MediaProfile00000
    driveway_floodlight_camera_sub:
      - rtsp://admin:{FRIGATE_DAHUA_PASSWORD}@172.16.30.23:554/cam/realmonitor?channel=1&subtype=1&proto=Onvif
      #- onvif://admin:{FRIGATE_DAHUA_PASSWORD}@172.16.30.23?subtype=MediaProfile00001

    ##############
    # Bulding Front Door
    ##############
    building_front_door_camera:
      - tapo://admin:{FRIGATE_TAPO_M5HASH}@172.16.30.25


    ##############
    ## Front Stairs
    ##############
    front_stairs_camera_main:
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.22:554/h264Preview_01_main
      - "ffmpeg:storage_camera_wide_main#video=h265#audio=pcm#audio=volume"
    front_stairs_camera_sub:
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.22:554/h264Preview_01_sub
      - "ffmpeg:storage_camera_wide_sub#video=h264#audio=opus#hardware"

    ##############
    ## Back Stairs
    ##############
    back-stairs-camera:
      - tapo://admin:{FRIGATE_TAPO_M5HASH}@172.16.30.24

    
    ##############
    ## Roof
    ##############
    roof_camera_main:
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.26:554/h264Preview_01_main
      - "ffmpeg:roof_camera_main#video=h265#audio=opus"
    roof_camera_sub:
      - rtsp://frigate:{FRIGATE_REOLINK_PASSWORD}@172.16.30.26:554/h264Preview_01_sub
      - "ffmpeg:roof_camera_sub#video=h264#audio=opus#hardware"

  webrtc:
    candidates:
      - 172.16.65.109:8555
      - cctv.nevilles.info
  ffmpeg:
    hwaccel_args: preset-nvidia-h264
    volume: "-af \"volume=30dB\""


#####################################
# Cameras
#####################################
cameras:  
  driveway_floodlight_camera:
    ui:
      order: 6

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_floodlight_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_floodlight_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      

      hwaccel_args: preset-nvidia-h264
    zones:
      definitely_a_drunk_peeing:
        coordinates: 480,263,480,362,385,348,408,241

      near_car:
        coordinates: 480,263,480,704,0,704,217,223

      maybe_near_business:
        coordinates: 0,151,0,704,217,223

      street:
        coordinates: 0,151,405,248,480,0,0,0
    
    record:
      enabled: true

      retain:
        days: 30
        mode: all

      events:
        retain:
          default: 90
          mode: active_objects
          
          objects:
            person: 365

    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle

      filters:
        motorcycle:
          mask:
            - 363,150,396,0,0,0,0,105
        car:
          mask:
            - 363,150,396,0,0,0,0,105
        bicycle:
          mask:
            - 363,150,396,0,0,0,0,105
        person:
          mask:
            - 0,0,458,0,441,125,0,72

    live:
      stream_name: driveway_floodlight_camera

    detect:
      width: 396
      height: 704

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 704

  front_stairs_camera:
    ui:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_stairs_camera_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_stairs_camera_main?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

      hwaccel_args: preset-nvidia-h264

    motion:
      mask:
        - 696,54,700,263,555,368,524,110  # window overlooking street 

    live:
      stream_name: front_stairs_camera_main

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080

  storage_camera_wide:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/storage_camera_wide_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/storage_camera_wide_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

      hwaccel_args: preset-nvidia-h264

    live:
      stream_name: storage_camera_wide_main

    objects:
      track:
        - person
        - backpack
        - bicycle
        - skis
        - snowboard

    record:
      enabled: true

      retain:
        days: 30
        mode: all

      events:
        retain:
          default: 90
          mode: active_objects
          
          objects:
            person: 365

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 512
  
  storage_camera_zoom:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/storage_camera_zoom_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/storage_camera_zoom_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

      hwaccel_args: preset-nvidia-h264

    live:
      stream_name: storage_camera_zoom_main

    record:
      enabled: true

      retain:
        days: 30
        mode: all

      events:
        retain:
          default: 90
          mode: active_objects
          
          objects:
            person: 365

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 512

  roof_camera:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/roof_camera_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/roof_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1536
      height: 576

    objects:
      filters:
        person:
          mask:
            - 0,0,1536,0,1536,411,986,210,844,187,686,186,0,462 # not on the roof

    
    zones:
      vegetables:
        coordinates: 1058,245,1154,318,1220,353,1242,310,1290,340,1307,390,1252,463,1162,413,1139,378,1087,344,990,309,980,269
      far_seating_area:
        coordinates: 945,195,947,276,746,235,747,189
      patio_table:
        coordinates: 953,323,1054,311,1094,343,1193,411,1227,518,1129,576,992,576,890,395

    motion:
      mask:
        - 450,391,527,311,534,230,598,213,632,323,508,473,454,453 # AC Units

    live:
      stream_name: roof_camera_main
      
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 576


  back-stairs-camera:
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back-stairs-camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-nvidia-h264

    objects:
      filters:
        person:
          mask: 
            - 1280,720,1280,497,1034,367,861,526,803,720 # Vacuum area which keeps identifying as a person

    live:
      stream_name: back-stairs-camera
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1296

  building-front-door-camera:
    ui:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/building_front_door_camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-nvidia-h264
    live:
      stream_name: building_front_door_camera

    record:
      enabled: true

      retain:
        days: 30
        mode: all

      events:
        retain:
          default: 90
          mode: active_objects
          
          objects:
            person: 365

    motion:
      mask:
        - 549,90,742,40,767,0,959,0,0,0,0,645,174,697,275,212,548,187 # not on property

    objects:
      filters:
        person:
          mask:
            - 549,90,742,40,767,0,959,0,0,0,0,645,174,697,275,212,548,187 # not on property

    zones:
      buzzer:
        coordinates: 645,478,758,420,883,277,1049,720,646,720
      flowerbox:
        coordinates: 542,78,740,43,754,108,542,123
      gate:
        coordinates: 759,404,716,190,788,0,863,0
      property_line:
        coordinates: 544,178,550,80,734,59,767,0,1280,0,1280,720,276,720,173,683,276,216
    
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1296
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"back-stairs-camera":{"camera_fps":5.0,"capture_pid":661,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":678,"pid":627,"process_fps":5.0,"skipped_fps":0.0},"building-front-door-camera":{"camera_fps":5.0,"capture_pid":677,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":686,"pid":628,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.4"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.1"},"1309":{"cpu":"0.0","mem":"0.0"},"1317":{"cpu":"0.0","mem":"0.0"},"1323":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"156":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"180":{"cpu":"0.0","mem":"0.0"},"215":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"252":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"289":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"323":{"cpu":"0.0","mem":"0.0"},"351":{"cpu":"0.0","mem":"0.0"},"388":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"574":{"cpu":"0.0","mem":"0.5"},"580":{"cpu":"0.3","mem":"0.1"},"581":{"cpu":"0.0","mem":"0.7"},"583":{"cpu":"0.0","mem":"0.7"},"586":{"cpu":"0.7","mem":"0.6"},"593":{"cpu":"0.3","mem":"0.6"},"594":{"cpu":"0.0","mem":"0.1"},"597":{"cpu":"0.0","mem":"0.6"},"619":{"cpu":"0.0","mem":"0.1"},"622":{"cpu":"0.3","mem":"0.6"},"623":{"cpu":"0.3","mem":"0.6"},"624":{"cpu":"0.0","mem":"0.1"},"625":{"cpu":"0.0","mem":"0.6"},"626":{"cpu":"0.0","mem":"0.1"},"627":{"cpu":"0.7","mem":"0.6"},"628":{"cpu":"0.3","mem":"0.6"},"629":{"cpu":"0.0","mem":"0.1"},"630":{"cpu":"0.7","mem":"0.6"},"633":{"cpu":"0.7","mem":"0.6"},"634":{"cpu":"1.0","mem":"1.0"},"635":{"cpu":"0.0","mem":"0.1"},"638":{"cpu":"1.0","mem":"0.6"},"639":{"cpu":"2.3","mem":"1.5"},"644":{"cpu":"0.0","mem":"0.1"},"645":{"cpu":"0.7","mem":"0.6"},"646":{"cpu":"1.0","mem":"1.0"},"647":{"cpu":"0.3","mem":"0.1"},"652":{"cpu":"1.0","mem":"0.1"},"653":{"cpu":"0.0","mem":"0.6"},"656":{"cpu":"1.0","mem":"1.0"},"659":{"cpu":"0.0","mem":"0.1"},"660":{"cpu":"0.3","mem":"0.1"},"661":{"cpu":"1.0","mem":"0.6"},"662":{"cpu":"0.3","mem":"1.1"},"676":{"cpu":"0.0","mem":"0.1"},"677":{"cpu":"0.7","mem":"0.6"},"678":{"cpu":"2.0","mem":"1.3"},"684":{"cpu":"0.0","mem":"0.1"},"686":{"cpu":"1.0","mem":"1.2"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"7.7","mem":"0.2"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"14.7","mem":"1.2"},"MiB":{"cpu":"8168.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"0.53,"}},"detection_fps":5.6,"detectors":{"coral_pci_1":{"detection_start":0.0,"inference_speed":6.21,"pid":581},"coral_pci_2":{"detection_start":0.0,"inference_speed":6.21,"pid":583}},"driveway_floodlight_camera":{"camera_fps":5.1,"capture_pid":630,"detection_enabled":1,"detection_fps":0.9,"ffmpeg_pid":634,"pid":593,"process_fps":5.1,"skipped_fps":0.0},"front_stairs_camera":{"camera_fps":5.1,"capture_pid":633,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":639,"pid":597,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"Quadro P2000":{"gpu":"4 %","mem":"77.5 %"}},"roof_camera":{"camera_fps":5.5,"capture_pid":653,"detection_enabled":1,"detection_fps":4.7,"ffmpeg_pid":662,"pid":625,"process_fps":5.4,"skipped_fps":0.0},"service":{"last_updated":1692024873,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":1061.7,"mount_type":"tmpfs","total":1073.7,"used":12.0},"/media/frigate/clips":{"free":13055177.3,"mount_type":"ext4","total":39825926.9,"used":24771426.2},"/media/frigate/recordings":{"free":13055177.3,"mount_type":"ext4","total":39825926.9,"used":24771426.2},"/tmp/cache":{"free":983.7,"mount_type":"tmpfs","total":1000.0,"used":16.3}},"temperatures":{"apex_0":48.55,"apex_1":47.05},"uptime":163,"version":"0.12.1-367d724"},"storage_camera_wide":{"camera_fps":5.0,"capture_pid":638,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":646,"pid":622,"process_fps":5.0,"skipped_fps":0.0},"storage_camera_zoom":{"camera_fps":5.1,"capture_pid":645,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":656,"pid":623,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Dahua IPC-L46N-USA
