### ISSUE TITLE
[Config Support]: Getting significant amount of detect events tagged with a zone, but well outside defined zone

### ISSUE THREAD

**Issue by duro** [blakeblackshear/frigate#7475]
### Describe the problem you are having

I have a zone defined for one of my cameras. I have also configured the camera to require that zone for any events it generates. However, I am still getting a significant number of events that claim to be inside that zone, but are well outside of it. The specific camera I am referring to is "camera2" in my setup.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: homeassistant.lan
  user: XXXX
  password: XXXX

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 5
    mode: all

snapshots:
  enabled: True

objects:
  track:
    - person
    - dog
    - cat

go2rtc:
  ngrok:
    command: /config/ngrok start --all --config /config/ngrok.yaml
  streams:
    camera1:
      - rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01
    camera2:
      - rtsp://XXX:XXX@192.168.XXX.XXX:554/
    camera3:
      - rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01
    camera4:
      - rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01
    camera5:
      - rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01
    camera6:
      - rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01
  webrtc:
    candidates:
      - 192.168.30.175:8555
      - stun:8555

cameras:
  camera1: # <------ Front Door
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://XXX:XXX@192.168.XXX.XXX@192.168.2.10:554/
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      filters:
        person:
          mask: 
            - 78,309,167,297,167,241,66,243
            # - 1048,1944,1046,1679,553,1705,558,1944
            # - 333,1330,646,1278,603,907,304,956
  camera2: # <------ Driveway
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        # - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01 # <----- The stream you want to use for detection
        #   roles:
        #     - detect
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/
          roles:
            - record
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2592 # <---- update for your camera's resolution
      height: 1944 # <---- update for your camera's resolution
    record:
      events:
        required_zones:
          - front_yard
    snapshots:
      required_zones:
        - front_yard
    # objects:
    #   filters:
    #     person:
    #       mask:
    #         - 0,1944,334,1944,339,1750,0,1735
    zones:
      front_yard:
        coordinates: 0,1944,2592,1944,2592,673,2110,535,1285,606,630,716,0,907
  camera3: # <------ Living Room
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/
          roles:
            - record
    snapshots:
      enabled: False
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
  camera4: # <------ Patio
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/
          roles:
            - record
    snapshots:
      enabled: False
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
  camera5: # <------ Studio Side Yard
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/
          roles:
            - record
    record:
      events:
        required_zones:
          - studio_alley
    snapshots:
      required_zones:
        - studio_alley
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    # motion:
    #   mask:
    #     - 0,1006,355,1082,700,943,839,581,851,299,718,207,731,0,0,0
    #     - 1588,1944,2592,1944,2592,0,1039,0,976,436,1649,414
    zones:
      studio_alley:
        coordinates: 164,480,449,480,455,205,310,205
  camera6: # <------ Kitchen Side Yard
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/cam/realmonitor?channel=1&subtype=01 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554/
          roles:
            - record
    record:
      events:
        required_zones:
          - kitchen_alley
    snapshots:
      required_zones:
        - kitchen_alley
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    zones:
      kitchen_alley:
        coordinates: 91,480,704,480,704,408,542,267,451,270,368,172,236,177
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
{"camera1":{"camera_fps":5.0,"capture_pid":316,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":321,"pid":306,"process_fps":5.0,"skipped_fps":0.0},"camera2":{"camera_fps":5.0,"capture_pid":320,"detection_enabled":1,"detection_fps":8.8,"ffmpeg_pid":326,"pid":309,"process_fps":5.1,"skipped_fps":0.0},"camera3":{"camera_fps":5.0,"capture_pid":325,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":345,"pid":310,"process_fps":5.0,"skipped_fps":0.0},"camera4":{"camera_fps":5.0,"capture_pid":328,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":349,"pid":312,"process_fps":5.1,"skipped_fps":0.0},"camera5":{"camera_fps":5.1,"capture_pid":333,"detection_enabled":1,"detection_fps":10.5,"ffmpeg_pid":351,"pid":313,"process_fps":5.0,"skipped_fps":0.0},"camera6":{"camera_fps":5.0,"capture_pid":337,"detection_enabled":1,"detection_fps":4.8,"ffmpeg_pid":358,"pid":314,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"5.1"},"1":{"cpu":"0.0","mem":"0.0"},"107":{"cpu":"0.0","mem":"0.0"},"111":{"cpu":"8.6","mem":"5.0"},"119":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.2"},"136":{"cpu":"0.0","mem":"0.3"},"137":{"cpu":"0.0","mem":"0.4"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"276":{"cpu":"0.3","mem":"0.2"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"292":{"cpu":"0.0","mem":"0.9"},"298":{"cpu":"0.3","mem":"0.1"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"2.7","mem":"1.1"},"306":{"cpu":"1.0","mem":"1.2"},"308":{"cpu":"0.0","mem":"0.0"},"309":{"cpu":"11.3","mem":"2.0"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"0.7","mem":"1.2"},"311":{"cpu":"0.0","mem":"0.0"},"312":{"cpu":"0.7","mem":"1.2"},"313":{"cpu":"10.6","mem":"1.2"},"314":{"cpu":"4.0","mem":"1.2"},"315":{"cpu":"0.0","mem":"0.0"},"316":{"cpu":"1.3","mem":"1.1"},"319":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"10.6","mem":"1.3"},"321":{"cpu":"2.3","mem":"0.2"},"324":{"cpu":"0.0","mem":"0.0"},"325":{"cpu":"1.3","mem":"1.1"},"326":{"cpu":"10.0","mem":"1.2"},"328":{"cpu":"1.0","mem":"1.1"},"332":{"cpu":"0.0","mem":"0.0"},"333":{"cpu":"1.3","mem":"1.1"},"337":{"cpu":"0.7","mem":"1.1"},"338":{"cpu":"2.0","mem":"0.2"},"340":{"cpu":"0.0","mem":"0.0"},"345":{"cpu":"2.3","mem":"0.2"},"349":{"cpu":"2.0","mem":"0.2"},"351":{"cpu":"2.0","mem":"0.2"},"358":{"cpu":"2.0","mem":"0.2"},"360":{"cpu":"2.3","mem":"0.2"},"362":{"cpu":"2.3","mem":"0.2"},"366":{"cpu":"2.3","mem":"0.2"},"368":{"cpu":"2.3","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"503433":{"cpu":"17.3","mem":"4.2"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"868511":{"cpu":"0.0","mem":"0.0"},"868537":{"cpu":"0.0","mem":"0.0"},"868545":{"cpu":"0.0","mem":"0.0"},"90":{"cpu":"1.3","mem":"0.4"},"MiB":{"cpu":"2158.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":24.1,"detectors":{"coral":{"detection_start":1692034779.516633,"inference_speed":16.11,"pid":503433}},"gpu_usages":{"intel-vaapi":{"gpu":"9.68 %","mem":"- %"}},"service":{"last_updated":1692034783,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":333.3,"mount_type":"tmpfs","total":373.3,"used":40.0},"/media/frigate/clips":{"free":1675917.2,"mount_type":"ext4","total":3936149.9,"used":2060210.6},"/media/frigate/recordings":{"free":1675917.2,"mount_type":"ext4","total":3936149.9,"used":2060210.6},"/tmp/cache":{"free":956.2,"mount_type":"tmpfs","total":1000.0,"used":43.8}},"temperatures":{},"uptime":431094,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
