### ISSUE TITLE
[Support]: Frigate won't start

### ISSUE THREAD

**Issue by Cornmeister** [blakeblackshear/frigate#7510]
### Describe the problem you are having

When I run a docker compose up, it starts the docker, 
after a couple of seconds, its gone.

### Version

dunno, latest docker

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.27:8554/stream
          roles:
            - detect
    detect:
      enabled: False
      width: 1280
      height: 720
```

### Relevant log output

```shell
root@proxmox:/mnt/proxmox_docker/frigate# docker ps
CONTAINER ID   IMAGE                    COMMAND        CREATED          STATUS          PORTS
                                         NAMES
2ab40b8dca65   portainer/portainer-ce   "/portainer"   38 minutes ago   Up 38 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 9443/tcp   portainer
root@proxmox:/mnt/proxmox_docker/frigate# docker compose up
[+] Running 1/0
 ✔ Container frigate  Created                                                                                                              0.0s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-08-18 11:51:23.108095203  [INFO] Preparing go2rtc config...
frigate  | 2023-08-18 11:51:23.108335436  [INFO] Starting Frigate...
frigate  | 2023-08-18 11:51:23.108646873  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-08-18 11:51:23.301790839  [INFO] Starting go2rtc...
frigate  | 2023-08-18 11:51:23.401252554  11:51:23.401 INF go2rtc version 1.2.0 linux/amd64
frigate  | 2023-08-18 11:51:23.401461132  11:51:23.401 INF [api] listen addr=:1984
frigate  | 2023-08-18 11:51:23.401563622  11:51:23.401 INF [rtsp] listen addr=:8554
frigate  | 2023-08-18 11:51:23.401682699  11:51:23.401 INF [srtp] listen addr=:8443
frigate  | 2023-08-18 11:51:23.401793420  11:51:23.401 INF [webrtc] listen addr=:8555
frigate  | 2023-08-18 11:51:23.815071811  [2023-08-18 11:51:23] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
frigate  | 2023-08-18 11:51:23.826228837  [2023-08-18 11:51:23] peewee_migrate                 INFO    : Starting migrations
frigate  | 2023-08-18 11:51:28.834533945  database is locked
frigate  | 2023-08-18 11:51:29.929656435  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-08-18 11:51:29.938056584  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2023-08-18 11:51:30.095435257  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2023-08-18 11:51:30.098575630  exit OK
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2023-08-18 11:51:30.101290033  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
root@proxmox:/mnt/proxmox_docker/frigate#
```

### FFprobe output from your camera

```shell
can't test
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

raspberry pi cam v3

### Any other information that may be helpful

Running docker on proxmox bare metal, not in a container.

Docker compose file
```
root@proxmox:/mnt/proxmox_docker/frigate# more docker-compose.yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/proxmox_docker/frigate/config/config.yml:/config/config.yml
      - /mnt/proxmox_docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "frigate"
```

**Comment by Cornmeister** [comment]
i had another frigate instance running on another machine, copied the DB from it, and now I'm able to start.

**Comment by NickM-27** [comment]
what is `/mnt/proxmox_docker/frigate/storage` ? (type of storage, mount type, etc.)

**Comment by Cornmeister** [comment]
> what is `/mnt/proxmox_docker/frigate/storage` ? (type of storage, mount type, etc.)

that's a cifs share on my synology (volume with M.2 disk)

**Comment by NickM-27** [comment]
Gotcha, like the docs say it is not recommended to run the DB on that type of storage. In the upcoming version of frigate the location of the db will be moving to /config. So you can move to that change now by adjusting the docker config to be

```
root@proxmox:/mnt/proxmox_docker/frigate# more docker-compose.yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/proxmox_docker/frigate/config/:/config/
      - /mnt/proxmox_docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "frigate"
```

and adding

```
database:
  path: /config/frigate.db
```

to the frigate config
