### ISSUE TITLE
[Support]: No MQTT events with audio events labels ¿Bug?

### ISSUE THREAD

**Issue by Cheerpipe** [blakeblackshear/frigate#7517]
### Describe the problem you are having

I am trying to get HA notifications on audio events for "crying" and "speech" labels but i get no events wtth audio labels in mqtt. Don't know if it is a non implemented yet feature, a bug or a config problem.

Thanks in advance and sorry if my english sounds rude or crude as it is not my main language.

### Version

0.13.0-28EA2AF

### Frigate config file

```yaml
mqtt:
  host: XXX.XXX.XXX.XXX
  user: XXXXXXXXX
  password: XXXXXXXXX

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /custom/models/yolov8m/yolov8m.xml

audio: # <- enable audio events for all camera
  enabled: True
  listen:
    - bark
    - scream
    - speech
    - yell
    - crying
    - children_playing
    - alarm

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /custom/models/yolov8m/coco_80cl.txt

go2rtc:
  rtsp:
    username: XXXX
    password: XXXX
  webrtc:
    candidates:
      - XXX.XXX.XXX.XXX:8555
      - stun:8555    
  streams:
      salon: 
        - rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
        - "ffmpeg:salon#audio=opus"
      pasillo: 
        - rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
        - "ffmpeg:pasillo#audio=opus"
      entrada: 
        - rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
        - "ffmpeg:entrada#audio=opus"
      comida_luke: 
        - rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX:8554/unicast
        - "ffmpeg:comida_luke#audio=opus"
      cocina: 
        - rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
        - "ffmpeg:cocina#audio=opus"
      dormitorio_pequeno: 
        - rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
        - "ffmpeg:dormitorio_pequeno#audio=opus"        
      dormitorio_principal: 
        - rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
        - "ffmpeg:dormitorio_principal#audio=opus"

cameras:
  salon:
    zones:
      comedor:
        coordinates: 385,284,363,144,303,94,32,186,27,256,82,415,364,310
        objects: 
          - person
      salon_sofa:          
        coordinates: 1034,282,902,466,864,556,530,375,533,267,710,166
        objects: 
          - person   
      salon_bergere:          
        coordinates: 446,388,356,374,272,312,202,320,68,403,91,479,148,609,213,699,356,699,455,681,513,558,508,452
        objects: 
          - person                   
    motion:
      mask:
        - 910,41,1250,43,1247,0,912,0
        - 394,720,602,580,610,521,630,499,700,498,751,541,893,608,1023,420,1152,0,1280,0,1280,720,231,720,218,687,330,638
        - 0,720,248,720,162,579,97,455,58,253,75,177,301,99,302,0,0,0
        - 1062,0,1020,211,695,117,439,71,428,0
    ffmpeg:
     inputs:
        - path: rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
          roles:
            - detect
            - record
            - audio
          
  pasillo:
    motion:
      mask:
        - 1280,720,987,720,1012,413,1236,0,1280,0
        - 910,41,1250,43,1247,0,912,0
    objects:
      filters:
        person:
          min_area: 40000
    ffmpeg:
     inputs:
        - path: rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
          roles:
            - detect
            - record
            - audio
    
  entrada:
    motion:
      mask:  
        - 910,41,1250,43,1247,0,912,0
        - 0,720,166,720,180,264,261,0,0,0
        - 1056,286,1083,440,1103,638,1005,622,981,362,914,30,935,0,980,0
    objects:
      filters:
        person:
          min_area: 40000          
          mask:
           - 1019,658,1043,416,1031,178,1010,0,926,0,947,273,938,604
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
          roles:
            - detect
            - record
            - audio
  
  comida_luke:
    motion:
      mask:
        - 775,0,0,0,0,720,1280,720,1280,0,751,0,529,200,833,167,1129,720,462,720,541,201
    objects:
      track:
        - cat
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX:8554/unicast
          roles:
            - detect
            - record
            - audio  
  cocina:
    motion:
      mask:
        #- 1155,720,1280,720,1280,470
        #- 0,720,0,0,343,0,164,89,197,249,437,563,522,558,725,720
        - 702,720,0,720,0,308,0,0,380,0,162,91,188,279,378,530,438,529
        - 910,41,1250,43,1247,0,912,0
        - 789,447,803,510,740,566,688,539,702,480
    ffmpeg:
     inputs:
        - path: rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0 
          roles:
            - detect
            - record
            - audio


  dormitorio_pequeno: 
    objects:
      filters:
        person:
          min_area: 30000
    motion:
      mask:
        - 115,0,164,175,235,158,402,77,458,54,454,0
        - 0,720,469,720,233,402,55,0,0,0
        - 578,62,588,145,424,195,276,267,246,169,410,105
        - 910,41,1250,43,1247,0,912,0
    ffmpeg:
    inputs:
        - path: rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
          roles:
            - detect
            - record
            - audio  
  
  dormitorio_principal:
    motion:
      mask:
        - 1064,385,1133,147,1164,0,1280,0,1280,720,880,720
        - 910,41,1250,43,1247,0,912,0
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX:XXXXXXXXXX@XXX.XXX.XXX.XXX/live0
          roles:
            - detect
            - record
            - audio            
ffmpeg:
  retry_interval: 2
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args: preset-vaapi 

birdseye:
  enabled: True
  restream: True
  width: 1280
  height: 720
  quality: 24
  mode: objects

objects:
  track:
    - person
    - cat
  filters:
    cat:
      min_score: 0.6
      threshold: 0.7
    person:
      min_score: 0.6
      threshold: 0.7

rtmp:
  enabled: False

snapshots:
  enabled: True
  bounding_box: True
  timestamp: True

detect:
  enabled: True
  width: 1280
  height: 720
  fps: 4
  stationary:
    interval: 75

record:
  enabled: True
  retain:
    days: 90
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects

motion:
  improve_contrast: False
```

### Relevant log output

```shell
irrelevant?
```

### FFprobe output from your camera

```shell
irrelevant?
```

### Frigate stats

```json
irrelevant?
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Eufy 360 2k

### Any other information that may be helpful

* My automations are working fine with video events.
* I get mqtt events in HA mqtt sniffer but only with video event labels like "person" or "cat".
* Audio events appears to be working fine in frigate as i have events with audio labels in "Events" UI on frigate frontend

![image](https://github.com/blakeblackshear/frigate/assets/972765/cab29be4-8bd4-4247-bc81-da9258fc50bb)
