### ISSUE TITLE
[Support]: Unable to use RTSP restreams

### ISSUE THREAD

**Issue by raddacle** [blakeblackshear/frigate#7526]
### Describe the problem you are having

I'm attempting to setup the RTSP restream option in this format "rtsp://<frigate_host>:8554/<camera_name>" or one of the variations listed in go2rtc. The same input stream url I've entered for go2rtc, works fine in frigate and even the mse stream works. However, none of the RTSP restreams work.

The only error I have in the go2rtc log is: 
WRN error="websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header"

This is the url that is being used as the stream input:
http://192.168.0.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password&proto=Onvif

Is that error connected to the issue I'm having, if so, how could I resolve it?

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.4
  port: 1883
  user: homeassistant
  password: *password*
cameras:
  Doorbell_Camera:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.0.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password&proto=Onvif
          roles:
            - record
        - path: http://192.168.0.42/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password&proto=Onvif
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 2560
      height: 1920
      fps: 7
    mqtt:
      quality: 100
      height: 500
      bounding_box: true
      timestamp: false
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    objects:
      track:
        - person
        - dog
        - cat
        - car
objects:
  track:
    - person
    - dog
    - car
    - cat
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 10
      mode: active_objects
      objects:
        car: 3
ui:
  use_experimental: false
  
birdseye:
  enabled: True
  mode: continuous

go2rtc:
  streams:
    Doorbell_Camera:
      - http://192.168.0.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password&proto=Onvif
    Doorbell_Camera_jpeg:
      - "ffmpeg:Doorbell_Camera#image=jpeg"
```

### Relevant log output

```shell
WRN error="websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header"
```

### FFprobe output from your camera

```shell
Metadata:
    displayWidth    : 2560
    displayHeight   : 1920
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 19 fps, 20 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Wifi Doorbell
