### ISSUE TITLE
[Config Support]: Incorrect video after ffmpeg rotation of RTSP

### ISSUE THREAD

**Issue by Jon811** [blakeblackshear/frigate#7527]
### Describe the problem you are having

I installed a camera in front of door, but not horizontal, as usual, but rotated 90 degree. I made an ffmpeg setting #rotate=270, but when i open Frigate interface, camera shows fine, vertical picture. Recordings shows "pressed" picture, on panel also "pressed"

### Version

0.12.1

### Frigate config file

```yaml
record:
  enabled: true
  expire_interval: 10
  retain:
    days: 3
    mode: all
go2rtc:
  streams:
    rtsp_cam: 
      - "ffmpeg:rtsp://jon811:771762@192.168.0.49:554/stream1#video=h264#rotate=270#width=1080#height=1920#audio=aac"

cameras:
  rtsp_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      width: 1080
      height: 1920
      enabled: false
```

### Relevant log output

```shell
All fine
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
