### ISSUE TITLE
[Support]: AttributeError: 'Dispatcher' object has no attribute '_camera_settings_handlers'

### ISSUE THREAD

**Issue by Cheerpipe** [blakeblackshear/frigate#7544]
### Describe the problem you are having

mqtt stop working with: AttributeError: 'Dispatcher' object has no attribute '_camera_settings_handlers'

It works OK for some time until it fails.

### Version

0.13.0-7C629C1

### Frigate config file

```yaml
mqtt:
  host: 
  user: 
  password: 

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /custom/models/yolov8m288/yolov8m.xml

model:
  width: 288
  height: 288
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /custom/models/yolov8m288/coco_80cl.txt      

audio:
  enabled: True
  listen:
    - bark
    - scream
    - speech
    - yell
    - crying
    - children_playing
    - alarm

go2rtc:
  rtsp:
    username: 
    password: 
  webrtc:
    candidates:
      - XXXXXXXXXX:8555
      - stun:8555    
  streams:
      salon: 
        - rtsp://XXXXXXX
        - "ffmpeg:salon#audio=opus"
      pasillo: 
        - rtsp://XXXXXXX
        - "ffmpeg:pasillo#audio=opus"
      entrada: 
        - rtsp://XXXXXXX
        - "ffmpeg:entrada#audio=opus"
      comida_luke: 
        - rtsp://XXXXXXX
        - "ffmpeg:comida_luke#audio=opus"
      cocina: 
        - rtsp://XXXXXXX
        - "ffmpeg:cocina#audio=opus"
      dormitorio_pequeno: 
        - rtsp://XXXXXXX
        - "ffmpeg:dormitorio_pequeno#audio=opus"        
      dormitorio_principal: 
        - rtsp://XXXXXXX
        - "ffmpeg:dormitorio_principal#audio=opus"

cameras:
  salon:
    zones:
      comedor:
        coordinates: 385,284,363,144,303,94,32,186,27,256,82,415,364,310
        objects: 
          - person
      salon_sofa:          
        coordinates: 1034,282,902,466,864,556,530,375,533,267,710,166
        objects: 
          - person   
      salon_bergere:          
        coordinates: 446,388,356,374,272,312,202,320,68,403,91,479,148,609,213,699,356,699,455,681,513,558,508,452
        objects: 
          - person                   
    motion:
      mask:
        - 910,41,1250,43,1247,0,912,0
        - 387,699,591,575,610,521,630,499,717,487,769,525,893,608,1023,420,1152,0,1280,0,1280,720,231,720,218,687,330,638
        - 0,720,248,720,162,579,97,455,58,253,75,177,301,99,302,0,0,0
        - 1062,0,1020,211,695,117,439,71,428,0
        - 255,453,315,551,246,577,203,469
    objects:
      filters:
        person:
          mask:
            - 999,720,1025,687,719,493,333,720
            - 302,0,333,213,443,184,436,0
            - 310,0,0,0,0,167,315,85
            - 432,0,1280,0,1280,720,1008,720,884,613,1118,289,439,86
            - 0,75,0,720,220,720,68,436
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:8554/salon
          input_args: preset-rtsp-restream-low-latency        
          roles:
            - detect
            - record
            - audio
          
  pasillo:
    motion:
      mask:
        - 1280,720,987,720,1012,413,1236,0,1280,0
        - 910,41,1250,43,1247,0,912,0
    objects:
      filters:
        person:
          min_area: 40000
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:8554/pasillo
          roles:
            - detect
            - record
            - audio
    
  entrada:
    motion:
      mask:  
        - 910,41,1250,43,1247,0,912,0
        - 0,720,166,720,180,264,261,0,0,0
        - 1056,286,1083,440,1103,638,1005,622,981,362,914,30,935,0,980,0
    objects:
      filters:
        person:
          min_area: 40000          
          mask:
           - 1019,658,1043,416,1031,178,1010,0,926,0,947,273,938,604
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:8554/entrada
          roles:
            - detect
            - record
            - audio
  
  comida_luke:
    motion:
      mask:
        - 775,0,0,0,0,720,1280,720,1280,0,751,0,529,200,833,167,1129,720,462,720,541,201
    objects:
      track:
        - cat
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:8554/comida_luke
          roles:
            - detect
            - record
    audio:
          enabled: False

  cocina:
    motion:
      mask:
        - 702,720,0,720,0,308,0,0,380,0,162,91,188,279,378,530,438,529
        - 910,41,1250,43,1247,0,912,0
        - 789,447,803,510,740,566,688,539,702,480
        - 969,0,991,53,760,42,755,0
    objects:
      filters:
        person:
          mask:
            - 989,0,991,58,772,38,768,0
            - 351,382,259,398,200,317,171,98,319,0
            - 0,720,409,549,609,720   
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:8554/cocina
          roles:
            - detect
            - record
            - audio

  dormitorio_pequeno: 
    objects:
      filters:
        person:
          min_area: 30000
    motion:
      mask:
        - 115,0,164,175,235,158,402,77,458,54,454,0
        - 0,720,469,720,233,402,55,0,0,0
        - 578,62,588,145,424,195,276,267,246,169,410,105
        - 910,41,1250,43,1247,0,912,0
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:8554/dormitorio_pequeno
          roles:
            - detect
            - record
            - audio  
  
  dormitorio_principal:
    motion:
      mask:
        - 1064,385,1133,147,1164,0,1280,0,1280,720,880,720
        - 910,41,1250,43,1247,0,912,0
    zones:
      cama:
        coordinates: 269,198,374,239,728,138,1004,369,604,606,551,583,441,604        
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:8554/dormitorio_principal
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
            - audio            
ffmpeg:
  retry_interval: 3
  output_args:
    record: preset-record-generic-audio-copy
  hwaccel_args: preset-vaapi

birdseye:
  enabled: True
  restream: True
  width: 1280
  height: 720
  quality: 24
  mode: objects

objects:
  track:
    - person
    - cat
  filters:
    cat:
      min_score: 0.65
      threshold: 0.7
    person:
      min_score: 0.765
      threshold: 0.7

rtmp:
  enabled: False

snapshots:
  enabled: True
  bounding_box: True
  timestamp: True

detect:
  enabled: True
  width: 1280
  height: 720
  fps: 5
  stationary:
    interval: 75

record:
  enabled: True
  retain:
    days: 90
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects

motion:
  improve_contrast: False
```

### Relevant log output

```shell
2023-08-21 18:33:51.434083215  [2023-08-21 18:33:51] frigate.app                    INFO    : Starting Frigate (0.13.0-7c629c1)
2023-08-21 18:33:51.511761154  [2023-08-21 18:33:51] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-08-21 18:33:51.531422242  [2023-08-21 18:33:51] peewee_migrate.logs            INFO    : Starting migrations
2023-08-21 18:33:51.566362451  [2023-08-21 18:33:51] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-08-21 18:33:51.586642901  [2023-08-21 18:33:51] frigate.app                    INFO    : Recording process started: 368
2023-08-21 18:33:51.586646162  [2023-08-21 18:33:51] frigate.app                    INFO    : go2rtc process pid: 86
2023-08-21 18:33:51.600253667  Exception in thread mqtt:
2023-08-21 18:33:51.600256942  Traceback (most recent call last):
2023-08-21 18:33:51.600258209    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-08-21 18:33:51.607574576      self.run()
2023-08-21 18:33:51.607577891    File "/usr/lib/python3.9/threading.py", line 892, in run
2023-08-21 18:33:51.607579082      self._target(*self._args, **self._kwargs)
2023-08-21 18:33:51.607580273    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3591, in _thread_main
2023-08-21 18:33:51.635684846      self.loop_forever(retry_first_connection=True)
2023-08-21 18:33:51.635747232    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
2023-08-21 18:33:51.642168247      rc = self._loop(timeout)
2023-08-21 18:33:51.642171093    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1164, in _loop
2023-08-21 18:33:51.642172256      rc = self.loop_read()
2023-08-21 18:33:51.642173502    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
2023-08-21 18:33:51.642174504      rc = self._packet_read()
2023-08-21 18:33:51.642177046    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
2023-08-21 18:33:51.642186755      rc = self._packet_handle()
2023-08-21 18:33:51.642188031    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3033, in _packet_handle
2023-08-21 18:33:51.642189406      return self._handle_publish()
2023-08-21 18:33:51.642190604    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3327, in _handle_publish
2023-08-21 18:33:51.642202947      self._handle_on_message(message)
2023-08-21 18:33:51.642204269    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3556, in _handle_on_message
2023-08-21 18:33:51.655817584  [2023-08-21 18:33:51] frigate.app                    INFO    : Output process started: 379
2023-08-21 18:33:51.660189123      callback(self, self._userdata, message)
2023-08-21 18:33:51.660192260    File "/opt/frigate/frigate/comms/mqtt.py", line 98, in on_mqtt_command
2023-08-21 18:33:51.660446539      self._dispatcher(
2023-08-21 18:33:51.660471160    File "/opt/frigate/frigate/comms/dispatcher.py", line 77, in _receive
2023-08-21 18:33:51.665436003      self._camera_settings_handlers[command](camera_name, payload)
2023-08-21 18:33:51.665439511  AttributeError: 'Dispatcher' object has no attribute '_camera_settings_handlers'
2023-08-21 18:33:51.713236009  [2023-08-21 18:33:51] frigate.app                    INFO    : Camera processor started for salon: 387
2023-08-21 18:33:51.723543060  [2023-08-21 18:33:51] detector.ov                    INFO    : Starting detection process: 378
2023-08-21 18:33:51.739103819  [2023-08-21 18:33:51] frigate.app                    INFO    : Camera processor started for pasillo: 389
2023-08-21 18:33:51.739915397  [2023-08-21 18:33:51] frigate.app                    INFO    : Camera processor started for entrada: 393
2023-08-21 18:33:51.747116999  [2023-08-21 18:33:51] frigate.app                    INFO    : Camera processor started for comida_luke: 394
2023-08-21 18:33:51.750494986  [2023-08-21 18:33:51] frigate.app                    INFO    : Camera processor started for cocina: 395
2023-08-21 18:33:51.760606215  [2023-08-21 18:33:51] frigate.app                    INFO    : Camera processor started for dormitorio_pequeno: 396
2023-08-21 18:33:51.776335759  [2023-08-21 18:33:51] frigate.app                    INFO    : Camera processor started for dormitorio_principal: 399
2023-08-21 18:33:51.779525152  [2023-08-21 18:33:51] frigate.app                    INFO    : Capture process started for salon: 401
2023-08-21 18:33:51.797219575  [2023-08-21 18:33:51] frigate.app                    INFO    : Capture process started for pasillo: 405
2023-08-21 18:33:51.823796388  [2023-08-21 18:33:51] frigate.app                    INFO    : Capture process started for entrada: 407
2023-08-21 18:33:51.823799855  [2023-08-21 18:33:51] frigate.app                    INFO    : Capture process started for comida_luke: 412
2023-08-21 18:33:51.832401519  [2023-08-21 18:33:51] frigate.app                    INFO    : Capture process started for cocina: 420
2023-08-21 18:33:51.848075296  [2023-08-21 18:33:51] frigate.app                    INFO    : Capture process started for dormitorio_pequeno: 425
2023-08-21 18:33:51.887553358  [2023-08-21 18:33:51] frigate.app                    INFO    : Capture process started for dormitorio_principal: 431
2023-08-21 18:33:51.887556366  [2023-08-21 18:33:51] frigate.app                    INFO    : Audio process started: 436
2023-08-21 18:34:03.421596928  [2023-08-21 18:34:03] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,3,288,288]
2023-08-21 18:34:03.421720589  [2023-08-21 18:34:03] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,84,1701]
2023-08-21 18:34:03.421722776  [2023-08-21 18:34:03] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"cocina":{"camera_fps":5.1,"capture_pid":420,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":429,"pid":395,"process_fps":5.1,"skipped_fps":0.0},"comida_luke":{"camera_fps":5.1,"capture_pid":412,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":421,"pid":394,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"18":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"40":{"cmdline":"/package/admin/s6-2.11.3.0/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"44":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"86":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"5.5","cpu_average":"4","mem":"0.2"},"100":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"115":{"cmdline":"python3 -u -m frigate","cpu":"4.7","cpu_average":"4","mem":"3.9"},"122":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"366":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"368":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"1","mem":"0.8"},"377":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"378":{"cmdline":"frigate.detector.ov  ","cpu":"25.0","cpu_average":"74","mem":"3.0"},"379":{"cmdline":"frigate.output       ","cpu":"6.2","cpu_average":"4","mem":"0.8"},"383":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"384":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"386":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"387":{"cmdline":"frigate.process:salon","cpu":"0.0","cpu_average":"0","mem":"0.8"},"388":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"389":{"cmdline":"frigate.process:pasillo","cpu":"0.0","cpu_average":"0","mem":"0.8"},"392":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"393":{"cmdline":"frigate.process:entrada","cpu":"0.0","cpu_average":"0","mem":"0.8"},"394":{"cmdline":"frigate.process:comida_luke","cpu":"0.8","cpu_average":"0","mem":"0.8"},"395":{"cmdline":"frigate.process:cocina","cpu":"0.0","cpu_average":"0","mem":"0.8"},"396":{"cmdline":"frigate.process:dormitorio_pequeno","cpu":"0.8","cpu_average":"0","mem":"0.8"},"399":{"cmdline":"frigate.process:dormitorio_principal","cpu":"3.9","cpu_average":"1","mem":"0.8"},"400":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"401":{"cmdline":"frigate.capture:salon","cpu":"0.8","cpu_average":"0","mem":"0.7"},"405":{"cmdline":"frigate.capture:pasillo","cpu":"1.6","cpu_average":"0","mem":"0.7"},"406":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-7c629c1 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://xxx.xxx.xxx.53:8554/salon -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/salon-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.6","cpu_average":"1","mem":"0.4"},"407":{"cmdline":"frigate.capture:entrada","cpu":"1.6","cpu_average":"0","mem":"0.7"},"408":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"412":{"cmdline":"frigate.capture:comida_luke","cpu":"1.6","cpu_average":"0","mem":"0.7"},"414":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-7c629c1 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://xxx.xxx.xxx.53:8554/pasillo -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/pasillo-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.4"},"419":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-7c629c1 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://xxx.xxx.xxx.53:8554/entrada -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/entrada-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"1","mem":"0.4"},"420":{"cmdline":"frigate.capture:cocina","cpu":"2.3","cpu_average":"0","mem":"0.7"},"421":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-7c629c1 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://xxx.xxx.xxx.53:8554/comida_luke -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/comida_luke-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.1","cpu_average":"2","mem":"0.4"},"425":{"cmdline":"frigate.capture:dormitorio_pequeno","cpu":"0.8","cpu_average":"0","mem":"0.7"},"429":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-7c629c1 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://xxx.xxx.xxx.53:8554/cocina -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/cocina-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.1","cpu_average":"2","mem":"0.4"},"430":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-7c629c1 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://xxx.xxx.xxx.53:8554/dormitorio_pequeno -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/dormitorio_pequeno-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.4"},"431":{"cmdline":"frigate.capture:dormitorio_principal","cpu":"1.6","cpu_average":"1","mem":"0.7"},"436":{"cmdline":"frigate.audio_manager","cpu":"9.4","cpu_average":"1","mem":"1.0"},"439":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-7c629c1 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://xxx.xxx.xxx.53:8554/dormitorio_principal -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/dormitorio_principal-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.3","cpu_average":"2","mem":"0.4"},"444":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 24 -bf 0 pipe:","cpu":"3.9","cpu_average":"2","mem":"0.3"},"457":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://xxx.xxx.xxx.53:8554/salon -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.8","cpu_average":"0","mem":"0.1"},"461":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://xxx.xxx.xxx.53:8554/pasillo -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"464":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://xxx.xxx.xxx.53:8554/entrada -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"468":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://xxx.xxx.xxx.53:8554/cocina -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"472":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://xxx.xxx.xxx.53:8554/dormitorio_pequeno -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.8","cpu_average":"0","mem":"0.1"},"473":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://xxx.xxx.xxx.53:8554/dormitorio_principal -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.8","cpu_average":"0","mem":"0.1"},"6346":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":7.3,"detectors":{"ov":{"detection_start":1692658125.598992,"inference_speed":46.44,"pid":378}},"dormitorio_pequeno":{"camera_fps":5.1,"capture_pid":425,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":430,"pid":396,"process_fps":5.1,"skipped_fps":0.0},"dormitorio_principal":{"camera_fps":5.0,"capture_pid":431,"detection_enabled":1,"detection_fps":7.2,"ffmpeg_pid":439,"pid":399,"process_fps":5.1,"skipped_fps":0.0},"entrada":{"camera_fps":5.1,"capture_pid":407,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":419,"pid":393,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"16.8%","mem":"-%"}},"pasillo":{"camera_fps":5.1,"capture_pid":405,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":414,"pid":389,"process_fps":5.1,"skipped_fps":0.0},"processes":{"audioDetector":{"pid":436},"go2rtc":{"pid":86},"logger":{"pid":366},"recording":{"pid":368}},"salon":{"camera_fps":5.1,"capture_pid":401,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":406,"pid":387,"process_fps":5.1,"skipped_fps":0.0},"service":{"last_updated":1692658126,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":1007.5,"mount_type":"tmpfs","total":1024.0,"used":16.5},"/media/frigate/clips":{"free":298238.5,"mount_type":"ext4","total":1876681.2,"used":1578426.7},"/media/frigate/recordings":{"free":298238.5,"mount_type":"ext4","total":1876681.2,"used":1578426.7},"/tmp/cache":{"free":950.5,"mount_type":"tmpfs","total":953.7,"used":3.2}},"temperatures":{},"uptime":895,"version":"0.13.0-7c629c1"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Eufy 360 2k
