### ISSUE TITLE
[Support]: Restream Picam V2

### ISSUE THREAD

**Issue by Quedale** [blakeblackshear/frigate#7563]
### Describe the problem you are having

First, I actually resolved the problem, I just thought I would share the solution given that I've seen it reported without actual fix.

I'm not using a branded camera, but rather a home-made solution based on raspberry pi with a picam v2 using the native v4l2 h264 capabilities.
I suppose the same issue can be found on other devices.

Two things are important to consider.
1. If restream is used, the default `h264_i_frame_period` value of 60 is way to long. It can take up to a minute for a live stream to load.
2. For recording playback to work properly, the v4l2 parameter `repeat_sequence_header` is **MANDATORY**!

If `repeat_sequence_header` isn't used, the playback will fail with the error :
`video append of 14372714b failed for segment #0 in playlist 0-index-v1.m3u8`

Maybe there's a possible ffmpeg output argument that could gracefully handle this instead of making the camera repeat it.

I suppose that videojs requires that the file starts with a sequence header, which abort the stream instead of dropping the frame.

You make what you want of that information.

Cheers! And thanks for the great project!

### Version

0.12.0-beta10-tensorrt

### Frigate config file

```yaml
record:
  enabled: True
  retain:
    days: 10
  events:
    retain:
      default: 10

snapshots:
  enabled: True
  clean_copy: False
  timestamp: True
  bounding_box: True
  crop: False
  retain:
    default: 10

go2rtc:
  streams:
    rtsp_cam:
      - rtsp://192.168.1.4:8554/h264
      - "ffmpeg:rtsp_cam#audio=pcmu"
  webrtc:
    candidates:
      - 192.168.1.2:8555
      - stun:8555
      
cameras:
  rtsp_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    zones:  
      zone_driveway:
        coordinates: 232,720,1186,720,1280,447,351,217,172,259
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
Nothing relevant on frigate side.
The error is actually client sided.
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://192.168.1.4:8554/h264':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 15 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "17": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "32": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "41": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "42": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "80": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "81": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "82": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "89": {
      "cpu": "7.3",
      "mem": "0.1"
    },
    "97": {
      "cpu": "2.7",
      "mem": "2.3"
    },
    "105": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "116": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "134": {
      "cpu": "0.3",
      "mem": "0.0"
    },
    "135": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "136": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "137": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "148": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "166": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "197": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "226": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "426": {
      "cpu": "0.0",
      "mem": "1.1"
    },
    "432": {
      "cpu": "0.7",
      "mem": "0.1"
    },
    "433": {
      "cpu": "0.0",
      "mem": "4.1"
    },
    "435": {
      "cpu": "1.7",
      "mem": "1.1"
    },
    "438": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "439": {
      "cpu": "2.3",
      "mem": "1.1"
    },
    "440": {
      "cpu": "9.3",
      "mem": "1.1"
    },
    "444": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "445": {
      "cpu": "10.0",
      "mem": "1.1"
    },
    "677": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "682": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "686": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "693": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "0.4"
    },
    "MiB": {
      "cpu": "13376.6",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "0"
    },
    "top": {
      "cpu": "average:",
      "mem": "0.25,"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "tensorrt": {
      "detection_start": 0,
      "inference_speed": 9.84,
      "pid": 433
    }
  },
  "gpu_usages": {
    "NVIDIA GeForce GTX 1060 3GB": {
      "gpu": "0 %",
      "mem": "9.8 %"
    }
  },
  "rtsp_cam": {
    "camera_fps": 15.1,
    "capture_pid": 440,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 445,
    "pid": 439,
    "process_fps": 15.1,
    "skipped_fps": 0
  },
  "service": {
    "last_updated": 1692840645,
    "latest_version": "0.12.1",
    "storage": {
      "/dev/shm": {
        "free": 63.5,
        "mount_type": "tmpfs",
        "total": 67.1,
        "used": 3.6
      },
      "/media/frigate/clips": {
        "free": 41065.1,
        "mount_type": "ext4",
        "total": 249322.4,
        "used": 196989.2
      },
      "/media/frigate/recordings": {
        "free": 41065.1,
        "mount_type": "ext4",
        "total": 249322.4,
        "used": 196989.2
      },
      "/tmp/cache": {
        "free": 994.8,
        "mount_type": "tmpfs",
        "total": 1000,
        "used": 5.2
      }
    },
    "temperatures": {},
    "uptime": 139,
    "version": "0.12.0-e454daf"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Raspberry Pi Cam V2

### Any other information that may be helpful

My home-made camera is based on the open source project [RPOS](https://breeeze.github.io/rpos/) project.
