### ISSUE TITLE
[Support]: Beta 0.13.0-7C629C1 Birdseye Width

### ISSUE THREAD

**Issue by aneisch** [blakeblackshear/frigate#7569]
### Describe the problem you are having

The width of Birdseye leaves a large black square to the right of the tiled feeds.

### Version

0.13.0-7C629C1

### Frigate config file

```yaml
birdseye:
  enabled: True
  mode: continuous  
  quality: 5

detect: # need to manually set resolution for substreams
  width: 704
  height: 480
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

![Screen Shot 2023-08-24 at 1 07 42 PM](https://github.com/blakeblackshear/frigate/assets/6991461/41d1c407-4b04-470f-a7d0-6bb1e0ab0f19)
