### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by eerison** [blakeblackshear/frigate#7577]
### Describe the problem you are having

My docker is mapped to external HD, when I run frigate container, it disconnect the hd and connect again in other device

for example

it starts in `/dev/sda` and disconnect and connect again in `/dev/sdb`, and I need to mount the HD manually :/

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: False
        # host: mosquitto
detect:
   enabled: False
birdseye:
   enabled: False
go2rtc:
  streams:
    back:
      - rtsp://192.168.1.128:554/user=myuser_password=mypass_channel=1_stream=0.sdp?real_stream
      - "ffmpeg:back#audio=aac"
cameras:
  back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          roles:
            - record
    detect:
      width: 1280
      height: 720
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

### Relevant log output

```shell
time to time I get a error like

invalid log's character, when it appear again I post here.
```

### FFprobe output from your camera

```shell
no error, it reproduce normally the video
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wireless

### Camera make and model

ICsee

**Comment by eerison** [comment]
> You need to include your docker config, frigate does not manage this at all, it is all done by docker or the host.

really strange, because it definetly happens when I start frigate container :(

it's my docker config

```yaml
version: "3"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.frigate.rule=Host(`$ZONE-frigate.mydomain.com`)"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.routers.frigate.tls.certresolver=cloudflare"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
     
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOME_HOST/apps/frigate/config/config.yml:/config/config.yml
      - frigate:/media/frigate
    networks:
      - proxy
      
networks:
  proxy:
    external: true
    
volumes:
  frigate:
```
