### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by medhathaddad** [blakeblackshear/frigate#7579]
### Describe the problem you are having

I keep getting this error every time I try running the automation. The integration seems to be set up fine as I am able to receive notifications via Telegram.

Logger: homeassistant.components.automation.frigate_notifications_0_12_0_1
Source: components/automation/__init__.py:269
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 7:08:22 PM (2 occurrences)
Last logged: 7:24:35 PM

Error rendering variables: TypeError: can only concatenate str (not "int") to str

### Version

(0.12.0.1)

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: core-mosquitto
  topic_prefix: frigate
  client_id: frigate
  port: 1883
  user: --------
  password: ---------

cameras:
  1:
    ffmpeg:
      inputs:
        - path: rtsp://-----:------@192.168.--.--:554/Streaming/Channels/101/
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 15
    record: # <----- Enable recording
      enabled: True
      events:
        retain:
          default: 10
    rtmp:
      enabled: false
    snapshots:
        enabled: true
        timestamp: true
        bounding_box: true
        crop: False
        retain:
            default: 10
            objects:
                person: 15
    objects:
        track:
            - person
            - cat
            - dog
            - car
```

### Relevant log output

```shell
Logger: homeassistant.components.automation.frigate_notifications_0_12_0_1
Source: components/automation/__init__.py:269
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 7:08:22 PM (2 occurrences)
Last logged: 7:24:35 PM

Error rendering variables: TypeError: can only concatenate str (not "int") to str
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
