### ISSUE TITLE
[Detector Support]:  TensorRT doesnt want to work

### ISSUE THREAD

**Issue by belmont** [blakeblackshear/frigate#7582]
### Describe the problem you are having

I am trying to test with TensorRT and my nvidia Tesla T4 card has latest driver with cuda 12
 NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2   

Questions:
1) is it OK to have latest nvidia driver ? this brings CUDA version 12.2 
2) Do you see any error in my docker-compose file and config file that causing ffmpeg error and frigate start issue?
3) should I use different docker image? If yes, which one is working?

### Version

0.13.0-7c629c1

### Frigate config file

```yaml
mqtt:
  host: 192.168.11.100
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: userone
  password: tester
  stats_interval: 60



detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416



logger:
  default: info

  logs:
    frigate.event: debug


objects:

  track:
    - person
 
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7


cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: 'rtsp://userone:pass123@@192.168.11.154/Streaming/Channels/101'
          roles:
            - detect
      global_args:
        - -hide_banner
        - -loglevel
        - info
      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - +genpts+discardcorrupt
      - -rtsp_transport
      - tcp
      - -stimeout
      - '5000000'
      - -use_wallclock_as_timestamps
      - '1'

    detect:
      width: 1920
      height: 1080
      fps: 2
```

### docker-compose file or Docker CLI command

```yaml
at docker-compose.yml 
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-7c629c1-tensorrt
    shm_size: "16g" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/zt/frigate/config:/config
      - /home/zt/frigate/storage:/media/frigate
      - /home/zt/frigate/storage/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    runtime: nvidia
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
     - FRIGATE_RTSP_PASSWORD=password
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Relevant log output

```shell
rigate    | 2023-08-26 18:29:17.657113816  [2023-08-26 18:29:17] frigate.app                    INFO    : Capture process started for entrance: 755
frigate    | 2023-08-26 18:29:17.683212760  [2023-08-26 18:29:17] frigate.video                  ERROR   : entrance: Unable to read frames from ffmpeg process.
frigate    | 2023-08-26 18:29:17.683328550  [2023-08-26 18:29:17] frigate.video                  ERROR   : entrance: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-26 18:29:19.447678080  [2023-08-26 18:29:17] detector.tensorrt              INFO    : Starting detection process: 748
frigate    | 2023-08-26 18:29:19.740314529  [2023-08-26 18:29:19] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 13 MiB
frigate    | 2023-08-26 18:29:19.924720656  [2023-08-26 18:29:19] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 232, Serialized Engine Version: 213)
frigate    | 2023-08-26 18:29:19.935519191  [2023-08-26 18:29:19] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
frigate    | 2023-08-26 18:29:19.936509540  Process detector:tensorrt:
frigate    | 2023-08-26 18:29:19.937716784  Traceback (most recent call last):
frigate    | 2023-08-26 18:29:19.937741153    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate    | 2023-08-26 18:29:19.937742824      self.run()
frigate    | 2023-08-26 18:29:19.937753153    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate    | 2023-08-26 18:29:19.937754708      self._target(*self._args, **self._kwargs)
frigate    | 2023-08-26 18:29:19.937756178    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
frigate    | 2023-08-26 18:29:19.937757758      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate    | 2023-08-26 18:29:19.937768642    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
frigate    | 2023-08-26 18:29:19.937770184      self.detect_api = create_detector(detector_config)
frigate    | 2023-08-26 18:29:19.937771668    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate    | 2023-08-26 18:29:19.937772962      return api(detector_config)
frigate    | 2023-08-26 18:29:19.937774462    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 221, in __init__
frigate    | 2023-08-26 18:29:19.937777371      self.input_shape = self._get_input_shape()
frigate    | 2023-08-26 18:29:19.937790784    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 93, in _get_input_shape
frigate    | 2023-08-26 18:29:19.937792202      binding = self.engine[0]
frigate    | 2023-08-26 18:29:19.937811787  TypeError: 'NoneType' object is not subscriptable
frigate    | 2023-08-26 18:29:19.937859689  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f933900da60>
frigate    | 2023-08-26 18:29:19.937880844  Traceback (most recent call last):
frigate    | 2023-08-26 18:29:19.937883401    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__
frigate    | 2023-08-26 18:29:19.938133140      if self.outputs is not None:
frigate    | 2023-08-26 18:29:19.938150614  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
frigate    | 2023-08-26 18:29:25.444289595  [INFO] Starting go2rtc healthcheck service...
frigate    | 2023-08-26 18:29:37.689884869  [2023-08-26 18:29:37] watchdog.entrance              ERROR   : Ffmpeg process crashed unexpectedly for entrance.
frigate    | 2023-08-26 18:29:37.690065310  [2023-08-26 18:29:37] watchdog.entrance              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2023-08-26 18:29:37.690231644  [2023-08-26 18:29:37] ffmpeg.entrance.detect         ERROR   : Unrecognized option 'stimeout'.
frigate    | 2023-08-26 18:29:37.690383910  [2023-08-26 18:29:37] ffmpeg.entrance.detect         ERROR   : Error splitting the argument list: Option not found
frigate    | 2023-08-26 18:29:37.705623154  [2023-08-26 18:29:37] frigate.video                  ERROR   : entrance: Unable to read frames from ffmpeg process.
frigate    | 2023-08-26 18:29:37.705736597  [2023-08-26 18:29:37] frigate.video                  ERROR   : entrance: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-26 18:29:37.987219817  [2023-08-26 18:29:37] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
frigate    | s6-rc: info: service legacy-services: stopping
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Proxmox hypervisor with PCI pass thru, nvidia-smi shows the GPU is working fine in the VM and also in the docker container.
