### ISSUE TITLE
[Config Support]: Live stream laggy - in HA frigate or dashboard cards - not so in VLC (rtsp) - reolink doorbell

### ISSUE THREAD

**Issue by jcat59** [blakeblackshear/frigate#7589]
### Describe the problem you are having

I have frigate HAOS addon set up - and having an issue with laggy live view within home assistant. This whether I view with frigate live card, or other camera entity. Is there anything I can do to help this? I'll have a USB coral tomorrow, but I'm guessing that won't help this issue.

Prior to installing Frigate, I had used RTSPtoWebRTC HAOS add on to display the live stream in HA, and that did not lag. I have removed that add on.

--------------------------------------------------------------------------------------------
I am using HAOS baremetal, with frigate add on - with intel i5 processor (HP 600 G2, 8gb ram, SSD drives) - camera is a reolink wifi doorbell. Everything else is working other than the laggy video - just installed the past 2 days.

my reolink wifi doorbell camera specs
  Main stream - 2560/1920, FPS (20), 4096 max bitrate, 1x interframe
  Sub stream - 640/480, FPS (10), 256 max bitrate, 4x interframe

### Version

latest

### Frigate config file

```yaml
environment_vars: #added as some have trouble with default for old intel (like current machine)
  LIBVA_DRIVER_NAME: i965
mqtt:
  host: 192.168.86.45
  user: user
  password: password

detectors:
  cpu:  #CPU inference at around 80ms
    type: cpu
    num_threads: 2
  #coral:   #Coral inference ? Comment out CPU once I have the coral
    #type: edgetpu
    #device: usb
    
cameras:
  frontdoor:
    ffmpeg:
      hwaccel_args: preset-vaapi     
      inputs:
      - path: rtsp://user:password@192.168.86.40:554/h264Preview_01_main
        roles:
          - record
      - path: rtsp://user:password@192.168.86.40:554/h264Preview_01_sub
        roles:
          - detect #detecting with sub stream, which is fluent (lower res)
    record:
      enabled: true
      events:
        required_zones:
          - front_door
    snapshots:
      enabled: true
      required_zones:
        - front_door
    detect: #height and width of reolink sub stream, which is fluent for detection
      enabled: true    
      width: 640
      height: 480
      fps: 5
    objects:
      track:
       - person
    motion:
      mask: #stops motion from being detected in this area, better performance
       - 429,0,640,79,312,232,0,133,0,38,0,0 #mask of date/time stamp and skyline
       #- 248,347,326,545,571,473,778,484,782,301,549,297 #2nd mask if needed
    rtmp:
      enabled: false
    zones:
      front_door:  #maps out the zone so no events/snapshots are created unless they step into my area
        coordinates: 419,480,351,443,352,369,270,355,166,427,81,392,72,274,0,285,0,480,160,480
        objects:
          - person
```

### Relevant log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

I am using HAOS baremetal, with frigate add on - with intel i5 processor (HP 600 G2, 8gb ram, SSD drives) - camera is a reolink wifi doorbell. Everything else is working other than the laggy video - just installed the past 2 days.

my reolink wifi doorbell camera specs
  Main stream - 2560/1920, FPS (20), 4096 max bitrate, 1x interframe
  Sub stream - 640/480, FPS (10), 256 max bitrate, 4x interframe
