### ISSUE TITLE
[Support]: Mask editor does not work in Firefox

### ISSUE THREAD

**Issue by nagisa** [blakeblackshear/frigate#7594]
### Describe the problem you are having

When I press on the image in the Map Editor in Firefox nothing happens.

### Version

0.12.1

### Frigate config file

```yaml
cameras:
  aikstele:
    birdseye:
      enabled: false
    detect:
      enabled: true
      height: 960
      width: 1280
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/aikstele_record
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/aikstele_detect
        roles:
        - detect
    live:
      height: 960
      stream_name: aikstele_mse
    record:
      enabled: false
    snapshots:
      enabled: false
  garazas:
    birdseye:
      enabled: false
    detect:
      enabled: true
      height: 960
      width: 1280
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/garazas_record
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/garazas_detect
        roles:
        - detect
    live:
      height: 960
      stream_name: garazas_mse
    record:
      enabled: false
    snapshots:
      enabled: false
  ivaziavimas:
    birdseye:
      enabled: false
    detect:
      enabled: true
      height: 960
      width: 1280
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/ivaziavimas_record
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/ivaziavimas_detect
        roles:
        - detect
    live:
      height: 960
      stream_name: ivaziavimas_mse
    record:
      enabled: false
    snapshots:
      enabled: false
  mazoji_pieva:
    birdseye:
      enabled: false
    detect:
      enabled: true
      height: 960
      width: 1280
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/mazoji_pieva_record
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/mazoji_pieva_detect
        roles:
        - detect
    live:
      height: 960
      stream_name: mazoji_pieva_mse
    record:
      enabled: false
    snapshots:
      enabled: false
  pieva:
    birdseye:
      enabled: false
    detect:
      enabled: true
      height: 960
      width: 1280
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/pieva_record
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/pieva_detect
        roles:
        - detect
    live:
      height: 960
      stream_name: pieva_mse
    record:
      enabled: false
    snapshots:
      enabled: false
  praejimas:
    birdseye:
      enabled: false
    detect:
      enabled: true
      height: 960
      width: 1280
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/praejimas_record
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/praejimas_detect
        roles:
        - detect
    live:
      height: 960
      stream_name: praejimas_mse
    record:
      enabled: false
    snapshots:
      enabled: false
  terasa:
    birdseye:
      enabled: false
    detect:
      enabled: true
      height: 960
      width: 1280
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/terasa_record
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/terasa_detect
        roles:
        - detect
    live:
      height: 960
      stream_name: terasa_mse
    record:
      enabled: false
    snapshots:
      enabled: false
database:
  path: /var/lib/frigate/frigate.db
go2rtc:
  streams:
    aikstele_detect: ...
    aikstele_mse: ffmpeg:aikstele_record#video=copy#audio=aac
    aikstele_record: ...
    garazas_detect: ...
    garazas_mse: ffmpeg:garazas_record#video=copy#audio=aac
    garazas_record: ...
    ivaziavimas_detect: ...
    ivaziavimas_mse: ffmpeg:ivaziavimas_record#video=copy#audio=aac
    ivaziavimas_record: ...
    mazoji_pieva_detect: ...
    mazoji_pieva_mse: ffmpeg:mazoji_pieva_record#video=copy#audio=aac
    mazoji_pieva_record: ...
    pieva_detect: ...
    pieva_mse: ffmpeg:pieva_record#video=copy#audio=aac
    pieva_record: ...
    praejimas_detect: ...
    praejimas_mse: ffmpeg:praejimas_record#video=copy#audio=aac
    praejimas_record: ...
    terasa_detect: ...
    terasa_mse: ffmpeg:terasa_record#video=copy#audio=aac
    terasa_record: ...
mqtt:
  enabled: false
  host: localhost
ui:
  live_mode: mse
```

### Relevant log output

```shell
The browser console shows 


Uncaught TypeError: can't access property "reduce", e is undefined
    f https://frigate.local/assets/CameraMap-f9610b1e.js:14
    Gn https://frigate.local/assets/index-0ad73b11.js:1
    Et https://frigate.local/assets/index-0ad73b11.js:1
    ni https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    xt https://frigate.local/assets/index-0ad73b11.js:1
    xt https://frigate.local/assets/index-0ad73b11.js:1
    setTimeout handler*Xt https://frigate.local/assets/index-0ad73b11.js:1
    setState https://frigate.local/assets/index-0ad73b11.js:1
    loadComponent https://frigate.local/assets/index-0ad73b11.js:1
    promise callback*loadComponent/< https://frigate.local/assets/index-0ad73b11.js:1
    loadComponent https://frigate.local/assets/index-0ad73b11.js:1
    componentWillMount https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    ri https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    xt https://frigate.local/assets/index-0ad73b11.js:1
    xt https://frigate.local/assets/index-0ad73b11.js:1
    setTimeout handler*Xt https://frigate.local/assets/index-0ad73b11.js:1
    setState https://frigate.local/assets/index-0ad73b11.js:1
    __ https://frigate.local/assets/index-0ad73b11.js:1
    i https://frigate.local/assets/index-0ad73b11.js:1
    c https://frigate.local/assets/index-0ad73b11.js:1
    Wi https://frigate.local/assets/index-0ad73b11.js:1
    Qt https://frigate.local/assets/index-0ad73b11.js:1
    xi https://frigate.local/assets/index-0ad73b11.js:1
    setTimeout handler*n https://frigate.local/assets/index-0ad73b11.js:1
    Ei https://frigate.local/assets/index-0ad73b11.js:1
    diffed https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Vr https://frigate.local/assets/index-0ad73b11.js:1
    vn https://frigate.local/assets/index-0ad73b11.js:1
    Zt https://frigate.local/assets/index-0ad73b11.js:1
    <anonymous> https://frigate.local/assets/index-0ad73b11.js:16
```

Looking at the debugger in this function:

```
function Gn(e) {
  this.l[e.type + !1](b.event ? b.event(e) : e)
}
```

the `e` is an actual and proper click event, and `b.event` exists, so `b.event(e)` is called which leads to

```
b.event = function (e) {
  return ur &&
  (e = ur(e)),
  e.persist = $i,
  e.isPropagationStopped = Di,
  e.isDefaultPrevented = Ti,
  e.nativeEvent = e
};
```

Within this function `ur` is `undefined`. However I was not able to set a breakpoint on `var ur = b.event;` just above this function definition to find out when it is being evaluated or why it is being set to `undefined`.

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

This is a docker-less setup, but that shouldn’t matter for user interface issues?
