### ISSUE TITLE
[Detector Support]: Tensorrt high GPU utilization

### ISSUE THREAD

**Issue by MichaelH02** [blakeblackshear/frigate#7596]
### Describe the problem you are having

Hi together,

I have only recently started to deal with frigate and am therefore not yet so deep in the matter. Unfortunately, however, I can no longer get on with one or the other topic.

I would be grateful if you could help me. If my description is not understandable, please let me know. It's my first post on GitHub. ;)

I have set up Tensorrt as a detector. The detection of people works, mostly quite well. However, some times cats are detected as humans or vice versa.
However, cats are often not detected.
The utilization of the GPU is very different. This fluctuates very often between 2% and 87%. I also had to take out 3 cameras, otherwise the whole system became very unstable.
What could be the reason that the GPU has such fluctuations in utilization and cats are very rarely detected?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx.xxx.xxx.xxx
  port: 1883
  topic_prefix: frigate
  user: user
  password: "password"

database:
  path: /config/frigate.db

logger:
  default: info #debug, info, warning, error, critical
  logs:
    frigate.mqtt: debug

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    Kamera_Katzenklappe:
      - rtsp://user:password@172.19.16.110:554/stream1
      - ffmpeg:Kamera_Katzenklappe#audio=opus
    Kamera_Katzenklappe_sub:
      - rtsp://user:password@xxx.xxx.xxx.110:554/stream2
      - ffmpeg:Kamera_Katzenklappe_sub#audio=opus
    Kamera_Box:
      - rtsp://user:password@xxx.xxx.xxx.112:554/stream1
      - ffmpeg:Kamera_Box#audio=opus
    Kamera_Box_sub:
      - rtsp://user:password@xxx.xxx.xxx.112:554/stream2
      - ffmpeg:Kamera_Box_sub#audio=opus
    Kamera_Eingang:
      - rtsp://user:password@xxx.xxx.xxx.114:554/stream1
      - ffmpeg:Kamera_Eingang#audio=opus
    Kamera_Eingang_sub:
      - rtsp://user:password@xxx.xxx.xxx.114:554/stream2
      - ffmpeg:Kamera_Eingang_sub#audio=opus
    Kamera_Aufgang:
      - rtsp://user:password@xxx.xxx.xxx.116:554/stream1
      - ffmpeg:Kamera_Aufgang#audio=opus
    Kamera_Aufgang_sub:
      - rtsp://user:password@xxx.xxx.xxx.116:554/stream2
      - ffmpeg:Kamera_Aufgang_sub#audio=opus

  candidates:
    - xxx.xxx.xxx.xxx:8555
    - stun: 8555

cameras:
  Kamera_Katzenklappe:
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera_Katzenklappe
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kamera_Katzenklappe_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Kamera_Katzenklappe_sub
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - cat
    motion:
      improve_contrast: true
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - cat
  
  Kamera_Box:
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera_Box
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kamera_Box_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Kamera_Box_sub
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - cat
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - cat

  Kamera_Eingang:
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera_Eingang
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: Kamera_Eingang_sub
    detect:
      enabled: True
      width: 2304
      height: 1296
      fps: 20
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 3500
          max_area: 700000
        cat:
          min_area: 3500
          max_area: 700000
    motion:
      improve_contrast: true
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - person
          - cat

  Kamera_Aufgang:
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera_Aufgang
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: Kamera_Aufgang_sub
    detect:
      enabled: True
      width: 2304
      height: 1296
      fps: 20
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 3500
          max_area: 700000
        cat:
          min_area: 3500
          max_area: 700000
    motion:
      improve_contrast: true
      mask:
        - 715,0,881,46,853,127,906,153,1013,110,993,49,1131,0
        - 385,321,310,0,0,0,0,785,69,899,471,619
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 7
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 5
        post_capture: 8
        objects:
          - person
          - cat
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: 512mb # update for your cameras based on calculation above

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/name/frigate/config/config.yml:/config/config.yml
      - /home/name/frigate/media:/media/frigate
      - /home/name/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      #USE_FP16: False
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
```

### Relevant log output

```shell
Log files are attached in the section "Any other information that may be helpful"
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Hardware:
- CPU: i7-2600k
- GPU: Nvidia GTX970
- RAM: 8GB

Cameras:
- 2 x Tapo C310 (integrated)
- 3 x Tapo C200 (not integrated
- 2 x Tapo C100 (integrated)

Detector:
I tried already the following Tensorrt Models:
- yolov7-640
- yolov7-tiny-416
- yolov4-p5-896 (Not usable because the RAM is getting filled up and frigate crashes)
![Nvidia low](https://github.com/blakeblackshear/frigate/assets/117905406/ec52dbfd-7c6a-44fd-9234-cc07f6e476a1)
![Nvidia high](https://github.com/blakeblackshear/frigate/assets/117905406/e9fc559f-1877-4354-ae90-ef605c3c7472)

When I open the VAINFO of the GTX970, then also comes an error message, can this be related?
{"return_code":3,"stderr":"error:XDG_RUNTIME_DIRisinvalidornotsetintheenvironment.nerror:can'tconnecttoXserver!nlibvainfo:VA-APIversion1.17.0nlibvainfo:Tryingtoopen/usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.sonlibvainfo:va_openDriver()returns-1nvaInitializefailedwitherrorcode-1(unknownlibvaerror),exit","stdout":""}

I have also attached the Log files:
[Frigate Log.txt](https://github.com/blakeblackshear/frigate/files/12453714/Frigate.Log.txt)
[Go2rtc Log.txt](https://github.com/blakeblackshear/frigate/files/12453717/Go2rtc.Log.txt)
