### ISSUE TITLE
[Config Support]: Motion detection extension

### ISSUE THREAD

**Issue by PovilasID** [blakeblackshear/frigate#7602]
### Describe the problem you are having

If something stops moving for a short period of time frigate quite quickly registers them as not moving and stops recording if recording mode is set to `motion`.
I had a couple instances when deer just looked at the camera and boom dispersed... or a man that was occluded by a bush a bit suddenly was no longer recorded.
So... Drax was right, you can turn invisible if you stand still.
Some of my problems can be addressed increasing motion `threshold` but not eliminated
I switched to continues recording, however I would love an opportunity to tune how much is recorded after motion is registered aka a bit of a margin.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
cameras:
  # # Stable detection
  door:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.1:554/Streaming/Channels/101
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 3
        # mode: motion # Keeps only motion parts in an hour
        mode: all
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1920
      height: 1080
      max_disappeared: 50
    objects:
      track:
        - person
        - car
        - bicycle
    motion:
      threshold: 20 # when recording only motion allows to tune how little/much motion  
      mask:
        - 0,1080,338,1080,315,680,0,495
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        objects:
          person: 15
    zones:
      sodas:
        coordinates: 1670,351,1920,1080,0,1080,0,87
```

### Relevant log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
