### ISSUE TITLE
[HW Accel Support]: Debian BullsEye with Intel Core i5-12400 Desktop Processor

### ISSUE THREAD

**Issue by thinkloop** [blakeblackshear/frigate#7605]
### Describe the problem you are having

I haven't been able to setup HW acceleration on my system:

- Debian BullsEye
- Intel Core i5-12400 Desktop Processor 
- Coral M.2 TPU
- no GPU

I tried both, `preset-vaapi`, and `preset-intel-qsv-h264`, but all cameras error out:

![image](https://github.com/blakeblackshear/frigate/assets/118814/1931c924-118f-4a3b-b225-5dac73afb354)

But in the "system" tab of the web-ui the message got upgraded to:

![image](https://github.com/blakeblackshear/frigate/assets/118814/6c200faf-b093-4a6b-ad12-4c1f57d29b20)

I have installed `intel-media-va-driver-non-free`:

![image](https://github.com/blakeblackshear/frigate/assets/118814/61f48a1a-0666-4c04-8f0f-3cf7e860788d)

I have included all the relevant config files below.

I am at a loss how to proceed. Should I verify that the intel drivers `intel-media-va-driver-non-free` are in use and installed correctly? Is there anything else anyone can recommend I try?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: None
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  #experimental_ui: False

database:
  path: /db/frigate.db
  
mqtt:
  host: nas.subdomain.domain.com
  user: yyy
  password: xxx
  port: 1883

detectors:
  coral1:
    type: edgetpu
    device: pci:0
    
ffmpeg:
  hwaccel_args: preset-vaapi

  # enable audio
  output_args: 
    record: preset-record-generic-audio-aac
    
detect:
  enabled: true
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 720
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 480
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 55
  # mqtt_off_delay: 10

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
  
record:
  enabled: true
  retain:
    days: 14
    mode: all  
  events:
    # Optional: Number of seconds before the event to include 
    pre_capture: 3
    # Optional: Number of seconds after the event to include 
    post_capture: 3
    # Optional: Objects to save recordings for. (default: all tracked objects)
    #objects:
    #  - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 60
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 365       
        
snapshots:
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true

rtmp:
  enabled: false

#restream:
  # Optional: Enable the restream (default: True)
#  enabled: true
  
timestamp_style:
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%Y/%m/%d %H:%M:%S"
  
go2rtc:
  webrtc:
    candidates:
      - nas.subdomain.domain.com:8555
      - stun:8555
  rtsp:
    username: "yyy"
    password: "xxx"      
  streams:
    lightwall:
      - http://lightwall.cams.subdomain.domain.com/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=yyy&password=xxx
    lightwall-sub:
      - http://lightwall.cams.subdomain.domain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=yyy&password=xxx      
#    driveway:
#      - rtsp://yyy:xxx@driveway.cams.subdomain.domain.com:554/stream0
#    driveway-sub:
#      - rtsp://yyy:xxx@driveway.cams.subdomain.domain.com:554/stream1

    doorbell:
      - http://doorbell.cams.subdomain.domain.com/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=yyy&password=xxx
    doorbell-sub:
      - http://doorbell.cams.subdomain.domain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=yyy&password=xxx      
      
    porch_left:
      - rtsp://porch-left.cams.subdomain.domain.com:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    porch_left-sub:
      - rtsp://porch-left.cams.subdomain.domain.com:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      
#    porch_right:
#      - rtsp://yyy:xxx@porch-right.cams.subdomain.domain.com:554/stream0
#    porch_right-sub:
#      - rtsp://yyy:xxx@porch-right.cams.subdomain.domain.com:554/stream1
      
    # former-porch_left:
      # - rtsp://yyy:xxx@porch-left.cams.subdomain.domain.com:554/stream0
    # former-porch_left-sub:
      # - rtsp://yyy:xxx@porch-left.cams.subdomain.domain.com:554/stream1

#    package:
#      - rtsp://admin:xxx123@package.cams.subdomain.domain.com:554/user=admin_password=xxx123_channel=1_stream=0.sdp?real_stream
#    package-sub:
#      - rtsp://admin:xxx123@package.cams.subdomain.domain.com:554/user=admin_password=xxx123_channel=1_stream=1.sdp?real_stream      
#    backyard:
#      - rtsp://yyy:xxx@backyard.cams.subdomain.domain.com:554/stream0
#    backyard-sub:
#      - rtsp://yyy:xxx@backyard.cams.subdomain.domain.com:554/stream1      
 #   baby:
 #     - rtsp://yyy:xxx@baby.cams.subdomain.domain.com:8554/profile0
#    baby-sub:
#      - rtsp://yyy:xxx@baby.cams.subdomain.domain.com:8554/profile1 
    # mini:
      # - rtsp://yyy:xxx@mini.cams.subdomain.domain.com:8554/profile0
    # mini-sub:
     # - rtsp://yyy:xxx@mini.cams.subdomain.domain.com:8554/profile1
    basement-front:
      - rtsp://yyy:xxx@basement-front.cams.subdomain.domain.com:554/cam/realmonitor?channel=1&subtype=0
    basement-front-sub:
      - rtsp://yyy:xxx@basement-front.cams.subdomain.domain.com:554/cam/realmonitor?channel=1&subtype=1          
    basement-back:
      - rtsp://yyy:xxx@basement-back.cams.subdomain.domain.com:554/cam/realmonitor?channel=1&subtype=0
    basement-back-sub:
      - rtsp://yyy:xxx@basement-back.cams.subdomain.domain.com:554/cam/realmonitor?channel=1&subtype=1     

cameras:
  lightwall:
    ffmpeg:   
      #input_args: preset-http-reolink
      inputs:
        - path: rtsp://127.0.0.1:8554/lightwall
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lightwall-sub
          roles:
            - detect
                           
    detect:
      width: 640
      height: 360       
      fps: 7
    
    ui:
      order: 1
      
  doorbell:
    ffmpeg:   
      #input_args: preset-http-reolink
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell-sub
          roles:
            - detect
                           
    detect:
      width: 640
      height: 480       
      fps: 7

    ui:
      order: 2   
      
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://yyy:xxx@driveway.cams.subdomain.domain.com:554/stream0
          roles:
            - record
        - path: rtsp://yyy:xxx@driveway.cams.subdomain.domain.com:554/stream1
          roles:
            - detect         
    detect:
      width: 640
      height: 352
      fps: 5            
    ui:
      order: 3
      
  porch_left: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch_left
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porch_left-sub
          roles:
            - detect       
    detect:
      width: 704
      height: 480            
    ui:
      order: 4

  porch_right: 
    ffmpeg:
      inputs:
        - path: rtsp://yyy:xxx@porch-right.cams.subdomain.domain.com:554/stream0
          roles:
            - record
        - path: rtsp://yyy:xxx@porch-right.cams.subdomain.domain.com:554/stream1
          roles:
            - detect       
    detect:
      width: 720
      height: 480            
      fps: 5       
    ui:
      order: 5
      
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://yyy:xxx@backyard.cams.subdomain.domain.com:554/stream0
          roles:
            - record
        - path: rtsp://yyy:xxx@backyard.cams.subdomain.domain.com:554/stream1
          roles:
            - detect
    ui:
      order: 7  

#  baby:
 #   ffmpeg:
 #     inputs:
 #       - path: rtsp://127.0.0.1:8554/baby
 #         roles:
 #           - record
 #       - path: rtsp://127.0.0.1:8554/baby-sub
 #         roles:
 #           - detect
#    ui:
 #     order: 9

  mini:
    ffmpeg:
      inputs:
        - path: rtsp://yyy:xxx@mini.cams.subdomain.domain.com:8554/profile0
          roles:
            - record
        - path: rtsp://yyy:xxx@mini.cams.subdomain.domain.com:8554/profile1
          roles:
            - detect
    ui:
      order: 8

      
#  former-porch-left:
#    ffmpeg:
#      inputs:
#        - path: rtsp://yyy:xxx@former-porch-left.cams.subdomain.domain.com:554/stream0
#          roles:
#            - record
#        - path: rtsp://yyy:xxx@former-porch-left.cams.subdomain.domain.com:554/stream1
#          roles:
#            - detect
#    ui:
#      order: 9
      
  basement-front:
    ffmpeg:      
      inputs:
        - path: rtsp://127.0.0.1:8554/basement-front
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/basement-front-sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
    ui:
      order: 10
      
  # basement-front-new:
    # ffmpeg:     
      # inputs:
        # - path: rtsp://127.0.0.1:8554/basement-front-new
          # roles:
            # - record
        # - path: rtsp://127.0.0.1:8554/basement-front-new-sub
          # roles:
            # - detect
    # detect:
      # width: 640
      # height: 480
    # ui:
      # order: 11      
      
  basement-back:
    ffmpeg:    
      inputs:
        - path: rtsp://127.0.0.1:8554/basement-back
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/basement-back-sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
    ui:
      order: 11
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    #network_mode: host
    privileged: true # this may not be necessary for all setups
    shm_size: "2048mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-data/frigate/config.yml:/config/config.yml
      - /mnt/docker-data/frigate/db:/db
      - /mnt/docker-data/frigate/cache:/tmp/cache # faster drive and data doesn't need to be backed up
      - /mnt/frigate/recordings:/media/frigate/recordings
      - /mnt/frigate/clips:/media/frigate/clips
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    ports:
      - "5000:5000" # web ui
      - "8554:8554" # RTSP feeds *from* frigate
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_USER=yyy
      - FRIGATE_RTSP_PASSWORD=xxx
      - FRIGATE_MQTT_USER=yyy
      - FRIGATE_MQTT_PASSWORD=xxx

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    #network_mode: host
    volumes:
      - /mnt/docker-data/mosquitto/config/:/mosquitto/config/
      - /mnt/docker-data/mosquitto/data/:/mosquitto/data/
      - /mnt/docker-data/mosquitto/log/:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001
```

### Relevant log output

```shell
frigate    | 2023-08-28 18:58:20.984915974  [2023-08-28 18:58:20] ffmpeg.basement-front.detect   ERROR   : Error parsing options for output file vaapi.
frigate    | 2023-08-28 18:58:20.984917541  [2023-08-28 18:58:20] ffmpeg.basement-front.detect   ERROR   : Error opening output files: Invalid argument
frigate    | 2023-08-28 18:58:20.987780005  [2023-08-28 18:58:20] ffmpeg.basement-front.record   ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
frigate    | 2023-08-28 18:58:20.990667860  [2023-08-28 18:58:20] ffmpeg.basement-back.record    ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
frigate    | 2023-08-28 18:58:20.990748218  [2023-08-28 18:58:20] ffmpeg.basement-front.record   ERROR   : Error parsing options for output file vaapi.
frigate    | 2023-08-28 18:58:20.990880461  [2023-08-28 18:58:20] ffmpeg.basement-back.record    ERROR   : Error parsing options for output file vaapi.
frigate    | 2023-08-28 18:58:20.991119175  [2023-08-28 18:58:20] ffmpeg.basement-back.record    ERROR   : Error opening output files: Invalid argument
frigate    | 2023-08-28 18:58:20.991121916  [2023-08-28 18:58:20] ffmpeg.basement-front.record   ERROR   : Error opening output files: Invalid argument
frigate    | 2023-08-28 18:58:20.991123593  [2023-08-28 18:58:20] watchdog.basement-back         INFO    : Terminating the existing ffmpeg process...
frigate    | 2023-08-28 18:58:20.991125032  [2023-08-28 18:58:20] watchdog.basement-front        INFO    : Terminating the existing ffmpeg process...
frigate    | 2023-08-28 18:58:20.991126320  [2023-08-28 18:58:20] watchdog.basement-front        INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2023-08-28 18:58:20.991127594  [2023-08-28 18:58:20] watchdog.basement-back         INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2023-08-28 18:58:22.516056563  [2023-08-28 18:58:22] frigate.video                  ERROR   : porch_right: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:22.516663285  [2023-08-28 18:58:22] frigate.video                  ERROR   : porch_right: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:22.516667273  [2023-08-28 18:58:22] frigate.video                  ERROR   : porch_right: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-28 18:58:24.167991511  [2023-08-28 18:58:24] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:24.167995814  [2023-08-28 18:58:24] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-28 18:58:24.174717760  [2023-08-28 18:58:24] frigate.video                  ERROR   : lightwall: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:24.175060372  [2023-08-28 18:58:24] frigate.video                  ERROR   : lightwall: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:24.175165679  [2023-08-28 18:58:24] frigate.video                  ERROR   : lightwall: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-28 18:58:25.515017540  [2023-08-28 18:58:25] frigate.video                  ERROR   : porch_left: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:25.515189424  [2023-08-28 18:58:25] frigate.video                  ERROR   : porch_left: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-28 18:58:25.524068770  [2023-08-28 18:58:25] frigate.video                  ERROR   : mini: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:25.524252276  [2023-08-28 18:58:25] frigate.video                  ERROR   : mini: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-28 18:58:25.635971674  [2023-08-28 18:58:25] frigate.video                  ERROR   : basement-front: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:25.635975640  [2023-08-28 18:58:25] frigate.video                  ERROR   : basement-front: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-28 18:58:25.683640788  [2023-08-28 18:58:25] frigate.video                  ERROR   : basement-back: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:25.683729053  [2023-08-28 18:58:25] frigate.video                  ERROR   : basement-back: ffmpeg process is not running. exiting capture thread...
^Xfrigate    | 2023-08-28 18:58:25.892433183  [2023-08-28 18:58:25] frigate.video                  ERROR   : backyard: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:25.892760545  [2023-08-28 18:58:25] frigate.video                  ERROR   : backyard: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-08-28 18:58:26.008036279  [2023-08-28 18:58:26] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
frigate    | 2023-08-28 18:58:26.008369037  [2023-08-28 18:58:26] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.6-0+deb11u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x56398b0e0a00] max delay reached. need to consume packet
[rtsp @ 0x56398b0e0a00] RTP: missed 68 packets
[rtsp @ 0x56398b0e0a00] max delay reached. need to consume packet
[rtsp @ 0x56398b0e0a00] RTP: missed 99 packets
[h264 @ 0x56398b0e5680] concealing 27382 DC, 27382 AC, 27382 MV errors in I frame
Input #0, rtsp, from 'rtsp://baz:bizwiz@driveway.cams.turgeon.memehouse.com:554/stream0':
  Metadata:
    title           : RTSP/RTP stream from icamra ipc
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2144, 20 fps, 20 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

various: dahua, reolink, generic amazon brand
