### ISSUE TITLE
[Config Support]: Events still being detected out of my zone

### ISSUE THREAD

**Issue by asteriqz** [blakeblackshear/frigate#7616]
### Describe the problem you are having

Hello,

I believe I have setup my zones according to the documentation although I am still getting events for people/cars outside of my zone.

What have I done wrong with my configuration? (driveway_area).

![image](https://github.com/blakeblackshear/frigate/assets/20625187/7a6158b4-1a5f-4013-b661-cb97a53f769d)

Thank you for the support and active development.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: a0d7b954-emqx
  user: frigate
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: -tag:v hvc1

database:
  path: /config/frigate.db
  
go2rtc:
  streams:
    username: "admin"
    password: "xxx"
    driveway: 
      - rtsp://admin:xxx@192.168.0.211:554/h265Preview_01_main
      - "ffmpeg:driveway#video=h264#hardware"
    backyard:
      - rtsp://admin:xxx@192.168.0.210:554/h265Preview_01_main
      - "ffmpeg:backyard#video=h264#hardware"
    # sideyard:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.104:554/h265Preview_01_main
    #  - "ffmpeg:sideyard#video=h264#hardware"
    #doorbell:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.108:554/h264Preview_01_main
    #viewcam:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.105:554/h265Preview_01_main
    #  - "ffmpeg:viewcam#video=h264#hardware"

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
        - car
    zones:
     driveway_area:
      coordinates: 4096,1536,4096,615,2860,530,2056,482,1597,681,130,1536

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
    zones:
     backyard_area:
      coordinates: 0,1536,4096,1536,4096,0,0,0
    motion:
       mask:
        - 2024,55,1884,245,1812,408,1578,526,1300,570,898,501,892,391,675,388,667,223,881,182

record:
 enabled: True
 retain:
  days: 7
  mode: motion
 events:
  required_zones:
    - driveway_area
    - backyard_area
  retain:
   default: 14
   mode: active_objects
snapshots:
  enabled: True

rtmp:
  enabled: false

birdseye:
  enabled: True
  mode: continuous
  restream: False
  width: 1920
  height: 1080
  quality: 4
```

### Relevant log output

```shell
No logs required.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
