### ISSUE TITLE
[Camera Support]:   container fails during startup

### ISSUE THREAD

**Issue by cresch06** [blakeblackshear/frigate#7622]
### Describe the problem you are having

I want to integrate my EZVIZ camera into frigate. Starting with a minimal configuration container fails during startup.

Am I missing any settings in configuration?

I can access the camera with motioneye using rtsp://admin:passwort@192.168.1.104:554/h264_stream

### Version

stable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  EZVIZ_Haustuer_01: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:passwort@192.168.1.104:554/h264_stream # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

### Relevant log output

```shell
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | 2023-08-30 09:59:49.765028842  [INFO] Preparing go2rtc config...
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | 2023-08-30 09:59:49.795089885  [INFO] Starting NGINX...
frigate    | 2023-08-30 09:59:49.813995144  [INFO] Starting Frigate...
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2023-08-30 09:59:50.749894979  [INFO] Starting go2rtc...
frigate    | 2023-08-30 09:59:51.221926744  09:59:51.221 INF go2rtc version 1.2.0 linux/amd64
frigate    | 2023-08-30 09:59:51.224422753  09:59:51.224 INF [api] listen addr=:1984
frigate    | 2023-08-30 09:59:51.226865730  09:59:51.226 INF [rtsp] listen addr=:8554
frigate    | 2023-08-30 09:59:51.229304994  09:59:51.229 INF [srtp] listen addr=:8443
frigate    | 2023-08-30 09:59:51.234051103  09:59:51.233 INF [webrtc] listen addr=:8555
frigate    | 2023-08-30 09:59:53.994587924  Fatal Python error: Illegal instruction
frigate    | 2023-08-30 09:59:53.994609071
frigate    | 2023-08-30 09:59:53.994625748  Current thread 0x00007f7c51a4c740 (most recent call first):
frigate    | 2023-08-30 09:59:53.994642147    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.994656128    File "<frozen importlib._bootstrap_external>", line 1108 in create_module
frigate    | 2023-08-30 09:59:53.994753564    File "<frozen importlib._bootstrap>", line 565 in module_from_spec
frigate    | 2023-08-30 09:59:53.994766733    File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
frigate    | 2023-08-30 09:59:53.994778343    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.994789510    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.994824767    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.994860870    File "<frozen importlib._bootstrap>", line 1058 in _handle_fromlist
frigate    | 2023-08-30 09:59:53.994904564    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 41 in <module>
frigate    | 2023-08-30 09:59:53.994957477    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.995010519    File "<frozen importlib._bootstrap_external>", line 790 in exec_module
frigate    | 2023-08-30 09:59:53.995062342    File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
frigate    | 2023-08-30 09:59:53.995112734    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.995186967    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.995224561    File "/opt/frigate/frigate/detectors/plugins/cpu_tfl.py", line 10 in <module>
frigate    | 2023-08-30 09:59:53.995268182    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.995329806    File "<frozen importlib._bootstrap_external>", line 790 in exec_module
frigate    | 2023-08-30 09:59:53.995372755    File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
frigate    | 2023-08-30 09:59:53.995433686    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.995476890    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.995519670    File "<frozen importlib._bootstrap>", line 1030 in _gcd_import
frigate    | 2023-08-30 09:59:53.995582208    File "/usr/lib/python3.9/importlib/__init__.py", line 127 in import_module
frigate    | 2023-08-30 09:59:53.995643102    File "/opt/frigate/frigate/detectors/detector_types.py", line 25 in <module>
frigate    | 2023-08-30 09:59:53.995704462    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.995754445    File "<frozen importlib._bootstrap_external>", line 790 in exec_module
frigate    | 2023-08-30 09:59:53.995797367    File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
frigate    | 2023-08-30 09:59:53.995858541    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.995900879    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.995959044    File "/opt/frigate/frigate/detectors/__init__.py", line 9 in <module>
frigate    | 2023-08-30 09:59:53.996010735    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.996072151    File "<frozen importlib._bootstrap_external>", line 790 in exec_module
frigate    | 2023-08-30 09:59:53.996115760    File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
frigate    | 2023-08-30 09:59:53.996175168    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.996225296    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.996259009    File "/opt/frigate/frigate/config.py", line 36 in <module>
frigate    | 2023-08-30 09:59:53.996319668    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.996372446    File "<frozen importlib._bootstrap_external>", line 790 in exec_module
frigate    | 2023-08-30 09:59:53.996458931    File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
frigate    | 2023-08-30 09:59:53.996502722    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.996536631    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.996570104    File "/opt/frigate/frigate/comms/dispatcher.py", line 9 in <module>
frigate    | 2023-08-30 09:59:53.996613655    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.996673126    File "<frozen importlib._bootstrap_external>", line 790 in exec_module
frigate    | 2023-08-30 09:59:53.996715891    File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
frigate    | 2023-08-30 09:59:53.996775835    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.996818559    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.996869286    File "/opt/frigate/frigate/app.py", line 17 in <module>
frigate    | 2023-08-30 09:59:53.996928961    File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
frigate    | 2023-08-30 09:59:53.996981302    File "<frozen importlib._bootstrap_external>", line 790 in exec_module
frigate    | 2023-08-30 09:59:53.997058192    File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
frigate    | 2023-08-30 09:59:53.997110446    File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
frigate    | 2023-08-30 09:59:53.997161231    File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
frigate    | 2023-08-30 09:59:53.997211257    File "/opt/frigate/frigate/__main__.py", line 9 in <module>
frigate    | 2023-08-30 09:59:53.997252434    File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
frigate    | 2023-08-30 09:59:53.997302431    File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
frigate    | 2023-08-30 09:59:54.526971896  [INFO] Service Frigate exited with code 256 (by signal 4)
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | s6-rc: info: service legacy-services successfully stopped
frigate    | s6-rc: info: service nginx: stopping
frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate    | 2023-08-30 09:59:54.577920186  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate    | 2023-08-30 09:59:54.639882353  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate    | s6-rc: info: service nginx successfully stopped
frigate    | s6-rc: info: service nginx-log: stopping
frigate    | s6-rc: info: service frigate: stopping
frigate    | s6-rc: info: service nginx-log successfully stopped
frigate    | s6-rc: info: service frigate successfully stopped
frigate    | s6-rc: info: service go2rtc: stopping
frigate    | s6-rc: info: service frigate-log: stopping
frigate    | 2023-08-30 09:59:54.661746700  exit OK
frigate    | s6-rc: info: service frigate-log successfully stopped
frigate    | 2023-08-30 09:59:54.678955625  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate    | s6-rc: info: service go2rtc successfully stopped
frigate    | s6-rc: info: service go2rtc-log: stopping
frigate    | s6-rc: info: service go2rtc-log successfully stopped
frigate    | s6-rc: info: service log-prepare: stopping
frigate    | s6-rc: info: service s6rc-fdholder: stopping
frigate    | s6-rc: info: service log-prepare successfully stopped
frigate    | s6-rc: info: service legacy-cont-init: stopping
frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate    | s6-rc: info: service legacy-cont-init successfully stopped
frigate    | s6-rc: info: service fix-attrs: stopping
frigate    | s6-rc: info: service fix-attrs successfully stopped
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:passwort@192.168.1.104:554/h264_stream
ffprobe version 4.4.2-0ubuntu0.22.04.1+esm1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1+esm1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x55e4a34bfd00] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://admin:passwort@192.168.1.104:554/h264_stream':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 25 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

EZVIZ CTQ3W (CS-CV310)

### Any other information that may be helpful

**docker-compose.yaml**

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "passwd"
```
