### ISSUE TITLE
[Support]: WebUI unable to show valid recordings or clips.

### ISSUE THREAD

**Issue by TheJambo** [blakeblackshear/frigate#7624]
### Describe the problem you are having

WebUI unable to show valid recordings or clips. The 10s segments are completely viewable via VLC or any other player and not found a single corrupt file yet, but nothing will load via the webUI.

Tried both direct connection to the camera via go2rtc as recommended in docs, (now commented out)
and currently trying an RTSP stream from neolink to handle the reolink-specific behaviours. Both methods provide great footage but unreadable on the UI.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.17
  user: Frigate
  password: "REDACTED"
detectors:
  coral:
    type: edgetpu
    device: usb
# go2rtc:
 # streams:
 #     Outdoor: 
  #     - http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=REDACTED
  #     - "ffmpeg:reolink#audio=opus"

  #     FrontDoor: 
  #     - "ffmpeg:http://192.168.0.179/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=REDACTED#video=copy#audio=copy#audio=opus"

  #     LivingRoom: 
  #     - "ffmpeg:http://192.168.0.162/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=REDACTED#video=copy#audio=copy#audio=opus"

record:
  # Optional: Enable recording (default: shown below)
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    days: 10
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    mode: all
  # Optional: Event recording settings
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args: 
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1
live:
  height: 1080
  quality: 8

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  fps: 5
  enabled: True
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
cameras:
  FrontDoor: 
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://192.168.0.17:8554/FrontDoor
          roles:
            - rtmp
            - record
    record:
      enabled: True

  LivingRoom: 
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://192.168.0.17:8554/LivingRoom
          roles:
            - rtmp
            - record
    record:
      enabled: True

  Outdoor: 
    zones:
      drivewayEntrance:
        coordinates: 1671,603,1524,453,517,507,466,598
        objects:
          - person
      driveway:
        coordinates: 1745,597,1871,1080,0,1080,0,617
        objects:
          - person
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://192.168.0.17:8554/Outdoor
          roles:
            - detect
            - rtmp
            - record
    record:
      enabled: True

#  Hallway: 
#    ffmpeg:
#      hwaccel_args: -c:v h264_cuvid
#      input_args: preset-rtsp-restream
#      inputs:
#        - path: rtsp://127.0.0.1:8554/Hallway
#          roles:
#            - detect
#            - rtmp
#            - record
#    record:
#      enabled: True
```

### Relevant log output

```shell
On the "Clips" page, when attempting to load a clip, this appears in the Frigate Log:

2023-08-30 12:33:17.353544049  2023/08/30 12:33:17 [error] 153#153: *895 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.0.22, server: , request: "GET /api/recordings/storage HTTP/1.1", upstream: "http://127.0.0.1:5001/recordings/storage", host: "192.168.0.17:5000", referrer: "http://192.168.0.17:5000/storage"

When opening the "Recordings" page of a camera, this appears in the Frigate Log:

2023-08-30 12:43:03.061732373  2023/08/30 12:43:03 [error] 165#165: *1061 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.0.22, server: , request: "GET /api/Outdoor/recordings/summary?timezone=Europe%2FLondon HTTP/1.1", upstream: "http://127.0.0.1:5001/Outdoor/recordings/summary?timezone=Europe%2FLondon", host: "192.168.0.17:5000", referrer: "http://192.168.0.17:5000/recording/Outdoor"
2023-08-30 12:43:03.061799141  192.168.0.22 - - [30/Aug/2023:12:43:03 +0100] "GET /api/Outdoor/recordings/summary?timezone=Europe%2FLondon HTTP/1.1" 504 569 "http://192.168.0.17:5000/recording/Outdoor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
2023-08-30 12:43:03.062877977  2023/08/30 12:43:03 [error] 165#165: *1062 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.0.22, server: , request: "GET /api/Outdoor/recordings?before=1693396799&after=1693393200 HTTP/1.1", upstream: "http://127.0.0.1:5001/Outdoor/recordings?before=1693396799&after=1693393200", host: "192.168.0.17:5000", referrer: "http://192.168.0.17:5000/recording/Outdoor"
2023-08-30 12:43:03.062945863  192.168.0.22 - - [30/Aug/2023:12:43:03 +0100] "GET /api/Outdoor/recordings?before=1693396799&after=1693393200 HTTP/1.1" 504 569 "http://192.168.0.17:5000/recording/Outdoor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1920
FPS: Unknown

Audio:

Codec: PCM signed 16-bit big-endian
```

### Frigate stats

```json
amera_fps":5.1,"capture_pid":597,"detection_enabled":1,"detection_fps":3.4,"ffmpeg_pid":7315,"pid":591,"process_fps":5.1,"skipped_fps":0.0},"LivingRoom":{"camera_fps":5.0,"capture_pid":600,"detection_enabled":1,"detection_fps":1.3,"ffmpeg_pid":794,"pid":593,"process_fps":4.9,"skipped_fps":0.0},"Outdoor":{"camera_fps":5.0,"capture_pid":603,"detection_enabled":1,"detection_fps":6.9,"ffmpeg_pid":608,"pid":596,"process_fps":4.9,"skipped_fps":0.0},"cpu_usages":{"1":{"cpu":"0.0","mem":"0.0"},"102":{"cpu":"0.0","mem":"0.0"},"107":{"cpu":"0.0","mem":"0.1"},"140":{"cpu":"0.0","mem":"0.1"},"141":{"cpu":"0.0","mem":"0.1"},"143":{"cpu":"0.3","mem":"0.1"},"153":{"cpu":"0.0","mem":"0.1"},"165":{"cpu":"0.0","mem":"0.1"},"177":{"cpu":"0.0","mem":"0.0"},"197":{"cpu":"0.0","mem":"0.0"},"21":{"cpu":"0.0","mem":"0.0"},"227":{"cpu":"0.0","mem":"0.1"},"23":{"cpu":"0.0","mem":"0.0"},"267":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"322":{"cpu":"0.0","mem":"0.0"},"328":{"cpu":"0.0","mem":"0.0"},"33":{"cpu":"0.0","mem":"0.0"},"34":{"cpu":"0.0","mem":"0.0"},"35":{"cpu":"0.0","mem":"0.0"},"36":{"cpu":"0.0","mem":"0.0"},"37":{"cpu":"0.0","mem":"0.0"},"38":{"cpu":"0.0","mem":"0.0"},"47":{"cpu":"0.0","mem":"0.0"},"48":{"cpu":"0.0","mem":"0.0"},"577":{"cpu":"0.0","mem":"1.9"},"583":{"cpu":"0.0","mem":"0.1"},"584":{"cpu":"3.0","mem":"2.1"},"587":{"cpu":"1.7","mem":"2.2"},"590":{"cpu":"0.0","mem":"0.1"},"591":{"cpu":"3.0","mem":"2.4"},"593":{"cpu":"6.0","mem":"2.3"},"595":{"cpu":"0.0","mem":"0.1"},"596":{"cpu":"5.6","mem":"2.4"},"597":{"cpu":"2.0","mem":"2.1"},"600":{"cpu":"2.0","mem":"2.1"},"603":{"cpu":"2.0","mem":"2.0"},"608":{"cpu":"6.3","mem":"2.5"},"610":{"cpu":"7.3","mem":"0.8"},"614":{"cpu":"0.0","mem":"0.1"},"7315":{"cpu":"7.0","mem":"2.6"},"794":{"cpu":"2.3","mem":"2.7"},"8428":{"cpu":"0.0","mem":"0.0"},"8448":{"cpu":"13.3","mem":"0.3"},"8450":{"cpu":"0.0","mem":"0.0"},"8455":{"cpu":"0.3","mem":"0.0"},"86":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"0.0","mem":"0.0"},"92":{"cpu":"0.0","mem":"0.2"},"98":{"cpu":"3.0","mem":"5.0"},"Tasks:":{"cpu":"stopped,","mem":"0.0"},"top":{"cpu":"average:","mem":"0.0"}},"detection_fps":11.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.71,"pid":584}},"gpu_usages":{"NVIDIA GeForce RTX 2080 SUPER":{"gpu":"1 %","mem":"14.1 %"}},"service":{"last_updated":1693395460,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":5357.6,"mount_type":"tmpfs","total":5368.7,"used":11.1},"/media/frigate/clips":{"free":1853901.8,"mount_type":"fuse.shfs","total":11998001.6,"used":10144099.8},"/media/frigate/recordings":{"free":1853901.8,"mount_type":"fuse.shfs","total":11998001.6,"used":10144099.8},"/tmp/cache":{"free":13234.7,"mount_type":"rootfs","total":14648.6,"used":1414.0}},"temperatures":{},"uptime":5478,"version":"0.12.1-367d724"}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink E1 Zoom Outdoor
