### ISSUE TITLE
[Support]: not being able to playing recordings successfully from vlc or videojs

### ISSUE THREAD

**Issue by sgrossiP** [blakeblackshear/frigate#7633]
### Describe the problem you are having

Hello. i have no idea what is going on here :) 
both audio and video feel lagged using vlc or a custom videojs from an angular app using this example url

http://0.0.0.0:5000/vod/2023-08/31/01/test/America,Buenos_Aires/master.m3u8
or

http://0.0.0.0:5000/vod/2023-08/31/01/test/America,Buenos_Aires/index.m3u8

but when played from frigate in this url http://0.0.0.0:5000/recording/testdos/2023-08-31/01 everything is working like a charm
how did you do it?

### Version

0.12.1-157b160

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.243
  user: publico
  password: 12sgrossi34
record:
  enabled: True
  retain_days: 3
  events:
    retain:
      default: 3
snapshots:
  enabled: True
  bounding_box: True
  crop: false
  retain:
    default: 3
cameras:
  test:
    ffmpeg:
      output_args:
          record: preset-record-generic-audio-aac-5s
      inputs:
        - path: rtsp://publico:12sgrossi34@sgg.ddns.net:666/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
      hwaccel_args: preset-vaapi
    rtmp:
      enabled: False
    detect:
        enabled: False
  testdos:
    ffmpeg:
      output_args:
          record: preset-record-generic-audio-aac-2s
      inputs:
        - path: rtsp://publico:12sgrossi34@sgg.ddns.net:33162/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
      hwaccel_args: preset-vaapi
    rtmp:
      enabled: False
    detect:
        enabled: False
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 25/1

Audio:

Codec: PCM mu-law / G.711 mu-law
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"138":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"160":{"cpu":"0.0","mem":"0.0"},"189":{"cpu":"0.0","mem":"0.0"},"222":{"cpu":"0.0","mem":"0.1"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"426":{"cpu":"0.0","mem":"0.3"},"432":{"cpu":"0.0","mem":"0.0"},"433":{"cpu":"0.0","mem":"0.3"},"435":{"cpu":"0.3","mem":"0.3"},"438":{"cpu":"0.3","mem":"0.3"},"439":{"cpu":"0.0","mem":"0.1"},"440":{"cpu":"0.3","mem":"0.3"},"441":{"cpu":"0.0","mem":"0.1"},"442":{"cpu":"1.0","mem":"0.3"},"445":{"cpu":"1.0","mem":"0.3"},"447":{"cpu":"3.3","mem":"0.2"},"450":{"cpu":"0.0","mem":"0.1"},"451":{"cpu":"3.0","mem":"0.2"},"7425":{"cpu":"0.0","mem":"0.0"},"7449":{"cpu":"0.0","mem":"0.0"},"7462":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.1"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"0.7","mem":"0.6"},"MiB":{"cpu":"17074.0","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"0.68,"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":433}},"gpu_usages":{"intel-vaapi":{"gpu":"21.16 %","mem":"- %"}},"service":{"last_updated":1693458354,"latest_version":"unknown","storage":{"/dev/shm":{"free":63.7,"mount_type":"tmpfs","total":67.1,"used":3.4},"/media/frigate/clips":{"free":977013.9,"mount_type":"fuseblk","total":1000203.1,"used":23189.1},"/media/frigate/recordings":{"free":977013.9,"mount_type":"fuseblk","total":1000203.1,"used":23189.1},"/tmp/cache":{"free":994.3,"mount_type":"tmpfs","total":1000.0,"used":5.7}},"temperatures":{},"uptime":3745,"version":"0.12.1-367d724"},"test":{"camera_fps":5.1,"capture_pid":442,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":447,"pid":438,"process_fps":5.1,"skipped_fps":0.0},"testdos":{"camera_fps":5.1,"capture_pid":445,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":451,"pid":440,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision DS-2CV1021G0-IDW1

### Any other information that may be helpful

stable connection
