### ISSUE TITLE
Frigate docker compose 

### ISSUE THREAD

**Issue by kasjet99** [blakeblackshear/frigate#7636]
### Describe the problem you are having

I  cant seem to get the volumes right

### Version

3.8

### Frigate config file

```yaml
mqtt:
  enabled: false
cameras:
  Camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:wagwoord@192.168.88.100:554/stream1
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
    record:
      enabled: True
      retain:
        days: 7
        mode: all
detectors:
    cpu1:
      type: cpu
      num_threads: 3
```

### Relevant log output

```shell
service "frigate" refers to undefined volume opt/frigate/config/config.yml: invalid compose project                                              

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - opt/frigate/config/config.yml:/config/config.yml
      - opt/frigate/media:/media/frigate
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Port used by the Web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "wagwoord"
```

### FFprobe output from your camera

```shell
none not installed yet
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Vigi C540 2.0

### Any other information that may be helpful

location of config.yml filr

rudi@ubuntu:/opt/frigate/config$ ls
config.yml
