### ISSUE TITLE
[Support]: Some errors for 0.13 dev version

### ISSUE THREAD

**Issue by lorenzomartini1** [blakeblackshear/frigate#7641]
### Describe the problem you are having

Hi there,
after installing the dev version I got these errors triggering event from API:

`https://URL/api/events/retro_alto/person/create`
```
{
  "subLabel": "some_string", // add sub label to event
  "duration": 5, // predetermined length of event (default: 30 seconds) or can be to null for indeterminate length event
  "include_recording": true // whether the event should save recordings along with the snapshot that is taken
}
```
or
```
{
  "subLabel": "some_string", // add sub label to event
  "duration": null, // predetermined length of event (default: 30 seconds) or can be to null for indeterminate length event
  "include_recording": true // whether the event should save recordings along with the snapshot that is taken
}
```

- Preview frame is more little then normal
- "IN PROGRESS" layer is not present
- Random video duration (42s both API calls, even if one time it was 5+pre_capture (7) +post_capture (7)) --> I expect it to be "IN PROGRESS" in both cases.
- MQTT entity are not updated (example Home Assistant one)

![image](https://github.com/blakeblackshear/frigate/assets/35630216/c4e1db11-5ce3-4bf5-bd78-fb1d53a358a4)

### Version

0.13.0-7C629C1

### Frigate config file

```yaml
mqtt:
  host: #
  port: #
  user: #
  password: #

detect:
  enabled: true
  width: 640 #960
  height: 480 #540
  fps: 10 #5
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 30 #50
  stationary:
    interval: 300
    threshold: 300 # 150 = 30 secondi # old 50 # dopo 30 secondi (150/5 fps = 30) un oggetto fermo viene considerato "stazionario"
    max_frames:
      default: 1800 # 900 = 3 minuti # dopo aver capito che è un oggetto stazionario, registra nell'evento al massimo 3 minuti

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu

go2rtc:
  streams:
    retro_alto: 
      - http://192.168.1.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:retro_alto#audio=opus"
    retro_alto_sub: 
      - http://192.168.1.59/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
    porta_vista_nord: 
      - http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:porta_vista_nord#audio=opus"
    porta_vista_nord_sub: 
      - http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
    porta_vista_sud: 
      - http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!
      - "ffmpeg:porta_vista_sud#audio=opus"
    porta_vista_sud_sub: 
      - http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=Stream1!

cameras:
  porta_vista_nord:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/porta_vista_nord?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porta_vista_nord_sub?video=copy
          input_args: preset-rtsp-restream
        # - path: /media/frigate/clip.mp4
        #   input_args: -re -stream_loop -1 -fflags +genpts          
          roles:
            - detect
    objects:
      track:
        - person
      # filters:
      #   person:
      #     min_area: 3500
      #     max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.68
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.7
    zones:
      giardino:
        coordinates: 196,371,222,263,342,266,339,91,396,101,400,0,383,0,376,52,331,58,328,0,0,0,0,179,0,480,78,480
      ingresso:
        coordinates: 403,204,427,330,216,304,87,480,567,480,573,446,527,378,582,90,586,43,430,0
        filters:
          persons:
            min_score: 0.65 #0.65
            threshold: 0.70 #0.75

      pavimento:
        coordinates: 349,98,395,101,422,204,431,313,210,311,232,268,353,263
      viottolino:
        coordinates: 332,0,384,0,378,59,330,55
    motion:
      mask:
        - 444,480,448,449,640,448,640,480
        - 179,330,290,331,229,0,122,27
      threshold: 25
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      height: 500

  # porta_vista_nord:
  #   ffmpeg:
  #       inputs:
  #         - path: rtmp://192.168.1.55/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #           roles:
  #             - record
  #             - detect
  #   zones:
  #     giardino:
  #       coordinates: 329,292,517,300,518,107,586,114,593,77,476,66,436,38,281,43,0,179,0,540,239,540
  #     pavimento:
  #       coordinates: 519,112,598,108,641,295,652,415,669,487,673,504,661,540,222,540,322,300,516,306
  #     ingresso:
  #       coordinates: 615,176,640,359,665,502,696,490,714,496,717,484,736,456,873,116,888,79,837,26,634,0
  #     viottolino:
  #       coordinates: 500,0,566,0,561,66,498,62
  #   motion:
  #     mask:
  #       - 632,365,817,316,734,502,536,505
  #     threshold: 40
              
  porta_vista_sud:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/porta_vista_sud?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porta_vista_sud_sub?video=copy
          input_args: preset-rtsp-restream
        # - path: /media/frigate/clip.mp4
        #   input_args: -re -stream_loop -1 -fflags +genpts          
          roles:
            - detect
    objects:
      track:
        - person
      # filters:
      #   person:
      #     min_area: 3500
      #     max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.7 # 0.6
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.75 # 0.7
    zones:
      giardino:
        coordinates: 520,480,640,480,640,193,537,99,418,96
      ingresso:
        coordinates: 0,91,0,480,295,480,520,480,498,403,451,398,389,400,222,411,75,48
        filters:
          persons:
            min_area: 15000
            min_score: 0.70 #0.65
            threshold: 0.75 #0.70
      tettoia:
        coordinates: 500,395,389,396,200,387,304,62,407,71
        filters:
          persons:
            min_score: 0.65 #0.65
            threshold: 0.70 #0.75
    motion:
      mask:
        - 445,480,640,480,640,454,442,455
        - 205,441,274,445,404,427,377,266,348,92,282,76,223,114,126,30,52,85
        - 457,87,493,100,505,50,466,48
        - 394,0,444,0,441,42,402,44
        - 429,318,509,309,532,0,439,0
      threshold: 25
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      height: 500

  # porta_vista_sud:
  #   ffmpeg:
  #     inputs:
  #         - path: rtmp://192.168.1.73/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #           roles:
  #             - record
  #             - detect
  #   zones:
  #     giardino:
  #       coordinates: 772,508,960,509,960,212,791,105,621,103
  #     ingresso:
  #       coordinates: 0,91,0,540,357,540,281,395,206,46
  #     tettoia:
  #       coordinates: 778,540,612,540,357,540,283,379,330,258,416,103,438,85,606,67
  #   motion:
  #     mask:
  #       - 224,379,313,513,353,540,459,519,529,498,468,398,427,368,378,363,320,352,277,356
  #     threshold: 40

  retro_alto:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/retro_alto?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/retro_alto_sub?video=copy
          input_args: preset-rtsp-restream
        # - path: /media/frigate/clip.mp4
        #   input_args: -re -stream_loop -1 -fflags +genpts          
          roles:
            - detect
    zones:
      campo:
        coordinates: 2048,0,2048,420,1409,410,593,440,0,496,0,0 #640,0,640,123,441,120,191,124,0,147,0,0
      giardino_dietro:
        coordinates: 534,841,1158,902,1177,1324,1939,1315,2048,1251,2048,1536,0,1536,0,825 #167,263,362,282,368,414,606,411,640,391,640,480,0,480,0,258
        filters:
          person:
            min_area: 18000 #2000
            min_score: 0.5
            threshold: 0.55
      viottolino:
        coordinates: 0,598,441,537,569,780,800,809,742,640,784,499,2048,515,2048,418,1632,429,1094,430,482,459,0,509 #0,187,138,168,178,244,250,253,232,200,245,156,640,161,640,123,508,118,335,110,153,121,0,151
        filter:
          person:
            min_score: 0.5
            threshold: 0.55
      viottolinoesposta:
        coordinates: 489,576,748,576,800,800,576,780 #153,180,234,180,250,250,180,244
        filter:
          person:
            min_score: 0.5
            threshold: 0.55
      spazzatura:
        coordinates: 1206,1299,1888,1286,1801,870,1190,908 #377,406,590,402,563,272,372,284
        filters:
          person:
            threshold: 0.75
    # record:
      # events:
        # required_zones:
        #   - campo
        #   - giardino_dietro
        #   - viottolino
        #   - viottolinoesposta
        #   - spazzatura
    # snapshots:
      # required_zones:
      #   - campo
      #   - giardino_dietro
      #   - viottolino
      #   - viottolinoesposta
      #   - spazzatura
    motion:
      mask:
        # # - 142,167,171,270,0,263,0,178
        # - 454,534,547,864,0,842,0,570

        # # - 563,271,583,389,640,381,640,173,597,156,393,156,248,159,226,203,268,269,345,280
        # - 1801,867,1865,1244,2048,1219,2048,553,1910,499,1257,499,793,508,723,649,857,860,1104,896
        
        # # - 640,480,640,457,444,449,444,480
        # - 2048,1536,2048,1462,1420,1436,1420,1536

        - 454,534,586,848,522,948,465,1160,218,1094,0,840,0,570
        - 1801,867,1865,1244,2048,1219,2048,553,1910,499,1257,499,793,508,723,649,857,860,1104,896
        - 2048,1536,2048,1449,1237,1455,1309,1536
      threshold: 20
      contour_area: 20
    detect:
      width: 2048
      height: 1536
      max_disappeared: 30
    objects:
      filters:
        person:
          min_score: 0.6
          threshold: 0.65
          min_area: 18000 #1500
          max_area: 90000 #108000 #12000
      track:
        - person
        - bicycle
        - motorcycle
        - car
        - cat
      # filters:
      #   person:
      #     #min_area: 3500
      #     #max_area: 100000
      #     #min_ratio: 0
      #     #max_ratio: 0.8
          
      #     # Optional: minimum score for the object to initiate tracking (default: shown below)
      #     min_score: 0.5 # 0.6
      #     # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #     threshold: 0.6 # 0.7
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      # required_zones:
      #   - campo
      #   - giardino_dietro
      #   - viottolino
      #   - viottolinoesposta
      #   - spazzatura

  # retro_alto:
  #   ffmpeg:
  #     inputs:
  #       - path: rtmp://192.168.1.59/bcs/channel0_main.bcs?channel=0&stream=0&user=stream&password=Stream1!
  #         roles:
  #           - record
  #           - detect
  #   zones:
  #     campo:
  #       coordinates: 133,28,132,0,960,0,960,140,625,131,300,145,0,166,0,21
  #     giardino:
  #       coordinates: 0,540,661,540,672,510,960,509,960,209,361,199,373,290,280,285,208,201,0,216
  #     viottolino:
  #       coordinates: 0,222,222,198,288,285,368,291,356,202,675,189,960,199,960,139,756,128,593,124,225,133,0,162
  #     viottolino_esposta:
  #       coordinates: 190,126,357,113,380,278,263,286
  #   motion:
  #     mask:
  #       - 750,399,869,402,860,334,768,338
  #     threshold: 40

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 14
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 6
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 6
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  height: 500
  crop: False
  required_zones: []
  retain:
    default: 10

# motion:
#     delta_alpha: 0.2
#     frame_alpha: 0.3
#     contour_area: 0

motion:
  mqtt_off_delay: 0
  improve_contrast: true

objects:
  filters:
    person:
      # min_score: 0.2
      # threshold: 0.3
      # min_area: 0
      # max_area: 24000000
      min_score: 0.6 #0.7
      threshold: 0.75 # 0.75
      max_area: 50000
      min_area: 1200

ffmpeg:
  hwaccel_args:
#    - -hwaccel
#   - vaapi
#   - -hwaccel_device
#   - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
#   - -fflags
#   - nobuffer
#   - -flags
#   - low_delay
#   - -strict
#   - experimental
#   - -fflags
#   - +genpts+discardcorrupt
#   - -rw_timeout
#   - "5000000"
#   - -use_wallclock_as_timestamps
#   - "1" 
  output_args:
    record: preset-record-generic-audio-aac
    
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "solid"
  
live:
  height: 480
  quality: 8
    
birdseye:
  enabled: True
  width: 1280
  height: 960
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 520A

**Comment by NickM-27** [comment]
> If I start now an event, I expect it’s in progress until it ends

That is not how it works, you have to specifically tell frigate to leave the event open, otherwise it ends by itself. Frigate has no way of knowing the event has ended other than the end event api

> What is the correct way to pass that parameter? My request bodies are in the original question…
Where is set the “default duration”?

it looks like you just copied the docs with some changed values. It would be much more helpful to see the actual request you made as a curl command or something along with the response.

> Why? It sounds so strange.
> Can I manually publish MQTT event? Are they cought by HA?

Because they are custom, they are completely different and unrelated to the object detection that the current entities are based on. You as the user are creating the event, so you already know that the event exists and can run any automation on that data.

**Comment by lorenzomartini1** [comment]
Ok thanks, solved with that.

Now I got this:
![image](https://github.com/blakeblackshear/frigate/assets/35630216/593acc01-cada-4546-b39b-6b9bce005921)
But after 30-40 min:
![image](https://github.com/blakeblackshear/frigate/assets/35630216/4fc65d74-e15c-4ad9-8ee3-e75710c27cae)

**Comment by NickM-27** [comment]
what is your docker compose?

**Comment by lorenzomartini1** [comment]
```
services:
  frigate:
    container_name: frigate-test
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-7c629c1
    shm_size: "80mb"
#    devices:
#      - /dev/bus/usb:/dev/bus/usb
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/hdd/frigate:/media/frigate
      - config:/config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935
      - 8554:8554
      
volumes:
  config:
```
