### ISSUE TITLE
[Camera Support]: FPS very low.

### ISSUE THREAD

**Issue by MajliTech** [blakeblackshear/frigate#7643]
### Describe the problem you are having

The camera FPS is very low, recordings are fine.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  pokoj:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.12.71:8080/h264.sdp
          roles:
            - detect
          # hwaccel_args: preset-vaapi
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
record:
  enabled: true
  retain:
    days: 3
    mode: all
```

### Relevant log output

```shell
No logs indicate this issue.
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://192.168.12.71:8080/h264.sdp':
  Metadata:
    title           : IP Webcam
  Duration: N/A, start: 0.051889, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(tv, unknown/bt470bg/unknown, progressive), 1920x1080, 19.25 tbr, 90k tbn
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Android IP Webcam, Xiaomi Redmi Note 4 (mido)

**Comment by NickM-27** [comment]
where is the fps low? you have provided no information

**Comment by MajliTech** [comment]
In the Live view

**Comment by NickM-27** [comment]
please read the docs https://docs.frigate.video/configuration/live

**Comment by MajliTech** [comment]
The config is now
```yml
mqtt:
  enabled: false

cameras:
  pokoj:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.12.71:8080/h264.sdp
          roles:
            - detect
          # hwaccel_args: preset-vaapi
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
record:
  enabled: true
  retain:
    days: 3
    mode: all
ui:
  live_mode: mse
```
but ui still show jsmpeg. Did I misunderstand the docs?

**Comment by NickM-27** [comment]
like it says in the docs, go2rtc config is required for the other options

**Comment by MajliTech** [comment]
Ok, I have configured go2rtc, but when using the mse or webrtc mode image doesnt load. (Tested firefox and chromium).
```yaml
mqtt:
  enabled: false

cameras:
  pokoj:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.12.71:8080/h264.sdp
          roles:
            - detect
          # hwaccel_args: preset-vaapi
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
record:
  enabled: true
  retain:
    days: 3
    mode: all
ui:
  live_mode: mse
```

**Comment by NickM-27** [comment]
What is you current config that has go2rtc setup?

**Comment by MajliTech** [comment]
> What is you current config that has go2rtc setup?

Sorry, just updated my config.

**Comment by NickM-27** [comment]
if it doesn't load then you should check go2rtc logs

**Comment by NickM-27** [comment]
What about browser console errors after trying to stream MSE (we don't expect webrtc to work, because that requires extra setup as the docs explain)

**Comment by MajliTech** [comment]
![preview of what the browser says after streaming mse, the output is nothing](https://github.com/blakeblackshear/frigate/assets/68728886/95742a3a-a481-446d-b0d9-65955001cf56)

**Comment by NickM-27** [comment]
How long are you waiting? Your camera may have a high iframe interval causing the stream start to be delayed (since the live stream has to start on an iframe)

**Comment by MajliTech** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/68728886/8f6bce43-87cf-48b3-9710-87d1076d2aa8)
This tab is open for propably 5 mins

**Comment by NickM-27** [comment]
you can use `chrome://media-internals` to debug, or you can try updating go2rtc to see if there is some compatibility issue with the camera that is fixed in a later version https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by MajliTech** [comment]
1. ```json
{
  "properties": {
    "render_id": 15,
    "player_id": 0,
    "created": "2023-08-31 20:40:37.158 UTC",
    "origin_url": "http://192.168.12.61:8004/",
    "kFrameUrl": "http://192.168.12.61:8004/cameras/pokoj",
    "kFrameTitle": "Frigate",
    "url": "blob:http://192.168.12.61:8004/e7c2bd6a-6312-4e0d-a00e-2178c9e50f3a",
    "kTextTracks": [],
    "info": "ChunkDemuxer",
    "kRendererName": "RendererImpl",
    "pipeline_state": "kStarting"
  },
  "events": [
    {
      "time": 0,
      "key": "created",
      "value": "2023-08-31 20:40:37.158 UTC"
    },
    {
      "time": 2.0760000012815,
      "key": "origin_url",
      "value": "http://192.168.12.61:8004/"
    },
    {
      "time": 2.087000001221895,
      "key": "kFrameUrl",
      "value": "http://192.168.12.61:8004/cameras/pokoj"
    },
    {
      "time": 2.0899999998509884,
      "key": "kFrameTitle",
      "value": "Frigate"
    },
    {
      "time": 2.2139999996870756,
      "key": "url",
      "value": "blob:http://192.168.12.61:8004/e7c2bd6a-6312-4e0d-a00e-2178c9e50f3a"
    },
    {
      "time": 2.217000000178814,
      "key": "kTextTracks",
      "value": []
    },
    {
      "time": 2.2359999995678663,
      "key": "info",
      "value": "ChunkDemuxer"
    },
    {
      "time": 2.2430000007152557,
      "key": "kRendererName",
      "value": "RendererImpl"
    },
    {
      "time": 20.354000000283122,
      "key": "pipeline_state",
      "value": "kStarting"
    }
  ]
}
```
2. I'm using Docker Compose, how can I update it?

**Comment by NickM-27** [comment]
try using ffmpeg and see if it makes a difference

```
go2rtc:
  streams:
    pokoj:
      - "ffmpeg:rtsp://192.168.12.71:8080/h264.sdp"
```

> I'm using Docker Compose, how can I update it?

like the docs explain to
