### ISSUE TITLE
[Config Support]: Unable to connect to hivemq MQTT broker

### ISSUE THREAD

**Issue by JeetR** [blakeblackshear/frigate#7644]
### Describe the problem you are having

Hello,

I am not able to connect to hiveMq broker from frigate even after providing the correct credentials in the configs file.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: "ffe6dd4317684512a3e5e54541bba4eb.s1.eu.hivemq.cloud"
  port: 8883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
```

### Relevant log output

```shell
Unable to publish to outdoor_camera/motion: client is not connected
2023-09-01 03:38:07.014340955  [2023-09-01 03:38:07] frigate.comms.mqtt             ERROR   : Unable to publish to outdoor_camera/motion: client is not connected
2023-09-01 03:38:18.515491822  [2023-09-01 03:38:18] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
2023-09-01 03:39:21.841955828  [2023-09-01 03:39:21] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

I can connect to the same broker using python code using paho-mqtt .

But the weird thing is that if i comment out this line from the default script provided by hiveMq it just hangs and nothing appears to be working.

`#client.tls_set(tls_version=mqtt.client.ssl.PROTOCOL_TLS)`

I do not know if it can be set in frigate or not, or does it make any difference?

**Comment by NickM-27** [comment]
looks like it requires tls by default

**Comment by JeetR** [comment]
> looks like it requires tls by default

can i set this in Frigate?

**Comment by NickM-27** [comment]
> > looks like it requires tls by default
> 
> can i set this in Frigate?

yes of course https://docs.frigate.video/configuration/

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: mqtt.server.com
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: mqtt_user
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  tls_client_cert: /path/to/client.crt
  tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
```
