### ISSUE TITLE
[Support]: Events recoded inside of motion mask 

### ISSUE THREAD

**Issue by hentismith** [blakeblackshear/frigate#7646]
### Describe the problem you are having

I'm getting events of people that are not "visible" since they are in the motion mask area.

![image](https://github.com/blakeblackshear/frigate/assets/652258/b5c78b68-fbb9-48a6-bf6e-73383c00df9e)

This person was only in the street, and the street is covered in a motion mask. 

My best guess is that I have motion outside the motion mask and the frame is sent to detector and the person is detected and triggers the recording :? 

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

birdseye:
  enabled: True
  mode: continuous

cameras:
  frontyard: # <------ Name the camera
    birdseye:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://<frontyard_camera>/stream1
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
        - 1920,0,1920,312,1682,315,728,290,716,0
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - cat
          - dog          
  backyard: # <------ Name the camera
    birdseye:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://<backyard_camera>/stream1
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,838,1001,207,1861,373,1920,434,1920,0,0,0
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - cat
          - dog          
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/edgetpu_model.tflite"
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://rtsp://<frontyard_camera>/stream1/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2304x1296, 15 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Frigate stats

```json
backyard	
camera_fps	5
capture_pid	443
detection_enabled	1
detection_fps	0
ffmpeg_pid	450
pid	439
process_fps	5
skipped_fps	0
cpu_usages	
1	
cpu	"0.0"
mem	"0.0"
15	
cpu	"0.0"
mem	"0.0"
17	
cpu	"0.0"
mem	"0.0"
24	
cpu	"0.0"
mem	"0.0"
25	
cpu	"0.0"
mem	"0.0"
26	
cpu	"0.0"
mem	"0.0"
27	
cpu	"0.0"
mem	"0.0"
28	
cpu	"0.0"
mem	"0.0"
29	
cpu	"0.0"
mem	"0.0"
30	
cpu	"0.0"
mem	"0.0"
31	
cpu	"0.0"
mem	"0.0"
32	
cpu	"0.0"
mem	"0.0"
41	
cpu	"0.0"
mem	"0.0"
42	
cpu	"0.0"
mem	"0.0"
80	
cpu	"0.0"
mem	"0.0"
81	
cpu	"0.0"
mem	"0.0"
82	
cpu	"0.0"
mem	"0.0"
88	
cpu	"0.0"
mem	"0.1"
97	
cpu	"0.0"
mem	"0.0"
98	
cpu	"2.3"
mem	"2.1"
104	
cpu	"0.0"
mem	"0.1"
134	
cpu	"0.0"
mem	"0.1"
135	
cpu	"0.0"
mem	"0.1"
136	
cpu	"0.0"
mem	"0.1"
137	
cpu	"0.0"
mem	"0.0"
139	
cpu	"0.0"
mem	"0.0"
154	
cpu	"0.0"
mem	"0.0"
182	
cpu	"0.0"
mem	"0.0"
218	
cpu	"0.0"
mem	"0.0"
426	
cpu	"0.0"
mem	"0.3"
431	
cpu	"0.0"
mem	"0.1"
432	
cpu	"0.0"
mem	"0.5"
434	
cpu	"1.7"
mem	"0.4"
437	
cpu	"1.0"
mem	"0.6"
438	
cpu	"0.0"
mem	"0.3"
439	
cpu	"1.0"
mem	"0.6"
440	
cpu	"0.0"
mem	"0.3"
441	
cpu	"4.3"
mem	"0.4"
443	
cpu	"3.7"
mem	"0.4"
449	
cpu	"0.0"
mem	"0.1"
450	
cpu	"8.0"
mem	"1.1"
27084	
cpu	"7.3"
mem	"0.4"
29711	
cpu	"0.0"
mem	"0.0"
29717	
cpu	"0.0"
mem	"0.0"
29777	
cpu	"0.0"
mem	"0.0"
29783	
cpu	"0.0"
mem	"0.0"
%Cpu(s):	
cpu	"id,"
mem	"4.2"
MiB	
cpu	"8196.4"
mem	"avail"
PID	
cpu	"%CPU"
mem	"%MEM"
Tasks:	
cpu	"stopped,"
mem	"0"
top	
cpu	"users,"
mem	"load"
detection_fps	0
detectors	
coral	
detection_start	0
inference_speed	11.52
pid	432
frontyard	
camera_fps	5
capture_pid	441
detection_enabled	1
detection_fps	0
ffmpeg_pid	27084
pid	437
process_fps	5
skipped_fps	0
gpu_usages	
intel-vaapi	
gpu	"1.28 %"
mem	"- %"
service	
last_updated	1693558813
latest_version	"0.12.1"
storage	
/dev/shm	
free	59.4
mount_type	"tmpfs"
total	67.1
used	7.8
/media/frigate/clips	
free	846958.6
mount_type	"ext4"
total	980667
used	92720.4
/media/frigate/recordings	
free	846958.6
mount_type	"ext4"
total	980667
used	92720.4
/tmp/cache	
free	998.2
mount_type	"tmpfs"
total	1000
used	1.8
temperatures	{}
uptime	74525
version	"0.12.1-367d724"
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

TP-Link Tapo c210 and c200
