### ISSUE TITLE
[Config Support]: Recording with audio, reproduce audio on vlc but not audio on frigate web page

### ISSUE THREAD

**Issue by ricain59** [blakeblackshear/frigate#7655]
### Describe the problem you are having

Hello,

I configured my camera on frigate, reolink RLC-520, it's working nice.
I can view live with sound on web page frigate. On recording, if i opening the mp4 file with vlc, vlc reproducing sound.
But, on frigate web page, i can reproducing recording but without sound.
I've search but not found the problem. Maybe, error on my configuration.

Thank you for help.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: x.x.x.x
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxx
  password: xxxxxxxxx
  stats_interval: 60

database:
  path: /db/frigate.db 

detectors:
  coral1:
    type: edgetpu
    device: pci:0

record:
  enabled: True
  expire_interval: 30
  retain:
    days: 0
    mode: all  
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      mode: motion
      default: 760

detect:
  enabled: True
  max_disappeared: 50
  stationary:
    interval: 0
    threshold: 100  

objects:
  track:
    - person
    - car
    - dog
    - cat
  
snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 760
    
timestamp_style:
  position: "tr"
  format: "%d-%m-%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  
go2rtc:
  streams:
    corredor: 
      - "ffmpeg:http://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    corredor_sub: 
      - "ffmpeg:http://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"        
      

cameras: 
  corredor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/corredor?video=copy&audio=opus
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/corredor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect          
    detect:
      width: 640
      height: 480
      fps: 10       
    record:
      events:
        required_zones:
          - corredor_0
    snapshots:
      required_zones:
        - corredor_0    
    objects:
      filters:
        dog:
          mask:
            - 97,480,520,480,605,122,412,68,0,290
    zones: 
      corredor_0:
        coordinates: 0,363,92,480,523,480,598,189,603,34,408,36,230,83,0,195      
    mqtt:
      enabled: True

ui:
  live_mode: mse
  use_experimental: False
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"

telemetry:
  version_check: True
```

### Relevant log output

```shell
can't get any errors on log about this problem.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

**Comment by NickM-27** [comment]
The problem is that you have `?audio=opus` for the url in the recording stream. The browser player is not capable of playing back opus audio, it needs to be aac

**Comment by ricain59** [comment]
@NickM-27 As suggested i've changed to `audio=aac`  but i get this error on log e doesn't recording any video:

> 2023-09-02 12:45:29.276994227  [2023-09-02 12:45:29] ffmpeg.corredor.record         ERROR   : rtsp://127.0.0.1:8554/corredor?video=copy&audio=aac: Invalid data found when processing input
> 2023-09-02 12:45:29.277065018  [2023-09-02 12:45:29] watchdog.corredor              INFO    : Terminating the existing ffmpeg process...
> 2023-09-02 12:45:29.277127305  [2023-09-02 12:45:29] watchdog.corredor              INFO    : Waiting for ffmpeg to exit gracefully...

```
cameras: 
  corredor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/corredor?video=copy&audio=aac
```

**Comment by NickM-27** [comment]
Very odd, I'd suggest using `preset-record-generic-audio-aac` instead for the recording output arg

**Comment by NickM-27** [comment]
also I'd suggest the url be `rtsp://127.0.0.1:8554/corredor?video&audio=aac`

**Comment by ricain59** [comment]
Thank you for your help, i've resolved my problem with this configuration:

```
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/corredor?video&audio=aac
```

Thank you very much for you time.
