### ISSUE TITLE
[HW Accel Support]: "AttributeError: 'TensorRtDetector' object has no attribute 'outputs' I get this error

### ISSUE THREAD

**Issue by vishalhero31** [blakeblackshear/frigate#7659]
### Describe the problem you are having

Hi Guys,
I'm Using the **Vultr GPU** instance which has "**Nvidia A16 GPU**" to setup Frigate and It has 8GB Vram. I have successfullt built the trt & .so files and mapped it correctly and Have changed different frigate tensor image but I get this error when I start my docker-Compose file:. If I change the Detector to CPU then Everything is Working perfectly

Please Help me

### Version

ghcr.io/blakeblackshear/frigate:master-e3eae53-tensorrt

### Frigate config file

```yaml
mqtt:
  enabled: false
rtmp:
  enabled: False
cameras:
  Camera:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.226:554/Streaming/channels/501
          hwaccel_args: preset-nvidia-h264
          roles:
            - detect
            - record
    objects:
      track:
        - person
    detect:
      width: 1920
      height: 1080
    record:
      enabled: False
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov4-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:master-e3eae53-tensorrt
    container_name: frigate
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    privileged: true
    restart: unless-stopped
    shm_size: '64mb'
    volumes:
      - /home/ubuntu/trt-models:/trt-models/
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/frigate/config/config.yaml:/config/config.yaml
      - /home/ubuntu/frigate/storage:/media/frigate
    tmpfs:
      - /tmp/cache:size=1000000000
    ports:
      - '5000:5000'
      - '8554:8554'
      - '8555:8555/tcp'
      - '8555:8555/udp'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
```

### Relevant log output

```shell
Status: Downloaded newer image for ghcr.io/blakeblackshear/frigate:0.12.0-beta10-tensorrt
Recreating frigate ... done
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | 2023-09-03 07:05:41.981593805  [INFO] Preparing go2rtc config...
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | 2023-09-03 07:05:41.984652645  [INFO] Starting Frigate...
frigate    | s6-rc: info: service nginx successfully started
frigate    | 2023-09-03 07:05:41.992312322  [INFO] Starting NGINX...
frigate    | s6-rc: info: service legacy-services: starting
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2023-09-03 07:05:42.192338589  [INFO] Starting go2rtc...
frigate    | 2023-09-03 07:05:42.266750064  07:05:42.266 INF go2rtc version 1.2.0 linux/amd64
frigate    | 2023-09-03 07:05:42.266755054  07:05:42.266 INF [api] listen addr=:1984
frigate    | 2023-09-03 07:05:42.266756595  07:05:42.266 INF [rtsp] listen addr=:8554
frigate    | 2023-09-03 07:05:42.266758298  07:05:42.266 INF [srtp] listen addr=:8443
frigate    | 2023-09-03 07:05:42.266760065  07:05:42.266 INF [webrtc] listen addr=:8555
frigate    | 2023-09-03 07:05:43.052370197  [2023-09-03 07:05:43] frigate.app                    INFO    : Starting Frigate (0.12.0-e454daf)
frigate    | 2023-09-03 07:05:43.064315765  [2023-09-03 07:05:43] peewee_migrate                 INFO    : Starting migrations
frigate    | 2023-09-03 07:05:43.069677588  [2023-09-03 07:05:43] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | 2023-09-03 07:05:43.085539084  [2023-09-03 07:05:43] frigate.app                    INFO    : Output process started: 256
frigate    | 2023-09-03 07:05:43.094295764  [2023-09-03 07:05:43] frigate.app                    INFO    : Camera processor started for Camera: 260
frigate    | 2023-09-03 07:05:43.109291655  [2023-09-03 07:05:43] frigate.app                    INFO    : Capture process started for Camera: 262
frigate    | 2023-09-03 07:05:43.117634112  [2023-09-03 07:05:43] detector.tensorrt              INFO    : Starting detection process: 254
frigate    | 2023-09-03 07:05:43.281815873  [2023-09-03 07:05:43] frigate.detectors.plugins.tensorrt ERROR   : ERROR: failed to load libraries. libcudart.so.12: cannot open shared object file: No such file or directory
frigate    | 2023-09-03 07:05:43.655812412  [2023-09-03 07:05:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +321, GPU +0, now: CPU 377, GPU 1015 (MiB)
frigate    | 2023-09-03 07:05:43.668866493  [2023-09-03 07:05:43] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 12 MiB
frigate    | 2023-09-03 07:05:43.683446065  [2023-09-03 07:05:43] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::40] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 213, Serialized Engine Version: 232)
frigate    | 2023-09-03 07:05:43.689989535  [2023-09-03 07:05:43] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
frigate    | 2023-09-03 07:05:43.690057672  Process detector:tensorrt:
frigate    | 2023-09-03 07:05:43.690761398  Traceback (most recent call last):
frigate    | 2023-09-03 07:05:43.690775707    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate    | 2023-09-03 07:05:43.690776857      self.run()
frigate    | 2023-09-03 07:05:43.690777891    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate    | 2023-09-03 07:05:43.690778786      self._target(*self._args, **self._kwargs)
frigate    | 2023-09-03 07:05:43.690779696    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
frigate    | 2023-09-03 07:05:43.690815309      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate    | 2023-09-03 07:05:43.690822684    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
frigate    | 2023-09-03 07:05:43.690823568      self.detect_api = create_detector(detector_config)
frigate    | 2023-09-03 07:05:43.690824511    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
frigate    | 2023-09-03 07:05:43.690825297      return api(detector_config)
frigate    | 2023-09-03 07:05:43.690826254    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 220, in __init__
frigate    | 2023-09-03 07:05:43.690827152      self.input_shape = self._get_input_shape()
frigate    | 2023-09-03 07:05:43.690828100    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 92, in _get_input_shape
frigate    | 2023-09-03 07:05:43.690829450      binding = self.engine[0]
frigate    | 2023-09-03 07:05:43.690830388  TypeError: 'NoneType' object is not subscriptable
frigate    | 2023-09-03 07:05:43.690831333  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f3398326820>
frigate    | 2023-09-03 07:05:43.690832147  Traceback (most recent call last):
frigate    | 2023-09-03 07:05:43.690845798    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
frigate    | 2023-09-03 07:05:43.691209602      if self.outputs is not None:
frigate    | 2023-09-03 07:05:43.691211226  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
frigate    | 2023-09-03 07:05:51.984959817  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Camera is Working Properly. I tested with CPU Detector
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision DVR
