### ISSUE TITLE
[Support]: HASS sensor does not go unavailable when Frigate is shutdown

### ISSUE THREAD

**Issue by simondsmason** [blakeblackshear/frigate#7661]
### Describe the problem you are having

The status of the camera sensor in HASS does not change to unavailable when frigate is shutdown.  I wanted to use this status change from unavailable to recording to stop certain cameras recording automatically at startup of Frigate.  In another support thread someone was asking the same thing and the suggestion was to monitor this sensor and look for change from unavailable to recording and then stop recording.  But when I shutdown Frigate it does not change the sensor to unavailable.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.110
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: $$$$$$$$$
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 30
    mode: all
birdseye:
  enabled: True
  mode: continuous
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.234:554//h264Preview_01_main
          roles:
            - rtmp
            - record
            - detect
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 0,720,441,720,643,308,573,129,1168,131,1168,0,513,0,0,0
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.33:554//h264Preview_01_main
          roles:
            - rtmp
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 441,707,437,671,11,676,11,710
    zones:
      back_step:
        coordinates: 979,720,1122,720,1086,564,1059,533,965,533
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.160:554//h264Preview_01_main
          roles:
            - rtmp
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 14,676,437,672,439,704,16,703
    zones:
      front_step:
        coordinates: 0,361,244,225,664,720,253,720
  porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.161:554//h264Preview_01_main
          roles:
            - rtmp
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
       - 442,707,442,664,14,665,12,711
  front_garden:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.149:554//h264Preview_01_main
          roles:
            - rtmp
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 12,705,439,703,437,666,11,671
        - 0,0,1280,0,1280,274,908,292,351,354,0,452  
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.227:554//h264Preview_01_main
          roles:
            - rtmp
            - detect
    detect:
      enabled: false
    motion:
      mask:
        - 0,720,433,720,433,677,0,676
        - 856,123,1193,125,1222,505,1193,720,700,720,735,530,851,521,854,315,730,306,732,141
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.110:8554/livingroom
          roles:
            - rtmp
            - detect
    detect:
      enabled: false
    birdseye:
      enabled: False
    motion:
      mask:
        - 8,713,428,715,429,668,7,666
  home_office:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.217:554/live
          roles:
            - rtmp
            - detect
    detect:
      enabled: false
    birdseye:
      enabled: False
    motion:
      mask:
        - 918,718,1251,716,1253,664,915,669
  home_theater:
    ffmpeg:
      inputs:
        - path: rtsp://admin:$$$$$$$$$@192.168.2.233:554/live
          roles:
            - rtmp
            - detect
    detect:
      enabled: false
    birdseye:
      enabled: False
    motion:
      mask:
        - 920,712,1255,712,1253,666,916,666
```

### Relevant log output

```shell
no relevant logs that I can see.
```

### FFprobe output from your camera

```shell
not relevant?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Mostly Reolinks
