### ISSUE TITLE
Allow stationary objects to be excluded from MQTT occupancy / count topics

### ISSUE THREAD

**Issue by ThisIsQasim** [blakeblackshear/frigate#7667]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to disable detection for certain objects that are no longer in motion so that they don't trigger automations/notifications

**Describe the solution you'd like**
Allow disabling detection for certain objects that stop moving. Something like this in the config.

```
objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
  disable_on_stationary:
    - car
    - motorcycle
    - bicycle
```

**Describe alternatives you've considered**
I have considered the `Avoiding stationary objects` section of the docs but that sounds like a hack to me. The MQTT topics around zones are difficult to setup, the recording events are still triggered and I want to detect moving objects in the entire frame not just a zone.
