### ISSUE TITLE
docs error :  Unsupported config option for services.frigate: 'runtime'

### ISSUE THREAD

**Issue by bbrendon** [blakeblackshear/frigate#767]
Following the docs on this page don't work.
https://blakeblackshear.github.io/frigate/configuration/nvdec/

```
# docker-compose up
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.frigate: 'runtime'
```

```
# cat /etc/docker/daemon.json
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}

```

```
version: '3.6'

services:

  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    #image: blakeblackshear/frigate:stable-amd64
    image: blakeblackshear/frigate:stable-amd64nvidia
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video

    volumes:
      #- /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./clips:/media/frigate/clips
      - ./recordings:/media/frigate/recordings
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds

    environment:
      FRIGATE_RTSP_PASSWORD: 'password'

```
