### ISSUE TITLE
[Support]: WebRTC don't work outside local network

### ISSUE THREAD

**Issue by GerdRuetten** [blakeblackshear/frigate#7671]
### Describe the problem you are having

Dear all,

i have the problem, that the webrtc stream from the Web UI / camera side outside my local network not work (no stream, no error, only a white field).
The debug stream works fine and the recording streams works too.

In the HA add-on and in Apple Homekit are no problems.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 10.24.2.3
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /media/frigate/frigate.db
    
birdseye:
  enabled: True
  mode: continuous

snapshots:
  enabled: True
  retain:
    default: 10
    objects:
      person: 15
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

ui:
  live_mode: webrtc

detect:
  enabled: True
  width: 1980
  height: 1080

go2rtc:
  streams:
    Haustuer:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.24.7.2:554/stream1#video=copy#audio=copy#audio=opus"
    Einfahrt:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.24.7.1:554/stream1#video=copy#audio=copy#audio=opus"
    Terrasse:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.24.7.3:554/stream1#video=copy#audio=copy#audio=opus"

cameras:
  Haustuer:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Haustuer
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

  Einfahrt:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Einfahrt
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

  Terrasse:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Terrasse
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
2023-09-03 21:51:48.548163829  [INFO] Starting Frigate...
2023-09-03 21:51:49.183626328  [2023-09-03 21:51:49] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-03 21:51:49.202717332  [2023-09-03 21:51:49] peewee_migrate                 INFO    : Starting migrations
2023-09-03 21:51:49.205383868  [2023-09-03 21:51:49] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-03 21:51:49.220525223  [2023-09-03 21:51:49] detector.cpu1                  INFO    : Starting detection process: 553
2023-09-03 21:51:49.221118954  [2023-09-03 21:51:49] frigate.app                    INFO    : Output process started: 557
2023-09-03 21:51:49.221405035  [2023-09-03 21:51:49] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-09-03 21:51:49.222998434  [2023-09-03 21:51:49] detector.cpu2                  INFO    : Starting detection process: 555
2023-09-03 21:51:49.223139390  [2023-09-03 21:51:49] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-09-03 21:51:49.226913919  [2023-09-03 21:51:49] frigate.app                    INFO    : Camera processor started for Haustuer: 560
2023-09-03 21:51:49.230410062  [2023-09-03 21:51:49] frigate.app                    INFO    : Camera processor started for Einfahrt: 562
2023-09-03 21:51:49.233457166  [2023-09-03 21:51:49] frigate.app                    INFO    : Camera processor started for Terrasse: 563
2023-09-03 21:51:49.236092262  [2023-09-03 21:51:49] frigate.app                    INFO    : Capture process started for Haustuer: 564
2023-09-03 21:51:49.239585399  [2023-09-03 21:51:49] frigate.app                    INFO    : Capture process started for Einfahrt: 567
2023-09-03 21:51:49.241681398  [2023-09-03 21:51:49] frigate.app                    INFO    : Capture process started for Terrasse: 569
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Frigate stats

```json
{"Einfahrt":{"camera_fps":5.1,"capture_pid":567,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":577,"pid":562,"process_fps":5.1,"skipped_fps":0.0},"Haustuer":{"camera_fps":5.1,"capture_pid":564,"detection_enabled":1,"detection_fps":1.0,"ffmpeg_pid":568,"pid":560,"process_fps":5.1,"skipped_fps":0.0},"Terrasse":{"camera_fps":5.0,"capture_pid":569,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":576,"pid":563,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.2"},"1":{"cpu":"0.0","mem":"0.0"},"107":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"1.0","mem":"0.9"},"118":{"cpu":"0.0","mem":"0.0"},"123":{"cpu":"0.0","mem":"0.0"},"124":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"130":{"cpu":"0.0","mem":"0.0"},"131":{"cpu":"0.0","mem":"0.0"},"132":{"cpu":"0.0","mem":"0.0"},"133":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"37956":{"cpu":"0.0","mem":"0.0"},"37976":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"546":{"cpu":"0.0","mem":"0.2"},"552":{"cpu":"0.0","mem":"0.0"},"553":{"cpu":"0.0","mem":"0.3"},"555":{"cpu":"0.0","mem":"0.3"},"557":{"cpu":"1.0","mem":"0.3"},"560":{"cpu":"0.3","mem":"0.4"},"561":{"cpu":"0.0","mem":"0.1"},"562":{"cpu":"0.3","mem":"0.4"},"563":{"cpu":"0.3","mem":"0.4"},"564":{"cpu":"2.0","mem":"0.3"},"567":{"cpu":"2.0","mem":"0.3"},"568":{"cpu":"11.7","mem":"0.2"},"569":{"cpu":"1.7","mem":"0.3"},"576":{"cpu":"11.3","mem":"0.2"},"577":{"cpu":"11.0","mem":"0.2"},"578":{"cpu":"1.0","mem":"0.1"},"581":{"cpu":"1.3","mem":"0.1"},"583":{"cpu":"1.0","mem":"0.1"},"584":{"cpu":"0.0","mem":"0.1"},"585":{"cpu":"0.0","mem":"0.1"},"592":{"cpu":"0.0","mem":"0.1"},"78":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"93":{"cpu":"1.7","mem":"0.1"},"MiB":{"cpu":"24812.3","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":1.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":52.26,"pid":553},"cpu2":{"detection_start":0.0,"inference_speed":49.61,"pid":555}},"service":{"last_updated":1693810853,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":256.2,"mount_type":"tmpfs","total":268.4,"used":12.2},"/media/frigate/clips":{"free":12073.5,"mount_type":"ext4","total":33501.8,"used":19693.5},"/media/frigate/recordings":{"free":12073.5,"mount_type":"ext4","total":33501.8,"used":19693.5},"/tmp/cache":{"free":996.5,"mount_type":"tmpfs","total":1000.0,"used":3.5}},"temperatures":{},"uptime":40144,"version":"0.12.1-367d724"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Tapo/TP-Link C310

### Any other information that may be helpful

My Docker compose:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/frigate/config.yml:/config/config.yml
      - /var/lib/docker/volumes/frigate:/config
      - /var/lib/docker/volumes/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_MQTT_USER: "xxxx"
      FRIGATE_MQTT_PASSWORD: "xxxx"
      FRIGATE_RTSP_USER: "xxxx"
      FRIGATE_RTSP_PASSWORD: "xxxx"
```

The problem exist with all three cameras.

**Comment by GerdRuetten** [comment]
> It doesn't look like you've followed the extra config steps for webrtc https://docs.frigate.video/configuration/live#webrtc-extra-configuration

Dear @NickM-27 
Thank you for your support!

In my Router, i open Port 8555/tcp and 8555/udp to the lokal IP from frigate

<img width="713" alt="image" src="https://github.com/blakeblackshear/frigate/assets/97361636/e1d3ec80-d029-4762-a962-e02272885a93">

And my frigate configuration updated with:

```
go2rtc:
  webrtc:
    candidates:
      - 10.24.2.3:8555
      - stun:8555
  streams:
    Haustuer:

```

I restart frigate and restart the frigate proxy add-on, but the error persists
