### ISSUE TITLE
[Config Support]: 2 way audio for Reolink Wifi Doorbell Camera only works on wifi

### ISSUE THREAD

**Issue by JayBlackedOut** [blakeblackshear/frigate#7703]
### Describe the problem you are having

I am using `frigate-card` from HACS to display my doorbell stream in the frontend. Everything runs great except I only get the 2-way audio buttons to display when I am on wifi. To clarify, it does not matter which wifi network I am on - it does not have to be the home-assistant/frigate LAN. If I access the frontend while on the cellular network, I do not get sound or the ability to speak through the camera. 

I don't even know how to begin to troubleshoot this. Seeking some guidance. Thanks!

### Version

0.12.1-367d724

### Frigate config file

```yaml
# MQTT Configuration
mqtt:
  host: [host]
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: [user]
  password: [pass]
  stats_interval: 60

# go2rtc Configuration
go2rtc:
  streams:
    doorbell:
      - rtsp://[user]:[pass]@[host]:554/h264Preview_01_sub
      - ffmpeg:doorbell#audio=pcm

# Camera Configuration
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://[user]:[pass]@[host]:554/h264Preview_01_sub
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy

# Global Configuration
record:
  enabled: true
  retain:
    days: 30
  events:
    pre_capture: 5
    post_capture: 5
    retain: 
      default: 30
detect:
  enabled: true
  width: 2560
  height: 1920
snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 30
objects:
  track:
  - person
  - cat
  - dog
  - car
  filters:
    person:
      min_area: 30000
    car:
      min_area: 500000
ui:
  live_mode: webrtc
```

### Relevant log output

```shell
Nothing stands out in the logs
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
