### ISSUE TITLE
[Support]: Recording not working

### ISSUE THREAD

**Issue by rodrigogonegit** [blakeblackshear/frigate#7719]
### Describe the problem you are having

Recording enabled through Home Assistant does not work.

1. On HA's side, open up the camera, hit "Recording" in the Configuration section of the camera device
2. Open Frigate's log section and observe `frigate.comms.dispatcher       INFO    : Turning on recordings for bedroom_tapo`
3. Plug in to Frigate's container, ls'ing `/media/frigate/recordings` shows no change` ls'ing `/tmp/cache` shows no change either.

If I simply enable the recording through the config file, it works, like below:

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: mqtt.REDACTED
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate_client
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: homeassistant
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: REDACTED

cameras:
  bedroom_tapo:
    ffmpeg:
      inputs:
        - path: rtsp://camera_viewer:REDACTED@10.15.0.249:554/stream1
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 2
        mode: all

    detect:
      enabled: False
```

### Relevant log output

```shell
2023-09-07 09:49:22.519117274  [INFO] Starting Frigate...
2023-09-07 09:49:23.454581373  [2023-09-07 09:49:23] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-09-07 09:49:23.470291070  [2023-09-07 09:49:23] peewee_migrate                 INFO    : Starting migrations
2023-09-07 09:49:23.474789163  [2023-09-07 09:49:23] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-07 09:49:23.487556694  [2023-09-07 09:49:23] detector.cpu                   INFO    : Starting detection process: 290
2023-09-07 09:49:23.493894615  [2023-09-07 09:49:23] frigate.app                    INFO    : Output process started: 292
2023-09-07 09:49:23.493903149  [2023-09-07 09:49:23] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-09-07 09:49:23.495261833  [2023-09-07 09:49:23] frigate.app                    INFO    : Camera processor started for bedroom_tapo: 294
2023-09-07 09:49:23.500188864  [2023-09-07 09:49:23] frigate.app                    INFO    : Capture process started for bedroom_tapo: 297
2023-09-07 09:50:05.360737943  [2023-09-07 09:50:05] frigate.comms.dispatcher       INFO    : Turning on recordings for bedroom_tapo
2023-09-07 09:50:23.732099076  [2023-09-07 09:50:23] frigate.record                 WARNING : Unable to find file from recordings database: /media/frigate/recordings/2023-09-06/22/bedroom_tapo/29.39.mp4
```

### FFprobe output from your camera

```shell
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --enable-chromaprint --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libbs2b --enable-libcdio --enable-libdrm --enable-libjack --enable-libjxl --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libilbc --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-libplacebo --enable-librsvg --enable-librav1e --enable-librubberband --enable-libsmbclient --enable-version3 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libshaderc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libvpl --enable-runtime-cpudetect
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://camera_viewer:REDACTED@10.15.0.249:554/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 15 fps, 16.58 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo C200
