### ISSUE TITLE
[Support]: Audio not recording with H265 Amcrest AD410 doorbell

### ISSUE THREAD

**Issue by TyzzyT** [blakeblackshear/frigate#7721]
### Describe the problem you are having

I'm using the Amcrest AD410 with 2560x1920 H265 video and PVM MU-LAW 8 kHz 16 bits audio. In VLC I can play this stream just fine, but in Frigate the audio is not being recorded.
Any idea what I'm doing wrong?
I tried both input presets `preset-rtsp-restream` and `preset-rtsp-restream-low-latency`
Also tried record presets `preset-record-generic-audio-copy` and `preset-record-generic-audio-aac`
Both without luck.

When checking the camera on the Cameras page with the mse stream, audio is working.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: hostname
  user: frigate
  password: password


# https://docs.frigate.video/configuration/detectors/
detectors:
  coral:
    type: edgetpu
    device: usb


# https://docs.frigate.video/configuration/index
timestamp_style:
  position: bl
  format: "%Y-%m-%d %H:%M:%S"
  effect: shadow


# https://docs.frigate.video/configuration/
ui:
  live_mode: mse
  time_format: 24hour
  date_style: full


# https://docs.frigate.video/guides/configuring_go2rtc
go2rtc:
  streams:
# Start with substream, to use that one in HA: https://github.com/blakeblackshear/frigate-hass-integration/issues/464#issuecomment-1505216499
    voortuin:
      - rtsp://admin:password@ip:port/cam/realmonitor?channel=1&subtype=1#backchannel=0
    voortuin_main:
      - rtsp://admin:password@ip:port/cam/realmonitor?channel=1&subtype=0#backchannel=0


# https://docs.frigate.video/configuration/cameras
cameras:
  voortuin:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/voortuin
          input_args: preset-rtsp-restream-low-latency
# https://docs.frigate.video/configuration/hardware_acceleration/
# Hardware acceleration is only H264 on Raspberry Pi, so only available for this stream
          hwaccel_args: preset-rpi-64-h264
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/voortuin_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 720
      height: 576
      fps: 5
      max_disappeared: 50 # (50 frames = 10 seconds)
      stationary:
        interval: 0
        threshold: 10 # (10 frames = 2 seconds)
# https://docs.frigate.video/configuration/record
    record:
      enabled: true
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 21
          objects:
            bird: 2
            car: 14
            backpack: 7
# https://docs.frigate.video/configuration/snapshots
    snapshots:
      enabled: true
      clean_copy: true
      bounding_box: true
      retain:
        default: 21
        objects:
          bird: 7
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
not sure how to do this
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest AD410
