### ISSUE TITLE
[Camera Support]: False positive in swimming pool triggering high confidence person

### ISSUE THREAD

**Issue by jvallery** [blakeblackshear/frigate#7724]
### Describe the problem you are having

Reflections in the water yield a 70%+ confidence of a person. How can I eliminate false positives in the water without false negatives?

<img width="1242" alt="image" src="https://github.com/blakeblackshear/frigate/assets/3673164/689c5d1d-afe4-4a6d-b5f1-f19f386742f8">

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: false
detectors:
  coral:
    type: edgetpu
    device: usb
objects:
  track:
    - person
    - cat
    - dog
    - car
  filters:
    person:
      min_area: 8000
      threshold: 0.7      
    car: 
      min_area: 8000
      threshold: 0.7      
timestamp_style:
  position: "tr"
  format: "%Y-%m-%d %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000
motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mask: 0,900,1080,900,1080,1920,0,1920
  improve_contrast: False
  mqtt_off_delay: 30

record:
  enabled: True  
  expire_interval: 1440

  retain:
    days: 0
    mode: active_objects
  events:    
    pre_capture: 5    
    post_capture: 5
    retain:
      default: 365
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  retain:
    default: 365

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 3840
  # Optional: Height of the output resolution (default: shown below)
  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 10
  restream: true
  mode: objects

logger:
  default: debug

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
     panorama_west: 
      - rtsp://admin:xx@192.168.1.234:554/cam/realmonitor?channel=1&subtype=0
    panorama_north: 
      - rtsp://admin:xx@192.168.1.127:554/cam/realmonitor?channel=1&subtype=0
    breezeway_front:
      - rtsp://admin:xx@192.168.1.114:554/cam/realmonitor?channel=1&subtype=0
    breezeway_interior:
      - rtsp://admin:xx@192.168.1.133:554/cam/realmonitor?channel=1&subtype=0
    garage_interior:
      - rtsp://admin:v@xx@192.168.1.9:554/cam/realmonitor?channel=1&subtype=0  
    driveway:
      - rtsp://admin:v@xx@192.168.1.131:554/cam/realmonitor?channel=1&subtype=0  
    suite:
      - rtsp://admin:v@xx@192.168.1.247:554/cam/realmonitor?channel=1&subtype=0 
    gate:
      - rtsp://admin:xx@192.168.1.42:554/cam/realmonitor?channel=1&subtype=0 
    circle_driveway:
      - rtsp://admin:xx@192.168.1.199:554/cam/realmonitor?channel=1&subtype=0 
    master_patio:
      - rtsp://admin:xx@192.168.1.148:554/cam/realmonitor?channel=1&subtype=0 
    pool1:
      - rtsp://admin:xx@192.168.1.126:554/cam/realmonitor?channel=1&subtype=0 
    pool2:
      - rtsp://admin:xx@192.168.1.90:554/cam/realmonitor?channel=1&subtype=0 
    patio1:
      - rtsp://admin:xx@192.168.1.59:554/cam/realmonitor?channel=1&subtype=0 
    patio2:
      - rtsp://admin:xx@192.168.1.146:554/cam/realmonitor?channel=1&subtype=0 
    front_door:
      - rtsp://admin:xx@192.168.1.78:554/cam/realmonitor?channel=1&subtype=0       
    backyard:
      - rtsp://admin:xx@192.168.1.77:554/cam/realmonitor?channel=1&subtype=0       
    back_gate:
      - rtsp://admin:xx@192.168.1.116:554/cam/realmonitor?channel=1&subtype=0    
    wall_southwest:
      - rtsp://admin:xx@192.168.1.224:554/cam/realmonitor?channel=1&subtype=0    
    garage_rear:
      - rtsp://admin:xx@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0  
    japanese_garden:
      - rtsp://admin:xx@192.168.1.98:554/cam/realmonitor?channel=1&subtype=0  
    pool_rear:
      - rtsp://admin:xx@192.168.1.232:554/cam/realmonitor?channel=1&subtype=0  
    workshop_door:
      - rtsp://admin:xx@192.168.1.250:554/cam/realmonitor?channel=1&subtype=0 
    wall_south:
      - rtsp://admin:xx@192.168.1.188:554/cam/realmonitor?channel=1&subtype=0 
    gazebo:
      - rtsp://admin:xx@192.168.1.175:554/cam/realmonitor?channel=1&subtype=0 
    sidewalk_east:
      - rtsp://admin:xx@192.168.1.176:554/cam/realmonitor?channel=1&subtype=0 
    storageyard_east:
      - rtsp://admin:xx@192.168.1.14:554/cam/realmonitor?channel=1&subtype=0  
    storageyard_west:
      - rtsp://admin:xx@192.168.1.117:554/cam/realmonitor?channel=1&subtype=0  
    suite_gate:
      - rtsp://admin:xx@192.168.1.7:554/cam/realmonitor?channel=1&subtype=0        
    powerwall:
      - rtsp://admin:xx@192.168.1.32:554/cam/realmonitor?channel=1&subtype=0
    sidewalk_west:
      - rtsp://admin:xx@192.168.1.181:554/cam/realmonitor?channel=1&subtype=0            
    wall_east:
      - rtsp://admin:xx@192.168.1.122:554/cam/realmonitor?channel=1&subtype=0                  
    wall_corner:
      - rtsp://admin:xx@192.168.1.79:554/cam/realmonitor?channel=1&subtype=0                  
    shed:
      - rtsp://admin:xx@192.168.1.101:554/cam/realmonitor?channel=1&subtype=0                  

  webrtc:
    listen: ":8555"
  api:
    listen: ":1984"
  log:
    level: debug

cameras:
  panorama_west:   
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/panorama_west
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  panorama_north:   
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/panorama_north
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp           
  breezeway_front:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/breezeway_front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  breezeway_interior:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/breezeway_interior
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  garage_interior:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_interior
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp        
  driveway:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp          
  suite:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/suite
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp  
  gate:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gate
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp  
  circle_driveway:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/circle_driveway
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
    zones:
      pool2_walkway:
        coordinates: 1920,0,0,0,0,1080,1920,1080
        objects:
          - person
          - car
        filters:
          person:
            min_area: 8000
            min_score: 0.6
            threshold: 0.7
          car:
            min_area: 10000    
            threshold: 0.7
            min_score: 0.6                
  master_patio:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/master_patio
          input_args: preset-rtsp-restream
          roles:            
            - detect
            - record
            - rtmp 
  pool1:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pool1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp 
    zones:
      pool1_walkway:
        coordinates: 1920,0,0,0,0,1080,1920,1080
        objects:
          - person
          - car
        filters:
          person:
            min_area: 8000
            min_score: 0.6
            threshold: 0.7
          car:
            min_area: 10000    
            threshold: 0.7
            min_score: 0.7

            
  pool2:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pool2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
    zones:
      pool2_walkway:
        coordinates: 1920,0,0,0,0,1080,1920,1080
        objects:
          - person
          - car
        filters:
          person:
            min_area: 8000
            min_score: 0.7
            threshold: 0.7
          car:
            min_area: 10000    
            threshold: 0.7
            min_score: 0.7               
  patio1:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/patio1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  patio2:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/patio2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  front_door:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  backyard:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp 
  back_gate:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_gate
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp  
  wall_southwest:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/wall_southwest
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  garage_rear:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_rear
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp                                  
  japanese_garden:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/japanese_garden
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp  
  pool_rear:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pool_rear
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  workshop_door:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/workshop_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  gazebo:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gazebo
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp   
  sidewalk_east:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/sidewalk_east
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp                             
  shed:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/shed
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  storageyard_east:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/storageyard_east
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
    zones:
      storageyard_east_zone1:
        coordinates: 1920,0,0,0,0,1080,1920,1080
        objects:
          - person
        filters:
          person:
            min_area: 8000
            min_score: 0.6
            threshold: 0.7
  storageyard_west:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/storageyard_west
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp                    
  suite_gate:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/suite_gate
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
  powerwall:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/powerwall
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
  sidewalk_west:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/sidewalk_west
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record       
  wall_east:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/wall_east
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record                                     
  wall_corner:
    birdseye:
      enabled: true
      mode: objects
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/wall_corner
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: Unknown
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
