### ISSUE TITLE
[Config Support]: Failed to probe corrupt segment / Discarding a corrupt recording segment

### ISSUE THREAD

**Issue by purplepenguinmedia** [blakeblackshear/frigate#7734]
### Describe the problem you are having

Cannot record my streams, when I switch on recording in my config I get the following messages in my log

2023-09-08 16:42:05.815148600  [2023-09-08 16:42:05] frigate.record 
WARNING : Discarding a corrupt recording segment: /tmp/cache/Entrance-F-20230908164154.mp4

2023-09-08 16:42:20.816128622  [2023-09-08 16:42:20] frigate.record
WARNING : Failed to probe corrupt segment /tmp/cache/Entrance-F-20230908164202.mp4: 0 - b'[extract_extradata @ 0x558659378640] No start code is found.\n/tmp/cache/Entrance-F-20230908164202.mp4: Invalid data found when processing input\n'

Cameras all work find for view and detecting people etc

Cameras were outputting h265 which was fine for viewing and detecting

Since switched to h264 incase that was the issue, same issue.

Any helps is much apricated, I have been trying and googling solutions for a week or so and im stuck

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: REMOVED
  port: 1883
  user: frigate
  password: REMOVED
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: True
  clean_copy: False
  bounding_box: True
  retain:
    default: 14 # days

record:
  enabled: True
  events:
    retain:
      default: 20

motion:
  improve_contrast: True

objects:
  track:
    - person
    - cat
    - dog

cameras:
  Gate-F: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://REMOVED:REMOVED@192.168.1.39:554/Streaming/Channels/103/ # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  Entrance-F: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://REMOVED:REMOVED@192.168.1.36:554/Streaming/Channels/103/ # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

    motion:
      mask:
        - 1280,320,1152,283,979,238,749,130,362,133,0,160,0,0,1280,0,1280,413
    zones:
      gate-entry:
        coordinates: 1001,617,1197,685,1280,370,1084,293
    objects:
      filters:
        person:
          mask:
            - 1280,320,1152,283,979,238,749,130,362,133,0,160,0,0,1280,0,1280,413
        dog:
          mask:
            - 1280,320,1152,283,979,238,749,130,362,133,0,160,0,0,1280,0,1280,413
        cat:
          mask:
            - 1280,320,1152,283,979,238,749,130,362,133,0,160,0,0,1280,0,1280,413

  Ginnel-F: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: preset-rtsp-generic
      inputs:
        - path: rtsp://REMOVED:REMOVED@192.168.1.12:554/Streaming/Channels/103/ # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  Side-F: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: preset-rtsp-restream-low-latency
      inputs:
        - path: rtsp://REMOVED:REMOVED@192.168.1.40:554/Streaming/Channels/103/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

    motion:
      mask:
        - 0,309,706,202,741,208,826,191,1020,156,1280,131,1280,0,0,0
    objects:
      filters:
        person:
          mask:
            - 0,328,805,185,860,180,994,155,1280,144,1280,0,0,0
        dog:
          mask:
            - 0,328,805,185,860,180,994,155,1280,144,1280,0,0,0
        cat:
          mask:
            - 0,328,805,185,860,180,994,155,1280,144,1280,0,0,0
```

### Relevant log output

```shell
Same for every camera

2023-09-08 16:41:40.826065605  [2023-09-08 16:41:40] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/Entrance-F-20230908164124.mp4
2023-09-08 16:41:50.818924095  [2023-09-08 16:41:50] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/Entrance-F-20230908164137.mp4: 0 - b'[extract_extradata @ 0x56107c937ac0] No start code is found.\n/tmp/cache/Entrance-F-20230908164137.mp4: Invalid data found when processing input\n'
```

### Frigate stats

```json
{"Entrance-F":{"camera_fps":5.1,"capture_pid":827,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":836,"pid":820,"process_fps":5.1,"skipped_fps":0.0},"Gate-F":{"camera_fps":5.1,"capture_pid":825,"detection_enabled":1,"detection_fps":4.9,"ffmpeg_pid":837,"pid":819,"process_fps":5.1,"skipped_fps":0.0},"Ginnel-F":{"camera_fps":5.1,"capture_pid":829,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":848,"pid":822,"process_fps":5.1,"skipped_fps":0.0},"Side-F":{"camera_fps":5.0,"capture_pid":833,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":847,"pid":823,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.2"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"0.0","mem":"0.0"},"108":{"cpu":"2.3","mem":"0.3"},"119":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"1266":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.0"},"1277":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"1283":{"cpu":"0.3","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"163":{"cpu":"0.0","mem":"0.0"},"164":{"cpu":"0.0","mem":"0.0"},"165":{"cpu":"0.0","mem":"0.0"},"175":{"cpu":"0.0","mem":"0.0"},"185":{"cpu":"0.0","mem":"0.0"},"195":{"cpu":"0.0","mem":"0.0"},"201":{"cpu":"0.0","mem":"0.0"},"202":{"cpu":"0.0","mem":"0.0"},"203":{"cpu":"0.0","mem":"0.0"},"204":{"cpu":"0.0","mem":"0.0"},"206":{"cpu":"0.0","mem":"0.0"},"209":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"337":{"cpu":"0.0","mem":"0.0"},"338":{"cpu":"0.0","mem":"0.0"},"339":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"804":{"cpu":"0.0","mem":"0.1"},"81":{"cpu":"0.0","mem":"0.0"},"810":{"cpu":"0.3","mem":"0.0"},"811":{"cpu":"8.6","mem":"0.2"},"812":{"cpu":"1.0","mem":"0.2"},"819":{"cpu":"3.0","mem":"0.2"},"82":{"cpu":"0.0","mem":"0.0"},"820":{"cpu":"1.3","mem":"0.2"},"821":{"cpu":"0.0","mem":"0.0"},"822":{"cpu":"1.0","mem":"0.2"},"823":{"cpu":"1.0","mem":"0.2"},"824":{"cpu":"0.0","mem":"0.0"},"825":{"cpu":"2.0","mem":"0.1"},"826":{"cpu":"0.0","mem":"0.0"},"827":{"cpu":"1.7","mem":"0.1"},"829":{"cpu":"1.7","mem":"0.1"},"832":{"cpu":"0.0","mem":"0.0"},"833":{"cpu":"1.7","mem":"0.1"},"836":{"cpu":"5.6","mem":"0.1"},"837":{"cpu":"5.0","mem":"0.1"},"838":{"cpu":"0.0","mem":"0.0"},"847":{"cpu":"5.6","mem":"0.1"},"848":{"cpu":"3.0","mem":"0.1"},"91":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"43671.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":5.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":27.35,"pid":811}},"gpu_usages":{"intel-vaapi":{"gpu":"0.73 %","mem":"- %"}},"service":{"last_updated":1694187938,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":529.3,"mount_type":"tmpfs","total":536.9,"used":7.5},"/media/frigate/clips":{"free":1447079.7,"mount_type":"zfs","total":1447198.6,"used":118.9},"/media/frigate/recordings":{"free":1447079.7,"mount_type":"zfs","total":1447198.6,"used":118.9},"/tmp/cache":{"free":997.4,"mount_type":"tmpfs","total":1000.0,"used":2.6}},"temperatures":{},"uptime":258,"version":"0.12.1-367d724"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
a few things:
1. suggest using hwaccel preset `preset-vaapi` instead of manual args
2. can you run ffprobe on the camera stream from the webUI

**Comment by purplepenguinmedia** [comment]
Hey

hwaccel_args: -hwaccel preset-vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

Breaks my streams and they will no longer load

Where as

hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

Works fine and shows the GPU in the system tab as being used  0.91 % but oddly mem use is blank

Probe when working shows as follows as I set all Camera to use the same codec, res and fps

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1280x720
FPS: 6/1

**Comment by NickM-27** [comment]
I meant replace the entire set of manual args with just `preset-vaapi`

**Comment by mrchris82** [comment]
sadly same or similar error

2023-09-08 17:57:08.676914789  [2023-09-08 17:57:08] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/Entrance-F-20230908175652.mp4: 0 - b'[extract_extradata @ 0x55df139e5640] No start code is found.\n/tmp/cache/Entrance-F-20230908175652.mp4: Invalid data found when processing input\n'
2023-09-08 17:57:08.677091280  [2023-09-08 17:57:08] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/Entrance-F-20230908175652.mp4

**Comment by mrchris82** [comment]
thanks for helping, this works now using preset-intel-qsv-h264

**Comment by Zen3515** [comment]
I was about to say that I know this problem all too well, since it has been here for 4 years.

But you said that your h.264 also suffers from the same problem, so I decided to make a new issue #7921 

To which I added some pointers on how you could work around it.

As for your problem, I suggest trying to debug it yourself

1. You should check first what's the current command arguments for ffmpeg
1.1 restart frigate
1.2 spamming this command to check the exact command ffmpeg is launched with

```bash
ps -eo args | grep ffmpeg --color
```


2. You should be able to replicate the command inside docker
2.1 exec into the docker

```bash
docker exec -it frigate bash
```

  2.2 try out your command, let the file save at different location

```bash
ffmpeg ... -i rtps://go2rtc:9554/example_camera_1 ... -y /tmp/test/example_camera_1....mp4
```

  2.3 run ffprobe on the saved file

```bash
ffprobe /tmp/test/example_camera_1_15654987564.mp4
```

It will give you more context on what's the actual error, and you could test your modified command, which you can apply it inside the config.

**Comment by Zen3515** [comment]
For this problem, there's no direct way to fix it.
But I found the perfect workaround, rather than patching frigate to support `shell=true`

I found that go2rtc [can pipe output of the exec command](https://github.com/AlexxIT/go2rtc#source-exec)
> **pipe** reads data from app stdout in different formats: MJPEG, H.264/H.265 bitstream, MPEG-TS.

Taking advantage of this, you could just add this to go2rtc and be fine on whatever program you want to use the stream in the future.

```yaml

streams:
  example:
    - exec:ffmpeg -fflags +genpts+igndts -use_wallclock_as_timestamps 1 -rtsp_transport tcp -i rtsp://exampleuser:examplepass@ipcam-01.example.com:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1 -c:v copy -c:a copy -f hevc -
    - "isapi://exampleuser:examplepass@ipcam-01.example.com:80/"
```

So this issue could be considered closed now, not just stale and closed.
