### ISSUE TITLE
[HW Accel Support]: P600 2GB - Out of VRAM w/10 of 12 Cameras  

### ISSUE THREAD

**Issue by domenicdistefano** [blakeblackshear/frigate#7736]
### Describe the problem you are having

**12 Camera Setup /  Intel i7-6700 - 2x Coral PCIe Detectors / NVIDIA P600 2GB VRAM**

- System ide / Frigate not running / 445mb of system RAM used.
- With the **iGPU** / vaapi enabled for decoding everything works well with all 12 cameras working - CPU usage is moderately high however due to the number of streams overall. Frigate does not report any GPU memory usage information. **2.3G** of system RAM used.
- With the **P600** enabled only 10 of the 12 cameras can start before the GPU hits 93% and complains its out of VRAM in the logs. **3.3G** of system RAM used.

So what am I missing here? How is it that the iGPU can decode all 12 cameras without issue and apparently by looking at the overall system memory consumption using little to no RAM. By comparison the discreet P600 GPU immediately consumes 93% of its 2GB dedicated VRAM with only 10 cameras. To make matters worse an additional GB of system ram is consumed when active also with 2 less cameras running.

Am I doing something wrong? I am using the ffmpeg presets but is there a way to tune this so the P600 uses far less VRAM. Why is it using anywhere close to this amount of VRAM for simple decoding anyway?

**iGPU**
![igpu](https://github.com/blakeblackshear/frigate/assets/7042586/5f753c41-1dda-44b2-bf41-a0e158d61bfb)

![GPUTop](https://github.com/blakeblackshear/frigate/assets/7042586/74d8d3cb-80a3-49db-8b6f-f3f532e43af0)

**P600**
![p600](https://github.com/blakeblackshear/frigate/assets/7042586/856723e2-0df1-4544-91f9-75b34f1b9491)

![gpumemory](https://github.com/blakeblackshear/frigate/assets/7042586/268a33e6-10e2-4324-9c60-b92caba65012)

### Version

0.12.1-367d724

### Frigate config file

```yaml
#ui:
#  use_experimental: false
#  live_mode: mse

mqtt:
  enabled: false

#record:
#  expire_interval: 10

go2rtc:
  streams:
    back_porch:
      - rtsp://admin:Goldfish10-@10.10.10.71:554/media/video0
    back_porch_sub:
      - rtsp://admin:Goldfish10-@10.10.10.71:554/media/video1
##############################################################################
    pool_road:
      - rtsp://admin:Goldfish10-@10.10.10.70:554/media/video0
    pool_road_sub:
      - rtsp://admin:Goldfish10-@10.10.10.70:554/media/video1
##############################################################################  
    back_yard:
      - rtsp://admin:Goldfish10-@10.10.10.72:554/media/video0
    back_yard_sub:
      - rtsp://admin:Goldfish10-@10.10.10.72:554/media/video1
##############################################################################
    garden:
      - rtsp://admin:Goldfish10-@10.10.10.73:554/media/video0
    garden_sub:
      - rtsp://admin:Goldfish10-@10.10.10.73:554/media/video1
##############################################################################
    front_yard:
      - rtsp://admin:Goldfish10-@10.10.10.74:554/media/video0
    front_yard_sub:
      - rtsp://admin:Goldfish10-@10.10.10.74:554/media/video1
##############################################################################
    front_door:
      - rtsp://admin:Goldfish10-@10.10.10.75:554/media/video0
    front_door_sub:
      - rtsp://admin:Goldfish10-@10.10.10.75:554/media/video1
##############################################################################
    driveway_front:
      - rtsp://admin:Goldfish10-@10.10.10.76:554/media/video0
    driveway_front_sub:
      - rtsp://admin:Goldfish10-@10.10.10.76:554/media/video1
##############################################################################
    driveway_pool:
      - rtsp://admin:Goldfish10-@10.10.10.77:554/media/video0
    driveway_pool_sub:
      - rtsp://admin:Goldfish10-@10.10.10.77:554/media/video1
##############################################################################
    lpr-41:
      - rtsp://admin:Caprica10@10.10.10.63:554/streaming/channels/101
    lpr-41_sub:
      - rtsp://admin:Caprica10@10.10.10.63:554/streaming/channels/102
##############################################################################
    lpr-cheltenham:
      - rtsp://admin:Caprica10@10.10.10.64:554/streaming/channels/101
    lpr-cheltenham_sub:
      - rtsp://admin:Caprica10@10.10.10.64:554/streaming/channels/102
##############################################################################
    lpr-pool:
      - rtsp://admin:Caprica10@10.10.10.65:554/streaming/channels/101
    lpr-pool_sub:
      - rtsp://admin:Caprica10@10.10.10.65:554/streaming/channels/102
##############################################################################
    doorbell: 
      - "ffmpeg:http://10.10.10.60/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=dingdong#video=copy#audio=copy#audio=opus"
    doorbell_sub: 
      - "ffmpeg:http://10.10.10.60/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=dingdong"


timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

cameras:

 ##############################################################################
  back_porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back_porch
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  pool_road:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool_road_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/pool_road
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15
##############################################################################
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back_yard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garden
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  driveway_front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway_front
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  driveway_pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway_pool
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 12
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  lpr-41:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lpr-41_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/lpr-41
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  lpr-cheltenham:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lpr-cheltenham_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/lpr-cheltenham
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  lpr-pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lpr-pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/lpr-pool
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog

      filters:
        dog:
          min_score: 0.3
          threshold: 0.5
#      mask:
#        - 23,480,333,480,333,442,26,440
#        - 640,95,640,0,464,0
#        - 258,211,323,246,357,142,274,140
#        - 383,342,457,365,477,261,401,232
#        - 425,131,553,227,640,251,640,213,607,176,460,88
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
  #  motion:
  #    mask:
  #      - 337,480,341,437,0,433,0,480,40,480

 #   zones:
 #     deck_area:
 #      coordinates: 0,284,0,457,207,480,474,480,640,480,540,406,392,259,253,106,166,31,108,49,0,72
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 3
          mode: motion 
        pre_capture: 5
        post_capture: 15  
##############################################################################
 
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
   hwaccel_args: preset-nvidia-h264
#  hwaccel_args: preset-vaapi
rtmp:
  enabled: false

birdseye:
  enabled: False
  restream: False
  width: 1280 
  height: 720
  quality: 1
  mode: objects

live:
  height: 720
  quality: 1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    runtime: nvidia
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/docker/appdata/frigate/config.yml:/config/config.yml
      - /root/docker/appdata/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: frigate
#      NVIDIA_VISIBLE_DEVICES: all 
#      NVIDIA_DRIVER_CAPABILITIES: all
```

### Relevant log output

```shell
2023-09-09 00:52:50.039934141  [2023-09-09 00:52:50] ffmpeg.back_porch.detect       ERROR   : [h264 @ 0x55828909bb00] Invalid NAL unit 0, skipping.
2023-09-09 00:52:50.040054855  [2023-09-09 00:52:50] ffmpeg.back_porch.detect       ERROR   : [h264 @ 0x558289a3cc00] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-09-09 00:52:50.040154253  [2023-09-09 00:52:50] ffmpeg.back_porch.detect       ERROR   : [h264 @ 0x558289a3cc00] Failed setup for format cuda: hwaccel initialisation returned error.
2023-09-09 00:52:50.040262528  [2023-09-09 00:52:50] ffmpeg.back_porch.detect       ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
2023-09-09 00:52:50.040368451  [2023-09-09 00:52:50] ffmpeg.back_porch.detect       ERROR   : Error reinitializing filters!
2023-09-09 00:52:50.040459205  [2023-09-09 00:52:50] ffmpeg.back_porch.detect       ERROR   : Failed to inject frame into filter network: Function not implemented
2023-09-09 00:52:50.040552370  [2023-09-09 00:52:50] ffmpeg.back_porch.detect       ERROR   : Error while processing the decoded data for stream #0:0
2023-09-09 00:52:50.064919418  [2023-09-09 00:52:50] watchdog.garden                ERROR   : Ffmpeg process crashed unexpectedly for garden.
2023-09-09 00:52:50.065050034  [2023-09-09 00:52:50] watchdog.garden                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-09-09 00:52:50.065166434  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac2d72b00] Invalid NAL unit 0, skipping.
2023-09-09 00:52:50.066638241  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   :     Last message repeated 1 times
2023-09-09 00:52:50.066644694  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac2d72b00] slice type 32 too large at -1
2023-09-09 00:52:50.066648567  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac2d72b00] decode_slice_header error
2023-09-09 00:52:50.066657339  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac2d72b00] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
2023-09-09 00:52:50.066661816  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac2d72b00] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
2023-09-09 00:52:50.066666015  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac3731a80] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-09-09 00:52:50.066669623  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac3731a80] Failed setup for format cuda: hwaccel initialisation returned error.
2023-09-09 00:52:50.066672388  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : [h264 @ 0x564ac382d0c0] Invalid NAL unit 0, skipping.
2023-09-09 00:52:50.066675902  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
2023-09-09 00:52:50.066678867  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : Error reinitializing filters!
2023-09-09 00:52:50.066681317  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : Failed to inject frame into filter network: Function not implemented
2023-09-09 00:52:50.066684297  [2023-09-09 00:52:50] ffmpeg.garden.detect           ERROR   : Error while processing the decoded data for stream #0:0
2023-09-09 00:52:50.258289222  [2023-09-09 00:52:50] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-09 00:52:50.258372057  [2023-09-09 00:52:50] frigate.record                 ERROR   : list index out of range
```

### FFprobe output from your camera

```shell
Back Porch
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}}]

Back Yard
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}}]

Pool Road
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}}]

Garden
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}}]

Front Yard
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}}]

Front Door
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}}]

Driveway Front
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}}]

Driveway Pool
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}}]

LPR-41
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":704}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1080,"width":1920}]}}]

LPR Cheltenham
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":704}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1080,"width":1920}]}}]

LPR-Pool
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":704}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1080,"width":1920}]}}]

Doorbell

[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":672,"width":896}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

SCW
