### ISSUE TITLE
[Camera Support]: Reolink camera refusing connection

### ISSUE THREAD

**Issue by Waiker** [blakeblackshear/frigate#7740]
### Describe the problem you are having

Hi everybody. I can’t connect my Relonk RLC-810A camera.

Using VLC I successfully connect to the camera via the link.
![Снимок экрана 2023-09-07 024412](https://github.com/blakeblackshear/frigate/assets/5464086/6f3e80d4-cfa3-42b0-9dee-a5474d9e29b1)

### Version

12.1.10

### Frigate config file

```yaml
mqtt:
     enabled: False
   cameras:
     dummy:
       enabled: true
       ffmpeg:
         inputs:
           - path: rtsp://user:123456@10.10.10.31:554/h264Preview_01_sub
             roles:
               - detect
```

### Relevant log output

```shell
2023-09-09 06:46:13.388444026  [2023-09-09 11:46:13] frigate.video                  ERROR   : dummy: ffmpeg process is not running. exiting capture thread...
2023-09-09 06:46:23.364433299  [2023-09-09 11:46:23] watchdog.dummy                 ERROR   : Ffmpeg process crashed unexpectedly for dummy.
2023-09-09 06:46:23.364769466  [2023-09-09 11:46:23] watchdog.dummy                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-09-09 06:46:23.365082281  [2023-09-09 11:46:23] ffmpeg.dummy.detect            ERROR   : [tcp @ 0x55f6eff96140] Connection to tcp://10.10.10.31:554?timeout=5000000 failed: Connection refused
2023-09-09 06:46:23.365392193  [2023-09-09 11:46:23] ffmpeg.dummy.detect            ERROR   : rtsp://*:*@10.10.10.31:554/h264Preview_01_sub: Connection refused
2023-09-09 06:46:23.387965639  [2023-09-09 11:46:23] frigate.video                  ERROR   : dummy: Unable to read frames from ffmpeg process.
```

### FFprobe output from your camera

```shell
# ffprobe rtsp://user:123456@10.10.10.31:554/h264Preview_01_sub
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[tcp @ 0x55d94db87ec0] Connection to tcp://10.10.10.31:554?timeout=0 failed: Connection refused
rtsp://user:123456@10.10.10.31:554/h264Preview_01_sub: Connection refused
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-810A (last firmware)

**Comment by NickM-27** [comment]
Is there a reason why a new issue was created? Seems like the same issue where the camera is refusing the connection `tcp @ 0x55f6eff96140] Connection to tcp://10.10.10.31:554?timeout=5000000 failed: Connection refused`

**Comment by Waiker** [comment]
> Is there a reason why a new issue was created? Seems like the same issue where the camera is refusing the connection `tcp @ 0x55f6eff96140] Connection to tcp://10.10.10.31:554?timeout=5000000 failed: Connection refused`

yes. I closed the previous problem. I'm trying to use the standard configuration, I hope it will be easier for you to help me with this

**Comment by NickM-27** [comment]
If you can paste the exact thing that's being entered into the frigate config (and then change the password) or show a similar password that would be helpful to see

**Comment by Waiker** [comment]
> If you can paste the exact thing that's being entered into the frigate config (and then change the password) or show a similar password that would be helpful to see

I don't understand what needs to be done. Change password?
Currently my test user:
user;123456

**Comment by NickM-27** [comment]
I did not think the credentials in the config were the actual credentials. 

Only other thing I can think to try is using

```yaml
cameras:
  dummy:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-udp
      inputs:
        - path: rtsp://user:123456@10.10.10.31:554/h264Preview_01_sub
          roles:
            - detect
```

because maybe the camera is refusing tcp connections for whatever reason

**Comment by NickM-27** [comment]
What is your full config?

**Comment by Waiker** [comment]
> ailed: Connection refused

```
   mqtt:
     enabled: False
   cameras:
     dummy:
       enabled: true
       ffmpeg:
         input_args: preset-rtsp-udp
         inputs:
           - path: rtsp://user:123456@10.10.10.31:554/h264Preview_01_sub
             roles:
               - detect
```

**Comment by NickM-27** [comment]
In that case I have no idea why the camera is refusing the connection

**Comment by Waiker** [comment]
> 

To check, I posted my camera on the Internet. I checked my rtsp URL through some sites - everything works.

![Снимок экрана 2023-09-09 181204](https://github.com/blakeblackshear/frigate/assets/5464086/3a36c7fb-5767-4613-a085-80dac0e624dc)

**Comment by NickM-27** [comment]
What happens if you use the `ffprobe` button in the frigate system page

**Comment by Waiker** [comment]
> What happens if you use the `ffprobe` button in the frigate system page

Endlesss loading 
![Снимок экрана 2023-09-09 181204](https://github.com/blakeblackshear/frigate/assets/5464086/48869caa-9f89-4ab3-a2b4-54a89e514cb5)

**Comment by NickM-27** [comment]
Seems either the camera is refused the connection for some unknown reason or there is some network config or filewall rule that is not allowing frigate's connection to the camera to go through

**Comment by Waiker** [comment]
> Seems either the camera is refused the connection for some unknown reason or there is some network config or filewall rule that is not allowing frigate's connection to the camera to go through

Yes, strange things with the network. My PC, ip-camera and frigate server are on the same home network.
The PC sees the ip-camera.
Frigate server on command:
`telnet 10.10.10.31 80` - everything is ok
but if `telnet 10.10.10.31 554` - connection refused.

**Comment by NickM-27** [comment]
well, that means you could use http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password for the detect stream, but for the record stream (requiring rtsp because the 8MP reolink cameras are h265 only) will need that issue to be fixed

**Comment by Waiker** [comment]
> 

error:

`ERROR   : http://10.10.10.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* Invalid data found when processing input`

i opening port 1935

**Comment by NickM-27** [comment]
It uses port 80, forgot to say you need to use `input_args: preset-reolink-http`

**Comment by Waiker** [comment]
> It uses port 80, forgot to say you need to use `input_args: preset-http-reolink`

No changes ((
config :
```
   mqtt:
     enabled: False
   cameras:
     dummy:
       enabled: true
       ffmpeg:
         input_args: preset-http-reolink
         inputs:
           - path: http://10.10.10.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=123456
             roles:
               - detect
```

log:
`http://10.10.10.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* Invalid data found when processing input`
