### ISSUE TITLE
[Support]: Deleted events still on file storage

### ISSUE THREAD

**Issue by uklatt** [blakeblackshear/frigate#7742]
### Describe the problem you are having

Hello,

when I delete events, I assume that the events including the recordings are deleted, but the recordings are still on the hard disk.

From my point of view it would be better if the recordings were also deleted.

Uwe

### Version

0.12.1-367d724

### Frigate config file

```yaml
go2rtc:
  ffmpeg:
    h264: "-rtsp_transport tcp -codec:v libx264 -g:v 15 -preset:v superfast -tune:v zerolatency -profile:v main -level:v 4.1"
  streams:
    AUSSEN: 
      - rtsp://192.168.180.94/11
      - "ffmpeg:rtsp_cam"
    crop: ffmpeg:AUSSEN#video=h264#raw=-vf crop=1920:1080:640:840

mqtt:
  enabled: false
  host: 192.168.178.60
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db

model:
  width: 320
  height: 320

logger:
  default: info
  logs:
    frigate.event: debug

environment_vars:
  TZ: CET

birdseye:
  enabled: True
  quality: 1  # 1..32
  mode: continuous  # objects, motion, continuous

record:
  enabled: true 

snapshots:
  clean_copy: false
  enabled: True
  timestamp: False
  bounding_box: False
  crop: True
  retain:
    default: 7
    mode: active_objects

live:
  height: 1080
  quality: 1

ui:
  live_mode: mse
  use_experimental: False

timestamp_style:
  position: "tl" # tl, tr, bl, br
  format: "%d.%m.%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 1
  effect: shadow # none, solid,shadow

telemetry:
  version_check: false

cameras:
  CAM:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/crop
          input_args: preset-rtsp-restream 
          roles:
            - record
            - detect
    best_image_timeout: 60

    detect:
      enabled: true
      fps: 5
      max_disappeared: 25
      stationary:
        interval: 5  # Wenn stationary, alle n Frames neu detektieren
        threshold: 50  # nach n Frames stationary
    
    record:
      enabled: true
      retain:
        days: 7
        mode: motion # all, motion, active_objects
      events:
        pre_capture: 5
        post_capture: 15
        retain:
          default: 7
          mode: motion # all, motion, active_objects

    objects:
      track:
        - bird
        - cat
    motion:
      frame_height: 150
      mask:
        - 922,530,913,404,1035,247,1113,151,1053,33,683,88,647,493,479,720,873,720,876,630,1280,631,1280,720,0,720,0,0,1280,0,1280,469,1185,446
```

### Relevant log output

```shell
no log
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Frigate stats

```json
{"CAM":{"camera_fps":4.2,"capture_pid":299,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":305,"pid":297,"process_fps":4.2,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"0.0","mem":"0.0"},"106":{"cpu":"0.7","mem":"2.2"},"119":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.5"},"135":{"cpu":"0.0","mem":"0.4"},"136":{"cpu":"0.0","mem":"0.4"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"21753":{"cpu":"0.0","mem":"0.0"},"21769":{"cpu":"0.3","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"283":{"cpu":"0.0","mem":"0.8"},"288":{"cpu":"0.0","mem":"0.1"},"289":{"cpu":"0.0","mem":"1.2"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"0.7","mem":"1.1"},"297":{"cpu":"1.0","mem":"1.1"},"298":{"cpu":"0.0","mem":"0.8"},"299":{"cpu":"2.0","mem":"1.0"},"30":{"cpu":"0.0","mem":"0.0"},"303":{"cpu":"0.0","mem":"0.4"},"305":{"cpu":"4.0","mem":"0.7"},"309":{"cpu":"69.1","mem":"1.1"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"3.7","mem":"0.3"},"MiB":{"cpu":"4070.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.47,"pid":289}},"gpu_usages":{"intel-vaapi":{"gpu":"1.37 %","mem":"- %"}},"service":{"last_updated":1694265626,"latest_version":"disabled","storage":{"/dev/shm":{"free":132.1,"mount_type":"tmpfs","total":134.2,"used":2.1},"/media/frigate/clips":{"free":42865.4,"mount_type":"ext4","total":65204.5,"used":19152.3},"/media/frigate/recordings":{"free":42865.4,"mount_type":"ext4","total":65204.5,"used":19152.3},"/tmp/cache":{"free":1634.6,"mount_type":"tmpfs","total":1639.8,"used":5.3}},"temperatures":{},"uptime":88451,"version":"0.12.1-367d724"}}
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wireless

### Camera make and model

IPCAM C6F0SoZ3N0P6L2
