### ISSUE TITLE
[Support]: After enabling go2rtc, ffmpeg takes longer than 20 seconds to connect to rtsp stream

### ISSUE THREAD

**Issue by mchugh19** [blakeblackshear/frigate#7747]
### Describe the problem you are having

I have been running frigate for over a year now (it's fantastic! Thank you!) with 3 poe ethernet cameras. I just tried to convert my config to use go2rtc, and while I can view the live image with MSE, I see errors about "No frames received from front2 in 20 seconds. Exiting ffmpeg..." in the logs, and the main frigate display shows the black boxes with "No frames have been received" message. 

I tried connecting from my laptop to the frigate host with the same rtsp url I'm using for the ffmpeg recording and detection (rtsp://stratos.local:8554/front1) and it works with VLC, but seems to take about 22-28 seconds to display anything. As this is higher than the 20 second timeout mentioned, this seems to be the source of my troubles. Is there something I'm doing wrong to make the rtsp stream take more than 20 seconds? 

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 10.88.0.1
ffmpeg:
  hwaccel_args: preset-vaapi
  #global_args: -hide_banner -loglevel error
go2rtc:
  streams:
    back1:
      - rtsp://admin:password@back1:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    back1_sub:
      - rtsp://admin:password@back1:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    front1:
      - rtsp://admin:password@front1:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front1_sub:
      - rtsp://admin:password@front1:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    front2:
      - rtsp://admin:password@front2:554/cam/realmonitor?channel=1&subtype=0&unicast=true
    front2_sub:
      - rtsp://admin:password@front2:554/cam/realmonitor?channel=1&subtype=1&unicast=true
  webrtc:
    candidates:
      - 10.88.0.1:8555
      - 10.88.0.2:8555
      - stun:8555
cameras:
  front1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
    zones:  
      approach:
        coordinates: 142,0,123,360,455,360,509,0
      at_door:
        coordinates: 514,0,468,360,640,360,640,0
  front2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front2
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 116,182,332,182,487,173,538,222,502,279,422,312,446,515,476,533,578,375,619,576,704,576,704,0,0,0,0,301
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 15
    objects:
      mask: 
        - 116,182,332,182,538,200,487,173,418,303,445,535,496,497,576,385,704,576,704,0,0,0,0,301
  back1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back1
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 360
      height: 640
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - sheep
        - bear
        - cow
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  retain:
    days: 14
    mode: all
```

### Relevant log output

```shell
2023-09-10 11:50:11.438172805  [INFO] Starting Frigate...
2023-09-10 11:50:12.551554031  [2023-09-10 11:50:12] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-10 11:50:12.579220458  [2023-09-10 11:50:12] peewee_migrate                 INFO    : Starting migrations
2023-09-10 11:50:12.582923705  [2023-09-10 11:50:12] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-10 11:50:12.596260103  [2023-09-10 11:50:12] detector.coral                 INFO    : Starting detection process: 428
2023-09-10 11:50:15.679663074  [2023-09-10 11:50:12] frigate.app                    INFO    : Output process started: 430
2023-09-10 11:50:15.679765477  [2023-09-10 11:50:12] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-09-10 11:50:15.679990576  [2023-09-10 11:50:12] frigate.app                    INFO    : Camera processor started for front1: 436
2023-09-10 11:50:15.680200705  [2023-09-10 11:50:12] frigate.app                    INFO    : Camera processor started for front2: 438
2023-09-10 11:50:15.680415824  [2023-09-10 11:50:12] frigate.app                    INFO    : Camera processor started for back1: 440
2023-09-10 11:50:15.680614914  [2023-09-10 11:50:12] frigate.app                    INFO    : Capture process started for front1: 441
2023-09-10 11:50:15.680823863  [2023-09-10 11:50:12] frigate.app                    INFO    : Capture process started for front2: 444
2023-09-10 11:50:15.681043881  [2023-09-10 11:50:12] frigate.app                    INFO    : Capture process started for back1: 447
2023-09-10 11:50:15.685143862  [2023-09-10 11:50:15] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-09-10 11:51:02.648585958  [2023-09-10 11:51:02] watchdog.front2                INFO    : No frames received from front2 in 20 seconds. Exiting ffmpeg...
2023-09-10 11:51:02.648710275  [2023-09-10 11:51:02] watchdog.front2                INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-10 11:51:02.650819027  [2023-09-10 11:51:02] watchdog.back1                 INFO    : No frames received from back1 in 20 seconds. Exiting ffmpeg...
2023-09-10 11:51:02.651257518  [2023-09-10 11:51:02] watchdog.back1                 INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-10 11:51:02.670258529  [2023-09-10 11:51:02] watchdog.front1                INFO    : No frames received from front1 in 20 seconds. Exiting ffmpeg...
2023-09-10 11:51:02.670607278  [2023-09-10 11:51:02] watchdog.front1                INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-10 11:51:32.678443891  [2023-09-10 11:51:32] watchdog.front2                INFO    : FFmpeg did not exit. Force killing...
2023-09-10 11:51:32.678570547  [2023-09-10 11:51:32] watchdog.back1                 INFO    : FFmpeg did not exit. Force killing...
2023-09-10 11:51:32.698513898  [2023-09-10 11:51:32] watchdog.front1                INFO    : FFmpeg did not exit. Force killing...



go2rtc log

2023-09-10 11:50:11.437689178  [INFO] Preparing go2rtc config...
2023-09-10 11:50:11.617499018  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-09-10 11:50:11.638466223  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-09-10 11:50:11.638470727  [INFO] Starting go2rtc...
2023-09-10 11:50:11.723731531  11:50:11.721 INF go2rtc version 1.7.0 linux/amd64
2023-09-10 11:50:11.723737416  11:50:11.722 INF [api] listen addr=0.0.0.0:1984
2023-09-10 11:50:11.723739461  11:50:11.722 INF [rtsp] listen addr=0.0.0.0:8554
2023-09-10 11:50:11.723745543  11:50:11.722 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-09-10 11:50:21.439299548  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
# ffprobe rtsp://localhost:8554/front1

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55744c6f9140] method SETUP failed: 461 Unsupported transport
[h264 @ 0x55744c6ff2c0] reference picture missing during reorder
[h264 @ 0x55744c6ff2c0] Missing reference picture, default is 65934
[h264 @ 0x55744c6ff2c0] reference picture missing during reorder
[h264 @ 0x55744c6ff2c0] Missing reference picture, default is 66034
Input #0, rtsp, from 'rtsp://localhost:8554/front1':
  Metadata:
    title           : go2rtc/1.7.0
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1520 [SAR 1:1 DAR 168:95], 25 fps, 25 tbr, 90k tbn
```

### Frigate stats

```json
{
    "back1": {
        "camera_fps": 0,
        "capture_pid": 447,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 453,
        "pid": 440,
        "process_fps": 0,
        "skipped_fps": 0
    },
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "10": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "11": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "19": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "20": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "21": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "22": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "23": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "36": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "37": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "75": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "76": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "77": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "84": {
            "cpu": "7.0",
            "mem": "0.2"
        },
        "92": {
            "cpu": "0.0",
            "mem": "1.3"
        },
        "93": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "111": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "129": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "130": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "131": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "137": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "152": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "174": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "207": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "239": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "421": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "427": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "428": {
            "cpu": "0.0",
            "mem": "0.6"
        },
        "430": {
            "cpu": "0.0",
            "mem": "0.6"
        },
        "436": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "437": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "438": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "439": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "440": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "441": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "444": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "447": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "450": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "453": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "456": {
            "cpu": "0.7",
            "mem": "0.2"
        },
        "460": {
            "cpu": "0.3",
            "mem": "0.2"
        },
        "461": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "462": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "468": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "471": {
            "cpu": "0.3",
            "mem": "0.2"
        },
        "675": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "743": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "776": {
            "cpu": "0.3",
            "mem": "0.0"
        },
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.2"
        },
        "MiB": {
            "cpu": "10892.1",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top": {
            "cpu": "users,",
            "mem": "load"
        }
    },
    "detection_fps": 0,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 10,
            "pid": 428
        }
    },
    "front1": {
        "camera_fps": 0,
        "capture_pid": 441,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 468,
        "pid": 436,
        "process_fps": 0,
        "skipped_fps": 0
    },
    "front2": {
        "camera_fps": 0,
        "capture_pid": 444,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 450,
        "pid": 438,
        "process_fps": 0,
        "skipped_fps": 0
    },
    "gpu_usages": {
        "amd-vaapi": {
            "gpu": "0.00 %",
            "mem": "17.57 %"
        }
    },
    "service": {
        "last_updated": 1694343196,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 133.6,
                "mount_type": "tmpfs",
                "total": 134.2,
                "used": 0.6
            },
            "/media/frigate/clips": {
                "free": 2562289.4,
                "mount_type": "xfs",
                "total": 3998832.5,
                "used": 1436543.1
            },
            "/media/frigate/recordings": {
                "free": 2562289.4,
                "mount_type": "xfs",
                "total": 3998832.5,
                "used": 1436543.1
            },
            "/tmp/cache": {
                "free": 985.4,
                "mount_type": "tmpfs",
                "total": 1000,
                "used": 14.6
            }
        },
        "temperatures": {},
        "uptime": 184,
        "version": "0.12.1-367d724"
    }
}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision IPC-T2347G-LU

### Any other information that may be helpful

I tried editing the video.py file to increase the timeout to 50 rather than 20, but this did not make any difference. I have also updated go2rtc to the latest 1.7.0, but this also did not help.
