### ISSUE TITLE
Delay streaming in HASSIO

### ISSUE THREAD

**Issue by goodsale** [blakeblackshear/frigate#7752]
### Describe the problem you are having

I configured a camera with "ONVIF" support and frigate in homeassistant as a peephole in the front door.

When the doorbell is pressed I take the video stream and run it on a 2nd generation nest hub (google) to see who rings the doorbell.

Given that frigate works very well and records every human movement correctly, the video streaming played on the NEST HUB is delayed by over 30 seconds, making it impossible to immediately see who is playing.

I previously had "Motioneye" which had absolutely no this problem.

Is there any particular configuration that can help decrease the video stream playback delay in Homeassistant?

I attach my frigate.Yaml

### Version

Frigate (Full Access) Beta (0.12.0)

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  host: xxxxx
  user: xxxxx
  password: xxxxx
  port: xxxx
cameras:
  Spioncino: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxxxxx@192.168.2.66:554/ch0_0.264
          roles:
            - detect
            - record
      hwaccel_args: 
        - -c:v 
        - h264_v4l2m2m

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 40
          mode: active_objects
        pre_capture: 8
        post_capture: 5


    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 15
birdseye:
  enabled: false
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

no brand

**Comment by NickM-27** [comment]
where are you getting the stream from in HA? You don't have go2rtc configured so the stream isn't coming from frigate itself

**Comment by goodsale** [comment]
I can see the camera in the Homeassistant front end without problems with this configuration file

My problem is the delay in viewing the video.

How can I configure go2rtc?

**Comment by NickM-27** [comment]
> I can see the camera in the Homeassistant front end without problems with this configuration file

all it is showing via the frigate integration is a snapshot that updates once per second, there is no actual camera stream

it is not clear what you are using in HA (as in what service call) to show the stream on the hub

> How can I configure go2rtc?

https://docs.frigate.video/guides/configuring_go2rtc

**Comment by goodsale** [comment]
Thank you
I had already seen these instructions and had tried to modify the configuration file as follows.
in frigate after configuring go2rtc I see the "mse" and "webrtc" entries.
But now how do I configure my camera on Homeassistant?
Even with the configuration file modified like this the flow is still very late.

```
detectors:
  cpu1:
    type: cpu
mqtt:
  host: xxxxxxxxxxx
  user: xxxxxxxxx
  password: xxxxxxxxxxxxx
  port: xxxxxxxxxxxxx
go2rtc:
  streams:
    rtsp_spioncino:
      - rtsp://xxxxxx:xxxxxxx@192.168.2.66:554/ch0_1.264
cameras:
  Spioncino: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxx:xxxxxx@192.168.2.66:554/ch0_0.264
          roles:
            - detect
            - record
      hwaccel_args: 
        - -c:v 
        - h264_v4l2m2m

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 40
          mode: active_objects
        pre_capture: 8
        post_capture: 5
    live:
      stream_name: rtsp_spioncino 


    detect:
      width: 1920 
      height: 1080 
      fps: 15
birdseye:
  enabled: false
```

**Comment by NickM-27** [comment]
The name of the stream and camera don't match, which is required for the frigate integration

**Comment by goodsale** [comment]
this is correct?

```
.......................................................

go2rtc:
  streams:
    spioncino:
      - rtsp://xxxxxx:xxxxxxx@192.168.2.66:554/ch0_1.264
cameras:
  Spioncino: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxx:xxxxxx@192.168.2.66:554/ch0_0.264
          roles:
            - detect
            - record
      hwaccel_args: 
        - -c:v 
        - h264_v4l2m2m

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 40
          mode: active_objects
        pre_capture: 8
        post_capture: 5
    live:
      stream_name: spioncino 

.................................................................

```

**Comment by NickM-27** [comment]
one is capitalized the other is not

**Comment by goodsale** [comment]
edited as below but still the same problem
```
.......................................
go2rtc:
  streams:
    Spioncino:
      - rtsp://xxxxx:xxx@192.168.2.66:554/ch0_1.264
cameras:
  Spioncino: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxxx@192.168.2.66:554/ch0_0.264
          roles:
            - detect
            - record
      hwaccel_args: 
        - -c:v 
        - h264_v4l2m2m

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 40
          mode: active_objects
        pre_capture: 8
        post_capture: 5
    live:
      stream_name: Spioncino 

    detect:
      width: 1920 
      height: 1080 
      fps: 15
....................................................
```

**Comment by NickM-27** [comment]
so what service / yaml are you using to open the stream on the hub?

**Comment by goodsale** [comment]
This is my "test" automation.

The automation works but streaming have a delay 30sec or more.

Homeassistant makes me choose the cam created in frigate correctly and offers me by default "media_content_type: application/vnd.apple.mpegurl"

Do these parameters need to be changed?

```
alias: test_streaming
description: []
trigger:
  - platform: device
    type: turned_on
    device_id: dfe831c891a05bdde58792b457272c71
    entity_id: a05604c5c7d807d03aaefcc42520c73e
    domain: light
condition: []
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.nest_ingresso
    data:
      media_content_id: media-source://camera/camera.spioncino
      media_content_type: application/vnd.apple.mpegurl
    metadata:
      title: null
      thumbnail: /api/camera_proxy/camera.spioncino
      media_class: video
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://camera
  - delay:
      hours: 0
      minutes: 0
      seconds: 40
      milliseconds: 0
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.nest_ingresso
mode: single

```

**Comment by NickM-27** [comment]
> Homeassistant makes me choose the cam created in frigate correctly and offers me by default "media_content_type: application/vnd.apple.mpegurl"

This means the streaming is done with HLS, which is known to have latency. You will likely want to use the `WebRTC Camera` custom integration to cast the stream as webrtc to the nest hub

**Comment by goodsale** [comment]
I tried installing the RTSPtoWeb - WebRTC add-on and its integration.

in the link http://homeassistant.local:8083/ I see the camera configured in frigate.
The video playing now is lag-free and even in Lovelace I was able to create the card with the correct live video stream and without any lag (awesome!)

I still have the problem in the automations where all the cameras disappeared after installing the component.
How do I tell in the automation to take the video stream from the correct source and run it on the nest_Hub?
Now my camera is disabled in the automations (it tells me that "camera.spioncino" is incompatible and is not made visible).

I assume that here I have tu put  a link to the new server created by the integration, but which one?

Thanks!!
```
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.nest_ingresso
    data:
      media_content_id: media-source://camera/camera.spioncino
      media_content_type: application/vnd.apple.mpegurl
    metadata:
      title: null
      thumbnail: /api/camera_proxy/camera.spioncino
      media_class: video
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://camera
```

**Comment by NickM-27** [comment]
That's not the integration I was referring to, I was referring to WebRTC Camera which is in HACS and has a custom service

**Comment by goodsale** [comment]
Sorry... but now I tried what you say via HACS.

I install the component and as integration it points me to the frigate server like go2rtc.
It tells me everything is configured correctly, but no camera and I don't know what I should do!!

But is it possible that it is so complicated to do a decent live streaming in home assistant???

**Comment by NickM-27** [comment]
Now you just need to use the WebRTC.dash_cast service with the url field set to `Spioncino` and it will automatically find the stream and send it

**Comment by goodsale** [comment]
Only write "Dash cast" on the nest screen... 

```
service: webrtc.dash_cast
data:
  entity_id: media_player.nest_ingresso
  entity: camera.spioncino
```

**Comment by NickM-27** [comment]
you may need to update the go2rtc in frigate https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by goodsale** [comment]
updated as log below to version 1.7.1
but nothing has changed.

only thing I noticed is that the video in frigate in WEBRTC mode is only played on the internal network. Could this be the problem?

MSE and JSMPEG work always,

```
2023-09-12 09:23:14.380449652  [INFO] Preparing go2rtc config...
2023-09-12 09:23:15.388721093  [INFO] Got IP address from supervisor: 192.168.2.60
2023-09-12 09:23:15.716610052  [INFO] Got WebRTC port from supervisor: 8555
2023-09-12 09:23:18.518130302  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-09-12 09:23:18.518172358  [INFO] Starting go2rtc...
2023-09-12 09:23:18.831877728  11:23:18.830 INF go2rtc version 1.7.1 linux/arm64
2023-09-12 09:23:18.831889488  11:23:18.831 INF [api] listen addr=0.0.0.0:1984
2023-09-12 09:23:18.834079798  11:23:18.833 INF [rtsp] listen addr=0.0.0.0:8554
2023-09-12 09:23:18.835068158  11:23:18.834 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-09-12 09:23:24.397386497  [INFO] Starting go2rtc healthcheck service...
```

**Comment by NickM-27** [comment]
More setup is required: https://docs.frigate.video/configuration/live#webrtc-extra-configuration

**Comment by goodsale** [comment]
Added this lines in my configuration:

```
  webrtc:
    candidates:
      - 192.168.2.60:8555
      - stun:8555     
``` 

Now I can see WEBRTC stream in local and out by frigate.

But the stream in nest hub  not work.

NEW CONFIGURATION
```
go2rtc:
  streams:
    spioncino:
      - rtsp://xxxxxxxx:xxxxxxxx@192.168.2.66:554/ch0_0.264
  webrtc:
    candidates:
      - 192.168.2.60:8555
      - stun:8555      
cameras:
  spioncino: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxx:xxxxxxxx@192.168.2.66:554/ch0_0.264
          roles:
            - detect
            - record
      hwaccel_args: 
        - -c:v 
        - h264_v4l2m2m

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 40
          mode: active_objects
        pre_capture: 8
        post_capture: 5
    live:
      stream_name: spioncino

    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 15
``` 

LOG go2rtc
```
2023-09-12 20:33:06.053297507  [INFO] Preparing go2rtc config...
2023-09-12 20:33:06.240683625  [INFO] Got IP address from supervisor: 192.168.2.60
2023-09-12 20:33:06.386126448  [INFO] Got WebRTC port from supervisor: 8555
2023-09-12 20:33:07.082468540  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-09-12 20:33:07.237528724  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-09-12 20:33:07.237540057  [INFO] Starting go2rtc...
2023-09-12 20:33:07.470666792  22:33:07.470 INF go2rtc version 1.7.1 linux/arm64
2023-09-12 20:33:07.471973854  22:33:07.471 INF [api] listen addr=0.0.0.0:1984
2023-09-12 20:33:07.473077807  22:33:07.472 INF [rtsp] listen addr=0.0.0.0:8554
2023-09-12 20:33:07.474018095  22:33:07.473 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-09-12 20:33:16.067736017  [INFO] Starting go2rtc healthcheck service...
```
