### ISSUE TITLE
[Support]: Can't get container to start on alpine linux

### ISSUE THREAD

**Issue by iridris** [blakeblackshear/frigate#7760]
### Describe the problem you are having

I'm trying to get Frigate to run in Docker on Alpine linux, which is a VM running in ESXi. Basic install of alpine, docker, and frigate, just trying to get it up and running before doing any specific configuration.

I'm getting errors when trying to start the container and haven't been able to find anything about how to resolve so far.

docker-compose.yml:
```
/docker/frigate # cat docker-compose.yml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: no
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/data/config/config.yml:/config/config.yml
      - /docker/frigate/data/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

config.yml is the default base config from documentation.

### Version

12.1

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
/docker/frigate # docker compose up
[+] Running 2/1
 ✔ Network frigate_default  Created                                                                                                                                                                          0.0s
 ✔ Container frigate        Created                                                                                                                                                                          0.1s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | 2023-09-11 12:58:19.794037245  [INFO] Preparing go2rtc config...
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-09-11 12:58:19.797202201  [INFO] Starting NGINX...
frigate  | 2023-09-11 12:58:19.797987252  [INFO] Starting Frigate...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-09-11 12:58:20.303289973  [INFO] Starting go2rtc...
frigate  | 2023-09-11 12:58:20.369629049  12:58:20.369 INF go2rtc version 1.2.0 linux/amd64
frigate  | 2023-09-11 12:58:20.372744541  12:58:20.372 INF [api] listen addr=:1984
frigate  | 2023-09-11 12:58:20.373051670  12:58:20.372 INF [rtsp] listen addr=:8554
frigate  | 2023-09-11 12:58:20.373053455  12:58:20.372 INF [srtp] listen addr=:8443
frigate  | 2023-09-11 12:58:20.373252364  12:58:20.373 INF [webrtc] listen addr=:8555
frigate  | 2023-09-11 12:58:20.923959489  Error importing detector runtime: /usr/lib/x86_64-linux-gnu/libffi.so.7: invalid ELF header
frigate  | 2023-09-11 12:58:20.925634797  Error importing detector runtime: /usr/lib/x86_64-linux-gnu/libffi.so.7: invalid ELF header
frigate  | 2023-09-11 12:58:21.149344847  Error importing detector runtime: /usr/lib/x86_64-linux-gnu/libffi.so.7: invalid ELF header
frigate  | 2023-09-11 12:58:21.177064870  Traceback (most recent call last):
frigate  | 2023-09-11 12:58:21.177067935    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
frigate  | 2023-09-11 12:58:21.177652523      return _run_code(code, main_globals, None,
frigate  | 2023-09-11 12:58:21.177689662    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
frigate  | 2023-09-11 12:58:21.177928912      exec(code, run_globals)
frigate  | 2023-09-11 12:58:21.177931158    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
frigate  | 2023-09-11 12:58:21.178405151      from frigate.app import FrigateApp
frigate  | 2023-09-11 12:58:21.178406682    File "/opt/frigate/frigate/app.py", line 17, in <module>
frigate  | 2023-09-11 12:58:21.179093693      from frigate.comms.dispatcher import Communicator, Dispatcher
frigate  | 2023-09-11 12:58:21.179096483    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
frigate  | 2023-09-11 12:58:21.179328978      from frigate.config import FrigateConfig
frigate  | 2023-09-11 12:58:21.179330496    File "/opt/frigate/frigate/config.py", line 853, in <module>
frigate  | 2023-09-11 12:58:21.179897535      class FrigateConfig(FrigateBaseModel):
frigate  | 2023-09-11 12:58:21.179899131    File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
frigate  | 2023-09-11 12:58:21.180148715    File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
frigate  | 2023-09-11 12:58:21.180220315    File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
frigate  | 2023-09-11 12:58:21.180432145    File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
frigate  | 2023-09-11 12:58:21.180539703    File "pydantic/fields.py", line 758, in pydantic.fields.ModelField._type_analysis
frigate  | 2023-09-11 12:58:21.180737495    File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
frigate  | 2023-09-11 12:58:21.180793152    File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
frigate  | 2023-09-11 12:58:21.180975308    File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
frigate  | 2023-09-11 12:58:21.181040121    File "pydantic/fields.py", line 629, in pydantic.fields.ModelField._type_analysis
frigate  | 2023-09-11 12:58:21.181285482    File "pydantic/fields.py", line 633, in pydantic.fields.ModelField._type_analysis
frigate  | 2023-09-11 12:58:21.181462813  TypeError: `discriminator` can only be used with `Union` type with more than one variant
frigate  | 2023-09-11 12:58:21.281765693  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-09-11 12:58:21.295183961  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2023-09-11 12:58:21.383299549  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2023-09-11 12:58:21.387454431  exit OK
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2023-09-11 12:58:21.391289727  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 1
```

### FFprobe output from your camera

```shell
N/A, haven't even gotten this far
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest
