### ISSUE TITLE
[Config Support]: 502 Errors

### ISSUE THREAD

**Issue by memattyg** [blakeblackshear/frigate#7787]
### Describe the problem you are having

I get the following errors multiple times a day in the system log:

Error fetching information from http://192.168.x.y:5001/api/stats: Cannot connect to host 192.168.x.y:5001 ssl:default [Connect call failed ('192.168.x.y', 5001)]
Error fetching information from http://192.168.x.y:5001/api/stats: 502, message='Bad Gateway', url=URL('http://192.168.x.y:5001/api/stats')
Error fetching information from http://192.168.x.y:5001/api/stats: Server disconnected

I saw another thread that to change the 5000 port to something else if also running Wyze Docker Bridge, I tried that (5001) but I still receive this error.  The integration is configured onto port 5001.  I am wondering if I need to alter a different port in the addon configuration?

### Version

12.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.y
  port: 1883
  user: user
  password: password

detectors:
    coral:
      type: edgetpu
      device: usb

go2rtc:
  streams:
    FrontDoor: 
      - rtsp://user:password@192.168.x.z:554/h264Preview_01_main
    FrontDoor_sub: 
      - rtsp://user:password@192.168.x.z:554/h264Preview_01_sub

cameras:
##########################################
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user.password@homeassistant.local:8554/driveway-cam-sub
          roles:    
            - detect
        - path: rtsp://user.password@homeassistant.local:8554/driveway-cam
          roles:    
            - record
    detect:
      width: 640
      height: 480
      fps: 5   
    record:
      enabled: true    
      retain:
        days: 1
        mode: motion
      events:
        pre_capture: 5
        post_capture: 15
        retain:
          default: 2
          mode: active_objects
          objects:
            person: 3
            car: 2
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 640,0,0,0,0,302,271,302,474,301,640,293
        person:
          mask:
            - 640,0,0,0,0,302,271,302,474,301,640,293
            - 428,233,480,233,491,310,429,311
    motion:
      mask:
        - 454,480,640,480,640,437,453,435
        - 640,0,0,0,0,302,271,302,474,301,640,293
##################################################
  FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontDoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 3
        post_capture: 10
        retain:
          default: 2
          mode: active_objects
          objects:
            person: 7
      filters:
        car:
          mask:
            - 640,0,640,275,464,282,374,293,211,298,103,297,0,288,0,0
        person:
          mask:
            - 640,0,640,275,464,282,374,293,211,298,103,297,0,288,0,0
    zones:
      zone1:
        coordinates: 82,377,236,394,233,354,410,328,467,366,563,317,640,313,640,480,244,480,74,480
    motion:
      mask:
        - 640,36,640,0,0,0,0,31
####################################################
objects:
  track:
    - person
    - car
###################################################
snapshots:
    enabled: true
    retain:
        default: 2
        objects:
            car: 5
            person: 7
###################################################
```

### Relevant log output

```shell
Error fetching information from http://192.168.x.y:5001/api/stats: Cannot connect to host 192.168.x.y:5001 ssl:default [Connect call failed ('192.168.x.y', 5001)]
Error fetching information from http://192.168.x.y:5001/api/stats: 502, message='Bad Gateway', url=URL('http://192.168.x.y:5001/api/stats')
Error fetching information from http://192.168.x.y:5001/api/stats: Server disconnected
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

I tried changing the port listed as 5000 in the config to 5001 since I saw that it could conflict with the Docker Wyze Bridge, but that hasn't alleviated the issue.
