### ISSUE TITLE
[HW Accel Support]: QSV Device not found 

### ISSUE THREAD

**Issue by WereCatf** [blakeblackshear/frigate#7788]
### Describe the problem you are having

Ffmpeg appears to insist on trying to use /dev/dri/renderD128, when I have configured in docker-compose.yml the device as renderD129. **I do not have a /dev/dri/renderD128 at all, there is only the /dev/dri/renderD129**, which appears to be the problem as the code doesn't actually check what is available and just assumes that the first available card would be renderD128.

### Version

No idea, can't get that far

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

cameras:
  tapo2:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@tapo2.elektrik.link:554/stream1
          roles:
            - detect
      hwaccel_args: preset-intel-qsv-h264
    detect:
      enabled: False
      width: 1920
      height: 1080
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    # privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD129
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
Creating network "frigate_default" with the default driver
Creating frigate ... done
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | 2023-09-13 09:10:16.191523426  [INFO] Preparing go2rtc config...
frigate    | 2023-09-13 09:10:16.195073765  [INFO] Starting Frigate...
frigate    | 2023-09-13 09:10:16.199338307  [INFO] Starting NGINX...
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2023-09-13 09:10:16.795545319  [INFO] Starting go2rtc...
frigate    | 2023-09-13 09:10:16.897307822  09:10:16.897 INF go2rtc version 1.2.0 linux/amd64
frigate    | 2023-09-13 09:10:16.897547105  09:10:16.897 INF [api] listen addr=:1984
frigate    | 2023-09-13 09:10:16.897900666  09:10:16.897 INF [rtsp] listen addr=:8554
frigate    | 2023-09-13 09:10:16.898173161  09:10:16.898 INF [srtp] listen addr=:8443
frigate    | 2023-09-13 09:10:16.898424309  09:10:16.898 INF [webrtc] listen addr=:8555
frigate    | 2023-09-13 09:10:17.577277192  [2023-09-13 09:10:17] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
frigate    | 2023-09-13 09:10:17.585885690  [2023-09-13 09:10:17] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
frigate    | 2023-09-13 09:10:17.588469903  [2023-09-13 09:10:17] peewee_migrate                 INFO    : Starting migrations
frigate    | 2023-09-13 09:10:17.591561972  [2023-09-13 09:10:17] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | 2023-09-13 09:10:17.601688856  [2023-09-13 09:10:17] frigate.app                    INFO    : Output process started: 580
frigate    | 2023-09-13 09:10:17.601770290  [2023-09-13 09:10:17] detector.ov                    INFO    : Starting detection process: 578
frigate    | 2023-09-13 09:10:17.605382293  [2023-09-13 09:10:17] frigate.app                    INFO    : Camera processor started for tapo2: 583
frigate    | 2023-09-13 09:10:17.608860216  [2023-09-13 09:10:17] frigate.app                    INFO    : Capture process started for tapo2: 585
frigate    | 2023-09-13 09:10:17.622725721  [2023-09-13 09:10:17] frigate.video                  ERROR   : tapo2: Unable to read frames from ffmpeg process.
frigate    | 2023-09-13 09:10:17.622849617  [2023-09-13 09:10:17] frigate.video                  ERROR   : tapo2: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-09-13 09:10:21.533934294  [2023-09-13 09:10:21] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
frigate    | 2023-09-13 09:10:21.534013275  [2023-09-13 09:10:21] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
frigate    | 2023-09-13 09:10:21.534146649  [2023-09-13 09:10:21] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
frigate    | 2023-09-13 09:10:26.198431423  [INFO] Starting go2rtc healthcheck service...
frigate    | 2023-09-13 09:10:37.627174448  [2023-09-13 09:10:37] watchdog.tapo2                 ERROR   : Ffmpeg process crashed unexpectedly for tapo2.
frigate    | 2023-09-13 09:10:37.627552228  [2023-09-13 09:10:37] watchdog.tapo2                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2023-09-13 09:10:37.627864575  [2023-09-13 09:10:37] ffmpeg.tapo2.detect            ERROR   : [AVHWDeviceContext @ 0x558226016740] No VA display found for device /dev/dri/renderD128.
frigate    | 2023-09-13 09:10:37.628508360  [2023-09-13 09:10:37] ffmpeg.tapo2.detect            ERROR   : Device creation failed: -22.
frigate    | 2023-09-13 09:10:37.628525854  [2023-09-13 09:10:37] ffmpeg.tapo2.detect            ERROR   : Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Invalid argument
frigate    | 2023-09-13 09:10:37.629049418  [2023-09-13 09:10:37] ffmpeg.tapo2.detect            ERROR   : Error parsing global options: Invalid argument
frigate    | 2023-09-13 09:10:37.675708377  [2023-09-13 09:10:37] frigate.video                  ERROR   : tapo2: Unable to read frames from ffmpeg process.
frigate    | 2023-09-13 09:10:37.676245014  [2023-09-13 09:10:37] frigate.video                  ERROR   : tapo2: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-09-13 09:10:47.655407135  [2023-09-13 09:10:47] watchdog.tapo2                 ERROR   : Ffmpeg process crashed unexpectedly for tapo2.
frigate    | 2023-09-13 09:10:47.655667285  [2023-09-13 09:10:47] watchdog.tapo2                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2023-09-13 09:10:47.655956573  [2023-09-13 09:10:47] ffmpeg.tapo2.detect            ERROR   : [AVHWDeviceContext @ 0x562767af4740] No VA display found for device /dev/dri/renderD128.
frigate    | 2023-09-13 09:10:47.656218003  [2023-09-13 09:10:47] ffmpeg.tapo2.detect            ERROR   : Device creation failed: -22.
frigate    | 2023-09-13 09:10:47.656282544  [2023-09-13 09:10:47] ffmpeg.tapo2.detect            ERROR   : Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Invalid argument
frigate    | 2023-09-13 09:10:47.656490648  [2023-09-13 09:10:47] ffmpeg.tapo2.detect            ERROR   : Error parsing global options: Invalid argument
frigate    | 2023-09-13 09:10:47.705924428  [2023-09-13 09:10:47] frigate.video                  ERROR   : tapo2: Unable to read frames from ffmpeg process.
frigate    | 2023-09-13 09:10:47.706268050  [2023-09-13 09:10:47] frigate.video                  ERROR   : tapo2: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-09-13 09:10:57.685497562  [2023-09-13 09:10:57] watchdog.tapo2                 ERROR   : Ffmpeg process crashed unexpectedly for tapo2.
frigate    | 2023-09-13 09:10:57.686004210  [2023-09-13 09:10:57] watchdog.tapo2                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2023-09-13 09:10:57.686344762  [2023-09-13 09:10:57] ffmpeg.tapo2.detect            ERROR   : [AVHWDeviceContext @ 0x55b04faa3740] No VA display found for device /dev/dri/renderD128.
frigate    | 2023-09-13 09:10:57.686595428  [2023-09-13 09:10:57] ffmpeg.tapo2.detect            ERROR   : Device creation failed: -22.
frigate    | 2023-09-13 09:10:57.686681038  [2023-09-13 09:10:57] ffmpeg.tapo2.detect            ERROR   : Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Invalid argument
frigate    | 2023-09-13 09:10:57.686903950  [2023-09-13 09:10:57] ffmpeg.tapo2.detect            ERROR   : Error parsing global options: Invalid argument
frigate    | 2023-09-13 09:10:57.729664383  [2023-09-13 09:10:57] frigate.video                  ERROR   : tapo2: Unable to read frames from ffmpeg process.
frigate    | 2023-09-13 09:10:57.730302896  [2023-09-13 09:10:57] frigate.video                  ERROR   : tapo2: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-09-13 09:11:07.713134041  [2023-09-13 09:11:07] watchdog.tapo2                 ERROR   : Ffmpeg process crashed unexpectedly for tapo2.
frigate    | 2023-09-13 09:11:07.713627172  [2023-09-13 09:11:07] watchdog.tapo2                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2023-09-13 09:11:07.714012816  [2023-09-13 09:11:07] ffmpeg.tapo2.detect            ERROR   : [AVHWDeviceContext @ 0x55a55a890740] No VA display found for device /dev/dri/renderD128.
frigate    | 2023-09-13 09:11:07.714299809  [2023-09-13 09:11:07] ffmpeg.tapo2.detect            ERROR   : Device creation failed: -22.
frigate    | 2023-09-13 09:11:07.714534374  [2023-09-13 09:11:07] ffmpeg.tapo2.detect            ERROR   : Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Invalid argument
frigate    | 2023-09-13 09:11:07.714809383  [2023-09-13 09:11:07] ffmpeg.tapo2.detect            ERROR   : Error parsing global options: Invalid argument
frigate    | 2023-09-13 09:11:07.764321857  [2023-09-13 09:11:07] frigate.video                  ERROR   : tapo2: Unable to read frames from ffmpeg process.
frigate    | 2023-09-13 09:11:07.764924200  [2023-09-13 09:11:07] frigate.video                  ERROR   : tapo2: ffmpeg process is not running. exiting capture thread...
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | s6-rc: info: service legacy-services successfully stopped
frigate    | s6-rc: info: service nginx: stopping
frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate    | 2023-09-13 09:11:09.956049292  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate    | 2023-09-13 09:11:10.104872427  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate    | s6-rc: info: service nginx successfully stopped
frigate    | s6-rc: info: service nginx-log: stopping
frigate    | s6-rc: info: service frigate: stopping
frigate    | 2023-09-13 09:11:10.108565306  [2023-09-13 09:11:10] frigate.app                    INFO    : Stopping...
frigate    | 2023-09-13 09:11:10.109083490  [2023-09-13 09:11:10] detector.ov                    INFO    : Signal to exit detection process...
frigate    | 2023-09-13 09:11:10.109517078  [2023-09-13 09:11:10] root                           INFO    : Waiting for detection process to exit gracefully...
frigate    | 2023-09-13 09:11:10.109680040  [2023-09-13 09:11:10] frigate.stats                  INFO    : Exiting stats emitter...
frigate    | s6-rc: info: service nginx-log successfully stopped
frigate    | 2023-09-13 09:11:10.110388990  [2023-09-13 09:11:10] frigate.events                 INFO    : Exiting event cleanup...
frigate    | 2023-09-13 09:11:10.110603487  [2023-09-13 09:11:10] frigate.record                 INFO    : Exiting recording cleanup...
frigate    | 2023-09-13 09:11:10.111100717  [2023-09-13 09:11:10] frigate.record                 INFO    : Exiting recording maintenance...
frigate    | 2023-09-13 09:11:10.111277593  [2023-09-13 09:11:10] frigate.storage                INFO    : Exiting storage maintainer...
frigate    | 2023-09-13 09:11:10.111506521  [2023-09-13 09:11:10] frigate.watchdog               INFO    : Exiting watchdog...
frigate    | 2023-09-13 09:11:10.596919457  [2023-09-13 09:11:10] detector.ov                    INFO    : Exited detection process...
frigate    | 2023-09-13 09:11:10.675100058  [2023-09-13 09:11:10] frigate.object_processing      INFO    : Exiting object processor...
frigate    | 2023-09-13 09:11:10.723185481  [2023-09-13 09:11:10] root                           INFO    : Detection process has exited...
frigate    | 2023-09-13 09:11:10.967371808  [2023-09-13 09:11:10] frigate.events                 INFO    : Exiting event processor...
frigate    | 2023-09-13 09:11:11.196770861  [2023-09-13 09:11:11] frigate.comms.ws               INFO    : Exiting websocket client...
frigate    | 2023-09-13 09:11:11.197154243  [2023-09-13 09:11:11] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate    | 2023-09-13 09:11:11.200238499  [2023-09-13 09:11:11] watchdog.tapo2                 INFO    : Terminating the existing ffmpeg process...
frigate    | 2023-09-13 09:11:11.200587765  [2023-09-13 09:11:11] watchdog.tapo2                 INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2023-09-13 09:11:11.692670876  [2023-09-13 09:11:11] frigate.video                  INFO    : tapo2: exiting subprocess
frigate    | 2023-09-13 09:11:12.258777173  [2023-09-13 09:11:12] frigate.output                 INFO    : exiting output process...
frigate    | 2023-09-13 09:11:13.707217800  [INFO] Service Frigate exited with code 0 (by signal 0)
frigate    | s6-rc: info: service frigate successfully stopped
frigate    | s6-rc: info: service go2rtc: stopping
frigate    | s6-rc: info: service frigate-log: stopping
frigate    | 2023-09-13 09:11:13.721517287  exit OK
frigate    | s6-rc: info: service frigate-log successfully stopped
frigate    | 2023-09-13 09:11:13.753896707  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate    | s6-rc: info: service go2rtc successfully stopped
frigate    | s6-rc: info: service go2rtc-log: stopping
frigate    | s6-rc: info: service go2rtc-log successfully stopped
frigate    | s6-rc: info: service log-prepare: stopping
frigate    | s6-rc: info: service s6rc-fdholder: stopping
frigate    | s6-rc: info: service log-prepare successfully stopped
frigate    | s6-rc: info: service legacy-cont-init: stopping
frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate    | s6-rc: info: service legacy-cont-init successfully stopped
frigate    | s6-rc: info: service fix-attrs: stopping
frigate    | s6-rc: info: service fix-attrs successfully stopped
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
```

### FFprobe output from your camera

```shell
The camera isn't the issue.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

TP-link Tapo c100

**Comment by NickM-27** [comment]
> which appears to be the problem as the code doesn't actually check what is available and just assumes that the first available card would be renderD128.

That is incorrect, the code checks when there are multiple drivers to see which will work. however, since there is only one available it assumes it is renderD128.

All that being said, the fix is very simple, you can update your computer to map to 128

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    # privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
