### ISSUE TITLE
[Support]: MQTT 'available' topic set 'offline' through LWT?

### ISSUE THREAD

**Issue by Dave-Baldwin** [blakeblackshear/frigate#7833]
### Describe the problem you are having

I am confused about how to use the MQTT 'frigate/available' topic. From looking in MQTT Explorer, it is not updated frequently.

The docs indicate that a value of 'offline' will be published right before Frigate shuts down, but this just isn't really reliable - if there is a crash that prevents that intended publish, or the machine hosting Frigate suffers a power outage.

Is Frigate configured to connect to the MQTT broker with a Last Will & Testament set to publish 'offline' into the 'frigate/available' topic if Frigate dies and does not gracefully disconnect? (If so, I think this should be clarified in the docs so folks can have more confidence that the 'available' topic can be trusted to truly indicate Frigate's operation.)

Thanks.

### Version

0.12.1-367D724   -- as shown on System page?

### Frigate config file

```yaml
mqtt:
  host: mqttip
detect:
  width: 640
  height: 480
  fps: 5
  max_disappeared: 40
  stationary:
    interval: 10
    threshold: 50
detectors:
  coral:
    type: edgetpu
    device: usb
snapshots:
  enabled: true
  retain:
    default: 14
    objects:
      person: 21
record:
  enabled: false
  expire_interval: 60
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
objects:
  track:
    - person
motion:
  threshold: 25
cameras:
  141:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@ip:554/Streaming/Channels/102
          roles:
            - detect
  142:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@ip:554/Streaming/Channels/102
          roles:
            - detect
  143:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@ip:554/Streaming/Channels/102
          roles:
            - detect
  Carport:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@ip:554/Streaming/Channels/102
          roles:
            - detect
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a
