### ISSUE TITLE
[Config Support]: Docker-compose on 13.1 beta

### ISSUE THREAD

**Issue by nmcrae85** [blakeblackshear/frigate#7834]
### Describe the problem you are having

Im seeing this error in the logs 
frigate       | 2023-09-16 13:52:34.904071158  [ERROR] Frigate config file not found

Im sure this is down to my docker-compose file. Ive looked at the docs and i think ive mapped the config correctly but this error would indicate its not.

### Version

13.1

### Frigate config file

```yaml
image: "ghcr.io/blakeblackshear/frigate:0.13.0-beta1"
    container_name: "frigate"
    domainname: "yours.com"
    hostname: "frigate"
    privileged: true
    restart: "unless-stopped"
    shm_size: "128mb" # adjust
    devices:
      - "/dev/dri/renderD128" # for intel hwaccel
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/etc/localtime:/etc/localtime:ro"
      - "/volume1/docker/volumes/frigate-0-config/config/:/config/"
      - "/volume1/docker/volumes/frigate-0-media:/media/frigate:rw"
      - "/volume1/docker/volumes/frigate-0-media:/media/snapshots/frigate:rw"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5050:5000" # web interface
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
    environment:
      - LIBVA_DRIVER_NAME=i965
    env_file:
      - "secrets.env"
```

### Relevant log output

```shell
frigate       | 2023-09-16 13:52:34.904071158  [ERROR] Frigate config file not found
```

### Operating system

HassOS

### Install method

Docker

### Coral version

USB
