### ISSUE TITLE
[Config Support]:  Any way to configure events to Active Objects and also save audio events?

### ISSUE THREAD

**Issue by taylortech** [blakeblackshear/frigate#7836]
### Describe the problem you are having

I recently changed events to record only Active Objects. My audio event clips were being recorded just fine then. Now, no audio event clips are being recorded, I just receive the snapshot. 

I thought it may be because it's not in a required zone. But my backyard camera doesn't have a required zone to record. 
![frigate](https://github.com/blakeblackshear/frigate/assets/48053172/a0630e04-e562-49c4-8397-e4e483ade8c2)

### Version

0.13.0-9185753

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.121
  user: MQTT-user
  password: mqttpass

birdseye:
  enabled: False
  mode: objects

snapshots:
  enabled: true
  crop: true
  retain:
    default: 20
    objects:
      person: 30
      
audio:
  enabled: true
  max_not_heard: 20
  listen:
    - bark
    - scream
    - yell
    - speech
    - fire_alarm
    - thunder

go2rtc:
  streams:
    driveway_cam:
      - rtsp://user:pass@192.168.1.222:554/h264Preview_01_main
      - "ffmpeg:driveway_cam#audio=opus"
    driveway_cam_sub:
      - rtsp://user:pass@192.168.1.222:554/h264Preview_01_sub
      - "ffmpeg:driveway_cam_sub#audio=opus"
    front_door_camera:
      - rtsp://user:pass@192.168.1.49:554/Streaming/Channels/101
      - "ffmpeg:front_door_camera#audio=opus"
    front_door_camera_sub:
      - rtsp://user:pass@192.168.1.49:554/Streaming/Channels/102
      - "ffmpeg:front_door_camera_sub#audio=opus"
    backyard_cam:
      - rtsp://user:pass@192.168.1.222:554/h264Preview_02_main
      - "ffmpeg:backyard_cam#audio=opus"
    backyard_cam_sub:
      - rtsp://User:pass@192.168.1.222:554/h264Preview_02_sub
      - "ffmpeg:backyard_cam_sub#audio=opus"

  webrtc:
    candidates:
      - 192.168.1.123:8555
      - stun:8555

cameras:
  front_door_camera:
    ffmpeg:
      inputs:
        - path: rtsp://userpass192.168.1.49:554/Streaming/Channels/102
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - audio
        - path: rtsp://userpass@192.168.1.49:554/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-aac




    snapshots:
      enabled: true
      crop: true
      required_zones:
        - person_zone
        - delivery_zone

    zones:
      person_zone:
        coordinates: 0,512,384,512,384,439,384,308,311,298,243,304,113,303,0,299
        objects:
          - person
          - dog
      delivery_zone:
        coordinates: 217,284,214,303,151,308,112,306,89,304,0,300,0,279
        inertia: 10
        objects:
          - car

    motion:
      mask:
        - 260,439,266,454,116,457,122,439
        - 133,303,95,296,100,356,123,351
        - 248,264,232,409,181,410,180,273
        - 34,399,32,368,68,373,66,409
        - 231,346,227,402,191,402,188,354
        - 384,53,252,0,274,274,384,307
        - 247,231,212,240,213,285,244,297

    record:
      enabled: True
      events:
        retain:
          default: 10
          mode: active_objects
        required_zones: 
          - delivery_zone
          - person_zone

    detect:
      width: 384
      height: 512
      fps: 5
      stationary:
        threshold: 50

    objects:
      track:
        - person
        - dog
        - car
      filters:
        person:
          threshold: .78
        car:
          threshold: .75

    

#  bus_cam:
#    ffmpeg:
#      inputs:
#        - path: rtsp://userpass@192.168.1.164/live
#          roles: 
#            - detect

#    record:
#      enabled: True
#      events:
#        retain:
#          default: 5

#    detect:
#      width: 1920
#      height: 1080
#      fps: 3

  backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://userpass@192.168.1.222:554/h264Preview_02_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - audio
#            - rtmp 
        - path: rtsp://userpass@192.168.1.222:554/h264Preview_02_main
          input_args: preset-rtsp-restream
          roles: 
            - record
      output_args:
        record: preset-record-generic-audio-aac


    detect:
      width: 640
      height: 360
      fps: 5

    zones:
      back_yard:
        coordinates: 640,0,640,360,0,360,0,229,68,31,140,0,380,0

    motion:
      mask:
        - 152,360,0,313,0,244,21,186,85,50,178,0,0,0,0,1280
        - 263,164,264,92,123,121,92,339,142,360,169,165
        - 291,27,418,28,419,0,298,0

    objects:
      track:
        - person
        - dog

      filters:
        person:
          threshold: 0.75
          min_area: 4770
        dog:
          threshold: 0.50
        

    record:
      enabled: True
      events:
        retain:
          mode: active_objects
          default: 10
          objects:
            dog: 4
      

  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://userpass@192.168.1.222:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - audio
#           - rtmp
        - path: rtsp://userpass@192.168.1.222:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles: 
            - record
           
      output_args:
        record: preset-record-generic-audio-aac

    detect:
      width: 640
      height: 360
      fps: 5
      stationary:
        threshold: 50

    motion:
      mask:
        - 381,0,389,31,298,22,297,0
        - 640,80,640,0,416,0,399,61

    snapshots:
      enabled: true
      required_zones:
        - driveway_far
        - driveway_close
        - yard_and_driveway
        - road

    zones:
      road:
        coordinates: 496,57,37,58,37,0,496,0
        objects:
          - car
          - bus
      driveway_far:
        coordinates: 198,93,406,97,398,35,210,33
        objects:
          - car
      driveway_close:
        coordinates: 77,360,499,360,420,116,188,108
        objects:
          - car
      yard_and_driveway:
        coordinates: 203,100,0,110,0,360,640,360,640,119,413,102
        objects:
          - person

    objects:
      track:
        - car
        - person
        - bus
      filters:
        person:
          threshold: 0.78
        car:
          threshold: 0.75
#          min_area: 50000
        bus:
          threshold: 0.6

    record:
      enabled: True
      events:
        retain:
          default: 10
          mode: active_objects
          objects:
            car: 4
            person: 10
        required_zones:
          - driveway_far
          - driveway_close
          - yard_and_driveway
          - road


detectors:
  coral:
    type: edgetpu
    device: pci:0

#detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
```

### Relevant log output

```shell
no relevant
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2
