### ISSUE TITLE
[Support]: Prevent recording cleanup when db not found?

### ISSUE THREAD

**Issue by zzachattack2** [blakeblackshear/frigate#7838]
### Describe the problem you are having

Is there a way to prevent cleaning up the recordings directory when the configured db file is not found? I discovered upon rebuilding my cluster that after frigate loaded (with its expected configuration file and media path mounted), but before the existing db file was restored, that all previous recordings in the media path got wiped out. 

I'm assuming that this is because frigate did not find the db file, generated a brand new one, went to run a cleanup on recordings in the media directory, and wiped all recordings not accounted for in the db? 

### Version

0.12.1-367D724

### Frigate config file

```yaml
Relevant portions:

database:
  path: /data/frigate.db

record:
  enabled: True
  retain:
    days: 4
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

Not using docker compose, but K8s. Volume mounts as follows;

    persistence:
      config:
        enabled: true
        type: configMap
        name: frigate-config
        subPath: config.yaml
        mountPath: /config/config.yml
        readOnly: true
      media:
        enabled: true
        existingClaim: frigate-nvr-nfs
        mountPath: /media

    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
