### ISSUE TITLE
[Config Support]: Camera added by HA integration has low FPS

### ISSUE THREAD

**Issue by dom8925** [blakeblackshear/frigate#7842]
### Describe the problem you are having

I have Frigate configured where everything in Frigate, including restreaming with go2rtc, works great. I integrated Frigate into HA (not the lovelace card) and was looking at live streaming my cameras but the FPS on there is very low (not sure the actual amount) and I get no audio. I get audio when using MSE on Frigate's UI and the config pulls in the high quality stream for live view and recordings. I only use the sub stream for detection. 
How can I get the automatically added camera via Frigate's integration to use the high quality stream and include audio? If I add the restream url as a generic camera in HA I get good FPS and audio. 

### Version

12.1

### Frigate config file

```yaml
mqtt:
  host: x.x.x.x
  user: user
  password: password
go2rtc:
  streams:
    Parking_lot:
      - rtsp://user:pass@192.168.1.253/stream1
      - "ffmpeg:Parking_lot#audio=aac"
    candidates:
      - 192.168.1.250:8555
      - stun:8555
cameras:
  Parking_Lot:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user:pass@192.168.1.253/stream2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Parking_lot
          input_args: preset-rtsp-restream
          roles:
            - record 
    live:
      stream_name: Parking_lot
    motion:
      mask:
        - 465,0,462,36,0,40,0,0
        - 1280,82,898,53,1006,211,959,217,1280,609        
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
    mqtt:
      crop: True
      quality: 100
detect:
  fps: 5
record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi
```

### Relevant log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
