### ISSUE TITLE
[Support]: Export: unable to find clips for the selected range

### ISSUE THREAD

**Issue by coledeck** [blakeblackshear/frigate#7845]
### Describe the problem you are having

Hi, when trying to use the new export UI on 0.13.0-beta1, I have some issues with exporting recordings.

The first time I tried it, worked fine. Gave me a 2.1GB recording of a few days of clips. 

The next time I tried it, gave me a 7.5MB recording of a single event, instead of the like dozens of clips that are in that timeframe.

Now, it doesn't work at all. It says export successfully started, but see log output below. Can't find any clips, then successive errors.
There are **definitely** viewable clips in the selected timeframe. 

as a sidenote; is there a effective "limit" to how much I can export? My goal is to be able to export 1 month of `detect` events (no motion or 24/7, but its a pretty active camera). I have plenty of disk space on the server.

### Version

0.13.0-9185753

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt: 
  host: mqtt

detectors:
  coral:
    type: edgetpu
    device: pci
#  cpu1:
#    type: cpu
#    num_threads: 8

birdseye:
  enabled: True
  width: 1408
  height: 960
  quality: 8
  mode: motion

record:
  enabled: True
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 400
      mode: active_objects

snapshots:
  enabled: True
  bounding_box: True
  crop: False
  retain:
    default: 90

#rtmp:
#  enabled: True

#live:
#  height: 480
#  quality: 8

  

motion:
  mask:
    - 560,20,686,20,686,36,560,36 # cut out the right side of timestamp from motion detection
  contour_area: 30
 
ffmpeg:
  hwaccel_args: []
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    #rtmp: -c copy -f flv

go2rtc:
  streams:
    office:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.100:554/cam/realmonitor?channel=1&subtype=0
    central:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.101:554/cam/realmonitor?channel=1&subtype=0
    left:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.102:554/cam/realmonitor?channel=1&subtype=0
    lounge:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.103:554/cam/realmonitor?channel=1&subtype=0
    mill:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.104:554/cam/realmonitor?channel=1&subtype=0
    right:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.105:554/cam/realmonitor?channel=1&subtype=0
    itr:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.106:554/cam/realmonitor?channel=1&subtype=0
    entrance:
      - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.107:554/cam/realmonitor?channel=1&subtype=0
  webrtc:
    candidates:
      - 10.69.40.2:8555
cameras:
  office:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.100:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/office
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5

  central:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/central                                                              
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5

  left:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.102:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/left                                                              
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5

  lounge:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.103:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/lounge                                                              
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5

  mill:
    ffmpeg: 
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.104:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/mill
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5

  right:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.105:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/right
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5

#  itr:
#    ffmpeg: 
#      inputs:
#        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.106:554/cam/realmonitor?channel=1&subtype=1
#          roles:
#            - detect
#        - path: rtsp://127.0.0.1:8554/itr
#          roles:
#            - record
#    detect:
#      width: 704
#      height: 480
#      fps: 5

  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.69.40.107:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/entrance
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    zones:
      zone_0:
        coordinates: 152,157,276,139,266,34,132,52
      zone_1:
        coordinates: 392,32,704,73,704,386,617,480,266,480,184,267,384,244
```

### Relevant log output

```shell
2023-09-16 20:12:43.968820145  [2023-09-16 20:12:43] frigate.http                   ERROR   : No recordings found for the requested time range
2023-09-16 20:12:43.972955942  [2023-09-16 20:12:43] frigate.record.export          ERROR   : Failed to export recording for command ffmpeg -hide_banner -y -protocol_whitelist pipe,file,http,tcp -f concat -safe 0 -i /dev/stdin -c copy /media/frigate/exports/in_progress.lounge@2023_09_16_00:00__2023_09_16_23:59.mp4
2023-09-16 20:12:43.973000646  [2023-09-16 20:12:43] frigate.record.export          ERROR   : [http @ 0x5609e8ad6200] HTTP error 502 Bad Gateway
2023-09-16 20:12:43.973001638  [concat @ 0x5609e8ac29c0] Impossible to open 'http://127.0.0.1:5000/vod/lounge/start/1694840400/end/1694847600/index.m3u8'
2023-09-16 20:12:43.973002219  /dev/stdin: Server returned 5XX Server Error reply
2023-09-16 20:12:43.973002630
```

### FFprobe output from your camera

```shell
Not relevant I think
```

### Frigate stats

```json
{"central":{"camera_fps":5.1,"capture_pid":1302,"detection_enabled":1,"detection_fps":5.1,"ffmpeg_pid":1307,"pid":1272,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"18":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"8.6","cpu_average":"8","mem":"0.0"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"1.4","cpu_average":"3","mem":"1.0"},"116":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"152":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"166":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"183":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"200":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"227":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"261":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"295":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"336":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"371":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"394":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"401":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"420":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"459":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"500":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"541":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"569":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"611":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"662":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"703":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"740":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"772":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"796":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"821":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"842":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"844":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"845":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"846":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"847":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1251":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.1"},"1253":{"cmdline":"frigate.recording_manager","cpu":"3.5","cpu_average":"3","mem":"0.1"},"1262":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(48)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"1263":{"cmdline":"frigate.detector.coral","cpu":"1.1","cpu_average":"0","mem":"0.1"},"1265":{"cmdline":"frigate.output       ","cpu":"0.7","cpu_average":"0","mem":"0.1"},"1270":{"cmdline":"frigate.process:office","cpu":"0.7","cpu_average":"0","mem":"0.1"},"1271":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1272":{"cmdline":"frigate.process:central","cpu":"3.4","cpu_average":"1","mem":"0.1"},"1283":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1284":{"cmdline":"frigate.process:left ","cpu":"0.7","cpu_average":"1","mem":"0.1"},"1288":{"cmdline":"frigate.process:lounge","cpu":"3.0","cpu_average":"3","mem":"0.1"},"1290":{"cmdline":"frigate.process:mill ","cpu":"0.5","cpu_average":"0","mem":"0.1"},"1291":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1292":{"cmdline":"frigate.process:right","cpu":"0.6","cpu_average":"0","mem":"0.1"},"1295":{"cmdline":"frigate.process:entrance","cpu":"0.6","cpu_average":"0","mem":"0.1"},"1296":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1297":{"cmdline":"frigate.capture:office","cpu":"0.3","cpu_average":"0","mem":"0.1"},"1300":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1302":{"cmdline":"frigate.capture:central","cpu":"0.3","cpu_average":"0","mem":"0.1"},"1305":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:pink4bubble@10.69.40.100:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"1","mem":"0.0"},"1306":{"cmdline":"frigate.capture:left ","cpu":"0.4","cpu_average":"0","mem":"0.1"},"1307":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:pink4bubble@10.69.40.101:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"1","mem":"0.0"},"1310":{"cmdline":"frigate.capture:lounge","cpu":"0.4","cpu_average":"0","mem":"0.1"},"1311":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1312":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:pink4bubble@10.69.40.102:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"1","mem":"0.0"},"1319":{"cmdline":"frigate.capture:mill ","cpu":"0.3","cpu_average":"0","mem":"0.1"},"1320":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/office -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/office-%Y%m%d%H%M%S.mp4","cpu":"0.5","cpu_average":"0","mem":"0.0"},"1321":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:pink4bubble@10.69.40.103:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"1","mem":"0.0"},"1322":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/central -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/central-%Y%m%d%H%M%S.mp4","cpu":"0.6","cpu_average":"0","mem":"0.0"},"1327":{"cmdline":"frigate.capture:right","cpu":"0.5","cpu_average":"0","mem":"0.1"},"1328":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1330":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:pink4bubble@10.69.40.104:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"2","mem":"0.0"},"1334":{"cmdline":"frigate.capture:entrance","cpu":"0.5","cpu_average":"0","mem":"0.1"},"1336":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/left -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/left-%Y%m%d%H%M%S.mp4","cpu":"0.6","cpu_average":"0","mem":"0.0"},"1337":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:pink4bubble@10.69.40.105:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"2","mem":"0.0"},"1340":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/lounge -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/lounge-%Y%m%d%H%M%S.mp4","cpu":"0.6","cpu_average":"0","mem":"0.0"},"1343":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:pink4bubble@10.69.40.107:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.1","cpu_average":"1","mem":"0.0"},"1344":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/mill -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/mill-%Y%m%d%H%M%S.mp4","cpu":"0.6","cpu_average":"0","mem":"0.0"},"1345":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1408x960 -i pipe: -f mpegts -s 1408x960 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1350":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/right -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/right-%Y%m%d%H%M%S.mp4","cpu":"0.6","cpu_average":"0","mem":"0.0"},"1360":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-9185753 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/entrance -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/entrance-%Y%m%d%H%M%S.mp4","cpu":"0.4","cpu_average":"0","mem":"0.0"},"10689":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":9.8,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.12,"pid":1263}},"entrance":{"camera_fps":5.1,"capture_pid":1334,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1343,"pid":1295,"process_fps":5.1,"skipped_fps":0.0},"left":{"camera_fps":5.0,"capture_pid":1306,"detection_enabled":1,"detection_fps":0.4,"ffmpeg_pid":1312,"pid":1284,"process_fps":5.1,"skipped_fps":0.0},"lounge":{"camera_fps":5.1,"capture_pid":1310,"detection_enabled":1,"detection_fps":4.3,"ffmpeg_pid":1321,"pid":1288,"process_fps":5.1,"skipped_fps":0.0},"mill":{"camera_fps":5.0,"capture_pid":1319,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1330,"pid":1290,"process_fps":5.0,"skipped_fps":0.0},"office":{"camera_fps":5.0,"capture_pid":1297,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1305,"pid":1270,"process_fps":5.0,"skipped_fps":0.0},"processes":{"go2rtc":{"pid":89},"logger":{"pid":1251},"recording":{"pid":1253}},"right":{"camera_fps":5.0,"capture_pid":1327,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1337,"pid":1292,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1694913766,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":592.9,"mount_type":"tmpfs","total":600.0,"used":7.1},"/media/frigate/clips":{"free":11939233.9,"mount_type":"zfs","total":16806550.6,"used":4867316.8},"/media/frigate/recordings":{"free":11939233.9,"mount_type":"zfs","total":16806550.6,"used":4867316.8},"/tmp/cache":{"free":2812.0,"mount_type":"tmpfs","total":2861.0,"used":49.0}},"temperatures":{"apex_0":32.05},"uptime":741,"version":"0.13.0-9185753"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW

### Any other information that may be helpful

I've used the API endpoint in the past on 0.12 *mostly* without issue but I exported only a few relatively small clips (few hundred MB) because it was very annoying to convert timestamps.

Also note; Frigate is accessed behind an auth proxy (oauth2-proxy) but I don't think that should affect anything.

Thank you so much for this awesome project!!
