### ISSUE TITLE
[Detector Support]: Person event stuck "in progress"

### ISSUE THREAD

**Issue by ianwood** [blakeblackshear/frigate#7856]
### Describe the problem you are having

New camera installed in backyard. Having some challenges with people detection events getting "stuck" and showing as "in progress" indefinitely. It doesn't happen often. Maybe one time in 30 or 40 normal person detection events. 

When it does happen, only thing that clears the event is a new person event or restarting Frigate. Debug image shows "person" where there was one quite some time ago but has long since disappeared. Only happens on the one camera. I only need the person detection within the zones that are defined as "required" but it doesn't seem to function that way.

[Debug screencap](https://ianwood.com/wp-content/uploads/2023/09/rear-stuck-person-01.jpg)
[Event screencap](https://ianwood.com/wp-content/uploads/2023/09/rear-stuck-person-02.jpg)

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: yyy
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  LIBVA_DRIVER_NAME: i965

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -c:a aac -f flv

rtmp:
  enabled: False

cameras:
  rear:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@zzz:554/H264/ch1/sub/av_stream
          roles:
            - detect
        - path: rtsp://xxx:yyy@zzz:554/H264/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 6
    motion:
      improve_contrast: True
      mask:
      - 1195,444,1115,287,1049,212,973,206,969,0,1280,0,1280,264,1280,720
      - 0,0,0,397,383,254,973,299,965,0
      - 1256,681,1256,720,897,720,897,681
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      required_zones:
        - backyard
    record:
      enabled: True
      retain:
        days: 4
        mode: motion
      events:
        retain:
          default: 4
          mode: active_objects
        required_zones:
          - backyard
    zones:
      backyard:
        coordinates: 1162,362,1280,720,56,720,0,633,0,410,333,254,975,296,976,257,1092,264
        objects:
        - person
  front:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@zzz:554/H264/ch1/sub/av_stream
          roles:
            - detect
        - path: rtsp://xxx:yyy@zzz:554/H264/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 1920
      height: 536
      fps: 6
    motion:
      improve_contrast: True
      mask:
      - 1503,216,1515,436,1458,536,1396,500,1438,345,1428,182,1337,32,781,34,549,81,367,149,0,345,0,0,1920,0,1920,514
      - 1319,536,1418,155,1331,99,1236,317,1226,488,1018,468,881,393,637,436,609,536
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      required_zones:
        - frontyard
    record:
      enabled: True
      retain:
        days: 4
        mode: motion
      events:
        retain:
          default: 4
          mode: active_objects
        required_zones:
          - frontyard
    zones:
      frontyard:
        coordinates: 1400,204,978,177,664,184,422,300,397,246,121,361,61,536,1761,536
        objects:
        - person
```

### docker-compose file or Docker CLI command

```yaml
As set in HASSIO. Protection mode off.
```

### Relevant log output

```shell
Nothing relevant in the logs.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
