### ISSUE TITLE
[Support]: Birdseye errors when using nonstandard aspect ratio

### ISSUE THREAD

**Issue by robinostlund** [blakeblackshear/frigate#7863]
### Describe the problem you are having

Hi,
I upgraded to beta 0.13.0 beta 1 today and after a while frigate has been running it spams the log with this information:

2023-09-18 15:30:54.913519806  Traceback (most recent call last):
2023-09-18 15:30:54.913526950    File "/opt/frigate/frigate/output.py", line 579, in update
2023-09-18 15:30:54.913530698      updated_frame = self.update_frame()
2023-09-18 15:30:54.913534101    File "/opt/frigate/frigate/output.py", line 354, in update_frame
2023-09-18 15:30:54.913537218      if len(self.camera_layout) == 0:
2023-09-18 15:30:54.913540319  TypeError: object of type 'int' has no len()
2023-09-18 15:30:54.913543015

### Version

0.13.0 beta 1

### Frigate config file

```yaml
# {{ ansible_managed }}
# Docs: https://frigate-docs.netlify.app/
logger:
  default: info
  # logs:
  #   frigate.mqtt: warning
  #   frigate.object_detection: debug
  #   peewee: info
  #   peewee.sqliteq: info

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ui:
  live_mode: mse
  strftime_fmt: "%Y-%m-%d %H:%M"

mqtt:
  host: "192.168.100.11"
  topic_prefix: frigate
  port: 1883
  stats_interval: 60

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1980
  # Optional: Height of the output resolution (default: shown below)
  height: 1024
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

live:
  height: 1024
  quality: 4
  #quality: 1

# ffmpeg configuration
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2

  hwaccel_args: preset-vaapi
  #hwaccel_args: preset-nvidia-h264

  input_args: preset-rtsp-restream
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti

  #output_args:
  #  detect: -f rawvideo -pix_fmt yuv420p
  #  #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
  #  record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  #  rtmp: -c copy -f flv

go2rtc:
  webrtc:
    candidates:
      - {{ network_interface_ip }}:{{ docker_tcp_port_homeassistant_frigate_webrtc }}
      - stun:{{ docker_tcp_port_homeassistant_frigate_webrtc }}

  streams:
    # high resolution streams
    home_bird_feeder:
      - rtspx://192.168.99.1:7441/XDQaUBRbcLDEzR83 # 1920x1080
      #- rtsp://192.168.99.1:7447/XDQaUBRbcLDEzR83 # 1920x1080
    home_workshop:
      - rtspx://192.168.99.1:7441/bY3yFl8JWQnYVqgt # 1920x1080
      #- rtsp://192.168.99.1:7447/bY3yFl8JWQnYVqgt # 1920x1080
    home_balcony:
      - rtspx://192.168.99.1:7441/05uUZqGYeJOrtryY # 2688x1512
      #- rtsp://192.168.99.1:7447/05uUZqGYeJOrtryY # 2688x1512
    home_garage:
      - rtspx://192.168.99.1:7441/LqMpQSYhuI4B8Gy2 # 1920x1080
      #- rtsp://192.168.99.1:7447/LqMpQSYhuI4B8Gy2 # 1920x1080
    home_road:
      - rtspx://192.168.99.1:7441/BqB7xw17u1l3S3yz # 2688x1512
      #- rtsp://192.168.99.1:7447/BqB7xw17u1l3S3yz # 2688x1512
    home_boiler_room:
      - rtspx://192.168.99.1:7441/iwS2X9KLpVZBMVMC # 1920x1080
      #- rtsp://192.168.99.1:7447/iwS2X9KLpVZBMVMC # 1920x1080
    home_garden:
      - rtspx://192.168.99.1:7441/ULXJBXmENA5JTI2e # 2688x1512
      #- rtsp://192.168.99.1:7447/ULXJBXmENA5JTI2e # 2688x1512
    home_entrance:
      - rtspx://192.168.99.1:7441/ielUCQSoSp9Lip22 # 1600x1200
      #- rtsp://192.168.99.1:7447/ielUCQSoSp9Lip22 # 1600x1200
    home_entrance_package:
      - rtspx://192.168.99.1:7441/4I2rXogKrUJb30ZT # 1600x1200
      #- rtsp://192.168.99.1:7447/4I2rXogKrUJb30ZT # 1600x1200

    # low resolution streams
    home_bird_feeder_low:
      - rtspx://192.168.99.1:7441/342QjXfWHXv8f5Tx # 1024x576
      #- rtsp://192.168.99.1:7447/342QjXfWHXv8f5Tx # 1024x576
    home_workshop_low:
      - rtspx://192.168.99.1:7441/q9kvmgXP5q0eJL1w # 1024x576
      #- rtsp://192.168.99.1:7447/q9kvmgXP5q0eJL1w # 1024x576
    home_balcony_low:
      - rtspx://192.168.99.1:7441/4l187Fmq1cmVNN1h # 1280x720
      #- rtsp://192.168.99.1:7447/4l187Fmq1cmVNN1h # 1280x720
    home_garage_low:
      - rtspx://192.168.99.1:7441/s8MHyGsI51DXjSiS # 1024x576
      #- rtsp://192.168.99.1:7447/s8MHyGsI51DXjSiS # 1024x576
    home_road_low:
      - rtspx://192.168.99.1:7441/YTONnzqeP5KCQsfG # 1280x720
      #- rtsp://192.168.99.1:7447/YTONnzqeP5KCQsfG # 1280x720
    home_boiler_room_low:
      - rtspx://192.168.99.1:7441/CcMESGWVum6XDae6 # 1024x576
      #- rtsp://192.168.99.1:7447/CcMESGWVum6XDae6 # 1024x576
    home_garden_low:
      - rtspx://192.168.99.1:7441/nKMUN0G0lcr2ihPm # 1280x720
      #- rtsp://192.168.99.1:7447/nKMUN0G0lcr2ihPm # 1280x720
    home_entrance_low:
      - rtspx://192.168.99.1:7441/lJKziP1775wbAcJN # 960x720
      #- rtsp://192.168.99.1:7447/lJKziP1775wbAcJN # 960x720


# default motion settings
motion:
  threshold: 60
  contour_area: 40
  #contour_area: 30
  #delta_alpha: 0.2
  improve_contrast: false
  mask:
    # this mask prevents triggering on date in corner
    - 0,67,228,68,225,0,0,0


# default record settings
record:
  enabled: False
  expire_interval: 60
  retain:
    days: 7
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 10
      mode: active_objects
      objects:
        person: 10
        car: 10
        bicycle: 10

# default snapshot settings
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 20
    objects:
      person: 15
      car: 15
      motorcycle: 15
      bicycle: 15

# default detect settings
detect:
  enabled: True
  width: 1280
  height: 720
  fps: 5
  max_disappeared: 25
  stationary:
    #interval: 0
    interval: 10
    threshold: 50

# default objects settings
objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
  filters:
    person:
      min_score: 0.6
      threshold: 0.7
    car:
      min_score: 0.6
      threshold: 0.7
    motorcycle:
      min_score: 0.6
      threshold: 0.7
    bicycle:
      min_score: 0.6
      threshold: 0.7


cameras:
  # home
  home_bird_feeder:
    enabled: True
    ui:
      order: 7
      dashboard: True
    live:
      stream_name: home_bird_feeder
    birdseye:
      enabled: False
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_bird_feeder
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_bird_feeder_low
          #input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: False
      width: 1024
      height: 576

    record:
      enabled: False

    snapshots:
      enabled: False

    motion:
      mask:
        - 0,576,199,576,218,537,217,480,196,424,99,411,0,406
        - 391,56,452,44,552,51,592,81,636,118,688,166,703,204,700,285,658,348,611,406,544,440,465,452,401,443,333,395,292,360,270,310,254,256,246,218,226,161,271,71
        - 848,0,816,61,776,116,739,159,665,171,623,149,584,119,579,90,577,48,576,0

  home_workshop:
    enabled: True
    ui:
      order: 8
      dashboard: True
    live:
      stream_name: home_workshop
    birdseye:
      mode: motion
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_workshop
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_workshop_low
          #input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: False
      width: 1024
      height: 576

    record:
      enabled: False

    snapshots:
      enabled: False

  home_entrance:
    enabled: True
    ui:
      order: 4
      dashboard: True
    live:
      stream_name: home_entrance
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_entrance
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_entrance_low
          #input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 960
      height: 720

    zones:
      balcony:
        coordinates: 398,558,532,571,658,555,845,720,419,720,332,720,220,720,107,720,0,720,0,557,0,499
      driveway:
        coordinates: 0,499,574,570,541,531,516,505,480,464,305,465,292,427,221,427,196,433,131,434,0,448
      garage:
        coordinates: 560,563,629,557,680,513,587,454,512,459

  home_entrance_package:
    enabled: True
    ui:
      order: 5
      dashboard: True
    live:
      stream_name: home_entrance_package
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_entrance_package
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    detect:
      enabled: False
      width: 1600
      height: 1200

    record:
      enabled: False

    snapshots:
      enabled: False

  home_balcony:
    enabled: True
    ui:
      order: 3
      dashboard: True
    live:
      stream_name: home_balcony
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_balcony
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_balcony_low
          #input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720

    zones:
      balcony:
        coordinates: 1244,275,847,250,822,299,770,390,501,720,1223,720
      lawn:
        coordinates: 435,720,733,371,791,91,1235,62,1228,0,910,0,807,0,693,31,410,204,0,509,0,720

  home_garage:
    enabled: True
    ui:
      order: 5
      dashboard: True
    live:
      stream_name: home_garage
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_garage
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_garage_low
          #input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1024
      height: 576
    objects:
      track:
        - person

  home_boiler_room:
    enabled: True
    ui:
      order: 9
      dashboard: True
    live:
      stream_name: home_boiler_room
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_boiler_room
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_boiler_room_low
          #input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1024
      height: 576
    
    snapshots:
      enabled: False


  home_road:
    enabled: True
    ui:
      order: 1
      dashboard: True
    live:
      stream_name: home_road
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_road
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_road_low
          #input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 1280
      height: 720

    record:
      events:
        required_zones:
          - "street"
          - "lawn"
          - "driveway"
          - "sten"

    snapshots:
      required_zones:
        - "street"
        - "lawn"
        - "driveway"
        - "sten"

    zones:
      street:
        coordinates: 1180,0,258,0,0,0,0,207,177,193,469,190,579,188,651,189,673,188,919,184,1017,177,1138,170
      lawn:
        coordinates: 1126,720,1259,593,1280,442,844,260,701,209,450,211,232,223,0,233,0,720
      driveway:
        coordinates: 773,203,1009,287,1280,400,1280,314,1076,233,1015,213
      sten:
        coordinates: 1280,268,1280,106,1213,113,1169,189,1052,189


  home_garden:
    enabled: True
    ui:
      order: 2
      dashboard: True
    live:
      stream_name: home_garden
    ffmpeg:
      # output_args:
      #   record: preset-record-ubiquiti
      inputs:
        - path: rtsp://127.0.0.1:8554/home_garden
          #input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/home_garden_low
          #input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720

    zones:
      hot_tub:
        coordinates: 551,175,563,200,587,219,647,224,655,211,679,208,796,183,801,163,797,101,726,61,631,70,564,75,525,141
      green_house:
        coordinates: 158,121,227,58,315,110,343,253,355,275,191,311,174,278,162,219
      lawn:
        coordinates: 1280,720,1280,0,1006,0,1194,0,868,0,825,36,824,164,806,206,688,231,659,255,555,235,512,184,441,179,395,281,278,309,195,324,126,320,84,225,32,232,0,228,0,333,0,370,0,398,0,412,0,720
```

### Relevant log output

```shell
2023-09-18 15:34:22.806133571  Traceback (most recent call last):
2023-09-18 15:34:22.806136145    File "/opt/frigate/frigate/output.py", line 579, in update
2023-09-18 15:34:22.806137284      updated_frame = self.update_frame()
2023-09-18 15:34:22.806138385    File "/opt/frigate/frigate/output.py", line 354, in update_frame
2023-09-18 15:34:22.806139390      if len(self.camera_layout) == 0:
2023-09-18 15:34:22.806140384  TypeError: object of type 'int' has no len()
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Ubiquiti AI Bullet

**Comment by NickM-27** [comment]
need to see the full logs, the part where the camera layout gets set to 0 (which is incorrect) is due to an exception already. Need to know what that exception is as well

**Comment by robinostlund** [comment]
I will try to get it :) it floods the output right now.

**Comment by robinostlund** [comment]
Able to get it now:
First i get this:
```
2023-09-18 15:46:30.515346441  Traceback (most recent call last):
2023-09-18 15:46:30.515356473    File "/opt/frigate/frigate/output.py", line 579, in update
2023-09-18 15:46:30.515360797      updated_frame = self.update_frame()
2023-09-18 15:46:30.515365455    File "/opt/frigate/frigate/output.py", line 436, in update_frame
2023-09-18 15:46:30.515369431      self.copy_to_position(
2023-09-18 15:46:30.515374057    File "/opt/frigate/frigate/output.py", line 320, in copy_to_position
2023-09-18 15:46:30.515377887      copy_yuv_to_position(
2023-09-18 15:46:30.515382308    File "/opt/frigate/frigate/util/image.py", line 458, in copy_yuv_to_position
2023-09-18 15:46:30.515386068      destination_frame[
2023-09-18 15:46:30.515391170  ValueError: could not broadcast input array from shape (278,988) into shape (256,988)
```

Then a couple of seconds later:
```
2023-09-18 15:46:40.768951425  Traceback (most recent call last):
2023-09-18 15:46:40.768961588    File "/opt/frigate/frigate/output.py", line 579, in update
2023-09-18 15:46:40.768966296      updated_frame = self.update_frame()
2023-09-18 15:46:40.768970585    File "/opt/frigate/frigate/output.py", line 354, in update_frame
2023-09-18 15:46:40.768973530      if len(self.camera_layout) == 0:
2023-09-18 15:46:40.768976316  TypeError: object of type 'int' has no len()
```

**Comment by NickM-27** [comment]
Right, so the original issue looks to be due to birdseye autolayout having some issue, if I had to guess it is due to the unusual detect resolution 1024x576

I'll have to see if I can recreate your config and reproduce it

**Comment by robinostlund** [comment]
Oright, yeah it is the Unifi G3 has 1024x576 on the medium quality rtsps stream.

**Comment by NickM-27** [comment]
actually I am wrong, I think the issue is the birdseye resolution being a non standard aspect ratio

**Comment by robinostlund** [comment]
Ahaa, actually had missed that i had wrong values there, i have changed to this now:
```
birdseye:
  enabled: True
  restream: True
  width: 1920
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
```

And now the errors is gone and i have verified that i got an motion in birdseye, so it seems solved now 😄 

Thanks
