### ISSUE TITLE
[Support]: Frigate+ images blank

### ISSUE THREAD

**Issue by dopeytree** [blakeblackshear/frigate#7879]
### Describe the problem you are having

Have been sending images to frigate+ but when I log in they are showing as blank and showing text

My account is hello@skynique.co.uk

https://imgur.com/a/9NazWTX

### Version

0.12.1-367d724

### Frigate config file

```yaml
# Configuration File
# Used https://docs.frigate.video/configuration/#vscode-configuration-schema

mqtt:
  enabled: true
  host: 192.168.22.2
  port: 1883
   # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user:
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password:
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60


# Optional: Restream configuration
# Uses https://github.com/AlexxIT/go2rtc (v1.2.0)
go2rtc:
   streams:
    barn HQ:
      - rtsp://MPG7QbYQ:ICRGvtBU2xo3DxMy@192.168.22.202:554/live/ch0
    #barn SQ:
     # - rtsp://MPG7QbYQ:ICRGvtBU2xo3DxMy@192.168.22.202:554/live/ch1
    #bird HQ:
      - rtsp://pSrUq7TZ:4ua2cFC2dq2UNEXx@192.168.22.201:554/live/ch0
    #bird SQ:
     # - rtsp://pSrUq7TZ:4ua2cFC2dq2UNEXx@192.168.22.201:554/live/ch1
    house_front HQ:
      - rtsp://EWLHSHKY:XGEJzBByF2IE3c@192.168.44.5:554/live/ch0
    house_front_2 HQ:
      - rtsp://admin:annke2023@192.168.44.6:554/H265/ch1/main/av_stream
    
    #house_front SQ:
     # - rtsp://EWLHSHKY:XGEJzBByF2IE3c@192.168.44.5:554/live/ch1
    #wyze:
      #- rtsp://admin:pass123@192.168.22.192:8554/live/ch0

# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 16
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-vaapi
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic-audio-aac
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 16 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic-audio-aac
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic
  
detectors:
  coral:
    type: edgetpu
    device: usb   


# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  #width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  #height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  #fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 75
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 10

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.4
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 30
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true
         

cameras:
         
  barn: # 1 - BARN - cam name - Brand: Wansview - Quality:1080p
    snapshots:
      enabled: true
      bounding_box: true
      quality: 99
    #  
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://MPG7QbYQ:ICRGvtBU2xo3DxMy@192.168.22.202:554/live/ch1 # SD Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/barn%20HQ?mp4 # HD Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 768
      height: 432
      fps: 5
      stationary:
        interval: 0
        threshold: 70
    motion:
      mask:
        - 768,0,768,24,524,24,524,0    
    objects:
      track:
        - person
        - cat
      filters:
        #     
        person:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        # 
        cat:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7           
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 28
          mode: active_objects 

  


  house_front: # no3 - HOUSE_FRONT - Cam name - Brand: Wansview - Quality:1080p
    snapshots:
      enabled: true
      bounding_box: true
      quality: 99
    #  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://EWLHSHKY:XGEJzBByF2IE3c@192.168.44.5:554/live/ch1 # SD Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/house_front%20HQ?mp4  # HD Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 768  
      height: 432
      fps: 5
      stationary:
        interval: 0
        threshold: 70
    motion:
      mask:
        - 768,450,768,325,724,317,653,288,614,294,606,260,596,224,518,205,414,233,371,299,332,407,444,450
        - 496,0,768,0,768,159,657,126,567,100,504,125,434,129,386,142,332,98,175,85,0,83,0,0,335,0
        - 0,215,0,296,69,305,127,265,141,225,110,167,64,136   
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bicycle
        - motorcycle
      filters:
        #
        car:  
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        #
        person:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.6
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        #
        dog:
          min_area: 1000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        # 
        cat:
          min_area: 1000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        # 
        bicycle:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        #  
        motorcycle:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7          
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        pre_capture: 3
        post_capture: 3
        objects:
        - person
        - car
        - dog
        - cat
        - bicycle
        - motorcycle
        retain:
          default: 28
          mode: active_objects


  house_front_2: # no4 - HOUSE_FRONT_2 - Cam name - Brand: Annke - Quality:3k
    snapshots:
      enabled: true
      bounding_box: true
      quality: 99
    #  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:annke2023@192.168.44.6:554/Streaming/Channels/102 # SQ Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/house_front_2%20HQ?mp4  # HQ Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640  
      height: 480
      fps: 5
      stationary:
        interval: 0
        threshold: 70
    motion:
      mask:
        - 189,0,189,23,0,23,0,0,0,0,0,0
        - 640,480,640,221,608,173,503,169,408,386,378,480
        - 334,106,505,111,527,0,330,0
    zones:
      zone_0:
        coordinates: 192,21,197,0,640,0,640,236,514,210,410,480,0,480,0,21 
        objects: # (everywhere you want a person, cat, dog)
        - person
        - cat
        - dog  
      zone_1:
        coordinates: 325,176,578,183,584,0,323,0   
        objects: # (everywhere you want a car)
        - car
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        #
        car:
          mask:
            - 331,329,538,311,532,194,328,183
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.6
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        #
        #person:
        #
        dog:
          min_area: 1000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        #
        cat:
          min_area: 1000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        pre_capture: 5
        post_capture: 3
        objects:
        - person
        - car
        - dog
        - cat
        retain:
          default: 28
          mode: active_objects
           
  

    # Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant log output

```shell
2023-09-19 17:35:23.096247414  [INFO] Starting Frigate...
2023-09-19 17:35:25.563127932  [2023-09-19 17:35:25] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-19 17:35:25.696654705  [2023-09-19 17:35:25] peewee_migrate                 INFO    : Starting migrations
2023-09-19 17:35:25.706485812  [2023-09-19 17:35:25] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-19 17:35:25.742820402  [2023-09-19 17:35:25] detector.coral                 INFO    : Starting detection process: 721
2023-09-19 17:35:25.748847851  [2023-09-19 17:35:25] frigate.app                    INFO    : Output process started: 723
2023-09-19 17:35:25.772376489  [2023-09-19 17:35:25] frigate.app                    INFO    : Camera processor started for barn: 729
2023-09-19 17:35:25.780268706  [2023-09-19 17:35:25] frigate.app                    INFO    : Camera processor started for house_front: 731
2023-09-19 17:35:25.783394294  [2023-09-19 17:35:25] frigate.app                    INFO    : Camera processor started for house_front_2: 733
2023-09-19 17:35:25.793897616  [2023-09-19 17:35:25] frigate.app                    INFO    : Capture process started for barn: 734
2023-09-19 17:35:25.805501046  [2023-09-19 17:35:25] frigate.app                    INFO    : Capture process started for house_front: 737
2023-09-19 17:35:25.815911020  [2023-09-19 17:35:25] frigate.app                    INFO    : Capture process started for house_front_2: 741
2023-09-19 17:35:28.416860498  [2023-09-19 17:35:25] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-09-19 17:35:28.423363925  [2023-09-19 17:35:28] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-09-19 18:34:56.073635010  [2023-09-19 18:34:56] watchdog.house_front           INFO    : house_front exceeded fps limit. Exiting ffmpeg...
2023-09-19 18:34:56.073813775  [2023-09-19 18:34:56] watchdog.house_front           INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-19 18:34:56.143965154  [2023-09-19 18:34:56] frigate.video                  ERROR   : house_front: Unable to read frames from ffmpeg process.
2023-09-19 18:34:56.144123583  [2023-09-19 18:34:56] frigate.video                  ERROR   : house_front: ffmpeg process is not running. exiting capture thread...
2023-09-19 18:35:06.146222459  [2023-09-19 18:35:06] watchdog.house_front           ERROR   : Ffmpeg process crashed unexpectedly for house_front.
2023-09-19 18:35:06.146503009  [2023-09-19 18:35:06] watchdog.house_front           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 640x480
FPS: 6/1

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 3072x1728
FPS: 20/1

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

ANNKE c500

### Any other information that may be helpful

not sure if any logs are recorded about frigate+
