### ISSUE TITLE
[HW Accel Support]: Intel Alder Lake-N [UHD Graphics]

### ISSUE THREAD

**Issue by krzakx** [blakeblackshear/frigate#7880]
### Describe the problem you are having

error-gpu
There was an error getting usage stats. This does not mean hardware acceleration is not working. Either your GPU does not support this or Frigate does not have proper access to get statistics. This is expected for the Home Assistant addon.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.xx
  user: xxxx
  password: xxxx

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-intel-qsv-h264
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic


go2rtc:
  webrtc:
   candidates:
     - 192.168.x.x:8555
     - stun:8555

  streams:
    Domofon:
       rtsp://admin:admin@192.168.x.x:8554/Streaming/Channels/101
    Salon:
       rtsp://192.168.x.x/ch0_0.h264
    Garaz:
       rtsp://192.168.x.x/ch0_0.h264

record:
  enabled: True
  events:
    retain:
      default: 10

detect:
  fps: 5
  enabled: True


#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15



cameras:
  Domofon:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/Domofon # <--- the name here must match the name of the camera in restream
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect

  Salon:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/Salon # <--- the name here must match the name of the camera in restream
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
  Garaz:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/Garaz # <--- the name here must match the name of the camera in restream
          #input_args: preset-rtsp-restream
          roles:
            - record
            - detect
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    cap_add:
      - CAP_PERFMON
  
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/recordings:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxx"
```

### Relevant log output

```shell
2023-09-19 20:35:31.936951235  [2023-09-19 20:35:31] frigate.util                   ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Permission denied)
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":1080,"width":1920}]}}]

[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Chines

### Any other information that may be helpful

My Docker is run in LXC container (turnkey-core).
`lspci -v -s $(lspci | grep VGA | cut -d" " -f 1)
`
does gives nothing

while this command run on Proxmox PVE console, gives:
```
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-N [UHD Graphics] (prog-if 00 [VGA controller])
        DeviceName: Onboard - Video
        Subsystem: Intel Corporation Alder Lake-N [UHD Graphics]
        Flags: bus master, fast devsel, latency 0, IRQ 129
        Memory at 6000000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 4000000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 5000 [size=64]
        Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit-
        Capabilities: [d0] Power Management version 2
        Capabilities: [100] Process Address Space ID (PASID)
        Capabilities: [200] Address Translation Service (ATS)
        Capabilities: [300] Page Request Interface (PRI)
        Capabilities: [320] Single Root I/O Virtualization (SR-IOV)
        Kernel driver in use: i915
        Kernel modules: i915
```

From what I've already read it could be needed to passthrough GPU into LXC container? any advice here, please
