### ISSUE TITLE
[Config Support]: No new recording segments were created in the last 120s

### ISSUE THREAD

**Issue by brembygit** [blakeblackshear/frigate#7888]
### Describe the problem you are having

I have 2 cameras and I see this error in the log

> 2023-09-19 21:54:45.100489177  [2023-09-19 21:54:45] watchdog.camera1               ERROR   : No new recording segments were created for camera1 in the last 120s. restarting the ffmpeg record process...
2023-09-19 21:54:45.100609895  [2023-09-19 21:54:45] watchdog.camera1               INFO    : Terminating the existing ffmpeg process...
2023-09-19 21:54:45.100669707  [2023-09-19 21:54:45] watchdog.camera1               INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-19 21:54:45.147227695  [2023-09-19 21:54:45] watchdog.camera2               ERROR   : No new recording segments were created for camera2 in the last 120s. restarting the ffmpeg record process...
2023-09-19 21:54:45.147315083  [2023-09-19 21:54:45] watchdog.camera2               INFO    : Terminating the existing ffmpeg process...
2023-09-19 21:54:45.147496381  [2023-09-19 21:54:45] watchdog.camera2               INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-19 21:54:55.107299230  [2023-09-19 21:54:55] watchdog.camera1               ERROR   : No new recording segments were created for camera1 in the last 120s. restarting the ffmpeg record process...

### Version

0.12.1-367D724

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.12:5000/api/config/schema.json
mqtt:
  enabled: true
  host: 192.168.1.10
  port: 1883
  user: mqtt_user
  password: mqtt_password
  topic_prefix: frigate

detectors:
  coral:
     type: edgetpu
     device: usb

go2rtc:
  streams:
    camera1:
      - rtsp://user:password@192.168.1.31:88/videoMain
    camera2:
      - rtsp://user:passwor@192.168.1.32:88/videoMain

  webrtc:
    candidates:
      - 192.168.1.12:8555
      - stun:8555

rtmp:
  enabled: False

birdseye:
  enabled: True
  mode: continuous
  #restream: True

objects:
 track:
   - person
#   - car
   - bicycle
   - motorcycle
   - bird
   - cat
   - dog

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  
cameras:
 camera1:
  enabled: True

  ffmpeg:
    inputs:
    - path: rtsp://127.0.0.1:8554/camera1_main
      input_args: preset-rtsp-restream
      roles:
       - record

    - path: rtsp://user:password@192.168.1.31:88/videoSub
      input_args: preset-rtsp-restream
      roles:
       - detect
    output_args:
      record: preset-record-generic


  record:
   enabled: True
   retain:
     days: 7
     mode: motion
   events:
     pre_capture: 15
     post_capture: 15
     retain:
       default: 5
       mode: active_objects
       objects:
        person: 5
     objects:
      - person

  snapshots:
    enabled: True
    timestamp: True
    bounding_box: True
    retain:
      default: 5
      objects:
        person: 5
        
  detect:
    enabled: True
    width: 1280
    height: 720
    fps: 5

 camera2:
  enabled: True

  ffmpeg:
    inputs:
    - path: rtsp://127.0.0.1:8554/camera2_main
      input_args: preset-rtsp-restream
      roles:
       - record

    - path: rtsp://user:password@192.168.1.32:88/videoSub
      input_args: preset-rtsp-restream
      roles:
       - detect
    output_args:
      record: preset-record-generic


  record:
   enabled: True
   retain:
     days: 7
     mode: motion
   events:
     pre_capture: 15
     post_capture: 15
     retain:
       default: 5
       mode: active_objects
       objects:
        person: 5
     objects:
      - person

  snapshots:
    enabled: True
    timestamp: True
    bounding_box: True
    retain:
      default: 5
      objects:
        person: 5

  detect:
    enabled: True
    width: 640
    height: 360
    fps: 5
```

### Relevant log output

```shell
FRIGATE

2023-09-19 21:51:34.085844936  [INFO] Starting Frigate...
2023-09-19 21:51:34.880685811  [2023-09-19 21:51:34] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-19 21:51:34.898763217  [2023-09-19 21:51:34] peewee_migrate                 INFO    : Starting migrations
2023-09-19 21:51:34.902221787  [2023-09-19 21:51:34] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-19 21:51:34.915581034  [2023-09-19 21:51:34] detector.coral                 INFO    : Starting detection process: 433
2023-09-19 21:51:34.916118722  [2023-09-19 21:51:34] frigate.app                    INFO    : Output process started: 435
2023-09-19 21:51:34.920781472  [2023-09-19 21:51:34] frigate.app                    INFO    : Camera processor started for camera1: 441
2023-09-19 21:51:34.926154358  [2023-09-19 21:51:34] frigate.app                    INFO    : Camera processor started for camera2: 443
2023-09-19 21:51:34.931307390  [2023-09-19 21:51:34] frigate.app                    INFO    : Capture process started for camera1: 445
2023-09-19 21:51:34.936041552  [2023-09-19 21:51:34] frigate.app                    INFO    : Capture process started for camera2: 448
2023-09-19 21:51:37.558583394  [2023-09-19 21:51:34] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-09-19 21:51:37.562142786  [2023-09-19 21:51:37] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-09-19 21:53:55.064569501  [2023-09-19 21:53:55] watchdog.camera1               ERROR   : No new recording segments were created for camera1 in the last 120s. restarting the ffmpeg record process...
2023-09-19 21:53:55.064687681  [2023-09-19 21:53:55] watchdog.camera1               INFO    : Terminating the existing ffmpeg process...
2023-09-19 21:53:55.064803003  [2023-09-19 21:53:55] watchdog.camera1               INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-19 21:53:55.113370442  [2023-09-19 21:53:55] watchdog.camera2               ERROR   : No new recording segments were created for camera2 in the last 120s. restarting the ffmpeg record process...
2023-09-19 21:53:55.113463634  [2023-09-19 21:53:55] watchdog.camera2               INFO    : Terminating the existing ffmpeg process...
2023-09-19 21:53:55.113533931  [2023-09-19 21:53:55] watchdog.camera2               INFO    : Waiting for ffmpeg to exit gracefully...


Go2RTC

2023-09-19 21:51:34.084942471  [INFO] Preparing go2rtc config...
2023-09-19 21:51:34.259949210  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-09-19 21:51:34.278889089  [INFO] Starting go2rtc...
2023-09-19 21:51:34.376516949  21:51:34.376 INF go2rtc version 1.2.0 linux/amd64
2023-09-19 21:51:34.376764990  21:51:34.376 INF [api] listen addr=:1984
2023-09-19 21:51:34.376995991  21:51:34.376 INF [rtsp] listen addr=:8554
2023-09-19 21:51:34.377273320  21:51:34.377 INF [srtp] listen addr=:8443
2023-09-19 21:51:34.377468724  21:51:34.377 INF [webrtc] listen addr=:8555
2023-09-19 21:51:44.086578791  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{
    "camera1": {
        "camera_fps": 5.1,
        "capture_pid": 445,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 451,
        "pid": 441,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "camera2": {
        "camera_fps": 3.4,
        "capture_pid": 448,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 655,
        "pid": 443,
        "process_fps": 3.4,
        "skipped_fps": 0
    },
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "16": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "89": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "96": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "98": {
            "cpu": "2.7",
            "mem": "1.2"
        },
        "113": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "134": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "135": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "136": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "137": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "148": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "165": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "194": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "232": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "426": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "432": {
            "cpu": "0.3",
            "mem": "0.1"
        },
        "433": {
            "cpu": "0.0",
            "mem": "0.7"
        },
        "435": {
            "cpu": "0.3",
            "mem": "0.6"
        },
        "441": {
            "cpu": "0.3",
            "mem": "0.6"
        },
        "442": {
            "cpu": "0.0",
            "mem": "0.3"
        },
        "443": {
            "cpu": "0.7",
            "mem": "0.6"
        },
        "444": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "445": {
            "cpu": "1.3",
            "mem": "0.5"
        },
        "448": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "449": {
            "cpu": "0.0",
            "mem": "0.3"
        },
        "451": {
            "cpu": "2.0",
            "mem": "0.4"
        },
        "655": {
            "cpu": "0.7",
            "mem": "0.3"
        },
        "5241": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "5248": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "5265": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "5291": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "5298": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "5307": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "5310": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "5311": {
            "cpu": "0.3",
            "mem": "0.0"
        },
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.1"
        },
        "MiB": {
            "cpu": "14262.1",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "2"
        },
        "top": {
            "cpu": "users,",
            "mem": "load"
        }
    },
    "detection_fps": 0,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 8.4,
            "pid": 433
        }
    },
    "gpu_usages": {
        "intel-qsv": {
            "gpu": "0.92 %",
            "mem": "- %"
        }
    },
    "service": {
        "last_updated": 1695153925,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 64.1,
                "mount_type": "tmpfs",
                "total": 67.1,
                "used": 3
            },
            "/media/frigate/clips": {
                "free": 226296.5,
                "mount_type": "ext4",
                "total": 249365.4,
                "used": 10327.2
            },
            "/media/frigate/recordings": {
                "free": 226296.5,
                "mount_type": "ext4",
                "total": 249365.4,
                "used": 10327.2
            },
            "/tmp/cache": {
                "free": 226296.5,
                "mount_type": "overlay",
                "total": 249365.4,
                "used": 10327.2
            }
        },
        "temperatures": {},
        "uptime": 831,
        "version": "0.12.1-367d724"
    }
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
