### ISSUE TITLE
[Support]: Frigate crashes with a segmentation fault

### ISSUE THREAD

**Issue by OnFreund** [blakeblackshear/frigate#7891]
### Describe the problem you are having

Once in a while, I see that Frigate restarted. CPU does not seem to be heavily utilized, and I'm not seeing any dropped frames.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: hass
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
ui:
  live_mode: webrtc
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  mode: motion
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
snapshots:
  enabled: true
detect:
  enabled: true
  width: 1280
  height: 720
  fps: 6
motion:
  mask:
    - 415,84,612,84,612,38,415,38
go2rtc:
  streams:
    camera1:
      - rtsp://<url_to_camera>/<main_stream>
    camera2:
      - rtsp://<url_to_camera>/<main_stream>
    camera3:
      - rtsp://<url_to_camera>/<main_stream>
    camera4:
      - rtsp://<url_to_camera>/<main_stream>
    camera5:
      - rtsp://<url_to_camera>/<main_stream>
    camera6:
      - rtsp://<url_to_camera>/<main_stream>
    camera7:
      - rtsp://<url_to_camera>/<main_stream>
  webrtc:
    candidates:
      - frigate:8555
      - frigate.local:8555
cameras:
  camera1:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://<url_to_camera>/<sub_stream>
          roles:
            - detect
    motion:
      mask:
        - 1280,0,1280,374,906,138,764,180,550,0
        - 415,84,612,84,612,38,415,38
    objects:
      track:
        - person
        - cat
  camera2:
    ui:
      order: 9
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://<url_to_camera>/<sub_stream>
          roles:
            - detect
    motion:
      mask:
        - 518,156,842,152,842,42,518,42
    objects:
      track:
        - person
        - cat
  camera3:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera3
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://<url_to_camera>/<sub_stream>
          roles:
            - detect
    motion:
      mask:
        - 1280,0,1280,248,1084,240,878,240,774,314,686,220,614,0
        - 623,0,0,0,0,60,84,260,284,216,430,188,621,81
    objects:
      track:
        - person
        - car
  camera4:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://<url_to_camera>/<sub_stream>
          roles:
            - detect
    motion:
      mask:
        - 0,457,127,500,399,248,1082,107,1001,0,0,0
    objects:
      track:
        - person
        - cat
  camera5:
    ui:
      order: 8
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera5
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://<url_to_camera>/<sub_stream>
          roles:
            - detect
    motion:
      mask:
        - 521,0,1061,0,1052,371,787,330,460,433,422,38
  camera6:
    ui:
      order: 10
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera6
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://<url_to_camera>/<sub_stream>
          roles:
            - detect
  camera7:
    ui:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera7
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://<url_to_camera>/<sub_stream>
          roles:
            - detect
    objects:
      track:
        - person
        - car
```

### Relevant log output

```shell
frigate  | 2023-09-20 11:27:04.856365711  Fatal Python error: Segmentation fault
frigate  | 2023-09-20 11:27:04.856371887
frigate  | 2023-09-20 11:27:04.856374575  Thread 0x00007f1f4a7fc6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.856457891    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate  | 2023-09-20 11:27:04.856461574    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
frigate  | 2023-09-20 11:27:04.856538336    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.856541834    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.856712146    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.856715354
frigate  | 2023-09-20 11:27:04.856717786  Thread 0x00007f1f68ff96c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.856720268    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate  | 2023-09-20 11:27:04.856722935    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
frigate  | 2023-09-20 11:27:04.856725117    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.856771545    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.856774265    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.856776079
frigate  | 2023-09-20 11:27:04.856778245  Thread 0x00007f1f697fa6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.856871183    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate  | 2023-09-20 11:27:04.856874560    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
frigate  | 2023-09-20 11:27:04.857021169    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.857024608    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.857027029    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.857028861
frigate  | 2023-09-20 11:27:04.857030948  Thread 0x00007f1f69ffb6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.857177874    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate  | 2023-09-20 11:27:04.857181664    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
frigate  | 2023-09-20 11:27:04.857184003    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.857186544    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.857240879    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.857243262
frigate  | 2023-09-20 11:27:04.857245441  Thread 0x00007f1f6a7fc6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.857323303    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 261 in wait
frigate  | 2023-09-20 11:27:04.857409194    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 349 in wait
frigate  | 2023-09-20 11:27:04.857412527    File "/opt/frigate/frigate/watchdog.py", line 24 in run
frigate  | 2023-09-20 11:27:04.857549099    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.857552534    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.857554589
frigate  | 2023-09-20 11:27:04.857556740  Thread 0x00007f1f6affd6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.857559318    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 261 in wait
frigate  | 2023-09-20 11:27:04.857724206    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 349 in wait
frigate  | 2023-09-20 11:27:04.857727383    File "/opt/frigate/frigate/stats.py", line 285 in run
frigate  | 2023-09-20 11:27:04.857729836    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.857732310    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.857734107
frigate  | 2023-09-20 11:27:04.857736480  Thread 0x00007f1f6b7fe6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.857938295    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 261 in wait
frigate  | 2023-09-20 11:27:04.857941891    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 349 in wait
frigate  | 2023-09-20 11:27:04.857944349    File "/opt/frigate/frigate/record.py", line 626 in run
frigate  | 2023-09-20 11:27:04.857946728    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.858081813    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.858084360
frigate  | 2023-09-20 11:27:04.858086874  Thread 0x00007f1f6bfff6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.858089433    File "/usr/lib/python3.9/subprocess.py", line 1779 in _execute_child
frigate  | 2023-09-20 11:27:04.858091584    File "/usr/lib/python3.9/subprocess.py", line 951 in __init__
frigate  | 2023-09-20 11:27:04.858197646    File "/usr/lib/python3.9/subprocess.py", line 505 in run
frigate  | 2023-09-20 11:27:04.858201019    File "/opt/frigate/frigate/record.py", line 318 in store_segment
frigate  | 2023-09-20 11:27:04.858203457    File "/opt/frigate/frigate/record.py", line 241 in move_files
frigate  | 2023-09-20 11:27:04.858215196    File "/opt/frigate/frigate/record.py", line 397 in run
frigate  | 2023-09-20 11:27:04.858267783    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.858352206    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.858354811
frigate  | 2023-09-20 11:27:04.858357112  Thread 0x00007f1f909a26c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.858411520    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 261 in wait
frigate  | 2023-09-20 11:27:04.858439145    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 349 in wait
frigate  | 2023-09-20 11:27:04.858478425    File "/opt/frigate/frigate/events.py", line 305 in run
frigate  | 2023-09-20 11:27:04.858517708    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.858563398    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.858565430
frigate  | 2023-09-20 11:27:04.858660330  Thread 0x00007f1f911a36c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.858663534    File "/usr/lib/python3.9/selectors.py", line 416 in select
frigate  | 2023-09-20 11:27:04.858665770    File "/usr/lib/python3.9/multiprocessing/connection.py", line 936 in wait
frigate  | 2023-09-20 11:27:04.858767919    File "/usr/lib/python3.9/multiprocessing/connection.py", line 429 in _poll
frigate  | 2023-09-20 11:27:04.858781350    File "/usr/lib/python3.9/multiprocessing/connection.py", line 262 in poll
frigate  | 2023-09-20 11:27:04.858822746    File "/usr/lib/python3.9/multiprocessing/queues.py", line 113 in get
frigate  | 2023-09-20 11:27:04.858870208    File "/opt/frigate/frigate/events.py", line 70 in run
frigate  | 2023-09-20 11:27:04.858929088    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.858990075    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.858992488
frigate  | 2023-09-20 11:27:04.858994605  Thread 0x00007f1f919a46c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.859019885    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 261 in wait
frigate  | 2023-09-20 11:27:04.859092162    File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 349 in wait
frigate  | 2023-09-20 11:27:04.859118259    File "/opt/frigate/frigate/storage.py", line 181 in run
frigate  | 2023-09-20 11:27:04.859168602    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.859236758    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.859239161
frigate  | 2023-09-20 11:27:04.859241524  Current thread 0x00007f1f921a56c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.859316289    File "/usr/lib/python3.9/selectors.py", line 239 in register
frigate  | 2023-09-20 11:27:04.859319157    File "/usr/lib/python3.9/selectors.py", line 353 in register
frigate  | 2023-09-20 11:27:04.859371101    File "/usr/lib/python3.9/multiprocessing/connection.py", line 930 in wait
frigate  | 2023-09-20 11:27:04.859421347    File "/usr/lib/python3.9/multiprocessing/connection.py", line 429 in _poll
frigate  | 2023-09-20 11:27:04.859482058    File "/usr/lib/python3.9/multiprocessing/connection.py", line 262 in poll
frigate  | 2023-09-20 11:27:04.859534400    File "/usr/lib/python3.9/multiprocessing/queues.py", line 129 in empty
frigate  | 2023-09-20 11:27:04.859594200    File "/opt/frigate/frigate/object_processing.py", line 1012 in run
frigate  | 2023-09-20 11:27:04.859626468    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.859672571    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.859674323
frigate  | 2023-09-20 11:27:04.859684850  Thread 0x00007f1f9a8e96c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.859781216    File "/usr/lib/python3.9/selectors.py", line 416 in select
frigate  | 2023-09-20 11:27:04.859784617    File "/usr/lib/python3.9/socketserver.py", line 232 in serve_forever
frigate  | 2023-09-20 11:27:04.859814669    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.859885721    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.859910293    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.859912071
frigate  | 2023-09-20 11:27:04.859950787  Thread 0x00007f1f99a136c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.860016106    File "/usr/local/lib/python3.9/dist-packages/ws4py/manager.py", line 141 in poll
frigate  | 2023-09-20 11:27:04.860037608    File "/usr/local/lib/python3.9/dist-packages/ws4py/manager.py", line 312 in run
frigate  | 2023-09-20 11:27:04.860086256    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.860149232    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.860151439
frigate  | 2023-09-20 11:27:04.860153735  Thread 0x00007f1fb1bff6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.860206138    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1150 in _loop
frigate  | 2023-09-20 11:27:04.860285690    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1756 in loop_forever
frigate  | 2023-09-20 11:27:04.860367987    File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3591 in _thread_main
frigate  | 2023-09-20 11:27:04.860411726    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.860462367    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.860516356    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.860518709
frigate  | 2023-09-20 11:27:04.860520824  Thread 0x00007f1fb13fe6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.860564647    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate  | 2023-09-20 11:27:04.860627112    File "/usr/lib/python3.9/queue.py", line 171 in get
frigate  | 2023-09-20 11:27:04.860662216    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 159 in loop
frigate  | 2023-09-20 11:27:04.860732538    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 136 in run
frigate  | 2023-09-20 11:27:04.860800048    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 266 in run
frigate  | 2023-09-20 11:27:04.860842462    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.860898233    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.860957252    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.860959681
frigate  | 2023-09-20 11:27:04.860961996  Thread 0x00007f1faebfd6c0 (most recent call first):
frigate  | 2023-09-20 11:27:04.861050250    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate  | 2023-09-20 11:27:04.861053274    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
frigate  | 2023-09-20 11:27:04.861082420    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate  | 2023-09-20 11:27:04.861154356    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate  | 2023-09-20 11:27:04.861183705    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate  | 2023-09-20 11:27:04.861221118
frigate  | 2023-09-20 11:27:04.861223694  Thread 0x00007f1fb5e2e740 (most recent call first):
frigate  | 2023-09-20 11:27:04.861250491    File "/usr/lib/python3.9/selectors.py", line 416 in select
frigate  | 2023-09-20 11:27:04.861282567    File "/usr/lib/python3.9/socketserver.py", line 232 in serve_forever
frigate  | 2023-09-20 11:27:04.861373367    File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 804 in serve_forever
frigate  | 2023-09-20 11:27:04.861455512    File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 1107 in run_simple
frigate  | 2023-09-20 11:27:04.861521873    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1191 in run
frigate  | 2023-09-20 11:27:04.861565990    File "/opt/frigate/frigate/app.py", line 403 in start
frigate  | 2023-09-20 11:27:04.861616999    File "/opt/frigate/frigate/__main__.py", line 16 in <module>
frigate  | 2023-09-20 11:27:04.861663117    File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
frigate  | 2023-09-20 11:27:04.861719030    File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
frigate  | 2023-09-20 11:27:05.188966832  [INFO] Service Frigate exited with code 256 (by signal 11)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-09-20 11:27:05.202375155  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2023-09-20 11:27:05.272594150  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2023-09-20 11:27:05.275454591  exit OK
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2023-09-20 11:27:05.283603297  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"168:95","height":1520,"width":2688}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"6/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"168:95","height":720,"width":1280}]}}]
```

### Frigate stats

```json
{"camera2":{"camera_fps":6.0,"capture_pid":311,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":324,"pid":298,"process_fps":6.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.4"},"1":{"cpu":"0.0","mem":"0.0"},"107":{"cpu":"4.3","mem":"1.2"},"118":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"146":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"1788":{"cpu":"0.0","mem":"0.0"},"1822":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"0.5"},"287":{"cpu":"1.0","mem":"0.1"},"288":{"cpu":"7.3","mem":"0.7"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"4.0","mem":"0.6"},"296":{"cpu":"7.3","mem":"0.6"},"297":{"cpu":"0.0","mem":"0.1"},"298":{"cpu":"2.7","mem":"0.6"},"299":{"cpu":"1.3","mem":"0.6"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.1"},"301":{"cpu":"1.7","mem":"0.6"},"302":{"cpu":"1.0","mem":"0.6"},"303":{"cpu":"0.0","mem":"0.1"},"304":{"cpu":"1.0","mem":"0.6"},"305":{"cpu":"1.0","mem":"0.7"},"306":{"cpu":"0.0","mem":"0.1"},"307":{"cpu":"3.3","mem":"0.6"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"0.0","mem":"0.1"},"311":{"cpu":"3.3","mem":"0.6"},"313":{"cpu":"3.0","mem":"0.3"},"315":{"cpu":"3.3","mem":"0.6"},"316":{"cpu":"0.0","mem":"0.1"},"318":{"cpu":"3.3","mem":"0.6"},"32":{"cpu":"0.0","mem":"0.0"},"322":{"cpu":"3.0","mem":"0.6"},"323":{"cpu":"1.7","mem":"0.2"},"324":{"cpu":"2.7","mem":"0.3"},"325":{"cpu":"2.7","mem":"0.6"},"326":{"cpu":"2.7","mem":"0.3"},"327":{"cpu":"0.0","mem":"0.1"},"329":{"cpu":"2.7","mem":"0.6"},"336":{"cpu":"0.0","mem":"0.1"},"337":{"cpu":"1.7","mem":"0.2"},"341":{"cpu":"2.7","mem":"0.3"},"342":{"cpu":"2.7","mem":"0.3"},"343":{"cpu":"2.0","mem":"0.2"},"348":{"cpu":"2.0","mem":"0.3"},"352":{"cpu":"2.7","mem":"0.2"},"356":{"cpu":"2.3","mem":"0.3"},"360":{"cpu":"1.7","mem":"0.2"},"366":{"cpu":"2.0","mem":"0.2"},"369":{"cpu":"1.3","mem":"0.2"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"24.7","mem":"0.2"},"97":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"14230.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":9.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":16.27,"pid":288}},"camera3":{"camera_fps":6.0,"capture_pid":315,"detection_enabled":1,"detection_fps":2.7,"ffmpeg_pid":326,"pid":299,"process_fps":6.1,"skipped_fps":0.0},"camera1":{"camera_fps":6.0,"capture_pid":307,"detection_enabled":1,"detection_fps":6.4,"ffmpeg_pid":313,"pid":296,"process_fps":6.0,"skipped_fps":0.0},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"camera4":{"camera_fps":6.0,"capture_pid":318,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":341,"pid":301,"process_fps":6.0,"skipped_fps":0.0},"camera5":{"camera_fps":6.1,"capture_pid":322,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":342,"pid":302,"process_fps":6.1,"skipped_fps":0.0},"camera6":{"camera_fps":6.0,"capture_pid":325,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":348,"pid":304,"process_fps":6.0,"skipped_fps":0.0},"service":{"last_updated":1695199756,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":165.3,"mount_type":"tmpfs","total":178.3,"used":13.0},"/media/frigate/clips":{"free":184746.6,"mount_type":"ext4","total":244707.9,"used":47456.3},"/media/frigate/recordings":{"free":184746.6,"mount_type":"ext4","total":244707.9,"used":47456.3},"/tmp/cache":{"free":946.5,"mount_type":"tmpfs","total":1000.0,"used":53.5}},"temperatures":{},"uptime":1325,"version":"0.12.1-367d724"},"camera7":{"camera_fps":6.1,"capture_pid":329,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":356,"pid":305,"process_fps":6.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2342WD-I
