### ISSUE TITLE
[Config Support]: go2rtc bubble support not there?

### ISSUE THREAD

**Issue by terribletrouble** [blakeblackshear/frigate#7895]
### Describe the problem you are having

go2rtc - bubble method does not seem to be implemented in Frigate yet? (dvr163 cameras)

### Version

Starting Frigate (0.12.1-367d724)

### Frigate config file

```yaml
#
#
mqtt:
  enabled: True
  host: hass.xxx.local
  port: 1883
  topic_prefix: frigate
  user: mqtt_user
  password: xxx
#
birdseye:
  enabled: true
  mode: motion
#
record:
  enabled: true
  events:
    retain:
      default: 7
#
objects:
  track:
    - person
    - cat
#
go2rtc:
  streams:
    driveway-ptz-1:
      - bubble://admin:xxx@10.20.1.79:80/bubble/live?ch=0&stream=0
    driveway-ptz-2:
      - bubble://admin:xxx@10.20.1.79:80/bubble/live?ch=0&stream=1

cameras:
#
  basement:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxx@camera-basement.xxx.local:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:xxx@camera-basement.xxx.local:554/h264Preview_01_main
          roles:
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
    birdseye:
      enabled: True
      mode: motion
#
  driveway-ptz:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway-ptz-1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway-ptz-2
          input_args: preset-rtsp-restream
          roles:
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    birdseye:
      enabled: True
      mode: motion
#
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://dock-1.xxx.local:8554/zztest2
          roles:
            - detect
        - path: rtsp://dock-1.xxx.local:8554/zztest1
          roles:
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 480
    birdseye:
      enabled: True
      mode: motion

#
  reolink-duo:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxx@10.20.1.78/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:xxx@10.20.1.78/h264Preview_01_main
          roles:
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 1536
      height: 576
    birdseye:
      enabled: True
      mode: motion
#
  e1-1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxx@10.20.1.80/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:xxx@10.20.1.80/h264Preview_01_main
          roles:
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
    birdseye:
      enabled: True
      mode: motion
#
  e1-2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxx@10.20.1.81/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:xxx@10.20.1.81/h264Preview_01_main
          roles:
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
    birdseye:
      enabled: True
      mode: motion
#
#
```

### Relevant log output

```shell
First section: go2rtc starting up, is it really showing version 1.2.0????
---
frigate    | 2023-09-20 23:18:54.540561670  [INFO] Preparing go2rtc config...
frigate    | 2023-09-20 23:18:54.541066430  [INFO] Starting NGINX...
frigate    | 2023-09-20 23:18:54.541414697  [INFO] Starting Frigate...
frigate    | 2023-09-20 23:18:56.141086265  [INFO] Starting go2rtc...
frigate    | 2023-09-20 23:18:56.254288267  23:18:56.254 INF go2rtc version 1.2.0 linux/amd64
frigate    | 2023-09-20 23:18:56.255098219  23:18:56.255 INF [api] listen addr=:1984
frigate    | 2023-09-20 23:18:56.255782627  23:18:56.255 INF [rtsp] listen addr=:8554
frigate    | 2023-09-20 23:18:56.256508879  23:18:56.256 INF [srtp] listen addr=:8443
frigate    | 2023-09-20 23:18:56.257172777  23:18:56.257 INF [webrtc] listen addr=:8555

Then later on as the system is starting.....:
---
frigate    | 2023-09-20 23:19:00.935052495  23:19:00.934 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: bubble://admin:xxx@10.20.1.79:80/bubble/live?ch=0&stream=1" url=bubble://admin:xxx@10.20.1.79:80/bubble/live?ch=0&stream=1
frigate    | 2023-09-20 23:19:00.935062227  23:19:00.934 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="unsupported scheme: bubble://admin:xxx@10.20.1.79:80/bubble/live?ch=0&stream=1" url=bubble://admin:xxx@10.20.1.79:80/bubble/live?ch=0&stream=1
frigate    | 2023-09-20 23:19:00.935066127  23:19:00.934 WRN [rtsp] error="source 0 error: unsupported scheme: bubble://admin:xxx@10.20.1.79:80/bubble/live?ch=0&stream=1" stream=driveway-ptz-2
frigate    | 2023-09-20 23:19:04.372000240  [INFO] Starting go2rtc healthcheck service...
frigate    | 2023-09-20 23
:19:07.752697927  10.20.1.40 - - [20/Sep/2023:23:19:07 -0400] "GET /api/stats HTTP/1.1" 200 4012 "-" "HomeAssistant/2023.9.2 aiohttp/3.8.5 Python/3.11" "-"
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

The current version of go2rtc support bubble, for the dvr163 cameras. Their version installed as docker works just fine:
https://github.com/AlexxIT/go2rtc

I think that the version integratedinto Frigate maybe older.
I have not seen where this integration is, I was hoping to see a docker image statement, but it seems the code was integrated. Is it just a version thing?
