### ISSUE TITLE
Not able to get bounding box in mediabrowser

### ISSUE THREAD

**Issue by Diondk** [blakeblackshear/frigate#790]
**Describe the bug**
I have enabled snapshots and the option bounding_box: True, but for some reasons the snapshots in HA dont contain the bounding box. Like in your example screenshot.

**Version of frigate**
Output from `/version`

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
mqtt:
  host: xxx.xxx.xxx.xxx
  port: 1883
  user: frigate
  password: xxxxxxxxxx
cameras:
  oprit:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@xxx.xxx.xxx.xxx/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46TEUyMUVCNDlC
          roles:
            - record
            - clips
            - detect
            - rtmp
    width: 1920 # Required: width of the frame for the input with the detect role
    height: 1080 # Required: height of the frame for the input with the detect role
    fps: 5 # Optional: desired fps for your camera for the input with the detect role
    motion: # Optional: camera level motion config
      mask: 639,572,303,595,183,1080,0,1080,0,0,680,0
    best_image_timeout: 60     # to be replaced by a newer image. (default: shown below)
    zones:    # Optional: zones for this camera
      driveway:
        coordinates: 1920,1080,638,583,301,602,176,1080 # Required: List of x,y coordinates to define the polygon of the zone.
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    detect:     # Optional: Camera level detect settings
      enabled: True # This value can be set via MQTT and will be updated in startup based on retained value
      max_disappeared: 10  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
    clips: # Optional: save clips configuration
      enabled: true # Required: enables clips for the camera (default: shown below)
      pre_capture: 5 # Optional: Number of seconds before the event to include in the clips (default: shown below)
      post_capture: 5 # Optional: Number of seconds after the event to include in the clips (default: shown below)
      objects: # Optional: Objects to save clips for. (default: all tracked objects)
        - person
        - car
      retain: # Optional: Camera override for retention settings (default: global values)
        default: 30 # Required: Default retention days (default: shown below)
        objects: # Optional: Per object retention days
          person: 15
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
  achtertuin:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@xxx.xxx.xxx.xxx/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46TEUyMUVCNDlC
          roles:
            - record
            - clips
            - detect
            - rtmp
    width: 1920 # Required: width of the frame for the input with the detect role
    height: 1080 # Required: height of the frame for the input with the detect role
    fps: 5 # Optional: desired fps for your camera for the input with the detect role
    #motion: # Optional: camera level motion config
    #  mask: 639,572,303,595,183,1080,0,1080,0,0,680,0
    best_image_timeout: 60     # to be replaced by a newer image. (default: shown below)
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
    detect:     # Optional: Camera level detect settings
      enabled: True # This value can be set via MQTT and will be updated in startup based on retained value
      max_disappeared: 10  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
    clips: # Optional: save clips configuration
      enabled: true # Required: enables clips for the camera (default: shown below)
      pre_capture: 5 # Optional: Number of seconds before the event to include in the clips (default: shown below)
      post_capture: 5 # Optional: Number of seconds after the event to include in the clips (default: shown below)
      objects: # Optional: Objects to save clips for. (default: all tracked objects)
        - person
        - car
      retain: # Optional: Camera override for retention settings (default: global values)
        default: 10 # Required: Default retention days (default: shown below)
        objects: # Optional: Per object retention days
          person: 15  
  woonkamer:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@xxx.xxx.xxx.xxx/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - record
            - clips
            - detect
    width: 640 # Required: width of the frame for the input with the detect role
    height: 480 # Required: height of the frame for the input with the detect role
    fps: 5 # Optional: desired fps for your camera for the input with the detect role
    #motion: # Optional: camera level motion config
    #  mask: 639,572,303,595,183,1080,0,1080,0,0,680,0
    best_image_timeout: 60     # to be replaced by a newer image. (default: shown below)
    #zones:    # Optional: zones for this camera
    #  driveway:
    #    coordinates: 1920,1080,638,583,301,602,176,1080 # Required: List of x,y coordinates to define the polygon of the zone.
    #    filters:
    #      person:
    #        min_area: 5000
    #        max_area: 100000
    #        threshold: 0.7
    record:
      enabled: false
    detect:     # Optional: Camera level detect settings
      enabled: false # This value can be set via MQTT and will be updated in startup based on retained value
      max_disappeared: 10  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
    clips: # Optional: save clips configuration
      enabled: false # Required: enables clips for the camera (default: shown below)
      pre_capture: 5 # Optional: Number of seconds before the event to include in the clips (default: shown below)
      post_capture: 5 # Optional: Number of seconds after the event to include in the clips (default: shown below)
      objects: # Optional: Objects to save clips for. (default: all tracked objects)
        - person
        - dog
      retain: # Optional: Camera override for retention settings (default: global values)
        default: 10 # Required: Default retention days (default: shown below)
        objects: # Optional: Per object retention days
          person: 15 
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
        
# Optional: 24/7 recording configuration
record:
  # Optional: Enable recording (default: global setting)
  enabled: true
  # Optional: Number of days to retain (default: global setting)
  retain_days: 30

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
  #tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
      car: 15
      
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  # global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  #hwaccel_args:
  #  - -hwaccel
  #  - qsv
  #  - -qsv_device
  #  - /dev/dri/renderD128
  # Optional: global input args (default: shown below)
  #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:   
    # Optional: output args for detect streams (default: shown below)
    #detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 300 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for clips streams (default: shown below)
    #clips: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    #rtmp: -c copy -f flv
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: debug
```

**Frigate container logs**
```
Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
detector.cpu1 INFO : Starting detection process: 49
detector.cpu3 INFO : Starting detection process: 53
detector.cpu2 INFO : Starting detection process: 50
frigate.app INFO : Camera processor started for oprit: 56
frigate.app INFO : Camera processor started for achtertuin: 57
frigate.app INFO : Camera processor started for woonkamer: 58
frigate.app INFO : Capture process started for oprit: 59
frigate.app INFO : Capture process started for achtertuin: 61
frigate.app INFO : Capture process started for woonkamer: 64
frigate.mqtt DEBUG : on_clips_toggle: frigate/woonkamer/clips/set ON
frigate.mqtt INFO : Turning on clips for woonkamer via mqtt
frigate.mqtt DEBUG : on_snapshots_toggle: frigate/woonkamer/snapshots/set ON
frigate.mqtt DEBUG : on_detect_toggle: frigate/woonkamer/detect/set ON
frigate.mqtt INFO : Turning on detection for woonkamer via mqtt
* Starting nginx nginx
...done.
frigate.app WARNING : Camera woonkamer has clips assigned to an input, but clips is not enabled.
frigate.app WARNING : Camera woonkamer has record assigned to an input, but record is not enabled.
frigate.app WARNING : Camera woonkamer has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
detector.cpu1 INFO : Starting detection process: 49
detector.cpu3 INFO : Starting detection process: 53
detector.cpu2 INFO : Starting detection process: 50
frigate.app INFO : Camera processor started for oprit: 56
frigate.app INFO : Camera processor started for achtertuin: 57
frigate.app INFO : Camera processor started for woonkamer: 58
frigate.app INFO : Capture process started for oprit: 59
frigate.app INFO : Capture process started for achtertuin: 61
frigate.app INFO : Capture process started for woonkamer: 64
frigate.mqtt DEBUG : on_clips_toggle: frigate/woonkamer/clips/set ON
frigate.mqtt INFO : Turning on clips for woonkamer via mqtt
frigate.mqtt DEBUG : on_snapshots_toggle: frigate/woonkamer/snapshots/set ON
frigate.mqtt DEBUG : on_detect_toggle: frigate/woonkamer/detect/set ON
frigate.mqtt INFO : Turning on detection for woonkamer via mqtt
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557025d35140] moov atom not found
/media/frigate/recordings/oprit-20210212205704.mp4: Invalid data found when processing input
frigate.record INFO : bad file: oprit-20210212205704.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d7dea5f140] moov atom not found
/media/frigate/recordings/achtertuin-20210212205704.mp4: Invalid data found when processing input
frigate.record INFO : bad file: achtertuin-20210212205704.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557025d35140] moov atom not found
/media/frigate/recordings/oprit-20210212205704.mp4: Invalid data found when processing input
frigate.record INFO : bad file: oprit-20210212205704.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d7dea5f140] moov atom not found
/media/frigate/recordings/achtertuin-20210212205704.mp4: Invalid data found when processing input
frigate.record INFO : bad file: achtertuin-20210212205704.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564be365e140] moov atom not found
/tmp/cache/woonkamer-20210212205721.mp4: Invalid data found when processing input
frigate.events INFO : bad file: woonkamer-20210212205721.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561e34503140] moov atom not found
/tmp/cache/oprit-20210212205722.mp4: Invalid data found when processing input
frigate.events INFO : bad file: oprit-20210212205722.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5592251cc140] moov atom not found
/tmp/cache/achtertuin-20210212205722.mp4: Invalid data found when processing input
frigate.events INFO : bad file: achtertuin-20210212205722.mp4
```
tis containts errors because i restarted the services
**Frigate stats**
```json
Output from frigate's /stats endpoint
```

**FFprobe from your camera**

```
# ffprobe "rtsp://admin:xxxx@xxxx/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46TEUyMUVCNDlC"
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:xxxx@xxxx/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46TEUyMUVCNDlC':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.074000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, progressive), 1920x1080, 100 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

**Screenshots**

**Computer Hardware**
 - OS: unraid
 - Install method: docker
 - Virtualization: unraid
 - Coral Version: none at this moment
 - Network Setup: wired

**Camera Info:**
 - Manufacturer: dahua
 - Model: G42P
 - Resolution: 1920x1080
 - FPS: 5
