### ISSUE TITLE
[Config Support]: Disabled Cam with Autotracking still enabled prevents Frigate from starting

### ISSUE THREAD

**Issue by gotschi** [blakeblackshear/frigate#7908]
### Describe the problem you are having

Camera with onvif: autotracking: True while having the camera enabled: false hinders frigate from starting

Further: disabling autotracking makes it start up fine again.
however if thats the only cam in the config and its disabled there's no need for the PTZ options in the frontend. They get displayed even if no camera with ptz is enabled. Only thing I can do now is to totally remove the onvif: part from my config

### Version

0.13.0-FA2E499

### Frigate config file

```yaml
cam:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://172.17.0.1:8554/cam?mp4
          roles:
            - record
        - path: rtsp://172.17.0.1:8554/cam_low?mp4
          roles:
            - detect
    detect:
      width: 640
      height: 352
    snapshots:
      enabled: True
    zones:
      all:
        coordinates: 229,352,453,352,450,0,236,0
    onvif:
      host: cam.iot
      port: 8080
      user: admin
      password: admin
      autotracking:
        enabled: False
        track:
          - person
        required_zones:
          - all
        return_preset: home
        timeout: 10
```

### Relevant log output

```shell
frigate                    | 2023-09-22 11:28:24.104735693  2023/09/22 11:28:24 [error] 147#147: *16 connect() failed (111: Connection refused) while connecting to upstream, client: ip, server: , request: "GET /api/events?cameras=all&labels=all&zones=all&sub_labels=all&favorites=0&include_thumbnails=0&limit=25 HTTP/1.1", upstream: "http://127.0.0.1:5001/events?cameras=all&labels=all&zones=all&sub_labels=all&favorites=0&include_thumbnails=0&limit=25", host: "server:5000", referrer: "http://server:5000/events"
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
