### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by hatmeh80** [blakeblackshear/frigate#7918]
### Describe the problem you are having

RPI4 93% CPU usage with detection off ?
Any help why is this ?
<img width="978" alt="Screenshot 2023-09-22 at 8 30 18 PM" src="https://github.com/blakeblackshear/frigate/assets/25508643/42450089-9959-49b0-833f-f041516e44b2">
<img width="904" alt="Screenshot 2023-09-22 at 8 31 13 PM" src="https://github.com/blakeblackshear/frigate/assets/25508643/54cc4672-eba0-4ca6-b361-e406bcd47af0">
<img width="921" alt="Screenshot 2023-09-22 at 8 30 59 PM" src="https://github.com/blakeblackshear/frigate/assets/25508643/27ae8ebc-3041-42a8-b271-1f1e23669d56">

P.S : Had 4 dahuha cameras one died, replaced it with hikvision then noticed the high cpu usage, dont know if this is related
I disabled the new camera and it went down to 78%

I guess i have something wrong in the config ?

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.100.237
  user: mqttbroker
  password: *******
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - detect
    detect:
      width: 1280
      height: 720

  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    
  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4
          roles:
            - detect
    detect:
          width: 1280
          height: 720











go2rtc:
  streams:
    frontdoor: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=******_channel=1_stream=0.sdp
    camera2: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=******_channel=2_stream=0.sdp
    camera4: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=******_channel=4_stream=0.sdp
    
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

motion:
  threshold: 20
```

### Relevant log output

```shell
2023-09-22 17:41:42.564239386  [INFO] Starting Frigate...
2023-09-22 17:41:50.247712287  [2023-09-22 20:41:50] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-22 17:41:50.345337373  [2023-09-22 20:41:50] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-09-22 17:41:50.354156636  [2023-09-22 20:41:50] peewee_migrate                 INFO    : Starting migrations
2023-09-22 17:41:50.377063395  [2023-09-22 20:41:50] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-22 17:41:50.473690244  [2023-09-22 20:41:50] detector.cpu                   INFO    : Starting detection process: 299
2023-09-22 17:41:50.475626145  [2023-09-22 20:41:50] frigate.app                    INFO    : Output process started: 301
2023-09-22 17:41:50.541810035  [2023-09-22 20:41:50] frigate.app                    INFO    : Camera processor started for frontdoor: 305
2023-09-22 17:41:50.565479425  [2023-09-22 20:41:50] frigate.app                    INFO    : Camera processor started for camera2: 306
2023-09-22 17:41:50.584302499  [2023-09-22 20:41:50] frigate.app                    INFO    : Camera processor started for camera4: 308
2023-09-22 17:41:50.628718919  [2023-09-22 20:41:50] frigate.app                    INFO    : Capture process started for frontdoor: 309
2023-09-22 17:41:50.667345081  [2023-09-22 20:41:50] frigate.app                    INFO    : Capture process started for camera2: 313
2023-09-22 17:41:50.697916815  [2023-09-22 20:41:50] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-09-22 17:41:50.703920846  [2023-09-22 20:41:50] frigate.app                    INFO    : Capture process started for camera4: 315
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
> RPI4 93% CPU usage with detection off ?
> Any help why is this ?

because you are not using hardware acceleration and it is taxing the rpi to use the CPU to decode 4 streams

**Comment by hatmeh80** [comment]
But i disabled the detecion in the UI 
<img width="972" alt="Screenshot 2023-09-22 at 8 53 37 PM" src="https://github.com/blakeblackshear/frigate/assets/25508643/4b217a39-e067-4181-ba23-e988739704cd">

**Comment by hatmeh80** [comment]
is there any where else to disable detection ?

**Comment by hatmeh80** [comment]
Got it, ordered a coral and should be delivered in a couple of days. Will it help lowering the cpu usage ?

**Comment by NickM-27** [comment]
it will not help with lowering the CPU usage that you see right now, you need to use hwaccel https://docs.frigate.video/configuration/hardware_acceleration#raspberry-pi-34

**Comment by hatmeh80** [comment]
Should i add this to each stream in the frigate.yml ?

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

**Comment by NickM-27** [comment]
or you can just set it globally

**Comment by hatmeh80** [comment]
Lol , Noob here , no idea how to set it globaly :)

**Comment by NickM-27** [comment]
it just means not indented, you could do it like this

```yaml
mqtt:
  host: 192.168.100.237
  user: mqttbroker
  password: *******

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - detect
    detect:
      width: 1280
      height: 720

  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    
  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4
          roles:
            - detect
    detect:
          width: 1280
          height: 720

go2rtc:
  streams:
    frontdoor: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=******_channel=1_stream=0.sdp
    camera2: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=******_channel=2_stream=0.sdp
    camera4: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=******_channel=4_stream=0.sdp
    
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

motion:
  threshold: 20
```
