### ISSUE TITLE
[Config Support]: The timezone appears to be showing as UTC on iOS browser

### ISSUE THREAD

**Issue by madasus** [blakeblackshear/frigate#7931]
### Describe the problem you are having

The timezone appears to be showing as UTC on iOS browser (Tried Safari and Brave).  Using Brave/Safari on my Mac shows the correct timezone.

I have tried to set the ui timezone in the config but no difference

```
ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: America/New_York
```

Any thoughts?

In the docker container i do pass /etc/localtime into the container (and this i assume is working as my Mac shows the correct time)

### Version

0.13 Beta 1

### Frigate config file

```yaml
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: America/New_York
```

### Relevant log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
