### ISSUE TITLE
[HW Accel Support]: Random out of memory errors

### ISSUE THREAD

**Issue by jubjubrsx** [blakeblackshear/frigate#7934]
### Describe the problem you are having

I'm getting some strange random out of memory errors, and machine hard locks. I think might be related to the vaapi drivers memory leak?  But those threads I read on this were a few years old, is this still a problem?

### Version

0.12.1-367D724

### Frigate config file

```yaml
# ~/docker/frigate/config.yml
# yaml-language-server: $schema=http://192.168.150.3:5000/api/config/schema.json

ui:
  use_experimental: false
  live_mode: mse

mqtt:
  host: 192.168.10.10
  port: 1883
  user: mqtt
  password: passwordsareawesome
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
  enabled: true

detectors:
  coral1:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  expire_interval: 10

logger:
  default: info

rtmp:
  enabled: false

live:
  height: 720
  quality: 1

birdseye:
  enabled: true
  restream: False
  width: 640
  height: 360
  quality: 1
  mode: continuous

#############################################################
go2rtc:
  streams:
    
    Front_Porch:
      - rtsp://admin:passwordsareawesome@192.168.150.10:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Front_Porch_sub:
      - rtsp://admin:passwordsareawesome@192.168.150.10:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Back_Porch:
      - rtsp://admin:passwordsareawesome@192.168.150.13:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Back_Porch_sub:
      - rtsp://admin:passwordsareawesome@192.168.150.13:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Air_Conditioner:
      - rtsp://admin:passwordsareawesome@192.168.150.14:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Air_Conditioner_sub:
      - rtsp://admin:passwordsareawesome@192.168.150.14:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Carport:
      - rtsp://admin:passwordsareawesome@192.168.150.12:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Carport_sub:
      - rtsp://admin:passwordsareawesome@192.168.150.12:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Driveway:
      - rtsp://admin:passwordsareawesome@192.168.150.11:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    Driveway_sub:
      - rtsp://admin:passwordsareawesome@192.168.150.11:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1


    Backyard:
      - rtsp://admin:passwordsareawesome@192.168.150.15:554/Streaming/Channels/101
    Backyard_sub:
      - rtsp://admin:passwordsareawesome@192.168.150.15:554/Streaming/Channels/102


    webrtc:
      candidates:
        - 192.168.150.3:8555
        #- stun:8555
##############################################################

cameras:

 Driveway: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 45
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
        pre_capture: 15
        post_capture: 30
    motion:
       mask:
        - 0,0,843,0,960,0,1049,0,1093,152,718,74,421,64,333,61,203,73,114,94,64,108,0,257

 Back_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Back_Porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Back_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 45
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 15
        post_capture: 30
    motion:
      mask:
       - 1012,0,1047,158,890,130,753,106,643,0


 Carport: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Carport
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Carport_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 45
        mode: motion
      events:
        required_zones:
         - Carzone_1
        retain:
          default: 5
          mode: motion
        pre_capture: 15
        post_capture: 30
    zones:
        Carzone_0:
          coordinates: 265,322,271,174,305,90,328,47,450,22,684,24,753,133,719,527,421,586,265,561
        Carzone_1:
          coordinates: 116,576,0,587,0,96,0,96,21,45,147,33


 Air_Conditioner: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Air_Conditioner
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Air_Conditioner_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
          mask:
           - 927,54,933,104,881,87,887,49
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 45
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 15
        post_capture: 30


 Front_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Front_Porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Front_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - bicycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 45
        mode: motion
      events:
        required_zones:
        - FPzone_0
        retain:
          default: 5
          mode: motion
        pre_capture: 15
        post_capture: 30
    motion:
      mask:
        - 872,0,1146,0,1189,58,1219,0,1032,0,1054,59,912,46,809,30,681,32,550,44,500,60,495,0
    zones:
     FPzone_0:
      coordinates: 1280,720,0,720,0,0,612,0,1018,0,1085,175,1201,192,1280,210,1280,433
     FPzone_1:
      coordinates: 1046,0,1280,0,1280,189,1055,163    


 Backyard: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - record
            - rtmp
       -  path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
             - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 #<---- update for your camera's resolution
      height: 360 #<---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          min_area: 700
          mask:
           - 927,54,933,104,881,87,887,49
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 45
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 15
        post_capture: 30
    motion:
      mask:
         - 798,394,664,473,625,488,412,425,426,298,757,300



 247Front_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Front_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 30
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false


 247Driveway: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 30
        mode: all
    detect:
        enabled: false
    birdseye:
      enabled: false

 247Carport: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Carport_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 30
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false

 247Back_Porch: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Back_Porch_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 30
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false

 247Air_Conditioner: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Air_Conditioner_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 30
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false

 247Backyard: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
       -  path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
             - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 30
        mode: all
    detect:
      enabled: false
    birdseye:
      enabled: false
```

### docker-compose file or Docker CLI command

```yaml
# ~/docker/frigate/frigate-compose.yml

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb" # update for your cameras based on calculation
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
      - /dev/dri/renderD128
      - /dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/frigate:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1500000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "_"
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","display_aspect_ratio":"16:9","height":2160,"width":3840}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","display_aspect_ratio":"16:9","height":360,"width":640}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

ankee c800

### Any other information that may be helpful

proxmox 8 
ubuntu server 23.04
passing raw gpu device to VM
passing raw coral m.2 bkey(pci-e adapter)
6gb memory
6 cpu (host=intel 11th gen i5 - rocket lake)

tried to use the 965 driver as stated in the help also the i915 for kicks.
Also tried to pass QSV it fails. (hwaccel_args: preset-intel-qsv-h264)
vaapi usage shows roughly 3-5% on average.
