### ISSUE TITLE
input_args on a camera level not accepted

### ISSUE THREAD

**Issue by mutasim** [blakeblackshear/frigate#794]
**Describe the bug**
The full example [in the docs](https://blakeblackshear.github.io/frigate/configuration/cameras/), has input_args at the camera level as well as the stream level.

I'm keen to do this so that I can set Reolink specific args to both the detect and the clip streams without replicating it for each input stream.

**Version of frigate**
0.8.1

**Config file**
```yaml
cameras:
  # Required: name of the camera
  driveway:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
        - path: rtsp://10.0.10.11:554/mpeg4
          # Required: list of roles for this stream. valid values are: detect,record,clips,rtmp
          # NOTICE: In addition to assigning the record, clips, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - rtmp
      # Optional: camera specific input args (default: inherit)
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
```

**Frigate container logs**
```
Error parsing config: extra keys not allowed @ data['cameras']['driveway']['ffmpeg']['input_args']
```
