### ISSUE TITLE
[Config Support]: Events outside of the zone

### ISSUE THREAD

**Issue by rv10guy** [blakeblackshear/frigate#7956]
### Describe the problem you are having

I have an alley behind my house. I am trying to avoid cars in the alley. I have setup zones but the system regularly has events for cars that never enter my "Main Driveway" zone. I have made the Main Driveway zone smaller but I still have the issue.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  user: ***
  password: ***
  host: ***
  port: 1883
  
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      porch:
        coordinates: 212,105,0,287,0,480,640,480,640,0,387,0,381,104
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      required_zones:
        - porch
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - porch
      enabled: True
    birdseye:
      mode: objects

  Garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
      enabled: True
    birdseye:
      mode: objects

  Back:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      patio:
        coordinates: 141,114,0,257,0,480,640,480,640,0,404,0,394,46
        objects:
          - person
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      required_zones:
        - patio
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - patio
      enabled: True
    birdseye:
      mode: objects

  Driveway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      main_driveway:
        coordinates: 35,463,0,440,0,576,1536,576,1536,284,1397,435,1196,285,1064,248,524,278,483,188,273,388
      backyard:
        coordinates: 35,463,273,388,483,188,125,270,0,326,0,443
        objects:
          - person
      alley:
        coordinates: 1280,0,1536,284,1397,435,1196,285,1064,248,524,278,483,188,123,270,0,326,0,207,190,0
        objects:
          - person
          - cat
          - dog
          - bicycle
    motion:
      mask:
        - 1016,73,1015,123,852,88,861,46
    detect:
      enabled: True 
      width: 1536 
      height: 576 
    snapshots:
      required_zones:
        - main_driveway
        - backyard
        - alley
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - main_driveway
          - backyard
          - alley
      enabled: True
    birdseye:
      mode: objects

objects:
  track:
    - car
    - motorcycle
    - bus
    - person
    - cat
    - dog
    - bicycle
    - package

birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
No relevant logs
```

### Frigate stats

```json
{"Back":{"camera_fps":5.0,"capture_pid":454,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":463,"pid":445,"process_fps":5.0,"skipped_fps":0.0},"Driveway":{"camera_fps":5.1,"capture_pid":461,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":473,"pid":446,"process_fps":5.1,"skipped_fps":0.0},"Front":{"camera_fps":5.1,"capture_pid":447,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":451,"pid":443,"process_fps":5.1,"skipped_fps":0.0},"Garage":{"camera_fps":5.1,"capture_pid":450,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":455,"pid":444,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.2"},"1":{"cpu":"0.0","mem":"0.0"},"113":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"144":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"167":{"cpu":"0.0","mem":"0.0"},"199":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"242":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"428":{"cpu":"0.0","mem":"0.2"},"434":{"cpu":"0.3","mem":"0.0"},"435":{"cpu":"0.0","mem":"0.3"},"437":{"cpu":"1.0","mem":"0.3"},"443":{"cpu":"0.3","mem":"0.3"},"444":{"cpu":"0.3","mem":"0.3"},"445":{"cpu":"0.7","mem":"0.3"},"446":{"cpu":"0.3","mem":"0.3"},"447":{"cpu":"0.7","mem":"0.3"},"450":{"cpu":"0.3","mem":"0.3"},"451":{"cpu":"2.3","mem":"0.2"},"454":{"cpu":"1.3","mem":"0.3"},"455":{"cpu":"1.7","mem":"0.1"},"459":{"cpu":"0.0","mem":"0.1"},"461":{"cpu":"1.7","mem":"0.3"},"462":{"cpu":"4.0","mem":"0.1"},"463":{"cpu":"2.7","mem":"0.2"},"467":{"cpu":"0.0","mem":"0.1"},"471":{"cpu":"1.0","mem":"0.1"},"473":{"cpu":"2.7","mem":"0.2"},"474":{"cpu":"3.0","mem":"0.1"},"475":{"cpu":"0.0","mem":"0.1"},"478":{"cpu":"2.3","mem":"0.1"},"479":{"cpu":"0.0","mem":"0.0"},"480":{"cpu":"0.0","mem":"0.2"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"863":{"cpu":"0.0","mem":"0.0"},"866":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.0"},"97":{"cpu":"1.7","mem":"0.6"},"98":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"29634.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"0","mem":"users,"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.58,"pid":435}},"gpu_usages":{"intel-vaapi":{"gpu":"1.58 %","mem":"- %"}},"service":{"last_updated":1695739969,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":62.4,"mount_type":"tmpfs","total":67.1,"used":4.7},"/media/frigate/clips":{"free":48550.3,"mount_type":"ext4","total":105089.3,"used":51153.5},"/media/frigate/recordings":{"free":48550.3,"mount_type":"ext4","total":105089.3,"used":51153.5},"/tmp/cache":{"free":966.6,"mount_type":"tmpfs","total":1000.0,"used":33.4}},"temperatures":{},"uptime":373,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Here is a pic of the Alley zone from debug:
<img width="1310" alt="Screenshot 2023-09-26 at 9 54 20 AM" src="https://github.com/blakeblackshear/frigate/assets/15802973/3ef72529-a507-4ba4-8f2a-7de42306e654">

Here is a pic of Main Driveway from debug:

<img width="1295" alt="Screenshot 2023-09-26 at 9 54 29 AM" src="https://github.com/blakeblackshear/frigate/assets/15802973/e381ce72-df01-4ae7-afa6-0491b21d043c">

Here is an example of a car being deteted in main driveway when it is not:
<img width="898" alt="Screenshot 2023-09-26 at 9 36 37 AM" src="https://github.com/blakeblackshear/frigate/assets/15802973/2e36917b-6274-4063-a9a4-6162959cf1a3">
