### ISSUE TITLE
[Camera Support]: Frigate 13 Beta 2 PTZ issue with Hikvision camera

### ISSUE THREAD

**Issue by sh0ckwavevr6** [blakeblackshear/frigate#7958]
### Describe the problem you are having

Hi, I have installed the new beta and configured the object autotracking feature. 
I can control the PTZ and call presets using the interface

but when a target is identified, the cameras move to the detection and stops moving with this exception in the logs

> 
> 2023-09-26 14:23:23.827838481  Exception in thread move_thread_PTZ_Roof:
> 2023-09-26 14:23:23.827943917  Traceback (most recent call last):
> 2023-09-26 14:23:23.828007477    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
> 2023-09-26 14:23:23.831246438      self.run()
> 2023-09-26 14:23:23.831449450    File "/usr/lib/python3.9/threading.py", line 892, in run
> 2023-09-26 14:23:23.832084336      self._target(*self._args, **self._kwargs)
> 2023-09-26 14:23:23.832154716    File "/opt/frigate/frigate/ptz/autotrack.py", line 237, in _process_move_queue
> 2023-09-26 14:23:23.832431351      self.onvif.get_camera_status(camera)
> 2023-09-26 14:23:23.832468648    File "/opt/frigate/frigate/ptz/onvif.py", line 359, in get_camera_status
> 2023-09-26 14:23:23.832748494      if status.MoveStatus.PanTilt == "IDLE" and status.MoveStatus.Zoom == "IDLE":
> 2023-09-26 14:23:23.832851232  AttributeError: 'NoneType' object has no attribute 'PanTilt'
> 2023-09-26 14:23:24.712562717  Exception in thread ptz_autotracker:
> 2023-09-26 14:23:24.712571543  Traceback (most recent call last):
> 2023-09-26 14:23:24.712573611    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
> 2023-09-26 14:23:24.713094848      self.run()
> 2023-09-26 14:23:24.713190971    File "/opt/frigate/frigate/ptz/autotrack.py", line 128, in run
> 2023-09-26 14:23:24.713471247      self.ptz_autotracker.camera_maintenance(camera_name)
> 2023-09-26 14:23:24.713546015    File "/opt/frigate/frigate/ptz/autotrack.py", line 399, in camera_maintenance
> 2023-09-26 14:23:24.714410313      self.onvif.get_camera_status(camera)
> 2023-09-26 14:23:24.714521002    File "/opt/frigate/frigate/ptz/onvif.py", line 359, in get_camera_status
> 2023-09-26 14:23:24.714761302      if status.MoveStatus.PanTilt == "IDLE" and status.MoveStatus.Zoom == "IDLE":
> 2023-09-26 14:23:24.714787563  AttributeError: 'NoneType' object has no attribute 'PanTilt'

### Version

0.13.0-0858859

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci:0
mqtt:
  # Required: host name
  host: 192.168.2.11
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: SecureUser
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: SecurePassword
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
record: # how long to record before and after motion
    events:
        pre_capture: 5
        post_capture: 10
        
cameras:
  PTZ_Roof:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:SecurePassword@192.168.50.200:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    onvif:
        host: 192.168.50.200
        port: 80
        user: admin
        password: SecurePassword
        autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
          enabled: True
        # Optional: list of objects to track from labelmap.txt (default: shown below)
          track:
            - person
            - bike
            - dog
            - car
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
          required_zones:
            - Rue
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
          return_preset: preset 1
        # Optional: Seconds to delay before returning to preset. (default: shown below)
          timeout: 10
    detect:
      width: 1920
      height: 1080
    record: # what you want Frigate to record
            enabled: True
           # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
           #     days: 1
           #     mode: all
            events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
                retain:
                    mode: active_objects
                    default: 30
    motion:
      mask:
       - 44,1080,776,1080,747,1004,47,1018
    snapshots:
            enabled: True
            retain:
                default: 30
    zones:  
      Rue:
        coordinates: 826,213,1314,155,1776,133,1869,224,1824,536,1195,1080,0,1049,0,508

    objects:
        track:
        - person
        - bike
        - dog
        - car


  Front_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:SecurePassword@192.168.50.201:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
    record: # what you want Frigate to record
            enabled: True
           # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
           #     days: 1
           #     mode: all
            events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
                retain:   
                    mode: active_objects
                    default: 30
    zones:  
      Porch:
        coordinates: 1535,1080,541,1080,427,812,711,714,995,597,1369,446,1773,722
    motion:
        mask:
          - 1350,0,1138,0,1070,298,1350,312
          - 1920,117,1920,256,1734,126,1761,45  
          - 45,1023,795,1025,795,960,41,956

    objects:
      filters:
        dog:
          mask:
          - 1350,0,1138,0,1070,298,1350,312
        cat: 
          mask:
          - 1350,0,1138,0,1070,298,1350,312
        person:
          mask:
          - 1350,0,1138,0,1070,298,1350,312
        car:
          mask:
          - 1920,117,1920,256,1714,133,1761,45
      track:
        - person
        - dog
        - cat
        - car
        - bicycle  
    snapshots:
            enabled: True
            retain:
                default: 30
  Parking:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:SecurePassword@192.168.50.203:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
    record: # what you want Frigate to record
            enabled: True
           # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
           #     days: 1
           #     mode: all
            events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
                retain:
                    mode: active_objects
                    default: 30
    motion:
        mask:
          - 45,1080,795,1080,791,999,45,1015
    objects:
        track:
        - person
        - dog
        - cat
        - bicycle
    snapshots:
            enabled: True
            retain:
                default: 30
  Patio:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:SecurePassword@192.168.50.208:554/Streaming/Channels/101/
          roles:
            - audio
            - detect
            - record    
            

    detect:
      width: 1920
      height: 1080
    record: # what you want Frigate to record
            enabled: True
           # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
           #     days: 1
           #     mode: all
            events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
                retain:
                    mode: active_objects
                    default: 30
    objects:
        track:
        - person
        - dog
        - cat
    
    audio:
      enabled: True
      listen:
        - bark
        - speech
        - yell


    snapshots:
            enabled: True
            retain:
                default: 30
  Back_Yard:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:SecurePassword@192.168.50.207:554/Streaming/Channels/101/
          roles:
            - audio
            - detect
            - record
            


    detect:
      width: 1920
      height: 1080
    record: # what you want Frigate to record
            enabled: True
           # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
           #     days: 1
           #     mode: all
            events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
                retain:
                    mode: active_objects
                    default: 30
    objects:
        track:
        - person
        - dog
        - cat
    
    audio:
      enabled: True
      listen:
        - bark
        - speech
        - yell
        
          
    snapshots:
            enabled: True
            retain:
                default: 30
```

### Relevant log output

```shell
2023-09-26 14:23:23.827838481  Exception in thread move_thread_PTZ_Roof:
2023-09-26 14:23:23.827943917  Traceback (most recent call last):
2023-09-26 14:23:23.828007477    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-09-26 14:23:23.831246438      self.run()
2023-09-26 14:23:23.831449450    File "/usr/lib/python3.9/threading.py", line 892, in run
2023-09-26 14:23:23.832084336      self._target(*self._args, **self._kwargs)
2023-09-26 14:23:23.832154716    File "/opt/frigate/frigate/ptz/autotrack.py", line 237, in _process_move_queue
2023-09-26 14:23:23.832431351      self.onvif.get_camera_status(camera)
2023-09-26 14:23:23.832468648    File "/opt/frigate/frigate/ptz/onvif.py", line 359, in get_camera_status
2023-09-26 14:23:23.832748494      if status.MoveStatus.PanTilt == "IDLE" and status.MoveStatus.Zoom == "IDLE":
2023-09-26 14:23:23.832851232  AttributeError: 'NoneType' object has no attribute 'PanTilt'
2023-09-26 14:23:24.712562717  Exception in thread ptz_autotracker:
2023-09-26 14:23:24.712571543  Traceback (most recent call last):
2023-09-26 14:23:24.712573611    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-09-26 14:23:24.713094848      self.run()
2023-09-26 14:23:24.713190971    File "/opt/frigate/frigate/ptz/autotrack.py", line 128, in run
2023-09-26 14:23:24.713471247      self.ptz_autotracker.camera_maintenance(camera_name)
2023-09-26 14:23:24.713546015    File "/opt/frigate/frigate/ptz/autotrack.py", line 399, in camera_maintenance
2023-09-26 14:23:24.714410313      self.onvif.get_camera_status(camera)
2023-09-26 14:23:24.714521002    File "/opt/frigate/frigate/ptz/onvif.py", line 359, in get_camera_status
2023-09-26 14:23:24.714761302      if status.MoveStatus.PanTilt == "IDLE" and status.MoveStatus.Zoom == "IDLE":
2023-09-26 14:23:24.714787563  AttributeError: 'NoneType' object has no attribute 'PanTilt'
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1536,"width":2048}]}}]
```

### Frigate stats

```json
{"Back_Yard":{"camera_fps":5.1,"capture_pid":363,"detection_enabled":1,"detection_fps":46.2,"ffmpeg_pid":369,"pid":343,"process_fps":3.6,"skipped_fps":1.5},"Front_Door":{"camera_fps":5.1,"capture_pid":349,"detection_enabled":1,"detection_fps":10.4,"ffmpeg_pid":354,"pid":337,"process_fps":5.1,"skipped_fps":0.0},"PTZ_Roof":{"camera_fps":5.0,"capture_pid":345,"detection_enabled":1,"detection_fps":5.2,"ffmpeg_pid":350,"pid":336,"process_fps":5.1,"skipped_fps":0.0},"Parking":{"camera_fps":5.1,"capture_pid":353,"detection_enabled":1,"detection_fps":19.8,"ffmpeg_pid":360,"pid":339,"process_fps":5.1,"skipped_fps":0.0},"Patio":{"camera_fps":5.1,"capture_pid":358,"detection_enabled":1,"detection_fps":19.2,"ffmpeg_pid":365,"pid":341,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.3","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.2"},"99":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"python3 -u -m frigate","cpu":"14.3","cpu_average":"14","mem":"5.0"},"120":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"293":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"295":{"cmdline":"frigate.recording_manager","cpu":"2.5","cpu_average":"7","mem":"2.2"},"304":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(51)","cpu":"0.3","cpu_average":"0","mem":"0.1"},"305":{"cmdline":"frigate.detector.coral","cpu":"28.8","cpu_average":"25","mem":"2.0"},"318":{"cmdline":"frigate.output       ","cpu":"4.7","cpu_average":"4","mem":"1.9"},"320":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"7.4","cpu_average":"6","mem":"0.7"},"321":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"322":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"323":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"324":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"325":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"336":{"cmdline":"frigate.process:PTZ_Roof","cpu":"87.2","cpu_average":"85","mem":"2.4"},"337":{"cmdline":"frigate.process:Front_Door","cpu":"6.5","cpu_average":"4","mem":"2.0"},"339":{"cmdline":"frigate.process:Parking","cpu":"11.5","cpu_average":"9","mem":"2.1"},"341":{"cmdline":"frigate.process:Patio","cpu":"12.4","cpu_average":"8","mem":"2.0"},"343":{"cmdline":"frigate.process:Back_Yard","cpu":"25.7","cpu_average":"25","mem":"2.1"},"345":{"cmdline":"frigate.capture:PTZ_Roof","cpu":"3.4","cpu_average":"3","mem":"1.9"},"349":{"cmdline":"frigate.capture:Front_Door","cpu":"4.0","cpu_average":"3","mem":"1.9"},"350":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:SecurePassword@192.168.50.200:554/Streaming/Channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/PTZ_Roof-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.9","cpu_average":"5","mem":"0.9"},"353":{"cmdline":"frigate.capture:Parking","cpu":"3.7","cpu_average":"3","mem":"1.9"},"354":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:SecurePassword@192.168.50.201:554/Streaming/Channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front_Door-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.7","cpu_average":"7","mem":"0.8"},"358":{"cmdline":"frigate.capture:Patio","cpu":"3.4","cpu_average":"3","mem":"1.9"},"360":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:SecurePassword@192.168.50.203:554/Streaming/Channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Parking-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.6","cpu_average":"4","mem":"0.8"},"363":{"cmdline":"frigate.capture:Back_Yard","cpu":"4.0","cpu_average":"3","mem":"1.9"},"365":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:SecurePassword@192.168.50.208:554/Streaming/Channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Patio-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.2","cpu_average":"6","mem":"0.8"},"368":{"cmdline":"frigate.audio_manager","cpu":"2.5","cpu_average":"0","mem":"2.0"},"369":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:SecurePassword@192.168.50.207:554/Streaming/Channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Back_Yard-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"7.7","cpu_average":"7","mem":"0.9"},"375":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://admin:SecurePassword@192.168.50.208:554/Streaming/Channels/101/ -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"2.2","cpu_average":"2","mem":"0.3"},"378":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -rtsp_transport tcp -timeout 5000000 -vn -i rtsp://admin:SecurePassword@192.168.50.207:554/Streaming/Channels/101/ -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"2.8","cpu_average":"2","mem":"0.3"},"2115":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":100.8,"detectors":{"coral":{"detection_start":1695753221.368401,"inference_speed":8.98,"pid":305}},"gpu_usages":{"intel-vaapi":{"gpu":"7.52%","mem":"-%"}},"processes":{"audioDetector":{"pid":368},"go2rtc":{"pid":89},"logger":{"pid":293},"recording":{"pid":295}},"service":{"last_updated":1695753221,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":223.6,"mount_type":"tmpfs","total":256.0,"used":32.4},"/media/frigate/clips":{"free":352383.9,"mount_type":"ext4","total":402075.4,"used":29195.6},"/media/frigate/recordings":{"free":352383.9,"mount_type":"ext4","total":402075.4,"used":29195.6},"/tmp/cache":{"free":929.4,"mount_type":"tmpfs","total":953.7,"used":24.3}},"temperatures":{"apex_0":62.55},"uptime":622,"version":"0.13.0-0858859"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Hikvision DS-2DE3304W-DE Firmware: V5.5.71 build 180725

**Comment by NickM-27** [comment]
This may be fixed by https://github.com/blakeblackshear/frigate/pull/7713

**Comment by NickM-27** [comment]
CC @hawkeye217

**Comment by hawkeye217** [comment]
@sh0ckwavevr6 Your camera might not support the ONVIF `MoveStatus` property:

> 5.3.7 GetStatus
> A PTZ-capable device shall be able to report its PTZ status through the GetStatus command. The PTZ status contains
> the following information:
> • Position (optional) – Specifies the absolute position of the PTZ unit together with the space references. The
> default absolute spaces of the corresponding PTZ configuration shall be referenced within the position element.
> This information shall be present if the device signals support via the capability StatusPosition.
> • MoveStatus (optional) – Indicates if the pan/tilt/zoom device unit is currently moving, idle or in an unknown
> state. This information shall be present if the device signals support via the capability MoveStatus. The state
> Unknown shall not be used during normal operation, but is reserved to initialization or error conditions.

https://www.onvif.org/onvif/specs/srv/ptz/ONVIF-PTZ-Service-Spec.pdf

Without this property, there's no way for the autotracking code to determine when your PTZ starts and stops moving.

Could you add this to your config:

```
logger:
  default: info
  logs:
    frigate.ptz.autotrack: debug
    frigate.ptz.onvif: debug
```

... then paste your log after restarting Frigate? The debug log should print all of the ONVIF capabilities of your camera on startup. Then we can see if there's a way to work around the issue.
