### ISSUE TITLE
[Config Support]: beta-2 motion option (treshold) in camera

### ISSUE THREAD

**Issue by CoMPaTech** [blakeblackshear/frigate#7968]
### Describe the problem you are having

Trying to add `treshold` to motion yields config validation error

### Version

0.13.0-0858859

### Frigate config file

```yaml
somecam:
    live:
      stream_name: somecam
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/somecam
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://127.0.0.1:8554/somecam_sub
          input_args: preset-rtsp-restream
          roles:
          - detect
    record:
      enabled: true
    motion:
      treshold: 10
    snapshots:
      enabled: true
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1024
```

### Relevant log output

```shell
frigate  | 2023-09-27 03:50:54.295038945  1 validation error for FrigateConfig
frigate  | 2023-09-27 03:50:54.295040096  cameras -> somecam-> motion -> treshold
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

PCIe

### Any other information that may be helpful

Sifted through config.py seems MotionConfig is just imported to Camera and should work (so either misreading or misinterpreting)
