### ISSUE TITLE
[Config Support]: H265 support

### ISSUE THREAD

**Issue by 2Belette** [blakeblackshear/frigate#7970]
### Describe the problem you are having

I would like to use H265 on my UNV camera with Frigate.
Is it because my Intel GPU is not supporting it ?
The only change I made from my working H264 config is hwaccel_args: preset-intel-qsv-h265 insted of hwaccel_args: preset-intel-qsv-h264

### Version

0.13.0-beta2

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-intel-qsv-h265
  output_args:
    record: preset-record-generic-audio-aac

live:
  height: 1920
  quality: 1

birdseye:
  enabled: True
  width: 2560
  height: 1920
  quality: 1
  mode: continuous

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True

detect:
  width: 2560
  height: 1440
  fps: 5
  enabled: True
  max_disappeared: 25

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 5
      mode: active_objects

go2rtc:
  streams:
    cam1:
        - rtsp://admin:pass@ip:554/media/video0

  webrtc:
    candidates:
      - ip:8555
      - stun:8555

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@ip:554/media/video0
          roles:
            - detect
    motion:
      mask:
        - 0,1162,803,951,1853,415,2050,377,2560,451,2560,0,0,0
    rtmp:
      enabled: False
    detect:
      width: 2560
      height: 1440
```

### Relevant log output

```shell
vainfo: VA-API version: 1.19 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.3.2 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP


2023-09-27 12:12:28.692195578  [extract_extradata @ 0x7ff8d01ddcc0] No start code is found.
2023-09-27 12:12:28.692270954  [ WARN:0@15.372] global cap_ffmpeg_impl.hpp:1139 open Unable to read codec parameters from stream (Invalid data found when processing input)
2023-09-27 12:12:28.718926387  [2023-09-27 12:12:28] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/cam1-20230927121214.mp4
2023-09-27 12:12:28.718953893  [2023-09-27 12:12:28] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/cam1-20230927121214.mp4
2023-09-27 12:12:33.711878275  [2023-09-27 12:12:33] watchdog.cam1                  INFO    : No frames received from cam1 in 20 seconds. Exiting ffmpeg...
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

H264 is working perfectly

**Comment by 2Belette** [comment]
Many thanks @NickM-27 it does solve my issue !

I am now with another one, as my browser is not able to play H265, so I tried :
```
go2rtc:
  streams:
    cam1:
        - rtsp://admin:pass@ip:554/media/video0
        - "ffmpeg:cam1#video=h264"
```

but still not able to see the WebRTC stream.

Is there also a way to convert in fly the recordings as it is like am also not able to play them in my browser.

Many thanks
