### ISSUE TITLE
[HW Accel Support]: hwaccel_args: preset-vaapi worked in 0.12 no longer in 0.13beta

### ISSUE THREAD

**Issue by rourke750** [blakeblackshear/frigate#7975]
### Describe the problem you are having

ffmpeg:
  hwaccel_args: preset-vaapi

Used to work in 12 but now in 13 it no longer works.

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  host: ####
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ####
  password: #####

birdseye:
  enabled: True
  mode: continuous

#ffmpeg:
#  hwaccel_args: preset-vaapi
#  hwaccel_args: preset-rpi-64-h264

detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3

#ffmpeg:
#  hwaccel_args: -c:v h264_v4l2m2m
go2rtc:
  streams:
    basement_camera:
      - rtsp://192.168.1.148:8554/basement
    front_door:
      - rtsp://192.168.1.148:8554/front
      - "ffmpeg:front_door#video=h264"
    garage:
      - rtsp://###:###@192.168.50.102:554/cam/realmonitor?channel=1&subtype=1
    backyard:
      - rtsp://###:###@192.168.50.104:554/cam/realmonitor?channel=1&subtype=1

cameras:
  # Required: name of the camera
  basement_camera:
    enabled: True
    # Required: ffmpeg settings for the camera
    ffmpeg:
      output_args: 
        record: preset-record-generic-audio-copy
      # Required: A list of input streams for the camera. See documentation for more information.
#      input_args:
#        - -avoid_negative_ts
#        - make_zero
#        - -fflags
#        - nobuffer
#        - -flags
#        - low_delay
#        - -strict
#        - experimental
#        - -fflags
#        - +genpts+discardcorrupt
#        - -use_wallclock_as_timestamps
#        - "1"
      inputs:
          # Required: the path to the stream
          # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
        - path: rtsp://127.0.0.1:8554/basement_camera
          input_args: preset-rtsp-restream
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - record
    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 1920
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 1080
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60

    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: True
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
          - cat
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
          mode: active_objects
          # Optional: Per object retention days

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
  front_door:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream-low-latency
          #input_args: preset-rtsp-restream
          roles:
            - detect
            - record

    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 1920
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 1080
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60

    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: True
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
          - car
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
          # Optional: Per object retention days

    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 704
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 480
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60
    record:
      # Optional: Enable recording (default: global setting)
      enabled: True
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
          - car
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
    objects:
      track:
        - person
        - car
        - cat

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 704
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 480
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    best_image_timeout: 60
    record:
      # Optional: Enable recording (default: global setting)
      enabled: True
      # Optional: Number of days to retain (default: global setting)
      retain:
        days: 7
        mode: motion
      events:
#        enabled: True
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save events for. (default: all tracked objects)
        objects:
          - person
        # Optional: Restrict events to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 10
    objects:
      track:
        - person
        - cat
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2
    shm_size: "100mb"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /home/rourke750/config:/config
      - /home/rourke750/clips:/clips
      - /home/rourke750/media:/media/frigate
      - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 100000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "###"
      LIBVA_DRIVER_NAME: "radeonsi"
      DISPLAY: ":0.0"
      XDG_RUNTIME_DIR: "/run/user/1000"
      PLUS_API_KEY: "###"
    healthcheck:
      test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m
```

### Relevant log output

```shell
2023-09-27 19:00:42.100416564  [2023-09-27 19:00:42] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2023-09-27 19:00:42.149366479  [2023-09-27 19:00:42] frigate.video                  ERROR   : backyard: Unable to read frames from ffmpeg process.
2023-09-27 19:00:42.149638745  [2023-09-27 19:00:42] frigate.video                  ERROR   : backyard: ffmpeg process is not running. exiting capture thread...
2023-09-27 19:00:45.811731726  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fd6c0007540] moov atom not found
2023-09-27 19:00:45.814628804  [ERROR:0@12.370] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2023-09-27 19:00:45.814645719
2023-09-27 19:00:45.814665116  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2023-09-27 19:00:45.814670660
2023-09-27 19:00:45.814675441
2023-09-27 19:00:45.854760874  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fd6c0015b40] moov atom not found
2023-09-27 19:00:45.855135995  [ERROR:0@12.410] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2023-09-27 19:00:45.855145766
2023-09-27 19:00:45.855156199  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2023-09-27 19:00:45.855161543
2023-09-27 19:00:45.855166421
2023-09-27 19:00:45.895336961  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fd6c0017c00] moov atom not found
2023-09-27 19:00:45.896416517  [ERROR:0@12.451] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2023-09-27 19:00:45.896430893
2023-09-27 19:00:45.896439216  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2023-09-27 19:00:45.896443780
2023-09-27 19:00:45.896447803
2023-09-27 19:00:45.940160466  [2023-09-27 19:00:45] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/backyard-20230927190042.mp4
2023-09-27 19:00:45.942546487  [2023-09-27 19:00:45] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/backyard-20230927190042.mp4
```

### FFprobe output from your camera

```shell
ffprobe rtsp://127.0.0.1:8554/garage
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5617b3945140] method SETUP failed: 461 Unsupported transport

Input #0, rtsp, from 'rtsp://127.0.0.1:8554/garage':
  Metadata:
    title           : go2rtc/1.7.1
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 704x480, 5 fps, 100 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

amcrest

### Any other information that may be helpful

Did work in 12 no longer in 13.  Removing the hw acceleration option everything works.
