### ISSUE TITLE
[HW Accel Support]: Can't get docker fire up, I think due to a GPU Driver issue

### ISSUE THREAD

**Issue by ShooterQ** [blakeblackshear/frigate#7976]
### Describe the problem you are having

When trying to start my docker, I get this error message:

"Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]" 

![docker compose](https://github.com/blakeblackshear/frigate/assets/37904834/38d50377-ad4a-41a6-af44-d6bfdc4926db)

When the problem started, I was running the 525 driver for my GPU, then updated to 535. I went back to 515 and then 525 again with no changes. Nvidia driver and ffmpeg seem to be working alright from the following: 

![nvidia and ffmpeg](https://github.com/blakeblackshear/frigate/assets/37904834/9831b0b5-8180-4cb0-844e-6651123e30ca)

### Version

Version 0.12

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.64
  port: 1883
  user:
  password:

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  restream: True
  width: 1920
  height: 1080
  quality: 5
  mode: motion

ffmpeg: 
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream
  output_args: 
    record: preset-record-generic
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "500mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Coral USB
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/Documents/Frigate Config File/config.yaml:/config/config.yml:ro
      - /mnt/footage/:/media/frigate
#     - ./media/:/media/frigate
      - type: tmpfs # Optional: Set to 2GB
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8554:8554" #RTSP Feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      PLUS_API_KEY:
```

### Relevant log output

```shell
N/A, I believe, I'm not up and running.
```

### FFprobe output from your camera

```shell
N/A, I believe, I'm not up and running.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

Running Ubuntu 22.04 LTS

I've been trying to fix this for awhile myself to no avail. Previous to this, I had a everything working with hardware acceleration for decoding using an Nvidia Quadro P400. CPU is i5-10500H. One day, I believe in July, everything just stopped working. I've been trying to fix the issue myself with research but I think I've hit my limit.

I read a few other issue threads here with the same error output that makes it seem like there's no driver or no communication with the driver, so I tried the following from what I could find: 

- Removing the "count" from the docker-compose file. 
- Adding "NVIDIA_VISIBLE_DEVICES: all" to the environment section.
- Made sure to install the ["decode" bit from here](https://github.com/blakeblackshear/frigate/issues/3619#issuecomment-1209564760) but it was already installed
- Changed to a server version of the same nvidia drivers

I'm not sure what else to do. Thank you for your help, I believe I'm just going to have to go back to quicksync for now until I find a solution.
