### ISSUE TITLE
[Support]: Clips not recording

### ISSUE THREAD

**Issue by gradation0746** [blakeblackshear/frigate#7980]
### Describe the problem you are having

I have three cameras connected to Frigate, two local and one remote. The two local cameras record just fine, no problem. The local camera doesn't record (the local/remote location is very likely not the problem, just how I separate them in my head while working on things). 

I have tried all of the ffmpeg input args to no avail.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mountaineer: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://the.correct.url.has.been.redacted # <----- The stream you want to use for detection
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2688 # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
    snapshots:
      enabled: true
      retain:
        default: 3
      required_zones:
        - driveway
    record:
      enabled: True
      retain:
        days: 3
        mode: active_objects
      events:
        required_zones:
          - driveway
    zones:
      driveway:
        coordinates: 2475,1520,2507,1408,2541,1261,2580,1052,2584,820,2596,650,2584,481,2547,301,2495,287,2380,263,2260,257,2155,257,2030,253,1883,246,1675,246,1523,250,1327,263,1194,263,994,261,824,253,743,285,683,327,703,374,683,491,618,646,539,737,457,859,354,1040,271,1188,190,1420,141,1520
    objects:
      filters:
        person:
          mask:
            - 832,158,838,79,778,79,778,164
            - 737,1222,806,798,655,810,535,1198
```

### Relevant log output

```shell
2023-09-28 08:22:56.942304134  [2023-09-28 08:22:56] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/mountaineer-20230928082243.mp4: 0 - b'[extract_extradata @ 0x5638057e4700] No start code is found.\n/tmp/cache/mountaineer-20230928082243.mp4: Invalid data found when processing input\n'
2023-09-28 08:22:56.942308795  [2023-09-28 08:22:56] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/mountaineer-20230928082243.mp4

(it's this over and over, only the time stamp changes).
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hevc @ 0x5588fa2ce600] VPS 0 does not exist
    Last message repeated 1 times
Input #0, rtsp, from 'rtsp://admin:Mountaineer123%21@173.92.204.193:554/media/video1':
  Metadata:
    title           : VCP IPC Realtime stream
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 2688x1520, 25 fps, 25 tbr, 90k tbn, 25 tbc
  Stream #0:1: Data: none
[hevc @ 0x5588fa320580] VPS 0 does not exist
Unsupported codec with id 0 for input stream 1
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A (I didn't install)

**Comment by NickM-27** [comment]
You could maybe try adding these output args to that camera specifically and see if it helps

```yaml
cameras:
  mountaineer: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://the.correct.url.has.been.redacted # <----- The stream you want to use for detection
          input_args: preset-rtsp-generic
```
