### ISSUE TITLE
[Support]: Sometimes black video with only audio

### ISSUE THREAD

**Issue by dopeytree** [blakeblackshear/frigate#7995]
### Describe the problem you are having

Am noticing past few days sometimes video is shown as black with only audio.
Specifically on bird cam.
It seems to be corrupting somewhere. 
If you download the clip it is just audio with a black rectangle shown in VLC.

How do I fix this?

My cameras are annke c500. 

### Version

0.12.1-367d724

### Frigate config file

```yaml
# Configuration File
# Used https://docs.frigate.video/configuration/#vscode-configuration-schema

mqtt:
  enabled: true
  host: 192.168.22.2
  port: 1883
   # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user:
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password:
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
  

detectors:
  coral:
    type: edgetpu
    device: usb   


# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  #width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  #height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  #fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 75
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 20

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.3
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 30
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true


# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 16
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-vaapi
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic-audio-aac
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 16 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic-audio-aac
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic


# Optional: Restream configuration
# Uses https://github.com/AlexxIT/go2rtc (v1.7.1)
go2rtc:
   streams:
    #barn HQ:
    # - rtsp://MPG7QbYQ:ICRGvtBU2xo3DxMy@192.168.22.202:554/live/ch0
    road_1080p HQ: rtsp://EWLHSHKY:XGEJzBByF2IE3c@192.168.44.5:554/live/ch0
      #
    road_cam HQ: rtsp://admin:annke2023@10.0.0.2:554/H265/ch1/main/av_stream
      #
    porch_cam HQ: rtsp://admin:annke2023@10.0.0.3:554/H265/ch1/main/av_stream
      #
    bird_cam HQ:  rtsp://admin:annke2023@10.0.0.7:554/H265/ch1/main/av_stream
      #
    barn HQ: rtsp://admin:annke2023@10.0.0.4:554/H265/ch1/main/av_stream
      #
    kitchen_cam HQ: rtsp://admin:annke2023@10.0.0.5:554/H265/ch1/main/av_stream
      #
    house_cam HQ: rtsp://admin:annke2023@10.0.0.6:554/H265/ch1/main/av_stream
      #
    


cameras:
  #
  bird_cam: # - Brand: Annke - Quality:3k
    snapshots:
      enabled: true
      bounding_box: false
      quality: 100
      #required_zones:
          #- bird-zone
    #  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:annke2023@10.0.0.7:554/Streaming/Channels/102 # SQ Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/bird_cam%20HQ?mp4  # HQ Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640  
      height: 360
      fps: 4
      stationary:
        interval: 0
        threshold: 70
    objects:
      track:
        - bird
      filters:
        bird:
          min_area: 1000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
        - bird
        retain:
          default: 28
          mode: active_objects 
     # Optional: Configuration for the jpg snapshots published via MQTT        
    mqtt:
      enabled: true
      bounding_box: false #this will get rid of the box around the bird. We already know it is a bird. Sheesh.
      timestamp: false #this will get rid of the time stamp in the image. 
      quality: 100 #default quality is 70, which will get you lots of compression artifacts


  road_1080p: # no3 - road 1080p - Cam name - Brand: Wansview - Quality:1080p
    snapshots:
      enabled: true
      bounding_box: true
      quality: 99
    #  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://EWLHSHKY:XGEJzBByF2IE3c@192.168.44.5:554/live/ch1 # SD Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/road_1080p?mp4  # HD Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 768  
      height: 432
      fps: 4
      stationary:
        interval: 0
        threshold: 70
    motion:
      mask:
        - 768,450,768,325,724,317,653,288,614,294,606,260,596,224,518,205,414,233,371,299,332,407,444,450
        - 496,0,768,0,768,159,657,126,567,100,504,125,434,129,386,142,332,98,175,85,0,83,0,0,335,0
        - 0,215,0,296,69,305,127,265,141,225,110,167,64,136   
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - motorcycle
      filters:
        #
        person:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.6
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        # 
        bicycle:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        #  
        motorcycle:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7          
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 3
        post_capture: 5
        objects:
        - person
        - dog
        - cat
        - bicycle
        - motorcycle
        retain:
          default: 28
          mode: active_objects
 


  porch_cam: # no4 - PORCH - Cam name - Brand: Annke - Quality:3k
    snapshots:
      enabled: true
      bounding_box: true
      quality: 99
    #  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:annke2023@10.0.0.3:554/Streaming/Channels/102 # SQ Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/porch_cam%20HQ?mp4  # HQ Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640  
      height: 360
      fps: 4
      stationary:
        interval: 0
        threshold: 70
    motion:
      mask:
        - 189,0,183,32,0,33,0,0,0,0,0,0
        - 640,360,619,228,583,178,473,223,423,360
        - 297,47,480,45,504,0,302,0
        - 124,246,194,242,174,207,147,193,110,228
    zones:
      zone_0:
        coordinates: 185,30,197,0,640,0,640,360,0,360,0,32
        objects: # (everywhere you want a person, cat, dog)
        - person
        - cat
        - dog  
      zone_1:
        coordinates: 268,154,256,0,575,0,544,150
        objects: # (everywhere you want a car)
        - car
        - person
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        #
        car:
          mask:
            - 0,360,640,360,640,153,264,163,244,0,0,0,0,198
        # min_area: 5000
        #  max_area: 100000
        #  # Optional: minimum width/height of the bounding box for the detected object (default: 0)
        #  min_ratio: 0.6
        #  # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
        #  max_ratio: 2.0
        #  # Optional: minimum score for the object to initiate tracking (default: shown below)
        #  min_score: 0.5
        #  # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
        #  threshold: 0.7
        #
        #person:
        #
        #dog:
        #  min_area: 1000
        #  max_area: 100000
        #  # Optional: minimum width/height of the bounding box for the detected object (default: 0)
        #  min_ratio: 0.5
        #  # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
        #  max_ratio: 2.0
        #  # Optional: minimum score for the object to initiate tracking (default: shown below)
        #  min_score: 0.5
        #  # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
        #  threshold: 0.7
        #
        #cat:
        #  min_area: 1000
        #  max_area: 100000
        #  # Optional: minimum width/height of the bounding box for the detected object (default: 0)
        #  min_ratio: 0.5
        #  # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
        #  max_ratio: 2.0
        #  # Optional: minimum score for the object to initiate tracking (default: shown below)
        #  min_score: 0.5
        #  # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
        #  threshold: 0.7
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
        - person
        - car
        - dog
        - cat
        retain:
          default: 28
          mode: active_objects 


  road_cam: # no4 - road - Cam name - Brand: Annke - Quality:3k
    snapshots:
      enabled: true
      bounding_box: true
      quality: 99
    #  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:annke2023@10.0.0.2:554/Streaming/Channels/102 # SQ Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/road_cam%20HQ?mp4  # HQ Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640  
      height: 360
      fps: 4
      stationary:
        interval: 0
        threshold: 70
    #motion:
      # mask:
       # - 189,0,189,23,0,23,0,0,0,0,0,0
    #zones:
      #zone_0:
        # coordinates: 192,21,197,0,640,0,640,236,514,210,410,480,0,480,0,21 
        # objects: # (everywhere you want a person, cat, dog)
        #- person
        #- cat
        #- dog  
      #zone_1:
        #coordinates: 325,176,578,183,584,0,323,0   
        #objects: # (everywhere you want a car)
        #- car
    objects:
      track:
        - person
        #- car
        - dog
        - cat
      filters:
        #
        #car:
        #person:
        #
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
        - person
        - dog
        - cat
        retain:
          default: 28
          mode: active_objects        


  barn: # no3 - barn - Cam name - Brand: Annke - Quality: 3k
    snapshots:
      enabled: true
      bounding_box: true
      quality: 99
    #  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac 
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:annke2023@10.0.0.4:554/Streaming/Channels/102 # SD Link
          input_args: preset-rtsp-generic
          roles:
            - detect
        - path: rtsp://192.168.22.2:8554/barn%20HQ?mp4  # HD Link
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 768  
      height: 432
      fps: 4
      stationary:
        interval: 0
        threshold: 70
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        #
        person:
          min_area: 2000
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.6
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7    
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
        - person
        - dog
        - cat
        retain:
          default: 28
          mode: active_objects         

# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: True  

    # Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant log output

```shell
road_1080p in the last 120s. restarting the ffmpeg record process...
2023-09-29 14:43:55.662746442  [2023-09-29 14:43:55] watchdog.road_1080p            INFO    : Terminating the existing ffmpeg process...
2023-09-29 14:43:55.662791067  [2023-09-29 14:43:55] watchdog.road_1080p            INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-29 14:44:05.673233477  [2023-09-29 14:44:05] watchdog.road_1080p            ERROR   : No new recording segments were created for road_1080p in the last 120s. restarting the ffmpeg record process...
2023-09-29 14:44:05.673331603  [2023-09-29 14:44:05] watchdog.road_1080p            INFO    : Terminating the existing ffmpeg process...
2023-09-29 14:44:05.673393277  [2023-09-29 14:44:05] watchdog.road_1080p            INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-29 14:44:15.686341674  [2023-09-29 14:44:15] watchdog.road_1080p            ERROR   : No new recording segments were created for road_1080p in the last 120s. restarting the ffmpeg record process...
2023-09-29 14:44:15.686496606  [2023-09-29 14:44:15] watchdog.road_1080p            INFO    : Terminating the existing ffmpeg process...
2023-09-29 14:44:15.686592073  [2023-09-29 14:44:15] watchdog.road_1080p            INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-29 14:44:25.697736002  [2023-09-29 14:44:25] watchdog.road_1080p            ERROR   : No new recording segments were created for road_1080p in the last 120s. restarting the ffmpeg record process...
2023-09-29 14:44:25.697854266  [2023-09-29 14:44:25] watchdog.road_1080p            INFO    : Terminating the existing ffmpeg process...
2023-09-29 14:44:25.697925339  [2023-09-29 14:44:25] watchdog.road_1080p            INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
Bird Cam

FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 640x360
FPS: 4/1

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 3072x1728
FPS: 20/1

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

annke c500

### Any other information that may be helpful

Noticed certain clips are not being recorded and only end up with a black square and audio...
Specificy bird cam.

![snapshot-1695798531 678319-kuj32u](https://github.com/blakeblackshear/frigate/assets/103341262/1537e731-665f-4ea3-81af-f1a9c44f9061)

https://github.com/blakeblackshear/frigate/assets/103341262/c26b34d4-1d6a-439f-a2fd-dc2c9857ddc0
