### ISSUE TITLE
[Support]: Frigate Card not working with Frigate 0.13Beta

### ISSUE THREAD

**Issue by kiloptero** [blakeblackshear/frigate#8008]
### Describe the problem you are having

experience some issue with the frigate 0.13 beta? with the 0.12 works flawless but now.. this error. I can see perfect the camera, recordings and clips in the webui of frigate.. but in the frigate card there is no way!. looks like some issue with the frigate card more than the frigate itself

### Version

Current version: 0.13.0-beta2  in frigate and v4 Frigate card

### Frigate config file

```yaml
mqtt:
  host: ip
  user: user
  password: pass
  topic_prefix: frigate

objects:
# Optional: list of objects to track from labelmap.txt (default: shown below)
    track:
      - person
      - cat
      - car
      - bicycle
      
    filters:
      bicycle:
       threshold: 0.5
    #  person:
    #    threshold: 0.7
    #  cat:
    #    threshold: 0.7


      
      

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    EntradaCasasub:
      - rtsp://admin:xxx@10.1.2.110:554/h264Preview_01_sub
      - "ffmpeg:EntradaCasasub#audio=opus"
    EntradaCasa:
      - rtsp://admin:xxxx@10.1.2.110:554/h264Preview_01_main
      - "ffmpeg:EntradaCasa#audio=opus"

  webrtc:
    candidates:
      - 10.1.2.100:8555
      - stun:8555


cameras:
    EntradaCasa:
      live:
        stream_name: EntradaCasasub
      ffmpeg:
        output_args:
          record: preset-record-generic-audio-copy
        inputs:
          
          - path: rtsp://127.0.0.1:8554/EntradaCasa?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record 
              - detect 
              - snapshots
              - clips
      zones: 
        Prueba_Zona:
          coordinates: 586,720,1280,720,1280,0,652,0
          objects:
            - bicycle
            - person
            - cat
     
   
        



 

record:
  enabled: True
  retain:
    days: 10
    
snapshots:
  enabled: True
  retain:
    default: 10



detectors:
  coral:
    type: edgetpu
    device: usb

database:
    path: /config/frigate.db
    # model:
    #  path: "/custom_model.tflite"

birdseye:
  enabled: True
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  mode: motion

detect:

  fps: 5
  enabled: True
  
ui:
  live_mode: webrtc

  

And for Frigate card

type: vertical-stack
cards:
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.entradacasa
        live_provider: go2rtc
        webrtc_card:
          entity: camera.entradacasa
        go2rtc:
          modes:
            - webrtc
          stream: EntradaCasasub
        hide: false
    live:
      preload: true
      microphone:
        always_connected: true
      draggable: false
      lazy_load: false
    menu:
      style: hover
      position: left
      buttons:
        download:
          enabled: false
        microphone:
          enabled: true
          icon: mdi:microphone
          type: momentary
          priority: 78
    media_gallery:
      controls:
        thumbnails:
          size: 113
          show_details: false
          show_favorite_control: false
          show_download_control: false
    performance:
      profile: high
```

### Relevant log output

```shell
Failed to receive response from Home Assistant for request. Check troubleshooting.
{
"request": {
"type": "frigate/events/get"
" instance id"; "frigate"
"cameras": [
"EntradaCasa"
], "limit": 50,
"id": 384
}, "response": {
"code": "frigate_error"
"message": "API error whilst retrie ving events for cameras ['EntradaCasa'1 for Frigate instance frigate"
?
}
```

### FFprobe output from your camera

```shell
none.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 811a
