### ISSUE TITLE
[Config Support]: Avoid detection of stationary vehicles in a specific zone/area

### ISSUE THREAD

**Issue by honeyfairy** [blakeblackshear/frigate#8019]
### Describe the problem you are having

I've integrated a frigate addon into my HAOS system, configuring it to send Telegram notifications. The frigate camera is monitoring a parking area where vehicles are regularly parked. Unfortunately, I'm experiencing a persistent issue where I continuously receive notifications for stationary parked vehicles.

I've followed the recommended solution provided in issue #4254, but the problem persists. I'm still receiving notifications for parked vehicles. 

Any guidance on resolving this matter?

### Version

0.12.1-367D724

### Frigate config file

```yaml
cam_fullview:
    ffmpeg:

      inputs:
        - path: rtsp://radacted1/Streaming/channels/101
          roles:
            - detect
            - rtmp
            - record
            - clips

    detect:
        
      width: 1920
      height: 1080
      fps: 5

    zones:
      entrance:
        coordinates: 1257,143,1328,1080,1920,1080,1920,208
        objects:
          - car
          - cat
          - person
      yard:
        coordinates: 1260,1080,215,1080,45,872,69,592,356,425,640,225,1245,155
        objects:
          - cat
          - person
  
    record:
      enabled: true
    
      retain:
        days: 7
        mode: all
      
      events:
         required_zones:
           - entrance
           - yard


         retain:
           default: 14
           mode: active_objects

    objects:
      track:
        - person
        - car
        - cat


 

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 7
      mode: motion


snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
```

### Relevant log output

```
{
    "before": {
        "id": "1696206317.54546-oa1bt2",
        "camera": "cam_fullview",
        "frame_time": 1696208873.122296,
        "snapshot_time": 1696206399.707933,
        "label": "car",
        "sub_label": null,
        "top_score": 0.78125,
        "false_positive": false,
        "start_time": 1696206317.54546,
        "end_time": null,
        "score": 0.78125,
        "box": [
            918,
            168,
            1248,
            453
        ],
        "area": 94050,
        "ratio": 1.1578947368421053,
        "region": [
            911,
            0,
            1727,
            816
        ],
        "stationary": true,
        "motionless_count": 12227,
        "position_changes": 1,
        "current_zones": [],
        "entered_zones": [],
        "has_clip": false,
        "has_snapshot": true
    },
    "after": {
        "id": "1696206317.54546-oa1bt2",
        "camera": "cam_fullview",
        "frame_time": 1696208933.437403,
        "snapshot_time": 1696206399.707933,
        "label": "car",
        "sub_label": null,
        "top_score": 0.78125,
        "false_positive": false,
        "start_time": 1696206317.54546,
        "end_time": null,
        "score": 0.78125,
        "box": [
            918,
            168,
            1248,
            453
        ],
        "area": 94050,
        "ratio": 1.1578947368421053,
        "region": [
            911,
            0,
            1727,
            816
        ],
        "stationary": true,
        "motionless_count": 12528,
        "position_changes": 1,
        "current_zones": [],
        "entered_zones": [],
        "has_clip": false,
        "has_snapshot": true
    },
    "type": "update"
}



### Frigate stats

_No response_

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

_No response_
