### ISSUE TITLE
RTSP Input Camera Resolution Resizing

### ISSUE THREAD

**Issue by mitchross** [blakeblackshear/frigate#802]
Hi -

It appears the input from a RTSP camera source requires the native resolution from the camera. So lets say I have a 4k IP camera, I need to set the resolution in the camera yaml file to the 4k resolution for the stream to work. However, I'm concerned about image object detection at 4k. My understanding is smaller the resolution, the better for object detection. Do you have plans to resize the input rtsp stream, such that 4k stream maybe resized to 640x480 and then feed into the tflite? Perhaps it already does this.

**Comment by jaburges** [comment]
I'm not an expert, so offering what i've seen. I'm also using some 4k and 1080 cameras, but you can resize for detection be specifying the height and width, and frigate will resize. The recommendation is (and I imagine on a 4k camera it should offer this functionality) is to use the primary stream as 4k, and the secondary or substream as 640x480 which will mean no transcoding. Incidentally what is the camera model?

I have the following config on my 4k camera:

```yaml
driveway:
    ffmpeg:   
      inputs:
        - path: rtsp://user:pass@IP:Port/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp                                
        - path: rtsp://user:pass@IP:Port/cam/realmonitor?channel=1&subtype=1 
          roles:
            - detect
            - clips                  
    motion: 
      threshold: 65
      contour_area: 150

    width: 640
    height: 480
    fps: 5
    clips:
      enabled: True
      pre_capture: 2
      post_capture: 5
      objects:
        - person
        - dog
        - car
    snapshots:
      enabled: True
      timestamp: True
      retain:
        default: 10
        objects:
          person: 30
          car: 15
          dog: 5    
    motion:
      mask:
        - 640,0,640,290,488,196,397,163,310,157,278,129,200,122,0,140,0,0
    zones:
      easement:
        coordinates: 31,169,274,189,512,291,618,380,640,280,507,208,328,159,263,134,40,139
      our_driveway:
        coordinates: 99,480,530,480,584,347,426,254,251,195,42,228
```
