### ISSUE TITLE
[Config Support]: Port 8555 is used

### ISSUE THREAD

**Issue by puthenjf** [blakeblackshear/frigate#8022]
### Describe the problem you are having

Frigate unable to start.
Port '8555' is already in use by something else on the host and frigate not starting

### Version

Port '8555' is already in use by something else on the host and frigate not starting

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.19
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-joy
  password: mqtt-joy
  stats_interval: 60
  
detectors:
  coral:
    type: edgetpu
    device: usb  
    
#  cpu:
#    type: cpu
#    num_threads: 2
    

cameras:

  porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:puthenjf@192.168.2.208:554/h264Preview_01_main      
          
          roles:
            - detect
            - record
            

#      output_args:
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
#        rtmp: -c:v copy -c:a copy -f flv

    rtmp:
      enabled: false
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 3
          mode: active_objects      
      
      
    detect:
      enabled: true
      width: 800
      height: 600
      fps: 10

    objects:
      track:
        - person
#      filters:
#        person:
#          threshold: 0.7
```

### Relevant log output

```shell
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 2:58:45 AM (1 occurrences)
Last logged: 2:58:45 AM

Failed to to call /addons/ccab4aaf_frigate/start - Port '8555' is already in use by something else on the host.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
