### ISSUE TITLE
[PTZ]:  frigate cannot run more than 1 ptz autotracking 

### ISSUE THREAD

**Issue by CurseStaff** [blakeblackshear/frigate#8030]
### Describe the problem you are having

frigate are not able to launch multiples camera ptz tracking,
if we comment all onvif exempt one (no matter with one) its successfull running.

### Version

dev-9a4f970

### Frigate config file

```yaml
mqtt:
  host: 192.168.100.237
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 25
  user: apsalhome
  password: <password>
birdseye:
  enabled: true
  restream: false
  width: 3840
  height: 2160
  quality: 1
  mode: continuous
detectors:
  coral:
    type: edgetpu
    device: usb
logger:
  default: info
ffmpeg:
  hwaccel_args: preset-nvidia-h264
rtmp:
  enabled: false
detect:
  width: 1920
  height: 1080
  fps: 10
  enabled: true
  max_disappeared: 50
  stationary:
    interval: 2
    threshold: 100
live:
  height: 1080
  quality: 3
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 30
    mode: active_objects
  events:
    pre_capture: 10
    post_capture: 10
    required_zones: []
    retain:
      default: 30
      mode: active_objects
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  required_zones: []
  retain:
    default: 30
objects:
  track:
    - person
    - dog
    - cat
    - truck
    - car
go2rtc:
  streams:
    cam_0:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/001'
    cam_1:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/101'
    cam_2:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/201'
    cam_3:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/301'
    cam_4:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/401'
    cam_5:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/501'
    cam_6:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/601'
    cam_7:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/701'
    cam_8:
      - 'rtsp://admin:<password>@192.168.100.140:554/Streaming/Channels/801'
    cam_17:
      - 'rtsp://Crestron:OikoParis2019@192.168.100.157:554/Streaming/Channels/1'
    interphone:
      - 'rtsp://192.168.50.3/h264_stream'
cameras:
  maison_tgbt:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_1'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.100.141
      # Optional: ONVIF port for device (default: shown below).
      port: 80
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: <password>
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: True
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: False
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: absolute
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.2
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
          - dog
          - cat
          - bike
          - car
          - truck
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - zone_0
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1448,849,1447,256,489,258,495,852'

  piscine_videsanitaire:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_2'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1811,1015,1795,101,150,89,155,1014'
        
  test:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_3'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.100.141
      # Optional: ONVIF port for device (default: shown below).
      port: 80
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: <password>
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: True
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: False
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: absolute
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.2
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
          - dog
          - cat
          - bike
          - car
          - truck
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - zone_0
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1448,849,1447,256,489,258,495,852'
        
  terrasse:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_4'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.100.144
      # Optional: ONVIF port for device (default: shown below).
      port: 80
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: <password>
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: True
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: False
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: absolute
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.1
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
          - dog
          - cat
          - bike
          - car
          - truck
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - zone_0
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10

    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1448,849,1447,256,489,258,495,852'
        
  garrage_porte:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_5'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.100.145
      # Optional: ONVIF port for device (default: shown below).
      port: 80
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: <password>
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: True
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: False
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: absolute
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.2
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
          - dog
          - cat
          - bike
          - car
          - truck
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - zone_0
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1448,849,1447,256,489,258,495,852'

  garrage_maison:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_6'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1811,1015,1795,101,150,89,155,1014'
  jardin_avant:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_7'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    onvif:
      host: 192.168.100.147
      port: 80
      user: admin
      password: <password>
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1448,849,1447,256,489,258,495,852'

  portail_interieur:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_8'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.100.148
      # Optional: ONVIF port for device (default: shown below).
      port: 80
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: <password>
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: True
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: False
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: absolute
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.1
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
          - dog
          - cat
          - bike
          - car
          - truck
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - zone_0
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1448,849,1447,256,489,258,495,852'

  portail_exterieur:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://127.0.0.1:8554/cam_17'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '923,0,923,114,37,109,34,0'
        - '1367,982,1694,981,1691,893,1361,895'
    zones:
      zone_0:
        coordinates: '1811,1015,1795,101,150,89,155,1014'
  interphone:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: 'rtsp://192.168.100.240:8554/interphone'
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
    zones:
      zone_0:
        coordinates: '1811,1015,1795,101,150,89,155,1014'
```

### Relevant log output

```shell
root@user:~/fregate# docker compose up
[+] Running 1/0
 ✔ Container frigate  Created                                                                                                                                        0.0s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-10-02 17:49:33.181182463  [INFO] Preparing Frigate...
frigate  | 2023-10-02 17:49:33.181613465  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-10-02 17:49:33.183943126  [INFO] Preparing go2rtc config...
frigate  | 2023-10-02 17:49:33.189184078  [INFO] Starting Frigate...
frigate  | 2023-10-02 17:49:33.444107332  [INFO] Starting go2rtc...
frigate  | 2023-10-02 17:49:33.498506338  17:49:33.498 INF go2rtc version 1.7.1 linux/amd64
frigate  | 2023-10-02 17:49:33.498751312  17:49:33.498 INF [api] listen addr=0.0.0.0:1984
frigate  | 2023-10-02 17:49:33.499047412  17:49:33.499 INF [rtsp] listen addr=0.0.0.0:8554
frigate  | 2023-10-02 17:49:33.499229327  17:49:33.499 INF [webrtc] listen addr=0.0.0.0:8555/tcp
frigate  | 2023-10-02 17:49:34.110085911  [2023-10-02 17:49:34] frigate.app                    INFO    : Starting Frigate (0.13.0-9a4f970)
frigate  | 2023-10-02 17:49:34.184236991  [2023-10-02 17:49:34] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2023-10-02 17:49:34.187102826  [2023-10-02 17:49:34] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2023-10-02 17:49:35.919434805  [2023-10-02 17:49:35] frigate.app                    INFO    : Recording process started: 582
frigate  | 2023-10-02 17:49:35.921210593  [2023-10-02 17:49:35] frigate.app                    INFO    : go2rtc process pid: 89
frigate  | 2023-10-02 17:49:35.940779931  [2023-10-02 17:49:35] detector.coral                 INFO    : Starting detection process: 592
frigate  | 2023-10-02 17:49:35.942649662  [2023-10-02 17:49:35] frigate.app                    INFO    : Output process started: 594
frigate  | 2023-10-02 17:49:35.945853794  [2023-10-02 17:49:35] frigate.comms.dispatcher       INFO    : Turning off snapshots for terrasse
frigate  | 2023-10-02 17:49:35.949710388  [2023-10-02 17:49:35] frigate.comms.dispatcher       INFO    : Turning off snapshots for maison_tgbt
frigate  | 2023-10-02 17:49:38.196903262  Traceback (most recent call last):
frigate  | 2023-10-02 17:49:38.196905891    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
frigate  | 2023-10-02 17:49:38.197072660      return _run_code(code, main_globals, None,
frigate  | 2023-10-02 17:49:38.197101869    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
frigate  | 2023-10-02 17:49:38.197186952      exec(code, run_globals)
frigate  | 2023-10-02 17:49:38.197189395    File "/opt/frigate/frigate/__main__.py", line 17, in <module>
frigate  | 2023-10-02 17:49:38.197221984      frigate_app.start()
frigate  | 2023-10-02 17:49:38.197223613    File "/opt/frigate/frigate/app.py", line 610, in start
frigate  | 2023-10-02 17:49:38.197354647      self.start_ptz_autotracker()
frigate  | 2023-10-02 17:49:38.197356464    File "/opt/frigate/frigate/app.py", line 417, in start_ptz_autotracker
frigate  | 2023-10-02 17:49:38.197419453      self.ptz_autotracker_thread = PtzAutoTrackerThread(
frigate  | 2023-10-02 17:49:38.197421079    File "/opt/frigate/frigate/ptz/autotrack.py", line 136, in __init__
frigate  | 2023-10-02 17:49:38.197469131      self.ptz_autotracker = PtzAutoTracker(config, onvif, ptz_metrics)
frigate  | 2023-10-02 17:49:38.197470798    File "/opt/frigate/frigate/ptz/autotrack.py", line 189, in __init__
frigate  | 2023-10-02 17:49:38.197510484      self._autotracker_setup(cam, camera_name)
frigate  | 2023-10-02 17:49:38.197512464    File "/opt/frigate/frigate/ptz/autotrack.py", line 240, in _autotracker_setup
frigate  | 2023-10-02 17:49:38.197563528      if not self.move_threads or not self.move_threads[camera_name]:
frigate  | 2023-10-02 17:49:38.197571213  KeyError: 'terrasse'
frigate  | 2023-10-02 17:49:38.604178301  [2023-10-02 17:49:35] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate  | 2023-10-02 17:49:38.607703266  [2023-10-02 17:49:38] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
<cannot access UI >
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

HIKVISION HWP-N4215IH-DE (8pc) + 9pc HIKVISION  4mp bullet   (latest firmware for all V5.6.18 build 210428)
