### ISSUE TITLE
[Detector Support]: Detector "IN PROGRESS", concatenating events together in single recording with massive time gaps.

### ISSUE THREAD

**Issue by kylepyke** [blakeblackshear/frigate#8036]
### Describe the problem you are having

Some of my frigate recordings contain several disjunct events (often of different objects) with jumps in time missing. It appears as though the detector is stuck "IN PROGRESS" when this happens.

Example:
https://github.com/blakeblackshear/frigate/assets/107963487/7201b460-552e-4c3a-be11-58061e4b6669

Several cars pass, then I take out the garbage, but all events are concatenated into a single frigate "Car" recording. Notice the jumps in the timestamp– particulary from :18s-21s, where the recording truncates one car event to begin a new car event ~15mins later.

Something is triggering a start/stop record, but for some reason frigate sees all of these noncontiguous events as a single event clip, when each should be its own event.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.171
  user: xxx
  password: xxx

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  #width: 1280
  # Optional: Height of the output resolution (default: shown below)
  #height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - cat
      - car
      - motorcycle
      - bicycle
      - dog
      - bus
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 28
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 14
        cat: 5
        car: 5
        motorcycle: 5
        bicycle: 5
        dog: 5
        bus: 5

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: True
  # Optional: height to resize the snapshot to (default: original size)
  height: 400
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 365

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "bl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  #effect: "None"

go2rtc:
  streams:
    hearth:
      - rtsp://xxx:xxx@192.168.1.238:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:hearth#audio=opus"
    hearth_detect:
      - rtsp://xxx:xxx@192.168.1.238:554/cam/realmonitor?channel=1&subtype=1
    living:
      - rtsp://xxx:xxx@192.168.1.239:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:living#audio=opus"
    living_detect:
      - rtsp://xxx:xxx@192.168.1.239:554/cam/realmonitor?channel=1&subtype=1
    basement:
      - rtsp://xxx:xxx@192.168.1.240:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:basement#audio=opus"
    basement_detect:
      - rtsp://xxx:xxx@192.168.1.240:554/cam/realmonitor?channel=1&subtype=1
    front_door:
      - rtsp://xxx:xxx@192.168.1.110:554/h264Preview_01_main
      - "ffmpeg:front_door#audio=opus"
    front_door_detect:
      - rtsp://xxx:xxx@192.168.1.110:554/h264Preview_01_sub
    side_yard_detect:
      - rtsp://xxx:xxx@192.168.1.13:554/h264Preview_01_sub
      - "ffmpeg:side_yard_detect#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.167:8555
      - stun:8555

cameras:
  Hearth_frgt:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/hearth
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hearth_detect
          roles:
            - detect
    detect:
      width: 640
      height: 480
    objects:
      track:
            - person
            - cat
    live:
      stream_name: hearth

  Living_frgt:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/living
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_detect
          roles:
            - detect
    detect:
      width: 640
      height: 480
    objects:
      track:
            - person
            - cat
    live:
      stream_name: living

  Basement_frgt:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/basement
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/basement_detect
          roles:
            - detect
    detect:
      width: 640
      height: 480
    objects:
      track:
            - person
            - cat
    live:
      stream_name: basement

  Front_door_frgt:
    record:
      events:
        required_zones:
          - stoop
          - street
    snapshots:
      required_zones:
        - stoop
        - street
    zones:
        stoop:
          coordinates: 640,480,640,367,577,326,484,332,420,330,304,318,223,314,208,297,205,75,0,38,0,315,0,411,0,480,416,480,640,480
          objects:
            - person
            - cat
            - dog
            - bird
        street:
          coordinates: 224,307,215,121,640,114,640,220,640,286,640,333
          objects:
            - car
            - motorcycle
            - person
            - bicycle
            - bus
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_detect
          roles:
            - detect
    detect:
      width: 640
      height: 480
    objects:
      track:
            - person
            - car
            - bird
            - motorcycle
            - bicycle
            - cat
            - dog
            - bus
    live:
      stream_name: front_door
      
  Side_yard_frgt:
    zones:
        walkway:
          coordinates: 219,480,537,480,598,180,499,150
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.13:554/h264Preview_01_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_yard_detect
          roles:
            - detect
    detect:
      width: 640
      height: 480
    objects:
      track:
            - person
            - car
            - bird
            - motorcycle
            - bicycle
            - cat
            - dog
            - bus
    live:
      stream_name: side_yard_detect

live:
  quality: 8
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified >
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your >
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/frigate/config.yaml:/config/config.yml
      - /home/frigate/frigate/go2rtc:/config/go2rtc
      - /mnt/FrigateMedia:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" #go2rtc
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxx"

^G Help      ^O Write Out ^W Where Is  ^K Cut       ^T Execute   ^C Location
^X Exit      ^R Read File ^\ Replace   ^U Paste     ^J Justify   ^/ Go To Line
```

### Relevant log output

```shell
None Recorded
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
