### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by nmcrae85** [blakeblackshear/frigate#8043]
### Describe the problem you are having

Trying to understand the logic of the following min_area. What is the recommended setting or way of calculating this? Im sure its going to dpend on application of use, but is there a relevance for objects such as a car vs a person? Are there defaults? Do you need to explicitly define this like below?

   objects:
      track:
        - person
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500

### Version

beta2

### Frigate config file

```yaml
objects:
      track:
        - person
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
```

### Relevant log output

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
