### ISSUE TITLE
[Config Support]: Possible to adjust how much movement permitted for 'stationary' objects

### ISSUE THREAD

**Issue by mjc-506** [blakeblackshear/frigate#8049]
### Describe the problem you are having

Frigate's working great, but having got it talking to HASS and looking through the recorded events, it seems I'm having the common "repeated notifications for stationary objects" issue.

Looking at the mqtt messages, I think what is happening is that the tracked object "moves" enough between frames so the 'stationary' flag becomes false (and the true again in a few frames).

I couldn't find a config variable to adjust how sensitive object tracking is to movement? I understand that "An object is determined to be stationary if the bounding box in the current frame overlaps almost entirely with the previous 10 frames" but I can't find what 'almost entirely' actually is :-)

I suspect I'm not helping matters by running detection on the cpu (fewer fps, so bigger changes between frames. Coral TPU soon to be plugged in) and using the high resolution stream from the camera (1080p), but a config variable would be useful, either in pixels or percent.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: <host>
  user: <user>    
  password: <password>
detectors:
  cpu_detector:
    type: cpu
go2rtc:
  streams:
    front:
      - rtsp://user:pass@192.168.1.6:554/0/av0
    rear:
      - rtsp://user:pass@192.168.1.7:554/11
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
detect:
  stationary:
    interval: 10
    threshold: 100
objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
record:
  enabled: True
  retain:
    days: 31
    mode: all
  events:
    retain:
      default: 99999
      mode: active_objects
cameras:
  front:
    motion:
      mask:
        - 0,432,825,157,890,85,1272,93,1332,97,1455,180,1920,304,1920,0,0,0
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 10
  rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,1080,157,1080,159,300,494,296,679,285,1032,364,1254,242,1920,244,1920,0,0,0
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 10
```

### Relevant log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)
