### ISSUE TITLE
[Config Support]: Frigate.yml not found with new beta?

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#8055]
### Describe the problem you are having

So after changing the mapping docker-compose.yaml to map the entire drive, it somehow can't find the frigate.yml file anymore (i have it in config).

I did exactly as per the instructions:

I changed from:
```
version: '3.9'
services:
  frigate:
    container_name: frigate
    network_mode: host
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0
    shm_size: '800mb'
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      **- ./config/frigate.yml:/config/config.yml:rw**
      - ./media/:/media/frigate
#      - /mnt/footage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555"
      - "1984:1984"
    environment:
       PLUS_API_KEY: 1234
#      FRIGATE_RTSP_PASSWORD: password
```

to:
```
./config:/config:rw (and yes i removed the :rw and used an absolute path as well)
```
Then i get upon startup:
```
frigate  | 2023-10-03 20:53:11.704916665  [INFO] Preparing Frigate...
frigate  | 2023-10-03 20:53:11.704944778  [ERROR] Frigate config file not found
frigate  | 2023-10-03 20:53:11.705918694  [INFO] Preparing go2rtc config...
frigate  | 2023-10-03 20:53:11.706231837  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-10-03 20:53:11.710533137  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
```

If i replace the old docker-compose.yaml everything works fine again (with using the old 12-beta2 image.
Bit baffled.

### Version

v13-beta2

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
See above
```

### Frigate stats

```json
Na
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Nope
