### ISSUE TITLE
[Support]: Select cameras not working, but not always the same ones

### ISSUE THREAD

**Issue by Iceman248** [blakeblackshear/frigate#8057]
### Describe the problem you are having

There are 25 cameras in the system currently. Once I added in the last several ones, about 2 out of the last 6 rotate from not working at all, to only partially, maybe just the detect stream or the recording, even though for some it is different RTSP streams and some just use a cut down version of the main stream.

It It seems to usually be 2 of 6 particular ones at the end of the config, but that spreads across 2 different camera models. It gave me the impression maybe something is overloaded. I did have to increase the shm size to 350MB, detect streams are all 720p. I also added analyzeduration and probesize config to 1000M each as log suggested, which is no longer complains about.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False
  host: 192.168.1.100
  user: admin
  password: password
go2rtc:
  streams:
    main_shop_front_far_north:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c1/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_front_mid_north:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c2/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_front_mid_south:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c4/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_back_mid:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c5/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_back_north:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c6/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_back_south:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c7/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_northside:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c8/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_inside_far_back:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c9/s0/live#video=copy#audio=aac#audio=opus"
    main_shop_southside:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c10/s0/live#video=copy#audio=aac#audio=opus"
    unknown1:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c11/s0/live#video=copy#audio=aac#audio=opus"
    unknown2:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c12/s0/live#video=copy#audio=aac#audio=opus"
    unknown3:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c13/s0/live#video=copy#audio=aac#audio=opus"
    unknown4:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c14/s0/live#video=copy#audio=aac#audio=opus"
    unknown5:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c15/s0/live#video=copy#audio=aac#audio=opus"
    unknown6:
      - "ffmpeg:rtsp://user2:password@192.168.1.200:554/unicast/c16/s0/live#video=copy#audio=aac#audio=opus"
    trans_shop_lpr:
      - rtsp://admin:password@192.168.1.201:554/live
      - "ffmpeg:trans_shop_lpr#audio=opus"
    north_gate_lpr:
      - rtsp://admin:password@192.168.1.202:554/live
      - "ffmpeg:north_gate_lpr#audio=opus"
    south_gate_lpr:
      - rtsp://admin:password@192.168.1.203:554/live
      - "ffmpeg:south_gate_lpr#audio=opus"
    office_front_door:
      - rtsp://admin:password@192.168.1.204:554/live
      - "ffmpeg:office_front_door#audio=opus"
    trans_shop_front:
      - rtsp://admin:password@192.168.1.205:554/live
      - "ffmpeg:trans_shop_front#audio=opus"
    trans_shop_side:
      - rtsp://admin:password@192.168.1.206:554/live
      - "ffmpeg:trans_shop_side#audio=opus"
    office_back:
      - rtsp://admin:password@192.168.1.207:554/live
      - "ffmpeg:office_back#audio=opus"
    office_front:
      - rtsp://admin:password@192.168.1.208:554/live
      - "ffmpeg:office_front#audio=opus"
    trans_shop_inside_north:
      - rtsp://admin:password@192.168.1.209:554/live
      - "ffmpeg:trans_shop_inside_north#audio=opus"
    trans_shop_inside_south:
      - rtsp://admin:password@192.168.1.211:554/live
      - "ffmpeg:trans_shop_inside_south#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.100:8555
      - stun:8555
cameras:
  main_shop_front_far_north:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_front_far_north
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user2:password@192.168.1.200:554/unicast/c1/s1/live
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    motion:
      mask:
        - 0,0,1280,0,1280,228,915,130,803,104,795,150,592,125,560,69,325,50,308,106,209,128,0,167
    objects:
      filters:
        car:
          mask:
            - 0,0,1280,0,1280,228,915,130,803,104,795,150,592,125,560,69,325,50,308,106,209,128,0,167
    mqtt:
      quality: 100
  main_shop_front_mid_north:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_front_mid_north
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    motion:
      mask:
        - 330,85,464,62,678,64,753,73,821,90,830,43,1280,123,1280,0,352,0,185,54,203,87
    objects:
      filters:
        car:
          mask:
            - 330,85,464,62,678,64,753,73,821,90,830,43,1280,123,1280,0,352,0,185,54,203,87
            - 159,724,1152,724,1151,626,160,625
            - 513,205,492,394,279,399,270,279
        motorcycle:
          mask:
            - 553,333,544,508,232,494,240,333
    mqtt:
      quality: 100
  main_shop_front_mid_south:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_front_mid_south
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    motion:
      mask:
        - 660,0,652,64,520,69,514,0
    objects:
      filters:
        car:
          mask:
            - 660,0,652,64,520,69,514,0
            - 267,724,788,724,794,504,242,530
            - 1217,203,1203,239,1120,222,1117,188
            - 220,139,236,173,0,238,0,191
    mqtt:
      quality: 100
  main_shop_back_mid:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_back_mid
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  main_shop_back_north:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_back_north
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  main_shop_back_south:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_back_south
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  main_shop_northside:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_northside
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  main_shop_inside_far_back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_inside_far_back
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  main_shop_southside:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main_shop_southside
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  unknown1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/unknown1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  unknown2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/unknown2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  unknown3:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/unknown3
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 724
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  unknown4:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/unknown4
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user2:password@192.168.1.200:554/unicast/c14/s1/live
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  unknown5:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/unknown5
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user2:password@192.168.1.200:554/unicast/c15/s1/live
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  unknown6:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/unknown6
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user2:password@192.168.1.200:554/unicast/c16/s1/live
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        max_frames:
          objects:
            car: 150
    mqtt:
      quality: 100
  trans_shop_lpr:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/trans_shop_lpr
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.201:554/cam/realmonitor?channel=1&subtype=3
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    mqtt:
      quality: 100
  north_gate_lpr:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/north_gate_lpr
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.202:554/cam/realmonitor?channel=1&subtype=3
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0,0,1280,0,1280,437,1004,405,882,325,703,323,447,319,318,312,250,397,0,460
    objects:
      filters:
        car:
          mask:
            - 0,0,1280,0,1280,437,1006,393,886,315,700,312,443,307,326,303,250,397,0,460
        motorcycle:
          mask:
            - 0,0,1280,0,1280,437,1006,393,886,315,700,312,443,307,326,303,250,397,0,460
        bicycle:
          mask:
            - 0,0,1280,0,1280,437,1006,393,886,315,700,312,443,307,326,303,250,397,0,460
    mqtt:
      quality: 100
  south_gate_lpr:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/south_gate_lpr
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.203:554/cam/realmonitor?channel=1&subtype=3
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0,0,1280,0,1280,341,0,381
    objects:
      filters:
        car:
          mask:
            - 0,0,1280,0,1280,341,0,381
        motorcycle:
          mask:
            - 0,0,1280,0,1280,341,0,381
        bicycle:
          mask:
            - 0,0,1280,0,1280,341,0,381
    mqtt:
      quality: 100
  office_front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/office_front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.204:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    mqtt:
      quality: 100 
  trans_shop_front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/trans_shop_front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.205:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0,0,1280,0,1280,253,496,133,0,157
    objects:
      filters:
        car:
          mask:
            - 0,0,1280,0,1280,253,496,133,0,157
        motorcycle:
          mask:
            - 0,0,1280,0,1280,253,496,133,0,157
        bicycle:
          mask:
            - 0,0,1280,0,1280,253,496,133,0,157
    mqtt:
      quality: 100 
  trans_shop_side:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/trans_shop_side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.206:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    mqtt:
      quality: 100 
  office_back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/office_back
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.207:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    mqtt:
      quality: 100 
  office_front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/office_front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.208:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    mqtt:
      quality: 100 
  trans_shop_inside_north:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/trans_shop_inside_north
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.209:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    mqtt:
      quality: 100 
  trans_shop_inside_south:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/trans_shop_inside_south
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.211:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    mqtt:
      quality: 100 
snapshots:
  enabled: True
  crop: False
  retain:
    default: 5
detect:
  stationary:
    interval: 0
objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - dog
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 10
    retain:
      default: 5
      mode: motion
birdseye:
  enabled: true
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
     record: preset-record-generic
  input_args:
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant log output

```shell
2023-10-03 18:32:37.653853886  [2023-10-03 18:32:37] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-10-03 18:32:37.653892699  [2023-10-03 18:32:37] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-10-03 18:32:37.653914239  [2023-10-03 18:32:37] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2023-10-03 18:32:40.061878173  [2023-10-03 18:32:40] frigate.video                  ERROR   : main_shop_front_mid_south: Unable to read frames from ffmpeg process.
2023-10-03 18:32:40.062059755  [2023-10-03 18:32:40] frigate.video                  ERROR   : main_shop_front_mid_south: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:32:42.587846449  [2023-10-03 18:32:42] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:32:42.587984834  [2023-10-03 18:32:42] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:32:57.407753058  [2023-10-03 18:32:57] watchdog.main_shop_front_mid_south ERROR   : Ffmpeg process crashed unexpectedly for main_shop_front_mid_south.
2023-10-03 18:32:57.407797728  [2023-10-03 18:32:57] watchdog.main_shop_front_mid_south ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:32:57.407834004  [2023-10-03 18:32:57] ffmpeg.main_shop_front_mid_south.detect ERROR   : Codec AVOption hwaccel_flags () specified for input file #0 (rtsp://127.0.0.1:8554/main_shop_front_mid_south) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some decoder which was not actually used for any stream.
2023-10-03 18:32:57.407856303  [2023-10-03 18:32:57] ffmpeg.main_shop_front_mid_south.detect ERROR   : Output file #1 does not contain any stream
2023-10-03 18:32:57.487854617  [2023-10-03 18:32:57] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:32:57.487919888  [2023-10-03 18:32:57] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:32:57.487971836  [2023-10-03 18:32:57] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:33:02.607951483  [2023-10-03 18:33:02] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:33:02.607997597  [2023-10-03 18:33:02] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:33:07.498081989  [2023-10-03 18:33:07] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:33:07.498301337  [2023-10-03 18:33:07] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:33:07.498515218  [2023-10-03 18:33:07] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:33:12.654389315  [2023-10-03 18:33:12] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:33:12.654812487  [2023-10-03 18:33:12] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:33:17.526346832  [2023-10-03 18:33:17] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:33:17.526423170  [2023-10-03 18:33:17] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:33:17.526505362  [2023-10-03 18:33:17] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:33:22.665734217  [2023-10-03 18:33:22] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:33:22.666045296  [2023-10-03 18:33:22] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:33:27.547815402  [2023-10-03 18:33:27] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:33:27.547988271  [2023-10-03 18:33:27] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:33:27.548124334  [2023-10-03 18:33:27] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:33:32.671693513  [2023-10-03 18:33:32] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:33:32.672387901  [2023-10-03 18:33:32] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:33:37.560340646  [2023-10-03 18:33:37] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:33:37.560412457  [2023-10-03 18:33:37] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:33:37.560460117  [2023-10-03 18:33:37] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:33:42.685979933  [2023-10-03 18:33:42] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:33:42.686126478  [2023-10-03 18:33:42] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:33:47.571022064  [2023-10-03 18:33:47] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:33:47.571202680  [2023-10-03 18:33:47] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:33:47.571306103  [2023-10-03 18:33:47] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:33:52.688680747  [2023-10-03 18:33:52] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:33:52.688735206  [2023-10-03 18:33:52] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:33:57.579294523  [2023-10-03 18:33:57] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:33:57.579348539  [2023-10-03 18:33:57] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:33:57.579384218  [2023-10-03 18:33:57] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:34:02.695555513  [2023-10-03 18:34:02] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:34:02.696150608  [2023-10-03 18:34:02] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
2023-10-03 18:34:07.585440624  [2023-10-03 18:34:07] watchdog.unknown3              ERROR   : Ffmpeg process crashed unexpectedly for unknown3.
2023-10-03 18:34:07.585509083  [2023-10-03 18:34:07] watchdog.unknown3              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-03 18:34:07.585557062  [2023-10-03 18:34:07] ffmpeg.unknown3.detect         ERROR   : rtsp://127.0.0.1:8554/unknown3: Invalid data found when processing input
2023-10-03 18:34:12.702225468  [2023-10-03 18:34:12] frigate.video                  ERROR   : unknown3: Unable to read frames from ffmpeg process.
2023-10-03 18:34:12.702337245  [2023-10-03 18:34:12] frigate.video                  ERROR   : unknown3: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]

[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Uniview NVR302-16S2-P16 (NVR)/IPC3614LE-ADF28K (Cam)/IPC3614SB-ADF28KM-I0 (Cam)

### Any other information that may be helpful

ffmpeg probe is from 2 working cameras that sometimes goes out. Trying on the one currently not working didn't produce anything. They are different as those are the 2 different models that rotate between working/not working.

**Comment by NickM-27** [comment]
What is the gpu usage on the system page?

**Comment by Iceman248** [comment]
intel-vaapi: 25-32%

**Comment by NickM-27** [comment]
What about inference time?

**Comment by Iceman248** [comment]
8-10ms

**Comment by Iceman248** [comment]
As a test of my theory of the system being overloaded, I disabled the last 2 cameras in the config and no errors in the log and both the record and detect streams work. I left those 2 cameras working in go2rtc and they still do work there, which they didn't always before, so just getting them out of Frigate specifically cleared up enough resources or whatever to allow everything to work.

**Comment by NickM-27** [comment]
there have been a lot of improvements to efficiency in 0.13, I'm not seeing anything pointing to what exactly is overloaded right now though

**Comment by DaCeige** [comment]
I've had some issues with the intel transcoder handling over about 16 cameras at a time (+/- depending on other factors)... I'd be curious if you tried to overwriting your ffmpeg preset on those 2 cameras and set them to not use the hardware transcoder and see if that makes any difference.  

example from my config:

  bird1_cam:
    ffmpeg:
      hwaccel_args: ' '

**Comment by Iceman248** [comment]
> I've had some issues with the intel transcoder handling over about 16 cameras at a time (+/- depending on other factors)... I'd be curious if you tried to overwriting your ffmpeg preset on those 2 cameras and set them to not use the hardware transcoder and see if that makes any difference.
> 
> example from my config:
> 
> ```
>   bird1_cam:
>     ffmpeg:
>       hwaccel_args: ' '
> ```

Thanks. I specifically type `hwaccel_args: ' '`? I can't tell if that made a difference in whether it uses hardware transcoder, but I still get the same issues.

**Comment by Iceman248** [comment]
I upgraded to 0.13 beta 2, still same issues. hardware transcoding or not, until I stopped using a separate detect stream for the 2 cameras at the end. Only so many even had one that was 720p or above, so for most I used the same stream as record and sized down the resolution. This would seem to have even more overhead, but so far so good, will monitor.

**Comment by Iceman248** [comment]
It is now pegged at or around 100% CPU usage in the system page now though, as well as almost 50% GPU. I do notice that the detect streams for some cameras goes out briefly, but for the most part is working well.

**Comment by DaCeige** [comment]
Check nvtop command to see all the processes using the GPU and count them....

You may find a correlation like I did. 
Either remove some substreams, split the load to another box, or take the CPU hit on a couple of the streams by selectively turning off the transcoder to stay under the limit.

Hope it helps. 

'ps... make sure you are selectively turning it off per camera by overriding the option per camera in the camera section, not globally in the ffmpeg section.

**Comment by NickM-27** [comment]
Given that the issue doesn't happen when running on the main stream, makes me think it's some sort of network bandwidth issue or something, because it's more processing to do on the frigate side that way

**Comment by Iceman248** [comment]
More on this. Trying to get 30 cameras going on a i5-12600K using vaapi to utilize the onboard GPU. Even with much less bandwidth usage, although that enabled more cameras to work when I had less connected, it seems to max out at 26-28 cameras with 2-4 being out chosen randomly it seems. With this much CPU usage per camera, it seems to be maxed out too much. Would getting a Coral for example for this system be something that should take away enough CPU usage to stabilize things?

<img width="1073" alt="image" src="https://github.com/blakeblackshear/frigate/assets/16282747/50a912bb-8391-41d8-a04b-510c82eb2b3e">

**Comment by NickM-27** [comment]
You could try specifically running openvino in GPU only mode

```
detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
```
