### ISSUE TITLE
[Support]: Audio recording only saved 24 hours by default?

### ISSUE THREAD

**Issue by Calimerorulez** [blakeblackshear/frigate#8061]
### Describe the problem you are having

The looking back at the audio detections, when I click a clip that is older then 24 hours, the clip can't be found.

### Version

0.13.0-0858859

### Frigate config file

```yaml
detectors:
  coral_pci:
    type: edgetpu
    device: pci
mqtt:
  # Required: host name
  host: 192.168.5.110
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: frigate
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 7
      mode: motion
#    max_seconds: 90

#ffmpeg:
#  input_args: preset-rtsp-restream
#  output_args:
#    record: preset-record-generic-audio-aac

# ffmpeg configuration
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2

  hwaccel_args: preset-vaapi
  #hwaccel_args: preset-nvidia-h264

  input_args: preset-rtsp-restream
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti

go2rtc:
  streams:
    g3b_voortuin:
      - rtspx://192.168.1.4:7441/hJ84WEkjmUXe6H66
    flex_ne:
      - rtspx://192.168.1.4:7441/eXz1bJYvAZNRyNOg
    flex_se:
      - rtspx://192.168.1.4:7441/8jU5tkUhuBVLqUNS
    g5b_achtertuin:
      - rtspx://192.168.1.4:7441/aqSo7WiK8WuY6XMW
    g4_deurbel:
      - rtspx://192.168.1.4:7441/8AwXQAd8rnKMYexm
    g5b_overkapping:
      - rtspx://192.168.1.4:7441/aPckb6DeNUXfYPVU
    g3i_garage:
      - rtspx://192.168.1.4:7441/Fz3j4v2biFVY3rKB

cameras:
  # Name of your camera
  g3b_voortuin:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080
    audio:
      enabled: True
      listen:
        - children_playing
        - cat
        - bird
        - dog
        - dogs
        - footsteps
        - clapping
        - bark
        - scream
        - speech
        - yell
        - whispering
        - laughter
        - honk
        - fireworks
        - firecracker
        - music
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/g3b_voortuin
          roles:
            - detect
            - record
            - audio
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
        # Optional: save clips configuration
    detect:
      width: 1920
      height: 1080
      fps: 5

  flex_ne:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/flex_ne
          roles:
            - detect
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      filters:
        car:
          mask:
          - 1318,389,1382,227,1113,202,976,347
          - 749,556,991,304,198,224,0,427
          - 0,640,691,824,833,553,0,393
          - 1460,240,1624,242,1627,282,1638,420,1462,407
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
        # Optional: save clips configuration
    detect:
      width: 1920
      height: 1080
      fps: 5

  flex_se:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/flex_se
          roles:
            - detect
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
        # Optional: save clips configuration
    detect:
      width: 1920
      height: 1080
      fps: 5

  g5b_achtertuin:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 2688
    audio:
      enabled: True
      listen:
        - children_playing
        - cat
        - bird
        - dog
        - dogs
        - footsteps
        - clapping
        - bark
        - scream
        - speech
        - yell
        - whispering
        - laughter
        - honk
        - fireworks
        - firecracker
        - music
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/g5b_achtertuin
          roles:
            - detect
            - record
            - audio
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
        # Optional: save clips configuration
    detect:
      width: 2688
      height: 1512
      fps: 5

  g4_deurbel:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1600
    audio:
      enabled: True
      listen:
        - children_playing
        - cat
        - bird
        - dog
        - dogs
        - footsteps
        - clapping
        - bark
        - scream
        - speech
        - yell
        - whispering
        - laughter
        - honk
        - fireworks
        - firecracker
        - music
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/g4_deurbel
          roles:
            - detect
            - record
            - audio
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - bird
        - bicycle
        - motorcycle
        - cat
        - dog
        # Optional: save clips configuration
    detect:
      width: 1600
      height: 1200
      fps: 5

  g5b_overkapping:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 2688
    audio:
      enabled: True
      listen:
        - children_playing
        - cat
        - bird
        - dog
        - dogs
        - footsteps
        - clapping
        - bark
        - scream
        - speech
        - yell
        - whispering
        - laughter
        - honk
        - fireworks
        - firecracker
        - music
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/g5b_overkapping
          roles:
            - detect
            - record
            - audio
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog
        - bird
        # Optional: save clips configuration
    detect:
      width: 2688
      height: 1512
      fps: 5

  g3i_garage:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/g3i_garage
          roles:
            - detect
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
        # Optional: save clips configuration
    detect:
      width: 1920
      height: 1080
      fps: 5
```

### Relevant log output

```shell
2023-10-04 10:07:11.339299221  [2023-10-04 10:07:11] frigate.http                   ERROR   : No recordings found for the requested time range
2023-10-04 10:07:11.643720724  [2023-10-04 10:07:11] frigate.http                   ERROR   : Event does not have recordings: 1696236824.829629-qh4sjg
2023-10-04 10:07:14.881716159  [2023-10-04 10:07:14] frigate.http                   ERROR   : No recordings found for the requested time range
2023-10-04 10:07:15.107234881  [2023-10-04 10:07:15] frigate.http                   ERROR   : Event does not have recordings: 1696264885.435137-zu3uus
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Unifi Protect
