### ISSUE TITLE
[Config Support]: Consumption increases a lot when incorporating a frigate+ model 

### ISSUE THREAD

**Issue by robertoprubio** [blakeblackshear/frigate#8064]
### Describe the problem you are having

Consumption increases a lot when incorporating a frigate+ model

I'm on 0.13-b2. Screenshot show power compsumpion. 

Before "1" config doesn't includes a model. From "1" to "2" config includes a model and, after "2" the config also doesn't includes any model. Graph is showing computer power compsumption (I have a smartplug and only the computer is connected to it).

In all cases the only thing that was active was the recording, but not the detection

### Version

0.13-b2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 127.0.0.1
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

ui:
  live_mode: mse

rtmp:
  enabled: false

birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
      
record:
  enabled: true
  retain:
    days: 7

motion:
  improve_contrast: true

detect:
  enabled: false
  width: 1920
  height: 1080

detectors:
  coral:
    type: edgetpu
    device: usb

#model:
#  path: plus://XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

objects:
  track:
    - person
    - dog
    - cat 
  filters:
    person:
      min_area: 25000

go2rtc:
  streams:
    terraza_trasera:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.231/stream1"
    dormitorio_principal:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.235/stream1"
    recibidor:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.233/stream1"
    comedor:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.234/stream1"
    terraza_delantera:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.232/stream1"
 
cameras:
  terraza_trasera:
    enabled: true
    ui: 
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraza_trasera
          roles:
            - record
            - detect

  dormitorio_principal:
    enabled: true
    ui:                 
      order: 2          
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dormitorio_principal
          roles:
            - record
            - detect

  recibidor:
    enabled: true
    ui:                 
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/recibidor
          roles:
            - record
            - detect

  comedor:
    enabled: true
    ui:                 
      order: 4          
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/comedor
          roles:
            - record
            - detect

  terraza_delantera:
    enabled: true
    ui:                 
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraza_delantera
          roles: 
            - record
            - detect
```

### Relevant log output

```shell
No any rellevant log. Only HA messages
```

### Frigate stats

```json
{"comedor":{"camera_fps":5.0,"capture_pid":340,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":365,"pid":323,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"14":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"23":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"40":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"83":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"2.9","cpu_average":"2","mem":"0.1"},"101":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"111":{"cmdline":"python3 -u -m frigate","cpu":"4.1","cpu_average":"4","mem":"2.3"},"117":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"297":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"299":{"cmdline":"frigate.recording_manager","cpu":"3.8","cpu_average":"1","mem":"0.8"},"308":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(47)","cpu":"0.6","cpu_average":"0","mem":"0.1"},"309":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"0","mem":"0.8"},"311":{"cmdline":"frigate.output       ","cpu":"3.2","cpu_average":"3","mem":"0.8"},"318":{"cmdline":"frigate.process:terraza_trasera","cpu":"0.3","cpu_average":"0","mem":"0.8"},"319":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"320":{"cmdline":"frigate.process:dormitorio_principal","cpu":"0.6","cpu_average":"0","mem":"0.8"},"322":{"cmdline":"frigate.process:recibidor","cpu":"0.6","cpu_average":"0","mem":"0.8"},"323":{"cmdline":"frigate.process:comedor","cpu":"0.3","cpu_average":"0","mem":"0.8"},"326":{"cmdline":"frigate.process:terraza_delantera","cpu":"0.6","cpu_average":"0","mem":"0.8"},"327":{"cmdline":"frigate.capture:terraza_trasera","cpu":"4.3","cpu_average":"4","mem":"0.8"},"328":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"331":{"cmdline":"frigate.capture:dormitorio_principal","cpu":"4.9","cpu_average":"4","mem":"0.8"},"336":{"cmdline":"frigate.capture:recibidor","cpu":"4.3","cpu_average":"4","mem":"0.8"},"337":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"338":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/dormitorio_principal -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/dormitorio_principal-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.3","cpu_average":"4","mem":"0.3"},"339":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/terraza_trasera -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/terraza_trasera-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.3","cpu_average":"4","mem":"0.3"},"340":{"cmdline":"frigate.capture:comedor","cpu":"4.9","cpu_average":"4","mem":"0.8"},"343":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"344":{"cmdline":"frigate.capture:terraza_delantera","cpu":"4.3","cpu_average":"4","mem":"0.8"},"350":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://frigate:SHs5qi3Ppwrfrfx82VYbXhXscEyZvJ@192.168.31.231/stream1 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/9604b47a26631b108946037bf5398640","cpu":"0.6","cpu_average":"0","mem":"0.1"},"352":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/recibidor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/recibidor-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.3","cpu_average":"4","mem":"0.3"},"353":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/terraza_delantera -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/terraza_delantera-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.0","cpu_average":"4","mem":"0.3"},"354":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://frigate:SHs5qi3Ppwrfrfx82VYbXhXscEyZvJ@192.168.31.235/stream1 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b45ae8cfdce1f01ccf68d8597402569f","cpu":"0.9","cpu_average":"0","mem":"0.1"},"355":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"364":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://frigate:SHs5qi3Ppwrfrfx82VYbXhXscEyZvJ@192.168.31.232/stream1 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/604bba1f2201fe88b16bd156ee289ec3","cpu":"0.9","cpu_average":"0","mem":"0.1"},"365":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/comedor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/comedor-%Y%m%d%H%M%S.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.6","cpu_average":"4","mem":"0.3"},"370":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://frigate:SHs5qi3Ppwrfrfx82VYbXhXscEyZvJ@192.168.31.233/stream1 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/edbb658b229918932d1e2b32bc274599","cpu":"0.9","cpu_average":"0","mem":"0.1"},"371":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://frigate:SHs5qi3Ppwrfrfx82VYbXhXscEyZvJ@192.168.31.234/stream1 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/0191bc8310a97c6b4a623bad78b42252","cpu":"0.6","cpu_average":"0","mem":"0.1"},"3489":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":11.54,"pid":309}},"dormitorio_principal":{"camera_fps":5.0,"capture_pid":331,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":338,"pid":320,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"2.18%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":297},"recording":{"pid":299}},"recibidor":{"camera_fps":5.0,"capture_pid":336,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":352,"pid":322,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1696427262,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":174.5,"mount_type":"tmpfs","total":192.0,"used":17.5},"/media/frigate/clips":{"free":674207.1,"mount_type":"ext4","total":937795.7,"used":215879.2},"/media/frigate/recordings":{"free":674207.1,"mount_type":"ext4","total":937795.7,"used":215879.2},"/tmp/cache":{"free":951.4,"mount_type":"tmpfs","total":953.7,"used":2.2}},"temperatures":{},"uptime":837,"version":"0.13.0-0858859"},"terraza_delantera":{"camera_fps":5.0,"capture_pid":344,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":353,"pid":326,"process_fps":5.0,"skipped_fps":0.0},"terraza_trasera":{"camera_fps":5.0,"capture_pid":327,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":339,"pid":318,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

-
