### ISSUE TITLE
[Support]: Manual Events API

### ISSUE THREAD

**Issue by MStcz** [blakeblackshear/frigate#8068]
### Describe the problem you are having

When record retain mode of the camera is set to motion, **Manual Events API** records just segments with motion. E.g. duration is set to 100 seconds recorded video has just e.g. 20 seconds. There is a workaround set record retain mode of the camera to all but it records 24/7 and consuming too much space. Is it bug or by design? If it is by design would be great to add new option to **Manual Events API** as it shown below - new option **recording_mode**.

{
  "sub_label": "some_string", // add sub label to event
  "duration": 30, // predetermined length of event (default: 30 seconds) or can be to null for indeterminate length event
  "include_recording": true, // whether the event should save recordings along with the snapshot that is taken
  **"recording_mode": "all", // all or motion, all - records everything for configured duration, motion - records just motion segments** detected
  "draw": {
    // optional annotations that will be drawn on the snapshot
    "boxes": [
      {
        "box": [0.5, 0.5, 0.25, 0.25], // box consists of x, y, width, height which are on a scale between 0 - 1
        "color": [255, 0, 0], // color of the box, default is red
        "score": 100 // optional score associated with the box
      }
    ]
  }
}

### Version

 0.13.0-beta2

### Frigate config file

```yaml
mqtt:
  host: 10.10.10.10
  user: mqtt
  password: ****

live:
  height: 1080

birdseye:
  width: 1920
  height: 1080
  quality: 8
  mode: motion

cameras:
  CAM11:
    ffmpeg:
      inputs:
        - path: rtsp://usr:****@10.10.10.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 3
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - horse
        - cow
        - bear

record:
  enabled: True
  retain:
    days: 15
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: True
  bounding_box: True

detectors:
  cpu1:
    type: cpu
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

amcrest
