### ISSUE TITLE
[Config Support]: Overriding object filter values at zone level has no effect.

### ISSUE THREAD

**Issue by desolator-x** [blakeblackshear/frigate#8071]
### Describe the problem you are having

It seems as if the object filter values set at the zone level are ignored.

The default value for the object filter 'threshold' is 0.7. I did all of the object configuration at the camera/zone level, setting the threshold to 0.5 for persons detected in the street zone: 

```
cameras:
  front:
    (...)
    objects:
      track:
        - person
    
    (...)
    
    zones:
      zone_front_street:
        (...)
        objects:
          - person
        filters:
          person:
            min_area: 500
            threshold: 0.5
```

However, all events that were being generated showed a confidence value of 70% or more.

When looking at the debug stream I could clearly see the following happening for example:

1) person enters the street zone
2) person is correctly labeled as a 'person' (yellow label) 
3) the confidence value changes between 50-70%
4) the bounding box area is above 500
5) the border line of the zone get thicker when the person is inside the zone  
6) person leaves zone

But no event was generated.

I began to suspect that overriding the values at the zone level had no effect for some reason.  

Then I added the filter values to the objects configuration at the camera level as well:

```
cameras:
  front:
    (...)
    objects:
      track:
        - person
      filters:
        person:
          min_area: 500
          threshold: 0.5
  
    (...)
    
    zones:
      zone_front_street:
        (...)
        objects:
          - person
        filters:
          person:
            min_area: 500
            threshold: 0.5
```

Hey presto! Now events with a confidence value below 70% (and above) started to show up.

Out of curiosity I changed the filter values in the object configuration at the camera level to the default values, but kept the non-default values at the zone level, to see what happened:

```
cameras:
  front:
    (...)
    objects:
      track:
        - person
      filters:
        person:
          min_area: 0
          threshold: 0.7
  
    (...)
    
    zones:
      zone_front_street:
        (...)
        objects:
          - person
        filters:
          person:
            min_area: 500
            threshold: 0.5
```

As I suspected all events generated after this was done has a confidence value of 70% or above, despite having the threshold value overridden in the zone setting.

Thought someone should know.

Cheers!

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate

go2rtc:
  streams:
    front:
      - rtsp://username:password@ip:554/Streaming/Channels/101
    front_sub:
      - rtsp://username:password@ip:554/Streaming/Channels/102
      
  webrtc:
    candidates:
      - 192.168.2.3:8555
      - stun:8555

detectors:
 coral:
   type: edgetpu
   device: usb

birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 8
  mode: objects

ui:
  live_mode: mse
  timezone: Europe/Stockholm
  use_experimental: false
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: "%Y-%m-%d %H:%M"

cameras:
  front:
    enabled: true
    best_image_timeout: 60

    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args: 
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect

    live:
      stream_name: front_sub
    
    ui:
      order: 0
      dashboard: true

    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 10
      max_disappeared: 50

    motion:
      threshold: 25
      contour_area: 15
      mask: 0,0,0,35,415,32,415,0   # timestamp

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
        required_zones:
          - zone_front_street
          - zone_front_driveway
          - zone_front_flowerbed
          - zone_front_restricted
        retain:
          default: 1
          mode: active_objects
          objects:
            person: 2

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: true
      height: 500
      required_zones:
        - zone_front_street
        - zone_front_driveway
        - zone_front_flowerbed
        - zone_front_restricted
      retain:
        default: 10
        objects:
          person: 10
          car: 1

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      quality: 100

    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 500
          threshold: 0.6
        car:
          min_area: 0
          threshold: 0.7

    zones:
      zone_front_street:
        coordinates: 516,234,489,147,687,120,698,233
        objects:
          - person
          - car
        filters:
          person:
            min_area: 500
            threshold: 0.6
          car:
            min_area: 5000
            threshold: 0.6

      zone_front_driveway:
        coordinates: 96,720,516,234,698,233,824,720
        objects:
          - person
        filters:
          person:
            min_area: 750
            threshold: 0.7
        
      zone_front_flowerbed:
        coordinates: 96,720,516,234,447,230,8,624,0,720
        objects:
          - person
        filters:
          person:
            min_area: 750
            threshold: 0.7
      
      zone_front_restricted:
        coordinates: 1280,720,1280,231,698,233,824,720
        objects:
          - person
        filters:
          person:
            min_area: 1000
            threshold: 0.7
```

### Relevant log output

```shell
2023-10-05 08:20:51.669007470  [INFO] Starting Frigate...
2023-10-05 08:20:52.342009804  [2023-10-05 08:20:52] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-05 08:20:52.354399925  [2023-10-05 08:20:52] peewee_migrate                 INFO    : Starting migrations
2023-10-05 08:20:52.357013061  [2023-10-05 08:20:52] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-05 08:20:52.364290957  [2023-10-05 08:20:52] frigate.app                    INFO    : Output process started: 722
2023-10-05 08:20:52.364435526  [2023-10-05 08:20:52] detector.coral                 INFO    : Starting detection process: 721
2023-10-05 08:20:52.369341373  [2023-10-05 08:20:52] frigate.app                    INFO    : Camera processor started for front: 730
2023-10-05 08:20:52.369433841  [2023-10-05 08:20:52] frigate.app                    INFO    : Capture process started for front: 731
2023-10-05 08:20:54.984370103  [2023-10-05 08:20:52] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-05 08:20:54.990102717  [2023-10-05 08:20:54] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"21.7","mem":"0.5"},"116":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"140":{"cpu":"0.7","mem":"0.1"},"148":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"169":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"203":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"247":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"27615":{"cpu":"0.0","mem":"0.0"},"27683":{"cpu":"0.0","mem":"0.0"},"27686":{"cpu":"0.3","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"287":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"322":{"cpu":"0.0","mem":"0.0"},"356":{"cpu":"0.0","mem":"0.0"},"398":{"cpu":"0.0","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"438":{"cpu":"0.0","mem":"0.0"},"469":{"cpu":"0.0","mem":"0.0"},"507":{"cpu":"0.0","mem":"0.0"},"714":{"cpu":"0.0","mem":"0.1"},"720":{"cpu":"0.0","mem":"0.0"},"721":{"cpu":"6.3","mem":"0.2"},"722":{"cpu":"0.3","mem":"0.1"},"729":{"cpu":"0.0","mem":"0.0"},"730":{"cpu":"23.0","mem":"0.2"},"731":{"cpu":"2.7","mem":"0.1"},"735":{"cpu":"0.3","mem":"0.1"},"736":{"cpu":"4.3","mem":"0.1"},"742":{"cpu":"3.7","mem":"0.1"},"80":{"cpu":"0.3","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"9.3","mem":"0.0"},"99":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"60721.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":25.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.64,"pid":721}},"front":{"camera_fps":10.1,"capture_pid":731,"detection_enabled":1,"detection_fps":25.0,"ffmpeg_pid":736,"pid":730,"process_fps":10.1,"skipped_fps":0.0},"gpu_usages":{"amd-vaapi":{"gpu":"1.67 %","mem":"14.71 %"}},"service":{"last_updated":1696492158,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":527.4,"mount_type":"tmpfs","total":536.9,"used":9.5},"/media/frigate/clips":{"free":1843337.7,"mount_type":"ext4","total":1965155.9,"used":40824.0},"/media/frigate/recordings":{"free":1843337.7,"mount_type":"ext4","total":1965155.9,"used":40824.0},"/tmp/cache":{"free":977.8,"mount_type":"tmpfs","total":1000.0,"used":22.2}},"temperatures":{},"uptime":5306,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
