### ISSUE TITLE
[Support]: Boundary box isn't available at snapshot when mqtt event is triggered

### ISSUE THREAD

**Issue by robertoprubio** [blakeblackshear/frigate#8075]
### Describe the problem you are having

Previous to 0.13 the boundary box of the detection was available into the snapshot when mqtt event triggered, but since 0.13 don't 

I have a home assistant automatization that sends a telegram message with the snapshot of the detection and now the boundary box of the detection aren't send.

This is the code of my automation. I have tried to access to the snapshot after a while via a browser and the boundary box are available. Do you know what time I need to wait until boundary boxes available?

```
alias: Notificar con foto al detectar una persona en una cámara
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    alias: Is a new event?
    value_template: "{{ event_type == 'new' }}"
  - condition: template
    alias: Is a person related event?
    value_template: "{{ object_type == 'person' }}"
  - condition: template
    alias: Is a camera event?
    value_template: "{{ camera is defined }}"
action:
  - service: notify.telegram_urgente
    data:
      message: Foto {{ camera_name }}
      data:
        parse_mode: html
        photo:
          - url: "{{ base_location }}/{{ id }}/snapshot.jpg?format=android"
            caption: Foto {{ camera_name }}
variables:
  base_location: https://frigate.lhospitalet.familiaperezmarti.com/api/events
  id: "{{ trigger.payload_json['after']['id'] }}"
  event_type: "{{ trigger.payload_json['type'] }}"
  object_type: "{{ trigger.payload_json['after']['label'] }}"
  camera: "{{ trigger.payload_json['after']['camera'] }}"
  camera_name: "{{ camera | replace('_', ' ') }}"
  start_time: "{{ trigger.payload_json['after']['start_time'] }}"
mode: single
```

### Version

0.13.b2

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo WS320

### Any other information that may be helpful

-
