### ISSUE TITLE
[Support]: Error Connecting Frigate .13 Beta 2 to Home Assistant

### ISSUE THREAD

**Issue by rv10guy** [blakeblackshear/frigate#8085]
### Describe the problem you are having

When I try to connect Frigate .13 Beta 2 to Home Assistant I get the error message. "Failed to setup." I know the URL is correct as I can connect to the URL. I did update to the newest version of the beta Home Assistant integration in HACS

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  enabled: True
  user: ***
  password: ***
  host: ***
  port: 1883
  
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      porch:
        coordinates: 212,105,0,287,0,480,640,480,640,0,387,0,381,104
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      required_zones:
        - porch
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - porch
      enabled: True

  Garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      main_garage:
        coordinates: 0,480,640,480,640,0,0,0
        objects:
          - person
          - cat
          - dog
          - bicycle
          - package
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      enabled: True
      required_zones:
        - main_garage
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - main_garage
      enabled: True

  Back:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      patio:
        coordinates: 141,114,0,257,0,480,640,480,640,0,404,0,394,46
        objects:
          - person
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      required_zones:
        - patio
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - patio
      enabled: True

  Driveway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      main_driveway:
        coordinates: 35,463,0,440,0,576,1536,576,1536,284,1397,435,1195,355,949,318,519,330,479,206,273,388
        filters:
          person:
            min_area: 2000
      backyard:
        coordinates: 35,463,273,388,483,188,125,270,0,326,0,443
        objects:
          - person
        filters:
          person:
            min_area: 2000    
      alley:
        coordinates: 1280,0,1536,284,1397,435,1195,355,949,318,519,330,479,206,123,270,0,326,0,207,190,0
        objects:
          - person
          - cat
          - dog
          - bicycle
        filters:
          person:
            min_area: 2000 
    motion:
      mask:
        - 1022,68,1015,123,852,88,855,30
    detect:
      enabled: True 
      width: 1536 
      height: 576 
    snapshots:
      required_zones:
        - main_driveway
        - backyard
        - alley
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - main_driveway
          - backyard
          - alley
      enabled: True

objects:
  track:
    - car
    - motorcycle
    - bus
    - person
    - cat
    - dog
    - bicycle
    - package

birdseye:
  enabled: True
```

### Relevant log output

```shell
Home Assistant Logs: 
2023-10-06 15:57:07.517 DEBUG (MainThread) [custom_components.frigate] Finished fetching frigate data in 0.528 seconds (success: True)
2023-10-06 15:57:07.524 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.142.4:5000 for frigate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigate/__init__.py", line 186, in async_setup_entry
    client = FrigateApiClient(
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 202, in __le__
    return self.__eq__(compareto) or self.__lt__(compareto)
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 176, in __lt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <unknown 0.13.0-0858859> and <SemVer 0.8.4>
2023-10-06 15:57:22.610 DEBUG (MainThread) [custom_components.frigate] Finished fetching frigate data in 0.528 seconds (success: True)
2023-10-06 15:57:22.620 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.142.4:5000 for frigate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigate/__init__.py", line 186, in async_setup_entry
    client = FrigateApiClient(
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 202, in __le__
    return self.__eq__(compareto) or self.__lt__(compareto)
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 176, in __lt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <unknown 0.13.0-0858859> and <SemVer 0.8.4>
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
{"Back":{"camera_fps":5.1,"capture_pid":479,"detection_enabled":1,"detection_fps":9.5,"ffmpeg_pid":493,"pid":462,"process_fps":5.1,"skipped_fps":0.0},"Driveway":{"camera_fps":5.1,"capture_pid":492,"detection_enabled":1,"detection_fps":15.1,"ffmpeg_pid":501,"pid":465,"process_fps":5.1,"skipped_fps":0.0},"Front":{"camera_fps":5.0,"capture_pid":466,"detection_enabled":1,"detection_fps":8.4,"ffmpeg_pid":475,"pid":457,"process_fps":5.0,"skipped_fps":0.0},"Garage":{"camera_fps":5.1,"capture_pid":474,"detection_enabled":1,"detection_fps":12.4,"ffmpeg_pid":1582,"pid":459,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"96":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"3.0","cpu_average":"2","mem":"0.8"},"114":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"156":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"175":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"202":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"236":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"438":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"440":{"cmdline":"frigate.recording_manager","cpu":"4.5","cpu_average":"3","mem":"0.4"},"449":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"450":{"cmdline":"frigate.detector.coral","cpu":"15.2","cpu_average":"12","mem":"0.4"},"452":{"cmdline":"frigate.output       ","cpu":"0.7","cpu_average":"0","mem":"0.4"},"456":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"457":{"cmdline":"frigate.process:Front","cpu":"7.2","cpu_average":"6","mem":"0.4"},"459":{"cmdline":"frigate.process:Garage","cpu":"10.6","cpu_average":"6","mem":"0.4"},"460":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"462":{"cmdline":"frigate.process:Back ","cpu":"4.7","cpu_average":"7","mem":"0.4"},"464":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"465":{"cmdline":"frigate.process:Driveway","cpu":"10.0","cpu_average":"6","mem":"0.4"},"466":{"cmdline":"frigate.capture:Front","cpu":"0.6","cpu_average":"0","mem":"0.3"},"470":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1536x576 -i pipe: -f mpegts -s 1920x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"474":{"cmdline":"frigate.capture:Garage","cpu":"0.6","cpu_average":"0","mem":"0.3"},"475":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"2","mem":"0.2"},"478":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"479":{"cmdline":"frigate.capture:Back ","cpu":"0.5","cpu_average":"0","mem":"0.3"},"491":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Front-%Y%m%d%H%M%S.mp4","cpu":"1.6","cpu_average":"2","mem":"0.1"},"492":{"cmdline":"frigate.capture:Driveway","cpu":"1.3","cpu_average":"1","mem":"0.3"},"493":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.6","cpu_average":"2","mem":"0.2"},"501":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_sub -r 5 -vf fps=5,scale_vaapi=w=1536:h=576,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.5","cpu_average":"2","mem":"0.2"},"503":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Back-%Y%m%d%H%M%S.mp4","cpu":"1.9","cpu_average":"2","mem":"0.1"},"506":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Driveway-%Y%m%d%H%M%S.mp4","cpu":"1.7","cpu_average":"1","mem":"0.1"},"1557":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Garage-%Y%m%d%H%M%S.mp4","cpu":"2.1","cpu_average":"1","mem":"0.1"},"1582":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.7","cpu_average":"1","mem":"0.1"},"5849":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":45.4,"detectors":{"coral":{"detection_start":1696626388.044702,"inference_speed":7.69,"pid":450}},"gpu_usages":{"intel-vaapi":{"gpu":"1.92%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":438},"recording":{"pid":440}},"service":{"last_updated":1696626388,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":59.2,"mount_type":"tmpfs","total":64.0,"used":4.8},"/media/frigate/clips":{"free":55649.0,"mount_type":"ext4","total":100220.9,"used":39435.9},"/media/frigate/recordings":{"free":55649.0,"mount_type":"ext4","total":100220.9,"used":39435.9},"/tmp/cache":{"free":917.4,"mount_type":"tmpfs","total":953.7,"used":36.3}},"temperatures":{},"uptime":1556,"version":"0.13.0-0858859"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA
