### ISSUE TITLE
[Config Support]: Motion Mask Suddenly Stopped Working

### ISSUE THREAD

**Issue by halexh** [blakeblackshear/frigate#8093]
### Describe the problem you are having

Recently, I tweaked my config to enable 24/7 recording, followed by disabling it a ~week later. Since that last modification, motion masks no longer seem to be working. Frigate keeps recording events in which motion never leaves the masked area. I am not sure if I accidentally tweaked something in my config, or at the same time something changed in frigate?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.68.75
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    reolink_doorbell: 
      - "ffmpeg:http://192.168.68.56/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    reolink_doorbell_sub: 
      - "ffmpeg:http://192.168.68.56/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}"

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

cameras:
  Doorbell:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell?video=copy&audio=aac
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub?video=copy
          roles:
            - detect
    detect:
      enabled: true
    motion:
      mask:
        - 203,519,347,524,461,520,482,476,559,453,725,437,1280,400,1280,0,444,0,0,0,0,488

  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.120:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.120:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:
        - 1920,0,1506,0,1224,0,1045,0,886,0,579,0,283,0,0,0,0,428,308,328,598,223,877,162,1100,135,1286,134,1523,156,1687,195,1920,273

  Back:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.121:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.121:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:
        - 1920,469,1920,0,375,0,379,64
        - 0,0,0,781,0,1080,222,1080,176,891,134,679,120,349,141,139,397,61,388,0

  Porch:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.122:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.122:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:
        - 1920,0,1920,537,1920,1080,1260,1080,1399,747,1487,557,1548,383,1614,160,1656,0

  Side:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.123:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.123:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:
        - 1920,0,1075,0,560,0,346,0,0,0,0,422,126,346,230,290,348,239,443,204,567,163,694,134,824,112,962,92,1081,88,1178,88,1315,96,1430,110,1590,135,1742,172,1920,236
        - 0,1080,359,1080,0,600

  Front:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.124:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.68.124:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080
    motion:
      mask:
        - 1789,170,1640,162,1492,179,1335,220,1028,324,721,441,335,609,0,780,0,0,231,0,595,0,848,0,1314,0,1473,0,1630,0,1765,0,1920,0,1920,197

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  #retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    #days: 10
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    #mode: all  
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include
    pre_capture: 5
    # Optional: Number of seconds after the event to include
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days
      default: 10
      # Optional: Mode for retention.
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view
  enabled: True
  # Optional: Restream birdseye via RTSP
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  width: 1920
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB
