### ISSUE TITLE
[Detector Support]: Crash during model generation for Tensor detector, proxmox lxc, 3060 Ti

### ISSUE THREAD

**Issue by jmhands** [blakeblackshear/frigate#8115]
### Describe the problem you are having

Crash during model generation for Tensor detector when building yolov7x-640 or yolov7-tiny-416.trt

### Version

ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.20
  user: admin
  password: xxx
ffmpeg:
  hwaccel_args: preset-nvidia-h265
  output_args:
    record: preset-record-generic-audio-copy
cameras:
  Reolink1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.0.10:554/h265Preview_01_main
          roles:
            - record
        - path: rtsp://admin:xxx@192.168.0.10:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 4
    snapshots:
      enabled: True
record:
  enabled: True
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 2
birdseye:
  enabled: True
  width: 3840
  height: 2160
  quality: 1
  mode: continuous
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt
    shm_size: "1024mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/config.yml:/config/config.yml:rw
      - /root/video/:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - YOLO_MODELS=yolov7x-640
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant log output

```shell
yolov7x-640.cfg and yolov7x-640.weights

Done.
2023-10-09 23:45:04.998682965  [INFO] Starting go2rtc healthcheck service...

Generating yolov7x-640.trt. This may take a few minutes.

/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:147: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
  builder.max_batch_size = MAX_BATCH_SIZE
/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:149: DeprecationWarning: Use set_memory_pool_limit instead.
  config.max_workspace_size = 1 << 30
/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:172: DeprecationWarning: Use build_serialized_network instead.
  engine = builder.build_engine(network, config)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Using Proxmox LXC container with Ubuntu 23.04. I can get CPU and Coral detectors working fine. Able to pass through GPU ok, can run nvidia-smi within the docker container and showing driver 535 properly. Just testing the NVIDIA detectors, I have other Frigate systems with Coral working fine!

GPU is 3060Ti on AMD Epyc 7302
