### ISSUE TITLE
[Support]: False positives help

### ISSUE THREAD

**Issue by zwack-am** [blakeblackshear/frigate#8116]
### Describe the problem you are having

Frigate detected a car in our drive zone when the car was nowhere near our drive zone.  The snapshot shows the car taillights entering the garage across the street, but the bounding box detects a car in an empty street.  Detection also detects the mirror and front right fender on our jeep as being a person. buut the jeep isn't present in this clip/snapshot.

Any idea how I can improve this?

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: besdersec123

objects:
  track:
    - person
    - car

go2rtc:
  streams:
    driveway:
      - rtsp://192.168.1.227:554/user=admin&password=besdersec123&channel=1&stream=0
    driveway_sub:
      - rtsp://192.168.1.227:554/user=admin&password=besdersec123&channel=1&stream=1
  
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
  driveway: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 630 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      events:
        required_zones:
          - "drive"
      enabled: true
    motion:
      mask:
        - 630,0,630,282,630,40,630,41,393,40,391,0
        - 316,360,630,360,630,124,320,129
        - 0,360,90,265,97,36,0,41
    snapshots:
      required_zones:
        - "drive"
      enabled: true
    zones:
      drive:
        coordinates: 0,360,88,130,339,128,324,360
        objects:
          - person
          - car
      street:
        coordinates: 95,133,630,126,630,41,358,43,95,27
        objects:
          - person
      all:
        coordinates: 0,0,0,360,630,360,630,0
        objects:
          - person
# stream=0 1920x1080, stream=1 630x360,
```

### Relevant log output

```shell
Nothing Relevant found
```

### FFprobe output from your camera

```shell
ffprobe version 6.0-7 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Debian 13.2.0-4)
  configuration: --prefix=/usr --extra-version=7 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --disable-libsvtav1 --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://192.168.1.227:554/user=admin&password=besdersec123&channel=1&stream=1':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.083333, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x360, 12 fps, 12 tbr, 90k tbn
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

BESDERSEC A6

### Any other information that may be helpful

![snapshot-1696730134 356126-fanqi2](https://github.com/blakeblackshear/frigate/assets/27191251/f1aa4375-f05c-465a-a45f-5a2d783ed554)
![Screenshot_2023-10-09_17-56-05](https://github.com/blakeblackshear/frigate/assets/27191251/b10fec0a-949b-4999-85bf-f94767eb550e)
