### ISSUE TITLE
[Support]: objects tacking help

### ISSUE THREAD

**Issue by jsbowling42** [blakeblackshear/frigate#8122]
### Describe the problem you are having

Objects are being detected nowhere near the actual object in the frame. 

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  host: xxxxxx
  user: xxxxxx
  password: xxxx
 
ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  output_args:
    record: preset-record-generic-audio-copy

audio:
  enabled: True

go2rtc:
  streams:
    driveway_cam: 
      - rtsp://admin:xxxxx@xxxxxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:driveway_cam#audio=opus"
    front_yard_cam: 
      - rtsp://admin:xxxxx@xxxxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_yard_cam#audio=opus"
    side_cam: 
      - rtsp://admin:xxxxx@xxxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:side_cam#audio=opus"
    front_door_cam: 
      - rtsp://admin:xxxxxx@xxxxxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_door_cam#audio=opus"
    backyard_cam: 
      - rtsp://admin:xxxxx@xxxxxxx:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:backyard_cam#audio=opus"
    
cameras:
########################################################################################################################################################################################
#
#
#        Driveway Cam
#
########################################################################################################################################################################################
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://frigate_ip:8554/driveway_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      # width: 2304
      # height: 1296
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - car
        - animal

      filters:
        animal:
          threshold: 0.7
        car:
          mask:
            - 317,183,220,270,376,226,571,196,887,131,1107,120,1326,120,1524,136,1529,0,410,0
          min_ratio: 0.5
          min_score: 0.45
          threshold: 0.6
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 1.0
          # Optional: minimum score for the object to initiate tracking (default: 0.5)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - side_yard
        - front_yard
        - driveway
        - driveway_entrance
    motion:
      improve_contrast: True
      mask: 596,997,596,1050,355,1051,357,992

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        pre_capture: 30
        post_capture: 30
        required_zones:
          - side_yard
          - front_yard
          - driveway
          - driveway_entrance
        retain:
          default: 14
          mode: active_objects
    zones:
      driveway_entrance:
        coordinates: 1252,276,1227,270,1209,260,1192,245,1178,229,1162,213,967,214,952,243,937,262,900,277,862,290
        objects:
          - car
          - person
          - animal

      side_yard:
        coordinates: 0,1080,132,1080,144,1059,197,977,251,900,296,843,390,706,437,646,497,581,535,535,559,506,591,465,632,432,663,391,695,363,749,319,782,306,810,300,835,291,864,283,899,273,927,260,944,248,957,232,972,203,810,207,793,212,757,235,692,279,653,302,608,329,452,446,187,687,102,730,0,856
        objects: 
          - person
          - animal

      front_yard:
        coordinates: 1195,235,1227,263,1251,270,1290,282,1327,290,1391,300,1449,307,1490,309,1507,297,1517,267,1521,241,1516,215,1483,213,1410,206,1310,201,1156,200
        objects: 
          - person
          - animal

      driveway:
        coordinates:  1920,1080,1920,879,1920,835,1889,807,1863,772,1859,741,1836,713,1806,675,1779,640,1749,610,1720,577,1695,546,1661,516,1629,476,1587,436,1562,418,1547,404,1524,384,1502,369,1506,351,1505,327,1492,317,1433,311,1391,307,1349,297,1311,294,1264,278,846,295,812,309,757,326,725,338,679,384,605,452,524,558,434,697,323,852,200,1011,150,1080
        objects:
          - car
          - person
          - animal
########################################################################################################################################################################################
#
#
#        Front yard Cam
#
########################################################################################################################################################################################
  front_yard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://frigate_ip:8554/front_yard_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - animal

      filters:
        animal:
          threshold: 0.7
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 1.0
          # Optional: minimum score for the object to initiate tracking (default: 0.5)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - front_yard
        - sidewalk
    motion:
      improve_contrast: True
      mask:
        - 558,1058,561,1005,25,1016,0,1058

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - front_yard
          - sidewalk
        retain:
          default: 14
          mode: active_objects
    zones:
      front_yard:
        coordinates: 458,1080,1494,1080,1920,1080,1920,762,1863,477,1798,325,1524,233,1329,188,1116,150,974,128,863,118,836,119,795,125,744,133,674,141,611,155,527,172,478,184,446,195,428,204,430,221,447,222,489,233,518,240,561,250,635,264,681,276,707,284,734,295,757,307,774,322,786,348,792,384,782,410,769,432,723,467,637,524,584,560,529,609,413,687,278,763
        objects: 
          - person
          - animal
   
      sidewalk:
        coordinates: 271,758,388,693,485,637,552,584,591,554,647,514,686,491,717,466,754,441,772,421,786,398,789,378,783,350,769,327,750,309,731,300,707,291,665,276,628,270,596,263,558,253,524,247,495,239,470,235,442,227,421,222,413,237,418,265,442,270,462,275,484,281,512,289,554,302,578,310,608,322,630,333,646,348,655,366,655,388,644,410,625,430,602,443,562,466,529,481,473,497,408,520,340,547,271,580,191,624
        objects:
          - person
          - animal

########################################################################################################################################################################################
#
#
#        master side yard Cam
#
########################################################################################################################################################################################
  side_cam:
    ffmpeg:
      inputs:
        - path: rtsp://frigate_ip:8554/side_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - animal

      filters:
        animal:
          threshold: 0.7
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 1.0
          # Optional: minimum score for the object to initiate tracking (default: 0.5)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - master_side_yard
    motion:
      improve_contrast: True
      mask:
        - 261,1005,429,1010,432,1044,259,1048

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - master_side_yard
        retain:
          default: 14
          mode: active_objects
    zones:
      master_side_yard:
        coordinates: 1920,1080,1633,716,1048,179,941,185,760,196,766,465,806,1080
        objects: 
          - person
          - animal

########################################################################################################################################################################################
#
#
#        Front door Cam
#
########################################################################################################################################################################################
  front_door_cam:
    ffmpeg:
      inputs:
        - path: rtsp://frigate_ip:8554/front_door_cam  # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      width: 1440
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - animal

      filters:
        animal:
          threshold: 0.7
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 1.0
          # Optional: minimum score for the object to initiate tracking (default: 0.5)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - front_yard
    motion:
      improve_contrast: True
      mask: 1418,0,1419,38,1017,35,1015,0


    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - front_yard
        retain:
          default: 14
          mode: active_objects
    zones:
      front_yard:
        coordinates: 404,1080,1440,1080,1440,671,1360,655,1276,640,1084,613,958,600,902,603,837,608,798,608,696,615,572,618,490,621,421,620,437,695
        objects: 
          - person
          - animal

########################################################################################################################################################################################
#
#
#        Backyard Cam
#
########################################################################################################################################################################################
  backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://frigate_ip:8554/backyard_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - animal
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 1.0
          # Optional: minimum score for the object to initiate tracking (default: 0.5)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - backyard
    motion:
      improve_contrast: True

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - backyard
        retain:
          default: 14
          mode: active_objects
    zones:
      backyard:
        coordinates: 0,1080,1465,1080,1502,776,1503,627,1485,449,1477,319,1474,273,1447,227,1391,220,1251,188,1116,166,885,136,667,131,546,157,383,206,0,365
        objects: 
          - person
          - animal
          
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov4-608.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 608
  height: 908
  labelmap:
    16: animal
    17: animal
```

### Relevant log output

```shell
2023-10-10 08:17:10.674386159  [INFO] Preparing Frigate...
2023-10-10 08:17:10.686396140  [INFO] Starting Frigate...
2023-10-10 08:17:11.888028594  [2023-10-10 08:17:11] frigate.app                    INFO    : Starting Frigate (0.13.0-0858859)
2023-10-10 08:17:12.593182736  [2023-10-10 08:17:12] peewee_migrate.logs            INFO    : Starting migrations
2023-10-10 08:17:12.597954810  [2023-10-10 08:17:12] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-10-10 08:17:12.700826062  [2023-10-10 08:17:12] frigate.app                    INFO    : Recording process started: 304
2023-10-10 08:17:12.704296084  [2023-10-10 08:17:12] frigate.app                    INFO    : go2rtc process pid: 98
2023-10-10 08:17:12.745506104  [2023-10-10 08:17:12] frigate.app                    INFO    : Output process started: 316
2023-10-10 08:17:12.747323891  [2023-10-10 08:17:12] detector.tensorrt              INFO    : Starting detection process: 314
2023-10-10 08:17:12.769522447  [2023-10-10 08:17:12] frigate.app                    INFO    : Camera processor started for driveway_cam: 322
2023-10-10 08:17:12.770532756  [2023-10-10 08:17:12] frigate.app                    INFO    : Camera processor started for front_yard_cam: 324
2023-10-10 08:17:12.782721982  [2023-10-10 08:17:12] frigate.app                    INFO    : Camera processor started for side_cam: 328
2023-10-10 08:17:12.790558411  [2023-10-10 08:17:12] frigate.app                    INFO    : Camera processor started for front_door_cam: 329
2023-10-10 08:17:12.799581889  [2023-10-10 08:17:12] frigate.app                    INFO    : Camera processor started for backyard_cam: 332
2023-10-10 08:17:12.806674108  [2023-10-10 08:17:12] frigate.app                    INFO    : Capture process started for driveway_cam: 334
2023-10-10 08:17:12.818366076  [2023-10-10 08:17:12] frigate.app                    INFO    : Capture process started for front_yard_cam: 337
2023-10-10 08:17:12.834236682  [2023-10-10 08:17:12] frigate.app                    INFO    : Capture process started for side_cam: 345
2023-10-10 08:17:12.844798540  [2023-10-10 08:17:12] frigate.app                    INFO    : Capture process started for front_door_cam: 350
2023-10-10 08:17:12.852905897  [2023-10-10 08:17:12] frigate.app                    INFO    : Capture process started for backyard_cam: 351
2023-10-10 08:17:12.865286434  [2023-10-10 08:17:12] frigate.app                    INFO    : Audio process started: 355
2023-10-10 08:17:13.054260052  [2023-10-10 08:17:13] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 284 MiB
2023-10-10 08:17:13.279791146  [2023-10-10 08:17:13] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 417, GPU 403 (MiB)
2023-10-10 08:17:13.286312435  [2023-10-10 08:17:13] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 418, GPU 413 (MiB)
2023-10-10 08:17:13.291298372  [2023-10-10 08:17:13] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +289, now: CPU 0, GPU 289 (MiB)
2023-10-10 08:17:13.365127220  [2023-10-10 08:17:13] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 135, GPU 413 (MiB)
2023-10-10 08:17:13.365132777  [2023-10-10 08:17:13] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 135, GPU 421 (MiB)
2023-10-10 08:17:13.372050729  [2023-10-10 08:17:13] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +144, now: CPU 0, GPU 433 (MiB)
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/35424582/49506194-0b19-49d6-bfb3-049707d982fa)

![image](https://github.com/blakeblackshear/frigate/assets/35424582/5f7760df-5fca-439d-a801-7e0fa1918e7b)

![image](https://github.com/blakeblackshear/frigate/assets/35424582/82245bce-dbdb-4803-9f37-7525763fd757)

![image](https://github.com/blakeblackshear/frigate/assets/35424582/5dfd24d2-39fc-4ac6-bed0-ef889d4e0bf7)
