### ISSUE TITLE
[Support]: birdseye view not working in iPad

### ISSUE THREAD

**Issue by mchangsp** [blakeblackshear/frigate#8133]
### Describe the problem you are having

I am using an iPad with iPad OS 17.3 The birdseye view is not working ,see screenshot. On a Windows 10 machine with Chrome I can see the live stream of my IP camera.
The birdseye view was working on my iPad with older Frigate versions.

![IMG_0209](https://github.com/blakeblackshear/frigate/assets/13312076/f05f2a9a-9104-4cd2-b513-e82f3d2b6f3a)

### Version

0.12.1-367d724

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

timestamp_style:
  format: "%d.%m.%Y %H:%M:%S"
  position: "bl"


snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 21

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 21
    mode: motion
  events:
    pre_capture: 10
    post_capture: 5
    retain:
      default: 21

cameras:
  # Required: name of the camera
  fr_frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://frigate *redacted*
          roles:
            - detect
            - record
      hwaccel_args: preset-rpi-64-h264
    detect:
      enabled: True
      # http flv feed = 896 x 672, 30 fps
      # rtsp feed = 640 x 480    
      width: 640
      height: 480
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True

objects:
  track:
    - person
    - cat
    - dog
    - bird

birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink E1 outdoor
