### ISSUE TITLE
MQTT not reconnecting properly if mosquitto restarts

### ISSUE THREAD

**Issue by Ulrar** [blakeblackshear/frigate#814]
**Describe the bug**
I've got mosquitto and frigate running on docker, and when mosquitto gets updated (so when it restarts) it looks like frigate doesn't reconnect to it properly.

When I try to enable / disable detection through mqtt (topic frigate/mycamera/detect/set), it does nothing until I restart frigate.
After restarting frigate it starts working again.

**Version of frigate**
/version just shows the web interface, but the version in the debug page is : 0.8.1-d376f6b

**Config file**
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: mqtt.local
  port: 8883
  topic_prefix: frigate
  client_id: frigate
  user: mqttuser
  password : mqttpassword

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

cameras:
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:8554/unicast
          roles:
            - detect
            - clips
            - record
            - rtmp
    motion:
      mask:
        - 244,0,244,33,0,33,0,0 # Timestamp
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      retain:
        default: 10
    record:
      enabled: False
      retain_days: 30
    fps: 5
    width: 1280
    height: 720
    best_image_timeout: 60
```

**Frigate container logs**
```
2021-02-19T09:27:28.891893985Z frigate.mqtt                   INFO    : MQTT connected
```
^This looks like the time mqtt got updated

**Frigate stats**
Here gain /stats is just returning the regular web interface, I'm assuming that's not expected.

**Computer Hardware**
 - OS: Debian buster
 - Install method: Docker container, amd64
 - Virtualization: None
 - Coral Version: USB
 - Network Setup: Wired, mqtt runs on the same host but different container

**Additional context**
Everything does work fine, I just can't control detection through mqtt if it restarted after frigate.
All my containers are setup using macvlan, they have their own IPs.
