### ISSUE TITLE
[HW Accel Support]: Still having FFMPEG processes at host even if using GPU

### ISSUE THREAD

**Issue by robertoprubio** [blakeblackshear/frigate#8144]
### Describe the problem you are having

I have enabled nvidia gpu to process FFMPEG but this kind of processes are listed when I exec TOP command at the host.

 
![imagen](https://github.com/blakeblackshear/frigate/assets/31618496/c7e70b62-1d5c-4aa7-8475-ee3a6241b0c9)

![imagen](https://github.com/blakeblackshear/frigate/assets/31618496/ce4fcc76-7d47-486d-bd6c-1cc5569fc2ed)

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.31.5
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

ui:
  live_mode: mse

rtmp:
  enabled: false

birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
      
record:
  enabled: true
  retain:
    days: 7

motion:
  improve_contrast: true

detect:
  enabled: false
  width: 1920
  height: 1080

detectors:
  coral:
    type: edgetpu
    device: usb

#model:
#  path: plus://a0702ae8f41e2a58d65dc2a7f1c184a8

objects:
  track:
    - person
    - dog
    - cat 
  filters:
    person:
      min_area: 25000
#      min_score: .8
#      threshold: .85 

go2rtc:
  streams:
    terraza_trasera:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.231/stream1"
    dormitorio_principal:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.235/stream1"
    recibidor:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.233/stream1"
    comedor:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.234/stream1"
    terraza_delantera:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.232/stream1"
 
cameras:
  terraza_trasera:
    enabled: true
    ui: 
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraza_trasera
          roles:
            - record
            - detect

  dormitorio_principal:
    enabled: true
    ui:                 
      order: 2          
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dormitorio_principal
          roles:
            - record
            - detect

  recibidor:
    enabled: true
    ui:                 
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/recibidor
          roles:
            - record
            - detect

  comedor:
    enabled: true
    ui:                 
      order: 4          
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/comedor
          roles:
            - record
            - detect

  terraza_delantera:
    enabled: true
    ui:                 
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraza_delantera
          roles: 
            - record
            - detect
    objects:
      filters:
        person:
          mask:
            - 1920,0,1920,252,1720,233,1708,0  # Foco
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2
    privileged: true 
    restart: unless-stopped
    shm_size: "192mb" 
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../dockers-data/frigate:/config
      - ../dockers-data-extra/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]
    environment:
      LIBVA_DRIVER_NAME: "i965"
      FRIGATE_MQTT_USER: "mosquitto"
      FRIGATE_MQTT_PASSWORD: "************************"
      FRIGATE_RTSP_USER: "frigate"
      FRIGATE_RTSP_PASSWORD: "*******************"
      PLUS_API_KEY: "*******************"

networks:
  default:
    external: true
    name: nginxpm_network
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Tapo
