### ISSUE TITLE
[Support]: Audio lost in recordings after a restart

### ISSUE THREAD

**Issue by tpjanssen** [blakeblackshear/frigate#8149]
### Describe the problem you are having

From time to time my recordings loose their audio stream. This happens after a start of Frigate. If I compare the last recorded segment before Frigate is restarted:

![image](https://github.com/blakeblackshear/frigate/assets/25168870/1c9ceea0-ef95-4ab8-b064-98bd002b312c)

With the first one after restart:

![image](https://github.com/blakeblackshear/frigate/assets/25168870/a6152d94-78c6-44ce-af66-c4a5afa9a1d8)

Viewing the live stream in the web interface gives audio, ffprobe of the cam shows that there is audio present in the stream.

The output of `http://192.168.10.172/live/webrtc/api/streams?src=voordeur` without sound:

```json
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.10.130:8554/voordeur",
      "remote_addr": "192.168.10.130:8554",
      "user_agent": "go2rtc/1.7.1",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.2.0\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=420028;sprop-parameter-sets=Z0IAKOkA8ARPywgAAB9IAAYcECAA,aMqPIAA=\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\n",
      "medias": [
        "video, recvonly, H.264 Baseline 4.0",
        "audio, recvonly, MPEG4-GENERIC/8000"
      ],
      "receivers": [
        "96 H264, bytes=27897083818, senders=1",
        "97 MPEG4-GENERIC/8000, bytes=5203753, senders=0"
      ],
      "recv": 28261969732
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/voordeur",
      "remote_addr": "127.0.0.1:35622",
      "user_agent": "FFmpeg Frigate/0.13.0-0858859",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.7.1\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=420028;sprop-parameter-sets=Z0IAKOkA8ARPywgAAB9IAAYcECAA,aMqPIAA=\r\na=control:trackID=0\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=27897083818, receivers=1"
      ],
      "send": 28210588234
    }
  ]
}
```

After another restart, when sound is restored, I see this:

```json
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.10.130:8554/voordeur",
      "remote_addr": "192.168.10.130:8554",
      "user_agent": "go2rtc/1.7.1",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.2.0\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=420028;sprop-parameter-sets=Z0IAKOkA8ARPywgAAB9IAAYcECAA,aMqPIAA=\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\n",
      "medias": [
        "video, recvonly, H.264 Baseline 4.0",
        "audio, recvonly, MPEG4-GENERIC/8000"
      ],
      "receivers": [
        "96 H264, bytes=3177156533, senders=1",
        "97 MPEG4-GENERIC/8000, bytes=11322530, senders=1"
      ],
      "recv": 3215267167
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/voordeur",
      "remote_addr": "127.0.0.1:60500",
      "user_agent": "FFmpeg Frigate/0.13.0-0858859",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.7.1\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=420028;sprop-parameter-sets=Z0IAKOkA8ARPywgAAB9IAAYcECAA,aMqPIAA=\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/8000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=158856E500\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=3177156533, receivers=1",
        "97 MPEG4-GENERIC/8000, bytes=11322530, receivers=1"
      ],
      "send": 3224196535
    }
  ]
}
```

Seems like after restart the capture process sometimes connects to go2rtc with requesting for sound? Once Frigate is started without sound, it never recovers from it. Only another restart will recover the sound.

### Version

0.13.0 beta2

### Frigate config file

```yaml
go2rtc:
  streams:
    voordeur:
      - rtsp://192.168.10.130:8554/voordeur
    voordeur_detect:
      - rtsp://192.168.10.130:8554/voordeur_detect

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  voordeur:
    mqtt:
      quality: 95
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/voordeur
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/voordeur_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    live:
      stream_name: voordeur
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: all
        required_zones:
          - zone_voordeur
    snapshots:
      enabled: True
      bounding_box: True
      quality: 100
      retain:
        default: 7
      required_zones:
        - zone_voordeur
    best_image_timeout: 0
    objects:
      track:
        - person
        - cat
        - dog
        - face
      filters:
        person:
          min_area: 2000
          min_score: 0.8
          threshold: 0.85
        cat:
          min_score: 0.65
          threshold: 0.8
        dog:
          mask:
            - 0,720,654,720,647,171,518,0,0,0
          min_score: 0.7
          threshold: 0.9
        face:
          min_score: 0.7
    zones:
      zone_voordeur:
        coordinates: 
          462,135,504,387,626,377,627,633,902,519,1280,572,1280,720,244,720,242,117
    motion:
      contour_area: 15
      improve_contrast: True
      mask:
        - 0,720,544,720,544,661,0,661
        - 0,720,197,720,140,0,0,0
        - 811,720,602,720,608,626,945,471,1064,485
        - 1006,0,939,318,618,244,532,0
        - 1166,338,1173,256,1141,65,1119,0,956,0,911,196,956,288,1033,336
```

### Relevant log output

```shell
Nothing
```

### FFprobe output from your camera

```shell
[{
        "return_code": 0,
        "stderr": "",
        "stdout": {
            "programs": [],
            "streams": [{
                    "avg_frame_rate": "25/1",
                    "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
                    "height": 1080,
                    "width": 1920
                }, {
                    "avg_frame_rate": "0/0",
                    "codec_long_name": "AAC(AdvancedAudioCoding)"
                }
            ]
        }
    }, {
        "return_code": 0,
        "stderr": "",
        "stdout": {
            "programs": [],
            "streams": [{
                    "avg_frame_rate": "10/1",
                    "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
                    "height": 720,
                    "width": 1280
                }
            ]
        }
    }
]
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

Incomings camera streams are coming from a go2rtc connection of another Frigate 0.12.1 instance.
