### ISSUE TITLE
[Support]: Frigate no longer detecting events.

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#8152]
### Describe the problem you are having

Frigate has stopped detecting / recording events. 

### Version

12.

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local
  user: 
  password: 

logger:
  default: debug

ui:
  use_experimental: True

environment_vars:
  AMC_USERNAME: admin
  AMC_PASSWORD: 

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  
detect:
  width: 704
  height: 480
  fps: 5

snapshots:
  enabled: True
    
record:
  enabled: True
  events:
    retain:
      default: 10
        
birdseye:
  enabled: True
  mode: continuous

objects:
  filters:
    person:
      min_area: 800
    car:
      max_area: 80000
  track:
    - car
    - person
    - dog

cameras:
  front_porch:
    record:
      enabled: true
      retain:
        days: 7

    motion:
      mask:
        - 0,0,0,74,70,52,173,32,274,29,416,33,530,57,653,92,704,85,704,0
        - 0,480,0,296,220,297,216,480
    zones:
      front_street:
        coordinates: 139,39,163,31,206,36,247,23,327,25,416,34,515,51,592,72,644,89,674,97,658,172,634,163,566,138,443,112,286,76,150,122,142,66
        objects:
          - person
          - car
          - dog
      front_porch_area:
        coordinates: 0,480,0,76,140,41,151,136,258,86,430,111,652,172,704,90,704,480
        objects:
          - person
          - dog
    objects:
      filters:      
        person:
          mask:
            - 0,480,204,480,190,268,0,281
            
    snapshots:
      required_zones:
        - front_street
        - front_porch_area
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record

  driveway:
    motion:
      mask:
        - 0,0,704,0,704,166,0,184
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    zones:
      front_street:
        coordinates: 0,250,704,239,704,170,0,181
        objects:
          - person
          - car
          - dog
      driveway_area:
        coordinates: 704,480,0,480,0,236,704,233        
        objects:
          - person
          - car
          - dog
    objects:
      filters:
        car:
          mask:            
            - 569,335,677,339,676,258,566,261
    snapshots:
      required_zones:
        - front_street
        - driveway_area

  south_side:
    motion:
      mask:
        - 0,0,0,56,38,45,114,42,345,76,629,156,704,238,704,0
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.22:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record

  back_north:
    motion:
      mask:
        - 626,173,630,156,629,134,543,110,449,97,316,69,171,67,78,63,0,79,0,0,704,0,704,203

    objects:
      filters:
        person:
          mask: 704,0,704,201,624,175,576,162,529,149,0,49,0,0

    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.23:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.23:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest

### Any other information that may be helpful

I have tried restarting the frigate addon and it still doesn't seem to be working. I know there are events that happened in the past 3 days. I am not there, but my mom has left the house many times and the street normally gets a lot of traffic.

I was thinking maybe storage as I am using an NFS share mounted through HA for my frigate folder, but 24/7 recordings seem to be working fine

All toggles are on
