### ISSUE TITLE
FFMPEG Hardware Acceleration on Raspberry Pi 4 running Home Assistant OS

### ISSUE THREAD

**Issue by HSB-collab** [blakeblackshear/frigate#817]
When I enable hardware acceleration using the options in the documentation, namely
 ```ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m```
I get the following error in the Frigate log:
```Error parsing config: extra keys not allowed @ data['cameras']['Camera1']['ffmpeg']['hwaccel_args']```

I am running Frigate 1.10.

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: Home Assistant Operating System
 - Install method: [from getting started instructions
  - Coral Version: None
 - Network Setup: Wired,

**Camera Info:**
 - Manufacturer: Sercomm
 - Model: iCamera2
 - Resolution:  720p
 - FPS: 2

**Comment by paularmstrong** [comment]
`hwaccel_args` are a global setting, not per camera

Can you post your whole config (with passwords redacted)?

**Comment by HSB-collab** [comment]
Thanks for the response. I have changed the hwaccel_args to a global setting as per my config file below (as requested it is the full frigate.yml file). 
However, I now have a different error: the camera preview cards have gone green (as per the picture attached) and when I click on them I no longer get the camera stream. I enclose the log from frigate which indicates some ffmpeg error (I am not familiar enough with ffmpeg to work out the issue).
![Cameras](https://user-images.githubusercontent.com/72898374/108643562-2c152d80-74ff-11eb-9237-2342f983b88b.JPG)

Here is the information: 
frigate.yml configuration file (passwords redacted)
```
mqtt:
  host: 10.0.0.214
  user: mqtt_user
  password: *******
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
 # Name of your camera
  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://user:******@10.0.0.120/img/video.sav
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 2  
    objects:
      track:
        - person
        - car
 # Name of your camera
  Camera2:
    ffmpeg:
      inputs:
        - path: rtsp://user:******@10.0.0.121/img/video.sav
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 2
    motion:
      mask:
        - 442,263,694,280,641,439,446,430
    objects:
      track:
        - person
        - car  
      filters:
        car:
          mask:
           - 434,309,666,307,639,432,447,424
        person:
          mask:
           - 439,295,684,295,627,441,445,432          
  # Name of your camera
  Camera3:
    ffmpeg:
      inputs:
        - path: rtsp://user:******@10.0.0.122/img/video.sav
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 2  
  # Name of your camera
  Camera4:
    ffmpeg:
      inputs:
        - path: rtsp://user:******@10.0.0.123/img/video.sav
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 2
detectors:
  cpu:
    type: cpu
```
And here is the log from Frigate when I added the hwaccel_args to the frigate.yml file:
```
frigate.video                  INFO    : Camera2: ffmpeg process is not running. exiting capture thread...
watchdog.Camera1               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
watchdog.Camera3               INFO    : FFmpeg didnt exit. Force killing...
watchdog.Camera4               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Camera4: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera4: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : Camera3: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera3: ffmpeg sent a broken frame. PyMemoryView_FromBuffer(): info->buf must not be NULL
frigate.video                  INFO    : Camera3: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : Camera3: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : Camera3: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : Camera3: ffmpeg process is not running. exiting capture thread...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55a4858c10] moov atom not found
/tmp/cache/Camera2-20210222110114.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera2-20210222110114.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5572ae6c10] moov atom not found
/tmp/cache/Camera3-20210222110104.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera3-20210222110104.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558b70fc10] moov atom not found
/tmp/cache/Camera1-20210222110104.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera1-20210222110104.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b142dc10] moov atom not found
/tmp/cache/Camera4-20210222110114.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera4-20210222110114.mp4
watchdog.Camera2               INFO    : No frames received from Camera2 in 20 seconds. Exiting ffmpeg...
watchdog.Camera2               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera1               INFO    : No frames received from Camera1 in 20 seconds. Exiting ffmpeg...
watchdog.Camera1               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera3               INFO    : No frames received from Camera3 in 20 seconds. Exiting ffmpeg...
watchdog.Camera3               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera4               INFO    : No frames received from Camera4 in 20 seconds. Exiting ffmpeg...
watchdog.Camera4               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera2               INFO    : FFmpeg didnt exit. Force killing...
watchdog.Camera1               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Camera2: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera2: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
watchdog.Camera4               INFO    : FFmpeg didnt exit. Force killing...
watchdog.Camera3               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Camera4: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera4: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : Camera3: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera3: ffmpeg process is not running. exiting capture thread...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55a8d8bc10] moov atom not found
/tmp/cache/Camera4-20210222110204.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera4-20210222110204.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55bee8ec10] moov atom not found
/tmp/cache/Camera1-20210222110213.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera1-20210222110213.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558f4dbc10] moov atom not found
/tmp/cache/Camera2-20210222110214.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera2-20210222110214.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c5834c10] moov atom not found
/tmp/cache/Camera3-20210222110204.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera3-20210222110204.mp4
watchdog.Camera2               INFO    : No frames received from Camera2 in 20 seconds. Exiting ffmpeg...
watchdog.Camera2               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera1               INFO    : No frames received from Camera1 in 20 seconds. Exiting ffmpeg...
watchdog.Camera1               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera4               INFO    : No frames received from Camera4 in 20 seconds. Exiting ffmpeg...
watchdog.Camera4               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera3               INFO    : No frames received from Camera3 in 20 seconds. Exiting ffmpeg...
watchdog.Camera3               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera2               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Camera2: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera2: ffmpeg process is not running. exiting capture thread...
watchdog.Camera1               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
watchdog.Camera4               INFO    : FFmpeg didnt exit. Force killing...
watchdog.Camera3               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Camera4: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera4: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : Camera3: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera3: ffmpeg process is not running. exiting capture thread...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x556674ec10] moov atom not found
/tmp/cache/Camera3-20210222110304.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera3-20210222110304.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c2c0dc10] moov atom not found
/tmp/cache/Camera2-20210222110314.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera2-20210222110314.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55ba290c10] moov atom not found
/tmp/cache/Camera4-20210222110304.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera4-20210222110304.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c398bc10] moov atom not found
/tmp/cache/Camera1-20210222110313.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Camera1-20210222110313.mp4
watchdog.Camera2               INFO    : No frames received from Camera2 in 20 seconds. Exiting ffmpeg...
watchdog.Camera2               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera1               INFO    : No frames received from Camera1 in 20 seconds. Exiting ffmpeg...
watchdog.Camera1               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera4               INFO    : No frames received from Camera4 in 20 seconds. Exiting ffmpeg...
watchdog.Camera4               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Camera3               INFO    : No frames received from Camera3 in 20 seconds. Exiting ffmpeg...
watchdog.Camera3               INFO    : Waiting for ffmpeg to exit gracefully...
```

Frigate is awesome! When I finally get it going, I shall try and write a tutorial guide to getting it going (at least on the Raspberry Pi with Home Assistant Operating System) to save you guys from having to nurse people like me through the process in future

**Comment by blakeblackshear** [comment]
Strange that ffmpeg isn't saying anything. Try setting `global_args` to `-hide_banner -loglevel info` for one of your cameras. Also try reducing the number of cameras temporarily.

**Comment by HSB-collab** [comment]
Thanks for the response.

I removed 3 cameras (leaving only 1), added the global_args line for that camera after `ffmpeg:` and before `inputs:`
The results are the same. The camera view in the UI goes green and I cannot stream the camera.
Here is the Frigate log output.
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera Camera1 has clips assigned to an input, but clips is not enabled.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
detector.cpu                   INFO    : Starting detection process: 37
frigate.app                    INFO    : Camera processor started for Camera1: 40
frigate.app                    INFO    : Capture process started for Camera1: 41
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
frigate.mqtt                   INFO    : MQTT connected
frigate.mqtt                   INFO    : Turning on clips for Camera1 via mqtt
ffmpeg.Camera1.detect          ERROR   : Invalid loglevel "-c:v". Possible levels are numbers or:
ffmpeg.Camera1.detect          ERROR   : "quiet"
ffmpeg.Camera1.detect          ERROR   : "panic"
ffmpeg.Camera1.detect          ERROR   : "fatal"
ffmpeg.Camera1.detect          ERROR   : "error"
ffmpeg.Camera1.detect          ERROR   : "warning"
ffmpeg.Camera1.detect          ERROR   : "info"
ffmpeg.Camera1.detect          ERROR   : "verbose"
ffmpeg.Camera1.detect          ERROR   : "debug"
ffmpeg.Camera1.detect          ERROR   : "trace"
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
```

It does not seem to like the argument `- -c:v` under hwaccel_args. I copied that straight from the Frigate documentation?

Appreciate your advice.

**Comment by blakeblackshear** [comment]
Can you post your updated config? You must have added the global_args incorrectly.

**Comment by HSB-collab** [comment]
That would not surprise me. I have great difficulty with the yaml syntax (I need to read up on it). 

Here is the frigate.yml file I used.
```
mqtt:
  host: 10.0.0.214
  user: mqtt_user
  password: *****
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2mcameras:
 # Name of your camera
  Camera1:
    ffmpeg:
      global_args:-hide_banner -loglevel info 
      inputs:
        - path: rtsp://user:*****@10.0.0.120/img/video.sav
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 2  
    objects:
      track:
        - person
        - car
     ```

**Comment by blakeblackshear** [comment]
Try this
```yaml
mqtt:
  host: 10.0.0.214
  user: mqtt_user
  password: *****
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
 # Name of your camera
  Camera1:
    ffmpeg:
      global_args: -hide_banner -loglevel info 
      inputs:
        - path: rtsp://user:*****@10.0.0.120/img/video.sav
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 2  
    objects:
      track:
        - person
        - car
```

Hopefully that will show the output from ffmpeg and tell us why its crashing.
