### ISSUE TITLE
[Config Support]: FileNotFoundError

### ISSUE THREAD

**Issue by grantbristow** [blakeblackshear/frigate#8170]
### Describe the problem you are having

Everything was going great ... then rebooted my computer. Next time I started frigate, it downloaded a "new" verison and I keep getting **FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'** Traceback shows: 
```
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
```
Repeats continously.

Originally, I had the config directory in a shared folder (NFS) and mapped to /config (/frigate/mnt/config). Never changed that, but thought maybe something weird was going on with the network drive, so I changed the the startup to map /frigate/config to /config. Still same error.

Here's my docker command:
```
/usr/bin/docker run --rm --name frigate \
--env-file /etc/frigate/secrets \
--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
--device /dev/bus/usb:/dev/bus/usb \
--device /dev/dri/renderD128 \
--shm-size=100m \
-v /frigate/mnt/media:/media/frigate \
-v /frigate/config:/config \
-v /frigate/database:/database \
-v /etc/localtime:/etc/localtime:ro \
-p 80:5000 \
-p 1935:1935 \
-p 8554:8554 \
-p 8555:8555/tcp \
-p 8555:8555/udp \
ghcr.io/blakeblackshear/frigate:stable
```
I'm kind of green with regards to docker ...

### Version

Can't get that far ... it is the latest stable, though

### Frigate config file

```yaml
mqtt:
  enabled: false
cameras:
  AMCREST01:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://{FRIGATE_CAM01_RTSP_USER}:{FRIGATE_CAM01_RTSP_PASS}@192.168.1.71:554/cam/realmonitor?channel=1&su
btype=0
          roles:
            - detect
        - path: rtsp://{FRIGATE_CAM01_RTSP_USER}:{FRIGATE_CAM01_RTSP_PASS}@192.168.1.71:554/cam/realmonitor?channel=1&su
btype=1
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 708
      height: 480
    record:
      enabled: True
      retain:
        days: 7
        mode: all
detectors:
    coral_usb:
      type: edgetpu
      device: usb
database:
    path: /database/frigate.db
```

### Relevant log output

```shell
Don't know how to get that, especially with the container constantly restarting.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB
