### ISSUE TITLE
[Camera Support]: error "no frames have been received" after move detect from default (cpu) to codeproject/deepstack

### ISSUE THREAD

**Issue by boyphongsakorn** [blakeblackshear/frigate#8173]
### Describe the problem you are having

i change from default detect to codeproject/deepstack
after that all 5 camera show "no frames have been received"
wait almost 12 hours, 3 camera show "no frames have been received"
some camera watch from web (mse mode) after that is show "no frames have been received" (is error i get from version 12 to beta 13 version 11 is never get error like that)

### Version

0.13.0-beta2

### Frigate config file

```yaml
mqtt:
  host: 192.168.31.227
  user: mqtt
  password: xxxxxxxx

detectors:
  deepstack:
    api_url: http://192.168.31.215:32168/v1/vision/detection
    type: deepstack
    api_timeout: 120

environment_vars:
  TZ: Asia/Bangkok

ffmpeg:
  #hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]
  hwaccel_args: preset-nvidia-h265
  output_args:
    #record: ["-f", "segment", "-segment_time", "10", "-segment_format", "mp4", "-reset_timestamps", "1", "-strftime", "1", "-c:v", "copy", "-c:a", "aac"]
    #rtmp: ["-c", "copy", "-f", "flv", "-c:v", "copy", "-c:a", "aac"]
    #rtmp: preset-rtsp-restream
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy
    #rtmp: preset-rtmp-generic
  retry_interval: 1

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720

go2rtc:
  streams:
    # fh_camera: ffmpeg:rtsp://admin:xxxxxxxx@192.168.31.208:554#video=copy#audio=copy#audio=opus
    # ff_camera: ffmpeg:rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream1#video=copy#audio=copy#audio=opus
    # ff_camera_sub: ffmpeg:rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream2#video=copy#audio=copy#audio=opus
    # dw_camera: ffmpeg:rtsp://admin:xxxxxxxx@192.168.31.205:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif#video=copy#audio=copy#audio=opus
    # dw_camera_sub: ffmpeg:rtsp://admin:xxxxxxxx@192.168.31.205:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif#video=copy#audio=copy#audio=opus
    dw_camera:
      - rtsp://admin:xxxxxxxx@192.168.31.208:554
      - ffmpeg:dw_camera#video=h264#audio=aac
    ff_camera:
      - rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream1
      - ffmpeg:ff_camera#video=h264#audio=aac
    ff_camera_sub:
      - rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream2
      - ffmpeg:ff_camera_sub#video=h264#audio=aac
    fh_camera:
      - rtsp://admin:L2F9CD06@192.168.31.205:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    fh_camera_sub:
      - rtsp://admin:L2F9CD06@192.168.31.205:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    # sfh_camera:
    #   - rtsp://192.168.31.88:5554/chinacamera
    #   - "ffmpeg:sfh_camera#video=h264#audio=aac"
    # sfh_camera_sub:
    #   - rtsp://192.168.31.88:5554/chinacamera_sub
    #   - "ffmpeg:sfh_camera_sub#video=h264#audio=aac"
    # sfh_camera:
    #   - rtsp://admin:xxxxxxxx@192.168.31.109:10554/udp/av0_0
    #   - "ffmpeg:sfh_camera#input=rtsp/udp#video=h264#audio=aac"
    # sfh_camera_sub:
    #   - rtsp://admin:xxxxxxxx@192.168.31.109:10554/udp/av0_1
    #   - "ffmpeg:sfh_camera_sub#input=rtsp/udp#video=h264#audio=aac"
    sfh_camera:
      - ffmpeg:rtsp://admin:xxxxxxxx@192.168.31.109:10554/tcp/av0_0#video=h264#audio=aac
    sfh_camera_sub:
      - ffmpeg:rtsp://admin:xxxxxxxx@192.168.31.109:10554/tcp/av0_1#video=h264#audio=aac
    future_camera:
      - rtsp://admin:xxxxxxxx@192.168.31.118:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    future_camera_sub:
      - rtsp://admin:xxxxxxxx@192.168.31.118:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
  webrtc:
    candidates:
      - 192.168.31.220:9005

cameras:
  fh_camera:
    ffmpeg:
      #input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv
      #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -timeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        #- path: rtmp://192.168.31.210:1935/cctv/uterum
        #- path: rtsp://admin:xxxxxxxx@192.168.31.205:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
        - path: rtsp://127.0.0.1:8554/fh_camera?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
          #- path: rtmp://192.168.31.210:1935/cctv/tertwo
          #- path: rtsp://admin:xxxxxxxx@192.168.31.205:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          #roles:
          #- restream
        - path: rtsp://127.0.0.1:8554/fh_camera_sub?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    # live:
    #   stream_name: fh_camera
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        car:
          mask:
            - 399,332,1280,73,1280,443
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 2
    motion:
      mask:
        - 399,332,1280,73,1280,443
        - 886,70,1228,69,1227,44,886,43
  # ftfh_camera:
  #   ffmpeg:
  #     input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
  #     inputs:
  #       - path: http://192.168.31.92:8080/video
  #         roles:
  #           - detect
  #     output_args:
  #       record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
  #       rtmp: -c:v libx264 -an -f flv
  #   objects:
  #     track:
  #       - person
  #       - cat
  #       - dog
  #   snapshots:
  #     enabled: true
  #     timestamp: false
  #     bounding_box: false
  #     retain:
  #       default: 2
  ff_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        #- path: rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream1
        - path: rtsp://127.0.0.1:8554/ff_camera_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/ff_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
          #- path: rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream2
          #roles:
          #- restream
    live:
      stream_name: ff_camera
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 2
    motion:
      mask:
        - 459,49,465,0,0,0,0,46
    #mqtt:
    #  timestamp: false
    #  bounding_box: false
    #  crop: True
    #  quality: 100
    #  height: 500
    #clips:
    #  enabled: true
    #  retain:
    #    default: 7
  dw_camera:
    ffmpeg:
      inputs:
        #- path: rtsp://admin:xxxxxxxx@192.168.31.208:554
        - path: rtsp://127.0.0.1:8554/dw_camera?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
              #- restream
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          mask:
            - 1182,720,857,720,981,325,1143,314
            - 363,684,363,720,56,720,56,685
            - 792,464,806,653,577,599,462,493,452,391
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 2
    motion:
      mask:
        - 1182,720,857,720,981,325,1143,314
        - 363,684,363,720,56,720,56,685
        - 792,464,806,653,577,599,462,493,452,391
    #mqtt:
    #  timestamp: false
    #  bounding_box: false
    #  crop: True
    #  quality: 100
    #  height: 500
  #gm_camera: # <------ Name the camera
  #  ffmpeg:
  #    inputs:
  #      - path: rtsp://192.168.31.206:8554/mjpeg/1 # <----- Update for your camera
  #        roles:
  #          - detect
  #    output_args:
  #      detect: -vf transpose=2,transpose=2 -f rawvideo -pix_fmt yuv420p
  #  restream:
  # Optional: Enable the RTMP stream (default: True)
  #    enabled: false
  #  detect:
  #    width: 640 # <---- update for your camera's resolution
  #    height: 480 # <---- update for your camera's resolution
  sfh_camera:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      # input_args: preset-rtsp-udp
      # output_args:
      #   record: preset-record-generic-audio-aac
      inputs:
        # - path: rtsp://127.0.0.1:8554/sfh_camera?video=copy&audio=aac
        #   input_args: preset-rtsp-restream-low-latency
        #   roles:
        #     - record
        #     # - detect
        # - path: rtsp://127.0.0.1:8554/sfh_camera_sub?video=copy&audio=aac
        #   input_args: preset-rtsp-restream-low-latency
        #   roles:
        #     # - record
        #     - detect
        - path: rtsp://127.0.0.1:8554/sfh_camera?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
              # - detect
        - path: rtsp://127.0.0.1:8554/sfh_camera_sub?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            # - record
            - detect
          # - path: rtmp://192.168.31.86:1935/cctv/uterum
          # input_args: preset-rtsp-restream-low-latency
          # input_args: preset-rtmp-generic
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        car:
          mask:
        motorcycle:
          mask:
        person:
          mask:
            - 534,720,1011,720,1074,415,834,361
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 2
    motion:
      mask:
        - 324,21,329,48,0,50,0,21
  future_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/future_camera?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/future_camera_sub?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    live:
      stream_name: future_camera
    objects:
      track:
        - person
          # - car
          # - motorcycle
      # filters:
      #   car:
      #     mask:
      #       - 719,195,1280,292,1280,0,168,137
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 2
    motion:
      mask:
        # - 719,195,1280,292,1280,0,168,137
        - 1225,42,1225,73,893,71,890,41

record:
  enabled: true
  retain:
    days: 7
    mode: all

birdseye:
  enabled: true
  mode: motion

ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: asia/bangkok
```

### Relevant log output

```shell
in comment
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x152704900] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://admin:xxxxxxxx@192.168.31.208:554':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream1
  Duration: N/A, start: 0.030750, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://boyalone99:xxxxxxxx@192.168.31.207:554/stream2':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.035500, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 640x360, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:xxxxxxxx@192.168.31.205:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:2: Data: none
Unsupported codec with id 0 for input stream 2

ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:xxxxxxxx@192.168.31.205:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480, 15 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:2: Data: none
Unsupported codec with id 0 for input stream 2

ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x139605600] max delay reached. need to consume packet
[rtsp @ 0x139605600] RTP: missed 1 packets
Input #0, rtsp, from 'rtsp://admin:xxxxxxxx@192.168.31.118:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:2: Data: none
Unsupported codec with id 0 for input stream 2

ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:xxxxxxxx@192.168.31.118:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:2: Data: none
Unsupported codec with id 0 for input stream 2
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

IMOU,TPLink (Tapo),EZVIZ
