### ISSUE TITLE
[Support]: Network bandwidth issue

### ISSUE THREAD

**Issue by sebastian-tischer** [blakeblackshear/frigate#8177]
### Describe the problem you are having

Dear Blake,

since I am on a streak for the price for worlds-next-top-issue-creator, I will follow with another question/issue:

The last months I got 2x INSTAR 9408 cameras via PoE working and connected to my switch and though in my home network. A few days ago, I installed another PoE INSTAR 9408.

**Problem:**
The loading time of the new camera webinterface as well as stream increased to 25-30 seconds (compared to the other cameras, where the WebUI loads in 6-7 seconds).
In the Instar app it takes 40-60 seconds to load P2P (via their servers) and IP (locally) - compared to 5-7seconds for other cams.

**Further Analyse:**
Removed one camera from the LAN connection => new camera loads also in 6-7 seconds
Deactivate frigate in HASS => new camera + all others load in 6-7 seconds
If all is connected and running, we come back to the previous state, where we have high load time and high interference spee of 105 - 160ms.

**Hardware & Software:**
Hardware:
- MacBook Pro via WLAN for WebUI access
- Server => Raspberry Pi 4. Gen - 4GB
- CPU Support => Google Coral via USB
- Camera => 3x INSTAR 9408
- Router => Telekom SpeedPort Pro
- PoE Switch => NETGEAR GS116LP https://www.amazon.de/gp/product/B07DFBX347/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Software
- Home Assistant OS
- Frigate NVR as HASS Addon
- Camera via 2 RTSP Streams in HASS OS / Frigate
- Detect = low resolution => rtsp://username:passwort@192.168.2.147:554/stream2
- Aufnahme = high resolution => rtsp://username:passwort@192.168.2.147:554/stream1

**Further Info**
The LAN connections has no further bandwidth heavy applications.
The whole home is controlled via KNX.
All devices who consume bandwidth are connected via LAN (Camera, RPI, TV, AppleTV). All other devices are connected via Mesh WLAN (3x Mesh sattelites).

**My new hardware will be:**
HPE Microserver Gen10+ v2 with Xeon processor & 32 GB Ram
NVIDIA T400 GPU
Unraid for Software Management
Frigate as Docker Image with GPU + Coral Support
Home Assistant OS as VM

What I am wondering now, is what caused the bandwidth issues - since it is clear, that something is having an issue. 

- It is the camera who might have a hardware issue
- Is it the cable of the camera who causes a bottleneck
- Is it frigate who brings a lot data into the network which causes to overload
- Is it the switch who might have an issue

I just want to find the bottleneck, since I am not sure if the new hardware can solve this or "only" the high interference speed.

Maybe you as an expert have an idea to help me :)

Thanks a lot for your help and warm regards
Sebastian

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
      enabled: true
      #host: 192.168.2.109
      host: core-mosquitto
      port: 1883
      user: hass-mqtt
      password: mqtt
    detectors:
      coral:
        type: edgetpu
        device: usb
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      #preset-nvidia-h265
      output_args:
        record: preset-record-generic-audio-copy
        #preset-record-generic-audio-aac
        #preset-record-generic-audio-copy
    motion:
      threshold: 15
      improve_contrast: True
    detect:
      enabled: True
      #width: 1280
      #height: 720
      width: 640
      height: 360
      fps: 5
    objects:
      filters:
        person:
          min_score: 0.7
          threshold: 0.7
      track:
        - person
    birdseye:
      enabled: True
      mode: continuous
#      restream: true
    record:
      enabled: True
      expire_interval: 60
      events:
        pre_capture: 15
        post_capture: 15
        objects:
          - person
        retain:
          default: 5
          mode: motion
          objects:
            person: 15
    
    snapshots:
      enabled: True
      clean_copy: True
      bounding_box: True
      crop: False
      retain:
        default: 5
        objects:
          person: 15

    cameras:
      Eingang:
        ffmpeg:
          inputs:
            - path: rtsp://private@192.168.2.127/livestream/13
              roles:
                - detect
            - path: rtsp://private@192.168.2.127/livestream/11
              roles:
                - record
      Garten:
        ffmpeg:
          inputs:
            - path: rtsp://private@192.168.2.128/livestream/13
              roles:
                - detect
            - path: rtsp://private@192.168.2.128/livestream/11
              roles:
                - record
        motion:
          mask:
            - 0,101,0,52,174,31,204,26,199,75
        objects:
          filters:
            person:
              mask:
                - 0,108,204,74,202,21,0,56
      Einfahrt:
        ffmpeg:
          inputs:
            - path: rtsp://private@192.168.2.141/livestream/13
              roles:
                - detect
            - path: rtsp://private@192.168.2.141/livestream/11
              roles:
                - record
        motion:
          mask:
            - 256,144,281,249,270,153,194,151
        objects:
          filters:
            person:
              mask:
                - 201,260,275,247,270,153,204,154
      Garage:
        ffmpeg:
          inputs:
            - path: rtsp://private@192.168.2.147:554/stream2
              roles:
                - detect
            - path: rtsp://private@192.168.2.147:554/stream1
              roles:
                - record
#      Wohnzimmer:
#        ffmpeg:
#          inputs:
#            - path: rtsp://private@192.168.2.148:554/stream2
#              roles:
#                - detect
#            - path: rtsp://private@192.168.2.148:554/stream1
#              roles:
#                - record
    go2rtc:
      streams:
        Eingang:
          - rtsp://private@192.168.2.127/livestream/11
          - "ffmpeg:Eingang#video=h264"
        Garten:
          - rtsp://private@192.168.2.128/livestream/11
          - "ffmpeg:Garten#video=h264"
        Einfahrt:
          - rtsp://private@192.168.2.141/livestream/11
          - "ffmpeg:Einfahrt#video=h264"
        Garage:
          - rtsp://private@192.168.2.147:554/stream1
#        Wohnzimmer:
#          - rtsp://private@192.168.2.148:554/stream1
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

INSTAR 9408
