### ISSUE TITLE
At start "ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have ffmpeg process is not running. exiting capture thread..."

### ISSUE THREAD

**Issue by heikkis** [blakeblackshear/frigate#818]
**Describe the bug**
Frigate stops working and uses 200-300% CPU. Whole Hassio Supervisor -platform will go to unstable state.

With older Hassio/Frigate I did not have these problems.

"ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have
ffmpeg process is not running. exiting capture thread..."

I have changed storage from sdcard to USB3 M.2 SSD disk but don't have any other problems so I guess it cannot be the reason.

**Version of frigate**
1.10

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
logger:
  default: info

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

mqtt:
  host: core-mosquitto.local.hass.io
  user: xxxxx
  password: xxxxxx
  
cameras:
  takapiha:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://xxxxxxxx/Streaming/Channels/101/
          roles:
            - clips
            - rtmp
            - detect
    fps: 6
    width: 1920
    height: 1080
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
  etupiha:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://xxxxxxxx/Streaming/Channels/101/
          roles:
            - clips
            - rtmp
            - detect
    fps: 6
    width: 1920
    height: 1080
    motion:
      mask:
        - '0,0,1257,0,1273,149,0,507'
    zones:
      etuovi:
        coordinates: 1734,378,1761,231,1499,244,1415,398
      autotalli:
        coordinates: 1494,236,1496,131,1379,118,1383,227
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false

clips:
  max_seconds: 60
  retain:
    default: 5

snapshots:
  retain:
    default: 10

objects:
  track:
    - person
    - car
    - cat
    - dog
    - bicycle
```

**Frigate container logs**
```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for takapiha: 39
frigate.app                    INFO    : Camera processor started for etupiha: 40
frigate.app                    INFO    : Capture process started for takapiha: 42
frigate.app                    INFO    : Capture process started for etupiha: 43
detector.coral                 INFO    : Starting detection process: 36
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
[h264 @ 0x55aad170f0] error while decoding MB 107 61, bytestream -38
watchdog.etupiha               INFO    : No frames received from etupiha in 20 seconds. Exiting ffmpeg...
watchdog.etupiha               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.takapiha              INFO    : No frames received from takapiha in 20 seconds. Exiting ffmpeg...
watchdog.takapiha              INFO    : Waiting for ffmpeg to exit gracefully...
frigate.video                  INFO    : takapiha: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : takapiha: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : takapiha: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : etupiha: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : etupiha: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : etupiha: ffmpeg process is not running. exiting capture thread...
```

**Frigate stats**
/stats gives only frontpage of Frigate with my browser.

**FFprobe from your camera**

From Macos ffprobe:

```
### TAKAPIHA camera

ffprobe version 4.3.1-with-options Copyright (c) 2007-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.28)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_5 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-demuxer=dash --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --disable-libjack --disable-indev=jack --disable-htmlpages --extra-version=with-options --enable-opencl --enable-videotoolbox
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

Input #0, rtsp, from 'rtsp://XXXXX/Streaming/Channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 1.281600, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 6 fps, 13.92 tbr, 90k tbn, 12 tbc


### ETUPIHA Camera
ffprobe version 4.3.1-with-options Copyright (c) 2007-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.28)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_5 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-demuxer=dash --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --disable-libjack --disable-indev=jack --disable-htmlpages --extra-version=with-options --enable-opencl --enable-videotoolbox
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x7fb168016c00] max delay reached. need to consume packet
[rtsp @ 0x7fb168016c00] RTP: missed 200 packets
[h264 @ 0x7fb169008e00] error while decoding MB 118 33, bytestream -50
[h264 @ 0x7fb169008e00] concealing 4131 DC, 4131 AC, 4131 MV errors in I frame
Input #0, rtsp, from 'rtsp://XXXXXX/Streaming/Channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.993333, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 6 fps, 25 tbr, 90k tbn, 12 tbc
```

**Computer Hardware**
 - Raspberry Pi 4 8GB
 - USB3 M2 SSD 1TB
 - OS: Hassio newest
 - Install method: Addon
 - Coral Version: USB3
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: two of them
 - Resolution: 1080p
 - FPS: 6
