### ISSUE TITLE
[Detector Support]: TPU Found and Not Found, Frigate+ Model not found?

### ISSUE THREAD

**Issue by leadZERO** [blakeblackshear/frigate#8181]
### Describe the problem you are having

Just trying to get my first Frigate+ model loaded. I'm receiving a ValueError for that.

(I copied XXXX from the Frigate+ models page and tried both EdgeTPU and CPU model, they each give that error.)

In addition, I'm seeing this error but not sure if that's new or not:
`frigate_1  | 2023-10-15 14:35:04.609261847  [2023-10-15 14:35:01] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate_1  | 2023-10-15 14:35:04.610759500  [2023-10-15 14:35:01] frigate.app                    INFO    : Camera processor started for front_door: 1593
frigate_1  | 2023-10-15 14:35:04.610866021  Process detector:coral:
frigate_1  | 2023-10-15 14:35:04.610888860  [2023-10-15 14:35:04] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate_1  | 2023-10-15 14:35:04.611006622  [2023-10-15 14:35:01] frigate.app                    INFO    : Camera processor started for front: 1596
frigate_1  | 2023-10-15 14:35:04.611134494  [2023-10-15 14:35:04] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.`

It looks like the TPU is both found and not found... Although before attempting to load the Frigate+ model things seemed to be working, so not sure if this is related or not.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: XXXX
  user: frigate
  port: 8883
  tls_insecure: false
  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
  password: "{FRIGATE_MQTT_PASSWORD}"

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    front_door:
      - rtsp://admin:{FRIGATE_ARTSP_PASSWORD}@192.168.2.149:554/cam/realmonitor?channel=1&subtype=0&authbasic=64#backchannel=0
    front:
      - rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.2.147:554/cam/realmonitor?channel=1&subtype=0
    driveway_side:
      - rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.2.134:554/cam/realmonitor?channel=1&subtype=0
    crawlspace_yard:
      - rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.2.156:554/cam/realmonitor?channel=1&subtype=0
    backyard:
      - rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.2.157:554/cam/realmonitor?channel=1&subtype=0
    weather_station:
      - rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.2.237:554/cam/realmonitor?channel=1&subtype=0
    back:
      - rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.2.155:554/cam/realmonitor?channel=1&subtype=0
    lake:
      - rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.2.129:554/cam/realmonitor?channel=1&subtype=0
    side_door:
      - rtsp://admin:{FRIGATE_ARTSP_PASSWORD}@192.168.2.189:554/cam/realmonitor?channel=1&subtype=0&authbasic=64#backchannel=0

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://XXXXX

logger:
  default: info
  logs:
    frigate.event: debug

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"
  thickness: 3
  effect: "shadow"

record:
  enabled: True
  retain:
    days: 10
    mode: motion
  events:
    retain:
      default: 10
      mode: active_objects
    required_zones:
      - yard
      - front_deck
      - driveway
      - lake_deck
      - side_deck

detect:
  width: 3840
  height: 2160
  fps: 5

birdseye:
  enabled: true
  mode: objects

snapshots:
  enabled: True
  timestamp: true
  bounding_box: true
  required_zones:
    - yard
    - front_deck
    - driveway
    - lake_deck
    - side_deck
  retain:
    default: 60

objects:
  track: [
    "amazon",
    "car",
    "cat",
    "deer",
    "dog",
    "face",
    "fedex",
    "license_plate",
    "package",
    "person",
    "ups"  
  ]


cameras:

  ############################
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door
          roles: ["detect", "record"]
    zones:
      front_deck:
        coordinates: 2560,589,2560,1920,0,1920,0,1071,647,894,1314,866,1645,840

      yard:
        coordinates: 1047,987,1032,792,863,744,314,630,275,829,0,790,0,1064,671,878
    detect:
      width: 2560
      height: 1920

  ############################
  front:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front
          roles: ["detect", "record"]
    zones:
      yard:
        coordinates: 3840,652,3840,1570,2432,1559,887,968,1768,770,1174,588,945,625,959,474,1736,423,2473,413
      front_deck:
        coordinates: 2708,1573,2443,1603,772,934,1445,795,1442,692,1082,572,1007,488,904,340,0,482,0,2160,3840,2160,3840,1592

  ############################
  driveway_side:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/driveway_side
          roles: ["detect", "record"]
    zones:
      yard:
        coordinates: 0,2160,3840,2160,3840,1104,3139,827,1862,893,1845,523,1083,517,0,648

      driveway:
        coordinates: 2041,839,2546,788,2546,575,1999,559

  ############################
  crawlspace_yard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/crawlspace_yard
          roles: ["detect", "record"]
    zones:
      yard:
        coordinates: 975,755,669,599,0,534,0,2160,3840,2160,3816,856,3384,1061,2761,903,1924,832

  ############################
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/backyard
          roles: ["detect", "record"]
    zones:
      yard:
        coordinates: 0,2160,3840,2160,3840,1776,3183,1249,2702,921,1970,710,0,701

  ############################
  weather_station:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/weather_station
          roles: ["detect", "record"]
    detect:
      width: 1920
      height: 1080
    objects:
      track: []
    record:
      retain:
        days: 1
        mode: all
      events:
        objects: []

  ############################
  back:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/back
          roles: ["detect", "record"]
    zones:
      lake_deck:
        coordinates: 3840,2160,3840,190,3628,176,2638,0,1933,0,1617,0,1433,159,1389,251,1283,349,1269,510,1336,508,279,1255,226,2160
      yard:
        coordinates: 310,1269,884,803,1269,558,1280,332,1428,276,1411,201,1143,248,775,533,340,666,0,959,0,2160,418,2160

  ############################
  lake:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/lake
          roles: ["detect", "record"]
    zones:
      lake_deck:
        coordinates: 1620,1489,1849,1255,2315,1503,2276,2047,2064,2160,220,2160,0,2160,0,708,1104,521,1280,627,1255,878,1500,909

      yard:
        coordinates: 2256,1913,1693,1712,1514,1054,1274,996,1258,772,1570,759,2002,929,3804,1679,3840,2160,2122,2160
      dam:
        coordinates: 2065,608,3322,784,3342,603,2078,442

  ############################
  side_door:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/side_door
          roles: ["detect", "record"]
    zones:
      side_deck:
        coordinates: 2560,0,2097,0,2017,232,2168,431,2270,851,2106,864,2041,967,1753,976,1469,1019,43,1128,0,1920,2560,1920
      yard:
        coordinates: 2010,976,2101,794,1774,746,1292,777,892,825,535,913,130,1123,1021,1075
    detect:
      width: 2560
      height: 1920
```

### docker-compose file or Docker CLI command

```yaml
version: "3.8"
services:
  frigate:
    shm_size: 1g
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml
      #- ./config/labelmap.txt:/labelmap.txt:ro
      - media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    ports:
      - "5000:5000"
      - "8554:8554"
    environment:
      - "FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}"
      - "FRIGATE_MQTT_PASSWORD=${FRIGATE_MQTT_PASSWORD}"
      - "FRIGATE_ARTSP_PASSWORD=${FRIGATE_ARTSP_PASSWORD}"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "PLUS_API_KEY=${PLUS_API_KEY}"

volumes:
  media:
```

### Relevant log output

```shell
frigate_1  | 2023-10-15 14:35:04.613015785  Traceback (most recent call last):
frigate_1  | 2023-10-15 14:35:04.613104648    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate_1  | 2023-10-15 14:35:04.613106681      self.run()
frigate_1  | 2023-10-15 14:35:04.613115698    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate_1  | 2023-10-15 14:35:04.613117837      self._target(*self._args, **self._kwargs)
frigate_1  | 2023-10-15 14:35:04.613120029    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
frigate_1  | 2023-10-15 14:35:04.613123305      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate_1  | 2023-10-15 14:35:04.613139266    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
frigate_1  | 2023-10-15 14:35:04.613141470      self.detect_api = create_detector(detector_config)
frigate_1  | 2023-10-15 14:35:04.613143796    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
frigate_1  | 2023-10-15 14:35:04.613145861      return api(detector_config)
frigate_1  | 2023-10-15 14:35:04.613148183    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 39, in __init__
frigate_1  | 2023-10-15 14:35:04.613151421      self.interpreter = Interpreter(
frigate_1  | 2023-10-15 14:35:04.613161117    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
frigate_1  | 2023-10-15 14:35:04.613163154      _interpreter_wrapper.CreateWrapperFromFile(
frigate_1  | 2023-10-15 14:35:04.613184486  ValueError: Could not open 'plus://XXXX'.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
