### ISSUE TITLE
MQTT frigate/events sended without thumbnail.

### ISSUE THREAD

**Issue by ilevac** [blakeblackshear/frigate#820]
**Describe the bug**
First of all thank you for the very great project.
My issue is regarding MQTT.
When subscribed too /frigate/events, I do received all the events correctly, but there is never an attached thumbnail.
I've read all the documentation and there is no mention of other special config for this so I assumed it was a bug.

Also, to save processing on my side, I would like to change some info in the event payload. Do you have an idea where I should do that in the file? I'm using MQTTWarn to process the notification and I would like to have the field thumbnail renamed as "imageurl", 

**Version of frigate**
0.8.1-D376F6B

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: XXX.XXX.XXX.XXX
cameras:
  maindoor:
    ffmpeg:
      inputs:
        - path: rtsp://XXX.XXX.XXX.XXX:7447/iK2LWbPKaaGt3pY9
          roles:
            - detect
            - clips
            - record
    width: 1920
    height: 1080
    fps: 5
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 175
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
objects:
  track:
    - person
    - car
    - dog
```

**Frigate container logs**
```
No relevant log
```

**Frigate stats**
```json
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":20.06,"pid":566}},"maindoor":{"camera_fps":5.1,"capture_pid":42,"detection_fps":0.0,"pid":40,"process_fps":5.1,"skipped_fps":0.0},"service":{"uptime":601,"version":"0.8.1-d376f6b"}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://XXX.XXX.XXX.XXX:7447/iK2LWbPKaaGt3pY9':
  Metadata:
    title           : B4FBE49EEE06_0
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac, 48000 Hz, mono, fltp
    Stream #0:1: Video: h264, yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 15 fps, 25 tbr, 90k tbn, 30 tbc

```

**Computer Hardware**
 - OS: Ubuntu 18.04
 - Install method: Docker
 - Virtualization: Proxmox AMD64
 - Coral Version: USB
 - Network Setup: 10G Wired

**Camera Info:**
 - Manufacturer: Ubiquiti
 - Model: G3-Pro
 - Resolution: 1080P
 - FPS: 5
