### ISSUE TITLE
[Support]: Updating go2rtc for Frigating running in container on TrueNAS Scale

### ISSUE THREAD

**Issue by MrMewCakes** [blakeblackshear/frigate#8211]
### Describe the problem you are having

Hi noob here,

I'm trying to update my go2rtc to a later version. I've been trying to follow along with notes from this [ticket ](https://github.com/AlexxIT/go2rtc/issues/430)but have been unsuccessful so far.

I've downloaded go2rtc_linux_amd64, renamed it to go2rtc and placed it in frigate/config/
Then went to the shell in TrueNAS and ran the following:
![image](https://github.com/blakeblackshear/frigate/assets/12710776/4110e673-3897-4c3d-bc68-f7963afb6d43)

I've restarted the container a few times but go2rtc is still showing as v1.2.0

Would appreciate some direction on how to update this in TrueNAS scale :)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.90
  port: 1883
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb


ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    lounge_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password
      # - "ffmpeg:lounge_camera#audio=opus"
    living_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel2_ext.bcs&user=user&password=password
      # - "ffmpeg:living_camera#audio=opus"
    outside_garage_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel1_ext.bcs&user=user&password=password
      # - "ffmpeg:outside_garage_camera#audio=opus"
    outside_garage_camera_restream:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel1_ext.bcs&user=user&password=password
      - "ffmpeg:outside_garage_camera_restream#audio=opus"
    outside_entrance_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel4_ext.bcs&user=user&password=password
      # - "ffmpeg:outside_entrance_camera#audio=opus"
    outside_entrance_camera_restream:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel4_ext.bcs&user=user&password=password
      - "ffmpeg:outside_entrance_camera_restream#audio=opus"
    backyard_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel3_ext.bcs&user=user&password=password
      # - "ffmpeg:backyard_camera#audio=opus"
    shed_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel9_ext.bcs&user=user&password=password
    side_of_house_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel5_ext.bcs&user=user&password=password
      # - "ffmpeg:side_of_house_camera#audio=opus"
    garage_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel6_ext.bcs&user=user&password=password
    back_of_garage_camera:
      - http://192.168.1.52/flv?port=1935&app=bcs&stream=channel7_ext.bcs&user=user&password=password
      # - "ffmpeg:back_of_garage_camera#audio=opus"
  # webrtc:
  #   candidates:
  #     - 192.168.1.128:8555
  #     - stun:8555

cameras:
  outside_garage_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_garage_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/outside_garage_camera_restream?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - cat
      filters:
        car:
          mask:
            - 345,0,371,0,431,0,387,0,462,0,442,42,356,56,340,78,241,77,0,151,0,0
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: True
      events:
        required_zones:
          - driveway
          - mailbox
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - driveway
        - mailbox
    motion:
      mask:
        - 56,121,154,89,254,66,378,45,437,0,376,0,316,0,0,0,0,70,0,116,0,161
    zones:
      driveway:
        coordinates: 585,360,370,360,101,360,34,153,284,94,640,233
      mailbox:
        coordinates: 379,40,403,50,408,83,391,115,349,105,346,41
      garage_block2:
        coordinates: 640,360,333,360,535,161,640,196
    ui:
      order: 1

  outside_entrance_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_entrance_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/outside_entrance_camera_restream?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - cat
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: True
      events:
        retain:
          default: 5
          mode: active_objects
        required_zones:
          - entry_way
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - entry_way
    motion:
      mask:
        - 575,0,640,0,640,111,596,132,518,67,490,70,418,83,214,30,207,0
    ui:
      order: 2
    zones:
      entry_way:
        coordinates: 73,360,640,360,640,321,640,288,611,267,566,188,478,146,454,126,348,68,196,82,151,50,29,54,66,272
      garage_block1:
        coordinates: 201,259,194,86,296,77,371,236
  lounge_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lounge_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            #- record
    objects:
      track:
        - person
        - dog
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    # record:
    #   enabled: True
    snapshots:
      enabled: True
      bounding_box: True
    motion:
      mask:
        - 222,0,226,28,412,25,413,0
    ui:
      order: 3

  living_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            # - record
    objects:
      track:
        - person
        - dog
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    # record:
    # enabled: True
    snapshots:
      enabled: True
      bounding_box: True
    motion:
      mask:
        - 222,0,226,28,412,25,413,0
    zones:
      kitchen_zone:
        coordinates: 0,73,0,133,87,109,129,65,129,32
    ui:
      order: 4
  backyard_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            # - record
    objects:
      track:
        - person
        - dog
        - cat
      # filters:
      #   person:
      #     mask:
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    # record:
    #   enabled: True
    snapshots:
      enabled: True
      bounding_box: True
    motion:
      mask:
        - 421,0,414,29,221,24,222,0
    zones:
      backyard_zone:
        coordinates: 505,360,113,360,84,296,76,206,125,193,105,89,67,94,63,0,107,0,300,0,378,42,452,71,554,135,640,201,585,286
    ui:
      order: 5

  shed_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shed_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            # - record
    objects:
      track:
        - person
        - dog
        - cat
      # filters:
      #   person:
      #     mask:
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    # record:
    #   enabled: True
    snapshots:
      enabled: True
      bounding_box: True
    motion:
      mask:
        - 421,0,414,29,221,24,222,0
    zones:
      shed_zone:
        coordinates: 0,360,0,99,140,21,391,31,497,47,504,360
    ui:
      order: 6

  garage_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            # - record
    objects:
      track:
        - person
        - dog
        - cat
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    # record:
    #   enabled: True
    snapshots:
      enabled: True
      bounding_box: True
    motion:
      mask:
        - 222,0,226,28,412,25,413,0
    zones:
      garage_inside_zone:
        coordinates: 0,360,640,360,640,236,532,140,186,136,171,23,81,37,0,64,0,206
      garage_driveway_zone:
        coordinates: 247,44,430,44,521,125,191,129
    ui:
      order: 7

  back_of_garage_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_of_garage_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            # - record
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.8
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    # record:
    #   enabled: True
    snapshots:
      enabled: True
      bounding_box: True
    motion:
      mask:
        - 222,0,226,28,412,25,413,0
    zones:
      back_of_garage_zone:
        coordinates: 0,360,0,56,321,30,449,38,422,170,520,189,535,360
      back_of_garage_forward_zone:
        coordinates: 448,27,214,21,222,99,424,162
    ui:
      order: 8

  side_of_house_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_of_house_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            # - record
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        # cat:
        #   mask:
        # dog:
        #   mask:
        person:
          mask:
            - 287,0,640,0,640,112
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    # record:
    #   enabled: True
    snapshots:
      enabled: True
      bounding_box: True
    motion:
      mask:
        - 222,0,226,28,412,25,413,0
        - 306,0,640,0,640,117
    zones:
      side_of_house_zone:
        coordinates: 640,360,0,360,306,0,360,25,640,129
    ui:
      order: 11
```

### Relevant log output

```shell
2023-10-18 11:19:24.360576557  [INFO] Preparing go2rtc config...
2023-10-18 11:19:24.660911116  [INFO] Starting go2rtc...
2023-10-18 11:19:24.753374390  11:19:24.753 INF go2rtc version 1.2.0 linux/amd64
2023-10-18 11:19:24.753597142  11:19:24.753 INF [api] listen addr=:1984
2023-10-18 11:19:24.753859809  11:19:24.753 INF [rtsp] listen addr=:8554
2023-10-18 11:19:24.754174500  11:19:24.754 INF [srtp] listen addr=:8443
2023-10-18 11:19:24.754364913  11:19:24.754 INF [webrtc] listen addr=:8555
2023-10-18 11:19:34.366270383  [INFO] Starting go2rtc healthcheck service...
2023-10-18 11:23:01.672092262  11:23:01.671 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:01.672104197  11:23:01.671 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:01.814931147  11:23:01.814 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:01.814938927  11:23:01.814 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:01.856979529  11:23:01.856 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:01.857005021  11:23:01.856 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.114993115  11:23:02.114 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.115003343  11:23:02.114 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.214358228  11:23:02.214 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.214670971  11:23:02.214 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.374751051  11:23:02.374 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.374846889  11:23:02.374 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.560608227  11:23:02.560 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.560612555  11:23:02.560 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.574814561  11:23:02.574 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.574849755  11:23:02.574 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.676327209  11:23:02.676 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:02.676374161  11:23:02.676 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-18 11:23:05.852082466  11:23:05.851 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="Get \"http://192.168.1.52/flv?port=1935&app=bcs&stream=channel1_ext.bcs&user=hass&password=&user=user&password=password\": dial tcp 192.168.1.52:80: i/o timeout" url=http://192.168.1.52/flv?port=1935&app=bcs&stream=channel1_ext.bcs&user=hass&password=&user=user&password=password
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":512,"width":896}]}}]
```

### Operating system

TrueNAS Scale

### Install method

TrueNAS Scale App

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink AU-RLC-811A
