### ISSUE TITLE
[Support]: go2rtc cam links for two way audio

### ISSUE THREAD

**Issue by leaskovski** [blakeblackshear/frigate#8219]
### Describe the problem you are having

So my camera supports 2 way audio according to the go2rtc site, and I have added using the "special" protocol for my camera, i.e. "tapo://".

Before I moved to frigate, and had a go2rtc addon running on my home assistance, I could get links to work so I could leverage the two way audio that the camera supports.  Since then, I have dropped those individual camera integrations and just gone for a frigate container (running seperatly to my HASS system), with a Frigate HACS addon (https://github.com/blakeblackshear/frigate-hass-integration) to basically add frigate into my HASS.

The integration all works fine, and Frigate seems to all work fine as well.  No problems there.

Now I am playing with the system, I have added my camera using the tapo protocol, and it works, however I don't know how I can use the links provided by the integrated go2rtc of frigate, to get access to the "video+audio+microphone = two way audio from camera" page.  One assumes that this needs to use HTTPS to be able to get the mic to be requested from the page, so I can't even test the page via a local URL as that doesnt have HTTPs.

Whats the right way of doing this?

### Version

0.13.0-9185753

### Frigate config file

```yaml
mqtt:
  host: homeassistant.home.local
  user: ***
  password: ***

database:
  path: /db/frigate.db

go2rtc:
  streams:
    dog_cam: tapo://***@***
    #dog_cam: rtsp://***:***@***/stream1
    garden_cam: rtsp://***:***@***/Streaming/Channels/101/
    drive_cam: rtsp://***:***@***/Streaming/Channels/101/

detectors:
  cpu:
    type: cpu
    num_threads: 3

# Set these back to similar values for 0.12 because im running CPU detectors
motion:
  contour_area: 30
  frame_height: 50
  improve_contrast: False
  
cameras:
  dog_cam:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@***/stream1
          roles:
            - record
        - path: rtsp://***:***@***/stream2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 0,0,0,54,541,54,541,0
    onvif:
      host: ***
      port: 2020
      user: ***
      password: ***
  garden_cam:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@***/Streaming/Channels/101/
          roles:
            - record
        - path: rtsp://***:***@***/Streaming/Channels/102/
          roles:
            - detect
    detect:
      width: 640
      height: 360
    motion:
      mask:
        - 439,0,431,67,640,176,640,0
        - 0,0,210,0,210,32,0,32
  drive_cam:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@***/Streaming/Channels/101/
          roles:
            - record
        - path: rtsp://***:***@***/Streaming/Channels/101/
          roles:
            - detect
    detect:
      width: 640
      height: 360

objects:
  track:
    - person
    - dog 
    
record:
  enabled: True
  events:
    retain:
      default: 10
      mode: motion
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

NA
