### ISSUE TITLE
[Config Support]: audio in recordings

### ISSUE THREAD

**Issue by nmcrae85** [blakeblackshear/frigate#8223]
### Describe the problem you are having

Only thing I notice is that the audio doesnt play on any videos captured via the web interface (i.e. playback).

FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:
Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1440
FPS: 25/1

Audio:
Codec: AAC (Advanced Audio Coding)

No issues as such, but wanting to gain some best practice or advise based on my config. Am I doing anything as is stupid or not optimal to best practice setup?

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  host: 192.168.150.4
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: 123456789
  stats_interval: 300

model:
  path: plus://NOTPUBLISHED

record:
  enabled: True
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

audio:
  enabled: True
  listen:
    - speech
    - yell

objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

go2rtc:
  log:
    exec: trace
  streams:
    ANPR: 
      - "ffmpeg:http://192.168.150.18/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    backdoor: 
      - "ffmpeg:http://192.168.150.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    office: 
      - "ffmpeg:http://192.168.150.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    bell: 
      - "ffmpeg:http://192.168.150.15/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    shed:
      - "ffmpeg:http://192.168.150.12/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    gate:
      - "ffmpeg:http://192.168.150.13/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    kids:
      - "ffmpeg:http://192.168.150.14/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    kids2:
      - "ffmpeg:http://192.168.150.14/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=admin&password=123456789#video=copy#audio=copy#audio=aac"
    steps:
      - rtsp://admin:123456789@192.168.150.17/Preview_01_main    
    steps_sub:
      - rtsp://admin:123456789@192.168.150.17/Preview_01_sub
    steps_zoom:
     - rtsp://admin:123456789@192.168.150.17:554/Preview_01_autotrack
cameras:
  backdoor:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/backdoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - package
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - backdoor_patio
        - backdoor_whole_area
      crop: True
      height: 1440
      retain:
        default: 7
    zones:
      backdoor_patio:
        coordinates: 1280,720,838,290,441,213,0,487,0,720
        objects:
          - person
          - face
          - dog
          - cat
          - package
      backdoor_whole_area:
        coordinates: 0,720,1280,720,1280,234,984,145,620,77,313,79,111,112,0,179
        objects:
          - person
          - face
          - dog
          - cat
          - package
    motion:
      mask:
        - 906,46,900,0,379,0,378,52
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - backdoor_patio
          - backdoor_whole_area
        pre_capture: 5
        post_capture: 15

  office:
   ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/office?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
   detect:
      width: 1280
      height: 720
      fps: 15
   objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
   snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - office_in_area
        - office_whole_area
      crop: True
      height: 1440
      retain:
        default: 3
   zones:
      office_in_drive:
        coordinates: 0,720,1280,720,1280,493,998,566,732,536,426,396,285,236,156,205,113,179,55,176,59,218,0,179
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
      office_whole_area:
        coordinates: 0,720,1280,720,1280,319,1025,236,869,188,658,190,372,182,145,207,119,180,70,176,0,179
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
   motion:
      mask:
        - 905,0,900,50,379,53,373,0
   record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - office_in_drive
          - office_whole_area
        pre_capture: 5
        post_capture: 15  

  ANPR:    
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/ANPR?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - car
        - license_plate
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - ANPR_drive
        - ANPR_driveway
        - ANPR_whole_area
      crop: True
      height: 1440
      retain:
        default: 7
    zones:
      ANPR_drive:
        coordinates: 1280,720,1280,478,1009,463,350,555,0,533,0,720
        objects:
          - car
          - license_plate
      ANPR_driveway:
        coordinates: 207,320,307,290,428,250,461,273,431,316,592,389,946,484,300,574
        objects:
          - car
          - license_plate
      ANPR_whole_area:
        coordinates: 0,720,1280,720,1280,253,858,262,727,246,615,204,0,326
        objects:
          - car
          - license_plate
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
        - ANPR_drive
        - ANPR_driveway
        - ANPR_whole_area
        pre_capture: 5
        post_capture: 15

  bell:   
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/bell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 960
      fps: 15
    objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - bell_in_area
        - bell_whole_area
      crop: True
      height: 1920
      retain:
        default: 7
    zones:
      bell_in_area:
        coordinates: 538,424,894,405,1003,411,1068,422,1047,502,806,530,293,594,0,688,0,435,221,417
        objects:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
      bell_whole_area:
        coordinates: 695,720,980,720,1280,720,1066,425,1068,375,937,372,876,360,759,371,531,371,370,374,0,405,0,720
        objects:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - bell_in_area
          - bell_whole_area
        pre_capture: 5
        post_capture: 15
 
  shed:    
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/shed?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - shed_whole_area
      crop: True
      height: 1440
      retain:
        default: 3
    zones:
      shed_whole_area:
        coordinates: 1022,720,1280,374,1280,220,1209,0,613,0,642,28,500,82,0,312,0,720
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - shed_whole_area
        pre_capture: 5
        post_capture: 15
  
  gate:    
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/gate?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - gate_in_drive
        - gate_whole_area
      crop: True
      height: 1440
      retain:
        default: 3
    zones:
      gate_in_drive:
        coordinates: 904,268,1280,589,1280,720,0,720,0,573,376,571,594,529,692,465,714,420,726,344,701,290,767,248,754,198,909,211
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
      gate_whole_area:
        coordinates: 904,268,1280,589,1280,720,0,720,0,350,316,353,522,333,623,285,716,254,767,248,754,198,909,211
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - gate_in_area
          - gate_whole_area
        pre_capture: 5
        post_capture: 15

  kids:    
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/kids?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - kids_whole_area
      crop: True
      height: 1440
      retain:
        default: 3
    zones:
      kids_whole_area:
        coordinates: 695,720,980,720,1280,720,1066,425,1068,375,937,372,876,360,759,371,531,371,370,374,0,405,0,720
        objects:
          - person
          - face
          - dog
          - cat
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - kids_whole_area
        pre_capture: 5
        post_capture: 15

  kids2:    
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/kids2?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - kids_whole_area
      crop: True
      height: 1440
      retain:
        default: 3
    zones:
      kids_whole_area:
        coordinates: 695,720,396,497,399,409,516,378,825,427,1095,364,669,337,395,295,0,274,0,720
        objects:
          - person
          - face
          - dog
          - cat
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - kids_whole_area
        pre_capture: 5
        post_capture: 15

  steps:    
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/steps?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - face
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - kids_steps
        - kids_whole_area
      crop: True
      height: 1440
      retain:
        default: 3
    zones:
      kids_steps:
        coordinates: 703,200,1049,222,1047,276,703,244
        objects:
          - person
          - face
          - dog
          - cat
      kids_whole_area:
        coordinates: 695,720,980,720,1280,720,1066,425,1068,375,937,372,876,360,759,371,531,371,370,374,0,405,0,720
        objects:
          - person
          - face
          - dog
          - cat
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - kids_steps
          - kids_whole_area
        pre_capture: 5
        post_capture: 15

  steps_zoom:    
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/steps_zoom?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - kids_in_area
        - kids_whole_area
      crop: True
      height: 480
      retain:
        default: 3
    zones:
      kids_in_area:
        coordinates: 538,424,894,405,1003,411,1068,422,1047,502,806,530,293,594,0,688,0,435,221,417
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
      kids_whole_area:
        coordinates: 695,720,980,720,1280,720,1066,425,1068,375,937,372,876,360,759,371,531,371,370,374,0,405,0,720
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
    motion:
      mask:
        - 899,0,371,0,372,45,907,41
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - kids_in_area
          - kids_whole_area
        pre_capture: 5
        post_capture: 15

detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1280
  height: 1080
  quality: 1
  mode: objects
```

### Relevant log output

```shell
2023-10-18 17:05:51.431909485  [2023-10-18 17:05:51] frigate.app                    WARNING : The current SHM size of 128.0MB is too small, recommend increasing it to at least 154.99999999999997MB.
2023-10-18 17:05:53.283333593  [2023-10-18 17:05:50] detector.coral                 INFO    : Starting detection process: 307
2023-10-18 17:05:53.283393007  [2023-10-18 17:05:50] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-18 17:05:53.286393888  [2023-10-18 17:05:53] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB
