### ISSUE TITLE
Failed to create tmpfs, error code: 8192

### ISSUE THREAD

**Issue by Eeeeeediot** [blakeblackshear/frigate#823]
**Describe the bug**
tmpfs is not created resulting in no clips.

**Version of frigate**
0.8.3-d771726. I use HassOS and I think the issue started with 1.10/.1.11

**Config file**
Include your full config file wrapped in triple back ticks.
```
detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3
mqtt:
  host: 192.168.0.200
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: Stephen
  password: Starwar5123
  stats_interval: 60
ffmpeg:
  global_args: '-hide_banner -loglevel fatal'
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m
  input_args: 
    - '-avoid_negative_ts'
    - make_zero
    - '-fflags'
    - nobuffer
    - '-flags'
    - low_delay
    - '-strict'
    - experimental
    - '-fflags'
    - +genpts+discardcorrupt
    - '-use_wallclock_as_timestamps'
    - '1'
  output_args:
    detect: '-f rawvideo -pix_fmt yuv420p'
    record: >-
      -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    clips: >-
      -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    rtmp: '-c copy -f flv'

logger:
  default: info
  logs:
    frigate.mqtt: error
database:
  path: /media/frigate/clips/frigate.db
model:
  height: 320
  width: 320
snapshots:
  retain:
    default: 7
    objects:
      person: 7
      cat: 3
      dog: 3
clips:
  max_seconds: 300
  tmpfs_cache_size: 512m
  retain:
    default: 7
    objects:
      person: 7
      cat: 3
      dog: 3
motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180
detect:
  max_disappeared: 20

# Global Object Detection
# objects:
#   track:
#     - person
#     - cat
#     - dog
#   filters:
#     person:
#       min_area: 1
#       max_area: 24000000
#       min_score: 0.5
#       threshold: 0.7
#     cat:
#       min_area: 1
#       max_area: 24000000
#       min_score: 0.4
#       threshold: 0.6
#     dog:
#       min_area: 1
#       max_area: 24000000
#       min_score: 0.4
#       threshold: 0.6

##############
# Cameras
##############
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtmp://192.168.0.201/bcs/channel0_sub.bcs?channel=0&stream=0&user=Stephen&password=Starwar5123'
          roles:
            - detect
            - rtmp
            - record
        - path: 'rtmp://192.168.0.201/bcs/channel0_main.bcs?channel=0&stream=0&user=Stephen&password=Starwar5123'
          roles:
            - clips
    width: 640
    height: 480
    fps: 7
    # motion:
    #   mask: '0,0,0,168,232,94,290,110,341,125,380,129,372,0'
    zones:
      zone_front:
        coordinates: 640,306,640,480,0,480,0,187,231,110,386,182,385,79,640,80
    best_image_timeout: 60
    detect:
      enabled: true
      # max_disappeared: 15
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain_days: 2
    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      # height: 175
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_area: 500
          max_area: 24000000
          min_score: 0.5
          threshold: 0.7
        cat:
          min_area: 1
          max_area: 20000
          min_score: 0.3
          threshold: 0.5
          mask:
            - 393,480,640,480,640,0,374,0
        dog:
          min_area: 1
          max_area: 20000
          min_score: 0.3
          threshold: 0.5
          mask:
            - 393,480,640,480,640,0,374,0

  garden:
    ffmpeg:
      inputs:
        - path: 'rtmp://192.168.0.202/bcs/channel0_sub.bcs?channel=0&stream=0&user=Stephen&password=Starwar5123'
          roles:
            - detect
            - rtmp
            - record
        - path: 'rtmp://192.168.0.202/bcs/channel0_main.bcs?channel=0&stream=0&user=Stephen&password=Starwar5123'
          roles:
            - clips
    width: 640
    height: 480
    fps: 7
    zones:
      zone_back:
        coordinates: 586,333,498,183,470,175,440,112,372,69,294,41,240,121,188,113,192,82,140,70,74,85,24,250,21,408,0,480,640,480
    motion:
      mask: '640,325,622,289,543,162,540,143,496,80,469,75,317,0,640,0'
    best_image_timeout: 60
    detect:
      enabled: true
      # max_disappeared: 15
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain_days: 2
    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 175
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_area: 5000
          max_area: 24000000
          min_score: 0.5
          threshold: 0.7
        cat:
          min_area: 1
          max_area: 7000
          min_score: 0.3
          threshold: 0.5
          mask:
            - 312,0,250,104,195,89,203,52,149,38,134,74,72,66,81,29,99,0
        dog:
          min_area: 1
          max_area: 7000
          min_score: 0.3
          threshold: 0.5
          mask:
            - 312,0,250,104,195,89,203,52,149,38,134,74,72,66,81,29,99,0

```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Creating tmpfs of size 512m
mount: /tmp/cache: cannot mount tmpfs read-only.
frigate.app                    ERROR   : Failed to create tmpfs, error code: 8192
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
detector.coral                 INFO    : Starting detection process: 38
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Camera processor started for driveway: 41
frigate.app                    INFO    : Camera processor started for garden: 42
frigate.app                    INFO    : Capture process started for driveway: 44
frigate.app                    INFO    : Capture process started for garden: 46
frigate.edgetpu                INFO    : TPU found
```

**Frigate stats**
```
{
  "detection_fps": 0.0, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 13.7, 
      "pid": 38
    }
  }, 
  "driveway": {
    "camera_fps": 6.9, 
    "capture_pid": 44, 
    "detection_fps": 0.0, 
    "pid": 41, 
    "process_fps": 6.8, 
    "skipped_fps": 0.0
  }, 
  "garden": {
    "camera_fps": 7.0, 
    "capture_pid": 46, 
    "detection_fps": 0.0, 
    "pid": 42, 
    "process_fps": 7.0, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1760.3, 
        "mount_type": "tmpfs", 
        "total": 1762.2, 
        "used": 1.9
      }, 
      "/media/frigate/clips": {
        "free": 11669.7, 
        "mount_type": "ext4", 
        "total": 62108.0, 
        "used": 47265.0
      }, 
      "/media/frigate/recordings": {
        "free": 11669.7, 
        "mount_type": "ext4", 
        "total": 62108.0, 
        "used": 47265.0
      }, 
      "/tmp/cache": {
        "free": 11669.7, 
        "mount_type": "overlay", 
        "total": 62108.0, 
        "used": 47265.0
      }
    }, 
    "uptime": 477, 
    "version": "0.8.3-d771726"
  }
}
```

**FFprobe from your camera**

not sur ehow to do this
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
RPI4 HassOS

**Camera Info:**
ReoLink 520's

**Additional context**
