### ISSUE TITLE
[Config Support]: Detection outside of zone

### ISSUE THREAD

**Issue by ptruman** [blakeblackshear/frigate#8234]
### Describe the problem you are having

People are being detected (and snapshotted):

a) outside of areas I've defined them to be detectedi n
b) inside areas I've "masked off"

Additionally, checking videos, there doesn't seem to be any obvious detection within the defined zone...

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 10.74.90.131

detectors:
  coral1:
    type: edgetpu
#    device: usb:0

cameras:
  Driveway:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://redacted:redacted@127.0.0.1:8554/driveway_cam?video&audio
          hwaccel_args: preset-nvidia-h264
          roles:
            - record
            - detect
#        - path: rtsp://redacted:redacted@127.0.0.1:8554/driveway_cam_sub?video&audio
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
    detect:
      width: 2592
      height: 1944 
      fps: 15
    motion:
      mask:
        - 2070,645,2592,1368,2592,535,2592,0,1465,0,1653,187
        - 0,0,1194,0,1145,109,1002,225,541,784,114,1591,0,1523
    zones:
      Drive:
        coordinates: 1029,363,740,709,333,1682,1020,1944,2376,1944,2516,1775,2010,891,1636,355
        objects:
            - person
      Approach:
        coordinates: 1182,0,1416,0,1627,339,1045,345
        objects:
            - car

go2rtc:
  rtsp:
    username: "redacted"
    password: "redacted"
  streams:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    driveway_cam:
      - rtsp://viewer:Fr1g4t3@10.74.60.4:554/stream0
        "ffmpeg:rtsp_cam#audio=aac"
    driveway_cam_sub:
      - rtsp://viewer:Fr1g4t3@10.74.60.4:554/stream1
        "ffmpeg:rtsp_cam#audio=aac"

live:

      height: 1944
      quality: 8
      stream_name: driveway_cam


ffmpeg:
  hwaccel_args: preset-nvidia-h264

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
        - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones:
      - Drive
      - Approach
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 7
        car : 7

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 1944
    # 576
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones:
    - Drive
    - Approach
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7
    # Optional: Per object retention days
    objects:
      person: 7
```

### Relevant log output

```shell
None shown
```

### Frigate stats

```json
{"Driveway":{"camera_fps":15.0,"capture_pid":439,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":447,"pid":437,"process_fps":15.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"2.0","mem":"3.0"},"11584":{"cpu":"0.0","mem":"0.0"},"116":{"cpu":"0.0","mem":"0.1"},"11601":{"cpu":"0.0","mem":"0.0"},"11605":{"cpu":"0.0","mem":"0.0"},"133":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.2"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.2"},"137":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"14":{"cpu":"0.0","mem":"0.0"},"147":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"168":{"cpu":"0.0","mem":"0.0"},"23":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"425":{"cpu":"0.0","mem":"0.5"},"431":{"cpu":"0.3","mem":"0.1"},"432":{"cpu":"0.0","mem":"0.7"},"434":{"cpu":"1.7","mem":"0.6"},"437":{"cpu":"2.0","mem":"0.9"},"439":{"cpu":"16.3","mem":"0.6"},"440":{"cpu":"0.0","mem":"0.1"},"446":{"cpu":"0.0","mem":"0.3"},"447":{"cpu":"36.3","mem":"5.4"},"78":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"91":{"cpu":"5.0","mem":"0.1"},"MiB":{"cpu":"9852.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"1.33,"}},"detection_fps":0.2,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":8.81,"pid":432}},"gpu_usages":{"Quadro P1000":{"gpu":"1 %","mem":"7.0 %"}},"service":{"last_updated":1697714887,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":259.8,"mount_type":"tmpfs","total":268.4,"used":8.7},"/media/frigate/clips":{"free":1051503.7,"mount_type":"ext4","total":1967714.0,"used":916193.5},"/media/frigate/recordings":{"free":1051503.7,"mount_type":"ext4","total":1967714.0,"used":916193.5},"/tmp/cache":{"free":1051503.7,"mount_type":"overlay","total":1967714.0,"used":916193.5}},"temperatures":{},"uptime":14919,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB
