### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by DC651F82053AD314** [blakeblackshear/frigate#8237]
### Describe the problem you are having

Hello!

The main issue I'm seeing in the Portainer/Docker logs for Frigate when trying to run the Frigate docker-compose (via the 'stack' method) is: "unable to open database file".  At least I _think_ that's the main issue.

I'm brand new to frigate and Coral/AI.  I just bought a Coral USB and I'm trying to get it setup for the first time.  I installed the drivers for the Coral device, the computer is running Ubuntu 22.04.3 LTS 64-bit

I'm running an SV3C POE PTZ 4k IP camera on my local network and trying to connect to it on the Ubuntu computer (with frigate) via the RTSP stream. The computer is a [Protectli VP2410](https://protectli.com/product/vp2410/), which should have plenty of power for capturing the 4k stream, and all gigabit connections with an Intel Celeron quad core 2 GHz (Burst up to 2.7 GHz).

**Here's the IP camera output settings**:
Video Format: 60Hz
Video Coding: H265 main profile
Resolution: 2560 X 1920
Bit Rate: 2048
Maximum Frame Rate: 30 FPS
Key frame interval: 100
Bit rate control: VBR

Docker compose version:  2.20.2

When I go to the Frigate URL in a web browser after starting the container in Docker/Portainer I see the Frigate logo in the upper lefthand corner and the blue circle just keeps on spinning, here's a screen shot:
![image](https://github.com/blakeblackshear/frigate/assets/127766978/a24445cf-bef1-40d2-8bb4-927144f7328e)

The logs seem to show the same loop, over and over while the system tries to startup but can't and the only real output that looks to be the culprit is that "unable to open database file" line.

### Version

ghcr.io/blakeblackshear/frigate:stable@sha256:dac652c4cf36785c91195cdba2d45ad2b320ae417ca221fcff91b4817c34d4dd (new install as of today - the Web UI won't load, so I can't see the 'Debug' page)

### Frigate config file

```yaml
Here is the frigate config.yml file contents:

cameras:
  truckcam1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.31:554/11
          roles:
            - detect
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
      fps: 30
 # truckcam2:
 #   ffmpeg:
 #     inputs:
 #       - path: rtsp://cameraIP:554/s0
 #         roles:
 #           - detect
 #           - rtmp
 #  detect:
 #     width: 1920 # <---- update for your camera's resolution
 #     height: 1080 # <---- update for your camera's resolution
 #     fps: 30
    motion:
 #     mask:
 #       - 0,0,1920,0,1920,393,297,241,314,464,0,541


# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /home/jmc-vp2410-001/Documents/frigate/database/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: usb
#  coral2:
#    type: edgetpu
#    device: pci:1

objects:
  track:
    - person
    - dog
    - cat
    - car
    - bus

snapshots:
  enabled: True
  timestamp: true
  bounding_box: true
  retain: 
    default: 30
mqtt:
  host: 192.168.1.32

ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p
  output_args:
     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects
    objects:
      - person
      - cat
      - dog
      - car
      - bus

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
2023-10-19 14:36:15.751224571  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-10-19 14:36:15.762409109  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-10-19 14:36:15.827392991  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-10-19 14:36:15.830960494  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-10-19 14:36:15.837552031  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2023-10-19 14:36:45.988455859  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-10-19 14:36:45.991473550  [INFO] Starting Frigate...
2023-10-19 14:36:45.994742536  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-10-19 14:36:46.311608316  [INFO] Starting go2rtc...
2023-10-19 14:36:46.488548729  14:36:46.488 INF go2rtc version 1.2.0 linux/amd64
2023-10-19 14:36:46.488967575  14:36:46.488 INF [api] listen addr=:1984
2023-10-19 14:36:46.489266641  14:36:46.489 INF [rtsp] listen addr=:8554
2023-10-19 14:36:46.489580849  14:36:46.489 INF [srtp] listen addr=:8443
2023-10-19 14:36:46.489859762  14:36:46.489 INF [webrtc] listen addr=:8555
2023-10-19 14:36:47.552313119  [2023-10-19 14:36:47] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-19 14:36:47.591110008  unable to open database file
2023-10-19 14:36:47.591342909  [2023-10-19 14:36:47] peewee_migrate                 INFO    : Starting migrations
2023-10-19 14:36:48.876516524  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-10-19 14:36:48.888339280  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-10-19 14:36:48.950729510  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-10-19 14:36:48.954647085  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-10-19 14:36:48.960387544  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I'm not using the MQTT server, as this is a standalone setup, but the docker-compose file wouldn't run without it, so I installed mosquitto on the ubuntu machine running Frigate and edited the mosquitto.conf by just adding this line: 
`allow_anonymous true` then in the Frigate config file, I have `host: 192.168.1.32` which is the IP address of the same Ubuntu machine I'm trying to run Frigate on.

**Here is the Frigate docker-compose file content** (I sanitized the password to something similar but different):

version: "3.9"
services:
  frigate:
    container_name: frigate
     privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/bus/usb:/dev/bus/usb
      #- /dev/apex_0:/dev/apex_0
      #- /dev/apex_1:/dev/apex_1
      #- /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/jmc-vp2410-001/Documents/frigate/config/frigate.yml:/config/config.yml:ro
      - /ssd-1tb/frigate/media/clips:/media/frigate/clips
      - /ssd-1tb/frigate/media/recordings:/media/frigate/recordings
      - /home/jmc-vp2410-001/Documents/frigate/database:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      #- "1935:1935" # RTMP feeds (deprecated)
      - "8554:8554" # RTSP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "Ee0DB5XyD36"
    #security_opt:
    #  - no-new-privileges:true
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.frigate.entrypoints=http"
    #  - "traefik.http.routers.frigate.rule=Host(`frigate.jimsgarage.co.uk`)"
    #  - "traefik.http.middlewares.frigate-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.frigate.middlewares=frigate-https-redirect"
    #  - "traefik.http.routers.frigate-secure.entrypoints=https"
    #  - "traefik.http.routers.frigate-secure.rule=Host(`frigate.jimsgarage.co.uk`)"
    #  - "traefik.http.routers.frigate-secure.tls=true"
    #  - "traefik.http.routers.frigate-secure.service=frigate"
    #  - "traefik.http.services.frigate.loadbalancer.server.port=5000"
    #  - "traefik.docker.network=proxy"

#proxy:
#  external: true
