### ISSUE TITLE
[Config Support]: MQTT snapshot timestamp frequently wrong

### ISSUE THREAD

**Issue by boswelja** [blakeblackshear/frigate#8241]
### Describe the problem you are having

I have my Frigate integrated into HomeAssistant, where I display the last person and last car seen alongside the camera feed. Unfortunately the timestamps are often wrong, they seem to be UTC sometimes, rather than my local timezone.
This doesn't happen 100% of the time, but it seems to be getting more frequent.

Here is a snippet from the snapshot:
![image](https://github.com/blakeblackshear/frigate/assets/15526339/5898ab11-5624-459e-8be1-815babef8671)

And according to HomeAssistant statistics, the event occurred at 9:31AM
![image](https://github.com/blakeblackshear/frigate/assets/15526339/d2067aed-1abe-4c9d-ac13-b29decd47a87)

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: <mqtt ip>
  port: <mqtt port>

detectors:
  cpu1:
    type: cpu
    num_threads: 10

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    driveway:
      - rtsp://<username>:<password>@<camera ip>/stream1
      - "ffmpeg:driveway#audio=aac"

cameras:
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
    motion:
      mask:
        - 1280,0,0,0,0,122,157,101,163,59,603,59,599,167,738,173,849,183,979,202,1280,306
    zones:
      gateway:
        coordinates: 745,177,615,191,746,223,846,187
objects:
  track:
    - person
    - car
  filters:
    person:
      min_score: 0.7
    car:
      min_score: 0.7

birdseye:
  enabled: False

record:
  enabled: True
  events:
    retain:
      default: 5
```

### Relevant log output

```shell
Nothing of note occurred at this time
```

### Frigate stats

```json
{"cpu_usages":{"1":{"cpu":"0.0","mem":"0.0"},"1010":{"cpu":"0.0","mem":"0.1"},"103":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"2.0","mem":"3.0"},"1055":{"cpu":"0.0","mem":"0.1"},"1086":{"cpu":"0.0","mem":"0.1"},"1108":{"cpu":"0.0","mem":"0.1"},"1128":{"cpu":"0.0","mem":"0.1"},"115":{"cpu":"0.0","mem":"0.1"},"1170":{"cpu":"0.0","mem":"0.1"},"1224":{"cpu":"0.0","mem":"0.1"},"1269":{"cpu":"0.0","mem":"0.1"},"1303":{"cpu":"0.0","mem":"0.1"},"1342":{"cpu":"0.0","mem":"0.1"},"1375":{"cpu":"0.0","mem":"0.1"},"1392":{"cpu":"0.0","mem":"0.2"},"140":{"cpu":"0.0","mem":"0.1"},"1408":{"cpu":"0.0","mem":"0.1"},"141":{"cpu":"0.0","mem":"0.1"},"142":{"cpu":"0.0","mem":"0.1"},"1447":{"cpu":"0.0","mem":"0.1"},"146":{"cpu":"0.0","mem":"0.1"},"1489":{"cpu":"0.0","mem":"0.1"},"1527":{"cpu":"0.0","mem":"0.1"},"1567":{"cpu":"0.0","mem":"0.1"},"1594":{"cpu":"0.0","mem":"0.1"},"161":{"cpu":"0.0","mem":"0.1"},"1629":{"cpu":"0.0","mem":"0.1"},"1675":{"cpu":"0.0","mem":"0.1"},"1714":{"cpu":"0.0","mem":"0.1"},"1742":{"cpu":"0.0","mem":"0.1"},"1766":{"cpu":"0.0","mem":"0.1"},"1806":{"cpu":"0.0","mem":"0.1"},"184":{"cpu":"0.0","mem":"0.1"},"1853":{"cpu":"0.0","mem":"0.1"},"1877":{"cpu":"0.0","mem":"0.1"},"1911":{"cpu":"0.0","mem":"0.1"},"202892":{"cpu":"5.0","mem":"2.3"},"21":{"cpu":"0.0","mem":"0.0"},"210":{"cpu":"0.0","mem":"0.1"},"2162":{"cpu":"0.0","mem":"1.0"},"2168":{"cpu":"0.3","mem":"0.1"},"2169":{"cpu":"0.0","mem":"1.2"},"2171":{"cpu":"0.3","mem":"1.1"},"2174":{"cpu":"0.0","mem":"0.2"},"2175":{"cpu":"1.0","mem":"1.4"},"2176":{"cpu":"2.3","mem":"1.2"},"24":{"cpu":"0.0","mem":"0.0"},"244":{"cpu":"0.0","mem":"0.1"},"291":{"cpu":"0.0","mem":"0.1"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"33":{"cpu":"0.0","mem":"0.0"},"34":{"cpu":"0.0","mem":"0.0"},"345":{"cpu":"0.0","mem":"0.1"},"349523":{"cpu":"0.0","mem":"0.0"},"349547":{"cpu":"0.0","mem":"0.0"},"349552":{"cpu":"0.0","mem":"0.0"},"35":{"cpu":"0.0","mem":"0.0"},"36":{"cpu":"0.0","mem":"0.0"},"37":{"cpu":"0.0","mem":"0.0"},"38":{"cpu":"0.0","mem":"0.0"},"398":{"cpu":"0.0","mem":"0.1"},"439":{"cpu":"0.0","mem":"0.1"},"466":{"cpu":"0.0","mem":"0.1"},"47":{"cpu":"0.0","mem":"0.0"},"48":{"cpu":"0.0","mem":"0.0"},"503":{"cpu":"0.0","mem":"0.1"},"539":{"cpu":"0.0","mem":"0.1"},"573":{"cpu":"0.0","mem":"0.1"},"609":{"cpu":"0.0","mem":"0.1"},"642":{"cpu":"0.0","mem":"0.1"},"674":{"cpu":"0.0","mem":"0.1"},"706":{"cpu":"0.0","mem":"0.1"},"745":{"cpu":"0.0","mem":"0.1"},"772":{"cpu":"0.0","mem":"0.1"},"793":{"cpu":"0.0","mem":"0.1"},"815":{"cpu":"0.0","mem":"0.1"},"838":{"cpu":"0.0","mem":"0.1"},"86":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"0.0","mem":"0.0"},"874":{"cpu":"0.0","mem":"0.1"},"88":{"cpu":"0.0","mem":"0.0"},"910":{"cpu":"0.0","mem":"0.1"},"938":{"cpu":"0.0","mem":"0.1"},"95":{"cpu":"1.7","mem":"0.4"},"969":{"cpu":"0.0","mem":"0.1"},"Tasks:":{"cpu":"stopped,","mem":"0.0"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":68.45,"pid":2169}},"driveway":{"camera_fps":5.0,"capture_pid":2176,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":202892,"pid":2175,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"Tesla P4":{"gpu":"0 %","mem":"2.6 %"}},"service":{"last_updated":1697752601,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":126.3,"mount_type":"tmpfs","total":134.2,"used":7.9},"/media/frigate/clips":{"free":565852.9,"mount_type":"zfs","total":566687.4,"used":834.5},"/media/frigate/recordings":{"free":565852.9,"mount_type":"zfs","total":566687.4,"used":834.5},"/tmp/cache":{"free":1073.5,"mount_type":"tmpfs","total":1073.7,"used":0.3}},"temperatures":{},"uptime":325625,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

Running both Frigate, HomeAssistant and Mosquitto as TrueNAS Scale apps.
Note inference still happens on CPU. Video transcode is accelerated by a Tesla P4, but I get the same timestamp issue with no hardware accel.
