### ISSUE TITLE
[Support]: False positives. Incorrect person detection

### ISSUE THREAD

**Issue by honeyfairy** [blakeblackshear/frigate#8243]
### Describe the problem you are having

I'm monitoring a construction parking area. We need to be notified when any person enters the area where the construction vehicles are parked. However we receive a multiple false positives daily as Frigate detects one of the vehicles as a person. How can we mitigate this?

Here is a screenshot from the debug screen:

![camperson](https://github.com/blakeblackshear/frigate/assets/17691989/17f42baf-9711-486a-8323-c65048351dd9)

### Version

Frigate (0.12.1-367d724)

### Frigate config file

```yaml
mqtt:
  host: [REDACTED]
  user: [REDACTED]
  password: [REDACTED]

detectors:
  cpu1:
    type: cpu
    num_threads: 3

  cpu2:
    type: cpu
    num_threads: 3

cameras:
  mpcam_fullview:
    ffmpeg:
      inputs:
        - path: [REDACTED]
          roles:
            - detect
            - rtmp
            - record
            - clips

    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
         interval: 0
         threshold: 50

    zones:
      entrance:
        coordinates: [REDACTED]
        objects:
          - car
          - person
      yard:
        coordinates: [REDACTED]
        objects:
          - person

    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - entrance
          - yard
        retain:
          default: 14
          mode: active_objects

    snapshots:
       required_zones:
         - entrance
         - yard

    objects:
      track:
        - person
        - car

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
Let me know if required.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision
