### ISSUE TITLE
[Config Support]: MSE not showing, only jsmpeg

### ISSUE THREAD

**Issue by sebastian-tischer** [blakeblackshear/frigate#8256]
### Describe the problem you are having

Hi Frigate-team,

after playing around for weeks, I think that I found a quite good config - besides some hardware issues that will be fixed soon.

Right now, I am not getting my head around the issue, that even though go2rtc is configured, it only show jsmpeg instead of MSE & webrtc.

Am I doing something wrong?

Best regards
Sebastian

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  #host: 192.168.2.109
  host: core-mosquitto
  port: 1883
  user: hass-mqtt
  password: mqtt
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-rpi-64-h264
motion:
  threshold: 15
  improve_contrast: True
detect:
  enabled: True
  #width: 1280
  #height: 720
  width: 640
  height: 360
  fps: 5
objects:
  filters:
    person:
      min_score: 0.7
      threshold: 0.7
  track:
    - person
#birdseye:
#  enabled: True
#  mode: continuous
#      restream: true
record:
  enabled: True
  expire_interval: 60
  events:
    pre_capture: 15
    post_capture: 15
    objects:
      - person
    retain:
      default: 5
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True
  crop: False
  retain:
    default: 5
    objects:
      person: 15

cameras:
  Eingang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang-Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Eingang-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
  Garten:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garten-Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garten-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,101,0,52,174,31,204,26,199,75
    objects:
      filters:
        person:
          mask:
            - 0,108,204,74,202,21,0,56
  Einfahrt:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Einfahrt-Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Einfahrt-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 108,131,140,126,129,75,95,83
    objects:
      filters:
        person:
          mask:
            - 106,132,138,128,130,84,96,87
  Garage:
    ffmpeg: 
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage-Record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage-Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
#      Wohnzimmer:
#        ffmpeg:
#          output_args:
#            record: preset-record-generic-audio-copy
#          inputs:
#            - path: rtsp://127.0.0.1:8554/Wohnzimmer-Record
#              input_args: preset-rtsp-restream
#              roles:
#                - record
#            - path: rtsp://127.0.0.1:8554/Wohnzimmer-Detect
#              input_args: preset-rtsp-restream
#              roles:
#                - detect
go2rtc:
  streams:
    Eingang-Detect:
      - rtsp://user:pw@192.168.2.127/livestream/13
      - "ffmpeg:Eingang-Detect#video=h264#audio=aac"
    Eingang-Record:
      - rtsp://user:pw@192.168.2.127/livestream/11
      - "ffmpeg:Eingang-Record#video=h264#audio=aac"
    Garten-Detect:
      - rtsp://user:pw@192.168.2.128/livestream/13
      - "ffmpeg:Garten-Detect#video=h264#audio=aac"
    Garten-Record:
      - rtsp://user:pw@192.168.2.128/livestream/11
      - "ffmpeg:Garten-Record#video=h264#audio=aac"
    Einfahrt-Detect:
      - rtsp://user:pw@192.168.2.141/livestream/13
      - "ffmpeg:Einfahrt-Detect#video=h264#audio=aac"
    Einfahrt-Record:
      - rtsp://user:pw@192.168.2.141/livestream/11
      - "ffmpeg:Einfahrt-Record#video=h264#audio=aac"
    Garage-Detect:
      - rtsp://operator-kamera:McN9foGXqtK2xPi@192.168.2.147:554/stream2
      - "ffmpeg:Garage-Detect#video=h264#audio=aac"
    Garage-Record:
      - rtsp://operator-kamera:McN9foGXqtK2xPi@192.168.2.147:554/stream1
      - "ffmpeg:Garage-Record#video=h264#audio=aac"
#        Wohnzimmer-Detect:
#          - rtsp://operator-kamera:McN9foGXqtK2xPi@192.168.2.148:554/stream2
#          - "ffmpeg:Wohnzimmer-Detect#video=h264#audio=aac"
#        Wohnzimmer-Record:
#          - rtsp://operator-kamera:McN9foGXqtK2xPi@192.168.2.148:554/stream1
#          - "ffmpeg:Wohnzimmer-Record#video=h264#audio=aac"
```

### Relevant log output

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
