### ISSUE TITLE
[Config Support]: Issue with notifications (ANPR alert)

### ISSUE THREAD

**Issue by nmcrae85** [blakeblackshear/frigate#8257]
### Describe the problem you are having

Im using the blueprint that @NickM-27 put together. But im repurposing for a different usecase. Im getting a Error rendering data template: UndefinedError: 'dict object' has no attribute 'trigger' 

### Version

 0.13.0-9185753

### Frigate config file

```yaml
alias: Advanced Process Detected Plates
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      after_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
      before_zones: "{{ trigger.payload_json['before']['entered_zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
      score: "{{ trigger.payload_json['after']['score'] }}"
      time_clip_start: "{{ trigger.payload_json['after']['start_time'] - 10.0 }}"
    payload: ANPR
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['type'] == 'new' }}"
      - condition: template
        value_template: "{{ before_zones | length == 0 }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['entered_zones']|length > 0 }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] == 'car' }}"
  - condition: template
    value_template: >-
      {{ ['ANPR_drive', 'ANPR_driveway'] | select('in', after_zones) | list |
      length > 0 }}
    enabled: true
  - condition: template
    value_template: >-
      {{ trigger.payload_json['after']['attributes'].get('license_plate') is not
      none }}
    enabled: false
  - condition: template
    value_template: "{{ id is not none and id != 'unavailable' }}"
action:
  - wait_template: >-
      {{ state_attr('image_processing.platerecognizer_tester', 'watched_plates')
      is not none }}
    timeout: "00:01:00"
    enabled: true
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ state_attr('image_processing.platerecognizer_tester',
              'watched_plates').values() | select('equalto', true) | list |
              length > 0 }}
        sequence:
          - service: script.1696850174003
            data:
              id: "{{ id }}"
              title: >-
                {% if (wait.trigger.payload_json["after"]["sub_label"] != None)
                -%} {{ (wait.trigger.payload_json["after"]["sub_label"]) | title
                }} {%- else -%} {{ label | replace("_", " ") | title }} {%-
                endif %} was detected in the {{ after_zones[0] | replace("_", "
                ") | title }}
              message: Detected with {{ int(score | round(2) * 100) }}% confidence
              notifTag: "{{ id }}"
              notifIcon: mdi:doorbell-video
              group: >-
                frigate-notification-{{ trigger.payload_json["after"]["camera"]
                }}
              importance: default
              image: /api/frigate/notifications/{{ id }}/snapshot.jpg
              video: >-
                https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
              clickAction: >-
                https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
      - conditions:
          - condition: template
            value_template: >-
              {{ state_attr('image_processing.platerecognizer_tester',
              'watched_plates').values() | select('equalto', false) | list |
              length > 0 }}
        sequence:
          - service: script.1696850174003
            data:
              id: "{{ id }}"
              title: Hi
              message: Detected with {{ int(score | round(2) * 100) }}% confidence
              notifTag: "{{ id }}"
              notifIcon: mdi:doorbell-video
              group: >-
                frigate-notification-{{ trigger.payload_json["after"]["camera"]
                }}
              importance: default
              image: /api/frigate/notifications/{{ id }}/snapshot.jpg
              video: >-
                https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
              clickAction: >-
                https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4

service: notify.mobile_app_nm
data:
  message: "{{ message }}"
  title: "{{ title }}"
  data:
    channel: "{{ channel }}"
    clickAction: "{{ video }}"
    tag: "{{ notifTag }}"
    group: "{{ group }}"
    image: >-
      {% if (importance == "default" and video != null) -%} {{ null }} {%- else
      -%} {{ image }} {%- endif %}
    video: >-
      {% if (importance == "default" and video != null) -%} {{ video }} {%- else
      -%} {{ null }} {%- endif %}
    notification_icon: "{{ notifIcon }}"
    importance: "{{ importance }}"
```

### Relevant log output

```shell
{
  "trace": {
    "last_step": "action/1/choose/0/sequence/0",
    "run_id": "36332de463fd9aad66bf8f106599153c",
    "state": "stopped",
    "script_execution": "error",
    "timestamp": {
      "start": "2023-10-21T10:17:55.674602+00:00",
      "finish": "2023-10-21T10:17:55.687166+00:00"
    },
    "domain": "automation",
    "item_id": "1697719671153",
    "error": "Error rendering data template: UndefinedError: 'dict object' has no attribute 'trigger'",
    "trigger": "mqtt topic frigate/events",
    "trace": {
      "trigger/0": [
        {
          "path": "trigger/0",
          "timestamp": "2023-10-21T10:17:55.674703+00:00",
          "changed_variables": {
            "this": {
              "entity_id": "automation.advanced_process_detected_plates",
              "state": "on",
              "attributes": {
                "id": "1697719671153",
                "last_triggered": "2023-10-21T09:33:57.975390+00:00",
                "mode": "single",
                "current": 0,
                "friendly_name": "Advanced Process Detected Plates"
              },
              "last_changed": "2023-10-21T10:17:52.966619+00:00",
              "last_updated": "2023-10-21T10:17:52.966619+00:00",
              "context": {
                "id": "01HD8VVH263Y876C44AQV8WVG7",
                "parent_id": null,
                "user_id": null
              }
            },
            "trigger": {
              "id": "0",
              "idx": "0",
              "alias": null,
              "platform": "mqtt",
              "topic": "frigate/events",
              "payload": "{\"before\": {\"id\": \"1697830047.961808-spynux\", \"camera\": \"ANPR\",     \"frame_time\": 1697830049.317514, \"snapshot\": {\"frame_time\":     1697830049.317514, \"box\": [254, 231, 890, 719], \"area\": 310368, \"region\":     [0, 0, 1528, 1528], \"score\": 0.95703125, \"attributes\": []}, \"label\": \"car\",     \"sub_label\": null, \"top_score\": 0.884765625, \"false_positive\": false,     \"start_time\": 1697830047.961808, \"end_time\": null, \"score\": 0.95703125,     \"box\": [254, 231, 890, 719], \"area\": 310368, \"ratio\": 1.3032786885245902,     \"region\": [0, 0, 1528, 1528], \"stationary\": false, \"motionless_count\": 2,     \"position_changes\": 1, \"current_zones\": [\"ANPR_drive\", \"ANPR_whole_area\"],     \"entered_zones\": [\"ANPR_drive\", \"ANPR_whole_area\"], \"has_clip\": true,     \"has_snapshot\": true, \"attributes\": {}, \"current_attributes\": []}, \"after\":     {\"id\": \"1697830047.961808-spynux\", \"camera\": \"ANPR\", \"frame_time\":     1697830054.35263, \"snapshot\": {\"frame_time\": 1697830050.837492, \"box\": [351,     327, 1279, 719], \"area\": 363776, \"region\": [0, 0, 1528, 1528], \"score\":     0.796875, \"attributes\": []}, \"label\": \"car\", \"sub_label\": null, \"top_score\":     0.95703125, \"false_positive\": false, \"start_time\": 1697830047.961808,     \"end_time\": null, \"score\": 0.6640625, \"box\": [406, 344, 1279, 719], \"area\":     327375, \"ratio\": 2.328, \"region\": [0, 0, 1532, 1532], \"stationary\": false,     \"motionless_count\": 19, \"position_changes\": 1, \"current_zones\":     [\"ANPR_drive\", \"ANPR_whole_area\"], \"entered_zones\": [\"ANPR_drive\",     \"ANPR_whole_area\"], \"has_clip\": true, \"has_snapshot\": true, \"attributes\":     {}, \"current_attributes\": []}, \"type\": \"new\"}",
              "qos": 0,
              "description": "mqtt topic frigate/events",
              "payload_json": {
                "before": {
                  "id": "1697830047.961808-spynux",
                  "camera": "ANPR",
                  "frame_time": 1697830049.317514,
                  "snapshot": {
                    "frame_time": 1697830049.317514,
                    "box": [
                      254,
                      231,
                      890,
                      719
                    ],
                    "area": 310368,
                    "region": [
                      0,
                      0,
                      1528,
                      1528
                    ],
                    "score": 0.95703125,
                    "attributes": []
                  },
                  "label": "car",
                  "sub_label": null,
                  "top_score": 0.884765625,
                  "false_positive": false,
                  "start_time": 1697830047.961808,
                  "end_time": null,
                  "score": 0.95703125,
                  "box": [
                    254,
                    231,
                    890,
                    719
                  ],
                  "area": 310368,
                  "ratio": 1.3032786885245902,
                  "region": [
                    0,
                    0,
                    1528,
                    1528
                  ],
                  "stationary": false,
                  "motionless_count": 2,
                  "position_changes": 1,
                  "current_zones": [
                    "ANPR_drive",
                    "ANPR_whole_area"
                  ],
                  "entered_zones": [
                    "ANPR_drive",
                    "ANPR_whole_area"
                  ],
                  "has_clip": true,
                  "has_snapshot": true,
                  "attributes": {},
                  "current_attributes": []
                },
                "after": {
                  "id": "1697830047.961808-spynux",
                  "camera": "ANPR",
                  "frame_time": 1697830054.35263,
                  "snapshot": {
                    "frame_time": 1697830050.837492,
                    "box": [
                      351,
                      327,
                      1279,
                      719
                    ],
                    "area": 363776,
                    "region": [
                      0,
                      0,
                      1528,
                      1528
                    ],
                    "score": 0.796875,
                    "attributes": []
                  },
                  "label": "car",
                  "sub_label": null,
                  "top_score": 0.95703125,
                  "false_positive": false,
                  "start_time": 1697830047.961808,
                  "end_time": null,
                  "score": 0.6640625,
                  "box": [
                    406,
                    344,
                    1279,
                    719
                  ],
                  "area": 327375,
                  "ratio": 2.328,
                  "region": [
                    0,
                    0,
                    1532,
                    1532
                  ],
                  "stationary": false,
                  "motionless_count": 19,
                  "position_changes": 1,
                  "current_zones": [
                    "ANPR_drive",
                    "ANPR_whole_area"
                  ],
                  "entered_zones": [
                    "ANPR_drive",
                    "ANPR_whole_area"
                  ],
                  "has_clip": true,
                  "has_snapshot": true,
                  "attributes": {},
                  "current_attributes": []
                },
                "type": "new"
              }
            },
            "after_zones": [
              "ANPR_drive",
              "ANPR_whole_area"
            ],
            "before_zones": [
              "ANPR_drive",
              "ANPR_whole_area"
            ],
            "camera": "ANPR",
            "id": "1697830047.961808-spynux",
            "label": "car",
            "score": 0.6640625,
            "time_clip_start": 1697830037.961808
          }
        }
      ],
      "condition/0": [
        {
          "path": "condition/0",
          "timestamp": "2023-10-21T10:17:55.674764+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "condition/0/conditions/0": [
        {
          "path": "condition/0/conditions/0",
          "timestamp": "2023-10-21T10:17:55.674808+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "condition/1": [
        {
          "path": "condition/1",
          "timestamp": "2023-10-21T10:17:55.674963+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "condition/2": [
        {
          "path": "condition/2",
          "timestamp": "2023-10-21T10:17:55.675164+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "condition/3": [
        {
          "path": "condition/3",
          "timestamp": "2023-10-21T10:17:55.675314+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "condition/4": [
        {
          "path": "condition/4",
          "timestamp": "2023-10-21T10:17:55.676971+00:00",
          "result": {
            "result": null
          }
        }
      ],
      "condition/5": [
        {
          "path": "condition/5",
          "timestamp": "2023-10-21T10:17:55.677038+00:00",
          "result": {
            "result": true,
            "entities": []
          }
        }
      ],
      "action/0": [
        {
          "path": "action/0",
          "timestamp": "2023-10-21T10:17:55.679327+00:00",
          "changed_variables": {
            "context": {
              "id": "01HD8VVKPTTF47WTPBZ0ERVJ3G",
              "parent_id": null,
              "user_id": null
            }
          },
          "result": {
            "wait": {
              "remaining": 60,
              "completed": true
            }
          }
        }
      ],
      "action/1": [
        {
          "path": "action/1",
          "timestamp": "2023-10-21T10:17:55.679992+00:00",
          "changed_variables": {
            "wait": {
              "remaining": 60,
              "completed": true
            }
          },
          "error": "Error rendering data template: UndefinedError: 'dict object' has no attribute 'trigger'",
          "result": {
            "choice": 0
          }
        }
      ],
      "action/1/choose/0": [
        {
          "path": "action/1/choose/0",
          "timestamp": "2023-10-21T10:17:55.680390+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/1/choose/0/conditions/0": [
        {
          "path": "action/1/choose/0/conditions/0",
          "timestamp": "2023-10-21T10:17:55.680440+00:00",
          "result": {
            "result": true,
            "entities": [
              "image_processing.platerecognizer_tester"
            ]
          }
        }
      ],
      "action/1/choose/0/sequence/0": [
        {
          "path": "action/1/choose/0/sequence/0",
          "timestamp": "2023-10-21T10:17:55.681200+00:00",
          "error": "Error rendering data template: UndefinedError: 'dict object' has no attribute 'trigger'"
        }
      ]
    },
    "config": {
      "id": "1697719671153",
      "alias": "Advanced Process Detected Plates",
      "description": "",
      "trigger": [
        {
          "platform": "mqtt",
          "topic": "frigate/events",
          "value_template": "{{ value_json['after']['camera'] }}",
          "variables": {
            "after_zones": "{{ trigger.payload_json['after']['entered_zones'] }}",
            "before_zones": "{{ trigger.payload_json['before']['entered_zones'] }}",
            "camera": "{{ trigger.payload_json['after']['camera'] }}",
            "id": "{{ trigger.payload_json['after']['id'] }}",
            "label": "{{ trigger.payload_json['after']['label'] }}",
            "score": "{{ trigger.payload_json['after']['score'] }}",
            "time_clip_start": "{{ trigger.payload_json['after']['start_time'] - 10.0 }}"
          },
          "payload": "ANPR"
        }
      ],
      "condition": [
        {
          "condition": "or",
          "conditions": [
            {
              "condition": "template",
              "value_template": "{{ trigger.payload_json['type'] == 'new' }}"
            },
            {
              "condition": "template",
              "value_template": "{{ before_zones | length == 0 }}"
            }
          ]
        },
        {
          "condition": "template",
          "value_template": "{{ trigger.payload_json['after']['entered_zones']|length > 0 }}"
        },
        {
          "condition": "template",
          "value_template": "{{ trigger.payload_json['after']['label'] == 'car' }}"
        },
        {
          "condition": "template",
          "value_template": "{{ ['ANPR_drive', 'ANPR_driveway'] | select('in', after_zones) | list | length > 0 }}",
          "enabled": true
        },
        {
          "condition": "template",
          "value_template": "{{ trigger.payload_json['after']['attributes'].get('license_plate') is not none }}",
          "enabled": false
        },
        {
          "condition": "template",
          "value_template": "{{ id is not none and id != 'unavailable' }}"
        }
      ],
      "action": [
        {
          "wait_template": "{{ state_attr('image_processing.platerecognizer_tester', 'watched_plates') is not none }}",
          "timeout": "00:01:00",
          "enabled": true
        },
        {
          "choose": [
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ state_attr('image_processing.platerecognizer_tester', 'watched_plates').values() | select('equalto', true) | list | length > 0 }}"
                }
              ],
              "sequence": [
                {
                  "service": "script.dynamicnotification",
                  "data": {
                    "id": "{{ id }}",
                    "title": "{% if (wait.trigger.payload_json[\"after\"][\"sub_label\"] != None) -%} {{ (wait.trigger.payload_json[\"after\"][\"sub_label\"]) | title }} {%- else -%} {{ label | replace(\"_\", \" \") | title }} {%- endif %} was detected in the {{ after_zones[0] | replace(\"_\", \" \") | title }}",
                    "message": "Detected with {{ int(score | round(2) * 100) }}% confidence",
                    "notifTag": "{{ id }}",
                    "notifIcon": "mdi:doorbell-video",
                    "group": "frigate-notification-{{ trigger.payload_json[\"after\"][\"camera\"] }}",
                    "importance": "default",
                    "image": "/api/frigate/notifications/{{ id }}/snapshot.jpg",
                    "video": "https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4",
                    "clickAction": "https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
                  }
                }
              ]
            },
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ state_attr('image_processing.platerecognizer_tester', 'watched_plates').values() | select('equalto', false) | list | length > 0 }}"
                }
              ],
              "sequence": [
                {
                  "service": "script.dynamicnotification",
                  "data": {
                    "id": "{{ id }}",
                    "title": "Hi",
                    "message": "Detected with {{ int(score | round(2) * 100) }}% confidence",
                    "notifTag": "{{ id }}",
                    "notifIcon": "mdi:doorbell-video",
                    "group": "frigate-notification-{{ trigger.payload_json[\"after\"][\"camera\"] }}",
                    "importance": "default",
                    "image": "/api/frigate/notifications/{{ id }}/snapshot.jpg",
                    "video": "https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4",
                    "clickAction": "https://ha.mcrae-labs.co.uk/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
                  }
                }
              ]
            }
          ]
        }
      ]
    },
    "blueprint_inputs": null,
    "context": {
      "id": "01HD8VVKPTTF47WTPBZ0ERVJ3G",
      "parent_id": null,
      "user_id": null
    }
  },
  "logbookEntries": [
    {
      "name": "Advanced Process Detected Plates",
      "message": "triggered by mqtt topic frigate/events",
      "source": "mqtt topic frigate/events",
      "entity_id": "automation.advanced_process_detected_plates",
      "context_id": "01HD8VVKPTTF47WTPBZ0ERVJ3G",
      "when": 1697883475.67739,
      "domain": "automation"
    }
  ]
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
