### ISSUE TITLE
[Config Support]: Attempting to have different record modes for each camera

### ISSUE THREAD

**Issue by psilantropy** [blakeblackshear/frigate#8268]
### Describe the problem you are having

Hi,

I usually run a global config for my record mode, but today wanted to adjust so I didn't have a 24/7 recording of a garage door.
I usually present this as a global config and nothing for each camera.

```
record:
  enabled: True
  retain:
    mode: all
  events:
    retain:
      default: 120
      mode: motion
```

I removed this from global, then added under each camera the individual setting, only changing the retain mode to motion on my garage camera.

BACKYARD: all
FRONT: all
GARAGE: motion
LAUNDRY: all

My backyard camera is the only one that appears to have recording enabled after doing this.
All other cameras receive this error in the gui. But I also have the list index out of range, and maintain recording cache error below.

```
No Recordings Found
Make sure you have enabled the record role in your configuration for the Garage camera.
```

If I change my config back to what it was and restart, I am stuck with the same issues.
Can anyone see what I'm missing here?

Thanks for the help.

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.200
  port: 1883
  user: user
  password: pass

database:
  path: /config/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: usb:0
    model:
  coral2:
    type: edgetpu
    device: usb:1
    model:

ffmpeg:
  hwaccel_args: preset-nvidia-h264

snapshots:
  enabled: true
  bounding_box: true
  clean_copy: true
  retain:
    default: 28

birdseye:
  enabled: true
  mode: continuous
  restream: true
  width: 1920
  height: 1080

go2rtc:
  streams:
    Front: # <- for RTSP streams
      - rtsp://user:pass@1.1.1.154:554/cam/realmonitor?channel=1&subtype=0
    Laundry: # <- for RTSP streams
      - rtsp://user:pass@1.1.1.150:554/cam/realmonitor?channel=1&subtype=0
    Backyard: # <- for RTSP streams
      - rtsp://user:pass@1.1.1.152:554/cam/realmonitor?channel=1&subtype=0
    Garage: # <- for RTSP streams
      - rtsp://user:pass@1.1.1.151:554/cam/realmonitor?channel=1&subtype=0

objects:
  track:
    - person
    - dog
    - cat
    - rat
    - plane
    - airplane

audio:
  enabled: True
  max_not_heard: 30
  listen:
    - speech
    - bark
    - fire_alarm
    - scream
    - yell

telemetry:
    version_check: true
    
cameras:
  Laundry:
    enabled: true
    record:
      enabled: true
      retain:
        mode: all
      events:
        retain:
          default: 120
          mode: motion
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.150:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://user:pass@1.1.1.150:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    motion:
        mask:
          - 0,0,1920,0,1920,696,1567,525,1000,323,877,292,347,171,184,150,0,230
          - 196,985,0,972,0,1080,398,1080,569,1080,577,981
    objects:
      filters:
        person:
          mask:
            - 1920,692,1920,0,0,0,0,115,0,239,199,150
    mqtt:
      timestamp: True
      crop: true
      height: 1080
      bounding_box: true

  Front:
    enabled: true
    record:
      enabled: true
      retain:
        mode: all
      events:
        retain:
          default: 120
          mode: motion
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.154:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://user:pass@1.1.1.154:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: True
      crop: true
      height: 1080
      bounding_box: true
    motion:
      mask:
        - 1920,0,0,0,0,683,313,740,656,789,1418,832,1920,766

  Backyard:
    enabled: true
    record:
      enabled: true
      retain:
        mode: all
      events:
        retain:
          default: 120
          mode: motion
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.152:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://user:pass@1.1.1.152:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - rat
    motion:
        mask:
          - 733,1080,0,1080,0,0,883,0,844,329,732,353,737,536
    mqtt:
      timestamp: True
      crop: true
      height: 1080
      bounding_box: true

  Garage:
    enabled: true
    record:
      enabled: true
      retain:
        mode: motion
      events:
        retain:
          default: 120
          mode: motion
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.151:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://user:pass@1.1.1.151:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: True
      crop: true
      height: 1080
      bounding_box: true
```

### Relevant log output

```shell
2023-10-22 22:43:28.114362593  [2023-10-22 22:43:28] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-10-22 22:43:28.114551922  [2023-10-22 22:43:28] frigate.record.maintainer      ERROR   : list index out of range
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
