### ISSUE TITLE
Help with zones - how to properly configure

### ISSUE THREAD

**Issue by r0ckyjoe** [blakeblackshear/frigate#8271]
### Describe the problem you are having

Hello,
I've configured two zones with my camera:
- esterno
- interno

I did some tests and based on my findings it seemed that the area of interest to map in the Zone is basically the one that becomes red when I start creating vertexes.
Though, today I got a strange behavior as I got a detection that triggered both areas although they do not overlap.

The scope of the two is the following: 
- the interno zone is used to trigger recording and HA automation (rings sirens, turn on lights, send telegram messages with pics and recordings and some other things) when somebody gets inside the property.
- the esterno zone is used to record clips just in case somebody lurks too much to the property.

Can you please kindly help me understanding what I am doing wrong and how I should configure the above zones to achieve what I need?

I am attaching 3 pictures: 1. interno zone 2. esterno zone 3. the last events when interno and esterno got detections inside.
![cam_interno_mask](https://github.com/blakeblackshear/frigate/assets/24768537/52de2527-f200-4d94-996f-861974a7c104)
![cam_esterno_mask](https://github.com/blakeblackshear/frigate/assets/24768537/035abd41-9ae3-43f8-87ba-ab7e1c16600d)
![cam_events](https://github.com/blakeblackshear/frigate/assets/24768537/871de019-be57-4cbb-8c68-d9ceb9628ffb)

Thanks!

### Version

Frigate (0.12.1-367d724)

### Frigate config file

```yaml
#### Please note: I renamed camera names in Camname except for the one I attached the pictures which I renamed as RelevantCam.

database:
  path: /db/frigate.db

mqtt:
  host: ***
  user: ***
  password: ***
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

logger:
  default: info
  logs:
    frigate.app: info
    frigate.mqtt: info
#    frigate.record: debug

detectors:
  cpu0:
    type: cpu
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
  cpu5:
    type: cpu
  cpu6:
    type: cpu
  cpu7:
    type: cpu

motion:
  threshold: 40
  frame_height: 60
  
detect:
  fps: 7
  enabled: True
  max_disappeared: 35

objects:
  track:
    - person
    - cat
    - dog
    - car
  filters:
    person:
      min_area: 2000
      max_area: 20000
      min_score: 0.7
    cat:
      min_area: 800
      max_area: 10000
      min_score: 0.7
    dog:
      min_area: 800
      max_area: 10000
      min_score: 0.7
    car:
      min_area: 3000
      max_area: 20000
      min_score: 0.7

snapshots:
  enabled: True
  bounding_box: True
timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"

record:
  enabled: True
  retain:
    days: 14
    mode: active_objects
  events:
    retain:
      mode: active_objects
      objects:
        car: 7
        dog: 7
        cat: 7

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: motion

cameras:
  Camname:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        # record: preset-record-generic-audio-aac
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac -strict experimental -max_interleave_delta 500M -async 1
      inputs:
        - path: rtsp://*:*@****:554/stream1 
          roles:
            - detect
        - path: rtsp://*:*@****:554/stream1 
          roles:
            - record
    objects:
      filters:
        cat:
          min_score: 0.5
        dog:
          min_score: 0.5
        person:
          min_score: 0.5
  RelevantCam:
    zones:
      esterno:
        coordinates: 0,225,202,239,231,233,245,290,333,290,325,246,397,242,402,283,681,280,681,238,726,238,726,372,1030,367,1044,295,1115,302,1280,454,1280,318,1280,0,0,0
      interno:
        coordinates: 1195,395,1280,395,1280,720,0,720,0,257,247,249,263,368,678,362,721,361,729,386,1029,394,1034,342,1058,253,1080,258,1083,287
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
          # record: preset-record-generic-audio-aac
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac -strict experimental -max_interleave_delta 500M -async 1
      inputs:
        - path: rtsp://*:*@****:554/stream1
          roles:
            - detect
        - path: rtsp://*:*@****:554/stream1
          roles:
            - record
    objects:
      track:
        - car
        - cat
        - dog
        - person
    record:
      events:
        required_zones:
          - esterno
          - interno
    snapshots:
      required_zones:
        - esterno
        - interno

  Camname:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
        # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac -strict experimental -max_interleave_delta 500M -async 1
      inputs:
        - path: rtsp://*:*@****:554/stream1
          roles:
            - detect
        - path: rtsp://*:*@****:554/stream1
          roles:
            - record
    motion:
      mask: 148,180,399,133,1280,93,1280,0,112,0,0,0,0,720,280,720
    objects:
      track:
        - car
        - cat
        - dog
        - person
  Camname:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
       # record: preset-record-generic-audio-aac
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac -strict experimental -max_interleave_delta 500M -async 1
      inputs:
        - path: rtsp://*:*@****:554/stream1
          roles:
            - detect
        - path: rtsp://*:*@****:554/stream1
          roles:
            - record
```

### Relevant log output

```shell
nothing relevant here
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
