### ISSUE TITLE
[Support]: Unable to detect objects with go2rtc streams. 

### ISSUE THREAD

**Issue by NYKoop** [blakeblackshear/frigate#8276]
### Describe the problem you are having

I have a pair of Reolink RLC-511W cameras that I have configured with the recommended go2rtc stream setup. The live video stream works great with mse within Frigate, and I get audio too. However, I can not get Frigate to detect any events with this configuration. If I switch back to just using ffmpeg to connect to the RTSP stream on the camera in the cameras section of the config (no go2rtc section), the detection works fine. As you know the downside with that is choppy video and no audio. I am running Frigate in a Podman container with a Coral USB TPU.
I have tried with and without the detect section in the cameras section. I've tried just using the main feed and having both the detect and record on that same feed. I've set the live stream_name to each of the go2rtc feeds to make sure they all work. Though I do get on occasion the invalid data error as shown in the logs.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

database:
  path: /config/frigate.db

objects:
  track:
    - person
    - car
    - dog

detectors:
 coral:
   type: edgetpu

go2rtc:
  streams:
    driveway:
      - "ffmpeg:http://192.168.0.131/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    driveway_sub:
      - "ffmpeg:http://192.168.0.131/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password={FRIGATE_RTSP_PASSWORD}"
    front:
      - "ffmpeg:http://192.168.0.118/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    front_sub:
      - "ffmpeg:http://192.168.0.118/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password={FRIGATE_RTSP_PASSWORD}"

cameras:
  driveway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 7
  front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 7
```

### Relevant log output

```shell
2023-10-22 14:06:29.291585101  [INFO] Starting Frigate...
2023-10-22 14:06:30.150069418  [2023-10-22 14:06:30] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-22 14:06:30.166785921  [2023-10-22 14:06:30] peewee_migrate                 INFO    : Starting migrations
2023-10-22 14:06:30.170824657  [2023-10-22 14:06:30] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-22 14:06:30.184953830  [2023-10-22 14:06:30] frigate.app                    INFO    : Output process started: 290
2023-10-22 14:06:30.202971826  [2023-10-22 14:06:30] frigate.app                    INFO    : Camera processor started for driveway: 295
2023-10-22 14:06:30.202976750  [2023-10-22 14:06:30] frigate.app                    INFO    : Camera processor started for front: 297
2023-10-22 14:06:30.202981961  [2023-10-22 14:06:30] frigate.app                    INFO    : Capture process started for driveway: 298
2023-10-22 14:06:30.202984583  [2023-10-22 14:06:30] frigate.app                    INFO    : Capture process started for front: 300
2023-10-22 14:06:33.005769467  [2023-10-22 14:06:30] detector.coral                 INFO    : Starting detection process: 288
2023-10-22 14:06:33.008635501  [2023-10-22 14:06:30] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-22 14:06:33.008724220  [2023-10-22 14:06:33] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-10-22 14:06:35.346337657  [2023-10-22 14:06:35] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
2023-10-22 14:06:35.346817907  [2023-10-22 14:06:35] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
2023-10-22 14:06:50.249673221  [2023-10-22 14:06:50] watchdog.driveway              ERROR   : Ffmpeg process crashed unexpectedly for driveway.
2023-10-22 14:06:50.249747249  [2023-10-22 14:06:50] watchdog.driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-22 14:06:50.249855355  [2023-10-22 14:06:50] ffmpeg.driveway.detect         ERROR   : rtsp://127.0.0.1:8554/driveway_sub?video=copy: Invalid data found when processing input

Go2RTC Logs:
2023-10-22 14:06:29.292911276  [INFO] Preparing go2rtc config...
2023-10-22 14:06:29.521173635  [INFO] Starting go2rtc...
2023-10-22 14:06:29.601435971  14:06:29.601 INF go2rtc version 1.2.0 linux/amd64
2023-10-22 14:06:29.601702891  14:06:29.601 INF [api] listen addr=:1984
2023-10-22 14:06:29.601922917  14:06:29.601 INF [rtsp] listen addr=:8554
2023-10-22 14:06:29.602370260  14:06:29.602 INF [srtp] listen addr=:8443
2023-10-22 14:06:29.602525195  14:06:29.602 INF [webrtc] listen addr=:8555
2023-10-22 14:06:35.596596034  14:06:35.596 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-22 14:06:39.287872822  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
front_sub:
 libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x563c4d427140] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/front_sub?video=copy':
  Metadata:
    title           : go2rtc/1.2.0
  Duration: N/A, start: 0.067000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x672, 30 tbr, 90k tbn

front:
 libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5578ebde3140] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/front?video=copy':
  Metadata:
    title           : go2rtc/1.2.0
  Duration: N/A, start: 0.033000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 30 tbr, 90k tbn
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.2"},"1":{"cpu":"0.0","mem":"0.0"},"102":{"cpu":"0.3","mem":"1.0"},"104":{"cpu":"0.0","mem":"0.0"},"118":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"0.5"},"287":{"cpu":"0.0","mem":"0.1"},"288":{"cpu":"2.3","mem":"0.7"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.3","mem":"0.6"},"295":{"cpu":"0.7","mem":"0.6"},"297":{"cpu":"5.3","mem":"0.6"},"298":{"cpu":"0.7","mem":"0.5"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.3","mem":"0.5"},"302":{"cpu":"0.0","mem":"0.1"},"304":{"cpu":"0.0","mem":"0.1"},"307":{"cpu":"1.3","mem":"0.4"},"309":{"cpu":"0.0","mem":"0.1"},"31":{"cpu":"0.0","mem":"0.0"},"312":{"cpu":"0.3","mem":"0.2"},"32":{"cpu":"0.0","mem":"0.0"},"355":{"cpu":"1.3","mem":"0.4"},"357":{"cpu":"0.7","mem":"0.2"},"39":{"cpu":"0.0","mem":"0.0"},"47":{"cpu":"0.0","mem":"0.0"},"535":{"cpu":"0.0","mem":"0.0"},"548":{"cpu":"0.0","mem":"0.0"},"77":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"91":{"cpu":"0.3","mem":"0.1"},"MiB":{"cpu":"11578.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":6.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.78,"pid":288}},"driveway":{"camera_fps":7.0,"capture_pid":298,"detection_enabled":1,"detection_fps":0.3,"ffmpeg_pid":355,"pid":295,"process_fps":7.0,"skipped_fps":0.0},"front":{"camera_fps":7.0,"capture_pid":300,"detection_enabled":1,"detection_fps":5.8,"ffmpeg_pid":307,"pid":297,"process_fps":7.0,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"1.17 %","mem":"- %"}},"service":{"last_updated":1697998927,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":65.1,"mount_type":"tmpfs","total":67.1,"used":2.0},"/media/frigate/clips":{"free":5870611.8,"mount_type":"ext4","total":7936070.4,"used":1665473.2},"/media/frigate/recordings":{"free":5870611.8,"mount_type":"ext4","total":7936070.4,"used":1665473.2},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":937,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink RLC-511W

**Comment by NickM-27** [comment]
Please let the logs run longer before posting, also I'd suggest updating go2rtc https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by NYKoop** [comment]
Thanks, I now have go2rtc 1.8.1 installed in /config. So far, nothing interesting in the logs, but am unable to get any events triggered. I'll wait to see if anything else pops in the logs.

023-10-22 16:26:28.315650032  [INFO] Preparing go2rtc config...
2023-10-22 16:26:28.542003211  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-10-22 16:26:28.542007857  [INFO] Starting go2rtc...
2023-10-22 16:26:28.609461141  16:26:28.607 INF go2rtc version 1.8.1 linux/amd64
2023-10-22 16:26:28.609465419  16:26:28.608 INF [api] listen addr=0.0.0.0:1984
2023-10-22 16:26:28.609466917  16:26:28.608 INF [rtsp] listen addr=0.0.0.0:8554
2023-10-22 16:26:28.609471559  16:26:28.608 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-10-22 16:26:38.313817155  [INFO] Starting go2rtc healthcheck service...

**Comment by NickM-27** [comment]
What are the Frigate logs? What do you see when viewing the detect live view with bounding boxes enabled

**Comment by NYKoop** [comment]
I am getting these errors now in the Frigate logs: It repeated quit a few times. Not sure what you mean by viewing the detect live view. Is that different that just the live view? One important thing I think I missed between the 2 configurations is the 

record:
  enabled: true

In the cameras section.

2023-10-22 17:06:14.850354928  [2023-10-22 17:06:14] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
2023-10-22 17:06:14.850467584  [2023-10-22 17:06:14] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
2023-10-22 17:06:19.737687394  [2023-10-22 17:06:19] watchdog.driveway              ERROR   : Ffmpeg process crashed unexpectedly for driveway.
2023-10-22 17:06:19.740025487  [2023-10-22 17:06:19] watchdog.driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-22 17:06:19.740092400  [2023-10-22 17:06:19] ffmpeg.driveway.detect         ERROR   : rtsp://127.0.0.1:8554/driveway_sub?video=copy: Invalid data found when processing input

**Comment by NickM-27** [comment]
letting the logs run a little longer then pasting will be helpful, these don't contain much information

I would suggest maybe doing something like this also in the config

```
  front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub?video
          input_args: preset-rtsp-restream
          roles:
            - detect
```
