### ISSUE TITLE
[Detector Support]: openvino aeozyalcin colab notebook for model conversion of yolov8 not working.

### ISSUE THREAD

**Issue by alsimms** [blakeblackshear/frigate#8277]
### Describe the problem you are having

I am using aeozyalcin colab notebook to convert yolov8n to openvino but it fails to load on frigate even though it completed the conversion without errors.

### Version

13 beta 2

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:

      path: /config/models/yolo8n/yolov8n.xml

model:
  width: 416
  height: 416
  input_tensor: nhwc
  model_type: yolov8
  input_pixel_format: bgr
  labelmap_path: /config/models/yolo8n/coco_80cl.txt
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2
    shm_size: "300mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/SHNET-POOL1/Docker/frigate/config/:/config/
      - /mnt/SHNET-POOL1/Docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
frigate  | 2023-10-22 18:40:07.307929835  Process detector:ov:
frigate  | 2023-10-22 18:40:07.308990053  Traceback (most recent call last):
frigate  | 2023-10-22 18:40:07.309005974    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2023-10-22 18:40:07.309027192      self.run()
frigate  | 2023-10-22 18:40:07.309029074    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2023-10-22 18:40:07.309030705      self._target(*self._args, **self._kwargs)
frigate  | 2023-10-22 18:40:07.309032354    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
frigate  | 2023-10-22 18:40:07.309033994      detections = object_detector.detect_raw(input_frame)
frigate  | 2023-10-22 18:40:07.309035642    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
frigate  | 2023-10-22 18:40:07.309037200      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate  | 2023-10-22 18:40:07.309038867    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 84, in detect_raw
frigate  | 2023-10-22 18:40:07.309040262      infer_request.infer([tensor_input])
frigate  | 2023-10-22 18:40:07.309041974    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 152, in infer
frigate  | 2023-10-22 18:40:07.309043515      return super().infer(normalize_inputs(self, dict(enumerate(inputs))))
frigate  | 2023-10-22 18:40:07.309052850  RuntimeError: Can't set input blob with name: images, because model input (shape=[1,3,416,416]) and blob (shape=(1.416.416.3)) are incompatible
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

$ ls -alh
total 12M
drwxrwxr-x 2 root root    7 Oct 22 16:48 .
drwxrwxr-x 3 root root    3 Oct 22 16:45 ..
-rw-rw-r-- 1 root root  606 Oct 22 16:48 coco_80cl.txt
-rw-r--r-- 1 root root 6.1M Oct 22 02:57 yolov8n.bin
-rw-r--r-- 1 root root  45K Oct 22 02:57 yolov8n.mapping
-rw-r--r-- 1 root root 296K Oct 22 02:57 yolov8n.xml
-rw-rw-r-- 1 root root 5.7M Oct 22 16:46 yolov8n.zip
