### ISSUE TITLE
[Config Support]: Reolink RTSP error on 1 camera feed

### ISSUE THREAD

**Issue by BurningTheSky** [blakeblackshear/frigate#8280]
### Describe the problem you are having

I have 3 Reolink RLC-810A cameras that I'm trying to connect to Frigate using the Reolink configuration via go2rtc streams but only the first seems to be wrong. I assume I have made a silly config mistake but I can't spot it. There is a rtsp.go warning as well but I'm not sure if that is the cause or a symptom.

When I open the http streams in VLC they run fine but only the first 2 rtsp streams, in line with the errors I'm seeing but the live view in the webUI seem to work fine.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.45
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password

database:
  path: /db/frigate.db

detectors:
#  coral:
#    type: edgetpu
#    device: usb
  cuda:
    type: tensorrt

go2rtc:
  streams:
    front:
      - "ffmpeg:http://192.168.0.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    front247:
      - "ffmpeg:http://192.168.0.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"
    garage:
      - "ffmpeg:http://192.168.0.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    garage247:
      - "ffmpeg:http://192.168.0.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"
    garden:
      - "ffmpeg:http://192.168.0.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    garden247:
      - "ffmpeg:http://192.168.0.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"

cameras:
  # <------- Event record ------->

  Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front247?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args:
            - -c:v
            - h264_cuvid
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
        - suitcase
        - skateboard
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
#          input_args: preset-rtsp-restream
#          roles:
#            - record
        - path: rtsp://127.0.0.1:8554/garage247?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args:
            - -c:v
            - h264_cuvid
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
        - suitcase
        - skateboard
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden247?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args:
            - -c:v
            - h264_cuvid
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Downstairs: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.57/live0
          roles:
            - detect
            - record
          hwaccel_args:
            - -c:v
            - h264_cuvid
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  # <------- 24/7 record ------->

  Front_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front247?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -c:v
            - h264_cuvid
    record:
      enabled: True
      retain:
        days: 31
        mode: all

  Garage_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage247?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args:
            - -c:v
            - h264_cuvid
    record:
      enabled: True
      retain:
        days: 31
        mode: all


model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### Relevant log output

```shell
2023-10-23 09:38:44.583127779  09:38:44.583 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-10-23 09:38:48.859282592  [2023-10-23 09:38:48] ffmpeg.Garden.record           ERROR   : rtsp://127.0.0.1:8554/garden?video=copy&audio=aac: Invalid data found when processing input
2023-10-23 09:38:48.859366751  [2023-10-23 09:38:48] watchdog.Garden                INFO    : Terminating the existing ffmpeg process...
2023-10-23 09:38:48.859441482  [2023-10-23 09:38:48] watchdog.Garden                INFO    : Waiting for ffmpeg to exit gracefully...
2023-10-23 09:38:49.624096377  192.168.3.45 - - [23/Oct/2023:09:38:49 +0100] "GET /api/stats HTTP/1.1" 200 4132 "-" "HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11" "-"
```

### Frigate stats

```json
{"Downstairs":{"camera_fps":5.1,"capture_pid":610,"detection_enabled":1,"detection_fps":5.1,"ffmpeg_pid":619,"pid":588,"process_fps":5.1,"skipped_fps":0.0},"Front":{"camera_fps":7.1,"capture_pid":593,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":597,"pid":584,"process_fps":7.1,"skipped_fps":0.0},"Front_247":{"camera_fps":5.2,"capture_pid":617,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":628,"pid":590,"process_fps":5.2,"skipped_fps":0.0},"Garage":{"camera_fps":7.0,"capture_pid":596,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":603,"pid":585,"process_fps":7.0,"skipped_fps":0.0},"Garage_247":{"camera_fps":5.1,"capture_pid":629,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":638,"pid":592,"process_fps":5.1,"skipped_fps":0.0},"Garden":{"camera_fps":7.0,"capture_pid":601,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":613,"pid":587,"process_fps":7.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"115":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"140":{"cpu":"0.0","mem":"0.0"},"147":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"166":{"cpu":"0.0","mem":"0.0"},"189":{"cpu":"0.0","mem":"0.0"},"222":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"2478":{"cpu":"3.7","mem":"0.1"},"2483":{"cpu":"2.0","mem":"0.1"},"25":{"cpu":"0.0","mem":"0.0"},"250":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"276":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"303":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"3787":{"cpu":"0.0","mem":"0.0"},"3841":{"cpu":"0.0","mem":"0.0"},"3849":{"cpu":"0.0","mem":"0.0"},"3852":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"43":{"cpu":"0.0","mem":"0.0"},"569":{"cpu":"0.0","mem":"0.5"},"575":{"cpu":"0.3","mem":"0.0"},"576":{"cpu":"4.7","mem":"2.2"},"578":{"cpu":"2.0","mem":"0.6"},"583":{"cpu":"0.0","mem":"0.0"},"584":{"cpu":"0.7","mem":"0.6"},"585":{"cpu":"0.7","mem":"0.6"},"586":{"cpu":"0.0","mem":"0.0"},"587":{"cpu":"0.7","mem":"0.6"},"588":{"cpu":"10.3","mem":"0.6"},"589":{"cpu":"0.0","mem":"0.0"},"590":{"cpu":"0.7","mem":"0.6"},"591":{"cpu":"0.0","mem":"0.0"},"592":{"cpu":"0.3","mem":"0.6"},"593":{"cpu":"0.7","mem":"0.6"},"596":{"cpu":"1.3","mem":"0.6"},"597":{"cpu":"5.0","mem":"0.5"},"598":{"cpu":"0.0","mem":"0.0"},"601":{"cpu":"0.7","mem":"0.6"},"603":{"cpu":"5.0","mem":"0.5"},"606":{"cpu":"1.0","mem":"0.1"},"608":{"cpu":"0.0","mem":"0.0"},"610":{"cpu":"0.7","mem":"0.5"},"611":{"cpu":"1.7","mem":"0.1"},"613":{"cpu":"5.0","mem":"0.5"},"616":{"cpu":"1.0","mem":"0.1"},"617":{"cpu":"1.3","mem":"0.6"},"618":{"cpu":"0.0","mem":"0.0"},"619":{"cpu":"9.0","mem":"0.5"},"623":{"cpu":"4.0","mem":"0.1"},"627":{"cpu":"1.0","mem":"0.1"},"628":{"cpu":"3.0","mem":"0.5"},"629":{"cpu":"1.3","mem":"0.6"},"638":{"cpu":"4.0","mem":"0.5"},"78":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"8.0","mem":"0.1"},"98":{"cpu":"5.6","mem":"1.2"},"99":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"12167.9","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":5.1,"detectors":{"cuda":{"detection_start":0.0,"inference_speed":7.59,"pid":576}},"gpu_usages":{"NVIDIA GeForce GTX 1050 Ti":{"gpu":"6 %","mem":"16.3 %"}},"service":{"last_updated":1698051466,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":260.1,"mount_type":"tmpfs","total":268.4,"used":8.4},"/media/frigate/clips":{"free":5055831.4,"mount_type":"fuse.shfs","total":15995344.7,"used":10939513.3},"/media/frigate/recordings":{"free":5055831.4,"mount_type":"fuse.shfs","total":15995344.7,"used":10939513.3},"/tmp/cache":{"free":981.5,"mount_type":"tmpfs","total":1000.0,"used":18.5}},"temperatures":{},"uptime":1208,"version":"0.12.1-367d724"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)
