### ISSUE TITLE
[Support]: unable to configure go2rtc 

### ISSUE THREAD

**Issue by marcgarciamarti** [blakeblackshear/frigate#8290]
### Describe the problem you are having

I'm a happy frigate user. It is amazing what it can do and how smooth it works. Congratulations!

I'm trying to setup go2rtc and I can't get it to work. The log information that I see does not seem to suggest there is an issue though:

```
2023-10-23 21:20:59.313495060  [INFO] Preparing go2rtc config...
2023-10-23 21:20:59.353081703  [INFO] Got IP address from supervisor: 192.168.1.5
2023-10-23 21:20:59.384170416  [INFO] Got WebRTC port from supervisor: 8555
2023-10-23 21:20:59.665604304  [INFO] Starting go2rtc...
2023-10-23 21:20:59.731207400  23:20:59.731 INF go2rtc version 1.2.0 linux/amd64
2023-10-23 21:20:59.731461642  23:20:59.731 INF [api] listen addr=:1984
2023-10-23 21:20:59.731995414  23:20:59.731 INF [rtsp] listen addr=:8554
2023-10-23 21:20:59.732195430  23:20:59.732 INF [srtp] listen addr=:8443
2023-10-23 21:20:59.732403037  23:20:59.732 INF [webrtc] listen addr=:8555
2023-10-23 21:21:09.316850786  [INFO] Starting go2rtc healthcheck service...
```
However, if I go to the cameras and click on the drop-down menu, I only see jsmpeg.

This is the go2rtc portion that I added to my everything-but-go2rtcd working configuration file:

```
go2rtc:
  streams:
    comedor:
      - rtsp://guest:pass@192.168.1.31:554/stream0
    recibidor:
      - rtsp://guest:pass@192.168.1.32:554/stream0
```
note that I'm using guest user for accessing the video feed.

I confirmed with VLC that the two streams above are working fine.  Read [this section](https://docs.frigate.video/guides/configuring_go2rtc/#what-if-my-video-doesnt-play) and  I believe my issue is not described in there as I have never managed to see go2rtc in the drop-down menu yet.

If I click on the go2rtc dashboard link all I see is this

```
404: Not Found
```

### Version

Home Assistant Add-on 0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.5
  user: USER
  password: PASS

birdseye:
  enabled: True
  mode: motion

go2rtc:
  streams:
    comedor:
      - rtsp://guest:pass@192.168.1.31:554/stream0
    recibidor:
      - rtsp://guest:pass@192.168.1.32:554/stream0
      
cameras:
  anpviz-camera-dome-comedor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.31:554/stream2
        roles:
          - detect
      - path: rtsp://192.168.1.31:554/stream0
        roles:
          - record
    objects:
      track:
        - person
    detect:
      enabled: false 
      width: 1280 
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: True
      events:
        retain:
          default: 14
          mode: active_objects

  anpviz-camera-dome-recibidor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.32:554/stream0
        roles:
          - record
      - path: rtsp://192.168.1.32:554/stream1
        roles:
          - detect
    objects:
      track:
        - person
    detect:
      enabled: false 
      width: 720
      height: 480
      fps: 5
    motion:
      mask:
        - 453,170,459,204,482,198,498,182,509,154,518,103,511,82,489,79,469,87
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
      enabled: True
      events:
        retain:
          default: 14
          mode: active_objects

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
2023-10-23 21:20:59.313495060  [INFO] Preparing go2rtc config...
2023-10-23 21:20:59.353081703  [INFO] Got IP address from supervisor: 192.168.1.5
2023-10-23 21:20:59.384170416  [INFO] Got WebRTC port from supervisor: 8555
2023-10-23 21:20:59.665604304  [INFO] Starting go2rtc...
2023-10-23 21:20:59.731207400  23:20:59.731 INF go2rtc version 1.2.0 linux/amd64
2023-10-23 21:20:59.731461642  23:20:59.731 INF [api] listen addr=:1984
2023-10-23 21:20:59.731995414  23:20:59.731 INF [rtsp] listen addr=:8554
2023-10-23 21:20:59.732195430  23:20:59.732 INF [srtp] listen addr=:8443
2023-10-23 21:20:59.732403037  23:20:59.732 INF [webrtc] listen addr=:8555
2023-10-23 21:21:09.316850786  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
homeassistant:/config# ffprobe rtsp://192.168.1.31:554/stream0
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://192.168.1.31:554/stream0':
  Metadata:
    title           : RTSP/RTP stream from icamra ipc
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Anpviz 4K POE Security Camera Outdoor 8MP
