### ISSUE TITLE
[Support]: MQTT Message - false_positive object

### ISSUE THREAD

**Issue by J-Pipe** [blakeblackshear/frigate#8294]
### Describe the problem you are having

I think the MQTT messages should always report the zone that the object is in. Right now, if the object is in a zone, but doesn't meet the filters for the zone, it just leaves the "zones" object empty, even though it is physically in that zone. I would expect that it still reports the correct zone, but should set the "false_positive" flag to true. Right now, I believe the "false_positive" flag gets set based only on the high-level object filters, but it should also accommodate the object filters in the "zones" as well. Because based on the zone that the object is in, it could have different area/ratio requirements.

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  host: 
  user: 
  password: 

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path:

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-blue-iris

live:
  stream_name: camera_name
  height: 720
  quality: 8

snapshots:
  enabled: True
  clean_copy: True
  crop: False
  bounding_box: True
  retain:
    default: 5




objects:
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .8
      threshold: .85
    car:
      min_score: .8
      threshold: .85  

detect:
  enabled: True
  width: 1280
  height: 720

cameras:
  baby_cam:
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:      
      inputs:
        - path: rtsp://10.0.1.35:3765/eufy_cam
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 1
    objects:
      track:
        - person
        - face
    motion:
      mask:    
        - 0,1080,684,1080,628,882,0,882
        - 1253,452,1436,608,1920,228,1920,0,1222,0
    mqtt:
      enabled: False
    zones:
      crib:
        coordinates: 338,962,795,927,663,363,368,382
        objects:
          - person
        filters:
          person:
            min_area: 9000
            max_area: 102500
      room:
        coordinates: 1396,319,1879,870,1571,1080,381,1080,385,973,795,941,742,338
        objects:
          - person
        filters:
          person:
            min_area: 66000
            max_area: 317550


  garage_cam:
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:      
      inputs:
        - path: rtsp://cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 5

    objects:
      track:
        - person
        - face
      filters:
        person:
          min_area: 5016
          max_area: 57630
          min_ratio: 0.15
          max_ratio: .6
          
    motion:
      mask:   
        - 0,33,407,21,409,0,0,0    
    

  driveway_cam:
    snapshots:
      enabled: True
      required_zones: []
    detect:
      fps: 5
    ffmpeg:      
      inputs:
        - path: rtsp:///driveway_sub
          roles:
            - detect
            - rtmp

    objects:
      track:
        - person
        - car
        - license_plate
        - dog
        - cat
        - face
        - amazon
        - ups
        - fedex
      mask:
        - 1061,0,1280,0,1280,216,1155,207,1099,191,1030,158,996,115,790,101,597,96,579,0
      filters:
        dog:
          mask:
            - 856,159,894,164,900,133,864,130
        car:
          mask: 
            - 948,181,1040,183,1085,0,1280,0,1280,426,1143,350,1034,368,766,280,639,193 
            - 240,0,565,0,575,115,244,156,0,200,0,0 
          min_area: 0
          max_area: 350000
          
    motion:
      mask:
        - 976,358,1280,411,1245,503,1146,671,1123,720,1280,720,1280,474,1280,0,0,0,0,137,374,69,562,72,642,113,801,110,882,104,1023,126,1019,215,933,226,818,229,792,287,834,293,899,327
        - 381,720,291,617,0,597,0,720 
    zones:
      sidewalk_zone:
        coordinates: 85,393,576,301,982,215,941,174,803,180,0,284,0,406
        objects:
          - person
          - face
          - dog
          - cat
          - amazon
        filters:
          person:
            min_area: 4225
            max_area: 29000
      driveway_car_zone:
        coordinates: 312,720,1016,720,1179,720,1200,611,1239,451,950,366,779,342,642,274,239,352
        objects:
          - car
          - license_plate
        filters:
          car:
            min_area: 40000
            max_area: 350000
      street_zone:          
        coordinates: 642,274,630,202,735,188,715,117,575,115,244,156,0,200,0,296,162,281,239,352
        objects:
          - person
          - car
          - dog
          - cat
          - face
          - amazon
          - ups
          - fedex
        filters:
          car:
            min_area: 5000
            max_area: 100000
          person:
            min_area: 600
            max_area: 15000
      driveway_person_zone:
        objects:
          - person
          - dog
          - cat
          - face
          - amazon
        coordinates: 34,720,1280,720,1280,394,1089,284,893,259,576,301,85,393
        filters:
          person:
            min_area: 7000
            max_area: 110000

  back_porch_cam:
    motion:
      mask:
        - 255,180,308,183,308,272,388,235,466,183,497,154,507,140,681,111,1146,297,1188,223,1280,242,1280,0,929,0,0,0,0,219
        - 767,464,906,475,926,328,773,316
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:
      inputs:
        - path: rtsp://10.0.1.35:3765/backyard_sub        
          roles:
            - detect
            - rtmp

    objects:
      track:
        - person
        - dog
        - cat
        - face
      mask:
        - 255,180,308,183,308,272,388,235,466,183,497,154,507,140,681,111,1146,297,1188,223,1280,242,1280,0,929,0,0,0,0,219
        - 767,464,906,475,926,328,773,316
      filters:
        dog:
          min_area: 572
          max_area: 16296
        cat:
          min_area: 572
          max_area: 16296
        person:
          min_area: 8000
          max_area: 121200
          min_ratio: 0.15
          max_ratio: .65
  back_dome_cam:
    motion:
      mask:
        - 0,0,0,288,174,193,739,175,968,241,1145,277,1280,273,1280,155,1280,0
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:
      inputs:
        - path: rtsp://10.0.1.35:3765/back_dome_sub        
          roles:
            - detect
            - rtmp

    objects:
      track:
        - person
        - dog
        - cat
        - face
      mask:
        - 0,0,0,288,174,193,739,175,968,241,1145,277,1280,273,1280,155,1280,0
      filters:
        dog:
          min_area: 650
          max_area: 19600
        cat:
          min_area: 650
          max_area: 19600
        person:
          min_area: 5000
          max_area: 184608
          min_ratio: 0.15
          max_ratio: .65

  front_yard_cam:
    snapshots:
      enabled: True
      required_zones: []
    ffmpeg:
      inputs:
        - path: rtsp://10.0.1.35:3765/front_yard_sub        
          roles:
            - detect
            - rtmp
            - record

    objects:
      track:
        - person
        - package
        - dog
        - cat
        - face
        - amazon
        - fedex
      mask:
        - 1280,82,1280,0,1077,0,0,0,0,584,396,342,359,74,635,70,763,68
      filters:
        dog:
          min_area: 26132
        cat:
          min_area: 26132
    motion:
      mask:
        - 0,0,969,0,1280,0,1280,127,1047,120,1013,146,929,138,872,113,725,99,354,111,376,257,146,303,244,662,146,689,0,232
        - 542,681,844,346,632,316,372,485,332,551

    zones:
      yard_zone:
        coordinates: 1280,720,1280,320,1205,313,1196,286,580,224,383,223,392,340,586,415,303,612,212,720
        filters:
          person:
            min_area: 8000
            max_area: 120000
      sidewalk_zone:
        coordinates: 1280,294,580,223,594,183,992,204,1280,237
        filters:
          person:
            min_area: 4200
            max_area: 19500
      porch_zone:
        coordinates: 187,673,573,414,386,346,0,513,0,720,145,720
        filters:
          person:
            min_area: 10000
            max_area: 120000
  
  doorbell_cam:
    snapshots:
      enabled: True
      required_zones:
        - porch_zone
    mqtt:
      required_zones:
        - porch_zone
    ffmpeg:
      inputs:
        - path: rtsp://10.0.1.35:3765/doorbell_sub        
          roles:
            - detect
            - rtmp
            - record
    
    objects:
      mask:
        - 0,720,180,652,128,477,0,492
      track:
        - person
        - dog
        - cat
        - face
        - package
        - amazon
        - ups
        - fedex

    motion:
      mask:
        - 0,1,0,93,561,167,658,266,619,317,619,415,700,428,682,720,1280,720,1280,0,2,3


    zones:
      porch_zone:
        coordinates: 0,720,983,720,1035,544,541,496,428,452,0,485
        filters:
          person:
            min_area: 7590
```

### Relevant log output

```shell
"before": {
            "id": "1698110981.905157-usayyy",
            "camera": "front_yard_cam",
            "frame_time": 1698110981.905157,
            "snapshot": null,
            "label": "person",
            "sub_label": null,
            "top_score": 0,
            "false_positive": true,
            "start_time": 1698110981.905157,
            "end_time": null,
            "score": 0.828125,
            "box": [
                776,
                303,
                805,
                344
            ],
            "area": 1189,
            "ratio": 0.7073170731707317,
            "region": [
                765,
                185,
                1085,
                505
            ],
            "stationary": false,
            "motionless_count": 0,
            "position_changes": 0,
            "current_zones": [], <-- object is in the yard zone. Should be indicated
            "entered_zones": [],
            "has_clip": false,
            "has_snapshot": false,
            "attributes": {},
            "current_attributes": []
        },
        "after": {
            "id": "1698110981.905157-usayyy",
            "camera": "front_yard_cam",
            "frame_time": 1698110982.39994,
            "snapshot": {
                "frame_time": 1698110982.39994,
                "box": [
                    775,
                    303,
                    805,
                    347
                ],
                "area": 1320,
                "region": [
                    765,
                    142,
                    1085,
                    462
                ],
                "score": 0.87890625,
                "attributes": []
            },
            "label": "person",
            "sub_label": null,
            "top_score": 0.87890625,
            "false_positive": false, <-- should be true because it is smaller than my area requirements for yard_zone
            "start_time": 1698110981.905157,
            "end_time": null,
            "score": 0.87890625,
            "box": [
                775,
                303,
                805,
                347
            ],
            "area": 1320,
            "ratio": 0.6818181818181818,
            "region": [
                765,
                142,
                1085,
                462
            ],
            "stationary": false,
            "motionless_count": 1,
            "position_changes": 1,
            "current_zones": [], <-- object is in the yard zone. Should be indicated
            "entered_zones": [],
            "has_clip": false,
            "has_snapshot": true,
            "attributes": {},
            "current_attributes": []
        },
        "type": "new"
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1280x720
FPS: 16/1
```

### Frigate stats

```json
{"baby_cam":{"camera_fps":1.0,"capture_pid":342,"detection_enabled":1,"detection_fps":1.0,"ffmpeg_pid":350,"pid":322,"process_fps":1.0,"skipped_fps":0.0},"back_dome_cam":{"camera_fps":5.2,"capture_pid":357,"detection_enabled":1,"detection_fps":3.2,"ffmpeg_pid":367,"pid":333,"process_fps":5.2,"skipped_fps":0.0},"back_porch_cam":{"camera_fps":5.2,"capture_pid":355,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":368,"pid":331,"process_fps":5.2,"skipped_fps":0.0},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.2"},"104":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"114":{"cmdline":"python3 -u -m frigate","cpu":"6.7","cpu_average":"4","mem":"5.9"},"120":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"151":{"cmdline":"nginx: worker process","cpu":"0.4","cpu_average":"0","mem":"0.1"},"304":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"306":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"0","mem":"1.9"},"315":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(51)","cpu":"0.4","cpu_average":"0","mem":"0.1"},"316":{"cmdline":"frigate.detector.coral","cpu":"1.1","cpu_average":"1","mem":"2.2"},"317":{"cmdline":"frigate.output       ","cpu":"2.6","cpu_average":"2","mem":"2.1"},"321":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"322":{"cmdline":"frigate.process:baby_cam","cpu":"0.7","cpu_average":"0","mem":"2.3"},"323":{"cmdline":"frigate.process:garage_cam","cpu":"2.2","cpu_average":"2","mem":"2.1"},"325":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"326":{"cmdline":"frigate.process:driveway_cam","cpu":"3.7","cpu_average":"3","mem":"2.2"},"331":{"cmdline":"frigate.process:back_porch_cam","cpu":"2.2","cpu_average":"3","mem":"2.2"},"333":{"cmdline":"frigate.process:back_dome_cam","cpu":"3.7","cpu_average":"3","mem":"2.2"},"334":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.6"},"337":{"cmdline":"frigate.process:front_yard_cam","cpu":"1.9","cpu_average":"2","mem":"2.2"},"338":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"341":{"cmdline":"frigate.process:doorbell_cam","cpu":"1.5","cpu_average":"2","mem":"2.1"},"342":{"cmdline":"frigate.capture:baby_cam","cpu":"1.1","cpu_average":"0","mem":"2.0"},"343":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"344":{"cmdline":"frigate.capture:garage_cam","cpu":"0.7","cpu_average":"0","mem":"2.0"},"350":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.1.35:3765/eufy_cam -r 1 -vf fps=1,scale_vaapi=w=1920:h=1080,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.1","cpu_average":"1","mem":"0.8"},"351":{"cmdline":"frigate.capture:driveway_cam","cpu":"2.2","cpu_average":"2","mem":"2.0"},"352":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.6"},"353":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif -r 5 -vf fps=5,scale_vaapi=w=640:h=480,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"2","mem":"0.7"},"355":{"cmdline":"frigate.capture:back_porch_cam","cpu":"1.9","cpu_average":"2","mem":"2.0"},"356":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.5"},"357":{"cmdline":"frigate.capture:back_dome_cam","cpu":"1.5","cpu_average":"2","mem":"2.0"},"365":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"366":{"cmdline":"frigate.capture:front_yard_cam","cpu":"1.9","cpu_average":"2","mem":"2.0"},"367":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.1.35:3765/back_dome_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.2","cpu_average":"2","mem":"0.9"},"368":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.1.35:3765/backyard_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.0","cpu_average":"2","mem":"0.9"},"369":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.1.35:3765/driveway_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.0","cpu_average":"2","mem":"0.9"},"374":{"cmdline":"frigate.capture:doorbell_cam","cpu":"1.5","cpu_average":"2","mem":"2.0"},"386":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.1.35:3765/front_yard_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.6","cpu_average":"2","mem":"0.9"},"389":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-0858859 -user_agent FFmpeg Frigate/0.13.0-0858859 -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.1.35:3765/doorbell_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.6","cpu_average":"2","mem":"0.9"},"77584":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":4.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.31,"pid":316}},"doorbell_cam":{"camera_fps":5.1,"capture_pid":374,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":389,"pid":341,"process_fps":5.1,"skipped_fps":0.0},"driveway_cam":{"camera_fps":5.1,"capture_pid":351,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":369,"pid":326,"process_fps":5.1,"skipped_fps":0.0},"front_yard_cam":{"camera_fps":5.1,"capture_pid":366,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":386,"pid":337,"process_fps":5.1,"skipped_fps":0.0},"garage_cam":{"camera_fps":5.0,"capture_pid":344,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":353,"pid":323,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"3.45%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":304},"recording":{"pid":306}},"service":{"last_updated":1698116234,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":3902.1,"mount_type":"tmpfs","total":3920.3,"used":18.2},"/media/frigate/clips":{"free":180246.5,"mount_type":"ext4","total":234006.2,"used":44212.3},"/media/frigate/recordings":{"free":180246.5,"mount_type":"ext4","total":234006.2,"used":44212.3},"/tmp/cache":{"free":3920.3,"mount_type":"tmpfs","total":3920.3,"used":0.0}},"temperatures":{},"uptime":106478,"version":"0.13.0-0858859"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

dahua
