### ISSUE TITLE
[Support]: Dust/mosquito in the air trigger Birdseye 

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#8307]
### Describe the problem you are having

Hi 
I know it's sound weird but it's fact 
In the night the camera catch dust/mosquito in the air and it's trigger Birdseye 
In version 0.12 it's not trigger it (to be sure I downgrade the version)

What do you think?
How I can fix this issue?

### Version

0.13-beta2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.187
  user: mqttuser
  password: '****'

birdseye:
  enabled: true
  width: 1920
  height: 1080
  quality: 15
  mode: objects #motion


detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

go2rtc:
  streams:
    Entrance:
    - rtsp://****@192.168.1.127:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:Entrance#audio=opus
    Entrance_sub:
    - rtsp://*****@192.168.1.127:554/cam/realmonitor?channel=1&subtype=1

cameras:
  Entrance:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/Entrance_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/Entrance?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 1280
      height: 720
      fps: 20
    rtmp:
      enabled: false

    objects:
      track:
      - person
      - dog
      - cat
      filters:
        person:
          threshold: 0.73

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 900
      retain:
        default: 60

    record:
      enabled: true
      retain:
        days: 30
      events:
        pre_capture: 50
        post_capture: 50
        objects:
        - person
        - cat
        - dog
        retain:
          default: 30
    motion:
      mask:
      - 1280,0,1280,327,961,0
      - 1163,234,1280,431,1280,469,1130,444,807,0,852,0,894,0,1010,0
      - 472,460,635,473,631,336,483,319
      - 289,182,555,240,590,108,360,64
    zones:
     #zone_entrance:
     #  coordinates: 74,720,563,611,768,565,993,497,1046,636,806,720,95,720,880,533,734,199,583,308,455,410,303,540,91,699,119,454,195,249,326,51,739,189
     #    zones:
      zone_entrance:
        coordinates: 
          74,720,576,566,923,449,768,565,804,490,844,720,806,720,95,720,984,440,831,133,594,316,466,419,303,540,91,699,119,454,195,249,321,0,819,140
        objects:
        - person
        - dog
        - cat
```

### Relevant log output

```shell
If relevant I will add
```

### FFprobe output from your camera

```shell
If relevant I will add
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

If relevant I will add

**Comment by NickM-27** [comment]
There is nothing to go off of here, there have been many changes to motion and object detection that could lead to birdseye triggering the camera. 

at a minimum we'd need to see your config, but what you're describing doesn't sound abnormal

**Comment by antonbek89** [comment]
> There is nothing to go off of here, there have been many changes to motion and object detection that could lead to birdseye triggering the camera.
> 
> at a minimum we'd need to see your config, but what you're describing doesn't sound abnormal

Yes I know it sounds abnormal
I did the test several times before I opened this ticket - same place - same configuration -same camera - different versions 0.12 vs 0.13-beta-2
As I said at 0.13-beta-2 Birdseye every 5-10 sec was triggered. In 0.12:stable version, it works perfectly
When I debug the stream via Frigate the Regions going crazy

This is my configuration, very standard I guess

```
mqtt:
  host: 192.168.1.187
  user: mqttuser
  password: '****'

birdseye:
  enabled: true
  width: 1920
  height: 1080
  quality: 15
  mode: objects #motion


detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

    Entrance:
    - rtsp://****@192.168.1.127:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:Entrance#audio=opus
    Entrance_sub:
    - rtsp://*****@192.168.1.127:554/cam/realmonitor?channel=1&subtype=1

cameras:
  Entrance:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/Entrance_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/Entrance?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 1280
      height: 720
      fps: 20
    rtmp:
      enabled: false

    objects:
      track:
      - person
      - dog
      - cat
      filters:
        person:
          threshold: 0.73

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 900
      retain:
        default: 60

    record:
      enabled: true
      retain:
        days: 30
      events:
        pre_capture: 50
        post_capture: 50
        objects:
        - person
        - cat
        - dog
        retain:
          default: 30
    motion:
      mask:
      - 1280,0,1280,327,961,0
      - 1163,234,1280,431,1280,469,1130,444,807,0,852,0,894,0,1010,0
      - 472,460,635,473,631,336,483,319
      - 289,182,555,240,590,108,360,64
    zones:
     #zone_entrance:
     #  coordinates: 74,720,563,611,768,565,993,497,1046,636,806,720,95,720,880,533,734,199,583,308,455,410,303,540,91,699,119,454,195,249,326,51,739,189
     #    zones:
      zone_entrance:
        coordinates: 
          74,720,576,566,923,449,768,565,804,490,844,720,806,720,95,720,984,440,831,133,594,316,466,419,303,540,91,699,119,454,195,249,321,0,819,140
        objects:
        - person
        - dog
        - cat
```
