### ISSUE TITLE
[Config Support]: Change recording quality

### ISSUE THREAD

**Issue by FinnakaLite** [blakeblackshear/frigate#8308]
### Describe the problem you are having

I want to use 24/7 recording but want to reduce the quality so the files are not that big. I can't find out anywhere how to do this, though, in the "full configuration reference," other components for example, "live" have the option to change the height and quality 

```
 Optional: jsmpeg stream configuration for WebUI
live:
   Optional: Set the name of the stream that should be used for live view
   in frigate WebUI. (default: name of camera)
  stream_name: camera_name

Focus on this:

  Optional: Set the height of the jsmpeg stream. (default: 720)
   This must be less than or equal to the height of the detect stream. Lower resolutions
   reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 720
   Optional: Set the encode quality of the jsmpeg stream (default: shown below)
   1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
```

How do I do this for recording? 

My bad if this is not a feature, just something that I kinda assumed existed. The config file below is a test config since I'm still just playing around with Frigate for now.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False

go2rtc:
  streams:
    name_of_your_camera: # <- for RTSP streams
      - rtsp://zephyr.rtsp.stream/pattern?streamKey=75d26805f4c8410c1cdc128f598c4090 # <- stream which supports video & aac audio
      - "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
      
cameras:
  name_of_your_camera:
    ffmpeg:
      inputs:
        - path: rtsp://zephyr.rtsp.stream/pattern?streamKey=75d26805f4c8410c1cdc128f598c4090
          roles:
            - detect
            - record

    detect:
      width: 1280
      height: 720

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: motion
```

### Relevant log output

```shell
Log output not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Easiest way to do that will be using go2rtc

**Comment by FinnakaLite** [comment]
> Easiest way to do that will be using go2rtc

Im unsure what you mean? Do you mean to create an internal loop by re-streaming it? Or create another container running go2rtc?

Thanks,
Finn

**Comment by NickM-27** [comment]
using the internal go2rtc change the quality.

```
go2rtc:
  streams:
    name_of_your_camera: # <- for RTSP streams
      - "ffmpeg:rtsp://zephyr.rtsp.stream/pattern?streamKey=75d26805f4c8410c1cdc128f598c4090#video=h264#width=x#height=y#hardware" # <- stream which supports video & aac audio
      - "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
```
