### ISSUE TITLE
[Support]: Mask & Zone Creator not working in Brave Browser

### ISSUE THREAD

**Issue by maxirus** [blakeblackshear/frigate#8309]
### Describe the problem you are having

The Mask & Zone creator does not work in the Brave Browser. In Developer tools, I get the following JS error when I click anywhere in the image:
![image](https://github.com/blakeblackshear/frigate/assets/1676208/f6c243ce-d462-4156-a71a-25b5cdb35be7)

```console
Uncaught TypeError: Cannot read properties of undefined (reading 'reduce')
    at Object.clickfalse (CameraMap-0e4b28dd.js:14:459)
    at HTMLDivElement.Gn (index-40e1e50b.js:1:4930)
```

### Version

0.12.1

### Frigate config file

```yaml
ui:
  live_mode: mse

birdseye:
  enabled: True
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    doorbell:
      - "rtsp://user:{FRIGATE_DOORBELL_PASSWORD}@<doorbell_ip>:554/cam/realmonitor?channel=1&subtype=0&audio=aac"
      - "ffmpeg:doorbell#audio=opus"
    doorbell_sub:
      - "rtsp://user:{FRIGATE_DOORBELL_PASSWORD}@<doorbell_ip>:554/cam/realmonitor?channel=1&subtype=1&audio=aac"
      - "ffmpeg:doorbell_sub#audio=opus"
    driveway_walkway:
      - "rtsp://user:{FRIGATE_WALKWAY_PASSWORD}@<cam2_ip>:554/h264Preview_01_main"
      - "ffmpeg:driveway_walkway#audio=opus"
    driveway_walkway_sub:
      - "rtsp://user:{FRIGATE_WALKWAY_PASSWORD}@<cam2_ip>:554/h264Preview_01_sub"
      - "ffmpeg:driveway_walkway_sub#audio=opus"
    pool:
      - "rtsp://user:{FRIGATE_POOL_PASSWORD}@<cam3_ip>:554/h264Preview_01_main"
      - "ffmpeg:pool#audio=opus"
    pool_sub:
      - "rtsp://user:{FRIGATE_POOL_PASSWORD}@<cam3_ip>:554/h264Preview_01_sub"
      - "ffmpeg:pool#audio=opus"

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/doorbell_sub"
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: "rtsp://127.0.0.1:8554/doorbell"
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
    detect:
      enabled: True
      width: 720
      height: 576

  walkway:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/driveway_walkway_sub"
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: "rtsp://127.0.0.1:8554/driveway_walkway"
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
    detect:
      enabled: True
      width: 640
      height: 480
  
  pool:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/pool_sub"
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: "rtsp://127.0.0.1:8554/pool"
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
    detect:
      enabled: True
      width: 640
      height: 480
```

### Relevant log output

```shell
2023-10-24 20:15:36.708308570  <client_ip> - - [24/Oct/2023:20:15:36 +0000] "GET /api/config HTTP/1.1" 200 11790 "http://frigate/cameras/doorbell/editor" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"3.8"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"2.7","mem":"2.4"},"118":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"141":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"20865":{"cpu":"1.7","mem":"0.3"},"20876":{"cpu":"2.3","mem":"0.5"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"0.9"},"288":{"cpu":"0.7","mem":"0.1"},"289":{"cpu":"1.0","mem":"1.3"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"1.7","mem":"1.1"},"297":{"cpu":"1.3","mem":"1.2"},"298":{"cpu":"0.0","mem":"0.2"},"299":{"cpu":"2.3","mem":"1.3"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"1.3","mem":"1.3"},"301":{"cpu":"0.0","mem":"0.2"},"302":{"cpu":"1.7","mem":"1.0"},"304":{"cpu":"3.0","mem":"1.0"},"308":{"cpu":"3.7","mem":"1.0"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"3.3","mem":"0.5"},"313":{"cpu":"2.7","mem":"0.5"},"316":{"cpu":"0.0","mem":"0.2"},"319":{"cpu":"2.0","mem":"0.3"},"32":{"cpu":"0.0","mem":"0.0"},"322":{"cpu":"0.0","mem":"0.2"},"323":{"cpu":"1.0","mem":"0.3"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79600":{"cpu":"0.0","mem":"0.0"},"79616":{"cpu":"0.3","mem":"0.0"},"79617":{"cpu":"0.0","mem":"0.0"},"79618":{"cpu":"46.7","mem":"0.5"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"17.0","mem":"0.3"},"MiB":{"cpu":"6520.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"1.84,"}},"detection_fps":4.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":13.68,"pid":289}},"doorbell":{"camera_fps":5.0,"capture_pid":302,"detection_enabled":1,"detection_fps":3.5,"ffmpeg_pid":20876,"pid":297,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"pool":{"camera_fps":5.0,"capture_pid":308,"detection_enabled":1,"detection_fps":0.8,"ffmpeg_pid":313,"pid":300,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1698178636,"latest_version":"disabled","storage":{"/dev/shm":{"free":127.7,"mount_type":"tmpfs","total":134.2,"used":6.6},"/media/frigate/clips":{"free":9573254.8,"mount_type":"nfs4","total":9652933.1,"used":79678.3},"/media/frigate/recordings":{"free":9573254.8,"mount_type":"nfs4","total":9652933.1,"used":79678.3},"/tmp/cache":{"free":991.9,"mount_type":"tmpfs","total":1000.0,"used":8.1}},"temperatures":{},"uptime":65807,"version":"0.12.1-367d724"},"walkway":{"camera_fps":5.1,"capture_pid":304,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":310,"pid":299,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink, Amcrest
