### ISSUE TITLE
[Config Support]: Zone config. I think I understand this wrong.

### ISSUE THREAD

**Issue by pjfian** [blakeblackshear/frigate#8311]
### Describe the problem you are having

Been using frigate for almost 2 years now, and thought I understood most things, but I've obviously set my zones up incorrectly, or I've misunderstood how they work.

I'm wanting to create events for cars entering or leaving my driveway, but not necessarily track them while parked on the driveway. I have a zone that covers the driveway entry, and a seperate zone that covers the rest of the driveway, where I'm only interested in tracking people, animals, and packages. As you can see from the attached image, cars are being tracked while the bottom centre of the bounding box is well away from the zone.

Zone objects are set how I think they should be, with car, and licence_plate in the driveway entry zone, and perso, face, package, cat, and dog set in the other zone.

I have required zones set for both recording and snapshot.

![Screenshot 2023-10-25 083407](https://github.com/blakeblackshear/frigate/assets/30766147/d4e2d2c8-b0e3-4c42-9893-b41142fae18f)

### Version

0.13.0

### Frigate config file

```yaml
cameras:
#############################################
###############   Driveway   ################
#############################################
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_driveway_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    live:
      stream_name: cam_driveway_sub
    audio:
      min_volume: 1000
    record:
      enabled: true
      events:
        required_zones:
          - zne_driveway_entry
          - zne_footpath
          - zne_driveway
    detect:
      height: 720
      width: 1280
      fps: 7
    motion:
      mask:
        - 249,0,492,0,488,22,260,49,67,98,22,0
    objects:
      track:
        - package
        - person
        - dog
        - cat
        - face
        - license_plate
        - car
    zones:
      zne_driveway:
        coordinates: 492,536,48,625,38,354,83,214,539,126,910,340
        objects:
          - person
          - package
          - face
          - cat
          - dog
      zne_driveway_entry:
        coordinates: 613,137,942,315,970,219,706,120
        objects:
          - car
          - license_plate
      zne_footpath:
        coordinates: 1280,323,1280,266,1036,163,710,68,704,98,1038,200
        objects:
          - person
          - cat
          - dog
    snapshots:
      required_zones:
        - zne_driveway
        - zne_driveway_entry
        - zne_footpath
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 600
```

### Relevant log output

```shell
no errors
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2
