### ISSUE TITLE
[Support]: Birdseye canvas does not support 2:1 aspect ratio

### ISSUE THREAD

**Issue by Majestic7979** [blakeblackshear/frigate#8317]
### Describe the problem you are having

<img width="361" alt="image" src="https://github.com/blakeblackshear/frigate/assets/128995501/73d4c358-a4e6-4df0-b7eb-beaeb4a18426">

Self explanatory... I understand the black space where the red X is drawn, but the huge black space enclosed within the yellow rectangle is just dumb. I use wall mounted tablets around the house to display the birdseye view as a "screensaver" that goes away when I touch the tablet screen, so that I can have a quick glance at my home's perimeter when I'm not using the tablet.

And that empty space means I get smaller camera views because most of the space is wasted with the black empty space.

### Version

0.13.0-9A4F970

### Frigate config file

```yaml
birdseye:
  enabled: true
  restream: true
  width: 2592
  height: 1944
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  mode: continuous
```
```


### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wired

### Camera make and model

Not relevant but resolution is 2592x1944
