### ISSUE TITLE
False Positives - How to best reduce them 

### ISSUE THREAD

**Issue by Solarflor** [blakeblackshear/frigate#8319]
### Describe the problem you are having

Below a nice cut that visited me in the middle of the night.

![image](https://github.com/blakeblackshear/frigate/assets/100423265/ab343bd5-7c60-42e9-9c54-5f689d73e86c)

To avoid being woken up by surprise in the middle of the night I used the following config

```
  Cancello: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:passwd@192.168.1.208:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://admin:passwd@192.168.1.208:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
#            - rtmp
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - cat
        - dog
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    zones:
      zone_3:
        coordinates: 667,210,1280,476,1280,720,304,720,107,409
        filters:
          person:
            min_area: 13000

```
What was wrong?

### Version

0.12.1-367d724

### Frigate config file

```yaml
See above
```

### Relevant log output

```shell
None
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

**Comment by Solarflor** [comment]
Not sure I have understood.

**Comment by NickM-27** [comment]
You have defined a zone in your config with min_area

```
    zones:
      zone_3:
        coordinates: 667,210,1280,476,1280,720,304,720,107,409
        filters:
          person:
            min_area: 13000
```

however, this zone is not currently [required for events](https://docs.frigate.video/configuration/zones#restricting-events-to-specific-zones)

so while the "person" (cat) was not considered in the zone, it was still detected and had an event created because you have not configured frigate to require the zone for events.

In short, you should either make these zones required or you should apply the min_area filter to the camera globally and not the camera zone

**Comment by Solarflor** [comment]
Not sure what is the best way.
I would avoid that an object of dimension lower than 13000 could be classified as Person.

I have tried to move the three rows below directly under camera but it seems that "Property filter is not allowed" 
```
        filters:
          person:
            min_area: 13000
```

**Comment by NickM-27** [comment]
to apply to the camera globally would look like this

```yaml
  Cancello: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:passwd@192.168.1.208:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://admin:passwd@192.168.1.208:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
#            - rtmp
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - cat
        - dog
      filters:
          person:
            min_area: 13000
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
    zones:
      zone_3:
        coordinates: 667,210,1280,476,1280,720,304,720,107,409
```
