### ISSUE TITLE
[Support]: Corrupted image buffer

### ISSUE THREAD

**Issue by 0anton** [blakeblackshear/frigate#8324]
### Describe the problem you are having

Image buffer is often corrupted: parts of the image are from the other camera.

Sample I
![image](https://github.com/blakeblackshear/frigate/assets/17309924/9ad05320-ef43-437f-a6ce-759ba012f9a2)
You can see that half of the screen is coming from _Camera4_ and the other half - from _Camera1_.

**Sample II**
![image](https://github.com/blakeblackshear/frigate/assets/17309924/7e9357cd-5c1d-4de7-a9d0-0ebe52669e69)

These screens is not just a browser glitch - this is how Frigate really sees the image and perform the entity recognition.
I can confirm this by checking the MQTT image data.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: xx.xx.xx.165
  user: mqtt
  password: mqtt
detectors:
  coral:
    type: edgetpu
    device: pci

logger:
  default: info

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@xx.xx.xx.148:554/h265Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True
    snapshots:
      enabled: True
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@xx.xx.xx.194:554/h265Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True
    snapshots:
      enabled: True
  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@xx.xx.xx.107:554/h265Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True
    snapshots:
      enabled: True

  camera4:
    ffmpeg:
      inputs:
        # - path: rtsp://user:password@xx.xx.xx.172:554/h264Preview_01_sub
        - path: rtsp://user:password@xx.xx.xx.172:554/h265Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True
    snapshots:
      enabled: True



record:
  enabled: False
  events:
    # capture 1 sec before and after event
    pre_capture: 1
    post_capture: 1



detect:
  fps: 5
  width: 2560
  height: 1440

objects:
  track:
    - person

ffmpeg:
  hwaccel_args: preset-vaapi
```

### Relevant log output

```shell
No errors in log
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{"camera1":{"camera_fps":5.1,"capture_pid":301,"detection_enabled":1,"detection_fps":1.5,"ffmpeg_pid":307,"pid":294,"process_fps":5.1,"skipped_fps":0.0},"camera2":{"camera_fps":5.0,"capture_pid":304,"detection_enabled":1,"detection_fps":5.0,"ffmpeg_pid":322,"pid":298,"process_fps":5.0,"skipped_fps":0.0},"camera3":{"camera_fps":5.1,"capture_pid":308,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":333,"pid":299,"process_fps":5.1,"skipped_fps":0.0},"camera4":{"camera_fps":5.0,"capture_pid":320,"detection_enabled":1,"detection_fps":6.2,"ffmpeg_pid":9433,"pid":300,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"3.6"},"1":{"cpu":"0.0","mem":"0.0"},"10000":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"4.0","mem":"4.4"},"118":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"1.0"},"288":{"cpu":"0.3","mem":"0.1"},"289":{"cpu":"5.3","mem":"1.6"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"4.0","mem":"1.6"},"294":{"cpu":"6.0","mem":"2.0"},"298":{"cpu":"2.0","mem":"2.0"},"299":{"cpu":"1.7","mem":"2.0"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"18.3","mem":"2.1"},"301":{"cpu":"8.3","mem":"1.5"},"304":{"cpu":"9.0","mem":"1.5"},"307":{"cpu":"10.0","mem":"1.4"},"308":{"cpu":"9.3","mem":"1.5"},"309":{"cpu":"0.0","mem":"0.7"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"8.6","mem":"1.5"},"322":{"cpu":"10.6","mem":"1.3"},"325":{"cpu":"0.0","mem":"0.8"},"331":{"cpu":"0.0","mem":"0.8"},"333":{"cpu":"9.6","mem":"1.4"},"334":{"cpu":"0.0","mem":"0.9"},"336":{"cpu":"0.0","mem":"0.7"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.3"},"9433":{"cpu":"10.6","mem":"1.5"},"9988":{"cpu":"0.0","mem":"0.0"},"9994":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"5647.0","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":12.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.11,"pid":289}},"gpu_usages":{"intel-vaapi":{"gpu":"3.76 %","mem":"- %"}},"service":{"last_updated":1698266294,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":238.8,"mount_type":"tmpfs","total":268.4,"used":29.6},"/media/frigate/clips":{"free":179991.7,"mount_type":"ext4","total":249365.4,"used":56632.1},"/media/frigate/recordings":{"free":179991.7,"mount_type":"ext4","total":249365.4,"used":56632.1},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{"apex_0":55.8},"uptime":10254,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink 811A
