### ISSUE TITLE
[Support]: Not able to get sound and good stream to homeassistant

### ISSUE THREAD

**Issue by cryd-s** [blakeblackshear/frigate#8330]
### Describe the problem you are having

Hi there,

if tried now severals days to get audio in the livestream and a good stream to homeassistant.
But i failed.

Someone here who can help me?

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.199
  user: mqtt_user
  password: xxx

database:
  path: /config/frigate.db

ffmpeg:
  hwaccel_args: preset-vaapi


detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    garten: 
      - "ffmpeg:http://192.168.178.161/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx"
      - "ffmpeg:reolink#audio=opus"
    garten_sub: 
      - "ffmpeg:http://192.168.178.161/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxx"

cameras:
  Garten:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garten?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garten_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - cat
        - dog 
      filters:
        person:
          threshold: 0.74
        cat:
          threshold: 0.8
        dog:
          threshold: 0.8
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 14
    motion:
      mask:
        - 0,0,2560,0,640,0,525,86,444,93,390,104,366,134,320,149,288,137,240,105,200,121,132,189,52,201,0,248
        - 2403,595,2462,718,2441,817,2414,880,2313,899,2224,872,2167,851,2137,781,2163,664,2259,601,2348,469
    ui:
      order: 1
```

### Relevant log output

```shell
2023-10-26 09:35:17.716338894  09:35:17.716 DBG [exec] run url="exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.168.178.161/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=seat001 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/7e0cb6a8780e7664b2b7f37b823b2c14"


2023-10-26 09:35:20.038903894  Input #0, flv, from 'http://192.168.178.161/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=seat001':
2023-10-26 09:35:20.038907391    Metadata:
2023-10-26 09:35:20.038908353      displayWidth    : 2560
2023-10-26 09:35:20.038909204      displayHeight   : 1440
2023-10-26 09:35:20.038910096    Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
2023-10-26 09:35:20.038911038    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 24 fps, 30 tbr, 1k tbn
2023-10-26 09:35:20.038913022    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
2023-10-26 09:35:20.043773457  09:35:20.043 DBG [exec] run launch=2.280052662s
2023-10-26 09:35:20.044228648  Output #0, rtsp, to 'rtsp://localhost:8554/21fec4af85a6619ac023de32aba8d44d':
2023-10-26 09:35:20.044230742    Metadata:
2023-10-26 09:35:20.044231643      displayWidth    : 896
2023-10-26 09:35:20.044232385      displayHeight   : 672
2023-10-26 09:35:20.044233196      encoder         : Lavf59.27.100
2023-10-26 09:35:20.044234579    Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x672, q=2-31, 16 fps, 30 tbr, 90k tbn
2023-10-26 09:35:20.044235440    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
2023-10-26 09:35:20.044236152  Stream mapping:
2023-10-26 09:35:20.044236903    Stream #0:0 -> #0:0 (copy)
2023-10-26 09:35:20.044237665    Stream #0:1 -> #0:1 (copy)
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":672,"width":896}]}}]


Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1440
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 896x672
FPS: Unknown
```

### Frigate stats

```json
{"Einfahrt":{"camera_fps":10.2,"capture_pid":709,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":730,"pid":696,"process_fps":10.2,"skipped_fps":0.0},"Garage":{"camera_fps":10.1,"capture_pid":712,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1674,"pid":697,"process_fps":10.1,"skipped_fps":0.0},"Garten":{"camera_fps":10.1,"capture_pid":700,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":704,"pid":692,"process_fps":10.1,"skipped_fps":0.0},"Garten_2":{"camera_fps":10.1,"capture_pid":703,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":727,"pid":694,"process_fps":10.1,"skipped_fps":0.0},"Garten_3":{"camera_fps":10.1,"capture_pid":705,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":717,"pid":695,"process_fps":10.1,"skipped_fps":0.0},"Haustuer":{"camera_fps":10.1,"capture_pid":716,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":735,"pid":698,"process_fps":10.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"102":{"cpu":"0.0","mem":"0.0"},"1033":{"cpu":"0.0","mem":"0.0"},"1034":{"cpu":"0.7","mem":"0.0"},"104":{"cpu":"3.0","mem":"0.3"},"119":{"cpu":"0.0","mem":"0.0"},"123":{"cpu":"0.0","mem":"0.0"},"124":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"130":{"cpu":"0.0","mem":"0.0"},"131":{"cpu":"0.0","mem":"0.0"},"132":{"cpu":"0.0","mem":"0.0"},"133":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"1674":{"cpu":"1.3","mem":"0.1"},"1676":{"cpu":"0.7","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"2851":{"cpu":"0.0","mem":"0.0"},"2882":{"cpu":"0.0","mem":"0.0"},"2885":{"cpu":"1.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"44":{"cpu":"0.0","mem":"0.0"},"677":{"cpu":"0.0","mem":"0.1"},"683":{"cpu":"0.3","mem":"0.0"},"684":{"cpu":"0.0","mem":"0.2"},"686":{"cpu":"1.3","mem":"0.1"},"692":{"cpu":"0.7","mem":"0.1"},"693":{"cpu":"0.0","mem":"0.0"},"694":{"cpu":"0.3","mem":"0.1"},"695":{"cpu":"0.3","mem":"0.1"},"696":{"cpu":"0.3","mem":"0.1"},"697":{"cpu":"1.0","mem":"0.1"},"698":{"cpu":"0.7","mem":"0.1"},"699":{"cpu":"0.0","mem":"0.1"},"700":{"cpu":"1.0","mem":"0.1"},"703":{"cpu":"0.7","mem":"0.1"},"704":{"cpu":"1.3","mem":"0.1"},"705":{"cpu":"0.7","mem":"0.1"},"706":{"cpu":"0.0","mem":"0.1"},"709":{"cpu":"1.0","mem":"0.1"},"712":{"cpu":"0.7","mem":"0.1"},"713":{"cpu":"0.0","mem":"0.1"},"714":{"cpu":"1.0","mem":"0.0"},"716":{"cpu":"0.7","mem":"0.1"},"717":{"cpu":"1.0","mem":"0.1"},"724":{"cpu":"0.3","mem":"0.0"},"725":{"cpu":"0.0","mem":"0.0"},"727":{"cpu":"1.3","mem":"0.1"},"730":{"cpu":"1.0","mem":"0.1"},"733":{"cpu":"1.3","mem":"0.0"},"734":{"cpu":"0.3","mem":"0.0"},"735":{"cpu":"1.3","mem":"0.1"},"736":{"cpu":"0.0","mem":"0.0"},"742":{"cpu":"1.3","mem":"0.0"},"745":{"cpu":"0.3","mem":"0.0"},"750":{"cpu":"1.0","mem":"0.0"},"751":{"cpu":"0.0","mem":"0.0"},"752":{"cpu":"0.3","mem":"0.0"},"754":{"cpu":"1.3","mem":"0.0"},"761":{"cpu":"0.7","mem":"0.0"},"762":{"cpu":"1.0","mem":"0.0"},"764":{"cpu":"1.0","mem":"0.0"},"774":{"cpu":"0.7","mem":"0.0"},"775":{"cpu":"0.3","mem":"0.0"},"777":{"cpu":"1.7","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.3","mem":"0.0"},"89":{"cpu":"3.7","mem":"0.0"},"MiB":{"cpu":"45130.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.72,"pid":684}},"gpu_usages":{"amd-vaapi":{"gpu":"6.67 %","mem":"52.52 %"}},"service":{"last_updated":1698306528,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":127.1,"mount_type":"tmpfs","total":134.2,"used":7.1},"/media/frigate/clips":{"free":697584.7,"mount_type":"cifs","total":1099511.6,"used":401926.9},"/media/frigate/recordings":{"free":697584.7,"mount_type":"cifs","total":1099511.6,"used":401926.9},"/tmp/cache":{"free":983.0,"mount_type":"tmpfs","total":1000.0,"used":17.0}},"temperatures":{},"uptime":811,"version":"0.12.1-367d724"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 410W and Reolink 510WA (Gartencam) and Reolink Doorbell
