### ISSUE TITLE
[Config Support]: only keep events and snapshots for 3 days then delete

### ISSUE THREAD

**Issue by Nicko33127** [blakeblackshear/frigate#8331]
### Describe the problem you are having

I am trying Frigate as an add on within Home Assistant  (OS) on my mini pc.
I was able to create the config file but I am having issues with deleting the record.

I only want records sent to my phone when I'm not home and kept for 3 days.
My current config file is (removed personal details):
mqtt:
  host: xxxxxxxxxxx
  user: xxxxxxxx
  password: xxxxxxxxxx

cameras:
  garage_cam:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxx/stream1
          roles:
            - record
        - path: rtsp://xxxxxxxxxxxxxx/stream2
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 10
    objects:
      track:
        - person
        - dog

snapshots:
  enabled: True

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 3
      mode: motion
      objects:
        person: 3

objects:
  filters:
    person:
      mask:
        - 497,579,802,414,706,0,455,29

motion:
  mask:
    - 608,750,789,729,1122,576,994,0,411,0

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

Stream1 is the low res camera feed that I want to use to detect activity while stream 2 is the HD one for recording and snapshop.

The recording doesn't seem to be automatically deleted after 3 days and I had to do this manually as the media folder starter to fill up too quickly.

I wish to only record snapshot and events recordings when activity is seen by the camera. I added the blueprint in home assistant to send the snapshot/video and this works well, but I need to figure out how to only keep the records I want and for a specific time.

I also need to work out how to save this into a ssd plugged in on my pc (potentially using samba in home assistant) but this is a problem for another day when I want to add more cameras.

### Version

 0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: xxxxxxxxxxx
  user: xxxxxxxx
  password: xxxxxxxxxx

cameras:
  garage_cam:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxx/stream1
          roles:
            - record
        - path: rtsp://xxxxxxxxxxxxxx/stream2
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 10
    objects:
      track:
        - person
        - dog

snapshots:
  enabled: True

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 3
      mode: motion
      objects:
        person: 3

objects:
  filters:
    person:
      mask:
        - 497,579,802,414,706,0,455,29

motion:
  mask:
    - 608,750,789,729,1122,576,994,0,411,0

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other
