### ISSUE TITLE
[Detector Support]: Frigate 0.13.0-0858859 will not start with audio detectors enabled

### ISSUE THREAD

**Issue by jamesahendry** [blakeblackshear/frigate#8332]
### Describe the problem you are having

When I enable the new audio detectors per beta doco Frigate will not start.
https://deploy-preview-6262--frigate-docs.netlify.app/configuration/audio_detectors

I have simply added the following to a working configuration.

audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    

### Version

0.13.0-0858859

### Frigate config file

```yaml
birdseye:
  enabled: True
  mode: continuous

record:
  enabled: True
  events:
    retain:
      default: 30
      mode: active_objects
#logger:
#  logs:
#    frigate.record: debug

go2rtc:
  streams:
    frontdrive_cam:
#      - rtsp://admin:mypassword@10.0.45.20:554/h264Preview_02_main
      - "ffmpeg:rtsp://10.0.45.26:8554/driveway#video=copy#audio=copy#audio=aac"

    backbbq_cam:
      - "ffmpeg:rtsp://10.0.45.28:8554/backbbq#video=copy#audio=copy#audio=aac"

    backbins_cam:
      - "ffmpeg:rtsp://10.0.45.27:8554/backgarage#video=copy#audio=copy#audio=aac"

    backgrass_cam:
      - "ffmpeg:rtsp://10.0.45.29:8554/backgrass#video=copy#audio=copy#audio=aac"

    frontgrass_cam:
      - rtsp://admin:mypassword@10.0.45.81:554/h264Preview_01_main
  #    - "ffmpeg:rtsp://10.0.45.22:8554/frontgrass#video=copy#audio=copy#audio=aac"
    frontdoor_cam:
      - "ffmpeg:rtsp://10.0.45.24:8554/frontdoor#video=copy#audio=copy#audio=aac"

    courtyard_cam:
      - "ffmpeg:rtsp://10.0.45.25:8554/courtyard#video=copy#audio=copy#audio=aac"
    pool_cam:
      - rtsp://admin:@10.0.45.79:554/h264Preview_01_main
#    subpool_cam:
#      - rtsp://admin:@10.0.45.79:554/h264Preview_01_sub



#    subcourtyard_cam:
 #     - rtsp://10.0.45.25:8554/courtyard/subStream
      
      
#    subbackbbq_cam:
#      - rtsp://10.0.45.28:8554/backbbq/subStream
   

 #   subfrontdoor_cam:
 #     - rtsp://10.0.45.24:8554/frontdoor/subStream
 #   subbackgrass_cam:
 #     - rtsp://10.0.45.29:8554/backgrass/subStream
      
 #   subbackbins_cam:
 #     - rtsp://10.0.45.27:8554/backgarage/subStream

#    subfrontdrive_cam:
#      - rtsp://10.0.45.22:8554/driveway/subStream  
#    subfrontgrass_cam:
#     - rtsp://admin:@10.0.45.81:554/h264Preview_01_sub

 # webrtc:
 #   candidates:
 #     - 10.0.45.5:8555
 #     - stun:8555

mqtt:
  host: 10.0.45.5
  user: mqttuser
  password: mypassword


cameras:
  frontdrive_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdrive_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

    objects:
      track:
        - person
        - car
        - bicycle

    zones:
      street_zone:
 # 4K      coordinates: 2456,269,3840,586,3840,0,2486,0
        coordinates: 2261,301,1646,131,1648,0,2560,0,2560,340,2329,149,2560,340

        objects:
          - person
          - car
          - bicycle

      driveway_zone:
# 4K       coordinates: 3840,2160,401,2160,951,0,2488,0,2445,276,3840,612
        coordinates: 250,1440,832,679,1486,250,1613,144,2301,344,2400,214,2560,324,2560,1440
        objects:
          - person
          - car
          - bicycle
        filters:
          person:
            threshold: 0.6

      deckgrass_zone:
 #  4K     coordinates: 410,2160,0,2160,0,0,938,0
        coordinates: 0,1440,0,1327,0,949,0,569,0,0,781,0,786,661,311,1440
        objects:
          - person
          - car

    detect:
      width: 2560
      height: 1440
      fps: 10

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

  frontdoor_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy

      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

    detect:
      width: 2560
      height: 1440
      fps: 5

    objects:
      track:
        - person
        - car
        - bicycle


    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      
  pool_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pool_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
 #       - path: rtsp://127.0.0.1/subpool_cam
 #         input_args: preset-rtsp-restream
 #         roles:
 #           - detect   
    detect:
      width: 4608
      height: 1728
      fps: 5

    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.8
        dog:
          threshold: 0.75

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

  backbbq_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backbbq_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
        - 0,1440,0,0,856,0,869,233,872,901,711,1440
        - 2065,474,2061,169,1921,0,2560,0,2560,763                
 #       - path: rtsp://127.0.0.1:8554/subbackbbq_cam?video=copy
 #         input_args: preset-rtsp-restream
 #         roles:
 #           - detect

    detect:
      width: 2560
      height: 1440
      fps: 5

    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

  courtyard_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/courtyard_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
           
#        - path: rtsp://127.0.0.1:8554/subcourtyard_cam?video=copy
#          input_args: preset-rtsp-restream
#          roles:
#            - detect

    detect:
      width: 2560
      height: 1440
      fps: 5

    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.8
        dog:
          threshold: 0.75

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

  backbins_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backbins_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            
#        - path: rtsp://127.0.0.1:8554/subbackbins_cam?video=copy
#          input_args: preset-rtsp-restream
#          roles:
#            - detect

    detect:
      width: 2560
      height: 1440
      fps: 5

    objects:
      track:
        - person
        - dog

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

  backgrass_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backgrass_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            
#        - path: rtsp://127.0.0.1:8554/subbackgrass_cam?video=copy
#          input_args: preset-rtsp-restream
#          roles:
#            - detect


    detect:
      width: 2560
      height: 1440
      fps: 5

    objects:
      track:
        - person
        - dog

      filters:
        person:
          threshold: 0.8
        dog:
          threshold: 0.75


    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

  frontgrass_cam:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy

      inputs:
        - path: rtsp://127.0.0.1:8554/frontgrass_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record


    detect:
      width: 2560
      height: 1440
      fps: 10
#    motion:
#      mask:
#        - 3840,2160,2182,2160,2154,0,3840,0
    objects:
      track:
        - person
        - car
        - bicycle
        - dog
      filters:
        person:
          threshold: 0.75
        dog:
          threshold: 0.75
    zones:
      street_zone_grass:
# 4K        coordinates: 0,565,0,0,2328,0,2185,510
        coordinates: 2560,369,2560,0,0,0,0,369
        objects:
          - person
          - car
          - bicycle
          - dog

      grass_zone:
 # 4K      coordinates: 0,2160,2905,2160,2354,502,0,562
        coordinates: 0,1440,0,277,1646,351,1900,1440
        objects:
          - person
          - dog


    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

detectors:
  coral:
    type: edgetpu
    device: usb
```

### docker-compose file or Docker CLI command

```yaml
ersion: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2
    shm_size: "400mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config:
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "mypassword"
```

### Relevant log output

```shell
I dont have any logs as Frigate doesn't start.  It's as if you're trying to load it without a config as soon as I add 

audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

to frigate config.  I don't get presented with any http access.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

As soon as I back the changes out by doing a nano config.yml, reboot the container  then all good.

**Comment by hawkeye217** [comment]
You need to specify an `audio` source for at least one of your cameras.

Note this in the docs:

```
cameras:
  front_camera:
    ffmpeg:
      inputs:
        - path: rtsp://.../main_stream
          roles:
            - record
        - path: rtsp://.../sub_stream # <- this stream must have audio enabled
          roles:
            - audio   <-------- Specify audio role
            - detect
```
