### ISSUE TITLE
[HW Accel Support]: Hardware acceleration not working with transpose parameter

### ISSUE THREAD

**Issue by martinjung7109** [blakeblackshear/frigate#8341]
### Describe the problem you are having

When I rotate the camera stream using transpose=1 as an output argument I get the errors shown in the logs below. Disabling hardware acceleration by commenting out the corresponding lines solves the problem and the stream gets rotated but the CPU usage is ten times higher than before.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com

#ffmpeg:
#  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci

birdseye:
  mode: continuous

objects:
  track:
    - person
    - car

record:
  enabled: true
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    retain:
      default: 5
      mode: active_objects
      objects:
        person: 15
        car: 15

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.170.21:554/ch1/main
          roles:
            - detect
            - record
      output_args:
        detect: -vf transpose=1 -f rawvideo
    detect:
      width: 1080
      height: 1920
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config.yml:/config/config.yml
      - /root/frigate/media/:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
2023-10-25 18:53:00.319213934  [INFO] Starting Frigate...
2023-10-25 18:53:00.811289591  [2023-10-25 18:53:00] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-25 18:53:00.818095867  [2023-10-25 18:53:00] peewee_migrate                 INFO    : Starting migrations
2023-10-25 18:53:00.820740686  [2023-10-25 18:53:00] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-25 18:53:00.828268472  [2023-10-25 18:53:00] frigate.app                    INFO    : Output process started: 219
2023-10-25 18:53:00.834672886  [2023-10-25 18:53:00] frigate.app                    INFO    : Camera processor started for back: 223
2023-10-25 18:53:00.837415874  [2023-10-25 18:53:00] frigate.app                    INFO    : Capture process started for back: 224
2023-10-25 18:53:00.987738040  [2023-10-25 18:53:00] detector.coral                 INFO    : Starting detection process: 218
2023-10-25 18:53:00.987831088  [2023-10-25 18:53:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-10-25 18:53:00.990401337  [2023-10-25 18:53:00] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-10-25 18:53:01.850074024  [2023-10-25 18:53:01] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
2023-10-25 18:53:01.850184124  [2023-10-25 18:53:01] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...
2023-10-25 18:53:13.872146987  [2023-10-25 18:53:13] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/back-20231025185301.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b70648b6c0] moov atom not found\n/tmp/cache/back-20231025185301.mp4: Invalid data found when processing input\n'
2023-10-25 18:53:13.872188161  [2023-10-25 18:53:13] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/back-20231025185301.mp4
2023-10-25 18:53:20.876593653  [2023-10-25 18:53:20] watchdog.back                  ERROR   : Ffmpeg process crashed unexpectedly for back.
2023-10-25 18:53:20.876595767  [2023-10-25 18:53:20] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-10-25 18:53:20.876596730  [2023-10-25 18:53:20] ffmpeg.back.detect             ERROR   : Multiple -filter, -af or -vf options specified for stream 0, only the last option '-filter:v transpose=1' will be used.
2023-10-25 18:53:20.876599626  [2023-10-25 18:53:20] ffmpeg.back.detect             ERROR   : [segment @ 0x55b2e3aec300] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-10-25 18:53:20.876607607  [2023-10-25 18:53:20] ffmpeg.back.detect             ERROR   : Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
2023-10-25 18:53:20.876620197  [2023-10-25 18:53:20] ffmpeg.back.detect             ERROR   : Error reinitializing filters!
2023-10-25 18:53:20.876620943  [2023-10-25 18:53:20] ffmpeg.back.detect             ERROR   : Failed to inject frame into filter network: Function not implemented
2023-10-25 18:53:20.876629004  [2023-10-25 18:53:20] ffmpeg.back.detect             ERROR   : Error while processing the decoded data for stream #0:0
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Grundig GD-CI-CC2616V

### Any other information that may be helpful

I am running Frigate in a Debian VM on Proxmox with iGPU of an Intel Core i5-12600K dedicated to Frigate via PCIe passthrough. The VM detects the GPU as shown below.

![Screenshot (45)](https://github.com/blakeblackshear/frigate/assets/64349124/d2b15658-6aae-4f9b-92f4-65bdf09790aa)

**Comment by NickM-27** [comment]
There are multiple problems here:
1. you are overwriting the debug output args and not including the original ones that are needed
2. you can not provide  -vf when using the vaapi preset because that has its own -vf.

in general rotation is recommended to be done in go2rtc as that has it built in using hwaccel

**Comment by martinjung7109** [comment]
Thank you. I wasn't aware that output_args is overwriting the original arguments and that vaapi has its own -vf arguments. I will look into doing the rotation in go2rtc.

**Comment by martinjung7109** [comment]
My config looks like this now, but unfortunatly the stream doesn't get rotated. There are no errors in the frigate an go2rtc logs.

`mqtt:
  host: mqtt.server.com

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    back:
      - rtsp://username:password@192.168.170.21:554/ch1/main
      - "ffmpeg:back#video=h264#rotate=90"

detectors:
  coral:
    type: edgetpu
    device: pci

birdseye:
  mode: continuous

objects:
  track:
    - person
    - car

record:
  enabled: true
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    retain:
      default: 5
      mode: active_objects
      objects:
        person: 15
        car: 15

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record`

**Comment by NickM-27** [comment]
you can't set the rotated stream as a secondary stream, because when frigate requests the stream the original stream satisfies the requirement so go2rtc never tries to create the rotated stream.

You should name them differently and specifically request the rotated stream

```
go2rtc:
  streams:
    back:
      - rtsp://username:password@192.168.170.21:554/ch1/main
    back_rotated:
      - "ffmpeg:back#video=h264#rotate=90"
```

**Comment by martinjung7109** [comment]
Awsome this works now. Thank you again.
The CPU usage went from 0,8% to 20% though (2 cores of i5-12600K allocated to VM). Is this considered normal behavior?

**Comment by NickM-27** [comment]
You should add `#hardware` to the rotate stream so it uses the GPU instead of cpu

**Comment by martinjung7109** [comment]
The `go2rtc` section of my config looks like this now
```
go2rtc:
  streams:
    back:
      - rtsp://username:password@192.168.170.21:554/ch1/main
    back_rotated:
      - "ffmpeg:back#video=h264#rotate=90#hardware"```
but I am getting the following errors from the go2rtc logs now
```
2023-10-29 20:35:01.864348774  [INFO] Preparing go2rtc config...
2023-10-29 20:35:01.959674268  [INFO] Starting go2rtc...
2023-10-29 20:35:02.009049702  20:35:02.008 INF go2rtc version 1.2.0 linux/amd64
2023-10-29 20:35:02.009052897  20:35:02.008 INF [api] listen addr=:1984
2023-10-29 20:35:02.009054205  20:35:02.008 INF [rtsp] listen addr=:8554
2023-10-29 20:35:02.009055110  20:35:02.008 INF [srtp] listen addr=:8443
2023-10-29 20:35:02.009056120  20:35:02.008 INF [webrtc] listen addr=:8555
2023-10-29 20:35:04.551211039  20:35:04.551 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#video=h264#rotate=90#hardware
2023-10-29 20:35:06.757549452  20:35:06.757 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:back#video=h264#rotate=90#hardware
2023-10-29 20:35:06.757611228  20:35:06.757 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=back_rotated
2023-10-29 20:35:11.888556574  [INFO] Starting go2rtc healthcheck service...```

**Comment by NickM-27** [comment]
Most likely the issue is that the GPU hasn't been passed to the vm / container.

**Comment by martinjung7109** [comment]
`lspci` on the Debian host shows the GPU. Is there a way to check wether it has been sucessfully passed to the container?

**Comment by NickM-27** [comment]
Check vainfo in webUI

**Comment by martinjung7109** [comment]
vainfo looks like this
```
Return Code: 0

Process Output:

vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```

**Comment by NickM-27** [comment]
I see, in that case you'll want to enable trace logs to get more info on the error

```
go2rtc:
  log:
    exec: trace
  streams: ...
```
