### ISSUE TITLE
[Config Support]: Frigate not respecting Zones 

### ISSUE THREAD

**Issue by honeyfairy** [blakeblackshear/frigate#8346]
### Describe the problem you are having

I have set the config to only detect "persons" in the Yard area. However it still detects "car" in that area.
Here is an example where the vehicle is clearly in the Yard area, yet a car is being detected and the event is saying it is under the other zone (entrance)

![car](https://github.com/blakeblackshear/frigate/assets/17691989/a55a121e-7c52-432b-98ad-4ec5dafbac9f)

### Version

Frigate (0.12.1-367d724)

### Frigate config file

```yaml
ones:
      entrance:
        coordinates: 1257,143,1328,1080,1920,1080,1920,208
        objects:
          - car
          - person
      yard:
        coordinates: 1260,1080,215,1080,45,872,69,592,356,425,640,225,1245,155
        objects:
          - person

  
    record:
      enabled: true
    
      retain:
        days: 7
        mode: all
      
      events:
         required_zones:
           - entrance
           - yard


         retain:
           default: 14
           mode: active_objects
    snapshots:
       required_zones:
         - entrance
         - yard
    objects:
      track:
        - person
        - car
```

### Relevant log output

```shell
none relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
