### ISSUE TITLE
[Support]: Min Max Ratio help

### ISSUE THREAD

**Issue by FigJam23** [blakeblackshear/frigate#8350]
### Describe the problem you are having

Trying to work out how to setup the min and max ratio of  detection events so I can iron out a few false positives I'm getting . Could someone explain how it's worked out as I can't see info in my snapshots apart from pixel count I've struggled to find information on how this is done.

person:
      min_area: 18000
    #  max_area: 100000
     #  min_ratio: 0.5 how is this worked out ?
     #  max_ratio: 2.0 how is this worked out ?
     #  min_score: 0.5
      threshold: 0.75
        

Also on a separate question can I run a Google coral on top of using my Nvidia gpu or is it one or the other?

### Version

12.1

### Frigate config file

```yaml
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: False
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  #time_format: browser
 # Optional: Set the date style for a specified length.
 # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  #date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
 # time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  #strftime_fmt: "%Y/%m/%d %H:%M"


#logger:
  # Optional: default log level (default: shown below)
  #default: warning
  # Optional: module by module log level configuration
 # logs:
    #frigate.mqtt: error

#timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  #position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  #format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
 # color:
  # All Required when color is specified (default: shown below)
   # red: 255
   # green: 255
   # blue: 255
  # Optional: Line thickness of font (default: shown below)
  #thickness: 1
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  #effect: solid

mqtt:
  host: 192.168.1.44
  port: 1883
  user: mqtt
  password: J
  
#birdseye:
  #enabled: True
  #width: 1280
  #height: 760
  #quality: 1
  #mode: objects
  
birdseye:
    # Optional: Enable birdseye view (default: shown below)
  enabled: True
   # Optional: Width of the output resolution (default: shown below)
  width: 1280
   # Optional: Height of the output resolution (default: shown below)
  height: 720
    # Optional: Encoding quality of the mpeg1 feed (default: shown below)
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 4
    # Optional: Mode of the view. Available options are: objects, motion, and continuous
    #   objects - cameras are included if they have had a tracked object within the last 30 seconds
    #   motion - cameras are included if motion was detected in the last 30 seconds
    #   continuous - all cameras are included always
  mode: objects
  #restream: false
#database: 
#  path: /media/NAS/cctv/frigate/frigate.db
  
record:
  enabled: True
  retain:
    days: 30
    mode: motion
  events:
    pre_capture: 6
    post_capture: 20  
    retain:
      default: 30
      mode: active_objects

snapshots:
  enabled: true
  timestamp: false
  clean_copy: true
  bounding_box: true
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
 # height: 300
  quality: 100 
  retain:
    default: 30
    objects:
      person: 30




ffmpeg:
  hwaccel_args: preset-nvidia-h264 



#Global Object Settings
objects:
  track:
    - person
    - car
    - cat
    - dog

  filters:
    person:
      min_area: 18000
    #  max_area: 100000
     #  min_ratio: 0.5
     #  max_ratio: 2.0
     #  min_score: 0.5
      threshold: 0.75
        
    cat:
      min_area: 9000
     # max_area: 100000
      # min_ratio: 0.5
     # max_ratio: 2.0
     # min_score: 0.5
      threshold: 0.75
          
    dog:
      min_area: 9000
     # max_area: 100000
     # min_ratio: 0.5
     # max_ratio: 2.0
     # min_score: 0.5
      threshold: 0.75


    
#  filters:
 #   person:
  #    min_area: 5000
   #   max_area: 100000

rtmp:
  enabled: false
  
go2rtc:
  streams:
    360cam:
    #  - 192.168.1.66:50000/live/mainview3.html?Language=0
      - rtsp://admin:Ju@192.168.1.66:554/MediaInput/h264
      - "ffmpeg:360cam#video=h264"
    front_entry:
      - rtsp://admin:Ju@192.168.1.226:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_entry#video=h264#audio=aac"
    front_deck:
      - rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/201
    driveway_cam:
      - rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/101   
    back_shed:
      - rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/301   
    sand_pit:
      - rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/401      
      
detectors:
  tensorrt:
    type: tensorrt
    device: 0 # This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
#########################################################################################################################################            
cameras:
########################################################################################################################################

  driveway_cam:
    ui:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/101
          roles:
            - record 
            - detect       
    motion:
      mask:  
        - 2385,0,2441,280,2424,452,2085,585,1709,698,344,2160,0,2160,0,204,0,0
        - 3840,2160,1323,2160,1541,1863,1851,1930,2358,1310,2680,1146,2773,767,2692,253,2301,0,3840,0
  #  record:
   #   events:
   #     required_zones:
   #       - zone_driveway_cars
    #      - zone_driveway_all       
    zones:  
      zone_driveway_cars:
        coordinates: 2258,399,2568,641,2445,907,1607,969,2672,1434,2960,614
        objects:
          - car
        filters:
          car:
            min_area: 100000
        #    max_area: 100000
         #   min_ratio: 0.5
         #   max_ratio: 2.0
         #   min_score: 0.5
            threshold: 0.75

      zone_driveway_all:
        coordinates: 3123,688,2194,417,759,1720,279,1144,0,1388,0,1927,3335,2160
        objects:   
          - person
          - cat  
          - dog   

        filters:
          person:
            min_area: 4000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.8

          cat:
            min_area: 4000
        #    max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.7
          
          dog:
            min_area: 4000
        #    max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.7

      zone_cars_road:
        coordinates: 1539,118,533,246,600,411,1399,278,2114,354,2377,359,3034,578,3840,863,3840,349
        objects:   
          - car
          - person
          - cat  
          - dog  
        filters:
          car:
            min_area: 35000
        #    max_area: 100000
         #   min_ratio: 0.5
         #   max_ratio: 2.0
         #   min_score: 0.5
            threshold: 0.75

          person:
            min_area: 10000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.75 

          cat:
            min_area: 4000
        #    max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.7
          
          dog:
            min_area: 4000
        #    max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.7       

    detect:
      width: 3840
      height: 2160
      fps: 8
    objects:
      filters:
        car:
          mask:
            - 2726,1284,1572,2160,540,2160,426,1553,1563,838
            - 1702,1053,1486,397,1999,291,2449,560
         #   - 1494,0,806,54,466,150,483,387,532,688,1267,288,1871,271,2869,574,3810,742,3818,25     
    record:
      events:
        required_zones:
          - zone_driveway_cars
          - zone_driveway_all  
          - zone_cars_road 

    snapshots:
      required_zones:
          - zone_driveway_cars
          - zone_driveway_all 
          - zone_cars_road
###############################################################################################################################
      

 #####################################################################################################################################                     

  front_entry:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://admin:Ju@192.168.1.226:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record 
            - detect    
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy 
    motion:
      mask:    
        - 3072,2048,2785,2048,2596,1845,2104,1626,1764,1412,1910,993,2401,1074,2576,812,2712,814,2720,724,2694,476,2557,419,2633,0,3072,0
    zones:
      zone_front_entry_people:
        coordinates: 3072,1630,2372,1180,2036,1027,2386,732,2753,915,3072,997
        objects:
          - person
        filters:
          person:
            min_area: 30000
           # max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.78

      zone_front_entry_area:
        coordinates: 462,2048,2793,2048,2612,1857,488,627,0,806,293,1406,161,1493
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_area: 30000
           # max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.78

          cat:
            min_area: 10000
          #  max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.74
          
          dog:
            min_area: 10000
           # max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.74

      zone_front_entry_dakoats_door:
        coordinates: 2561,527,2848,645,2783,863,2413,712
        objects:
          - person
        filters:
          person:
            min_area: 20000
           # max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.78

      zone_front_entry_cat:
        coordinates: 177,1192,840,854,505,588,0,808
        objects:
          - cat
          - dog
        filters:
          cat:
            min_area: 10000
          #  max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.74
          
          dog:
            min_area: 10000
           # max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.74


    detect:
      width: 3072
      height: 2048
      fps: 8
    objects:
      filters:
        person:
          mask:
            - 500,456,472,83,753,0,1125,0,1117,297
            - 2565,1847,2822,2048,3072,2048,3072,1650,2919,1512,596,437,608,718
            - 89,1021,317,1379,121,1452,0,1365,0,1080
            - 0,236,279,146,346,614,0,777 
    record:
      events:
        required_zones:
          - zone_front_entry_people
          - zone_front_entry_dakoats_door
          - zone_front_entry_deck
          - zone_front_entry_cat
    snapshots:
      required_zones:
          - zone_front_entry_people
          - zone_front_entry_dakoats_door
          - zone_front_entry_deck
          - zone_front_entry_cat
 ####################################################################################################################################################  
 
  front_deck:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/201 
          roles:
            - record 
            - detect
    motion:
      mask:   
        - 0,2160,838,2160,0,441,0,1287
        - 2606,0,781,0,281,601,1649,1072,1918,449,2083,340,2675,531,3761,1800,3810,1591,3393,0


    zones:
      zone_front_deck:
        coordinates: 34,2160,0,270,2267,106,3115,900,3840,1748,3840,2160
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_area: 90000
        #    max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
            min_score: 0.65
            threshold: 0.78   
          cat:
            min_area: 6000
         #   max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.7
          dog:
            min_area: 6000
          #  max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.7

      zone_front_deck_road:
        coordinates: 2726,332,2461,130,2626,0,3840,452,3840,1473
        objects:  
          - car
          - person
        filters:
          car:
            min_area: 35000
        #    max_area: 100000
         #   min_ratio: 0.5
         #   max_ratio: 2.0
         #   min_score: 0.5
            threshold: 0.75

          person:
            min_area: 10000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.75 

           

    detect:
      width: 3840
      height: 2160
      fps: 8 
    record:
      events:
        required_zones:
          - zone_front_deck
          - zone_front_deck_road
    snapshots:
      required_zones:
          - zone_front_deck
          - zone_front_deck_road




 
############################################################################################################################################################### 
 
  back_shed:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/301
          roles:
            - record 
            - detect         
    
    motion:
      mask:    
        - 0,2160,1459,2160,560,1375,0,1684
        - 0,747,513,582,3840,0,877,0,0,0
        - 3120,407,3044,826,3458,922,3557,520                                
    detect:
      width: 3840
      height: 2160
      fps: 8
    objects:
      track:
        - person
        - cat   
        - dog 

      filters:
        person:
          min_area: 82000
        #  max_area: 100000
         # min_ratio: 0.5
         # max_ratio: 2.0
         # min_score: 0.5
          threshold: 0.75
        
        cat:
          min_area: 59000
         # max_area: 100000
        #  min_ratio: 0.5
         # max_ratio: 2.0
         # min_score: 0.5
          threshold: 0.7
          
        dog:
          min_area: 59000
          #max_area: 100000
         # min_ratio: 0.5
         # max_ratio: 2.0
         # min_score: 0.5
          threshold: 0.7


##########################################################################################################################################################          
  sand_pit:
    ui:
      order: 4  
    ffmpeg:
      inputs:
        - path: rtsp://admin:Ju@192.168.1.30:554/Streaming/channels/401
          roles:
            - record
            - detect
    motion:
      mask:    
        - 0,2160,0,0,1453,0,1421,214,1401,526,1529,1273,733,1438,1128,2160
        - 1448,0,2571,0,3840,0,3840,900,3523,892,3584,1178,3840,1391,3840,2160,3031,2160,1733,1003,1726,706,1598,452,1430,375
    zones:
      zone_sand_pit:
        coordinates: 32,2136,0,890,1278,647,1293,546,1753,543,2876,902,3673,1539,3840,2160 
        objects:  
          - person
          - cat
          - dog
        filters:
          person:
            min_area: 40000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.7  
          cat:
            min_area: 20000
           # max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.7
          dog:
            min_area: 20000
           # max_area: 100000
           # min_ratio: 0.5
           # max_ratio: 2.0
           # min_score: 0.5
            threshold: 0.7          
          
      zone_sand_pit_over_fence_area:
        coordinates: 2984,848,1915,489,1443,376,1450,224,3840,651,3815,1669
        objects:  
          - person
        filters:
          person:
            min_area: 10000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.5

    detect:
      width: 3840
      height: 2160
      fps: 8
    record:
      events:
        required_zones:
          - zone_sand_pit_over_fence_area
          - zone_sand_pit
    snapshots:
      required_zones:
          - zone_sand_pit_over_fence_area
          - zone_sand_pit
 


###########################################################################################################################          

  360cam:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:Ju@192.168.1.66:554/MediaInput/h264
          roles:
            - record     
            - detect
    motion:
      mask:    
        - 1568,261,1267,181,1268,69,1064,0,1920,0,1920,251
        - 0,546,1544,535,1475,694,978,736,0,794 
    zones:  
      zone_360_nextdoor:
        coordinates: 1561,262,1276,198,1057,0,1203,0,1920,0,1920,261    
        objects:  
          - person
        filters:
          person:
            min_area: 20000
          #  max_area: 100000
          #  min_ratio: 0.5
          #  max_ratio: 2.0
          #  min_score: 0.5
            threshold: 0.6         

    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person  
        - cat
        - dog

      filters:
        person:
          min_area: 18000
        #  max_area: 100000
        #  min_ratio: 0.5
        #  max_ratio: 2.0
        #  min_score: 0.5
          threshold: 0.75
        
        cat:
          min_area: 9000
         # max_area: 100000
         # min_ratio: 0.5
         # max_ratio: 2.0
         # min_score: 0.5
          threshold: 0.75
          
        dog:
          min_area: 9000
         # max_area: 100000
         # min_ratio: 0.5
         # max_ratio: 2.0
         # min_score: 0.5
          threshold: 0.75


 
      
 #####################################################################################################################################         
#testing
#####################################################################################################################################
```

### Relevant log output

```shell
2023-10-27 17:23:50.294408265  [INFO] Starting Frigate...
2023-10-27 17:23:50.970567226  [2023-10-27 17:23:50] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-27 17:23:51.041524654  [2023-10-27 17:23:51] peewee_migrate                 INFO    : Starting migrations
2023-10-27 17:23:51.044159070  [2023-10-27 17:23:51] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-27 17:23:51.062852916  [2023-10-27 17:23:51] frigate.app                    INFO    : Output process started: 439
2023-10-27 17:23:51.071453824  [2023-10-27 17:23:51] frigate.app                    INFO    : Camera processor started for driveway_cam: 442
2023-10-27 17:23:51.072173400  [2023-10-27 17:23:51] detector.tensorrt              INFO    : Starting detection process: 437
2023-10-27 17:23:51.285923297  [2023-10-27 17:23:51] frigate.app                    INFO    : Camera processor started for front_entry: 446
2023-10-27 17:23:51.286328048  [2023-10-27 17:23:51] frigate.app                    INFO    : Camera processor started for front_deck: 448
2023-10-27 17:23:51.286330490  [2023-10-27 17:23:51] frigate.app                    INFO    : Camera processor started for back_shed: 449
2023-10-27 17:23:51.286335115  [2023-10-27 17:23:51] frigate.app                    INFO    : Camera processor started for sand_pit: 451
2023-10-27 17:23:51.286336471  [2023-10-27 17:23:51] frigate.app                    INFO    : Camera processor started for 360cam: 452
2023-10-27 17:23:51.286359573  [2023-10-27 17:23:51] frigate.app                    INFO    : Capture process started for driveway_cam: 454
2023-10-27 17:23:51.286361153  [2023-10-27 17:23:51] frigate.app                    INFO    : Capture process started for front_entry: 457
2023-10-27 17:23:51.286362300  [2023-10-27 17:23:51] frigate.app                    INFO    : Capture process started for front_deck: 462
2023-10-27 17:23:51.286384481  [2023-10-27 17:23:51] frigate.app                    INFO    : Capture process started for back_shed: 468
2023-10-27 17:23:51.286385732  [2023-10-27 17:23:51] frigate.app                    INFO    : Capture process started for sand_pit: 470
2023-10-27 17:23:51.286386782  [2023-10-27 17:23:51] frigate.app                    INFO    : Capture process started for 360cam: 475
2023-10-27 17:23:51.607617834  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +535, GPU +0, now: CPU 645, GPU 562 (MiB)
2023-10-27 17:23:51.613228314  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 15 MiB
2023-10-27 17:23:51.645001128  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 696, GPU 588 (MiB)
2023-10-27 17:23:51.648394812  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 697, GPU 598 (MiB)
2023-10-27 17:23:51.653175335  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +15, now: CPU 0, GPU 15 (MiB)
2023-10-27 17:23:51.653190728  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 681, GPU 590 (MiB)
2023-10-27 17:23:51.653260621  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +1, GPU +8, now: CPU 682, GPU 598 (MiB)
2023-10-27 17:23:51.653267515  [2023-10-27 17:23:51] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +7, now: CPU 0, GPU 22 (MiB)
2023-10-27 17:26:55.552684900  [2023-10-27 17:26:55] frigate.comms.dispatcher       INFO    : Turning off recordings for front_entry
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":2160,"width":3840}]}}]
```

### Frigate stats

```json
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEInVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointVLD"}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Hikvision4k Panasonic 360 Dahua

### Any other information that may be helpful

![Screenshot_20231027-182049](https://github.com/blakeblackshear/frigate/assets/29391962/715c86b8-c3ef-4603-85e8-a79cde056ccb)
