### ISSUE TITLE
[Config Support]: frigate.ptz

### ISSUE THREAD

**Issue by melnikovRV** [blakeblackshear/frigate#8357]
### Describe the problem you are having

When the “move” command is issued to frigate.ptz in Home Assistant, the camera automatically turns to the limit, without stopping, as if the “move left” button is held down. The issue is how to make it so when the “left” argument is invoked, only a slight turn is made.

### Version

0.13.0 Beta 2

### Frigate config file

```yaml
service: frigate.ptz
data:
  action: move
  argument: left
target:
  entity_id: camera.street
```

### Relevant log output

```shell
/
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
this is expected, when using the HA automation you as the user must issue the stop command as well

**Comment by melnikovRV** [comment]
> this is expected, when using the HA automation you as the user must issue the stop command as well

How i can do it in frigate card?

```
elements:
  - type: custom:frigate-card-ptz
    orientation: horizontal
    style:
      transform: none
      right: 5vh
      top: 40%
    service: onvif.ptz
    data_left:
      entity_id: camera.street
      action: move
      argument: left
    data_right:
      entity_id: camera.street
      action: move
      argument: right
    data_up:
      entity_id: camera.street
      action: move
      argument: up
    data_down:
      entity_id: camera.street
      action: move
      argument: down
    data_zoom_in:
      entity_id: camera.street
      action: zoom
      argument: in
    data_zoom_out:
      entity_id: camera.street
      action: zoom
      argument: out
```

**Comment by NickM-27** [comment]
like this https://github.com/dermotduffy/frigate-hass-card/issues/1163#issuecomment-1722282019

**Comment by melnikovRV** [comment]
> like this [dermotduffy/frigate-hass-card#1163 (comment)](https://github.com/dermotduffy/frigate-hass-card/issues/1163#issuecomment-1722282019)

thank you! I'm sorry for question, but where's my miss? 

```
elements:
  - type: custom:frigate-card-ptz
    orientation: horizontal
    style:
      transform: none
      right: 5vh
      top: 40%
    actions_left:
        start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.street
              action: move
              argument: left
        end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
               entity_id: camera.street
               action: stop
    actions_right:
        start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.street
              action: move
              argument: right
        end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
               entity_id: camera.street
               action: stop
    actions_up:
        start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.street
              action: move
              argument: up
        end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
               entity_id: camera.street
               action: stop
    actions_down:
        start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.street
              action: move
              argument: down
        end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
               entity_id: camera.street
               action: stop
```
