### ISSUE TITLE
[Support]: Using a Frigate server with version 0.12.1-367d724 <= 0.12.1 which is not compatible

### ISSUE THREAD

**Issue by BKirev** [blakeblackshear/frigate#8373]
### Describe the problem you are having

There was an update yesterday, if I'm not mistaken and I see this(title) in the logs now

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: xxxxxxx
  user: xxxxxxx
  password: xxxxxxx

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3

birdseye:
  enabled: True
  mode: continuous

cameras:
  baby-camera: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxxx:xxxx@xxxx:xxx/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://xxxx:xxxx@xxxx:xxx/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
          pre_capture: 5
          post_capture: 5
          objects:
            - person
          required_zones: []
          retain:
            default: 10
            mode: motion
            objects:
              person: 15
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 575
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15

  vhod-camera: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxxx:xxxx@xxxx:xxx/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://xxxx:xxxx@xxxx:xxx/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
          pre_capture: 5
          post_capture: 5
          objects:
            - person
          required_zones: []
          retain:
            default: 10
            mode: motion
            objects:
              person: 15
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 575
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15

  bedroom-baby-camera: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxxxxxxxx:xxx/realmonitor?channel=1&stream=1.sdp # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://xxxxxxxxx:xxx/realmonitor?channel=1&stream=0.sdp # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 7
        mode: all
      events:
          pre_capture: 5
          post_capture: 5
          objects:
            - person
          required_zones: []
          retain:
            default: 10
            mode: motion
            objects:
              person: 15
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 575
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
```

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.frigate
Source: custom_components/frigate/__init__.py:201
Integration: Frigate (documentation, issues)
First occurred: 1:53:49 PM (2 occurrences)
Last logged: 2:03:16 PM

Using a Frigate server (http://ccab4aaf-frigate-fa:5000) with version 0.12.1-367d724 <= 0.12.1 which is not compatible -- you must upgrade: https://github.com/blakeblackshear/frigate/releases
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"},{"avg_frame_rate":"0/0"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"},{"avg_frame_rate":"0/0"}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

IMOU Ranger 2

### Any other information that may be helpful

2023-10-29 11:53:38.172286835  [INFO] Starting Frigate...
2023-10-29 11:53:43.426784298  [2023-10-29 13:53:43] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-29 11:53:43.494504042  [2023-10-29 13:53:43] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-10-29 11:53:43.498401840  [2023-10-29 13:53:43] peewee_migrate                 INFO    : Starting migrations
2023-10-29 11:53:43.520740810  [2023-10-29 13:53:43] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-29 11:53:43.557408743  [2023-10-29 13:53:43] frigate.app                    INFO    : Output process started: 301
2023-10-29 11:53:43.568257302  [2023-10-29 13:53:43] frigate.app                    INFO    : Camera processor started for baby-camera: 305
2023-10-29 11:53:43.574650495  [2023-10-29 13:53:43] frigate.app                    INFO    : Camera processor started for vhod-camera: 307
2023-10-29 11:53:43.585108169  [2023-10-29 13:53:43] frigate.app                    INFO    : Camera processor started for bedroom-baby-camera: 308
2023-10-29 11:53:43.593218269  [2023-10-29 13:53:43] frigate.app                    INFO    : Capture process started for baby-camera: 310
2023-10-29 11:53:43.596287410  [2023-10-29 13:53:43] detector.coral                 INFO    : Starting detection process: 300
2023-10-29 11:53:47.467934949  [2023-10-29 13:53:43] frigate.app                    INFO    : Capture process started for vhod-camera: 311
2023-10-29 11:53:47.481797709  [2023-10-29 13:53:43] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-29 11:53:47.494793569  [2023-10-29 13:53:43] frigate.app                    INFO    : Capture process started for bedroom-baby-camera: 316
2023-10-29 11:53:47.494949796  [2023-10-29 13:53:47] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
