### ISSUE TITLE
[Support]: Extended Load Times For Clips

### ISSUE THREAD

**Issue by nickcmeyer** [blakeblackshear/frigate#8383]
### Describe the problem you are having

Frigate in Unraid Docker. When viewing event clips there is an extended period that the clip takes to load before the video begins. This is generally 3-10 seconds, sometimes more. This is on LAN direct to unraid:5000, the database is on config (NVME Cache), and media is also primary cache so these events are not spinning up the disks. This is running on a E5-2630V4 so not exactly a a speed demon but I wouldn't think it would be bad enough to be the cause itself.

![image](https://github.com/blakeblackshear/frigate/assets/49877497/b95e4392-5442-4267-9595-a7aa45a9ea7c)

I have noticed that although these processes are not pegged 100%+ for loading a single clip if I rapidly select multiple clips the processes greatly exceed 100%. Testing the same on my parents E-2124G system does not result in python over 10% and I didn't even see SHFS. Play time there is more like 200ms and that includes the network going through a S2S tunnel.

![image](https://github.com/blakeblackshear/frigate/assets/49877497/c06574ab-4d86-4bc6-b877-77926ea32baa)

Suggestions?

Thanks,
-Nick

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.99
  user: homeassistant
  password: redacted
detectors:
  detector_name:
    type: edgetpu
    device: pci

database:
  path: /config/frigate.db

birdseye:
  width: 1920
  height: 1080
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

detect:
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 50
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 300
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    #max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      #default: 3000
      # Optional: Object specific values
      #objects:
        #person: 1000

objects:
  filters:
    person:
      min_area: 1000
      #max_area: 100000
      min_score: 0.60
      threshold: 0.70
    cat:
      min_area: 1000
      #max_area: 20000
      min_score: 0.60
      threshold: 0.70
    dog:
      min_area: 1000
      #max_area: 20000
      min_score: 0.60
      threshold: 0.70
    car:
      #min_area: 1000
      #max_area: 20000
      min_score: 0.66
      threshold: 0.7
      
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 35
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 70
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 100
  #8MP total pixels resived to 17,700

record:
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 10000
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    days: 90
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones:
        - FrontYard(walkway)
        - FrontYard(driveway)
        - FrontYard(street)
        - FrontYard(south)
        - FrontYard(north)
        - SideYard(close)
        - BackYard(far)
        - BackYard(close)
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 90
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 180

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones:
        - FrontYard(walkway)
        - FrontYard(driveway)
        - FrontYard(street)
        - FrontYard(south)
        - FrontYard(north)
        - SideYard(close)
        - BackYard(far)
        - BackYard(close)
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 180
    # Optional: Per object retention days
    #objects:
    #  person: 15

# Optional: jsmpeg stream configuration for WebUI
live:
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 1080
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  effect: shadow

cameras:
  FrontSouth:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.152:554/Streaming/channels/101
          roles:
            - detect
            - record
    best_image_timeout: 60

    detect:
        width: 3840
        height: 2160
        fps: 4

    motion:
        mask:    
            - 3840,463,3111,275,2164,92,1407,26,986,31,714,72,430,118,0,164,0,0,3840,0
            - 437,2160,0,491,0,2160
    
    objects:
        track:
            - person
            - cat
            - dog
            - car  

    zones:
      FrontYard(walkway):
        coordinates: 0,390,1186,224,1536,409,956,511,970,781,103,1019
        objects:
          - person
        filters:
          person:
            min_area: 8000
            max_area: 250000
            threshold: 0.7
      FrontYard(driveway):
        coordinates: 1440,241,1802,365,1383,413,1126,279
        filters:
          person:
            min_area: 4000
            max_area: 60000
            threshold: 0.7
          car:
            min_area: 100000
            max_area: 300000
            threshold: 0.7
      FrontYard(street):
        coordinates: 3840,580,2953,323,2136,158,1622,105,1168,68,1014,66,823,68,788,156,1232,237,1769,338,2867,650,3840,986
        filters:
          person:
            min_area: 4000
            max_area: 60000
            threshold: 0.7
          car:
            min_area: 20000
            max_area: 1000000
            threshold: 0.7
      FrontYard(south):
        coordinates: 961,790,94,1001,191,1434,439,2160,3840,2160,3840,957,2898,624,1789,345,593,518
        objects:
          - person
        filters:
          person:
            min_area: 20000
            max_area: 500000
            threshold: 0.7
      FrontYard(north):
        coordinates: 40,443,590,334,1346,270,815,163,503,204,24,287
        objects:
          - person
        filters:
          person:
            min_area: 4000
            max_area: 40000
            threshold: 0.7

    ui:
      order: 1
      dashboard: True

  FrontNorth:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.159:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    best_image_timeout: 60

    detect:
        width: 2592
        height: 1944
        fps: 5

    motion:
        mask:    0,0,2416,0,1771,75,1355,147,811,311,404,490,0,751
    
    objects:
        track:
            - person
            - cat
            - dog
            - car  
        
        mask: 0,814,361,578,720,395,1106,252,1363,173,1750,97,2091,55,2093,0,0,0

    zones:
      FrontYard(walkway):
        coordinates: 2517,117,2540,657,2525,729,1756,540,1858,347,2013,218,2182,178,2224,104
        filters:
          person:
            min_area: 10000
            max_area: 100000
            threshold: 0.7
      FrontYard(driveway):
        coordinates: 448,1106,339,857,1177,404,1618,419
        filters:
          person:
            min_area: 10000
            max_area: 500000
            threshold: 0.7
          car:
            min_area: 100000
            max_area: 1000000
            threshold: 0.7
      FrontYard(street):
        coordinates: 477,506,949,309,1278,193,1599,125,2064,59,2230,107,1668,235,1113,433,532,744,0,1085,0,814
        filters:
          person:
            min_area: 5000
            max_area: 30000
            threshold: 0.7
          car:
            min_area: 10000
            max_area: 400000
            threshold: 0.7
      FrontYard(south):
        coordinates: 1121,433,2104,505,2309,209,1916,164
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
      FrontYard(north):
        coordinates: 543,1325,1024,1944,0,1944,0,1105,358,861
        filters:
          person:
            min_area: 12000
            max_area: 500000
            threshold: 0.7

    ui:
      order: 2
      dashboard: True


  SideYard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.153:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    best_image_timeout: 60

    detect:
        width: 2592
        height: 1944
        fps: 5

    motion:
        mask:    0,0,962,0,2592,0,2592,1944,2224,1944,2592,1127,2592,118,2307,62,1834,37,1341,91,369,495,0,742
    
    objects:
        track:
            - person
            - cat
            - dog
            - car  
        
        mask: 636,83,807,89,1204,112,1542,172,2156,374,2592,578,2592,0,643,0

    zones:
      SideYard(close):
        coordinates: 0,1944,2210,1944,2398,1643,2592,1082,2592,533,881,398,0,857
        filters:
          person:
            min_area: 5000
            max_area: 600000
            threshold: 0.7
      FrontYard(north):
        coordinates: 2592,592,2592,265,2073,187,1351,195,846,425
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7       

    ui:
     order: 3
     dashboard: True

  Shed:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.154:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    best_image_timeout: 60

    detect:
        width: 2592
        height: 1944
        fps: 5

    motion:
        mask:    0,0,962,0,2592,0,2592,466,2031,337,1670,280,1311,272,890,291,558,329,304,414,0,563
    
    objects:
        track:
            - person
            - cat
            - dog
            - car  
        
        mask: 636,83,807,89,1204,112,1542,172,2156,374,2592,578,2592,0,643,0

    zones:
      SideYard(close):
        coordinates: 580,398,742,316,1108,270,1662,261,2592,382,2592,1944,2273,1944,974,1944,0,1944,0,659
        filters:
          person:
            min_area: 5000
            max_area: 600000
            threshold: 0.7

    ui:
      order: 4
      dashboard: True


  BackYardNorth:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.160:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    best_image_timeout: 60

    detect:
        width: 2592
        height: 1944
        fps: 5

    motion:
        mask:
            - 2592,0,2592,542,2173,327,1569,154,768,151,779,0    
            - 452,1944,95,216,343,0,0,0,0,1944
    
    objects:
        track:
            - person
            - cat
            - dog
        
        mask: 636,83,807,89,1204,112,1542,172,2156,374,2592,578,2592,0,643,0

    zones:
      BackYard(far):
        coordinates: 1517,138,2153,326,2592,531,2592,1146,1747,617,732,154
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
      BackYard(close):
        coordinates: 2592,1944,2592,855,876,131,90,214,121,545,442,1944
        filters:
          person:
            min_area: 15000
            max_area: 200000
            threshold: 0.7

    ui:
      order: 5
      dashboard: True


  BackYardSouth:
    ffmpeg:
 
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.151:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    best_image_timeout: 60

    detect:
        width: 3840
        height: 2160
        fps: 5

    motion:
        mask:    3840,2160,3840,0,0,0,0,597,162,368,677,208,1624,55,2326,55,2229,682,3373,1295,2931,2160
    
    objects:
        track:
            - person
            - cat
            - dog
        
        mask: 636,83,807,89,1204,112,1542,172,2156,374,2592,578,2592,0,643,0

    zones:
      BackYard(close):
        coordinates: 2925,2160,3428,1223,1857,475,0,985,0,2160
        filters:
          person:
            min_area: 60000
            max_area: 400000
            threshold: 0.7
      BackYard(far):
        coordinates: 0,1025,1815,485,2232,641,2317,71,1618,60,968,161,151,370,0,615
        filters:
          person:
            min_area: 2000
            max_area: 150000
            threshold: 0.7
    ui:
      order: 6
      dashboard: True
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
{"BackYardNorth":{"camera_fps":5.1,"capture_pid":898,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":906,"pid":876,"process_fps":5.1,"skipped_fps":0.0},"BackYardSouth":{"camera_fps":5.0,"capture_pid":903,"detection_enabled":1,"detection_fps":6.1,"ffmpeg_pid":910,"pid":877,"process_fps":5.2,"skipped_fps":0.0},"FrontNorth":{"camera_fps":5.1,"capture_pid":882,"detection_enabled":1,"detection_fps":1.4,"ffmpeg_pid":888,"pid":871,"process_fps":5.1,"skipped_fps":0.0},"FrontSouth":{"camera_fps":4.1,"capture_pid":879,"detection_enabled":1,"detection_fps":4.8,"ffmpeg_pid":883,"pid":859,"process_fps":4.0,"skipped_fps":0.0},"Shed":{"camera_fps":5.0,"capture_pid":891,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":899,"pid":874,"process_fps":5.0,"skipped_fps":0.0},"SideYard":{"camera_fps":5.1,"capture_pid":887,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":893,"pid":872,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"138":{"cpu":"0.7","mem":"0.1"},"148":{"cpu":"0.3","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"180":{"cpu":"0.0","mem":"0.0"},"225":{"cpu":"0.0","mem":"0.1"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"264":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"294":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"323":{"cpu":"0.0","mem":"0.0"},"365":{"cpu":"0.0","mem":"0.0"},"397":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"437":{"cpu":"0.0","mem":"0.0"},"467":{"cpu":"0.0","mem":"0.0"},"514":{"cpu":"0.0","mem":"0.0"},"5241":{"cpu":"0.0","mem":"0.0"},"5270":{"cpu":"0.0","mem":"0.0"},"5274":{"cpu":"0.0","mem":"0.0"},"5280":{"cpu":"3.0","mem":"0.1"},"550":{"cpu":"0.0","mem":"0.0"},"589":{"cpu":"0.0","mem":"0.0"},"620":{"cpu":"0.0","mem":"0.0"},"642":{"cpu":"0.0","mem":"0.0"},"662":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"846":{"cpu":"0.0","mem":"0.2"},"852":{"cpu":"0.0","mem":"0.0"},"853":{"cpu":"3.0","mem":"0.7"},"855":{"cpu":"9.0","mem":"0.8"},"859":{"cpu":"19.6","mem":"0.8"},"870":{"cpu":"0.0","mem":"0.4"},"871":{"cpu":"21.9","mem":"0.8"},"872":{"cpu":"1.0","mem":"0.7"},"873":{"cpu":"0.0","mem":"0.3"},"874":{"cpu":"2.3","mem":"0.7"},"875":{"cpu":"0.0","mem":"0.2"},"876":{"cpu":"1.3","mem":"0.7"},"877":{"cpu":"17.3","mem":"0.8"},"878":{"cpu":"0.0","mem":"0.1"},"879":{"cpu":"9.0","mem":"0.8"},"882":{"cpu":"7.3","mem":"0.7"},"883":{"cpu":"40.2","mem":"0.5"},"886":{"cpu":"21.3","mem":"0.3"},"887":{"cpu":"7.0","mem":"0.7"},"888":{"cpu":"28.9","mem":"0.3"},"89":{"cpu":"0.0","mem":"0.1"},"891":{"cpu":"7.0","mem":"0.7"},"893":{"cpu":"22.6","mem":"0.3"},"894":{"cpu":"0.0","mem":"0.1"},"898":{"cpu":"6.6","mem":"0.7"},"899":{"cpu":"28.9","mem":"0.3"},"903":{"cpu":"12.3","mem":"0.8"},"904":{"cpu":"0.0","mem":"0.1"},"906":{"cpu":"24.6","mem":"0.3"},"910":{"cpu":"12.6","mem":"0.4"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"10.6","mem":"3.1"},"MiB":{"cpu":"16927.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":12.3,"detectors":{"detector_name":{"detection_start":0.0,"inference_speed":7.21,"pid":853}},"service":{"last_updated":1698616529,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":1003.2,"mount_type":"tmpfs","total":1073.7,"used":70.5},"/media/frigate/clips":{"free":8071781.7,"mount_type":"fuse.shfs","total":28996969.0,"used":20924573.0},"/media/frigate/recordings":{"free":8071781.7,"mount_type":"fuse.shfs","total":28996969.0,"used":20924573.0},"/tmp/cache":{"free":1966.1,"mount_type":"tmpfs","total":2000.0,"used":33.9}},"temperatures":{"apex_0":46.05},"uptime":2736,"version":"0.12.1-367d724"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Amcrest/Hikvision
