### ISSUE TITLE
[Detector Support]: Frigate detects a person where there definitely isn't one.

### ISSUE THREAD

**Issue by MarcelFranken** [blakeblackshear/frigate#8386]
### Describe the problem you are having

I have a Reolink E1 Outdoor camera installed at my carport at home. I'm using Frigate for object detection that specifically targets people.

Could someone please tell me why a person is being detected in this snapshot? I definitely do not see a person here.
![snapshot](https://github.com/blakeblackshear/frigate/assets/25133684/ec41af08-1e8f-4963-a08e-b8b6e4df3d1a)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.15
  user: smarthome
  password: ***
database:
  path: /config/frigate.db

birdseye:
  enabled: True
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb
  # cpu1:
  #   type: cpu
  #   num_threads: 3

ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    carport: 
      - rtsp://hass:***@192.168.178.18/h264Preview_01_main
      - "ffmpeg:carport#audio=opus"
    carport_sub: 
      - rtsp://hass:***@192.168.178.18/h264Preview_01_sub
      - "ffmpeg:carport_sub#audio=opus"

cameras:
  Carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    live:
      stream_name: carport

    detect:
      width: 640
      height: 480
      fps: 10
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - car
      filters:
        person:
          threshold: 0.60
          min_area: 1800
          # mask:
          #   - 0,480,566,480,640,333,640,200,483,114,323,69,226,48,163,21,56,64,0,0,0,108
        car:
          threshold: 0.60
          # mask:
          #   - 0,480,566,480,640,333,640,200,483,114,323,69,226,48,163,21,56,64,0,0,0,108
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      required_zones:
        - entire_carport
      retain:
        default: 30
    record:
      enabled: True
      events:
        required_zones:
          - entire_carport
        retain:
          default: 7
    mqtt:
      enabled: True
      required_zones:
        - entire_carport
    zones:
      entire_carport:
        coordinates: 0,480,566,480,640,333,640,200,483,114,323,69,226,48,163,21,56,64,0,0,0,108
        objects:
          - person
          - car
    motion:
      improve_contrast: True
      mask:
       - 0,0,212,0,205,21,40,86
       - 212,35,158,0,640,0,640,79
```

### docker-compose file or Docker CLI command

```yaml
none - runs as HassOS Addon
```

### Relevant log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
