### ISSUE TITLE
[Support]: Birdseye rotating in funny colors since upgrading to 0.13.0-beta

### ISSUE THREAD

**Issue by Trashmee** [blakeblackshear/frigate#8389]
### Describe the problem you are having

Hi,

I upgraded from 0.12.1 to 0.13.0-beta3 today. 
All seems fine (live camera views, events, HomeAssistant integration), however the birdseye view is acting funny.
 - the entire birdseye image is rotating bottom to top
 - flickering colors are overlaying the actual camera images

![image](https://github.com/blakeblackshear/frigate/assets/8881956/d22cd494-e712-429a-bd03-d3436a3ad653)

It might be due to configs not being properly adapter to 0.13.0 - but as birdseye has very limited configs and the remainder is working fine I'm a bit clueless.

### Version

0.13.0-CD64399

### Frigate config file

```yaml
logger:
  default: info
  logs:
    frigate.mqtt: error
mqtt:
  host: mqtt.domain
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: password
detectors:
  coral:
    type: edgetpu
    device: usb
database:
  path: /media/frigate/database/frigate.db
birdseye:
  enabled: True
  width: 1900
  height: 1080
  mode: continuous
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi

motion:
  threshold: 25
  contour_area: 33
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
objects:
  track:
    - person
    - cat
  filters:
    cat:
      threshold: 0.5
    person:
      min_area: 1000
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
      - car
    required_zones: []
    retain:
      default: 11
      mode: active_objects
      objects:
        person: 16
snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 2
    objects:
      person: 2
go2rtc:
  streams:
    garten:
        - rtsp://frigate:password@10.10.10.57/cam/realmonitor?channel=1&subtype=0
    garten_sub:
        - rtsp://frigate:password@10.10.10.57/cam/realmonitor?channel=1&subtype=1
    eingang:
        - rtsp://frigate:password@10.10.10.56/cam/realmonitor?channel=1&subtype=00&authbasic=ZnJpZ2F0ZTpTZXQ0RnJpZ2F0ZQ
    eingang_sub:
        - rtsp://frigate:password@10.10.10.56/cam/realmonitor?channel=1&subtype=01&authbasic=ZnJpZ2F0ZTpTZXQ0RnJpZ2F0ZQ
    vorgarten:
        - http://vorgarten.domain/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=password
        - ffmpeg:reolink
    vorgarten_sub:
        - http://vorgarten.domain/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=frigate&password=password
        - ffmpeg:reolink
    terasse:
        - rtsp://frigate:password@terasse.domain/cam/realmonitor?channel=1&subtype=0
    terasse_sub:
        - rtsp://frigate:password@terasse.domain/cam/realmonitor?channel=1&subtype=1
cameras:
  garten:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garten
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garten_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 576
      fps: 5
    motion:
      mask:
        - 704,0,704,576,0,576,0,349,165,382,191,426,203,539,491,537,419,445,300,407,323,372,304,324,204,362,95,345,39,285,163,232,95,225,0,272,0,0
  terasse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terasse
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/terasse_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 576
      fps: 5
    motion:
      mask:
       - 704,576,619,576,612,350,597,225,525,227,501,281,489,346,346,329,106,576,0,576,0,0,704,0
  eingang:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/eingang
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/eingang_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 576
      fps: 5
    motion:
      mask:
        - 412,576,199,393,196,310,336,257,452,263,446,430,704,576,704,0,0,0,0,576
  vorgarten:      # Reolink RLC-511
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vorgarten
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/vorgarten_sub
          input_args: preset-rtsp-restream
          roles:
            - rtmp
            - detect
    zones:
      relevant:
        coordinates: 79,480,517,480,640,255,590,199,458,150,63,262
    objects:
      track:
        - person
        - cat
        - car

    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
       - 134,480,126,408,60,304,54,196,104,172,172,130,408,104,618,176,483,237,394,278,356,342,366,420,434,480,640,480,640,0,0,0,0,480
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua + ReoLink
