### ISSUE TITLE
[Config Support]: Manual Events in MQTT

### ISSUE THREAD

**Issue by primevisionservices** [blakeblackshear/frigate#8391]
### Describe the problem you are having

I'm testing the frigate beta (0.13.0 Beta 3), and now I can create events via curl on the HTTP API.

"POST /api/events/<camera_name>/<label>/create"

but when sending an event I don't receive anything in the home assistant's mqtt, is that right? Don't these events also appear in mqtt for homeassistant?

### Version

0.13.0 Beta 3

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.14
  user: xxxxx
  password: xxxxxx

database:
  path: /db/frigate.db

go2rtc:
  streams:
    camera_01:      
      - dvrip://xxxxxxx:xxxxxx@192.168.50.245:34567?channel=0&subtype=1
      

cameras:
 
  camera_01:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_01
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 6
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 6
          mode: all
        pre_capture: 10
        post_capture: 10
    motion:
      mask:
        - 0,0,704,0,704,79,439,31,245,37,0,68


detectors:
    
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
