### ISSUE TITLE
[Config Support]: How not to loose stationary object during night

### ISSUE THREAD

**Issue by Tux92** [blakeblackshear/frigate#8402]
### Describe the problem you are having

I usually park my car in front of the garage. So I use the stationary function to know if the car is in front of the garage and I can't open it.
Some nights with storm or fog the car detection end and my sensor is empty.

This is a normal night:
![image](https://github.com/blakeblackshear/frigate/assets/26909922/96d3ca5e-353a-41dd-b69a-6b5fda2f3460)

And this a stormy night:
![image](https://github.com/blakeblackshear/frigate/assets/26909922/d89ef023-d6c7-4381-82b6-bdeae1d2fd34)

Is there something to change for not loosing car presence?

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: True
  restream: True

detect:
  enabled: True
  width: 1280
  height: 720
  stationary:
    interval: 10

snapshots:
  enabled: True

record:
  enabled: True

cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@10.0.0.20:554/Streaming/Channels/101
          roles:
            - detect
    detect:
      width: 2688
      height: 1520
    motion:
      mask:
        - 0,1034,384,861,785,718,1017,657,1406,652,1940,682,2415,730,2688,841,2688,0,0,0
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 10000
          max_area: 150000
          max_ratio: 0.4
        car:
          min_area: 30000
          max_area: 800000
    zones:
      fronte_garage:
        coordinates: 2688,1520,2688,1245,2316,1021,1639,1037,1631,1520
        filters:
          car:
            threshold: 0.45
      passo_carraio:
        coordinates: 1616,859,1986,851,1787,670,1598,667
```

### Relevant log output

```shell
nothing to report
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
