### ISSUE TITLE
[Support]: Audio detector not working / wrong config

### ISSUE THREAD

**Issue by mhoogenbosch** [blakeblackshear/frigate#8404]
### Describe the problem you are having

I'm using since b1 the version 0.13. I enabled the audio detection, never seemed to work, but never looked into it. Now with b3 I finally found some time to look into it.

It never detects motion. Since it is on my baby son's room, and i have shouted a lot this night to the camera (testing ;-)). It should have at least noticed a yell.

### Version

0.13 beta 3

### Frigate config file

```yaml
mqtt:
  host: 192.168.20.72
  user: mosquitto
  password: test

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous
  quality: 8

ui:
  live_mode: webrtc
  timezone: Europe/Amsterdam
#  use_experimental: true

objects:
  track:
    - person
    - dog
    - cat
    - bicycle
    - bird
    - car
    - sports ball
    - motorcycle  

ffmpeg:
  hwaccel_args: preset-vaapi
#  bin: ffmpeg
#  volume: "-af \"volume=30dB\"" 

#######################################################
#################### GO2RTC CONFIG ####################
#######################################################

go2rtc:
  streams:
    fynncam_sub:
      - rtsp://admin:password@192.168.21.3:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    fynncam_main:
      - rtsp://admin:password@192.168.21.3:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    fynncam_main_noaudio:
      - rtsp://127.0.0.1:8554/fynncam_main?video
    deurbel_sub:
#      - rtsp://admin:password@192.168.22.52:554/h264Preview_01_sub
#      - http://192.168.22.52/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=password
      - "ffmpeg:http://192.168.22.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus#raw=-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000"
#      - ffmpeg:deurbel_sub#audio=opus
    deurbel_main:
      - "ffmpeg:http://192.168.22.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus#raw=-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000"
      - rtsp://admin:password@192.168.22.52:554/h264Preview_01_main
    deurbel_main_noaudio:
      - rtsp://127.0.0.1:8554/deurbel_sub?video
    fietsen_sub:
      - rtsp://admin:password@192.168.22.48:554/h264Preview_01_sub
      - ffmpeg:fietsen_sub#audio=opus
    fietsen_main:
      - rtsp://admin:password@192.168.22.48:554/h264Preview_01_main
      - ffmpeg:fietsen_main#audio=opus
    fietsen_main_noaudio:
      - rtsp://127.0.0.1:8554/fietsen_sub?video
    wallboard:
      - http://192.168.22.201:2323/?cmd=getCamshot&password=password
      - "ffmpeg:http://127.0.0.1:1984/api/stream.mjpeg?src=wallboard#video=h264#hardware"
  webrtc:
    candidates:
     - 95.99.23.100:8555
#     - stun:8555      

#######################################################
#################### CAMERA CONFIG ####################
#######################################################

cameras:
  wallboard:
    live:
      stream_name: wallboard
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wallboard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 1
    detect:
      enabled: True
      fps: 5
      width: 352
      height: 288   
  fynncam:
    live:
      stream_name: fynncam_main
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fynncam_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/fynncam_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 1
    detect:
      enabled: True
      fps: 5
      width: 800
      height: 600
  fietsen:
    live:
      stream_name: fietsen_main
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fietsen_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record              
        - path: rtsp://127.0.0.1:8554/fietsen_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect           
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 1
        objects:
          person: 7        
    record:
      enabled: True
      events:
        retain:
          objects:
            person: 7
          default: 1
    detect:
      enabled: true
      fps: 5
      width: 640
      height: 360
    motion:
      mask:
        - 159,68,167,194,292,207,286,62
        - 103,200,31,193,26,91,85,81
  deurbel:
    live:
      stream_name: deurbel_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deurbel_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deurbel_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 2
        objects:
          person: 7
    record:
      enabled: True
      events:
        retain:
          objects:
            person: 7
          default: 2
    detect:
      enabled: true
      fps: 5
      width: 800
      height: 600
    motion:
      mask:
        - 0,600,254,427,254,188,0,0
        - 650,351,602,59,700,0,800,0,800,600,578,600
        - 403,458,515,490,532,372,536,251,509,128,401,125
```

### Relevant log output

```shell
023-10-31 17:32:23.874047356  [2023-10-31 18:32:23] ffmpeg.fynncam.audio           ERROR   : Output file #0 does not contain any stream
2023-10-31 17:32:23.880725959  [2023-10-31 18:32:23] audio.fynncam                  INFO    : Terminating the existing ffmpeg process...
2023-10-31 17:32:23.881080521  [2023-10-31 18:32:23] audio.fynncam                  INFO    : Waiting for ffmpeg to exit gracefully...
2023-10-31 17:32:27.729104360  [2023-10-31 18:32:27] audio.fynncam                  ERROR   : ffmpeg process is not running, restarting...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"},{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}}]
```

### Frigate stats

```json
{
    "cameras": {
        "deurbel": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5.1,
            "capture_pid": 346,
            "detection_enabled": 1,
            "detection_fps": 2.6,
            "ffmpeg_pid": 354,
            "pid": 332,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "fietsen": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 4.8,
            "capture_pid": 342,
            "detection_enabled": 1,
            "detection_fps": 17.6,
            "ffmpeg_pid": 12346,
            "pid": 330,
            "process_fps": 4.9,
            "skipped_fps": 0
        },
        "fynncam": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 338,
            "detection_enabled": 1,
            "detection_fps": 0,
            "ffmpeg_pid": 347,
            "pid": 328,
            "process_fps": 5,
            "skipped_fps": 0
        },
        "wallboard": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 1.4,
            "capture_pid": 334,
            "detection_enabled": 1,
            "detection_fps": 2,
            "ffmpeg_pid": 3641,
            "pid": 327,
            "process_fps": 1.4,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "80": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "/config/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "13.6",
            "cpu_average": "15",
            "mem": "0.6"
        },
        "109": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "4.3",
            "cpu_average": "5",
            "mem": "6.3"
        },
        "112": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "121": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "144": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "147": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "295": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "2.4"
        },
        "297": {
            "cmdline": "frigate.recording_manager",
            "cpu": "2.0",
            "cpu_average": "2",
            "mem": "3.5"
        },
        "305": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(55)",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "306": {
            "cmdline": "frigate.detector.coral",
            "cpu": "32.1",
            "cpu_average": "29",
            "mem": "3.2"
        },
        "309": {
            "cmdline": "frigate.output       ",
            "cpu": "1.8",
            "cpu_average": "1",
            "mem": "2.8"
        },
        "315": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 352x288 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "316": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 800x600 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "317": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "318": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 800x600 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "319": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "327": {
            "cmdline": "frigate.process:wallboard",
            "cpu": "4.3",
            "cpu_average": "6",
            "mem": "3.5"
        },
        "328": {
            "cmdline": "frigate.process:fynncam",
            "cpu": "4.0",
            "cpu_average": "4",
            "mem": "4.5"
        },
        "330": {
            "cmdline": "frigate.process:fietsen",
            "cpu": "44.5",
            "cpu_average": "39",
            "mem": "3.5"
        },
        "332": {
            "cmdline": "frigate.process:deurbel",
            "cpu": "13.1",
            "cpu_average": "12",
            "mem": "3.5"
        },
        "334": {
            "cmdline": "frigate.capture:wallboard",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "3.2"
        },
        "338": {
            "cmdline": "frigate.capture:fynncam",
            "cpu": "3.0",
            "cpu_average": "2",
            "mem": "3.2"
        },
        "342": {
            "cmdline": "frigate.capture:fietsen",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "3.2"
        },
        "346": {
            "cmdline": "frigate.capture:deurbel",
            "cpu": "3.5",
            "cpu_average": "2",
            "mem": "3.2"
        },
        "347": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/fynncam_sub?video=copy&audio=aac -r 5 -vf fps=5,scale_vaapi=w=800:h=600,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "5.3",
            "cpu_average": "5",
            "mem": "1.6"
        },
        "351": {
            "cmdline": "frigate.audio_manager",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "3.3"
        },
        "354": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/deurbel_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=800:h=600,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "6.8",
            "cpu_average": "6",
            "mem": "1.5"
        },
        "359": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/fietsen_main?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/fietsen-%Y%m%d%H%M%S.mp4",
            "cpu": "2.5",
            "cpu_average": "1",
            "mem": "0.7"
        },
        "360": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/deurbel_main?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/deurbel-%Y%m%d%H%M%S.mp4",
            "cpu": "2.8",
            "cpu_average": "2",
            "mem": "0.7"
        },
        "363": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.22.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b681f80d512ac3db6d6abedfd9d020ea",
            "cpu": "5.6",
            "cpu_average": "5",
            "mem": "0.8"
        },
        "365": {
            "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.22.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5a93f24717684ae02b6f58b44a1d986b",
            "cpu": "7.1",
            "cpu_average": "6",
            "mem": "0.9"
        },
        "3641": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/wallboard -r 5 -vf fps=5,scale_vaapi=w=352:h=288,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "1.4"
        },
        "3643": {
            "cmdline": "ffmpeg -hide_banner -v error -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags allow_profile_mismatch -fflags nobuffer -flags low_delay -i http://127.0.0.1:1984/api/stream.mjpeg?src=wallboard -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -an -vf format=vaapi|nv12,hwupload -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/7355894db681164dcfd1fc54d63a3dd0",
            "cpu": "2.0",
            "cpu_average": "2",
            "mem": "1.0"
        },
        "12346": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/fietsen_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "4.3",
            "cpu_average": "3",
            "mem": "1.3"
        },
        "13422": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 22.2,
    "detectors": {
        "coral": {
            "detection_start": 1698778942.390061,
            "inference_speed": 18.83,
            "pid": 306
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "3.48%",
            "mem": "-%"
        }
    },
    "processes": {
        "audioDetector": {
            "pid": 351
        },
        "go2rtc": {
            "pid": 89
        },
        "logger": {
            "pid": 295
        },
        "recording": {
            "pid": 297
        }
    },
    "service": {
        "last_updated": 1698778942,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 251.1,
                "mount_type": "tmpfs",
                "total": 256,
                "used": 4.9
            },
            "/media/frigate/clips": {
                "free": 17173.5,
                "mount_type": "ext4",
                "total": 118147.7,
                "used": 94927.5
            },
            "/media/frigate/recordings": {
                "free": 17173.5,
                "mount_type": "ext4",
                "total": 118147.7,
                "used": 94927.5
            },
            "/tmp/cache": {
                "free": 945.7,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 8
            }
        },
        "temperatures": {},
        "uptime": 5411,
        "version": "0.13.0-cd64399"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Imou Rex

**Comment by NickM-27** [comment]
Would need to see more logs and also I'd suggest using mqtt to see what the volume levels are looking like, most likely it is just below min_volume because the mic is quiet or something.

**Comment by mhoogenbosch** [comment]
> Would need to see more logs and also I'd suggest using mqtt to see what the volume levels are looking like, most likely it is just below min_volume because the mic is quiet or something.

![image](https://github.com/blakeblackshear/frigate/assets/36899598/c41c50eb-9248-456d-aa77-51abf3e018bb)

I have been lookin at mqtt explorer but i cannot find min_volume. Am I looking into the wrong place?

**Comment by NickM-27** [comment]
The fact that the volume and dbfs are not there indicates that it has never connected to your camera. I would suggest using 

```
rtsp://127.0.0.1:8554/fynncam_sub?video&audio=aac
```

for the config instead of what is there now

**Comment by NickM-27** [comment]
The fact that it is not there means that the camera has never connected. I'd suggest using this config instead

```yaml
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fynncam_sub?video
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/fynncam_sub?audio
          input_args: preset-rtsp-restream 
            - audio
        - path: rtsp://127.0.0.1:8554/fynncam_main?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
```
