### ISSUE TITLE
[Support]: 502 Bad Gateway after upgrade to 13

### ISSUE THREAD

**Issue by ajcorrea** [blakeblackshear/frigate#8414]
### Describe the problem you are having

Hello,

I have some automations that´s using Frigate + HA to start a service (send the person pictures to my Whatsapp via link).

After upgraded to 13, seems frigate api URL stop works and just works with HA Ingress module. But for access this url now, need to be authenticated in HA.

### Version

13-beta3

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local
  user: 
  password: 
  topic_prefix: frigate
  client_id: frigate01
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb
#  ov:
#    type: openvino
#    device: CPU
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml

#model:
#  width: 320
#  height: 320
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: 
    - -hwaccel
    - vaapi 
    - -hwaccel_device 
    - /dev/dri/renderD128 
    - -hwaccel_output_format 
    - yuv420p
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -an

#ffmpeg:
#  #hwaccel_args: preset-rpi-64-h264
#  hwaccel_args: preset-vaapi
  
cameras:
  Rua-Baixo:
    ffmpeg:
      # hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://127.0.0.1:8554/Rua-Baixo_sub
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: false
    detect:
      width: 1920
      height: 1080
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
        - plate
  Rua-Cima:
    ffmpeg:
      # hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://127.0.0.1:8554/Rua-Cima_sub
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: false
    detect:
      width: 1920
      height: 1080
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
        - plate
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.7
  Entrada:
    ffmpeg:
      # hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://127.0.0.1:8554/Entrada
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: false
    detect:
      width: 1920
      height: 1080
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.7
  Jardim:
    ffmpeg:
      # hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://127.0.0.1:8554/Jardim
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: false
    detect:
      width: 1920
      height: 1080
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.7
  Corredor:
    ffmpeg:
      # hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://127.0.0.1:8554/Corredor_sub
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: false
    detect:
      width: 704
      height: 576
#       width: 1920
#       height: 1080
    objects:
      track:
        - person
        - dog
        - cat

snapshots:
  enabled: True
  bounding_box: False
  timestamp: False
  retain:
    default: 10
    objects:
      person: 30

timestamp_style:
  position: "br"
  format: "%d/%m/%Y %H:%M:%S"
  thickness: 1
  effect: solid
  color:
    red: 255
    green: 255
    blue: 0
    
#objects:
#  track:
#    - person    
#  filters:
#    person:
#      min_area: 5000
#      max_area: 100000


go2rtc:
  streams:
    Rua-Baixo:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/201/
    Rua-Baixo_sub:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/202/
    Rua-Cima:
      - rtsp://xxx:xx192.168.0.184:554/Streaming/Channels/301/
    Rua-Cima_sub:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/302/
    Entrada:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/101/
    Entrada_sub:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/102/
    Corredor:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/501/
    Corredor_sub:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/502/
    Jardim:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/601/
    Jardim_sub:
      - rtsp://xxx:xx@192.168.0.184:554/Streaming/Channels/602/
detect:
  max_disappeared: 30
  stationary:
    interval: 10
    # estava 50
    threshold: 100 
#    max_frames:
#      objects:
#        car: 100
#        bicycle: 100
#        cat: 100
#        dog: 100

#ui:  
#  live_mode: mse
#  time_format: browser

birdseye:
  enabled: True
  width: 640
  height: 480
  quality: 1
  mode: objects
```

### Relevant log output

```shell
---
```

### FFprobe output from your camera

```shell
---
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikivision
