### ISSUE TITLE
[Support]: seeing memory usage going up on frigate 0.13

### ISSUE THREAD

**Issue by alez007** [blakeblackshear/frigate#8417]
### Describe the problem you are having

Frigate 0.12 memory usage in the past 90 days:
<img width="623" alt="Screenshot 2023-11-01 at 20 14 03" src="https://github.com/blakeblackshear/frigate/assets/459478/c6d92db4-c815-44b8-92b8-8a169ef4d698">

Frigate 0.13 memory usage in the past 7 days:
<img width="608" alt="Screenshot 2023-11-01 at 20 15 00" src="https://github.com/blakeblackshear/frigate/assets/459478/aeb49d54-4fdb-4ac6-a795-a42ce0409616">

### Version

0.13-beta2

### Frigate config file

```yaml
mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate013
  client_id: frigate013

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db


detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /frigate_models/yolox_tiny/public/yolox-tiny/FP16/yolox-tiny.xml

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolox
  labelmap_path: /frigate_models/dataset/coco_80cl.txt

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1024
  # Optional: Height of the output resolution (default: shown below)
  height: 768
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  restream: True

# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  #hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  hwaccel_args: preset-vaapi
  # Optional: global input args (default: shown below)
  #input_args:
  # - -avoid_negative_ts
  #  - make_zero
  #  - -fflags
  #  - +genpts+discardcorrupt
  #  - -flags
  #  - low_delay
  #  - -strict
  #  - experimental
  #  - -analyzeduration
  #  - 1000M
  #  - -probesize
  #  - 1000M
  #  - -use_wallclock_as_timestamps
  #  - '1'
  input_args: preset-http-reolink

  # Optional: global output args
#  output_args:
#    detect: -f rawvideo -pix_fmt yuv420p
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  output_args:
#    detect: -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1440
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  #max_disappeared: 50
  # Optional: Configuration for stationary object tracking
  #stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    #interval: 100
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate>
    #threshold: 100
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    #max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      #default: 3000
      # Optional: Object specific values
      #objects:
        #person: 1000


# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    #- cat
    # - dog
  filters:
    person:
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.3
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 0.8
      # Optional: minimum score for the object to initiate tracking (default: 0.5)
      min_score: 0.75
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      threshold: 0.85
    cat:
      min_score: 0.70
      threshold: 0.80
      max_area: 70000


# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 8
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      #- cat
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 15
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 20

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 15
    # Optional: Per object retention days
    objects:
      person: 20

motion:
  improve_contrast: True

# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 20

go2rtc:
  log:
    streams: trace
  streams:
    camera1:
      - "ffmpeg:http://192.168.1.9/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password="
      - ffmpeg:camera1#audio=opus
    camera2:
      - "ffmpeg:http://192.168.1.7/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password="
      - ffmpeg:camera2#audio=opus
    camera3:
      - "ffmpeg:http://192.168.1.8/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password="
      - ffmpeg:camera3#audio=opus
    camera4:
      - "ffmpeg:http://192.168.1.13/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password="
      - ffmpeg:camera4#audio=opus
    camera5:
      - "ffmpeg:http://192.168.1.6/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password="
      - ffmpeg:camera5#audio=opus
    camera6:
      - "ffmpeg:http://192.168.1.12/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password="
      - ffmpeg:camera6#audio=opus

cameras:
  camera1:
    birdseye:
      order: 1
    detect:
      enabled: True
    record:
      enabled: True
    motion:
      mask:
        - 826,148,824,279,1084,348,1115,199,1440,285,1440,0,0,0,0,367
    ffmpeg:
      inputs:
        #- path: rtsp://127.0.0.1:8554/camera1?video=copy&audio=aac
        - path: rtsp://127.0.0.1:8554/camera1?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
    objects:
      filters:
        person:
          min_area: 15000

  camera2:
    detect:
      enabled: False
    record:
      enabled: True
    birdseye:
      enabled: False
    ffmpeg:
      inputs:
        #- path: http://192.168.1.7/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
        - path: rtsp://127.0.0.1:8554/camera2?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
  camera3:
    birdseye:
      order: 3
    detect:
      enabled: True
    record:
      enabled: True
    motion:
      mask:
        - 1440,0,1440,129,630,149,0,266,0,0
        - 298,466,841,1080,1440,1080,1440,617,1440,415,1052,308,761,353
    ffmpeg:
      inputs:
        #- path: http://192.168.1.8/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
        - path: rtsp://127.0.0.1:8554/camera3?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
    objects:
      track:
#        - car
        - person
        #- cat
      filters:
        person:
          threshold: 0.8
          min_area: 10000


  camera4:
    detect:
      enabled: True
    record:
      enabled: True
    birdseye:
      enabled: False
    motion:
      mask:
        - 819,450,0,913,0,0,1021,0,1440,0,1440,91,1440,370,1132,661,969,780
    ffmpeg:
      inputs:
        #- path: http://192.168.1.13/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
        - path: rtsp://127.0.0.1:8554/camera4?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
    objects:
      filters:
        cat:
          max_area: 10000
        person:
          min_area: 8000


  camera5:
    detect:
      enabled: True
    record:
      enabled: True
    birdseye:
      order: 5
    motion:
      mask:
        - 0,974,597,498,996,323,1290,176,1440,173,1440,0,0,0
    objects:
      filters:
        person:
          min_area: 16000
    ffmpeg:
      inputs:
        #- path: http://192.168.1.6/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
        - path: rtsp://127.0.0.1:8554/camera5?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect


  camera6:
    detect:
      enabled: True
    record:
      enabled: True
    birdseye:
      order: 6
    motion:
      mask:
        - 0,0,683,0,647,375,778,471,718,909,0,905
        - 1071,682,1146,1080,1440,1080,1440,0,1214,0,689,0,697,64,1202,106
    objects:
      filters:
        person:
          min_area: 25000
          max_area: 250000
    ffmpeg:
      inputs:
        #- path: http://192.168.1.12/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
        #- path: rtmp://192.168.1.12/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=
        #- path: rtsp://admin:@192.168.1.12:554/h264Preview_01_main
        - path: rtsp://127.0.0.1:8554/camera6?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
```

### Relevant log output

```shell
nothing meaningful, no errors
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink 520A
