### ISSUE TITLE
[HW Accel Support]: Error Code 1: Cudnn (CUDNN_STATUS_MAPPING_ERROR)

### ISSUE THREAD

**Issue by leahciMic** [blakeblackshear/frigate#8423]
### Describe the problem you are having

I am having an issue where everything works fine for awhile, and then detection stops working.

Hardware:

```
           .://:`              `://:.            root@pve
         `hMMMMMMd/          /dMMMMMMh`          OS: Proxmox VE 8.0
          `sMMMMMMMd:      :mMMMMMMMs`           Kernel: x86_64 Linux 6.2.16-19-pve
  `-/+oo+/:`.yMMMMMMMh-  -hMMMMMMMy.`:/+oo+/-`   Uptime: 42m
  `:oooooooo/`-hMMMMMMMyyMMMMMMMh-`/oooooooo:`   Packages: 1885
    `/oooooooo:`:mMMMMMMMMMMMMm:`:oooooooo/`     Shell: bash 5.2.15
      ./ooooooo+- +NMMMMMMMMN+ -+ooooooo/.       Disk: 28T / 45T (64%)
        .+ooooooo+-`oNMMMMNo`-+ooooooo+.         CPU: AMD Ryzen 9 5900X 12-Core @ 24x 3.7GHz
          -+ooooooo/.`sMMs`./ooooooo+-           GPU: NVIDIA GeForce RTX 3050
            :oooooooo/`..`/oooooooo:             RAM: 42796MiB / 64212MiB
            :oooooooo/`..`/oooooooo:            
          -+ooooooo/.`sMMs`./ooooooo+-          
        .+ooooooo+-`oNMMMMNo`-+ooooooo+.        
      ./ooooooo+- +NMMMMMMMMN+ -+ooooooo/.      
    `/oooooooo:`:mMMMMMMMMMMMMm:`:oooooooo/`    
  `:oooooooo/`-hMMMMMMMyyMMMMMMMh-`/oooooooo:`  
  `-/+oo+/:`.yMMMMMMMh-  -hMMMMMMMy.`:/+oo+/-`  
          `sMMMMMMMm:      :dMMMMMMMs          
         `hMMMMMMd/          /dMMMMMMh         
           `://:`              `://:`       
```

```
Thu Nov  2 12:48:05 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050        On  | 00000000:05:00.0  On |                  N/A |
| 53%   45C    P2              61W / 115W |   1076MiB /  8192MiB |     27%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     81140      G   /usr/lib/xorg/Xorg                           89MiB |
|    0   N/A  N/A     83278      G   /usr/bin/gnome-shell                         18MiB |
|    0   N/A  N/A     87036      G   ...7057625,15446254101993136767,262144        1MiB |
|    0   N/A  N/A    102432      G   /usr/lib/firefox-esr/firefox-esr              8MiB |
|    0   N/A  N/A    282195      C   frigate.detector.tensorrt                   330MiB |
|    0   N/A  N/A    282328      C   ffmpeg                                      123MiB |
|    0   N/A  N/A    282331      C   ffmpeg                                      123MiB |
|    0   N/A  N/A    282341      C   ffmpeg                                      123MiB |
|    0   N/A  N/A    282343      C   ffmpeg                                      123MiB |
|    0   N/A  N/A    282446      C   ffmpeg                                      105MiB |
+---------------------------------------------------------------------------------------+
```

### Version

13.0-beta3-tensorrt

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate-nv:5000/api/config/schema.json
mqtt:
  enabled: True
  user: frigate
  password: ipwehosmssivpenrl
  host: mosquitto
logger:
  default: debug
  # logs:
    # frigate.object_detection: debug
    # detector.

go2rtc:
  streams:
    side:
      "ffmpeg:rtmp://reolink/bcs/channel0_ext.bcs?channel=0&user=admin&password=<redacted>"
    front_door:
      "ffmpeg:rtmp://reolink/bcs/channel1_ext.bcs?channel=1&user=admin&password=<redacted>"
    pool:
      "ffmpeg:rtmp://reolink/bcs/channel2_ext.bcs?channel=2&user=admin&password=<redacted>"
    court:
      "ffmpeg:rtmp://reolink/bcs/channel3_ext.bcs?channel=3&user=admin&password=<redacted>"

cameras:
  side:
    motion:
      mask:
        - 0,0,244,0,264,133,252,217,229,323,170,374,84,413,0,411
    best_image_timeout: 60
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

  front_door:
    best_image_timeout: 60
    record:
      events:
        required_zones:
          - everywhere
          - cars_entering
    snapshots:
      required_zones:
        - everywhere
        - cars_entering
    zones:
      cars_entering:
        coordinates: 260,100,444,103,448,58,261,43,0,32,0,111,0,138
        objects:
          - car
      everywhere:
        coordinates: 896,0,896,512,0,512,0,0
        objects:
          - person
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

  pool:
    best_image_timeout: 60
    objects:
      track:
        - person
      filters:
        person:
          min_area: 1000
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

  court:
    best_image_timeout: 60
    zones:
      road:
        coordinates: 258,0,278,59,485,58,695,68,725,105,640,125,544,142,470,146,411,142,355,149,287,136,207,126,180,0
        objects:
          - car
          - person
      property:
        coordinates: 687,512,896,512,896,173,716,104,443,143,228,136,0,225,0,512
        objects:
          - person
      kev:
        coordinates: 624,0,628,59,268,57,265,0
        objects:
          - person
    record:
      events:
        required_zones:
          - "road"
          - "property"
          - "kev"
    snapshots:
      required_zones:
        - "road"
        - "property"
        - "kev"
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/court?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/court?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

detectors:
  tensorrt:
    type: tensorrt
    device: 0
  # cpu1:
  #   type: cpu
  #   num_threads: 3
  # cpu2:
  #   type: cpu
  #   num_threads: 3
  # cpu3:
  #   type: cpu
  #   num_threads: 3
  # cpu4:
  #   type: cpu
  #   num_threads: 3

model:
  # path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  # path: /config/model_cache/tensorrt/yolov7x-320.trt
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  # path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

birdseye:
  enabled: True
  restream: True
  width: 1280
  height: 720
  mode: objects

database:
  path: /media/frigate/frigate.db

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-nvidia-h264
  # hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    # detect: -threads 2 -f rawvideo -pix_fmt rgb
    # Optional: output args for record streams (default: shown below)
    # record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -b:v 4M -r 25
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 896
  height: 512
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 10
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  # min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50

record:
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: active_objects
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 90
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 365

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  retain:
    # Required: Default retention days (default: shown below)
    default: 120
    # Optional: Per object retention days
    objects:
      person: 365

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  filters:
    person:
      min_area: 1500
      min_score: 0.75
    car:
      min_area: 1500

  track:
    - person
    - car
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta3-tensorrt
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
    shm_size: "2048mb" # update for your cameras based on calculation above
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - ./trt-models:/trt-models
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      #USE_FP16: false
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
      YOLO_MODELS: yolov7-tiny-416,yolov7-320,yolov7x-320,yolov7x-640
```

### Relevant log output

```shell
frigate              | 2023-11-02 12:41:34.500044791  [2023-11-02 12:41:34] frigate.detectors.plugins.tensorrt DEBUG   : Trying to load shared library libcudnn.so.8
frigate              | 2023-11-02 12:41:34.500306317  [2023-11-02 12:41:34] frigate.detectors.plugins.tensorrt DEBUG   : Loaded shared library libcudnn.so.8
frigate              | 2023-11-02 12:41:34.500307660  [2023-11-02 12:41:34] frigate.detectors.plugins.tensorrt DEBUG   : Trying to load shared library libcudnn.so.8
frigate              | 2023-11-02 12:41:34.500656212  [2023-11-02 12:41:34] frigate.detectors.plugins.tensorrt DEBUG   : Loaded shared library libcudnn.so.8
frigate              | 2023-11-02 12:41:34.500658145  [2023-11-02 12:41:34] frigate.detectors.plugins.tensorrt ERROR   : 1: [context.cpp::setStream::82] Error Code 1: Cudnn (CUDNN_STATUS_MAPPING_ERROR)
```

### FFprobe output from your camera

```shell
ffprobe version n6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, flv, from 'rtmp://reolink/bcs/channel0_ext.bcs?channel=0&user=admin&password=<redacted>':
  Metadata:
    |RtmpSampleAccess: true
    displayWidth    : 896
    displayHeight   : 512
  Duration: 00:00:00.00, start: 611217.515000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x512, 24 fps, 25 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

NVR: Reolink RLN8-410 | Camera: Reolink B800

### Any other information that may be helpful

NVR details:

Hardware No.: N2MB02
Config Version: v3.0.0.0
Firmware Version: v3.3.0.226_23031644

The problem occurs after an indeterminate amount of time (could be a couple of hours, or minutes)
