### ISSUE TITLE
[Config Support]: Manually Configured Time Zone Doesn't Work on iOS 17

### ISSUE THREAD

**Issue by gonzalezcalleja** [blakeblackshear/frigate#8424]
### Describe the problem you are having

Hi, I'm using this config for timezone:

```yaml
# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Europe/Madrid
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: False
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"
```

But I have an issue with timezone, recordings (/recording/) shows correct timezone but events view (/events) shows incorrect timezone (-1 hour).

Issue with Version: 0.13.0-CD64399 (beta 3) and with this custom docker-compose config about timezone:
```    
volumes:
      - /etc/localtime:/etc/localtime:ro
 ```

Thanks for your support! 

### Version

0.13.0-CD64399

### Frigate config file

```yaml
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Europe/Madrid
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: False
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"
```

### Relevant log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

custom docker-compose config about timezone:
```    
volumes:
      - /etc/localtime:/etc/localtime:ro
 ```
