### ISSUE TITLE
[Support]: Help in updating go2rtc in HAOS

### ISSUE THREAD

**Issue by madjetey** [blakeblackshear/frigate#8429]
### Describe the problem you are having

I want to update the go2rtc 1.2.0 [to 1.6.0+](https://github.com/AlexxIT/go2rtc/releases/) in Frigate running in HAOS (Home Assistant 2023.10.5, Supervisor 2023.10.1, Operating System 11.1, Frontend 20231005.0 - latest).  I want to confirm if the procedure is the same as in the [documentation](https://docs.frigate.video/configuration/advanced/#custom-go2rtc-version) especially since I'm not sure about using File editor to assign permissions.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.108
  port: 1883
  user: XXX
  password: XXX
  topic_prefix: frigate

#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 1

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

go2rtc:
  streams:
#    HouseCamTest:
#      - rtsp://192.168.1.108:8554/housecam1
#    HouseCamTest_lo:
#      - rtmp://192.168.1.108:1935/housecam1
    GateCam1:
      - rtsp://xxx:XXX@192.168.1.117:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:rtsp_cam#audio=copy#audio=opus"
    GateCam1Lo:
      - rtsp://xxx:XXX@192.168.1.117:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - "ffmpeg:rtsp_cam#audio=copy#audio=opus"
    GateCamHTTP: # <- for other streams
      - rtsp://xxx:XXX@192.168.1.117:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <- stream which supports video & aac audio
      - "ffmpeg:http_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)


cameras:
  HouseCam1:
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      # High resolution
        - path: rtsp://192.168.1.108:8554/housecam1
          roles:
            - record
      # Low resolution
        - path: rtsp://192.168.1.108:8554/housecam1-sub
          roles:
            - detect
      output_args:
        #detect: -dn -an -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        #rtmp: -c copy -f flv
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    record:
     enabled: True
     events:
       objects:
         - person
         - dog
    zones:
      DownstairsInterior1:
        coordinates: 0,0,0,360,454,360,567,0
  GateCam1:
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
       # High resolution
        - path: rtsp://127.0.0.1:8554/GateCam1
          roles:
            - record
      # Low resolution
        - path: rtsp://127.0.0.1:8554/GateCam1Lo
          roles:
            - detect
            - rtmp
      output_args:
        rtmp: preset-rtmp-generic
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 740 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    record:
     enabled: True
     events:
       objects:
         - person
         - car
         - dog
         - motorcycle
         - bicycle
    zones:
      Driveway1:
       coordinates: 289,292,302,480,740,480,740,0,567,0

objects:
  track:
    - person
    - car
    - dog
    - motorcycle
    - bicycle

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 640
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 360
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
        car: 100
        motorcycle: 200
        bicycle: 100

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: active_objects
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
      - dog
      - motorcycle
      - bicycle
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 1
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 2
        car: 1
        motorcycle: 1
        bicycle: 1
        dog: 1
```

### Relevant log output

```shell
2023-11-01 12:52:05.668712497  172.30.32.1 - - [01/Nov/2023:12:52:05 +0000] "GET /api/stats HTTP/1.1" 200 2394 "-" "HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11" "-"
2023-11-01 12:52:13.592165011  172.30.32.1 - - [01/Nov/2023:12:52:13 +0000] "GET /api/stats HTTP/1.1" 200 2359 "-" "HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11" "-"
2023-11-01 12:52:21.595740780  172.30.32.1 - - [01/Nov/2023:12:52:21 +0000] "GET /api/stats HTTP/1.1" 200 2289 "-" "HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11" "-"
2023-11-01 12:52:29.595178485  172.30.32.1 - - [01/Nov/2023:12:52:29 +0000] "GET /api/stats HTTP/1.1" 200 2324 "-" "HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11" "-"
2023-11-01 12:52:37.632471857  172.30.32.1 - - [01/Nov/2023:12:52:37 +0000] "GET /api/stats HTTP/1.1" 200 2324 "-" "HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11" "-"
```

### FFprobe output from your camera

```shell
2023-11-02 02:08:10.118230497  [2023-11-02 02:08:10] watchdog.HouseCam1             INFO    : Waiting for ffmpeg to exit gracefully...
2023-11-02 02:08:15.225494849  [2023-11-02 02:08:15] frigate.video                  ERROR   : HouseCam1: Unable to read frames from ffmpeg process.
2023-11-02 02:08:15.226546192  [2023-11-02 02:08:15] frigate.video                  ERROR   : HouseCam1: ffmpeg process is not running. exiting capture thread...
2023-11-02 02:08:20.130209980  [2023-11-02 02:08:20] watchdog.HouseCam1             ERROR   : Ffmpeg process crashed unexpectedly for HouseCam1.
2023-11-02 02:08:20.130676022  [2023-11-02 02:08:20] watchdog.HouseCam1             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-02 02:08:20.130948780  [2023-11-02 02:08:20] ffmpeg.HouseCam1.detect        ERROR   : rtsp://192.168.1.108:8554/housecam1-sub: Invalid data found when processing input
2023-11-02 02:08:20.151899114  [2023-11-02 02:08:20] watchdog.HouseCam1             ERROR   : No new recording segments were created for HouseCam1 in the last 120s. restarting the ffmpeg record process...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

ReolinkIPC-HDW2439TP-AS-LED-S2 & Wyze V3 by Docker Wyze Bridge
