### ISSUE TITLE
[Config Support]: Renaming Objects / Labelmap

### ISSUE THREAD

**Issue by 503Dev** [blakeblackshear/frigate#8441]
### Describe the problem you are having

This is not necessarily a problem, but I am not positive how or if this works as I think.  I wish to rename an object, for example, "cat" to "custom_name".  

I attempted to use the "labelmap" clause as such:
```
model:
  path: plus://00000000
  labelmap:
    14: fluffy
```
However, this did not make any difference.  If I change my object track list to include my custom label only, then it never tracks anything.

Is it possible to replace a label with a custom name (not something else already in the label) or is this not possible?

### Version

0.13.0-0858859

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.68.2
  user: user
  password: pass

detectors:
  coral:
    type: edgetpu
    device: usb


model:
  path: plus://000000000
  labelmap:
    14: fluffy
    15: fluffy

objects:
  track:
    - person
    - fluffy

<.... other config not directly related ....>
```

### Relevant log output

```shell
N/A no log output related
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Nothing else unusual.
