### ISSUE TITLE
[Config Support]: Timestamp missing in live video and clips, but not snapshots

### ISSUE THREAD

**Issue by Strux-DK** [blakeblackshear/frigate#8443]
### Describe the problem you are having

When i go to watch the live video in Frigate or a clip Frigate has saved, there is no timestamp. However, there is on the snapshots. I looked through the documentation and tried fiddling with the config file to make it work, but didn't succeed.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.18
  port: 1883
  client_id: frigate
  topic_prefix: frigate
  user: HAFrigate
  password: etagirFAH

go2rtc:
  # go2rtc is to prevent multiple streams from the camera. Go2rtc pulls the stream from the camera and is able to multiply it to other
  # services, minimizing unnecessary data transfer.
  streams:
    front_garden:
      - rtsp://XX:XX@192.168.1.30:554/stream1

ffmpeg:
  output_args:
    # Makes sure video AND audio is recorded
    record: preset-record-generic-audio-copy
    # If issues occur, try with: preset-record-generic-audio-copy
    # Befor change at 03.11.23, it was: preset-record-generic-audio-aac

cameras:
  front_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden
          roles:
            - record
            - detect

    zones:
      # Zones are used to specify certain filters on certain areas
      Front_garden_bedding:
        coordinates: 1447,1080,1546,586,634,482,0,889,0,1080
        # This zone only covers the flower bed and the pathway in front of the house
      Front_garden_entryway:
        coordinates: 735,420,1555,588,1557,329,1325,285,1239,381,1245,112,856,106,863,321
        # This zone covers some of the grass, the area in front of the front door and the pathway to it
      Front_garden_parking:
        coordinates: 0,870,510,557,949,285,833,222,413,386,0,583
        # This zone covers the parking space and the mailbox

detect:
  enabled: True
  width: 1920
  height: 1080
  fps: 5

objects:
  track:
    - person
    - cat
  filters:
    person:
      min_area: 10000
      # minimum width*height of the bounding box for the detected object
      min_score: 0.4
      # minimum score for the object to initiate tracking
      threshold: 0.7
      # minimum decimal percentage for tracked object's computed score to be considered a true positive
    cat:
      min_score: 0.3
      threshold: 0.5

record:
# Settings for recording
  enabled: True
  retain:
  # Retention settings for general recording
    days: 7
    # Save recordings for 7 days
    mode: motion
    # Save only recordings with movement
  events:
  # Events are when something is happening.
    pre_capture: 5
    # Seconds of recording before movement is registered, to also be saved
    post_capture: 5
    # Seconds of recording after movement is disappeared, to also be saved
    objects:
      - person
      - cat
    required_zones:
      - Front_garden_bedding
      - Front_garden_entryway
      - Front_garden_parking
    retain:
      default: 14
      # Number of days to retain/save recordings
      mode: active_objects
      # This mode saves all recording segments with active/moving objects

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  required_zones:
    - Front_garden_bedding
    - Front_garden_entryway
    - Front_garden_parking
  retain:
    default: 30

motion:
  # This section configures areas of motion to ignore
  mask:
    - 1515,1080,1920,1080,1920,0,1636,0
    # The windows of the house, where the camera can see movement inside the house

rtmp:
  enabled: False

timestamp_style:
  #Yes, the legacy software is capable of showing the timestamp, but i like all the configurations to be the same place
  position: "tl"
  format: "%d/%m/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 3

ui:
  timezone: Europe/Copenhagen
  strftime_fmt: "%d/%m/%Y %H:%M:%S"
  # Date and time style for the events overview in the UI
```

### Relevant log output

```shell
2023-11-03 09:02:25.349908769  [INFO] Starting Frigate...
2023-11-03 09:02:26.894939506  [2023-11-03 10:02:26] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-03 09:02:26.926246086  [2023-11-03 10:02:26] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-11-03 09:02:26.928661708  [2023-11-03 10:02:26] peewee_migrate                 INFO    : Starting migrations
2023-11-03 09:02:26.933271945  [2023-11-03 10:02:26] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-03 09:02:26.952985259  [2023-11-03 10:02:26] detector.cpu                   INFO    : Starting detection process: 299
2023-11-03 09:02:26.957541042  [2023-11-03 10:02:26] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-11-03 09:02:26.959486694  [2023-11-03 10:02:26] frigate.app                    INFO    : Output process started: 301
2023-11-03 09:02:26.969101028  [2023-11-03 10:02:26] frigate.app                    INFO    : Camera processor started for front_garden: 303
2023-11-03 09:02:26.970846764  [2023-11-03 10:02:26] frigate.app                    INFO    : Capture process started for front_garden: 305
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
