### ISSUE TITLE
[Camera Support]: Dahua PTZ not working

### ISSUE THREAD

**Issue by matthiasgold** [blakeblackshear/frigate#8445]
### Describe the problem you are having

I have a Dahua SD3A405-GN-PV1 PTZ Camera. The video configuration works and people are recognized, but the PTZ control does not work. When I activate onvif in the configuration, the error "Onvif is not setup" appears in the log. 
According to the specification, the camera supports onvif-s and onvif-t. 

The tool fovtest.py outputs the following:

> Connected to ONVIF camera
> Created media service object
> Creating PTZ object
> Created PTZ service object
> NO - RelativeMove Pan/Tilt within the camera's field of view is unsupported.
> YES - RelativeMove Zoom is supported.

### Version

0.13.0-CD64399

### Frigate config file

```yaml
Cam_2:
    onvif:
      host: 192.168.7.154
      port: 80
      user: frigate
      password: ******
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam_2_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Cam_2?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
      events:
        required_zones:
          - pavement
    snapshots:
      enabled: true
    zones:
        pavement:
          coordinates: 0,440,702,440,702,283,483,239,483,141,304,117,224,182,122,205,0,310
          objects:
            - person
        entrance:
          coordinates: 498,233,489,143,301,114,179,190
    motion:
      mask: 
        - 119,87,702,171,702,0,0,0,0,134
    detect:
      width: 702
      height: 440
    live:
      stream_name: Cam_2

logger:
  default: info
  logs:
    frigate.ptz.onvif: debug
```

### Relevant log output

```shell
frigate.ptz.onvif              ERROR   : Onvif connection to Cam_2 failed: Unknown error: Unknown fault occured
frigate.ptz.onvif              ERROR   : Onvif is not setup for Cam_2
```

### FFprobe output from your camera

```shell
** not relevant. video works
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Dahua SD3A405-GN-PV1
