### ISSUE TITLE
Inertia feature for specific object detection?

### ISSUE THREAD

**Issue by cvroque** [blakeblackshear/frigate#8449]
**Describe what you are trying to accomplish and why in non technical terms**
I have an outdoor camera that faces the street, I made different zones for my patio, sidewalk and road. 
A passing car will show up for 5~8s at most.

The inertia feature for my road zone helps quite a bit and I get an notification only from parked cars, very satisfied. But I don't want to record every car that passes on the road , just the ones that park in front of it.

**Describe the solution you'd like**
I would like to be ablet to set inertia for object and/or zone recording.

**Describe alternatives you've considered**
I started by creating different zones (enlarging "sidewalk" zone and recording cars there, add cars mask on road) and adjusting sizes based on recordings, but due to the angle (and bad drivers) sometimes parked cars will be too far to be in the sidewalk zone.

**Additional context**
The inertia feature is great, thanks for the new features!

**Comment by NickM-27** [comment]
I think this should be working as is unless I'm misunderstanding. If you make the street zone required for recordings then it will only record if the car is stopped, same as notifications.

**Comment by cvroque** [comment]
Hello, thanks for the fast reply!

I had my configuration like this:

```
  zones:
      patio:
        coordinates: 640,360,640,112,290,64,0,279,0,360
      road:
        coordinates: 551,78,225,51,0,70,0,0,640,0,640,105
        inertia: 60 #fps = 12s
```

Then there are times that a car passes by for a really short time, like this:
![image](https://github.com/blakeblackshear/frigate/assets/65680394/4d018d83-1be4-4a21-8d4f-8b30c20bdc0e) ->![image](https://github.com/blakeblackshear/frigate/assets/65680394/e36ffe71-eec5-4f01-997d-824afbeca8b7)
The inertia setting keeps the car count at zero and I don't receive a notification, which is great. 
But I still end up recording every car that passes by, even for 2 seconds.

After I tried your suggestion it's correctly preventing any recording, thanks a lot!

I'll leave the final configuration here:

```
    zones:
      patio:
        coordinates: 640,360,640,112,290,64,0,279,0,360
      road:
        coordinates: 551,78,225,51,0,70,0,0,640,0,640,105
        inertia: 60 #fps = 12s
    record:
      events:
        required_zones:
        - patio
        - road
    snapshots:
      required_zones:
      - patio
      - road
```
