### ISSUE TITLE
[Config Support]: Frigate detects person outside zone?

### ISSUE THREAD

**Issue by MarcelFranken** [blakeblackshear/frigate#8450]
### Describe the problem you are having

I've created a zone in Frigate called "Zone Carport Person" where only people should be detected. However, a person was detected for this zone even though they were outside of it. Can someone please tell me what I'm doing wrong?

Zone Carport Person:
![image](https://github.com/blakeblackshear/frigate/assets/25133684/355cc70f-2786-4d49-bf4c-0dfe8aa0659b)

Detected Person:
![image](https://github.com/blakeblackshear/frigate/assets/25133684/1998b860-c2c3-45d2-aa4a-eb52a744010c)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.15
  user: smarthome
  password: ###
database:
  path: /config/frigate.db

birdseye:
  enabled: True
  mode: objects

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True 
  retain:
    days: 30
    mode: motion
  events:
    pre_capture: 6
    post_capture: 20
    retain:
      default: 7
      mode: active_objects

snapshots:
  enabled: True
  timestamp: false
  clean_copy: true
  bounding_box: true
  quality: 100
  retain:
    default: 30

objects:
  track:
    - person
    - car
  filters:
    person:
      threshold: 0.60
      min_area: 1800
    car:
      threshold: 0.60

ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    carport: 
      - rtsp://hass:###@192.168.178.18/h264Preview_01_main
      - "ffmpeg:carport#audio=opus"
     # - "ffmpeg:carport#video=h264#hardware"
    carport_sub: 
      - rtsp://hass:###@192.168.178.18/h264Preview_01_sub
      - "ffmpeg:carport_sub#audio=opus"
    #   - "ffmpeg:http://192.168.178.18/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=hass&password=###"

cameras:
  Carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    live:
      stream_name: carport

    detect:
      width: 640
      height: 480
      fps: 10
      stationary:
        interval: 0
        threshold: 50

    snapshots:
      required_zones:
        - zone_carport_cars
        - zone_carport_person

    record:
      enabled: True
      events:
        required_zones:
          - zone_carport_cars
          - zone_carport_person

    zones:
      zone_carport_cars:
        coordinates: 186,94,588,255,530,480,264,480,55,194
        objects:
          - car
      zone_carport_person:
        coordinates: 0,480,567,480,640,342,640,239,300,109,180,77,56,101,0,35,0,118
        objects:
          - person
          
    motion:
      improve_contrast: True
      mask:
       - 0,0,212,0,205,21,40,86
       - 212,35,158,0,640,0,640,79
```

### Relevant log output

```shell
none
```

### Frigate stats

```json
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
