### ISSUE TITLE
[Support]: Birdseye Not Loading

### ISSUE THREAD

**Issue by tdashmike** [blakeblackshear/frigate#8451]
### Describe the problem you are having

The cameras load on the home screen but when I click on Birdseye the video player just spins and then stops but no video shows.

### Version

0.13.0-CD64399

### Frigate config file

```yaml
ui:
  live_mode: mse
  
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

mqtt:
  enabled: False

go2rtc:
  ffmpeg:
    yi: "-avoid_negative_ts make_zero -fflags +genpts+igndts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -timeout 5000000 -i {input}"

  streams:
    FRONTDOOR:
      - ffmpeg:rtsp://192.168.1.45:8554/ch0_0.h264#video=copy#audio=copy#input=yi
  webrtc:
    candidates:
      - 192.168.1.4:8555
      - stun:8555

cameras:
  FRONTDOOR:
    ui:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/FRONTDOOR # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: True

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 2
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    required_zones: []
    retain:
      default: 31

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - cat
    - car
    - bear
    - bird
    - bicycle
    - bus
```

### Relevant log output

```shell
2023-11-03 21:31:12.082877796  192.168.7.5 - - [03/Nov/2023:21:31:12 -0400] "GET /api/config HTTP/1.1" 200 41877 "http://192.168.7.1:5000/birdseye" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Yi Home

### Any other information that may be helpful

<img width="447" alt="Screenshot 2023-11-03 213543" src="https://github.com/blakeblackshear/frigate/assets/19343200/34ea472d-1e1d-44fe-bba3-fc1de4403f8d">
