### ISSUE TITLE
[Camera Support]: Hikvision DS-2CD2366G2-IU best settings

### ISSUE THREAD

**Issue by BurningTheSky** [blakeblackshear/frigate#8452]
### Describe the problem you are having

I've just got my first Hikvision after running all Reolinks so I want to make sure I get the best possible set up going for it. I'd also like to be able to get audio on live video but I think I'm misunderstanding the RTSP config for that to work so any help would be appreaciated. Should I use H264+?

On the camera I have the following settings:
Video
```
Video Type: Video&Audio
Resolution: 3200*1800
Video Quality: Highest
Frame Rate: 20
Max bitrate: 10240
Video Encoing: H.264
H.264+: Off
```

Audio
```
Audio Encoding: AAC
Sampling Rate: 48kHz
Audio Stream Bitrate: 64kbps
Audio Input: MicIn
```

### Version

0.12.1-367d724

### Frigate config file

```yaml
go2rtc:
  streams:
    front:
      - "rtsp://user:password@192.168.x.xx:554//Streaming/Channels/1/"
      - "ffmpeg:front#audio=aac#audio=opus"
    front247:
      - "rtsp://user:password@192.168.x.xx:554//Streaming/Channels/2/"

cameras:
  # <------- Event record ------->

  Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
        - suitcase
        - skateboard
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Front_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all
```

### Relevant log output

```shell
No errors
```

### FFprobe output from your camera

```shell
[rtsp @ 0x556877c9d140] max delay reached. need to consume packet
[rtsp @ 0x556877c9d140] RTP: missed 337 packets
[h264 @ 0x556877ca2100] concealing 14307 DC, 14307 AC, 14307 MV errors in I frame
Input #0, rtsp, from 'rtsp://stream:rM43iU8NQY4VCw5o@192.168.3.54:554//Streaming/Channels/1/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 3200x1800 [SAR 1:1 DAR 16:9], 20 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2366G2-IU
