### ISSUE TITLE
[Detector Support]: Coral mPCI not being detected by Frigate

### ISSUE THREAD

**Issue by BurningTheSky** [blakeblackshear/frigate#8453]
### Describe the problem you are having

I have a mPCIe Coral installed in my system using a StarTech mPCIe to PCIe adaptor. Frigate is running on Unraid 6.12.4, I've installed the Coral driver on Unraid and it is detecting the TPU but when I try and include it in the config then it errors saying no coral device is detected.

Unraid driver output:
```
Coral TPU1:
Status: ALIVE
Temperature: 39.80 °C
Frequency: 500 MHz
Driver Version: 1.2
Framework Version: 1.1.4
```

I can see the device in Unraid in the SysDevs section:
```
 [1ac1:089a] 25:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
```

I have passed the pci through and installed lspci on the docker and I can see the device:
```
# lspci -v -s 25:00.0
25:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU (prog-if ff)
        Subsystem: Global Unichip Corp. Coral Edge TPU
        Flags: bus master, fast devsel, latency 0, IRQ 31, IOMMU group 15
        Memory at e2200000 (64-bit, prefetchable) [size=16K]
        Memory at e2100000 (64-bit, prefetchable) [size=1M]
        Capabilities: [80] Express Endpoint, MSI 00
        Capabilities: [d0] MSI-X: Enable+ Count=128 Masked-
        Capabilities: [e0] MSI: Enable- Count=1/32 Maskable- 64bit+
        Capabilities: [f8] Power Management version 3
        Capabilities: [100] Vendor Specific Information: ID=1556 Rev=1 Len=008 <?>
        Capabilities: [108] Latency Tolerance Reporting
        Capabilities: [110] L1 PM Substates
        Capabilities: [200] Advanced Error Reporting
        Kernel driver in use: apex
```

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.x.45
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci
  cuda:
    type: tensorrt

go2rtc:
  log:
    exec: trace
  streams:
    front:
      - "rtsp://user:password@192.168.x.54:554//Streaming/Channels/1/"
      - "ffmpeg:front#audio=aac#audio=opus"
    front247:
      - "rtsp://user:password@192.168.x.54:554//Streaming/Channels/2/"
    garage:
      - "ffmpeg:http://192.168.x.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    garage247:
      - "ffmpeg:http://192.168.x.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"
    garden:
      - "ffmpeg:http://192.168.x.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    garden247:
      - "ffmpeg:http://192.168.x.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"

cameras:
  # <------- Event record ------->

  Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
        - suitcase
        - skateboard
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
        - suitcase
        - skateboard
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Downstairs: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.x.57/live0
          roles:
            - detect
            - record
          hwaccel_args: preset-nvidia-h264
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  # <------- 24/7 record ------->

  Front_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all

  Garage_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all


model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='br0'
  --ip='192.168.x.48'
  --privileged=true
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Unraid"
  -e HOST_CONTAINERNAME="frigate"
  -e 'TCP_PORT_5000'='5000'
  -e 'TCP_PORT_8554'='8554'
  -e 'FRIGATE_RTSP_PASSWORD'='password'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-6b240216-4ebc-194d-099d-5d86624395a0'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='compute,utility,video'
  -e 'TCP_PORT_8555'='8555'
  -e 'UDP_PORT_8555'='8555'
  -e 'TCP_PORT_1984'='1984'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -v '/mnt/cache/appdata/frigate':'/config':'rw'
  -v '/mnt/user/Media/frigate':'/media/frigate':'rw'
  -v '/mnt/user/appdata/trt-models':'/trt-models':'ro'
  -v '/mnt/user/appdata/trt-models':'/trt-models':'ro'
  -v '/mnt/cache/frigate/':'/db':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/apex_0'
  --shm-size=256mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped
  --runtime=nvidia 'ghcr.io/blakeblackshear/frigate:stable-tensorrt'
```

### Relevant log output

```shell
2023-11-03 12:49:18.767219029  [INFO] Preparing go2rtc config...
2023-11-03 12:49:18.767580529  [INFO] Starting Frigate...
2023-11-03 12:49:18.768623682  [INFO] Starting NGINX...
2023-11-03 12:49:18.957519850  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-11-03 12:49:18.960160839  [INFO] Starting go2rtc...
2023-11-03 12:49:19.063972373  12:49:19.063 INF go2rtc version 1.8.1 linux/amd64
2023-11-03 12:49:19.064282260  12:49:19.064 INF [api] listen addr=0.0.0.0:1984
2023-11-03 12:49:19.064866554  12:49:19.064 INF [rtsp] listen addr=0.0.0.0:8554
2023-11-03 12:49:19.064871792  12:49:19.064 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-11-03 12:49:19.771751395  [2023-11-03 12:49:19] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-03 12:49:19.811722914  [2023-11-03 12:49:19] peewee_migrate                 INFO    : Starting migrations
2023-11-03 12:49:19.815743064  [2023-11-03 12:49:19] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-03 12:49:19.840242161  [2023-11-03 12:49:19] detector.coral                 INFO    : Starting detection process: 577
2023-11-03 12:49:19.956163315  [2023-11-03 12:49:19] detector.cuda                  INFO    : Starting detection process: 580
2023-11-03 12:49:19.956171347  [2023-11-03 12:49:19] frigate.app                    INFO    : Output process started: 585
2023-11-03 12:49:19.956179867  [2023-11-03 12:49:19] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-11-03 12:49:19.956187410  Process detector:coral:
2023-11-03 12:49:19.956194534  [2023-11-03 12:49:19] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-11-03 12:49:19.956218629  [2023-11-03 12:49:19] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe
