### ISSUE TITLE
[Bug]: TypeError: list indices must be integers or slices, not tuple on Beta 4

### ISSUE THREAD

**Issue by BBaoVanC** [blakeblackshear/frigate#8460]
### Describe the problem you are having

After updating to beta 4, Frigate shows an error in logs and crashes on startup:

```
2023-11-04 15:09:28.613699800  Process detector:tensorrt:
2023-11-04 15:09:28.614703785  Traceback (most recent call last):
2023-11-04 15:09:28.614737562    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-11-04 15:09:28.614740441      self.run()
2023-11-04 15:09:28.614752966    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-11-04 15:09:28.614755453      self._target(*self._args, **self._kwargs)
2023-11-04 15:09:28.614757707    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2023-11-04 15:09:28.614763378      detections = object_detector.detect_raw(input_frame)
2023-11-04 15:09:28.614766198    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2023-11-04 15:09:28.614783100      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-11-04 15:09:28.614798552    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 307, in detect_raw
2023-11-04 15:09:28.614801091      raw_detections[:, 4] = raw_detections[:, 4] * raw_detections[:, 6]
2023-11-04 15:09:28.614803398  TypeError: list indices must be integers or slices, not tuple
```

### Version

0.13.0 Beta 4

### Frigate config file

```yaml
enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - bang
    - glass
    - gunshot
    - explosion
    - boom
    - siren
    - door
    - doorbell
    - lawn_mower
    - police_car
    - ambulance
    - fire_engine
    - emergency_vehicle
    - honk

objects:
  track:
  - person
  - car
  - bird
  - cat
  - dog

go2rtc:
  streams:
    deck:
      - ffmpeg:http://deck.cam.ldb/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=[redacted]
    deck_sub:
      - ffmpeg:http://deck.cam.ldb/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=[redacted]

    front_door: # used for both record and detect
      - ffmpeg:rtsp://front-door.cam.ldb:554/img/media.sav?channel=1#video=copy#audio=aac

cameras:
  deck:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/deck?video=copy&audio=aac
        input_args: preset-rtsp-restream-low-latency
        roles:
          - record
          - audio

      - path: rtsp://127.0.0.1:8554/deck_sub?video=copy
        input_args: preset-rtsp-restream-low-latency
        roles:
          - detect
    detect:
      width: 640
      height: 480
      fps: 7

    zones:
      back_sidewalk:
        coordinates: 640,0,640,161,393,0
      back_deck:
        coordinates: 617,285,526,480,0,480,0,153,210,97

    objects:
      filters:
        person:
          mask:
            - 310,136,260,155,229,148,217,105,263,76
            - 177,61,216,64,215,23,184,25
            - 603,68,640,79,640,40,617,30
        cat:
          mask:
            - 425,245,578,344,640,212,638,94,463,92
        bird:
          mask:
            - 425,245,578,344,640,212,638,94,463,92 # bush on the right

  front_door:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
        input_args: preset-rtsp-generic
        roles:
          - record
          - detect
          - audio
    detect:
      width: 1280
      height: 720
      fps: 5

    zones:
      front_street:
        coordinates: 1280,467,814,0,962,0,1280,300
      front_porch:
        coordinates: 890,720,173,720,76,401,543,265
      front_sidewalk:
        coordinates: 1280,285,1082,91,1105,74,1280,220
    motion:
      mask:
      - 644,43,848,112,904,149,970,189,1050,245,1180,237,1188,192,1150,170,1202,130,1144,58,1126,0,631,0

    objects:
      filters:
        bird:
          mask:
            - 1012,472,974,591,863,534,955,425
        person:
          mask:
            - 1012,472,974,591,863,534,955,425
            - 709,426,765,450,779,394,731,379
            - 1166,337,1210,392,1274,296,1235,262
        car:
          mask:
            - 709,426,765,450,779,394,731,379
```

### Relevant log output

```shell
frigate-frigate-1    | s6-rc: info: service s6rc-fdholder: starting
frigate-frigate-1    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-frigate-1    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-frigate-1    | s6-rc: info: service fix-attrs: starting
frigate-frigate-1    | s6-rc: info: service s6rc-fdholder successfully started
frigate-frigate-1    | s6-rc: info: service fix-attrs successfully started
frigate-frigate-1    | s6-rc: info: service legacy-cont-init: starting
frigate-frigate-1    | s6-rc: info: service legacy-cont-init successfully started
frigate-frigate-1    | s6-rc: info: service trt-model-prepare: starting
frigate-frigate-1    | s6-rc: info: service log-prepare: starting
frigate-frigate-1    | No models to convert.
frigate-frigate-1    | s6-rc: info: service trt-model-prepare successfully started
frigate-frigate-1    | s6-rc: info: service log-prepare successfully started
frigate-frigate-1    | s6-rc: info: service nginx-log: starting
frigate-frigate-1    | s6-rc: info: service go2rtc-log: starting
frigate-frigate-1    | s6-rc: info: service frigate-log: starting
frigate-frigate-1    | s6-rc: info: service nginx-log successfully started
frigate-frigate-1    | s6-rc: info: service go2rtc-log successfully started
frigate-frigate-1    | s6-rc: info: service go2rtc: starting
frigate-frigate-1    | s6-rc: info: service frigate-log successfully started
frigate-frigate-1    | s6-rc: info: service go2rtc successfully started
frigate-frigate-1    | s6-rc: info: service go2rtc-healthcheck: starting
frigate-frigate-1    | s6-rc: info: service frigate: starting
frigate-frigate-1    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-frigate-1    | s6-rc: info: service frigate successfully started
frigate-frigate-1    | s6-rc: info: service nginx: starting
frigate-frigate-1    | s6-rc: info: service nginx successfully started
frigate-frigate-1    | s6-rc: info: service legacy-services: starting
frigate-frigate-1    | 2023-11-04 15:09:12.029387967  [INFO] Preparing Frigate...
frigate-frigate-1    | 2023-11-04 15:09:12.030573818  [INFO] Starting NGINX...
frigate-frigate-1    | s6-rc: info: service legacy-services successfully started
frigate-frigate-1    | 2023-11-04 15:09:12.034241945  [INFO] Preparing go2rtc config...
frigate-frigate-1    | 2023-11-04 15:09:12.043083522  [INFO] Starting Frigate...
frigate-frigate-1    | 2023-11-04 15:09:12.429262584  [INFO] Starting go2rtc...
frigate-frigate-1    | 2023-11-04 15:09:12.517203945  15:09:12.517 INF go2rtc version 1.8.1 linux/amd64
frigate-frigate-1    | 2023-11-04 15:09:12.517470349  15:09:12.517 INF [api] listen addr=0.0.0.0:1984
frigate-frigate-1    | 2023-11-04 15:09:12.517788686  15:09:12.517 INF [rtsp] listen addr=0.0.0.0:8554
frigate-frigate-1    | 2023-11-04 15:09:12.517988378  15:09:12.517 INF [webrtc] listen addr=0.0.0.0:8555/tcp
frigate-frigate-1    | 2023-11-04 15:09:14.296856371  [2023-11-04 15:09:14] frigate.app                    INFO    : Starting Frigate (0.13.0-65e3e67)
frigate-frigate-1    | 2023-11-04 15:09:14.761833042  [2023-11-04 15:09:14] peewee_migrate.logs            INFO    : Starting migrations
frigate-frigate-1    | 2023-11-04 15:09:14.767498372  [2023-11-04 15:09:14] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate-frigate-1    | 2023-11-04 15:09:14.773504226  [2023-11-04 15:09:14] frigate.app                    INFO    : Recording process started: 452
frigate-frigate-1    | 2023-11-04 15:09:14.777370107  [2023-11-04 15:09:14] frigate.app                    INFO    : go2rtc process pid: 110
frigate-frigate-1    | 2023-11-04 15:09:14.803730838  [2023-11-04 15:09:14] detector.tensorrt              INFO    : Starting detection process: 461
frigate-frigate-1    | 2023-11-04 15:09:14.871968901  [2023-11-04 15:09:14] frigate.app                    INFO    : Output process started: 464
frigate-frigate-1    | 2023-11-04 15:09:14.956637175  [2023-11-04 15:09:14] frigate.app                    INFO    : Camera processor started for deck: 477
frigate-frigate-1    | 2023-11-04 15:09:14.965718024  [2023-11-04 15:09:14] frigate.app                    INFO    : Camera processor started for front_door: 478
frigate-frigate-1    | 2023-11-04 15:09:14.965955920  [2023-11-04 15:09:14] frigate.app                    INFO    : Capture process started for deck: 480
frigate-frigate-1    | 2023-11-04 15:09:14.972674685  [2023-11-04 15:09:14] frigate.app                    INFO    : Capture process started for front_door: 484
frigate-frigate-1    | 2023-11-04 15:09:14.979966544  [2023-11-04 15:09:14] frigate.app                    INFO    : Audio process started: 488
frigate-frigate-1    | 2023-11-04 15:09:15.088260822  [2023-11-04 15:09:15] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 175 MiB
frigate-frigate-1    | 2023-11-04 15:09:15.157933780  2023/11/04 15:09:15 [error] 154#154: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "nvr.ldb"
frigate-frigate-1    | 2023-11-04 15:09:15.282575424  [2023-11-04 15:09:15] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 301, GPU 236 (MiB)
frigate-frigate-1    | 2023-11-04 15:09:15.289122629  [2023-11-04 15:09:15] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 303, GPU 246 (MiB)
frigate-frigate-1    | 2023-11-04 15:09:15.299360793  [2023-11-04 15:09:15] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +179, now: CPU 0, GPU 179 (MiB)
frigate-frigate-1    | 2023-11-04 15:09:15.303123737  [2023-11-04 15:09:15] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 127, GPU 242 (MiB)
frigate-frigate-1    | 2023-11-04 15:09:15.303278068  [2023-11-04 15:09:15] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 127, GPU 250 (MiB)
frigate-frigate-1    | 2023-11-04 15:09:15.303414021  [2023-11-04 15:09:15] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +115, now: CPU 0, GPU 294 (MiB)
frigate-frigate-1    | 2023-11-04 15:09:22.029654609  [INFO] Starting go2rtc healthcheck service...
frigate-frigate-1    | 2023-11-04 15:09:28.613699800  Process detector:tensorrt:
frigate-frigate-1    | 2023-11-04 15:09:28.614703785  Traceback (most recent call last):
frigate-frigate-1    | 2023-11-04 15:09:28.614737562    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate-frigate-1    | 2023-11-04 15:09:28.614740441      self.run()
frigate-frigate-1    | 2023-11-04 15:09:28.614752966    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate-frigate-1    | 2023-11-04 15:09:28.614755453      self._target(*self._args, **self._kwargs)
frigate-frigate-1    | 2023-11-04 15:09:28.614757707    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
frigate-frigate-1    | 2023-11-04 15:09:28.614763378      detections = object_detector.detect_raw(input_frame)
frigate-frigate-1    | 2023-11-04 15:09:28.614766198    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
frigate-frigate-1    | 2023-11-04 15:09:28.614783100      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate-frigate-1    | 2023-11-04 15:09:28.614798552    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 307, in detect_raw
frigate-frigate-1    | 2023-11-04 15:09:28.614801091      raw_detections[:, 4] = raw_detections[:, 4] * raw_detections[:, 6]
frigate-frigate-1    | 2023-11-04 15:09:28.614803398  TypeError: list indices must be integers or slices, not tuple
frigate-frigate-1    | 2023-11-04 15:09:35.318392615  [2023-11-04 15:09:35] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
frigate-frigate-1    | s6-rc: info: service legacy-services: stopping
frigate-frigate-1    | s6-rc: info: service legacy-services successfully stopped
frigate-frigate-1    | s6-rc: info: service nginx: stopping
frigate-frigate-1    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate-frigate-1    | 2023-11-04 15:09:35.330259297  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate-frigate-1    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate-frigate-1    | 2023-11-04 15:09:35.387760709  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate-frigate-1    | s6-rc: info: service nginx successfully stopped
frigate-frigate-1    | s6-rc: info: service nginx-log: stopping
frigate-frigate-1    | s6-rc: info: service frigate: stopping
frigate-frigate-1    | 2023-11-04 15:09:35.389911806  [2023-11-04 15:09:35] frigate.app                    INFO    : Stopping...
frigate-frigate-1    | 2023-11-04 15:09:35.390245720  [2023-11-04 15:09:35] frigate.watchdog               INFO    : Exiting watchdog...
frigate-frigate-1    | s6-rc: info: service nginx-log successfully stopped
frigate-frigate-1    | 2023-11-04 15:09:35.393667804  [2023-11-04 15:09:35] frigate.events.cleanup         INFO    : Exiting event cleanup...
frigate-frigate-1    | 2023-11-04 15:09:35.398335858  [2023-11-04 15:09:35] frigate.record.cleanup         INFO    : Exiting recording cleanup...
frigate-frigate-1    | 2023-11-04 15:09:35.398484739  [2023-11-04 15:09:35] frigate.storage                INFO    : Exiting storage maintainer...
frigate-frigate-1    | 2023-11-04 15:09:35.398617927  [2023-11-04 15:09:35] frigate.ptz.autotrack          INFO    : Exiting autotracker...
frigate-frigate-1    | 2023-11-04 15:09:35.398739648  [2023-11-04 15:09:35] frigate.stats                  INFO    : Exiting stats emitter...
frigate-frigate-1    | 2023-11-04 15:09:35.815134487  [2023-11-04 15:09:35] frigate.comms.ws               INFO    : Exiting websocket client...
frigate-frigate-1    | 2023-11-04 15:09:35.966500403  [2023-11-04 15:09:35] frigate.object_processing      INFO    : Exiting object processor...
frigate-frigate-1    | 2023-11-04 15:09:36.353011176  [2023-11-04 15:09:36] frigate.events.maintainer      INFO    : Exiting event processor...
frigate-frigate-1    | 2023-11-04 15:09:36.354272159  [2023-11-04 15:09:36] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate-frigate-1    | 2023-11-04 15:09:36.357072887  [2023-11-04 15:09:36] frigate.record.maintainer      INFO    : Exiting recording maintenance...
frigate-frigate-1    | 2023-11-04 15:09:36.357274609  [2023-11-04 15:09:36] watchdog.deck                  INFO    : Terminating the existing ffmpeg process...
frigate-frigate-1    | 2023-11-04 15:09:36.357413190  [2023-11-04 15:09:36] watchdog.front_door            INFO    : Terminating the existing ffmpeg process...
frigate-frigate-1    | 2023-11-04 15:09:36.357536033  [2023-11-04 15:09:36] watchdog.deck                  INFO    : Waiting for ffmpeg to exit gracefully...
frigate-frigate-1    | 2023-11-04 15:09:36.357727720  [2023-11-04 15:09:36] watchdog.front_door            INFO    : Waiting for ffmpeg to exit gracefully...
frigate-frigate-1    | 2023-11-04 15:09:36.443727536  [2023-11-04 15:09:36] watchdog.deck                  INFO    : Terminating the existing ffmpeg process...
frigate-frigate-1    | 2023-11-04 15:09:36.443869159  [2023-11-04 15:09:36] watchdog.deck                  INFO    : Waiting for ffmpeg to exit gracefully...
frigate-frigate-1    | 2023-11-04 15:09:37.212461824  [2023-11-04 15:09:37] audio.front_door               INFO    : Terminating the existing ffmpeg process...
frigate-frigate-1    | 2023-11-04 15:09:37.212703041  [2023-11-04 15:09:37] audio.front_door               INFO    : Waiting for ffmpeg to exit gracefully...
frigate-frigate-1    | 2023-11-04 15:09:37.277427000  [2023-11-04 15:09:37] audio.deck                     INFO    : Terminating the existing ffmpeg process...
frigate-frigate-1    | 2023-11-04 15:09:37.277573378  [2023-11-04 15:09:37] audio.deck                     INFO    : Waiting for ffmpeg to exit gracefully...
frigate-frigate-1    | 2023-11-04 15:09:37.397828203  [2023-11-04 15:09:37] frigate.output                 INFO    : exiting output process...
frigate-frigate-1    | 2023-11-04 15:09:40.830737543  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 8 leaked shared_memory objects to clean up at shutdown
frigate-frigate-1    | 2023-11-04 15:09:40.830745853    warnings.warn('resource_tracker: There appear to be %d '
frigate-frigate-1    | 2023-11-04 15:09:40.834331679  [INFO] Service Frigate exited with code 0 (by signal 0)
frigate-frigate-1    | s6-rc: info: service frigate successfully stopped
frigate-frigate-1    | s6-rc: info: service trt-model-prepare: stopping
frigate-frigate-1    | s6-rc: info: service go2rtc: stopping
frigate-frigate-1    | s6-rc: info: service frigate-log: stopping
frigate-frigate-1    | 2023-11-04 15:09:40.837248705  exit with signal: terminated
frigate-frigate-1    | s6-rc: info: service trt-model-prepare successfully stopped
frigate-frigate-1    | s6-rc: info: service frigate-log successfully stopped
frigate-frigate-1    | 2023-11-04 15:09:40.843070549  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate-frigate-1    | s6-rc: info: service go2rtc successfully stopped
frigate-frigate-1    | s6-rc: info: service go2rtc-log: stopping
frigate-frigate-1    | s6-rc: info: service go2rtc-log successfully stopped
frigate-frigate-1    | s6-rc: info: service log-prepare: stopping
frigate-frigate-1    | s6-rc: info: service s6rc-fdholder: stopping
frigate-frigate-1    | s6-rc: info: service log-prepare successfully stopped
frigate-frigate-1    | s6-rc: info: service legacy-cont-init: stopping
frigate-frigate-1    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate-frigate-1    | s6-rc: info: service legacy-cont-init successfully stopped
frigate-frigate-1    | s6-rc: info: service fix-attrs: stopping
frigate-frigate-1    | s6-rc: info: service fix-attrs successfully stopped
frigate-frigate-1    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate-frigate-1    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

**Comment by Pgnee** [comment]
Same problem here.

```
2023-11-06 21:33:21.094342575  Process detector:tensorrt:
2023-11-06 21:33:21.095288466  Traceback (most recent call last):
2023-11-06 21:33:21.095481638    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-11-06 21:33:21.095482970      self.run()
2023-11-06 21:33:21.095629174    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-11-06 21:33:21.095630306      self._target(*self._args, **self._kwargs)
2023-11-06 21:33:21.095756332    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2023-11-06 21:33:21.095757454      detections = object_detector.detect_raw(input_frame)
2023-11-06 21:33:21.095886947    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2023-11-06 21:33:21.095888109      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-11-06 21:33:21.096037829    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 307, in detect_raw
2023-11-06 21:33:21.096039012      raw_detections[:, 4] = raw_detections[:, 4] * raw_detections[:, 6]
2023-11-06 21:33:21.096164467  TypeError: list indices must be integers or slices, not tuple
2023-11-06 21:33:27.483916987  [INFO] Starting go2rtc healthcheck service...
```

**Comment by NickM-27** [comment]
fixed in https://github.com/blakeblackshear/frigate/pull/8497

**Comment by vajonam** [comment]
confirmed working in `dev-cc5357a-tensorrt`

**Comment by Pgnee** [comment]
> confirmed working in `dev-cc5357a-tensorrt`

Where can I find a way to use this? Getting a access to resource denied on docker pull....  Sorry for my ignorance.  Relatively new to all this but trying ;-).

**Comment by vajonam** [comment]
@Pgnee 

In [here](https://github.com/blakeblackshear/frigate/pkgs/container/frigate) if you will find all the tags for which a docker image has bee built. 

Then its just a matter of using that tag name in your docker compose or run command.

```
    frigate:
      container_name: frigate
      restart: unless-stopped
      image: ghcr.io/blakeblackshear/frigate:dev-cc5357a-tensorrt
      .... 
```
