### ISSUE TITLE
[Support]: Single Camera stream unavailable after messing (and then restoring) with go2rtc's webrtc candidates. RTC stream still works.

### ISSUE THREAD

**Issue by CJOWood** [blakeblackshear/frigate#8462]
### Describe the problem you are having

I have been playing around with my webrtc settings in go2rtc as I moved to a Cloudflare Tunnel recently and wanted to make sure I was using WebRTC/STUN.

After playing around with the candidates settings for a while I suddenly lost access to a single camera (backyard_cam) which now show the following errors... I have an identical camera with identical settings that still works.
```
2023-11-04 15:05:39.288910718  [2023-11-04 15:05:39] frigate.video                  ERROR   : backyard_cam: Unable to read frames from ffmpeg process.
2023-11-04 15:05:39.290051070  [2023-11-04 15:05:39] frigate.video                  ERROR   : backyard_cam: ffmpeg process is not running. exiting capture thread...
2023-11-04 15:05:54.022206464  [2023-11-04 15:05:54] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for backyard_cam. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-11-04 15:05:59.308215289  [2023-11-04 15:05:59] watchdog.backyard_cam          ERROR   : Ffmpeg process crashed unexpectedly for backyard_cam.
2023-11-04 15:05:59.308767396  [2023-11-04 15:05:59] watchdog.backyard_cam          ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-04 15:05:59.308770420  [2023-11-04 15:05:59] ffmpeg.backyard_cam.detect     ERROR   : [rtsp @ 0x564542619c40] method DESCRIBE failed: 404 Not Found
2023-11-04 15:05:59.308776124  [2023-11-04 15:05:59] ffmpeg.backyard_cam.detect     ERROR   : rtsp://127.0.0.1:8554/backyard_cam_sub?video=copy: Server returned 404 Not Found
2023-11-04 15:05:59.330664553  [2023-11-04 15:05:59] frigate.video                  ERROR   : backyard_cam: Unable to read frames from ffmpeg process.
2023-11-04 15:05:59.331542343  [2023-11-04 15:05:59] frigate.video                  ERROR   : backyard_cam: ffmpeg process is not running. exiting capture thread...
```

The RTSP stream is accessible directly from the camera and the go2rtc stream 'http://<frigate>:5000/live/webrtc/stream.html?src=backyard_cam' works with WebRTC.

The config as been restored to last-good settings and restarts have been completed, including the camera... but this stream continues to error out.

### Version

0.13.0-cd64399

### Frigate config file

```yaml
model:
  path: plus://<key>
mqtt:
  host: <ha>
  user: frigate
  password: *******************

# ui:
  # use_experimental: true

detectors:
  coral_pci:
    type: edgetpu
    device: pci

snapshots:
  bounding_box: true

timestamp_style:
  position: bl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

objects:
  filters:
    person:
      threshold: .8
    car:
      threshold: .8
    bear:
      threshold: .8
    dog:
      threshold: .8
    bicycle:
      threshold: .8
    cat:
      threshold: .8

go2rtc:
  streams:
    backyard_cam:
    - ffmpeg:https://192.168.1.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass>#video=copy#audio=copy#audio=opus
    bakyard_cam_sub:
    - ffmpeg:https://192.168.1.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=<pass>
    driveway_cam:
    - ffmpeg:https://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass>#video=copy#audio=copy
    driveway_cam_sub:
    - ffmpeg:https://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=<pass>
    rvlane_cam:
    - ffmpeg:https://192.168.1.22/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass>
    rvlane_cam_sub:
    - ffmpeg:https://192.168.1.22/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=<pass>
    driveway_frontyard_cam:
    - rtsp://frigate:<pass>@192.168.1.23:554/Streaming/Channels/101/
    driveway_frontyard_sub:
    - rtsp://frigate:<pass>@192.168.1.23:554/Streaming/Channels/102/
    front_doorbell_cam:
    - ffmpeg:https://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass>#video=copy#audio=copy#audio=opus#raw=
      -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay
      -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
    - rtsp://frigate:Swoosh-Exception-Sweep5@192.168.1.24:554/h264Preview_01_main #This rtsp stream is included to enable 2-way audio
    front_doorbell_sub:
    - ffmpeg:https://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=<pass>#raw=
      -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay
      -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000

  webrtc:
    candidates:
    - stun:8555
    - 192.168.1.91:8555

cameras:
  front_doorbell_cam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_doorbell_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/front_doorbell_cam?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: front_doorbell_sub

    objects:
      track:
      - person
      - car
      - bear
      - dog
      - bicycle
      - cat

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      required_zones:
      - front_porch
      - front_path
      - roadway
      - front_garden

    record:
      enabled: true
      retain:
        days: 3
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
        - front_porch
        - front_path
        - roadway
        - front_garden
        retain:
          default: 5
          mode: active_objects
          objects:
            person: 7

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7

    motion:
      mask:
      - 640,0,640,213,640,209,575,207,579,217,512,216,471,0
      - 324,26,621,26,621,8,324,8
    zones:
      front_porch:
        coordinates: 125,480,454,480,640,480,640,387,603,362,480,338,336,315,97,451
        objects:
        - person
        - car
        - bear
        - dog
        - bicycle
        - cat
      roadway:
        coordinates: 545,262,561,278,501,282,401,276,307,272,228,261,115,240
        objects:
        - person
        - bear
        - bicycle
      front_garden:
        coordinates: 233,339,160,377,52,407,0,338,2,300,89,292
        objects:
        - person
        - car
        - bear
        - dog
        - bicycle
        - cat
      front_path:
        coordinates: 
          279,304,226,297,154,279,126,282,141,293,179,305,220,316,284,328,305,310,343,292,323,286
        objects:
        - person
        - car
        - bear
        - dog
        - bicycle
        - cat

  ########################################################################
  driveway_frontyard_cam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_frontyard_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/driveway_frontyard_cam?video=copy
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: driveway_frontyard_sub

    objects:
      track:
      - person
      - car
      - bear
      - dog
      - bicycle
      - cat
      # filters:
      #   person:
      #     threshold: 0.76

    zones:
      doorway:
        coordinates: 598,219,606,154,558,122,491,116,445,119,418,136
        objects:
        - person
        - bear
        - dog
        - bicycle
        - cat
      front_garden:
        coordinates: 227,364,303,480,534,480,606,249,474,183
        objects:
        - person
        - bear
        - dog
        - bicycle
        - cat
      house_parking:
        coordinates: 0,480,0,338,115,282,212,480
        objects:
        - person
        - bear
        - dog
        - bicycle
        - cat
      driveway_entrance:
        coordinates: 90,206,0,261,0,274,101,220
        objects:
        - person
        - car
        - bear
        - dog
        - bicycle
        - cat
      roadway:
        coordinates: 0,174,206,68,460,0,464,31,215,114,0,237
        objects:
        - person
        - bear
        - bicycle

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      required_zones:
      - driveway_entrance
      - front_garden
      - doorway
      - house_parking
      - roadway

    record:
      enabled: true
      retain:
        days: 3
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
        - driveway_entrance
        - front_garden
        - doorway
        - house_parking
        - roadway
        retain:
          default: 5
          mode: active_objects
          objects:
            person: 7

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 6

    motion:
      mask:
      - 184,440,184,456,24,456,24,440

########################################################################
  rvlane_cam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/rvlane_cam_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/rvlane_cam?video=copy
        input_args: preset-rtsp-restream
        roles:
        - record
    live:
      stream_name: rvlane_cam_sub

    zones:
      rvlane:
        coordinates: 342,279,640,302,640,214,562,114,463,100
      alleyway:
        coordinates: 452,0,640,0,640,88,454,78

    objects:
      track:
      - person
      - car
      - bear
      - dog
      - bicycle
      - cat
      # filters:
      #   person:
      #     threshold: 0.76

    motion:
      mask:
      - 430,142,358,161,221,190,107,281,0,197,0,0,451,0,450,46
      - 4,471,272,471,272,449,5,452

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true

    record:
      enabled: true
      retain:
        days: 3
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 5
          mode: active_objects
          objects:
            person: 7

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7

########################################################################
  backyard_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/backyard_cam_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/backyard_cam?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - record
      # output_args:
      #   record: preset-record-generic-audio-copy

    live:
      stream_name: backyard_cam_sub

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true

    record:
      enabled: true
      retain:
        days: 3
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 5
          mode: active_objects
          objects:
            person: 7

    detect:
      enabled: true
      width: 640
      height: 360
      fps: 7

    objects:
      track:
      - person
      - bear
      - dog
      - bicycle
      - cat
      # filters:
      #   person:
      #     threshold: 0.76

    zones:
      garage_entrance:
        coordinates: 590,95,585,131,569,151,522,136,519,93,558,49,582,62,563,80
      shed_entrance:
        coordinates: 24,173,85,151,59,110,9,114
      deck_stairs:
        coordinates: 105,360,492,360,253,298

    motion:
      mask:
      - 0,352,278,351,274,329,0,335

########################################################################
  driveway_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_cam_sub?video=copy
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/driveway_cam?video=copy
        input_args: preset-rtsp-restream
        roles:
        - record

    live:
      stream_name: driveway_cam_sub

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      required_zones:
      - driveway_entrance
      - suite_parking
      - house_parking
      - roadway

    record:
      enabled: true
      retain:
        days: 3
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
        - driveway_entrance
        - suite_parking
        - house_parking
        - roadway
        retain:
          default: 5
          mode: active_objects
          objects:
            person: 7

    detect:
      enabled: true
      width: 640
      height: 360
      fps: 7

    objects:
      track:
      - person
      - car
      - bear
      - dog
      - bicycle
      - cat

    zones:
      house_parking:
        coordinates: 526,360,582,162,383,123,104,360
        objects:
        - person
        - bear
        - dog
        - bicycle
        - cat
      roadway:
        coordinates: 363,33,264,23,105,20,144,0,518,0,640,25,640,88,480,47
        objects:
        - person
        - bear
        - bicycle
      suite_parking:
        coordinates: 241,80,0,245,116,329,369,115
        objects:
        - person
        - bear
        - dog
        - bicycle
        - cat
      driveway_entrance:
        coordinates: 321,42,608,99,604,142,261,72
        objects:
        - person
        - car
        - bear
        - dog
        - bicycle
        - cat


    motion:
      mask:
      - 109,0,0,0,0,52
      - 4,352,271,351,270,334,6,333
```

### Relevant log output

```shell
2023-11-04 15:05:39.288910718  [2023-11-04 15:05:39] frigate.video                  ERROR   : backyard_cam: Unable to read frames from ffmpeg process.
2023-11-04 15:05:39.290051070  [2023-11-04 15:05:39] frigate.video                  ERROR   : backyard_cam: ffmpeg process is not running. exiting capture thread...
2023-11-04 15:05:54.022206464  [2023-11-04 15:05:54] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for backyard_cam. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-11-04 15:05:59.308215289  [2023-11-04 15:05:59] watchdog.backyard_cam          ERROR   : Ffmpeg process crashed unexpectedly for backyard_cam.
2023-11-04 15:05:59.308767396  [2023-11-04 15:05:59] watchdog.backyard_cam          ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-04 15:05:59.308770420  [2023-11-04 15:05:59] ffmpeg.backyard_cam.detect     ERROR   : [rtsp @ 0x564542619c40] method DESCRIBE failed: 404 Not Found
2023-11-04 15:05:59.308776124  [2023-11-04 15:05:59] ffmpeg.backyard_cam.detect     ERROR   : rtsp://127.0.0.1:8554/backyard_cam_sub?video=copy: Server returned 404 Not Found
2023-11-04 15:05:59.330664553  [2023-11-04 15:05:59] frigate.video                  ERROR   : backyard_cam: Unable to read frames from ffmpeg process.
2023-11-04 15:05:59.331542343  [2023-11-04 15:05:59] frigate.video                  ERROR   : backyard_cam: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
None, just loads
```

### Frigate stats

```json
cameras	
backyard_cam	
audio_dBFS	0
audio_rms	0
camera_fps	0
capture_pid	467
detection_enabled	1
detection_fps	0
ffmpeg_pid	2165
pid	455
process_fps	0
skipped_fps	0
driveway_cam	
audio_dBFS	0
audio_rms	0
camera_fps	7.1
capture_pid	476
detection_enabled	1
detection_fps	1.7
ffmpeg_pid	498
pid	458
process_fps	7.1
skipped_fps	0
driveway_frontyard_cam	
audio_dBFS	0
audio_rms	0
camera_fps	6
capture_pid	463
detection_enabled	1
detection_fps	3.7
ffmpeg_pid	486
pid	451
process_fps	5.9
skipped_fps	0.1
front_doorbell_cam	
audio_dBFS	0
audio_rms	0
camera_fps	7.1
capture_pid	461
detection_enabled	1
detection_fps	4.7
ffmpeg_pid	475
pid	449
process_fps	7.1
skipped_fps	0
rvlane_cam	
audio_dBFS	0
audio_rms	0
camera_fps	7
capture_pid	464
detection_enabled	1
detection_fps	1.5
ffmpeg_pid	484
pid	452
process_fps	7
skipped_fps	0
cpu_usages	
1	
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
15	
cmdline	"s6-supervise s6-linux-init-shutdownd"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
16	
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
24	
cmdline	"s6-supervise s6rc-fdholder"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
25	
cmdline	"s6-supervise nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
26	
cmdline	"s6-supervise frigate-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
27	
cmdline	"s6-supervise go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
28	
cmdline	"s6-supervise nginx-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
29	
cmdline	"s6-supervise go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
30	
cmdline	"s6-supervise frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
31	
cmdline	"s6-supervise go2rtc-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
32	
cmdline	"s6-supervise s6rc-oneshot-runner"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
39	
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
42	
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
79	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
80	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
83	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
101	
cmdline	"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
cpu	"10.0"
cpu_average	"7"
mem	"0.3"
113	
cmdline	"bash ./run.user go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
114	
cmdline	"python3 -u -m frigate"
cpu	"4.7"
cpu_average	"3"
mem	"1.8"
130	
cmdline	"nginx: master process nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
132	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
133	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
134	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
135	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
136	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
137	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
138	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
139	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
418	
cmdline	"frigate.logger       "
cpu	"0.0"
cpu_average	"0"
mem	"0.6"
420	
cmdline	"frigate.recording_manager"
cpu	"0.0"
cpu_average	"4"
mem	"0.9"
428	
cmdline	"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(57)"
cpu	"0.7"
cpu_average	"0"
mem	"0.1"
430	
cmdline	"frigate.detector.coral_pci"
cpu	"0.7"
cpu_average	"0"
mem	"0.8"
431	
cmdline	"frigate.output       "
cpu	"0.7"
cpu_average	"0"
mem	"0.7"
446	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
448	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
449	
cmdline	"frigate.process:front_doorbell_cam"
cpu	"4.0"
cpu_average	"2"
mem	"0.8"
450	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
451	
cmdline	"frigate.process:driveway_frontyard_cam"
cpu	"1.3"
cpu_average	"1"
mem	"0.8"
452	
cmdline	"frigate.process:rvlane_cam"
cpu	"1.3"
cpu_average	"1"
mem	"0.8"
454	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
455	
cmdline	"frigate.process:backyard_cam"
cpu	"0.0"
cpu_average	"0"
mem	"0.7"
458	
cmdline	"frigate.process:driveway_cam"
cpu	"3.3"
cpu_average	"3"
mem	"0.8"
460	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
461	
cmdline	"frigate.capture:front_doorbell_cam"
cpu	"0.0"
cpu_average	"0"
mem	"0.7"
462	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
463	
cmdline	"frigate.capture:driveway_frontyard_cam"
cpu	"0.7"
cpu_average	"0"
mem	"0.7"
464	
cmdline	"frigate.capture:rvlane_cam"
cpu	"0.7"
cpu_average	"0"
mem	"0.7"
467	
cmdline	"frigate.capture:backyard_cam"
cpu	"0.0"
cpu_average	"0"
mem	"0.7"
475	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_doorbell_sub?video=copy -r 7 -vf fps=7,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"4.7"
cpu_average	"4"
mem	"0.2"
476	
cmdline	"frigate.capture:driveway_cam"
cpu	"0.7"
cpu_average	"0"
mem	"0.7"
484	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rvlane_cam_sub?video=copy -r 7 -vf fps=7,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"6.0"
cpu_average	"5"
mem	"0.2"
486	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_frontyard_sub?video=copy -r 6 -vf fps=6,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"1.3"
cpu_average	"1"
mem	"0.2"
495	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_doorbell_cam?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_doorbell_cam-%Y%m%d%H%M%S.mp4"
cpu	"0.7"
cpu_average	"0"
mem	"0.2"
496	
cmdline	"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=<pass> -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ed4f91354bfa47115d56fa2c69c13b54"
cpu	"0.7"
cpu_average	"1"
mem	"0.2"
498	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_cam_sub?video=copy -r 7 -vf fps=7,scale=640:360 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"5.3"
cpu_average	"4"
mem	"0.2"
501	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_frontyard_cam?video=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway_frontyard_cam-%Y%m%d%H%M%S.mp4"
cpu	"1.3"
cpu_average	"0"
mem	"0.2"
505	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/backyard_cam?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/backyard_cam-%Y%m%d%H%M%S.mp4"
cpu	"0.7"
cpu_average	"0"
mem	"0.2"
507	
cmdline	"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.1.22/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=<pass> -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/0b5786f9ac350e254627919a8865f2b1"
cpu	"2.0"
cpu_average	"1"
mem	"0.2"
508	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/rvlane_cam?video=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/rvlane_cam-%Y%m%d%H%M%S.mp4"
cpu	"0.7"
cpu_average	"0"
mem	"0.2"
510	
cmdline	"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=<pass> -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b95d9cd90668b96d896130dd1c3b0d27"
cpu	"1.3"
cpu_average	"1"
mem	"0.2"
511	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-cd64399 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_cam?video=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/driveway_cam-%Y%m%d%H%M%S.mp4"
cpu	"0.7"
cpu_average	"0"
mem	"0.1"
512	
cmdline	"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass> -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/851c16a66a9656f09fc49514b1bc3f10"
cpu	"5.3"
cpu_average	"4"
mem	"0.2"
516	
cmdline	"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.1.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass> -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/42a9bead8810947a544eec1a41b579d9"
cpu	"6.0"
cpu_average	"5"
mem	"0.2"
517	
cmdline	"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.1.22/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass> -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5089ed9a62944926330489083eccbc11"
cpu	"6.0"
cpu_average	"4"
mem	"0.2"
520	
cmdline	"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=<pass> -c:v copy -c:a copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/cee0f8a7c043d5ea5f5eafe87074526d"
cpu	"6.0"
cpu_average	"4"
mem	"0.2"
2143	
cmdline	"sleep 30s"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
detection_fps	11.6
detectors	
coral_pci	
detection_start	0
inference_speed	5.4
pid	430
processes	
go2rtc	
pid	101
logger	
pid	418
recording	
pid	420
service	
last_updated	1699136092
latest_version	"0.12.1"
storage	
/dev/shm	
free	115.7
mount_type	"tmpfs"
total	120
used	4.3
/media/frigate/clips	
free	38980.2
mount_type	"ext4"
total	1007348.5
used	926348.7
/media/frigate/recordings	
free	38980.2
mount_type	"ext4"
total	1007348.5
used	926348.7
/tmp/cache	
free	38980.2
mount_type	"overlay"
total	1007348.5
used	926348.7
temperatures	
apex_0	31.8
uptime	553
version	"0.13.0-cd64399"
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink RLC-810A
