### ISSUE TITLE
[Config Support]:  Could not run on Intel chip version of Mac

### ISSUE THREAD

**Issue by joseph2903106** [blakeblackshear/frigate#8473]
As the title tells , I can use the same code base in the M2 version Mac perfectly.

Whenever I transfer the same code to the intel version of mac, the following error will appear

nginx: [emerg] "proxy_pass" directive is duplicate in /usr/local/nginx/conf/nginx.conf:159

I have tried clean docker build cache using the following command "docker system prune ", 

and make file again as " make -f Makefile" then. execute the command 

"docker-compose -f docker-compose.yml up" , but still get the same error, 

I even changed /usr/local/nginx/conf/nginx.conf 

I deleted the entire line of proxy_pass code in conf:159, 

but the same error still occurs. 

Could you please guide me on how to execute frigate nvr on the Intel chip version of Mac?

This is the environment of my local server :

![image](https://github.com/blakeblackshear/frigate/assets/4049227/50a5621c-0fec-4467-ae0d-eebcfd04b6ca)

### Version

0.13.0-d1620b4e

### docker-compose.yml  file

```yaml
version: "3"
services:
  devcontainer:
    container_name: frigate-slc
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
    environment:
      YOLO_MODELS: yolov7-320

    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
```

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: False
  # Required: host name
  host: mqtt.server.com
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: home-assistant-1
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

logger:
  default: info
  logs:
    frigate.mqtt: debug
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 3
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets

cameras:
  channel1:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://user:pw@xxx.xxx.xxx.xxx:999/cam/realmonitor?channel=1&subtype=0
          input_args: -re -stream_loop -1 -fflags +genpts -rtsp_transport tcp
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 25
    snapshots: # <----- Enable snapshots
      enabled: True

live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
  stream_name: test
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - motorcycle
    - bus
    - plate
    - knife
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      mask: 0,0,1000,0,1000,200,0,200

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: False
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30
```

### Relevant log output

```shell
(base) josephwang@jialideMac-mini frigate % docker-compose -f docker-compose.yml up
mqtt is up-to-date
frigate-slc is up-to-date
Attaching to mqtt, frigate-slc
mqtt            | 1699195405: mosquitto version 1.6.15 starting
mqtt            | 1699195405: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt            | 1699195405: Opening ipv4 listen socket on port 1883.
mqtt            | 1699195405: Opening ipv6 listen socket on port 1883.
mqtt            | 1699195405: mosquitto version 1.6.15 running
frigate-slc     | s6-rc: info: service s6rc-fdholder: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-slc     | s6-rc: info: service fix-attrs: starting
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully started
frigate-slc     | s6-rc: info: service fix-attrs successfully started
frigate-slc     | s6-rc: info: service legacy-cont-init: starting
frigate-slc     | s6-rc: info: service legacy-cont-init successfully started
frigate-slc     | s6-rc: info: service log-prepare: starting
frigate-slc     | s6-rc: info: service log-prepare successfully started
frigate-slc     | s6-rc: info: service nginx-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log: starting
frigate-slc     | s6-rc: info: service frigate-log: starting
frigate-slc     | s6-rc: info: service nginx-log successfully started
frigate-slc     | s6-rc: info: service frigate-log successfully started
frigate-slc     | s6-rc: info: service go2rtc-log successfully started
frigate-slc     | s6-rc: info: service go2rtc: starting
frigate-slc     | s6-rc: info: service go2rtc successfully started
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: starting
frigate-slc     | s6-rc: info: service frigate: starting
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-slc     | s6-rc: info: service frigate successfully started
frigate-slc     | s6-rc: info: service nginx: starting
frigate-slc     | s6-rc: info: service nginx successfully started
frigate-slc     | s6-rc: info: service legacy-services: starting
frigate-slc     | 2023-11-05 14:43:25.793286751  [INFO] Preparing Frigate...
frigate-slc     | 2023-11-05 14:43:25.794872626  [INFO] Starting NGINX...
frigate-slc     | 2023-11-05 14:43:25.807866191  nginx: [emerg] "proxy_pass" directive is duplicate in /usr/local/nginx/conf/nginx.conf:159
frigate-slc     | 2023-11-05 14:43:25.811424212  [INFO] Preparing go2rtc config...
frigate-slc     | 2023-11-05 14:43:25.812068109  [INFO] Starting Frigate...
frigate-slc     | s6-rc: info: service legacy-services successfully started
frigate-slc     | 2023-11-05 14:43:25.818136484  [INFO] Service NGINX exited with code 1 (by signal 0)
frigate-slc     | s6-rc: info: service legacy-services: stopping
frigate-slc     | s6-rc: info: service legacy-services successfully stopped
frigate-slc     | s6-rc: info: service nginx: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: stopping
frigate-slc     | s6-rc: info: service nginx successfully stopped
frigate-slc     | s6-rc: info: service nginx-log: stopping
frigate-slc     | s6-rc: info: service frigate: stopping
frigate-slc     | s6-rc: info: service nginx-log successfully stopped
frigate-slc     | 2023-11-05 14:43:25.848700152  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate-slc     | 2023-11-05 14:43:25.853725507  [INFO] Service Frigate exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service frigate successfully stopped
frigate-slc     | s6-rc: info: service go2rtc: stopping
frigate-slc     | s6-rc: info: service frigate-log: stopping
frigate-slc     | s6-rc: info: service frigate-log successfully stopped
frigate-slc     | 2023-11-05 14:43:25.862372644  [INFO] The go2rtc service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service go2rtc successfully stopped
frigate-slc     | s6-rc: info: service go2rtc-log: stopping
frigate-slc     | s6-rc: info: service go2rtc-log successfully stopped
frigate-slc     | s6-rc: info: service log-prepare: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder: stopping
frigate-slc     | s6-rc: info: service log-prepare successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init successfully stopped
frigate-slc     | s6-rc: info: service fix-attrs: stopping
frigate-slc     | s6-rc: info: service fix-attrs successfully stopped
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate-slc     | s6-rc: info: service s6rc-fdholder: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-slc     | s6-rc: info: service fix-attrs: starting
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully started
frigate-slc     | s6-rc: info: service fix-attrs successfully started
frigate-slc     | s6-rc: info: service legacy-cont-init: starting
frigate-slc     | s6-rc: info: service legacy-cont-init successfully started
frigate-slc     | s6-rc: info: service log-prepare: starting
frigate-slc     | s6-rc: info: service log-prepare successfully started
frigate-slc     | s6-rc: info: service nginx-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log: starting
frigate-slc     | s6-rc: info: service frigate-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log successfully started
frigate-slc     | s6-rc: info: service go2rtc: starting
frigate-slc     | s6-rc: info: service nginx-log successfully started
frigate-slc     | s6-rc: info: service frigate-log successfully started
frigate-slc     | s6-rc: info: service go2rtc successfully started
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: starting
frigate-slc     | s6-rc: info: service frigate: starting
frigate-slc     | s6-rc: info: service frigate successfully started
frigate-slc     | s6-rc: info: service nginx: starting
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-slc     | 2023-11-05 14:43:30.407305656  [INFO] Preparing Frigate...
frigate-slc     | 2023-11-05 14:43:30.408522055  [INFO] Preparing go2rtc config...
frigate-slc     | s6-rc: info: service nginx successfully started
frigate-slc     | s6-rc: info: service legacy-services: starting
frigate-slc     | 2023-11-05 14:43:30.420365737  [INFO] Starting NGINX...
frigate-slc     | 2023-11-05 14:43:30.425899153  nginx: [emerg] "proxy_pass" directive is duplicate in /usr/local/nginx/conf/nginx.conf:159
frigate-slc     | s6-rc: info: service legacy-services successfully started
frigate-slc     | 2023-11-05 14:43:30.433345671  [INFO] Service NGINX exited with code 1 (by signal 0)
frigate-slc     | 2023-11-05 14:43:30.434646989  [INFO] Starting Frigate...
frigate-slc     | s6-rc: info: service legacy-services: stopping
frigate-slc     | s6-rc: info: service legacy-services successfully stopped
frigate-slc     | s6-rc: info: service nginx: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: stopping
frigate-slc     | 2023-11-05 14:43:30.452786694  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service nginx successfully stopped
frigate-slc     | s6-rc: info: service nginx-log: stopping
frigate-slc     | s6-rc: info: service frigate: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate-slc     | s6-rc: info: service nginx-log successfully stopped
frigate-slc     | 2023-11-05 14:43:30.463662366  [INFO] Service Frigate exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service frigate successfully stopped
frigate-slc     | s6-rc: info: service go2rtc: stopping
frigate-slc     | s6-rc: info: service frigate-log: stopping
frigate-slc     | s6-rc: info: service frigate-log successfully stopped
frigate-slc     | 2023-11-05 14:43:30.475659374  [INFO] The go2rtc service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service go2rtc successfully stopped
frigate-slc     | s6-rc: info: service go2rtc-log: stopping
frigate-slc     | s6-rc: info: service go2rtc-log successfully stopped
frigate-slc     | s6-rc: info: service log-prepare: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder: stopping
frigate-slc     | s6-rc: info: service log-prepare successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init successfully stopped
frigate-slc     | s6-rc: info: service fix-attrs: stopping
frigate-slc     | s6-rc: info: service fix-attrs successfully stopped
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate-slc     | s6-rc: info: service s6rc-fdholder: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-slc     | s6-rc: info: service fix-attrs: starting
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully started
frigate-slc     | s6-rc: info: service fix-attrs successfully started
frigate-slc     | s6-rc: info: service legacy-cont-init: starting
frigate-slc     | s6-rc: info: service legacy-cont-init successfully started
frigate-slc     | s6-rc: info: service log-prepare: starting
frigate-slc     | s6-rc: info: service log-prepare successfully started
frigate-slc     | s6-rc: info: service nginx-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log: starting
frigate-slc     | s6-rc: info: service frigate-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log successfully started
frigate-slc     | s6-rc: info: service go2rtc: starting
frigate-slc     | s6-rc: info: service nginx-log successfully started
frigate-slc     | s6-rc: info: service frigate-log successfully started
frigate-slc     | s6-rc: info: service go2rtc successfully started
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: starting
frigate-slc     | s6-rc: info: service frigate: starting
frigate-slc     | s6-rc: info: service frigate successfully started
frigate-slc     | s6-rc: info: service nginx: starting
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-slc     | s6-rc: info: service nginx successfully started
frigate-slc     | s6-rc: info: service legacy-services: starting
frigate-slc     | 2023-11-05 14:43:35.119942589  [INFO] Preparing Frigate...
frigate-slc     | 2023-11-05 14:43:35.121655051  [INFO] Starting NGINX...
frigate-slc     | 2023-11-05 14:43:35.127880535  [INFO] Preparing go2rtc config...
frigate-slc     | 2023-11-05 14:43:35.128546154  nginx: [emerg] "proxy_pass" directive is duplicate in /usr/local/nginx/conf/nginx.conf:159
frigate-slc     | 2023-11-05 14:43:35.136736921  [INFO] Service NGINX exited with code 1 (by signal 0)
frigate-slc     | 2023-11-05 14:43:35.143367677  [INFO] Starting Frigate...
frigate-slc     | s6-rc: info: service legacy-services successfully started
frigate-slc     | s6-rc: info: service legacy-services: stopping
frigate-slc     | s6-rc: info: service legacy-services successfully stopped
frigate-slc     | s6-rc: info: service nginx: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: stopping
frigate-slc     | 2023-11-05 14:43:35.166308094  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service nginx successfully stopped
frigate-slc     | s6-rc: info: service nginx-log: stopping
frigate-slc     | s6-rc: info: service frigate: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate-slc     | s6-rc: info: service nginx-log successfully stopped
frigate-slc     | 2023-11-05 14:43:35.183700254  [INFO] Service Frigate exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service frigate successfully stopped
frigate-slc     | s6-rc: info: service go2rtc: stopping
frigate-slc     | s6-rc: info: service frigate-log: stopping
frigate-slc     | 2023-11-05 14:43:35.189566719  [INFO] The go2rtc service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service go2rtc successfully stopped
frigate-slc     | s6-rc: info: service go2rtc-log: stopping
frigate-slc     | s6-rc: info: service frigate-log successfully stopped
frigate-slc     | s6-rc: info: service go2rtc-log successfully stopped
frigate-slc     | s6-rc: info: service log-prepare: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder: stopping
frigate-slc     | s6-rc: info: service log-prepare successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init successfully stopped
frigate-slc     | s6-rc: info: service fix-attrs: stopping
frigate-slc     | s6-rc: info: service fix-attrs successfully stopped
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate-slc     | s6-rc: info: service s6rc-fdholder: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-slc     | s6-rc: info: service fix-attrs: starting
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully started
frigate-slc     | s6-rc: info: service fix-attrs successfully started
frigate-slc     | s6-rc: info: service legacy-cont-init: starting
frigate-slc     | s6-rc: info: service legacy-cont-init successfully started
frigate-slc     | s6-rc: info: service log-prepare: starting
frigate-slc     | s6-rc: info: service log-prepare successfully started
frigate-slc     | s6-rc: info: service nginx-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log: starting
frigate-slc     | s6-rc: info: service frigate-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log successfully started
frigate-slc     | s6-rc: info: service go2rtc: starting
frigate-slc     | s6-rc: info: service nginx-log successfully started
frigate-slc     | s6-rc: info: service frigate-log successfully started
frigate-slc     | s6-rc: info: service go2rtc successfully started
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: starting
frigate-slc     | s6-rc: info: service frigate: starting
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-slc     | s6-rc: info: service frigate successfully started
frigate-slc     | s6-rc: info: service nginx: starting
frigate-slc     | s6-rc: info: service nginx successfully started
frigate-slc     | 2023-11-05 14:43:40.019296608  [INFO] Preparing go2rtc config...
frigate-slc     | 2023-11-05 14:43:40.020425045  [INFO] Preparing Frigate...
frigate-slc     | 2023-11-05 14:43:40.021176402  [INFO] Starting NGINX...
frigate-slc     | s6-rc: info: service legacy-services: starting
frigate-slc     | 2023-11-05 14:43:40.028605854  nginx: [emerg] "proxy_pass" directive is duplicate in /usr/local/nginx/conf/nginx.conf:159
frigate-slc     | 2023-11-05 14:43:40.037073549  [INFO] Service NGINX exited with code 1 (by signal 0)
frigate-slc     | s6-rc: info: service legacy-services successfully started
frigate-slc     | s6-rc: info: service legacy-services: stopping
frigate-slc     | 2023-11-05 14:43:40.045701960  [INFO] Starting Frigate...
frigate-slc     | s6-rc: info: service legacy-services successfully stopped
frigate-slc     | s6-rc: info: service nginx: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: stopping
frigate-slc     | s6-rc: info: service nginx successfully stopped
frigate-slc     | s6-rc: info: service nginx-log: stopping
frigate-slc     | s6-rc: info: service frigate: stopping
frigate-slc     | s6-rc: info: service nginx-log successfully stopped
frigate-slc     | 2023-11-05 14:43:40.064992042  [INFO] Service Frigate exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service frigate successfully stopped
frigate-slc     | 2023-11-05 14:43:40.068147259  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service frigate-log: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate-slc     | s6-rc: info: service go2rtc: stopping
frigate-slc     | s6-rc: info: service frigate-log successfully stopped
frigate-slc     | 2023-11-05 14:43:40.075653806  [INFO] The go2rtc service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service go2rtc successfully stopped
frigate-slc     | s6-rc: info: service go2rtc-log: stopping
frigate-slc     | s6-rc: info: service go2rtc-log successfully stopped
frigate-slc     | s6-rc: info: service log-prepare: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder: stopping
frigate-slc     | s6-rc: info: service log-prepare successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init successfully stopped
frigate-slc     | s6-rc: info: service fix-attrs: stopping
frigate-slc     | s6-rc: info: service fix-attrs successfully stopped
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate-slc     | s6-rc: info: service s6rc-fdholder: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-slc     | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-slc     | s6-rc: info: service fix-attrs: starting
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully started
frigate-slc     | s6-rc: info: service fix-attrs successfully started
frigate-slc     | s6-rc: info: service legacy-cont-init: starting
frigate-slc     | s6-rc: info: service legacy-cont-init successfully started
frigate-slc     | s6-rc: info: service log-prepare: starting
frigate-slc     | s6-rc: info: service log-prepare successfully started
frigate-slc     | s6-rc: info: service nginx-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log: starting
frigate-slc     | s6-rc: info: service frigate-log: starting
frigate-slc     | s6-rc: info: service go2rtc-log successfully started
frigate-slc     | s6-rc: info: service go2rtc: starting
frigate-slc     | s6-rc: info: service nginx-log successfully started
frigate-slc     | s6-rc: info: service frigate-log successfully started
frigate-slc     | s6-rc: info: service go2rtc successfully started
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: starting
frigate-slc     | s6-rc: info: service frigate: starting
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-slc     | 2023-11-05 14:43:45.318046893  [INFO] Preparing go2rtc config...
frigate-slc     | s6-rc: info: service frigate successfully started
frigate-slc     | s6-rc: info: service nginx: starting
frigate-slc     | 2023-11-05 14:43:45.321628373  [INFO] Preparing Frigate...
frigate-slc     | s6-rc: info: service nginx successfully started
frigate-slc     | s6-rc: info: service legacy-services: starting
frigate-slc     | 2023-11-05 14:43:45.326725408  [INFO] Starting NGINX...
frigate-slc     | 2023-11-05 14:43:45.335962448  nginx: [emerg] "proxy_pass" directive is duplicate in /usr/local/nginx/conf/nginx.conf:159
frigate-slc     | 2023-11-05 14:43:45.342069561  [INFO] Service NGINX exited with code 1 (by signal 0)
frigate-slc     | s6-rc: info: service legacy-services successfully started
frigate-slc     | s6-rc: info: service legacy-services: stopping
frigate-slc     | 2023-11-05 14:43:45.352575491  [INFO] Starting Frigate...
frigate-slc     | s6-rc: info: service legacy-services successfully stopped
frigate-slc     | s6-rc: info: service nginx: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck: stopping
frigate-slc     | s6-rc: info: service nginx successfully stopped
frigate-slc     | s6-rc: info: service nginx-log: stopping
frigate-slc     | 2023-11-05 14:43:45.380658941  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service frigate: stopping
frigate-slc     | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate-slc     | s6-rc: info: service nginx-log successfully stopped
frigate-slc     | 2023-11-05 14:43:45.390544871  [INFO] Service Frigate exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service frigate successfully stopped
frigate-slc     | s6-rc: info: service go2rtc: stopping
frigate-slc     | s6-rc: info: service frigate-log: stopping
frigate-slc     | 2023-11-05 14:43:45.400135312  [INFO] The go2rtc service exited with code 256 (by signal 15)
frigate-slc     | s6-rc: info: service go2rtc successfully stopped
frigate-slc     | s6-rc: info: service go2rtc-log: stopping
frigate-slc     | s6-rc: info: service go2rtc-log successfully stopped
frigate-slc     | s6-rc: info: service frigate-log successfully stopped
frigate-slc     | s6-rc: info: service log-prepare: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder: stopping
frigate-slc     | s6-rc: info: service s6rc-fdholder successfully stopped
frigate-slc     | s6-rc: info: service log-prepare successfully stopped
frigate-slc     | s6-rc: info: service legacy-cont-init: stopping
frigate-slc     | s6-rc: info: service legacy-cont-init successfully stopped
frigate-slc     | s6-rc: info: service fix-attrs: stopping
frigate-slc     | s6-rc: info: service fix-attrs successfully stopped
```

### Frigate stats

```json
(base) josephwang@jialideMac-mini frigate % cd web                                 
(base) josephwang@jialideMac-mini web % npm run dev                            

> frigate@0.0.0 dev
> vite --host


  VITE v4.5.0  ready in 531 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.1.103:5173/
  ➜  press h to show help
11:00:52 PM [vite] http proxy error at /api/config:
AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
11:01:02 PM [vite] http proxy error at /api/config:
AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5) (x2)
11:01:12 PM [vite] http proxy error at /api/config:
AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5) (x3)
11:01:12 PM [vite] http proxy error at /api/config:
AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5) (x4)
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Could you please guide me on how to execute frigate nvr on the Intel version of Mac?
