### ISSUE TITLE
[Support]: Prevent birdseye from displaying on certain objects

### ISSUE THREAD

**Issue by mostlychris** [blakeblackshear/frigate#8499]
### Describe the problem you are having

I use car detection to do some automation. In order to allow car detection, I have to set it as a detected object for the camera. I have a number of zones enabled and have the specific objects specified in those zones. I don't need car detection in all zones. For example, the front_street zone only has person and bicycle set as objects. However, I still get birdseye popping up that camera because I have to set objects globally for that camera in order for frigate to start. How can I tell birdseye to only show for objects specified in the zones? The blue box is really the only place I need car detection. I don't get events in the other zones, just want to stop birdseye from showing everything that drives by.

<img width="334" alt="image" src="https://github.com/blakeblackshear/frigate/assets/3884025/7c13b98d-8bb8-4cc3-9aee-b3753819da66">

### Version

13 beta 3

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  host: 172.31.10.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: pass
  stats_interval: 300

record:
  expire_interval: 10

detect:
  annotation_offset: -800

go2rtc:
  streams:
    driveway:
    - rtsp://user:pass@172.31.10.20:554/cam/realmonitor?channel=1&subtype=0
    driveway_sub:
    - rtsp://user:pass@172.31.10.20:554/cam/realmonitor?channel=1&subtype=1
    front_porch:
    - rtsp://user:pass@172.31.10.21:554/cam/realmonitor?channel=1&subtype=0
    front_porch_sub:
    - rtsp://user:pass@172.31.10.21:554/cam/realmonitor?channel=1&subtype=1
    east_side_cam:
    - rtsp://user:pass@172.31.10.22:554/cam/realmonitor?channel=1&subtype=0
    east_side_sub:
    - rtsp://user:pass@172.31.10.22:554/cam/realmonitor?channel=1&subtype=1
    west_side_cam:
    - rtsp://user:pass@172.31.10.24:554/cam/realmonitor?channel=1&subtype=0
    west_side_sub:
    - rtsp://user:pass@172.31.10.24:554/cam/realmonitor?channel=1&subtype=1
    garage:
    - rtsp://user:pass@172.31.10.152:554/h264Preview_01_main
    garage_sub:
    - rtsp://user:pass@172.31.10.152:554/h264Preview_01_sub
    back_porch:
    - rtsp://user:pass@172.31.10.23:554/cam/realmonitor?channel=1&subtype=0
    back_porch_sub:
    - rtsp://user:pass@172.31.10.23:554/cam/realmonitor?channel=1&subtype=1
    front_doorbell:
    - rtsp://user:pass@172.31.10.128:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    front_doorbell_sub:
    - rtsp://user:pass@172.31.10.128:554/cam/realmonitor?channel=1&subtype=1#backchannel=0

# motion:
#   # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
#   # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
#   # The value should be between 1 and 255.
#   threshold: 32

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%m/%d/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

cameras:
  driveway:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/driveway
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
      - person
      - dog
      - bicycle
      - cat
      - car
      filters:
        car:
          max_area: 70000
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - driveway_left_side
        - driveway_right_side
        - front_yard
        - front_street
      crop: true
      height: 500
      retain:
        default: 3
    zones:
      driveway_right_side:
        coordinates: 505,131,604,128,611,459,466,459,361,480,188,480,229,305,158,279,242,210,320,138
        #inertia: 1
        objects:
          - person
          - dog
          - cat
          - bicycle
      driveway_left_side:
        coordinates: 223,330,194,426,143,480,43,394,109,323,136,285
        #inertia: 1
        objects:
          - person
          - dog
          - cat
          - bicycle
          - car
      front_yard:
        coordinates: 145,278,299,148,152,165,29,256
        objects:
        - person
      front_street:
        coordinates: 80,183,187,155,337,132,640,123,640,0,502,0,292,63,0,161,0,251
        objects:
          - person
          - bicycle
    motion:
      mask:
      - 640,0,640,41,451,40,450,0
      lightning_threshold: 0.6
    record:
      enabled: true
      retain:
        days: 3
      events:
        retain:
          default: 3
          mode: active_objects
        required_zones:
          - driveway_left_side
          - driveway_right_side
          - front_yard
          - front_street
        pre_capture: 3
        post_capture: 10

  front_porch:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_porch_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/front_porch
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
      - person
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      required_zones:
      - front_porch_close_in
      retain:
        default: 3
    motion:
      mask:
      - 441,42,640,43,640,0,444,0
    zones:
      front_porch_close_in:
        coordinates: 640,0,640,480,201,480,156,301,112,0
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 3
          mode: active_objects
        required_zones:
        - front_porch_close_in
        pre_capture: 3
        post_capture: 10

  front_doorbell:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_doorbell_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/front_doorbell
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 720
      height: 576
      fps: 15
    objects:
      track:
      - person
      - dog
      - bicycle
      - cat
      - mouse
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 3
    motion:
      mask:
      - 720,0,720,28,430,22,428,0
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects
        pre_capture: 10
        post_capture: 15

  east_side_cam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/east_side_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/east_side_cam
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 1000
    objects:
      track:
      - person
      - dog
      - mouse
      - cat
      filters:
        person:
          mask:
          - 434,480,640,480,640,0,450,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 3
    zones:
      side_of_house:
        coordinates: 472,480,0,480,100,279,351,54,456,42
    motion:
      mask:
      - 464,232,424,480,640,480,640,0,439,0
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 3
          mode: motion
        pre_capture: 3
        post_capture: 10

  back_porch:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/back_porch_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/back_porch
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
      - person
      - dog
      - cat
      - mouse
      filters:
        person:
          mask:
          - 192,480,0,480,0,94
          - 538,331,366,480,640,480,640,90
          max_area: 100000 # Reduce the false positives when detecting whole porch as a person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    motion:
      mask:
      - 199,480,171,433,0,110,0,480,40,480
      - 640,163,640,480,536,480,387,480
    zones:
      deck_area:
        #intertia: 8
        coordinates: 105,0,436,0,484,21,640,108,640,290,640,398,427,480,181,480,108,352,62,257,0,112,0,39
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 3
          mode: motion
        pre_capture: 5
        post_capture: 15

  west_side_cam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/west_side_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/west_side_cam
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      filters:
        person:
          mask:
          - 314,480,0,480,0,0,199,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 3
    zones:
      west_side_of_house:
        coordinates: 323,78,478,65,640,174,640,290,640,480,310,480,263,321,193,0,268,0
    motion:
      mask:
      - 442,44,640,44,640,0,439,0
      - 0,480,319,480,233,204,196,0,0,0
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 3
          mode: motion
        pre_capture: 3
        post_capture: 10
        #

  garage:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/garage_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/garage
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
      - person
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 2
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    motion:
      mask:
      - 208,98,532,96,539,0,209,0

    
detectors:
  #  cpu1:
  #    type: cpu
  #    num_threads: 3
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  restream: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

# live:
#   height: 640
#   quality: 1
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1944,"width":2592},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW-28MM
