### ISSUE TITLE
Memory usage Frigate. What I should expect and how clean up works?

### ISSUE THREAD

**Issue by heikkis** [blakeblackshear/frigate#851]
**Describe the bug**

I have faced few time RPI 4 8GB (with Hassio and Frigate addon) to stuck and without video cable I could only reboot with force. Last time was just after running couple of days. Frigate is only "heavy" app in Hassio.

Now I have looked few times the memory usage and after few event it has gone up +50MB. Currently it is 925 MB. I will check it later again.

What I should expect for memory usage to be? How the clean up works?

Picture of process inside container (top in container):
![image](https://user-images.githubusercontent.com/1392264/109384250-3c108100-78f4-11eb-886f-f79376b2b60d.png)

**Version of frigate**
0.8.4-5043040

**Config file**

```yaml

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

mqtt:
  host: core-mosquitto.local.hass.io
  user: xxxx
  password: xxxx
  
cameras:
  takapiha:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://xxxx/Streaming/Channels/101/
          global_args: -hide_banner
          roles:
            - detect
            - clips
            - rtmp
    fps: 4
    width: 1920
    height: 1080    
    clips:
      enabled: true
      pre_capture: 2
      post_capture: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
  etupiha:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://xxxx/Streaming/Channels/101/
          roles:
            - detect
            - clips
            - rtmp
    fps: 4
    width: 1920
    height: 1080
    motion:
        mask:
            - 0,288,129,278,184,459,0,510
            - 0,0,1241,0,1243,188,702,380,342,446
    zones:
        etuovi:
            coordinates: 1744,315,1759,199,1540,186,1445,398    
        autotalli:
            coordinates: 1388,224,1488,224,1496,127,1383,129
    clips:
      enabled: true
      pre_capture: 2
      post_capture: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false

clips:
  max_seconds: 60
  retain:
    default: 15

snapshots:
  retain:
    default: 15

objects:
  track:
    - person
    - car
    - cat
    - dog
    - bicycle



```

**Frigate container logs**
```
Cannot see any in Hassio addon
```

**Frigate stats**
```json
{
  "detection_fps": 2.5, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 14.4, 
      "pid": 37
    }
  }, 
  "etupiha": {
    "camera_fps": 4.1, 
    "capture_pid": 46, 
    "detection_fps": 0.0, 
    "pid": 42, 
    "process_fps": 4.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 4089.2, 
        "mount_type": "tmpfs", 
        "total": 4096.4, 
        "used": 7.2
      }, 
      "/media/frigate/clips": {
        "free": 894833.9, 
        "mount_type": "ext4", 
        "total": 983752.8, 
        "used": 48311.1
      }, 
      "/media/frigate/recordings": {
        "free": 894833.9, 
        "mount_type": "ext4", 
        "total": 983752.8, 
        "used": 48311.1
      }, 
      "/tmp/cache": {
        "free": 4032.1, 
        "mount_type": "tmpfs", 
        "total": 4096.4, 
        "used": 64.3
      }
    }, 
    "uptime": 60252, 
    "version": "0.8.4-5043040"
  }, 
  "takapiha": {
    "camera_fps": 4.1, 
    "capture_pid": 44, 
    "detection_fps": 2.5, 
    "pid": 40, 
    "process_fps": 4.1, 
    "skipped_fps": 0.0
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below

Not able to do currently

**Screenshots**

**Computer Hardware**
 - Raspberry Pi 4 8GB
 - USB3 M2 SSD 1TB
 - OS: Hassio newest
 - Install method: Addon
 - Coral Version: USB3
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: two of them
 - Resolution: 1080p
 - FPS: 4

**Additional context**
-
