### ISSUE TITLE
[Support]: Wrong stream (detect) is used for live view and birdseye despite config setting

### ISSUE THREAD

**Issue by Programmierus** [blakeblackshear/frigate#8535]
### Describe the problem you are having

I have a Dahua fisheye camera that is mounted on the ceiling. Using a combination of ffmpeg filters I convert this image to a nice looking vstack of two horizontal views. For detection though I still take a direct 720p stream from the camera without any modifications (_btw - is it a good approach?_). In the config I setup restream (ffmpeg filtered) to be used as a live view. Despite this I am still getting the fisheye stream on: cameras tab, birdseye tab and in the liveview if I select fsmpeg. Interestingly, MSE shows correct restream, but it's the only place where I can see it.

### Version

0.12.1-367D724

### Frigate config file

```yaml
birdseye:
  enabled: True
  mode: continuous

go2rtc:
  streams:
    living_cam:
      - 'ffmpeg:rtsp://xxx:xxx@1.2.3.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif1#video=h264#audio=aac#raw=-vf "crop=1835:1835:385:25,v360=fisheye:e:ih_fov=180:iv_fov=180:pitch=90,crop=3650:830:0:925,split=2[left_half][right_half];[left_half]crop=1825:830:0:0[left_cropped];[right_half]crop=1825:830:1825:0[right_cropped];[left_cropped][right_cropped]vstack"'
      - 'ffmpeg:living_cam#audio=opus'

cameras:
  living:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/living_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:xxx@1.2.3.4:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          input_args: preset-rtsp-generic
          roles:
            - detect
    live:
      stream_name: living_cam
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
```

### Relevant log output

```shell
No errors in the logs, irrelevant
```

### FFprobe output from your camera

```shell
Irrelevant as working as expected
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua
