### ISSUE TITLE
[Support]: using Mask & Zone Generator producing an javascript error (Firefox)

### ISSUE THREAD

**Issue by osworx** [blakeblackshear/frigate#8543]
### Describe the problem you are having

Using Homeassistant Supervised:

> Core 2023.11.1
> Supervisor 2023.11.0
> Operating System 11.1
> Frontend 20231030.1

and Frigate **v4.0.0**

on a 

Raspberry pi 4 w. SSD card.
No Coral

Browser: Firefox 119.0

The bug: when I try to define a mask or zone, this javascript error is displayed (browser dev tools):

`Uncaught TypeError: e is undefined
    f https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/CameraMap-0e4b28dd.js:14
    Gn https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    Et https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    ni https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    ri https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    vn https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    Vr https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
CameraMap-0e4b28dd.js:14:457
`

### Version

4.0.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.0.0.60
  user: michael
  password: mic110459

cameras:
  Torkamera:  # <------ Name the camera
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://******:554/Streaming/Channels/102 #
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
    record:
      enabled:  true
      retain:
        days: 5 # default = 0
    snapshots:
      enabled: True
      timestamp: true
      retain:
        default: 20 # default = 10

birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
Uncaught TypeError: e is undefined
    f https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/CameraMap-0e4b28dd.js:14
    Gn https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    Et https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    ni https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    ri https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    vn https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
    Vr https://******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/assets/index-40e1e50b.js:1
CameraMap-0e4b28dd.js:14:457
```

### FFprobe output from your camera

```shell
no ffprobe installed (I assume)
```

### Frigate stats

```json
Sorry, don't know where this should be ..
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Hikvision DS-2CD2185FWD-I
