### ISSUE TITLE
[Camera Support]: Need expertise with finetuning my config.

### ISSUE THREAD

**Issue by BelgarionNL** [blakeblackshear/frigate#8544]
### Describe the problem you are having

I believe I am getting 5fps on my main stream for recording I would like to increase it to 15.

plus I might be missing some additional configuration parameters that will improve the overall quality/performance.

right now its running on my rpi for testing for my parents house but I will be copying it over to my i5 8th gen Unraid server.

### Version

0.13.0-65E3E67

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.57
  user: frigate
  password: frigate

# RPI CPU SETTINGS
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

# UNRAID CPU SETTINGS
  # ffmpeg:
  # hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  # log:
  #   exec: trace
  streams:
    Deurbel:
      - "ffmpeg:http://192.168.1.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=123Dw1#video=copy#audio=copy#audio=opus"
    Deurbel_sub:
      - "ffmpeg:http://192.168.1.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=123Dw1"

cameras:
  Deurbel:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Deurbel
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Deurbel_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Deurbel_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink Doorbell POE, Dahua IPC-HDBW2431F-AS-S2
