### ISSUE TITLE
[Support]: Stored clips are not playable > Javascript Error

### ISSUE THREAD

**Issue by osworx** [blakeblackshear/frigate#8545]
### Describe the problem you are having

When in **Frigate > Events >Click on any image >> Click on Clip** : the recorded clip is not displayed.
Instead the loading animation is displayed AND this javascript error (dev console) is displayed:

> VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. 
Object { code: 3, message: "Playback cannot continue. No available working or supported playlists." }
videojs-seek-buttons-fa3a5bd5.js:31:1499

Displaying snapshots is fully working.

Next error when I try to view clips, only waiting animation is displayd: **Cameras > Name-of-camera >Recordings**
a HTTP and javscript error is given:

> XHRGET
https://*******/api/hassio_ingress/BzWR0W3dOsbNb5Hi65deW6RHgnqnUctLj__GvaAnwwc/vod/2023-11/08/07/Torkamera/Europe,Vienna/master.m3u8
[HTTP/1.1 400 Bad Request 0ms]

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
videojs-seek-buttons-fa3a5bd5.js:31:1499

All clips can be displayed after downloading and viewing with VLC (for example, WIN Media Viewer is not able to display because of the format).

### Version

0.12.1-367d724

### Frigate config file

```yaml
# see https://docs.frigate.video/guides/getting_started and https://docs.frigate.video/configuration/#full-configuration-reference
mqtt:
  enabled: true
  host: 10.0.0.60
  user: ****
  password: ****

cameras:
  Torkamera:
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://*****/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://****/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
    record:
      enabled:  true
      retain:
        days: 5
    snapshots:
      enabled: True
      timestamp: true
      retain:
        default: 20
    # mask and zone as manually defined in Frigate
    motion:
        mask:
          - 1159,368,1005,697,645,622,821,209
    zones:
      zone_0:
        coordinates: 630,235,576,73,161,183,192,300

birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
see above
```

### FFprobe output from your camera

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2185FWD-I

### Any other information that may be helpful

not really .. all said above.
