### ISSUE TITLE
[Solved]: Reolink RLC-511 unable to read from ffmpeg / ffmpeg crash

### ISSUE THREAD

**Issue by asaupp** [blakeblackshear/frigate#8562]
### Describe the problem you are having

[Solved]
The issue was identified as config issue:
```
    vorgarten:
        - ffmpeg:http://vorgarten.domain.local/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=password#video=copy#audio=copy#audio=opus

    vorgarten_sub:
        - http://vorgarten.domain.local/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=password
```

As you might notice, the _sub doesn't contain `ffmpeg:`
Once adding that, the camera worked flawless again. Follow the docs & look at the details.

---- 

The HW setup is stable for the last 12+ month, since upgrading to frigate:0.13.0 I see very frequent (every 5 minutes at least) issues reading from the ReoLink camera due to ffmpeg not getting / delivering frames. Then the video will work fine for a couple of minutes again.

The Camera WebUI keeps showing video footage while the error occures, so its not the camera crashing or network droping in general.

Compared to the three Dahua cameras the ReoLink .. was picky in the past - but it has been much more stable prior to the upgrade.

I read a couple of tickets with similar ffmpeg issues, but they do not seem to match entirely. I've tried a couple of ReoLink specific config adaptions from them / docs - without success so far.

### Version

frigate:0.13.0-beta5

### Frigate config file

```yaml
logger:
  default: info
  logs:
    frigate.mqtt: error

mqtt:
  host: mqtt.domain.local
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/database/frigate.db

birdseye:
  enabled: True
  width: 1920
  height: 1080
  mode: continuous

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi


motion:
  threshold: 25
  contour_area: 33
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50

objects:
  track:
    - person
    - cat
  filters:
    cat:
      threshold: 0.5
    person:
      min_area: 1000

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
      - car
    required_zones: []
    retain:
      default: 11
      mode: active_objects
      objects:
        person: 16

snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 2
    objects:
      person: 2

go2rtc:
  streams:
    vorgarten:
        - ffmpeg:http://vorgarten.domain.local/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=password#video=copy#audio=copy#audio=opus

    vorgarten_sub:
        - http://vorgarten.domain.local/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=password

    terasse:
        - rtsp://frigate:password@terasse.domain.local/cam/realmonitor?channel=1&subtype=0
    terasse_sub:
        - rtsp://frigate:password@terasse.domain.local/cam/realmonitor?channel=1&subtype=1

cameras:
  vorgarten:      # Reolink RLC-511
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vorgarten?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/vorgarten_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - rtmp
            - detect

    zones:
      relevant:
        coordinates: 79,480,517,480,640,255,590,199,458,150,63,262

    objects:
      track:
        - person
        - cat
        - car

    detect:
      fps: 5

    motion:
      mask:
       - 134,480,126,408,60,304,54,196,104,172,172,130,408,104,618,176,483,237,394,278,356,342,366,420,434,480,640,480,640,0,0,0,0,480

  terasse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terasse
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/terasse_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 576
      fps: 5

    motion:
      mask:
       - 704,576,619,576,612,350,597,225,525,227,501,281,489,346,346,329,106,576,0,576,0,0,704,0
```

### Relevant log output

```shell
2023-11-10 09:18:01.980398851  [2023-11-10 09:18:01] watchdog.vorgarten             INFO    : No frames received from vorgarten in 20 seconds. Exiting ffmpeg...
2023-11-10 09:18:01.980526992  [2023-11-10 09:18:01] watchdog.vorgarten             INFO    : Waiting for ffmpeg to exit gracefully...
2023-11-10 09:18:02.038679216  [2023-11-10 09:18:02] frigate.video                  ERROR   : vorgarten: Unable to read frames from ffmpeg process.
2023-11-10 09:18:02.038814776  [2023-11-10 09:18:02] frigate.video                  ERROR   : vorgarten: Unable to read frames from ffmpeg process.
2023-11-10 09:18:02.038937262  [2023-11-10 09:18:02] frigate.video                  ERROR   : vorgarten: ffmpeg process is not running. exiting capture thread...
2023-11-10 09:18:12.039217921  [2023-11-10 09:18:12] watchdog.vorgarten             ERROR   : Ffmpeg process crashed unexpectedly for vorgarten.
2023-11-10 09:18:12.040124019  [2023-11-10 09:18:12] watchdog.vorgarten             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-10 09:18:37.112383316  127.0.0.1 - - [10/Nov/2023:09:18:37 +0100] "GET / HTTP/1.1" 200 10168 "-" "Wget/1.21" "-"
2023-11-10 09:19:32.071277065  [2023-11-10 09:19:32] watchdog.vorgarten             INFO    : No frames received from vorgarten in 20 seconds. Exiting ffmpeg...
2023-11-10 09:19:32.071474972  [2023-11-10 09:19:32] watchdog.vorgarten             INFO    : Waiting for ffmpeg to exit gracefully...
2023-11-10 09:19:32.128401200  [2023-11-10 09:19:32] frigate.video                  ERROR   : vorgarten: Unable to read frames from ffmpeg process.
2023-11-10 09:19:32.128669116  [2023-11-10 09:19:32] frigate.video                  ERROR   : vorgarten: ffmpeg process is not running. exiting capture thread...
2023-11-10 09:19:38.105170547  127.0.0.1 - - [10/Nov/2023:09:19:38 +0100] "GET / HTTP/1.1" 200 10168 "-" "Wget/1.21" "-"
2023-11-10 09:19:42.130963975  [2023-11-10 09:19:42] watchdog.vorgarten             ERROR   : Ffmpeg process crashed unexpectedly for vorgarten.
2023-11-10 09:19:42.131738262  [2023-11-10 09:19:42] watchdog.vorgarten             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-10 09:20:39.107405747  127.0.0.1 - - [10/Nov/2023:09:20:39 +0100] "GET / HTTP/1.1" 200 10168 "-" "Wget/1.21" "-"
2023-11-10 09:20:52.161163130  [2023-11-10 09:20:52] watchdog.vorgarten             INFO    : No frames received from vorgarten in 20 seconds. Exiting ffmpeg...
2023-11-10 09:20:52.161295367  [2023-11-10 09:20:52] watchdog.vorgarten             INFO    : Waiting for ffmpeg to exit gracefully...
2023-11-10 09:20:52.227141746  [2023-11-10 09:20:52] frigate.video                  ERROR   : vorgarten: Unable to read frames from ffmpeg process.
2023-11-10 09:20:52.227149080  [2023-11-10 09:20:52] frigate.video                  ERROR   : vorgarten: ffmpeg process is not running. exiting capture thread...
2023-11-10 09:21:02.199603603  172.19.0.10 - - [10/Nov/2023:09:21:02 +0100] "GET /ws HTTP/1.1" 101 82708 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Iron Safari/537.36" "192.168.177.61"
2023-11-10 09:21:02.228307519  [2023-11-10 09:21:02] watchdog.vorgarten             ERROR   : Ffmpeg process crashed unexpectedly for vorgarten.
2023-11-10 09:21:02.228777983  [2023-11-10 09:21:02] watchdog.vorgarten             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-10 09:21:40.167206129  127.0.0.1 - - [10/Nov/2023:09:21:40 +0100] "GET / HTTP/1.1" 200 10168 "-" "Wget/1.21" "-"
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"eingang":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":351,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":360,"pid":340,"process_fps":5.1,"skipped_fps":0.0},"garten":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":343,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":348,"pid":336,"process_fps":5.1,"skipped_fps":0.0},"terasse":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":347,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":353,"pid":338,"process_fps":5.1,"skipped_fps":0.0},"vorgarten":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":4.2,"capture_pid":357,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":6255,"pid":342,"process_fps":4.2,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"10":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"12":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"19":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"20":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"21":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"22":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"23":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"34":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"74":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"75":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"85":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"14.7","cpu_average":"15","mem":"0.4"},"105":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"3.0","cpu_average":"4","mem":"4.0"},"114":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"141":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"149":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"294":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"301":{"cmdline":"frigate.recording_manager","cpu":"8.0","cpu_average":"7","mem":"1.6"},"310":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)","cpu":"0.4","cpu_average":"0","mem":"0.1"},"311":{"cmdline":"frigate.detector.coral","cpu":"0.2","cpu_average":"0","mem":"1.6"},"313":{"cmdline":"frigate.output       ","cpu":"1.3","cpu_average":"10","mem":"1.6"},"319":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"320":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"321":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x576 -i pipe: -f mpegts -s 880x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"322":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"323":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1920x1080 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"6","mem":"0.9"},"336":{"cmdline":"frigate.process:garten","cpu":"1.3","cpu_average":"1","mem":"1.6"},"338":{"cmdline":"frigate.process:terasse","cpu":"1.3","cpu_average":"1","mem":"1.6"},"340":{"cmdline":"frigate.process:eingang","cpu":"1.2","cpu_average":"1","mem":"1.6"},"342":{"cmdline":"frigate.process:vorgarten","cpu":"1.9","cpu_average":"1","mem":"1.6"},"343":{"cmdline":"frigate.capture:garten","cpu":"1.2","cpu_average":"1","mem":"1.5"},"347":{"cmdline":"frigate.capture:terasse","cpu":"1.1","cpu_average":"1","mem":"1.5"},"348":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garten_sub?video -r 5 -vf fps=5,scale_vaapi=w=704:h=576,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.4","cpu_average":"10","mem":"0.7"},"351":{"cmdline":"frigate.capture:eingang","cpu":"1.2","cpu_average":"1","mem":"1.5"},"353":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/terasse_sub -r 5 -vf fps=5,scale_vaapi=w=704:h=576,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.6","cpu_average":"10","mem":"0.7"},"357":{"cmdline":"frigate.capture:vorgarten","cpu":"1.4","cpu_average":"0","mem":"1.5"},"359":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garten?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garten@%Y%m%d%H%M%S%z.mp4","cpu":"2.6","cpu_average":"2","mem":"0.3"},"360":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang_sub -r 5 -vf fps=5,scale_vaapi=w=704:h=576,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.9","cpu_average":"10","mem":"0.7"},"370":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/terasse -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/terasse@%Y%m%d%H%M%S%z.mp4","cpu":"1.9","cpu_average":"1","mem":"0.3"},"371":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/vorgarten?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/vorgarten@%Y%m%d%H%M%S%z.mp4","cpu":"1.6","cpu_average":"1","mem":"0.3"},"372":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/eingang@%Y%m%d%H%M%S%z.mp4","cpu":"2.0","cpu_average":"1","mem":"0.3"},"373":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://vorgarten.domain.local/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=password -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/e5101a89db8424820b2e285b0d5c9f76","cpu":"3.6","cpu_average":"3","mem":"0.4"},"6255":{"cmdline":"ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/vorgarten_sub?video=copy -r 5 -vf fps=5,scale_vaapi=w=896:h=672,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"15.2","cpu_average":"7","mem":"0.7"},"6279":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":40.65,"pid":311}},"gpu_usages":{"intel-vaapi":{"gpu":"3.14%","mem":"-%"}},"processes":{"go2rtc":{"pid":85},"logger":{"pid":294},"recording":{"pid":301}},"service":{"last_updated":1699604556,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":4090.9,"mount_type":"tmpfs","total":4096.0,"used":5.1},"/media/frigate/clips":{"free":492316.2,"mount_type":"nfs","total":3754443.8,"used":3071339.2},"/media/frigate/recordings":{"free":492316.2,"mount_type":"nfs","total":3754443.8,"used":3071339.2},"/tmp/cache":{"free":3788.2,"mount_type":"tmpfs","total":3814.7,"used":26.5}},"temperatures":{},"uptime":1988,"version":"0.13.0-aa93d4f"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-511
