### ISSUE TITLE
[Config Support]: Frigate 0.13-b5 do not respecting masks

### ISSUE THREAD

**Issue by robertoprubio** [blakeblackshear/frigate#8563]
### Describe the problem you are having

I have previously added a mask and Frigate 0.13-b5 isn't respecting it.

![RZK2ULpVjsIchwN6](https://github.com/blakeblackshear/frigate/assets/31618496/3ecdd19a-3cef-42db-8206-dee28df99afc)

![EIxWMYe5e10IEXvu](https://github.com/blakeblackshear/frigate/assets/31618496/b0344660-d4f8-4111-b070-adb22048e104)

### Version

0.13-b5

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 127.0.0.1
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

ui:
  live_mode: mse

rtmp:
  enabled: false

birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
      
record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 10
      mode: active_objects

motion:
  improve_contrast: true

detect:
  enabled: false
  width: 1920
  height: 1080

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://1af7c9ab224e38bd9deafaa5c1a68d19

objects:
  track:
    - person
    - dog
    - cat 
  filters:
    person:
#      min_area: 25000
      min_score: .8
      threshold: .85 

go2rtc:
  streams:
    terraza_delantera:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.31.232/stream1"
 
cameras:
  terraza_delantera:
    enabled: true
    ui:                 
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terraza_delantera
          roles: 
            - record
            - detect
    objects:
      filters:
        person:
          mask:
            - 1920,0,1920,252,1656,226,1653,0     # Foco
```

### Relevant log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
