### ISSUE TITLE
[Config Support]:  "Service Frigate exited with code 1" Should not be an MQTT issue

### ISSUE THREAD

**Issue by akutruff** [blakeblackshear/frigate#8576]
### Describe the problem you are having

Been trying to get frigate to start and there is no additional debugging information to go on.  I have tried starting frigate with mqtt disabled, and enabled.  In either case I get the same error.  When I tried starting it enabled, I had a verified mosquitto server running with anonymous access.  

I've tried this on a Raspberry PI on ubuntu as well as an amd64 with ubuntu.  I verified that the database files etc. are getting created on my nas volume just fine.

```yaml
version: "3.9"

services:
  frigate:
    build: .
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    shm_size: "64mb" # update for your cameras based on calculation above
    # devices:
    # - /dev/bus/usb:/dev/bus/usb 
    # - /dev/video10
    #  - /dev/apex_0:/dev/apex_0 
    #  - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - config/config.yml:/config/config.yml:ro
      - nas:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

volumes:
  nas:
    driver_opts:
      type: cifs
      o: <redacted>

```

### Version

frigate:stable 

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  reolink: 
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@10.10.x.x:554/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    # rtmp:
    #   enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
```

### Relevant log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | 2023-11-10 21:44:01.480401534  [INFO] Preparing go2rtc config...
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-11-10 21:44:01.510349050  [INFO] Starting Frigate...
frigate  | 2023-11-10 21:44:01.547304297  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-11-10 21:44:02.370084237  [INFO] Starting go2rtc...
frigate  | 2023-11-10 21:44:02.591664537  21:44:02.591 INF go2rtc version 1.2.0 linux/arm64
frigate  | 2023-11-10 21:44:02.593144523  21:44:02.592 INF [api] listen addr=:1984
frigate  | 2023-11-10 21:44:02.594856192  21:44:02.594 INF [rtsp] listen addr=:8554
frigate  | 2023-11-10 21:44:02.596509806  21:44:02.596 INF [srtp] listen addr=:8443
frigate  | 2023-11-10 21:44:02.598537473  21:44:02.598 INF [webrtc] listen addr=:8555
frigate  | 2023-11-10 21:44:06.086421723  [2023-11-10 21:44:06] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
frigate  | 2023-11-10 21:44:06.153152507  [2023-11-10 21:44:06] peewee_migrate                 INFO    : Starting migrations
frigate  | 2023-11-10 21:44:11.171795715  database is locked
frigate  | 2023-11-10 21:44:11.490304737  [INFO] Starting go2rtc healthcheck service...
frigate  | 2023-11-10 21:44:12.740710415  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-11-10 21:44:12.793255757  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2023-11-10 21:44:12.893781242  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2023-11-10 21:44:12.910991693  exit OK
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2023-11-10 21:44:12.934270549  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

The only thing I'm doing different is using a 
```
FROM ghcr.io/blakeblackshear/frigate:stable
COPY config/config.yml /config/config.yml
```
