### ISSUE TITLE
[HW Accel Support]: Fedora 38 (IoT) Raspberry Pi 4

### ISSUE THREAD

**Issue by ctml91** [blakeblackshear/frigate#8578]
### Describe the problem you are having

So far I've been unsuccessful getting GPU support working on a PI 4 running Fedora 38 (IoT)

From what I gathered drivers should be available for GPU but I'm not 100% sure how to verify that?
https://docs.fedoraproject.org/en-US/quick-docs/raspberry-pi/#_what_desktop_environments_are_supported 
https://docs.fedoraproject.org/en-US/iot/reference-platforms/

Here I'm mounting the two devices I see available on the system, but 
```
[root@fedora ~]# cat /etc/redhat-release
Fedora release 38 (Thirty Eight)
[root@fedora ~]# rpm-ostree status
State: idle
Deployments:
● fedora-iot:fedora/stable/aarch64/iot
                  Version: 38.20230920.0 (2023-09-20T16:23:40Z)
               BaseCommit: df5f553b562ed4edad8d4afc607adcf79407ebd8fc27d9c4bd2e9b0d0b5292f5
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: cloud-utils-growpart mesa-va-drivers podman-compose vulkan

  fedora-iot:fedora/stable/aarch64/iot
                  Version: 38.20230720.0 (2023-07-20T14:42:16Z)
               BaseCommit: abd1d5a045a6fcdcf0257f9e5d6a17c82bbbe580281e516c47d95363737c624f
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: cloud-utils-growpart mesa-va-drivers podman-compose vulkan

[root@fedora ~]# ls -lthR /dev/dri/
/dev/dri/:
total 0
drwxr-xr-x. 2 root root         80 Sep 18 00:00 by-path
crw-rw-rw-. 1 root render 226, 128 Sep 18 00:00 renderD128
crw-rw----. 1 root video  226,   0 Sep 18 00:00 card0

/dev/dri/by-path:
total 0
lrwxrwxrwx. 1 root root  8 Sep 18 00:00 platform-fec00000.v3d-card -> ../card0
lrwxrwxrwx. 1 root root 13 Sep 18 00:00 platform-fec00000.v3d-render -> ../renderD128

[root@fedora ~]# podman run --replace -d --name frigate -v frigate-media:/media/frigate:z -v frigate-config:/config:z --device /dev/dri/card0:/dev/dri/card0 --device /dev/dri/renderD128:/dev/dri/renderD128 -e FRIGATE_RTSP_PASSWORD=gigabit -p 5001:5000 -p 8555:8555 -p 1936:1935 ghcr.io/blakeblackshear/frigate:0.13.0-beta3-standard-arm64
```

Test was unsuccessful, tbh I'm not sure if /dev/dri/card0 actually represents the Pi 4 GPU... or perhaps I need to use something other than h264_v4l2m2m because I'm not using raspbian. 

Any help is appreciated, trying to offload recording/ffmpeg rotation to GPU as I'm unable to rotate my camera stream currently due to lack of CPU.

### Version

0.13.0-cd64399

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.100
cameras:
#  backbedroom:
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.2.100:8554/bens-other-cam
#          roles:
#            - audio
#            - detect
#    detect:
#      width: 640
#      height: 360
  doorbell:
    motion:
      mask:
        #- 0,1130,340,1197,792,964,1084,981,1116,802,907,153,329,124,0,470
        # japanese maple tree
        # - 882,938,961,856,1042,932,995,974,956,1011,916,970
        # left garden bed + tree
        # - 350,755,434,966,305,978,476,1077,614,1036,648,1005,743,999,759,956,784,936,812,959,821,996,407,1206,169,1175,153,887
        - 843,925,956,804,1064,938,1009,980,956,1011,893,978
        - 352,701,441,974,495,1063,627,1018,691,987,725,842,846,1007,271,1297,162,1251,153,887
    zones:
      walkway:
        coordinates: 506,1149,0,1129,0,1671,1296,1675,1296,1226,1296,1084,1296,965,1058,964,1010,958,918,971,740,1029
        filters:
          person:
            min_area: 1000
        objects:
          - person
          - dog
      lawn:
        coordinates: 459,944,1051,964,1060,1005,773,993,460,1101,264,1082,234,970
        objects:
          - person
          - dog
        filters:
          person:
            min_area: 500
          dog:
            min_area: 500
    record:
      events:
        required_zones:
          - walkway
          - lawn
    snapshots:
      required_zones:
        - walkway
        - lawn
    ffmpeg:
#  hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://192.168.2.100:8554/front-doorbell
          roles:
            - detect
            - rtmp
      output_args:
        detect: -vf transpose=1 -f rawvideo -pix_fmt yuv420p 
    rtmp:
      enabled: False
    detect:
      width: 1296
      height: 1728
#      width: 480
#      height: 640
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
snapshots:
  enabled: True
record:
  enabled: True
  events:
    pre_capture: 10
    retain:
      default: 10
objects:
  track:
    - person
    - dog
  filters:
    person:
      threshold: 0.7
      min_score: 0.7
    dog:
      threshold: 0.7
      min_score: 0.7
```

### docker-compose file or Docker CLI command

```yaml
podman run --replace -d --name frigate -v frigate-media:/media/frigate:z -v frigate-config:/config:z --device /dev/dri/card0:/dev/dri/card0 --device /dev/dri/renderD128:/dev/dri/renderD128 -e FRIGATE_RTSP_PASSWORD=gigabit -p 5001:5000 -p 8555:8555 -p 1936:1935 ghcr.io/blakeblackshear/frigate:0.13.0-beta3-standard-arm64
```

### Relevant log output

```shell
[root@fedora ~]# podman exec -it frigate /bin/bash
root@abfc1e482e31:/opt/frigate# ls -lth /dev/dri/
total 0
crw-rw----. 1 root irc 226,   0 Nov  8 00:15 card0
crw-rw-rw-. 1 root 105 226, 128 Nov  8 00:15 renderD128

root@abfc1e482e31:/opt/frigate# ffmpeg -c:v h264_v4l2m2m -re -stream_loop -1 -i https://streams.videolan.org/ffmpeg/incoming/720p60.mp4 -f rawvideo -pix_fmt yuv420p pipe: > /dev/null
ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://streams.videolan.org/ffmpeg/incoming/720p60.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.10.100
  Duration: 00:00:16.28, start: 0.000000, bitrate: 2503 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m, progressive), 1280x720 [SAR 1:1 DAR 16:9], 2496 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[h264_v4l2m2m @ 0xaaaad0def7b0] Could not find a valid device
[h264_v4l2m2m @ 0xaaaad0def7b0] can't configure decoder
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_v4l2m2m) -> rawvideo (native))
Error while opening decoder for input stream #0:0 : Invalid argument
```

### FFprobe output from your camera

```shell
ffprobe rtsp://192.168.2.100:8554/front-doorbell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0xaaaac32bb030] method SETUP failed: 461 Unsupported Transport
Input #0, rtsp, from 'rtsp://192.168.2.100:8554/front-doorbell':
  Metadata:
    title           : No Name
  Duration: N/A, start: 0.176500, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, unknown/bt709/unknown, progressive), 1728x1296, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wireless

### Camera make and model

Wyze Doorbell
