### ISSUE TITLE
[Support]: Run command after container has started

### ISSUE THREAD

**Issue by PP-JN-RL** [blakeblackshear/frigate#8586]
### Describe the problem you are having

Hi all,

I'm looking for a way to run a command after the container has started. This is so that I can route all frigate traffic through a wireguard container. Currently I run the following command manually inside the container: apt-get update -y; apt-get install -y iproute2; ip route del default; ip route add default via 172.18.0.2

The problem is that I have to run it manually every time the container restarts. I have tried to add this to my docker compose file: command: apt-get update -y; apt-get install -y iproute2; ip route del default; ip route add default via 172.18.0.2

But this causes the container to crash on startup. Is there a way I can achieve this? Any help is much appreciate.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False

birdseye:
  enabled: False

#ffmpeg:
#  hwaccel_args: preset-vaapi

cameras:
  CCTV01:
    ffmpeg:
      inputs:
        - path: rtsp://10.8.0.5:554/media/video1
          input_args: preset-rtsp-udp
          roles:
            - detect

    detect:
      enabled: True
      width: 1280 #Update for Camera
      height: 720 #Update for Camera
      fps: 18
      stationary:
        interval: 0
        threshold: 10
        max_frames:
          objects:
            car: 360
            bus: 360
            motorcycle: 360
            bicycle: 360
            dog: 360

    objects:
      track:
        - person
        - car
        - bus
        - motorcycle
        - bicycle
        - dog

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

### Relevant log output

```shell
non
```

### FFprobe output from your camera

```shell
non
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision
