### ISSUE TITLE
[Support]: Camera detection very 'jittery' and gets bad in rain

### ISSUE THREAD

**Issue by JRascagneres** [blakeblackshear/frigate#8590]
### Describe the problem you are having

My camera detection works great for the most part, detecting people and cars. However, at night the detection gets very jittery resulting in frigate detecting a car is there and then not there. This results in fairly frequent notifications. The problem gets much much worse when it rains. 

Is there any tips for resolving this in terms of settings to tweak?

The camera in question from my config is 'garage'

https://github.com/blakeblackshear/frigate/assets/3264971/ca492554-14d1-4adc-b692-75e834f35519

### Version

0.13.0-AA93D4F

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: homeassistant.lan
  user: mqtt-user
  password: bladder-doe-fencing

detectors:
  coral_pci:
    type: edgetpu
    device: pci

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  doorbell_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_reolink?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - car
        - bicycle
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      required_zones:
        - plant bed
        - path
        - road and path
      retain:
        default: 30
    record:
      enabled: True
      events:
        required_zones:
          - plant bed
          - path
          - road and path
        retain:
          default: 20
    live:
      stream_name: doorbell_reolink
    motion:
      mask:
        - 640,90,0,97,0,298,224,303,510,294,542,282,640,298,640,222
    zones:
      plant bed:
        coordinates: 262,474,398,446,523,391,604,325,528,306,246,365
        objects:
          - person
      path:
        coordinates: 579,480,626,411,609,382,631,329,607,323,553,369,450,429,256,480
        objects:
          - person
      road and path:
        coordinates: 323,282,472,270,506,282,585,287,508,315,417,340,301,356,140,360,149,267,233,280
        objects:
          - person
          - car
          - bicycle
    ui:
      order: 0
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
  front_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_reolink?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - car
        - dog
        - bicycle
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 20
    motion:
      mask:
        - 640,0,0,0,0,165,0,312,37,373,394,163,387,63,640,154
    zones:
      front_path:
        coordinates: 458,480,190,273,42,362,0,292,0,480
      front_pavement:
        coordinates: 640,301,640,197,425,113,346,164
      front_road:
        coordinates: 640,205,640,71,546,33,432,117
    live:
      stream_name: front_reolink
    ui:
      order: 1
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
  back_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_reolink?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 20
    zones:
      patio:
        coordinates: 323,248,271,203,16,259,79,480,434,480,290,343,185,379,127,291
      grass:
        coordinates: 323,248,271,203,527,147,640,187,640,480,434,480,290,343,185,379,127,291
    ui:
      order: 2
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
  garage_reolink:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_reolink?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track: 
        - person
        - car
        - bicycle
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: True
      events:
        retain:
          default: 20
    motion:
      mask:
        - 0,58,375,58,445,204,640,204,640,67,640,0,0,0
    zones:
      driveway:
        coordinates: 96,480,256,117,400,117,544,480
      driveway entrance:
        coordinates: 256,117,400,117,400,75,256,75
    ui:
      order: 3
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1920

birdseye:
  enabled: True
  mode: continuous
  quality: 1
  restream: True

rtmp:
  enabled: false

live:
  quality: 1
  height: 2560

go2rtc:
  streams:
    doorbell_reolink:
      # - rtsp://admin:redact@192.168.4.69:554/h264Preview_01_main
      - "ffmpeg:https://192.168.4.69/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redact#video=copy#audio=copy#audio=opus"
      - rtsp://admin:Fx8ayCvN6*nyW9Gr@192.168.4.69:554/h264Preview_01_sub
    doorbell_reolink_sub:
      - "ffmpeg:https://192.168.4.69/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redact"
    front_reolink:
      - "ffmpeg:https://192.168.4.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redact#video=copy#audio=copy#audio=opus"
      # - rtsp://admin:redact@192.168.4.30:554/h264Preview_01_main
      # - ffmpeg:front_reolink#video=copy#audio=copy#audio=opus
    front_reolink_sub:
      - "ffmpeg:https://192.168.4.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redact"
      # - rtsp://admin:redact@192.168.4.30:554/h264Preview_01_main
      # - ffmpeg:front_reolink_sub
    back_reolink:
      - "ffmpeg:https://192.168.4.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redact#video=copy#audio=copy#audio=opus"
      # - rtsp://admin:redact6@192.168.4.31:554/h264Preview_01_main
      # - ffmpeg:back_reolink#video=copy#audio=copy#audio=opus
    back_reolink_sub:
      - "ffmpeg:https://192.168.4.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redact"
      # - rtsp://admin:redact@192.168.4.31:554/h264Preview_01_main
      # - ffmpeg:back_reolink_sub
    garage_reolink:
      # - "ffmpeg:https://192.168.4.44/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redact#video=copy#audio=copy#audio=opus"
      - rtsp://admin:redact@192.168.4.44:554/h264Preview_01_main
      - ffmpeg:garage_reolink#video=copy#audio=copy#audio=opus
    garage_reolink_sub:
      # - "ffmpeg:https://192.168.4.44/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redact"
      - rtsp://admin:redact@192.168.4.44:554/h264Preview_01_sub
      - ffmpeg:garage_reolink_sub
  webrtc:
    candidates:
      - homeserver.lan:8555
      - homeassistant.lan:8555

record:
  retain:
    mode: active_objects
  events:
    post_capture: 15
    retain:
      mode: active_objects
      objects:
        person: 5

snapshots:
  retain:
    objects:
      person: 15

# objects:
#   filters:
#     person:
#       min_score: 0.65
#       threshold: 0.75

detect:
  # Number of frames before someone has disappeared --> measured in frames. So frames * framerate
  max_disappeared: 300
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"back_reolink":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":790,"detection_enabled":1,"detection_fps":4.3,"ffmpeg_pid":802,"pid":779,"process_fps":10.1,"skipped_fps":0.0},"doorbell_reolink":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":783,"detection_enabled":1,"detection_fps":6.2,"ffmpeg_pid":787,"pid":775,"process_fps":10.1,"skipped_fps":0.0},"front_reolink":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":786,"detection_enabled":1,"detection_fps":5.9,"ffmpeg_pid":791,"pid":777,"process_fps":10.0,"skipped_fps":0.0},"garage_reolink":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":799,"detection_enabled":1,"detection_fps":11.3,"ffmpeg_pid":807,"pid":781,"process_fps":9.8,"skipped_fps":0.2}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"7.7","cpu_average":"8","mem":"0.1"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"5.9","cpu_average":"11","mem":"1.0"},"110":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"155":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"172":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"196":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"240":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"269":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"293":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"329":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"371":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"421":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"460":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"505":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"543":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"575":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"609":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"728":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"730":{"cmdline":"frigate.recording_manager","cpu":"3.1","cpu_average":"2","mem":"0.5"},"739":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)","cpu":"0.7","cpu_average":"0","mem":"0.0"},"740":{"cmdline":"frigate.detector.coral_pci","cpu":"7.5","cpu_average":"8","mem":"0.4"},"742":{"cmdline":"frigate.output       ","cpu":"62.6","cpu_average":"58","mem":"0.4"},"746":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 3413x2560 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"748":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 3413x2560 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"760":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 3413x2560 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"761":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 3413x2560 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"762":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 1 -bf 0 pipe:","cpu":"10.7","cpu_average":"9","mem":"0.2"},"775":{"cmdline":"frigate.process:doorbell_reolink","cpu":"28.8","cpu_average":"32","mem":"0.4"},"777":{"cmdline":"frigate.process:front_reolink","cpu":"21.5","cpu_average":"21","mem":"0.4"},"779":{"cmdline":"frigate.process:back_reolink","cpu":"20.8","cpu_average":"23","mem":"0.4"},"781":{"cmdline":"frigate.process:garage_reolink","cpu":"47.6","cpu_average":"47","mem":"0.4"},"783":{"cmdline":"frigate.capture:doorbell_reolink","cpu":"1.6","cpu_average":"1","mem":"0.4"},"786":{"cmdline":"frigate.capture:front_reolink","cpu":"1.7","cpu_average":"1","mem":"0.4"},"787":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_reolink_sub?video=copy -r 10 -vf fps=10,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.7","cpu_average":"3","mem":"0.7"},"790":{"cmdline":"frigate.capture:back_reolink","cpu":"1.9","cpu_average":"1","mem":"0.4"},"791":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_reolink_sub?video=copy -r 10 -vf fps=10,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.0","cpu_average":"4","mem":"0.7"},"796":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.4.69/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Fx8ayCvN6*nyW9Gr -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/e32cdba8fad65853adde6feb9d818f79","cpu":"1.1","cpu_average":"1","mem":"0.1"},"797":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell_reolink?video=copy&audio=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/doorbell_reolink@%Y%m%d%H%M%S%z.mp4","cpu":"1.3","cpu_average":"1","mem":"0.1"},"799":{"cmdline":"frigate.capture:garage_reolink","cpu":"2.0","cpu_average":"1","mem":"0.4"},"802":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_reolink_sub?video=copy -r 10 -vf fps=10,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.9","cpu_average":"3","mem":"0.7"},"803":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.4.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=-ca2Kv-@jMjki4pE -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/081a3d4f457fd4f6ecf8f21bcd5e3b94","cpu":"1.6","cpu_average":"1","mem":"0.1"},"806":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_reolink?video=copy&audio=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front_reolink@%Y%m%d%H%M%S%z.mp4","cpu":"1.2","cpu_average":"1","mem":"0.1"},"807":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_reolink_sub?video=copy -r 10 -vf fps=10,scale_cuda=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.9","cpu_average":"1","mem":"0.7"},"810":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.4.69/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Fx8ayCvN6*nyW9Gr -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -ar:a:1 48000 -ac:a:1 2 -application:a:1 voip -compression_level:a:1 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/18b3e15ede5ac37958f15855ff50b95f","cpu":"3.3","cpu_average":"3","mem":"0.1"},"813":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.4.31/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=ppRUvw88opg7kzmnUXw6 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/d0d7011bfc41232cbf8ebcc0ca1cbf30","cpu":"1.6","cpu_average":"1","mem":"0.1"},"814":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_reolink?video=copy&audio=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/back_reolink@%Y%m%d%H%M%S%z.mp4","cpu":"1.2","cpu_average":"1","mem":"0.1"},"816":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.4.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=-ca2Kv-@jMjki4pE -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -ar:a:1 48000 -ac:a:1 2 -application:a:1 voip -compression_level:a:1 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1e8f3cc0c6275d2d4501a05b19808450","cpu":"4.1","cpu_average":"4","mem":"0.1"},"821":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_reolink?video=copy&audio=copy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage_reolink@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.1"},"822":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.4.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=ppRUvw88opg7kzmnUXw6 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -ar:a:1 48000 -ac:a:1 2 -application:a:1 voip -compression_level:a:1 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1d7a6e09684368f8d2f81519191767f5","cpu":"4.5","cpu_average":"4","mem":"0.1"},"26068":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":27.7,"detectors":{"coral_pci":{"detection_start":1699812123.507983,"inference_speed":7.59,"pid":740}},"gpu_usages":{"NVIDIA GeForce GT 710":{"dec":"-1.0%","enc":"-1.0%","gpu":"0.0%","mem":"31.59%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":728},"recording":{"pid":730}},"service":{"last_updated":1699812123,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":1016.6,"mount_type":"tmpfs","total":1024.0,"used":7.4},"/media/frigate/clips":{"free":346199.7,"mount_type":"ext4","total":937296.0,"used":543412.5},"/media/frigate/recordings":{"free":346199.7,"mount_type":"ext4","total":937296.0,"used":543412.5},"/tmp/cache":{"free":346199.7,"mount_type":"overlay","total":937296.0,"used":543412.5}},"temperatures":{"apex_0":40.3},"uptime":2796,"version":"0.13.0-aa93d4f"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink RLC-510WA
