### ISSUE TITLE
Detection : set up rotation of stream

### ISSUE THREAD

**Issue by IPv777** [blakeblackshear/frigate#8591]
Hey :)

**Describe what you are trying to accomplish and why in non technical terms**
I would like to detect people on a raw stream, 90 ° rotated.

I don't have a powerful hardware to transcode my stream with ffmpeg (to rotate it), so I would like to setup the detection and say to frigate "detect 90° clockwise"

![image](https://github.com/blakeblackshear/frigate/assets/19636346/3b77a46a-e63a-4fb1-b1f2-f89b640d6519)

Thanks !

**Comment by hawkeye217** [comment]
The only way this can be accomplished with Frigate is to use ffmpeg/go2rtc with rotation parameters.

**Comment by 7floor** [comment]
What is your source? Would you instead check your camera settings, many (most?) cameras have in-built ability to flip/rotate image. It is at minimum pain in the neck to watch such a footage =)

**Comment by IPv777** [comment]
Lenovo NVR (dvr163), my source is [bubble:// in go2rtc](https://github.com/AlexxIT/go2rtc#source-bubble).

I will check the cameras settings, thanks !

**Comment by IPv777** [comment]
Finally found ! So I'm transcoding, rotate 3 cameras with go2rtc !

```

mqtt:
  enabled: false
detectors:
  coral:
    type: edgetpu
    device: usb

#detectors:
#    cpu1:
#        type: cpu

logger:
  logs:
    frigate.record.maintainer: debug

go2rtc:
  #api:
  #  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  #  username: "admin"  # default "", Basic auth for WebUI
  #  password: "pass"   # default "", Basic auth for WebUI
  #  base_path: "/rtc"  # default "", API prefix for serve on suburl (/api => /rtc/api)
  #  static_dir: "www"  # default "", folder for static files (custom web interface)
  #  origin: "*"        # default "", allow CORS requests (only * supported)
  log:
    level: debug
    api: debug
    exec: debug
  #ffmpeg:
    # -headers \"Authorization:\ Basic YWRtaW46\"
    #myinput: '-fflags nobuffer -flags low_delay -f:v h264 -timeout 5000000 -i {input}'
  streams:
    camera_est_hd_sansRotation:
    - bubble://admin:@192.168.1.102:80/bubble/live?ch=0&stream=0
    - ffmpeg:camera_est_hd_sansRotation
    camera_est_sd_sansRotation:
    - bubble://admin:@192.168.1.102:80/bubble/live?ch=0&stream=1
    - ffmpeg:camera_est_sd_sansRotation
    camera_est_hd:
    - ffmpeg:camera_est_hd_sansRotation#video=h264#rotate=90#hardware=vaapi
    camera_est_sd:
    - ffmpeg:camera_est_sd_sansRotation#video=h264#rotate=90#hardware=vaapi
    camera_sud_hd_sansRotation:
    - bubble://admin:@192.168.1.103:80/bubble/live?ch=0&stream=0
    - ffmpeg:camera_sud_hd_sansRotation
    camera_sud_sd_sansRotation:
    - bubble://admin:@192.168.1.103:80/bubble/live?ch=0&stream=1
    - ffmpeg:camera_sud_sd_sansRotation
    camera_sud_hd:
    - ffmpeg:camera_sud_hd_sansRotation#video=h264#rotate=90#hardware=vaapi
    camera_sud_sd:
    - ffmpeg:camera_sud_sd_sansRotation#video=h264#rotate=90#hardware=vaapi
    camera_ouest1_hd_sansRotation:
    - bubble://admin:@192.168.1.104:80/bubble/live?ch=0&stream=0
    - ffmpeg:camera_ouest1_hd_sansRotation
    camera_ouest1_sd_sansRotation:
    - bubble://admin:@192.168.1.104:80/bubble/live?ch=0&stream=1
    - ffmpeg:camera_ouest1_sd_sansRotation
    camera_ouest1_hd:
    - ffmpeg:camera_ouest1_hd_sansRotation#video=h264#rotate=90#hardware=vaapi
    camera_ouest1_sd:
    - ffmpeg:camera_ouest1_sd_sansRotation#video=h264#rotate=90#hardware=vaapi
    camera_ouest2_hd:
    - bubble://admin:@192.168.1.105:80/bubble/live?ch=0&stream=0
    camera_ouest2_sd:
    - bubble://admin:@192.168.1.105:80/bubble/live?ch=0&stream=1

    #camera_est:
    #  - "ffmpeg:http://192.168.1.102:80/livestream/11?action=play&media=video_audio_data#header=Authorization: Basic YWRtaW46"
      #- "ffmpeg:camera_est#video=h264#rotate=90"
    #  - "ffmpeg:http://192.168.18.50:80/cgi-bin/sp.cgi?chn=0&u=admin&p=password#video=h264#rotate=90"
    #  - bubble://admin:password@192.168.1.101:80/bubble/live?ch=0&stream=1
    #camera_est:
    #  - ffmpeg:camera_est_not_rotated#video=h264#rotate=90
  #  camera_ouest1
      # - "ffmpeg:http://192.168.18.45:80/cgi-bin/sp.cgi?chn=2&u=admin&p=password#video=h264#"
   #   - bubble://admin:password@192.168.1.101:80/bubble/live?ch=2&stream=1
  #  camera_ouest2:
      #- "ffmpeg:http://172.20.14.33:80/livestream/12?action=play&media=video_audio_data#video=h264#rotate=90#raw=myinput"
      # - exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -f:v h264 -headers \"Authorization: Basic YWRtaW46\" -i http://172.20.14.32:80/livestream/12?action=play&media=video -g:v 30 -preset:v superfast -tune:v zerolatency -profile:v high -level:v 4.1 -an -vf transpose=1 -user_agent ffmpeg/go2rtc -g 50 -c:v libx264 -rtsp_transport tcp -f rtsp {output}
 #     - bubble://admin:password@192.168.1.101:80/bubble/live?ch=1&stream=1
    #camera_ouest2:
    #  - ffmpeg:camera_ouest2_not_rotated#video=h264#rotate=90
 #   camera_sud:
    #  - "ffmpeg:http://192.168.1.101:80/cgi-bin/sp.cgi?chn=3&u=admin&p=password#video=h264#rotate=90"
 #     - bubble://admin:password@192.168.1.101:80/bubble/live?ch=3&stream=1
    #camera_sud:
    #  - ffmpeg:camera_sud_not_rotated#video=h264#rotate=90


# fonctionne a peu pres : go2rtc pas en #hardware mais ffmpeg rtsp oui
# #width=320#height=640

birdseye:
  enabled: true
  mode: continuous

ui:
  timezone: Europe/Paris
  time_format: 24hour



cameras:
  camera_est: # <------ Name the camera
    enabled: true
    ffmpeg:
      #output_args:
      #  record: -fflags +genpts+discardcorrupt+igndts
      #  detect: -fflags +genpts+discardcorrupt+igndts
      hwaccel_args: preset-vaapi
      inputs:
         #- path: "http://192.168.1.102:80/livestream/11?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_est_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - record
         #- path: "http://192.168.1.102:80/livestream/12?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_est_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - detect
      #input_args:
      #  - -headers
      #  - "Authorization: Basic YWRtaW46"
      #  - "-f:v"
      #  - "h264"
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 360 # <---- update for your camera's resolution
      #width: 1280 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution
      #height: 720 # <---- update for your camera's resolution
    motion:
      mask:
      - 360,248,331,249,328,52,360,42
      - 64,293,125,0,0,0,0,640,24,640
      - 360,0,360,171,93,97,114,0
    zones:
      pelouse_est:
        coordinates: 360,250,326,252,313,186,100,113,89,174,80,593,360,640
      facade_est:
        coordinates: 0,564,0,0,120,0,102,170,77,599
    record:
      enabled: true
      events:
        retain:
          default: 10
        required_zones:
        - pelouse_est
        - facade_est

  camera_sud: # <------ Name the camera
    enabled: true
    ffmpeg:
      #output_args:
      #  record: -fflags +genpts+discardcorrupt+igndts
      #  detect: -fflags +genpts+discardcorrupt+igndts
      hwaccel_args: preset-vaapi
      inputs:
         #- path: "http://192.168.1.103:80/livestream/12?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_sud_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - detect
         #- path: "http://192.168.1.103:80/livestream/11?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_sud_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - record
      #input_args:
      #  - -headers
      #  - "Authorization: Basic YWRtaW46"
      #  - "-f:v"
      #  - "h264"
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 360 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution
    motion:
      mask:
      - 258,137,324,140,339,265,253,278,240,399,310,409,268,640,360,640,360,0,0,0,0,143,78,139,227,168
    zones:
      balcon:
        coordinates: 332,275,327,123,268,115,216,260
      pelouse_sud:
        coordinates: 0,326,0,143,98,138,139,153,152,133,254,171,216,256,218,314,42,346
      terrasse:
        coordinates: 0,349,47,341,217,321,235,436,304,449,360,376,360,640,0,522
    record:
      enabled: true
      events:
        retain:
          default: 10
        required_zones:
        - terrasse
        - pelouse_sud
        - balcon

  camera_ouest1: # <------ Name the camera
    enabled: true
    ffmpeg:
      #output_args:
      #  record: -fflags +genpts+discardcorrupt+igndts
      #  detect: -fflags +genpts+discardcorrupt+igndts
      hwaccel_args: preset-vaapi
      inputs:
         #- path: "http://192.168.1.103:80/livestream/12?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_ouest1_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - detect
         #- path: "http://192.168.1.103:80/livestream/11?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_ouest1_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - record
      #input_args:
      #  - -headers
      #  - "Authorization: Basic YWRtaW46"
      #  - "-f:v"
      #  - "h264"
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 360 # <---- update for your camera's resolution
      height: 640 # <---- update for your camera's resolution
    record:
      enabled: true
      events:
        retain:
          default: 10
        #required_zones:
        #- terrasse
        #- pelouse_sud
        #- balcon

  camera_ouest2: # <------ Name the camera
    enabled: true
    ffmpeg:
      #output_args:
      #  record: -fflags +genpts+discardcorrupt+igndts
      #  detect: -fflags +genpts+discardcorrupt+igndts
      hwaccel_args: preset-vaapi
      inputs:
         #- path: "http://192.168.1.103:80/livestream/12?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_ouest2_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - detect
         #- path: "http://192.168.1.103:80/livestream/11?action=play&media=video_audio_data"
      - path: rtsp://127.0.0.1:8554/camera_ouest2_sd    # <----- The stream you want to use for detection
        input_args: preset-rtsp-restream
        roles:
        - record
      #input_args:
      #  - -headers
      #  - "Authorization: Basic YWRtaW46"
      #  - "-f:v"
      #  - "h264"
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: true
      events:
        retain:
          default: 10
        #required_zones:
        #- terrasse
        #- pelouse_sud
        #- balcon

```
