### ISSUE TITLE
Wont detect cats

### ISSUE THREAD

**Issue by NoOneReally2021** [blakeblackshear/frigate#8593]
### Describe the problem you are having

Hi All, i am new Frigate user, i have one issue which i cant figure out how to resolve.
Essentially the issue is detecting cats, either during the day or at night.
I am able to get detection working for just about everything else but not cats.
I am using Openvino detector on 11th Gen cpu.

Any help would be appreciated.

### Version

0.12

### Frigate config file

```yaml
Backyard:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Backyard
      
    detect:
      width: 640
      height: 480
      fps: 10

    objects:
      track:
        - person
        - cat

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30

    motion:
      improve_contrast: True
      threshold: 15
      contour_area: 15
      delta_alpha: 0.3
      frame_alpha: 0.1
      mask:      
        - 640,0,640,206,450,146,352,112,270,107,204,75,151,56,0,76,0,0,182,0
        - 640,360,640,226,470,163,323,119,204,172
        - 433,254,490,0,508,0,478,348,401,331
        - 0,480,148,480,0,196

    record:
      enabled: True
#      retain:
#        days: 30
#        mode: motion
#      events:
#        retain:
#          default: 30
#          mode: active_objects
```

### docker-compose file or Docker CLI command

```yaml
None
```

### Relevant log output

```shell
None
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other
