### ISSUE TITLE
[Config Support]: It's possibly to standardize cameras resolution?

### ISSUE THREAD

**Issue by merencia** [blakeblackshear/frigate#8600]
### Describe the problem you are having

First, thanks for frigate it's an amazing project.

Before knowing frigate I bought some popular cameras here in Brazil, but after starting using the cameras streams I realize they are really awful.

I've used many tricks to improve it and using sub-streams for detection it's working OK.

However the final result is not so charming... Basically two cameras of same model have different resolution on low quality stream, which I'm using for detection.

![image](https://github.com/blakeblackshear/frigate/assets/1686635/83d2ce03-d5d8-45ac-b8c0-fb4a6ac34865)
![image](https://github.com/blakeblackshear/frigate/assets/1686635/2675238d-f76e-4f36-9ca1-875bebe5593c)

So, I've set my configs to match that resolution and everything is working good, but the Birdseye final result it's not so good because the screens are displayed with large black borders to make them all use the same space. So, I'd like to know if there is a way to standardize the resolution on frigate or go2rtc to make all of them look similar, for example, may I set all the detect to 640 to 480?

This the Birdseye result:
![image](https://github.com/blakeblackshear/frigate/assets/1686635/ac2fe717-a94f-4a95-9e8d-8819e0d07af8)

**Notice for Brazilians:**  Avoid using Intelbras Mibo cameras.

### Version

0.12.1

### Frigate config file

```yaml
sala:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/sala
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sala_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 704
      height: 480

  cozinha:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/cozinha
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cozinha_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
```

### Relevant log output

```shell
none
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)
