### ISSUE TITLE
[Support]: recording playback with Chrome stopped working?

### ISSUE THREAD

**Issue by sammyke007** [blakeblackshear/frigate#8608]
### Describe the problem you are having

Hi
Since today I've noticed that I can't playback my recording from 1 camera (Reolink PoE doorbell).
Other camera's work, other browser (Firefox) also works.

Has anything been changed that you know of in Chrome?

It are the events / recordings playback from **deurbel** that stopped working.

![image](https://github.com/blakeblackshear/frigate/assets/33524412/9ade73d5-fe24-4ed9-9610-9b2fd1395fe2)

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.7
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ***REDACTED***
  password: ***REDACTED***
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

birdseye:
  enabled: True
  mode: continuous

go2rtc:
  streams:
    voordeur:
      - rtsp://***REDACTED***:***REDACTED***@192.168.1.24:554/videoMain
    tuin:
      - rtsp://***REDACTED***@192.168.1.25:554/user=***REDACTED***_password=***REDACTED***_channel=1_stream=0.sdp?real_stream
    tuin_sub:
      - rtsp://***REDACTED***@192.168.1.25:554/user=***REDACTED***_password=***REDACTED***_channel=1_stream=1.sdp?real_stream
    living:
      - rtsp://***REDACTED***@192.168.1.23:554/videoMain
    pakjes:
      - rtsp:/***REDACTED***@192.168.1.26:554/videoMain
    deurbel:
      # - rtsp://***:***@192.168.1.22:554/h264Preview_01_main
      - rtsp://***:***@192.168.1.22:554/Preview_01_main
      # - http://192.168.1.22/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=***&password=***
      - ffmpeg:deurbel#audio=opus
    deurbel_sub:
      # - rtsp://***:***@192.168.1.22:554/h264Preview_01_sub
      - rtsp://***:***@192.168.1.22:554/Preview_01_sub
      # - http://192.168.1.22/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=***&password=***
      - ffmpeg:deurbel_sub#audio=opus
    oprit:
      - rtsp://***:***@192.168.1.27:554/user=***_password=***_channel=1_stream=0.sdp?real_stream
      - ffmpeg:oprit#audio=aac
    oprit_sub:
      - rtsp://***:***@192.168.1.27:554/user=***_password=***_channel=1_stream=1.sdp?real_stream
      - ffmpeg:oprit_sub#audio=aac
    garage:
      - rtsp://***:***@192.168.1.28:554/videoMain

  webrtc:
    listen: ":8555" # address of your local server and port (TCP/UDP)
    candidates:
      - 173.245.48.0/20:8555
      - 103.21.244.0/22:8555
      - 103.22.200.0/22:8555
      - 103.31.4.0/22:8555
      - 141.101.64.0/18:8555
      - 108.162.192.0/18:8555
      - 190.93.240.0/20:8555
      - 188.114.96.0/20:8555
      - 197.234.240.0/22:8555
      - 198.41.128.0/17:8555
      - 162.158.0.0/15:8555
      - 104.16.0.0/13:8555
      - 104.24.0.0/14:8555
      - 172.64.0.0/13:8555
      - 131.0.72.0/22:8555
  
  log:
    level: info  # default level
    #api: trace
    #exec: debug
    ngrok: info
    #rtsp: warn
    #streams: error
    webrtc: info

cameras:
  deurbel:
    ffmpeg:
      #output_args:
      #  record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/deurbel_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/deurbel?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
    ui:
      order: 0
    zones:
      deurbel_prive:
        coordinates: 640,480,640,310,521,295,239,337,0,325,0,480
        objects:
          - person
          - dog
          - cat
          - bird
          - bicycle
      deurbel_straat:
        coordinates: 595,264,497,287,231,311,173,309,213,257,252,259,276,270,301,279,364,283,462,275,541,265
        objects:
          - car
      deurbel_driveway:
        coordinates: 142,311,0,288,0,372,94,375,212,371,258,342,264,312
        objects:
          - car
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - car
        - bicycle
      filters:
        car:
          mask:
            - 640,0,0,0,0,480,189,480,199,270,248,252,276,283,325,286,407,280,640,269
    record:
      enabled: True
      events:
        required_zones:
          - deurbel_prive
          - deurbel_driveway
        retain: 
          default: 10
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - deurbel_prive
        - deurbel_driveway
      retain:
        default: 10

  voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/voordeur
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720 
    zones:
      voordeur_all:
        coordinates: 1280,0,0,0,0,720,1280,720
        objects:
          - person
          - dog
          - cat
          - bird
          - bicycle
      voordeur_driveway:
        coordinates: 998,131,1201,328,1092,488,885,168
        objects:
          - car
    record:
      enabled: True
      events:
        required_zones:
          - voordeur_all
          - voordeur_driveway
        retain: 
          default: 10
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - voordeur_all
        - voordeur_driveway
      retain:
        default: 10
    ui:
      order: 1
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - car 
        - bicycle
      filters:
        car:
          mask:
            - 0,720,0,88,139,122,255,526,366,720
            - 1280,0,1280,228,964,135,871,0
    motion:
      mask:
        - 0,0,0,259,304,142,597,130,985,118,1193,0

  oprit:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/oprit
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/oprit_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 704
      height: 576 
    record:
      enabled: True
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      bounding_box: True
      #required_zones:
      #  - aaa
      retain:
        default: 10
    ui:
      order: 2
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle

  living:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living
          input_args: preset-rtsp-restream
    detect:
      enabled: True
      width: 1280
      height: 720
    record:
      enabled: True
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 10
    ui:
      order: 3
    objects:
      track:
        #- person
        - dog

  tuin:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tuin
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tuin_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 704
      height: 576 
      stationary:
        max_frames:
          objects:
            dog: 1000
    record:
      enabled: True
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      bounding_box: True
      #required_zones:
      #  - aaa
      retain:
        default: 10
    ui:
      order: 4
    objects:
      track:
        - person
        - dog
        - bird
        - cat
    motion:
      mask:
        - 0,576,133,576,114,265,27,62,0,0
    zones:
      zijgevel:
        coordinates: 94,235,156,229,161,10,82,38,84,89,49,119

  pakjes:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pakjes
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720 
    record:
      enabled: True
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      bounding_box: True
      #required_zones:
      #  - aaa
      retain:
        default: 10
    motion:
      mask:
        - 550,233,784,399,1090,271,1100,155,1280,82,1080,0,150,0,0,35,0,378
    ui:
      order: 5
    objects:
      track:
        - person
        - dog
        - cat
        - bird

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720 
    record:
      enabled: True
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      bounding_box: True
      #required_zones:
      #  - aaa
      retain:
        default: 10
    ui:
      order: 6
    objects:
      track:
        - person
        - dog
```

### Relevant log output

```shell
/
```

### FFprobe output from your camera

```shell
/
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"2.0","mem":"0.9"},"106":{"cpu":"0.0","mem":"0.0"},"117":{"cpu":"0.0","mem":"0.0"},"123":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.1"},"128":{"cpu":"0.0","mem":"0.1"},"129":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"1744":{"cpu":"0.0","mem":"0.0"},"1777":{"cpu":"0.0","mem":"0.0"},"1781":{"cpu":"0.3","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"347":{"cpu":"0.0","mem":"0.2"},"353":{"cpu":"0.3","mem":"0.0"},"354":{"cpu":"0.0","mem":"0.3"},"356":{"cpu":"1.0","mem":"0.3"},"362":{"cpu":"0.0","mem":"0.1"},"363":{"cpu":"0.3","mem":"0.3"},"364":{"cpu":"0.0","mem":"0.1"},"365":{"cpu":"0.3","mem":"0.3"},"366":{"cpu":"0.0","mem":"0.3"},"367":{"cpu":"0.0","mem":"0.1"},"368":{"cpu":"0.3","mem":"0.3"},"369":{"cpu":"0.0","mem":"0.1"},"370":{"cpu":"0.3","mem":"0.3"},"371":{"cpu":"0.3","mem":"0.3"},"372":{"cpu":"0.0","mem":"0.1"},"373":{"cpu":"0.3","mem":"0.3"},"374":{"cpu":"0.3","mem":"0.3"},"375":{"cpu":"0.0","mem":"0.1"},"376":{"cpu":"0.7","mem":"0.3"},"379":{"cpu":"0.3","mem":"0.3"},"380":{"cpu":"0.0","mem":"0.1"},"381":{"cpu":"1.0","mem":"0.1"},"382":{"cpu":"1.0","mem":"0.3"},"386":{"cpu":"0.3","mem":"0.3"},"390":{"cpu":"1.0","mem":"0.3"},"391":{"cpu":"0.0","mem":"0.1"},"393":{"cpu":"5.7","mem":"0.1"},"394":{"cpu":"7.0","mem":"0.1"},"395":{"cpu":"2.0","mem":"0.1"},"398":{"cpu":"1.0","mem":"0.3"},"403":{"cpu":"0.3","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"411":{"cpu":"0.3","mem":"0.1"},"413":{"cpu":"1.0","mem":"0.1"},"414":{"cpu":"1.0","mem":"0.1"},"415":{"cpu":"6.7","mem":"0.1"},"42":{"cpu":"0.0","mem":"0.0"},"423":{"cpu":"6.0","mem":"0.1"},"429":{"cpu":"0.0","mem":"0.1"},"430":{"cpu":"1.0","mem":"0.1"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"7.3","mem":"0.1"},"MiB":{"cpu":"23384.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"0","mem":"users,"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.07,"pid":354}},"deurbel":{"camera_fps":5.0,"capture_pid":374,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":381,"pid":363,"process_fps":5.0,"skipped_fps":0.0},"garage":{"camera_fps":5.1,"capture_pid":398,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":415,"pid":373,"process_fps":5.1,"skipped_fps":0.0},"living":{"camera_fps":5.1,"capture_pid":382,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":394,"pid":368,"process_fps":5.1,"skipped_fps":0.0},"oprit":{"camera_fps":5.1,"capture_pid":379,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":395,"pid":366,"process_fps":5.1,"skipped_fps":0.0},"pakjes":{"camera_fps":5.0,"capture_pid":390,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":423,"pid":371,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1699957942,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":1063.1,"mount_type":"tmpfs","total":1073.7,"used":10.6},"/media/frigate/clips":{"free":900019.2,"mount_type":"ext4","total":1006979.7,"used":55733.4},"/media/frigate/recordings":{"free":900019.2,"mount_type":"ext4","total":1006979.7,"used":55733.4},"/tmp/cache":{"free":974.7,"mount_type":"tmpfs","total":1000.0,"used":25.3}},"temperatures":{},"uptime":724,"version":"0.12.1-367d724"},"tuin":{"camera_fps":5.1,"capture_pid":386,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":414,"pid":370,"process_fps":5.1,"skipped_fps":0.0},"voordeur":{"camera_fps":5.1,"capture_pid":376,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":393,"pid":365,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink PoE doorbell
