### ISSUE TITLE
[Support]: connect() failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by Maximus48p** [blakeblackshear/frigate#8616]
### Describe the problem you are having

Error message in Docker log:

`2023/11/14 17:26:09 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.112.4, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "frigate:5000"`

172.29.112.4 = address of HA docker container!

### Version

v13-beta5 combined with HA/HACS v5.0.0-beta.3

### Frigate config file

```yaml
not relevant (i think), no issues with config.

Setup Frigate an HA in Docker Container

docker-compose file
services:
  frigate:
    container_name: frigate
    hostname: frigate
    depends_on:
      - deepstack
      - double-take
    networks:
      default:
    privileged: true # this may not be necessary for all setups
    restart: always #unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta5
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /dev/bus/usb:/dev/bus/usb # EdgeTPU
      - /etc/localtime:/etc/localtime:ro
      - /share/docker-volumes/frigate/config:/config
      - /share/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1935:1935"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555" # WebRTC
```

### Relevant log output

Logging from Home Assistant Docker container (172.29.112.4 = address of HA docker container!)
```
e.api] Error fetching information from http://frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://frigate:5000/api/stats')
2023-11-14 16:54:57.401 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://frigate:5000/api/stats')
2023-11-14 16:55:02.403 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://frigate:5000/api/stats')
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

With google i came up with this site:
https://serverfault.com/questions/317393/connect-failed-111-connection-refused-while-connecting-to-upstream

Error message says:
`upstream: "http://127.0.0.1:5001stats"`

shouldn't that be ...5001**/**stats ?
