### ISSUE TITLE
[Support]: frigate not resuming detection stream even if its available and working

### ISSUE THREAD

**Issue by ristoavila** [blakeblackshear/frigate#8624]
### Describe the problem you are having

I have a problem where the sub stream just stops and frigate doesn't restart the ffmpeg process for the sub_stream.
When accessing the substream it works perfectly fine. How ever it is not able to recover from the failure it received. 
I also dont see anything wrong in go2rtc logs. To me it seems like watchdog waits for ever for something that never happens.

I was thinking that could/should there bere a mqtt API to show possible error if camera detection stream doesn't receive frames for x period of time and after this one could force restart of the detection stream (also through mqtt).

### Version

0.12

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.13
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate123
  stats_interval: 300

go2rtc:
  api:
    listen: "0.0.0.0:1984"
  rtsp:
    listen: "0.0.0.0:8554"
  webrtc:
    candidates:
      - 192.168.0.1:8555
      - stun:8555
    listen: "0.0.0.0:8555"
  streams:
    talli_etu: rtsp://192.168.0.36:554/0/h264major
    talli_etu_sub: rtsp://192.168.0.36:554/0/h264minor
    #640x480 5fps i-frame 5
    talli_taka: rtsp://192.168.0.30/user=_password=_channel=1_stream=0.sdp
    talli_taka_sub: rtsp://192.168.0.30/user=_password=_channel=1_stream=1.sdp
    #704x576 5fps i-frame 5
    talli_sivu: rtsp://192.168.0.33/user=_password=_channel=1_stream=0.sdp
    talli_sivu_sub: rtsp://192.168.0.33/user=_password=_channel=1_stream=1.sdp
    #704x576 5fps i-frame 5
    takaovi: rtsp://u:p@192.168.0.32:554/cam/realmonitor?channel=1&subtype=0
    takaovi_sub: rtsp://u:p@192.168.0.32:554/cam/realmonitor?channel=1&subtype=1
    #704x576 5 fps i-frame 5
    etuovi: rtsp://192.168.0.34:554/user=_password=_channel=1_stream=0.sdp?real_stream
    etuovi_sub: rtsp://192.168.0.34:554/user=_password=_channel=1_stream=1.sdp?real_stream
    #704x576 5fps i-frame 5
    katos: rtsp://u:p@192.168.0.35:554/cam/realmonitor?channel=1&subtype=0
    katos_sub: rtsp://u:p@192.168.0.35:554/cam/realmonitor?channel=1&subtype=1
    #704x576 5fps i-frame 5
    katostie: rtsp://192.168.0.31/user=_password=_channel=1_stream=0.sdp
    katostie_sub: rtsp://192.168.0.31/user=_password=_channel=1_stream=1.sdp
    #704x576 5fps i-frame 5

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  expire_interval: 10
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 704
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 576
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
#  stationary:
#    interval: 10
#    threshold: 50
#    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
#      default: 3000
      # Optional: Object specific values
#      objects:
#        person: 1000
#        car: 1000
#        dog: 1000
#        cat: 1000

model:
  width: 320 #default 320
  height: 320 #default 320

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  retain:
    # Required: Default retention days (default: shown below)
    default: 3
    # Optional: Per object retention days
    objects:
      person: 5

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat
  restream: false
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - car
    - bus
  filters:
    cat:
      min_score: 0.4
      threshold: 0.5
    dog:
      min_score: 0.4
      threshold: 0.5
    person:
      min_score: 0.5
      threshold: 0.6
    car:
      min_score: 0.3
      threshold: 0.5


cameras:
#  test:
#    ffmpeg:
#      inputs:
#        - path: /media/frigate/10.17.mp4
#          input_args: -re -stream_loop -1 -fflags +genpts
#          roles:
#            - detect
#    detect:
#      width: 704
#      height: 576
#      fps: 5

  talli_etu:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/talli_etu_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/talli_etu
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
       stream_name: talli_etu_sub
    detect:
      width: 640
      height: 360
      fps: 5
    zones:
      piha:
        coordinates: 640,480,640,208,332,123,0,184,0,480
      tie:
        coordinates: 183,57,176,75,640,198,640,149
      metsa:
        coordinates: 155,48,153,0,640,0,640,0,640,143
      parkki:
        coordinates: 0,0,125,0,179,146,0,169
    record:
      events:
        required_zones:
          - piha
          - tie
          - metsa
    snapshots:
      required_zones:
        - piha
        - tie
        - metsa

  talli_taka:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/talli_taka_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/talli_taka
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
    live:
       stream_name: talli_taka_sub

  talli_sivu:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/talli_sivu_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/talli_sivu
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
    live:
       stream_name: talli_sivu_sub

  takaovi:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/takaovi_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/takaovi
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
    live:
       stream_name: takaovi_sub

  etuovi:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/etuovi_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/etuovi
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
    live:
       stream_name: etuovi_sub

  katos:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/katos_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/katos
          input_args: preset-rtsp-restream
          roles:
            - record
    zones:
      parkki:
        coordinates: 704,576,704,48,657,93,363,81,391,576
      piha:
        coordinates: 0,0,298,0,704,0,704,0,704,38,661,72,356,67,365,576,0,576
    objects:
      filters:
        car:
          mask:
            - 646,89,704,48,704,576,440,576,364,93
    record:
      events:
        required_zones:
          - piha
    snapshots:
      required_zones:
        - piha
    live:
       stream_name: katos_sub

  katostie:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/katostie_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/katostie
          input_args: preset-rtsp-restream
          roles:
            - record
    zones:
      tie:
        coordinates: 704,229,704,352,399,182,399,88
      metsa:
        coordinates: 704,0,409,0,404,103,704,237
      piha:
        coordinates: 704,355,400,193,411,0,89,0,85,77,0,102,0,576,704,576,704,354
      talli:
        coordinates: 0,92,73,77,86,0,0,0
    record:
      events:
        required_zones:
          - tie
          - piha
          - metsa
    snapshots:
      required_zones:
        - tie
        - piha
        - metsa
    live:
       stream_name: katostie_sub
```

### Relevant log output

```shell
2023-11-14 20:18:37.066294925  [INFO] Starting Frigate...
2023-11-14 20:18:37.819409119  [2023-11-14 20:18:37] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-14 20:18:37.848228213  [2023-11-14 20:18:37] peewee_migrate                 INFO    : Starting migrations
2023-11-14 20:18:37.850952294  [2023-11-14 20:18:37] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-14 20:18:37.861324986  [2023-11-14 20:18:37] detector.coral                 INFO    : Starting detection process: 579
2023-11-14 20:18:40.506627037  [2023-11-14 20:18:37] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-11-14 20:18:40.506686197  [2023-11-14 20:18:37] frigate.app                    INFO    : Output process started: 581
2023-11-14 20:18:40.506722271  [2023-11-14 20:18:37] frigate.app                    INFO    : Camera processor started for talli_etu: 587
2023-11-14 20:18:40.506754971  [2023-11-14 20:18:37] frigate.app                    INFO    : Camera processor started for talli_taka: 589
2023-11-14 20:18:40.506786013  [2023-11-14 20:18:37] frigate.app                    INFO    : Camera processor started for talli_sivu: 591
2023-11-14 20:18:40.506812767  [2023-11-14 20:18:37] frigate.app                    INFO    : Camera processor started for takaovi: 592
2023-11-14 20:18:40.506844828  [2023-11-14 20:18:37] frigate.app                    INFO    : Camera processor started for etuovi: 594
2023-11-14 20:18:40.506871613  [2023-11-14 20:18:37] frigate.app                    INFO    : Camera processor started for katos: 595
2023-11-14 20:18:40.506901565  [2023-11-14 20:18:37] frigate.app                    INFO    : Camera processor started for katostie: 597
2023-11-14 20:18:40.506930695  [2023-11-14 20:18:37] frigate.app                    INFO    : Capture process started for talli_etu: 599
2023-11-14 20:18:40.506958355  [2023-11-14 20:18:37] frigate.app                    INFO    : Capture process started for talli_taka: 602
2023-11-14 20:18:40.506986280  [2023-11-14 20:18:37] frigate.app                    INFO    : Capture process started for talli_sivu: 607
2023-11-14 20:18:40.507014346  [2023-11-14 20:18:37] frigate.app                    INFO    : Capture process started for takaovi: 614
2023-11-14 20:18:40.507042764  [2023-11-14 20:18:37] frigate.app                    INFO    : Capture process started for etuovi: 621
2023-11-14 20:18:40.507072066  [2023-11-14 20:18:37] frigate.app                    INFO    : Capture process started for katos: 630
2023-11-14 20:18:40.507100627  [2023-11-14 20:18:37] frigate.app                    INFO    : Capture process started for katostie: 659
2023-11-14 20:18:40.514368861  [2023-11-14 20:18:40] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-11-15 06:56:09.405972689  [2023-11-15 06:56:09] watchdog.katos                 INFO    : katos exceeded fps limit. Exiting ffmpeg...
2023-11-15 06:56:09.406067195  [2023-11-15 06:56:09] watchdog.katos                 INFO    : Waiting for ffmpeg to exit gracefully...
2023-11-15 06:56:22.964826494  [2023-11-15 06:56:22] frigate.video                  ERROR   : katos: Unable to read frames from ffmpeg process.
2023-11-15 06:56:22.973920700  [2023-11-15 06:56:22] frigate.video                  ERROR   : katos: ffmpeg process is not running. exiting capture thread...

go2rtc log
2023-11-14 20:18:37.066308309  [INFO] Preparing go2rtc config...
2023-11-14 20:18:37.284260994  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-11-14 20:18:37.309467646  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-11-14 20:18:37.309471490  [INFO] Starting go2rtc...
2023-11-14 20:18:37.375044223  20:18:37.374 INF go2rtc version 1.8.1 linux/amd64
2023-11-14 20:18:37.375262846  20:18:37.375 INF [api] listen addr=0.0.0.0:1984
2023-11-14 20:18:37.375579158  20:18:37.375 INF [rtsp] listen addr=0.0.0.0:8554
2023-11-14 20:18:37.376307391  20:18:37.376 INF [webrtc] listen addr=0.0.0.0:8555
2023-11-14 20:18:47.066880086  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe rtsp://192.168.0.1:8554/katos_sub
ffprobe version 4.3.6-0+deb11u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x555ee5bf8a00] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://192.168.0.1:8554/katos_sub':
  Metadata:
    title           : go2rtc/1.8.1
  Duration: N/A, start: 1.280000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt470bg, progressive), 704x576 [SAR 27:22 DAR 3:2], 5 fps, 5 tbr, 90k tbn, 10 tbc

with forced tcp
ffprobe rtsp://192.168.0.1:8554/katos_sub -rtsp_transport tcp
ffprobe version 4.3.6-0+deb11u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://192.168.0.1:8554/katos_sub':
  Metadata:
    title           : go2rtc/1.8.1
  Duration: N/A, start: 1.280000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt470bg, progressive), 704x576 [SAR 27:22 DAR 3:2], 5 fps, 5 tbr, 90k tbn, 10 tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

Everything is else than the detect stream is working perfect. I can access streams and recordings inside frigate.
