### ISSUE TITLE
[Config Support]: recording is disabled in config. but it keeps turning on. without interaction

### ISSUE THREAD

**Issue by mortalone** [blakeblackshear/frigate#8625]
### Describe the problem you are having

So. i am using a camera as a presence detection for a livingroom. and i do not want it to record. AND after some time the configuration is changed to say "record:   enabled: true" in the configuration file.
so i have this configuration

### Version

0.12.1-367d724

### Frigate config file

```yaml
go2rtc:
  streams:
    livingroom:
      - rtsp://xxx:xxx@192.168.0.178/live0

cameras:
stuen: # <------ Name the camera
    ffmpeg:
      #hwaccel_args:
      #  - -c:v:1
      #  - h264_v4l2m2m
      inputs:
        - path: rtsp://Mortal12:Hellwiz12@192.168.0.178/live0 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      enabled: false
      mode: objects            
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      #width: 640 # <---- update for your camera's resolution
      #height: 360 # <---- update for your camera's resolution
      fps: 1
    record: 
      enabled: false
      retain:
        days: 1
        mode: motion
      events:
        objects:
          - car 
        retain: 
          default: 1
          mode: motion
    motion:
      improve_contrast: true
      threshold: 10
      contour_area: 10
      delta_alpha: 0.5
      mask:
        - 0,0,1920,0,1920,1080,1871,1080,1853,463,1340,448,937,483,695,502,748,911,1328,882,1868,953,1876,1080,721,1080,0,1080            
    objects:
      track:
        - person
        #- cat
        #- dog
      filters:
        person:
          min_score: 0.40 # min score for object to initiate tracking (default: 0.5
          threshold: 0.12 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          min_area: 2000
          max_area: 150000
          #min_ratio: 0.8 # Optional: minimum width/height of the bounding box for the detected object (default: 0) 
          #max_ratio: 2.0 # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)          
          mask:
            - 0,0,1920,0,1920,1080,1871,1080,1853,463,1340,448,937,483,695,502,748,911,1328,882,1868,953,1876,1080,721,1080,0,1080
```

### Relevant log output

```shell
dont see any relevant entries in log
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
