### ISSUE TITLE
[Support]: UI Events time is invalid

### ISSUE THREAD

**Issue by a2nt** [blakeblackshear/frigate#8632]
### Describe the problem you are having

![image](https://github.com/blakeblackshear/frigate/assets/672794/156622d6-9bd4-4aa3-b2e2-94c1a78a931c)

### Version

0.13.0-8c7f6d4

### Frigate config file

```yaml
ui:
  use_experimental: true

detectors:
  armnn:
    type: rknn

model:
  width: 320
  height: 320

mqtt:
  host: 192.168.88.2 # Docker Host
  user: home
  password: pass
  stats_interval: 60

database:
  path: /media/frigate/frigate.db

# Optional: ffmpeg configuration
ffmpeg:
  hwaccel_args: preset-rk-h264 # or preset-rk-h265
  output_args:
     record: preset-record-generic-audio-aac
     detect: -f rawvideo
     rtmp: -c copy -f flv -flvflags no_duration_filesize

objects:
  track:
    - person
    - car
    - dog
    - cat

motion:
  threshold: 30
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mqtt_off_delay: 30

record:
  enabled: True
  retain:
    days: 2
    mode: motion

  events:
    #max_seconds: 300
    pre_capture: 10 # sec
    post_capture: 30 # sec
    objects:
      - person
      - car
      - dog
      - cat

    retain:
      default: 7
      mode: active_objects
      objects:
        person: 10
        car: 3
        dog: 1
        cat: 1

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  height: 1080
  retain:
    default: 15
    objects:
      person: 15
      car: 3
      dog: 2
      cat: 1
rtmp:
  enabled: False

live:
  height: 1080
  quality: 1

timestamp_style:
  position: "br"
  format: "%d.%m.%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: "solid"

detect:
  enabled: true
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 100
    threshold: 50

  # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
  #max_frames:
  #    default: 3000 # 3000 frames / 5 fps = 10 mins

logger:
  default: info
  logs:
    frigate.mqtt: error

cameras:
  camera_0: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.88.10:554 # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2880 # <---- update for your camera's resolution
      height: 1616 # <---- update for your camera's resolution
    zones:
      inner0:
        coordinates: 0,1616,2880,1616,2880,1301,2369,755,0,1044
      outside_gate0:
        coordinates: 2607,824,2880,975,2880,697,2625,673,2458,659,2396,673,2387,699,2451,755
      outside_house0:
        coordinates: 262,753,1614,504,1645,642,2149,617,2343,726,2767,688,2574,626,2380,544,2680,384,2880,395,2880,666,1559,824,313,959
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 90

  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.88.11:554 # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2880 # 1920 <---- update for your camera's resolution
      height: 1616 # 1080 <---- update for your camera's resolution
    zones:
      inner1:
        coordinates: 2880,813,1807,275,1696,242,0,260,0,1616,2880,1616
      outside1:
        coordinates: 65,0,67,209,1177,185,1781,218,2880,697,2880,0
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 90

  camera_2: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.88.12:554 # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2880 # <---- update for your camera's resolution
      height: 1616 # <---- update for your camera's resolution
    zones:
      inside2:
        coordinates: 413,693,460,0,0,0,0,1616,455,1616
      outside2:
        coordinates: 1434,1616,1414,1412,1377,1179,1124,462,984,193,406,0,404,506,429,1616
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 90

  camera_3: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.88.13:554 # <----- Update for your camera
          roles:
            - detect
            - record
    detect:
      width: 2880 # <---- update for your camera's resolution
      height: 1616 # <---- update for your camera's resolution
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 90
    zones:
      inner3:
        coordinates: 2880,895,2880,1616,2245,1616,2687,1157
      outside3:
        coordinates: 0,1616,2249,1616,2660,1204,2880,886,2669,724,1830,926,0,1201
```

### Relevant log output

```shell
2023-11-16 00:47:09.969617439  [INFO] Preparing Frigate...
2023-11-16 00:47:10.009846688  [INFO] Starting Frigate...
2023-11-16 00:47:11.870620731  [2023-11-16 00:47:11] frigate.app                    INFO    : Starting Frigate (0.13.0-8c7f6d4)
2023-11-16 00:47:11.955994611  [2023-11-16 00:47:11] peewee_migrate.logs            INFO    : Starting migrations
2023-11-16 00:47:11.962835837  [2023-11-16 00:47:11] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-11-16 00:47:11.977586358  [2023-11-16 00:47:11] frigate.app                    INFO    : Recording process started: 452
2023-11-16 00:47:11.981430465  [2023-11-16 00:47:11] frigate.app                    INFO    : go2rtc process pid: 89
2023-11-16 00:47:12.042031438  [2023-11-16 00:47:12] detector.rknn                  INFO    : Starting detection process: 462
2023-11-16 00:47:12.048791875  [2023-11-16 00:47:12] frigate.app                    INFO    : Output process started: 464
2023-11-16 00:47:12.103085072  [2023-11-16 00:47:12] frigate.app                    INFO    : Camera processor started for camera_0: 470
2023-11-16 00:47:12.104592965  [2023-11-16 00:47:12] frigate.app                    INFO    : Camera processor started for camera_1: 473
2023-11-16 00:47:12.113578783  [2023-11-16 00:47:12] frigate.app                    INFO    : Camera processor started for camera_2: 474
2023-11-16 00:47:12.130735808  [2023-11-16 00:47:12] frigate.app                    INFO    : Camera processor started for camera_3: 476
2023-11-16 00:47:12.132608279  [2023-11-16 00:47:12] frigate.app                    INFO    : Capture process started for camera_0: 479
2023-11-16 00:47:12.142512541  [2023-11-16 00:47:12] frigate.app                    INFO    : Capture process started for camera_1: 482
2023-11-16 00:47:12.170686520  [2023-11-16 00:47:12] frigate.app                    INFO    : Capture process started for camera_2: 488
2023-11-16 00:47:12.171616047  [2023-11-16 00:47:12] frigate.app                    INFO    : Capture process started for camera_3: 492
2023-11-16 00:47:12.354402452  I RKNN: [00:47:12.354] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
2023-11-16 00:47:12.354489951  I RKNN: [00:47:12.354] RKNN Driver Information: version: 0.9.2
2023-11-16 00:47:12.354873487  I RKNN: [00:47:12.354] RKNN Model Information: version: 6, toolkit version: 1.5.2+b642f30c(compiler version: 1.5.2 (c6b7b351a@2023-08-23T07:39:01)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
```

### FFprobe output from your camera

```shell
ffprobe version 6.0-5+git230804.e243e8d001~j1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version='5+git230804.e243e8d001~j1' --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-version3 --enable-rkmpp --enable-sdl2 --disable-sndio --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-shared
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://admin:pass@192.168.88.10:554':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, progressive), 2880x1616, 10 fps, 10 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
[h264_rkmpp_decoder @ 0xaaaac5d3a9d0] Picture format is yuv420p.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

unknown

**Comment by NickM-27** [comment]
more information is going to be needed like json payload or browser logs, I am not able to reproduce this

**Comment by a2nt** [comment]
> more information is going to be needed like json payload or browser logs, I am not able to reproduce this

I can see following json response:

http://192.168.88.2:85/api/events?cameras=all&labels=all&zones=all&sub_labels=all&time_range=00:00,24:00&timezone=AtlanticTime&favorites=0&is_submitted=-1&in_progress=0&include_thumbnails=0&limit=25

```
[{"box":null,"camera":"camera_0","data":{"attributes":[],"box":[0.7625,0.530940594059406,0.02847222222222222,0.1454207920792079],"region":[0.7229166666666667,0.4591584158415842,0.13333333333333333,0.2376237623762376],"score":0.7470703125,"top_score":0.7470703125,"type":"object"},"end_time":1700089934.420568,"false_positive":null,"has_clip":true,"has_snapshot":true,"id":"1700089902.909669-s6retw","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700089892.909669,"sub_label":null,"top_score":null,"zones":["inner0"]},{"box":null,"camera":"camera_0","data":{"attributes":[],"box":[0.7840277777777778,0.47896039603960394,0.034375,0.1998762376237624],"region":[0.7222222222222222,0.4603960396039604,0.13333333333333333,0.2376237623762376],"score":0.8466796875,"top_score":0.8466796875,"type":"object"},"end_time":1700089936.264065,"false_positive":null,"has_clip":true,"has_snapshot":true,"id":"1700089902.003851-x1e8c4","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700089892.003851,"sub_label":null,"top_score":null,"zones":["inner0"]},{"box":null,"camera":"camera_0","data":{"attributes":[],"box":[0.2743055555555556,0.6534653465346535,0.09861111111111111,0.24133663366336633],"region":[0.22361111111111112,0.6206683168316832,0.1736111111111111,0.3094059405940594],"score":0.8818359375,"top_score":0.8818359375,"type":"object"},"end_time":1700089924.229201,"false_positive":null,"has_clip":true,"has_snapshot":true,"id":"1700089890.908504-7qjbyz","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700089880.908504,"sub_label":null,"top_score":null,"zones":["inner0"]},{"box":null,"camera":"camera_0","data":{"attributes":[],"box":[0.5243055555555556,0.7320544554455446,0.0920138888888889,0.26732673267326734],"region":[0.4597222222222222,0.21534653465346534,0.44027777777777777,0.7846534653465347],"score":0.61328125,"top_score":0.728271484375,"type":"object"},"end_time":1700089912.239924,"false_positive":null,"has_clip":true,"has_snapshot":true,"id":"1700089880.727053-k3jbbc","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700089870.727053,"sub_label":null,"top_score":null,"zones":["inner0"]},{"box":null,"camera":"camera_0","data":{"attributes":[],"box":[0.496875,0.6528465346534653,0.36701388888888886,0.2877475247524752],"region":[0.4600694444444444,0.21782178217821782,0.4388888888888889,0.7821782178217822],"score":0.8857421875,"top_score":0.904296875,"type":"object"},"end_time":1700091207.451076,"false_positive":null,"has_clip":true,"has_snapshot":true,"id":"1700089093.221174-b9nwgm","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700089083.221174,"sub_label":null,"top_score":null,"zones":["inner0"]},{"box":[2246,206,2386,320],"camera":"camera_3","data":{},"end_time":1700086399.910193,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700086265.392853-0x19gv","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700086255.392853,"sub_label":null,"top_score":0.734375,"zones":[]},{"box":[759,694,881,884],"camera":"camera_0","data":{},"end_time":1700086231.351853,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700086195.9518-seatr3","label":"cat","plus_id":null,"retain_indefinitely":false,"start_time":1700086185.9518,"sub_label":null,"top_score":0.71484375,"zones":["outside_house0"]},{"box":[690,809,2770,1584],"camera":"camera_0","data":{},"end_time":1700085321.498925,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700085277.515608-v0dlb8","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700085267.515608,"sub_label":null,"top_score":0.716796875,"zones":["inner0"]},{"box":[2246,301,2261,316],"camera":"camera_3","data":{},"end_time":1700085629.273019,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700085171.87514-4wgehu","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700085161.87514,"sub_label":null,"top_score":0.75390625,"zones":[]},{"box":[2380,293,2420,342],"camera":"camera_3","data":{},"end_time":1700084723.67336,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700084414.65441-pekv6d","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700084404.65441,"sub_label":null,"top_score":0.70703125,"zones":[]},{"box":[2380,270,2434,331],"camera":"camera_3","data":{},"end_time":1700084452.057111,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700084064.049862-mlrumq","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700084054.049862,"sub_label":null,"top_score":0.70703125,"zones":[]},{"box":[759,8,890,84],"camera":"camera_1","data":{},"end_time":1700083963.876525,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700083476.497069-zpugw0","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700083466.497069,"sub_label":null,"top_score":0.8203125,"zones":["outside1"]},{"box":[1395,1032,1450,1160],"camera":"camera_0","data":{},"end_time":1700082563.86698,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700082498.852756-gvgn49","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700082488.852756,"sub_label":null,"top_score":0.70703125,"zones":["inner0"]},{"box":[1444,1131,1462,1169],"camera":"camera_0","data":{},"end_time":1700081225.671234,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700081159.420775-kwo5vl","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700081149.420775,"sub_label":null,"top_score":0.70703125,"zones":["inner0"]},{"box":[740,8,889,80],"camera":"camera_1","data":{},"end_time":1700082053.509705,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700080816.588859-dru73e","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700080806.588859,"sub_label":null,"top_score":0.796875,"zones":["outside1"]},{"box":[614,1,775,87],"camera":"camera_1","data":{},"end_time":1700080874.506049,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700080668.186145-r5y49g","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700080658.186145,"sub_label":null,"top_score":0.76953125,"zones":["outside1"]},{"box":[1394,1024,1451,1171],"camera":"camera_0","data":{},"end_time":1700080071.393262,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700079950.987609-ofl7j3","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700079940.987609,"sub_label":null,"top_score":0.78125,"zones":["outside_house0","inner0"]},{"box":[111,399,184,561],"camera":"camera_2","data":{},"end_time":1700078698.120256,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700078657.10824-iqkg8z","label":"cat","plus_id":null,"retain_indefinitely":false,"start_time":1700078647.10824,"sub_label":null,"top_score":0.84375,"zones":["inside2"]},{"box":[1440,1130,1460,1172],"camera":"camera_0","data":{},"end_time":1700078467.641015,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700078258.374322-dlhojw","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700078248.374322,"sub_label":null,"top_score":0.70703125,"zones":["inner0"]},{"box":[1439,1130,1461,1174],"camera":"camera_0","data":{},"end_time":1700078305.458371,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700078233.637426-2t80d0","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700078223.637426,"sub_label":null,"top_score":0.70703125,"zones":["inner0"]},{"box":[1592,458,1619,547],"camera":"camera_3","data":{},"end_time":1700076995.565838,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700076956.005053-hw52nb","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700076946.005053,"sub_label":null,"top_score":0.71484375,"zones":[]},{"box":[2683,512,2702,541],"camera":"camera_0","data":{},"end_time":1700076923.479659,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700076841.459825-9q6vt4","label":"person","plus_id":null,"retain_indefinitely":false,"start_time":1700076831.459825,"sub_label":null,"top_score":0.70703125,"zones":["inner0","outside_gate0","outside_house0"]},{"box":[751,6,890,82],"camera":"camera_1","data":{},"end_time":1700080743.180765,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700076342.292296-zv6ia3","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700076332.292296,"sub_label":null,"top_score":0.7890625,"zones":["outside1"]},{"box":[1540,40,1699,117],"camera":"camera_1","data":{},"end_time":1700075793.699243,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700075736.4539-ellf1y","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700075726.4539,"sub_label":null,"top_score":0.76171875,"zones":["outside1"]},{"box":[770,7,891,86],"camera":"camera_1","data":{},"end_time":1700076337.715711,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1700075713.799916-4hgxjp","label":"car","plus_id":null,"retain_indefinitely":false,"start_time":1700075703.799916,"sub_label":null,"top_score":0.78125,"zones":["outside1"]}]
```

Just noticed that it works ok using Chrome, but doesn't work at Firefox 115.4.0esr (64-bit)

I think it happens cuz UI is unable to detect browser timezone
Some details here: https://stackoverflow.com/questions/37798404/getting-timezone-using-intl-api-doesnt-work-in-firefox

If UI is unable to get browser timezone server timezone should be used. Sometimes timezone can be hidden for privacy

**Comment by NickM-27** [comment]
If that's the case then you should confirm the time zone in the frigate config

```
ui:
  timezone: x/y
```

**Comment by a2nt** [comment]
> If that's the case then you should confirm the time zone in the frigate config
> 
> ```
> ui:
>   timezone: x/y
> ```

thx, but I don't see documentation what is x/y? Can u give me an example?

**Comment by NickM-27** [comment]
You can find an example in the config reference https://docs.frigate.video/configuration/

```
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: False
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: "%Y/%m/%d %H:%M"
```

**Comment by a2nt** [comment]
> If that's the case then you should confirm the time zone in the frigate config
> 
> ```
> ui:
>   timezone: x/y
> ```

Thx it works

**Comment by a2nt** [comment]
@NickM-27 I can see one more issue at browser console
[WARNING] No locale found with identifier "en-US" and time still doesn't work

**Comment by NickM-27** [comment]
That warning is common even in chrome, what is not working?

**Comment by a2nt** [comment]
> That warning is common even in chrome, what is not working?

I have defined UI settings, but time still invalid

```
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Etc/GMT-2
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: True
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 24hour
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
#  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
 # time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: "%d.%m.%Y %H:%M"

```
