### ISSUE TITLE
[Config Support]: Help reducing strange person detection false positives

### ISSUE THREAD

**Issue by avvalex** [blakeblackshear/frigate#8648]
### Describe the problem you are having

Hi friends, i'm facing a strange (for me) problem in person detection.
I have (for now) only a cam enabled in persons detection, and many times i've encountered false positives (lukily it seems not missing a hit with real persons).
Sometimes a cat, sometimes something else moving thru my courtyard, but more times with objects that i don't understand how it can think it's a person.
In other words, maybe a certain number of pixel change can trigger a look, but without a human shape why it sees a person?
Example: a bike parked (it's 3 days that the bike triggers many human detectionn....), another time it was a garbage bin left in the middle of the yard that triggered dozen of false positives.....
Surely i'm making some mistake.... Can you help me?

<img width="846" alt="Screenshot 2023-11-17 215021" src="https://github.com/blakeblackshear/frigate/assets/60694870/263f82c3-aba5-475f-bda3-11d9c3273d6d">

PS: I use detect width 854 but the cam sub resolution in 640x480; 854 is needed in order to see correct aspect ratio in frigate webui and in HA cards (or at least i haven't fount a better solution)

### Version

0.12.1

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

[...]

# cam yard
  yard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxxx:xxxx@127.0.0.1:8554/yard
#          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxxx:xxxx@127.0.0.1:8554/yard_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 854
      height: 480
#     fps: 5
    motion:
      mask:
        - 0,0,0,102,520,99,520,143,854,247,854,0
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.6
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
```

### Relevant log output

```shell
no log
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
