### ISSUE TITLE
[Support]: RKNN detection no longer works with latest dev

### ISSUE THREAD

**Issue by sylv3rblade** [blakeblackshear/frigate#8653]
### Describe the problem you are having

Thanks for the efforts on this project.

After pulling the latest dev, I noticed that the debug screen on my cameras no longer display the bounding boxes on the objects I know would be previously detected.  This happened seemingly after this [PR](https://github.com/blakeblackshear/frigate/pull/8631/files) got merged.  I reverted the merge [commit ](7522bb6fabdb36f8cfafa1877c13e66d052481a5.) in my local and rebuilt the image using sudo make local-rk and the detection works again.

I'm guessing there's a diff between the provided yolov8n-320x320.rknn and the one the image downloads but havent tried manually downloading and comparing the diff of the files.

current dev:

![Screenshot 2023-11-18 151252](https://github.com/blakeblackshear/frigate/assets/467007/f1ec7d45-4082-4f61-b8ef-70cf720b9820)

after revert

![Screenshot 2023-11-18 152122](https://github.com/blakeblackshear/frigate/assets/467007/fa60784d-f5f6-4aaf-92e2-691b796371e6)

### Version

0.13.0-64618AAA

### Frigate config file

```yaml
detectors:
  rknn:
    type: rknn
    # core mask for npu
    core_mask: 0b011

model:
  #path: default-yolov8n
  path: /models/yolov8n-320x320.rknn
  width: 320
  height: 320
  input_pixel_format: bgr             # required
  input_tensor: nhwc

go2rtc:
  streams:
    balcony:
    - rtsp://user:pass@ip/stream1
    - ffmpeg:rtsp_cam#audio=opus

  balcony:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/balcony
        roles: 
          - detect
    detect:
      enabled: true
    objects:
      track:
        - person
        - cat
        - bird
        - dog
        - car
```

### Relevant log output

```shell
2023-11-18 07:20:53.620822411  [INFO] Preparing Frigate...
2023-11-18 07:20:53.665779684  [INFO] Starting Frigate...
2023-11-18 07:20:55.320791891  [2023-11-18 07:20:55] frigate.app                    INFO    : Starting Frigate (0.13.0-64618aaa)
2023-11-18 07:21:02.319936597  [2023-11-18 07:21:02] peewee_migrate.logs            INFO    : Starting migrations
2023-11-18 07:21:02.337079691  [2023-11-18 07:21:02] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-11-18 07:21:02.376080033  [2023-11-18 07:21:02] detector.rknn                  INFO    : Starting detection process: 494
2023-11-18 07:21:02.698458399  I RKNN: [07:21:02.698] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
2023-11-18 07:21:02.698544440  I RKNN: [07:21:02.698] RKNN Driver Information: version: 0.9.0
2023-11-18 07:21:02.698937018  I RKNN: [07:21:02.698] RKNN Model Information: version: 6, toolkit version: 1.5.2+b642f30c(compiler version: 1.5.2 (c6b7b351a@2023-08-23T07:39:01)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
```

### FFprobe output from your camera

```shell
ffprobe version e243e8d001-20231113 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-nonfree --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-openssl --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --enable-libdrm --enable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --disable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --disable-libvpx --enable-libwebp --enable-lv2 --enable-rkmpp --disable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --disable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lstdc++ -lgomp' --extra-version=20231113
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://dvrusr:senbonzakura@192.168.0.232:554/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 2560x1440, 15 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
[h264_rkmpp_decoder @ 0xaaaaf1a1a9a0] Picture format is yuv420p.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo 320WS
