### ISSUE TITLE
[Support]: birdseye output vertical aspect ratio: wrong arrangement

### ISSUE THREAD

**Issue by toxic0berliner** [blakeblackshear/frigate#8666]
### Describe the problem you are having

I have 8 cameras all horizontal 1080p
Birdseye is displaying a 3x3 grid with one cell black.
As I'm mostly viewing this on my phone I wanted to display a 2x4lines instead so I defined with and height: 2160 of the birdseye in my config, but the output is still a 3x3 grid but now with lots of black space between lines of cameras...

I suspect this is how it's intended by frigate, I was wondering nonetheless if it can be setup somehow to output a 4x2 vertical grid...

### Version

 0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: home.lan
  user: frigate
  password: xxx
  stats_interval: 60


logger:
  # Optional: Default log verbosity (default: shown below)
  #default: warning
  # Optional: Component specific logger overrides
  logs:
    frigate.event: info 
    frigate.ffmpeg: debug

ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'
    - -rtsp_transport 
    - tcp 
    - -timeout 
    - 5000000 

detectors: 
  cpu1:
    type: cpu
  #cpu2:
  #  type: cpu
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  retain:
    days: 10
    #mode: motion
    #mode: active_objects
    mode: all
  events:
    pre_capture: 4
    post_capture: 35
    retain:
      default: 70
      mode: active_objects
      objects:
        dog: 2
        car: 7
        cat: 7
        person: 70
      
birdseye:
  enabled: True
  mode: continuous
  restream: true  
  width: 1920 
  height: 1080 
  #height: 2400
  # Optional: Encoding quality of the mpeg1 feed, 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15

go2rtc:
  rtsp:
    username: "xxx"
    password: "xxx"
  streams:
    Portail: 
      - rtsp://xxx:554/stream1
    Sonnette: 
      - rtsp://xxx:554/h264Preview_01_sub
    Escalier: 
      - rtsp://xxx:554/stream2
    Entree: 
      - rtsp://xxx:554/stream2
    Balcon: 
      - rtsp://xxx:554/stream2
    Cuisine: 
      - rtsp://xxx:554/stream2
    Vigne: 
      - rtsp://xxx:554/stream2
    Garage: 
      - rtsp://xxx:554/stream2
  webrtc:
    candidates:
      - stun:8554
      - stun:8555
      - 127.0.0.1:8554
      - 127.0.0.1:8555

cameras:
  Portail:
    ui:
      order: 5
    ffmpeg:
      output_args:
        # Optional: output args for detect streams (default: shown below)
        detect: -f rawvideo -pix_fmt yuv420p
        # Optional: output args for record streams (default: shown below)
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        # Optional: output args for rtmp streams (default: shown below)
        rtmp: -c:v copy -c:a copy -f flv
        record: preset-record-generic-audio-aac
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://127.0.0.1:8554/Portail
        
          roles: 
            - detect
            - path: rtsp://127.0.0.1:8554/Portail
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        - car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        car:
          min_score: 0.65
          threshold: 0.75
        cat:
          min_score: 0.65
          threshold: 0.77
    
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
  Sonnette:
    ui:
      order: 1
    ffmpeg:
      output_args:
        # Optional: output args for detect streams (default: shown below)
        detect: -f rawvideo -pix_fmt yuv420p
        # Optional: output args for record streams (default: shown below)
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
        record: preset-record-generic-audio-copy
        # Optional: output args for rtmp streams (default: shown below)
        #rtmp: -c:v copy -c:a aac -f flv
        rtmp: -c:v copy -c:a copy
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:554/h264Preview_01_sub
          roles: 
            - detect
        - path: rtsp://xxx:554/h264Preview_01_main
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        #- car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        #car:
        #  min_score: 0.5
        #  threshold: 0.7
        cat:
          min_score: 0.65
          threshold: 0.77
    #motion:
    #  mask:
    #    - 45,144,363,48,347,0,0,0
    #    - 640,0,640,161,569,170,558,0
    #    - 376,57,640,74,640,0,366,0
    #record:
    #  enabled: True
    #  retain:
    #    days: 1
    #    mode: motion
    #  events:
    #    retain:
    #      default: 50
    #      mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
  Escalier:
    ui:
      order: 2
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v copy -c:a copy -f flv
        record: preset-record-generic-audio-aac
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:554/stream2
          roles: 
            - detect
        - path: rtsp://xxx:554/stream1
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        #- car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        #car:
        #  min_score: 0.5
        #  threshold: 0.7
        cat:
          min_score: 0.65
          threshold: 0.77
    #motion:
    #  mask:
    #    - 45,144,363,48,347,0,0,0
    #    - 640,0,640,161,569,170,558,0
    #    - 376,57,640,74,640,0,366,0
    #record:
    #  enabled: True
    #  retain:
    #    days: 1
    #    mode: motion
    #  events:
    #    retain:
    #      default: 50
    #      mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
  Entree:
    ui:
      order: 3
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v copy -c:a copy -f flv
        record: preset-record-generic-audio-aac
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:554/stream2
          roles: 
            - detect
        - path: rtsp://xxx:554/stream1
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        #- car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        #car:
        #  min_score: 0.5
        #  threshold: 0.7
        cat:
          min_score: 0.65
          threshold: 0.77
    #motion:
    #  mask:
    #    - 45,144,363,48,347,0,0,0
    #    - 640,0,640,161,569,170,558,0
    #    - 376,57,640,74,640,0,366,0
    #record:
    #  enabled: True
    #  retain:
    #    days: 1
    #    mode: motion
    #  events:
    #    retain:
    #      default: 50
    #      mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
  Balcon:
    ui:
      order: 4
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v copy -c:a copy -f flv
        record: preset-record-generic-audio-aac
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:554/stream2
          roles: 
            - detect
        - path: rtsp://xxx:554/stream1
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        #- car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        #car:
        #  min_score: 0.5
        #  threshold: 0.7
        cat:
          min_score: 0.65
          threshold: 0.77
    #motion:
    #  mask:
    #    - 45,144,363,48,347,0,0,0
    #    - 640,0,640,161,569,170,558,0
    #    - 376,57,640,74,640,0,366,0
    #record:
    #  enabled: True
    #  retain:
    #    days: 1
    #    mode: motion
    #  events:
    #    retain:
    #      default: 50
    #      mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
  Cuisine:
    ui:
      order: 5
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v copy -c:a copy -f flv
        record: preset-record-generic-audio-aac
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:554/stream2
          roles: 
            - detect
        - path: rtsp://xxx:554/stream1
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        #- car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        #car:
        #  min_score: 0.5
        #  threshold: 0.7
        cat:
          min_score: 0.65
          threshold: 0.77
    #motion:
    #  mask:
    #    - 45,144,363,48,347,0,0,0
    #    - 640,0,640,161,569,170,558,0
    #    - 376,57,640,74,640,0,366,0
    #record:
    #  enabled: True
    #  retain:
    #    days: 1
    #    mode: motion
    #  events:
    #    retain:
    #      default: 50
    #      mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
  Vigne:
    ui:
      order: 7
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v copy -c:a copy -f flv
        record: preset-record-generic-audio-aac
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:554/stream2
          roles: 
            - detect
        - path: rtsp://xxx:554/stream1
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        #- car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        #car:
        #  min_score: 0.5
        #  threshold: 0.7
        cat:
          min_score: 0.65
          threshold: 0.77
    #motion:
    #  mask:
    #    - 45,144,363,48,347,0,0,0
    #    - 640,0,640,161,569,170,558,0
    #    - 376,57,640,74,640,0,366,0
    #record:
    #  enabled: True
    #  retain:
    #    days: 1
    #    mode: motion
    #  events:
    #    retain:
    #      default: 50
    #      mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
  Garage:
    ui:
      order: 6
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v copy -c:a copy -f flv
        record: preset-record-generic-audio-aac
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:554/stream2
          roles: 
            - detect
        - path: rtsp://xxx:554/stream1
          roles: 
            - rtmp
            - record
    objects:
      track:
        - person
        #- car
        #- dog
        - cat
      filters:
        person:
          min_score: 0.65
          threshold: 0.74
        #dog:
        #  min_score: 0.5
        #  threshold: 0.7
        #car:
        #  min_score: 0.5
        #  threshold: 0.7
        cat:
          min_score: 0.65
          threshold: 0.77
    #motion:
    #  mask:
    #    - 45,144,363,48,347,0,0,0
    #    - 640,0,640,161,569,170,558,0
    #    - 376,57,640,74,640,0,366,0
    #record:
    #  enabled: True
    #  retain:
    #    days: 1
    #    mode: motion
    #  events:
    #    retain:
    #      default: 50
    #      mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 100
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"10/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":576,"width":704},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"10/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

cheap Chinese  noname + reolink Poe doorbell
