### ISSUE TITLE
[HW Accel Support]: using custom ffmpeg including libraries on jetson nano

### ISSUE THREAD

**Issue by Geronimo2015** [blakeblackshear/frigate#8667]
### Describe the problem you are having

I'm using a custom built ffmpeg for HW acceleration on my nvidia jetson nano.
Managed to build ffmpeg on the jetson nano and configured a volume [mapping](https://docs.frigate.video/configuration/advanced#custom-ffmpeg-build).

I'm getting an error like when runnin in Frigate container:
`./ffmpeg: error while loading shared libraries: libnvmpi.so.1: cannot open shared object file: No such file or directory`

Any ideas how to overcome this?
Do I need to create a custom frigate docker image which has nVidia drivers installed?

### Version

0.12.1-367d724

### Frigate config file

```yaml
....

ffmpeg:
  hwaccel_args: h264_nvmpi


.....
```

### docker-compose file or Docker CLI command

```yaml
frigate:
      container_name: frigate
      restart: unless-stopped
      image: ghcr.io/blakeblackshear/frigate:stable
      shm_size: "64mb" # update for your cameras based on calculation above
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ..../volumes/frigate/config.yml:/config/config.yml
        - .../volumes/frigate/storage:/media/frigate
        - /home/user/src/jetson-ffmpeg/ffmpeg:/usr/lib/btbn-ffmpeg:ro
        - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
          target: /tmp/cache
          tmpfs:
            size: 250000000
      ports:
        - "5000:5000"
        - "8554:8554" # RTSP feeds
        - "8555:8555/tcp" # WebRTC over tcp
        - "8555:8555/udp" # WebRTC over udp
      environment:
        FRIGATE_RTSP_PASSWORD: "xxxxxx"
```

### Relevant log output

```shell
root@71386c721c2b:/usr/lib/btbn-ffmpeg# ./ffmpeg
./ffmpeg: error while loading shared libraries: libnvmpi.so.1: cannot open shared object file: No such file or directory
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

na
