### ISSUE TITLE
[Config Support]: I need help with my face recognition config and I even bought a new 8MP camera

### ISSUE THREAD

**Issue by nabheet** [blakeblackshear/frigate#8676]
### Describe the problem you are having

Here is the image that my frigate instance is sending to Double-Take over MQTT. I can't even recognize myself. :smile: 

I have had this problem for a while and I thought maybe getting a new camera might solve this problem. The new camera solved other problems but not this one. I didn't realize that 8MP just means the image gets bigger. :facepalm: 

I have also tried a lot of different settings based on the docs or googles and in some cases made the situation lot worse - like getting rainbows in my video feed.

Also, I realize this is a night time image but the daytime isn't much better. I will get an example tomorrow.

![image](https://github.com/blakeblackshear/frigate/assets/1319809/caff28fe-b8fb-4147-85c3-4c7724cf95b0)

Anyways, I really hope someone can help me get a better image shot.

### Version

0.13.0-beta5

### Frigate config file

```yaml
# yaml-language-server: $schema=http://localhost:5000/api/config/schema.json
mqtt:
  host: m
  user: USERNAME
  password: PASSWORD

detectors:
  deepstack:
    api_url: http://ds:5000/v1/vision/detection
    type: deepstack
    api_timeout: 5

  # tensorrt:
  #   type: tensorrt
  #   device: 0

# model:
#   path: /config/model_cache/tensorrt/yolov7x-640.trt
#   input_tensor: nchw
#   input_pixel_format: rgb
#   width: 640
#   height: 640


go2rtc:
  streams:
    front_door:
      - rtsp://192.168.86.54:554/user=USER&password=PASSWORD&channel=1&stream=0.sdp?
    garage_main:
     - rtsp://USERNAME:PASSWORD@192.168.86.55:88/videoMain

cameras:
  front_door:
    ffmpeg:
      # hwaccel_args: -c:v hevc_cuvid
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 1000
    ui:
      dashboard: true
    zones:
      front_path:
        coordinates: 1619,2160,1167,687,122,877,434,2160
        objects:
          - person
          - face
    objects:
      filters:
        amazon:
          mask:
          - 0,528,2701,577,3214,1164,1130,1937,1204,2160,3006,2160,3840,2160,3840,0,0,0
        fedex:
          mask:
          - 0,528,2701,577,3214,1164,1130,1937,1204,2160,3006,2160,3840,2160,3840,0,0,0
        ups:
          mask:
          - 0,528,2701,577,3214,1164,1130,1937,1204,2160,3006,2160,3840,2160,3840,0,0,0
        bus:
          mask:
          - 0,528,2701,577,3214,1164,1130,1937,1204,2160,3006,2160,3840,2160,3840,0,0,0
        bicycle:
          mask:
          - 0,528,2701,577,3214,1164,1130,1937,1204,2160,3006,2160,3840,2160,3840,0,0,0
        motorcycle:
          mask:
          - 0,528,2701,577,3214,1164,1130,1937,1204,2160,3006,2160,3840,2160,3840,0,0,0
        car:
          mask:
          - 0,528,2701,577,3214,1164,1130,1937,1204,2160,3006,2160,3840,2160,3840,0,0,0

  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 1000
    ui:
      dashboard: true
    objects:
      filters:
        bus:
          mask:
          - 83,422,520,303,513,157,1030,191,1117,334,1280,352,1280,0,0,0,0,194
        bicycle:
          mask:
          - 83,422,520,303,513,157,1030,191,1117,334,1280,352,1280,0,0,0,0,194
        motorcycle:
          mask:
          - 83,422,520,303,513,157,1030,191,1117,334,1280,352,1280,0,0,0,0,194
        car:
          mask:
          - 83,422,520,303,513,157,1030,191,1117,334,1280,352,1280,0,0,0,0,194
    zones:
      driveway:
        coordinates: 854,720,1059,339,523,247,56,330
        labels:
          - person
          - face
rtmp:
  enabled: false

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: true
  retain:
    default: 10
    objects:
      person: 15

record:
  enabled: true
  retain:
    days: 5
    mode: active_objects
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 10
      mode: active_objects
      objects:
        person: 15

birdseye:
  enabled: true
  quality: 31
  mode: continuous

detect:
  enabled: true
  width: 1280
  height: 720
  fps: 15

objects:
  track:
    - person
    - bicycle
    - motorcycle
    - car
    - bus
    - bird
    - cat
    - dog
    - face
  filters:
    dog:
      threshold: 0.8
    person:
      threshold: 0.8
    bicycle:
      threshold: 0.8
    motorcycle:
      threshold: 0.8
    car:
      threshold: 0.8
    bus:
      threshold: 0.8
    bird:
      threshold: 0.8
    cat:
      threshold: 0.8

motion:
  improve_contrast: true
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

I have even tried it with the NVIDIA GPU based TensorRT image. But right now I moved it to a server that has more RAM and CPU but no GPU. Also, I recently changed to the DeepStack detector hoping that it would help. And it didn't.

I have also messed with detect and mqtt height values without success.

PLEASE HAAAALLLLLLLPPPPPPPP!!!!!!
