### ISSUE TITLE
[Config Support]: setting strftime_fmt produces "invalid time"

### ISSUE THREAD

**Issue by dziban303** [blakeblackshear/frigate#8707]
### Describe the problem you are having

The `strftime_fmt` config option doesn't seem to work. Any format produces 'Invalid time' in the Events screen.

I wanted to change the date shown on events. It looks like I should be able to do that using `strftime_fmt` in the config. Initially I'd tried using `strftime_fmt: "%F %R"`, which should produce ISO8601-like format of "2023-11-21 14:24", but I also tried `strftime_fmt: "%Y-%m-%d %H:%M"` and a few other formats besides. All produce the same 'Invalid time' in the Events screen. Even using the default value `strftime_fmt: "%Y/%m/%d %H:%M"` as shown in [the documentation](https://docs.frigate.video/configuration) produces the same 'Invalid time' message:

![image](https://github.com/blakeblackshear/frigate/assets/7931765/3470a5e5-1205-4189-91ee-52de1a3ed284)

### Version

0.12.1-367D724

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.0.175:5000/api/config/schema.json
#database:
#  path: /mnt/d/frigate/frigate.db

mqtt:
  enabled: True
  host: 192.168.0.170
  topic_prefix: frigate
  client_id: frigate

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://u:p@192.168.0.198:554/
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 2048
      height: 1536
    motion:
      mask:
        - 1388,57,1390,128,1982,120,1972,63
        - 0,973,253,1222,503,1408,619,1358,873,1536,1057,1235,1175,1082,1041,931,1220,924,1334,694,1222,623,1076,671,962,743,615,549,870,457,724,252,345,93,65,320,126,449,0,577
        - 1208,1536,1162,1416,1297,1348,1480,1326,1525,1058,1525,901,1362,781,1483,707,1401,472,1299,377,1161,373,991,181,1052,196,1254,78,1580,147,1575,0,1861,0,1914,551,1744,1536
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: True
      events:
        retain:
          default: 2

go2rtc:
  streams:
    backyard:
      - rtsp://u:p@192.168.0.198:554/cam/realmonitor?channel=1&subtype=0

ui:
  strftime_fmt: "%Y/%m/%d %H:%M"
```

### Relevant log output

```shell
2023-11-21 13:13:05.506749421  [INFO] Starting Frigate...
2023-11-21 13:13:06.566854052  [2023-11-21 13:13:06] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-21 13:13:06.589856904  [2023-11-21 13:13:06] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-11-21 13:13:06.594353848  [2023-11-21 13:13:06] peewee_migrate                 INFO    : Starting migrations
2023-11-21 13:13:06.599395401  [2023-11-21 13:13:06] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-21 13:13:06.617008142  [2023-11-21 13:13:06] detector.ov                    INFO    : Starting detection process: 290
2023-11-21 13:13:06.621880751  [2023-11-21 13:13:06] frigate.app                    INFO    : Output process started: 292
2023-11-21 13:13:06.639794363  [2023-11-21 13:13:06] frigate.app                    INFO    : Camera processor started for backyard: 296
2023-11-21 13:13:06.646253933  [2023-11-21 13:13:06] frigate.app                    INFO    : Capture process started for backyard: 297
2023-11-21 13:13:07.287274102  [2023-11-21 13:13:07] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-11-21 13:13:07.287279288  [2023-11-21 13:13:07] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-11-21 13:13:07.287284562  [2023-11-21 13:13:07] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### Frigate stats

```json
{"backyard":{"camera_fps":5.0,"capture_pid":296,"detection_enabled":1,"detection_fps":9.9,"ffmpeg_pid":303,"pid":294,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"4.3"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"2.7","mem":"1.5"},"118":{"cpu":"0.0","mem":"0.1"},"133":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"0.5"},"287":{"cpu":"0.0","mem":"0.1"},"288":{"cpu":"20.3","mem":"3.0"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.7","mem":"0.6"},"293":{"cpu":"0.0","mem":"0.3"},"294":{"cpu":"11.7","mem":"0.8"},"295":{"cpu":"0.0","mem":"0.1"},"296":{"cpu":"6.3","mem":"0.6"},"30":{"cpu":"0.0","mem":"0.0"},"303":{"cpu":"15.7","mem":"0.7"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"3920":{"cpu":"0.0","mem":"0.0"},"3933":{"cpu":"0.0","mem":"0.0"},"3939":{"cpu":"0.0","mem":"0.0"},"3942":{"cpu":"0.3","mem":"0.0"},"3943":{"cpu":"9.3","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"13781.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":9.9,"detectors":{"ov":{"detection_start":0.0,"inference_speed":16.03,"pid":288}},"gpu_usages":{"intel-vaapi":{"gpu":"10.61 %","mem":"- %"}},"service":{"last_updated":1700598528,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":95.2,"mount_type":"tmpfs","total":100.7,"used":5.4},"/media/frigate/clips":{"free":460084.4,"mount_type":"ext4","total":501386.0,"used":15757.4},"/media/frigate/recordings":{"free":460084.4,"mount_type":"ext4","total":501386.0,"used":15757.4},"/tmp/cache":{"free":983.0,"mount_type":"tmpfs","total":1000.0,"used":17.0}},"temperatures":{},"uptime":3773,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
