### ISSUE TITLE
Birdseye Configure "Motion within the last 30 seconds"

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#8715]
### Describe the problem you are having

I like the Birdseye feature and especially its ability to re Stream it out as RTSP (amazing!)  However I'm not seeing where we can change the 30 seconds part of the of the birdseye modes.  (or if that 30sec part is even configurable)
from the docs:
```
Birdseye Modes:
    continuous: All cameras are always included
    motion: Cameras that have detected motion within the **last 30 seconds** are included
    objects: Cameras that have tracked an **active object within the last 30 seconds are included**``
```

**I would like to change that 30 seconds to 15 seconds or something different.**

if this is possible please let me know where (i have searched docs and web) -  and I make / push an addition to the Frigate Docs / Documentation. 
Or if it's not Available - I think this would be a great feature / feature request for the future.
Thanks

### Version

0.13.0-500d369

### Frigate config file

```yaml
mqtt:
  enabled: false
  #host: mqtt.server.com
cameras:
  XX-Front:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@192.168.2.174:554/axis-media/media.amp
        #- path: rtsp://view:view@r.XX.com:11554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

  XX-Back:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@XX.XX.com:2554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

  XX-Courtyard:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:xx@myIP:5554/live/99F4247B-5009-492A-A12A-1191F1FC64D1
        #- path: rtsp://view:view@r.XX.com:11554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

  XX-FrontRight:
    enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://view:xx@myIP:5554/live/A0EFE674-10FA-4E35-A321-814220E7147C
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 720
      height: 1280

  XX-Driveway:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@192.168.2.30:554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      filters:
        motion:
          mask:
          - 464,302,618,0,0,0,0,609,0,809

    motion:
      mask:
      - 0,343,0,0,197,0,432,61,0,603
  XX-Carriage:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:xx@myIP:5554/live/FEE3A857-B88E-4B58-8E95-AB09F008E053
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      filters:
        motion:
          mask:
          - 116,469,324,339,293,276,324,287,307,211,307,107,462,64,340,0,37,105
      track:
      - person

  XX-Pool:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:xx@myIP:5554/live/5A3587EA-802B-4765-B433-A9A24DDE8FB8
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

  XX-2ndFloor:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:xx@myIP:5554/live/09521127-A72C-4683-A8D9-XX326A12DD7
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 720
      height: 1280

  XX-Door:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:xx@myIP:5554/live/44E21C65-21A7-49BB-BB13-C0BCF02F0A2C
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 960
    objects:
      filters:
        motion:
          mask:
          - 116,469,324,339,293,276,324,287,307,211,307,107,462,64,340,0,37,105
      track:
      - person

  XX-Hallway:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@c.XX.com:554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 720
      height: 1280

  XX-Mid:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@b.XX.com:3554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

  XX-Carriage:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@b.XX.com:55554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

    motion:
      mask:
      - 55,0,262,0,313,78,57,163
  630-CourtYard:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@s.XX.com:554/axis-media/media.amp
        roles:
        - detect
        - record
    detect:
      enabled: true
      width: 1280
      height: 720

#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 3
#    model:
#      path: "/custom_model.tflite"

detectors:
  coral:
    type: edgetpu
    device: usb

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
# XX- this is aval in webGUI - OR MORE IMPORTANT via RTSP at:
#
#   rtsp://172.17.195.51:8554/birdseye 
#   rtsp://p.XX.com:8554/birdseye     (i have NAT to force LOCAL Devs 
#       using XX ATT pubIP to redirect to correct 172.17.195 ip on 8554)
#
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

  # Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
  - person
  - car
  - bicycle
#    - cat
#    - dog
#    - hat

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: true
  quality: 90

timestamp_style:
  position: bl
  effect: solid

logger:
  logs:
    frigate.record.maintainer: debug

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 21
#      mode: active_objects
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Axis
