### ISSUE TITLE
Motion/Object Mask not working

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#8719]
### Describe the problem you are having

Object (or at least car) detection is not respecting masks, this and all prior versions I have used:
![image](https://github.com/blakeblackshear/frigate/assets/5632034/76c2deef-fc00-4990-b78a-f4c7c96a4409)
![image](https://github.com/blakeblackshear/frigate/assets/5632034/5662915e-8cb1-4dd4-9e46-8741e4b711af)
![image](https://github.com/blakeblackshear/frigate/assets/5632034/a5042b84-0707-4d03-baee-a64ac4befd13)

### Version

ghcr.io/blakeblackshear/frigate:0.13.0-beta5

### Frigate config file

```yaml
FrontHigha:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/front-higha
              roles:
                - detect
                - record
        detect:
          width: 4608
          height: 1728
          fps: 10
        objects:
          track:
            - person
            - car
          filters:
            car:
              mask:
                - 0,512,0,1728,4108,1728,4257,1509,3443,842,2650,378,1976,161
            person:
              mask: 
                - 0,512,0,1728,4108,1728,4257,1509,3443,842,2650,378,1976,161
        motion:
          threshold: 60
          contour_area: 50
          mask:
            - 0,512,0,1728,4108,1728,4257,1509,3443,842,2650,378,1976,161
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

All

### Any other information that may be helpful

Has never worked - not specific to this beta/release
