### ISSUE TITLE
[Config Support]: Ability to use TensorRT alongside EdgeTPU

### ISSUE THREAD

**Issue by mLupine** [blakeblackshear/frigate#8721]
### Describe the problem you are having

The problem with the current configuration file is that while it does allow multiple detectors of different types to be specified at the same time, only one model can be selected. This might be fine for multiple detectors of the same type (multiple Corals or GPUs), but does not work at all if we want to use two models for two different devices. I believe the simplest solution would be to move the model configuration to the detector-specific settings.

### Version

0.13.0-dev

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0
  coral:
    type: edgetpu
    device: usb

model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

# Could become:

detectors:
  tensorrt:
    type: tensorrt
    device: 0
    model:
      path: /config/model_cache/tensorrt/yolov7x-640.trt
      input_tensor: nchw
      input_pixel_format: rgb
      width: 640
      height: 640
  coral:
    type: edgetpu
    device: usb
    model:
      path: /edgetpu_model.tflite
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
