### ISSUE TITLE
[Support]: Which "percent" is correct for detection - the snapshot or the Events UI?

### ISSUE THREAD

**Issue by AlasdairH** [blakeblackshear/frigate#8724]
### Describe the problem you are having

In the UI, there are two different "percent" values for a false positive detection I'm seeing with Frigate+. Which one should I base by adjust by threshholds? The Events page is reading 75% while the snapshot says 51%.
![image](https://github.com/blakeblackshear/frigate/assets/8287753/9dc1589a-10ac-437f-8ac2-318b7e7278bf)

### Version

0.13.0-AA93D4F

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: x.x.x.x
  # Optional: port (default: shown below)
  port: xxxx

detect:
  enabled: True

rtmp:
  enabled: False

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    porch: 
      - "ffmpeg:http://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password=#video=copy#audio=copy#audio=opus"
    porch_sub: 
      - "ffmpeg:http://x.x.x.x/flv?port=xxxx&app=bcs&stream=channel0_ext.bcs&user=&password="
    garden: 
      - "ffmpeg:http://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password=#video=copy#audio=copy#audio=opus"
    garden_sub: 
      - "ffmpeg:http://x.x.x.x/flv?port=xxxx&app=bcs&stream=channel0_ext.bcs&user=&password="

cameras:
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      filters:
        car:
          mask:
            - 1026,0,1249,0,1247,69,1147,106,1058,83,978,69
      track:
        - person
        - car
        - cat
        - dog
        - deer
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 10
        post_capture: 5
        objects:
          - person
          - car
          - cat
          - dog
          - deer
        retain:
          default: 3
          mode: active_objects
          objects:
            car: 1
    snapshots:
      enabled: True
    zones:
      in_garden:
        coordinates: 0,720,1106,720,1162,245,796,198,515,309,0,558
      out_garden:
        coordinates: 483,327,792,203,1156,249,1134,445,1037,720,1280,720,1280,0,0,0,0,556
    motion:
      mask:
        - 0,720,541,720,543,671,0,670
      contour_area: 15
  porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porch_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    objects:
      filters:
        car:
          mask:
            - 515,301,593,315,600,372,552,368,557,418,448,469,342,572,0,527,0,259,134,289
            - 823,720,0,720,0,502,267,456,473,465,601,478,802,490,817,574
            - 989,338,992,364,872,360,867,341
        person:
          mask:
            - 619,343,634,343,630,384,616,383
      track:
        - person
        - bicycle
        - car
        - cat
        - dog
        - deer
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 10
        post_capture: 5
        objects:
          - person
          - bicycle
          - car
          - cat
          - dog
          - deer
        retain:
          default: 3
          mode: active_objects
          objects:
            car: 1
    snapshots:
      enabled: True
    zones:
      driveway:
        coordinates: 823,720,0,720,0,502,267,456,473,465,601,478,802,490,817,574
      driveway_entrance:
        coordinates: 562,430,670,433,622,488,481,473,308,450,389,437
      path:
        coordinates: 771,456,727,720,310,720,635,447
    motion:
      mask:
        - 1280,720,954,720,958,688,965,624,1011,551,1063,436,1133,411,1280,399
        - 0,720,558,720,543,664,0,661
        - 0,0,0,267,99,265,139,300,169,313,219,298,272,272,308,295,343,273,379,276,454,292,514,291,548,325,580,326,644,316,714,327,759,321,780,305,831,298,899,305,942,329,1016,338,1117,291,1103,160,1011,0
        - 944,720,881,563,816,440,755,441,675,720
      # Increasing this value will make motion detection less sensitive and decreasing it will make
      # motion detection more sensitive.
      # Default: 25
      threshold: 25
      # Optional: Minimum size in pixels in the resized motion image that counts as motion
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing
      # will make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # Default: 30
      contour_area: 15
      # Higher values mean the current frame impacts the delta a lot, and a single raindrop may
      # register as motion. Too low and a fast moving person wont be detected as motion.
      # Default: 0.2
      delta_alpha: 0.4

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://<id>
```

### Relevant log output

```shell
Nothing relevant.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":672,"width":896}]}}]
```

### Frigate stats

```json
{"cameras":{"garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":327,"detection_enabled":1,"detection_fps":3.1,"ffmpeg_pid":10213,"pid":324,"process_fps":10.1,"skipped_fps":0.0},"porch":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":331,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":337,"pid":326,"process_fps":10.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package//s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package//s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package//s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package//s6/command/s6-ipcserverd -1 -- /package//s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package//s6/command/s6-sudod -t 30000 -- /package//s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"6.1","cpu_average":"9","mem":"0.4"},"100":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"102":{"cmdline":"python3 -u -m frigate","cpu":"7.8","cpu_average":"10","mem":"4.5"},"117":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"141":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.5"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.5"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.5"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.5"},"157":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"294":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.0"},"296":{"cmdline":"frigate.recording_manager","cpu":"7.8","cpu_average":"3","mem":"1.8"},"304":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.6","cpu_average":"0","mem":"0.1"},"305":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"5","mem":"1.3"},"307":{"cmdline":"frigate.output       ","cpu":"2.2","cpu_average":"3","mem":"1.2"},"313":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"315":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"324":{"cmdline":"frigate.process:garden","cpu":"6.1","cpu_average":"24","mem":"1.4"},"326":{"cmdline":"frigate.process:porch","cpu":"7.2","cpu_average":"15","mem":"1.4"},"327":{"cmdline":"frigate.capture:garden","cpu":"5.6","cpu_average":"9","mem":"1.3"},"331":{"cmdline":"frigate.capture:porch","cpu":"6.1","cpu_average":"10","mem":"1.3"},"337":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/porch_sub?video=copy -r 10 -vf fps=10,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.1","cpu_average":"8","mem":"0.4"},"339":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.226/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=&password= -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/bed156f8e43201545c52e67ae647e576","cpu":"0.0","cpu_average":"0","mem":"0.3"},"343":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.224/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=&password= -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/698bee9a57b371b9371a4d8a5e07ccb0","cpu":"1.1","cpu_average":"1","mem":"0.3"},"344":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/porch?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/porch@%Y%m%d%H%M%S%z.mp4","cpu":"1.7","cpu_average":"2","mem":"0.3"},"350":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.226/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password= -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/94c754ff80365be1d57f61fa66a1832c","cpu":"0.0","cpu_average":"2","mem":"0.4"},"351":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.224/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password= -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/57e6061585dc254ed3b1053e63c02b7d","cpu":"3.9","cpu_average":"7","mem":"0.3"},"10213":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_sub?video=copy -r 10 -vf fps=10,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.6","cpu_average":"8","mem":"0.4"},"10215":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.226/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=&password= -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/bed156f8e43201545c52e67ae647e576","cpu":"1.1","cpu_average":"2","mem":"0.3"},"10216":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-aa93d4f -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4","cpu":"2.8","cpu_average":"3","mem":"0.3"},"10217":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.226/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=&password= -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/94c754ff80365be1d57f61fa66a1832c","cpu":"6.1","cpu_average":"8","mem":"0.4"},"27441":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":3.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":23.15,"pid":305}},"gpu_usages":{"intel-vaapi":{"gpu":"1.99%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":294},"recording":{"pid":296}},"service":{"last_updated":1700735641,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":57.7,"mount_type":"tmpfs","total":64.0,"used":6.3},"/media/frigate/clips":{"free":355062.1,"mount_type":"ext4","total":468355.7,"used":89430.7},"/media/frigate/recordings":{"free":355062.1,"mount_type":"ext4","total":468355.7,"used":89430.7},"/tmp/cache":{"free":81297.7,"mount_type":"overlay","total":119110.6,"used":31717.3}},"temperatures":{},"uptime":9421,"version":"0.13.0-aa93d4f"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink
