### ISSUE TITLE
[Config Support]: Error occurred when starting Frigate through Docker on Synology NAS with DSM 7.

### ISSUE THREAD

**Issue by MarsYear** [blakeblackshear/frigate#8732]
### Describe the problem you are having

I encountered a 'keyError' :rtsp when trying to start Frigate through Docker on Synology NAS. I have checked my RTSP stream, and it plays fine locally using VLC.

### Version

0.12.0

### Frigate config file

```yaml
detectors:
  coral:
    type: cpu
    
mqtt:
  host: 192.168.5.22
  port: 1883
  user: user
  password: pass

cameras:
  fristcamera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.5.28:554/h264/ch1/main/av_stream
          roles:
            - detect

    rtmp:
      enabled: False

    detect:
      enabled: True
      stationary:
        interval: 10
        threshold: 10

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 30000000
      min_score: 0.65
      mask: 690,131,638,285,483,261,569,110
      
motion:
  threshold: 10
  improve_contrast: True
```

### Relevant log output

```shell
KeyError: 'rtsp'
self.rtsp_url = get_rtsp_url(self.config['rtsp'])
File "/opt/frigate/frigate/video.py", line 135, in __init__
cameras[name] = Camera(name, config, prepped_frame_queue, client, MQTT_TOPIC_PREFIX)
File "detect_objects.py", line 44, in main
main()
File "detect_objects.py", line 90, in <module>
Traceback (most recent call last):
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)
