### ISSUE TITLE
[Config Support]: Cannot get 2 way audio to work

### ISSUE THREAD

**Issue by Menz01** [blakeblackshear/frigate#8739]
### Describe the problem you are having

i have tried countless different config that were suggested here and i just cannot get 2 way audio to work with my ReoLink Video Doorbell WiFi edition. the more configs i try the more unstable it gets

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.203
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: (password)
  stats_interval: 300
ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy 
go2rtc:
  #...
  # THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
  #...
  streams:
    frontdoor-audio: 
      - "ffmpeg:http://192.168.0.139/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=(user)&password=(password)#video=copy#audio=copy#audio=opus#raw= -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000"
      - rtsp://(user):(password)@192.168.0.139:554/h264Preview_01_main #This rtsp stream is included to enable 2-way audio
    frontdoor-sub: 
      - "ffmpeg:http://192.168.0.139/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=(user)&password=(password)#video=copy#audio=copy#audio=opus#raw= -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000"
    backyard_cam:
      - rtsp://192.168.0.206:8554/backyard-cam
    spikey_cam:
      - rtsp://192.168.0.206:8554/spikey-cam
    mike_s_office_cam:
      - rtsp://192.168.0.206:8554/mikes-office-cam
    rear_doorbell_cam:
      - rtsp://192.168.0.203:9550/T8210P002024093B
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor-audio?video=all&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor-sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy      
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    #snapshots:
      #enabled: true
      #timestamp: false
      #bounding_box: true    
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      retain:
        days: 0
        mode: all
    zones:
      driveway_enter:
        coordinates: 1636,794,1666,759,1226,735,1162,743
      driveway_main:
        coordinates: 1121,746,1638,801,1368,1156,588,910,632,798   
  backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_cam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - bear
    #snapshots:
      #enabled: true
      #timestamp: false
      #bounding_box: true    
    detect:
      width: 1920
      height: 1080
    record:
      enabled: True
      retain:
        days: 0
        mode: all      
detectors:
    cpu1:
      type: cpu
      num_threads: 3
    cpu2:
      type: cpu
      num_threads: 3  
snapshots:
      enabled: true
      timestamp: false
      bounding_box: true       
birdseye:
  enabled: True
  restream: False
  width: 1280 
  height: 720
  quality: 8
  mode: motion 
telemetry:
  version_check: True
```

### Relevant log output

```shell
2023-11-24 18:16:47.807460469  [2023-11-24 18:16:47] ffmpeg.frontdoor.record        ERROR   : rtsp://127.0.0.1:8554/frontdoor-audio?video=all&audio=aac: Connection timed out
2023-11-24 18:16:47.808357165  [2023-11-24 18:16:47] watchdog.frontdoor             INFO    : Terminating the existing ffmpeg process...
2023-11-24 18:16:47.815375239  [2023-11-24 18:16:47] watchdog.frontdoor             INFO    : Waiting for ffmpeg to exit gracefully...
2023-11-24 18:16:50.124639408  [2023-11-24 18:16:50] frigate.video                  ERROR   : frontdoor: Unable to read frames from ffmpeg process.
2023-11-24 18:16:50.125248383  [2023-11-24 18:16:50] frigate.video                  ERROR   : frontdoor: ffmpeg process is not running. exiting capture thread...
2023-11-24 18:16:57.822521676  [2023-11-24 18:16:57] watchdog.frontdoor             ERROR   : Ffmpeg process crashed unexpectedly for frontdoor.
2023-11-24 18:16:57.822845559  [2023-11-24 18:16:57] watchdog.frontdoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-24 18:16:57.823191131  [2023-11-24 18:16:57] ffmpeg.frontdoor.detect        ERROR   : rtsp://127.0.0.1:8554/frontdoor-sub?video=copy&audio=aac: Connection timed out
2023-11-24 18:16:57.823196917  [2023-11-24 18:16:57] ffmpeg.frontdoor.detect        ERROR   :     Last message repeated 1 times
2023-11-24 18:16:57.847526867  [2023-11-24 18:16:57] ffmpeg.frontdoor.record        ERROR   : rtsp://127.0.0.1:8554/frontdoor-audio?video=all&audio=aac: Invalid data found when processing input
2023-11-24 18:16:57.847534889  [2023-11-24 18:16:57] watchdog.frontdoor             INFO    : Terminating the existing ffmpeg process...
2023-11-24 18:16:57.847538183  [2023-11-24 18:16:57] watchdog.frontdoor             INFO    : Waiting for ffmpeg to exit gracefully...
2023-11-24 18:17:02.954550275  [2023-11-24 18:17:02] frigate.video                  ERROR   : frontdoor: Unable to read frames from ffmpeg process.
2023-11-24 18:17:02.954813745  [2023-11-24 18:17:02] frigate.video                  ERROR   : frontdoor: ffmpeg process is not running. exiting capture thread...
2023-11-24 18:17:07.858496446  [2023-11-24 18:17:07] watchdog.frontdoor             ERROR   : Ffmpeg process crashed unexpectedly for frontdoor.
2023-11-24 18:17:07.858505461  [2023-11-24 18:17:07] watchdog.frontdoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-24 18:17:07.858509761  [2023-11-24 18:17:07] ffmpeg.frontdoor.detect        ERROR   : rtsp://127.0.0.1:8554/frontdoor-sub?video=copy&audio=aac: Invalid data found when processing input
2023-11-24 18:17:07.879322385  [2023-11-24 18:17:07] ffmpeg.frontdoor.record        ERROR   : rtsp://127.0.0.1:8554/frontdoor-audio?video=all&audio=aac: Invalid data found when processing input
2023-11-24 18:17:07.884496240  [2023-11-24 18:17:07] watchdog.frontdoor             INFO    : Terminating the existing ffmpeg process...
2023-11-24 18:17:07.884503951  [2023-11-24 18:17:07] watchdog.frontdoor             INFO    : Waiting for ffmpeg to exit gracefully...
```

### Frigate stats

```json
{
    "backyard_cam": {
        "camera_fps": 5.1,
        "capture_pid": 231,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 241,
        "pid": 227,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "17": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "44": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "90": {
            "cpu": "1.7",
            "mem": "0.4"
        },
        "109": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "111": {
            "cpu": "3.0",
            "mem": "3.7"
        },
        "117": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "125": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "127": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "210": {
            "cpu": "0.0",
            "mem": "1.0"
        },
        "216": {
            "cpu": "0.3",
            "mem": "0.1"
        },
        "217": {
            "cpu": "0.0",
            "mem": "1.3"
        },
        "218": {
            "cpu": "0.0",
            "mem": "1.3"
        },
        "220": {
            "cpu": "1.0",
            "mem": "1.2"
        },
        "224": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "225": {
            "cpu": "0.7",
            "mem": "1.2"
        },
        "226": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "227": {
            "cpu": "1.0",
            "mem": "1.2"
        },
        "228": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "229": {
            "cpu": "1.3",
            "mem": "1.1"
        },
        "231": {
            "cpu": "5.3",
            "mem": "1.1"
        },
        "241": {
            "cpu": "16.3",
            "mem": "0.7"
        },
        "245": {
            "cpu": "0.0",
            "mem": "0.3"
        },
        "247": {
            "cpu": "0.0",
            "mem": "0.4"
        },
        "522": {
            "cpu": "15.9",
            "mem": "0.4"
        },
        "524": {
            "cpu": "1.0",
            "mem": "0.3"
        },
        "525": {
            "cpu": "2.7",
            "mem": "0.3"
        },
        "526": {
            "cpu": "3.0",
            "mem": "0.4"
        },
        "1273": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "1293": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "1297": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.2"
        },
        "MiB": {
            "cpu": "6783.4",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top": {
            "cpu": "average:",
            "mem": "0.80,"
        }
    },
    "detection_fps": 0,
    "detectors": {
        "cpu1": {
            "detection_start": 0,
            "inference_speed": 264.24,
            "pid": 217
        },
        "cpu2": {
            "detection_start": 0,
            "inference_speed": 270.07,
            "pid": 218
        }
    },
    "frontdoor": {
        "camera_fps": 5.1,
        "capture_pid": 229,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 522,
        "pid": 225,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "service": {
        "last_updated": 1700868703,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 129.5,
                "mount_type": "tmpfs",
                "total": 134.2,
                "used": 4.8
            },
            "/media/frigate/clips": {
                "free": 23851.9,
                "mount_type": "ext4",
                "total": 37993.5,
                "used": 12178.7
            },
            "/media/frigate/recordings": {
                "free": 23851.9,
                "mount_type": "ext4",
                "total": 37993.5,
                "used": 12178.7
            },
            "/tmp/cache": {
                "free": 998.5,
                "mount_type": "tmpfs",
                "total": 1000,
                "used": 1.5
            }
        },
        "temperatures": {},
        "uptime": 1056,
        "version": "0.12.1-367d724"
    }
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

GO2RTC logs:
2023-11-24 18:15:36.461103881  18:15:36.460 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=rtsp://ha-user:Flex3210@192.168.0.139:554/h264Preview_01_main
2023-11-24 18:16:49.779898793  18:16:49.779 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 127.0.0.1:8554->127.0.0.1:38368: i/o timeout" url="ffmpeg:http://192.168.0.139/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=ha-user&password=Flex3210#video=copy#audio=copy#audio=opus#raw= -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000"
2023-11-24 18:16:55.933492311  18:16:55.933 WRN [rtsp] error="streams: exec: exit status 1, dial tcp 192.168.0.139:554: i/o timeout" stream=frontdoor-audio
