### ISSUE TITLE
[Config Support]: In go2rtc what is the relationship between appending #video or #audio to the rtsp url vs. having a separate line with "ffmpeg:back#video=h264"

### ISSUE THREAD

**Issue by thinkloop** [blakeblackshear/frigate#8748]
### Describe the problem you are having

In [the go2rtc documentation](https://docs.frigate.video/guides/configuring_go2rtc/) there are options to adjust audio and video like so:

```
go2rtc:
  streams:
    back:
      - rtsp://user:password@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:back#video=h264#audio=aac"
```

And in various comments there are suggestions to add #video and #audio to the urls themselves:

```
go2rtc:
  streams:
    back:
      - rtsp://user:password@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2#video=h264#audio=aac
```

What is the difference between the two?

### Version

n/a

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
