### ISSUE TITLE
[Camera Support]: regular config works, but go2rtc fails, with certain brand of camera

### ISSUE THREAD

**Issue by thinkloop** [blakeblackshear/frigate#8749]
### Describe the problem you are having

I have a few cameras from a certain off-brand that work when configured "normally" like so:

```
  porch_right: 
    ffmpeg:
      inputs:
        - path: rtsp://domain:554/stream0
          roles:
            - record
        - path: rtsp://domain/stream1
          roles:
            - detect    
```

However when I try to do the same in go2rtc like so:

```
go2rtc:
    porch_right:
      - rtsp://domain:554/stream0
    porch_right-sub:
      - rtsp://domain:554/stream1

  porch_right: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch_right
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porch_right-sub
          roles:
            - detect  
 ```

I get errors (included below). 

I tried re-encoding the go2rtc without any difference:

```
go2rtc:
    porch_right:
      - rtsp://domain:554/stream0
      - "ffmpeg:porch_right#video=h264#audio=aac"
    porch_right-sub:
      - rtsp://domain:554/stream1
      - "ffmpeg:porch_right#video=h264#audio=aac"
 ```

The camera config page looks like this:

![image](https://github.com/blakeblackshear/frigate/assets/118814/b61a6c6c-814c-41e3-9dc0-747deeec3df5)

Any idea why it would work with regular config but not with go2rtc?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
(included in main description)
```

### Relevant log output

```shell
frigate    | 2023-11-26 05:16:43.338366824  [2023-11-26 05:16:43] watchdog.porch_right           ERROR   : Ffmpeg process crashed unexpectedly for porch_right.
frigate    | 2023-11-26 05:16:43.338405969  [2023-11-26 05:16:43] watchdog.porch_right           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2023-11-26 05:16:43.338434310  [2023-11-26 05:16:43] ffmpeg.porch_right.detect      ERROR   : [rtsp @ 0x55f5f2a3c6c0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate    | 2023-11-26 05:16:43.338458887  [2023-11-26 05:16:43] ffmpeg.porch_right.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
frigate    | 2023-11-26 05:16:43.338482061  [2023-11-26 05:16:43] ffmpeg.porch_right.detect      ERROR   : Output file #0 does not contain any stream
frigate    | 2023-11-26 05:16:43.343362848  [2023-11-26 05:16:43] watchdog.porch_right           ERROR   : No new recording segments were created for porch_right in the last 120s. restarting the ffmpeg record process...
frigate    | 2023-11-26 05:16:43.343429429  [2023-11-26 05:16:43] watchdog.porch_right           INFO    : Terminating the existing ffmpeg process...
frigate    | 2023-11-26 05:16:43.343464136  [2023-11-26 05:16:43] watchdog.porch_right           INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2023-11-26 05:16:43.589032474  05:16:43.588 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.26.0.3:36306->10.2.20.12:554: i/o timeout" url=rtsp://domain:554/stream0
frigate    | 2023-11-26 05:16:44.641784832  10.1.10.12 - - [26/Nov/2023:05:16:44 -0500] "GET /api/recordings/storage HTTP/1.1" 200 766 "http://nad.domain:5000/storage" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0" "-"
frigate    | 2023-11-26 05:16:48.419331324  05:16:48.419 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.26.0.3:36312->10.2.20.12:554: i/o timeout" url=rtsp://domain:554/stream1
frigate    | 2023-11-26 05:16:48.531667222  [2023-11-26 05:16:48] frigate.video                  ERROR   : porch_right: Unable to read frames from ffmpeg process.
frigate    | 2023-11-26 05:16:48.531875767  [2023-11-26 05:16:48] frigate.video                  ERROR   : porch_right: ffmpeg process is not running. exiting capture thread...
frigate    | 2023-11-26 05:16:51.037644833  [2023-11-26 05:16:51] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/porch_right-20231126051648.mp4
frigate    | 2023-11-26 05:16:53.561793534  05:16:53.561 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.26.0.3:38272->10.2.20.12:554: i/o timeout" url=rtsp://domain:554/stream0
```

### FFprobe output from your camera

```shell
fails to load anything
```

### Frigate stats

```json
"porch_right": {
        "camera_fps": 0,
        "capture_pid": 636,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 6822,
        "pid": 605,
        "process_fps": 0,
        "skipped_fps": 0
    },
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

chinese off-brand

**Comment by NickM-27** [comment]
```
go2rtc:
    porch_right:
      - rtsp://domain:554/stream0
      - "ffmpeg:porch_right#video=h264#audio=aac"
    porch_right-sub:
      - rtsp://domain:554/stream1
      - "ffmpeg:porch_right#video=h264#audio=aac"
```

does nothing because your stream is already h264 so go2rtc will send the original stream and not even run ffmpeg

if the above solution does not work then I would suggest

```
go2rtc:
    porch_right:
      - "ffmpeg:rtsp://domain:554/stream0"
    porch_right-sub:
      - "ffmpeg:rtsp://domain:554/stream1"
```
