### ISSUE TITLE
[Support]: Missing 20 mins of each hour under recording

### ISSUE THREAD

**Issue by superdong69** [blakeblackshear/frigate#8771]
### Describe the problem you are having

Since moving my recording directory from local HD to NAS, each hour of recording I have 00:00 to about 00:00:30 then it skips to 00:21 on all camera feeds. I haven't changed anything in my config, and maybe it's always done this and I never noticed before, perhaps something in my config I messed up? But I went to use it to scrub through a video today to see what happened on my property, and the 20 mins where the event happened ( guessing it was due to wind ) was missing.

### Version

frigate:0.13.0-beta4

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse
model:
  path: plus://<codehere>
mqtt:
  host: 192.168.1.80
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: pass
  stats_interval: 300
record:
  expire_interval: 10
go2rtc:
  streams:
    driveway:
      - rtsp://user:pass@192.168.1.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    driveway_sub:
      - rtsp://user:pass@192.168.1.95:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    garage_rear:
      - rtsp://user:pass@192.168.1.94:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garage_rear_sub:
      - rtsp://user:pass@192.168.1.94:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    house_front:
      - rtsp://user:pass@192.168.1.93:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    house_front_sub:
      - rtsp://user:pass@192.168.1.93:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    house_side:
      - rtsp://user:pass@192.168.1.90:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    house_side_sub:
      - rtsp://user:pass@192.168.1.90:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    house_back1:
      - rtsp://user:pass@192.168.1.91:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    house_back1_sub:
      - rtsp://user:pass@192.168.1.91:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
    garage_side:
      - rtsp://user:pass@192.168.1.92:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garage_side_sub:
      - rtsp://user:pass@192.168.1.92:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
  webrtc:
    candidates:
      - 192.168.1.79:8555
      - stun:8555
timestamp_style:
  position: tr
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
objects:
  track:
    - face
    - person
    - dog
    - car
    - ups
    - fedex
    - amazon
    - package
  filters:
    face:
      min_score: 0.7
      threshold: 0.9
    dog:
      min_score: 0.7
      threshold: 0.9
    person:
      min_score: 0.7
      threshold: 0.9
    car:
      min_score: 0.6
      threshold: 0.8
    ups:
      min_score: 0.7
      threshold: 0.9
    fedex:
      min_score: 0.7
      threshold: 0.9
    amazon:
      min_score: 0.7
      threshold: 0.9
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_driveway
        - monitor_car_detect
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_driveway:
        coordinates: 0,504,101,428,239,357,333,310,442,259,536,201,571,162,644,99,693,88,747,75,800,69,930,53,1046,59,1160,59,1305,61,1381,68,1409,68,1431,96,1513,99,1582,109,1649,119,1700,128,1760,138,1833,164,1920,200,1920,1080,0,1080
        objects:
          - face
          - car
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_car_detect:
        coordinates: 1497,306,579,226,768,100,1018,93
        objects:
          - face
          - car
          - fedex
          - ups
          - amazon
          - person
          - dog
    motion:
      mask:
        - 1846,34,1851,84,1440,83,1440,40
        - 0,0,453,0,470,122,0,396
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_driveway
          - monitor_car_detect
        pre_capture: 5
        post_capture: 15
  house_front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/house_front
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_house_front
        - monitor_car_detect
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_house_front:
        coordinates: 0,210,45,201,105,182,193,147,320,112,410,95,574,69,738,45,928,21,1038,21,1147,21,1242,40,1391,83,1559,141,1758,235,1920,333,1920,1080,0,1080
        objects:
          - face
          - car
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_car_detect:
        coordinates: 1229,70,649,117,465,156,376,94,546,71,695,45,885,21,1013,21
        objects:
          - face
          - car
          - fedex
          - ups
          - amazon
          - person
          - dog
    motion:
      mask:
        - 1853,40,1858,86,1440,87,1442,39
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_house_front
          - monitor_car_detect
        pre_capture: 5
        post_capture: 15
  garage_rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage_rear
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - face
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_garage_rear
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_garage_rear:
        coordinates:  0,1080,1691,1080,1756,908,1920,826,1920,403,1899,367,1872,334,1788,264,1680,228,1642,224,1198,159,1140,108,1101,57,1082,26,1019,21,843,0,565,0,405,25,214,83,0,175
        objects:
          - face
          - person
          - dog
    motion:
      mask:
        - 1716,923,1920,783,1920,1080,1619,1080
        - 1436,80,1845,83,1845,34,1439,38
        - 0,1080,122,1080,0,911
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_garage_rear
        pre_capture: 5
        post_capture: 15
  house_side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/house_side
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_house_side
        - monitor_house_side_dog
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_house_side:
        coordinates: 269,886,377,808,317,671,222,550,165,470,96,504,64,415,29,297,40,258,124,210,175,190,246,162,404,117,473,97,569,75,642,61,706,49,787,38,873,31,945,25,1019,23,1087,24,1154,26,1216,29,1279,38,1347,49,1408,64,1485,90,1566,115,1631,138,1730,171,1920,226,1920,424,1920,1080,398,1080
        objects:
          - face
          - person
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_house_side_dog:
        coordinates: 21,279,57,266,86,251,113,238,156,216,199,195,241,177,360,147,424,124,478,107,539,87,587,77,650,65,709,55,772,49,832,42,882,38,939,32,1005,24,1046,24,1094,23,1140,23,1195,24,1247,30,1359,46,1442,80,235,572,171,476,93,510
        objects:
          - face
          - dog
    motion:
      mask:
        - 1846,34,1851,84,1440,83,1440,40
        - 0,0,453,0,470,122,0,396
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_house_side_dog
          - monitor_house_side
        pre_capture: 5
        post_capture: 15
  house_back1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_back1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/house_back1
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_house_back1
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_house_back1:
        coordinates: 1613,1080,1920,725,1920,509,1830,454,1881,319,1817,279,1726,231,1637,200,1549,165,1455,128,1332,88,1263,65,1142,40,1055,27,963,21,890,21,807,21,715,21,637,25,539,36,467,33,355,64,196,80,0,127,0,1080
        objects:
          - face
          - person
    motion:
      mask:
        - 1846,34,1851,84,1440,83,1440,40
        - 0,0,453,0,470,122,0,396
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_house_back1
        pre_capture: 5
        post_capture: 15
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.80:8557/front-doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1296
      height: 1728
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_front_doorbell
        - monitor_doorstep
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_front_doorbell:
        coordinates: 0,1529,356,1417,469,1491,903,1623,1296,1670,1296,1347,1296,1074,1212,1065,1114,1059,1008,1049,886,1044,840,1043,772,1042,695,1039,542,1038,350,1041,0,1038
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_doorstep:
        coordinates: 0,1728,875,1728,941,1643,647,1560,406,1471,356,1480,292,1456,222,1492,57,1534,0,1549
        objects:
          - face
          - fedex
          - ups
          - amazon
          - person
          - dog
          - package
    motion:
      mask:
        - 1296,1728,1296,1674,922,1682,927,1728
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_doorstep
          - monitor_front_doorbell
        pre_capture: 5
        post_capture: 15
  back_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.80:8557/back_doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1296
      height: 1728
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_back_doorbell
        - monitor_back_doorstep
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_back_doorbell:
        coordinates: 66,1035,0,1036,0,1728,362,1728,318,1568,296,1485,334,1472,528,1438,915,1355,926,1006,837,1003,770,1009,651,1005,581,1010,475,1014,227,1027
        objects:
          - face
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
      monitor_back_doorstep:
        coordinates: 358,1728,1296,1728,1296,1548,1006,1463,957,1490,923,1474,872,1494,852,1473,764,1397,295,1486
        objects:
          - face
          - person
          - dog
    motion:
      mask:
        - 1296,1728,1296,1674,922,1682,927,1728
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_back_doorstep
          - monitor_back_doorbell
        pre_capture: 5
        post_capture: 15
  garage_side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage_side
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - monitor_garage_side
      crop: true
      height: 500
      retain:
        default: 5
    zones:
      monitor_garage_side:
        coordinates: 1920,1080,1920,177,1733,97,1493,21,1028,0,705,23,501,32,361,95,87,151,0,195,0,1080
        objects:
          - face
          - person
          - dog
        stationary:
          duration: 60
          filter:
            car: {}
    motion:
      mask:
        - 1844,43,1843,94,1450,87,1446,45
      threshold: 20
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - monitor_garage_side
        pre_capture: 5
        post_capture: 15

detectors:
  coral:
    type: edgetpu
    device: usb
rtmp:
  enabled: false
birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: continuous
live:
  height: 640
  quality: 1
```

### Relevant log output

```shell
Nothing
```

### FFprobe output from your camera

```shell
Nothing
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest
