### ISSUE TITLE
[Camera Support]: Two way audio only works off Wifi (Reolink POE Doorbell)

### ISSUE THREAD

**Issue by Pickman711** [blakeblackshear/frigate#8779]
### Describe the problem you are having

I have been struggling to get my two way audio to work on my new doorbell. I have frigate configured with a minimal setup to get started.

Frigate is installed on docker in my unraid machine and HA is on my dell mini pc. Frigate has no errors and seems to be working fine.

I can get the two way audio to work when my phone is off wifi and doesn't work when connected. It was to my surprise since I figured I would have the opposite issue of it not working away from home.

The frigate card has what I think is a broken microphone symbol on wifi and goes red and works off of wifi.
![card](https://github.com/blakeblackshear/frigate-hass-integration/assets/102765544/381f9f65-3278-48e6-b460-6836cce189e0)

Here is my frigate yaml and card configuration. I'd appreciate any insight, thanks in advance.
```
type: custom:frigate-card
cameras:
  - live_provider: go2rtc
    frigate: {}
    go2rtc:
      modes:
        - webrtc
    camera_entity: camera.doorbell
menu:
  style: overlay
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      type: toggle
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: true
    mute:
      enabled: true
live:
  microphone:
    always_connected: false
```

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.10.0.50
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: password
  stats_interval: 60

go2rtc:
  streams:
    doorbell:
      - rtsp://admin:password@10.10.30.13:554/h264Preview_01_main
      - ffmpeg:doorbell#audio=opus#audio=volume#audio=aac
    doorbell_sub:
      - rtsp://admin:password@10.10.30.13:554/h264Preview_01_sub
      - ffmpeg:doorbell_sub#audio=opus#audio=volume
  webrtc:
    candidates:
      - 10.10.0.100:8555
      - stun:8555
      
  ## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: doorbell_sub
      
    detect: 
      enabled: false
      width: 640
      height: 480
      fps: 5
    record:
      enabled: false
      retain: 
        days: 2 
        #mode: active_objects 
      events:
        retain:
          default: 5 
          mode: motion 
        pre_capture: 3 
        post_capture: 10
```

### Relevant log output

```shell
2023-11-28 08:18:29.071156278  [INFO] Starting Frigate...
2023-11-28 08:18:29.800562356  [2023-11-28 08:18:29] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-28 08:18:29.813324355  [2023-11-28 08:18:29] peewee_migrate                 INFO    : Starting migrations
2023-11-28 08:18:29.816285570  [2023-11-28 08:18:29] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-28 08:18:29.826602182  [2023-11-28 08:18:29] detector.cpu                   INFO    : Starting detection process: 431
2023-11-28 08:18:29.828925487  [2023-11-28 08:18:29] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-11-28 08:18:29.829421031  [2023-11-28 08:18:29] frigate.app                    INFO    : Output process started: 433
2023-11-28 08:18:29.834886336  [2023-11-28 08:18:29] frigate.app                    INFO    : Camera processor started for doorbell: 437
2023-11-28 08:18:29.839412289  [2023-11-28 08:18:29] frigate.app                    INFO    : Capture process started for doorbell: 438

2023-11-28 08:18:29.071397604  [INFO] Preparing go2rtc config...
2023-11-28 08:18:29.212041811  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-11-28 08:18:29.233440390  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-11-28 08:18:29.233443617  [INFO] Starting go2rtc...
2023-11-28 08:18:29.313962118  08:18:29.312 INF go2rtc version 1.7.1 linux/amd64
2023-11-28 08:18:29.313966439  08:18:29.313 INF [api] listen addr=0.0.0.0:1984
2023-11-28 08:18:29.313968119  08:18:29.313 INF [rtsp] listen addr=0.0.0.0:8554
2023-11-28 08:18:29.313972600  08:18:29.313 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-11-28 08:18:39.071342081  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Main Stream
***********

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:password@10.10.30.13:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 20 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
*********
Sub Stream
*********
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:password@10.10.30.13:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 10 fps, 10 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Doorbell POE
