### ISSUE TITLE
403 Forbidden interface only

### ISSUE THREAD

**Issue by leon-Glitchking** [blakeblackshear/frigate#878]
**Describe the bug**
I have been trying to get Frigate running on mu OMV server.
I seam to have it working (clips are saving) and my home assistant (running on another device) can interact with the docker.
the api seams to work (see output below) however whenever I try to load the interface I get back, 
       403 Forbidden
       nginx/1.18.0 (Ubuntu)

I have scoured the git issues and discussions as well as the documentation and tried everything that i could find that was even partially related. 
I believe I have granted all the permissions it requires.
is there something I'm missing as this is the first time I have used a docker 

Thank-you

**Version of frigate**
Output from `/api/version`
0.8.4-5043040

**Config file**
```
database:
  path: /clips/frigate.db

mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigateNAS
  client_id: frigate
  user: USER
  password: PASSWORD
  stats_interval: 60

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

cameras:
  door:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@192.168.1.6:554/ch01/1
          roles:
            - detect
            - rtmp
        - path: rtsp://USER:PASSWORD@192.168.1.6:554/ch01/0
          roles:
            - clips
            - record
    width: 352
    height: 288
    fps: 5
    motion:
      mask:
        - 0,288,54,288,124,128,90,72,0,75
    detect:
      enabled: True
      max_disappeared: 25
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 3
        objects:
          person: 3


  door2:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@192.168.1.6:554/ch02/1
          roles:
            - detect
            - rtmp
        - path: rtsp://USER:PASSWORD@192.168.1.6:554/ch02/0
          roles:
            - clips
            - record
    width: 352
    height: 288
    fps: 5
    motion:
      mask:
        - 352,288,204,241,239,119,223,56,255,38,270,102,352,108
    detect:
      enabled: True
      max_disappeared: 25
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 3
        objects:
          person: 3
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```
{
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 10.0, 
      "pid": 33
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 10.0, 
      "pid": 35
    }
  }, 
  "door": {
    "camera_fps": 5.2, 
    "capture_pid": 40, 
    "detection_fps": 0.0, 
    "pid": 38, 
    "process_fps": 5.2, 
    "skipped_fps": 0.0
  }, 
  "door2": {
    "camera_fps": 5.1, 
    "capture_pid": 41, 
    "detection_fps": 0.0, 
    "pid": 39, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 66.4, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 0.7
      }, 
      "/media/frigate/clips": {
        "free": 941680.2, 
        "mount_type": "ext4", 
        "total": 983429.8, 
        "used": 41732.8
      }, 
      "/media/frigate/recordings": {
        "free": 941680.2, 
        "mount_type": "ext4", 
        "total": 983429.8, 
        "used": 41732.8
      }, 
      "/tmp/cache": {
        "free": 116229.1, 
        "mount_type": "overlay", 
        "total": 117611.0, 
        "used": 1365.1
      }
    }, 
    "uptime": 26, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: OMV4
 - Install method: Addon
 - Virtualization: 
 - Coral Version: None
 - Network Setup: wired

**Additional context**
Container Detatails
```
[
    {
        "Id": "19f6f1a865975e3454d7433bee12e721034c211880411e979f03fd8823643f9c",
        "Created": "2021-03-06T00:09:13.2142588Z",
        "Path": "/run.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2111,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-03-06T01:46:23.454181919Z",
            "FinishedAt": "2021-03-06T01:46:15.836769418Z"
        },
        "Image": "sha256:2a4f9c0d53d15d186cfed68b50bbf1d557c6924b287708749ba739fc4b0edde3",
        "ResolvConfPath": "/srv/dev-disk-by-label-Vault/Docker_Portainer/containers/19f6f1a865975e3454d7433bee12e721034c211880411e979f03fd8823643f9c/resolv.conf",
        "HostnamePath": "/srv/dev-disk-by-label-Vault/Docker_Portainer/containers/19f6f1a865975e3454d7433bee12e721034c211880411e979f03fd8823643f9c/hostname",
        "HostsPath": "/srv/dev-disk-by-label-Vault/Docker_Portainer/containers/19f6f1a865975e3454d7433bee12e721034c211880411e979f03fd8823643f9c/hosts",
        "LogPath": "/srv/dev-disk-by-label-Vault/Docker_Portainer/containers/19f6f1a865975e3454d7433bee12e721034c211880411e979f03fd8823643f9c/19f6f1a865975e3454d7433bee12e721034c211880411e979f03fd8823643f9c-json.log",
        "Name": "/FrigateNVR",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/srv/dev-disk-by-label-StorageA/FrigateNVR:/clips:rw",
                "/dev/bus/usb:/dev/bus/usb:rw",
                "/srv/dev-disk-by-label-StorageA/FrigateNVR:/config:rw",
                "/srv/dev-disk-by-label-StorageA/FrigateNVR:/media/frigate:rw",
                "/srv/dev-disk-by-label-StorageA/FrigateNVR:/media:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "1935/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1935"
                    }
                ],
                "5000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5001"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1a992d3742896e4befb5106a02ab803a527230315b3d47cd4d4ca4b4164b49a5-init/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/fc7791065d6d842473e65a1714545fb49dbbf7747e5b073021b8a8c6a03d701e/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/c93d6f80781fa6dfe5690c36a4d844a782ddc0f5dd98630438cf300d1ba5ba19/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1b8497a73babfa32d08ec6868f6e9497fc4588508420675c33f2aa54cfe9a660/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/79bea52681b1882baeaa0322b888afcde9d9e1f3dbc2d8ffac5fc8b3796a2af8/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/cf2d7dbb606b23992614e47ddb1e564d693bd08a3adcbdc3bda6b53bdf03f297/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/c16aa69fe6cd5fd8943ca1044ed1cbe47059e7a9995b47b4d935f45deb6e2aca/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/31dc79160f84f64003d9b3f09f22936ed83b3d246e898fd5f813ce068c902464/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/30c3d28df77f782cdb7df1f9201522abd68e973f278720cf29550338e928ec3e/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1417efd96711e4ff4c1d1d5d859c98a9f991d26ddce6a952c13203c61f93d8d9/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/a21a4947706b5175d2ff1d26b6a8ebda0ef664dad6e7d4f1eadaa17922c9c0bf/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1d44ef153253114c43d7ab830e61383362d2d63cb134a7c1c37ea594165e4870/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/ec95661cae84c7ab46fdf74a436f7e15f0242931d82ccb74edb0f7351517620a/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/e09ce25f8f6b9d99323578e67df3d0717a46f0aa3f352b2308f445d3bc3c3798/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1046a358c0522071878551dc562a345e3bdf25baa9639283d031be63463108df/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/b68549a5251d87f73287251cb1dcb41ab43c71db780165aefde23e15a7a3fad0/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/4aab83644d042991ff27cace2930d848791f92a0122d002f728209b974a06848/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/13b64df128980da4711ffd69456c2a8ef17d95e7c5a7022c8e11d6065c5faade/diff:/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/5bc8699926597d350467d3e55641d2ac56835ba4a52f45787df4befaefee851f/diff",
                "MergedDir": "/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1a992d3742896e4befb5106a02ab803a527230315b3d47cd4d4ca4b4164b49a5/merged",
                "UpperDir": "/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1a992d3742896e4befb5106a02ab803a527230315b3d47cd4d4ca4b4164b49a5/diff",
                "WorkDir": "/srv/dev-disk-by-label-Vault/Docker_Portainer/overlay2/1a992d3742896e4befb5106a02ab803a527230315b3d47cd4d4ca4b4164b49a5/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/srv/dev-disk-by-label-StorageA/FrigateNVR",
                "Destination": "/clips",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/dev/bus/usb",
                "Destination": "/dev/bus/usb",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/srv/dev-disk-by-label-StorageA/FrigateNVR",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/srv/dev-disk-by-label-StorageA/FrigateNVR",
                "Destination": "/media/frigate",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/srv/dev-disk-by-label-StorageA/FrigateNVR",
                "Destination": "/media",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "rockpro64",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1935/tcp": {},
                "5000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "FLASK_ENV=development",
                "DEBIAN_FRONTEND=noninteractive",
                "FRIGATE_RTSP_PASSWORD="PASSWORD"",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/run.sh"
            ],
            "Image": "blakeblackshear/frigate:stable-armv7",
            "Volumes": null,
            "WorkingDir": "/opt/frigate",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "maintainer": "blakeb@blakeshome.com"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8085a831d210d4fe07ba1a96dc16a8ea99de294d670b371d796ca1241140ee90",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1935/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1935"
                    }
                ],
                "5000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5001"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/8085a831d210",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "da0afa9c5c0e279d9fb5f37fb70528eea1278b073608a7dea572312d649d237a",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d52d0a2b878f0908a9b015be63161e9a66e58cccbf76977b5845ccfb8784be0c",
                    "EndpointID": "da0afa9c5c0e279d9fb5f37fb70528eea1278b073608a7dea572312d649d237a",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```
