### ISSUE TITLE
[Config Support]: Do you know how to disable the best image? I just need record video!!!thanks

### ISSUE THREAD

**Issue by yuhuanfan** [blakeblackshear/frigate#8786]
### Describe the problem you are having

Do you know how to disable the best image? I just need record video!!!thanks  frigate10.1

### Version

10.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.157
  port: 1883
  user: ***************
  password: ********
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 2

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects

detectors:
  cpu1:
    type: cpu
    num_threads: 3

cameras:
  camera_1:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_mmal
      #input_args: -avoid_negative_ts auto -fflags nobuffer+genpts+discardcorrupt -flags low_delay -rtsp_transport tcp -use_wallclock_as_timestamps 1 -stimeout 5000000
      inputs:
        - path: rtsp://192.168.10.157:8554/rtmp
          roles:
            - record
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    rtmp:
      enabled: False
      
    detect:
      fps: 5


    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 30
        mode: active_objects
      events:
        pre_capture: 15
        post_capture: 10
    
    snapshots:
      enabled: True

    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 493,0,534,388,591,335,563,0
            - 1222,675,1226,699,913,699,914,676
            - 1280,0,1280,720,1007,720,1116,0
            - 315,720,148,720,0,307,0,0,458,0,490,260
          
    zones:
      1105:
        coordinates: 1280,720,1280,0,815,0,752,260,576,271,498,0,0,0,0,720
        objects:
          - person


      1103:
        coordinates: 766,0,548,0,574,266,782,257
        objects:
          - person

 

    timestamp_style:
      position: "bl"
      format: "%H:%M:%S"
      color:
        red: 255
        green: 255
        blue: 255

    motion:
      mask:
        - 1222,675,1226,699,913,699,914,676
        - 1280,0,1280,720,1007,720,1116,0
        - 315,720,148,720,0,307,0,0,458,0,490,260
```

### Relevant log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
