### ISSUE TITLE
[Support]: System > info not showing memory info.  

### ISSUE THREAD

**Issue by PatSloan** [blakeblackshear/frigate#8788]
### Describe the problem you are having

When navigating to the system menu page, I do not see a memory card that shows the /tmp/cahce etc..

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.2.6
  port: 1883 
go2rtc:
    streams:
      doorbell: 
        - rtsp://admin:PW@192.168.30.40:554/h264Preview_01_main
        - "ffmpeg:doorbell#audio=aac"
      doorbell_sub: 
        - rtsp://admin:PW@192.168.30.40:554/h264Preview_01_sub
      driveway: 
        - rtsp://camadmin:PW@192.168.30.41:554/stream1
        - "ffmpeg:driveway#audio=aac" 
      driveway_sub: 
        - rtsp://camadmin:PW@192.168.30.41:554/stream2
      porch: 
        - rtsp://camadmin:PW@192.168.30.42:554/stream1
        - "ffmpeg:porch#audio=aac" 
      porch_sub: 
        - rtsp://camadmin:PW@192.168.30.42:554/stream2
 #     camera1: tapo://CFHtqOK9%fgY39cU&@&14vglAaNOh*1c@192.168.30.41
    webrtc:
      candidates:
        - 192.168.2.6:8555
        - stun:8555
rtmp:
  enabled: false
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  mode: continuous
  width: 1600
  height: 1080
detect:
  enabled: True
  width: 640
  height: 480
  fps: 5
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 10  
objects:
  track:
    - person
    - car
    - bear
    - horse
    - dog
    - motorcycle
    - bicycle
    - umbrella
    - cow
    - sheep
    - truck
cameras:
  doorbell:
    enabled: true
    ffmpeg:
#      hwaccel_args: preset-intel-qsv-h264
      hwaccel_args: preset-vaapi
      output_args:
          record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
    zones:  
      front_door:
        coordinates: 591,276,599,235,640,231,640,297,567,480,179,480,147,313,205,292,336,293,433,275,495,279    
    motion:
      mask:    
        - 640,0,640,191,602,202,601,277,451,275,366,281,301,285,253,295,143,301,143,141,159,0
    record:
      enabled: True
      retain:
       days: 20
       mode: all
    snapshots:
      enabled: True
    live:
      stream_name: doorbell
  driveway:
    enabled: true
    ffmpeg:
#      hwaccel_args: preset-intel-qsv-h264
      output_args:
          record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    zones:  
      drive_way:
        coordinates: 640,165,640,360,154,360,0,360,0,265,144,159,283,96,391,109,513,118
    motion:
      mask:
        - 640,0,640,130,296,97,219,94,153,97,34,109,0,143,0,0
    record:
      enabled: True
      retain:
       days: 20
       mode: all
    snapshots:
      enabled: True            
    live:
      stream_name: driveway
  porch:
    enabled: true
    ffmpeg:
#      hwaccel_args: preset-intel-qsv-h264
      output_args:
          record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/porch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    zones:
      patio:
        coordinates: 617,165,456,146,270,161,225,183,45,282,0,360,596,360       
    motion:
      mask:    
        - 601,0,601,101,435,94,321,132,224,183,0,305,0,0
    record:
      enabled: True
      retain:
       days: 20
       mode: all
    snapshots:
      enabled: True            
    live:
      stream_name: porch
detectors: 
  coral:
    type: edgetpu
    device: usb
# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: America/Los_angeles
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: false
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
 # time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: "%Y/%m/%d %H:%M"

# Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
 # height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
 # required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```

### Relevant log output

```shell
2023-11-29 08:02:43.762063568  [INFO] Starting Frigate...
2023-11-29 08:02:44.910232478  [2023-11-29 08:02:44] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-29 08:02:44.941312481  [2023-11-29 08:02:44] peewee_migrate                 INFO    : Starting migrations
2023-11-29 08:02:44.962911975  [2023-11-29 08:02:44] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-29 08:02:44.976144665  [2023-11-29 08:02:44] detector.coral                 INFO    : Starting detection process: 435
2023-11-29 08:02:44.978843389  [2023-11-29 08:02:44] frigate.app                    INFO    : Output process started: 437
2023-11-29 08:02:44.983641536  [2023-11-29 08:02:44] frigate.app                    INFO    : Camera processor started for doorbell: 443
2023-11-29 08:02:44.989382262  [2023-11-29 08:02:44] frigate.app                    INFO    : Camera processor started for driveway: 445
2023-11-29 08:02:44.995904405  [2023-11-29 08:02:44] frigate.app                    INFO    : Camera processor started for porch: 447
2023-11-29 08:02:45.001984395  [2023-11-29 08:02:45] frigate.app                    INFO    : Capture process started for doorbell: 448
2023-11-29 08:02:45.006679917  [2023-11-29 08:02:45] frigate.app                    INFO    : Capture process started for driveway: 451
2023-11-29 08:02:45.011067100  [2023-11-29 08:02:45] frigate.app                    INFO    : Capture process started for porch: 454
2023-11-29 08:02:48.175729015  [2023-11-29 08:02:44] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-11-29 08:02:48.178584970  [2023-11-29 08:02:48] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

tplink

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/19332597/7b3d6c63-76fd-4c6a-85aa-2fb8d3b50a4b)
