### ISSUE TITLE
ReoLink DUO 2 --weird issues with Frigate/Go2rtc  [Camera Support]: 

### ISSUE THREAD

**Issue by tiny-e** [blakeblackshear/frigate#8794]
### Describe the problem you are having

I've added a new ReoLink Duo 2 (poe version) to my setup.  Frigate sees the camera and seems to work as normal.  ** Until I view the camera from another device** .    Note I'm viewing the go2rtc restream in my other devices (VLC, TinyCam Monitor, or browser via go2rtc).

Then I lose video in the dashboard and I see this message in the logs:

```
2023-11-29 16:26:26.996794235  [2023-11-29 16:26:26] watchdog.3_driveway_cam        INFO    : 3_driveway_cam exceeded fps limit. Exiting ffmpeg...
2023-11-29 16:26:26.997241684  [2023-11-29 16:26:26] watchdog.3_driveway_cam        INFO    : Waiting for ffmpeg to exit gracefully...
```

I also noticed that frigate reports CPU usage and weird FPS rates for the camera as way higher than normal.
![image](https://github.com/blakeblackshear/frigate/assets/2148511/8ee7ae22-32ad-4f45-9e5d-f09128cd4db5)

![image](https://github.com/blakeblackshear/frigate/assets/2148511/2d6928e3-0aa3-4085-9e4d-24ef464c3a9e)

### Version

SYSTEM 0.12.1-367D724

### Frigate config file

```yaml
---

mqtt:
  host: 192.168.11.5
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

ffmpeg:
  hwaccel_args: preset-nvidia-h264
    #- skip_frame nokey
  input_args: preset-rtsp-restream-low-latency 
  output_args:
    record: preset-record-generic-audio-copy


##############################
go2rtc:
  streams:
    backyard_west_main:
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.141:554/h264Preview_01_main
      - http://192.168.11.141/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
      #- ffmpeg:reolink audio=opus
      - "ffmpeg:ofice#audio=aac"

    backyard_west_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.141:554/h264Preview_01_sub
      - "ffmpeg:ofice#audio=aac"


    backyard_east_main: 
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.141:554/h264Preview_02_main
      - http://192.168.11.141/flv?port=1935&app=bcs&stream=channel1_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
      - "ffmpeg:ofice#audio=aac"

      
    backyard_east_sub: 
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.141:554/h264Preview_02_sub
      - "ffmpeg:ofice#audio=aac"


   
    #test_3_driveway: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.140:554/stream0
      #- ffmpeg:-c:v:h264_nvenc
      #- ffmpeg:-preset:v:fast

    test_4_willowPTZ: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.178/live

    front_door_main:
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.141:554/h264Preview_01_main
      - http://192.168.11.143/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
      #- ffmpeg:reolink audio=opus
      - "ffmpeg:ofice#audio=aac"

    front_door_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.143:554/h264Preview_01_sub
      - "ffmpeg:ofice#audio=aac"

    driveway_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.142:554/h264Preview_01_main
      #- http://192.168.11.142/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
      #- ffmpeg:reolink audio=opus
      - "ffmpeg:ofice#audio=aac"

    driveway_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.142:554/h264Preview_01_sub
      - "ffmpeg:ofice#audio=aac"  
 
########################################


detectors:
  coral:
    type: edgetpu
    device: usb


birdseye:
  enabled: true
  mode: continuous
  restream: true


cameras:
  1_backyard_west:
    birdseye:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_west_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_west_sub?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect

       

    detect:  
      width: 640
      height: 360  
      fps: 4   

    motion:
      mask:
        - 0,142,44,138,118,103,384,107,407,124,499,98,571,110,592,95,640,90,640,0,229,0,0,0 

    record:
      enabled: true
      retain:
        days: 30
        mode: all
    objects:
      track:
        - person
        - car
        - dog
        - cat
    

  2_backyard_east:
    birdseye:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_east_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_east_sub?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect

    detect:  
      width: 640
      height: 360  
      fps: 4   

    motion:
      mask:
        - 193,78,226,96,283,111,296,133,352,134,385,113,509,173,640,195,640,0,0,0,0,74

    record:
      enabled: true
      retain:
        days: 30
        mode: all
    objects:
      track:
        - person
        - car
        - dog
        - cat
    


  3_driveway_cam:
    birdseye:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect

    detect:
      fps: 5
    motion:
        mask:
          - 0,389,281,259,392,209,581,284,725,243,948,289,1069,329,1280,344,1280,331,1280,83,1280,0,461,0,0,0,0,334


    record:
      enabled: true
      retain:
        days: 30
        mode: all
    objects:
      track:
        - person
        - car
        - dog
        - cat         

  4_Willow:
    birdseye:
      order: 4
    ffmpeg:
      output_args:
          record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.11.178/live
  
 
  5_front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect
```

### Relevant log output

```shell
2023-11-29 16:26:26.996794235  [2023-11-29 16:26:26] watchdog.3_driveway_cam        INFO    : 3_driveway_cam exceeded fps limit. Exiting ffmpeg...
2023-11-29 16:26:26.997241684  [2023-11-29 16:26:26] watchdog.3_driveway_cam        INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1536,"width":4096},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":576,"width":1536}]}}]
```

### Frigate stats

```json
{"1_backyard_west":{"camera_fps":4.1,"capture_pid":1889,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1896,"pid":1878,"process_fps":4.1,"skipped_fps":0.0},"2_backyard_east":{"camera_fps":4.0,"capture_pid":1893,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1899,"pid":1881,"process_fps":4.0,"skipped_fps":0.0},"3_driveway_cam":{"camera_fps":5.1,"capture_pid":1897,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1907,"pid":1882,"process_fps":5.1,"skipped_fps":0.0},"4_Willow":{"camera_fps":5.1,"capture_pid":1903,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1915,"pid":1886,"process_fps":5.1,"skipped_fps":0.0},"5_front_door":{"camera_fps":5.0,"capture_pid":1909,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":1920,"pid":1888,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.2"},"1":{"cpu":"0.0","mem":"0.0"},"1014":{"cpu":"0.0","mem":"0.0"},"1048":{"cpu":"0.0","mem":"0.0"},"1083":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.0"},"1119":{"cpu":"0.0","mem":"0.0"},"1157":{"cpu":"0.0","mem":"0.0"},"1189":{"cpu":"0.0","mem":"0.0"},"1218":{"cpu":"0.0","mem":"0.0"},"1254":{"cpu":"0.0","mem":"0.0"},"1291":{"cpu":"0.0","mem":"0.0"},"1323":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"1361":{"cpu":"0.0","mem":"0.0"},"139":{"cpu":"0.0","mem":"0.0"},"1398":{"cpu":"0.0","mem":"0.0"},"1431":{"cpu":"0.0","mem":"0.0"},"1462":{"cpu":"0.0","mem":"0.0"},"148":{"cpu":"0.0","mem":"0.0"},"1497":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"1530":{"cpu":"0.0","mem":"0.0"},"1565":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"1600":{"cpu":"0.0","mem":"0.0"},"164":{"cpu":"0.0","mem":"0.0"},"1866":{"cpu":"0.0","mem":"0.0"},"1872":{"cpu":"0.7","mem":"0.0"},"1873":{"cpu":"0.0","mem":"0.0"},"1875":{"cpu":"122.3","mem":"0.0"},"1878":{"cpu":"0.3","mem":"0.0"},"1879":{"cpu":"0.0","mem":"0.0"},"188":{"cpu":"0.0","mem":"0.0"},"1881":{"cpu":"0.3","mem":"0.0"},"1882":{"cpu":"0.7","mem":"0.0"},"1883":{"cpu":"0.0","mem":"0.0"},"1886":{"cpu":"0.3","mem":"0.0"},"1887":{"cpu":"0.0","mem":"0.0"},"1888":{"cpu":"1.0","mem":"0.0"},"1889":{"cpu":"0.7","mem":"0.0"},"1892":{"cpu":"0.0","mem":"0.0"},"1893":{"cpu":"0.7","mem":"0.0"},"1896":{"cpu":"1.3","mem":"0.0"},"1897":{"cpu":"1.7","mem":"0.0"},"1899":{"cpu":"1.0","mem":"0.0"},"1903":{"cpu":"2.0","mem":"0.0"},"1904":{"cpu":"0.0","mem":"0.0"},"1907":{"cpu":"3.0","mem":"0.0"},"1908":{"cpu":"0.7","mem":"0.0"},"1909":{"cpu":"2.0","mem":"0.0"},"1915":{"cpu":"3.0","mem":"0.0"},"1916":{"cpu":"4.7","mem":"0.0"},"1918":{"cpu":"1.3","mem":"0.0"},"1920":{"cpu":"2.7","mem":"0.0"},"1929":{"cpu":"1.0","mem":"0.0"},"217":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"2668":{"cpu":"0.0","mem":"0.0"},"268":{"cpu":"0.0","mem":"0.0"},"2681":{"cpu":"0.3","mem":"0.0"},"2682":{"cpu":"6.2","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"0.0","mem":"0.0"},"364":{"cpu":"0.0","mem":"0.0"},"405":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"443":{"cpu":"0.0","mem":"0.0"},"484":{"cpu":"0.0","mem":"0.0"},"514":{"cpu":"0.0","mem":"0.0"},"535":{"cpu":"0.0","mem":"0.0"},"559":{"cpu":"0.0","mem":"0.0"},"585":{"cpu":"0.0","mem":"0.0"},"615":{"cpu":"0.0","mem":"0.0"},"646":{"cpu":"0.0","mem":"0.0"},"677":{"cpu":"0.0","mem":"0.0"},"710":{"cpu":"0.0","mem":"0.0"},"742":{"cpu":"0.0","mem":"0.0"},"776":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"812":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"847":{"cpu":"0.0","mem":"0.0"},"880":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"11.3","mem":"0.0"},"920":{"cpu":"0.0","mem":"0.0"},"951":{"cpu":"0.0","mem":"0.0"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"3.7","mem":"0.1"},"984":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"421835.3","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":31.94,"pid":1873}},"gpu_usages":{"Quadro M2000":{"gpu":"2 %","mem":"10.4 %"}},"service":{"last_updated":1701297433,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":259.8,"mount_type":"tmpfs","total":268.4,"used":8.7},"/media/frigate/clips":{"free":910744.4,"mount_type":"zfs","total":3861525.6,"used":2950781.2},"/media/frigate/recordings":{"free":910744.4,"mount_type":"zfs","total":3861525.6,"used":2950781.2},"/tmp/cache":{"free":142.7,"mount_type":"tmpfs","total":150.0,"used":7.4}},"temperatures":{},"uptime":169,"version":"0.12.1-367d724"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

ReoLink Duo 2

### Any other information that may be helpful

Feed dies within minutes of viewing from another device.
