### ISSUE TITLE
[Support]: Storage and Recordings pages do not work.

### ISSUE THREAD

**Issue by AleArchitect** [blakeblackshear/frigate#8796]
### Describe the problem you are having

All of the features of Frigare are working for me, except the storage and the recording/<camera> pages. 

I have 8 cameras all recording to a NFS folder on a Synology NAS. All of the camera's footage is being saved to the NAS. The live view works and Frigate is recording events (although all I can view are the snapshots, the clips will not load). The Figate install and NAS are on different VLANs.

I've checked all my firewall settings and nothing seems to be blocking access to/from Frigate to the NAS. 

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.21
  user: homeassistant
  password: <removed>

# ffmpeg:
#   hwaccel_args:
#     - -hwaccel
#     - vaapi
#     - -hwaccel_device
#     - /dev/dri/renderD128
#     - -hwaccel_output_format
#     - yuv420p

# detectors:
#   cpu1:
#     type: cpu
#   cpu2:
#     type: cpu
#   cpu3:
#     type: cpu
#   cpu4:
#     type: cpu

# ffmpeg:
#   hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb
  
objects:
  track:
    - person
#    - car

record:
  enabled: True
  retain:
    days: 21
    mode: all
  events:
    retain:
      default: 45
      mode: active_objects

birdseye:
  enabled: false
  width: 1280
  height: 960
  mode: motion

go2rtc:
  streams:
    Camera1: 
      - http://192.168.3.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<removed>&password=<removed>
      - "ffmpeg:Camera1#audio=opus"
    Camera1_sub: 
      - http://192.168.3.51/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<removed>&password=<removed>

    Camera2: 
      - http://192.168.3.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<removed>&password=<removed>
      - "ffmpeg:Camera2#audio=opus"
    Camera2_sub: 
      - http://192.168.3.52/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<removed>&password=<removed>

    Camera3: 
      - http://192.168.3.53/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<removed>&password=<removed>
      - "ffmpeg:Camera2#audio=opus"
    Camera3_sub: 
      - http://192.168.3.53/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<removed>&password=<removed>

    FrontPatio: 
      - http://192.168.3.54/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<removed>&password=<removed>
      - "ffmpeg:Camera2#audio=opus"
    FrontPatio_sub: 
      - http://192.168.3.54/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<removed>&password=<removed>

    Camera5: 
      - http://192.168.3.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<removed>&password=<removed>
      - "ffmpeg:Camera2#audio=opus"
    Camera5_sub: 
      - http://192.168.3.55/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<removed>&password=<removed>

    Camera6: 
      - http://192.168.3.56/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<removed>&password=<removed>
      - "ffmpeg:Camera2#audio=opus"
    Camera6_sub: 
      - http://192.168.3.56/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<removed>&password=<removed>

    Yard: 
      - http://192.168.3.57/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=adm<removed>in&password=<removed>
      - "ffmpeg:Camera2#audio=opus"
    Yard_sub: 
      - http://192.168.3.57/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=<removed>&password=<removed>

cameras:

  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.10:8554/Camera1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.3.10:8554/Camera1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,0,640,38,361,38,360,0

  Camera2:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.10:8554/Camera2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.3.10:8554/Camera2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,0,640,38,361,38,360,0

  Camera3:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.10:8554/Camera3
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.3.10:8554/Camera3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,0,640,38,361,38,360,0

  FrontPatio:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.10:8554/FrontPatio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.3.10:8554/FrontPatio_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,0,640,38,361,38,360,0

  Camera5:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.10:8554/Camera5
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.3.10:8554/Camera5_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,0,640,38,361,38,360,0

  Camera6:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.10:8554/Camera6
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.3.10:8554/Camera6_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,0,640,38,361,38,360,0


  Yard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.10:8554/Yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.3.10:8554/Yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,0,640,38,361,38,360,0

  FishEye:
    ffmpeg:
      inputs:
        - path: rtsp://<removed>:<removed>@192.168.3.58:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
        - path: rtsp://<removed>:<removed>@192.168.3.58:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
      enabled: false
    # record:
    #   enabled: true
    snapshots:
      enabled: false
    motion:
      mask:
        - 704,0,704,46,402,47,395,0
```

### Relevant log output

```shell
2023-11-29 19:35:03.251051536  [INFO] Starting Frigate...
2023-11-29 19:35:04.107465458  [2023-11-29 19:35:04] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-29 19:35:04.144846058  [2023-11-29 19:35:04] peewee_migrate                 INFO    : Starting migrations
2023-11-29 19:35:04.217990410  [2023-11-29 19:35:04] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-29 19:35:04.238351167  [2023-11-29 19:35:04] frigate.app                    INFO    : Output process started: 290
2023-11-29 19:35:04.239129039  [2023-11-29 19:35:04] detector.coral                 INFO    : Starting detection process: 288
2023-11-29 19:35:07.034224365  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for Camera1: 293
2023-11-29 19:35:07.034308018  [2023-11-29 19:35:04] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-11-29 19:35:07.034980434  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for Camera2: 295
2023-11-29 19:35:07.034982819  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for Camera3: 299
2023-11-29 19:35:07.034986790  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for FrontPatio: 301
2023-11-29 19:35:07.034988377  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for Camera5: 302
2023-11-29 19:35:07.034997416  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for Camera6: 304
2023-11-29 19:35:07.034999032  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for Yard: 306
2023-11-29 19:35:07.035000357  [2023-11-29 19:35:04] frigate.app                    INFO    : Camera processor started for FishEye: 307
2023-11-29 19:35:07.035014030  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for Camera1: 308
2023-11-29 19:35:07.035015295  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for Camera2: 309
2023-11-29 19:35:07.035016415  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for Camera3: 313
2023-11-29 19:35:07.035023439  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for FrontPatio: 320
2023-11-29 19:35:07.035024625  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for Camera5: 324
2023-11-29 19:35:07.035025837  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for Camera6: 327
2023-11-29 19:35:07.035026955  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for Yard: 347
2023-11-29 19:35:07.035034994  [2023-11-29 19:35:04] frigate.app                    INFO    : Capture process started for FishEye: 354
2023-11-29 19:35:07.045260474  [2023-11-29 19:35:07] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-11-29 19:35:21.635452011  [2023-11-29 19:35:21] frigate.comms.dispatcher       INFO    : Turning off detection for Camera1
2023-11-29 19:35:21.677322654  [2023-11-29 19:35:21] frigate.comms.dispatcher       INFO    : Turning off detection for FrontPatio
2023-11-29 19:35:21.678005657  [2023-11-29 19:35:21] frigate.comms.dispatcher       INFO    : Turning off detection for Camera2
2023-11-29 19:35:21.678486868  [2023-11-29 19:35:21] frigate.comms.dispatcher       INFO    : Turning off detection for Yard
2023-11-29 19:35:21.678794885  [2023-11-29 19:35:21] frigate.comms.dispatcher       INFO    : Turning off detection for Camera5
2023-11-29 19:35:21.720069198  [2023-11-29 19:35:21] frigate.comms.dispatcher       INFO    : Turning off detection for Camera6
2023-11-29 19:35:21.720452413  [2023-11-29 19:35:21] frigate.comms.dispatcher       INFO    : Turning off detection for Camera3
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1536,"width":2048},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":640},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{
Camera1: {
camera_fps: 7,
capture_pid: 308,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 603,
pid: 293,
process_fps: 7,
skipped_fps: 0
},
Camera2: {
camera_fps: 7.1,
capture_pid: 309,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 593,
pid: 295,
process_fps: 7.1,
skipped_fps: 0
},
Camera3: {
camera_fps: 7,
capture_pid: 313,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 607,
pid: 299,
process_fps: 7,
skipped_fps: 0
},
Camera5: {
camera_fps: 7.1,
capture_pid: 324,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 598,
pid: 302,
process_fps: 7.1,
skipped_fps: 0
},
Camera6: {
camera_fps: 7,
capture_pid: 327,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 597,
pid: 304,
process_fps: 7,
skipped_fps: 0
},
FishEye: {
camera_fps: 5.1,
capture_pid: 354,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 605,
pid: 307,
process_fps: 5.1,
skipped_fps: 0
},
FrontPatio: {
camera_fps: 7,
capture_pid: 320,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 601,
pid: 301,
process_fps: 7,
skipped_fps: 0
},
Yard: {
camera_fps: 7.1,
capture_pid: 347,
detection_enabled: 0,
detection_fps: 0,
ffmpeg_pid: 594,
pid: 306,
process_fps: 7.1,
skipped_fps: 0
},
cpu_usages: {
1: {
cpu: "0.0",
mem: "0.0"
},
15: {
cpu: "0.0",
mem: "0.0"
},
17: {
cpu: "0.0",
mem: "0.0"
},
24: {
cpu: "0.0",
mem: "0.0"
},
25: {
cpu: "0.0",
mem: "0.0"
},
26: {
cpu: "0.0",
mem: "0.0"
},
27: {
cpu: "0.0",
mem: "0.0"
},
28: {
cpu: "0.0",
mem: "0.0"
},
29: {
cpu: "0.0",
mem: "0.0"
},
30: {
cpu: "0.0",
mem: "0.0"
},
31: {
cpu: "0.0",
mem: "0.0"
},
32: {
cpu: "0.0",
mem: "0.0"
},
41: {
cpu: "0.0",
mem: "0.0"
},
42: {
cpu: "0.0",
mem: "0.0"
},
80: {
cpu: "0.0",
mem: "0.0"
},
81: {
cpu: "0.0",
mem: "0.0"
},
82: {
cpu: "0.0",
mem: "0.0"
},
88: {
cpu: "11.0",
mem: "0.2"
},
101: {
cpu: "2.7",
mem: "2.6"
},
102: {
cpu: "0.0",
mem: "0.0"
},
112: {
cpu: "0.0",
mem: "0.2"
},
134: {
cpu: "0.0",
mem: "0.1"
},
135: {
cpu: "0.0",
mem: "0.1"
},
136: {
cpu: "0.0",
mem: "0.1"
},
137: {
cpu: "0.0",
mem: "0.1"
},
281: {
cpu: "0.0",
mem: "1.0"
},
287: {
cpu: "0.0",
mem: "0.1"
},
288: {
cpu: "0.0",
mem: "1.3"
},
290: {
cpu: "1.0",
mem: "1.1"
},
293: {
cpu: "0.3",
mem: "1.2"
},
295: {
cpu: "0.3",
mem: "1.2"
},
297: {
cpu: "0.0",
mem: "0.2"
},
299: {
cpu: "0.3",
mem: "1.2"
},
300: {
cpu: "0.0",
mem: "0.2"
},
301: {
cpu: "0.7",
mem: "1.2"
},
302: {
cpu: "0.3",
mem: "1.2"
},
303: {
cpu: "0.0",
mem: "0.2"
},
304: {
cpu: "0.3",
mem: "1.2"
},
305: {
cpu: "0.0",
mem: "0.2"
},
306: {
cpu: "0.3",
mem: "1.2"
},
307: {
cpu: "0.0",
mem: "1.1"
},
308: {
cpu: "0.7",
mem: "1.1"
},
309: {
cpu: "0.7",
mem: "1.1"
},
310: {
cpu: "0.0",
mem: "0.2"
},
313: {
cpu: "0.7",
mem: "1.1"
},
316: {
cpu: "0.0",
mem: "0.2"
},
318: {
cpu: "0.0",
mem: "0.2"
},
320: {
cpu: "0.3",
mem: "1.1"
},
321: {
cpu: "0.0",
mem: "0.2"
},
324: {
cpu: "0.7",
mem: "1.1"
},
327: {
cpu: "0.7",
mem: "1.1"
},
347: {
cpu: "0.7",
mem: "1.1"
},
354: {
cpu: "0.3",
mem: "1.1"
},
563: {
cpu: "0.3",
mem: "0.3"
},
564: {
cpu: "0.7",
mem: "0.3"
},
565: {
cpu: "0.7",
mem: "0.3"
},
566: {
cpu: "0.7",
mem: "0.3"
},
567: {
cpu: "0.7",
mem: "0.3"
},
568: {
cpu: "0.7",
mem: "0.3"
},
569: {
cpu: "0.0",
mem: "0.3"
},
570: {
cpu: "0.7",
mem: "0.3"
},
593: {
cpu: "0.7",
mem: "0.4"
},
594: {
cpu: "0.7",
mem: "0.4"
},
597: {
cpu: "0.7",
mem: "0.4"
},
598: {
cpu: "1.0",
mem: "0.4"
},
601: {
cpu: "1.0",
mem: "0.4"
},
603: {
cpu: "1.0",
mem: "0.4"
},
605: {
cpu: "0.7",
mem: "0.4"
},
607: {
cpu: "0.7",
mem: "0.4"
},
5112: {
cpu: "0.0",
mem: "0.0"
},
5165: {
cpu: "0.0",
mem: "0.0"
},
5184: {
cpu: "0.0",
mem: "0.0"
},
5186: {
cpu: "0.0",
mem: "0.0"
},
%Cpu(s):: {
cpu: "id,",
mem: "76.1"
},
MiB: {
cpu: "6722.5",
mem: "avail"
},
PID: {
cpu: "%CPU",
mem: "%MEM"
},
Tasks:: {
cpu: "stopped,",
mem: "0"
},
top: {
cpu: "load",
mem: "average:"
}
},
detection_fps: 0,
detectors: {
coral: {
detection_start: 0,
inference_speed: 15.21,
pid: 288
}
},
service: {
last_updated: 1701314284,
latest_version: "0.12.1",
storage: {
/dev/shm: {
free: 59.9,
mount_type: "tmpfs",
total: 67.1,
used: 7.2
},
/media/frigate/clips: {
free: 2869900.1,
mount_type: "nfs",
total: 13428129.4,
used: 10558229.3
},
/media/frigate/recordings: {
free: 2869900.1,
mount_type: "nfs",
total: 13428129.4,
used: 10558229.3
},
/tmp/cache: {
free: 951.5,
mount_type: "tmpfs",
total: 1000,
used: 48.5
}
},
temperatures: { },
uptime: 2580,
version: "0.12.1-367d724"
}
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

ReoLink & hikvision
