### ISSUE TITLE
[Config Support]: Docker media volume

### ISSUE THREAD

**Issue by Sonusss** [blakeblackshear/frigate#8806]
### Describe the problem you are having

Frigate writes media files somewhere without caring the specified media volume mounted.
Recordings are working well and I can playback sequences but web storage page displays a total of 4.01GB while my mounted storage is 1.9TB
There are absolutely no files written in my specified media path...

Docker inspect reports correct mounted volumes
        "Mounts": [
            {
                "Type": "tmpfs",
                "Source": "",
                "Destination": "/tmp/cache",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/storage/frigate",
                "Destination": "/media/frigate",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/docker/frigate",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 10.10.0.1
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  # tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  # tls_client_cert: /path/to/client.crt
  # tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  # tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi


cameras:
  Gate:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@10.10.3.192:554/Streaming/Channels/101
          roles:
            - detect
    detect:
      enabled: true 
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: true

      retain:
        mode: all
        days: 10
      events:  
        pre_capture: 5
        post_capture: 5
        required_zones: []
        retain:
          default: 10

  Cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@10.10.3.101:554/11
          roles:
            - detect
    detect:
      enabled: false 
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
    record:
      enabled: true
      events:
       retain:
        default: 10

go2rtc:
  streams:
    Gate:
      - rtsp://admin:xxx@10.10.3.192:554/Streaming/Channels/101
      - isapi://admin:xxx@10.10.3.192:80/
    Cam1:
      - rtsp://admin:xxx@10.10.3.101:554/11
```

### Relevant log output

```shell
2023-11-30 16:32:26.382199840  [INFO] Starting Frigate...
2023-11-30 16:32:27.208134828  [2023-11-30 16:32:27] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-30 16:32:27.230545988  [2023-11-30 16:32:27] peewee_migrate                 INFO    : Starting migrations
2023-11-30 16:32:27.234024207  [2023-11-30 16:32:27] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-30 16:32:27.247090104  [2023-11-30 16:32:27] detector.coral                 INFO    : Starting detection process: 288
2023-11-30 16:32:29.893898228  [2023-11-30 16:32:27] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-11-30 16:32:29.893987588  [2023-11-30 16:32:27] frigate.app                    INFO    : Output process started: 290
2023-11-30 16:32:29.894565323  [2023-11-30 16:32:27] frigate.app                    INFO    : Camera processor started for Gate: 296
2023-11-30 16:32:29.894568702  [2023-11-30 16:32:27] frigate.app                    INFO    : Camera processor started for Cam1: 298
2023-11-30 16:32:29.894573166  [2023-11-30 16:32:27] frigate.app                    INFO    : Capture process started for Gate: 299
2023-11-30 16:32:29.894575609  [2023-11-30 16:32:27] frigate.app                    INFO    : Capture process started for Cam1: 302
2023-11-30 16:32:29.900492608  [2023-11-30 16:32:29] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Frigate stats

```json
{"Cam1":{"camera_fps":5.0,"capture_pid":302,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":308,"pid":298,"process_fps":5.0,"skipped_fps":0.0},"Gate":{"camera_fps":5.0,"capture_pid":299,"detection_enabled":1,"detection_fps":1.4,"ffmpeg_pid":307,"pid":296,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.8"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"0.0","mem":"0.2"},"109":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"1.0","mem":"2.3"},"118":{"cpu":"0.0","mem":"0.2"},"1222":{"cpu":"0.0","mem":"0.0"},"123":{"cpu":"0.0","mem":"0.2"},"124":{"cpu":"0.0","mem":"0.1"},"125":{"cpu":"0.0","mem":"0.1"},"1258":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"1.0"},"287":{"cpu":"0.3","mem":"0.1"},"288":{"cpu":"0.0","mem":"1.4"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"1.7","mem":"1.2"},"296":{"cpu":"0.7","mem":"1.2"},"297":{"cpu":"0.0","mem":"0.2"},"298":{"cpu":"0.7","mem":"1.2"},"299":{"cpu":"2.3","mem":"1.1"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.2"},"302":{"cpu":"9.0","mem":"1.3"},"307":{"cpu":"4.7","mem":"0.8"},"308":{"cpu":"9.3","mem":"1.3"},"31":{"cpu":"0.0","mem":"0.0"},"311":{"cpu":"0.0","mem":"0.2"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"3660.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":1.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.94,"pid":288}},"gpu_usages":{"intel-vaapi":{"gpu":"5.74 %","mem":"- %"}},"service":{"last_updated":1701362641,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":619.6,"mount_type":"tmpfs","total":629.1,"used":9.6},"/media/frigate/clips":{"free":1065.9,"mount_type":"tmpfs","total":4103.1,"used":3037.2},"/media/frigate/recordings":{"free":1065.9,"mount_type":"tmpfs","total":4103.1,"used":3037.2},"/tmp/cache":{"free":996.4,"mount_type":"tmpfs","total":1000.0,"used":3.6}},"temperatures":{},"uptime":694,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Running on Ubuntu 22
/storage is a mounted ext4 partition
