### ISSUE TITLE
set Time range to enable/disable detection (per camera)

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#8807]
**Describe what you are trying to accomplish and why in non technical terms**
It would be great if we could define a daily time-range to disable detection during this time -  IE for a camera that looks at my home office room , or at a retail shop/store - One presumably would not want detection's running during business hours as there may be hundreds per hour, but they *would like* detection's running **after business hours**.  Thus would be great if we could define:

```
   detect:
      enabled: true
         timeENABLED: 1830
         timeDISABLED: 0700 
```

^( thus daily at 6:30pm detection/events for this one camera would be enabled/working,  but at 700am each morning, detection would stop,  then come back on at 630pm -- and on and on)

thanks
