### ISSUE TITLE
[Config Support]: clips deleted after a few minutes although retention is set to 30 days

### ISSUE THREAD

**Issue by remz1337** [blakeblackshear/frigate#8810]
### Describe the problem you are having

I have my recording set up to keep clips of events for 30 days, however the clips get deleted after a few minutes.

### Version

0.13.0

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mosquitto.test.com
  user: mosquitto
  password: abc

go2rtc:
  streams:
    Camera1:
      - "ffmpeg:http://mycam.test.com/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=abc#video=copy#audio=copy#audio=opus"
    Camera1_sub:
      - "ffmpeg:http://mycam.test.com/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=abc"

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  tensorrt:
    type: tensorrt
#    device: 0

model:
  path: /config/model_cache/tensorrt/8.5.3/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
#  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
#  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
#  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
#  crop: False
  # Optional: height to resize the snapshot to (default: original size)
#  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
#  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
#  retain:
    # Required: Default retention days (default: shown below)
#    default: 10
    # Optional: Per object retention days
#    objects:
#      person: 15

# Enable 24/7 recording (mode: all means all clips, not just clips with objects in)
# Keep 30 days worth of footage (Frigate automatically deletes the oldest footage once space gets extremely low)
record:
  enabled: true
  retain:
    days: 30
#mode motion or all
    mode: motion

cameras:
  Porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera1?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Camera1_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
```

### Relevant log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)
