### ISSUE TITLE
[Camera Support]: go2rtc connection to doorbell keeps mic active.

### ISSUE THREAD

**Issue by twister36** [blakeblackshear/frigate#8813]
### Describe the problem you are having

I've noticed that since I've added the go2rtc stream options to my config file for my door bell camera (Lorex) that it keeps an active connection to the mic on the camera for audio. This prevents anyone else from using the mic, (i.e. through Lorex App) and also prevents the door bell from ringing because the Lorex doorbell thinks there is an active conversation going on.

Is there a way to configure a restream with no audio?

### Version

0.12.1-367D724

### Frigate config file

```yaml
go2rtc:
  streams:
     door_bell:
       - rtsp://user:pass!@0.0.0.0:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
```

### Relevant log output

```shell
not applicable.
```

### FFprobe output from your camera

```shell
not applicable.
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Lorex B451AJDB-E
