### ISSUE TITLE
[Support]: Amcrest secondary stream 704x480 birdseye ratio

### ISSUE THREAD

**Issue by eric-cgn** [blakeblackshear/frigate#8834]
### Describe the problem you are having

Birdseye in 0.13.0-beta6 overrides configuration to match aspect ratio. Amcrest cameras sending (what they call D1), NTSC DVT resolution of 704x480 requires an aspect of 22:15 to avoid empty space in the stream.

### Version

0.13.0-beta6

### Frigate config file

```yaml
birdseye:
  enabled: True
  mode: continuous
  width: 2560
  # height: 1920
  height: 1746
  quality: 5
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Amcrest IP5M*28MM
