### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by grainsoflight** [blakeblackshear/frigate#8842]
### Describe the problem you are having

I dont understand the error that WebRTC is giving me, it throws back 2023-12-03 02:26:26.734991514  02:26:26.734 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="dial tcp: lookup admin on 192.168.0.1:53: no such host"

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: 2MCHouYnzpqN3&
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:#Hg#oDXvd@%o96@192.168.5.3:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:#Hg#oDXvd@%o96@192.168.5.3:554/h264Preview_01_main
          roles:
            - record
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:#Hg#oDXvd@%o96@192.168.5.2:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:#Hg#oDXvd@%o96@192.168.5.2:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 480

go2rtc:
  streams:
    backyard:
      - rtsp://admin:#Hg#oDXvd@%o96@192.168.5.2:554/h264Preview_01_main
  webrtc:
    candidates:
      -192.168.0.11:8555
      -stun:8555
```

### Relevant log output

```shell
2023-12-03 02:26:26.734991514  02:26:26.734 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="dial tcp: lookup admin on 192.168.0.1:53: no such host"
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink trackmix4
