### ISSUE TITLE
[Support]: Clip not showing detected object

### ISSUE THREAD

**Issue by rici44** [blakeblackshear/frigate#8843]
### Describe the problem you are having

I got these record section in config 
```
# Optional: Record configuration
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
``` 
But this occurs:
**Frigate detected Car at 09:23:46 
Frigate recorded clip begins at 09:23:46 and ends at 09:23:52
And clip did not catch the object at all**

### Version

SYSTEM 0.12.1-367D724

### Frigate config file

```yaml
record part as you can see above
```

### Relevant log output

```shell
..
```

### FFprobe output from your camera

```shell
..
```

### Frigate stats

```json
..
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Dahua Imou Versa
