### ISSUE TITLE
[Detector Support]: Frigate+ Multiple Objects Detected

### ISSUE THREAD

**Issue by cliffburdick** [blakeblackshear/frigate#8845]
### Describe the problem you are having

When multiple objects are detected in the same frame, there's only a trigger for one of the types. For example. whenever a dog is in the frame, there's almost always someone walking the dog. However, the trigger only shows Person. This makes it so when you filter on dog, even though dozens of dogs appeared, it does not find them. As an example, in the image below two dogs are present, but the detector doesn't show it.
![snapshot](https://github.com/blakeblackshear/frigate/assets/30670611/0944dbef-c05b-441b-8789-5bb72f90554b)

### Version

0.13.0-614a36a

### Frigate config file

```yaml
mqtt:
  enabled: False

coral:
  type: edgetpu
  device: usb  

model:
  path: plus://2796c40187c4de388be52a5cad32983a

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat
    - motorcycle
    - horse
    - bicycle

cameras:
  lower_wb: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac        
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass!@192.168.1.170:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass!@192.168.1.170:554 # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 10
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50              
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 10
          mode: active_objects
    motion:
      mask:    
        - 1280,398,1121,212,852,0,383,0,292,94,191,145,140,200,0,251,26,458,199,720,1280,720 
    zones:  
      front_and_street:
        coordinates: 1428,161,922,150,739,411,651,480,490,560,517,632,478,707,342,821,373,881,234,1013,258,1080,1920,1080,1920,251
        objects:
          - person
          - car
          - cat
          - bicycle
          - dog
          - motorcycle
            
  upper_wb: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac        
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass!@192.168.1.172:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass!@192.168.1.172:554 # <----- The stream you want to use for detection
          roles:
            - record            
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 10
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50 
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          mode: active_objects
          default: 10
    motion:
      mask:    
        - 1243,535,1280,183,1118,73,877,68,854,0,185,0,43,89,65,192,0,251,0,720,1147,720
    zones:  
      driveway_and_street:
        coordinates:  391,0,1868,0,1968,137,2358,127,2375,261,2238,527,2575,657,2688,1520,0,1520,0,277
        objects:
          - person
          - car
          - bicycle
          - cat
          - dog
          - motorcycle
  porch: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac        
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass@192.168.1.171:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect      
        - path: rtsp://admin:pass@192.168.1.171:554 # <----- The stream you want to use for detection
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          mode: active_objects
          default: 10            
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
      stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        interval: 10
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        threshold: 50        
    motion:
      mask:    
        - 1280,117,1161,95,1089,165,805,131,530,97,387,147,334,0,0,0,0,720,1280,720
    zones:  
      porch_and_lawn:
        coordinates: 2688,0,2381,244,2315,347,1945,261,1618,244,1178,187,931,267,735,0,0,0,0,1520,2688,1520
        objects:
          - person
          - car
          - bicycle
          - cat
          - dog
          - motorcycle
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta6
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/cburdick/frigate/config:/config
      - /mnt/media/frigate:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
        #- /home/cburdick/frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "pw"
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by cliffburdick** [comment]
Hi @blakeblackshear , that's correct, there are no dog events at all on all these times where it says a person. For example, I looked back manually and saw about 6 dogs in the last 24 hours on the person thumbnails. However, Dog didn't have a match in over 30 hours. I will try labeling them and seeing if that improves things 

By the way, is there a method for labeling without the GUI button? I have a lot of cases where Frigate just didn't find any events, but if I go look at the recording I can see something like a car. But I can't click anything since there wasn't a snapshot taken.

**Comment by cliffburdick** [comment]
Just looking through some old events, it really seems like it's just not detecting dogs at all in most cases. I know nothing is "obvious", for a model, but in this case for example, the person is 99% and the dog is not detected at all:

![image](https://github.com/blakeblackshear/frigate/assets/30670611/5557ed61-e7c1-4cd7-b78f-bd2a901620c0)

**Comment by NickM-27** [comment]
something seems wrong, I have had no issues with my model detecting dogs. 

what I would suggest is downloading one of these "person with dog" clips. you can then temporarily edit your camera config to use the clip file as a camera instead of the camera itself and then you can watch the debug live view and see what is going on https://deploy-preview-6262--frigate-docs.netlify.app/development/contributing#2-modify-your-local-config-file-for-testing

**Comment by cliffburdick** [comment]
Thanks, I will try that. FWIW another just happened where the person was 100% and the dog was undetected:

![image](https://github.com/blakeblackshear/frigate/assets/30670611/88d9f6af-fd7a-4d25-a4fd-c274a68a0403)

**Comment by NickM-27** [comment]
yes, I am suspecting something else is at play here causing the events to not be created, examples of the debug steps should help figure out regardless

**Comment by cliffburdick** [comment]
Hi @NickM-27 , I did as you suggested and it's not putting a bounding box around the dog at all while the video plays:

![image](https://github.com/blakeblackshear/frigate/assets/30670611/45709bbb-4392-4688-85ee-54348369a5a8)

**Comment by NickM-27** [comment]
it would also be helpful if you can open `http://frigate_ip:5000/api/<camera_name>/grid.jpg` and show that image here. I'm wondering if the detections from the larger nvidia model are causing some confusion

**Comment by cliffburdick** [comment]
Here is the grid I get:
![image](https://github.com/blakeblackshear/frigate/assets/30670611/31998313-60ca-4c01-a1f1-a23dcfcc033a)

**Comment by NickM-27** [comment]
yeah, these numbers do look pretty large. If you have the ability, I would suggest stopping frigate and using `sqlite3` to clear out the existing historical data by running sql command `REMOVE FROM regions;` and then try the clip again and see if it works better. 

I will put up a PR to ensure this does not happen when users are running larger models then switch to a smaller model

**Comment by cliffburdick** [comment]
Hi @NickM-27 , I did a `docker compose down`, then edited the database: 

```
sqlite> delete from regions;
sqlite>
```

Then I did a `docker compose up`. The grid appears the same, and the debug clip does not match on the dog still. Should I be seeing something different?

**Comment by NickM-27** [comment]
can you show the grid image as it is now? we would at least expect things to be slightly different since since the historical data would have to be rebuilt from current events only

**Comment by cliffburdick** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/30670611/3bb7863e-8fac-477e-bc3a-da3e31a61894)

**Comment by NickM-27** [comment]
something seems wrong here because cars are also not being detected. Can you copy your config from the frigate config editor in the webUI and paste it here?

**Comment by cliffburdick** [comment]
```
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb  

model:
  path: plus://2796c40187c4de388be52a5cad32983a

cameras:
  lwb: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac        
      inputs:
        - path: rtsp://admin:pass!@192.168.1.170:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass!@192.168.1.170:554 # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
        #stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        #interval: 10
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        #threshold: 50              
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 10
          mode: active_objects
    motion:
      mask:    
        - 1280,398,1121,212,852,0,383,0,292,94,191,145,140,200,0,251,26,458,199,720,1280,720 
    zones:  
      front_and_street:
        coordinates: 1428,161,922,150,739,411,651,480,490,560,517,632,478,707,342,821,373,881,234,1013,258,1080,1920,1080,1920,251
          #objects:
          #- person
          #- car
          #- cat
          #- bicycle
          #- dog
          #- motorcycle
            
  uwb: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac        
      inputs:
        - path: /media/frigate/clip_upper_white_birch_1701706715.987178-1701706741.95463.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect      
        # - path: rtsp://admin:pass@192.168.1.172:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
        #   roles:
        #     - detect
        # - path: rtsp://admin:pass@192.168.1.172:554 # <----- The stream you want to use for detection
        #   roles:
        #     - record            
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
        #stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        #interval: 10
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        #threshold: 50 
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          mode: active_objects
          default: 10
    motion:
      mask:    
        - 1243,535,1280,183,1118,73,877,68,854,0,185,0,43,89,65,192,0,251,0,720,1147,720
    zones:  
      driveway_and_street:
        coordinates:  391,0,1868,0,1968,137,2358,127,2375,261,2238,527,2575,657,2688,1520,0,1520,0,277
          #objects:
          #- person
          #- car
          #- bicycle
          #- cat
          #- dog
          #- motorcycle
  porch: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac        
      inputs:
        - path: rtsp://admin:pass@192.168.1.171:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream you want to use for detection
          roles:
            - detect      
        - path: rtsp://admin:pass@192.168.1.171:554 # <----- The stream you want to use for detection
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        retain:
          mode: active_objects
          default: 10            
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
        #stationary:
        # Optional: Frequency for confirming stationary objects (default: shown below)
        # When set to 0, object detection will not confirm stationary objects until movement is detected.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
        #interval: 10
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
        #threshold: 50        
    motion:
      mask:    
        - 1280,117,1161,95,1089,165,805,131,530,97,387,147,334,0,0,0,0,720,1280,720
    zones:  
      porch_and_lawn:
        coordinates: 2688,0,2381,244,2315,347,1945,261,1618,244,1178,187,931,267,735,0,0,0,0,1520,2688,1520
          #objects:
          #- person
          #- car
          #- bicycle
          #- cat
          #- dog
          #- motorcycle
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
```
