### ISSUE TITLE
[Camera Support]: Invalid data found when processing input (on Tiandy camera)

### ISSUE THREAD

**Issue by Rhalah** [blakeblackshear/frigate#8856]
### Describe the problem you are having

I'm trying to configure a Tiandy TC-H134N PTZ camera in Frigate but I'm getting the error "Invalid data found when processing input".
I thought that the error was with ffmpeg but, at least in my PC, FFplay can open the stream without any error (using the exact same rtsp path that is in Frigate's config).

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: ***.***.***.***
  port: 1883
  user: *** 
  password: ****

environment_vars:
  LIBVA_DRIVER_NAME: i965

ffmpeg:
  hwaccel_args: preset-vaapi

objects:
    track:
        - person
        - cat
        - dog
    filters:
      person:
        threshold: 0.7
      cat:
        threshold: 0.7
      dog:
        threshold: 0.7  

birdseye:
  enabled: true
  mode: continuous

detectors:
#  ov:
#    type: openvino
#    device: AUTO
#    model:
#      path: /openvino-model/ssdlite_mobilenet_v2.xml
  coral:
    type: edgetpu
    device: usb

#model:   # this is required by OpenVino
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  Dahua1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.1.130:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif# <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://***:***@192.168.1.130:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif# <----- The stream you want to use for detection
          roles:
            - record
    zones:
      zone_0:
        coordinates: 854,480,854,0,0,0,0,480
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 854 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record: # <----- Enable recording
       enabled: True
  Dahua2: # <------ Name the camera
     ffmpeg:
       inputs:
         - path: rtsp://***:***@192.168.1.131:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif# <----- The stream you want to use for detection
           roles:
            - detect
         - path: rtsp://***:***@192.168.1.131:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif# <----- The stream you want to use for detection
           roles:
            - record
     detect:
       enabled: True
       width: 854 # <---- update for your camera's resolution
       height: 480 # <---- update for your camera's resolution
     motion:
       mask:
         - 145,423,311,286,272,102,0,270
     record: # <----- Enable recording
       enabled: True
  Dahua3: # <------ Name the camera
     ffmpeg:
       inputs:
         - path: rtsp://***:***@192.168.1.132:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif# <----- The stream you want to use for detection
           roles:
            - detect
         - path: rtsp://***:***@192.168.1.132:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif# <----- The stream you want to use for detection
           roles:
            - record
     detect:
       enabled: True # <---- disable detection until you have a working camera feed
       width: 854 # <---- update for your camera's resolution
       height: 480 # <---- update for your camera's resolution
     record: # <----- Enable recording
       enabled: True
  TiandyPT: # <------ Name the camera
     ffmpeg:
       inputs:
         - path: rtsp://***:***@192.168.1.133:554/1/2# <----- The stream you want to use for detection
           roles:
            - detect
         - path: rtsp://***:***@192.168.1.133:554/1/1# <----- The stream you want to use for detection
           roles:
            - record
     detect:
       enabled: True # <---- disable detection until you have a working camera feed
       width: 854 # <---- update for your camera's resolution
       height: 480 # <---- update for your camera's resolution
     record: # <----- Enable recording
       enabled: True
```

### Relevant log output

```shell
ffmpeg.TiandyPT.record         ERROR   : rtsp://*:*@192.168.1.133:554/1/0# <----- The stream you want to use for detection: Invalid data found when processing input
2023-12-04 21:56:54.964700696  [2023-12-04 18:56:54] watchdog.TiandyPT              INFO    : Terminating the existing ffmpeg process...
2023-12-04 21:56:54.964707428  [2023-12-04 18:56:54] watchdog.TiandyPT              INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-04 21:56:54.966462362  [2023-12-04 18:56:54] frigate.video                  ERROR   : TiandyPT: Unable to read frames from ffmpeg process.
2023-12-04 21:56:54.967068162  [2023-12-04 18:56:54] frigate.video                  ERROR   : TiandyPT: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://***:***@192.168.1.133:554/1/1':
  Metadata:
    title           : SDP Descrption
    comment         : SDP Descrption
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1920x1080, 15 fps, 24.92 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: pcm_alaw, 16000 Hz, 1 channels, s16, 128 kb/s
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tiandy TC-H134N
