### ISSUE TITLE
Only "person" is been detected

### ISSUE THREAD

**Issue by oangelo** [blakeblackshear/frigate#886]
**Describe the bug**
Only person is detected.

**Version of frigate**
Output from `/api/version`: 0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: host_IP
  user: user
  password: {FRIGATE_RTSP_PASSWORD}
cameras:
  Frontal:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
      inputs:
        - path: "rtmp://camfrontal/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password={FRIGATE_RTSP_PASSWORD}" 
          roles:
            - detect
            - clips
    width: 2304 
    height: 1296 
    fps: 6
  Direita:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
      inputs:
        - path: "rtmp://camdireita/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password={FRIGATE_RTSP_PASSWORD}" 
          roles:
            - detect
            - clips
    width: 2560 
    height: 1920 
    fps: 6 
  Traseira:
    ffmpeg:
      inputs:
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.1.189 
          roles:
            - rtmp
            - detect
            - clips
    width: 1280 
    height: 720 
    fps: 6


detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

```

**Additional context**
The system is detecting people very well. I tried other systems and Frigate is the best. However, for my configuration it is detecting only "person". Is this the default behavior? It is not clear in the documentation which objects the Frigate detects by default, nor which objects it can detect. The documentation says "Optional: setting object filters at the camera level", but how can I enable global object detection?

PS: Can I detect snakes? I live in a rainforest and would like to know when there is a snake close to the house.

**Comment by paularmstrong** [comment]
Yes, that is the default behavior.

The available object list is here: https://github.com/blakeblackshear/frigate/blob/31d408a7467ca1cce29df8db26d6552b17c7f658/labelmap.txt

Update your config to track more objects: https://blakeblackshear.github.io/frigate/configuration/index#objects

**Comment by rcjkierkels** [comment]
I have the same problem:

```
cameras:
  g3camera:
    ffmpeg:
      inputs:
        - path: rtsp://x.x.x.x:xxxx/xxxx
          roles:
            - detect
            - rtmp
            - clips
    snapshots:
      enabled: True
    detect:
      width: 1024
      height: 576
    objects:
      track:
        - person
        - cell phone
        - banana
        - keyboard
        - pizza
        - knife
```
It works very well detecting persons. But it won't detect any other objects. When I am holding a cell phone it still only detects person. Also tested it with banana and all the other objects. When I remove person from the list it detects none of them.
Do I miss a configuration here?
