### ISSUE TITLE
The Speaker and Mic Icons do not appear when using Chrome on a Amazon Fire Tab

### ISSUE THREAD

**Issue by def1149** [blakeblackshear/frigate#8863]
### Describe the problem you are having

I'm using an Amazon Fire tablet for HA.  The frigate card does not show the Speaker, Microphone or Pause icons. 

### Version

v5.2.0

### Frigate config file

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
      stream: doorbell_stream
menu:
  buttons:
    microphone:
      enabled: true
      icon: mdi:microphone
      type: momentary
      alignment: matching
    mute:
      enabled: true
    expand:
      enabled: false
    play:
      enabled: true
  style: overlay
  position: top
live:
  microphone:
    always_connected: false
    disconnect_seconds: 0
view:
  default: live
performance:
  profile: high
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Reolink Doorbell wi-fi
