### ISSUE TITLE
[Support]: Multi-live view resolution

### ISSUE THREAD

**Issue by ankycooper** [blakeblackshear/frigate#8875]
### Describe the problem you are having

##Multi-live view resolution##

I have set my mainstream on 2592x1520 and substream 2 1280x720

record and live view uses the mainstream via go2rtc (unmodified)
detect on substream.

The issue I have is my Alexa devices only support 1920x1080 resolution. I don't want to reduce the main resolution to 1080p.

Is there a go2rtc option that I can enable which can scale down the resolution to 1080p when the call is made from a device supporting only 1080p

### Version

0.12.1-367D724

### Frigate config file

```yaml
streams:
    House-Front: #<------ Name the camera
      - rtsp://user:pass@10.1.2.3:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    House-Front-Sub: #<------ Name the camera substream
      - rtsp://user:pass@10.1.2.3:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dahua
