### ISSUE TITLE
[Support]: Live View doesn't work through Nginx Proxy, but debug View works

### ISSUE THREAD

**Issue by Hanens178** [blakeblackshear/frigate#8876]
### Describe the problem you are having

I'm Running Frigate stable via Docker, and it's exposed to the internet via NPM. I use the default configuration for NPM.

And I now have the problem that the live view doesn't load, but this only happens in live, when I go to the debug feed it works without any Problems. Recordings work without any problems as well.

Chrome Console says:
"WebSocket connection to wss://frigate.website.com/live/jsmpeg/insert_name failed"

### Version

stable

### Frigate config file

```yaml
Cams are configured like this

  name:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://insert_camera_ip
          input_args: preset-rtsp-generic
          roles:
            - record

    detect:
      enabled: false
```

### Relevant log output

```shell
Log shows no errors
```

### FFprobe output from your camera

```shell
I don't think this matters, this problem is across two machines and 3 separate types of cameras
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC510A; Tapo C310; Tapo C320WS
