### ISSUE TITLE
[Camera Support]: Timeout/EOF on a wired POE intercom

### ISSUE THREAD

**Issue by xavan83** [blakeblackshear/frigate#8882]
### Describe the problem you are having

I receive a lot (6-7 times per hour) an error on this camera: 
>192.168.0.70:554: i/o timeout" url=rtsp:/192.168.0.70:554/Streaming/Channels/101

This is a Hikvision poe powered ds-kb8113-ime intercom located 100meters away from my home.
Maybe the network connection is not perfect but I am unable to do a better one
I am using it using the main stream (fullhd + audio) but the same problem occurs using the sub stream.
How can I reduce the timeout/buffer/reorder frame ?

### Version

0.13.0-614A36A (beta6)

### Frigate config file

```yaml
go2rtc:
  streams:
    sonnette:
      - rtsp://192.168.0.70:554/Streaming/Channels/101
cameras:
  sonnette:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/sonnette
          roles:
            - detect,record
    detect:
      fps: 5
      enabled: True
      width: 1920
      height: 1080
    motion:
      mask:
        - 0,674,880,739,1514,672,1920,597,1920,0,0,0
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      quality: 100
      required_zones: []
    objects:
      filters:
        person:
           min_score: 0.3
           threshold: 0.5
           min_area: 10000
        cars:
          min_score: 0.3
          threshold: 0.5
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - cat
        - dog
        - horse
```

### Relevant log output

```shell
2023-12-07 12:17:22.070139725  12:17:22.070 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.2:50360->192.168.0.70:554: i/o timeout" url=rtsp://192.168.0.70:554/Streaming/Channels/101
```

### FFprobe output from your camera

```shell
ffprobe version 6.0-6ubuntu1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-2ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[rtsp @ 0x557e0ce37c40] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://192.168.0.70:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 1920x1080, 12 fps, 12 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision
