### ISSUE TITLE
[Camera Support]: Amcrest IP8M recordings without audio

### ISSUE THREAD

**Issue by gloaysa** [blakeblackshear/frigate#8903]
### Describe the problem you are having

Hi! First of all, thank you in advance to anyone that will read this. I appreciate your time!

I've spent hours and hours for the last 3 days trying to get audio out of my camera. I know the camera's audio is working because when I navigate to the amcrest UI I get audio there.

I got a partial result after setting the go2rtc streams. If I navigate to go2rtc dashboard I get in there a stream with audio.
The audio is not passed to Frigate, tho. I use HomeAssistant and I don't get audio in there (unless I select as the streaming source go2rtc from the Frigate card) and more importantly, I don't get audio on the recordings.

I've been reading all issues I could find that could help me, the closest I got was with:
 - https://github.com/blakeblackshear/frigate/issues/6392
 - https://github.com/blakeblackshear/frigate/issues/6471
 - https://github.com/blakeblackshear/frigate/issues/5341 

But following the recommendations in there didn't fix my problem.

I feel like I'm very close, and any help will be greatly appreciated it.

### Version

0.12.1-367d724

### Frigate config file

```yaml
# https://docs.frigate.video/configuration/index/#full-configuration-reference
mqtt:
  host: xxxxxxx
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

go2rtc:
  streams:
    main: # <- for RTSP streams
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.142:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:main#audio=opus"
    
cameras:
  main:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 10
    detect:
      enabled: False
      width: 3840
      height: 2160

detectors:
  coral:
    type: edgetpu
    device: usb

# Optional: Object configuration https://docs.frigate.video/configuration/objects
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - cat
    - person
  filters:
    cat:
      # Optional: minimum score for the object to initiate tracking (default: 0.5)
      min_score: 0.4
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
      threshold: 0.7

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 3840
  # Optional: Height of the output resolution (default: shown below)
  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
no relevant logs
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}}]
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.9"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"3.0","mem":"5.4"},"119":{"cpu":"0.0","mem":"0.2"},"125":{"cpu":"0.0","mem":"0.1"},"126":{"cpu":"0.0","mem":"0.6"},"127":{"cpu":"0.0","mem":"0.1"},"128":{"cpu":"0.0","mem":"0.6"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"1.0"},"288":{"cpu":"0.0","mem":"0.1"},"289":{"cpu":"0.0","mem":"1.3"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"0.7","mem":"1.8"},"297":{"cpu":"0.3","mem":"1.7"},"298":{"cpu":"0.0","mem":"0.8"},"299":{"cpu":"9.6","mem":"1.4"},"30":{"cpu":"0.0","mem":"0.0"},"302":{"cpu":"0.0","mem":"3.0"},"307":{"cpu":"15.3","mem":"1.7"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"35536":{"cpu":"0.0","mem":"0.0"},"35541":{"cpu":"0.0","mem":"0.0"},"35546":{"cpu":"0.3","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"7.0","mem":"0.3"},"99":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"4540.5","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"0.43,"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.38,"pid":289}},"gpu_usages":{"intel-vaapi":{"gpu":"4.5 %","mem":"- %"}},"main":{"camera_fps":5.1,"capture_pid":299,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":307,"pid":297,"process_fps":5.1,"skipped_fps":0.0},"service":{"last_updated":1702112385,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":53.0,"mount_type":"tmpfs","total":67.1,"used":14.1},"/media/frigate/clips":{"free":43892.6,"mount_type":"ext4","total":105089.3,"used":55811.1},"/media/frigate/recordings":{"free":43892.6,"mount_type":"ext4","total":105089.3,"used":55811.1},"/tmp/cache":{"free":4094.2,"mount_type":"tmpfs","total":4101.0,"used":6.8}},"temperatures":{},"uptime":46716,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP8M-T2599EW

### Any other information that may be helpful

I haven't setup any other substream for two reasons:
 - I want a very simple setup that works first.
 - We use the camera to check on our cats when we are away. The substream have less quality than the main stream and I'm not sure is worth to save the bandwith on the cost of quality, but I don't know what I'm doing so feel free to suggest anything.

_No response_

**Comment by NickM-27** [comment]
Also about the sub stream issue. You have hwaccel working so you can set detect to something like 1280x720 and the gpu will be used to do the scaling. This will reduce CPU usage because full 4k is not used for motion and object detection.

**Comment by gloaysa** [comment]
> Are you sure that audio is enabled on the camera? Easiest way to debug this will be to check to check go2rtc dashboard for stream info

Yes, I have audio enabled. From the go2rtc dashboard I get video and audio. Also, from HA, using Frigate's card I can select go2rtc stream and also get audio in there.

So I take my config seems correct and the issue could lie somewhere else?

**Comment by NickM-27** [comment]
Most likely the issue is config, camera has non aac audio selected. Can you show the go2rtc stream info

**Comment by gloaysa** [comment]
> Most likely the issue is config, camera has non aac audio selected. Can you show the go2rtc stream info

Is this what you mean?

```json
{
  "producers": [
    {
      "url": "rtsp://xx:xxxx@192.168.0.xxx:554/cam/realmonitor?channel=1\u0026subtype=0"
    },
    {
      "url": "ffmpeg:main#audio=opus"
    }
  ],
  "consumers": null
}

```

**Comment by NickM-27** [comment]
Yes but you need to get the info while watching live view

**Comment by gloaysa** [comment]
> Yes but you need to get the info while watching live view

here it is:

```json

{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.0.142:554/cam/realmonitor?channel=1\u0026subtype=0/",
      "remote_addr": "192.168.0.142:554",
      "user_agent": "go2rtc/1.2.0",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 8 PCMA/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1",
        "8 PCMA/8000, sinks=1"
      ],
      "recv": 13728459
    },
    {
      "url": "ffmpeg:main#audio=opus"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.0.237:49819 related :0",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0",
      "send": 13755954
    }
  ]
}


```

**Comment by NickM-27** [comment]
Right so you have pcma audio which won't work with recordings, you need aac. 

```
go2rtc:
  streams:
    main: # <- for RTSP streams
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.142:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:main#audio=aac"
```

Should get things working
