### ISSUE TITLE
[Support]: Tons of clips not saving on Portainer Docker install

### ISSUE THREAD

**Issue by GrandNagusQuark** [blakeblackshear/frigate#8908]
### Describe the problem you are having

I am having a lot of issues with clips not being saved due to videos going over the cache.
My system is a Beelink S12 Pro with a 12th Gen N100 Processor, PCIe NVME drive, 16GB of ram, a Coral TPU, and connected over ethernet. I have 4 5MP cameras scaled down to 1080P (camera does the scaling, not Frigate) over PoE. I record at 15 FPS.  System is running on Portainer in a docker container. Here is my Portainer Docker Compose:

`version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb"
    devices:
      - /dev/bus/usb/:/dev/bus/usb/
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/hubfiles/frigate/frigate.yml:/config/config.yml:ro
      - /media/recordings:/media/frigate
      - /home/user/frigate:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 13000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "554:554"
      - "8554:8554"

    environment:
      FRIGATE_RTSP_PASSWORD: "my_password"`

This happens randomly and often, and currently I do not have logs as I just rebooted the system. CPU usage is rarely over 210% (400% is full load, 4 core CPU). Ram usage is usually about 6GB max.

Another issue I am having is with Home Assistant, but not on the Home Assistant side. I receive notifications through Home Assistant, and when I tap on the notification, it brings me to the clip saved on the PC frigate is installed on. This rarely lets me view the clip, usually says could not save clip.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: ip
  port: port
  user: CCTV
  password: pass

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  width: 1920
  height: 1080
  mode: objects

record:
  enabled: true
  events:
    pre_capture: 20
    post_capture: 10
    retain:
      default: 21
      mode: active_objects

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 15
  max_disappeared: 25
  stationary:
    interval: 25

snapshots:
  enabled: true

objects:
  track:
    - cat
    - person


cameras:
  Driveway_and_Path:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: -f segment -segment_time 30 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:pass@192.168.50.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    ui:
      order: 0
      dashboard: true
    live:
      height: 1080
      quality: 8

  Deck:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:pass@192.168.50.10:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    ui:
      order: 1
      dashboard: true
    live:
      height: 1080
      quality: 8

  Driveway:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:pass@192.168.50.13:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    ui:
      order: 2
      dashboard: true
    live:
      height: 1080
      quality: 8
    zones:
      zone_0:
        coordinates: 0,1034,731,776,1149,801,1594,1080,1920,1080,1920,409,1106,278,1094,338,613,344,0,415
        objects:
          - person
    record:
      events:
        required_zones:
          - zone_0
    snapshots:
      required_zones:
        - zone_0

  Shed:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:pass@192.168.50.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    ui:
      order: 3
      dashboard: true
    live:
      height: 1080
      quality: 8
```

### Relevant log output

```shell
2023-12-09 11:11:16.525563982  [2023-12-09 11:11:16] frigate.record                 WARNING : Unable to keep up with recording segments in cache for Deck. Keeping the 5 most recent segments out of 6 and discarding the rest...
2023-12-09 19:38:53.643709762  [2023-12-09 19:38:53] frigate.object_processing      WARNING : Unable to create jpg because frame 1702172331.662526 is not in the cache
2023-12-09 19:38:53.643917580  [2023-12-09 19:38:53] frigate.object_processing      WARNING : Unable to save snapshot for 1702172324.32864-haxwnx.
2023-12-09 19:38:53.644036983  [2023-12-09 19:38:53] frigate.object_processing      WARNING : Unable to create clean png because frame 1702172331.662526 is not in the cache
2023-12-09 19:38:53.644135571  [2023-12-09 19:38:53] frigate.object_processing      WARNING : Unable to save clean snapshot for 1702172324.32864-haxwnx.
2023-12-09 19:38:53.644769961  [2023-12-09 19:38:53] frigate.object_processing      WARNING : Unable to create jpg because frame 1702172331.662526 is not in the cache
2023-12-09 19:38:53.672468934  [2023-12-09 19:38:53] frigate.object_processing      WARNING : Unable to create jpg because frame 1702172331.662526 is not in the cache
2023-12-09 19:38:53.672630584  [2023-12-09 19:38:53] frigate.object_processing      WARNING : Unable to send mqtt snapshot for 1702172324.32864-haxwnx.
```

### FFprobe output from your camera

```shell
[2] 10310
[1]   Done                    ffprobe rtsp://admin:pass@192.168.50.11:554/cam/realmonitor?channel=1
root@ed12bf64d640:/opt/frigate# ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Frigate stats

```json
{"Deck":{"camera_fps":15.1,"capture_pid":305,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":317,"pid":297,"process_fps":15.1,"skipped_fps":0.0},"Driveway":{"camera_fps":15.2,"capture_pid":307,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":321,"pid":298,"process_fps":15.2,"skipped_fps":0.0},"Driveway_and_Path":{"camera_fps":15.0,"capture_pid":301,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":306,"pid":296,"process_fps":15.0,"skipped_fps":0.0},"Shed":{"camera_fps":15.0,"capture_pid":312,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":322,"pid":299,"process_fps":15.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"5.5"},"1":{"cpu":"0.0","mem":"0.0"},"10013":{"cpu":"0.0","mem":"0.0"},"102":{"cpu":"6.0","mem":"2.0"},"10413":{"cpu":"0.0","mem":"0.0"},"10460":{"cpu":"0.0","mem":"0.0"},"10470":{"cpu":"0.0","mem":"0.0"},"10473":{"cpu":"0.0","mem":"0.0"},"10475":{"cpu":"0.0","mem":"0.0"},"117":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"139":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.3","mem":"0.5"},"287":{"cpu":"1.0","mem":"0.1"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"4.7","mem":"0.7"},"296":{"cpu":"2.3","mem":"0.9"},"297":{"cpu":"1.7","mem":"0.9"},"298":{"cpu":"2.0","mem":"0.8"},"299":{"cpu":"2.3","mem":"0.7"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.1"},"301":{"cpu":"13.0","mem":"0.7"},"304":{"cpu":"0.0","mem":"0.1"},"305":{"cpu":"10.0","mem":"0.7"},"306":{"cpu":"28.3","mem":"0.5"},"307":{"cpu":"12.3","mem":"0.7"},"31":{"cpu":"0.0","mem":"0.0"},"312":{"cpu":"12.7","mem":"0.7"},"314":{"cpu":"0.0","mem":"0.1"},"317":{"cpu":"30.7","mem":"0.5"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"0.0","mem":"0.1"},"321":{"cpu":"31.3","mem":"0.5"},"322":{"cpu":"31.3","mem":"0.5"},"323":{"cpu":"0.0","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"7224":{"cpu":"0.0","mem":"1.8"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.2"},"95":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"13645.5","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"2.66,"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.12,"pid":7224}},"gpu_usages":{"intel-vaapi":{"gpu":"15.86 %","mem":"- %"}},"service":{"last_updated":1702168222,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":2118.6,"mount_type":"tmpfs","total":2147.5,"used":28.9},"/media/frigate/clips":{"free":221146.1,"mount_type":"vfat","total":249998.2,"used":28852.2},"/media/frigate/recordings":{"free":221146.1,"mount_type":"vfat","total":249998.2,"used":28852.2},"/tmp/cache":{"free":12938.8,"mount_type":"tmpfs","total":13000.0,"used":61.2}},"temperatures":{},"uptime":4392,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EB-28MM
