### ISSUE TITLE
[Config Support]: MQTT secure connection problems

### ISSUE THREAD

**Issue by freedomlives** [blakeblackshear/frigate#8915]
### Describe the problem you are having

I am unable to connect to my mosquitto broker on a remote server which uses Let's Encrypt certificates.
Watching the Mosquitto logs, each time Frigate tries to connect, these errors are output:
`New connection from 69.218.231.160:39457 on port 8883.
OpenSSL Error[0]: error:0A00010B:SSL routines::wrong version number
Client <unknown> disconnected: Protocol error.
`

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 37.205.12.155
  # Optional: port (default: shown below)
  port: 8883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: cooperlake
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: ThePassword

# detectors:
#   ov:
#     type: openvino
#     device: AUTO
#     model:
#       path: /openvino-model/ssdlite_mobilenet_v2.xml

detectors:
  coral:
    type: edgetpu
    device: pci

# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bus
    - cat
    - dog
    - horse
    - sheep

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Z!OG4iU7^Kr08t@192.168.1.188:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:Z!OG4iU7^Kr08t@192.168.1.188:554/h264Preview_01_main
          roles:
            - record
      hwaccel_args: preset-vaapi
    
    detect:
      enabled: True
      width: 640
      height: 480

    snapshots: # <----- Enable snapshots
      enabled: True

    record:
      enabled: true

  Dome1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:B5kuzmG6@192.168.1.40:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:B5kuzmG6@192.168.1.40:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
    
    detect:
      enabled: True
      width: 640
      height: 480

    snapshots: # <----- Enable snapshots
      enabled: True

    record:
      enabled: True

  Dome2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:B5kuzmG6@192.168.1.41:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:B5kuzmG6@192.168.1.41:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
    
    detect:
      enabled: True
      width: 640
      height: 480

    snapshots: # <----- Enable snapshots
      enabled: True

    record:
      enabled: True

  KitchenPTZ:
    ffmpeg:
      inputs:
        - path: rtsp://admin:B5kuzmG6@192.168.1.208:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:B5kuzmG6@192.168.1.208:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
    
    detect:
      enabled: True
      width: 640
      height: 480

    snapshots: # <----- Enable snapshots
      enabled: True

    record:
      enabled: False

  DenPTZ:
    ffmpeg:
      inputs:
        - path: rtsp://admin:B5kuzmG6@192.168.1.239:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:B5kuzmG6@192.168.1.239:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      hwaccel_args: preset-vaapi
    
    detect:
      enabled: True
      width: 640
      height: 480

    snapshots: # <----- Enable snapshots
      enabled: True

    record:
      enabled: False

  Bullet1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:B5kuzmG6@192.168.1.42:554/stream2
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    
    detect:
      enabled: True
      width: 640
      height: 480
    
    objects:
      track:
        - person

    snapshots: # <----- Enable snapshots
      enabled: True

    record:
      enabled: True

birdseye:
  enabled: true
  mode: continuous

ui:
  timezone: America/New_York
```

### Relevant log output

```shell
New connection from 69.218.231.160:39457 on port 8883.
OpenSSL Error[0]: error:0A00010B:SSL routines::wrong version number
Client <unknown> disconnected: Protocol error.
```

### Frigate stats

```json
{"Bullet1":{"camera_fps":5.0,"capture_pid":786,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":793,"pid":746,"process_fps":5.0,"skipped_fps":0.0},"DenPTZ":{"camera_fps":5.0,"capture_pid":767,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":789,"pid":745,"process_fps":5.0,"skipped_fps":0.0},"Dome1":{"camera_fps":5.0,"capture_pid":752,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":759,"pid":740,"process_fps":5.0,"skipped_fps":0.0},"Dome2":{"camera_fps":5.1,"capture_pid":754,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":764,"pid":741,"process_fps":5.1,"skipped_fps":0.0},"KitchenPTZ":{"camera_fps":5.0,"capture_pid":761,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":782,"pid":743,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"0.0","mem":"0.1"},"1153":{"cpu":"0.0","mem":"0.0"},"1175":{"cpu":"0.3","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"147":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"177":{"cpu":"0.0","mem":"0.0"},"219":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"257":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"330":{"cpu":"0.0","mem":"0.0"},"355":{"cpu":"0.0","mem":"0.0"},"391":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"431":{"cpu":"0.0","mem":"0.0"},"481":{"cpu":"0.0","mem":"0.0"},"522":{"cpu":"0.0","mem":"0.0"},"554":{"cpu":"0.0","mem":"0.0"},"713":{"cpu":"0.0","mem":"0.5"},"719":{"cpu":"0.7","mem":"0.1"},"720":{"cpu":"0.7","mem":"0.7"},"721":{"cpu":"1.3","mem":"0.6"},"728":{"cpu":"9.6","mem":"0.6"},"729":{"cpu":"0.0","mem":"0.1"},"740":{"cpu":"0.3","mem":"0.6"},"741":{"cpu":"0.7","mem":"0.6"},"742":{"cpu":"0.0","mem":"0.1"},"743":{"cpu":"0.3","mem":"0.6"},"744":{"cpu":"0.0","mem":"0.1"},"745":{"cpu":"0.3","mem":"0.6"},"746":{"cpu":"0.3","mem":"0.6"},"747":{"cpu":"0.0","mem":"0.1"},"748":{"cpu":"1.0","mem":"0.5"},"749":{"cpu":"0.0","mem":"0.1"},"752":{"cpu":"0.3","mem":"0.5"},"753":{"cpu":"2.7","mem":"0.3"},"754":{"cpu":"0.7","mem":"0.5"},"757":{"cpu":"0.0","mem":"0.3"},"759":{"cpu":"2.3","mem":"0.3"},"761":{"cpu":"1.0","mem":"0.5"},"764":{"cpu":"2.7","mem":"0.3"},"765":{"cpu":"0.0","mem":"0.1"},"767":{"cpu":"0.3","mem":"0.5"},"769":{"cpu":"2.0","mem":"0.2"},"782":{"cpu":"4.0","mem":"0.3"},"785":{"cpu":"1.7","mem":"0.2"},"786":{"cpu":"1.0","mem":"0.5"},"788":{"cpu":"1.7","mem":"0.2"},"789":{"cpu":"3.3","mem":"0.3"},"793":{"cpu":"2.7","mem":"0.3"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.1"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"2.0","mem":"1.0"},"MiB":{"cpu":"13111.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.5,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.15,"pid":720}},"doorbell":{"camera_fps":5.1,"capture_pid":748,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":753,"pid":728,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"2.17 %","mem":"- %"}},"service":{"last_updated":1702247449,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":95.0,"mount_type":"tmpfs","total":100.7,"used":5.6},"/media/frigate/clips":{"free":912683.5,"mount_type":"ext4","total":983351.1,"used":20640.6},"/media/frigate/recordings":{"free":912683.5,"mount_type":"ext4","total":983351.1,"used":20640.6},"/tmp/cache":{"free":961.1,"mount_type":"tmpfs","total":1000.0,"used":38.9}},"temperatures":{"apex_0":36.55},"uptime":179,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

**Comment by mariodivece** [comment]
I found the issue -- try using the `ca-certificates.crt` file from your host instead of what is provided inside the frigate image.

in your `docker-compose.yaml` file, map the host folder to your container folder:

```yaml
    volumes:
      - ...
      - /etc/ssl/certs:/certs:ro
      - ...
```

And now in your frigate `config.yaml`

```yaml
mqtt:
  enabled: true
  host: mqtt.things.mydomain.com
  port: 1933
  user: YOURUSER
  password: YOURPASS
  stats_interval: 60
  tls_ca_certs: /certs/ca-certificates.crt
  tls_insecure: true
```

make sure you call:

```bash
docker compose down
docker compose up -d --force-recreate
```

That should work.
