### ISSUE TITLE
[Config Support]: Camera used to work with H265 in GO2RTC, but not anymore!?

### ISSUE THREAD

**Issue by diegoweb** [blakeblackshear/frigate#8944]
### Describe the problem you are having

Hey guys!

I have 4 IP cameras running with H265 enabled in the main stream (they are all different models from DAHUA). All of them used to work since July to about September.
Now I just can't figure out why one camera can no longer work with H265. There's no ERRORS LOGS right now after I fiddle with the config, but I still can't have this camera GO2RTC stream work with H265. If I enable H264, it works great.

Again, I have 4 cameras, and besides this one in particular, all of them are working great with H265. I even tried to update the camera firmware, but it doesn't make sense it would just stop working in the camera side, since this camera doesn't get auto-updates.

My setup is:
Alder Lake CPU > Proxmox with PCI-e Passthrough > Ubuntu VM running Docker > Frigate.
The GO2RTC stream that is bugged is the "FRENTE". Even if I disable the audio from the stream, it doesn't work. So far I could only figure out that the h265 codec is the reason why it's not working.

In go2rtc dashboard, I can't watch the stream for this camera when it's running in H265, I get a black screen.
In Cameras/Birdseye in Frigate UI, I can see all cameras working great.
For "FRENTE" camera only, if it's running in H265, the recordings are all "corrupted" to be seen via web browser. I need to download the recordings to be able to watch the content.

The errors that I could see in logs (that are not present anymore) are the ones below:

> Invalid data found when processing input
> method DESCRIBE failed: 404 Not Found

### Version

0.12.1-367D724

### Frigate config file

```yaml
logger:
  # Optional: default log level (default: shown below)
  default: info

mqtt:
  enabled: False
  host: "{FRIGATE_MQTT_HOST}"
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

birdseye:
  enabled: True
  mode: continuous
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 7
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
      - bicycle
      - motorcycle
      - dog
      - cat
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 15
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: false
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: True
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 15
    # Optional: Per object retention days
    objects:
      dog: 7
      cat: 7

go2rtc:
  streams:
    garagem: 
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.92:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:garagem#audio=opus" # <- copy of the stream which transcodes audio to opus
    frente:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.91:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:garagem#audio=opus" # <- copy of the stream which transcodes audio to opus
    pomar:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.93:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:pomar#audio=opus" # <- copy of the stream which transcodes audio to opus
    escritorio:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.94:554/cam/realmonitor?channel=1&subtype=0
      #- "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.94:554/cam/realmonitor?channel=1&subtype=1#audio=opus" # <- copy of the stream which transcodes audio to opus

cameras:
  GARAGEM:
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.92:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garagem
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True # <---- turn on detection
      width: 704
      height: 576
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat

  FRENTE:
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.91:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frente
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True # <---- turn on detection
      width: 704
      height: 576
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat

  POMAR:
    ui:
      order: 3
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.93:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/pomar
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True # <---- turn on detection
      width: 704
      height: 576
    objects:
      track:
        - person
        - dog
        - cat


  ESCRITORIO:
    ui:
      order: 4
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.94:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/escritorio
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True # <---- turn on detection
      width: 704
      height: 576
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat



database:
  path: /db/frigate.db
```

### Relevant log output

```shell
Invalid data found when processing input
method DESCRIBE failed: 404 Not Found
```

### Frigate stats

```json
{"ESCRITORIO":{"camera_fps":5.1,"capture_pid":452,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":465,"pid":441,"process_fps":5.1,"skipped_fps":0.0},"FRENTE":{"camera_fps":5.1,"capture_pid":445,"detection_enabled":1,"detection_fps":3.1,"ffmpeg_pid":453,"pid":439,"process_fps":5.1,"skipped_fps":0.0},"GARAGEM":{"camera_fps":5.1,"capture_pid":442,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":447,"pid":438,"process_fps":5.1,"skipped_fps":0.0},"POMAR":{"camera_fps":5.1,"capture_pid":446,"detection_enabled":1,"detection_fps":3.2,"ffmpeg_pid":459,"pid":440,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.6"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"6.3","mem":"0.1"},"110":{"cpu":"0.0","mem":"0.0"},"111":{"cpu":"2.3","mem":"1.3"},"119":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.2"},"142":{"cpu":"0.0","mem":"0.1"},"146":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"154":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"165":{"cpu":"0.0","mem":"0.0"},"187":{"cpu":"0.0","mem":"0.1"},"2118":{"cpu":"0.0","mem":"0.0"},"2122":{"cpu":"0.0","mem":"0.0"},"2126":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"427":{"cpu":"0.0","mem":"0.5"},"432":{"cpu":"0.3","mem":"0.1"},"433":{"cpu":"13.3","mem":"2.2"},"434":{"cpu":"0.7","mem":"0.6"},"438":{"cpu":"0.3","mem":"0.6"},"439":{"cpu":"3.0","mem":"0.6"},"440":{"cpu":"4.7","mem":"0.6"},"441":{"cpu":"0.0","mem":"0.6"},"442":{"cpu":"0.3","mem":"0.5"},"445":{"cpu":"0.3","mem":"0.5"},"446":{"cpu":"0.7","mem":"0.5"},"447":{"cpu":"2.7","mem":"0.3"},"452":{"cpu":"0.7","mem":"0.5"},"453":{"cpu":"2.0","mem":"0.3"},"459":{"cpu":"2.3","mem":"0.3"},"460":{"cpu":"1.3","mem":"0.1"},"465":{"cpu":"2.0","mem":"0.3"},"467":{"cpu":"1.0","mem":"0.1"},"468":{"cpu":"0.3","mem":"0.1"},"471":{"cpu":"0.0","mem":"0.3"},"472":{"cpu":"0.3","mem":"0.1"},"473":{"cpu":"0.0","mem":"0.3"},"474":{"cpu":"0.0","mem":"0.1"},"475":{"cpu":"0.0","mem":"0.1"},"476":{"cpu":"0.0","mem":"0.1"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"11686.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"load","mem":"average:"}},"detection_fps":6.3,"detectors":{"ov":{"detection_start":0.0,"inference_speed":13.13,"pid":433}},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"service":{"last_updated":1702424329,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":264.0,"mount_type":"tmpfs","total":268.4,"used":4.4},"/media/frigate/clips":{"free":164185.9,"mount_type":"ext4","total":527293.5,"used":336247.3},"/media/frigate/recordings":{"free":164185.9,"mount_type":"ext4","total":527293.5,"used":336247.3},"/tmp/cache":{"free":990.5,"mount_type":"tmpfs","total":1000.0,"used":9.5}},"temperatures":{},"uptime":1096,"version":"0.12.1-367d724"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

It used to work great with the config above.
The issues seems to be related with the H265 codec, but I could be wrong.
