### ISSUE TITLE
[Support]:  Frigate stops displaying cameras after a few days

### ISSUE THREAD

**Issue by kornyhiv** [blakeblackshear/frigate#8949]
### Describe the problem you are having

First of all, thank you for creating and supporting this wonderful project.  New to this, and learning every day.

Here is my issue.
Frigate stops displaying cameras after a few days of running.

![image](https://github.com/blakeblackshear/frigate/assets/29285614/afbfdd69-27e2-418d-93bc-6c2808969741)

I also see an export task stuck there spinning, and is unable to stop, complete, or fail. (Restarting docker container or Ubuntu VM to no difference)

![image](https://github.com/blakeblackshear/frigate/assets/29285614/911eb313-554b-4aaa-b461-985b1616a333)

Running a combination of Reolink's: RLC-410 (H.264), RLC-820a (H.265), and Chinese PTZ (H.264 or H.265)

VM, 64 CPU, 2 USB Corals, 32GB of RAM, 2TB+ SCSI ESXI 10K Disks. NVIDIA Quadro K1200.
Ubuntu 20.04 Server solely running Frigate.

![image](https://github.com/blakeblackshear/frigate/assets/29285614/2aff4e5b-92c8-45a7-ba38-95609dad593d)

### Version

0.13.0-614A36A and go2rtc 1.8.4

### Frigate config file

```yaml
mqtt:
  enabled: false  # Set this to true if you want to use MQTT
  host: mqtt.server.com
  user: mqtt_user
  password: password


detectors:
  coral:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

detect:
  stationary:
    interval: 50
    threshold: 50

snapshots:
  enabled: true
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 10
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100


record:
  enabled: true
  retain:
    days: 15
    mode: motion
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 30
      mode: motion
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.00054*PTS -r 30



objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
  - person
  - face
  - license_plate
  - car
  - bicycle
  - motorcycle
  - bus
  - amazon
  - fedex
  - ups
  - cat
  - package
  - dog
  - horse
  - sheep
  - cow
  - bear
  - airplane
  - bird
  filters:
    car:
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.8

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
  quality: 1

go2rtc:
  streams:
    Gate_Corner_Left:
    - ffmpeg:rtsp://frigate:XXXX@192.168.2.220:554/h265Preview_01_main
    - ffmpeg:Gate_Corner_Left#video=h264#hardware

    Gate_Corner_Left_sub:
    - rtsp://frigate:XXXX@192.168.2.220:554/h264Preview_01_sub

    Gate_Corner_Right:
    - ffmpeg:rtsp://frigate:XXXX@192.168.2.221:554/h265Preview_01_main
    - ffmpeg:Gate_Corner_Right#video=h264#hardware

    Gate_Corner_Right_sub:
    - rtsp://frigate:XXXX@192.168.2.221:554/h264Preview_01_sub

    Gate_Center_Left:
    - ffmpeg:rtsp://frigate:XXXX@192.168.2.222:554/h265Preview_01_main
    - ffmpeg:Gate_Center_Left#video=h264#hardware

    Gate_Center_Left_sub:
    - rtsp://frigate:XXXX@192.168.2.222:554/h264Preview_01_sub

    Gate_Center_Right:
    - ffmpeg:rtsp://frigato:XXXX@192.168.2.228:554/h265Preview_01_main
    - ffmpeg:Gate_Center_Right#video=h264#hardware

    Gate_Center_Right_sub:
    - rtsp://frigato:XXXX@192.168.2.228:554/h264Preview_01_sub

    Gate_Center_Inside:
    - ffmpeg:rtsp://frigate:XXXX@192.168.2.224:554/h265Preview_01_main
    - ffmpeg:Gate_Center_Inside#video=h264#hardware

    Gate_Center_Inside_sub:
    - rtsp://frigate:XXXX@192.168.2.224:554/h264Preview_01_sub

    Chicken_Nest:
    - ffmpeg:rtsp://frigate:XXXX@192.168.2.219:554/h265Preview_01_main
    - ffmpeg:Chicken_Nest#video=h264#hardware

    Chicken_Nest_sub:
    - rtsp://frigate:XXXX@192.168.2.219:554/h264Preview_01_sub

    Camera_PTZ:
    - ffmpeg:rtsp://admin:XXXX@192.168.2.200:554/11
    - ffmpeg:Camera_PTZ#video=h264#hardware

    Camera_PTZ_sub:
    - rtsp://admin:XXXX@192.168.2.200:554/12

    Balcon:
    - rtsp://frigate:XXXX@192.168.2.203:554/h264Preview_01_main

    Balcon_sub:
    - rtsp://frigate:XXXX@192.168.2.203:554/h264Preview_01_sub

    Parking_Lot:
    - rtsp://frigate:XXXX@192.168.2.201:554/h264Preview_01_main

    Parking_Lot_sub:
    - rtsp://frigate:XXXX@192.168.2.201:554/h264Preview_01_sub

    Basement_Aquarium:
    - rtsp://frigate:XXXX@192.168.2.211:554/h264Preview_01_main

    Basement_Aquarium_sub:
    - rtsp://frigate:XXXX@192.168.2.211:554/h264Preview_01_sub

    Basement_Outside:
    - rtsp://frigate:XXXX@192.168.2.209:554/h264Preview_01_main

    Basement_Outside_sub:
    - rtsp://frigate:XXXX@192.168.2.209:554/h264Preview_01_sub

    Basement_Inside:
    - rtsp://frigate:XXXX@192.168.2.210:554/h264Preview_01_main

    Basement_Inside_sub:
    - rtsp://frigate:XXXX@192.168.2.210:554/h264Preview_01_sub

    Chicken_Coop:
    - rtsp://frigate:XXXX@192.168.2.218:554/h264Preview_01_main

    Chicken_Coop_sub:
    - rtsp://frigate:XXXX@192.168.2.218:554/h264Preview_01_sub

    Shed:
    - rtsp://frigate:XXXX@192.168.2.206:554/h264Preview_01_main

    Shed_sub:
    - rtsp://frigate:XXXX@192.168.2.206:554/h264Preview_01_sub

    Dog_House:
    - rtsp://frigate:XXXX@192.168.2.217:554/h264Preview_01_main

    Dog_House_sub:
    - rtsp://frigate:XXXX@192.168.2.217:554/h264Preview_01_sub

    Parking_Garage:
    - rtsp://frigate:XXXX@192.168.2.202:554/h264Preview_01_main

    Parking_Garage_sub:
    - rtsp://frigate:XXXX@192.168.2.202:554/h264Preview_01_sub

    Front_Camera:
    - rtsp://frigate:XXXX@192.168.2.227:554/h265Preview_01_main

    Front_Camera_sub:
    - rtsp://frigate:XXXX@192.168.2.227:554/h264Preview_01_sub

    Backyard:
    - rtsp://frigate:XXXX@192.168.2.207:554/h264Preview_01_main

    Backyard_sub:
    - rtsp://frigate:XXXX@192.168.2.207:554/h264Preview_01_sub



cameras:
  Balcon:
    ui:
      order: 1
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Balcon_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Balcon
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7




  Parking_Lot:
    ui:
      order: 2
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Parking_Lot_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Parking_Lot
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7


  Basement_Aquarium:
    ui:
      order: 3
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Basement_Aquarium_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Basement_Aquarium
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7


  Basement_Outside:
    ui:
      order: 4
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Basement_Outside_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Basement_Outside
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7



  Basement_Inside:
    ui:
      order: 5
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Basement_Inside_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Basement_Inside
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7



  Chicken_Coop:
    ui:
      order: 6
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Chicken_Coop_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Chicken_Coop
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
      - person
      - bird
      - cat
      - dog


  Shed:
    ui:
      order: 7
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Shed_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Shed
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7


  Dog_House:
    ui:
      order: 8
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Dog_House_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Dog_House
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7


  Parking_Garage:
    ui:
      order: 9
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Parking_Garage_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Parking_Garage
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
      - person
      - car
      - cat
      - dog


  Gate_Corner_Left:
    ui:
      order: 10
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Gate_Corner_Left_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Gate_Corner_Left
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 15


  Gate_Corner_Right:
    ui:
      order: 11
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Gate_Corner_Right_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Gate_Corner_Right
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 15


  Gate_Center_Right:
    ui:
      order: 12
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Gate_Center_Right_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Gate_Center_Right
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 15


  Gate_Center_Left:
    ui:
      order: 13
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Gate_Center_Left_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Gate_Center_Left
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 15


  Camera_PTZ:
    ui:
      order: 14
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Camera_PTZ_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Camera_PTZ
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: false
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 352
      fps: 15

  Front_Camera:
    ui:
      order: 15
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Front_Camera_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Front_Camera
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
       record: preset-record-generic-audio-copy
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 15

 

  Gate_Center_Inside:
    ui:
      order: 16
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Gate_Center_Inside_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Gate_Center_Inside
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 15


  Chicken_Nest:
    ui:
      order: 17
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Chicken_Nest_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Chicken_Nest
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
      - cat
      - dog
      - bird


  Backyard:
    ui:
      order: 18
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Backyard_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
      - path: rtsp://127.0.0.1:8554/Backyard
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    audio:
      enabled: true
      listen:
      - scream
      - speech
      - yell
      - skidding
      - tire_squeal
      - emergency_vehicle
      - gunshot
      - glass
      - crack
      - shatter
      - smash
      - breaking
    detect:
      width: 640
      height: 360
      fps: 7
```

### Relevant log output

```shell
https://drive.google.com/file/d/1dco2GQoaRz9AkXthPcTPMjjaSq6n_SwB/view?usp=sharing

Sorry Github gave an error that the log was too long.

"There was an error creating your issue: body is too long, body is too long (maximum is 65536 characters)."
```

### FFprobe output from your camera

```shell
RLC-410:

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://frigate:XXXX@192.168.2.203:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 30 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

RLC-820A:

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://frigate:XXXX@192.168.2.228:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000125, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 24.92 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp


Chinese PTZ:

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:XXXXX@192.168.2.200:554/11':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 0.08 fps, 0.08 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Frigate stats

```json
SYSTEM 0.13.0-614A36A
go2rtc 1.8.4 dashboard
Last refreshed: 50s ago

DETECTORS
coral
P-ID	Inference Speed	CPU %	Memory %
2407647	51.95 ms	0.0%	0.0%
coral2
P-ID	Inference Speed	CPU %	Memory %
2391496	170238260402.44 ms	0.0%	0.0%
GPUS
VAINFO
Quadro K1200
GPU %	Memory %	Decoder %	Encoder %
3.0%	15.77%	3.0%	0.0%
CAMERAS
Balcon
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	1648994	7.1	3.6%	0.3%
Capture	2532	0.3	2.7%	0.1%
Detect	2488	0.2 (6.8 skipped)	7.0%	0.1%
Parking Lot
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	2043684	7.1	3.8%	0.3%
Capture	2536	0.2	2.2%	0.1%
Detect	2489	0.2 (6.9 skipped)	7.7%	0.1%
Basement Aquarium
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	1649230	7.1	4.4%	0.3%
Capture	2539	3.5	2.5%	0.1%
Detect	2492	0.1 (6.1 skipped)	5.7%	0.1%
Basement Outside
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561019	7.1	4.1%	0.3%
Capture	2544	7.1	2.7%	0.1%
Detect	2494	0 (0 skipped)	5.0%	0.1%
Basement Inside
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3560094	7.1	4.0%	0.3%
Capture	2548	1.9	2.3%	0.1%
Detect	2497	0.2 (5.7 skipped)	7.9%	0.1%
Chicken Coop
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3560075	7.2	4.0%	0.3%
Capture	2553	0.2	2.9%	0.1%
Detect	2499	0.2 (7 skipped)	6.9%	0.1%
Shed
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3560138	7	3.6%	0.3%
Capture	2565	0.1	2.1%	1.6%
Detect	2502	0.2 (6.9 skipped)	10.2%	0.1%
Dog House
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	1649143	7	3.7%	0.3%
Capture	2571	7	2.2%	0.1%
Detect	2504	0 (0 skipped)	4.7%	0.1%
Parking Garage
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561385	7.1	3.6%	0.3%
Capture	2579	7.1	2.7%	0.1%
Detect	2507	0 (0 skipped)	4.0%	0.1%
Gate Corner Left
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561852	15	6.6%	0.1%
Capture	2589	0.1	5.3%	0.1%
Detect	2510	0.2 (14.9 skipped)	8.9%	0.1%
Gate Corner Right
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561041	15.2	7.2%	0.1%
Capture	2595	0.2	4.9%	0.1%
Detect	2512	0.2 (15 skipped)	8.8%	0.1%
Gate Center Right
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561848	15.1	6.7%	0.1%
Capture	2601	0.2	4.8%	0.1%
Detect	2515	0.2 (14.9 skipped)	9.9%	0.1%
Gate Center Left
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561011	15	5.8%	0.1%
Capture	2611	0.1	4.6%	0.1%
Detect	2517	0.2 (15 skipped)	8.8%	0.1%
Camera PTZ
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561828	15.1	5.2%	0.1%
Capture	2620	0.1	4.7%	0.1%
Detect	2520	0.2 (15 skipped)	7.9%	0.1%
Front Camera
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3560329	15	6.6%	0.1%
Capture	2626	0.1	5.7%	0.1%
Detect	2522	0.2 (14.9 skipped)	7.1%	0.1%
Gate Center Inside
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561846	15.1	7.3%	0.1%
Capture	2676	0.1	5.1%	0.1%
Detect	2525	0.2 (15 skipped)	7.7%	0.1%
Chicken Nest
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561850	7.1	4.3%	0.1%
Capture	2685	0.2	2.4%	0.1%
Detect	2527	0.2 (6.9 skipped)	7.3%	0.1%
Backyard
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	3561854	7	4.2%	0.3%
Capture	2689	7	2.6%	0.1%
Detect	2530	0 (0 skipped)	4.6%	0.1%
OTHER PROCESSES
Logger
P-ID	CPU %	Avg CPU %	Memory %
2455	0.0%	0%	0.0%
Recording
P-ID	CPU %	Avg CPU %	Memory %
2457	36.0%	39%	0.6%
Go2rtc
P-ID	CPU %	Avg CPU %	Memory %
89	- %	- %	- %
AudioDetector
P-ID	CPU %	Avg CPU %	Memory %
2702	16.3%	21%	0.4%
System stats update automatically every 60 seconds.
```

### Operating system

Linux Other - Ubuntu Server 20.04

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-410, RLC820A, and Chinese PTZ
