### ISSUE TITLE
Works amazing, then crashes home assistant?!

### ISSUE THREAD

**Issue by lowgoz** [blakeblackshear/frigate#895]
**Describe the bug**
Frigate causes home assistant to grind to a halt after periods of detection. Terminating the frigate docker container causes home assistant to immediately load whatever screen which had stalled. 

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.3
ffmpeg: {}

cameras:
  frontyard:
    width: 1280
    height: 720
    ffmpeg:
      inputs:
        - path: >-
            rtsp://****:*****@192.168.1.53/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - clips
            - rtmp
    fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    clips:
      enabled: true
      retain:
        objects:
          person: 3
          car: 3
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 407,63,546,49,1149,50,1126,0,461,0,169,0,0,0,0,110
            - 982,26,1198,100,1166,150,1148,218,927,99
        person:
          mask:  
            - 0,0,0,110,1013,0,1013,74,587,112,0,231
            - 1198,364,1068,558,1020,429,1073,340,1112,319
    motion:
      mask:
        - 320,65,678,56,1019,51,1085,0,0,0,0,121

  paddy:
    width: 1280
    height: 720
    ffmpeg:
      inputs:
        - path: >-
            rtsp://****:*****@192.168.1.88/11
          roles:
            - detect
            - clips

            - rtmp
    fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    clips:
      enabled: true
      retain:
        objects:
          person: 1
    objects:
      track:
        - person
    motion:
      mask:
        - 0,720,1280,720,1280,0,0,0



  alex:
    width: 1280
    height: 720
    ffmpeg:
      inputs:
        - path: rtsp://****:*****@192.168.1.206/11
          roles:
            - detect
            - clips
            - rtmp
    fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    clips:
      enabled: true
      retain:
        objects:
          person: 1
          
    objects:
      track:
        - person
    motion:
      mask:
        - 0,0,1280,0,1280,720,0,720


  backyard:
    width: 1280
    height: 720
    ffmpeg:
      inputs:
        - path: rtsp://****:*****@192.168.1.54/11
          roles:
            - detect
            - clips
            - rtmp
    fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    clips:
      enabled: true
      retain:
        objects:
          person: 1
          
    objects:
      track:
        - person

  garage:
    width: 640
    height: 360
    ffmpeg:
      inputs:
        - path: rtsp://root:root@192.168.1.248:8554/unicast
          roles:
            - detect
            - clips
            - rtmp
    fps: 1
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
    clips:
      enabled: true
      retain:
        objects:
          person: 1
          
    objects:
      track:
        - person



record:
  enabled: false
  retain_days: 3
logger: {}
```

**Frigate container logs**
```
* Starting nginx nginx
...done.
Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
frigate.app INFO : Camera processor started for frontyard: 37
frigate.app INFO : Camera processor started for paddy: 39
frigate.app INFO : Camera processor started for alex: 41
frigate.app INFO : Camera processor started for backyard: 43
frigate.app INFO : Camera processor started for garage: 44
frigate.app INFO : Capture process started for frontyard: 45
frigate.app INFO : Capture process started for paddy: 46
frigate.app INFO : Capture process started for alex: 47
frigate.app INFO : Capture process started for backyard: 49
frigate.app INFO : Capture process started for garage: 57
detector.coral INFO : Starting detection process: 34
frigate.edgetpu INFO : Attempting to load TPU as usb
frigate.edgetpu INFO : TPU found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c83ba1e140] moov atom not found
/tmp/cache/garage-20210309201021.mp4: Invalid data found when processing input
frigate.events INFO : bad file: garage-20210309201021.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55fa68637140] moov atom not found
/tmp/cache/paddy-20210309201023.mp4: Invalid data found when processing input
frigate.events INFO : bad file: paddy-20210309201023.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e8d34a3140] moov atom not found
/tmp/cache/backyard-20210309201024.mp4: Invalid data found when processing input
frigate.events INFO : bad file: backyard-20210309201024.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5632fccb7140] moov atom not found
/tmp/cache/alex-20210309201031.mp4: Invalid data found when processing input
frigate.events INFO : bad file: alex-20210309201031.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5561dbcce140] moov atom not found
/tmp/cache/frontyard-20210309201032.mp4: Invalid data found when processing input
frigate.events INFO : bad file: frontyard-20210309201032.mp4```
```
**Frigate stats**
```
json
{
  "alex": {
    "camera_fps": 5.1, 
    "capture_pid": 47, 
    "detection_fps": 0.0, 
    "pid": 41, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "backyard": {
    "camera_fps": 5.0, 
    "capture_pid": 49, 
    "detection_fps": 0.0, 
    "pid": 43, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.9, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 11.13, 
      "pid": 34
    }
  }, 
  "frontyard": {
    "camera_fps": 5.1, 
    "capture_pid": 45, 
    "detection_fps": 0.0, 
    "pid": 37, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "garage": {
    "camera_fps": 1.0, 
    "capture_pid": 57, 
    "detection_fps": 0.9, 
    "pid": 44, 
    "process_fps": 1.0, 
    "skipped_fps": 0.0
  }, 
  "paddy": {
    "camera_fps": 5.1, 
    "capture_pid": 46, 
    "detection_fps": 0.0, 
    "pid": 39, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 530.0, 
        "mount_type": "tmpfs", 
        "total": 536.9, 
        "used": 6.9
      }, 
      "/media/frigate/clips": {
        "free": 4258899.7, 
        "mount_type": "fuse.shfs", 
        "total": 6997961.3, 
        "used": 2739061.5
      }, 
      "/media/frigate/recordings": {
        "free": 4258899.7, 
        "mount_type": "fuse.shfs", 
        "total": 6997961.3, 
        "used": 2739061.5
      }, 
      "/tmp/cache": {
        "free": 33832.6, 
        "mount_type": "btrfs", 
        "total": 42949.7, 
        "used": 6339.8
      }
    }, 
    "uptime": 306, 
    "version": "0.8.4-5043040"
  }
}

```

**FFprobe from your camera**
```still working on getting this for you```

**Screenshots**
``````NA``````
**Computer Hardware**
`````` - OS: Unraid. Home assistant on VM with Frigate on docker. Server 3.4ghz with 16gb Ram. 
 - Install method: Unraid frigate package
 - Virtualization: HA is Virtualised with Frigate Dockerised
 - Coral Version: USB (with 11 interface speed?!) Also have the Unraid community drivers installed
 - Network Setup: hardwired with a single wifi camera running at 1FPS.
``````
**Camera Info:**
`````` - Manufacturer: Dahua 
 - Model: IPC-HDW4431C-A-V2
 - Resolution: 1080
 - FPS: 5

2 of the below
 - Manufacturer: SV3C
 - Model: Generic 1080 bulle cams
 - Resolution: 720
  - FPS: 5

 - Manufacturer: Dafang hacked 
 - Model: Generic 1080 xiaomi wifi camera
 - Resolution: 640x360
  - FPS: 1
``````
**Additional context**
``````I've tried everything including upgrading to a coral and moving the frigate instance between a docker environment and the home assistant supervised add on. 

Seems to work fine with a single camera but as soon as i load it up with additional cameras it was almost like home assistant was running out / ran out of memory and ended up rebooting itself or locking. With the TPU being recognised, im confused as to why only a couple of cams running at 5fps seem to be killing the system? Frigate however works smooth as butter during all of this drama.. 

Apart from that, it's working AMAZINGLY and detections are perfect. It's the missing piece of home automation and if i can get this working it's going to be absolutely epic. 
``````
