### ISSUE TITLE
[Detector Support]: coral TPU on raspberry Pi 5 does not record without CPU 

### ISSUE THREAD

**Issue by arne182** [blakeblackshear/frigate#8965]
### Describe the problem you are having

2023-12-14 22:13:13.362996276  [INFO] Starting Frigate...
2023-12-14 22:13:14.168779792  Error importing detector runtime: /usr/local/lib/python3.9/dist-packages/openvino/pyopenvino.cpython-39-aarch64-linux-gnu.so: ELF load command alignment not page-aligned
2023-12-14 22:13:14.386695199  [2023-12-14 22:13:14] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-14 22:13:14.414537213  [2023-12-14 22:13:14] peewee_migrate                 INFO    : Starting migrations
2023-12-14 22:13:14.420253313  [2023-12-14 22:13:14] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-14 22:13:14.448266087  [2023-12-14 22:13:14] detector.coral                 INFO    : Starting detection process: 289

### Version

0.12.1-367D724

### Frigate config file

```yaml
database:
    path: /media/frigate/frigate.db
mqtt:
  enabled: False

detectors:



  coral:
    type: edgetpu
    device: usb

objects:
  track:
   - person
   - car

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects

cameras:
  parkplatz:
      
        
    zones:
      2OG:
            coordinates: 1824,1088,985,1039,1270,0,1820,0
            objects:
              - car
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.188.167:554
          roles:
            - detect
            - record
    detect:
      width: 3664
      height: 1088
      fps: 12
```

### docker-compose file or Docker CLI command

```yaml
.
```

### Relevant log output

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
