### ISSUE TITLE
[Support]: 404 error when deleting Export from web interface 

### ISSUE THREAD

**Issue by T3chArmy** [blakeblackshear/frigate#8987]
### Describe the problem you are having

When attempting to delete an export via the web interface, a 404 error is produced.

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
# yaml-language-server: $schema=http://10.112.0.4:5000/api/config/schema.json

go2rtc:
  streams:
    front_yard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.112.0.10/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:front_yard#audio=opus
    back_yard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.112.0.11/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:back_yard#audio=opus
    rear_garage:
      - nest:?client_id={FRIGATE_NEST_CLIENT_ID}&client_secret={FRIGATE_NEST_CLIENT_SECRET}&device_id={FRIGATE_NEST_DEVICE_ID_REARGARAGE}&project_id={FRIGATE_NEST_PROJECT_ID}&refresh_token={FRIGATE_NEST_REFRESH_TOKEN}
      - ffmpeg:rear_garage#audio=opus
    test_cam:
      - nest:?client_id={FRIGATE_NEST_CLIENT_ID}&client_secret={FRIGATE_NEST_CLIENT_SECRET}&device_id={FRIGATE_NEST_DEVICE_ID_TESTCAM}&project_id={FRIGATE_NEST_PROJECT_ID}&refresh_token={FRIGATE_NEST_REFRESH_TOKEN}
      - ffmpeg:test_cam#audio=opus
  webrtc:
    candidates:
      - 10.112.0.4:8555
      - stun:8555

mqtt:
  host: 10.112.0.6
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

cameras:
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - audio
            - record
            - detect
    detect:
      width: 1280
      height: 960
      fps: 5
    motion:
      mask:
        - 20,7,375,7,375,48,20,48
    ui:
      order: 1
    zones:
      driveway:
        coordinates: 1296,972,593,972,190,972,0,802,26,766,49,592,301,346,646,138,724,72,1166,147,1296,407
      lawn:
        coordinates: 293,353,76,538,0,391,0,224,162,143,269,106,735,78
    snapshots:
      required_zones:
        - driveway
        - lawn
    record:
      events:
        required_zones:
          - driveway
          - lawn
    objects:
      track:
        - person
        - face
        - car
        - license_plate
        - fedex
        - ups
        - amazon
        - package
        - dog
        - cat
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - audio
            - record
            - detect
    detect:
      width: 1280
      height: 960
      fps: 5
    motion:
      mask:
        - 20,7,375,7,375,48,20,48
    ui:
      order: 2
    zones:
      attached_garage_back_door:
        coordinates: 1296,972,1179,910,692,421,802,371,810,257,989,340,1014,55,1296,114,1296,650
      behind_attached_garage:
        coordinates: 0,972,0,608,657,412,907,604,1193,893,1114,972
      distant_backyard:
        coordinates: 808,386,821,116,487,147,0,257,0,603
      detached_garage_driveway:
        coordinates: 254,110,0,227,0,329,472,158,690,128,691,0,577,0,573,48
    snapshots:
      required_zones:
        - attached_garage_back_door
        - behind_attached_garage
        - distant_backyard
        - detached_garage_driveway
    record:
      events:
        required_zones:
          - attached_garage_back_door
          - behind_attached_garage
          - distant_backyard
          - detached_garage_driveway
  rear_garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_garage
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    audio:
      enabled: false
    #motion:
    #  mask:
    #    - 0,0,0,0
    ui:
      order: 3
    #zones:
    #  driveway:
    #   coordinates: 0,0,0,0
    #record:
    #  events:
    #    required_zones:
    #      - driveway
    #      - lawn
  test_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/test_cam
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    audio:
      enabled: false
    #motion:
    #  mask:
    #    - 0,0,0,0
    ui:
      order: 4
    #zones:
    #  driveway:
    #   coordinates: 0,0,0,0
    #record:
    #  events:
    #    required_zones:
    #      - driveway
    #      - lawn


audio:
  enabled: true
  listen:
    - bark
    - scream
    - speech
    - yell
    - skidding
    - tire_squeal
    - emergency_vehicle
    - smoke_detector
    - fire_alarm
    - gunshot
    - glass
    - crack
    - shatter
    - smash
    - breaking

snapshots:
  enabled: true
  crop: true
  quality: 90
  timestamp: true

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 42
      mode: active_objects

objects:
  track:
    - person
    - face
    - car
    - dog
    - cat
  filters:
    dog:
      min_score: .65
      threshold: .8
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

telemetry:
  network_interfaces: 
    - eno
    - br
  stats:
    network_bandwidth: false

detect:
  stationary:
    interval: 25

model:
    path: plus://redacted

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  output_args:
    record:  preset-record-generic-audio-aac
  hwaccel_args: preset-vaapi
```

### Relevant log output

```shell
[17/Dec/2023:08:18:30 +0000] "DELETE /api/export/front_yard_2023_10_04_13:36__2023_10_05_01:38.mp4 HTTP/1.1" 404 91 "http://10.112.0.4:5000/exports" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36" "-"
2023-12-17 08:18:34.190600317  10.112.1.233 - -
```

### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

```json
{"cameras":{"back_yard":{"audio_dBFS":-56.1568,"audio_rms":51.0046,"camera_fps":5.1,"capture_pid":633,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1906679,"pid":623,"process_fps":5.1,"skipped_fps":0.0},"front_yard":{"audio_dBFS":-57.8566,"audio_rms":41.9394,"camera_fps":5.1,"capture_pid":629,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":1906677,"pid":622,"process_fps":5.1,"skipped_fps":0.0},"rear_garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.3,"capture_pid":637,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":2021192,"pid":625,"process_fps":5.3,"skipped_fps":0.0},"test_cam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":642,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1937200,"pid":627,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"97":{"cmdline":"python3 -u -m frigate","cpu":"7.1","cpu_average":"5","mem":"1.0"},"98":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"110":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"163":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"194":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"226":{"cmdline":"nginx: worker process","cpu":"0.3","cpu_average":"0","mem":"0.0"},"264":{"cmdline":"nginx: worker process","cpu":"1.0","cpu_average":"0","mem":"0.0"},"292":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"327":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"369":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"403":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"446":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"585":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"587":{"cmdline":"frigate.recording_manager","cpu":"1.0","cpu_average":"1","mem":"0.3"},"596":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(55)","cpu":"0.5","cpu_average":"0","mem":"0.0"},"597":{"cmdline":"frigate.detector.coral","cpu":"0.1","cpu_average":"0","mem":"0.2"},"599":{"cmdline":"frigate.output       ","cpu":"2.6","cpu_average":"2","mem":"0.2"},"605":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x960 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"606":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x960 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"607":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"608":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"609":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"622":{"cmdline":"frigate.process:front_yard","cpu":"2.5","cpu_average":"4","mem":"0.2"},"623":{"cmdline":"frigate.process:back_yard","cpu":"1.2","cpu_average":"1","mem":"0.2"},"625":{"cmdline":"frigate.process:rear_garage","cpu":"1.2","cpu_average":"1","mem":"0.2"},"627":{"cmdline":"frigate.process:test_cam","cpu":"1.2","cpu_average":"0","mem":"0.2"},"629":{"cmdline":"frigate.capture:front_yard","cpu":"3.7","cpu_average":"3","mem":"0.2"},"633":{"cmdline":"frigate.capture:back_yard","cpu":"3.6","cpu_average":"3","mem":"0.2"},"637":{"cmdline":"frigate.capture:rear_garage","cpu":"2.9","cpu_average":"2","mem":"0.2"},"642":{"cmdline":"frigate.capture:test_cam","cpu":"2.9","cpu_average":"2","mem":"0.2"},"647":{"cmdline":"frigate.audio_manager","cpu":"1.3","cpu_average":"0","mem":"0.2"},"1906608":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"19.0","cpu_average":"19","mem":"0.1"},"1906677":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-e390533 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/front_yard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/front_yard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=960:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"14.4","cpu_average":"14","mem":"0.2"},"1906679":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-e390533 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/back_yard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/back_yard@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=960:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"14.4","cpu_average":"14","mem":"0.2"},"1906711":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-e390533 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/front_yard -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.7","cpu_average":"1","mem":"0.0"},"1906712":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-e390533 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/back_yard -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.9","cpu_average":"1","mem":"0.0"},"1937200":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-e390533 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/test_cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/test_cam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.3","cpu_average":"6","mem":"0.1"},"2021192":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-e390533 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/rear_garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/rear_garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.0","cpu_average":"2","mem":"0.1"},"2022997":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.63,"pid":597}},"gpu_usages":{"intel-vaapi":{"gpu":"6.34%","mem":"-%"}},"processes":{"audioDetector":{"pid":647},"go2rtc":{"pid":89},"logger":{"pid":585},"recording":{"pid":587}},"service":{"last_updated":1702801188,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":114.1,"mount_type":"tmpfs","total":128.0,"used":13.9},"/media/frigate/clips":{"free":5984177.0,"mount_type":"zfs","total":7081094.6,"used":1096917.6},"/media/frigate/recordings":{"free":5984177.0,"mount_type":"zfs","total":7081094.6,"used":1096917.6},"/tmp/cache":{"free":2038.2,"mount_type":"tmpfs","total":2048.0,"used":9.8}},"temperatures":{},"uptime":371738,"version":"0.13.0-e390533"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
