### ISSUE TITLE
[Support]: go2rtc HomeKit module pairing list writeback to config.yml

### ISSUE THREAD

**Issue by civita** [blakeblackshear/frigate#9016]
### Describe the problem you are having

I am using [HomeKit module from go2rtc](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-homekit) and am able to pair cameras and view them in Apple Home app. However, it works until Frigate restarts. 

In go2rtc logs, it shows the following error after restarting Frigate:
`ERR github.com/AlexxIT/go2rtc/internal/homekit/homekit.go:179 > error="hap: PairVerify from: 10.8.0.86:49347, with unknown client_id: ..."`

It looks like [go2rtc will append client_id to config.yml](https://github.com/AlexxIT/go2rtc/issues/805#issuecomment-1845371437) after successful pairing. However, the file go2rtc uses in Frigate instance is located in `/dev/shm/go2rtc.yaml` which is a `tmpfs` filesystem and will be re-generated from Frigate's `config.yml` after restart.

The workaround I am using is looking at the `go2rtc.ymal`, finding `client_id`, and manually add it into `config.yml` in Frigate:

```yaml
go2rtc:
  streams:
    camer_1:
      # ...
  homekit:
    camera_1:
      # the following two lines are manually added
      pairings:
       - client_id=...
```

I would like to know if there's better way to do that. Thanks.

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
go2rtc:
  streams:
    camer_1:
      # ...
  homekit:
    camera_1:
      # the following two lines are manually added
      pairings:
       - client_id=...
```

### Relevant log output

```shell
ERR github.com/AlexxIT/go2rtc/internal/homekit/homekit.go:179 > error="hap: PairVerify from: 10.8.0.86:49347, with unknown client_id: ..."
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
