### ISSUE TITLE
[Config Support]: Installed in Docker Container in Proxmox LXC but no frames are being received

### ISSUE THREAD

**Issue by tomhusband** [blakeblackshear/frigate#9019]
### Describe the problem you are having

Frigate loads but I can't get a picture. Previously I had Frigate as an add-on in Home Assistant in a Proxmox VM. Now on a new NUC I have HA in a VM and Frigate in Docker in a Proxmox LXC. I plan on linking the two at a later date. When I go to the Frigate IP address everything loads but no camera. I used this [tutorial](https://www.homeautomationguy.io/blog/running-frigate-on-proxmox) as a guide. I used the config file from my old installation as the camera didn't change (maybe that's where I went wrong).

The logs seem very brief. I have a USB Coral Accelerator and when I restarted the initial log had a lot more information but disappeared.

### Version

I don't see the version in Debug but it should the latest

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:username@192.168.1.15:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
      
    objects:
      track:
        - car
            mask
              - 1164,611,610,720,493,211,838,71
        - person
        - dog
        - cat
        - bicycle
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
        dog:
          min_score: 0.6
          threshold: 0.75
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects
      
    motion:
      improve_contrast: True
```

### Relevant log output

```shell
2023-12-19 15:19:42.588698274  [INFO] Starting Frigate...
2023-12-19 15:19:43.121530468  [2023-12-19 15:19:43] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-19 15:19:43.130164166  [2023-12-19 15:19:43] peewee_migrate                 INFO    : Starting migrations
2023-12-19 15:19:43.132207181  [2023-12-19 15:19:43] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-19 15:19:43.138841189  [2023-12-19 15:19:43] detector.coral                 INFO    : Starting detection process: 553
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
