### ISSUE TITLE
Getting Go2RTC working in the UI

### ISSUE THREAD

**Issue by Jens-Wymeersch** [blakeblackshear/frigate#9020]
### Describe the problem you are having

The purpose is to have 2-way audio feeds in home assistant/Frigate.
I installed go2rtc version 1.8.4 (which is visible in Frigate) and configured a go2rtc feed.
I'm able to toggle to MSE and get audio, but not to go2rtc and don't know why ?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: url
  port: 1883
  user: user
  password: pw
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb

############ Go2RTC ##############

go2rtc:
  streams:
    parkingCam:
      - rtsp://url
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\"" ## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED

##################################

###### Global Camera Config ######

detect:
  stationary:
    interval: 0
    threshold: 50
timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"
  position: tr
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
objects:    
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: max_int)
      max_area: 200000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.8
    cat:
      min_area: 4000
      max_area: 6000
      threshold: 0.6
    dog:
      min_area: 4000
      max_area: 6000
      min_score: 0.5
      threshold: 0.9
    car:
      min_area: 10000
      max_area: 1000000
      min_score: 0.5
      threshold: 0.8
    motorcycle:
      min_area: 10000
      max_area: 1000000
      min_score: 0.5
      threshold: 0.8
    bicycle:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.8
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: True
  height: 500
  retain:
    default: 7
record:
  enabled: True
  events:
    retain:
      default: 7
      mode: motion
    pre_capture: 5
    post_capture: 15

ui:
  live_mode: mse
##################################

cameras:
  parkingCam:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        # High Resolution Stream
        - path: rtsp://url
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      # Optional: height of the frame
      # NOTE: Recommended to set this value, but frigate will attempt to autodetect.
      width: 3840
      # Optional: desired fps for your camera
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      #       Frigate will attempt to autodetect if not specified.
      height: 2160
      # Optional: width of the frame
      # NOTE: Recommended to set this value, but frigate will attempt to autodetect.
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
    record:
      events:
        required_zones:
              - parking_key_zone
              - parking_entry_zone
    motion:
      mask: 
        - 0,0,659,0,842,379,0,948
        - 3840,0,3840,285,3776,243,3543,149,3350,183,2998,270,2535,297,2102,302,1896,233,1572,292,1270,381,975,0
    zones:
      parking_key_zone:
        coordinates: 609,1661,998,2160,3840,2160,3840,703,3595,418,2154,418,1109,1755,758,1471,317,1112,205,1196,183,1159
        objects:
          - person
          - cat
      parking_entry_zone:
        coordinates: 839,2028,369,1357,104,1045,421,753,718,738,819,621,1169,557,2171,525
        objects:
          - cat
          - dog
          - car
          - motorcycle
          - bicycle
```

### Relevant log output

```shell
Nothing really to see in the logs
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"},{"avg_frame_rate":"0/0","codec_long_name":"Opus(OpusInteractiveAudioCodec)"},{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":2160,"width":3840}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G5 pro
