### ISSUE TITLE
[Config Support]: Post_capture not working 

### ISSUE THREAD

**Issue by holligram** [blakeblackshear/frigate#9023]
### Describe the problem you are having

The post_cature time is not being followed. I have an event  pre_capture of 3s and post_capture of 20s so the total event clip recording should be at least 23s, but I mostly get 8 to 12 second total recorded time. The object is being detected correctly an event clips are recording for each event, it's just that the total clip is too short and adding post_capture does not seem to change anything.

### Version

13 beta 6

### Frigate config file

```yaml
record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 3
        post_capture: 20
        retain:
          default: 14
          mode: active_objects
```

### Relevant log output

```shell
none
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
