### ISSUE TITLE
[Config Support]: motion mask not respected?

### ISSUE THREAD

**Issue by euro2** [blakeblackshear/frigate#9029]
### Describe the problem you are having

every night at infrared setting, motion+person detection triggers and starts recording a covered table set. Its clearly blocked off by a mask. 

![Screenshot 2023-12-20 at 14-07-15 Frigate](https://github.com/blakeblackshear/frigate/assets/6632948/b28bc672-5420-4fdf-a5cc-04e93267508a)
![Screenshot 2023-12-20 at 14-06-41 Frigate](https://github.com/blakeblackshear/frigate/assets/6632948/08f2c28f-1024-4df0-84bb-8f638f7dd5fe)
![snapshot](https://github.com/blakeblackshear/frigate/assets/6632948/e12c569e-6993-40e7-ae4f-f61e6ac89d1f)

### Version

0.13beta7

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.xxx
  user: xxx
  password: xxx
  topic_prefix: frigate
  client_id: frigate

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu

birdseye:
  enabled: True
  mode: objects

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    voortuin_cam:
      - "ffmpeg:http://192.168.1.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx#video=copy#audio=copy#audio=opus"
    voortuin_cam_sub:
      - "ffmpeg:http://192.168.1.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx"
    achtertuin_cam:
      - "ffmpeg:http://192.168.1.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx#video=copy#audio=copy#audio=opus"
    achtertuin_cam_sub:
      - "ffmpeg:http://192.168.1.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx"

cameras:
  voortuin_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/voortuin_cam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
      - 0,1440,764,1440,764,1351,0,1340
      - 0,1073,0,0,1580,0,2456,0,2420,336,1813,240,1807,488,1167,373,1129,113,952,101,800,158,874,535,742,607,800,646
    birdseye:
      order: 1

  achtertuin_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/achtertuin_cam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
      - 753,1440,220,1440,0,1440,0,439,118,453,429,556,466,771,521,898,580,1186,758,1352
      - 882,52,1241,71,2024,75,2560,174,2560,0,0,0,0,71,402,71
    birdseye:
      order: 1

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  contour_area: 50

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 10000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 120
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 14
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: true
  retain:
    # Required: Default retention days (default: shown below)
    default: 14
    # Optional: Per object retention days
    objects:
      person: 14
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 95
```

### Relevant log output

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Debian Trixie

### Install method

Podman Quadlet

### Coral version

CPU (no coral)

### Any other information that may be helpful

Using Debian Trixie because this way i can use Podman Quadlet and start docker images as systemd units
