### ISSUE TITLE
[Config Support]: Dual lens wide camera wrong size in gui

### ISSUE THREAD

**Issue by gravelfreeman** [blakeblackshear/frigate#9035]
### Describe the problem you are having

I want my dual lens ultra wide camera to take 2 spaces in Frigate's gui. If I recall, I've seen a Youtuber doing this, while watching Youtube videos. I've read the documentation and couldn't find any relevant config variables for this.

![image](https://github.com/blakeblackshear/frigate/assets/44218371/89c4efab-1d46-46a4-bbd9-7bf22f21152e)

### Version

0.12.1-367d724

### Frigate config file

```yaml
# yaml-language-server: $schema=http://xxxxx:1984/api/config/schema.json

mqtt:
  enabled: True
  host: mqtt://core-mosquitto.local.hass.io
  port: 1883
  user: "xxxxx"
  password: "xxxxx"

database:
  path: /config/frigate.db

go2rtc:
  streams:
    camera_2: 
      - "ffmpeg:http://xxxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx#video=copy#audio=copy#audio=opus"
    camera_2_sub: 
      - "ffmpeg:http://xxxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx"
    camera_3: 
      - "ffmpeg:http://xxxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx#video=copy#audio=copy#audio=opus"
    camera_3_sub: 
      - "ffmpeg:http://xxxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx"

cameras:
  camera-1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxx@xxxxx/h264Preview_01_main
          roles:
            - record
        - path: rtsp://admin:xxxxx@xxxxx/h264Preview_01_sub
          roles:
            - detect
            - rtmp
    detect:
      width: 1536
      height: 576
  camera-2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_2_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
  camera-3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_3_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant log output

```shell
None
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

This is a brand new installation so my config file is in an early stage.
