### ISSUE TITLE
[Support]: /tmp/cache reporting wildly incorrect values with Docker installation

### ISSUE THREAD

**Issue by pypeaday** [blakeblackshear/frigate#9044]
### Describe the problem you are having

Frigate is deployed as a docker container, I've set the /tmp/cache tmpfs volume copy paste from the docs however in the frigate webui it's reporting that /tmp/cache is using over 100 GB and has a total of almost 1 TB of space

### Version

0.12.1-367d724

### Frigate config file

```yaml
---
mqtt:
  enabled: false
go2rtc:
  streams:
    front_door:
      - rtsp://user:password@192.168.1.82:554  # main
      - "ffmpeg:front_door#audio=aac"
cameras:
  front_door: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac # <----- The stream you want to use for detection
          hwaccel_args: preset-vaapi
          roles: [detect, record]
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution%
    record:
      enabled: True # <---- disable record until you have a working camera feed
    snapshots:
      enabled: True
detectors:
  coral:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
2023-12-21 08:50:58.683616257  [INFO] Starting Frigate...
2023-12-21 08:50:59.419602510  [2023-12-21 08:50:59] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-21 08:50:59.445522991  [2023-12-21 08:50:59] peewee_migrate                 INFO    : Starting migrations
2023-12-21 08:50:59.448345003  [2023-12-21 08:50:59] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-21 08:50:59.458190250  [2023-12-21 08:50:59] detector.coral                 INFO    : Starting detection process: 721
2023-12-21 08:50:59.495143020  [2023-12-21 08:50:59] frigate.app                    INFO    : Output process started: 723
2023-12-21 08:50:59.498054400  [2023-12-21 08:50:59] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-12-21 08:50:59.499329275  [2023-12-21 08:50:59] frigate.app                    INFO    : Camera processor started for front_door: 726
2023-12-21 08:50:59.499409556  [2023-12-21 08:50:59] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-12-21 08:50:59.499671678  [2023-12-21 08:50:59] frigate.app                    INFO    : Capture process started for front_door: 734
```

### FFprobe output from your camera

```shell
Not an issue with any camera
```

### Frigate stats

```json
{
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "116": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "134": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "135": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "136": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "137": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "149": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "16": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "174": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "199": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "2419": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "2436": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "2442": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "245": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "280": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "316": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "350": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "385": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "41": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "427": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "463": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "504": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "544": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "714": {
            "cpu": "0.0",
            "mem": "1.0"
        },
        "720": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "721": {
            "cpu": "0.3",
            "mem": "1.3"
        },
        "723": {
            "cpu": "0.7",
            "mem": "1.1"
        },
        "726": {
            "cpu": "0.7",
            "mem": "1.2"
        },
        "727": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "728": {
            "cpu": "0.3",
            "mem": "1.1"
        },
        "729": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "730": {
            "cpu": "0.0",
            "mem": "1.1"
        },
        "731": {
            "cpu": "0.3",
            "mem": "1.1"
        },
        "732": {
            "cpu": "0.3",
            "mem": "1.2"
        },
        "733": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "734": {
            "cpu": "0.7",
            "mem": "1.1"
        },
        "737": {
            "cpu": "0.7",
            "mem": "1.1"
        },
        "738": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "739": {
            "cpu": "1.7",
            "mem": "1.3"
        },
        "742": {
            "cpu": "1.0",
            "mem": "1.1"
        },
        "743": {
            "cpu": "2.3",
            "mem": "1.4"
        },
        "744": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "748": {
            "cpu": "1.0",
            "mem": "1.1"
        },
        "751": {
            "cpu": "1.7",
            "mem": "1.4"
        },
        "756": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "757": {
            "cpu": "1.0",
            "mem": "1.1"
        },
        "758": {
            "cpu": "1.7",
            "mem": "1.3"
        },
        "773": {
            "cpu": "1.7",
            "mem": "1.6"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "89": {
            "cpu": "4.7",
            "mem": "0.2"
        },
        "97": {
            "cpu": "1.7",
            "mem": "2.2"
        },
        "98": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0.0"
        },
        "top": {
            "cpu": "average:",
            "mem": "0.0"
        }
    },
    "detection_fps": 0.0,
    "detectors": {
        "coral": {
            "detection_start": 0.0,
            "inference_speed": 6.39,
            "pid": 721
        }
    },
    "front_door": {
        "camera_fps": 5.0,
        "capture_pid": 734,
        "detection_enabled": 1,
        "detection_fps": 0.0,
        "ffmpeg_pid": 739,
        "pid": 726,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "gpu_usages": {
        "amd-vaapi": {
            "gpu": "0.00 %",
            "mem": "89.94 %"
        }
    },
    "service": {
        "last_updated": 1703171787,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 527.5,
                "mount_type": "tmpfs",
                "total": 536.9,
                "used": 9.4
            },
            "/media/frigate/clips": {
                "free": 3958748.2,
                "mount_type": "zfs",
                "total": 3963369.9,
                "used": 4621.7
            },
            "/media/frigate/recordings": {
                "free": 3958748.2,
                "mount_type": "zfs",
                "total": 3963369.9,
                "used": 4621.7
            },
            "/tmp/cache": {
                "free": 806145.2,
                "mount_type": "overlay",
                "total": 982240.0,
                "used": 126124.3
            }
        },
        "temperatures": {
            "apex_0": 53.8
        },
        "uptime": 1528,
        "version": "0.12.1-367d724"
    }
}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

I deploy my docker containers with ansible, however I don't think this is actually relevant.

OS: Ubuntu 22.04.3 (server)
Kernel: 5.15.0-91-generic

**Comment by pypeaday** [comment]
Here is the ansible config for the docker container as well:

```
    - name: frigate Docker Container
      docker_container:
        name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        pull: true
        privileged: true  # this may not be necessary for all setups
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - '{{ frigate_config_directory }}/config.yml:/config/config.yml:rw'
          - '{{ frigate_media_directory }}:/media/frigate:rw'
          - type: tmpfs
            target: /tmp/cache
            tmpfs:
              size: 1000000000
        ports:
          - '{{ frigate_webui_port }}:5000'
          - '{{ frigate_rtsp_port }}:8554'  # RTSP feeds
          - '{{ frigate_webrtc_port }}:8555/tcp'  # WebRTC over tcp
          - '{{ frigate_webrtc_port }}:8555/udp'  # WebRTC over udp
        devices:
          - /dev/apex_0:/dev/apex_0  # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
          - /dev/dri/renderD128:/dev/dri/renderD128  # should pass through the AMD iGPU
          - /dev/dri/card0:/dev/dri/card0
        env:
          TZ: '{{ ansible_nas_timezone }}'
          LIBVA_DRIVER_NAME: radeonsi
          FRIGATE_RTSP_PASSWORD: '{{ frigate_password }}'
        restart_policy: unless-stopped
        shm_size: 512MB  # update for your cameras based on calculation above
        memory: '{{ frigate_memory }}'
```

**Comment by NickM-27** [comment]
it may be an ansible issue with the unit that is used. You can get a shell in the container and check using df

**Comment by pypeaday** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/32268273/4d4f4fb9-0bf0-479c-9e3f-75e9a54d2934)

Well hot dang I didn't even think about that... ok so I need to read some ansible docs and figure out the issue with the volume then... will try to report back on that before too long!

**Comment by pypeaday** [comment]
You are the man @NickM-27 :rocket: 

Correct Ansible configuration uses `mounts` for the `tmpfs` instead of just `volumes` like so:

```
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - '{{ frigate_config_directory }}/config.yml:/config/config.yml:rw'
          - '{{ frigate_media_directory }}:/media/frigate:rw'
        mounts:
          - type: tmpfs
            target: /tmp/cache
            tmpfs_size: 1000000000
```

Thank you for the quick response!
