### ISSUE TITLE
[Config Support]: Invalid data found when processing input

### ISSUE THREAD

**Issue by gravelfreeman** [blakeblackshear/frigate#9048]
### Describe the problem you are having

My `camera-2` and `camera-3` are throwing out errors in the logs and won't initiate record.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: core-mosquitto.local.hass.io
  port: 1883
  user: "***"
  password: "***"

database:
  path: /config/frigate.db

go2rtc:
  streams:
    camera_2: 
      - "ffmpeg:http://***/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=***#video=copy#audio=copy#audio=opus"
    camera_2_sub: 
      - "ffmpeg:http://***/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=***"
    camera_3: 
      - "ffmpeg:http://***/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=***#video=copy#audio=copy#audio=opus"
    camera_3_sub: 
      - "ffmpeg:http://***/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=***"

cameras:
  camera-1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:***@***/h264Preview_01_main
          roles:
            - record
        - path: rtsp://admin:***@***/h264Preview_01_sub
          roles:
            - detect
            - rtmp
    detect:
      width: 1536
      height: 576
  camera-2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_2_sub?video
          input_args: preset-rtsp-restream
          roles:
            - detect
  camera-3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_3_sub?video
          input_args: preset-rtsp-restream
          roles:
            - detect

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

### Relevant log output

```shell
2023-12-22 00:23:40.200834213  19:23:40.200 ERR [exec] timeout url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://***/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=***-map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -ar:a:1 48000 -ac:a:1 2 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/***"

2023-12-22 00:23:40.201099286  19:23:40.200 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error=timeout url=ffmpeg:http://10.0.10.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=***#video=copy#audio=copy#audio=opus
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

I can access the camera feeds in browser with these URLs;

`http://***/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=***#video=copy#audio=copy#audio=opus `

`http://***/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=***`
