### ISSUE TITLE
Any help with Asus Tinkerboard?

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#906]
My Asus Tinkerboard has a `/dev/dri/renderD128` device. I don't think it is Intel, and none of the recommended options seem to work. Currently I am getting this:

```yaml
mqtt:
  host: 192.168.1.10
  user: mosquitto
  password: 

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.1.20:554/cam/realmonitor?channel=1&subtype=01
          roles: 
            - detect
            - rtmp
    width: 704
    height: 480
    fps: 5

~                                           
```

```log
ffmpeg.front.detect            ERROR   : [h264 @ 0x80992580] No device available for decoder: device type vaapi needed for codec h264.


ffmpeg.front.detect            ERROR   : Device setup failed for decoder on input stream #0:0 : Cannot allocate memory


frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures


frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...


ffmpeg.front.detect            ERROR   : Device creation failed: -12.


ffmpeg.front.detect            ERROR   : [h264 @ 0x80b7b580] No device available for decoder: device type vaapi needed for codec h264.


ffmpeg.front.detect            ERROR   : Device setup failed for decoder on input stream #0:0 : Cannot allocate memory


frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures


frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...


ffmpeg.front.detect            ERROR   : Device creation failed: -12.


ffmpeg.front.detect            ERROR   : [h264 @ 0x802e1580] No device available for decoder: device type vaapi needed for codec h264.


ffmpeg.front.detect            ERROR   : Device setup failed for decoder on input stream #0:0 : Cannot allocate memory


frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures


frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...


```
