### ISSUE TITLE
[Config Support]: 2 cameras vertical layout in birdeye

### ISSUE THREAD

**Issue by ivanvaccari** [blakeblackshear/frigate#9076]
### Describe the problem you are having

I need help to setup the birdseye view to better fit smartphone and tablet screen. In my case, i have two cameras wich are displayed horizontally, taking only a very small portion of the birdseye area(and making them basically invisible)
I'd like to display the cameras in a single vertical column so they becames bigger and at least "visible".
I've tried to set a thinner but higher birdseye area but the cameras are still downsized to be fitted in one row.

Both cameras uses the sub streams for live view, the horizontal resolution is 720px, but the verical one differ since one of them is 3/4, the other one 16/9.

Is it configurable as single column?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com
cameras:
  cortile:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cortile_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rtsp_cortile_cam_sub
          roles:
            - detect
    live:
      stream_name: rtsp_cortile_cam_sub
  cancello:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cancello_cam
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rtsp_cancello_cam_sub
          roles:
            - detect
    live:
      stream_name: rtsp_cancello_cam_sub
detect:
  enabled: False
birdseye:
  enabled: True
  mode: continuous
  width: 576
  height: 1280
go2rtc:
  streams:
    rtsp_cortile_cam:
      - rtsp://192.168.0.21:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    rtsp_cortile_cam_sub:
      - rtsp://192.168.0.21:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
    rtsp_cancello_cam:
      - rtsp://192.168.0.20:554/Streaming/Channels/101?transportmode=unicast
    rtsp_cancello_cam_sub:
      - rtsp://192.168.0.20:554/Streaming/Channels/102?transportmode=unicast
```

### Relevant log output

```shell
No log. Will copy relevant sections upon request
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

CPU (no coral)
