### ISSUE TITLE
[Config Support]: Timeline and Snapshot Events but no Clips

### ISSUE THREAD

**Issue by DustyArmstrong** [blakeblackshear/frigate#9077]
### Describe the problem you are having

I have a different recording setup for one of my cameras due to zone masks. This camera, as a result, behaves differently than the others. My other cameras will capture an event both as a snapshot and a video clip, while this camera will only record motion events to the timeline view - no clips. I can still view them and the camera works, detection works, it just isn't doing clips. 

From my config file, you can see I have a global `record` entry, which differs from the one for this camera. Is it this section that is telling it "record motion events on a timeline, not as clips" as I've said to retain 3 days?

```
retain:
  days: 3
```

I could just remove this line and test it but I'd rather understand it. For clarity, when I say no "clips" are being made, I mean no clip of the event is being made, the "clip" button is greyed out.

### Version

0.12.1-367d724

### Frigate config file

```yaml
go2rtc:
  streams:
    camera1: 
      - "http://ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password"
      - "ffmpeg:camera1#audio=opus"
    camera1_sub: 
      - "http://ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"
    camera2: 
      - "http://ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password"
      - "ffmpeg:camera2#audio=opus"
    camera2_sub: 
      - "http://ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"
    camera3: 
      - "rtsp://admin:password@ip:554/h264Preview_01_main"
      - "ffmpeg:camera3#audio=opus"
    camera3_sub: 
      - "http://ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password"

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user:password@ip:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: True
      required_zones:
        - driveway
        - full
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - driveway
          - full
    mqtt:
      required_zones:
        - driveway
        - full
    zones:
      driveway:
        coordinates: 209,237,377,270,450,242,458,0,640,0,640,442,437,436,440,480,0,480,0,231
        objects:
          - car
      full: 
        coordinates: 0,480,418,480,426,440,640,440,640,27,535,32,488,0,382,85,0,93
        objects: 
          - person
          - dog
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - car
        
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user:password@ip:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog

  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user:password@ip:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30
mqtt:
  host: ip
  enabled: True
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password

ffmpeg:
  #hwaccel_args: preset-vaapi
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

record:
  enabled: True
  events:
    pre_capture: 3
    post_capture: 2
    retain:
      default: 3
      mode: motion
    objects:
      - person
      - dog

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```

### Relevant log output

```shell
No notable logs, I think it is behaving as expected but configured incorrectly by me. Happy to provide any if necessary, I just don't see anything.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
> while this camera will only record motion events to the timeline view - no clips.

There seems to be some confusion here, there is no difference between different recording modes like this. All recordings are treated the same in the backend so if a recording is visible as an event it is also visible in the recordings viewer.

"Clips" are just generated from the recording segments that are saved

**Comment by DustyArmstrong** [comment]
Thanks Nick. 

I'm probably explaining it wrong. None of the recordings for this camera are shown as events, I can only view the recordings via the timeline browser or media browser. The clips button for each event is greyed out, and when I watch the footage back via the timeline/recordings it says `0 Events`. I still get a snapshot of the event but no clip is created. My other 2 cameras will have both snapshots and clips for the event.

**Comment by NickM-27** [comment]
Do you have an automation or notifications that run when the event is created? I'd think this is a bug (one that has been fixed in 0.13)

**Comment by DustyArmstrong** [comment]
No I have no automations or otherwise for events that I'm aware of. The only thing I did was add the detection zones according to a guide I followed (that guide did seem to get event clips populated so I was unsure what I was doing wrong).

**Comment by NickM-27** [comment]
Seeing a full copy of the logs would be good

**Comment by DustyArmstrong** [comment]
Is this the Frigate log? There's basically nothing there unless I'm looking in the wrong place. 

```
2023-12-26 12:28:09.401781560  [INFO] Starting Frigate...
2023-12-26 12:28:11.194748737  [2023-12-26 12:28:11] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-26 12:28:11.235442015  [2023-12-26 12:28:11] peewee_migrate                 INFO    : Starting migrations
2023-12-26 12:28:11.242503519  [2023-12-26 12:28:11] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-26 12:28:11.264568123  [2023-12-26 12:28:11] frigate.app                    INFO    : Output process started: 291
2023-12-26 12:28:11.269533253  [2023-12-26 12:28:11] detector.coral                 INFO    : Starting detection process: 290
2023-12-26 12:28:11.269633383  [2023-12-26 12:28:11] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-12-26 12:28:11.292426021  [2023-12-26 12:28:11] frigate.app                    INFO    : Camera processor started for camera1: 296
2023-12-26 12:28:11.292432578  [2023-12-26 12:28:11] frigate.app                    INFO    : Camera processor started for camera2: 300
2023-12-26 12:28:11.292439740  [2023-12-26 12:28:11] frigate.app                    INFO    : Camera processor started for camera3: 301
2023-12-26 12:28:11.293943874  [2023-12-26 12:28:11] frigate.app                    INFO    : Capture process started for camera1: 303
2023-12-26 12:28:11.303492464  [2023-12-26 12:28:11] frigate.app                    INFO    : Capture process started for camera2: 304
2023-12-26 12:28:11.303499028  [2023-12-26 12:28:11] frigate.app                    INFO    : Capture process started for camera3: 307
2023-12-26 12:28:13.529451580  [2023-12-26 12:28:13] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found

```

**Comment by DustyArmstrong** [comment]
OK, I'm going to try something from [this thread](https://github.com/blakeblackshear/frigate/issues/5969).

Changing from: 

```
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 5
        required_zones:
          - driveway
          - full
```

to:

```
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 5
        objects:
          - person
          - dog
          - car
        required_zones:
          - driveway
          - full
```

Will see if that has success as it did for them.
