### ISSUE TITLE
[FR] Ensure snapshot is written to disk before publishing MQTT event

### ISSUE THREAD

**Issue by fl42** [blakeblackshear/frigate#908]
**Describe the bug**
Frigate seems to publish an event to MQTT as soon as the event occurs, even if the snapshot is not yet written to disk. This can cause issues if another software (e.g, Home Assistant) tries to access the snapshot on MQTT event.

**Version of frigate**
0.8.4-5043040

**Home assistant config**
```yaml
automation:
- alias: Copy snapshots from Frigate to HA
  mode: parallel
  trigger:
    platform: mqtt
    topic: frigate/events
  condition:
    - "{{ trigger.payload_json['before']['label'] in ['person'] }}"
  action:
    - service: shell_command.copy_snapshot
      data_template:
        camera: "{{ trigger.payload_json['before']['camera'] }}"
        id: "{{ trigger.payload_json['before']['id'] }}"
        label: "{{ trigger.payload_json['before']['label'] }}"

shell_command:
  copy_snapshot: "cp /mnt/frigate/clips/{{ camera }}-{{ id }}.jpg /media/screenshots/{{ camera }}_{{ label }}.jpg"
```

**Home assistant logs**
```
2021-03-14 13:21:35 DEBUG (MainThread) [homeassistant.components.shell_command] Stderr of command: `cp /mnt/frigate/clips/{{ camera }}-{{ id }}.jpg /media/screenshots/latest_{{ label }}.jpg`, return code: 1:
b"cp: can't stat '/mnt/frigate/clips/Camera1-1615724310.012594-17ay1i.jpg': No such file or directory\n"
2021-03-14 13:21:35 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `cp /mnt/frigate/clips/{{ camera }}-{{ id }}.jpg /media/screenshots/latest_{{ label }}.jpg`, return code: 1
NoneType: None
```

**Feature request**
By default Frigate should wait to have snapshot written to disk before publishing MQTT event.
A parameter could be added to allow sending the MQTT event even if the snapshot is not written to disk, for example for users who don't care about having the snapshot immediately available.

Thank you for this great software!

**Comment by blakeblackshear** [comment]
You need another condition to only run on event type “end”. The file is not written to disk until the event is over.

**Comment by fl42** [comment]
> The file is not written to disk until the event is over.

You mean for clips?
As far as I understood [from docs](https://blakeblackshear.github.io/frigate/usage/mqtt#frigateevents) for snapshots Frigate writes the image as soon as an object is detected, and may update the snapshot later on if a better accuracy is found. I'm right?

If I'm waiting for the "end" event I'll be notified only when the event is over, i.e. when the object is not anymore detected?
I would be notified as soon as the object is detected (not marked at false positive), else I won't be notified I an object comes and don't leave the area.

For those you are interested, I found a better than nothing workaround
```yaml
shell_command:
  copy_snapshot: |
    sh -x -c "for i in {1..30}; do [ -f /mnt/frigate/clips/{{ camera }}-{{ id }}.jpg ] && break; sleep 1; done &&
    sleep 0.2 && cp /mnt/frigate/clips/{{ camera }}-{{ id }}.jpg /media/screenshots/{{ camera }}_{{ label }}.jpg"
```
