### ISSUE TITLE
[Config Support]: Limit stationary object events for a single object type in a zone.

### ISSUE THREAD

**Issue by bluesk1d** [blakeblackshear/frigate#9081]
### Describe the problem you are having

I have a number of zones for the front of my house and I am trying to limit stationary vehicles generating events in the driveway while still being able to detect other object types. 

There is a good example in the docs [here ](https://docs.frigate.video/guides/stationary_objects) and I could use the sidewalk in the same way as "Zone 2" but I don't want that same restriction on people and animals. I have tried limiting the object types that the "Driveway" zone will detect but it seems if a car is already parked there and becomes detected via other motion, it sits there as an ongoing event forever. There is no zone displayed in the ongoing event so perhaps that is why it isn't filtering it but I am not sure if the zone info doesn't fill in until the event is over. I've also tried to limit events to objects that are in one of the defined zones and that didn't seem to help.

I've attached a pic that shows the zone boundaries and the object bounding box if that helps visualize it. I also attached a shot of the event indicating no zone for the object.

![2023-12-26 18_07_11-Frigate](https://github.com/blakeblackshear/frigate/assets/32088886/56ee3759-eeeb-40df-9e75-5d4a8172bcaa)
![2023-12-26 18_08_00-Frigate](https://github.com/blakeblackshear/frigate/assets/32088886/1718e2b5-79f0-4207-a6ff-5cfd5b1cc84b)

Is there a better way to filter out that car while leaving other detections unaffected? 

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
garage_exterior:
  mqtt:
    timestamp: False
    bounding_box: False
    crop: True
    quality: 100
    height: 500
  ffmpeg:
    inputs:
      - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.30.169:554/H264/ch1/main/av_stream
        roles:
          - detect
          - record
  detect:
    width: 2560
    height: 720
    fps: 6
  motion:
    mask:
      - 0,540,119,425,259,307,113,253,230,191,442,102,851,0,2006,0,1730,0,1845,78,1768,108,1710,185,1639,410,1775,430,2028,379,2132,363,2212,325,2311,183,2560,361,2560,0,0,0 # Sky/bushes
  record:
    events:
      required_zones:
        - Porch
        - Frontyard
        - East sideyard
        - Driveway
        - Sidewalk
        - Street
  zones:
    Porch:
      coordinates: 2078,720,1763,515,1686,644,1544,720,1403,510,1644,448,1849,523,2067,404,2233,329,2279,495,2303,468,2351,486,2432,462,2491,468,2318,720
    Frontyard:
      coordinates: 1709,422,1716,253,1490,199,1231,180,1405,507
    East sideyard:
      coordinates: 314,441,148,468,0,531,0,720,339,720,571,427,709,195,571,218
    Driveway:
      coordinates: 1531,720,1364,437,1221,180,947,180,695,200,556,425,348,720
      objects:
        - person
        - cat
        - dog
    Sidewalk:
      coordinates: 375,210,650,158,877,131,1196,121,1418,137,1730,187,1714,234,1503,193,1236,178,934,180,764,191,627,203,483,225,369,241,192,276,166,254
    Street:
      coordinates: 1395,0,1692,51,1635,0,1716,0,1870,96,1786,196,1227,123,806,139,496,190,152,257,137,230,323,148,583,63,823,0
```

### Relevant log output

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB
