### ISSUE TITLE
[Config Support]: Camera Not Recording 

### ISSUE THREAD

**Issue by grainsoflight** [blakeblackshear/frigate#9083]
### Describe the problem you are having

My doorbell camera stopped recording on the 14th, Im sure it was a config change I made but I have no idea what it was and am not entirely certain how to interpret the logs. Can you possibly look at them ad see if you can see what the issue is?

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: 2MCHouYnzpqN3&
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:BW5ynKNVLDhQyS@192.168.5.3:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://0.0.0.0:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    record:
      enabled: True
      retain:
        days: 14
    motion:
      mask:
        - 422,0,421,26,208,29,207,0
        - 222,112,293,45,436,51,453,123,442,279,218,302
    objects:
      filters:
        person:
          mask:
            - 301,0,0,0,0,480,230,480,229,100,265,99
            - 438,40,640,0,640,480,501,480,438,437
            - 234,102,305,21,440,52,445,187,228,185
    snapshots:
      enabled: True
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://0.0.0.0:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 8
    motion:
      mask:
        - 231,36,649,40,650,0,267,0,236,0
        - 444,53,453,270,377,296,350,67
        - 132,71,198,307,300,276,261,41
        - 578,0,567,185,509,205,509,0
        - 896,55,896,122,864,125,873,42
    record:
      enabled: True
      retain:
        days: 14
    snapshots:
      enabled: True

go2rtc:
  streams:
    doorbell:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.3:554/h264Preview_01_main
      - "ffmpeg:doorbell#audio=opus"
    backyard:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_01_main
      - "ffmpeg:backyard#video=h264#audio=opus#hardware"
  webrtc:
    candidates:
      - 192.168.0.11:8555
      - stun:8555

birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
>127.0.0.1:34778: write: broken pipe"
2023-12-17 14:00:58.001479517  14:00:58.001 WRN [rtsp] error="streams: codecs not matched: H264, AAC => H264, H265, AAC" stream=doorbell
2023-12-17 14:00:58.001506528  14:00:58.001 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:225 > error="write tcp 127.0.0.1:8554->127.0.0.1:57384: write: broken pipe"
2023-12-17 20:31:34.307208150  20:31:34.307 WRN error="websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header"
2023-12-24 01:59:58.873061335  01:59:58.872 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_01_main
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
