### ISSUE TITLE
[Support]: Mask & Zone Creator, disable Snap to Edges option not working

### ISSUE THREAD

**Issue by baylanger** [blakeblackshear/frigate#9088]
### Describe the problem you are having

Hi.

I searched in the docs, discussions ad open/close issues, couldn't find any info on this topic.

Regardless if "snap to edges" is enable or not, the Mask & Zone Creator UI still snaps points to edges. Correct me if I'm wrong, disabling this option should allow the end user to freely place a point. If so, that's not the case. With this option disable, all points still want to snap and don't freely move.

### Version

0.12.0 & 0.13-beta7

### Frigate config file

```yaml
# Providing bare minimum config just in case the root cause could be related to camera resolution?

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
    frontyard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@12.16.8.XXX:554/Streaming/Channels/101
    frontyard_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@12.16.8.XXX:554/Streaming/Channels/102

cameras:
  frontyard:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/frontyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      # use same resolution as feed
      width: 1280
      height: 720
      fps: 12
```

### Relevant log output

```shell
Not needed.
```

### FFprobe output from your camera

```shell
Not needed.
```

### Frigate stats

```json
Not needed.
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

Same behavior in Chrome 118.0.5993.70 & Firefox 121.0
