### ISSUE TITLE
[Config Support]: Reolink Video Doorbell POE latency on mobile

### ISSUE THREAD

**Issue by blarg3891** [blakeblackshear/frigate#9092]
### Describe the problem you are having

Live view latency mostly apparent on Video Doorbell and only on my mobile device.  It will skip seconds often and freeze up.  Tried to set live view substream but cannot tell if its working but the latency is still there.  Having trouble figuring out how to debug this issue.  Wondering if settings need to be changed on the actual device or in frigate.  I set to FPS 15, interframe space 1x.  Installed on Truenas Scale, truecharts.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: mosquitto.ix-mosquitto.svc.cluster.local
  port: 1883
  user: xxxx
  password: "{FRIGATE_MQTT_PASSWORD}"

go2rtc:
  streams:
    doorbell: 
      - "ffmpeg:rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@x.x.x.x:554/h264Preview_01_main#video=copy#audio=copy#audio=opus"
      #- "ffmpeg:http://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}#video=copy#audio=copy#audio=opus"
    doorbell_sub: 
      - "ffmpeg:rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@x.x.x.x:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus"
      #- "ffmpeg:http://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}"
    garage: 
      - "ffmpeg:rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@x.x.x.x:554/h264Preview_01_main#video=copy#audio=copy#audio=opus"
      #- "ffmpeg:http://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}#video=copy#audio=copy#audio=opus"      

#detectors:
  #coral:
    #type: edgetpu
    #device: usb

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-nvidia-h264

birdseye:
  enabled: True
  mode: continuous
  restream: False
  width: 1920
  height: 1080
  quality: 4
   
#rtmp:
  #enabled: false

detect:
  fps: 5
  enabled: true

objects:
  filters:
    person:
      min_area: 5000
      min_score: 0.6

record:
  enabled: True
  expire_interval: 240
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 21
      mode: active_objects

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: doorbell_sub      
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record   
            - detect
    #detect:
      #width: 4096
      #height: 1536
```

### Relevant log output

```shell
not that i can see
```

### Frigate stats

```json
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"},{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
