### ISSUE TITLE
[Support]: Error during clip playback

### ISSUE THREAD

**Issue by bassho** [blakeblackshear/frigate#9094]
### Describe the problem you are having

/Edit
Sorry; title missing

When playing media via Events > Clip, it often happens Frigate throws an error while playing a video. It happens when the videoclip is completely played. 

![image](https://github.com/blakeblackshear/frigate/assets/27589134/9d5157c5-6491-47d0-a244-d099b6f50413)

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.***.***
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ***
  password: ***
  stats_interval: 60

#AI detectors
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

#go2rtc
go2rtc:
  streams:
    reolink:
      - rtsp://admin:***@192.168.***.***:554/h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

#Cameras
cameras:
  reolink:
    enabled: True
    ffmpeg:
      inputs:
        #HQ stream
        - path: rtsp://admin:***@192.168.***.***:554/h264Preview_01_main
          roles:
            - record
        #LQ stream
        - path: rtsp://admin:***@192.168.***.***:554/h264Preview_01_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
    motion:
      mask:
        - 333,436,351,0,0,0,0,544
        - 1280,565,1280,0,991,0,949,459
    zones:
      zone_voortuin:
        coordinates: 1280,720,1280,571,949,481,710,485,335,467,0,570,0,720

#default camera conf
objects:
  track:
    - person
  filters:
    person:
      threshold: 0.7

snapshots:
  enabled: True
  required_zones:
    - zone_voortuin
  retain:
    default: 14
    objects:
      person: 14

#record
record:
  enabled: True
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 14
    required_zones:
      - zone_voortuin
```

### Relevant log output

```shell
BROWSER CONSOLE LOG

VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. Ke {code: 3, message: 'The media playback was aborted due to a corruption…media used features your browser did not support.'}code: 3message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."[[Prototype]]: ObjectMEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: 0message: ""status: nullconstructor: ƒ Ke(a)[[Prototype]]: Object

videojs-seek-buttons-fa3a5bd5.js:31  VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) video append of 4613160b failed for segment #1 in playlist 0-index-v1-a1.m3u8 Ke {code: 3, message: 'video append of 4613160b failed for segment #1 in playlist 0-index-v1-a1.m3u8'}

videojs-seek-buttons-fa3a5bd5.js:31  VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. Ke {code: 3, message: 'The media playback was aborted due to a corruption…media used features your browser did not support.'}
```

### FFprobe output from your camera

```shell
Not relevant.
```

### Frigate stats

```json
{
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "16": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "40": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "75": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "84": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "93": {
            "cpu": "0.0",
            "mem": "0.6"
        },
        "98": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "109": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "112": {
            "cpu": "1.3",
            "mem": "6.5"
        },
        "122": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "141": {
            "cpu": "0.0",
            "mem": "0.6"
        },
        "174": {
            "cpu": "0.0",
            "mem": "0.7"
        },
        "219": {
            "cpu": "0.0",
            "mem": "0.9"
        },
        "225": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "226": {
            "cpu": "28.6",
            "mem": "3.0"
        },
        "227": {
            "cpu": "0.3",
            "mem": "1.1"
        },
        "231": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "232": {
            "cpu": "1.0",
            "mem": "1.5"
        },
        "233": {
            "cpu": "1.0",
            "mem": "1.2"
        },
        "234": {
            "cpu": "0.0",
            "mem": "0.6"
        },
        "17553": {
            "cpu": "3.3",
            "mem": "0.8"
        },
        "17555": {
            "cpu": "2.7",
            "mem": "0.6"
        },
        "18049": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "18063": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "18071": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "18072": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "18073": {
            "cpu": "0.3",
            "mem": "0.8"
        },
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.0"
        },
        "MiB": {
            "cpu": "2472.1",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top": {
            "cpu": "users,",
            "mem": "load"
        }
    },
    "detection_fps": 1.5,
    "detectors": {
        "ov": {
            "detection_start": 0,
            "inference_speed": 43.54,
            "pid": 226
        }
    },
    "reolink": {
        "camera_fps": 5.1,
        "capture_pid": 233,
        "detection_enabled": 1,
        "detection_fps": 1.5,
        "ffmpeg_pid": 17553,
        "pid": 232,
        "process_fps": 5,
        "skipped_fps": 0
    },
    "service": {
        "last_updated": 1703711434,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 2035.1,
                "mount_type": "tmpfs",
                "total": 2039.5,
                "used": 4.3
            },
            "/media/frigate/clips": {
                "free": 20739,
                "mount_type": "ext4",
                "total": 33059,
                "used": 10936.6
            },
            "/media/frigate/recordings": {
                "free": 20739,
                "mount_type": "ext4",
                "total": 33059,
                "used": 10936.6
            },
            "/tmp/cache": {
                "free": 2034.2,
                "mount_type": "tmpfs",
                "total": 2039.5,
                "used": 5.3
            }
        },
        "temperatures": {},
        "uptime": 23702,
        "version": "0.12.1-367d724"
    }
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

Reolink Doorbell

### Any other information that may be helpful

Edge on Windows
Multiple systems
