### ISSUE TITLE
[HW Accel Support]: CUDA initialization failure with error: 35

### ISSUE THREAD

**Issue by weswitt** [blakeblackshear/frigate#9097]
### Describe the problem you are having

just installing 13.0 beta 7 and am having problems with the model build. i get a "CUDA initialization failure with error: 35." error every time. i seem to have the right versions of the nvidia drivers & cuda installed, but the error seems to indicate a cuda compatibility problem. not sure what to do to get this working. i had this working for 8 months on version 12 and am now trying to move forward to the latest frigate version. any help would be appreciated,

### Version

13.0 beta 7

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.172
  client_id: frigate

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

snapshots:
  enabled: true

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 3
      mode: active_objects

ffmpeg:
  hwaccel_args: -c:v h264_cuvid
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta7-tensorrt
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      USE_FP16: "False"
```

### Relevant log output

```shell
Recreating 1d43f8ce9a11_frigate ... done
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service trt-model-prepare: starting
frigate    | s6-rc: info: service log-prepare: starting
frigate    | Generating the following TRT Models: yolov7-320
frigate    | Downloading yolo weights
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | 2023-12-27 19:17:02.619811834  [INFO] Preparing new go2rtc config...
frigate    | 2023-12-27 19:17:02.807833238  [INFO] Starting go2rtc...
frigate    | 2023-12-27 19:17:02.856874058  19:17:02.856 INF go2rtc version 1.8.4 linux/amd64
frigate    | 2023-12-27 19:17:02.857306452  19:17:02.857 INF [api] listen addr=:1984
frigate    | 2023-12-27 19:17:02.857565438  19:17:02.857 INF [rtsp] listen addr=:8554
frigate    | 2023-12-27 19:17:02.857784865  19:17:02.857 INF [webrtc] listen addr=:8555
frigate    |
frigate    | Creating yolov7-320.cfg and yolov7-320.weights
frigate    |
frigate    | Done.
frigate    |
frigate    | Generating yolov7-320.trt. This may take a few minutes.
frigate    |
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 214, in <module>
frigate    |     main()
frigate    |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 202, in main
frigate    |     engine = build_engine(
frigate    |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 112, in build_engine
frigate    |     with trt.Builder(TRT_LOGGER) as builder, builder.create_network(*EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
frigate    | TypeError: pybind11::init(): factory function returned nullptr
frigate    | [12/27/2023-19:17:10] [TRT] [W] Unable to determine GPU memory usage
frigate    | [12/27/2023-19:17:10] [TRT] [W] Unable to determine GPU memory usage
frigate    | [12/27/2023-19:17:10] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
frigate    | Loading the ONNX file...
frigate    | Available tensorrt models:
frigate    | ls: cannot access '*.trt': No such file or directory
frigate    | s6-rc: warning: unable to start service trt-model-prepare: command exited 2
frigate    | 2023-12-27 19:17:12.618628981  [INFO] Starting go2rtc healthcheck service...
^CGracefully stopping... (press Ctrl+C again to force)
Stopping frigate                ... done
```

### FFprobe output from your camera

```shell
n/a.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Amcrest

### Any other information that may be helpful

Wed Dec 27 19:20:26 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1060 6GB    On  | 00000000:01:00.0 Off |                  N/A |
|  0%   33C    P8               5W / 120W |     63MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2164      G   /usr/lib/xorg/Xorg                           56MiB |
|    0   N/A  N/A      2383      G   /usr/bin/gnome-shell                          4MiB |
+---------------------------------------------------------------------------------------+
