### ISSUE TITLE
[Camera Support]: Unable to stream RTSP from RPi Camera

### ISSUE THREAD

**Issue by jrussell05** [blakeblackshear/frigate#9105]
### Describe the problem you are having

I've built a camera from a RPi Zero 2W and an Arducam.  I'm using the following command to produce an RTSP stream.

`rpicam-vid --framerate 10 --intra 1 --width 1920 --height 1080 -t 0 -n --inline -o - | cvlc stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/stream1}' :demux=h264`

There are a few errors associated with the fact that there is no local display system or any audio.  However, I can view the video stream **just fine** from a Windows computer running VLC (See VLC media information screenshot below).

```
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[4:35:51.045176081] [1429]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
[000a1d88] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[4:35:51.131609154] [1435]  WARN RPiSdn sdn.cpp:39 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[4:35:51.138212487] [1435]  INFO RPI vc4.cpp:444 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media2 and ISP device /dev/media0
[4:35:51.138339154] [1435]  INFO RPI pipeline_base.cpp:1142 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
Mode selection for 1920:1080:12:P(10)
    SGBRG10_CSI2P,640x480/58.924 - Score: 6093.33
    SGBRG10_CSI2P,1296x972/43.247 - Score: 3797.33
    SGBRG10_CSI2P,1920x1080/30.6185 - Score: 1000
    SGBRG10_CSI2P,2592x1944/15.6335 - Score: 2717.33
Stream configuration adjusted
[4:35:51.149870248] [1429]  INFO Camera camera.cpp:1183 configuring streams: (0) 1920x1080-YUV420 (1) 1920x1080-SGBRG10_CSI2P
[4:35:51.150593633] [1435]  INFO RPI vc4.cpp:608 Sensor: /base/soc/i2c0mux/i2c@1/ov5647@36 - Selected sensor format: 1920x1080-SGBRG10_1X10 - Selected unicam format: 1920x1080-pGAA
[0009e2d8] main interface error: no suitable interface module
[0001fb50] main libvlc error: interface "globalhotkeys,none" initialization failed
[0009e2d8] dummy interface: using the dummy interface module...
[725034b0] main stream error: unknown query 0x30e in demux_vaControlHelper
```

![image](https://github.com/blakeblackshear/frigate/assets/10651901/9ccd3f62-134f-4742-9d33-12a7cb21e8e9)

However, I get errors in the Frigate log with no video.

I've read numerous posts somewhat related to this issue but no clear resolution.  Any help appreciated.  Thanks.

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
  coral_pci:
    type: edgetpu
    device: pci
database:
  path: /db/frigate.db
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: False)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: True)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: False)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: False)
  bounding_box: False
  # Optional: crop the snapshot (default: False)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: 10)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 10
cameras:

### Other cameras removed ###

  trailcam-1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://trailcam-1.XXXX.XXXX:8554/stream1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
```

### Relevant log output

```shell
2023-12-28 15:27:00.264109646  [2023-12-28 15:27:00] watchdog.trailcam-1            ERROR   : Ffmpeg process crashed unexpectedly for trailcam-1.
2023-12-28 15:27:00.264329276  [2023-12-28 15:27:00] watchdog.trailcam-1            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-12-28 15:27:00.264451896  [2023-12-28 15:27:00] ffmpeg.trailcam-1.detect       ERROR   : [rtsp @ 0x55d61e2c6f00] method SETUP failed: 461 Unsupported transport
2023-12-28 15:27:00.264705446  [2023-12-28 15:27:00] ffmpeg.trailcam-1.detect       ERROR   : rtsp://trailcam-1.XXXX.XXXX:8554/stream1: Protocol not supported
2023-12-28 15:27:00.418955204  [2023-12-28 15:27:00] frigate.video                  ERROR   : trailcam-1: Unable to read frames from ffmpeg process.
2023-12-28 15:27:00.419145914  [2023-12-28 15:27:00] frigate.video                  ERROR   : trailcam-1: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55bec0812140] max delay reached. need to consume packet
[rtsp @ 0x55bec0812140] RTP: missed 3 packets
[rtsp @ 0x55bec0812140] max delay reached. need to consume packet
[rtsp @ 0x55bec0812140] RTP: missed 96 packets
Input #0, rtsp, from 'rtsp://trailcam-1.XXXX.XXXX:8554/stream1':
  Metadata:
    title           : Unnamed
    comment         : N/A
  Duration: N/A, start: 5231.881122, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 10 fps, 10.83 tbr, 90k tbn
```

### Frigate stats

```json
"gpu_usages": {
        "NVIDIA GeForce GTX 1050 Ti": {
            "gpu": "0 %",
            "mem": "12.7 %"
        }
    },
    "service": {
        "last_updated": 1703796055,
        "latest_version": "0.12.1",
        "storage": {
            "/dev/shm": {
                "free": 261.7,
                "mount_type": "tmpfs",
                "total": 268.4,
                "used": 6.7
            },
            "/media/frigate/clips": {
                "free": 27867.9,
                "mount_type": "ext4",
                "total": 33635.9,
                "used": 4033.3
            },
            "/media/frigate/recordings": {
                "free": 27867.9,
                "mount_type": "ext4",
                "total": 33635.9,
                "used": 4033.3
            },
            "/tmp/cache": {
                "free": 2125.7,
                "mount_type": "tmpfs",
                "total": 2147.5,
                "used": 21.8
            }
        },
        "temperatures": {
            "apex_0": 48.8
        },
        "uptime": 865,
        "version": "0.12.1-367d724"
    },
    "trailcam-1": {
        "camera_fps": 0,
        "capture_pid": 519,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 2054,
        "pid": 461,
        "process_fps": 0,
        "skipped_fps": 0
    }
}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

RPi with Arducam

**Comment by NickM-27** [comment]
looks like the camera is UDP only, you should try using the `preset-rtsp-udp` input args

**Comment by jrussell05** [comment]
Thanks @NickM-27.  I ended up moving away from `cvlc `for streaming got `mediamtx `working.  All seems good now.

**Comment by NickM-27** [comment]
feel free to create a new issue if something else comes up

**Comment by eridon-pro** [comment]
Hi @jrussell05 ,

I'm encountering same issue. How did you fix the issue by mediamtx? It would be great if you could show me the actual configuration.

**Comment by jrussell05** [comment]
Hi @eridon-pro ,

Here is what I changed in my `mediamtx.yml` file:

```
###############################################
# Path settings

# Settings in "paths" are applied to specific paths, and the map key
# is the name of the path.
# Any setting in "pathDefaults" can be overridden here.
# It's possible to use regular expressions by using a tilde as prefix,
# for example "~^(test1|test2)$" will match both "test1" and "test2",
# for example "~^prefix" will match all paths that start with "prefix".
paths:
  # example:
  # my_camera:
  #   source: rtsp://my_camera
  # RPi Camera
  cam:
    source: rpiCamera

  # Settings under path "all_others" are applied to all paths that
  # do not match another entry.
  all_others:
```

And here is my config in Frigate:

```
  trailcam-1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://trailcam-1:8554/cam
          roles:
            - detect
        - path: rtsp://trailcam-1:8554/cam
          roles:
            - record
```

Good luck.  I remember it being a frustrating experience getting it working for myself.  For instance, I didn't put the `/cam` at the end of the URL, which I didn't catch for a while.
