### ISSUE TITLE
[Support]: Error occurs when updating subLabel

### ISSUE THREAD

**Issue by CodingTomato** [blakeblackshear/frigate#9109]
### Describe the problem you are having

I'm trying to change a subLabel of a certain clip in NodeJS. Maybe I'm doing something wrong, but to me it doesn't seem so.

I'm getting the following error in the logs:
```
2023-12-28 23:08:37.097948168  TypeError: can only concatenate str (not "NoneType") to str
2023-12-28 23:09:21.449725582  [2023-12-28 23:09:21] frigate.http                   ERROR   : Exception on /events/1703694950.996275-4r3yak/sub_label [POST]
2023-12-28 23:09:21.449728285  Traceback (most recent call last):
2023-12-28 23:09:21.449730452    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2023-12-28 23:09:21.449732229      response = self.full_dispatch_request()
2023-12-28 23:09:21.449734262    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2023-12-28 23:09:21.449735971      rv = self.handle_user_exception(e)
2023-12-28 23:09:21.449737889    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2023-12-28 23:09:21.449739504      rv = self.dispatch_request()
2023-12-28 23:09:21.449741392    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2023-12-28 23:09:21.449766176      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-28 23:09:21.449768177    File "/opt/frigate/frigate/http.py", line 438, in set_sub_label
2023-12-28 23:09:21.449851089      "message": "Event " + id + " sub label set to " + new_sub_label,
2023-12-28 23:09:21.449853574  TypeError: can only concatenate str (not "NoneType") to str
```

And I'm using the following code in Node JS: 
```
await fetch(
    `http://192.168.178.140:5000/api/events/${clipId}/sub_label`,
    {
      method: 'POST',
      body: JSON.stringify({ subLabel: 'test' }),
    },
  );
```

Thanks for the awesome work and help!

### Version

0.13.0-beta7

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.178.34
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

birdseye:
  enabled: True
  mode: objects
  restream: true

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3
  cpu4:
    type: cpu
    num_threads: 3

record:
  enabled: True
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 60
      mode: active_objects

snapshots:
  enabled: True

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    einfahrt:
      - rtsp://viewer:<myPassword>@192.168.178.113:554/h264Preview_01_main # 4608*1728@20fps
    einfahrt_sub:
      - rtsp://viewer:<myPassword>@192.168.178.113:554/h264Preview_01_sub # 1536*576@20fps
    einfahrt_schwenk:
      - rtsp://viewer:<myPassword>@192.168.178.52:554/h264Preview_01_main # 2560*1920@30fps
    einfahrt_schwenk_sub:
      - rtsp://viewer:<myPassword>@192.168.178.52:554/h264Preview_01_sub # 640*480@7fps
    halle:
      - rtsp://viewer:<myPassword>@192.168.178.37:554/h264Preview_01_main # 2560*1920@30fps
    halle_sub:
      - rtsp://viewer:<myPassword>@192.168.178.37:554/h264Preview_01_sub # 640*480@7fps
    parkplatz:
      - rtsp://viewer:<myPassword>@192.168.178.33:554/h264Preview_01_main # 2304*1296@30fps
    parkplatz_sub:
      - rtsp://viewer:<myPassword>@192.168.178.33:554/h264Preview_01_sub # 640*480@7fps

cameras:
  #########################################
  #         Kamera Einfahrt               #
  #########################################
  kamera_einfahrt:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/einfahrt_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/einfahrt
          roles:
            - record
    detect:
      enabled: True 
      width: 1536
      height: 576
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
    motion:
      mask:
        - 380,535,382,576,0,576,0,540
    zones:
      reinhold_einfahrt:
        coordinates: 0,529,0,280,243,237,319,517
      einfahrt:
        coordinates: 890,196,878,0,577,74,234,201,328,480
      garten:
        coordinates: 381,455,898,199,885,0,1536,0,1536,576,444,576
  
  #########################################
  #         Kamera Schwenk                #
  #########################################
  kamera_einfahrt_schwenk:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/einfahrt_schwenk_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/einfahrt_schwenk
          roles:
            - record
      output_args:
        record: preset-record-generic
    detect:
      enabled: True 
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
    motion:
      mask:
        - 629,445,632,466,433,468,432,441
        - 225,445,227,480,0,480,0,444
    zones:
      einfahrt:
        coordinates: 215,239,243,139,371,112,470,148,640,216,640,404,640,441,289,442,0,373
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.178.52
      # Optional: ONVIF port for device (default: shown below).
      port: 8000
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: <myPassword>
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: True
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: True
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: disabled
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.3
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
          #- car
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - einfahrt
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: Einfahrt
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        #timeout: 10
        # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
        #movement_weights: []

  #########################################
  #         Kamera Halle                  #
  #########################################
  kamera_halle:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/halle_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/halle
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 215,440,213,468,8,473,9,448

  #########################################
  #         Kamera Parkplatz              #
  #########################################
  kamera_parkplatz:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/parkplatz_sub
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/parkplatz
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          mask:
            - 487,29,146,49,76,78,0,100,0,380,263,331,470,307,518,271,566,155
    audio:
      enabled: True
    zones:
      container:
        coordinates: 0,0,0,265,0,480,455,480,536,290,581,214,595,0
      einfahrt:
        coordinates: 640,230,640,0,586,0,583,210,439,480,640,480
    motion:
      mask:
        - 11,468,206,469,208,445,17,445
        - 478,253,520,176,455,74,316,36,272,214
```

### Relevant log output

```shell
2023-12-28 23:09:21.449725582  [2023-12-28 23:09:21] frigate.http                   ERROR   : Exception on /events/1703694950.996275-4r3yak/sub_label [POST]
2023-12-28 23:09:21.449728285  Traceback (most recent call last):
2023-12-28 23:09:21.449730452    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2023-12-28 23:09:21.449732229      response = self.full_dispatch_request()
2023-12-28 23:09:21.449734262    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2023-12-28 23:09:21.449735971      rv = self.handle_user_exception(e)
2023-12-28 23:09:21.449737889    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2023-12-28 23:09:21.449739504      rv = self.dispatch_request()
2023-12-28 23:09:21.449741392    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2023-12-28 23:09:21.449766176      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-28 23:09:21.449768177    File "/opt/frigate/frigate/http.py", line 438, in set_sub_label
2023-12-28 23:09:21.449851089      "message": "Event " + id + " sub label set to " + new_sub_label,
2023-12-28 23:09:21.449853574  TypeError: can only concatenate str (not "NoneType") to str
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
{"cameras":{"kamera_einfahrt":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":357,"detection_enabled":1,"detection_fps":3.3,"ffmpeg_pid":384,"pid":350,"process_fps":1.5,"skipped_fps":3.6},"kamera_einfahrt_schwenk":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":359,"detection_enabled":1,"detection_fps":2.0,"ffmpeg_pid":365,"pid":351,"process_fps":2.5,"skipped_fps":2.5},"kamera_halle":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.1,"capture_pid":361,"detection_enabled":1,"detection_fps":3.0,"ffmpeg_pid":369,"pid":352,"process_fps":3.5,"skipped_fps":1.9},"kamera_parkplatz":{"audio_dBFS":-25.6988,"audio_rms":1700.2471,"camera_fps":5.1,"capture_pid":364,"detection_enabled":1,"detection_fps":3.2,"ffmpeg_pid":380,"pid":355,"process_fps":1.3,"skipped_fps":3.9}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"3.5","cpu_average":"11","mem":"0.3"},"107":{"cmdline":"python3 -u -m frigate","cpu":"1.1","cpu_average":"2","mem":"4.7"},"109":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"120":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"141":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"142":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"294":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.3"},"296":{"cmdline":"frigate.recording_manager","cpu":"0.3","cpu_average":"2","mem":"1.8"},"304":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(55)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"305":{"cmdline":"frigate.detector.cpu1","cpu":"91.4","cpu_average":"25","mem":"1.7"},"307":{"cmdline":"frigate.detector.cpu2","cpu":"89.7","cpu_average":"26","mem":"1.7"},"309":{"cmdline":"frigate.detector.cpu3","cpu":"89.5","cpu_average":"25","mem":"1.7"},"311":{"cmdline":"frigate.detector.cpu4","cpu":"92.9","cpu_average":"26","mem":"1.7"},"312":{"cmdline":"frigate.output       ","cpu":"0.4","cpu_average":"1","mem":"1.6"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1536x576 -i pipe: -f mpegts -s 1920x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"315":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"317":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"318":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"319":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.1","cpu_average":"0","mem":"0.6"},"350":{"cmdline":"frigate.process:kamera_einfahrt","cpu":"1.4","cpu_average":"2","mem":"1.9"},"351":{"cmdline":"frigate.process:kamera_einfahrt_schwenk","cpu":"1.3","cpu_average":"2","mem":"1.9"},"352":{"cmdline":"frigate.process:kamera_halle","cpu":"1.3","cpu_average":"1","mem":"1.9"},"355":{"cmdline":"frigate.process:kamera_parkplatz","cpu":"1.1","cpu_average":"1","mem":"1.9"},"357":{"cmdline":"frigate.capture:kamera_einfahrt","cpu":"0.7","cpu_average":"1","mem":"1.7"},"359":{"cmdline":"frigate.capture:kamera_einfahrt_schwenk","cpu":"0.3","cpu_average":"0","mem":"1.7"},"361":{"cmdline":"frigate.capture:kamera_halle","cpu":"0.3","cpu_average":"0","mem":"1.7"},"364":{"cmdline":"frigate.capture:kamera_parkplatz","cpu":"0.3","cpu_average":"0","mem":"1.7"},"365":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/einfahrt_schwenk_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"1","mem":"0.5"},"368":{"cmdline":"frigate.audio_manager","cpu":"4.5","cpu_average":"1","mem":"1.9"},"369":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/halle_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.4","cpu_average":"1","mem":"0.5"},"378":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/halle -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/kamera_halle@%Y%m%d%H%M%S%z.mp4","cpu":"2.4","cpu_average":"5","mem":"0.3"},"380":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/parkplatz_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.4","cpu_average":"0","mem":"0.5"},"381":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/einfahrt_schwenk -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/kamera_einfahrt_schwenk@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.3"},"383":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/parkplatz_sub -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.1","cpu_average":"0","mem":"0.3"},"384":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/einfahrt_sub -r 5 -vf fps=5,scale_vaapi=w=1536:h=576:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.0","cpu_average":"2","mem":"0.6"},"388":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/parkplatz -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/kamera_parkplatz@%Y%m%d%H%M%S%z.mp4","cpu":"2.3","cpu_average":"5","mem":"0.3"},"390":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/einfahrt -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/kamera_einfahrt@%Y%m%d%H%M%S%z.mp4","cpu":"2.4","cpu_average":"5","mem":"0.3"},"3065":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":11.5,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":327.25,"pid":305},"cpu2":{"detection_start":1703805595.050081,"inference_speed":326.9,"pid":307},"cpu3":{"detection_start":1703805595.179741,"inference_speed":340.75,"pid":309},"cpu4":{"detection_start":0.0,"inference_speed":323.37,"pid":311}},"gpu_usages":{"intel-vaapi":{"gpu":"1.75%","mem":"-%"}},"processes":{"audioDetector":{"pid":368},"go2rtc":{"pid":89},"logger":{"pid":294},"recording":{"pid":296}},"service":{"last_updated":1703805595,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":142.6,"mount_type":"tmpfs","total":150.0,"used":7.4},"/media/frigate/clips":{"free":1468035.3,"mount_type":"ext4","total":2815557.6,"used":1204426.9},"/media/frigate/recordings":{"free":1468035.3,"mount_type":"ext4","total":2815557.6,"used":1204426.9},"/tmp/cache":{"free":206249.7,"mount_type":"overlay","total":236716.5,"used":19763.5}},"temperatures":{},"uptime":892,"version":"0.13.0-c35c7da"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink
