### ISSUE TITLE
[Camera Support]: HiLook streams are laggy and playback is choppy

### ISSUE THREAD

**Issue by deanfourie1** [blakeblackshear/frigate#9131]
### Describe the problem you are having

Playback is not smooth, its choppy and can miss large chunks of footage.
Also, sometimes in the "Cameras" section, the image does not load and it says waiting for frames. If I got away from the cameras tab and come back, there image will be there but a different camera would have dropped out.

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: False

birdseye:
# Optional: Enable birdseye view (default: shown below)
  enabled: True
# Optional: Width of the output resolution (default: shown below)
  width: 1408
# Optional: Height of the output resolution (default: shown below)
  height: 1152
# Optional: Encoding quality of the mpeg1 feed (default: shown below)
# 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15
# Optional: Mode of the view. Available options are: objects, motion, and continuous
#   objects - cameras are included if they have had a tracked object within the last 30 seconds
#   motion - cameras are included if motion was detected in the last 30 seconds
#   continuous - all cameras are included always
  mode: continuous

cameras:
  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/101/ # <----- The stream you want to use for detection
          roles:
            - detect
            - record
  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    motion:
      mask:
        - 674,625,620,720,0,720,0,433,170,444,401,366,485,414
        - 383,106,127,213,95,36,251,0
        - 1280,76,1280,0,913,0
  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    motion:
      mask:
        - 251,123,297,182,223,219,405,284,531,216,931,243,1032,154,1202,121,1280,159,1280,0,303,0
        - 1218,383,948,307,1280,166,1280,609

  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    motion:
      mask:
        - 567,0,298,720,0,720,0,0
        - 1280,247,865,56,1280,0
        - 964,520,941,661,1025,633,1205,552,1007,249,796,94,753,101
  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@1redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    motion:
      mask:
        - 1251,0,1280,0,1280,720,1073,720
        - 542,0,57,169,0,236,0,0,96,0
        - 1280,135,1280,0,1004,0
  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    motion:
      mask:
        - 1280,0,1280,217,1129,79,1130,0
        - 0,0,112,0,262,147,0,385
        - 1130,188,1141,0,581,0

  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,176,386,120,518,133,677,151,884,81,1058,83,1075,0,0,0

  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record

  redacted: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://redacted:redacted@redacted/Streaming/Channels/1/
 # <----- The stream you want to use for detection
          roles:
            - detect
            - record


  
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 32
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 15

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 32
    # Optional: Per object retention days
    objects:
      person: 32

# Optional: RTMP configuration
# NOTE: RTMP is deprecated in favor of restream
# NOTE: Can be overridden at the camera level

database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/frigate.db

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      mask: 0,0,1000,0,1000,200,0,200

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level

detectors:
  # Required: name of the detector
  default:
    # Required: type of the detector
    # Frigate provided types include 'cpu', 'edgetpu', and 'openvino' (default: shown below)
    # Additional detector types can also be plugged in.
    # Detectors may require additional configuration.
    # Refer to the Detectors configuration page for more information.
    type: cpu
```

### Relevant log output

```shell
VAINFO OUTPUT
Return Code: 0

Process Output:

vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
VAProfileNone : VAEntrypointVideoProc
VAProfileNone : VAEntrypointStats
VAProfileMPEG2Simple : VAEntrypointVLD
VAProfileMPEG2Simple : VAEntrypointEncSlice
VAProfileMPEG2Main : VAEntrypointVLD
VAProfileMPEG2Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointFEI
VAProfileH264Main : VAEntrypointEncSliceLP
VAProfileH264High : VAEntrypointVLD
VAProfileH264High : VAEntrypointEncSlice
VAProfileH264High : VAEntrypointFEI
VAProfileH264High : VAEntrypointEncSliceLP
VAProfileVC1Simple : VAEntrypointVLD
VAProfileVC1Main : VAEntrypointVLD
VAProfileVC1Advanced : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointEncPicture
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264ConstrainedBaseline: VAEntrypointFEI
VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
VAProfileVP8Version0_3 : VAEntrypointVLD
VAProfileVP8Version0_3 : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointFEI
VAProfileHEVCMain10 : VAEntrypointVLD
VAProfileHEVCMain10 : VAEntrypointEncSlice
VAProfileVP9Profile0 : VAEntrypointVLD
VAProfileVP9Profile2 : VAEntrypointVLD
```

### FFprobe output from your camera

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 3200x1800
FPS: 20/1

Audio:

Codec: PCM mu-law / G.711 mu-law
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

HiLook
