### ISSUE TITLE
[Config Support]: Only person allowed on zone 

### ISSUE THREAD

**Issue by Routout** [blakeblackshear/frigate#9132]
### Describe the problem you are having

I can't add a car in my zone config, Frigate doesn't start up if I add anything else than a person in zone objects.

### Version

0.13.0

### Frigate config file

```yaml
mqtt:
  host: ******
  user: ********
  password: ********
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
go2rtc:
  streams:
    front:
    - rtsp://*******************************
    - ffmpeg:camera#audio=opus
timestamp_style:
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

#Global Object Settings
#objects:
#  track:
#    - person
#    - car
#  - license_plate
#    - cat
#  - dog
#  - deer
#  filters:
#    person:
#      min_score: .75
#    car:
#      min_score: .75
#      min_area: 5000
#      max_area: 100000
cameras:
  front:
    ffmpeg:
      inputs:
      - path: rtsp://**********************
        roles:
        - record
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1920
      height: 1080
      fps: 5
#      stationary:
        #interval: 5
#        threshold: 50
    record:
      enabled: true
      events:
        required_zones:
        - zone_0
#        - zone_1
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: true
    zones:
      zone_0:
        coordinates: 728,473,1920,717,1868,791,591,488
        objects:
#          - car
          - person
#          - umbrella

    
motion:
  # https://deploy-preview-6262--frigate-docs.netlify.app/configuration/motion_detection/
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 100
    # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
    # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
```

### Relevant log output

```shell
No log because wont start
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
