### ISSUE TITLE
[Support]: Increasing memory usage

### ISSUE THREAD

**Issue by martinj9320** [blakeblackshear/frigate#9164]
### Describe the problem you are having

I have the same issue as described in #7079. As this issue was closed without a solution, I thought I'd open a new one.
Memory usage is constantly increasing until about 500 MB of 16 GB are left. In my case the high usage also comes from "buff/cache".

![grafik](https://github.com/blakeblackshear/frigate/assets/64349124/e7bcba18-9b2a-436f-ae58-f2496564610e)

The logs don't show any errors. I was previously running `go2rtc` `v1.3.1` because hardware transpose wasn't supported with the integrated version and upgraded to `v1.5.0` because apparently this has solved issues with high memory usage for others, though unfortunatly not for me.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  log:
    exec: trace
  streams:
    Turbinenhaus:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.100:554/ch1/main
    Turbinenhaus_gedreht:
      - "ffmpeg:Turbinenhaus#video=h264#rotate=90#hardware"
    Rechenreiniger:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.101:554/ch1/main
    Muehlenhof:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.102:554/ch1/main
    Werkstatt:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.170.103:554/ch1/main

detectors:
  coral:
    type: edgetpu
    device: pci

birdseye:
  mode: continuous
  restream: true

objects:
  track:
    - person
    - car

record:
  enabled: true
  retain:
    days: 0
  events:
    pre_capture: 20
    post_capture: 20
    objects:
      - person
      - car
    retain:
      default: 14
      mode: active_objects

cameras:
  Turbinenhaus:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Turbinenhaus_gedreht
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1080
      height: 1920
    live:
      stream_name: Turbinenhaus_gedreht

  Rechenreiniger:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Rechenreiniger
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080

  Muehlenhof:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Muehlenhof
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 3840
      height: 2160

  Werkstatt:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Werkstatt
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Grundig GD-CI-CC2616V
