### ISSUE TITLE
[Support]: Big delay in stream

### ISSUE THREAD

**Issue by JohannCR** [blakeblackshear/frigate#9171]
### Describe the problem you are having

Stream has a big delay for some cameras... Like nearly 5 minutes.
Here's an example in HA (note that the same delay exists in frigate interface). Notice the time difference between stream and top of screenshot:
![Capture d’écran du 2024-01-02 10-28-48](https://github.com/blakeblackshear/frigate/assets/7448079/6e521fd1-4345-485e-b58e-461e5f4eb942)
![Capture d’écran du 2024-01-02 18-19-38](https://github.com/blakeblackshear/frigate/assets/7448079/e89f35ba-1a50-48af-b61b-9de44139685e)

Got multiple cameras of same make and model, and two out of them do that (not the others). They are all wired the same way, with identical cable type and length, plus I didn't get that delay using another NVR like DSM surveillance station.

Don't know if it's related, but I get lots of errors "Unable to read frames from ffmpeg process" when restarting Frigate and after a few minutes the errors disappear and the streams do work without any further error (delay still present though).

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.68.xxxx
  client_id: frigate
  user: xxxx
  password: xxxx
logger:
  default: error
  logs:
    frigate.mqtt: error
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  log:
    exec: trace
  streams:
    frigate_interieur: 
      - "ffmpeg:http://192.168.0.xxxx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus"
    frigate_entree: 
      - "ffmpeg:http://192.168.0.xxxx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus"
    frigate_jardin: 
      - "ffmpeg:http://192.168.0.xxxx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus"
    frigate_jardin_est: 
      - "ffmpeg:http://192.168.0.xxxx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus"
    frigate_jardin_est_rotated:
      - "ffmpeg:frigate_jardin_est#video=h264#rotate=90"
    frigate_ptz: 
      - "ffmpeg:rtsp://xxxx:xxxx@192.168.68.xxxx:554?subtype=PROFILE_001#video=h264"
  webrtc:
    candidates:
      - 192.168.68.xxxx:8555
      - 127.0.0.1:8555
      - stun:8555
cameras:
  frigate_interieur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_interieur?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: False
    mqtt:
      crop: False
      timestamp: False
      bounding_box: False
  frigate_entree:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_entree?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    mqtt:
      crop: False
      timestamp: False
      bounding_box: False
  frigate_jardin:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_jardin?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    mqtt:
      crop: False
      timestamp: False
      bounding_box: False
  frigate_jardin_est_rotated:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_jardin_est_rotated?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    mqtt:
      crop: False
      timestamp: False
      bounding_box: False
  frigate_ptz:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_ptz?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
    rtmp:
      enabled: False
    detect:
      enabled: False
    mqtt:
      crop: False
      timestamp: False
      bounding_box: False
detectors:
    cpu1:
      type: cpu
      num_threads: 3
detect:
  enabled: True
  width: 640
  height: 480
  fps: 4
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
objects:
  track:
    - person
    - dog
  filters:
    person:
      min_score: 0.5
      threshold: 0.7
    dog:
      min_score: 0.7
      threshold: 0.8
snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: False
  crop: False
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

Using frigate interface for camera with delay :
```Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.0"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"2.3","mem":"0.2"},"108":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"3.7","mem":"3.1"},"118":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"210":{"cpu":"0.0","mem":"0.8"},"216":{"cpu":"0.7","mem":"0.1"},"217":{"cpu":"0.0","mem":"1.0"},"218":{"cpu":"0.7","mem":"0.9"},"220":{"cpu":"0.3","mem":"0.9"},"221":{"cpu":"0.7","mem":"1.0"},"223":{"cpu":"0.3","mem":"0.9"},"224":{"cpu":"0.0","mem":"0.2"},"225":{"cpu":"0.3","mem":"0.9"},"226":{"cpu":"0.0","mem":"0.2"},"227":{"cpu":"0.3","mem":"0.9"},"228":{"cpu":"0.3","mem":"0.9"},"229":{"cpu":"0.0","mem":"0.2"},"230":{"cpu":"0.7","mem":"0.9"},"231":{"cpu":"0.7","mem":"0.9"},"232":{"cpu":"0.0","mem":"0.2"},"236":{"cpu":"0.3","mem":"0.9"},"238":{"cpu":"0.0","mem":"0.2"},"239":{"cpu":"0.3","mem":"0.9"},"24":{"cpu":"0.0","mem":"0.0"},"246":{"cpu":"0.0","mem":"0.2"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"355":{"cpu":"19.7","mem":"0.5"},"361":{"cpu":"2.3","mem":"0.3"},"379":{"cpu":"6.3","mem":"0.5"},"387":{"cpu":"17.0","mem":"0.4"},"390":{"cpu":"3.0","mem":"0.3"},"394":{"cpu":"2.3","mem":"0.3"},"398":{"cpu":"2.3","mem":"0.3"},"41":{"cpu":"0.0","mem":"0.0"},"417":{"cpu":"6.3","mem":"0.6"},"418":{"cpu":"6.0","mem":"0.5"},"42":{"cpu":"0.0","mem":"0.0"},"421":{"cpu":"5.7","mem":"0.5"},"423":{"cpu":"6.7","mem":"0.5"},"77":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"934":{"cpu":"0.0","mem":"0.0"},"962":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"3150.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":465.57,"pid":217}},"frigate_entree":{"camera_fps":4.2,"capture_pid":230,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":418,"pid":221,"process_fps":4.2,"skipped_fps":0.0},"frigate_interieur":{"camera_fps":4.2,"capture_pid":228,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":417,"pid":220,"process_fps":4.2,"skipped_fps":0.0},"frigate_jardin":{"camera_fps":4.1,"capture_pid":231,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":421,"pid":223,"process_fps":4.1,"skipped_fps":0.0},"frigate_jardin_est_rotated":{"camera_fps":4.1,"capture_pid":236,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":423,"pid":225,"process_fps":4.1,"skipped_fps":0.0},"frigate_ptz":{"camera_fps":4.1,"capture_pid":239,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":379,"pid":227,"process_fps":4.1,"skipped_fps":0.0},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"service":{"last_updated":1704189059,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":263.8,"mount_type":"tmpfs","total":268.4,"used":4.6},"/media/frigate/clips":{"free":813817.0,"mount_type":"btrfs","total":1915630.6,"used":1101813.6},"/media/frigate/recordings":{"free":813817.0,"mount_type":"btrfs","total":1915630.6,"used":1101813.6},"/tmp/cache":{"free":998.7,"mount_type":"tmpfs","total":1000.0,"used":1.3}},"temperatures":{},"uptime":506,"version":"0.12.1-367d724"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 510A

### Any other information that may be helpful

Frigate docker container in DSM synology DS220+

**Comment by JohannCR** [comment]
Tried to disable detection in case it was due to some kind of CPU overload, delay is still present.

FYI here's an extract of go2rtc log error for a camera with no delay but ffmpeg rotation error :
```
2024-01-02 11:02:34.396001133  [INFO] Starting go2rtc healthcheck service...
2024-01-02 11:02:34.816147812  [h264 @ 0x56247a223e00] reference picture missing during reorder
2024-01-02 11:02:34.816154566  [h264 @ 0x56247a223e00] Missing reference picture, default is 142
2024-01-02 11:02:35.806455839  [h264 @ 0x56247a223e00] reference picture missing during reorder
2024-01-02 11:02:35.806463116  [h264 @ 0x56247a223e00] Missing reference picture, default is 166
2024-01-02 11:02:36.816637594  [h264 @ 0x56247a223e00] reference picture missing during reorder
2024-01-02 11:02:36.816939083  [h264 @ 0x56247a223e00] Missing reference picture, default is 190
2024-01-02 11:02:37.815901719  [h264 @ 0x56247a223e00] reference picture missing during reorder
2024-01-02 11:02:37.815908365  [h264 @ 0x56247a223e00] Missing reference picture, default is 214
2024-01-02 11:02:38.785468529  rtsp://localhost:8554/frigate_jardin_est?video: Invalid data found when processing input
2024-01-02 11:02:38.786840462  11:02:38.786 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:frigate_jardin_est#video=h264#rotate=90
2024-01-02 11:02:38.786888629  11:02:38.786 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=frigate_jardin_est_rotated
2024-01-02 11:02:38.787074148  11:02:38.786 DBG [exec] run url="exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i rtsp://localhost:8554/frigate_jardin_est?video -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -an -vf transpose=1 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/c93496a6e32da78c533d2f8b2e863a73"
```


camera with delay :
```
2024-01-02 11:02:38.846663045  Output #0, rtsp, to 'rtsp://localhost:8554/ce66e5cf07f7a09f90b48969bd62235f':
2024-01-02 11:02:38.846669960    Metadata:
2024-01-02 11:02:38.846671582      displayWidth    : 640
2024-01-02 11:02:38.846672977      displayHeight   : 480
2024-01-02 11:02:38.846674441      encoder         : Lavf59.27.100
2024-01-02 11:02:38.846675963  11:02:38.846 DBG [exec] run launch=10.301697893s
2024-01-02 11:02:38.846677793    Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, q=2-31, 4 fps, 30 tbr, 90k tbn
2024-01-02 11:02:38.846679374    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp (default)
2024-01-02 11:02:38.846680931    Stream #0:2: Audio: opus, 48000 Hz, stereo, flt, 96 kb/s
2024-01-02 11:02:38.846684191      Metadata:
2024-01-02 11:02:38.846685660        encoder         : Lavc59.37.100 libopus
2024-01-02 11:02:38.846687457  11:02:38.846 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2024-01-02 11:02:38.846691559  11:02:38.846 DBG [exec] run url="exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -i http://192.168.0.6/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=entreeadmin&password=lLV6tzK1zTDYh3 -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -ar:a:1 48000 -ac:a:1 2 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/ce66e5cf07f7a09f90b48969bd62235f"
2024-01-02 11:02:38.862142926  frame=    0 fps=0.0 q=-1.0 size=N/A time=00:00:10.11 bitrate=N/A speed=N/A    
11:02:38.861 DBG [exec] run launch=10.323817009s
```

**Comment by NickM-27** [comment]
what is your frigate card config?

**Comment by JohannCR** [comment]
Well, since he delay also happens in the frigate interface, I don't see how the card config would matter, but anyway here you go :

```
    type: custom:frigate-card
    cameras:
      - live_provider: auto
        triggers:
          occupancy: false
        camera_entity: camera.frigate_entree
        go2rtc:
          modes:
            - webrtc
          stream: frigate_entree
        frigate:
          camera_name: frigate_entree
          url: http://192.168.68.xxxx
    live:
      lazy_unload: hidden
      auto_play: all
      controls:
        title:
          mode: none
        builtin: false
      draggable: false
      auto_pause: never
      zoomable: false
      auto_mute: all
      layout:
        fit: contain
    dimensions:
      aspect_ratio_mode: static
      aspect_ratio: '4:3'
    view:
      default: live
    menu:
      buttons:
        frigate:
          enabled: false
        cameras:
          enabled: false
        substreams:
          enabled: false
        live:
          enabled: true
        media_player:
          enabled: false
        timeline:
          enabled: false
        camera_ui:
          enabled: false
        download:
          enabled: false
        clips:
          enabled: false
        screenshot:
          enabled: true
        mute:
          enabled: true
      style: overlay
    image:
      mode: camera
    timeline:
      show_recordings: false

```
