### ISSUE TITLE
[Config Support]: inertia parameter

### ISSUE THREAD

**Issue by xavan83** [blakeblackshear/frigate#9175]
### Describe the problem you are having

I don't find all the information I need when reading the documentation about inertia parameter.
You are talking about a number of frames. Which one? The detection fps (in my case 5fps) or the camera fps (in my case 24fps).
I want to receive mqtt notification only for cars that are running to slowly to cross the street (zone==streetcar).
I receive notification for car that cross the street in only one second (only from the moment a car is detected, this happens about half the fov of the camera). However I setup a inertia of 72 for the zone (3seconds for 24fps or 14,4 with 5fps).

### Version

0.13.0-c35c7da

### Frigate config file

```yaml
sonnette:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/sonnette?video=copy&audio=aac
          roles:
            - detect,record
    detect:
      fps: 5
      enabled: True
      width: 1920
      height: 1080
    motion:
      mask:
        - 0,674,880,739,1514,672,1920,597,1920,0,0,0
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      quality: 100
      required_zones: [streetpeople,streetcar,boiteauxlettres]
    zones:
      streetpeople:
        objects:
          - person
        inertia: 120
        coordinates: 0,1080,1920,1080,1920,389,0,451
      streetcar:
        objects:
          - car
        inertia: 72
        coordinates: 0,1080,1920,1080,1920,389,0,451
      boiteauxlettres:
        objects:
          - person
        coordinates: 1920,1045,1920,1080,0,1080,0,1041
```

### Relevant log output

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)
