### ISSUE TITLE
[Support]: Frigate is adding a config to go2rtc which is disabling audio

### ISSUE THREAD

**Issue by jkay90** [blakeblackshear/frigate#9186]
### Describe the problem you are having

Here's the ffprobe output for one of my camera

```
[
  {
    "return_code": 0,
    "stderr": "",
    "stdout": {
      "programs": [],
      "streams": [
        {
          "avg_frame_rate": "25/1",
          "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
          "height": 1440,
          "width": 2560
        }
      ]
    }
  }
]
```

And here's the ffprobe output if I remove the following from go2rtc config

```
rtsp:
  default_query: mp4
```
![image](https://github.com/blakeblackshear/frigate/assets/1256194/a7448d63-ca9c-4679-9122-2f5ed1262652)

```[
  {
    "return_code": 0,
    "stderr": "",
    "stdout": {
      "programs": [],
      "streams": [
        {
          "avg_frame_rate": "15/1",
          "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
          "height": 1440,
          "width": 2560
        },
        {
          "avg_frame_rate": "0/0",
          "bit_rate": "64000",
          "codec_long_name": "PCMA-law/G.711A-law"
        }
      ]
    }
  }
]
```

I used to just delete the go2rtc config and it works fine. but when I had to reboot my docker host operating system then the config is back

### Version

0.13.0-614A36A

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560}]}}]
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Tapo C220

**Comment by NickM-27** [comment]
This is working as intended, mp4 is required for things like recording because pcma audio does not work. You should add aac audio transcoding to the go2rtc config for cameras that don't produce aac audio like the docs suggest.

**Comment by jkay90** [comment]
Hi Nick, 
Thanks for your time. 
I'm using Tapo camera.  
With `default_query` in go2rtc config, the recordings, restream (the default rtsp link without any url query) have no audio only live view does, removing that config adds audio everywhere. 

So, in my case frigate works as I need without that config. 
```
mqtt:
  enabled: True
  host: localhost
  port: 1883
  topic_prefix: frigate
record:
  enabled: True
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 5
      mode: active_objects
ffmpeg:
  global_args: -hide_banner -loglevel info
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac


birdseye:
  enabled: True
  mode: continuous

detectors:
  coral1:
    type: edgetpu
    device: pci:0  

detect:
  fps: 5
  width: 640
  height: 360

go2rtc:
  streams:
    camera1:
      - tapo://admin:HASH@10.0.0.51
    camera2:
      - tapo://admin:HASH@10.0.0.52
    camera3:
      - tapo://admin:HASH@10.0.0.53
    camera4:
      - tapo://admin:HASH@10.0.0.54
    camera5:
      - tapo://admin:HASH@10.0.0.55
    camera6:
      - tapo://admin:HASH@10.0.0.56
  webrtc:
    candidates:
      - 10.0.0.105:8555
      - stun:8555
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1 #?video&audio
          roles:
            - record
            - detect
    live:
      stream_name: camera1
    birdseye:
      enabled: False
    detect:
      fps: 5

  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2 #?video&audio
          roles:
            - record
            - detect
    live:
      stream_name: camera2
    detect:
      fps: 5

  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4 #?video&audio
          # input_args: -rtsp_transport tcp -timeout 5000000
          roles:
            - record
            - detect
    live:
      stream_name: camera4
    detect:
      fps: 5

  camera5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera5 #?video&audio
          # input_args: -rtsp_transport tcp -timeout 5000000
          roles:
            - record
            - detect
    live:
      stream_name: camera5
    detect:
      fps: 5

  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera3 #?video&audio
          # input_args: -rtsp_transport tcp -timeout 5000000
          roles:
            - detect
            - record
    live:
      stream_name: camera3
    detect:
      fps: 5
  camera6:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera6 #?video&audio
          # input_args: -rtsp_transport tcp -timeout 5000000
          roles:
            - record
            - detect
    live:
      stream_name: camera6
    birdseye:
      enabled: False
    detect:
      fps: 5
    # objects:
    #   track:
    #     - person
```

**Comment by NickM-27** [comment]
you have configured frigate to do the audio transcoding

```
  output_args:
    record: preset-record-generic-audio-aac
```

the suggested solution is to simply have that done in go2rtc and have frigate copy the aac audio from go2rtc.

```
ffmpeg:
  global_args: -hide_banner -loglevel info
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    camera1:
      - tapo://admin:HASH@10.0.0.51
     - "ffmpeg:camera1#audio=aac"
    camera2:
      - tapo://admin:HASH@10.0.0.52
      - "ffmpeg:camera2#audio=aac"
    camera3:
      - tapo://admin:HASH@10.0.0.53
      - "ffmpeg:camera3#audio=aac"
    camera4:
      - tapo://admin:HASH@10.0.0.54
      - "ffmpeg:camera4#audio=aac"
    camera5:
      - tapo://admin:HASH@10.0.0.55
      - "ffmpeg:camera5#audio=aac"
    camera6:
      - tapo://admin:HASH@10.0.0.56
      - "ffmpeg:camera6#audio=aac"
```

 There is no reason that this won't work with your cameras and is what many other users with the same cameras do.

With that repeated, if you want to override the config like that you can but it is not recommended or supported solution.
