### ISSUE TITLE
[Support]: Frigate does not listen to retention configuration

### ISSUE THREAD

**Issue by mabed-fr** [blakeblackshear/frigate#9188]
### Describe the problem you are having

Frigate does not listen to retention configuration

Retention is larger than 1 days for recording

### Version

0.13.0-49814B3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.254

birdseye:
  enabled: True
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi

    #detectors:
    #  coral:
    #    type: edgetpu
    #    device: usb

objects:
 track:
   - person
   - car
   - bicycle
   - motorcycle
   - cat
   - dog
   - plate
   - traffic light

go2rtc:
  streams:
    clim:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main

cameras:
  clim:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    onvif:
      host: 192.168.1.146
      port: 8000
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 10
  stationary:
    interval: 60
    threshold: 60

record:
  expire_interval: 60
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 31

snapshots:
  enabled: true
```

### Relevant log output

```shell
NC
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://frigate:password@192.168.1.146:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: 0.000188, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"cameras":{"clim":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":242,"detection_enabled":1,"detection_fps":1.0,"ffmpeg_pid":252,"pid":241,"process_fps":7.0,"skipped_fps":3.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"14":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"23":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"39":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"46":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"106":{"cmdline":"python3 -u -m frigate","cpu":"1.1","cpu_average":"1","mem":"2.9"},"113":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"125":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"138":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"139":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"140":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"221":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"223":{"cmdline":"frigate.recording_manager","cpu":"0.3","cpu_average":"0","mem":"0.9"},"232":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(41)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"233":{"cmdline":"frigate.detector.cpu ","cpu":"30.8","cpu_average":"15","mem":"0.9"},"234":{"cmdline":"frigate.output       ","cpu":"0.6","cpu_average":"0","mem":"0.8"},"238":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"240":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"241":{"cmdline":"frigate.process:clim ","cpu":"2.7","cpu_average":"3","mem":"1.1"},"242":{"cmdline":"frigate.capture:clim ","cpu":"4.8","cpu_average":"6","mem":"0.8"},"252":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-49814b3 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:password@192.168.1.146:554/h265Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/clim@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"11.9","cpu_average":"15","mem":"0.8"},"92253":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92293":{"cmdline":"timeout 0.5s intel_gpu_top -J -o - -s 1","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92294":{"cmdline":"intel_gpu_top -J -o - -s 1","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":1.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":418.36,"pid":233}},"gpu_usages":{"intel-vaapi":{"gpu":"7.97%","mem":"-%"}},"processes":{"go2rtc":{"pid":92},"logger":{"pid":221},"recording":{"pid":223}},"service":{"last_updated":1704274770,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":2044.0,"mount_type":"tmpfs","total":2048.0,"used":4.0},"/media/frigate/clips":{"free":712114.0,"mount_type":"ext4","total":936330.1,"used":176581.2},"/media/frigate/recordings":{"free":712114.0,"mount_type":"ext4","total":936330.1,"used":176581.2},"/tmp/cache":{"free":1901.8,"mount_type":"tmpfs","total":1907.4,"used":5.5}},"temperatures":{},"uptime":69539,"version":"0.13.0-49814b3"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

rlc-811a

### Any other information that may be helpful

```
~ → date
mer. 03 janv. 2024 10:38:29 CET

~ → du -sh /docker/volumes/frigate/media/frigate/recordings/*
271M    /docker/volumes/frigate/media/frigate/recordings/2023-12-31
1,9G    /docker/volumes/frigate/media/frigate/recordings/2024-01-01
52G     /docker/volumes/frigate/media/frigate/recordings/2024-01-02
34G     /docker/volumes/frigate/media/frigate/recordings/2024-01-03
```
