### ISSUE TITLE
Web UI and api broken.

### ISSUE THREAD

**Issue by mdallaire** [blakeblackshear/frigate#919]
**Describe the bug**
Running Frigate with docker-compose I can't seem to get a web ui. When accessing on serverip:5000 I get a message saying "Frigate is running. Alive and healthy!". When I access using serverip:5000/camera01 I get a stream of the camera I have configured.

My question is what is the URL to access the web ui to configure things like masks? I can't seem to find it anywhere in the docs and https://blakeblackshear.github.io/frigate/usage/web does not provide many details.

**Version of frigate**
Output from `/api/version`

serverip:5000/api/version returns 404 not found.

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: mqtt.redacted.net
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: redacted
cameras:
  camera01:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:redacted@redacted:554/Streaming/Channels/1?transportmode=unicast&profile=Profile_1
          roles:
            - rtmp
            - detect
    width: 1920
    height: 1080
    fps: 30

```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for camera01: 36
frigate.app                    INFO    : Capture process started for camera01: 37
detector.coral                 INFO    : Starting detection process: 33
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.

```

**Frigate stats**
```json
404 not found
```

**Computer Hardware**
 - OS: Ubuntu
 - Install method: docker-compose
 - Virtualization: proxmox
 - Coral Version: None
 - Network Setup: Wired

**Additional context**
