### ISSUE TITLE
[Config Support]: Is the support for dynamic configuration of video sources (streaming addresses) considered?（是否考虑支持动态配置视频源（流地址）)

### ISSUE THREAD

**Issue by AwadYoo** [blakeblackshear/frigate#9197]
### Describe the problem you are having

Is the support for dynamic configuration of video sources (streaming addresses) considered?（是否考虑支持动态配置视频源（流地址）？）

### Version

dev

### Frigate config file

```yaml
cameras:
  name_of_your_camera: # <------ Name the camera
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp # <----- The stream you want to use for detection
          roles:
            - detect
```

### Relevant log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
