### ISSUE TITLE
Audio Detection using Google Coral (instead CPU)

### ISSUE THREAD

**Issue by ufoczek** [blakeblackshear/frigate#9216]
**Description**
I have not found any information about the possibility of selecting a model for audio detection, but I have found that there is a hardcoded cpu_audio_model.tflite in audio.py

**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use Audio Detector using Google Coral devices as cpu_audio_model.tflite uses about 33% of the CPU.

**Describe the solution you'd like**
Allow users to switch between CPU and Coral models. The YamNet model is available at https://coral.ai/models/audio-classification/ with EdgeTPU model and labels files.

![image](https://github.com/blakeblackshear/frigate/assets/5657176/3e00fb0c-d052-4667-9f67-b81862907bc6)

**Comment by Calimerorulez** [comment]
My audio detector only uses:

![image](https://github.com/blakeblackshear/frigate/assets/1130552/b44e3ef1-dec9-4dc3-bc86-6da0f130081f)

For 4 camera's.

**Comment by ufoczek** [comment]
> My audio detector only uses:
> For 4 camera's.

Thanks for sharing the CPU usage on your computer in audio detection. I suspect you are using a much more powerful computer than I am. I'm posting my config with -rc1 by the way. 
Regardless, detection using YamNet with Google Coral can be a great enhancement anyway.

```
audio:
  enabled: True
  max_not_heard: 30
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivityf
  min_volume: 200
  listen:
    - alarm
    - bark
    - breaking
    - fire_alarm
    - crack
    - drill
    - tools
    - footsteps

  filters:
    drill:
      threshold: 0.6
    breaking:
      threshold: 0.6
    alarm:
      threshold: 0.6
    crack:
      threshold: 0.5
    bark:
      threshold: 0.5

```
