### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by wouterverduin** [blakeblackshear/frigate#9217]
### Describe the problem you are having

Attempting to get audio detection working. I first attempted to only add it for the android camera (My S21 with the IP Webcam app). I get the error both when i add the settings for audio on camera basis or separate as done below.

What am i missing?  Also: i cant seem to find the audio configuration documentation? 

Thanks in advance!

### Version

0.13.0-49814B3

### Frigate config file

```yaml
mqtt:
  host: 1.1.1.1
  user: xxx
  password: xxx

database:
  path: /config/frigate.db

go2rtc:
  rtsp:
    username: "xxx"
    password: "xxx"
  streams:
    android:
      - rtsp://10.0.2.2:8387/h264_opus.sdp
    puppy:
      - rtsp://192.168.1.159:8554/unicast
  webrtc:
    candidates:
      - 192.168.1.50:8555
      - stun:8555

objects:
  track:
    - person
    - dog

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - crying
    - fire_alarm
    - scream
    - yell

motion:
  threshold: 25
  improve_contrast: false
  mqtt_off_delay: 30

record:
  enabled: True
  retain:
    days: 3
  events:
    pre_capture: 3
    post_capture: 20
    retain:
      default: 3
      mode: motion

cameras:
  puppycam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.159:8554/unicast
          roles:
            - detect
            - record
    audio:
      enabled: False
    detect:
      width: 800
      height: 600
  android:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.2.2:8387/h264_opus.sdp
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
2024-01-05 12:53:45.680647809  *************************************************************
2024-01-05 12:53:45.680650960  *************************************************************
2024-01-05 12:53:45.680654073  ***    Your config file is not valid!                     ***
2024-01-05 12:53:45.680655748  ***    Please check the docs at                           ***
2024-01-05 12:53:45.680656828  ***    https://docs.frigate.video/configuration/index     ***
2024-01-05 12:53:45.680667002  *************************************************************
2024-01-05 12:53:45.680668081  *************************************************************
2024-01-05 12:53:45.680669377  ***    Config Validation Errors                           ***
2024-01-05 12:53:45.680670431  *************************************************************
2024-01-05 12:53:45.680671412  Camera android has audio events enabled, but audio is not assigned to an input.
2024-01-05 12:53:45.681177852  Traceback (most recent call last):
2024-01-05 12:53:45.681180632    File "/opt/frigate/frigate/app.py", line 644, in start
2024-01-05 12:53:45.681182065      self.init_config()
2024-01-05 12:53:45.681183646    File "/opt/frigate/frigate/app.py", line 113, in init_config
2024-01-05 12:53:45.681185202      self.config = user_config.runtime_config(self.plus_api)
2024-01-05 12:53:45.681187871    File "/opt/frigate/frigate/config.py", line 1251, in runtime_config
2024-01-05 12:53:45.681189215      verify_config_roles(camera_config)
2024-01-05 12:53:45.681190660    File "/opt/frigate/frigate/config.py", line 959, in verify_config_roles
2024-01-05 12:53:45.681191856      raise ValueError(
2024-01-05 12:53:45.681193306  ValueError: Camera android has audio events enabled, but audio is not assigned to an input.
2024-01-05 12:53:45.681194339
2024-01-05 12:53:45.681195540  *************************************************************
2024-01-05 12:53:45.681196819  ***    End Config Validation Errors                       ***
2024-01-05 12:53:45.681198112  *************************************************************
```

### Frigate stats

```json
{"cameras":{"android":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":464,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":619,"pid":458,"process_fps":0.0,"skipped_fps":0.0},"puppycam":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":460,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":617,"pid":457,"process_fps":0.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"101":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"109":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"110":{"cmdline":"python3 -u -m frigate","cpu":"1.9","cpu_average":"1","mem":"0.7"},"122":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"152":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"170":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"191":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"232":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"258":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"439":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"441":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"0","mem":"0.3"},"450":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(45)","cpu":"0.0","cpu_average":"0","mem":"0.0"},"451":{"cmdline":"frigate.detector.cpu ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"453":{"cmdline":"frigate.output       ","cpu":"0.0","cpu_average":"0","mem":"0.4"},"457":{"cmdline":"frigate.process:puppycam","cpu":"0.0","cpu_average":"0","mem":"0.3"},"458":{"cmdline":"frigate.process:android","cpu":"0.0","cpu_average":"0","mem":"0.3"},"460":{"cmdline":"frigate.capture:puppycam","cpu":"0.0","cpu_average":"0","mem":"0.3"},"464":{"cmdline":"frigate.capture:android","cpu":"0.0","cpu_average":"0","mem":"0.3"},"471":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 800x600 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"473":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"474":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"600":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":451}},"processes":{"go2rtc":{"pid":101},"logger":{"pid":439},"recording":{"pid":441}},"service":{"last_updated":1704455791,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":63.2,"mount_type":"tmpfs","total":64.0,"used":0.8},"/media/frigate/clips":{"free":17384.1,"mount_type":"ext4","total":181112.2,"used":154496.1},"/media/frigate/recordings":{"free":17384.1,"mount_type":"ext4","total":181112.2,"used":154496.1},"/tmp/cache":{"free":953.7,"mount_type":"tmpfs","total":953.7,"used":0.0}},"temperatures":{},"uptime":118,"version":"0.13.0-49814b3"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by ufoczek** [comment]
```
cameras:
  puppycam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.159:8554/unicast
          roles:
            - detect
            - record
    audio:
      enabled: False
``` 

Try change it to enabled: True

**Comment by ufoczek** [comment]
Check documentation: https://deploy-preview-6262--frigate-docs.netlify.app/configuration/audio_detectors#enabling-audio-events

```
cameras:
  puppycam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.159:8554/unicast
          roles:
            - detect
            - record
    audio:
      enabled: False <<-- Why False? Set it to True
```
