### ISSUE TITLE
[Support]: View Only Camera

### ISSUE THREAD

**Issue by Aersaud** [blakeblackshear/frigate#9219]
### Describe the problem you are having

Hello, 

I am inquiring if it is possible to have some cameras that are "view only" in the bird's eye view but they do not actually detect or record anything. I have a few cameras that I am using for detecting and recording and those work fine, however I have about 4 more cameras that I would like to just view when I am watching the Bird's Eye view.

If this is possible please advise, or if you need any further info.

Thank you.

### Version

0.13.0-49814b3

### Frigate config file

```yaml
go2rtc:
  webrtc:
   candidates:
     - stun:8555
  streams:
    camera.bedroom:
      - rtsp://172.30.1.90:43483/ef62ea1d2446bf37
      - ffmpeg:camera.bedroom#video=copy#audio=opus
    camera.driveway:
      - rtsp://172.30.1.90:42881/5e2eb2a278b4ca90
      - ffmpeg:camera.driveway#video=copy#audio=opus
    camera.drivewaylow:
      - rtsp://172.30.1.90:42881/c1ea21e9f80ddd0e
      - ffmpeg:camera.driveway_low#video=copy
    camera.frontdoor:
      - rtsp://172.30.1.90:34143/b1807ce8d601fdcb#backchannel=0
      - ffmpeg:camera.frontdoor#video=copy#audio=opus
    camera.frontdoorlow:
      - rtsp://172.30.1.90:34143/b1807ce8d601fdcb#backchannel=0
      - ffmpeg:camera.frontdoor_low#video=copy
    camera.livingroom:
      - rtsp://172.30.1.90:34367/2e3055dffa5b5dbc
      - ffmpeg:camera.livingroom#video=copy#audio=opus
    camera.backporch:
      - rtsp://172.30.1.90:46029/e14b4a7d7cdca675
      - ffmpeg:camera.backporch#video=copy#audio=opus
    camera.backporchlow:
      - rtsp://172.30.1.90:46029/beee909f0cdbac22
      - ffmpeg:camera.backporch#video=copy
    camera.upstairs:
      - rtsp://172.30.1.90:38867/68af65e28857caee
      - ffmpeg:camera.upstairs#video=copy#audio=opus
    camera.azrael:
      - rtsp://172.30.1.90:35397/91623fcbffdcc7de
      - ffmpeg:camera.azrael#video=copy#audio=opus
  ffmpeg:
    bin: ffmpeg
mqtt:
  host: 172.30.1.90
  user: admin
  password: [REDACTED]
detectors:
  coral:
    type: edgetpu
    device: usb
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
rtmp:
  enabled: false
record:
  enabled: true
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 7
      mode: active_objects
detect:
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
ffmpeg:
  hwaccel_args: preset-vaapi
cameras:
  frontdoor:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/camera.frontdoor
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/camera.frontdoorlow
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 720
      height: 576
      fps: 5
    motion:
      mask:
      - 720,0,720,29,444,27,450,0
    objects:
      track:
      - person
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          #min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
          #mask: 0,0,1000,0,1000,200,0,200
    live:
      stream_name: camera.frontdoor
  driveway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/camera.driveway
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/camera.drivewaylow
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
      - 616,21,619,46,403,42,404,21
    objects:
      track:
      - person
      - car
      - motorcycle
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          #min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
          #mask: 0,0,1000,0,1000,200,0,200
        car:
          mask:
          - 617,0,414,184,256,192,255,124,424,107
          - 273,336,277,374,280,480,0,480,0,311,0,166,0,0,135,0,259,0
    live:
      stream_name: camera.driveway
  backporch:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/camera.backporch
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/camera.backporchlow
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
      - person
      - car
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          #min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.76
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
          #mask: 0,0,1000,0,1000,200,0,200
        car:
          mask:
          - 0,1080,333,1080,367,976,336,904,297,818,261,726,224,630,187,507,166,371,149,243,138,116,128,0,0,0
          - 1440,331,1527,331,1541,167,1437,153
    motion:
      mask:
      - 393,0,388,43,0,39,0,0
    live:
      stream_name: camera.backporch
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/frigate.db

birdseye:
  enabled: true
  mode: continuous
  quality: 1
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream.
  # Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed
  # to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize
  # less CPU resources.
  quality: 1
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
you can disable object detection and recording for the cameras specifically

**Comment by Aersaud** [comment]
> you can disable object detection and recording for the cameras specifically

Thanks for the response. Could you provide the config for that? Or a link to the documentation where it shows an example?
For example if I have:

```
cameras:
  livingroom:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/camera.livingroom
        input_args: preset-rtsp-restream
        roles:
```

What would I set the role to for just viewing only?

**Comment by NickM-27** [comment]
roles do not disable functionality, only assigns functionality streams

```
cameras:
  livingroom:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://127.0.0.1:8554/camera.livingroom
        input_args: preset-rtsp-restream
   detect:
    enabled: false
   record:
    enabled: false
```
