### ISSUE TITLE
What is the proper syntax for ffmpeg entries to transcode h265 input to h264 rtmp  and clips output?

### ISSUE THREAD

**Issue by deepcoder** [blakeblackshear/frigate#922]
What is the proper syntax for ffmpeg entries to transcode h265 input to h264 rtmp  and clips output?

I have a Reolink RLC810 camera that only supports h265 for it's high resolution stream. I would like to use the hi res stream for rtmp and clips.

I am trying the following with Frigate : 0.8.4-5043040  and receiving errors shown below. Thx!

```
  rlc810-01:
    ffmpeg:
      inputs:
        - path: rtsp://x:y@192.168.1.100:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://x:y@192.168.1.100:554/h265Preview_01_main
          roles:
            - rtmp
            # - clips
            # - record
      output_args:
        rtmp: -c:a copy -c:v libx264
    width: 640
    height: 360
    fps: 5

```

```
ffmpeg.rlc810-01.rtmp          ERROR   : [NULL @ 0x555c85f0c280] Unable to find a suitable output format for 'rtmp://127.0.0.1/live/rlc810-01'
ffmpeg.rlc810-01.rtmp          ERROR   : rtmp://127.0.0.1/live/rlc810-01: Invalid argument
watchdog.rlc810-01             INFO    : Terminating the existing ffmpeg process...

**Comment by erikarenhill** [comment]
I have the same issue with both Reolink 810 and 820. Have tried different both rtmp and rtsp url's and ffmpeg parameters

**Comment by blakeblackshear** [comment]
When you specify output args, you replace the default args. You are missing the format parameter. Try this:
```yaml
  rlc810-01:
    ffmpeg:
      inputs:
        - path: rtsp://x:y@192.168.1.100:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://x:y@192.168.1.100:554/h265Preview_01_main
          roles:
            - rtmp
            # - clips
            # - record
      output_args:
        rtmp: -c:a copy -c:v libx264 -f flv
    width: 640
    height: 360
    fps: 5
```
