### ISSUE TITLE
 No PTZ controls with DAHUA camera

### ISSUE THREAD

**Issue by Bsimon1986** [blakeblackshear/frigate#9222]
### Describe the problem you are having

i have Dahua SD2A500-GN-AW-PV camera, that is fully ONVIF compatible. i have checked it with ONVIF device manager, and when i connect to camera all th PTZ controls are there.
if i add the camera to frigate i have only option for presets and zoom which this camera does not support.
![PTZ1](https://github.com/blakeblackshear/frigate/assets/155776682/8b792179-9254-4cbb-97b7-02a44bae3c98)

data from ONVIF device manager

![PTZ2](https://github.com/blakeblackshear/frigate/assets/155776682/1e5a7d3f-56c2-4155-8ce8-a536b50f4823)

camera Vhod keeps disconnecting so this is why there is so much errors

what am i missing

### Version

Frigate 0.13 rc1

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 11
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 11

birdseye:
  enabled: true
  mode: continuous

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    Dvorisce:
    - rtsp://admin:BHS317dv@192.168.1.53:554/cam/realmonitor?channel=1&subtype=0
    Vhod:
    - rtsp://admin:BHS317dv@192.168.1.50:554/Streaming/Channels/101/
    Delavnica:
    - rtsp://admin:BHS317dv@192.168.1.51:554/cam/realmonitor?channel=1&subtype=0
    Garaza:
    - rtsp://admin:L2D50D26@192.168.1.54:554/cam/realmonitor?channel=1&subtype=0
    glavna_kamera:
    - rtsp://admin:BHS317dv.@192.168.1.47:554/cam/realmonitor?channel=1&subtype=0
objects:
  track:
  - person
  - car
  - cat
  - dog
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      #min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.72

cameras:
  Vhod:
    enabled: true
    ffmpeg:
     # hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://admin:BHS317dv@192.168.1.50:554/Streaming/Channels/102/# <-----
          The stream you want to use for detection
        roles:
        - detect
      - path: rtsp://admin:BHS317dv@192.168.1.50:554/Streaming/Channels/101/# <-----
          The stream you want to use for detection
        roles:
        - record
    motion:
      mask:
      - 440,0,450,52,704,53,704,0
      - 216,305,294,0,0,0,0,576,210,576,138,529,160,348
    zones:
      Vhodna_vrata:
        coordinates: 491,576,352,576,356,412,297,400,330,249,375,252,381,101,704,68
      Postar:
        coordinates: 256,444,273,329,192,329,180,576,294,576

    detect:
      stationary:
        interval: 10
        threshold: 50
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5

  Dvorisce:
    enabled: true
    ffmpeg:
     # hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://admin:BHS317dv@192.168.1.53:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: rtsp://admin:BHS317dv@192.168.1.53:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect

    motion:
      mask:
      - 704,0,570,0,568,126,565,174,492,184,518,188,516,317,704,291
      - 498,172,324,158,331,243,493,243
    zones:
      Dovoz_dvorisce:
        coordinates: 388,576,704,576,704,437,664,442,563,370,316,420
        objects:
        - car
        - person
      Dvorisce_trikotnik:
        coordinates: 704,257,506,308,556,362,589,394,639,419,704,426
        objects:
        - person
        - cat
        - dog

    detect:
      stationary:
        interval: 10
        threshold: 50
      enabled: true
      width: 704
      height: 576
      fps: 5

  glavna_kamera:
    enabled: true
    ffmpeg:
      #hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://admin:BHS317dv.@192.168.1.47:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record

      - path: rtsp://admin:BHS317dv.@192.168.1.47:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - detect
    onvif:
      host: 192.168.1.47
      port: 80
      user: admin
      password: BHS317dv.
      autotracking:
        enabled: false
        calibrate_on_startup: true
        zooming: disabled
        
    detect:
      stationary:
        interval: 10
        threshold: 50
      enabled: true
      width: 704
      height: 576
      fps: 5



  Delavnica:
    enabled: true
    ffmpeg:
    #  hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://admin:BHS317dv@192.168.1.51:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record

      - path: rtsp://admin:BHS317dv@192.168.1.51:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect

    motion:
      mask:
      - 302,116,307,158,472,165,475,118,509,72,508,0,305,0,0,21,21,169
      - 158,576,704,576,704,153,474,113,482,199,453,260,362,320,104,470
      - 471,52,471,0,704,0,704,62

    detect:
      stationary:
        interval: 10
        threshold: 30
      enabled: true
      width: 704
      height: 576
      fps: 5

  Garaza:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-vaapi
      #hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://admin:L2D50D26@192.168.1.54:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: rtsp://admin:L2D50D26@192.168.1.54:554/cam/realmonitor?channel=1&subtype=1
        roles:
        - detect
    motion:
      mask:
      - 0,0,194,0,203,136,124,178,0,247
      - 677,30,675,69,598,60,594,26
    detect:
      stationary:
        interval: 10
        threshold: 50
      enabled: true
      width: 704
      height: 576
      fps: 5


    zones:
      Dovoz:
        coordinates: 227,191,178,222,87,271,0,341,0,576,164,576,536,576,560,457
      Stopnišče:
        coordinates: 567,452,596,105,550,105,478,425
      vrt:
        coordinates: 540,98,426,106,289,137,254,195,482,246
      zone_0:
        coordinates: 258,285,228,185,130,239,0,340,0,576,537,576,562,465
      Kašča:
        coordinates: 298,0,194,0,201,101,298,85




snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
 # height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
 # required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```

### Relevant log output

```shell
2024-01-05 19:47:09.458314752  [INFO] Preparing Frigate...
2024-01-05 19:47:09.472329184  [INFO] Starting Frigate...
2024-01-05 19:47:11.234351724  [2024-01-05 20:47:11] frigate.app                    INFO    : Starting Frigate (0.13.0-49814b3)
2024-01-05 19:47:11.234467827  [2024-01-05 20:47:11] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-01-05 19:47:11.294245304  [2024-01-05 20:47:11] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2024-01-05 19:47:11.316245298  [2024-01-05 20:47:11] peewee_migrate.logs            INFO    : Starting migrations
2024-01-05 19:47:11.321228755  [2024-01-05 20:47:11] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-01-05 19:47:11.774840972  [2024-01-05 20:47:11] frigate.app                    INFO    : Recording process started: 302
2024-01-05 19:47:11.778009241  [2024-01-05 20:47:11] frigate.app                    INFO    : go2rtc process pid: 89
2024-01-05 19:47:11.811269988  [2024-01-05 20:47:11] frigate.app                    INFO    : Output process started: 313
2024-01-05 19:47:11.826043356  [2024-01-05 20:47:11] detector.ov                    INFO    : Starting detection process: 312
2024-01-05 19:47:11.914744558  [2024-01-05 20:47:11] frigate.app                    INFO    : Camera processor started for Vhod: 323
2024-01-05 19:47:11.922914191  [2024-01-05 20:47:11] frigate.app                    INFO    : Camera processor started for Dvorisce: 325
2024-01-05 19:47:11.930957969  [2024-01-05 20:47:11] frigate.app                    INFO    : Camera processor started for glavna_kamera: 326
2024-01-05 19:47:11.938093643  [2024-01-05 20:47:11] frigate.app                    INFO    : Camera processor started for Delavnica: 328
2024-01-05 19:47:11.954030193  [2024-01-05 20:47:11] frigate.app                    INFO    : Camera processor started for Garaza: 330
2024-01-05 19:47:11.968862234  [2024-01-05 20:47:11] frigate.app                    INFO    : Capture process started for Vhod: 331
2024-01-05 19:47:11.975422990  [2024-01-05 20:47:11] frigate.app                    INFO    : Capture process started for Dvorisce: 340
2024-01-05 19:47:11.982232780  [2024-01-05 20:47:11] frigate.app                    INFO    : Capture process started for glavna_kamera: 344
2024-01-05 19:47:11.995419228  [2024-01-05 20:47:11] frigate.app                    INFO    : Capture process started for Delavnica: 351
2024-01-05 19:47:12.005837443  [2024-01-05 20:47:12] frigate.app                    INFO    : Capture process started for Garaza: 358
2024-01-05 19:47:21.808570039  [2024-01-05 20:47:21] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,300,300,3]
2024-01-05 19:47:21.808871044  [2024-01-05 20:47:21] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,1,100,7]
2024-01-05 19:47:21.808874517  [2024-01-05 20:47:21] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2024-01-05 19:47:30.740806661  [2024-01-05 20:47:30] frigate.comms.dispatcher       INFO    : Setting ptz command to preset for glavna_kamera
2024-01-05 19:47:32.045766698  [2024-01-05 20:47:32] watchdog.Vhod                  INFO    : Vhod exceeded fps limit. Exiting ffmpeg...
2024-01-05 19:47:32.046080792  [2024-01-05 20:47:32] watchdog.Vhod                  INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-05 19:47:32.124188980  [2024-01-05 20:47:32] frigate.video                  ERROR   : Vhod: Unable to read frames from ffmpeg process.
2024-01-05 19:47:32.126649868  [2024-01-05 20:47:32] frigate.video                  ERROR   : Vhod: Unable to read frames from ffmpeg process.
2024-01-05 19:47:32.126835521  [2024-01-05 20:47:32] frigate.video                  ERROR   : Vhod: Unable to read frames from ffmpeg process.
2024-01-05 19:47:32.126892023  [2024-01-05 20:47:32] frigate.video                  ERROR   : Vhod: Unable to read frames from ffmpeg process.
2024-01-05 19:47:32.126980513  [2024-01-05 20:47:32] frigate.video                  ERROR   : Vhod:
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"13/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"13/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua SD2A500-GN-AW-PV

**Comment by NickM-27** [comment]
you can try enabling debug logs for `frigate.ptz.onvif` and paste them here, but we can only go off of what the camera claims to support and it seems in this case it does not claim to support continuous move

**Comment by Bsimon1986** [comment]
It supports continuous and absolute movement but no relative. What is nedded for autotrack?

**Comment by NickM-27** [comment]
Relative is needed for auto tracking but that won't affect the buttons

**Comment by Bsimon1986** [comment]
i tested a little bit and when i have ONVIF turned on frigate crashes and does not restart until i manually start it. if i am correct. for ptz buttons to be enabled, camera has to have continuous movements possible? i can pan and tilt my camera only with continuous movements.

**Comment by NickM-27** [comment]
It would be best to see the debug output. @hawkeye217 let me know if I am missing something

**Comment by FranciscoBalles** [comment]
Hi everyone, I have the same issue with a DH-SD2A200HB-GN-A-PV-S2 in the frigate UI. I think part of the problem is these cameras are PT, not PTZ.
 I am using [Frigate v0.13.0-rc1](https://github.com/blakeblackshear/frigate/releases/tag/v0.13.0-rc1).
Using the the Frigate NVR Custom Component for Home Assistant [v5.0.0-rc1](https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-rc1) and Frigate Lovelace Card [v5.2.0](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v5.2.0) the PT and preset functions worked great with the [custom:frigate-card-ptz](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#customfrigate-card-ptz) in Home Assitant.
I also have an older Dahua PTZ,  DH-SD22204UEN-GN. This one works great in both Frigate UI and with the [custom:frigate-card-ptz](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#customfrigate-card-ptz) in Home Assitant.
My code for the frigate card:
```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.porton
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
elements:
  - type: custom:frigate-card-conditional
    conditions:
      media_loaded: true
      view:
        - live
        - image
    elements:
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          transform: scale(1.5, 1.5)
          right: 50%
          top: 50%
        actions_left:
          start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: move
              argument: left
          end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: stop
        actions_right:
          start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: move
              argument: right
          end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: stop
        actions_up:
          start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: move
              argument: up
          end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: stop
        actions_down:
          start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: move
              argument: down
          end_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: stop
        actions_home:
          start_tap_action:
            action: call-service
            service: frigate.ptz
            service_data:
              entity_id: camera.porton
              action: preset
              argument: Preset1
menu:
  buttons:
    cameras:
      enabled: false
    microphone:
      enabled: true
``` 

My Frigate Config:
```yaml
mqtt:
  enabled: True
  host: 192.168.12.30
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: MyUser
  password: MyPasword

detectors:
  coral1:
    type: edgetpu
    device: pci:0

birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  quality: 1
  mode: objects

ffmpeg:
  hwaccel_args: preset-vaapi

rtmp:
  enabled: false

go2rtc:
  streams:
    porton:
    - rtsp://admin:pass@192.168.12.14:554/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:rtsp://admin:pass@192.168.12.14:554/cam/realmonitor?channel=1&subtype=0#audio=opus
    porton_sub:
    - rtsp://admin:pass@192.168.12.14:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    puerta:
    - rtsp://admin:passa@192.168.12.12:554/cam/realmonitor?channel=1&subtype=0
    puerta_sub:
    - rtsp://admin:pass@192.168.12.12:554/cam/realmonitor?channel=1&subtype=1

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:
  porton:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/porton_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/porton?video&audio
        input_args: preset-rtsp-restream
        roles:
        - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    objects:
      track:
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 7
    motion:
        mask:
          - 686,14,686,40,470,40,470,14
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 3
        post_capture: 10
    onvif:
      host: 192.168.12.14
      port: 80
      user: OnvifUser
      password: pass
      autotracking:
        enabled: false
    zones:
      area_banqueta:
        coordinates: 437,480,281,191,173,202,205,480
        objects:
          - person
      area_patio:
        coordinates: 104,480,0,480,1,245,107,228
        objects:
          - person

  puerta:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/puerta_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/puerta
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    objects:
      track:
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - dog
      - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      retain:
        default: 7
    motion:
        mask:
          - 680,21,680,47,459,47,459,21
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 3
        post_capture: 10
    onvif:
      host: 192.168.12.12
      port: 80
      user: OnvifUser
      password: pass
      autotracking:
        enabled: false
    zones:
      area_banqueta:
        coordinates: 375,480,704,480,704,102,670,53,629,239,551,199,453,352
        objects:
          - person
``` 
The Dahua DH-SD22204UEN-GN PTZ in Frigate UI
![Frigate PTZ UI](https://github.com/blakeblackshear/frigate/assets/106566453/e522f4d4-054b-407c-b802-075f926b8260)

The Dahua DH-SD2A200HB-GN-A-PV-S2 PT in Frigate UI
![Frigate PT UI](https://github.com/blakeblackshear/frigate/assets/106566453/504eae52-d970-40fb-bb2d-47d2d9d7271a)

The Dahua DH-SD2A200HB-GN-A-PV-S2 PT in HA with the [custom:frigate-card-ptz](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#customfrigate-card-ptz)
![HA PT UI](https://github.com/blakeblackshear/frigate/assets/106566453/1e311bb5-ea2c-49b6-ba08-3e913ec8b367)

Frigate logs after moving the camera in HA
```
2024-01-29 17:59:47.427939568  [2024-01-29 17:59:47] frigate.comms.dispatcher       INFO    : Setting ptz command to move_left for porton
2024-01-29 17:59:48.025643829  [2024-01-29 17:59:48] frigate.comms.dispatcher       INFO    : Setting ptz command to stop for porton
2024-01-29 17:59:48.668124876  [2024-01-29 17:59:48] frigate.comms.dispatcher       INFO    : Setting ptz command to move_up for porton
2024-01-29 17:59:49.191947990  [2024-01-29 17:59:49] frigate.comms.dispatcher       INFO    : Setting ptz command to stop for porton
2024-01-29 17:59:49.890426861  [2024-01-29 17:59:49] frigate.comms.dispatcher       INFO    : Setting ptz command to move_right for porton
2024-01-29 17:59:50.532149886  [2024-01-29 17:59:50] frigate.comms.dispatcher       INFO    : Setting ptz command to stop for porton
2024-01-29 17:59:51.314486112  [2024-01-29 17:59:51] frigate.comms.dispatcher       INFO    : Setting ptz command to move_down for porton
2024-01-29 17:59:51.757973478  [2024-01-29 17:59:51] frigate.comms.dispatcher       INFO    : Setting ptz command to stop for porton
2024-01-29 17:59:52.850617881  [2024-01-29 17:59:52] frigate.comms.dispatcher       INFO    : Setting ptz command to preset for porton
```

**Comment by NickM-27** [comment]
I have an amcrest camera that is PT and it works without issues

**Comment by FranciscoBalles** [comment]
Thank you @NickM-27, other thing in common with the camera of  @Bsimon1986 and mine (besides being Dahua) is the use of [ONVIF Profile T](https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf). I am not an expert at all,  I discovered that when I also enabled the two way talk of the camera. It could also be an implementation error from Dahua. I personally don't mind since I use my cameras from HA, but thank you for you time!

**Comment by hawkeye217** [comment]
As @NickM-27 said to the OP, it would be helpful to see debug output from Frigate on startup.

Add this to your frigate config file, restart, and paste the initial log output here:

```
logger:
  default: info
  logs:
    frigate.ptz.onvif: debug
```
