### ISSUE TITLE
Is there a way to join/concatenate all the event recordings of a day into one file in Frigate 12?

### ISSUE THREAD

**Issue by tboonstl** [blakeblackshear/frigate#9246]
### Describe the problem you are having

It is my understanding that the beta Frigate 13 can join/concatenate event recordings into one file.  Is that right?

Is there a way - via a preset or a command - to do that in version 12?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral1:
    type: edgetpu
    device: usb

cameras:
  Camera1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://fred:Ticket4you@192.168.0.153:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://fred:Ticket4you@192.168.0.153:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480

objects:
  filters: 
    sports ball:
     min_score: 0.1
     threshold: 0.1
  track:
    - person 
    - sports ball

record:
  enabled: True
  retain: 
    mode: all      
    days: 0
  events:
    retain:
      default: 10
    pre_capture: 2
    post_capture: 6
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
