### ISSUE TITLE
[Support]: Download recording directly from remote computer to local one via web-ui

### ISSUE THREAD

**Issue by tliaresq** [blakeblackshear/frigate#9253]
### Describe the problem you are having

Hi, I am really impressed with Frigate so far and have had an easy time setting everything up. I just had a question on functionality that I am hoping someone could help me with.

I am looking to have this run on a remote computer that will just save the last day of video from an RTSP camera (I do not really care about object detection right now). A functionality I am looking for is to download certain clips from the web-ui, to my local computer when accessing the remote computer (running Frigate) via the web-ui. These would both be on the same network but it would be nice to download directly from the web-ui instead of using a seperate script which copies the file that is saved on the computer running Frigate when using the Export button. 

### Version

0.13.0 Beta 7

### Frigate config file

```yaml
mqtt:
  enabled: False

record:
  enabled: True
  retain:
    days: 1

cameras:
  cab_camera:
    ffmpeg:
      inputs:
        - path: rtsp://***
          roles:
            - record
    detect:
      enabled: False
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a
