### ISSUE TITLE
[Camera Support]: ONVIF config vars not working.

### ISSUE THREAD

**Issue by booyaamps** [blakeblackshear/frigate#9262]
### Describe the problem you are having

Hi!
I'm trying to add autotracking to two of my cameras. I know both cameras are ONVIF compatible and the python script confirmed that.
Per the config file reference, i'm trying to add the ONVIF info for each camera and i'm receiving this error:
Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 761, in config_save
    new_yaml = FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1083, in parse_raw
    return cls.parse_obj(config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> FrontSide -> onvif
  extra fields not permitted (type=value_error.extra)

In the most recent docs, i no longer see autotracking like i do here: https://deploy-preview-6262--frigate-docs.netlify.app/configuration/autotracking/

Did i stumble upon an old feature that no longer exists, or am i missing something?

Here's the config for that camera (everything works fine when commenting out the onvif section):

#-------------------West side of house-------------------#
  FrontSide:
    zones:
      zone_0:
        coordinates: 0,1080,1920,1080,1920,252,1816,132,1616,103,1493,63,1380,68,1262,94,1030,103,544,200,0,339
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/FrontSide
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
    onvif:
      host: 10.0.0.53
      port: 8080
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"
      autotracking:
        enabled: True
        zooming: enabled
        required_zones:
          - zone_0
        track:
          - person
          - dog
          - cat
        return_preset: home
        timeout: 15        
    ui:
      order: 3        
    birdseye:
      order: 3

### Version

Latest from docker

### Frigate config file

```yaml
---
ui:
  use_experimental: True
  live_mode: mse

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  restream: True
  mode: continuous
  quality: 1
  width: 1920
  height: 1080

database:
  path: /config/frigate.db

mqtt:
  enabled: false

record:
  enabled: True
  retain:
    days: 4
    mode: motion
  events:
    pre_capture: 2
    retain:
      default: 4
      mode: motion

timestamp_style:
  position: "tr"
  effect: solid

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  crop: True
  retain:
    default: 4
    objects:
      person: 4

detect:
  fps: 5
  width: 1920
  height: 1080
  stationary:
    interval: 10
    threshold: 150

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_score: 0.6

go2rtc:
  streams:
    Deck:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.50:554/live
      - "ffmpeg:Deck#audio=aac"
    Driveway:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.51:554/live
      - "ffmpeg:Driveway#audio=aac"
    Front:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.52:554/live
      - "ffmpeg:Front#audio=aac"
    FrontSide:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.53:554/1
      - "ffmpeg:FrontSide#audio=aac"
    BirdFeeder:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.54:554/1
      - "ffmpeg:BirdFeeder#audio=aac"
  rtsp:
    username: "{FRIGATE_RTSP_USER}"
    password: "{FRIGATE_RTSP_PASSWORD}"
  webrtc:
    candidates:
      - 0.0.0.0:8555
  #     stun:8555

ffmpeg:
  hwaccel_args: preset-vaapi
  global_args: -hide_banner -loglevel warning -threads 2
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo
    record: preset-record-generic
    rtmp: preset-rtmp-generic
#-------------------CAMERAS-------------------#
cameras:
#-------------------Deck-------------------#  
  Deck:
    motion:
      mask:
        - 553,1080,0,1080,0,625
    zones:
      deck_far:
        coordinates: 668,228,0,456,0,0,508,0,1920,0,1920,480,1293,112
      deck_near:
        coordinates: 0,1080,0,479,67,398,827,145,1718,341,1613,1080
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/Deck
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
    ui:
      order: 0        
    birdseye:
      order: 0
#-------------------Driveway-------------------#
  Driveway:
    zones:
      driveway_far:
        coordinates: 1920,0,0,0,0,406,546,67,926,159,1677,256,1920,487
      zone_0:
        coordinates: 1898,423,1148,110,613,41,391,104,0,300,0,1080,1920,1080
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/Driveway
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
    ui:
      order: 1        
    birdseye:
      order: 1
#-------------------Front entrance-------------------#
  Front:
    motion:
      mask:
        - 1552,0,1920,0,1920,97,1641,54,1604,91,1378,88,588,249,0,472,0,0
    zones:
      zone_0:
        coordinates: 0,1080,1920,1080,1920,252,1580,168,0,653
      zone_1:
        coordinates: 388,328,774,201,1512,81,1641,54,1632,88,1658,54,1823,74,1920,200,490,637,291,693,0,700,0,486
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/Front
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - cat
        - dog
         - car
         - motorcycle
         - bicycle
    ui:
      order: 2         
    birdseye:
      order: 2
#-------------------West side of house-------------------#
  FrontSide:
    zones:
      zone_0:
        coordinates: 0,1080,1920,1080,1920,252,1816,132,1616,103,1493,63,1380,68,1262,94,1030,103,544,200,0,339
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/FrontSide
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
    onvif:
      host: 10.0.0.53
      port: 8080
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"
      autotracking:
        enabled: True
        zooming: enabled
        required_zones:
          - zone_0
        track:
          - person
          - dog
          - cat
        return_preset: home
        timeout: 15        
    ui:
      order: 3        
    birdseye:
      order: 3
#-------------------Birds-------------------#
  BirdFeeder:
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@127.0.0.1:8554/BirdFeeder
          roles:
            - record
            - detect
    objects:
      track:
        - bird
    ui:
      order: 4        
    birdseye:
      order: 4
```

### Relevant log output

```shell
Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 761, in config_save
    new_yaml = FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1083, in parse_raw
    return cls.parse_obj(config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> FrontSide -> onvif
  extra fields not permitted (type=value_error.extra)
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x556a4d611ec0] max delay reached. need to consume packet
[rtsp @ 0x556a4d611ec0] RTP: missed 16 packets
[h264 @ 0x556a4d617340] concealing 2872 DC, 2872 AC, 2872 MV errors in I frame
Input #0, rtsp, from 'rtsp://10.0.0.53/1':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn, 40 tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{"BirdFeeder":{"camera_fps":4.4,"capture_pid":314,"detection_enabled":1,"detection_fps":15.2,"ffmpeg_pid":331,"pid":297,"process_fps":4.4,"skipped_fps":0.0},"Deck":{"camera_fps":5.0,"capture_pid":298,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":305,"pid":293,"process_fps":5.1,"skipped_fps":0.0},"Driveway":{"camera_fps":5.0,"capture_pid":301,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":318,"pid":294,"process_fps":5.0,"skipped_fps":0.0},"Front":{"camera_fps":5.0,"capture_pid":307,"detection_enabled":1,"detection_fps":1.3,"ffmpeg_pid":321,"pid":295,"process_fps":5.1,"skipped_fps":0.0},"FrontSide":{"camera_fps":5.0,"capture_pid":310,"detection_enabled":1,"detection_fps":9.6,"ffmpeg_pid":323,"pid":296,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.5"},"1":{"cpu":"0.0","mem":"0.0"},"116":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.3","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"2024":{"cpu":"0.0","mem":"0.0"},"2035":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"0.5"},"286":{"cpu":"0.3","mem":"0.1"},"287":{"cpu":"14.0","mem":"0.7"},"288":{"cpu":"23.7","mem":"0.8"},"29":{"cpu":"0.0","mem":"0.0"},"293":{"cpu":"1.0","mem":"0.9"},"294":{"cpu":"1.7","mem":"0.7"},"295":{"cpu":"2.3","mem":"0.6"},"296":{"cpu":"9.7","mem":"0.7"},"297":{"cpu":"20.7","mem":"0.8"},"298":{"cpu":"4.3","mem":"0.6"},"299":{"cpu":"0.0","mem":"0.3"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"4.0","mem":"0.6"},"305":{"cpu":"5.3","mem":"0.4"},"306":{"cpu":"0.0","mem":"0.1"},"307":{"cpu":"4.3","mem":"0.6"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"5.0","mem":"0.6"},"312":{"cpu":"0.0","mem":"0.1"},"314":{"cpu":"2.7","mem":"0.6"},"318":{"cpu":"5.0","mem":"0.4"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"0.0","mem":"0.1"},"321":{"cpu":"5.3","mem":"0.5"},"323":{"cpu":"4.7","mem":"0.5"},"326":{"cpu":"0.0","mem":"0.1"},"327":{"cpu":"0.7","mem":"0.1"},"330":{"cpu":"13.3","mem":"0.5"},"331":{"cpu":"3.0","mem":"0.4"},"340":{"cpu":"0.7","mem":"0.1"},"352":{"cpu":"7.0","mem":"0.4"},"385":{"cpu":"1.7","mem":"0.1"},"386":{"cpu":"3.3","mem":"0.1"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"8.7","mem":"0.1"},"96":{"cpu":"2.0","mem":"1.7"},"99":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"13909.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":26.6,"detectors":{"coral":{"detection_start":1704742254.903433,"inference_speed":11.81,"pid":287}},"gpu_usages":{"intel-vaapi":{"gpu":"15.14 %","mem":"- %"}},"service":{"last_updated":1704742258,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":1052.6,"mount_type":"tmpfs","total":1073.7,"used":21.1},"/media/frigate/clips":{"free":203022.2,"mount_type":"ext4","total":502919.0,"used":274274.6},"/media/frigate/recordings":{"free":203022.2,"mount_type":"ext4","total":502919.0,"used":274274.6},"/tmp/cache":{"free":203022.2,"mount_type":"overlay","total":502919.0,"used":274274.6}},"temperatures":{},"uptime":1545,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

SV3C
