### ISSUE TITLE
[Support]: Frigate won't load with Frigate+ models

### ISSUE THREAD

**Issue by mattgio22** [blakeblackshear/frigate#9263]
### Describe the problem you are having

I added Frigate+ models to 0.13.0-rc1 (as well as 0.13-beta7), and in both cases, the Frigate GUI won't open in my browser with the model in the config. I tried this with both the CPU and TPU versions (one at a time) - neither work. When I hash (#) these lines out, frigate works as expected.

I added these lines to the very top of my config: 
model:
  path: plus://[model]

I'm using docker compose on Ubuntu Server 20.04 - everything is up to date. I checked the Frigate logs, but unfortunately I can only see the logs for the current boot - I'm not sure how to check the logs for failed boots.

I'm happy to provide any other info or even a video to show the issue. Many thanks in advance for the help.

### Version

0.13.0-49814B3

### Frigate config file

```yaml
#model:
#CPU
#  path: plus://[redacted]
#TPU
#  path: plus://[redacted]

mqtt:
  host: [redacted]
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: [redacted]
  password: [redacted]
  stats_interval: 60
  enabled: True

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car

record:
  enabled: True
  events: 
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    retain:
      default: 2
      mode: active_objects

birdseye:
  enabled: True
  mode: continuous

cameras:
  indoor1zoom:
    ffmpeg:
      inputs:
        - path: [redacted] # <----- The stream you want to use for detection
          #input_args: preset-http-reolink
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
  
  indoor2:
    ffmpeg:
      inputs:
        - path: [redacted] # <----- The stream you want to use for detection
          #input_args: preset-http-reolink
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
  
  indoor3:
    ffmpeg:
      inputs:
        - path: [redacted] # <----- The stream you want to use for detection
          #input_args: preset-http-reolink
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    objects:
      filters:
        car:
          mask:
            - 0,360,640,360,640,0,0,0


  outdoor1:
    ffmpeg:
      inputs:
        - path: [redacted] # <----- The stream you want to use for detection
          #input_args: preset-http-reolink
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
  
  outdoor2:
    ffmpeg:
      inputs:
        - path: [redacted] # <----- The stream you want to use for detection
          #input_args: preset-http-reolink
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      filters:
        car:
          mask:
            - 310,206,367,192,419,177,417,137,207,0,110,0,96,70,136,288,251,282,291,252,243,213

  outdoor3duo:
    ffmpeg:
      inputs:
        - path: [redacted] # <----- The stream you want to use for detection
          #input_args: preset-http-reolink
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
  
  outdoor4front:
    ffmpeg:
      inputs:
        - path: [redacted] # <----- The stream you want to use for detection
          #input_args: preset-http-reolink
          roles:
            - detect
            - record
    detect:
      enabled: true  # <---- disable detection until you have a working camera feed
      width: 896 # <---- update for your camera's resolution
      height: 512 # <---- update for your camera's resolution
```

### Relevant log output

```shell
No relevant log output - don't know how to access logs from failed boots.
```

### FFprobe output from your camera

```shell
Cameras are OK
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink - various

### Any other information that may be helpful

I checked the folder where the frigate+ models are supposed to be downloaded and nothing was in there. I wonder if there's an issue with how Frigate is fetching the model?
