### ISSUE TITLE
[Config Support]: Error parsing when starting container

### ISSUE THREAD

**Issue by Kfrard** [blakeblackshear/frigate#9278]
### Describe the problem you are having

The container does not start and the logs show the following.

### Version

not applicable

### Frigate config file

```yaml
mqtt:
  enabled: false
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-vaapi
cameras:
  Obrotowa:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.1.1:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
Error parsing config: extra keys not allowed @ data['cameras']['back']['detect']['width']
```

### Operating system

Debian

### Install method

Portainer

### Coral version

USB

### Any other information that may be helpful

Docker version 24.0.7, build afdd53b
