### ISSUE TITLE
[Support]: Clips playback video, but repeat the video within a clip

### ISSUE THREAD

**Issue by psilantropy** [blakeblackshear/frigate#9282]
### Describe the problem you are having

I've noticed this issue across multiple versions and different deployments, but finally decided to ask about it.

If I look at events, and see a person event;
![image](https://github.com/blakeblackshear/frigate/assets/79955883/e9a2c871-6855-4dd0-b556-367f7f914940)

Play the clip, starts at 16:44 (follow the timestamp)
![image](https://github.com/blakeblackshear/frigate/assets/79955883/0be70d77-18ad-4f72-a76a-b9f02be68904)

After a few seconds of playback up to this point...
![image](https://github.com/blakeblackshear/frigate/assets/79955883/6dceecd2-a711-480e-9172-04fd7a98afff)

...the video suddenly starts again, but the clip progress bar is continuing as normal
![image](https://github.com/blakeblackshear/frigate/assets/79955883/b76e52e4-7461-44c9-9f2a-d0ace005a9ad)

This happens just the one time, and the clip continues to the end
![image](https://github.com/blakeblackshear/frigate/assets/79955883/325d3e50-c471-4bc4-b453-b2100094ec0f)

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.1.1.1
  port: 1883
  user: user
  password: pass

record:
  enabled: true
  events:
    retain:
      default: 120

database:
  path: /config/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: usb:0
    model:
  coral2:
    type: edgetpu
    device: usb:1
    model:

logger:
  default: error
  logs:
    frigate.app: info
    frigate.mqtt: error
    frigate.event: error


snapshots:
  enabled: true
  bounding_box: true
  clean_copy: true
  retain:
    default: 60
    objects:
      person: 365

birdseye:
  enabled: true
  mode: continuous
  restream: true
  width: 1920
  height: 1080

go2rtc:
  streams:
    Front: # <- for RTSP streams
    - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
    Laundry: # <- for RTSP streams
    - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
    Backyard: # <- for RTSP streams
    - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
    Garage: # <- for RTSP streams
    - rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
    wyze-01: # <- for RTSP streams
    - rtmp://192.1.1.1:1935/wyze-01
    wyze-02: # <- for RTSP streams
    - rtmp://192.1.1.1:1935/wyze-02

objects:
  track:
  - person
  - dog
  - cat
  - rat
  - plane
  - airplane
  - motorbike
  filters:
    person:
      threshold: 0.7
    dog:
      threshold: 0.8
    cat:
      threshold: 0.8

telemetry:
  version_check: true

cameras:

  Laundry:
    enabled: true
    record:
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 120
          mode: active_objects
    audio:
      enabled: true
      max_not_heard: 30
      listen:
      - speech
      - fire_alarm
      - scream
      - yell
      - bang
      - smash
      - breaking
      - honk
      - toot
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
        - audio
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
      - dog
      - cat
      - rat
    mqtt:
      timestamp: true
      crop: true
      height: 1080
      bounding_box: false
      quality: 100
    motion:
      mask:
      - 0,720,0,657,374,661,373,720
      - 1280,434,738,221,315,121,125,101,0,151,0,0,1280,0
    zones:
      path:
        coordinates:
        - 1280,720,1280,470,689,219,134,99,0,150,0,720
        objects:
        - person
        - dog
        - cat
        - rat

  Front:
    enabled: true
    record:
      retain:
        days: 60
        mode: motion
      events:
        retain:
          default: 120
          mode: active_objects
    audio:
      enabled: false
      max_not_heard: 30
      listen:
      - speech
      - bark
      - fire_alarm
      - scream
      - yell
      - fart
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
        - audio
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
#      output_args:
#        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 10
    mqtt:
      timestamp: true
      crop: true
      height: 1080
      bounding_box: true
      quality: 100
    objects:
      track:
      - person
    motion:
      mask:
      - 1280,0,0,0,0,399,0,720,79,410,162,373,239,335,250,167,450,165,937,158,1280,156
      - 1280,720,1280,670,914,675,917,720
  Backyard:
    enabled: true
    record:
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 120
          mode: active_objects
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
        - audio
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
      - person
      - dog
      - cat
      - rat
    motion:
      mask:
      - 1280,0,1280,253,1098,161,1118,90,1020,59,1011,132,936,83,953,0
      - 561,0,327,0,0,0,0,720,439,720,497,398,509,248,581,190
    mqtt:
      timestamp: true
      crop: true
      height: 1080
      bounding_box: true
      quality: 100

  Garage:
    enabled: true
    record:
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 120
          mode: active_objects
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
        - audio
      - path: rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
#      output_args:
#        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    mqtt:
      timestamp: true
      crop: true
      height: 1080
      bounding_box: true
      quality: 100
    motion:
      mask:
      - 0,720,375,720,378,670,0,662

  wyze-01:
    enabled: true
    record:
      retain:
        days: 60
        mode: all
      events:
        retain:
          default: 120
          mode: active_objects
    audio:
      enabled: true
      max_not_heard: 30
      listen:
      - bark
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-rtmp-generic
      inputs:
      - path: rtmp://ip:1935/wyze-01
        roles:
        - record
        - audio
      output_args:
        record: preset-record-generic-audio-aac
    birdseye:
      enabled: false

  wyze-02:
    enabled: true
    record:
      retain:
        days: 60
        mode: all
      events:
        retain:
          default: 120
          mode: active_objects
    audio:
      enabled: true
      max_not_heard: 30
      listen:
      - bark
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-rtmp-generic
      inputs:
      - path: rtmp://ip:1935/wyze-02
        roles:
        - record
        - audio
      output_args:
        record: preset-record-generic-audio-aac
    birdseye:
      enabled: false
```

### Relevant log output

```shell
Nothing relevant
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua 5442 series
