### ISSUE TITLE
[Support]: Camera stream stopped working

### ISSUE THREAD

**Issue by ashwinikalantri** [blakeblackshear/frigate#9284]
### Describe the problem you are having

I have a Hikvision camera setup with frigate. This has been running without a problem for more than a year. Today the camera stopped displaying any frames. A black screen with error: no frames were received, check logs is displayed. I haven't made any changes to warrant this. The rtsp stream is working using VLC.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 172.16.1.115
  port: 1883
  user: ****
  password: ****

birdseye:
  enabled: False
  
record:
  enabled: False

objects:
  track:
    - person
    - bicycle
    - dog
  
cameras:
  outside:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@172.30.1.111:554/Streaming/channels/101
          roles:
            - detect
            - rtmp
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 0
        threshold: 30
    record:
      enabled: True
      retain:
        days: 0
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones:
          - road
          - inside
          - vyas
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: True
      timestamp: True
      retain:
        default: 5
    motion:
        mask:
          - 778,146,831,133,1170,133,1412,129,1421,193,1603,201,1616,26,32,28,47,216
    zones:
      inside:
        coordinates: 1596,330,1708,1080,216,1056,705,283,1189,291
        objects:
          - person
          - dog
          - bicycle
      road:
        coordinates: 1592,54,1609,212,1421,189,1404,135,1187,122,1172,298,814,272,816,167,47,231,49,32
        objects:
          - person 
      vyas:
        coordinates: 725,160,192,1080,32,1080,21,226
        objects:
          - person
    timestamp_style:
      position: "tl"
      format: "%d/%m/%Y %H:%M:%S"
      effect: shadow
```

### Relevant log output

```shell
2024-01-09 10:58:01.913895124  [2024-01-09 10:58:01] frigate.video                  ERROR   : outside: Unable to read frames from ffmpeg process.
2024-01-09 10:58:01.914066409  [2024-01-09 10:58:01] frigate.video                  ERROR   : outside: ffmpeg process is not running. exiting capture thread...
2024-01-09 10:58:06.894560964  [2024-01-09 10:58:06] watchdog.outside               ERROR   : Ffmpeg process crashed unexpectedly for outside.
2024-01-09 10:58:06.894676789  [2024-01-09 10:58:06] watchdog.outside               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-01-09 10:58:06.894803649  [2024-01-09 10:58:06] ffmpeg.outside.detect          ERROR   : [tcp @ 0x55db916d44c0] Connection to tcp://172.30.1.111:554?timeout=5000000 failed: Connection timed out
2024-01-09 10:58:06.894901619  [2024-01-09 10:58:06] ffmpeg.outside.detect          ERROR   : rtsp://*:*@172.30.1.111:554/Streaming/channels/101: Connection timed out
```

### FFprobe output from your camera

```shell
[tcp @ 0x55c7b9a3de40] Connection to tcp://172.30.1.111:554?timeout=0 failed: No route to host
rtsp://admin:password@123@172.30.1.111:554/Streaming/channels/101: No route to host
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"151":{"cpu":"0.0","mem":"0.0"},"172":{"cpu":"0.0","mem":"0.0"},"185":{"cpu":"0.0","mem":"0.0"},"208":{"cpu":"0.0","mem":"0.0"},"21":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"242":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"273":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"498":{"cpu":"0.3","mem":"0.2"},"504":{"cpu":"0.0","mem":"0.0"},"505":{"cpu":"0.0","mem":"0.3"},"506":{"cpu":"0.0","mem":"0.3"},"510":{"cpu":"0.3","mem":"0.3"},"511":{"cpu":"0.0","mem":"0.0"},"512":{"cpu":"0.0","mem":"0.3"},"53803":{"cpu":"0.0","mem":"0.0"},"53826":{"cpu":"0.0","mem":"0.1"},"53831":{"cpu":"0.3","mem":"0.0"},"53833":{"cpu":"0.0","mem":"0.0"},"53837":{"cpu":"0.3","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.1"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"0.7","mem":"0.7"},"MiB":{"cpu":"28346.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"0.03,"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":505}},"outside":{"camera_fps":0.0,"capture_pid":512,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":53826,"pid":510,"process_fps":0.0,"skipped_fps":0.0},"service":{"last_updated":1704860386,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":58.7,"mount_type":"tmpfs","total":67.1,"used":8.4},"/media/frigate/clips":{"free":1690362.7,"mount_type":"ext4","total":2158836.8,"used":379609.2},"/media/frigate/recordings":{"free":1690362.7,"mount_type":"ext4","total":2158836.8,"used":379609.2},"/tmp/cache":{"free":1690362.7,"mount_type":"overlay","total":2158836.8,"used":379609.2}},"temperatures":{},"uptime":64612,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision
