### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by StefanoGiu** [blakeblackshear/frigate#9291]
### Describe the problem you are having

I upgraded from v0.13.0-beta5 to v0.13.0-beta7.

Now my 2K cameras always appears with black image, no frame sent. They were working properly before with beta5, no change in the config...

### Version

v0.13.0-beta7

### Frigate config file

```yaml
Giovanni3:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@XX.XX.XX.XX:XX/Streaming/Channels/101
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask:
        - 2304,0,2304,333,1714,0
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - car
        - motorcycle
    detect:
      width: 2304
      height: 1296
      fps: 15
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Codnida 2K
