### ISSUE TITLE
Feature Request: Allow a time_limit for recording events using the "all" option when the object is not in motion

### ISSUE THREAD

**Issue by jay-kub** [blakeblackshear/frigate#9303]
**Describe what you are trying to accomplish and why in non technical terms**
I prefer to use the "all" option when recording events, however there are edge cases that result in recordings that can last for several days with no motion, which then cause storage issues.

**Describe the solution you'd like**
Let's consider a scenario where you drive up and park in your driveway, go inside, then come back out 4 hours later. With the all option all segments for the duration of the event would be saved for the event. This event would have 4 hours of footage.

If a time_limit of 60 was set, the recording would stop 60 minutes after the you parked the car and left the frame, and a new recording would begin when you re-entered the frame four hours later. This event would have ~63 minutes of footage separated into two recordings.

```
record:
  enabled: True
  events:
    retain:
      default: 14
      mode: all
        # If the object is not in motion for a period that exceeds the time_limit, the recording will stop. Time limit is set in minutes.
        time_limit: 60
```

**Describe alternatives you've considered**
[#9275](https://github.com/blakeblackshear/frigate/issues/9275) is an alternative option, but I think time based parameters are more practical.
