### ISSUE TITLE
Constant video glitching

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#931]
**Describe the bug**
random visual glitching
https://i.imgur.com/0xNSbzc.png

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.178.79
  user: mosquitto
  password: PASSWORD
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASS@192.168.178.113:554/h264Preview_01_main
          roles:
            - record
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 5
    clips:
      enabled: True
    snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
  # Optional: crop the snapshot (default: shown below)
      crop: True
  # Optional: height to resize the snapshot to (default: original size)
     #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
 # retain:
  #  # Required: Default retention days (default: shown below)
   # default: 10
    # Optional: Per object retention days
    #objects:
     # person: 15

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu


record:
  enabled: False
ffmpeg:
 # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning 
#  # Optional: global hwaccel args (default: shown below)
#  # NOTE: See hardware acceleration docs for your specific device 
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -c:v h264_cuvid
  # Optional: global output args
#  output_args:
    # Optional: output args for detect streams (default: shown below)
   # detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
#    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for clips streams (default: shown below)
#    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
  #  rtmp: -c copy -f flv


#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - -c:v
#    - h264_cuvid
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - train
    - car
    - bird
    - cat
    - dog
    - backpack
    - umbrella
    - handbag
    - suitcase
    - sports ball
    - skateboard
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush  

clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 30
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
  #tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```

**Frigate container logs**
```
Attaching to frigate
frigate             |  * Starting nginx nginx
frigate             |    ...done.
frigate             | frigate.app                    WARNING : Camera back has record assigned to an input, but record is not enabled.
frigate             | Starting migrations
frigate             | peewee_migrate                 INFO    : Starting migrations
frigate             | There is nothing to migrate
frigate             | peewee_migrate                 INFO    : There is nothing to migrate
frigate             | frigate.mqtt                   INFO    : MQTT connected
frigate             | detector.cpu1                  INFO    : Starting detection process: 41
frigate             | detector.cpu2                  INFO    : Starting detection process: 43
frigate             | frigate.app                    INFO    : Camera processor started for back: 47
frigate             | detector.cpu3                  INFO    : Starting detection process: 45
frigate             | frigate.app                    INFO    : Capture process started for back: 49
frigate             | [h264 @ 0x55a49c2a8f00] error while decoding MB 39 1, bytestream -15
frigate             | [h264 @ 0x5579f672bf00] left block unavailable for requested intra mode
frigate             | [h264 @ 0x5579f672bf00] error while decoding MB 0 80, bytestream 41904
frigate             | [h264 @ 0x55f89d41af00] left block unavailable for requested intra4x4 mode -1
frigate             | [h264 @ 0x55f89d41af00] error while decoding MB 0 73, bytestream 69294
frigate             | [h264 @ 0x5641254b0f00] left block unavailable for requested intra4x4 mode -1
frigate             | [h264 @ 0x5641254b0f00] error while decoding MB 0 81, bytestream 37129
frigate             | [h264 @ 0x560b9d248f00] left block unavailable for requested intra4x4 mode -1
frigate             | [h264 @ 0x560b9d248f00] error while decoding MB 0 81, bytestream 31122
frigate             | [h264 @ 0x55a607bdff00] cabac decode of qscale diff failed at 120 75
frigate             | [h264 @ 0x55a607bdff00] error while decoding MB 120 75, bytestream 57374
```

**Frigate stats**
```json
{
back: {
camera_fps: 8.9,
capture_pid: 49,
detection_fps: 7.2,
pid: 47,
process_fps: 4,
skipped_fps: 0
},
detection_fps: 7.2,
detectors: {
cpu1: {
detection_start: 0,
inference_speed: 78.66,
pid: 41
},
cpu2: {
detection_start: 0,
inference_speed: 79.53,
pid: 43
},
cpu3: {
detection_start: 0,
inference_speed: 75.48,
pid: 45
}
},
service: {
storage: {
/dev/shm: {
free: 63.4,
mount_type: "tmpfs",
total: 67.1,
used: 3.7
},
/media/frigate/clips: {
free: 314026.4,
mount_type: "ext4",
total: 3936911.9,
used: 3422829.5
},
/media/frigate/recordings: {
free: 314026.4,
mount_type: "ext4",
total: 3936911.9,
used: 3422829.5
},
/tmp/cache: {
free: 972.8,
mount_type: "tmpfs",
total: 1000,
used: 27.2
}
},
uptime: 276,
version: "0.8.4-5043040"
}
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
root@skynetbams:/docker# ffprobe rtsp://admin:MuggenLaan1@192.168.178.113:554/h264Preview_01_main
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

```

**Screenshots**
https://i.imgur.com/0xNSbzc.png

**Computer Hardware**
 - OS:: Ubuntu server 20.04 LTS
 - Install method: Docker Compose
 - CPU: Intel(R) Xeon(R) CPU E31270 @ 3.40GHz
 - GPU: GTX 1050TI 4GB
 - RAM: 16GB DDR3

**Camera Info:**
not sure how applicable, happens with multiple, but alas
 - Manufacturer: REOLINK
 - Model: reolink 410w
 - Resolution: 1440p, tried lower but glitches got worse
 - FPS: 5
