### ISSUE TITLE
[Camera Support]: Android IP Webcam 2 way communication

### ISSUE THREAD

**Issue by zyznos321** [blakeblackshear/frigate#9310]
### Describe the problem you are having

I have Android phone with IP webcam app installed. Camera stream from phone is working fine with frigate on home assistant. I added mic and sound button on home assistant card. I can hear voice from camera but when I try to record sound from mic and play on camera it's not working.

Is there any way to use android ip webcam with frigate 2 way audio?
Sound to ip webcam app can be send via curl --data-binary @rec.wav http://ip:port/audioin.wav

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: homeassistant
  user: homeassistant
  password: PASS
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
go2rtc:
  streams:
    rtsp_cam: # <- for RTSP streams
      - rtsp://ip_addr:8080:8080/h264_opus.sdp 
      
ffmpeg:
  hwaccel_args: preset-vaapi
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://ip_addr:8080/h264.sdp
          roles:
            - detect
    detect:
      enabled: true
      width: 720
      height: 480
    snapshots: # <----- Enable snapshots
      enabled: True
    live:
      stream_name: rtsp_cam
```

### Relevant log output

```shell
empty
```

### FFprobe output from your camera

```shell
empty
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

android ip webcam
