### ISSUE TITLE
[Support]: False positives detected in 0.13 beta

### ISSUE THREAD

**Issue by derhappy** [blakeblackshear/frigate#9314]
### Describe the problem you are having

I recently switched from 0.12.1 to the latest beta and see a huge increase in wrongly assigned labels. For example, a lot of dogs get marked as person whilst I am pretty sure the person is the object at the other end of the leash.
Before the update I had some wrongly assigned labels, but mostly without the right object being in the frame. For example, previously some gras was mistaken for a dog / cat.

![grafik](https://github.com/blakeblackshear/frigate/assets/61394775/aff2e60e-49d8-4848-8664-99f6a3e1663f)

### Version

0.13.0-c35c7da

### Frigate config file

```yaml
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 5000000 -use_wallclock_as_timestamps 1

go2rtc:
  streams:
    gartenseite:
    - rtsp://ya:na@ney/Streaming/Channels/101/
    gartenseite_sub:
    - rtsp://ya:na@ney/Streaming/Channels/102/
    gartenende:
    - ffmpeg:gartenseite#video=h264#raw=-vf crop=1280:720:2580:0
    eingang:
    - rtsp://this:is@wrong/axis-media/media.amp?streamprofile=full264&camera=2
    eingang_sub:
    - rtsp://this:is@wrong/axis-media/media.amp?streamprofile=detect&camera=2
    klingel_ipad:
    - rtsp://this:is@wrong/axis-media/media.amp?camera=3

mqtt:
  host: 192.168.1.222
  user: mqtt_user
  password: mqtt_password

cameras:
  garage:
    ffmpeg:
      inputs:
      - path: rtsp://not:relevant@here/Streaming/Channels/101/
        roles:
        - detect
        - record
    detect:
      width: 2304
      height: 1296
      fps: 5
      stationary:
        interval: 10
        max_frames:
          objects:
            person: 300
    rtmp:
      enabled: false
    motion:
      mask:
      - 636,162,1833,278,2053,381,2131,0,0,0,0,535,350,291,451,272
    zones:
      rasen:
        coordinates: 2092,415,1866,273,819,182,563,314,1517,473,2059,529
      einfahrt:
        coordinates: 540,1296,1878,1296,2062,527,1515,471,613,291,89,657
    objects:
      track:
      - person
      - car
      - cat
      - dog
      - bear
      - mouse
      filters:
        bear:
          mask:
          - 2304,1296,2304,0,2071,0,2099,1296
          - 2137,0,0,0,0,172,2135,200
          - 0,448,0,1296,412,1296
          - 938,0,0,0,0,564
        car:
          mask:
          - 2304,1296,2304,0,2071,0,2099,1296
          - 0,1296,0,411,564,1296,316,1296
          - 1568,259,1898,601,1680,1296,742,1296,167,705,219,610,745,161
        cat:
          mask:
          - 2304,1296,2304,0,2071,0,2099,1296
          - 2137,0,0,0,0,172,2135,200
          - 0,448,0,1296,412,1296
          - 938,0,0,0,0,564
        dog:
          mask:
          - 2304,1296,2304,0,2071,0,2099,1296
          - 2137,0,0,0,0,172,2135,200
          - 0,448,0,1296,412,1296
          - 938,0,0,0,0,564
        person:
          min_area: 10000
          mask:
          - 526,296,587,79,764,0,0,0,0,581,74,581
        mouse:
        #btw, does not work at all. 
          min_area: 200
          max_area: 11000
          min_score: 0.1
          threshold: 0.1
          mask:
          - 0,1296,0,0,2130,0,2113,325,1785,280,1689,1294
          - 2157,0,2304,0,2304,1296,1910,1296,2053,820
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100

  gartenseite:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/gartenseite_sub
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/gartenseite
        input_args: preset-rtsp-restream
        roles:
        - record
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 10
        max_frames:
          objects:
            person: 300
    rtmp:
      enabled: false
    motion:
      mask:
      - 329,40,669,35,1103,96,1107,0,0,0,0,73
      - 1280,225,1204,229,956,720,1280,720
      contour_area: 40
      frame_height: 80
    zones:
      tonnen:
        coordinates: 94,581,591,402,466,70,0,178,0,291
      weg:
        coordinates: 1046,236,1144,267,718,720,183,720,131,615
      gartenseite_all:
        coordinates: 0,89,256,28,782,64,1219,106,1001,720,0,720
    objects:
      track:
      - person
      - cat
      - mouse
      filters:
        cat:
          mask:
          - 409,24,1075,41,1091,0,0,0,0,72
          - 1105,423,1233,0,1280,0,1280,720,947,720
        person:
          min_area: 10000
          mask:
          - 409,24,1075,41,1091,0,0,0,0,72
          - 1105,423,1233,0,1280,0,1280,720,947,720
        mouse:
          min_score: 0.3
          threshold: 0.3
          mask:
          - 409,24,1075,41,1091,0,0,0,0,72
          - 1105,423,1233,0,1280,0,1280,720,947,720
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100

  gartenende:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/gartenende
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 10
        max_frames:
          objects:
            person: 300
    record:
      enabled: false
    rtmp:
      enabled: false
    motion:
      mask:
      - 1280,0,1280,267,0,272,0,0
      - 813,566,790,627,758,620,773,549
    objects:
      track:
      - person
      filters:
        person:
          threshold: 0.5
          min_area: 2500
          max_area: 160000
          mask:
          - 718,720,860,720,867,698,824,684,852,598,826,570,768,555
          - 569,517,795,504,1280,543,1280,0,0,0,0,623,195,581,387,521
    zones:
      gartenende_all:
        coordinates: 1280,720,1280,0,0,0,0,720
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
    ui:
      order: 4

  eingang:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/eingang
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/eingang_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 50
        max_frames:
          objects:
            person: 300
    rtmp:
      enabled: false
    zones:
      treppe:
        coordinates: 1502,534,788,650,642,840,1461,925
      einfahrt:
        coordinates: 1462,129,1152,166,979,396,1461,310
      eingang_ext:
        coordinates: 1556,1080,1535,46,1155,98,385,1080
      eingang_all:
        coordinates: 1514,1080,1456,0,1063,0,0,984,0,1080
        objects:
        - car
        - cat
        - bear
        - mouse
    objects:
      track:
      - person
      - car
      - cat
      - dog
      - bear
      - mouse
      mask:
      - 826,0,0,0,0,652
      filters:
        bear:
          mask:
          - 1920,1080,1920,0,1487,0,1511,446,1515,1080
        car:
          mask:
          - 1920,1080,1920,0,1462,0,1485,321,1018,402,495,1080
          - 1268,74,1458,0,1471,246,1279,251
        cat:
          mask:
          - 1920,1080,1920,0,1487,0,1511,446,1515,1080
          - 950,657,776,635,948,407,1051,392
        dog:
          mask:
          - 1920,1080,1920,0,1487,0,1511,446,1515,1080
          - 960,671,994,462,895,482,847,560,791,654
        person:
          mask:
          - 1053,169,1168,115,1182,0,0,0,0,1080,135,1080
    motion:
      mask:
      - 0,0,975,0,430,519,0,648
      - 588,867,546,935,548,998,616,1014,699,986,736,896,714,870,657,838
      - 1920,1080,1629,1080,1634,0,1920,0
      - 454,1080,0,904,0,1080
      - 1207,1080,1221,911,959,863,848,1080
      - 990,416,1109,284,1313,256,1369,407,1324,594,1147,601
      - 161,1080,28,990,0,719,106,725,131,837,155,904,189,729,270,761,224,960,329,957,376,969,437,1005,437,1080
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100

detectors:
  coral:
    type: edgetpu
    device: usb


record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    required_zones:
    - treppe
    - einfahrt
    - rasen
    - gartenseite_all
    - gartenende_all
    pre_capture: 5
    post_capture: 5
    retain:
      default: 8
      objects:
        person: 15
snapshots:
  enabled: true
  bounding_box: true
  crop: true
  clean_copy: true
  retain:
    default: 8
  required_zones:
  - eingang_ext
  - einfahrt
  - rasen
  - eingang_all
  - gartenseite_all
  - gartenende_all

database:
  path: /db/frigate.db

# Optional: birdseye configuration
birdseye:
  enabled: false
  width: 800
  height: 600
  quality: 20
  mode: continuous
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{
  "cameras": {
    "eingang": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.1,
      "capture_pid": 930,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 937,
      "pid": 906,
      "process_fps": 5.1,
      "skipped_fps": 0.0
    },
    "garage": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.0,
      "capture_pid": 917,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 493104,
      "pid": 899,
      "process_fps": 5.0,
      "skipped_fps": 0.0
    },
    "gartenende": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.0,
      "capture_pid": 925,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 934,
      "pid": 903,
      "process_fps": 5.0,
      "skipped_fps": 0.0
    },
    "gartenseite": {
      "audio_dBFS": 0.0,
      "audio_rms": 0.0,
      "camera_fps": 5.1,
      "capture_pid": 921,
      "detection_enabled": 1,
      "detection_fps": 0.0,
      "ffmpeg_pid": 926,
      "pid": 901,
      "process_fps": 5.1,
      "skipped_fps": 0.0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "79": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "12.1",
      "cpu_average": "9",
      "mem": "0.1"
    },
    "97": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "98": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "2.2",
      "cpu_average": "2",
      "mem": "1.2"
    },
    "110": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "145": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "146": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "149": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "164": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "185": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "214": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "244": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "269": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "293": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "319": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "339": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "372": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "414": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "451": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "490": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "547": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "584": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "614": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "642": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "664": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "876": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "878": {
      "cmdline": "frigate.recording_manager",
      "cpu": "3.0",
      "cpu_average": "1",
      "mem": "0.3"
    },
    "887": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)",
      "cpu": "0.2",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "890": {
      "cmdline": "frigate.output       ",
      "cpu": "1.3",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "896": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1"
    },
    "897": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "899": {
      "cmdline": "frigate.process:garage",
      "cpu": "1.2",
      "cpu_average": "6",
      "mem": "0.3"
    },
    "900": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "901": {
      "cmdline": "frigate.process:gartenseite",
      "cpu": "1.2",
      "cpu_average": "1",
      "mem": "0.3"
    },
    "902": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "903": {
      "cmdline": "frigate.process:gartenende",
      "cpu": "1.2",
      "cpu_average": "1",
      "mem": "0.3"
    },
    "906": {
      "cmdline": "frigate.process:eingang",
      "cpu": "1.3",
      "cpu_average": "1",
      "mem": "0.3"
    },
    "917": {
      "cmdline": "frigate.capture:garage",
      "cpu": "3.0",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "921": {
      "cmdline": "frigate.capture:gartenseite",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "925": {
      "cmdline": "frigate.capture:gartenende",
      "cpu": "1.1",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "926": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/gartenseite_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.3",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "930": {
      "cmdline": "frigate.capture:eingang",
      "cpu": "2.5",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "934": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gartenende -r 5 -vf fps=5,scale_vaapi=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.4",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "937": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang_sub -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "5.6",
      "cpu_average": "5",
      "mem": "0.2"
    },
    "938": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gartenseite -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/gartenseite@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.6",
      "cpu_average": "1",
      "mem": "0.0"
    },
    "940": {
      "cmdline": "ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/gartenseite?video -vf crop=1280:720:2580:0 -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -pix_fmt:v yuv420p -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/678eb1c8ff561a5cf9427b22705793fe",
      "cpu": "73.0",
      "cpu_average": "69",
      "mem": "0.2"
    },
    "943": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-c35c7da -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/eingang -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/eingang@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "160978": {
      "cmdline": "frigate.detector.coral",
      "cpu": "0.0",
      "cpu_average": "2",
      "mem": "0.5"
    },
    "493104": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://pleaseremovepasswords/Streaming/Channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2304:h=1296:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "10.4",
      "cpu_average": "8",
      "mem": "0.3"
    },
    "806844": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 0.0,
  "detectors": {
    "coral": {
      "detection_start": 0.0,
      "inference_speed": 8.53,
      "pid": 160978
    }
  },
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "1.92%",
      "mem": "-%"
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 876
    },
    "recording": {
      "pid": 878
    }
  },
  "service": {
    "last_updated": 1705049983,
    "latest_version": "disabled",
    "storage": {
      "/dev/shm": {
        "free": 101.7,
        "mount_type": "tmpfs",
        "total": 128.0,
        "used": 26.3
      },
      "/media/frigate/clips": {
        "free": 388445.2,
        "mount_type": "zfs",
        "total": 894306.4,
        "used": 505861.1
      },
      "/media/frigate/recordings": {
        "free": 388445.2,
        "mount_type": "zfs",
        "total": 894306.4,
        "used": 505861.1
      },
      "/tmp/cache": {
        "free": 924.1,
        "mount_type": "tmpfs",
        "total": 953.7,
        "used": 29.6
      }
    },
    "temperatures": {},
    "uptime": 125422,
    "version": "0.13.0-c35c7da"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Axis, Hikvision
