### ISSUE TITLE
[Support]: High network usage with NAS

### ISSUE THREAD

**Issue by LordXaosa** [blakeblackshear/frigate#9315]
### Describe the problem you are having

Seem like ffmpeg uses too much io on read while writing files. So the question is how to prevent it and write on NAS only results files without temp (if it's temp?)

All works fine, just network activity is weird.
I've got 300kb\sec on write (what is correct) and near 14-17mb\sec on read from NAS, which is not correct I guess.

Here is network activity:
![image](https://github.com/blakeblackshear/frigate/assets/1145380/aaed3eb8-a338-4ce7-9b87-46aab477bf42)
So RTSP is ok and it's close to network output to NAS, but what is reading from NAS? And why it's so huge for one camera? 
If I stop frigate container - activity go to zero, so it's definitely relevant to frigate container. May be temp processing by ffmpeg? How to avoid it?

Also important remark. Network activity is ok after restarting container, but become again weird in 2-5 minutes later.

### Version

0.13.0-beta3

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: host
  port: port
  user: user
  password: pwd
go2rtc:
  streams:
    kids_cam: >-
      exec:ffmpeg
      -rtsp_transport tcp -i "rtsp://%cam%/live/ch00_0"
      -rtsp_transport tcp
      -c:a aac -c:v copy
      -filter:a "volume=20dB"
      -f rtsp
      {{output}}

cameras:
  back:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/kids_cam
        roles:
        - detect
        - record
        - audio
      output_args:
        record: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c:a aac -c:v copy

    detect:
      width: 1920
      height: 1080
    audio:
      enabled: true
      listen:
      - scream
      - crying
audio:
  enabled: true
  min_volume: 100
  listen:
  - scream
  - crying
  filters:
    crying:
      threshold: 0.6

detect:
  max_disappeared: 5
objects:
  track:
  - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.7
      mask:
      - 1644,227,1818,320,1872,111,1886,0,1683,0

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  improve_contrast: false
  mqtt_off_delay: 5
  mask:
  - 1644,227,1818,320,1872,111,1886,0,1683,0
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 30
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
    - person
    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: false
  crop: false
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
```

### Relevant log output

```shell
logs contains only access_log, nothing interesting here.
```

### FFprobe output from your camera

```shell
not a camera problem
```

### Operating system

Debian (proxmox LXC)

### Install method

Docker

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Jooan 5MP
