### ISSUE TITLE
Unable to create clip for ***

### ISSUE THREAD

**Issue by Rothammel** [blakeblackshear/frigate#932]
sometimes no clip is recorded

0.8.4-5043040

**Config file**
```
mqtt:
  host: 192.168.0.5
  user: Stan
  password: ~
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus

cameras:
  Garten:
    ffmpeg:
      inputs:
        - path: rtsp://admin:st@ni0815@192.168.0.101:554/h264Preview_01_main
          roles:
            - detect
            - clips
      input_args:
        - -rtsp_transport
        - tcp
    width: 2560
    height: 1920

    fps: 2
    clips:
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 10
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 20
      # Optional: Objects to save clips for. (default: all tracked objects)
      # objects:
      #  - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 120
        # Optional: Per object retention days
        # objects:
        #  person: 15
    snapshots:
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      # height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 120
        # Optional: Per object retention days
        # objects:
        #  person: 15

  Einfahrt:
    ffmpeg:
      inputs:
        - path: rtsp://admin:st@ni0815@192.168.0.100:554/h264Preview_01_main
          roles:
            - detect
            - clips
      input_args:
        - -rtsp_transport
        - tcp

    width: 2560
    height: 1920
    fps: 2

    clips:
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 10
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 20
      # Optional: Objects to save clips for. (default: all tracked objects)
      # objects:
      #  - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 120
        # Optional: Per object retention days
        # objects:
        #  person: 15
    snapshots:
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      # height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 120
        # Optional: Per object retention days
        # objects:
        #  person: 15

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

**Frigate container logs**
```
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915964980 / timestamp: 2916324462 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915968039 / timestamp: 2916327522 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915971008 / timestamp: 2916330492 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915973977 / timestamp: 2916333462 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915976946 / timestamp: 2916336432 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915980005 / timestamp: 2916339492 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915982974 / timestamp: 2916342462 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915985943 / timestamp: 2916345432 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915988912 / timestamp: 2916348402 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915991971 / timestamp: 2916351462 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915994940 / timestamp: 2916354432 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2915997909 / timestamp: 2916357402 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916000968 / timestamp: 2916360462 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916003937 / timestamp: 2916363432 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916006906 / timestamp: 2916366402 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916009875 / timestamp: 2916369372 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916012934 / timestamp: 2916372432 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916015903 / timestamp: 2916375402 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916018872 / timestamp: 2916378372 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916021931 / timestamp: 2916381432 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916024900 / timestamp: 2916384402 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916027869 / timestamp: 2916387372 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916030838 / timestamp: 2916390342 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916033897 / timestamp: 2916393402 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916036866 / timestamp: 2916396372 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916039835 / timestamp: 2916399342 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916042894 / timestamp: 2916402402 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916045863 / timestamp: 2916405372 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916048832 / timestamp: 2916408342 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916051801 / timestamp: 2916411312 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916054860 / timestamp: 2916414372 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916057829 / timestamp: 2916417342 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916060798 / timestamp: 2916420312 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916063767 / timestamp: 2916423282 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916066826 / timestamp: 2916426342 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916069795 / timestamp: 2916429312 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] Application provided duration: 2916072764 / timestamp: 2916432282 is out of range for mov/mp4 format
ffmpeg.Einfahrt.detect         ERROR   : [mp4 @ 0x562165957ac0] pts has no value
ffmpeg.Einfahrt.detect         ERROR   : More than 10000 frames duplicated
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616567581.40239-4gj8py. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616576709.82348-3x6bwd. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616578687.768327-9pic06. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616579229.706888-aeu0pl. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616581800.601124-n4cm5h. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616581977.997514-48tuu2. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616583417.002309-eqzvp4. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616586022.238308-cmu5ru. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616587810.724563-wa6o3g. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616592560.121652-4ebmq3. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616592588.221563-smluk9. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616592673.687023-g2f9zj. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616593664.163029-pjyjjh. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616594009.635661-a0zqqi. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616594468.20862-hgyr52. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616595570.957551-gb15qw. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616595630.492151-nbboxg. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616595712.02697-xnlqsf. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616595800.495942-qkqh7t. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Garten and event 1616596163.270055-jnrxqu. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Garten and event 1616597779.940635-enj7il. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616598678.148776-dew9vi. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616599509.934566-ifg3js. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Einfahrt and event 1616600043.98121-8cfigc. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for Garten and event 1616601600.649534-z7l7ab. There were no cache files for this event.
```

**Frigate stats**
```
json
{
  "Einfahrt": {
    "camera_fps": 2.1, 
    "capture_pid": 44, 
    "detection_fps": 2.6, 
    "pid": 42, 
    "process_fps": 2.0, 
    "skipped_fps": 0.0
  }, 
  "Garten": {
    "camera_fps": 2.0, 
    "capture_pid": 43, 
    "detection_fps": 0.0, 
    "pid": 41, 
    "process_fps": 2.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 2.6, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 99.2, 
      "pid": 36
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 79.95, 
      "pid": 37
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1670.0, 
        "mount_type": "tmpfs", 
        "total": 1685.7, 
        "used": 15.8
      }, 
      "/media/frigate/clips": {
        "free": 25004.0, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 6690.0
      }, 
      "/media/frigate/recordings": {
        "free": 25004.0, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 6690.0
      }, 
      "/tmp/cache": {
        "free": 1445.7, 
        "mount_type": "tmpfs", 
        "total": 1685.7, 
        "used": 240.0
      }
    }, 
    "uptime": 84922, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**
```
Input #0, rtsp, from 'rtsp://admin:st@ni0815@192.168.0.101:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 30 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

**Screenshots**
![image](https://user-images.githubusercontent.com/42540450/112345745-9a4b3c80-8cc5-11eb-8e5c-e9587a73a043.png)

**Computer Hardware**
 - OS: HASSIO
 - Install method: Addon
 - Virtualization: Proxmox
 - Coral Version: None
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-410-5MP
 - Resolution: 5MP 2560x1920
 - FPS: 30

**Additional context**
