### ISSUE TITLE
Frigate not storing media on second drive

### ISSUE THREAD

**Issue by JABeaver** [blakeblackshear/frigate#9338]
### Describe the problem you are having

I'm running Frigate on ubuntu with docker compose and it's integrated with homeassistant in another docker container. Everything works fine except when I try to change the docker compose yaml to move the /media/frigate map to the new drive mounted at /data. (- /data/frigate:/media/frigate) it doesn't move the files to the persistent volume it stays inside the docker environment.  I'm running docker compose as root via sudo docker compose up -d and the permissions on the drive are 755 and the owner and group are root.  I realize this may be a docker issue but I can't figure it out. Any help or leads would be appreciated. 

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: localhost
  port: 1883
  client_id: Frigate_NVR
  user: F-NVR
  password: ****
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous

cameras:
  camera_1: # <------ Name of the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://****@10.5.5.151:554/cam/realmonitor?channel=1&subtype=1 # Low Res Sub-Stream
          roles:
            - detect
            - rtmp
        - path: rtsp://****@10.5.5.151:554/cam/realmonitor?channel=1&subtype=0 # High Res Stream
          roles:
            - record
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
#    rtmp:
#      enabled: true
    detect:
      width: 704
      height: 480
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    snapshots:
      enabled: true
      retain:
        default: 7
    motion:
      mask:
        - 683,48,684,11,511,11,509,51
  inside: # <------ Name of the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://****@10.5.5.152:554/h264Preview_01_sub # Low Res Sub-Stream
          roles:
            - detect
            - rtmp
        - path: rtsp://****@10.5.5.152:554/h264Preview_01_main # High Res Stream
          roles:
            - record
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
#    rtmp:
#      enabled: true
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
    snapshots:
      enabled: true
      retain:
        default: 7
    motion:
      mask:
        - 419,11,409,32,223,34,214,10
        - 538,155,640,163,640,63,544,48
        - 506,84,501,138,465,137,466,81
objects:
  track:
    - person
    - cat
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua and REOLink

### Any other information that may be helpful

docker compose yaml: I currently have the file in my user's home folder
```yaml
version:` "3.9"
services:
  frigate:
    container_name: frigate
    network_mode: host
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker-compose/frigate/config.yml:/config/config.yml:ro
#      - /data/frigate:/media/frigate
      - /home/user/docker-compose/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```
