### ISSUE TITLE
[Config Support]: Best way to tackle my false positives

### ISSUE THREAD

**Issue by asteriqz** [blakeblackshear/frigate#9348]
### Describe the problem you are having

Hello All,

Just wanting confirmation on the best way to setup people detection on this camera I was planning on using **min_ratio** and **max_ratio** although it seems like I could also use **min_area** and **max_area**.

What would be recommended in my situation?

**Person(80%)**
![snapshot-1705362301 128929-rxjmle](https://github.com/blakeblackshear/frigate/assets/20625187/b7ca8b39-0d1a-48f1-b910-06c611d34feb)
**Person(73%)**
![snapshot-1705359791 870305-52gib1 (1)](https://github.com/blakeblackshear/frigate/assets/20625187/5e2e3bdc-921c-4ae1-9c20-06b5ad241b13)
**Person(82%)**
![snapshot-1705358422 274241-4o1grn](https://github.com/blakeblackshear/frigate/assets/20625187/e348170e-c195-4eb3-adb3-a293a93cca96)

Thank you.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: a0d7b954-emqx
  user: frigate
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: -tag:v hvc1

database:
  path: /config/frigate.db
  
go2rtc:
  streams:
    username: "admin"
    password: "xxx"
    driveway: 
      - rtsp://admin:xxx@192.168.0.211:554/h265Preview_01_main
      - "ffmpeg:driveway#video=h264#hardware"
    backyard:
      - rtsp://admin:xxx@192.168.0.210:554/h265Preview_01_main
      - "ffmpeg:backyard#video=h264#hardware"
    # sideyard:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.104:554/h265Preview_01_main
    #  - "ffmpeg:sideyard#video=h264#hardware"
    #doorbell:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.108:554/h264Preview_01_main
    #viewcam:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.105:554/h265Preview_01_main
    #  - "ffmpeg:viewcam#video=h264#hardware"

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
        - car
    zones:
     driveway_area:
      coordinates: 4096,1536,4096,615,2860,530,2056,482,1597,681,130,1536

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
      filters: 
       person:
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
        threshold: 0.8
    zones:
     backyard_area:
      coordinates: 0,1536,4096,1536,4096,0,0,0
    motion:
      mask:
      - 2035,0,1884,245,1575,454,1738,548,1600,592,1438,625,1195,512,1107,344,1003,264,790,234,705,102,1319,0,1581,0

record:
 enabled: True
 retain:
  days: 7
  mode: motion
 events:
  required_zones:
    - driveway_area
    - backyard_area
  retain:
   default: 14
   mode: active_objects
snapshots:
  enabled: True

rtmp:
  enabled: false

birdseye:
  enabled: True
  mode: continuous
  restream: False
  width: 1920
  height: 1080
  quality: 4
```

### Relevant log output

```shell
Photos have been attached
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
