### ISSUE TITLE
[Support]: Frigate+ (generated model) model does not fully detect the car

### ISSUE THREAD

**Issue by mabed-fr** [blakeblackshear/frigate#9354]
### Describe the problem you are having

Frigate+ model does not fully detect the car

![Car_detection_not_complet](https://github.com/blakeblackshear/frigate/assets/25350431/c6ba7d82-6ae0-4465-936a-a175d283e639)

### Version

SYSTEM 0.13.0-49814B3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.254

model:
  path: plus://f146fbad60ac7504eb57a5b950f37e31


birdseye:
  enabled: True
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
 track:
   - person
   - car
   - bicycle
   - motorcycle
   - cat
   - dog
   - plate

go2rtc:
  streams:
    TELECOM:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main

cameras:
  TELECOM:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
      output_args:
       record: preset-record-generic-audio-aac
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    onvif:
      host: 192.168.1.146
      port: 8000
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"

detect:
  enabled: true
  width: 1920
  height: 1080
#fps: 10

record:
  expire_interval: 60
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 1

snapshots:
  enabled: true
```

### Relevant log output

```shell
NC
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":2160,"width":3840},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Frigate stats

```json
{"cameras":{"TELECOM":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.2,"capture_pid":248,"detection_enabled":1,"detection_fps":0.2,"ffmpeg_pid":256,"pid":245,"process_fps":5.2,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.1"},"108":{"cmdline":"python3 -u -m frigate","cpu":"7.2","cpu_average":"1","mem":"2.9"},"113":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"116":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"136":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"137":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.3"},"138":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"222":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"224":{"cmdline":"frigate.recording_manager","cpu":"0.0","cpu_average":"0","mem":"0.8"},"233":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(41)","cpu":"0.0","cpu_average":"0","mem":"0.1"},"235":{"cmdline":"frigate.output       ","cpu":"0.0","cpu_average":"0","mem":"0.8"},"242":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"243":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"245":{"cmdline":"frigate.process:TELECOM","cpu":"1.4","cpu_average":"4","mem":"1.1"},"248":{"cmdline":"frigate.capture:TELECOM","cpu":"2.9","cpu_average":"3","mem":"0.8"},"256":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.0-49814b3 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://frigate:12*34@192.168.1.146:554/h265Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/TELECOM@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"10.1","cpu_average":"15","mem":"0.8"},"12264":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"0","mem":"2.8"},"75825":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.95,"pid":12264}},"gpu_usages":{"intel-vaapi":{"gpu":"11.3%","mem":"-%"}},"processes":{"go2rtc":{"pid":98},"logger":{"pid":222},"recording":{"pid":224}},"service":{"last_updated":1705403279,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":2040.5,"mount_type":"tmpfs","total":2048.0,"used":7.5},"/media/frigate/clips":{"free":685959.7,"mount_type":"ext4","total":936330.1,"used":202735.5},"/media/frigate/recordings":{"free":685959.7,"mount_type":"ext4","total":936330.1,"used":202735.5},"/tmp/cache":{"free":1899.6,"mount_type":"tmpfs","total":1907.4,"used":7.8}},"temperatures":{},"uptime":54450,"version":"0.13.0-49814b3"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

rlc811a
