### ISSUE TITLE
events.py error

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#936]
**Describe the bug**
I get a python error when running frigate.

**Version of frigate**
Output from `/api/version`
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.178.79
  user: mosquitto
  password: x
#  bounding_box: True
cameras:
  back:
    mqtt:
      bounding_box: True
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtmp://192.168.178.113/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=x
          roles:
            #- record
            - detect
            - rtmp
            - clips
    width: 2560
    height: 1440
    fps: 5
    clips:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
    

  front:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'

      inputs:
        - path: rtsp://192.168.178.55:8554/unicast
          roles:
            #- record
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    clips:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True

detectors:
  cpu1:
    type: cpu


record:
  enabled: False




ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'
    - -c:v
    - h264_cuvid

objects:

  track:
    - person
    - bicycle
    - motorcycle
    - bus
    - train
    - bird
    - cat
    - dog
    - backpack
    - umbrella
    - handbag
    - suitcase
    - sports ball
    - skateboard
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - chair
    - couch
    - bed
    - dining table
    - toilet
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush  

clips:
  max_seconds: 240
  retain:
    default: 10
    objects:
      person: 15

```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
```
Exception in thread event_processor:
frigate             | Traceback (most recent call last):
frigate             |   File "/opt/frigate/frigate/events.py", line 193, in run
frigate             |     event_type, camera, event_data = self.event_queue.get(timeout=10)
frigate             |   File "/usr/lib/python3.8/multiprocessing/queues.py", line 108, in get
frigate             |     raise Empty
frigate             | _queue.Empty
frigate             | 
frigate             | During handling of the above exception, another exception occurred:
frigate             | 
frigate             | Traceback (most recent call last):
frigate             |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
frigate             |     self.run()
frigate             |   File "/opt/frigate/frigate/events.py", line 196, in run
frigate             |     self.refresh_cache()
frigate             |   File "/opt/frigate/frigate/events.py", line 69, in refresh_cache
frigate             |     start_time = datetime.datetime.strptime(f.split('-')[-1].split('.')[0], '%Y%m%d%H%M%S')
frigate             |   File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
frigate             |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
frigate             |   File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
frigate             |     raise ValueError("time data %r does not match format %r" %
frigate             | ValueError: time data '%Y%m%d%H%M%S' does not match format '%Y%m%d%H%M%S'
````

**Computer Hardware**
 - OS:: Ubuntu server 20.04 LTS
 - Install method: Docker Compose
 - CPU: Intel(R) Xeon(R) CPU E31270 @ 3.40GHz
 - GPU: GTX 1050TI 4GB
 - RAM: 16GB DDR3

**Camera Info:**
not sure how applicable, happens with multiple, but alas
 - Manufacturer: REOLINK
 - Model: reolink 410w
 - Resolution: 1440p, tried lower but glitches got worse
 - FPS: 5
