### ISSUE TITLE
[Support]: Go2rtc binary not loading

### ISSUE THREAD

**Issue by ryphez** [blakeblackshear/frigate#9380]
### Describe the problem you are having

I tried adding go2rtc binary (64 bit) for unraid and have the permissions setup correctly, but frigate is not loading the binary.

> -rwxrwxrwx 1 nobody nogroup 5316520 Jan 18 11:55 go2rtc*
> root@Andromeda:/mnt/user/appdata/frigate/config# 

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.215
  user: mqttuser
  password: 

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    reolink_indoor_e1_zoom_camera:
      - rtsp://admin:PASSWORD@192.168.1.79//h264Preview_01_main
      - "ffmpeg:reolink_indoor_e1_zoom_camera#audio=opus" 
    reolink_indoor_e1_zoom_camera_sub:
      - rtsp://admin:PASSWORD@192.168.1.79//h264Preview_01_sub
      - "ffmpeg:reolink_indoor_e1_zoom_camera_sub#audio=opus" 
    reolink_doorbell_camera:
      - rtsp://admin:PASSWORD@192.168.107.87//h264Preview_01_main
      - "ffmpeg:reolink_doorbell_camera#audio=opus" 
    reolink_doorbell_camera_sub:
      - rtsp://admin:PASSWORD@192.168.107.87//h264Preview_01_sub
      - "ffmpeg:reolink_doorbell_camera_sub#audio=opus" 
    backyard_camera:
      - rtsp://admin:PASSWORD@192.168.1.172//h265Preview_01_main
      - "ffmpeg:backyard_camera#audio=opus" 
    backyard_camera_sub:
      - rtsp://admin:PASSWORD@192.168.1.172//h264Preview_01_sub
      - "ffmpeg:backyard_camera_sub#audio=opus" 
    reolink_side_camera:
      - rtsp://admin:PASSWORD@192.168.1.71//h265Preview_01_main
      - "ffmpeg:reolink_side_camera#audio=opus" 
    reolink_side_camera_sub:
      - rtsp://admin:PASSWORD@192.168.1.71//h264Preview_01_sub
      - "ffmpeg:reolink_side_camera_sub#audio=opus" 

cameras:
  reolink_indoor_e1_zoom_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_indoor_e1_zoom_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_indoor_e1_zoom_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 960
      fps: 7
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
    record:
      enabled: True
  reolink_doorbell_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 960
      fps: 7
    objects:
      track:
        - person
        - dog
        - car
        - bird
        - cat
    snapshots:
      enabled: True
    record:
      enabled: True
    motion:
      mask:    
        - 412,27,834,37,840,0,414,0
        - 946,229,1010,292,1027,396,938,519,804,515,711,499,640,476,642,324,770,237,900,231
    zones:  
      porch:
        coordinates: 1280,960,1280,593,1162,580,1015,587,890,754,661,773,429,774,304,687,0,668,0,960
      sidewalk:
        coordinates: 742,648,432,650,412,675,485,690,555,685,624,687,684,687,796,672,912,653,920,617
      steps:
        coordinates: 411,773,658,787,882,755,689,696,613,709,498,707
  backyard_camera:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 2304
      height: 864
      fps: 7
    objects:
      track:
        - person
        - dog
        - bird
        - cat
    snapshots:
      enabled: True
    record:
      enabled: True
    motion:
     mask:    
      - 670,579,759,545,666,289,593,317
      - 925,27,1355,31,1356,0,927,0
  reolink_side_camera:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_side_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_side_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 2256
      height: 1256
      fps: 7
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
    record:
      enabled: True
```

### Relevant log output

```shell
None. go2rtc dashboard shows version 1.2.0
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a
