### ISSUE TITLE
Go2RTC  Templated Environment Variables 

### ISSUE THREAD

**Issue by craigcurtin-dev** [blakeblackshear/frigate#9384]
### Describe the problem you are having

Guys, am trying to follow best practices and not have passwords in my config file.

Works fine for Frigate - but does not work for Go2RTC

This seems to be this issue that is described here and marked as fixed

https://github.com/blakeblackshear/frigate/issues/5982

However i can not actually see what the Fixed solution is - nor do the docs seem to advise this.

I am currently using a complex password for the RTSP stream and hence have to use a URL encoder to add all the complex characters - this works fine on the RTSP stream in the GO2RTC section of the config file.

In my Cameras section for Frigate i am using environment Variables for the username and password 

How do i use these same variables from the Frigate camera config in the Go2RTC config ?

Craig

### Version

Starting Frigate (0.12.1-367d724)

### Frigate config file

```yaml
mqtt:
  host: 172.16.100.31
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 300

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tr"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

go2rtc:
  streams:
    driveway:
      - rtsp://Viewer:xxxx@172.16.101.155:554/cam/realmonitor?channel=1&subtype=0
      #- rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.155:554/cam/realmonitor?channel=1&subtype=0

    sidepath:
      - rtsp://Viewer:xxxx@172.16.101.154:554/cam/realmonitor?channel=1&subtype=0
          
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.155:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.155:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    detect:                 
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_score: 0.7
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 3
    record:
      enabled: True
      retain: 
        days: 60
        mode: all
      events:
        retain:
          default: 90
          mode: active_objects 
  sidepath:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.154:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.154:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    detect:                 
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_score: 0.7
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 60
        mode: motion
      events:
        retain:
          default: 90
          mode: active_objects 
    motion:
      mask:
        - 1353,0,1920,0,1920,554
        - 408,0,0,0,0,160,427,103    
  kitchenstairs:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.153:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.153:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp 
    detect:                 
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_score: 0.7
          threshold: 0.6
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 60
        mode: motion
      events:
        retain:
          default: 90
          mode: active_objects  
  frontpath:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.152:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.152:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp 
    detect:                 
      width: 1920
      height: 1080
      fps: 10
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_score: 0.6
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 28
        mode: motion
      events:
        retain:
          default: 60
          mode: active_objects     
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.151:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.151:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    detect:                 
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_score: 0.7
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 28
        mode: motion
      events:
        retain:
          default: 60
          mode: active_objects 
    
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.150:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@172.16.101.150:554/h264Preview_01_main
          roles:
            - record
            - rtmp
    detect:                 
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_score: 0.7
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 28
        mode: motion
      events:
        retain:
          default: 60
          mode: active_objects
    motion:
      mask:
        - 666,0,1247,0,1252,39,669,37
        - 1491,183,699,224,749,539,1639,533
detectors: 
  coral:
    type: edgetpu
    device: usb

logger:
  logs:
    frigate.record: debug
```

### Relevant log output

```shell
2024-01-19 14:23:19.259888923  [INFO] Preparing go2rtc config...
2024-01-19 14:23:19.462595714  [INFO] Starting go2rtc...
2024-01-19 14:23:19.504723643  14:23:19.504 INF go2rtc version 1.2.0 linux/amd64
2024-01-19 14:23:19.504930932  14:23:19.504 INF [api] listen addr=:1984
2024-01-19 14:23:19.505095269  14:23:19.505 INF [rtsp] listen addr=:8554
2024-01-19 14:23:19.505202126  14:23:19.505 INF [srtp] listen addr=:8443
2024-01-19 14:23:19.505325675  14:23:19.505 INF [webrtc] listen addr=:8555
2024-01-19 14:23:29.260283511  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
Not used under HA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
