### ISSUE TITLE
[Config Support]: person detection only in zone

### ISSUE THREAD

**Issue by ViezeVisNL** [blakeblackshear/frigate#9390]
### Describe the problem you are having

Hey!

My Reolink Doorbell POE is running fluently on Frigate now. But what I noticed is that the person detection happens even outside of the zone. And if I make a motion mask in the middle of the screen I am afraid the camera might not be detecting persons quick. I am using the entity 'camera.reolink_person'.

Can I set my config so only person detection happens in the zone only, instead of outside the zone? See the example here.

You can see a person here:
![image](https://github.com/blakeblackshear/frigate/assets/27589134/0fc04f9e-c210-4854-92f3-e73c4d113d7a)

You can see the motion- and zone masks here.
![image](https://github.com/blakeblackshear/frigate/assets/27589134/6be028ea-88d2-486d-b110-7421e8a3b5e4)

I thought with my config setting snapshots enabled only to the 'zone_voortuin' it should not trigger snapshots outside of this area. But I might misinterpreted that. See my config. I removed go2rtc, model, detector, mqtt part.

If you see any other strange things just let me know. Thnx !

### Version

0.12.1-367D724

### Frigate config file

```yaml
#Cameras
cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
#            - detect
        - path: rtsp://127.0.0.1:8554/reolink_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
    motion:
      mask:
        - 347,445,351,0,0,0,0,544
        - 1280,565,1280,0,942,87,958,454
        - 347,233,944,224,939,160,349,175
    zones:
      zone_voortuin:
        coordinates: 1280,720,1280,571,967,465,709,474,381,463,0,570,0,720
#default camera conf
objects:
  track:
    - person
  filters:
    person:
      threshold: 0.7

snapshots:
  enabled: True
  required_zones:
    - zone_voortuin
  retain:
    default: 14
    objects:
      person: 14

#record
record:
  enabled: True
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 14
```

### Relevant log output

```shell
//
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
you need to make the zone required for snapshots and recordings https://docs.frigate.video/configuration/zones#restricting-events-to-specific-zones

also using motion masks like that is discouraged and not how they are supposed to be used

**Comment by ViezeVisNL** [comment]
@NickM-27 I miscopied my config. It is listed.
The Motion Masks should only be used for the false-positive regions such as plants etc?

```
#Cameras
cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink
          input_args: preset-rtsp-restream
          roles:
            - record
#            - detect
        - path: rtsp://127.0.0.1:8554/reolink_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
    motion:
      mask:
        - 347,445,351,0,0,0,0,544
        - 1280,565,1280,0,942,87,958,454
        - 347,233,944,224,939,160,349,175
    zones:
      zone_voortuin:
        coordinates: 1280,720,1280,571,967,465,709,474,381,463,0,570,0,720

#default camera conf
objects:
  track:
    - person
  filters:
    person:
      threshold: 0.7

snapshots:
  enabled: True
  required_zones:
    - zone_voortuin
  retain:
    default: 14
    objects:
      person: 14

#record
record:
  enabled: True
  retain:
    days: 0
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 14
    required_zones:
      - zone_voortuin
```
