### ISSUE TITLE
Please help with docker-compose.yml[HW Accel Support]: 

### ISSUE THREAD

**Issue by customstudioyandexru** [blakeblackshear/frigate#9391]
### Describe the problem you are having

Hello! Please help with docker-compose.yml
I want to run Freegate with Nvidia hardware acceleration.
I installed NVIDIA in docker according to this article:
[push](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

Checked the installation according to this page.
[Push ](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html)
![photo_5280838083899675749_y](https://github.com/blakeblackshear/frigate/assets/113539114/0609ca64-0ca2-4a12-870e-56a9899402fd)

in Frigate.yaml specified:
```
ffmpeg:
  hwaccel_args: preset-nvidia-h264
```
after that, the cameras turned off.
I think I missed this step.
[push](https://docs.frigate.video/configuration/hardware_acceleration/)
![Screenshot+(1)](https://github.com/blakeblackshear/frigate/assets/113539114/6cfed15d-4491-4f04-8dd8-06e9733e548a)

when entering the command line:

```
nvidia-smi

```

![photo_5282870930575578586_y](https://github.com/blakeblackshear/frigate/assets/113539114/aa2c26ba-728c-42f9-afcb-c78f771711a4)

How do I create a docker-compose.yml to make hardware acceleration work? 
Can I do this using the Home Assistant Porteiner app?

### Version

 0.12.0

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.134
  user: ADMIN
  password: 123
  topic_prefix: frigate

# ffmpeg:
#   hwaccel_args: preset-nvidia-h264
  
# --------------DETECT-------------
detect:
  width: 1280
  height: 720
  fps: 15
  enabled: True
  stationary:
    interval: 0
    threshold: 50

# ----------OBJECTS--------------
objects:
  track:
    - person
    - car
    - cat
    - bird

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 1
    post_capture: 1
    objects:
      - person
      - car
      - cat
      - bird
    retain:
      default: 6
      mode: active_objects
      objects:
        person: 6
        car: 3
        cat: 6
        bird: 6

snapshots:
  enabled: true
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 475
  required_zones: []
  retain:
    default: 10
    objects:
      person: 10
      car: 10
      cat: 6
      bird: 6


birdseye:
  enabled: True
  mode: continuous
  


#---------CAMERAS-----------
cameras:
  masterskaya:
      ffmpeg:
        inputs:
          - path: rtsp://admin:123@192.168.1.62:554/user=admin_password=123&channel=0&stream=1.sdp
            roles:
              - detect
              - record

      rtmp:
        enabled: False
```

### docker-compose file or Docker CLI command

```yaml
I don't understand Docker well.
```

### Relevant log output

```shell
2024-01-19 06:56:20.947942033  [INFO] Starting Frigate...
2024-01-19 06:56:24.443683182  [2024-01-19 09:56:24] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2024-01-19 06:56:24.484028532  [2024-01-19 09:56:24] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-01-19 06:56:24.486171085  [2024-01-19 09:56:24] peewee_migrate                 INFO    : Starting migrations
2024-01-19 06:56:24.491559815  [2024-01-19 09:56:24] peewee_migrate                 INFO    : There is nothing to migrate
2024-01-19 06:56:24.508589993  [2024-01-19 09:56:24] detector.cpu                   INFO    : Starting detection process: 298
2024-01-19 06:56:24.683640653  [2024-01-19 09:56:24] frigate.app                    INFO    : Output process started: 300
2024-01-19 06:56:24.684760480  [2024-01-19 09:56:24] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
```

### FFprobe output from your camera

```shell
-=-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

hikvision

### Any other information that may be helpful

I don't understand Docker well.
