### ISSUE TITLE
[Config Support]: Accessing go2rtc streams in 0.13

### ISSUE THREAD

**Issue by aegjoyce** [blakeblackshear/frigate#9414]
### Describe the problem you are having

Prior to (I think) 0.13-b7 I had Frigate's go2rtc integration configured to convert one of my streams to MJPEG so I could use it with my 3D printer monitoring software (Mainsail).

Since b7 access to the go2rtc dashboard has been removed and subsequently my stream address doesn't work - is there now a new way to achieve this?

### Version

0.13 rc-1

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.200
  user: xxxxxxx
  password: xxxxxxxxx

cameras:
  Front_Garden_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:40105/612cf176aaa0678e
          roles:
            - record
        - path: rtsp://192.168.1.35:40105/2c6ae32ef1179b08
          roles:
            - detect
    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 28
          mode: active_objects
    detect:
      width: 896
      height: 672
      fps: 5
    motion:
      mask:
        - 671,672,532,289,436,185,413,0,140,0,150,186,0,237,0,672
        - 896,453,852,385,656,122,461,134,616,235,675,352,797,551
    zones:
      front_path:
        coordinates: 513,263,689,672,829,672,613,250,519,179,437,196
  Back_Garden_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:42001/3f6ebc63aab11dd3
          roles:
            - record
        - path: rtsp://192.168.1.35:42001/39f5f8ed71a16863
          roles:
            - detect
    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 28
          mode: active_objects
    detect:
      width: 896
      height: 672
      fps: 5
    motion:
      mask:
        - 377,151,180,268,122,359,0,445,0,193,148,127
    zones:
      back_garden_door:
        coordinates: 593,291,676,313,712,247,654,233
  Front_Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:32911/a0e7dc9612fbe014
          roles:
            - record
        - path: rtsp://192.168.1.35:32911/a86444eae835f8eb
          roles:
            - detect
    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 28
          mode: active_objects
    detect:
      width: 896
      height: 672
      fps: 5
    motion:
      mask:
        - 426,0,212,114,184,250,252,246,298,187,366,225,336,304,409,375,497,297,528,191,896,246,896,0
    zones:
      front_door:
        coordinates: 661,672,684,441,571,437,252,672
  3D_Printer:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.35:34263/9fcf018353a4bea0
    record:
      enabled: False
    detect:
      enabled: False

go2rtc:
  streams:
    3D_Printer:
      rtsp://192.168.1.35:34263/9fcf018353a4bea0

objects:
  track:
    - person
    - cat
    - dog

birdseye:
  enabled: False

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant log output

```shell
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)
