### ISSUE TITLE
[HW Accel Support]: Hardware Acceleration with NVIDIA not working. No such file or directory: 'nvidia-smi' 

### ISSUE THREAD

**Issue by ropelletier** [blakeblackshear/frigate#9416]
### Describe the problem you are having

I am getting errors when trying to run hardware accelaeration using go2rtc. I have a mediamtx container that I have been experimenting with and NVIDIA hardware decoding works without any problem in that container. Here is the result of sample workload:

```
# sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
Mon Jan 22 14:57:52 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 ...    Off | 00000000:24:00.0 Off |                  N/A |
| 48%   49C    P2              42W / 125W |    415MiB /  6144MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

### Version

0.12.1-367D724

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  #hwaccel_args: preset-intel-qsv-h264
go2rtc:
  streams:
    test:
      - rtsp://10.30.100.77:8554/test
      - "ffmpeg:test#video=h264#hardware#width=1280#height=640"
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "9554:8554" # RTSP feeds
      - "9555:8555/tcp" # WebRTC over tcp
      - "9555:8555/udp" # WebRTC over udp
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```

### Relevant log output

```shell
2024-01-22 09:54:16.729538494  future: <Task finished name='Task-2' coro=<set_gpu_stats() done, defined at /opt/frigate/frigate/stats.py:120> exception=FileNotFoundError(2, 'No such file or directory')>
2024-01-22 09:54:16.729549790  Traceback (most recent call last):
2024-01-22 09:54:16.729554816    File "/opt/frigate/frigate/stats.py", line 152, in set_gpu_stats
2024-01-22 09:54:16.729560736      nvidia_usage = get_nvidia_gpu_stats()
2024-01-22 09:54:16.729565246    File "/opt/frigate/frigate/util.py", line 940, in get_nvidia_gpu_stats
2024-01-22 09:54:16.729592880      p = sp.run(
2024-01-22 09:54:16.729597579    File "/usr/lib/python3.9/subprocess.py", line 505, in run
2024-01-22 09:54:16.729602075      with Popen(*popenargs, **kwargs) as process:
2024-01-22 09:54:16.729605815    File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
2024-01-22 09:54:16.729641582      self._execute_child(args, executable, preexec_fn, close_fds,
2024-01-22 09:54:16.729645823    File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
2024-01-22 09:54:16.729672373      raise child_exception_type(errno_num, err_msg, err_filename)
2024-01-22 09:54:16.729676665  FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'
```

### FFprobe output from your camera

```shell
ffprobe version N-113385-g6c4388b468 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --enable-gpl --enable-gnutls --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      58. 36.101 / 58. 36.101
  libavcodec     60. 37.100 / 60. 37.100
  libavformat    60. 20.100 / 60. 20.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Meraki MX22

**Comment by NickM-27** [comment]
what is your docker compose

**Comment by ropelletier** [comment]
@NickM-27 Unless I am misunderstanding, it is above, but here it is again:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "9554:8554" # RTSP feeds
      - "9555:8555/tcp" # WebRTC over tcp
      - "9555:8555/udp" # WebRTC over udp
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```
