### ISSUE TITLE
[Support]: USB Coral TPU not detected when Frigate installed in unprivileged LXC container

### ISSUE THREAD

**Issue by dme11** [blakeblackshear/frigate#9436]
### Describe the problem you are having

Hello,
I've installed Frigate in unprivileged LXC container by following [this ](https://blog.sysadminpanda.co.uk/frigate-proxmox-lxc-coral-11th-gen-hw-accel/)instructions.  Installation went well, Frigate starts but it doesn't detect Coral TPU. I've checked various forums related to TPU detection problem and nothing I've tried didn't work. Also, neither [webcoral ](https://github.com/google-coral/webcoral)and [parrot](https://coral.ai/docs/accelerator/get-started/) examples flash the FW to TPU from unprivileged container (Ubuntu v20.04 with default Python v3.8.10), so it' no surprise that Frigate can't detect and flash the FW to TPU.

I assume the issue is related to USB port permissions since I've managed to get Coral TPU detected in Frigate when installed in privileged LXC container.

I'd appreciate any guidance helping to solve this problem.

Regards,

Dusan

### Version

0.12.1-367D724

### Frigate config file

```yaml
database:
    path: /db/frigate.db
mqtt:
    enabled: false
detectors:
    coral:
        type: edgetpu
        device: usb
ffmpeg:
    output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    hwaccel_args: # This is the section for the H/W Accelaration, you will need to figure out what settings you need to enable - https://docs.frigate.video/configuration/hardware_acceleration
        -c:v h264_qsv
       # - -hwaccel
       # - vaapi
       # - -hwaccel_device
       # - /dev/dri/renderD128
       # - -hwaccel_output_format
       # - yuv420p
objects: # Object to detect - https://docs.frigate.video/configuration/objects
    track:
        - person
        - cat
        - dog
    filters:
        person:
            min_area: 5000
            max_area: 8000000
            threshold: 0.80
record: # how long to record before and after motion
    events:
        pre_capture: 7
        post_capture: 10
cameras:
    test: # <------ Name the camera
        ffmpeg:
            inputs:
                - path: rtsp://user:password@192.168.2.236:554/cam/realmonitor?channel=1&subtype=1 # Update with your camera info (Normally the lower res stream, 1280*720 would be a good detection res)
                  roles:
                    - detect
                    - rtmp
                - path: rtsp://user:password@192.168.2.236:554/cam/realmonitor?channel=1&subtype=0 # Update with your camera info (Normally the higher res stream, used for actual recording)
                  roles:
                    - record
                   # - detect
                    #- rtmp
        rtmp:
            enabled: False # <-- RTMP should be disabled if your stream is not H264
        detect:
            width: 704 # <---- update for your camera's resolution
            height: 576 # <---- update for your camera's resolution
            #width: 2688
            #height: 1520
        record: # what you want Frigate to record
            enabled: True
           # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
           #     days: 1
           #     mode: all
            events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
                retain:
                    mode: active_objects
                    default: 10
        snapshots:
            enabled: True
            retain:
                default: 10
```

### Relevant log output

```shell
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started

2024-01-25 08:14:33.630410451  [INFO] Starting go2rtc healthcheck service...
2024-01-25 08:14:49.561553598  [2024-01-25 08:14:24] detector.coral                 INFO    : Starting detection process: 282
2024-01-25 08:14:49.561693860  [2024-01-25 08:14:24] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-01-25 08:14:49.562216707  [2024-01-25 08:14:49] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2024-01-25 08:14:49.562219535  Process detector:coral:
2024-01-25 08:14:49.563025128  Traceback (most recent call last):
2024-01-25 08:14:49.563037569    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2024-01-25 08:14:49.563038847      delegate = Delegate(library, options)
2024-01-25 08:14:49.563040211    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2024-01-25 08:14:49.563042270      raise ValueError(capture.message)
2024-01-25 08:14:49.563049784  ValueError
2024-01-25 08:14:49.563050750
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":576,"width":704},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1620,"width":2880},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW1530S

### Any other information that may be helpful

Below some more information about the current configuration.

Host info
Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.5.11-7-pve
Architecture: x86-64
Hardware Vendor: Protectli
Hardware Model: FW6
Firmware Version: coreboot 4.12, Dasharo 1.0.14
Proxmox PVE version: pve-manager/8.1.4/ec5affc9e41f1d79 (running kernel: 6.5.11-7-pve)

Host USB info
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

LXC container USB info
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

LXC container config
arch: amd64
cores: 2
features: nesting=1
hostname: frigate
memory: 4096
mp0: /mnt/lxc_shares/frigate_network_storage/,mp=/opt/frigate/media
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=BC:24:11:4A:28:D0,ip=dhcp,type=veth
onboot: 1
ostype: ubuntu
rootfs: local-lvm:vm-100-disk-0,size=20G
swap: 512
unprivileged: 1
usb0: host=1a6e:089a,usb3=1
usb1: host=18d1:9302,usb3=1
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/bus/usb/002 dev/bus/usb/002 none bind,optional,create=dir
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0, 0
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir

Docker compose file
version: "3.9"
services:
frigate:
container_name: frigate
privileged: true # this may not be necessary for all setups
restart: unless-stopped
image: ghcr.io/blakeblackshear/frigate:stable
shm_size: "128mb" # update for your cameras based on calculation above
devices:
- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
volumes:
- /etc/localtime:/etc/localtime:ro
- /opt/frigate/config:/config:rw
- /opt/frigate/media:/media/frigate
- /opt/frigate/storage:/db
- type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
target: /tmp/cache
tmpfs:
size: 1000000000
ports:
- "5000:5000"
- "8554:8554" # RTSP feeds
- "8555:8555/tcp" # WebRTC over tcp
- "8555:8555/udp" # WebRTC over udp
environment:
FRIGATE_RTSP_PASSWORD: "password"
