### ISSUE TITLE
[Config Support]: Reolink RLC822-A RTSP Configuration Support

### ISSUE THREAD

**Issue by roflware** [blakeblackshear/frigate#9441]
### Describe the problem you are having

I am unable to load any RTSP stream successfully in Frigate. RTSP streams work in VLC. RTMP for the low quality stream works in Frigate, however, the higher quality "channel0_main" is unfortunately unreachable for some reason via RTMP.  Regardless of using the hwaccel, input, or output args or not, I get the same result with the relevant log output below.

### Version

0.12.1-367D724

### Frigate config file

```yaml
LivingRoom:
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-generic
      output_args:
        detect: -threads 2 -f rawvideo -pix_fmt yuv420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://username:password@192.168.x.x:554/Preview_01_main
          roles:
            - detect
            - record
            - rtmp
```

### Relevant log output

```shell
LivingRoom: Unable to read frames from ffmpeg process.
LivingRoom: ffmpeg process is not running. exiting capture thread...
Ffmpeg process crashed unexpectedly for LivingRoom.
The following ffmpeg logs include the last 100 lines prior to exit.
Option rtsp_transport not found.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2
