### ISSUE TITLE
[Config Support]: using /api/frigate/notifications

### ISSUE THREAD

**Issue by ViezeVisNL** [blakeblackshear/frigate#9442]
### Describe the problem you are having

Hey,

I was using the "http://homeassistant.local:5000/api/reolink/person/snapshot.jpg" URL for sending the latest snapshot when my doorbell button triggered. I did this using a automation which changed the "Visitor State" from Off to On. If it changed, it sent me an image via the automation Action yaml underneath here which would send the last person snapshot as 'rich text message' to iOS. This works flawless, but because this is a LOCAL URL it didnt work out outside of my home.

```
image: http://homeassistant.local:5000/api/reolink/person/snapshot.jpg
push:
  sound:
    name: default
    critical: 1
    volume: 1
```

So I deciced to change it via a little more complex one. This one would receive the MQTT message, test the condition if the visitor state changed and then sends me an image based on the /api/frigate/notifications api. And looks like this:

```
alias: Doorbell - Notify when the doorbell's pressed
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.reolink_video_doorbell_poe_visitor
        state: "on"
action:
  - service: notify.all_devices
    data:
      data:
        image: >-
          https://mypublicwebsite.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        push:
          sound:
            name: default
            critical: 1
            volume: 1
      title: Deurbel
      message: Er is op de deurbel gedrukt.
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
mode: single
```

Now theres an issue. It seems that mqtt is firing several messages/events when the doorbell state is on. Which causes to spam allot of critical notifications. So I built in a delay, but this is not the most clean solution I guess. Basically, my question is: is there an easy way of getting the LATEST image via a more easier url like my first setup? Something like

https://mypublicwebsite.com/api/frigate/notifications/reolink/person/thumbnail.jpg

the http api seems to be local only and for the latest snapshot I couldnt figure out yet.
https://docs.frigate.video/integrations/api
https://docs.frigate.video/integrations/mqtt

### Version

0.12.1-367D724

### Frigate config file

```yaml
//
```

### Relevant log output

```shell
//
```

### Frigate stats

```json
//
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
No, this is not possible because it would allow users to access the latest camera image without authentication (or an auth token could be required but that is much more complicated to setup). You can edit your automation to only send notifications at certain times like when an object enters a zone for the first time

**Comment by ViezeVisNL** [comment]
> No, this is not possible because it would allow users to access the latest camera image without authentication (or an auth token could be required but that is much more complicated to setup). You can edit your automation to only send notifications at certain times like when an object enters a zone for the first time

You mean by adding [this](https://docs.frigate.video/guides/ha_notifications/#conditions)?
```
condition:
  - "{{ trigger.payload_json['after']['label'] == 'person' }}"
  - "{{ 'yard' in trigger.payload_json['after']['entered_zones'] }}"
```

For example. If a person enters the zone it takes up to 3-5 seconds before the person actually presses the doorbell button. If I add this condition to it, will it get the snapshot image when the person entered the zone, no matter how long it takes before the person presses the doorbell button?

**Comment by NickM-27** [comment]
that would still trigger multiple times, 

this is what i have

```yaml
  - alias: new event or an object has not previously entered a zone
    condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['type'] == 'new' }}"
      - condition: template
        value_template: "{{ before_zones | length == 0 }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ [\"street\"] | select(\"in\", before_zones) | list | length == 1 }}"
          - condition: template
            value_template: "{{ stationary == false }}"
  - alias: Object is in primary zone
    condition: or
    conditions:
      - alias: Object is in Driveway, SIde Yard, or Front Yard
        condition: template
        value_template: >-
          {{ ["driveway", "side_yard", "front_yard"] |
          select("in", after_zones) | list | length > 0 }}
```
