### ISSUE TITLE
[Config Support]: camera shows no frames received on camera page but works

### ISSUE THREAD

**Issue by lygris** [blakeblackshear/frigate#9449]
### Describe the problem you are having

On the cameras page my wyze doorbell shows no frames received but when clicking into it, it works fine. It also seems like it isn't detecting or triggering birdseye.
![image](https://github.com/blakeblackshear/frigate/assets/22260038/351e8055-6e0a-43c3-846d-5ab460904bbd)

### Version

0.13.0 rc1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://10.0.6.43:5000/api/config/schema
mqtt: 
  host: *****
  user: *****
  password: *****
detectors:
  coral:
    type: edgetpu
    device: pci
birdseye:
  enabled: True
  mode: objects
  quality: 8
ffmpeg:
  # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # output_args:
  #   record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  #   rtmp: -c copy -f flv
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-intel-qsv-h264 #preset-vaapi #preset-intel-qsv-h264
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 5 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 100
  contour_area: 10
audio:
  # Optional: Enable audio events (default: shown below)
  enabled: True
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - yell
    - gunshot
go2rtc:
  streams:
    Front-Door:
      - rtsp://*****:*****@*****:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    X1C:
      - rtsps://*****:*****@*****:322/streaming/live/1
    Garage:
      - rtsp://*****/live0
    Garage-Doorbell:
      - ffmpeg:rtsp://*****:8554/garage-doorbell#video=h264#rotate=90#audio=opus
    Laundry-Room:
      - rtsp://*****/live0
    # Entryway:
    #   - rtsp://*****/live0
    Kitchen:
      - rtsp://*****/live0
    Backyard:
      - rtsp://*****:*****@*****/cam/realmonitor?channel=1&subtype=0
    Backyard-2:
      - rtsp://*****:*****@*****:80/videoMain
    Driveway:
      - rtsp://*****:*****@*****/cam/realmonitor?channel=1&subtype=0
cameras:
  X1C:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/X1C # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    detect:
      enabled: False
    audio:
      enabled: False
    record:
      enabled: False
    snapshots:
      enabled: False  
    # objects:
    #   track:
    #     - person
    #     - dog      
    # motion:
    #   mask:
    #     # - 1920,0,1920,63,1378,55,1372,0
    #     - 1920,0,1920,1080,0,1080,0,0
  Garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      track:
        - person
        - car
        - dog
    motion:
      mask:
        - 1920,0,1920,63,1378,55,1372,0
  Garage-Doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage-Doorbell # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      filters:
       car:
        mask:
          - 975,572,748,574,743,619,984,615
          - 0,344,0,750,688,648,675,498
      track:
        - person
        - car
        - dog
    motion:
      mask:
        - 1920,1044,1920,1080,1167,1080,1165,1046
        - 1920,0,1920,497,679,591,680,648,0,758,0,373,0,0
        # - 1920,1043,1920,1080,1167,1080,1173,1046,1487,1045
        # - 0,0,1920,0,1920,559,1137,529,679,566,679,642,0,755,0,1080
  Front-Door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Door # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      filters:
        person:
          threshold: 0.8
          mask:
            - 1920,0,1920,795,1574,749,1296,621,793,621,534,612,552,685,0,818,0,0
        car:
          threshold: 0.8
          mask:
            - 883,622,889,539,654,536,648,611
      track:
        - person
        - dog
    motion:
      mask:
        - 1920,0,1920,795,1574,749,1296,621,793,621,534,612,552,685,0,818,0,0
  Laundry-Room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Laundry-Room # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1920,0,1920,63,1378,55,1372,0
  # Entryway:
  #   ffmpeg:
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/Entryway # <--- the name here must match the name of the camera in restream
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - detect
  #   objects:
  #     track:
  #       - person
  #       - dog
  #   motion:
  #     mask:
  #       - 1920,0,1920,63,1378,55,1372,0
  Kitchen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1920,0,1920,63,1378,55,1372,0
  # Bedroom:
  #   ffmpeg:
  #     input_args:
  #       - -c:v
  #       - h264_cuvid
  #       - -c:a
  #       - aac
  #     inputs:
  #       - path: rtsp://10.0.4.167/live0
  #         roles:
  #           - detect
  #           - rtmp
  #           - record
  #   detect:
  #     enabled: True
  #     max_disappeared: 45
  #   objects:
  #     track:
  #       - person
  #       - dog
  #   record:
  #     enabled: True
  #   motion:
  #     mask:
  #       - 1244,14,1244,35,920,33,920,10
  Backyard:
    ffmpeg:
      # hwaccel_args: preset-intel-qsv-h265
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1920,0,0,0,0,303,590,119,1471,83,1920,341
        - 1920,1080,1920,844,1765,889,1619,1080
        - 745,969,837,1080,1000,194,888,0,517,0
  Backyard-2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard-2 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,207,0,0,0,0,462,0,454,46
  Driveway:
    ffmpeg:
      # hwaccel_args: preset-intel-qsv-h265
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    objects:
      filters:
        car:
          threshold: 0.8
          mask:
            - 749,0,1920,0,1920,300,1075,231,792,243,757,285,649,347,0,879,0,0
        person:
          threshold: 0.8
          mask:
            - 1920,0,1920,316,1422,257,1430,0
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 857,0,622,0,0,0,0,854,493,442,814,234,1499,245,1920,311,1920,0
    zones:
      parked_cars:
        coordinates: 0,1080,1381,1080,1062,285,742,284,743,216,598,0,0,0
        objects:
          - person
          - dog
      everything_else:
        coordinates: 1920,0,1920,1080,1370,1080,1075,297,755,269,710,0
        objects:
          - car
          - motorcycle
          - dog
          - person
snapshots:
  enabled: true
record:
  enabled: true
  retain:
    days: 3
  events:
    pre_capture: 10
    post_capture: 20
    retain:
      mode: active_objects
      default: 3
      objects:
        person: 7
        dog: 3
        car: 3
        motorcycle: 3
        bark: 2
```

### Relevant log output

```shell
2024-01-26 08:54:37.817290799  [2024-01-26 08:54:37] audio.Garage-Doorbell          ERROR   : ffmpeg process is not running, restarting...
2024-01-26 08:54:38.322039565  [2024-01-26 08:54:38] watchdog.Garage-Doorbell       ERROR   : Ffmpeg process crashed unexpectedly for Garage-Doorbell.
2024-01-26 08:54:38.322116268  [2024-01-26 08:54:38] watchdog.Garage-Doorbell       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-01-26 08:54:38.322175548  [2024-01-26 08:54:38] ffmpeg.Garage-Doorbell.detect  ERROR   : [segment @ 0x556ddddefb00] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2024-01-26 08:54:38.322222140  [2024-01-26 08:54:38] ffmpeg.Garage-Doorbell.detect  ERROR   : [segment @ 0x556ddddefb00] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
2024-01-26 08:54:38.322269431  [2024-01-26 08:54:38] ffmpeg.Garage-Doorbell.detect  ERROR   : [h264_qsv @ 0x556ddddedf00] video_get_buffer: image parameters invalid
2024-01-26 08:54:38.322315082  [2024-01-26 08:54:38] ffmpeg.Garage-Doorbell.detect  ERROR   : [h264_qsv @ 0x556ddddedf00] get_buffer() failed
2024-01-26 08:54:38.322356999  [2024-01-26 08:54:38] ffmpeg.Garage-Doorbell.detect  ERROR   : Error while decoding stream #0:0: Invalid argument
2024-01-26 08:54:38.322401449  [2024-01-26 08:54:38] ffmpeg.Garage-Doorbell.detect  ERROR   : Finishing stream 1:0 without any data written to it.
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

M.2
