### ISSUE TITLE
[Config Support]: Stationary Object detection stops after a few seconds

### ISSUE THREAD

**Issue by Joeviocoe** [blakeblackshear/frigate#9450]
### Describe the problem you are having

Not sure if this is the expected behavior or not, as the documentation seems to be focused on either avoiding stationary objects or tuning stationary object for use outdoors on a driveway.

The issue I am having is in an enclosed two-car garage where no motion will be detected all day.

When viewing the debug video, when there is motion (triggered manually or toggling contrast switch in HA), I can see detection of the "car" object.  The bounding boxes bounce around a bit as expected.  After motion is no longer detected, the bounding box (blue) holds steady for about 3-5 seconds and then disappears.  The HA sensors for object counts go to 0.

 I have tried many different values and combinations of the following settings:
```
max_disappeared:
stationary:
  interval:
  threshold:
```
They don't seem to change the behavior at all.

The posted config is under the specific garage camera.

### Version

0.13.0-rc1

### Frigate config file

```yaml
detect:
      width: 704
      height: 480
      fps: 5
      max_disappeared: 2500
      stationary:
        interval: 10
    motion:
      mask: 143,2,230,0,228,48,140,51
    zones:
      garage:
        coordinates: 704,480,704,0,0,0,0,480
      garage_left:
        coordinates: 704,0,704,480,66,0
      garage_right:
        coordinates: 466,480,0,480,0,0
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 60
    objects:
      track:
      - person
      - car
      filters:
        car:
          min_score: 0.35
```

### Relevant log output

```shell
no logs relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2
