### ISSUE TITLE
[Support]: HA Android App Slow Loading of Clips Behind Traefik Reverse Proxy and HA Frigate Proxy

### ISSUE THREAD

**Issue by hevel86** [blakeblackshear/frigate#9451]
### Describe the problem you are having

On my Pixel 8 Pro and my wife's Pixel 7A, loading clips is extremely slow when viewing through the Home Assistant app.
- Frigate and Home Assistant are on separate servers.
  - All servers are wired
- I am running Frigate Proxy inside Home Assistant
- Everything works, but it takes about 20+ seconds to load clips from the Event Viewer inside the Home Assistant app
- When running the standalone Frigate Android app, the clips take less than 3 seconds to load
- There is no difference when the events storage is running off a single SSD disk or a RAIDZ6 HDD pool
- When viewing from a web browser, the time is as expected, less than 3 seconds
- I have not tested from my iPad

### Version

Frigate v0.12.1-367d724, HA Frigate Proxy 1.4

### Frigate config file

```yaml
mqtt:
  host: redacted
  port: 1883
  user: redacted
  password: redacted

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

go2rtc:
  streams:
    office:
    # Use 8556 for rtsp port in wyze_bridge
      - rtsp://camera_ip:8556/office-cam
      #"ffmpeg:office#audio=aac"
      #- "ffmpeg:office#audio=opus"
    doorbell:
      - ffmpeg:rtsp://admin:redacted@cam_subnet.109:554/cam/realmonitor?channel=1&subtype=0#video=h264#audio=copy#hardware=nvenc
      #- ffmpeg:rtsp://admin:redacted@cam_subnet.109:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:doorbell#audio=opus"
  webrtc:
    candidates:
      - frigate_ip:8555
      - stun:8555
    
# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous

cameras:
  office:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        #- path: rtsp://camera_ip:8554/office-cam
        - path: rtsp://127.0.0.1:8554/office
          #input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      #fps: 5 #detection rate, not camera fps
      
    objects:
      track:
        - person

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10

    record:
      enabled: true
      events:
        objects:
          - person
        retain:
          default: 10

  doorbell:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        #- path: rtsp://admin:redacted@cam_subnet.109:554/cam/realmonitor?channel=1&subtype=0
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
            - record

    motion:
      mask:
        - 2560,1920,2560,0,1682,0,1578,1920

    zones:
      front_porch:
        coordinates: 509,1917,434,1728,1137,1364,1766,1405,1720,1920
        objects:
          - person
      driveway:
        coordinates: 1229,1140,1630,1186,1311,1254,424,1671,341,1292
        objects:
          - person
#          - car
          - dog
          - cat
      culdesac:
        coordinates: 1718,1068,1196,1050,1194,1137,1409,1170,1713,1180
        objects:
          - person
          - bus

    detect:
      width: 2560
      height: 1920
#      fps: 5 #detection rate, not camera fps

      
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bus

      filters:
        car:
          mask:
            - 1119,1149,1114,945,1114,631,453,259,356,655,357,1156

    snapshots:
      enabled: true
      required_zones:
        - driveway
        - front_porch
      timestamp: false
      bounding_box: true
      retain:
        default: 10

    record:
      enabled: true
      events:
        required_zones:
          - driveway
          - front_porch
        objects:
          - person
        retain:
          default: 10


detectors:
  coral_pci:
    type: edgetpu
    device: pci

  #CPU Detector
#  cpu1:
#    type: cpu
#    num_threads: 16
```

### Relevant log output

```shell
2024-01-26 17:33:47.920220544  [INFO] Starting Frigate...
2024-01-26 17:33:49.974125129  [2024-01-26 17:33:49] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2024-01-26 17:33:50.031645002  [2024-01-26 17:33:50] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-01-26 17:33:50.031757572  [2024-01-26 17:33:50] peewee_migrate                 INFO    : Starting migrations
2024-01-26 17:33:50.037681949  [2024-01-26 17:33:50] peewee_migrate                 INFO    : There is nothing to migrate
2024-01-26 17:33:50.053034917  [2024-01-26 17:33:50] frigate.comms.dispatcher       ERROR   : Received invalid set command: office/detect/set
2024-01-26 17:33:50.099479688  [2024-01-26 17:33:50] frigate.app                    INFO    : Output process started: 724
2024-01-26 17:33:50.112873112  [2024-01-26 17:33:50] detector.coral_pci             INFO    : Starting detection process: 721
2024-01-26 17:33:50.127858674  [2024-01-26 17:33:50] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2024-01-26 17:33:50.127865507  [2024-01-26 17:33:50] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-01-26 17:33:50.136511770  [2024-01-26 17:33:50] frigate.app                    INFO    : Camera processor started for office: 729
2024-01-26 17:33:50.136520195  [2024-01-26 17:33:50] frigate.app                    INFO    : Camera processor started for doorbell: 741
2024-01-26 17:33:50.138313068  [2024-01-26 17:33:50] frigate.app                    INFO    : Capture process started for office: 742
2024-01-26 17:33:50.151507650  [2024-01-26 17:33:50] frigate.app                    INFO    : Capture process started for doorbell: 746
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
^[[AInput #0, rtsp, from 'rtsp://admin:redacted@camera_ip':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.140000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "17": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "32": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "41": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "42": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "80": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "81": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "82": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "89": {
      "cpu": "1.0",
      "mem": "0.0"
    },
    "94": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "112": {
      "cpu": "4.0",
      "mem": "0.4"
    },
    "118": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "134": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "135": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "136": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "139": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "150": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "171": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "196": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "221": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "241": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "263": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "294": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "331": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "369": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "404": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "437": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "468": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "714": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "720": {
      "cpu": "0.3",
      "mem": "0.0"
    },
    "721": {
      "cpu": "1.3",
      "mem": "0.2"
    },
    "723": {
      "cpu": "1.0",
      "mem": "0.2"
    },
    "727": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "728": {
      "cpu": "0.3",
      "mem": "0.2"
    },
    "731": {
      "cpu": "11.6",
      "mem": "0.2"
    },
    "742": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "743": {
      "cpu": "2.7",
      "mem": "0.2"
    },
    "746": {
      "cpu": "6.0",
      "mem": "0.2"
    },
    "749": {
      "cpu": "3.0",
      "mem": "0.3"
    },
    "751": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "752": {
      "cpu": "8.0",
      "mem": "0.4"
    },
    "759": {
      "cpu": "112.0",
      "mem": "0.3"
    },
    "1293": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1306": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1312": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "6.1"
    },
    "MiB": {
      "cpu": "12390.6",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "0"
    },
    "top": {
      "cpu": "users,",
      "mem": "load"
    }
  },
  "detection_fps": 1,
  "detectors": {
    "coral_pci": {
      "detection_start": 0,
      "inference_speed": 7.04,
      "pid": 721
    }
  },
  "doorbell": {
    "camera_fps": 5,
    "capture_pid": 746,
    "detection_enabled": 1,
    "detection_fps": 1,
    "ffmpeg_pid": 752,
    "pid": 731,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "gpu_usages": {
    "Quadro P2000": {
      "gpu": "1 %",
      "mem": "7.0 %"
    }
  },
  "office": {
    "camera_fps": 5,
    "capture_pid": 743,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 749,
    "pid": 728,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "service": {
    "last_updated": 1706289925,
    "latest_version": "0.12.1",
    "storage": {
      "/dev/shm": {
        "free": 1062.2,
        "mount_type": "tmpfs",
        "total": 1073.7,
        "used": 11.6
      },
      "/media/frigate/clips": {
        "free": 129313.9,
        "mount_type": "zfs",
        "total": 171673.4,
        "used": 42359.5
      },
      "/media/frigate/recordings": {
        "free": 129313.9,
        "mount_type": "zfs",
        "total": 171673.4,
        "used": 42359.5
      },
      "/tmp/cache": {
        "free": 106708.9,
        "mount_type": "overlay",
        "total": 250374.1,
        "used": 130872.4
      }
    },
    "temperatures": {
      "apex_0": 39.05
    },
    "uptime": 299,
    "version": "0.12.1-367d724"
  }
}
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Amcrest AD410

### Any other information that may be helpful

Frigate Docker Compose:
```yaml
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1g"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /hdd_zpool/frigate/config/frigate.yml:/config/config.yml:ro
      - /mnt/ssd_zpool0/frigate/storage:/media/frigate
    devices:
      # Coral
      - /dev/apex_0:/dev/apex_0
      # Nvidia
      - /dev:/dev
      - /dev/dri:/dev/dri
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    ports:
      - "5002:5000"
      - "8554:8554" #RTSP feeds
      - "8555:8555/tcp" #WebRTC TPC
      - "8555:8555/udp" #WebRTC UDP
      #- "8890:8890" #stund
    environment:
      - FRIGATE_MQTT_PASSWORD=$FRIGATE_MQTT_PASSWORD
      - FRIGATE_MQTT_USER=$FRIGATE_MQTT_USER
      - FRIGATE_RTSP_USER=$FRIGATE_RTSP_USER
      - PLUS_API_KEY=$PLUS_API_KEY
      - FRIGATE_RTSP_PASSWORD=$FRIGATE_RTSP_PASSWORD
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
