### ISSUE TITLE
[Detector Support]: which Coral TPU for my Intel Nuc

### ISSUE THREAD

**Issue by UeT-Fire** [blakeblackshear/frigate#9456]
### Describe the problem you are having

Hello everyone,

I have an Intel NUC13ANKi50WC.

As far as I know, this has 3 different M.2. Interfaces.

PCIe x4 Gen 4: M.2 22x80 (key M)
PCIe x1 Gen 3: M.2 22x42 (key B)
PCIe x1: M.2 22x30 (key E)

In the top interface is my Nvme.

Can I use one of the other two for an internal Google Coral TPU or does it have to be the USB stick?

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.88
  user: mqtt-user
  password: ****
  
detectors:
  cpu1:
    type: cpu
    num_threads: 3
    
database:
  path: /media/frigate/frigate.db    
    

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy   

go2rtc:
  streams:
    doorbell_sub:
      - "ffmpeg:http://192.168.178.84//flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus"

  webrtc:
    candidates:
      - stun:8555
    
cameras:
  Doorbell:
    ffmpeg:      
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy&audio=aac
          roles:
            - detect
        - path: rtsp://admin:password@192.168.178.81:554/h264Preview_01_main
          roles:
            - record   
            
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

    objects:
      track:
        - person
      
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 10
          mode: active_objects
          
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
```

### docker-compose file or Docker CLI command

```yaml
No
```

### Relevant log output

```shell
No
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2
