### ISSUE TITLE
[Support]: Birdseye green screen/scanning lines 

### ISSUE THREAD

**Issue by singhkays** [blakeblackshear/frigate#9458]
### Describe the problem you are having

I'm seeing some strange green scan lines when changing the Birdseye resolution from 1280x720. I'm trying to get the Birdseye to be taller rather than wider so it fits better on a Home assistant dashboard. 

Here's how the Birdseye appears

https://github.com/blakeblackshear/frigate/assets/6164178/ee385006-c31c-47f7-817c-f094147212fc

<img width="371" alt="image" src="https://github.com/blakeblackshear/frigate/assets/6164178/afeac2eb-aa3b-4631-93a4-6849f2d5f46e">

### Version

0.13-rc1

### Frigate config file

```yaml
birdseye:
  enabled: true
  mode: continuous
  width: 720
  height: 720
  restream: true
  quality: 6

go2rtc:
  streams:
    annke_front:
    - rtsp://{user}:{pass}@10.0.40.4:554/Streaming/Channels/101
    - ffmpeg:annke_front#audio=opus
  webrtc:
    candidates:
    - 10.0.0.10:8555
    - stun:8555

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /config/model_cache/yolov8s/yolov8s.xml

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /config/model_cache/coco_80cl.txt

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
    pre_capture: 15
    post_capture: 15
  sync_recordings: true

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  required_zones: []
  retain:
    default: 14

detect:
  fps: 5
  enabled: true
  annotation_offset: -1500
  stationary:
    interval: 10
    threshold: 200
    max_frames:
      default: 300

motion:
  threshold: 100
  contour_area: 30

objects:
  track:
  - person
  - car
  - dog
  - cat
  - animal
  - truck
  - bicycle
  - motorcycle
  - bird

cameras:
  annke_front: # <------ Name the camera
    ffmpeg:
      inputs:
      - path: rtsp://{user}:{pass}@10.0.40.4:554/Streaming/Channels/102
        roles:
        - detect
      - path: rtsp://{user}:{pass}@10.0.40.4:554/Streaming/Channels/101
        roles:
        - record
    detect:
      width: 960   # <---- update for your camera's resolution
      height: 432   # <---- update for your camera's resolution
    zones:
      zone_0:
        coordinates: 
          338,47,387,33,472,21,594,25,662,39,712,69,751,92,798,120,841,159,916,233,886,263,806,314,740,382,647,432,298,432,227,391,82,276,159,143,237,102,282,74
    record:
      events:
        required_zones:
        - zone_0
    snapshots:
      required_zones:
      - zone_0
    motion:
      mask:
      - 207,0,0,0,0,190,72,270,167,133,318,60,408,35,527,22,711,58,798,122,926,245,960,0
```

### Relevant log output

```shell
2024-01-26 14:48:32.711894188  [2024-01-26 14:48:32] frigate.output                 WARNING : The birdseye resolution is a non-standard aspect ratio, forcing birdseye resolution to 720 x 960
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"20:9","height":432,"width":960},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"227:102","height":1632,"width":3632},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Annke FCD800
