### ISSUE TITLE
[Support]: Only one camera out of 4 showing detected person's name

### ISSUE THREAD

**Issue by kmelihk** [blakeblackshear/frigate#9460]
### Describe the problem you are having

Hello, I have Double Take with CompreFace integrated through the same mqtt server. On Double Take, all cameras show that I'm correctly identified. However on Frigate, Only one camera shows me with my name (FrontDoorbell on my configuration), other cameras simply show me as 'Person'. The only difference is that the cameras where detection shows only 'Person' is Reolink with H265 stream for recording and H264 substream for detection, and the one where I'm detected is Amcrest with no substreams. But Double Take shows names on all cameras so I suspect issue is elsewhere, but I'm not sure where to look. I appreciate any help you can provide.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: host
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password

objects:
  track:
    - person
    - cat
    - dog

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 2
    post_capture: 2
    objects:
      - person
      - car
    retain:
      default: 5
      mode: motion
      objects:
        person: 5

cameras:
  FrontDoor:
    ffmpeg:
      inputs:
        - path: "rtsp://user:pass@192.168.2.11:554//h265Preview_01_main"
          roles:
            - record
        - path: "rtsp://user:pass@192.168.2.11:554//h264Preview_01_sub"
          roles:
            - detect
    detect:
      enabled: True
    record:
      enabled: True
  BackyardDoor:
    ffmpeg:
      inputs:
        - path: "rtsp://user:pass@192.168.2.12:554//h265Preview_01_main"
          roles:
            - record
        - path: "rtsp://user:pass@192.168.2.12:554//h264Preview_01_sub"
          roles:
            - detect
    detect:
      enabled: True
    record:
      enabled: True
  GarageDoor:
    ffmpeg:
      inputs:
        - path: "rtsp://user:pass@192.168.2.13:554//h265Preview_01_main"
          roles:
            - record
        - path: "rtsp://user:pass@192.168.2.13:554//h264Preview_01_sub"
          roles:
            - detect
    detect:
      enabled: True
    record:
      enabled: True
    objects:
      track:
        - person
        - dog
        - cat
        - car
  FrontDoorbell:
    ffmpeg:
      inputs:
        - path: "rtsp://user:pass@192.168.2.15/cam/realmonitor?channel=1&subtype=00&authbasic=pass"
          roles:
            - record
            - detect
    detect:
      enabled: True
    record:
      enabled: True
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 810A, Amcrest Video Doorbell
