### ISSUE TITLE
[Config Support]: Blank page when I start Frigate

### ISSUE THREAD

**Issue by Mific78** [blakeblackshear/frigate#9475]
### Describe the problem you are having

I have just install Frigate 0.12.1 with the docker compose method. My host is Ubuntu 22.04. When I try to start Frigate from my Chrome browser (http://myIPaddress:5001), I got a blank page and I got the following error in my browser in debug mode :

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.`

The module is src/main.tsx.

My docker-compose file is as follows :

```
version: "3"
services:
  devcontainer:
    container_name: frigate-devcontainer
    privileged: true
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    deploy:
          resources:
              reservations:
                  devices:
                      - driver: nvidia
                        count: 1
                        capabilities: [gpu]
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /home/choupi/frigate/config:/config
      - .:/workspace/frigate:cached
      - /home/choupi/frigate/web:/opt/frigate/web
      - /etc/localtime:/etc/localtime:ro
      # - ./config/config.yml:/config/config.yml:ro
      - /home/choupi/frigate/storage:/media/frigate
      # Create the trt-models folder using the documented method of generating TRT models
      # - ./debug/trt-models:/trt-models
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "5001:5000" # API access
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
```

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mqtt
  port: 1883

cameras:
  test:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.0.xx:554/ISAPI/Streaming/channels/101
          roles:
            - detect
    detect:
      enabled: False
      height: 1080
      width: 1920
      fps: 5
```

### Relevant log output

```shell
Recreating frigate-devcontainer ... done
Recreating mqtt                 ... done
Attaching to mqtt, frigate-devcontainer
mqtt            | 1706465218: mosquitto version 1.6.15 starting
mqtt            | 1706465218: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt            | 1706465218: Opening ipv4 listen socket on port 1883.
mqtt            | 1706465218: Opening ipv6 listen socket on port 1883.
mqtt            | 1706465218: mosquitto version 1.6.15 running
frigate-devcontainer | s6-rc: info: service s6rc-fdholder: starting
frigate-devcontainer | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-devcontainer | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-devcontainer | s6-rc: info: service fix-attrs: starting
frigate-devcontainer | s6-rc: info: service s6rc-fdholder successfully started
frigate-devcontainer | s6-rc: info: service fix-attrs successfully started
frigate-devcontainer | s6-rc: info: service legacy-cont-init: starting
frigate-devcontainer | s6-rc: info: service legacy-cont-init successfully started
frigate-devcontainer | s6-rc: info: service log-prepare: starting
frigate-devcontainer | s6-rc: info: service log-prepare successfully started
frigate-devcontainer | s6-rc: info: service nginx-log: starting
frigate-devcontainer | s6-rc: info: service go2rtc-log: starting
frigate-devcontainer | s6-rc: info: service frigate-log: starting
frigate-devcontainer | s6-rc: info: service nginx-log successfully started
frigate-devcontainer | s6-rc: info: service go2rtc-log successfully started
frigate-devcontainer | s6-rc: info: service go2rtc: starting
frigate-devcontainer | s6-rc: info: service frigate-log successfully started
frigate-devcontainer | s6-rc: info: service go2rtc successfully started
frigate-devcontainer | s6-rc: info: service go2rtc-healthcheck: starting
frigate-devcontainer | s6-rc: info: service frigate: starting
frigate-devcontainer | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-devcontainer | s6-rc: info: service frigate successfully started
frigate-devcontainer | s6-rc: info: service nginx: starting
frigate-devcontainer | s6-rc: info: service nginx successfully started
frigate-devcontainer | s6-rc: info: service legacy-services: starting
frigate-devcontainer | 2024-01-28 19:06:58.926239437  [INFO] Preparing go2rtc config...
frigate-devcontainer | 2024-01-28 19:06:58.926411744  [INFO] The fake Frigate service is running...
frigate-devcontainer | 2024-01-28 19:06:58.926764969  [INFO] Starting NGINX...
frigate-devcontainer | s6-rc: info: service legacy-services successfully started
frigate-devcontainer | 2024-01-28 19:06:59.058430060  [INFO] Starting go2rtc...
frigate-devcontainer | 2024-01-28 19:06:59.108719987  19:06:59.108 INF go2rtc version 1.2.0 linux/amd64
frigate-devcontainer | 2024-01-28 19:06:59.108831829  19:06:59.108 INF [api] listen addr=:1984
frigate-devcontainer | 2024-01-28 19:06:59.108947576  19:06:59.108 INF [rtsp] listen addr=:8554
frigate-devcontainer | 2024-01-28 19:06:59.109045541  19:06:59.109 INF [srtp] listen addr=:8443
frigate-devcontainer | 2024-01-28 19:06:59.109134438  19:06:59.109 INF [webrtc] listen addr=:8555
frigate-devcontainer | 2024-01-28 19:07:03.927099283  [INFO] The fake Frigate service is running...
frigate-devcontainer | 2024-01-28 19:07:08.926719082  [INFO] Starting go2rtc healthcheck service...
frigate-devcontainer | 2024-01-28 19:07:08.928090953  [INFO] The fake Frigate service is running...
frigate-devcontainer | 2024-01-28 19:07:12.940771965  192.168.0.70 - - [28/Jan/2024:19:07:12 +0100] "GET /images/android-chrome-192x192.png HTTP/1.1" 200 3186 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
frigate-devcontainer | 2024-01-28 19:07:12.943136947  192.168.0.70 - - [28/Jan/2024:19:07:12 +0100] "GET /images/android-chrome-512x512.png HTTP/1.1" 200 7070 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
frigate-devcontainer | 2024-01-28 19:07:13.928889676  [INFO] The fake Frigate service is running...
frigate-devcontainer | 2024-01-28 19:07:14.940573592  192.168.0.70 - - [28/Jan/2024:19:07:14 +0100] "GET /images/android-chrome-192x192.png HTTP/1.1" 200 3186 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
frigate-devcontainer | 2024-01-28 19:07:14.944549876  192.168.0.70 - - [28/Jan/2024:19:07:14 +0100] "GET /images/android-chrome-512x512.png HTTP/1.1" 200 7070 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
frigate-devcontainer | 2024-01-28 19:07:14.999556591  192.168.0.70 - - [28/Jan/2024:19:07:14 +0100] "GET / HTTP/1.1" 200 532 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
frigate-devcontainer | 2024-01-28 19:07:15.026260201  192.168.0.70 - - [28/Jan/2024:19:07:15 +0100] "GET /src/main.tsx HTTP/1.1" 200 213 "http://192.168.0.70:5001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
frigate-devcontainer | 2024-01-28 19:07:18.930182926  [INFO] The fake Frigate service is running...
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
