### ISSUE TITLE
[Support]: Snapshots are being saved on HW disk instead of cache disk in UNRAID

### ISSUE THREAD

**Issue by yayitazale** [blakeblackshear/frigate#9477]
### Describe the problem you are having

Hi:

I noticed that the snapshots are being saved in the Array disk of share in Unraid witch is configured to use the cache array as main storage. The recordings instead, are being saved correctly at the cache share. Also, every 10 minutes or so, the disk is being read by frigate so it spins up. If I stop frigate docker, this behavior is not happening anymore.

The share configuration:
![imagen](https://github.com/blakeblackshear/frigate/assets/6462849/51a23404-4de7-4a60-850d-ee4f33359226)

Evidence that the newly created files are being saved on the array instead of the cache:
![imagen](https://github.com/blakeblackshear/frigate/assets/6462849/c6f3dfd2-24f6-41b3-b614-9b75a339f73c)

Evidence that the recordings are being saved on the cache until the mover is called at 6am:
![imagen](https://github.com/blakeblackshear/frigate/assets/6462849/31bda972-77c5-4f4c-a744-7d7c398bb05e)

What I have miss configured?

### Version

0.13.0-49814b3

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

audio:
  enabled: false
  min_volume: 500
  listen:
  - meow
  - speech

mqtt:
  # Required: host name
  host: 192.168.1.20
  # Optional: port (default: shown below)
  # port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: pass
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7

ui:
  live_mode: webrtc

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 10
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

record:
  enabled: true
  expire_interval: 2480
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 7
      mode: all
  
  
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%m/%d/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 50)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  #mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: true
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  #mqtt_off_delay: 30

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
  - person
  - cat
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 3000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 10000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.65
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
    cat:
      min_area: 3000
      #max_area: 1000
      min_score: 0.65
      threshold: 0.75
    bird:
      min_area: 3000
      #max_area: 1000
      min_score: 0.65
      threshold: 0.75

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  #width: 640
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  #height: 360
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 20
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  rtsp:
    username: user
    password: pass
  streams:
    pasillo:
    - rtsp://user:pass@192.168.1.113:554/stream1
    - ffmpeg:oficina#audio
    oficina:
    - rtsp://user:pass@192.168.1.134:554/stream1
    - ffmpeg:pasillo#audio
    cocina:
    - rtsp://user:pass@192.168.1.116:554/stream1
    - ffmpeg:cocina#audio
    salon:
    - rtsp://user:pass@192.168.1.247:554/stream1
    - ffmpeg:salon#audio
    garaje:
    - rtsp://user:pass@192.168.1.120:554/stream1
    - ffmpeg:garaje#audio
    terraza:
    - rtsp://user:pass@192.168.1.197:554/stream1
    - ffmpeg:terraza#audio
    balcon:
    - rtsp://user:pass@192.168.1.217:554/stream1
    - ffmpeg:balcon#audio
    barbacoa:
    - rtsp://user:pass@192.168.1.115:554/stream1
    - ffmpeg:barbacoa#audio
  webrtc:
    candidates:
    - 192.168.1.20:8555
    - stun:8555

cameras:
  # Name of your camera
  pasillo:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/pasillo
        roles:
        - record
        - detect

  # Name of your camera
  oficina:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/oficina
        roles:
        - record
        - detect
    # zones:
    #   oficina_zone:
    #     coordinates: 640,0,640,360,0,360,0,0
    # onvif:
    #   # Required: host of the camera being connected to.
    #   host: 192.168.1.134
    #   # Optional: ONVIF port for device (default: shown below).
    #   port: 2020
    #   # Optional: username for login.
    #   # NOTE: Some devices require admin to access ONVIF.
    #   user: user
    #   # Optional: password for login.
    #   password: pass
    #   # Optional: PTZ camera object autotracking. Keeps a moving object in
    #   # the center of the frame by automatically moving the PTZ camera.
    #   autotracking:
    #     # Optional: enable/disable object autotracking. (default: shown below)
    #     enabled: False
    #     # Optional: list of objects to track from labelmap.txt (default: shown below)
    #     track:
    #       - person
    #     # Required: Begin automatically tracking an object when it enters any of the listed zones.
    #     required_zones:
    #       - oficina_zone
    #     # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
    #     return_preset: not_home
    #     # Optional: Seconds to delay before returning to preset. (default: shown below)
    #     timeout: 10

  # Name of your camera
  cocina:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/cocina
        roles:
        - record
        - detect

  # Name of your camera
  salon:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/salon
        roles:
        - record
        - detect
    # zones:
    #   salon_zone:
    #     coordinates: 640,0,640,360,0,360,0,0
    # onvif:
    #   # Required: host of the camera being connected to.
    #   host: 192.168.1.247
    #   # Optional: ONVIF port for device (default: shown below).
    #   port: 2020
    #   # Optional: username for login.
    #   # NOTE: Some devices require admin to access ONVIF.
    #   user: user
    #   # Optional: password for login.
    #   password: pass
    #   # Optional: PTZ camera object autotracking. Keeps a moving object in
    #   # the center of the frame by automatically moving the PTZ camera.
    #   autotracking:
    #     # Optional: enable/disable object autotracking. (default: shown below)
    #     enabled: False
    #     # Optional: list of objects to track from labelmap.txt (default: shown below)
    #     track:
    #       - person
    #     # Required: Begin automatically tracking an object when it enters any of the listed zones.
    #     required_zones:
    #       - salon_zone
    #     # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
    #     return_preset: not_home
    #     # Optional: Seconds to delay before returning to preset. (default: shown below)
    #     timeout: 10

  # Name of your camera
  garaje:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/garaje
        roles:
        - record
        - detect
    objects:
      track:
      - person

  # Name of your camera
  terraza:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/terraza
        roles:
        - record
        - detect
    objects:
      track:
      - bird
      - person
    motion:
      mask:
      - 0,360,0,286,115,237,271,360
    mqtt:
      enabled: true
      bounding_box: false #this will get rid of the box around the bird. We already know it is a bird. Sheesh.
      timestamp: false #this will get rid of the time stamp in the image. 
      quality: 95 #default quality is 70, which will get you lots of compression artifacts

  # Name of your camera
  balcon:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/balcon
        roles:
        - record
        - detect
    objects:
      track:
      - bird
      - person
      filters:
        bird:
          mask:
          - 1920,1080,1920,435,1335,409,1066,626,1029,1080
    mqtt:
      enabled: true
      bounding_box: false #this will get rid of the box around the bird. We already know it is a bird. Sheesh.
      timestamp: false #this will get rid of the time stamp in the image. 
      quality: 95 #default quality is 70, which will get you lots of compression artifacts
    motion:
      mask:
        #- 564,0,1012,0,990,286,805,257,593,286
      - 1042,1080,1658,1080,1711,736,1749,441,1261,371,1085,552,1040,706

# Name of your camera
  barbacoa:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/barbacoa
        roles:
        - record
        - detect
    objects:
      track:
      - bird
      - person
      filters:
        bird:
          mask:
          - 883,899,630,1080,486,1080,98,1080,22,789,0,446,111,259,262,146,506,244,1002,102,1118,0,1298,0,1322,298,766,609
    mqtt:
      enabled: true
      bounding_box: false #this will get rid of the box around the bird. We already know it is a bird. Sheesh.
      timestamp: false #this will get rid of the time stamp in the image. 
      quality: 95 #default quality is 70, which will get you lots of compression artifacts
    motion:
      mask:    
        - 1042,1080,0,1080,0,0,477,0,266,150,350,250,458,205,552,262,571,372,966,296,940,62,1065,0,1212,0,1324,30,1280,312,1494,407,1505,642

# Optional: Telemetry configuration
telemetry:
  # Optional: Enabled network interfaces for bandwidth stats monitoring (default: shown below)
  network_interfaces: []
  # Optional: Configure system stats
  stats:
    # Enable AMD GPU stats (default: shown below)
    amd_gpu_stats: false
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    network_bandwidth: false
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
```

### Relevant log output

```shell
I don't see nothing relevant
```

### FFprobe output from your camera

```shell
-
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Tapo
