### ISSUE TITLE
[Config Support]: Unable to use exec in go2rtc

### ISSUE THREAD

**Issue by n1ght-hunter** [blakeblackshear/frigate#9486]
### Describe the problem you are having

when using go2rtc you are unable to exec an example being 
`printer: exec:ffmpeg -f v4l2 -framerate 30 -c:v mjpeg -i /dev/video0 -c copy -rtsp_transport tcp -f rtsp {output}`
it causes no go2rtc.yaml file to be created

as far as i can tell this is due the way frigate alters the yaml before creating the `/dev/shm/go2rtc.yaml ` file
relevant file: [docker/main/rootfs/usr/local/go2rtc/create_config.py](https://github.com/blakeblackshear/frigate/blob/64a91f552f26ee134461e24c590350fd75328053/docker/main/rootfs/usr/local/go2rtc/create_config.py)

PS 
the place where you put the version in for issue needs to be changed from saying 
"Visible on the Debug page in the Web UI"
to 
"Visible on the System page in the Web UI"

### Version

0.12.1-367d724

### Frigate config file

```yaml
go2rtc:
  streams:
    printer: exec:ffmpeg -f v4l2 -framerate 30 -c:v mjpeg -i /dev/video0 -c copy -rtsp_transport tcp -f rtsp {output}
```

### Relevant log output

```shell
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

Other
