### ISSUE TITLE
Objects detected in zones when they did not enter the zone

### ISSUE THREAD

**Issue by rsteckler** [blakeblackshear/frigate#9491]
### Describe the problem you are having

This car is detected as being in the Front Gate WalkWay Notify zone:
![image](https://github.com/blakeblackshear/frigate/assets/1714230/1ac75adf-a5be-41bb-af2c-9ab38fe2d49a)

It's VERY clearly not in the zone:
![image](https://github.com/blakeblackshear/frigate/assets/1714230/b8cb2585-8dd9-4a14-8e6f-73b510b706e9)

My only guess is that the bounding box from one of the frames extended into the zone, but there's only a few frames where a car driving by is visible, so I don't think it would be the majority, and clearly isn't in the frame chosen for the snapshot.

I know the zone is chosen based on the bottom-center of the bounding box, but I'm not sure if there's a way to see what Frigate chose as the bounding box as it relates to which zone is triggered.

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
mqtt:
  host: homestack-mosquitto-service

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/database.db

model:
  path: plus://6ec0bb734efc83f493a91b2b57116a41

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 35

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  #    debug_test:
  #  ffmpeg:
  #    inputs:
  #      - path: /media/frigate/dog2.mp4
  #        input_args: -re -stream_loop -1 -fflags +genpts
  #        roles:
  #          - detect
  #  detect:
  #    height: 2688
  #    width: 1520
  #    fps: 5
  #  rtmp:
  #    enabled: False
  #  snapshots:
  #    enabled: True
  #    timestamp: False
  #    bounding_box: True
  #    crop: False
  #    retain:
  #      default: 365
  camera_pool:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.25/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
      - 1300,30,1850,30,1850,100,1300,100
      - 1450,275,1830,405,990,880,585,445
    zones:
      pool_notify:
        coordinates: 1822,406,1000,882,581,451,0,0,0,1080,1920,1080,1920,0,0,0,603,457,1483,280
    objects:
      track:
      - person
      - dog
      - cat
      - face
      - package
      - amazon
      - fedex
      - ups
  camera_rear_patio:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.23/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
      - 1300,30,1850,30,1850,100,1300,100
      - 1323,0,1367,282,1063,339,1065,284,778,301,0,583,0,0
    zones:
      rear_patio_notify:
        coordinates: 1920,1080,1920,0,1052,303,1046,451,931,479,748,427,723,331,0,614,0,1080
    objects:
      track:
      - person
      - dog
      - cat
      - face
      - package
      - amazon
      - fedex
      - ups
  camera_driveway:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.24/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
      - 1300,30,1850,30,1850,100,1300,100
    zones:
      driveway_notify:
        coordinates: 0,0,0,1080,1920,1080,1920,0
    objects:
      filters:
        car:
          mask:
            - 1920,1020,1920,150,1380,150,1380,1020
  camera_front_gate_driveway:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 960
    ffmpeg:
      output_args:
        detect: -vf 
          hwdownload,v360=fisheye:flat:ih_fov=185:iv_fov=180:h_fov=80:v_fov=80:roll=-10:pitch=-20:yaw=-35:rorder=pyr:w=1280:h=960,format=yuv420p
          -f rawvideo -pix_fmt yuv420p
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.29/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1280
      height: 960
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 960
      retain:
        default: 365
        objects:
          person: 50
    objects:
      filters:
        car:
          min_score: .5
          threshold: .85
    zones:
      front_gate_driveway_notify:
        coordinates: 588,409,1042,497,1045,960,0,960,0,0
  camera_front_gate_walkway:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 960
    ffmpeg:
      output_args:
        detect: -vf 
          hwdownload,v360=fisheye:flat:ih_fov=185:iv_fov=180:h_fov=80:v_fov=80:roll=0:pitch=0:yaw=35:rorder=pyr:w=1280:h=960,format=yuv420p
          -f rawvideo -pix_fmt yuv420p
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.29/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1280
      height: 960
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 960
      retain:
        default: 365
        objects:
          person: 50
    objects:
      filters:
        car:
          min_score: .5
          threshold: .85
    zones:
      front_gate_walkway_notify:
        coordinates: 0,960,1280,960,1280,604,650,630,242,675,124,677,0,614
  camera_garage:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.22/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
      - 1300,30,1850,30,1850,100,1300,100
    zones:
      garage_notify:
        coordinates: 0,0,0,1080,1920,1080,1920,0
    objects:
      track:
      - person
      - face
      - package
      - amazon
      - fedex
      - ups
  camera_balcony:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.27/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
      - 1300,30,1850,30,1850,100,1300,100
      - 1178,0,1172,61,404,329,0,396,0,0
    zones:
      balcony_notify:
        coordinates: 1239,175,443,388,989,1080,1471,1080,1920,348,1695,410,1454,243
    objects:
      track:
      - person
      - dog
      - cat
      - face
      - package
      - amazon
      - fedex
      - ups
  camera_front_yard:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.26/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      contour_area: 40
      threshold: 40
      mask:
      - 1300,30,1850,30,1850,100,1300,100
#      - 1920,0,1920,496,1808,518,1781,258,1008,240,749,261,609,194,300,319,0,203,0,0      
    zones:
      front_yard_notify:
        coordinates: 0,0,0,1080,1920,1080,1920,0
    objects:
      track:
      - person
      - dog
      - cat
      - face
  camera_casita:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.30/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
      - 1300,30,1850,30,1850,100,1300,100
      - 0,0,0,441,435,396,744,278,705,0
    zones:
      casita_notify:
        coordinates: 0,0,0,1080,1920,1080,1920,0
  camera_front_door:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.21/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    motion:
      mask:
      - 1300,30,1850,30,1850,100,1300,100
    zones:
      front_door_notify:
        coordinates: 0,0,0,1080,1920,1080,1920,0
    objects:
      track:
      - person
      - dog
      - cat
      - face
      - package
      - amazon
      - fedex
      - ups
  camera_familyroom_pool:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      output_args:
        detect: -vf 
          hwdownload,v360=fisheye:flat:ih_fov=180:iv_fov=180:h_fov=90:v_fov=50:roll=90:pitch=40:rorder=rpy:w=1920:h=1080,format=yuv420p
          -f rawvideo -pix_fmt yuv420p
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.31/Streaming/Channels/101/
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    zones:
      familyroom_pool_notify:
        coordinates: 0,0,1920,0,1920,1080,0,1080
    objects:
      track:
      - person
      - dog
      - cat
      - face
      - package
      - amazon
      - fedex
      - ups
  camera_familyroom:
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1080
    ffmpeg:
      output_args:
        detect: -vf 
          hwdownload,v360=fisheye:flat:ih_fov=180:iv_fov=180:h_fov=60:v_fov=33:roll=180:pitch=70:rorder=rpy:w=1920:h=1080,format=yuv420p
          -f rawvideo -pix_fmt yuv420p
      inputs:
      - path: rtsp://admin:Cypher800!@192.168.3.31/Streaming/Channels/101/
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      height: 1080
      retain:
        default: 365
        objects:
          person: 50
    zones:
      familyroom_notify:
        coordinates: 0,0,1920,0,1920,1080,0,1080
    objects:
      track:
      - person
      - dog
      - cat
      - face
      - package
      - amazon
      - fedex
      - ups
objects:
  track:
  - person
  - dog
  - cat
  - car
  - face
  - package
  - amazon
  - fedex
  - ups
  - license_plate
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .75
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

dahua fisheye

**Comment by NickM-27** [comment]
the snapshot that is saved is not necessarily the moment that the car has entered the zone. You should use the clip timeline view to see what the box was when it was detected in the zone, however it looks like there is no clip for this event

**Comment by rsteckler** [comment]
I have a different NVR with 24/7 recording, so don't have clips enabled.  Is the bounding box for the zone determined by the first frame the object was detected?

**Comment by NickM-27** [comment]
> Is the bounding box for the zone determined by the first frame the object was detected?

I don't know what you are asking. an object will be considered part of a zone if it enters the zone at any point while it is being tracked. The snapshot saved is not the moment that the object was in the zone, with recordings enabled there are ways to see that.

In any case what most likely happened here is that the bounding box was not accurate and was inside the zone causing the object to be considered having entered the zone. Part of this is probably caused by using the low .5 min_score for car despite using frigate+ which can lead to incorrect bounding box. If you don't want to try increasing the min_score then this can be addressed by increasing the zone intertia

```
    zones:
      front_gate_walkway_notify:
        inertia: 6
        coordinates: 0,960,1280,960,1280,604,650,630,242,675,124,677,0,614
```

without the zone data there is no reason to believe that this is a bug with the zone logic
