### ISSUE TITLE
[Support]: Default to animal if not cat or dog

### ISSUE THREAD

**Issue by scopedial** [blakeblackshear/frigate#9492]
### Describe the problem you are having

Hello
I have been running Frigate for a few months now but it is not for tracking people or cars. I use
it to track animals in my back yard. I have many. 
If the animal is not a dog or cat is there any way to default to a generic "animal" label?
I have many squirrels in my yard and they are either a "cat" or "dog". 
I have a frigate+ account and I have been feeding my false positives to that account and generating
models as a result. It may be helping a bit. 
Would it be possible to expand the false positive labels to include squirrel or rabbit or maybe just "animal"
Any suggestions is appreciated.
I am running it on a Pi 4 with RaspOS (latest).

### Version

0.13.0 rc1

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://8ef102b606cece6ff8ffaac3c6261e12

ffmpeg:
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration

cameras:
  tapo1:  #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://tapocam:foxtrot3cho@192.168.232.180:554/stream1 #The Stream you want to monitor
          roles:
            - record
        - path: rtsp://tapocam:foxtrot3cho@192.168.232.180:554/stream2 #The Stream you want to monitor
          roles:
            - detect           
    detect:
      enabled: true # Detection is ?
      width: 1920 # The Cameras resolution
      height: 1080 # The Cameras resolution
    motion: 
      mask:
       - 1202,0,1193,552,0,880,0,0

  tapo2:  #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://tapocam:foxtrot3cho@192.168.232.239:554/stream1 #The Stream you want to monitor
          roles:
            - record
        - path: rtsp://tapocam:foxtrot3cho@192.168.232.239:554/stream2 #The Stream you want to monitor
          roles:
            - detect
    detect:
      enabled: true # Detection is ?
      width: 1920 # The Cameras resolution
      height: 1080 # The Cameras resolution
    motion:
      mask:
         - 1888,0,1877,479,1100,173,995,0 #bushes
         - 697,0,26,0,23,66,714,49 #timestamp
 
  MiniCam1:  #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://192.168.232.241:554/live/ch00_1 #The Stream you want to monitor
          roles:
            - record
            - detect
    detect:
      enabled: true # Detection is ?
      width: 1920 # The Cameras resolution
      height: 1080 # The Cameras resolution
    motion:
      mask:
         - 1280,0,1920,0,1920,0,1920,83,1283,80

  testpi:  #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://192.168.232.207:8554/stream  #The Stream you want to monitor
          roles:
            - record
            - detect
    detect:
      enabled: false # Detection is ?
      width: 1920 # The Cameras resolution
      height: 1080 # The Cameras resolution
    motion:
      mask:
         - 1280,0,1920,0,1920,0,1920,83,1283,80

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  
  # Optional: Retention settings for recording
  
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 14
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 25   

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - dog
    - rabbit
    - bird
    - animal
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  mask: 0,0,1000,0,1000,200,0,200

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 7
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  
go2rtc:
  streams:
    testpi:
      rtsp://192.168.232.207:8554/stream  
  publish:
    testpi:
      rtmps://a.rtmp.youtube.com/live2/mss2-2a4k-urtd-yf02-5g5f 
  log:
    streams: error
    rtsp: error
    stream: error

database:
  path: /config/frigate.db

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.app: error

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
```

### Relevant log output

```shell
I could not find any
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMA-law/G.711A-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMA-law/G.711A-law"}]}}]
AND
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMA-law/G.711A-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMA-law/G.711A-law"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo C310/C210
