### ISSUE TITLE
[Support]: Event Didnt show in WebUI

### ISSUE THREAD

**Issue by jsbowling42** [blakeblackshear/frigate#9493]
### Describe the problem you are having

I had a notification of a package on my Front porch. but the event didn't show in the WebUI for that camera. in my config the threshold is .8 and in the MQTT payload is showing .85 and it is in my zone for the front door. So im not sure why it not in the WebUI Events logs. 

HA Notification:
![notfication](https://github.com/blakeblackshear/frigate/assets/35424582/f49b5936-11a8-4c35-9197-968ae21a7044)

here is the MQTT Payload:
```    {
        "before": {
            "id": "1706557505.325746-zyc1pd",
            "camera": "front_door_cam",
            "frame_time": 1706557505.523792,
            "snapshot": {
                "frame_time": 1706557505.523792,
                "box": [
                    496,
                    771,
                    588,
                    872
                ],
                "area": 9292,
                "region": [
                    380,
                    657,
                    700,
                    977
                ],
                "score": 0.83984375,
                "attributes": []
            },
            "label": "package",
            "sub_label": null,
            "top_score": 0.83984375,
            "false_positive": false,
            "start_time": 1706557505.325746,
            "end_time": null,
            "score": 0.83984375,
            "box": [
                496,
                771,
                588,
                872
            ],
            "area": 9292,
            "ratio": 0.9108910891089109,
            "region": [
                380,
                657,
                700,
                977
            ],
            "stationary": false,
            "motionless_count": 0,
            "position_changes": 1,
            "current_zones": [],
            "entered_zones": [],
            "has_clip": false,
            "has_snapshot": false,
            "attributes": {},
            "current_attributes": []
        },
        "after": {
            "id": "1706557505.325746-zyc1pd",
            "camera": "front_door_cam",
            "frame_time": 1706557505.938415,
            "snapshot": {
                "frame_time": 1706557505.721261,
                "box": [
                    492,
                    761,
                    587,
                    874
                ],
                "area": 10735,
                "region": [
                    380,
                    659,
                    700,
                    979
                ],
                "score": 0.8515625,
                "attributes": []
            },
            "label": "package",
            "sub_label": null,
            "top_score": 0.845703125,
            "false_positive": false,
            "start_time": 1706557505.325746,
            "end_time": null,
            "score": 0.8671875,
            "box": [
                490,
                757,
                587,
                874
            ],
            "area": 11349,
            "ratio": 0.8290598290598291,
            "region": [
                380,
                658,
                700,
                978
            ],
            "stationary": false,
            "motionless_count": 2,
            "position_changes": 1,
            "current_zones": [
                "front_porch"
            ],
            "entered_zones": [
                "front_porch"
            ],
            "has_clip": false,
            "has_snapshot": false,
            "attributes": {},
            "current_attributes": []
        },
        "type": "update"
    }

```
Here is the Image of my Events Panel:
![image](https://github.com/blakeblackshear/frigate/assets/35424582/bcd2d398-0cd8-4a4f-8d1c-0ca08c7a746d)

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
mqtt:
  host: IP
  user: user
  password: password
 
ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  output_args:
    record: preset-record-generic-audio-copy

objects:
  filters:
    dog:
      min_score: .7
      threshold: .92
    cat:
      min_score: .65
      threshold: .9
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .8
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      max_ratio: 1.0
      min_score: .65
      threshold: .9
    car:
      min_ratio: 0.5
      min_score: .65
      threshold: .85

go2rtc:
  streams:
    driveway_cam: 
      - rtsp://user:password@IP:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:driveway_cam#audio=opus"
    front_yard_cam: 
      - rtsp://user:password@IP:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_yard_cam#audio=opus"
    side_cam: 
      - rtsp://user:password@IP:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:side_cam#audio=opus"
    front_door_cam: 
      - rtsp://user:password@IP:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_door_cam#audio=opus"
    backyard_cam: 
      - rtsp://user:password@IP:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:backyard_cam#audio=opus"
    
cameras:
########################################################################################################################################################################################
#
#
#        Driveway Cam
#
########################################################################################################################################################################################
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://IP:8554/driveway_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            # - audio
    detect:
      # width: 2304
      # height: 1296
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package

      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - side_yard
        - front_yard
        - driveway
        - driveway_entrance
    motion:
      improve_contrast: True
      mask: 596,997,596,1050,355,1051,357,992

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        pre_capture: 30
        post_capture: 30
        required_zones:
          - side_yard
          - front_yard
          - driveway
          - driveway_entrance
        retain:
          default: 14
          mode: active_objects
    zones:
      driveway_entrance:
        coordinates: 1252,276,1227,270,1209,260,1192,245,1178,229,1162,213,967,214,952,243,937,262,900,277,862,290
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package

      side_yard:
        coordinates: 0,1080,132,1080,144,1059,197,977,251,900,296,843,390,706,437,646,497,581,535,535,559,506,591,465,632,432,663,391,695,363,749,319,782,306,810,300,835,291,864,283,899,273,927,260,944,248,957,232,972,203,810,207,793,212,757,235,692,279,653,302,608,329,452,446,187,687,102,730,0,856
        objects: 
          - person
          - dog
          - cat

      front_yard:
        coordinates: 1195,235,1227,263,1251,270,1290,282,1327,290,1391,300,1449,307,1490,309,1507,297,1517,267,1521,241,1516,215,1483,213,1410,206,1310,201,1156,200
        objects: 
          - person
          - dog
          - cat

      driveway:
        coordinates:  1920,1080,1920,879,1920,835,1889,807,1863,772,1859,741,1836,713,1806,675,1779,640,1749,610,1720,577,1695,546,1661,516,1629,476,1587,436,1562,418,1547,404,1524,384,1502,369,1506,351,1505,327,1492,317,1433,311,1391,307,1349,297,1311,294,1264,278,846,295,812,309,757,326,725,338,679,384,605,452,524,558,434,697,323,852,200,1011,150,1080
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package
########################################################################################################################################################################################
#
#
#        Front yard Cam
#
########################################################################################################################################################################################
  front_yard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://IP:8554/front_yard_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            # - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        - car
        - amazon
        - fedex
        - ups
        - package

      filters:
        person:
         # mask:
            #- 365,928,633,788,509,548,331,606
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - front_yard
        - sidewalk
    motion:
      threshold: 50
      lightning_threshold: 0.6
      improve_contrast: True
      mask:
        - 574,1080,579,1003,25,1016,0,1058

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - front_yard
          - sidewalk
        retain:
          default: 14
          mode: active_objects
    zones:
      front_yard:
        coordinates: 458,1080,1494,1080,1920,1080,1920,762,1863,477,1798,325,1524,233,1329,188,1116,150,974,128,863,118,836,119,795,125,744,133,674,141,611,155,527,172,478,184,446,195,428,204,430,221,447,222,489,233,518,240,561,250,635,264,681,276,707,284,734,295,757,307,774,322,786,348,792,384,782,410,769,432,723,467,637,524,584,560,529,609,413,687,278,763
        objects: 
          - person
          - face
          - license_plate
          - dog
          - cat
          - car
          - amazon
          - fedex
          - ups
          - package
   
      sidewalk:
        coordinates: 271,758,388,693,485,637,552,584,591,554,647,514,686,491,717,466,754,441,772,421,786,398,789,378,783,350,769,327,750,309,731,300,707,291,665,276,628,270,596,263,558,253,524,247,495,239,470,235,442,227,421,222,413,237,418,265,442,270,462,275,484,281,512,289,554,302,578,310,608,322,630,333,646,348,655,366,655,388,644,410,625,430,602,443,562,466,529,481,473,497,408,520,340,547,271,580,191,624
        objects:
          - person
          - face
          - license_plate
          - dog
          - cat
          # - car
          - amazon
          - fedex
          - ups
          - package

########################################################################################################################################################################################
#
#
#        master side yard Cam
#
########################################################################################################################################################################################
  side_cam:
    ffmpeg:
      inputs:
        - path: rtsp://IP:8554/side_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            # - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - face
        - license_plate
        - dog
        - cat
        # - car
        - amazon
        - fedex
        - ups
        - package

      filters:

        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - master_side_yard
    motion:
      improve_contrast: True
      mask:
        - 21,987,429,990,429,1080,21,1056

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - master_side_yard
        retain:
          default: 14
          mode: active_objects
    zones:
      master_side_yard:
        coordinates: 1920,1080,1633,716,1048,179,941,185,760,196,766,465,806,1080
        objects: 
          - person
          - face
          - license_plate
          - dog
          - cat
          # - car
          - amazon
          - fedex
          - ups
          - package

########################################################################################################################################################################################
#
#
#        Front door Cam
#
########################################################################################################################################################################################
  front_door_cam:
    ffmpeg:
      inputs:
        - path: rtsp://IP:8554/front_door_cam  # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            # - audio
    detect:
      width: 1440
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - face
        # - license_plate
        - dog
        - cat
        # - car
        - amazon
        - fedex
        - ups
        - package

      filters:

        person:
          #mask:
            #- 981,652,993,829,841,842,851,661
            #- 988,905,1068,897,1064,802,991,802
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - front_yard
    motion:
      improve_contrast: True
      mask: 1418,0,1419,38,1017,35,1015,0


    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - front_yard
        retain:
          default: 14
          mode: active_objects
    zones:
      side_walk:
        coordinates: 495,788,459,787,441,671,465,658,487,656,527,660,559,665,616,672,643,680,674,689,700,707,732,721,782,735,830,758,930,811,519,873
        objects: 
          - person
          - face
          # - license_plate
          - dog
          - cat
          # - car
          - amazon
          - fedex
          - ups
          - package
      front_porch:
        coordinates: 495,1080,1103,1080,1440,1080,1440,1003,1440,974,932,811,517,874
        objects: 
          - person
          - face
          # - license_plate
          - dog
          - cat
          # - car
          - amazon
          - fedex
          - ups
          - package
      front_yard:
        coordinates: 597,663,671,683,695,707,742,724,937,816,939,708,941,675,944,659,963,634,958,600,902,603,837,608,798,608,696,615,644,614,584,617,514,619,473,619,428,616,442,657,514,660
        objects: 
          - person
          - face
          # - license_plate
          - dog
          - cat
          # - car
          - amazon
          - fedex
          - ups
          - package

########################################################################################################################################################################################
#
#
#        Backyard Cam
#
########################################################################################################################################################################################
  backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://IP:8554/backyard_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            # - audio
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - face
        - dog
        - cat
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          # min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 14
      required_zones:
        - backyard
    motion:
      improve_contrast: True
      mask:
        - 21,1058,442,1058,436,997,0,1001

    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        required_zones:
          - backyard
        retain:
          default: 14
          mode: active_objects
    zones:
      backyard:
        coordinates: 0,1080,1465,1080,1502,776,1503,627,1485,449,1477,319,1474,273,1447,227,1391,220,1251,188,1116,166,885,136,667,131,546,157,383,206,0,365
        objects: 
          - person
          - dog
          - cat
          - face
          
detectors:
  coral1:
    type: edgetpu
    device: pci:0

model:
  path: plus://
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Loryta IPC-T5442TM-AS
