### ISSUE TITLE
Unable to use the SEND TO FRIGATE+ button

### ISSUE THREAD

**Issue by guim31** [blakeblackshear/frigate#9495]
### Describe the problem you are having

When I click the button it stays on "uploading" but nothing happens.
In the logs I got : 
`ERROR   : Unable to load clean png for event: xxxx`

### Version

13 RC

### Frigate config file

```yaml
mqtt:
  host: 192.168.100.150
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb 

birdseye:
  enabled: true
  width: 896
  height: 672
  quality: 4
  mode: continuous

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25

objects:
  track:
    - person
    - cat
    - car


record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 3
    post_capture: 8
    retain:
      default: 15

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  retain:
    default: 10
    objects:
      person: 15
  quality: 100


rtmp:
  enabled: False 

go2rtc:
  streams:
    CAM1: 
      - http://192.168.100.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
      #- "ffmpeg:reolink#audio=opus"
    CAM1_sub: 
      - http://192.168.100.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
    CAM2: 
      - http://192.168.100.202/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
      #- "ffmpeg:reolink#audio=opus"
    CAM2_sub: 
      - http://192.168.100.202/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=


cameras:
  CAM1:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - nobuffer+genpts+discardcorrupt
      - -flags
      - low_delay
      - -strict
      - experimental
      - -analyzeduration
      - 1000M
      - -probesize
      - 1000M
      - -rw_timeout
      - "5000000"
      inputs:
        - path: http://192.168.100.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp

        - path: http://192.168.100.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    mqtt:
      quality: 100
      timestamp: True
    zones:
      passage:
        coordinates: 0,1920,595,1577,2070,790,1513,738,323,1263,406,909,0,1112
      parking:
       coordinates: 0,1144,598,853,223,728,0,799
    motion:
      mask:
        - 0,463,1457,151,2068,228,2560,650,2560,0,0,0
        

  CAM2:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - nobuffer+genpts+discardcorrupt
      - -flags
      - low_delay
      - -strict
      - experimental
      - -analyzeduration
      - 1000M
      - -probesize
      - 1000M
      - -rw_timeout
      - "5000000"
      inputs:
        - path: http://192.168.100.202/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.100.202/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    mqtt:
      quality: 100
      timestamp: True
    zones:
      parking:
        coordinates: 0,1920,2312,1920,2141,1628,1836,1202,1349,796,0,805

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow
```

### Relevant log output

```shell
ERROR   : Unable to load clean png for event: xxxxx
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB
