### ISSUE TITLE
[Bug]: In the Events page, filters by "Month" don't appear to work

### ISSUE THREAD

**Issue by supermarkert** [blakeblackshear/frigate#9503]
### Describe the problem you are having

In the Events page, if I choose to filter events by "This Month", it shows events for _only_ today (1/30) and nothing before.  
If I choose to filter by "Last Month", it shows events for everything _before_ today (so it's still this month).  

I've spent the past week installing/setting up my Frigate install for the first time, so there's only about 6 days of events, but I would still expect the Month filters to show January properly.

**"This Month"**
![image](https://github.com/blakeblackshear/frigate/assets/15205204/b790e52d-6ac0-493d-9a0c-27d6699dd477)

**"Last Month"**
![image](https://github.com/blakeblackshear/frigate/assets/15205204/54f1abe9-0321-4265-a96a-158bb9eaab0c)

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: homeassistant.lan
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  topic_prefix: frigate
#
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - cat
    - bird
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 100
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 500000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.4
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 1.5
    dog:
      min_area: 100
      max_area: 100000
      min_ratio: 1.0
      max_ratio: 2.0
      threshold: 0.6
    cat:
      min_area: 100
      max_area: 100000
      min_ratio: 1.0
      max_ratio: 2.0
      threshold: 0.6
    bird:
      min_area: 10
      max_area: 4000
      min_ratio: 0.8
      max_ratio: 1.2
      threshold: 0.7

record:
  enabled: True
  expire_interval: 60
  retain:
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    # objects:
    #   - person
    #   - dog
    #   - cat
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 14
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
birdseye:
  enabled: True
  mode: motion

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
go2rtc:
  log:
    format: text
    exec: trace
  webrtc:
    candidates:
      - 192.168.60.202:8555
      - stun:8555
  streams:
    camerafrontdoor:
      - "ffmpeg:http://192.168.40.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.21:554/h264Preview_01_main
#      - "ffmpeg:camerafrontdoor#audio=opus"
    camerafrontdoor_sub:
      - "ffmpeg:http://192.168.40.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}"
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.21:554/h264Preview_01_sub
#      - "ffmpeg:camerafrontdoor_sub#audio=opus"
#
    camerabackyard:
      # - "ffmpeg:http://192.168.40.22/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=iot&password=7wYMZ5qPzLjtNbo#video=copy#audio=copy#audio=opus"
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.22:554/h265Preview_01_main
      - "ffmpeg:camerabackyard#audio=opus"
    camerabackyard_sub:
      - "ffmpeg:http://192.168.40.22/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}"
      # - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.22:554/h264Preview_01_sub
      # - "ffmpeg:camerabackyard_sub#audio=opus"
cameras:
  frontdoor_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/camerafrontdoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camerafrontdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 494,27,497,0,149,0,149,32
    detect:
      width: 640
      height: 480
    live:
      stream_name: camerafrontdoor_sub
    record:
      events:
        required_zones:
          - frontporch_zone
          - frontstreet_zone
    snapshots:
      required_zones:
        - frontporch_zone
        - frontstreet_zone
    zones:
      frontporch_zone:
        coordinates: 640,480,640,419,516,368,324,371,155,370,0,325,0,480
        objects:
          - person
          - dog
          - cat
      frontstreet_zone:
        coordinates: 39,327,145,362,309,379,436,373,550,351,558,316,517,301,289,297,134,286
        objects:
          - person
          - dog
#
  backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camerabackyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camerabackyard_sub?video=copy
          input_args: preset-rtsp-restream
          hwaccel_args: preset-nvidia-h264
          roles:
            - detect
    motion:
      mask:
        - 312,50,932,50,928,0,314,0
    live:
      stream_name: camerabackyard_sub
    record:
      events:
        required_zones:
          - backyard_zone
          - lincoln_ave_zone
    snapshots:
      required_zones:
        - backyard_zone
        - lincoln_ave_zone
    zones:
      backyard_zone:
        coordinates: 0,720,1280,720,1280,249,884,125,562,73,0,138
        objects:
          - person
          - dog
          - cat
          - bird
      lincoln_ave_zone:
        coordinates: 1280,0,1280,236,936,137,577,68,577,0
        objects:
          - person
          - dog
```

### Relevant log output

```shell
2024-01-30 07:31:42.497087238  [INFO] Starting Frigate...
2024-01-30 07:31:43.326510366  [2024-01-30 07:31:43] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2024-01-30 07:31:43.364004913  [2024-01-30 07:31:43] peewee_migrate                 INFO    : Starting migrations
2024-01-30 07:31:43.367731630  [2024-01-30 07:31:43] peewee_migrate                 INFO    : There is nothing to migrate
2024-01-30 07:31:43.394084622  [2024-01-30 07:31:43] frigate.app                    INFO    : Output process started: 217
2024-01-30 07:31:43.402479106  [2024-01-30 07:31:43] detector.cpu                   INFO    : Starting detection process: 216
2024-01-30 07:31:43.405037445  [2024-01-30 07:31:43] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-01-30 07:31:43.405574403  [2024-01-30 07:31:43] frigate.app                    INFO    : Camera processor started for frontdoor_cam: 221
2024-01-30 07:31:43.421796833  [2024-01-30 07:31:43] frigate.app                    INFO    : Camera processor started for backyard_cam: 222
2024-01-30 07:31:43.428062668  [2024-01-30 07:31:43] frigate.app                    INFO    : Capture process started for frontdoor_cam: 224
2024-01-30 07:31:43.436205654  [2024-01-30 07:31:43] frigate.app                    INFO    : Capture process started for backyard_cam: 225
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink
