### ISSUE TITLE
[Support]: Frigate not starting

### ISSUE THREAD

**Issue by ofilin** [blakeblackshear/frigate#9511]
### Describe the problem you are having

After update to 0.13.0 Frigate not starting

### Version

0.13.0

### Frigate config file

```yaml
go2rtc:
  streams:
    rtsp_cam_ip193:
      - rtsp://IP
      - "ffmpeg:rtsp_cam#audio=opus"
    rtsp_cam_ip194:
      - rtsp://IP
      - "ffmpeg:rtsp_cam#audio=opus"

mqtt:
  host: IP
  user: frigate
  password: PASS

ffmpeg:
  global_args: -hide_banner -loglevel warning
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

# objects:
#   track: []

database:
  path: /config/frigate.db

objects:
  track:
    - person
    - cat

record:
  enabled: True
  events:
    retain:
      default: 3

motion:
  threshold: 25

cameras:
  ip193:
    ffmpeg:
      inputs:
        - path: rtsp://IP
          roles:
            - record
            - detect
            #- rtmp
    detect:
      width: 1280
      height: 720
  ip194:
    ffmpeg:
      inputs:
        - path: rtsp://IP
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
  cam41:
    ffmpeg:
      inputs:
        - path: rtsp://IP
          input_args: -rtsp_transport tcp -timeout 10000000
          roles:
            - record
            - detect
            #- rtmp
    detect:
      width: 1280
      height: 720


timestamp_style:
  position: "br"
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024-01-31 07:49:58.190223222  [INFO] Preparing Frigate...
2024-01-31 07:49:58.195085895  [INFO] Starting NGINX...
2024-01-31 07:49:58.348633767  nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 32
2024-01-31 07:49:58.368035240  [INFO] Service NGINX exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
2024-01-31 07:49:58.401372896  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-01-31 07:49:58.404837830  [INFO] Service Frigate exited with code 256 (by signal 15)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service frigate-log successfully stopped
2024-01-31 07:49:58.421859384  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink
