### ISSUE TITLE
[Config Support]: Modify stream presentation on Birdseye page 

### ISSUE THREAD

**Issue by tliaresq** [blakeblackshear/frigate#9513]
### Describe the problem you are having

I have 4 RTSP streams that are 5120x960 and the way Birdseye is stacking the streams is not really user friendly since the streams are so wide and short. I was wondering if it is possible to change how the streams are organized in Birdseye
Image for reference:
![Untitled drawing (1)](https://github.com/blakeblackshear/frigate/assets/14988689/0fc2c2e8-3818-4077-a7cb-ffe3619dc84d)

### Version

0.13.0

### Frigate config file

```yaml
mqtt:
  enabled: False

birdseye:
  mode: continuous
  
database:
  path: /config/frigate.db

detect:
  enabled: False
  
record:
  enabled: True
  sync_recordings: True
  retain:
    days: 1

go2rtc:
  streams:
    camera_0: exec:ffmpeg -rtsp_transport tcp -threads 1 -i rtsp://xxx:xxx@xxx/xxx -filter_complex "split=2[top][bottom];[top]crop=iw:ih/2:0:0,format=yuv420p[top];[bottom]crop=iw:ih/2:0:ih/2,format=yuv420p[bottom];[top][bottom]hstack,drawtext=fontfile=arial.ttf:text='%{{localtime\:%Y-%m-%d %H\\\:%M\\\:%S}}':x=20:y=20:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.5:boxborderw=5'" -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp {{output}}
    camera_1: exec:ffmpeg -rtsp_transport tcp -threads 1 -i rtsp://xxx:xxx@xxx/xxx -filter_complex "split=2[top][bottom];[top]crop=iw:ih/2:0:0,format=yuv420p[top];[bottom]crop=iw:ih/2:0:ih/2,format=yuv420p[bottom];[top][bottom]hstack,drawtext=fontfile=arial.ttf:text='%{{localtime\:%Y-%m-%d %H\\\:%M\\\:%S}}':x=20:y=20:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.5:boxborderw=5'" -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp {{output}}
    camera_2: exec:ffmpeg -rtsp_transport tcp -threads 1 -i rtsp://xxx:xxx@xxx/xxx -filter_complex "split=2[top][bottom];[top]crop=iw:ih/2:0:0,format=yuv420p[top];[bottom]crop=iw:ih/2:0:ih/2,format=yuv420p[bottom];[top][bottom]hstack,drawtext=fontfile=arial.ttf:text='%{{localtime\:%Y-%m-%d %H\\\:%M\\\:%S}}':x=20:y=20:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.5:boxborderw=5'" -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp {{output}}
    camera_3: exec:ffmpeg -rtsp_transport tcp -threads 1 -i rtsp://xxx:xxx@xxx/xxx -filter_complex "split=2[top][bottom];[top]crop=iw:ih/2:0:0,format=yuv420p[top];[bottom]crop=iw:ih/2:0:ih/2,format=yuv420p[bottom];[top][bottom]hstack,drawtext=fontfile=arial.ttf:text='%{{localtime\:%Y-%m-%d %H\\\:%M\\\:%S}}':x=20:y=20:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.5:boxborderw=5'" -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp {{output}}

cameras:
  camera_0:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_0
          roles:
            - record
    ui:
      order: 0
    birdseye:
      order: 0
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_1
          roles:
            - record
    ui:
      order: 1
    birdseye:
      order: 1
  camera_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2
          roles:
            - record
    ui:
      order: 2
    birdseye:
      order: 2
  camera_3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3
          roles:
            - record
    ui:
      order: 3
    birdseye:
      order: 3
```

### Relevant log output

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)
