### ISSUE TITLE
[Support]: migrate Home Assistant camera to image integration

### ISSUE THREAD

**Issue by TyzzyT** [blakeblackshear/frigate#9524]
### Describe the problem you are having

In the past, I used the camera.cameraname_person entity, to snapshot it with a Home Assistant service and make a capture of a specific moment. For example when the mailbox has been opened, I would snapshot the person camera entity 1 minute later.
I used it like this, but this is obviously not working anymore and there is no image.snapshot replacement service in HA
```
service: camera.snapshot
data:
  filename: /config/www/frontdoor_mailbox_randomtext.jpg
target:
  entity_id: image.frontdoor_person
```

Right now, the camera entity has been replaced by the image entity. This totally makes sense, because it is an image instead of a camera.
How can I snapshot/capture this image in Home Assistant?

### Version

0.13.0-49814B3

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired
