### ISSUE TITLE
[Config Support]:  Camera-entities "person" are gone with new Update

### ISSUE THREAD

**Issue by albotroz** [blakeblackshear/frigate#9531]
### Describe the problem you are having

I have just updated from the previous to the latest Frigate version 0.13.0 and Frigate Addon and immediately there was a problem.

In the dashboard I use Frigate Hass Cards in the vertical stack.
Previously, I set it so that the last events are still displayed under my livestreams in the vertical stack (person).

But now only yaml-code appears, because camera-entities "camera.location_person" are not selectable.

### Version

0.13.0

### Frigate config file

```yaml
type: vertical-stack
cards:
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.hof_person
    dimensions:
      aspect_ratio_mode: static
    view:
      update_force: true
      scan:
        untrigger_seconds: 10
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.front_person
    dimensions:
      aspect_ratio_mode: static
    view:
      update_force: true
      scan:
        untrigger_seconds: 10
```

### Relevant log output

```shell
no errors
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
