### ISSUE TITLE
[HW Accel Support]: Enable HW acceleration when exporting video

### ISSUE THREAD

**Issue by Shlyakhoff** [blakeblackshear/frigate#9536]
### Describe the problem you are having

It looks that doesn't work correctly hardware acceleration when I am trying to export video from camera in a given period of time.

HTOP shows following command for the process: ffmpeg -hide_banner -y -protocol_whitelist pipe,file -f concat -safe 0 -i /dev/stdin -c copy -movflags +faststart /tmp/cache/clip_cam3_1706713200-1706716799.mp4

When the process is going on the CPU usage is high because of HW acceleration is not used. I tried with both parameters of hwaccel_args - preset-vaapi and preset-intel-qsv-h264. At the time HW acceleration in other threads (transcoding, decoding, detection) is working correctly.

I think there is some issue in export.py file.

### Version

0.13

### Frigate config file

```yaml
database:
  path: /config/frigate.db

mqtt:
  enabled: true
  host: homeassistant.local
  port: 1883
  user: admin
  password: password
  topic_prefix: frigate
  client_id: frigate

ui:
  live_mode: mse
  use_experimental: false

birdseye:
  enabled: false

detect:
  enabled: false
  width: 320
  height: 176
  fps: 1

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

snapshots:
  enabled: true

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 12
    mode: all
  events:
    retain:
      default: 12

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

logger:
  default: error
  logs:
    frigate.mqtt: error
    frigate.app: error
    frigate.ffmpeg: critical

go2rtc:
  api:
    origin: '*'
  hass:
    config: /config
  log:
    format: text
    level: "error"
  rtsp:
    default_query: mp4
  streams:
    cam3:
    - rtsp://admin:password@192.168.1.62:554
    cam3_sub:
    - rtsp://admin:password@192.168.1.62:554/Streaming/channels/2
  webrtc:
    candidates:
    - stun:8555

cameras:
  cam3:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/cam3
        input_args: preset-rtsp-restream-low-latency
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/cam3_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      mask:
      - 0,176,110,176,110,155,0,155
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='bridge'
  --privileged=true
  -e TZ="Europe/Moscow"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="SERVER"
  -e HOST_CONTAINERNAME="frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='password'
  -e 'LIBVA_DRIVER_NAME'='iHD'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '5000:5000/tcp'
  -p '8554:8554/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -p '1984:1984/tcp'
  -v '/mnt/user/appdata/frigate':'/config':'rw'
  -v '/mnt/disks/cameras/':'/media/frigate':'rw,slave'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/dri/renderD128'
  --shm-size=256mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=2726297600
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:stable'
```

### Relevant log output

```shell
2024-01-31 21:59:45.970505599  [INFO] Preparing Frigate...
2024-01-31 21:59:46.053258660  [INFO] Starting Frigate...
2024-01-31 21:59:48.987277518  [2024-01-31 21:59:48] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
2024-01-31 21:59:49.074264350  [2024-01-31 21:59:49] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":288,"width":512},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Ezviz and several another chinese models
