### ISSUE TITLE
[Support]: Stuck starting go2rtc healthcheck since v0.13

### ISSUE THREAD

**Issue by BurningTheSky** [blakeblackshear/frigate#9537]
### Describe the problem you are having

Since upgrading to 0.13 the container doesn't seem to move past starting the go2rtc healthcheck service. I have tried restarting the container with no luck. I had placed version 1.8.4 of go2rtc in my config folder to fix another issue but I have deleted that and am getting the same blocker

### Version

0.13

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.45
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci
#  cuda:
#    type: tensorrt

go2rtc:
  log:
    exec: trace
  streams:
    Front:
     # - "ffmpeg:rtsp://user:password@192.168.0.54:554//Streaming/Channels/101/#video=copy#audio=aac#audio=opus"
     - "ffmpeg:rtsp://user:password@192.168.0.54:554//Streaming/Channels/101/#video=copy#audio=aac"
    Front247:
      - "rtsp://user:password@192.168.054:554//Streaming/Channels/102/"
    Driveway:
      - "ffmpeg:http://192.168.0.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus#hardware"
    Driveway247:
      - "ffmpeg:http://192.168.0.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password#hardware"
    Garage:
      - "ffmpeg:http://192.168.0.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus#hardware"
    Garage247:
      - "ffmpeg:http://192.168.0.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password#hardware"
    Garden:
      - "ffmpeg:http://192.168.0.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus#hardware"
    Garden247:
      - "ffmpeg:http://192.168.0.52/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password#hardware"
    Downstairs:
      - "rtsp://192.168.0.57/live0"
      - "ffmpeg:Downstairs#audio=aac#audio=opus#hardware"

cameras:
  # <------- Event record ------->

  Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy # was preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects
    motion:
      mask:
        - 595,0,640,0,640,87,619,72,588,46,549,23,497,0


  Driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garden247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - cat
        - dog
        - person
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage247?video
          input_args: preset-rtsp-restream
          roles:
            - detect
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    record:
      enabled: True
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  Downstairs: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Downstairs?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
          hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: true
      retain:
          days: 3
          mode: all
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 42
          mode: active_objects

  # <------- 24/7 record ------->

  Front_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all

  Driveway_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all

  Garage_247: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage247?video
          input_args: preset-rtsp-restream
          roles:
            - record
          hwaccel_args: preset-nvidia-h264
    record:
      enabled: True
      retain:
        days: 31
        mode: all
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service go2rtc-healthcheck successfully started
Generating the following TRT Models: yolov7-320
Downloading yolo weights
2024-01-31 19:01:44.267663765  [INFO] Preparing new go2rtc config...
2024-01-31 19:01:45.056118870  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2024-01-31 19:01:45.056126413  [INFO] Starting go2rtc...
2024-01-31 19:01:45.134236743  19:01:45.134 INF go2rtc version 1.8.4 linux/amd64
2024-01-31 19:01:45.134838567  19:01:45.134 INF [api] listen addr=:1984
2024-01-31 19:01:45.134926079  19:01:45.134 INF [rtsp] listen addr=:8554
2024-01-31 19:01:45.135258665  19:01:45.135 INF [webrtc] listen addr=:8555
2024-01-31 19:01:54.077261320  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
None
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

n/a
