### ISSUE TITLE
[Support]: My frigate container instance cannot be reached

### ISSUE THREAD

**Issue by obogle1986** [blakeblackshear/frigate#9539]
### Describe the problem you are having

I decided to upgrade from my HA yellow and have a commission a dedicated server running an Intel N100 on Proxmox and a frigate container on portainer. I followed the installation steps covered by [homeautomationguy.io](https://www.homeautomationguy.io/blog/running-frigate-on-proxmox) but I am unable to browse it via the port 5000 URL. I have also noticed that the IP address and published ports show up during the initial run but disappear shortly after.
![image](https://github.com/blakeblackshear/frigate/assets/35006235/de9add0e-a57a-45bf-b2ec-52b66b45a6f4)
![image](https://github.com/blakeblackshear/frigate/assets/35006235/a5840148-b22c-4de3-b173-9b6c4c22cfa9)
![image](https://github.com/blakeblackshear/frigate/assets/35006235/cdf93fe9-d5a5-4f06-b89f-10498849d688)

### Version

0.13.0 (unable to view debug page but it should be the latest)

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  front_doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://192.168.1.193:8554/front_doorbell?video=all&audio=all
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - rtmp
    live:
      stream_name: front_doorbell
    detect:
      width: 960 
      height: 1280
    zones:
      drive_way:
        coordinates: 0,669,105,619,960,632,960,1280,0,1280
    motion:
      mask:
      - 960,1280,960,1259,960,1229,960,1183,960,1113,960,1032,960,935,960,652,352,637,84,946,0,1047,0,1280
```

### Relevant log output

```shell
2024-01-31 19:44:35.081426113  [2024-01-31 19:44:35] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
2024-01-31 19:44:35.081429269  [2024-01-31 19:44:35] frigate.app                    INFO    : Creating directory: /config/model_cache
2024-01-31 19:44:36.245437751  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-01-31 19:44:36.255120429  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-01-31 19:44:36.313313193  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-01-31 19:44:36.318325568  exit with signal: terminated
s6-rc: info: service frigate-log successfully stopped
2024-01-31 19:44:36.322156627  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2024-01-31 19:45:40.605563258  [INFO] Preparing new go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-01-31 19:45:40.610541508  [INFO] Starting NGINX...
2024-01-31 19:45:40.625899988  [INFO] Preparing Frigate...
s6-rc: info: service legacy-services successfully started
2024-01-31 19:45:40.644841101  [INFO] Starting Frigate...
2024-01-31 19:45:40.809492255  [INFO] Starting go2rtc...
2024-01-31 19:45:40.876994981  19:45:40.876 INF go2rtc version 1.8.4 linux/amd64
2024-01-31 19:45:40.877331894  19:45:40.877 INF [rtsp] listen addr=:8554
2024-01-31 19:45:40.877505721  19:45:40.877 INF [webrtc] listen addr=:8555
2024-01-31 19:45:40.878563163  19:45:40.878 INF [api] listen addr=:1984
2024-01-31 19:45:41.754839200  [Errno 30] Read-only file system: '/config/model_cache'
2024-01-31 19:45:41.917725853  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-01-31 19:45:41.925325859  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-01-31 19:45:41.985656189  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2024-01-31 19:45:41.988846847  exit with signal: terminated
s6-rc: info: service frigate-log successfully stopped
2024-01-31 19:45:41.992592294  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
Unknown
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Google Nest Doorbell Gen2
