### ISSUE TITLE
[Support]: Multiple objects at the same time are being saved as individual event clips

### ISSUE THREAD

**Issue by supermarkert** [blakeblackshear/frigate#9540]
### Describe the problem you are having

Not sure if this is a bug or intended behavior, but it's definitely new with version 0.13.  
In this example noted below, a group of ~8 Persons walked by at the same time. While it was happening, there were 8 individual recording events In Progress. When complete, it saved 8 individual Event clips for the exact same period. 
Is this intended behavior? I only need one clip, showing all of the same persons at the same time. Each snapshot was of a different person in the group. It's like it was tracking each person individually and recording 8 concurrent streams. Neat, but I don't recall version 0.12 operating this way.  Is there any way to group this as one recorded event, and just keep recording until they're all out of frame?

![image](https://github.com/blakeblackshear/frigate/assets/15205204/8e6761d4-5fe9-4e10-b510-1ae24c8f0732)

### Version

0.13.0-01E2D20

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: homeassistant.lan
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  topic_prefix: frigate
#
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - cat
    - bird
    - sports ball
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 100
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 500000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.3
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 1.5
      threshold: 0.7
    dog:
      min_area: 100
      max_area: 100000
      min_ratio: 1.0
      max_ratio: 3.0
      threshold: 0.6
    cat:
      min_area: 100
      max_area: 100000
      min_ratio: 1.0
      max_ratio: 3.0
      threshold: 0.6
    bird:
      min_area: 10
      max_area: 2000
      min_ratio: 0.8
      max_ratio: 1.2
      threshold: 0.7
    sports ball:
      min_area: 5
      max_area: 200
      min_ratio: 0.9
      max_ratio: 1.1
      threshold: 0.7

record:
  enabled: True
  expire_interval: 60
  retain:
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    # objects:
    #   - person
    #   - dog
    #   - cat
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 14
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
birdseye:
  enabled: True
  mode: motion

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
go2rtc:
  log:
    format: text
    exec: trace
  webrtc:
    candidates:
      - 192.168.60.202:8555
      - stun:8555
  streams:
    camerafrontdoor:
      - "ffmpeg:http://192.168.40.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.21:554/h264Preview_01_main
#      - "ffmpeg:camerafrontdoor#audio=opus"
    camerafrontdoor_sub:
      - "ffmpeg:http://192.168.40.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}"
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.21:554/h264Preview_01_sub
#      - "ffmpeg:camerafrontdoor_sub#audio=opus"
#
    camerabackyard:
      # - "ffmpeg:http://192.168.40.22/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=iot&password=7wYMZ5qPzLjtNbo#video=copy#audio=copy#audio=opus"
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.22:554/h265Preview_01_main
      - "ffmpeg:camerabackyard#audio=opus"
    camerabackyard_sub:
      - "ffmpeg:http://192.168.40.22/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}"
      # - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.40.22:554/h264Preview_01_sub
      # - "ffmpeg:camerabackyard_sub#audio=opus"
cameras:
  frontdoor_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/camerafrontdoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camerafrontdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 494,27,497,0,149,0,149,32
    detect:
      width: 640
      height: 480
    live:
      stream_name: camerafrontdoor_sub
    record:
      events:
        required_zones:
          - frontporch_zone
          - frontstreet_zone
    snapshots:
      required_zones:
        - frontporch_zone
        - frontstreet_zone
    zones:
      frontporch_zone:
        coordinates: 640,480,640,419,516,368,324,371,155,370,0,325,0,480
        objects:
          - person
          - dog
          - cat
      frontstreet_zone:
        coordinates: 39,305,39,327,145,362,309,379,436,373,550,351,568,312,568,292,348,297,144,287
        objects:
          - person
          - dog
#
  backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camerabackyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camerabackyard_sub?video=copy
          input_args: preset-rtsp-restream
          hwaccel_args: preset-nvidia-h264
          roles:
            - detect
    motion:
      mask:
        - 213,41,664,46,663,0,218,0
    live:
      stream_name: camerabackyard_sub
    record:
      events:
        required_zones:
          - backyard_zone
          - lincoln_ave_zone
    snapshots:
      required_zones:
        - backyard_zone
        - lincoln_ave_zone
    zones:
      backyard_zone:
        coordinates: 0,512,896,512,896,181,715,112,401,51,402,27,0,89
        objects:
          - person
          - dog
          - cat
          - bird
      lincoln_ave_zone:
        coordinates: 896,0,896,167,699,104,400,50,404,0
        objects:
          - person
          - dog
```

### Relevant log output

```shell
2024-01-31 14:42:33.984563389  [INFO] Preparing Frigate...
2024-01-31 14:42:34.022788627  [INFO] Starting Frigate...
2024-01-31 14:42:35.136310126  [2024-01-31 14:42:35] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
2024-01-31 14:42:42.595071379  [2024-01-31 14:42:42] peewee_migrate.logs            INFO    : Starting migrations
2024-01-31 14:42:42.599533282  [2024-01-31 14:42:42] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-01-31 14:42:42.604072876  [2024-01-31 14:42:42] frigate.app                    INFO    : Recording process started: 236
2024-01-31 14:42:42.606489299  [2024-01-31 14:42:42] frigate.app                    INFO    : go2rtc process pid: 93
2024-01-31 14:42:42.641566046  [2024-01-31 14:42:42] frigate.app                    INFO    : Output process started: 247
2024-01-31 14:42:42.656986663  [2024-01-31 14:42:42] detector.cpu                   INFO    : Starting detection process: 246
2024-01-31 14:42:42.657207462  [2024-01-31 14:42:42] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-01-31 14:42:42.662446586  [2024-01-31 14:42:42] frigate.app                    INFO    : Camera processor started for frontdoor_cam: 252
2024-01-31 14:42:42.667403544  [2024-01-31 14:42:42] frigate.app                    INFO    : Camera processor started for backyard_cam: 253
2024-01-31 14:42:42.672342675  [2024-01-31 14:42:42] frigate.app                    INFO    : Capture process started for frontdoor_cam: 255
2024-01-31 14:42:42.677648374  [2024-01-31 14:42:42] frigate.app                    INFO    : Capture process started for backyard_cam: 256
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":2160,"width":3840},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":512,"width":896}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-822A
