### ISSUE TITLE
[Support]: Error when attempting to update to v13, seemingly related to db migration

### ISSUE THREAD

**Issue by ksheyman** [blakeblackshear/frigate#9541]
### Describe the problem you are having

Error when attempting to update from v12 to v13. 

This is a secondary Frigate instance I only use for my 3d printer cameras, I was testing the upgrade to v13 on this instance before applying it to my main instance and I am getting errors. Seems like an error when migrating the db to the new default location. I am seeing both 'frigate_old.db' and 'frigate.db' in my /config directory. I think I had previously tried to update to a v13 beta and got this error and rolled back, not sure if that matters. Mostly wondering if I need to worry about updating my main instance to v13.0, but the main instance is already on v13b7...

### Version

v13.0

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate_printers
    privileged: True # 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0 
    shm_size: "1024mb"  
    devices:
      - /dev/dri/renderD129
      - /dev/dri/card1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker-compose/docker-data/frigate_printers/config:/config
      - /home/user/media/nas_frigate_storage/printers:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5005:5000"
      - "1936:1935"
      - "8555:8554"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]        


mqtt:
  host: 192.168.2.137
  user: mqtt
  password: mqtt
  client_id: frigate_printers
  topic_prefix: frigate_printers
  

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 1
      mode: motion

ffmpeg:
  hwaccel_args: preset-nvidia-h264
live:
  height: 1080
  quality: 1

motion:
  threshold: 50
#  countour_area: 50

go2rtc:
  streams:
    prusa_mini:
      - rtsp://admin:pass@192.168.1.73:554/cam/realmonitor?channel=1&subtype=0
    prusa_mk4:
      - rtsp://192.168.3.146:7447/6dVYKUmQfnzvtXDc #?enableSrtp
    prusa_mk3:
      - rtsp://admin:pass@192.168.1.78:554/cam/realmonitor?channel=1&subtype=0
    prusa_mmu:
      - rtsp://admin:pass@192.168.1.72:554/cam/realmonitor?channel=1&subtype=0
    ender_5:
      - rtsp://admin:pass@192.168.2.104:554/cam/realmonitor?channel=1&subtype=0
    ender_5_wide:
      - rtsp://admin:pass@192.168.1.65:554/cam/realmonitor?channel=1&subtype=0
    prusa_mini_sub:
      - rtsp://admin:pass@192.168.1.73:554/cam/realmonitor?channel=1&subtype=1
    prusa_mk4_sub:
      - rtsp://192.168.3.146:7447/JMwrdFFiBiclJ0J8  
    prusa_mk3_sub:
      - rtsp://admin:pass@192.168.1.78:554/cam/realmonitor?channel=1&subtype=1
    prusa_mmu_sub:
      - rtsp://admin:pass@192.168.1.72:554/cam/realmonitor?channel=1&subtype=1
    ender_5_sub:
      - rtsp://admin:pass@192.168.2.104:554/cam/realmonitor?channel=1&subtype=1  
    ender_5_wide_sub:
      - rtsp://admin:pass@192.168.1.65:554/cam/realmonitor?channel=1&subtype=1 



birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 1
  restream: True
  mode: motion



cameras:

  prusa_mini:
    ffmpeg:
      inputs: 
        - path: rtsp://192.168.2.137:8555/prusa_mini
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.2.137:8555/prusa_mini_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    birdseye:
      enabled: True
      mode: motion  
    ui:
      order: 3      

  prusa_mk4:
    ffmpeg:
      inputs: 
        - path: rtsp://192.168.2.137:8555/prusa_mk4
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.2.137:8555/prusa_mk4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    birdseye:
      enabled: True
      mode: motion  
    ui:
      order: 6      

  prusa_mk3:
    ffmpeg:
      inputs: 
        - path: rtsp://192.168.2.137:8555/prusa_mk3
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.2.137:8555/prusa_mk3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    birdseye:
      enabled: True
      mode: motion  
    ui:
      order: 2      

  prusa_mmu:        
    ffmpeg:
      inputs: 
        - path: rtsp://192.168.2.137:8555/prusa_mmu
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.2.137:8555/prusa_mmu_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    birdseye:
      enabled: True
      mode: motion  
    ui:
      order: 5    
      
  ender_5:        
    ffmpeg:
      inputs: 
        - path: rtsp://192.168.2.137:8555/ender_5
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.2.137:8555/ender_5_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    birdseye:
      enabled: False
#      mode: motion  
    ui:
      order: 4          
      

  ender_5_wide:        
    ffmpeg:
      inputs: 
        - path: rtsp://192.168.2.137:8555/ender_5_wide
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.2.137:8555/ender_5_wide_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    birdseye:
      enabled: False
#      mode: motion  
    ui:
      order: 4
```

### Relevant log output

```shell
frigate_printers | 2024-01-31 16:00:25.349023150  [INFO] Preparing Frigate...
frigate_printers | 2024-01-31 16:00:25.349322942  [INFO] Starting NGINX...
frigate_printers | s6-rc: info: service legacy-services successfully started
frigate_printers | 2024-01-31 16:00:25.351262884  [INFO] Preparing new go2rtc config...
frigate_printers | 2024-01-31 16:00:25.359117170  [INFO] Starting Frigate...
frigate_printers | 2024-01-31 16:00:25.636638280  [INFO] Starting go2rtc...
frigate_printers | 2024-01-31 16:00:25.701860017  16:00:25.701 INF go2rtc version 1.8.4 linux/amd64
frigate_printers | 2024-01-31 16:00:25.702342113  16:00:25.702 INF [api] listen addr=:1984
frigate_printers | 2024-01-31 16:00:25.702701547  16:00:25.702 INF [rtsp] listen addr=:8554
frigate_printers | 2024-01-31 16:00:25.702703499  16:00:25.702 INF [webrtc] listen addr=:8555
frigate_printers | 2024-01-31 16:00:26.391995082  [2024-01-31 16:00:26] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
frigate_printers | 2024-01-31 16:00:26.421623145  [2024-01-31 16:00:26] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
frigate_printers | 2024-01-31 16:00:26.434482378  [2024-01-31 16:00:26] peewee_migrate.logs            INFO    : Starting migrations
frigate_printers | 2024-01-31 16:00:26.447989815  [2024-01-31 16:00:26] peewee_migrate.logs            INFO    : Migrate "014_event_updates_for_fp"
frigate_printers | 2024-01-31 16:00:26.448053504  [2024-01-31 16:00:26] peewee_migrate.logs            INFO    : add_column ('event', 'score', <FloatField: Event.score>)
frigate_printers | 2024-01-31 16:00:26.449191312  duplicate column name: score
frigate_printers | 2024-01-31 16:00:26.449419438  [2024-01-31 16:00:26] peewee_migrate.logs            ERROR   : Migration failed: 014_event_updates_for_fp
frigate_printers | 2024-01-31 16:00:26.449421383  Traceback (most recent call last):
frigate_printers | 2024-01-31 16:00:26.449426419    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
frigate_printers | 2024-01-31 16:00:26.449428005      cursor.execute(sql, params or ())
frigate_printers | 2024-01-31 16:00:26.449429385  sqlite3.OperationalError: duplicate column name: score
frigate_printers | 2024-01-31 16:00:26.449430937
frigate_printers | 2024-01-31 16:00:26.449432064  During handling of the above exception, another exception occurred:
frigate_printers | 2024-01-31 16:00:26.449451748
frigate_printers | 2024-01-31 16:00:26.449452699  Traceback (most recent call last):
frigate_printers | 2024-01-31 16:00:26.449454013    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/router.py", line 200, in run_one
frigate_printers | 2024-01-31 16:00:26.449455083      migrator()
frigate_printers | 2024-01-31 16:00:26.449456277    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/migrator.py", line 76, in __call__
frigate_printers | 2024-01-31 16:00:26.449477199      op.run()
frigate_printers | 2024-01-31 16:00:26.449478293    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
frigate_printers | 2024-01-31 16:00:26.449479604      self._handle_result(method(*self.args, **kwargs))
frigate_printers | 2024-01-31 16:00:26.449480860    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 156, in _handle_result
frigate_printers | 2024-01-31 16:00:26.449492612      self._handle_result(item)
frigate_printers | 2024-01-31 16:00:26.449493723    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 153, in _handle_result
frigate_printers | 2024-01-31 16:00:26.449494578      result.run()
frigate_printers | 2024-01-31 16:00:26.449495713    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
frigate_printers | 2024-01-31 16:00:26.449496578      self._handle_result(method(*self.args, **kwargs))
frigate_printers | 2024-01-31 16:00:26.449507781    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 151, in _handle_result
frigate_printers | 2024-01-31 16:00:26.449508646      self.execute(result)
frigate_printers | 2024-01-31 16:00:26.449509680    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 147, in execute
frigate_printers | 2024-01-31 16:00:26.449510599      self.migrator.database.execute(node)
frigate_printers | 2024-01-31 16:00:26.449511590    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3260, in execute
frigate_printers | 2024-01-31 16:00:26.449512400      return self.execute_sql(sql, params)
frigate_printers | 2024-01-31 16:00:26.449513389    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
frigate_printers | 2024-01-31 16:00:26.449526210      cursor.execute(sql, params or ())
frigate_printers | 2024-01-31 16:00:26.449527077    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3020, in __exit__
frigate_printers | 2024-01-31 16:00:26.449527796      reraise(new_type, new_type(exc_value, *exc_args), traceback)
frigate_printers | 2024-01-31 16:00:26.449528518    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
frigate_printers | 2024-01-31 16:00:26.449529248      raise value.with_traceback(tb)
frigate_printers | 2024-01-31 16:00:26.449530100    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
frigate_printers | 2024-01-31 16:00:26.449530803      cursor.execute(sql, params or ())
frigate_printers | 2024-01-31 16:00:26.449531509  peewee.OperationalError: duplicate column name: score
frigate_printers | 2024-01-31 16:00:27.688389294  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate_printers | s6-rc: info: service legacy-services: stopping
frigate_printers | s6-rc: info: service legacy-services successfully stopped
frigate_printers | s6-rc: info: service nginx: stopping
frigate_printers | s6-rc: info: service go2rtc-healthcheck: stopping
frigate_printers | 2024-01-31 16:00:27.704638743  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate_printers | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate_printers | 2024-01-31 16:00:27.766640622  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate_printers | s6-rc: info: service nginx successfully stopped
frigate_printers | s6-rc: info: service nginx-log: stopping
frigate_printers | s6-rc: info: service frigate: stopping
frigate_printers | s6-rc: info: service frigate successfully stopped
frigate_printers | s6-rc: info: service go2rtc: stopping
frigate_printers | s6-rc: info: service frigate-log: stopping
frigate_printers | s6-rc: info: service nginx-log successfully stopped
frigate_printers | 2024-01-31 16:00:27.768363520  exit with signal: terminated
frigate_printers | s6-rc: info: service frigate-log successfully stopped
frigate_printers | 2024-01-31 16:00:27.771456381  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate_printers | s6-rc: info: service go2rtc successfully stopped
frigate_printers | s6-rc: info: service go2rtc-log: stopping
frigate_printers | s6-rc: info: service go2rtc-log successfully stopped
frigate_printers | s6-rc: info: service log-prepare: stopping
frigate_printers | s6-rc: info: service s6rc-fdholder: stopping
frigate_printers | s6-rc: info: service log-prepare successfully stopped
frigate_printers | s6-rc: info: service legacy-cont-init: stopping
frigate_printers | s6-rc: info: service s6rc-fdholder successfully stopped
frigate_printers | s6-rc: info: service legacy-cont-init successfully stopped
frigate_printers | s6-rc: info: service fix-attrs: stopping
frigate_printers | s6-rc: info: service fix-attrs successfully stopped
frigate_printers | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate_printers | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate_printers | s6-rc: info: service s6rc-fdholder: starting
frigate_printers | s6-rc: info: service s6rc-oneshot-runner: starting
frigate_printers | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate_printers | s6-rc: info: service fix-attrs: starting
frigate_printers | s6-rc: info: service s6rc-fdholder successfully started
frigate_printers | s6-rc: info: service fix-attrs successfully started
frigate_printers | s6-rc: info: service legacy-cont-init: starting
frigate_printers | s6-rc: info: service legacy-cont-init successfully started
frigate_printers | s6-rc: info: service log-prepare: starting
frigate_printers | s6-rc: info: service log-prepare successfully started
frigate_printers | s6-rc: info: service nginx-log: starting
frigate_printers | s6-rc: info: service go2rtc-log: starting
frigate_printers | s6-rc: info: service frigate-log: starting
frigate_printers | s6-rc: info: service go2rtc-log successfully started
frigate_printers | s6-rc: info: service go2rtc: starting
frigate_printers | s6-rc: info: service nginx-log successfully started
frigate_printers | s6-rc: info: service frigate-log successfully started
frigate_printers | s6-rc: info: service go2rtc successfully started
frigate_printers | s6-rc: info: service go2rtc-healthcheck: starting
frigate_printers | s6-rc: info: service frigate: starting
frigate_printers | s6-rc: info: service go2rtc-healthcheck successfully started
frigate_printers | 2024-01-31 16:01:32.513772697  [INFO] Preparing Frigate...
frigate_printers | s6-rc: info: service frigate successfully started
frigate_printers | s6-rc: info: service nginx: starting
frigate_printers | 2024-01-31 16:01:32.514283346  [INFO] Preparing new go2rtc config...
frigate_printers | s6-rc: info: service nginx successfully started
frigate_printers | s6-rc: info: service legacy-services: starting
frigate_printers | 2024-01-31 16:01:32.517193965  [INFO] Starting NGINX...
frigate_printers | s6-rc: info: service legacy-services successfully started
frigate_printers | 2024-01-31 16:01:32.530513868  [INFO] Starting Frigate...
frigate_printers | 2024-01-31 16:01:32.780308972  [INFO] Starting go2rtc...
frigate_printers | 2024-01-31 16:01:32.855021166  16:01:32.854 INF go2rtc version 1.8.4 linux/amd64
frigate_printers | 2024-01-31 16:01:32.855462067  16:01:32.855 INF [rtsp] listen addr=:8554
frigate_printers | 2024-01-31 16:01:32.855517373  16:01:32.855 INF [api] listen addr=:1984
frigate_printers | 2024-01-31 16:01:32.855657336  16:01:32.855 INF [webrtc] listen addr=:8555
frigate_printers | 2024-01-31 16:01:33.617731826  [2024-01-31 16:01:33] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
frigate_printers | 2024-01-31 16:01:33.647127611  [2024-01-31 16:01:33] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
frigate_printers | 2024-01-31 16:01:33.661081044  [2024-01-31 16:01:33] peewee_migrate.logs            INFO    : Starting migrations
frigate_printers | 2024-01-31 16:01:33.675744139  [2024-01-31 16:01:33] peewee_migrate.logs            INFO    : Migrate "014_event_updates_for_fp"
frigate_printers | 2024-01-31 16:01:33.675805423  [2024-01-31 16:01:33] peewee_migrate.logs            INFO    : add_column ('event', 'score', <FloatField: Event.score>)
frigate_printers | 2024-01-31 16:01:33.677205781  duplicate column name: score
frigate_printers | 2024-01-31 16:01:33.677373433  [2024-01-31 16:01:33] peewee_migrate.logs            ERROR   : Migration failed: 014_event_updates_for_fp
frigate_printers | 2024-01-31 16:01:33.677375205  Traceback (most recent call last):
frigate_printers | 2024-01-31 16:01:33.677379925    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
frigate_printers | 2024-01-31 16:01:33.677381335      cursor.execute(sql, params or ())
frigate_printers | 2024-01-31 16:01:33.677382470  sqlite3.OperationalError: duplicate column name: score
frigate_printers | 2024-01-31 16:01:33.677383808
frigate_printers | 2024-01-31 16:01:33.677384969  During handling of the above exception, another exception occurred:
frigate_printers | 2024-01-31 16:01:33.677404628
frigate_printers | 2024-01-31 16:01:33.677405781  Traceback (most recent call last):
frigate_printers | 2024-01-31 16:01:33.677406998    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/router.py", line 200, in run_one
frigate_printers | 2024-01-31 16:01:33.677407870      migrator()
frigate_printers | 2024-01-31 16:01:33.677408958    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/migrator.py", line 76, in __call__
frigate_printers | 2024-01-31 16:01:33.677435530      op.run()
frigate_printers | 2024-01-31 16:01:33.677436847    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
frigate_printers | 2024-01-31 16:01:33.677438219      self._handle_result(method(*self.args, **kwargs))
frigate_printers | 2024-01-31 16:01:33.677439287    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 156, in _handle_result
frigate_printers | 2024-01-31 16:01:33.677453063      self._handle_result(item)
frigate_printers | 2024-01-31 16:01:33.677454302    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 153, in _handle_result
frigate_printers | 2024-01-31 16:01:33.677455311      result.run()
frigate_printers | 2024-01-31 16:01:33.677456427    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
frigate_printers | 2024-01-31 16:01:33.677457334      self._handle_result(method(*self.args, **kwargs))
frigate_printers | 2024-01-31 16:01:33.677469194    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 151, in _handle_result
frigate_printers | 2024-01-31 16:01:33.677470066      self.execute(result)
frigate_printers | 2024-01-31 16:01:33.677471022    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 147, in execute
frigate_printers | 2024-01-31 16:01:33.677471971      self.migrator.database.execute(node)
frigate_printers | 2024-01-31 16:01:33.677473122    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3260, in execute
frigate_printers | 2024-01-31 16:01:33.677473967      return self.execute_sql(sql, params)
frigate_printers | 2024-01-31 16:01:33.677474985    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
frigate_printers | 2024-01-31 16:01:33.677491418      cursor.execute(sql, params or ())
frigate_printers | 2024-01-31 16:01:33.677492634    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3020, in __exit__
frigate_printers | 2024-01-31 16:01:33.677493778      reraise(new_type, new_type(exc_value, *exc_args), traceback)
frigate_printers | 2024-01-31 16:01:33.677494924    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
frigate_printers | 2024-01-31 16:01:33.677496061      raise value.with_traceback(tb)
frigate_printers | 2024-01-31 16:01:33.677497133    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
frigate_printers | 2024-01-31 16:01:33.677498164      cursor.execute(sql, params or ())
frigate_printers | 2024-01-31 16:01:33.677499294  peewee.OperationalError: duplicate column name: score
frigate_printers | 2024-01-31 16:01:34.887042211  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate_printers | s6-rc: info: service legacy-services: stopping
frigate_printers | s6-rc: info: service legacy-services successfully stopped
frigate_printers | s6-rc: info: service nginx: stopping
frigate_printers | s6-rc: info: service go2rtc-healthcheck: stopping
frigate_printers | 2024-01-31 16:01:34.894287689  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate_printers | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate_printers | 2024-01-31 16:01:34.965723844  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate_printers | s6-rc: info: service nginx successfully stopped
frigate_printers | s6-rc: info: service nginx-log: stopping
frigate_printers | s6-rc: info: service frigate: stopping
frigate_printers | s6-rc: info: service frigate successfully stopped
frigate_printers | s6-rc: info: service go2rtc: stopping
frigate_printers | s6-rc: info: service frigate-log: stopping
frigate_printers | s6-rc: info: service nginx-log successfully stopped
frigate_printers | 2024-01-31 16:01:34.967229979  exit with signal: terminated
frigate_printers | s6-rc: info: service frigate-log successfully stopped
frigate_printers | 2024-01-31 16:01:34.970138992  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate_printers | s6-rc: info: service go2rtc successfully stopped
frigate_printers | s6-rc: info: service go2rtc-log: stopping
frigate_printers | s6-rc: info: service go2rtc-log successfully stopped
frigate_printers | s6-rc: info: service log-prepare: stopping
frigate_printers | s6-rc: info: service s6rc-fdholder: stopping
frigate_printers | s6-rc: info: service log-prepare successfully stopped
frigate_printers | s6-rc: info: service legacy-cont-init: stopping
frigate_printers | s6-rc: info: service s6rc-fdholder successfully stopped
frigate_printers | s6-rc: info: service legacy-cont-init successfully stopped
frigate_printers | s6-rc: info: service fix-attrs: stopping
frigate_printers | s6-rc: info: service fix-attrs successfully stopped
frigate_printers | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate_printers | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Various
