### ISSUE TITLE
[Config Support]: Object Mask Editor does not copy results displayed in editor

### ISSUE THREAD

**Issue by ElksInNC** [blakeblackshear/frigate#9542]
### Describe the problem you are having

When editing an object mask in the Editor under Debug for camera, the results displayed in the editor do not actually get copied to the clipboard.  The array is truncated.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.xxxxxxxxxx
  port: 1883
  user: mqttuser
  password: xxxxxxxxxxx

detectors:
 coral:
   type: edgetpu
   device: pci

birdseye:
 enabled: true
 restream: true

go2rtc:
 streams:
   doorbellcam_substream:
     - rtsp://admin:xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1
   doorbellcam_2wayaudio_button_disabled:
     - rtsp://xxxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
   doorbellcam_main:
     - "ffmpeg:rtsp://xxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0#backchannel=0#video=copy#audio=copy#audio=aac#hardware=vaapi"
   sidewalkcam_substream:
     - rtsp://xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1
   sidewalkcam_main:
     - "ffmpeg:rtsp://xxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0#backchannel=0#video=copy#audio=copy#audio=aac#hardware=vaapi"
   #sidewalkcam_detect:
   #  - "ffmpeg:sidewalkcam_main#video=h264#width=1280#height=960#raw=-fpsmax 5#audio=copy#audio=aac#hardware=vaapi"
   candidates:
     - 192.168.xxxxxxxxx:8555
     - stun:8555


cameras:
 doorbell_cam:
   ffmpeg:
     hwaccel_args: preset-vaapi
     output_args:
       record: preset-record-generic-audio-copy
     inputs:
       - path: rtsp://127.0.0.1:8554/doorbellcam_main
         roles:
           - record
       - path: rtsp://127.0.0.1:8554/doorbellcam_substream
         roles:
           - detect
   detect:
     width: 720
     height: 576
   snapshots:
     enabled: true
     timestamp: false
     bounding_box: true
     retain:
       default: 10
   ui:
     order: 2
   record:
     enabled: True
     retain:
       days: 7
       mode: motion
     events:
#       required_zones:
#         - zone_0
       retain:
         default: 14
         mode: active_objects
   zones:
    frontsteps:
      coordinates: 434,247,427,488,339,576,16,564,11,282
    frontporch:
      coordinates: 716,576,296,573,404,479,416,123,718,4,720,176
   motion:
    mask:
      - 0,307,197,330,417,351,420,147,561,104,549,0,429,0,267,0,0,0
 sidewalk_cam:
   ffmpeg:
     hwaccel_args: preset-vaapi
     output_args:
       record: preset-record-generic-audio-copy
     inputs:
       - path: rtsp://127.0.0.1:8554/sidewalkcam_main
         roles:
           - record
       - path: rtsp://127.0.0.1:8554/sidewalkcam_substream
         roles:
           - detect
   detect:
     width: 704
     height: 480
   snapshots:
     enabled: true
     timestamp: false
     bounding_box: true
     retain:
       default: 10
   ui:
     order: 1
   record:
     enabled: True
     retain:
       days: 7
       mode: motion
     events:
#       required_zones:
#        - zone_0
       retain:
         default: 14
         mode: active_objects
   zones:
    driveway-east:
      coordinates: 34,174,151,104,199,93,189,51,105,63,0,130
    driveway-west:
      coordinates: 318,0,377,0,362,27,301,60,213,87,204,37
    sidewalk-north:
      coordinates: 370,200,382,315,169,375,35,365,0,268,58,218,88,145,195,101
    sidewalk-south:
      coordinates: 581,222,704,278,704,480,654,480,611,388,376,320,378,189
   motion:
    mask:
      - 701,0,704,133,647,52,539,22,424,14,377,4,308,7,241,19,124,41,2,100,1,0

objects:
 # Optional: list of objects to track from labelmap.txt (default: shown below)
 track:
   - person
   - dog
   - car
   - book


database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db
```

### Relevant log output

```shell
Nothing relevant
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.2"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"1056":{"cpu":"0.0","mem":"0.0"},"108":{"cpu":"5.0","mem":"1.6"},"1087":{"cpu":"0.7","mem":"0.0"},"1089":{"cpu":"0.0","mem":"0.0"},"1097":{"cpu":"0.3","mem":"0.0"},"1100":{"cpu":"0.3","mem":"0.0"},"116":{"cpu":"0.0","mem":"0.1"},"123":{"cpu":"0.0","mem":"0.1"},"124":{"cpu":"0.0","mem":"0.1"},"125":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.0","mem":"0.1"},"14":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"23":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"278":{"cpu":"0.0","mem":"0.7"},"28":{"cpu":"0.0","mem":"0.0"},"284":{"cpu":"0.0","mem":"0.1"},"285":{"cpu":"0.0","mem":"0.9"},"287":{"cpu":"1.0","mem":"0.8"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.0","mem":"0.1"},"291":{"cpu":"0.0","mem":"0.3"},"292":{"cpu":"0.7","mem":"0.8"},"293":{"cpu":"1.0","mem":"0.8"},"294":{"cpu":"1.7","mem":"0.7"},"30":{"cpu":"0.0","mem":"0.0"},"307":{"cpu":"2.0","mem":"0.7"},"31":{"cpu":"0.0","mem":"0.0"},"311":{"cpu":"0.7","mem":"0.4"},"313":{"cpu":"3.7","mem":"0.4"},"320":{"cpu":"2.7","mem":"0.5"},"323":{"cpu":"0.3","mem":"0.2"},"324":{"cpu":"2.0","mem":"0.2"},"325":{"cpu":"6.0","mem":"0.2"},"326":{"cpu":"10.6","mem":"0.2"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"76":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"92":{"cpu":"5.6","mem":"0.2"},"MiB":{"cpu":"9020.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":13.52,"pid":285}},"doorbell_cam":{"camera_fps":5.0,"capture_pid":294,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":313,"pid":292,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"0.65 %","mem":"- %"}},"service":{"last_updated":1706736561,"latest_version":"0.13.0","storage":{"/dev/shm":{"free":130.6,"mount_type":"tmpfs","total":134.2,"used":3.6},"/media/frigate/clips":{"free":9607478.1,"mount_type":"cifs","total":11854078.7,"used":2246600.6},"/media/frigate/recordings":{"free":9607478.1,"mount_type":"cifs","total":11854078.7,"used":2246600.6},"/tmp/cache":{"free":1063.2,"mount_type":"tmpfs","total":1073.7,"used":10.5}},"temperatures":{"apex_0":47.55},"uptime":582,"version":"0.12.1-367d724"},"sidewalk_cam":{"camera_fps":5.0,"capture_pid":307,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":320,"pid":293,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

Chrom Version 121.0.6167.85 (Official Build) (x86_64) - Mac OS Ventura
Screenshot of editor after clicking on video and creating a 4 sided poly. (book)
![Screenshot 2024-01-31 at 16 22 22](https://github.com/blakeblackshear/frigate/assets/77821967/088f99d9-fd8b-49b3-b8cb-6a8e0d24d821)

Screenshot of resulting PASTE into CONFIG EDITOR
![image](https://github.com/blakeblackshear/frigate/assets/77821967/367d3fc3-eb1c-470d-b9ea-1cd81f9295d3)
