### ISSUE TITLE
[Config Support]: Moving to Go2RTC, but no more sound on recordings

### ISSUE THREAD

**Issue by RobHofmann** [blakeblackshear/frigate#9546]
### Describe the problem you are having

I used to have a config that gave me 24/7 recordings with audio. Today i've moved to the latest frigate and switched to go2rtc. In this process I seem to have lost the audio in the recordings. I'm looking for someone what can help me with this config to re-enable audio.
I've got 6 camera's:
- 3x DH-SD1A404XB-GNR
- 2x Foscam C1
- 1x Foscam R2M

## Old config:
```yaml
mqtt:
  host: mosquittomqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: <redacted>
  stats_interval: 60
birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous
cameras:
  voortuin:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      filters:
        car:
          mask:
            - 443,460,593,288,734,247,842,210,997,172,1274,166,1396,284,1441,486,521,710
    motion:
      mask:
        - 194,0,670,0,1035,0,1382,0,1744,0,1920,0,1920,192,1827,167,1319,123,726,155,397,203,0,308,0,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 1080
  achtertuin:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 1080
  parkeerplek:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      filters:
        bicycle:
          mask:
            - 366,0,373,66,243,99,234,23
        car:
          mask:
            - 1131,112,1920,303,1920,643,1246,374,363,147,420,55,743,56
            - 622,361,901,353,1127,443,1344,586,1559,784,1478,1080,786,1080,309,611,297,442
            - 366,0,373,66,243,99,234,23
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 1080
  woonkamer:
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@<redacted>:554/videoMain
          roles:
            - record
            - rtmp
        - path: rtsp://<redacted>:<redacted>@<redacted>:554/videoSub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
  master_bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@<redacted>:554/videoMain
          roles:
            - record
            - rtmp
        - path: rtsp://<redacted>:<redacted>@<redacted>:554/videoSub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
  slaapkamer_puck:
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@<redacted>:88/videoMain
          roles:
            - record
            - rtmp
        - path: rtsp://<redacted>:<redacted>@<redacted>:88/videoSub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
record:
  enabled: true
  retain:
    days: 7
  events:
    retain:
      default: 14
detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5
rtmp:
  enabled: true
detectors:
  coral:
    type: edgetpu
    device: usb
objects:
  track:
    - person
    - cat
    - car
    - bicycle
    - motorcycle
    - bus
    - dog
logger:
  default: info
```

## New/current config:
```yaml
# yaml-language-server: $schema=http://<redacted>:5000/api/config/schema.json
mqtt:
  host: mosquittomqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: <redacted>
  stats_interval: 60
birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous
  restream: true
cameras:
  voortuin:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/voortuin?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/voortuin?video
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 15
    objects:
      filters:
        car:
          mask:
            - 443,460,593,288,734,247,842,210,997,172,1274,166,1396,284,1441,486,521,710
    motion:
      mask:
        - 194,0,670,0,1035,0,1382,0,1744,0,1920,0,1920,192,1827,167,1319,123,726,155,397,203,0,308,0,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 1080
  achtertuin:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/achtertuin?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/achtertuin?video
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 1080
  parkeerplek:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/parkeerplek?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/parkeerplek?video
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      filters:
        bicycle:
          mask:
            - 366,0,373,66,243,99,234,23
        car:
          mask:
            - 1131,112,1920,303,1920,643,1246,374,363,147,420,55,743,56
            - 622,361,901,353,1127,443,1344,586,1559,784,1478,1080,786,1080,309,611,297,442
            - 366,0,373,66,243,99,234,23
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 1080
  woonkamer:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/woonkamer?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/woonkamer?video
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
  master_bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/master_bedroom?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/master_bedroom?video
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 480
      fps: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
  slaapkamer_puck:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/slaapkamer_puck?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/slaapkamer_puck?video
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
      fps: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
record:
  enabled: true
  retain:
    days: 7
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
go2rtc:
  streams:
    voortuin:
      - rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=0
    achtertuin:
      - rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=0
    parkeerplek:
      - rtsp://admin:<redacted>@<redacted>:554/cam/realmonitor?channel=1&subtype=0
    woonkamer:
      - rtsp://robhofmann:<redacted>@<redacted>:554/videoMain
    master_bedroom:
      - rtsp://robhofmann:<redacted>@<redacted>:554/videoMain
    slaapkamer_puck:
      - rtsp://robhofmann:<redacted>@<redacted>:88/videoMain
rtmp:
  enabled: false
detectors:
  coral:
    type: edgetpu
    device: usb
objects:
  track:
    - person
    - cat
    - car
    - bicycle
    - motorcycle
    - bus
    - dog
logger:
  default: info
```

### Version

0.13.0-01E2D20

### Relevant log output

```shell
2024-02-01 01:27:35.117945162  [INFO] Preparing Frigate...
2024-02-01 01:27:35.118661910  [INFO] Starting NGINX...
2024-02-01 01:27:35.121207035  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-02-01 01:27:35.129897738  [INFO] Starting Frigate...
2024-02-01 01:27:35.379542745  [INFO] Starting go2rtc...
2024-02-01 01:27:35.497162050  01:27:35.497 INF go2rtc version 1.8.4 linux/amd64
2024-02-01 01:27:35.497814555  01:27:35.497 INF [api] listen addr=:1984
2024-02-01 01:27:35.497927528  01:27:35.497 INF [rtsp] listen addr=:8554
2024-02-01 01:27:35.498140574  01:27:35.498 INF [webrtc] listen addr=:8555
2024-02-01 01:27:36.388379282  [2024-02-01 01:27:36] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
2024-02-01 01:27:36.452852732  [2024-02-01 01:27:36] peewee_migrate.logs            INFO    : Starting migrations
2024-02-01 01:27:36.456539185  [2024-02-01 01:27:36] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-01 01:27:36.460576533  [2024-02-01 01:27:36] frigate.app                    INFO    : Recording process started: 728
2024-02-01 01:27:36.462602799  [2024-02-01 01:27:36] frigate.app                    INFO    : go2rtc process pid: 93
2024-02-01 01:27:36.486092284  [2024-02-01 01:27:36] detector.coral                 INFO    : Starting detection process: 738
2024-02-01 01:27:39.149894497  [2024-02-01 01:27:36] frigate.app                    INFO    : Output process started: 740
2024-02-01 01:27:39.150022760  [2024-02-01 01:27:36] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-02-01 01:27:39.150328439  [2024-02-01 01:27:36] frigate.app                    INFO    : Camera processor started for voortuin: 752
2024-02-01 01:27:39.150383532  [2024-02-01 01:27:36] frigate.app                    INFO    : Camera processor started for achtertuin: 753
2024-02-01 01:27:39.150429839  [2024-02-01 01:27:36] frigate.app                    INFO    : Camera processor started for parkeerplek: 755
2024-02-01 01:27:39.150466733  [2024-02-01 01:27:36] frigate.app                    INFO    : Camera processor started for woonkamer: 758
2024-02-01 01:27:39.150527284  [2024-02-01 01:27:36] frigate.app                    INFO    : Camera processor started for master_bedroom: 761
2024-02-01 01:27:39.150608032  [2024-02-01 01:27:36] frigate.app                    INFO    : Camera processor started for slaapkamer_puck: 763
2024-02-01 01:27:39.150668159  [2024-02-01 01:27:36] frigate.app                    INFO    : Capture process started for voortuin: 776
2024-02-01 01:27:39.150720226  [2024-02-01 01:27:36] frigate.app                    INFO    : Capture process started for achtertuin: 784
2024-02-01 01:27:39.150786703  [2024-02-01 01:27:36] frigate.app                    INFO    : Capture process started for parkeerplek: 787
2024-02-01 01:27:39.150841495  [2024-02-01 01:27:36] frigate.app                    INFO    : Capture process started for woonkamer: 790
2024-02-01 01:27:39.150900588  [2024-02-01 01:27:36] frigate.app                    INFO    : Capture process started for master_bedroom: 797
2024-02-01 01:27:39.150963464  [2024-02-01 01:27:36] frigate.app                    INFO    : Capture process started for slaapkamer_puck: 804
2024-02-01 01:27:39.155047613  [2024-02-01 01:27:39] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-02-01 01:27:45.121762476  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB
