### ISSUE TITLE
[HW Accel Support]: amd gpu

### ISSUE THREAD

**Issue by ignacio82** [blakeblackshear/frigate#9551]
### Describe the problem you are having

error-gpu with amd gpu

### Version

0.13.0-01e2d20

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.86.124:5000/api/config/schema.json
mqtt:
  enabled: True
  host: 192.168.86.124
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ignacio
  password: XXXXX


database:
  path: /config/frigate.db

go2rtc:
  streams:
    family_room: 
      - rtsp://ignacio:XXXX@192.168.86.156:554/stream1
      - "ffmpeg:family_room#audio=aac"
    family_room_sub:   
      - rtsp://ignacio:XXXX@192.168.86.156:554/stream2
    living_room: 
      - rtsp://ignacio:XXXX@192.168.86.102:554/stream1
      - "ffmpeg:family_room#audio=aac"
    living_room_sub:   
      - rtsp://ignacio:XXXX@192.168.86.102:554/stream2
    motion:
      threshold: 70  
    objects:
      track:
      - person
      - dog      
    detect:
      width: 1280
      height: 720
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 45
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 45      
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.124:8554/front
          roles:
            - detect
            - record
            - audio
    motion:
      threshold: 70  
    objects:
      track:
      - person
      - dog  
      - cat    
    detect:
      width: 960
      height: 1280
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 45
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 45  

  Kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.124:8554/kitchen
          roles:
            - detect
            - record
            - audio
    motion:
      threshold: 70  
    objects:
      track:
      - person
      - dog      
    detect:
      width: 640
      height: 480
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 45
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 45

  danielle:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.124:8554/danielle
          roles:
            - detect
            - record
            - audio
    motion:
      threshold: 70  
    objects:
      track:
      - person
      - dog      
    detect:
      width: 640
      height: 480
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 45
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 45

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://ignacio82:XXXX@192.168.86.69/live
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record  
            - audio
    motion:
      threshold: 70  
    objects:
      track:
      - person
      - dog      
    detect:
      width: 1920
      height: 1080
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 45
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 45            

  family_room:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/family_room
          roles:
            - record 
        - path: rtsp://localhost:8554/family_room_sub
          roles:
            - detect   
            - audio         
    motion:
      threshold: 70  
    objects:
      track:
      - person
      - dog      
    detect:
      width: 640
      height: 360
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 45
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 45

  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.86.102:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - record 
        - path: rtsp://localhost:8554/living_room_sub
          roles:
            - detect 
            - audio      
    motion:
      threshold: 70  
    objects:
      track:
      - person
      - dog      
    detect:
      width: 640
      height: 360
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 5
        post_capture: 10
        retain:
          default: 45
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 45

detectors:
  coral:
    type: edgetpu
    device: usb
    
birdseye:
  enabled: True
  mode: continuous   
  restream: True
  width: 1280
  height: 720
  quality: 8

ffmpeg:
  hwaccel_args: preset-vaapi    

audio: # <- enable audio events for all camera
  enabled: True     
  listen:
    - bark
    - fire_alarm
    - crying
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/kfd:/dev/kfd
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nfs-frigate-config:/config
      - nfs-frigate:/media/frigate
    ports:
      - "5000:5000"
      - "5554:8554" # RTSP feeds
      - "5555:8555/tcp" # WebRTC over tcp
      - "5555:8555/udp" # WebRTC over udp

volumes:
  nfs-frigate-config:
    external: true
  nfs-frigate:
    external: true
```

### Relevant log output

```shell
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:MesaGalliumdriver22.3.6forAMDRadeonGraphics(rembrandt,LLVM15.0.6,DRM3.42,5.15.0-92-generic)nvainfo:SupportedprofileandentrypointsnVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointVLDnVAProfileAV1Profile0:tVAEntrypointVLDnVAProfileNone:tVAEntrypointVideoProc"}
```

### FFprobe output from your camera

```shell
$ ffprobe rtsp://ignacio82:UNj9TsbjVS@192.168.86.69/live
ffprobe version 4.4.2-0ubuntu0.22.04.1+esm3 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1+esm3 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://ignacio82:XXXX@192.168.86.69/live':
  Metadata:
    title           : Session streamed by the WYZE Media Server
    comment         : live
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 10 fps, 10 tbr, 90k tbn, 20 tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

wyze

### Any other information that may be helpful

I tried following the guide to enable my amd gpu but it is not working. Any help would be appreciated
