### ISSUE TITLE
[Support]: Missing /live/webrtc ?

### ISSUE THREAD

**Issue by wouterverduin** [blakeblackshear/frigate#9555]
### Describe the problem you are having

I recently upgraded to version 0.13.0-01E2D20. Everything is working fine. However: I used to be able to acces a page which had links to just the camera feeds and also with a link that said 'two-way audio' and if remember correctly this was when i go to the link '192.168.x.x/live/webrtc. However, this now just brings me to the frontend camera menu instead.

Did the link change or did i misremember something?

### Version

0.13.0-01E2D20

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.157
  user: XX
  password: XX

database:
  path: /config/frigate.db

go2rtc:
  rtsp:
    username: "XX"
    password: "XX"
  streams:
    android:
      - rtsp://10.0.2.2:8387/h264_opus.sdp
    babycam:
      - rtsp://XX:XX@192.168.1.142/av_stream/ch0
    puppy:
      - rtsp://192.168.1.159:8554/unicast
  webrtc:
    candidates:
      - 192.168.1.50:8555
      - stun:8555

objects:
  track:
    - person
    - dog

audio:
  enabled: true
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - crying
    - fire_alarm
    - scream
    - yell

motion:
  threshold: 40
  improve_contrast: false
  mqtt_off_delay: 30

record:
  enabled: True
  retain:
    days: 3
  events:
    pre_capture: 3
    post_capture: 20
    retain:
      default: 3
      mode: motion

cameras:
  puppycam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.159:8554/unicast
          roles:
            - detect
            - record
    audio:
      enabled: False
    detect:
      width: 800
      height: 600
  babycam:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@192.168.1.142/av_stream/ch0
          roles:
            - detect
            - audio
    audio:
      enabled: true
  android:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.0.2.2:8387/h264_opus.sdp
          roles:
            - detect
            - audio
    audio:
      enabled: True
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

sonoff gk-200mp2-b
