### ISSUE TITLE
[Config Support]: Reolink doorbell detect resolution for 0.13.1

### ISSUE THREAD

**Issue by adamburgoyne** [blakeblackshear/frigate#9559]
### Describe the problem you are having

I've had a pretty basic frigate setup for the last year now, consisting of as little config as possible to get my reolink doorbell working. I've just upgraded to 0.13.1 as I've been waiting to try out some of the audio detection and it's messed up the detect resolution and my masks - as I expected it would before I updated as listed in the breaking changes. 

I just wanted to check if the correct solution for the Reolink POE doorbell is to set the detect resolution to 896 x 672 5FPS and reconfigure the masks? Ideally I'd have it show as it was before and not need to reconfigure masks but I can't seem to find out what resolution it was set to by default originally as everywhere points to 896 x 672 for the reolink ext stream which is the one listed in the docs...? If anyone knows the previous matching resolution that would be great as it also looked better in the UI! Thanks. 

### Version

0.13.1

### Frigate config file

```yaml
mqtt:
  host: xxxxx
  user: xxxxx
  password: xxxxx
  
database:
  path: /config/frigate.db

birdseye:
    enabled: true
    mode: continuous
  
go2rtc:
  streams:
    doorbell:
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus"
    doorbell_sub:
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 5
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 14
        required_zones:
          - driveway        
    snapshots:
      enabled: true
      required_zones:
        - driveway
    zones:
      driveway:
        coordinates: 485,489,788,479,881,482,1155,544,1280,438,1280,720,0,720,0,462
        objects:
          - person
    motion:
      mask:
        - 1280,0,1280,45,1095,46,1173,178,1206,308,1147,290,1089,249,1062,252,891,235,877,262,693,262,574,310,504,309,447,222,198,464,0,440,0,0
objects:
  track:
    - person

# Enable sound and HW accelleration
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
  
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
No log problems
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
