### ISSUE TITLE
[HW Accel Support]:  Fresh pull of v13 in Unraid - CUDA initialization failure

### ISSUE THREAD

**Issue by usafle** [blakeblackshear/frigate#9575]
### Describe the problem you are having

I had removed the original Frigate container and template and pulled down a "fresh" copy for v13 and installed the NVIDIA Branch when it asked me in Community Apps which branch I wanted to install.  So I did not upgrade from 12-13, I started with a new pull down of the container.  I have a CUDA capable GPU installed and visibile.

### Version

v13

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.102
  user: frigate
  password: PASSWORD
# detectors:
#  cpu1:
#    type: cpu
#    num_threads: 2

# birdseye:
#   enabled: True
#   restream: false
#   mode: continuous
#   width: 1280
#   height: 720
#   quality: 8

go2rtc:
  streams:
    Rear_Deck:
      - rtsp://admin:PASSWORD@192.168.1.114:554/h264Preview_01_main
    Rear_Deck_sub:
      - rtsp://admin:PASSWORD@192.168.1.114:554/h264Preview_01_sub
    Garage_Camera:
      - rtsp://admin:PASSWORD@192.168.1.215:554/cam/realmonitor?channel=1&subtype=0
    Garage_Camera_sub:
     - rtsp://admin:PASSWORD@192.168.1.215:554/cam/realmonitor?channel=1&subtype=1

ffmpeg:
  hwaccel_args: preset-nvidia-h265

rtmp:
  enabled: False 

cameras:
############## REAR DECK ##################
  Rear_Deck:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Rear_Deck_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Rear_Deck
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    objects:
      track:
        - person
        - dog
        - bird
        - cat
    detect:
      width: 1280
      height: 720
      fps: 4
    record:
      enabled: True
      events:
        retain:
          default: 2
    snapshots:
      enabled: True

  Garage_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage_Camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Garage_Camera
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        # record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - package
    detect:
      width: 1280
      height: 720
      fps: 4
    record:
      enabled: True
      events:
        retain:
          default: 2
    snapshots:
      enabled: True
```

### docker-compose file or Docker CLI command

```yaml
Installed Via Community Apps
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service go2rtc-healthcheck successfully started
Generating the following TRT Models: yolov4-416,yolov4-tiny-416
Downloading yolo weights
2024-02-01 10:30:12.079536551  [INFO] Preparing new go2rtc config...
2024-02-01 10:30:13.159361526  [INFO] Starting go2rtc...
2024-02-01 10:30:13.279687971  10:30:13.279 INF go2rtc version 1.8.4 linux/amd64
2024-02-01 10:30:13.280390371  10:30:13.280 INF [api] listen addr=:1984
2024-02-01 10:30:13.280428249  10:30:13.280 INF [rtsp] listen addr=:8554
2024-02-01 10:30:13.280808608  10:30:13.280 INF [webrtc] listen addr=:8555

Creating yolov4-tiny-416.cfg and yolov4-tiny-416.weights
Creating yolov4-416.cfg and yolov4-416.weights

Done.
2024-02-01 10:30:21.744747617  [INFO] Starting go2rtc healthcheck service...

Generating yolov4-416.trt. This may take a few minutes.

Traceback (most recent call last):
  File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 214, in <module>
    main()
  File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 202, in main
    engine = build_engine(
  File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 112, in build_engine
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(*EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
TypeError: pybind11::init(): factory function returned nullptr
[02/01/2024-10:30:38] [TRT] [W] Unable to determine GPU memory usage
[02/01/2024-10:30:38] [TRT] [W] Unable to determine GPU memory usage
[02/01/2024-10:30:38] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Loading the ONNX file...

Generating yolov4-tiny-416.trt. This may take a few minutes.

Traceback (most recent call last):
  File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 214, in <module>
    main()
  File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 202, in main
    engine = build_engine(
  File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 112, in build_engine
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(*EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
TypeError: pybind11::init(): factory function returned nullptr
[02/01/2024-10:30:41] [TRT] [W] Unable to determine GPU memory usage
[02/01/2024-10:30:41] [TRT] [W] Unable to determine GPU memory usage
[02/01/2024-10:30:41] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Loading the ONNX file...
Available tensorrt models:
ls: cannot access '*.trt': No such file or directory
s6-rc: warning: unable to start service trt-model-prepare: command exited 2
```

### FFprobe output from your camera

```shell
Can't access Frigate due to above error
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink + Amcrest

**Comment by NickM-27** [comment]
what version of the nvidia driver is installed and what is your docker cli command

**Comment by NickM-27** [comment]
you do have cli, the unraid community apps just setup a docker command and you are shown this docker command when you apply changes to the unraid container

**Comment by usafle** [comment]
Perhaps you are looking for the template when it pulls down the container from C.A.?

![Screenshot 2024-02-01 at 12-26-03 CozsNAS_UpdateContainer](https://github.com/blakeblackshear/frigate/assets/18576664/84b14420-2dbe-4236-a2e2-5898ab9f6b86)
![Screenshot 2024-02-01 at 12-26-19 CozsNAS_UpdateContainer](https://github.com/blakeblackshear/frigate/assets/18576664/cf18ec6b-3524-4e56-8b62-d761ae24bb3c)

**Comment by NickM-27** [comment]
no, after you press apply at the bottom it shows you the cli command

**Comment by usafle** [comment]
![Screenshot 2024-02-01 at 12-30-52 CozsNAS_UpdateContainer](https://github.com/blakeblackshear/frigate/assets/18576664/f9c6d2c6-4f80-41e8-8187-e0179767f226)

Thanks for the clarification

**Comment by NickM-27** [comment]
you need to add `--gpus=all` to the extra arguments list

**Comment by usafle** [comment]
S.O.B.  That fixed it.  She starts now.  Question while I have your attention, What do I now do with the  

`# detectors:
#  cpu1:
#    type: cpu
#    num_threads: 2`

Will it automatically utilize the GPU now for detectors or, do I have to specfically put a different line of code in he YML?

**Comment by NickM-27** [comment]
if you want it to use the GPU for object detection then you should follow https://docs.frigate.video/configuration/object_detectors#nvidia-tensorrt-detector

**Comment by usafle** [comment]
So I should be paying attention to this specific paragraph?

```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```
