### ISSUE TITLE
[Config Support]: Frigate will not start  error Config.yml not found

### ISSUE THREAD

**Issue by mikey6283** [blakeblackshear/frigate#9582]
### Describe the problem you are having

After upgraded to recent 013 and Frigate Integration 5.0 thru Hacs. I am unable to start Frigate coming up with error Config not found. I may have caused the problem as i looked a the Breaking Changes by changes the path in the container config_folder/ : /config/ I tried to revert back to my  working system by not successful. Now i am totally lost on my next step as the working config.yml  is there when i go to /mnt/user/appdata/frigate/config.

### Version

N/A

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.55.51:5000/api/config/schema

mqtt:
  host: 192.168.55.51
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db
record:
  expire_interval: 20

go2rtc:
  streams:
    koipond:
      - "ffmpeg:http://10.10.75.25/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Koipond1#video=copy#audio=copy#audio=opus"
    koipond_sub:
      - "ffmpeg:http://10.10.75.25/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Koipond1"
    backgarden:
      - "ffmpeg:http://10.10.75.26/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=BackGarden1#video=copy#audio=copy#audio=opus"
    backgarden_sub:
      - "ffmpeg:http://10.10.75.26/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=BackGarden1"
    garage:
      - "ffmpeg:http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Garage1#video=copy#audio=copy#audio=opus"
    garage_sub:
      - "ffmpeg:http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Garage1"
    front:
      - "ffmpeg:http://10.10.75.27/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Front1#video=copy#audio=copy#audio=opus"
    front_sub:
      - "ffmpeg:http://10.10.75.27/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Front1"
cameras:
  koipond:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/koipond?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/koipond_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7  
    motion:
      mask:
        - 192,35,448,31,445,0,194,0
        - 359,156,394,214,423,288,248,314,0,333,32,198
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
  backgarden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backgarden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backgarden_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
         - 188,31,446,32,441,0,191,0
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
              - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
         - 188,37,461,30,460,0,186,0   
    zones:
       garage_driveway:
        coordinates: 195,124,240,105,232,197,550,256,588,349,605,480,463,480,336,480,246,480,169,480,100,480,53,480,36,451,29,411,31,349,40,291,65,245,92,207,149,159 
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000 
          min_score: 0.5
          threshold: 0.7  
    motion:
      mask:
        - 186,37,450,35,449,0,185,0
        - 247,295,285,305,360,302,451,283,551,250,547,229,496,95,416,76,352,75,304,99,278,166,238,239 
    zones:
      driveway:
        coordinates: 640,480,571,311,546,279,526,252,498,221,478,187,466,162,430,139,398,112,353,113,305,110,254,110,139,306,92,383,54,480    
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 3
        post_capture: 10
```

### Relevant log output

```shell
2024-02-01 19:59:39.644440807  [INFO] Preparing Frigate...
2024-02-01 19:59:39.644472737  [ERROR] Frigate config file not found
2024-02-01 19:59:39.649263165  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-02-01 19:59:39.655515239  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-02-01 19:59:39.762072032  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-02-01 19:59:39.806357875  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-02-01 19:59:39.820902352  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 35, in <module>
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
2024-02-01 19:59:55.028675502  [INFO] Starting NGINX...
s6-rc: info: service legacy-services: starting
2024-02-01 19:59:55.031424959  [INFO] Preparing Frigate...
2024-02-01 19:59:55.031446599  [ERROR] Frigate config file not found
2024-02-01 19:59:55.035119084  [INFO] Service Frigate exited with code 1 (by signal 0)
2024-02-01 19:59:55.036880561  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-02-01 19:59:55.093118779  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-02-01 19:59:55.160277440  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2024-02-01 19:59:55.187326275  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

PCIe
