### ISSUE TITLE
[Detector Support]:  No match for discriminator 'type' and value 'deepstack' (allowed values: 'cpu', 'edgetpu', 'openvino', 'tensorrt') 

### ISSUE THREAD

**Issue by pacmac** [blakeblackshear/frigate#9588]
### Describe the problem you are having

I have codeproject AI running on same docker host as frigate.

Whenever I try and save the config and restart I get the following error.

` No match for discriminator 'type' and value 'deepstack' (allowed values: 'cpu', 'edgetpu', 'openvino', 'tensorrt') `

`Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 761, in config_save
    new_yaml = FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1077, in parse_raw
    return cls.parse_obj(config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
detectors -> deepstack
  No match for discriminator 'type' and value 'deepstack' (allowed values: 'cpu', 'edgetpu', 'openvino', 'tensorrt') (type=value_error.discriminated_union.invalid_discriminator; discriminator_key=type; discriminator_value=deepstack; allowed_values='cpu', 'edgetpu', 'openvino', 'tensorrt')`

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
detectors:
  deepstack:
    api_url: http://192.168.0.55:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.1 # seconds
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name  : frigate
    privileged      : true # this may not be necessary for all setups
    restart         : unless-stopped
    image           : ghcr.io/blakeblackshear/frigate:stable
    shm_size        : "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/xxx/docker/frigate/config.yml:/config/config.yml
      - /nfs/backups/frigate/media:/media/frigate
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # Birdseye In v 0.12
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxxxxx"
```

### Relevant log output

```shell
As per error above
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

Other
