### ISSUE TITLE
[Support]: Migration from 0.12->0.13 permission issue

### ISSUE THREAD

**Issue by mist0706** [blakeblackshear/frigate#9596]
### Describe the problem you are having

When migrating to 0.13 the database file and a number of other files are moved/created in the /config directory. The logs complain that it doesn't have sufficient permissions or that the filesystem is readonly

### Version

0.12 -> 0.13

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.1
    shm_size: "512mb" # update for your cameras based on calculation above
    runtime: nvidia
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate:/config:ro
      - /mnt/Seagate/frigate:/media/frigate:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5001:5000"
      - "1935:1935" # RTMP feeds
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
      FRIGATE_RTSP_PASSWORD: "xxxxxxxxxxxx"
```

### Relevant log output

```shell
2024-02-02 14:31:45.681033629  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2024-02-02 14:31:45.762270025  [INFO] Moving db from '/media/frigate/frigate.db' to the '/config' dir...
2024-02-02 14:31:45.765805947  [INFO] Preparing new go2rtc config...
mv: inter-device move failed: '/media/frigate/frigate.db' to '/config/frigate.db'; unable to remove target: Read-only file system
mv: inter-device move failed: '/media/frigate/frigate.db-shm' to '/config/frigate.db-shm'; unable to remove target: Read-only file system
mv: inter-device move failed: '/media/frigate/frigate.db-wal' to '/config/frigate.db-wal'; unable to remove target: Read-only file system
2024-02-02 14:31:45.776460479  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-02-02 14:31:45.794750174  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-02-02 14:31:45.871203661  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-02-02 14:31:45.874312313  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-02-02 14:31:51.184409731  [INFO] Preparing Frigate...
2024-02-02 14:31:51.184488301  [INFO] Preparing new go2rtc config...
2024-02-02 14:31:51.185199828  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2024-02-02 14:31:51.192436683  [INFO] Moving db from '/media/frigate/frigate.db' to the '/config' dir...
mv: inter-device move failed: '/media/frigate/frigate.db' to '/config/frigate.db'; unable to remove target: Read-only file system
mv: inter-device move failed: '/media/frigate/frigate.db-shm' to '/config/frigate.db-shm'; unable to remove target: Read-only file system
mv: inter-device move failed: '/media/frigate/frigate.db-wal' to '/config/frigate.db-wal'; unable to remove target: Read-only file system
2024-02-02 14:31:51.198836704  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-02-02 14:31:51.233103706  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-02-02 14:31:51.310576917  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-02-02 14:31:51.317002145  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

Rolling back to 0.12.1 works. Besides setting permissions 777 i've attempted setting executable rights on the parent directory (+x) for both the media folder and the config folder. I've tried to setting user and group to 1000:1000 as well as root:root
