### ISSUE TITLE
[Detector Support]: v.13 tensorrt object detection not working

### ISSUE THREAD

**Issue by repomanz** [blakeblackshear/frigate#9599]
### Describe the problem you are having

I had a fully working configuration with v.12 but moving to v.13 has broken object detection for me.   Running nvidia-smi I see frigate is leveraging my gtx 1660.  I also see that tensorrt shows up in the system area of frigate.

![image](https://github.com/blakeblackshear/frigate/assets/20090451/c5f4ea5c-d3f6-4174-b784-8b7f3c1a67ae)

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  host: 10.180.xxx.xx
  user: frigate_mqtt
  password: xyz

cameras:
  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs: 
        - path: rtsp://urlpassremoved:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://urlpassremoved@10.180.50.70:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain: 
        default: 14
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        pre_capture: 8
        post_capture: 3
        required_zones:
          - zone_front_driveway
          - zone_front_yard
        retain:
          default: 14
          mode: active_objects
    zones:  
      zone_front_driveway:
        coordinates: 0,135,147,69,606,270,508,480,0,480
      zone_front_yard:
        coordinates: 286,22,368,21,404,39,424,65,502,83,560,64,640,106,640,131,603,264,142,67
  backdoor:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs: 
        - path: rtsp://urlpassremoved@10.180.50.71:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://urlpassremoved@10.180.50.71:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain: 
        default: 14
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        required_zones:
          - zone_back_door
          - zone_back_deck
        pre_capture: 8
        post_capture: 3
        retain:
          default: 14
          mode: active_objects
    zones:
      zone_back_door:
        coordinates: 0,67,140,0,259,0,273,206,436,395,396,438,389,480,0,480
      zone_back_deck:
        coordinates: 350,0,415,35,544,136,640,236,640,291,589,362,544,318,514,323,480,339,460,382,422,389,265,195,255,0
  backyard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs: 
        - path: rtsp://urlpassremoved@10.180.50.72:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://urlpassremoved@10.180.50.72:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain: 
        default: 14
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        required_zones:
          - zone_back_yard_near
          - zone_back_yard_patio
          - zone_back_yard_far
        pre_capture: 8
        post_capture: 3
        retain:
          default: 14
          mode: active_objects
    zones:
      zone_back_yard_near:
        coordinates: 0,300,386,199,640,299,640,480,384,480,0,480
      zone_back_yard_patio:
        coordinates: 289,26,36,61,90,279,386,200
      zone_back_yard_far:
        coordinates: 458,28,640,211,640,301,378,202,282,26
  owlcam_1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://urlpassremoved&channel=1&stream=1.sdp?real_stream 
          roles:
            - detect
            - rtmp
        - path: rtsp://urlpassremoved&channel=1&stream=0.sdp?real_stream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 25
    objects:
      track:
        - bird
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        required_zones:
          - zone_owlcam1
        pre_capture: 8
        post_capture: 3
        retain:
          default: 14
          mode: active_objects
    zones:
      zone_owlcam1:
        coordinates: 168,52,468,54,475,480,162,480
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /trt-models/yolov4-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='br4'
  --ip='10.180.50.15'
  --cpuset-cpus='1,2,3,5,6,7'
  --privileged=true
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="cybertron"
  -e HOST_CONTAINERNAME="frigate"
  -e 'TCP_PORT_5000'='5000'
  -e 'TCP_PORT_8554'='8554'
  -e 'FRIGATE_RTSP_PASSWORD'='iA->Vk<J3m_#UedP@v4g'
  -e 'PLUS_API_KEY'='0090fc25-98ae-482e-ba53-7869268c8550:b194eac894975ed7c74b4d1743e9d39b557a1f49'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-9f37ffd2-8f54-e408-2c11-d3981d0f2d06'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'TCP_PORT_8555'='8555'
  -e 'UDP_PORT_8555'='8555'
  -e 'TCP_PORT_1984'='1984'
  -e 'YOLO_MODELS'='yolov4-416,yolov4-tiny-416'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -v '/mnt/cache/appdata/frigate/':'/config':'rw'
  -v '/mnt/disks/content/cctv/frigate':'/media/frigate':'rw,slave'
  -v '/mnt/cache/appdata/frigate/model_cache/tensorrt':'/trt-models':'rw,slave'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --runtime=nvidia
  --dns=10.180.50.5
  --shm-size=4076mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=100000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:stable-tensorrt'

b42b690509a73ccf1034a84dc7d15bb566fec22aacb9d18b45a4afb462e43b53
```

### Relevant log output

```shell
tensorrt being loaded (I assume)
2024-02-02 09:15:44.771355727  [2024-02-02 09:15:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 326, GPU 268 (MiB)
2024-02-02 09:15:44.785458300  [2024-02-02 09:15:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 328, GPU 278 (MiB)
2024-02-02 09:15:44.796322435  [2024-02-02 09:15:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +190, now: CPU 0, GPU 190 (MiB)
2024-02-02 09:15:44.798092537  [2024-02-02 09:15:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 139, GPU 272 (MiB)
2024-02-02 09:15:44.798178590  [2024-02-02 09:15:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 139, GPU 280 (MiB)
2024-02-02 09:15:44.798283214  [2024-02-02 09:15:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +33, now: CPU 0, GPU 223 (MiB)
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

Other

### Any other information that may be helpful

reolink cameras
