### ISSUE TITLE
Beta 0.4.0 - Regions are dynamic but still not optional in the config

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#96]
In the releasenote its stated that regions are dynamic based on the tracked object. But still I need to declare a region (box) for each camera.

```
root@docker04:/usr/share/dockers/frigate/config# cat config.yml
web_port: 5000

mqtt:
  host: 192.168.1.1
  user: username
  password: password
  topic_prefix: frigate

objects:
  track:
    - person
cameras:
  uppfart:
    ffmpeg:
      input: rtsp://camop:haxx0r@192.168.1.30:554/Streaming/Channels/1
      take_frame: 1
    regions:
      - size: 1000
        x_offset: 400
        y_offset: 500
      - size: 1220
        x_offset: 1400
        y_offset: 300
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.8

  framsidan:
    ffmpeg:
      input: rtsp://camop:haxx0r@192.168.1.32:554/Streaming/Channels/1
      take_frame: 1
    regions:
      - size: 900
        x_offset: 300
        y_offset: 0
      - size: 1200
        x_offset: 1200
        y_offset: 100
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.8
```
If I comment out the `regions:` settings for each camera it gives the following error:

```
Traceback (most recent call last):
  File "detect_objects.py", line 155, in <module>
    main()
  File "detect_objects.py", line 80, in main
    prepped_frame_queue, client, MQTT_TOPIC_PREFIX)
  File "/opt/frigate/frigate/video.py", line 155, in __init__
    self.regions = self.config['regions']
KeyError: 'regions'
On connect called

```

Did I make a booboo or misunderstood something? (Feels like it). :)

Other than this it works great! Thanks for the hard work! <3
