### ISSUE TITLE
Retain settings failing to delete old clips and snapshots

### ISSUE THREAD

**Issue by KonTiki1957** [blakeblackshear/frigate#960]
Experimenting with frigate since a couple of day I noticed that the amount of clips and snapshots was increasing from day to day maintaining all files several days old in spite of my settings (retain 1). My settings follows:

```yaml
cameras:
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://user:passwd@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - clips
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: True
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
      retain:
        default: 1
        objects:
          person: 1
              width: 640
    height: 480
    fps: 5
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
        cat:
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
        - 621,37,619,15,450,14,451,38
        - 528,194,587,186,603,236,518,236
      threshold: 15
      contour_area: 50
      delta_alpha: 0.2
      frame_alpha: 0.2
      frame_height: 200
```
