### ISSUE TITLE
[Support]: Frigate not starting after moving to docker 0.13.1 from 0.12

### ISSUE THREAD

**Issue by briodan** [blakeblackshear/frigate#9600]
### Describe the problem you are having

container does not start, complaining that it cant connect to upstream client

docker compose file:

```
version: '2.4'
networks:
    iot-net:
        external: true
services:
    rtsptoweb:
        container_name: frigate
        restart: unless-stopped
        image: ghcr.io/blakeblackshear/frigate:stable
        shm_size: "250mb"
        networks:
            iot-net:
                ipv4_address: 10.10.10.251
        volumes:
            - type: bind
              source: /dockershare/frigate/clips
              target: /media/frigate/clips
            - type: bind
              source: /dockershare/frigate/recordings
              target: /media/frigate/recordings
            - type: bind
              source: /dockershare/frigate/config
              target: /config 
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        devices:
            - /dev/apex_0:/dev/apex_0
```

### Version

0.13.1

### Frigate config file

```yaml
mqtt:
  host: 10.10.10.225
  user: homeassistant
  password: XXXXXXXXX
birdseye:
  enabled: True
  mode: continuous
detectors:
#  cpu:
#    type: cpu
  coral_pci:
    type: edgetpu
    device: pci
  
cameras:
  camera_front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.10.10.252:8554/camera_front # <----- Update for your camera
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolutio
    objects:
      filters:
        car:
          mask:
            - 522,480,704,480,704,442,520,439
      track:
        - person
        - dog
        - cat
        - car
    zones:
      driveway_left:
        coordinates: 188,59,318,58,261,356,0,322
      driveway_person:
        coordinates: 501,66,215,45,0,313,0,480,704,480,704,357
      driveway_right:
        coordinates: 639,358,512,67,353,58,303,370
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
        objects:
          person: 10
          car: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
          mode: all
    mqtt:
      crop: false
  camera_front_door: # <------ Name the camera
    ffmpeg:
      inputs:
         - path: rtsp://10.10.10.252:8554/camera_front_door # <----- Update for your camera
           input_args: preset-rtsp-restream
           roles:
             - detect
             - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolutio
    objects:
      filters:
        person:
          mask:
            - 356,255,354,286,328,291,331,260
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
        objects:
          person: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
          mode: all
  camera_back_door: # <------ Name the camera
    ffmpeg:
      inputs:
         - path: rtsp://10.10.10.252:8554/camera_back_door # <----- Update for your camera
           input_args: preset-rtsp-restream
           roles:
             - detect
             - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolutio
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
        objects:
          person: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
          mode: all
  camera_skunk: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.10.10.252:8554/camera_skunk # <----- Update for your camera
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolutio
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
        objects:
          person: 10
          car: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
          mode: all
  camera_garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.10.10.252:8554/camera_garage # <----- Update for your camera
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 960 # <---- update for your camera's resolution
      height: 540 # <---- update for your camera's resolutio
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 2
        objects:
          person: 10
          car: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
          mode: all
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
2024-02-02 08:11:12.960641728  [INFO] Preparing new go2rtc config...
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
2024-02-02 08:11:12.978132990  [INFO] Preparing Frigate...
2024-02-02 08:11:12.992507710  [INFO] Starting Frigate...
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2024-02-02 08:11:13.004025063  [INFO] Starting NGINX...
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024-02-02 08:11:13.260487523  [INFO] Starting go2rtc...
2024-02-02 08:11:13.329249217  08:11:13.329 INF go2rtc version 1.8.4 linux/amd64
2024-02-02 08:11:13.329701048  08:11:13.329 INF [rtsp] listen addr=:8554
2024-02-02 08:11:13.330041049  08:11:13.329 INF [webrtc] listen addr=:8555
2024-02-02 08:11:13.330237215  08:11:13.330 INF [api] listen addr=:1984
2024-02-02 08:11:13.872335639  2024/02/02 08:11:13 [error] 134#134: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.10.225, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "10.10.10.251:5000"
2024-02-02 08:11:14.133509058  [2024-02-02 08:11:14] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-02-02 08:11:14.168125128  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-02-02 08:11:14.219167807  [2024-02-02 08:11:14] peewee_migrate.logs            INFO    : Starting migrations
2024-02-02 08:11:14.223056125  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2024-02-02 08:11:14.247673193  [INFO] Service Frigate exited with code 256 (by signal 15)
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-02-02 08:11:14.269611434  exit with signal: terminated
2024-02-02 08:11:14.273372294  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

N/A
