### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by joernborup** [blakeblackshear/frigate#9616]
### Describe the problem you are having

Need link for where the docker image upgrade process is described - for persons not family with docker.
I can see several ending with the same problems as I have - guess with a docker image named frigate.yml.

With 'sudo docker-compose  pull'  (in directory where the frigate.yml file is)  - it says "Can't find a suitable configuration file in this directory..."

Trying 'sudo docker compose pull' - it says  'o configuration file provided: not found'

Yes - docker novice... what to do ?
/Joern

### Version

12.1

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 192.168.2.85
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: mqtt
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: mqtt

detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous
# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - cat

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.2.215:88/videoSub #replace with your RTSP camera url
          roles:
            - detect
        - path: rtsp://@192.168.2.215:88/videoMain #replace with your RTSP camera url
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
    record:
      enabled: True      
    snapshots:
      enabled: True 
    motion:
      mask:
        - 0,22,241,30,240,0,0,0
    zones:
      FrontDoorZone: 
        coordinates: 233,480,640,480,640,409,640,362,480,305,363,261,264,217,253,123,22,87,22,342,74,480    

  front2:
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.2.217:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://@192.168.2.217:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: True
      width: 704
      height: 576
    record:
      enabled: True      
    snapshots:
      enabled: True 
    motion:
      mask:
        - 306,60,683,57,683,22,650,21,311,21
    zones:
      path:
        coordinates: 623,269,569,237,501,187,427,149,443,90,504,74,576,89,704,111,704,219,704,389,650,289
      front_lawn:
        coordinates: 671,345,638,280,611,265,569,238,499,200,418,152,330,157,165,162,125,210,0,383,66,576,528,576,662,443,704,398

  back:
    ffmpeg:
      inputs:
        - path: rtsp://@192.168.2.216:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://@192.168.2.216:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: True
      width: 704
      height: 576
    record:
      enabled: True      
    snapshots:
      enabled: True 
    motion:
      mask:
        - 310,50,704,55,704,22,314,21   

record:
  enabled: True
  retain:
    days: 4
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 7
        car: 7
```

### Relevant log output

```shell
hmm... no logs..
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
docker compose pull needs to be run wherever your docker compose file is, only you would know that

**Comment by joernborup** [comment]
Thanks for answering.. I guess my docker compose file, is what I have named frigate.yml , containing:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable # blakeblackshear/frigate:stable-amd64
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/joern/Documents/frigate/config/config.yml:/config/config.yml
      - /home/joern/Documents/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
it is located in /home/joern/Documents/frigate
and that is the place where I run 'docker compose mull' from.
/Jørn
