### ISSUE TITLE
[Support]: Won't start - stuck on starting go2rtc healthcheck service

### ISSUE THREAD

**Issue by esand** [blakeblackshear/frigate#9619]
### Describe the problem you are having

Read release notes for 0.13; reviewed config and updated docker compose.yml per notes. Upgraded from 0.12 working setup to 0.13.1. Started new container and everything looked good - but it's just hanging on starting the go2rtc healthcheck service and the web interface isn't responding (nor is healthcheck service; reported as unhealthy).

I've confirmed that go2rtc is properly configured and working. I can access the go2rtc web interface and the streams are all working. All my cameras are set as restreams - the camera configs haven't changed at all since they were working in 0.12.

For the record, I have frigate set to have an ipvlan ip for local (only cameras and my computer can route to it from inside my network) access, and then it also has a docker bridge ip which is used to communicate with nginx proxy for an SSL proxy setup. I normally access the web UI from an https url that goes through nginx and through the bridge ip to frigate. However, the 5000 port is exposed to all the interfaces, so I should also be able to access it via http directly (which is how I was able to confirm the go2rtc config is OK - through port 1984).

I'm at a loss - I can't get it to start up. I've tried with a new db, I've tried with go2rtc 1.8.5, I've turned on debug logging and got nothing extra in my logs.

### Version

0.13.1

### Frigate config file

```yaml
mqtt:
  host: 172.18.x.y
  port: 1883
  user: xxx
  password: xxx

database:
  path: /db/frigate.db

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

birdseye:
  enabled: true
  mode: continuous

record:
  expire_interval: 60
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 5
    post_capture: 15
    retain:
      default: 15
      mode: active_objects
      objects:
        car: 5
        dog: 5
        cat: 5

snapshots:
  retain:
    default: 20

go2rtc:
  ffmpeg:
    bin: ffmpeg
    myfix: "-fflags +genpts+discardcorrupt -i {input}"
    myvol: "-af \"volume=2\""
  streams:
    Front_doorbell:
      # 2560x1920 @15fps
      - rtsp://xxx:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:Front_doorbell#audio=myvol#audio=aac
    # Front_doorbell_2way:
      # rtsp://xxx:554/cam/realmonitor?channel=1&subtype=0
      # ffmpeg:Front_doorbell_2way#video=h264#audio=myvol#audio=opus
    Front_doorbell_sub1:
      # 720x576 @15 fps
      - rtsp://xxx:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    Front_door:
      # 1920x1080 @30fps
      - rtsp://xxx:554/s0
      # 640x360 @10fps
      # rtsp://xxx:554/s1
    Front_door_sub1:
      # 1024x576 @5fps
      - rtsp://xxx:554/s2
    Front_driveway:
      # 3840x2160 @30fps
      - rtsp://xxx:554/cam/realmonitor?channel=1&subtype=0
      # 640x480 @10fps
      # rtsp://xxx:554/cam/realmonitor?channel=1&subtype=1
    Front_driveway_sub1:
      # 1280x720 @5fps
      - rtsp://xxx:554/cam/realmonitor?channel=1&subtype=2
    Side_yard:
      # 3840x2160 @30fps
      - rtsp://xxx:554/cam/realmonitor?channel=1&subtype=0
      # 640x480 @10fps
      # rtsp://xxx:554/cam/realmonitor?channel=1&subtype=1
    Side_yard_sub1:
      # 1280x720 @5fps
      - rtsp://xxx:554/cam/realmonitor?channel=1&subtype=2

cameras:
  Front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_doorbell_sub1
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 720
      height: 576
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
        - 0,0,720,0,720,362,498,355,319,348,178,350,0,363 # road
    zones:
      Driveway:
        coordinates: 720,349,494,352,551,523,608,521,633,576,720,576
      Doorstep:
        coordinates: 0,576,0,516,146,455,259,484,309,446,413,459,531,464,552,524,607,525,636,576
      Lawn:
        coordinates: 533,463,427,462,303,444,259,484,163,459,0,522,0,364,54,356,177,348,318,344,493,353
  Front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_door_sub1
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 1024
      height: 576
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
        - 0,466,14,342,41,220,84,99,104,68,328,0,0,0 # road
        - 1024,113,1024,0,730,0,830,24,926,60 # road
    zones:
      Driveway:
        coordinates: 490,37,415,49,336,68,590,273,692,363,803,347,908,437,1024,218,872,123,739,71,584,23
      Doorstep:
        coordinates: 340,576,257,393,592,272,689,359,795,360,908,448,1024,196,1024,576
      Lawn:
        coordinates: 0,576,4,393,27,277,53,175,96,153,212,100,332,65,593,272,192,412,281,576
  Front_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_driveway_sub1
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 1280
      height: 720
      stationary:
        max_frames:
          objects:
            car: 600
    snapshots:
      enabled: true
    objects:
      track:
        - person
        # car
        - dog
        - cat
    motion:
      mask:
        - 1280,0,1280,190,1189,110,1136,87,1074,69,957,47,867,34,719,28,580,32,471,40,360,55,244,86,142,124,72,165,0,215,0,0 # road
    zones:
      Driveway:
        coordinates: 1216,720,1187,607,1120,441,1013,256,922,130,838,33,731,27,609,27,468,37,393,138,318,247,210,434,146,596,104,720
      Doorstep:
        coordinates: 0,720,0,437,212,435,161,558,108,720
      Lawn:
        coordinates: 343,213,467,43,374,55,315,67,247,87,185,111,127,136,50,180,0,219,0,437,211,435
  Side_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Side_yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Side_yard_sub1
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 1280
      height: 720
      stationary:
        max_frames:
          objects:
            person: 600
            car: 600
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car
        - dog
        - cat
    motion:
      mask:
        - 0,0,1280,0,1280,0,1280,256,1234,231,1168,201,1060,160,930,134,761,115,604,109,431,113,257,130,94,163,0,189 # neighbours
    zones:
      Lawn:
        coordinates: 0,720,1280,720,1280,298,1235,277,1193,262,1138,249,1060,238,906,227,599,225,381,235,170,255,0,291
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
Generating the following TRT Models: yolov7-320
Downloading yolo weights
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2024-02-02 22:35:08.749830592  [INFO] Preparing new go2rtc config...
2024-02-02 22:35:09.472004385  [INFO] Starting go2rtc...
2024-02-02 22:35:09.693179330  22:35:09.692 INF go2rtc version 1.8.4 linux/amd64
2024-02-02 22:35:09.694152279  22:35:09.694 INF [api] listen addr=:1984
2024-02-02 22:35:09.694427569  22:35:09.694 INF [rtsp] listen addr=:8554
2024-02-02 22:35:09.694939394  22:35:09.694 INF [webrtc] listen addr=:8555
2024-02-02 22:35:18.746512393  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Tested ffprobe with the go2rtc config stream URL's, as well as the restream URLs that Frigate uses - both work correctly.
```

### Frigate stats

```json
API isn't responding/functional.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Mix; cameras are functional
