### ISSUE TITLE
Frigate no longer keeps track of stationary objects in HA in v0.13

### ISSUE THREAD

**Issue by kirashogun** [blakeblackshear/frigate#9621]
### Describe the problem you are having

I use the car count (sensor.garage_car_count) sensor in Frigate HACs to keep track whether a car is present in the garage or not. Basically a presence sensor for cars. This works perfectly in 0.12.

However, in 0.13, when the car is parked in the garage, frigate detects car's presence (car count inceases to 1), same behaviour as 0.12. However, after around 3-4 minutes, the car count counter would reset to 0 indicating no car in the garage when the car is still clearly there.

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.200
  user: mqtt
  password: //redacted 

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous

go2rtc:
  streams:
//redacted
  webrtc:
    candidates:
      - 192.168.1.9:8555
      - stun:8555

cameras:
  intercom:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/intercom
          roles:
            - detect

    detect:
      width: 1920
      height: 1080
      fps: 5

    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 0,1028,487,769,497,320,0,388

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080

  front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 1280,0,1280,198,1043,90,1035,164,652,161,0,189,0,0

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 544,0,540,46,0,49,0,0    

    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 947,278,1581,319,1587,504,1520,564,1458,737,1396,1080,1920,1080,1920,0,468,0,0,0,0,732
        person:
          mask:
            - 0,0,1920,0,1920,551,1601,229,1596,377,0,282
          min_score: 0.79

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - car
        - person
      filters:
        car:
          min_score: 0.77
    birdseye:
      mode: objects        

  alfresco:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/alfresco
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 962,353,1190,450,1214,338,1172,229,1013,163
            - 213,210,264,447,123,501,46,256
            - 570,132,588,322,463,355,433,156
          min_score: 0.77
    birdseye:
      mode: objects

  westside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/westside
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 337,201,648,144,932,130,1103,156,1100,0,0,0,0,312
    birdseye:
      mode: objects

  eastside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/eastside
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          mask: 
            - 953,0,917,357,699,260,505,247,369,97,0,92,0,0
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 6000

objects:
  filters:
    person:
      threshold: 0.8

motion:
  mask:
    - 357,0,357,47,0,49,0,0

snapshots:
    enabled: true
    timestamp: false
    clean_copy: true
    bounding_box: false
    retain:
      default: 60

timestamp_style:
  position: "tl"
  format: "%Y-%m-%d %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 100
  thickness: 1
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision
