### ISSUE TITLE
[Support]: Recordings saved on external NAS can not be viewed from Frigate Addon/HA instance since 13.0. 

### ISSUE THREAD

**Issue by T3KPCS7** [blakeblackshear/frigate#9622]
### Describe the problem you are having

Hi,

Ever since updating to 0.13, my recordings can not be seen inside Frigate. For the last 6 months or so I've been saving them on external storage on a NAS, and they are still being saved there. However, I can't watch them from my HA interface or the Frigate addon anymore. Logging into the NAS directly I can save the clips and view them without any issues. Trying to watch them from for example the Media menu in HA, it shows the first frame and then says the file is corrupted. 

Recordings from before the update can still be viewed normally.

Also, I'm getting a new error I've posted in relevant log output that has not been there prior to the update.

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
database:
  path: /config/frigate.db


mqtt:
  host: My HA-instance
  user: *********
  password: ******

ffmpeg:
  #hwaccel_args:
  hwaccel_args: preset-rpi-64-h264
   # - -c:v:1
    #- h264_v4l2m2m 
  output_args:
    record: preset-record-generic-audio-aac


detectors:
  coral:
    type: edgetpu
    device: usb


go2rtc:
  streams:
    Garage: 
      - "ffmpeg:http://cameraIP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=*****#video=copy#audio=copy#audio=opus"
    Garage_sub: 
      - "ffmpeg:http://cameraIP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*****&password=*****"
    Entredorr: 
      - "ffmpeg:http://cameraIP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*****&password=*****#video=copy#audio=copy#audio=opus"
    Entredorr_sub: 
      - "ffmpeg:http://cameraIP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*****&password=*****"
    Driveway: 
      - "ffmpeg:http://cameraIP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*****&password=*****#video=copy#audio=copy#audio=opus"
    Driveway_sub: 
      - "ffmpeg:http://cameraIP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*****&password=*****"

cameras:


#///////////////ÉNTREDÖRR/////////////////

  Entredorr:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Entredorr?video=copy&audio=aac  #GoodQuality Stream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Entredorr_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
      - person
      - cat
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4
      
#///////////////DRIVEWAY/////////////////

  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects: 
      track: 
        - person
        - cat
        - car
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4

#///////////////GARAGE/////////////////
  
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage?video=copy&audio=aac #GoodQuality Stream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects: 
     track:
      - person
      - car
    record:
      enabled: True
      events:
        retain:
          default: 7
          mode: active_objects
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4
```

### Relevant log output

```shell
2024-02-03 07:17:00.583065343  [h264 @ 0x7f6000a760] sps_id 32 out of range
2024-02-03 07:17:00.584258174  [h264 @ 0x7f6000a760] sps_id 32 out of range
2024-02-03 07:17:00.585641613  [h264 @ 0x7f6000a760] sps_id 32 out of range
2024-02-03 07:17:00.586007865  [h264 @ 0x7f6000a760] sps_id 32 out of range
2024-02-03 07:17:00.586433951  [h264 @ 0x7f6000a760] sps_id 32 out of range
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 1

Error: 
Stream 1:
Return Code: 1

Error:
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 410/420
