### ISSUE TITLE
Snapshot function with detection person

### ISSUE THREAD

**Issue by samidcs2** [blakeblackshear/frigate#9623]
### Describe the problem you are having

Good morning,
Since the new Frigate update,
Camera entities, linked to person detection
ex: camera.cam_garage.person
have become :
image.cam_garage.person

The problem is that I used it to send on telegram, there's the camera.snapshot function.

Has anyone noticed the problem and if not, is there a solution to send an image entity on telegram?

Thank you for your answers

### Version

frigate_0.13.0

### Frigate config file

```yaml
mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: hoSmaz960706nt

cameras:
  cam_jardin_devant_2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:reSmaz960706nk@192.168.0.10:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
        enabled: True
        width: 2560
        height: 1920
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 14
  cam_jardin_devant_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:reSmaz960706nk@192.168.0.41:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
        enabled: True
        width: 2560
        height: 1920
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 14
  cam_jardin_derriere:
    ffmpeg:
      inputs:
        - path: rtsp://admin:reSmaz960706nk@192.168.0.15:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
        enabled: True
        width: 2560
        height: 1920
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 14
  cam_garage:
    ffmpeg:
      inputs:
        - path: rtsp://samidcs2@yahoo.fr:tpSmaz960706nk@192.168.0.71:554/stream1
          roles:
            - detect
            - record
    detect:
        enabled: True
        width: 1920
        height: 1080
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 14
  cam_poules:
    ffmpeg:
      inputs:
        - path: rtsp://samidcs2@yahoo.fr:tpSmaz960706nk@192.168.0.37:554/stream1
          roles:
            - detect
            - record
    detect:
        enabled: True
        width: 1920
        height: 1080
    objects:
      track:
        - person
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
      events:
        retain:
          default: 14
```

### Relevant log output

```shell
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
