### ISSUE TITLE
Frigate 13.1 Beta Stationary objects being redected during rain

### ISSUE THREAD

**Issue by MickPBduece** [blakeblackshear/frigate#9636]
### Describe the problem you are having

A vehicle parked in the drive for a couple months started being detected every few minutes just after apply 13.1.  This is new behavior.  We've snow and much heavier rain and the vehicle would be detected as soon as Frigate started and then many just 1-2 times per month.

### Version

Frigate (Full Access) Beta       0.13.1-34FB1C2

### Frigate config file

```yaml
#   Config notes - The Addon ethernet card is plugged into a blue usb on the PI.  Not sure if it needs to be but after this last reload... Just do it
#   The Coral and the SSD are plugged into the powered usb hub
#   The network is consigured eth0 - 192.168.1.9/24 and 192.168.1.1 (Gateway) and 192.168.1.1 for DNS  IPV6 is disabled
#                         enp1sou1 - 192.168.10.9/24 and 192.168.10.9 (Gateway) and no DNS IPV6 is disabled
#   Frigate add on is the version that allows me to turn off protection mode (Spefically 3.1 as o 6/4/2022)
#   HArdware accel is the PI3/4 settings for 64 bit
#
#   Changing the ffmpeg setting seems to reqiure a hardware restart?? !! // 
#   shm-size (width * height * 1.5 * 9 + 270480)/1048576 = <shm size in mb>
detectors:
  # Required: name of the detector
  coral:
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    #  num_threads: 3   - commented 7/11 based on note "only for CPU types"

mqtt:
    host: 192.168.1.9    
    user: mqtt
    password: mqtt

#global_args: -hide_banner -loglevel error

#Front door camera will WILL work with audio enabled (AAC) and HWaccel for RPI4. 
#Adding HWaccel for all cameras except front door keep the second and all subsequent cameras with hwaccel config from running
#I had opened an issue for this in the past - it is now closed
#

ffmpeg:
    hwaccel_args: preset-rpi-64-h264
    input_args: -tag:v hvc1  #  added 8/25/2023 to try to get clips sent by frigate blueprint to play on iphone

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width:  704    ##removed 1/3/2023 added back  did not make snapshot frame readable
  height: 480    ##removed 1/3/2023  added back  did not make snapshot frame readable
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  #max_disappeared: 25
  stationary:
    interval: 300  #added on Feb 3/2024

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - motorcycle
  filters:   #<-- Added 1/3/2023 after the trash can was determined to be a person 3 times during snow
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.73  #<-- Added 1/3/2023 after the trash can was determined to be a person 3 times during snow
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0,0,1000,0,1000,200,0,200    

# Video stream storage settings
record:
  enabled: True
#  this is the config to retain recording of everything.  Probably need to move to harddrive it utilize this option
  retain:
    days: 5
# this reduces retention to only when there is motion
    mode: motion
  events:
    retain:
      default: 5 
      mode: active_objects

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175  # removed 1/3/2023--This made snapsot to small to use
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 5  
       

go2rtc:
  streams:
    frontdoor:    rtsp://HA:HA123456@192.168.10.121:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
    frontmiddle:  rtsp://HA:HA123456@192.168.10.118:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif  
    fronteast:    rtsp://HA:HA123456@192.168.10.116:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif 
    garage:       rtsp://HA:HA123456@192.168.10.122:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
    patiodoor:    rtsp://HA:HA123456@192.168.10.117:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
    patiowest:    rtsp://HA:HA123456@192.168.10.123:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
    basement:     rtsp://HA:HA123456@192.168.10.124:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
    
cameras:
  frontdoor:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#        record: preset-record-generic-audio-aac
#   Substream 1 path   
      inputs:
        - path: rtsp:HA:HA123456@192.168.10.121:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
#   Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.121:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      mask:
        - 516,1,128,44,1,434,4,0
        - 693,480,700,365,655,324,531,476 
#   Substream 2 path          
      #  - path: rtsp://HA:HA123456@192.168.10.121:554/cam/realmonitor?channel=1&subtype=2
      #      - clips   

  frontmiddle:
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
#   Substream path          
      inputs:
        - path: rtsp:HA:HA123456@192.168.10.118:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
#   Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.118:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      mask:
        - 539,96,704,143,704,123,599,42,0,43,0,125
        - 704,350,704,480,649,480

  fronteast:
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
#   Substream path          
      inputs:
        - path: rtsp:HA:HA123456@192.168.10.116:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
#   Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.116:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
  
    motion:
      mask:
        - 85,424,170,458,171,480,0,480,0,162,73,287,72,380
        - 126,45,374,22,461,56,568,44,704,148,704,0,201,0,0,0,0,136
        - 704,284,608,190,552,0,704,0

  garage:
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
#   Substream path          
      inputs:
        - path: rtsp:HA:HA123456@192.168.10.122:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
#   Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.122:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      mask: 0,0,0,217,79,98,71,0
  patiodoor:
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
#   Substream path          
      inputs:
        - path: rtsp:HA:HA123456@192.168.10.117:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
#   Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.117:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      mask: 33,163,53,0,0,0,0,405,0,480,203,480,100,457

    
  patiowest:
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
#   Substream path          
      inputs:
        - path: rtsp:HA:HA123456@192.168.10.123:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
#   Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.123:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      mask: 33,0,0,0,0,0,0,0,0,33
  basement:
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
#   Substream path          
      inputs:
        - path: rtsp:HA:HA123456@192.168.10.124:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
#   Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.124:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      mask: 0,0,0,480,157,480,100,28
```

### Relevant log output

```shell
This is last few miniutes of the log during which Frigate detected the vehicle

2024-02-03 20:20:22.114413369  [h264 @ 0x7f700178b0] error while decoding MB 0 64, bytestream 28427
2024-02-03 20:21:32.422798582  [h264 @ 0x7f70016e50] cabac decode of qscale diff failed at 50 30
2024-02-03 20:21:32.422811359  [h264 @ 0x7f70016e50] error while decoding MB 50 30, bytestream 230807
2024-02-03 20:22:01.406711042  [h264 @ 0x7f700178b0] left block unavailable for requested intra mode
2024-02-03 20:22:01.406725023  [h264 @ 0x7f700178b0] error while decoding MB 0 11, bytestream 249493
2024-02-03 20:22:06.383117781  [h264 @ 0x7f70016e50] left block unavailable for requested intra4x4 mode -1
2024-02-03 20:22:06.383455349  [h264 @ 0x7f70016e50] error while decoding MB 0 55, bytestream 80297
2024-02-03 20:24:01.248824949  [h264 @ 0x7f700178b0] cabac decode of qscale diff failed at 35 14
2024-02-03 20:24:01.249116074  [h264 @ 0x7f700178b0] error while decoding MB 35 14, bytestream 324719
2024-02-03 20:24:01.359086645  [h264 @ 0x7f700178b0] left block unavailable for requested intra4x4 mode -1
2024-02-03 20:24:01.359391640  [h264 @ 0x7f700178b0] error while decoding MB 0 23, bytestream 189155
```

### FFprobe output from your camera

```shell
[{"return_code":1,"stderr":"","stdout":""},{"return_code":1,"stderr":"","stdout":""}]
```

### Frigate stats

```json
I get a blank screen
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua Starlight
