### ISSUE TITLE
[Detector Support]: Google Coral M.2 not detected in Frigate while running on a Raspberry Pi 5

### ISSUE THREAD

**Issue by diggity801** [blakeblackshear/frigate#9645]
### Describe the problem you are having

I have a Google Coral M.2 plugged into the M.2 expansion hat for a Raspberry Pi 5.
The device is recognized and shows up properly with lspci; however, frigate will not detect it as pci or pci:0 in the conf file.

```
root@rpi5b:~# lspci
0000:00:00.0 PCI bridge: Broadcom Inc. and subsidiaries Device 2712 (rev 21)
0000:01:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
0001:00:00.0 PCI bridge: Broadcom Inc. and subsidiaries Device 2712 (rev 21)
0001:01:00.0 Ethernet controller: Device 1de4:0001
root@rpi5b:~#

```

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
snapshots:
  enabled: true
  clean_copy: true
  crop: true
mqtt:
  enabled: true
  host: 10.0.0.1
  port: 1883
detect:
  fps: 3
  max_disappeared: 500
detectors:
  coral:
    type: edgetpu
    device: pci:0
objects:
  track:
    - truck
    - motorcycle
    - bicycle
    - person
    - cat
    - car
  filters:
    person:
      min_score: 0.84 # Minimum confidence score of 80%
    cat:
      min_score: 0.84 # Minimum confidence score of 80%
    car:
      min_score: 0.84 # Minimum confidence score of 80%
ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy
database:
  path: /config/frigate.db
cameras:
  doorbell_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/doorbell_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/doorbell_camera_sub
          roles:
            - detect
  sideyard_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/sideyard_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/sideyard_camera_sub
          roles:
            - detect
  rear_house_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/rear_house_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/rear_house_camera_sub
          roles:
            - detect
  patio_camera:
    ffmpeg:
      input_args: preset-rtsp-restream
      hwaccel_args: preset-rpi-64-h265
      inputs:
        - path: rtsp://rpi5b:8554/patio_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/patio_camera_sub
          roles:
            - detect
    objects:
      track:
        - person
  third_floor_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/third_floor_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/third_floor_camera_sub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
  north_standard_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/north_standard_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/north_standard_camera_sub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
  trash_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/trash_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/trash_camera_sub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - car
  sidewalk_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/sidewalk_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/sidewalk_camera_sub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
  garage_camera:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/garage_camera
          roles:
            - record
        - path: rtsp://rpi5b:8554/garage_camera_sub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
  rear_camera_two:
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://rpi5b:8554/rear_camera_two
          roles:
            - record
        - path: rtsp://rpi5b:8554/rear_camera_two_sub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - car
record:
  enabled: true
  retain:
    days: 20
    mode: all
  events:
    retain:
      default: 30
      mode: all
ui:
  timezone: America/Los_Angeles
  live_mode: webrtc
  use_experimental: false
  time_format: 12hour
go2rtc:
  streams:
    sideyard_camera:
      - rtsp://admin:Just4fun@sideyard-camera:554/h264Preview_01_main
      - "ffmpeg:sideyard_camera#audio=opus"
    sideyard_camera_sub:
      - rtsp://admin:Just4fun@sideyard-camera:554/h264Preview_01_sub
#      - "ffmpeg:sideyard_camera_sub"
    rear_house_camera:
      - rtsp://admin:Just4fun@rear-house-camera:554/h264Preview_01_main
      - "ffmpeg:rear_house_camera#audio=opus"
    rear_house_camera_sub:
      - rtsp://admin:Just4fun@rear-house-camera:554/h264Preview_01_sub
#      - "ffmpeg:rear_house_camera_sub"
    doorbell_camera:
      - rtsp://admin:Just4fun@doorbell-camera:554/h264Preview_01_main
      - "ffmpeg:doorbell_camera#audio=opus"
    doorbell_camera_sub:
      - rtsp://admin:Just4fun@doorbell-camera:554/h264Preview_01_sub
#      - "ffmpeg:doorbell_camera_sub"
    patio_camera:
      - rtsp://admin:Just4fun@patio-camera:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:patio_camera#audio=opus"
    patio_camera_sub:
      - rtsp://admin:Just4fun@patio-camera:554/cam/realmonitor?channel=1&subtype=1
    sidewalk_camera:
      - rtsp://sidewalk-camera:554/video1_unicast
      - "ffmpeg:sidewalk-camera#audio=opus"
    sidewalk_camera_sub:
      - rtsp://sidewalk-camera:554/video2_unicast
#      - "ffmpeg:sidewalk_camera_sub"
    front_window_camera_high:
      - rtsp://front-window-camera-high:554/video1_unicast
      - "ffmpeg:front-window-camera-high#audio=opus"
    front_window_camera_high_sub:
      - rtsp://front-window-camera-high:554/video2_unicast
#      - "ffmpeg:front_window_camera_high_sub"
    rear_camera_two:
      - rtsp://rear-camera-two:554/video1_unicast
      - "ffmpeg:rear-camera-two#audio=opus"
    rear_camera_two_sub:
      - rtsp://rear-camera-two:554/video2_unicast
#      - "ffmpeg:rear_camera_two_sub"
    north_standard_camera:
      - rtsp://north-standard-camera:554/video1_unicast
      - "ffmpeg:north-standard-camera#audio=opus"
    north_standard_camera_sub:
      - rtsp://north-standard-camera:554/video2_unicast
#      - "ffmpeg:north_standard_camera_sub"
    trash_camera:
      - rtsp://trash-camera:554/video1_unicast
      - "ffmpeg:trash-camera#audio=opus"
    trash_camera_sub:
      - rtsp://trash-camera:554/video2_unicast
#      - "ffmpeg:trash_camera_sub"
    third_floor_camera:
      - rtsp://third-floor-camera:554/video1_unicast
      - "ffmpeg:third-floor-camera#audio=opus"
    third_floor_camera_sub:
      - rtsp://third-floor-camera:554/video2_unicast
#      - "ffmpeg:third-floor-camera_sub"
    garage_camera:
      - rtsp://garage-camera:554/video1_unicast
      - "ffmpeg:garage-camera#audio=opus"
    garage_camera_sub:
      - rtsp://garage-camera:554/video2_unicast
#      - "ffmpeg:garage-camera_sub"
  webrtc:
    candidates:
      - rpi5b:8555
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.1
    privileged: true
    restart: unless-stopped
    ports:
      - "80:5000"
      - "8554:8554" # RTSP feed
      - "8555:8555/tcp" # WebRTC over TCP
      - "8555:8555/udp" # WebRTC over UDP
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config:/config
      - ./media:/media
    shm_size: '2gb'
```

### Relevant log output

```
-04 06:17:56.052966105  [2024-02-04 06:17:56] frigate.app                    INFO    : go2rtc process pid: 95
2024-02-04 06:17:56.128461792  [2024-02-04 06:17:56] frigate.app                    INFO    : Output process started: 348
2024-02-04 06:17:56.151292147  [2024-02-04 06:17:56] detector.coral            INFO    : Starting detection process: 343
2024-02-04 06:17:56.152068500  [2024-02-04 06:17:56] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2024-02-04 06:17:56.152075259  [2024-02-04 06:17:56] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

This same M.2 chip works fine on a Rockpi 5b board. It loaded and detected it just fine in Frigate. However; there seems to be a problem specifically with Raspberry Pi 5 and Frigate. It is detected in Debian and the driver is loaded as /dev/apex_0 but Frigate cannot detect it.
