### ISSUE TITLE
After Update to 13.1 Service didnt start. 

### ISSUE THREAD

**Issue by cho1103** [blakeblackshear/frigate#9650]
### Describe the problem you are having

Hello,
after the update to 13.1 the service want start without any log hints. I saw there must be the Database in Docker changed.
i dont know the location in docker and exactly what to do. Can someone give me instrution how to change the Database.

### Version

13.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  user: XXXX
  password: XXXX
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

record:
  expire_interval: 5

timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
cameras:
  Eingang_Keller:
    ffmpeg:
#      hwaccel_args: preset-rpi-64-h264 
      inputs:
        - path: rtsp://XX:XX@192.168.5.125:554/h264_stream
          roles:
            - detect
            - record
    motion:
      mask:
        - 445,720,436,665,42,675,43,720
        - 1280,0,1280,720,849,720,814,506,788,318,833,0
        - 0,0,0,529,521,273,502,0
    objects:
      track:
        - person
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 5
  Garage:
    ffmpeg:
#      hwaccel_args: preset-rpi-64-h264 
      inputs:
        - path: rtsp://XX:XX@192.168.5.110:554/Streaming/Channels/1
          roles:
            - detect
            - record
    motion:
      mask:
        - 442,677,444,720,49,720,47,674
        - 1280,720,922,720,961,570,1280,511
        - 1157,129,1280,0,942,0
        - 1280,299,1152,192,1162,138,1280,0
    objects:
      track:
        - person
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 5

  Garten_Hang:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@192.168.5.62:554/h264Preview_01_main
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,504,436,311,1280,573,1280,720,0,720
    objects:
      track:
        - person
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 5
  Garten_Tor:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@192.168.5.117:554/h264_stream
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,492,0,720,464,720,207,499,117,495
    objects:
      track:
        - person
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 5
  Eingang_EG:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@192.168.5.76:554/h264_stream
          roles:
            - detect
            - record
    motion:
      mask:
        - 42,664,437,670,446,720,44,720
        - 1280,720,737,720,1114,0,1280,0
    objects:
      track:
        - person
        - dog
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 5
  Garten_Grillwerkstatt:
    ffmpeg:
      inputs:
        - path: rtsp://XX:XX@192.168.5.46:554/h264_stream
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 5
# detectors:
#  cpu1:
#   type: cpu
#  cpu2:
#   type: cpu
rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 2
  mode: continuous
live:
  height: 720
  quality: 3
```

### Relevant log output

```shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:259
Integration: Frigate (documentation, issues)
First occurred: 16:00:05 (9 occurrences)
Last logged: 16:07:12

Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Connect call failed ('172.30.33.6', 5000)]

**and this one:**

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 16:02:41 (1 occurrences)
Last logged: 16:02:41

Failed to to call /addons/ccab4aaf_frigate-fa/start - Can't create container from addon_ccab4aaf_frigate-fa: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate-fa: Bad Request ("invalid CapAdd: unknown capability: "CAP_PERFMON"")
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB
