### ISSUE TITLE
[Support]: Motion frames on frigate startup cause object detection to "stick" on all parked cars in the area. Driving high detector usage. 

### ISSUE THREAD

**Issue by aredon** [blakeblackshear/frigate#9651]
### Describe the problem you are having

Pretty much title. I upgraded to V13 and have been going through my cameras to update the configs and noticed that object detection is stuck on all the parked cars on my street that are in frame. As far as I can tell these just keep detecting until object detection is toggled off. 

From what I can tell there are some errant motion boxes being drawn when frigate first starts. These are driving object detection for most of the frame - and then it just stays on because the object hasn't left. 

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
#GLOBAL FFMPEG
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

#GLOBAL OBJECT SETTINGS
#Objects list: https://docs.frigate.video/configuration/objects/
objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car

snapshots:
  retain:
    default: 7

birdseye:
  enabled: True
  mode: motion

#CAMERAS
cameras:
  ##################################################### OFFICE
  office:
    ffmpeg:
      inputs:
        - path: rtsp://Frigate:REDACTED@192.168.1.201:554//cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://Frigate:REDACTED@192.168.1.201:554//cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    zones:
      porch:
        coordinates: 74,251,302,336,640,425,640,480,535,480,406,480,298,480,180,480,150,452,64,370,0,293,68,295
    detect:
      enabled: True
      # width: 640
      # height: 480
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        required_zones: 
          - porch
        retain:
          default: 7
          mode: active_objects
    snapshots:
      enabled: True
      bounding_box: True
      required_zones: 
        - porch
    motion:
      mask:
        - 211,86,640,36,640,480,573,480,491,480,482,420,465,364,469,292,375,271,285,254,277,325,246,328,181,300,66,262,71,137
        - 640,451,640,480,382,480,383,454
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Misc Amcrest Devices
