### ISSUE TITLE
[Detector Support]: Coral USB Ubuntu LTS 22.04.3 Server Frigate takes multiple restarts to detect TPU

### ISSUE THREAD

**Issue by RutgerDiehard** [blakeblackshear/frigate#9663]
### Describe the problem you are having

Running Frigate 0.13.1 on Ubuntu Server 22.04.3 LTS in Docker, I've had an issue with a Coral USB TPU getting stuck multiple times a day. After a bit of troubleshooting (moving USB ports etc.) I have found using a powered USB hub the most reliable solution; it stays up for days at a time.

The issue I have now, is that when I restart Frigate (after config changes) Frigate does not immediately find the TPU, it takes 3 or 4 restarts before it actually finds the TPU and starts successfully.

I've tested this on a different PC running Frigate 0.12 in Docker on Ubuntu Server 20.04.6 LTS with the same results. When the Coral TPU is plugged in to a USB port on the PC, Frigate finds the device after the first restart every time.

Is there something I'm missing, or is there something I can do (maybe add a delay) to help?

### Version

0.13.1

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: HOSTIP
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: mqtt
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3
record:
  # Optional: Enable recording (default: shown below)
  enabled: True
  # Optional: Number of days to retain recordings regardless of events (default: shown below)
  # NOTE: This should be set to 0 and retention should be defined in events section below
  #       if you only want to retain recordings of events.
  retain:
    days: 0
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    # max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Per object retention days
      objects:
        person: 15
go2rtc:
  streams:
#    username: "user"
#    password: "password"
    Drive:
      - "ffmpeg:rtsp://user:password@CAMERAIP:554/h265Preview_01_main"
    Front_Door:
      - "ffmpeg:rtsp://user:password@CAMERAIP:554/h265Preview_01_main"      
    Front_Door_Sub: 
      - http://CAMERAIP/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=user&password=password
cameras:
  Front_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: http://CAMERAIP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&user=password
          input_args: preset-http-reolink
          roles:
            - detect
    live:
      stream_name: Front_Door_Sub
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
      filters:
        dog:
          mask: 471,349,469,439,533,443,534,347
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
      required_zones:
        - drive_zone
        - drive_parking_zone
        - drive_path_zone
    record:
      events:
        required_zones:
          - drive_zone
          - drive_parking_zone
          - drive_path_zone
    zones:
      drive_zone:
        coordinates: 348,65,50,227,0,85,54,61,91,49,118,0,346,0
        objects:
          - person
          - car
          - dog
      drive_parking_zone:
        coordinates: 72,221,568,402,516,512,846,512,896,314,896,0,360,0,358,59
        objects:
          - person
          - dog
      drive_path_zone:
        coordinates: 0,512,461,512,521,388,46,211,0,107
        objects:
          - person
          - dog
      street_zone:
        coordinates: 2,1,87,0,98,35,50,57,0,78
    motion:
      mask:
        - 638,477,638,500,260,501,261,475
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
  Drive:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Drive
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: http://CAMERAIP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&user=password
          input_args: preset-http-reolink
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
      required_zones:
        - drive_zone
        - drive_parking_zone
        - drive_path_zone
    record:
      events:
        required_zones:
          - drive_zone
          - drive_parking_zone
          - drive_path_zone
    zones:
      drive_parking_zone:
        coordinates: 0,512,534,512,684,384,316,132,315,62,0,173
        objects:
          - person
          - dog
      drive_path_zone:
        coordinates: 537,512,800,512,827,450,683,383
        objects:
          - person
          - dog
      drive_zone:
        coordinates: 896,0,896,289,825,447,593,320,320,128,318,65
        objects:
          - person
          - car
          - dog
      close_zone:
        coordinates: 0,235,67,236,296,138,301,0,0,0
    motion:
      mask:
        - 896,0,896,154,659,96,328,53,304,0
        - 638,476,633,499,265,501,265,476
        - 162,117,324,70,314,0,164,0,141,31
        - 128,108,139,79,134,50,89,48,64,45,301,0,21,129,73,109
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "100mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified >
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructi>
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your h>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/bob/frigate/config:/config
      - /home/bob/go2rtc:/config/go2rtc
      - /home/bob/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "5000:5000"
      - "8123:8123"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
TPU not found
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
