### ISSUE TITLE
[Support]: Birdseye layout configuration help

### ISSUE THREAD

**Issue by reassuringgreet** [blakeblackshear/frigate#9674]
### Describe the problem you are having

I have 2 1536x576 camera streams that I'd like to see in birdseye vertically like this:
![image](https://github.com/blakeblackshear/frigate/assets/8457771/401c0b6f-6a4f-46a9-8dff-c10a60574dc7)
but they only show horizontally, like this:
![image](https://github.com/blakeblackshear/frigate/assets/8457771/042992a9-b115-4168-9388-d6260b3f190a)

I've read that you can define both the birdview resolution and each camera resolution under the "detect" section, so this is what I'm trying to do:
```
birdseye:
  enabled: True
  width: 1536
  height: 1152 #twice the height to get them vertically
  quality: 10
  mode: continuous
```
the cameras have the following:

```
record:
  enabled: False
  retain:
    days: 7
    mode: all
detect:
  enabled: False
  width: 1536
  height: 576
```

I've tried this configuration and several other resolutions but they won't show vertically. Is there something I'm doing wrong? Thanks

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False


birdseye:
  enabled: True
  width: 1536
  height: 1152
  quality: 10
  mode: continuous

record:
  enabled: False
  retain:
    days: 7
    mode: all
detect:
  enabled: False
  width: 1536 
  height: 576 

go2rtc:
  streams:
#4kduo
    4kfondo:
      - "rtsp://user:pass@192.168.1.1:554/h264Preview_01_sub"
    4kfrente:
      - "rtsp://user:pass@192.168.1.2:554/h264Preview_01_sub"

cameras:
#4kduo
  4kback:
    ffmpeg:
      hwaccel_args: " "
      input_args:
        preset-rtsp-restream
        #  " "
      inputs:
        - path: "rtsp://user:pass@192.168.1.1:554/h264Preview_01_sub"
          roles:
            - record
            - detect

  4kfront:
    ffmpeg:
      hwaccel_args: " "
      input_args:
        preset-rtsp-restream
      inputs:
        - path: "rtsp://user:pass@192.168.1.2:554/h264Preview_01_sub"
          roles:
            - record
            - detect
```

### Relevant log output

```shell
No relevant log
```

### FFprobe output from your camera

```shell
ffprobe version 6.1.1-1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Debian 13.2.0-9)
  configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libharfbuzz --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libsvtav1 --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, rtsp, from 'rtsp://user:pass@192.168.1.1:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_sub
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1536x576, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink duo 2 poe
