### ISSUE TITLE
[Config Support]: Neolink and Docker

### ISSUE THREAD

**Issue by lloydsmart** [blakeblackshear/frigate#9680]
### Describe the problem you are having

Hello, perhaps I'm demonstrating my ignorance of docker networking here, but for the life of me I have been unable to get Frigate to connect to Neolink which I'm using to support a Reolink E1 3MP.

I'm running both Frigate and Neolink as docker containers on the same host. Everything else runs fine. In the attached config, the camera is called livingroom.

I've tried using the docker container name (which I believe should work, and resolve to the internal docker IP address of the Neolink container), the internal IP address of the Debian host and the DNS domain name of the host, but none seem to work. I just get the "No frames have been received, check error logs" error for that camera.

I can confirm that Neolink is working, because I can connect to the feed using VLC running on another machine on my network, connecting to Neolink via RTSP using the IP address of the host, and the chosen port number. It displays the E1 feed (albeit with quite a significant lag of about 10s, but this isn't the issue I'm troubleshooting right now).

docker-compose.yaml:
```yaml
version: "3.91"
services:
  neolink:
    image: quantumentangledandy/neolink:latest
    container_name: neolink
    ports:
      - 9554:9554
    volumes:
      - /opt/cctv/neolink/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
  frigate:
    container_name: frigate
    depends_on:
      - neolink
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.1
    shm_size: "384mb"
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/cctv/frigate:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984/tcp" # WebRTC config page
    environment:
      FRIGATE_MQTT_USER: "frigate"
      FRIGATE_MQTT_PASSWORD: "<MY_MQTT_PASSWORD>"
      FRIGATE_RTSP_USER: "frigate"
      FRIGATE_RTSP_PASSWORD: "<MY_RTSP_PASSWORD>"
      PLUS_API_KEY: "<MY_API_KEY>"
```
neolink.toml:
```toml
bind = "0.0.0.0"
bind_port = 9554
discovery = "local"

[[cameras]]
name = "livingroom"
username = "frigate"
password = "<MY_RTSP_PASSWORD>"
address = "livingroom.mydomain.com:9000"
format = "h264"
```

Any help getting this to work would be appreciated.

### Version

0.13.1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://apoc.mydomain.com:5000/api/config/schema.json
mqtt:
  enabled: true
  host: mqtt.mydomain.com
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 300

detectors:
  coral1:
    type: edgetpu
    device: pci:0

model:
  path: plus://********************************

audio:
  enabled: true
  max_not_heard: 10
  min_volume: 1000
  listen:
    - bark
    - fire_alarm
    - scream
    - yell

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 4
  input_args: preset-rtsp-udp
  output_args:
    record: preset-record-generic-audio-copy

detect:
  stationary:
    threshold: 100

objects:
  filters:
    dog:
      threshold: 0.85

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 3
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

rtmp:
  enabled: false

go2rtc:
  streams:
    front_door:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@doorbell.mydomain.com:554/h264Preview_01_main
      - "ffmpeg:front_door#audio=opus"
    front_door_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@doorbell.mydomain.com:554/h264Preview_01_sub
      - "ffmpeg:front_door_sub#audio=opus"
    front:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@front.mydomain.com:554/h265Preview_01_main
      - "ffmpeg:front#audio=opus"
    front_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@front.mydomain.com:554/h264Preview_01_sub
      - "ffmpeg:front_sub#audio=opus"
    side:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@side.mydomain.com:554/h265Preview_01_main
      - "ffmpeg:side#audio=opus"
    side_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@side.mydomain.com:554/h264Preview_01_sub
      - "ffmpeg:side_sub#audio=opus"
    garden:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@garden.mydomain.com:554/h265Preview_01_main
      - "ffmpeg:garden#audio=opus"
    garden_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@garden.mydomain.com:554/h264Preview_01_sub
      - "ffmpeg:garden_sub#audio=opus"
    kitchen:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@kitchen.mydomain.com:554/h264Preview_01_main
      - "ffmpeg:kitchen#audio=opus"
    kitchen_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@kitchen.mydomain.com:554/h264Preview_01_sub
      - "ffmpeg:kitchen_sub#audio=opus"
  webrtc:
    candidates:
      - 192.168.188.5:8555
      - stun:8555
    listen: ":8555"

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    webui_url: "https://doorbell.mydomain.com"
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
        - motorcycle
        - horse
      filters:
        car:
          mask:
            - 0,386,142,289,101,267,42,233,0,227 # Next door driveway
    motion:
      mask:
        - 410,0,410,25,218,25,218,0 # Timestamp
        - 132,245,133,314,289,343,308,315,288,251 # Left bush
        - 640,340,640,256,384,271,375,343 # Right bush
    zones:
      near_front_door:
        coordinates: 88,326,473,337,447,480,0,480
        objects:
          - person
  front:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    webui_url: "https://front.mydomain.com"
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
        - motorcycle
        - horse
    motion:
      mask:
        - 410,0,410,25,218,25,218,0 # Timestamp
        - 565,0,640,0,640,42 # Motorway
        - 308,293,313,232,273,205,160,232,27,288,0,364,0,433 # Left bush
        - 427,150,491,124,571,122,640,166,640,205,572,183,490,185,368,247,361,185 # Right bush
    zones:
      lawn_left:
        coordinates: 489,480,0,480,0,426,323,290,466,391,511,447
        objects:
          - person
          - dog
          - cat
      lawn_right:
        coordinates: 501,354,598,199,494,194,367,260
        objects:
          - person
          - dog
          - cat
  side:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/side_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    webui_url: "https://side.mydomain.com"
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
        - motorcycle
    motion:
      mask:
        - 410,0,410,25,218,25,218,0 # Timestamp
        - 575,55,577,122,333,93,335,43 # Motorway / bridge
        - 0,51,248,36,368,113,0,233 # Other street
        - 450,180,500,180,500,130,450,130 # Tree
        - 435,237,476,231,480,204,454,186,427,205,398,216,382,241,384,269 # Hedge by driveway
    zones:
      back_path:
        coordinates: 557,316,555,288,381,270,363,290
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garden
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/garden_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    webui_url: "https://garden.mydomain.com"
    audio:
      min_volume: 500
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        dog:
          mask:
            - 434,480,640,480,640,296
    motion:
      mask:
        - 410,0,410,25,218,25,218,0
    zones:
      mud:
        coordinates: 640,81,418,31,223,30,128,56,56,93,78,138,137,86,193,145,457,164,472,224,439,394,640,436
        objects:
          - dog
          - cat
          - person
      gate:
        coordinates: 48,97,117,96,78,141
        objects:
          - person
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/kitchen_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    webui_url: "https://kitchen.mydomain.com"
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 217,526,362,566,348,625,181,730,112,666,87,588,84,532,110,487,178,494 # Sofa
    motion:
      mask:
        - 700,0,700,40,325,40,325,0
        - 268,185,311,235,207,269,174,244
    zones:
      utility_room:
        coordinates: 423,326,551,342,611,90,470,72,306,119
        objects:
          - person
          - dog
      back_door:
        coordinates: 180,333,125,558,40,569,48,417,99,287
        objects:
          - person
          - dog
  livingroom:
    audio:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://neolink:9554/livingroom
          input_args: preset-rtsp-restream

ui:
  live_mode: webrtc
  time_format: browser
  date_style: medium
  time_style: medium
  strftime_fmt: "%d/%m/%Y %H:%M"

telemetry:
  version_check: true
```

### Relevant log output

```shell
frigate    | 2024-02-05 18:44:05.156733948  [2024-02-05 18:44:05] ffmpeg.livingroom.detect       ERROR   : rtsp://192.168.188.5:9554/livingroom: Connection timed out
frigate    | 2024-02-05 18:44:10.184042977  [2024-02-05 18:44:10] frigate.video                  ERROR   : livingroom: Unable to read frames from ffmpeg process.
frigate    | 2024-02-05 18:44:10.184260412  [2024-02-05 18:44:10] frigate.video                  ERROR   : livingroom: ffmpeg process is not running. exiting capture thread...
frigate    | 2024-02-05 18:44:15.172284411  [2024-02-05 18:44:15] watchdog.livingroom            ERROR   : Ffmpeg process crashed unexpectedly for livingroom.
frigate    | 2024-02-05 18:44:15.172464406  [2024-02-05 18:44:15] watchdog.livingroom            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2024-02-05 18:44:15.172641969  [2024-02-05 18:44:15] ffmpeg.livingroom.detect       ERROR   : [tcp @ 0x5651b6349140] Connection to tcp://192.168.188.5:9554?timeout=5000000 failed: Connection timed out
frigate    | 2024-02-05 18:44:15.172840517  [2024-02-05 18:44:15] ffmpeg.livingroom.detect       ERROR   : rtsp://192.168.188.5:9554/livingroom: Connection timed out
frigate    | 2024-02-05 18:44:20.201969076  [2024-02-05 18:44:20] frigate.video                  ERROR   : livingroom: Unable to read frames from ffmpeg process.
frigate    | 2024-02-05 18:44:20.202093352  [2024-02-05 18:44:20] frigate.video                  ERROR   : livingroom: ffmpeg process is not running. exiting capture thread...
frigate    | 2024-02-05 18:44:25.190068476  [2024-02-05 18:44:25] watchdog.livingroom            ERROR   : Ffmpeg process crashed unexpectedly for livingroom.
frigate    | 2024-02-05 18:44:25.196419937  [2024-02-05 18:44:25] watchdog.livingroom            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | 2024-02-05 18:44:25.196564031  [2024-02-05 18:44:25] ffmpeg.livingroom.detect       ERROR   : [tcp @ 0x556108d0a140] Connection to tcp://192.168.188.5:9554?timeout=5000000 failed: Connection timed out
frigate    | 2024-02-05 18:44:25.196701803  [2024-02-05 18:44:25] ffmpeg.livingroom.detect       ERROR   : rtsp://192.168.188.5:9554/livingroom: Connection timed out
frigate    | 2024-02-05 18:44:30.218303169  [2024-02-05 18:44:30] frigate.video                  ERROR   : livingroom: Unable to read frames from ffmpeg process.
frigate    | 2024-02-05 18:44:30.218535769  [2024-02-05 18:44:30] frigate.video                  ERROR   : livingroom: ffmpeg process is not running. exiting capture thread...
```

### Frigate stats

```json
{"cameras":{"front_door":{"audio_dBFS":-47.2984,"audio_rms":141.4261,"camera_fps":5.1,"capture_pid":573,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":578,"pid":562,"process_fps":5.1,"skipped_fps":0.0},"garden":{"audio_dBFS":-58.8442,"audio_rms":37.4319,"camera_fps":5.1,"capture_pid":587,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":597,"pid":568,"process_fps":5.1,"skipped_fps":0.0},"kitchen":{"audio_dBFS":-47.6205,"audio_rms":136.2774,"camera_fps":5.1,"capture_pid":594,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":606,"pid":569,"process_fps":5.1,"skipped_fps":0.0},"livingroom":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":0.0,"capture_pid":601,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1580,"pid":571,"process_fps":0.0,"skipped_fps":0.0},"side":{"audio_dBFS":-35.629,"audio_rms":542.0015,"camera_fps":5.0,"capture_pid":581,"detection_enabled":1,"detection_fps":0.4,"ffmpeg_pid":589,"pid":565,"process_fps":5.0,"skipped_fps":0.0},"front":{"audio_dBFS":-42.4985,"audio_rms":245.7688,"camera_fps":5.1,"capture_pid":577,"detection_enabled":1,"detection_fps":0.3,"ffmpeg_pid":582,"pid":563,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"27.8","cpu_average":"19","mem":"0.4"},"97":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"98":{"cmdline":"python3 -u -m frigate","cpu":"3.8","cpu_average":"7","mem":"5.8"},"115":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"142":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"143":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"153":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"172":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"203":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"238":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"271":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"439":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"1.3"},"509":{"cmdline":"frigate.recording_manager","cpu":"3.8","cpu_average":"3","mem":"1.8"},"518":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)","cpu":"0.4","cpu_average":"0","mem":"0.1"},"519":{"cmdline":"frigate.detector.coral1","cpu":"0.1","cpu_average":"1","mem":"1.6"},"521":{"cmdline":"frigate.output       ","cpu":"1.5","cpu_average":"0","mem":"1.5"},"524":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"525":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"526":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"},"527":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"543":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1024x1024 -i pipe: -f mpegts -s 720x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"544":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"545":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"562":{"cmdline":"frigate.process:front_door","cpu":"1.6","cpu_average":"1","mem":"1.9"},"563":{"cmdline":"frigate.process:front","cpu":"3.4","cpu_average":"7","mem":"1.9"},"565":{"cmdline":"frigate.process:side","cpu":"3.7","cpu_average":"9","mem":"1.9"},"568":{"cmdline":"frigate.process:garden","cpu":"1.8","cpu_average":"4","mem":"1.9"},"569":{"cmdline":"frigate.process:kitchen","cpu":"1.6","cpu_average":"6","mem":"2.1"},"571":{"cmdline":"frigate.process:livingroom","cpu":"0.1","cpu_average":"0","mem":"1.9"},"573":{"cmdline":"frigate.capture:front_door","cpu":"0.8","cpu_average":"0","mem":"1.9"},"577":{"cmdline":"frigate.capture:front","cpu":"0.8","cpu_average":"0","mem":"1.9"},"578":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front_door_sub -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.9","cpu_average":"2","mem":"0.4"},"581":{"cmdline":"frigate.capture:side","cpu":"0.9","cpu_average":"0","mem":"1.9"},"582":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front_sub -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.8","cpu_average":"2","mem":"0.4"},"587":{"cmdline":"frigate.capture:garden","cpu":"0.9","cpu_average":"0","mem":"1.9"},"588":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4","cpu":"1.3","cpu_average":"0","mem":"0.3"},"589":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/side_sub -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.8","cpu_average":"2","mem":"0.5"},"594":{"cmdline":"frigate.capture:kitchen","cpu":"2.4","cpu_average":"2","mem":"1.9"},"597":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/garden_sub -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.8","cpu_average":"2","mem":"0.5"},"598":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front@%Y%m%d%H%M%S%z.mp4","cpu":"1.7","cpu_average":"0","mem":"0.3"},"601":{"cmdline":"frigate.capture:livingroom","cpu":"0.1","cpu_average":"0","mem":"1.8"},"602":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/side@%Y%m%d%H%M%S%z.mp4","cpu":"1.5","cpu_average":"0","mem":"0.3"},"606":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/kitchen_sub -r 5 -vf fps=5,scale=1024:1024 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"5.8","cpu_average":"5","mem":"0.6"},"608":{"cmdline":"frigate.audio_manager","cpu":"2.0","cpu_average":"4","mem":"2.2"},"611":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4","cpu":"1.7","cpu_average":"0","mem":"0.3"},"614":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/kitchen -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/kitchen@%Y%m%d%H%M%S%z.mp4","cpu":"1.4","cpu_average":"0","mem":"0.3"},"618":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front_door_sub -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.3","cpu_average":"0","mem":"0.3"},"621":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front_sub -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.4","cpu_average":"0","mem":"0.3"},"624":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/side_sub -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.4","cpu_average":"0","mem":"0.3"},"628":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/garden_sub -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.4","cpu_average":"0","mem":"0.3"},"630":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/kitchen_sub -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.4","cpu_average":"0","mem":"0.3"},"1520":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1580":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.188.5:9554/livingroom -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/livingroom@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.0","cpu_average":"0","mem":"0.3"}},"detection_fps":0.7,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":6.0,"pid":519}},"processes":{"audioDetector":{"pid":608},"go2rtc":{"pid":89},"logger":{"pid":439},"recording":{"pid":509}},"service":{"last_updated":1707158176,"latest_version":"0.13.1","storage":{"/dev/shm":{"free":377.4,"mount_type":"tmpfs","total":384.0,"used":6.6},"/media/frigate/clips":{"free":1170384.3,"mount_type":"xfs","total":3760810.8,"used":2590426.5},"/media/frigate/recordings":{"free":1170384.3,"mount_type":"xfs","total":3760810.8,"used":2590426.5},"/tmp/cache":{"free":911.1,"mount_type":"tmpfs","total":953.7,"used":42.6}},"temperatures":{"apex_0":35.3},"uptime":142,"version":"0.13.1-34fb1c2"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

Hardware is Dell R210ii with a Xeon E3. Matrox GPU so no hardware acceleration.

**Comment by NickM-27** [comment]
perhaps neolink only supports outputting udp

**Comment by lloydsmart** [comment]
Hmm maybe. How would I know?

If it helps, here's the output of ffprobe, run from inside the Frigate container using docker exec:
```bash
root@e6298f2256a4:/opt/frigate# ffprobe rtsp://neolink:9554/livingroom
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://neolink:9554/livingroom':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2304x1296, 19.58 tbr, 90k tbn
  Stream #0:1: Audio: pcm_s16be, 16000 Hz, stereo, s16, 512 kb/s
```

**Comment by NickM-27** [comment]
I would try changing it to

```
  livingroom:
    audio:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://neolink:9554/livingroom
          input_args: preset-rtsp-udp
```
