### ISSUE TITLE
[Config Support]: Birdseye hits , but no related event in events gui (BE set to objects mode)

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#9683]
### Describe the problem you are having

first off, frigate has been ROCK solid on my large setup of 19x cams (most offsite via vpns) w a usb Coral + nvidia p1000 gpu doing dec/encoding - (frigate became solid/stable once i got some HW / setup issues resolved though extensive testing / troubleshooting and help here).  I say Rock solid as in i now get many weeks of uptime / no issues (and I have been using/running frigate for 3-4 months now).  
So thank you for all the hardwork on its code, and the tons of support here in github issues (and the docs). 
IMO the most over-looked (and powerful) feature of frigate, is birdseye set to object mode.   FWIW-  Almost all of my cameras are high quality, more modern model Axis cameras.
```-------------------------------------------------------------------------```
 
running version:  0.13.0-614a36a
Question:
One issue i haven't been able to resolve on my own-  with birdseye set to OBJECT mode, and restream = true ( so its always running / encoding - config info is at bottom).  **I have 2 or 3x cams that very frequently get triggered on birdseye, but there is no related entry over in the frigate webGUI under events.**  So its hard to troubleshoot away these "birdseye" false positives.  

I'll even watch the debug view of one of these cams (ie via http://<IP>:5000/api/CamName?motion=1&regions=1&bbox=1&h=1080) , and will see birdseye trigger on the camera, but In the debug view I have only seen green or red bounding boxes - (ie no yellow/blue "car + X%" bounding boxes).  

Is this correct behavior for birdseye ?  or are there any suggestions on how I can reduce these birdseye false positives? 

(My main use case for frigate is BirdsEye, as I have 3x different raspberryPI's + plus monitors constantly showing the bird's eye RTSP feed, and it works great!!  2x at my house, and 1x at my office).

relevant config info:

13sec capture of the ?motion=1&regions=1&bbox=1&h=1080  , during which birdseye was triggered (but i dont see why from this capture)
thank you!

![debugMJPGcount](https://github.com/blakeblackshear/frigate/assets/60830628/85148ab8-0cee-4136-8b1e-06982de50ffa)

0.13.0-614a36a  via docker on Ubuntu 20.04.6 LTS  w  usb Coral + nvidia p1000 gpu  
Coral inference speed ~ 15ms

config of 2x of the problem cams:
```
####
  XXX-ParkLot:
    enabled: true
    # enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://view:view@XXX:4554/live.sdp
        roles:
        - detect
        - record
    detect:
      enabled: true
      fps: 4
      width: 1920
      height: 1080
    motion:
      mask:
       - 0,0,665,0,1920,0,1920,1080,1510,857,1116,501,634,337,259,386,237,774,309,1080,0,1080
    objects:
      filters:
        motion:
          mask:
           - 0,0,665,0,1920,0,1920,688,1671,600,1180,408,634,337,254,318,237,774,93,1080,0,1080
        person:
          mask:
           - 0,0,665,0,1920,0,1920,688,1671,600,1180,408,634,337,254,318,237,774,93,1080,0,1080
          # min_area: 5000
          # max_area: 100000
            # Optional: minimum score for the object to initiate tracking (default: 0.5)
          min_score: 0.75
            # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          threshold: 0.85
        car:
          min_score: 0.75
          threshold: 0.85


####
  XXX-Park:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:X@X:5554/live/539B6806-1DCF-492C-AEB1
        roles:
        - detect
        - record
    detect:
      enabled: true
      fps: 4
      width: 2560
      height: 1920
      #width: 1600   - might sw to this on milestone side
      #height: 1200
    motion:
      mask:
      - 0,0,437,0,284,109,125,171,34,421,419,1920,0,1920
      - 1271,1920,2560,1920,2560,1691,2560,1235,2207,944,779,1725
      - 1156,175,815,0,0,208,69,490
    objects:
      filters:
        person:
          mask:
           - 0,0,665,0,1404,0,1920,0,1925,130,1771,304,1164,57,605,150,65,260,101,751,93,1080,0,1080
          # min_area: 5000
          # max_area: 100000
            # Optional: minimum score for the object to initiate tracking (default: 0.5)
          min_score: 0.75
            # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
          threshold: 0.85
        car:
          mask:
           - 0,0,437,0,284,109,125,171,34,421,419,1920,0,1920
           - 0,1920,2560,1920,2560,1691,2560,1235,2216,739,0,1473
           - 2189,185,2400,629,2276,1099,2560,1394,2560,856,2560,0,1258,0,1260,114
          min_score: 0.75
          threshold: 0.85
      track:
       - person
       - car 


```	
		  
		  
FFprobe of 1x of the problem cams:
```
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30000/1001","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560}]}}]
``` 
	
	
birdseye config:
```
birdseye:
  enabled: true
  restream: true
  width: 1920
  height: 1080
  quality: 6
    # Optional: Mode of the view. Available options are: objects, motion, and continuous
    #   objects - cameras are included if they have had a tracked object within the last 30 seconds
    #   motion - cameras are included if motion was detected in the last 30 seconds
    #   continuous - all cameras are included always
  mode: objects
```

### Version

0.13.0-614a36a

### Frigate config file

```yaml
see above
```

### Relevant log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
> Is this correct behavior for birdseye ? or are there any suggestions on how I can reduce these birdseye false positives?

birdseye triggers as soon as an object is detected, it does not wait for them to be considered a true positive (which is required for events). This is so that the latency for when a camera shows is lower

**Comment by bob454522** [comment]
> birdseye triggers as soon as an object is detected, it does not wait for them to be considered a true positive (which is required for events). This is so that the latency for when a camera shows is lower

ok, that makes sense-  so what type of masking would prevent an object from being detected (forget about the object being a true positive or not, please)?

(i THINK the answer is:   if i made a object->filter->person-Mask, the size of the ENTIRE image (ie a 1920x1080  ) AND i had  -track: -> - person   set,   then that camera should never trigger on birdseye,  right? 
(i realize this would not make sense, but It's a hypothetical to help me understand).

IE if i have this right, then NEITHER of these 2x configs, separately, should ever show this camera on birds eye, correct? )

```
  XXX-ParkLot:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@XXX:2554/live.sdp
		roles:
        - detect
        - record
    detect:
      enabled: true
      fps: 4
      width: 1920
      height: 1080
    motion:
      mask:
       - 0,0 (no motion mask at all)
    objects:
      filters:
        person:
          mask:
           - 0,1920,0,1080  (or whatever coordinates equal a redbox covering the ENTIRE screen)
      track:
      - person 
```

NOR should this config ever trigger for birdseye (ie entire image covered by a red box for Motion mask)

```
  XXX-ParkLot:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://view:view@XXX:2554/live.sdp
		roles:
        - detect
        - record
    detect:
      enabled: true
      fps: 4
      width: 1920
      height: 1080
    motion:
      mask:
       - 0,1920,0,1080  (or whatever coordinates equal a redbox covering the ENTIRE screen)
```  

thank you
