### ISSUE TITLE
[Config Support]: Playback cannot continue. No available working or supported playlists.

### ISSUE THREAD

**Issue by Khangry** [blakeblackshear/frigate#9696]
### Describe the problem you are having

I'm having trouble playing recorded videos on Microsoft Edge on my PC. It works fine on Chrome for Android, so I'm not sure what the issue is with Edge.

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  enabled: False
record:
  enabled: True
  retain:
    days: 7
    mode: all
  sync_recordings: True
go2rtc:
  webrtc:
    candidates:
      - stun:8555
      - 192.168.1.166:8555
      - 192.168.1.136:8555
  streams:
    Backyard:
      - rtsp://xxx@192.168.1.156:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif 
      - "ffmpeg:Backyard#video=h264#audio=opus"
    Backyard-record:
      - rtsp://xxx@192.168.1.156:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif 
      - "ffmpeg:Backyard-record#audio=opus"

cameras:
  Backyard:
    enabled: True
    record:
      enabled: True
    detect: 
      enabled: False 
    birdseye:
      order: 1
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Backyard-record
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
birdseye:
  enabled: True
  width: 1280
  height: 720
  mode: continuous
  quality: 8

logger:
  default: info
  logs:
    frigate.event: debug

timestamp_style:
  position: "tl"
  format: "%H:%M:%S %d/%m/%Y"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid
ui:
  live_mode: mse
  use_experimental: False
  time_format: browser
  date_style: short
  time_style: short
  strftime_fmt: "%H:%M %d/%m/%Y"
```

### Relevant log output

```shell
{
  "properties": {
    "render_id": 45,
    "player_id": 20,
    "created": "2024-02-06 05:43:15.060302 UTC",
    "info": "ChunkDemuxer",
    "origin_url": "http://192.168.1.166:5000/",
    "kFrameUrl": "http://192.168.1.166:5000/recording/Backyard",
    "kFrameTitle": "Frigate",
    "url": "blob:http://192.168.1.166:5000/4c010054-e248-4ea2-b5ea-fb17b18a9ce5",
    "kRendererName": "RendererImpl",
    "renderer_created": {
      "renderer_engine": "Default",
      "renderer_type": "RendererImpl"
    },
    "pipeline_state": "kStopped",
    "kMediaAutoplayPolicy": "document-user-activation-required",
    "autoplay_decision": {
      "effectively_muted": false,
      "policy": "document-user-activation-required",
      "source": "method",
      "was_blocked": true
    },
    "duration": 3603.756999,
    "event": "kWebMediaPlayerDestroyed"
  },
  "events": [
    {
      "time": 0,
      "key": "created",
      "value": "2024-02-06 05:43:15.060302 UTC"
    },
    {
      "time": 0.03700000047683716,
      "key": "info",
      "value": "AV1 decoder support: 0, WebMfDecoderCheck: not null, kMediaFoundationClearAV1Support enabled: 1, disable_av1_accelerated_decode_gpu_workaround: 0, av1_hw_decoder_support: 0, vp9_decoder_support: 1"
    },
    {
      "time": 1.2300000041723251,
      "key": "info",
      "value": "kForceMFMediaEngineRenderer:No; kMediaFoundationClearPlayback:No; DCompDisabled:Yes; RemotePlaybackDisabled:No; DomainOverride:Uninitialized; CDMAvailable:Yes; MFOverrideEnabled:No; MFClearWorkaround:Enabled;CanUseVidSuperRes:No; IsOnBattery: No; BatteryExclusiveStart:No"
    },
    {
      "time": 1.2960000038146973,
      "key": "origin_url",
      "value": "http://192.168.1.166:5000/"
    },
    {
      "time": 1.297999992966652,
      "key": "kFrameUrl",
      "value": "http://192.168.1.166:5000/recording/Backyard"
    },
    {
      "time": 1.3020000010728836,
      "key": "kFrameTitle",
      "value": "Frigate"
    },
    {
      "time": 1.363999992609024,
      "key": "url",
      "value": "blob:http://192.168.1.166:5000/4c010054-e248-4ea2-b5ea-fb17b18a9ce5"
    },
    {
      "time": 1.3809999972581863,
      "key": "info",
      "value": "ChunkDemuxer"
    },
    {
      "time": 1.3889999985694885,
      "key": "kRendererName",
      "value": "RendererImpl"
    },
    {
      "time": 1.402999997138977,
      "key": "renderer_created",
      "value": {
        "renderer_engine": "Default",
        "renderer_type": "RendererImpl"
      }
    },
    {
      "time": 1.414000004529953,
      "key": "pipeline_state",
      "value": "kStarting"
    },
    {
      "time": 2.2329999953508377,
      "key": "kMediaAutoplayPolicy",
      "value": "document-user-activation-required"
    },
    {
      "time": 2.2360000014305115,
      "key": "autoplay_decision",
      "value": {
        "effectively_muted": false,
        "policy": "document-user-activation-required",
        "source": "method",
        "was_blocked": true
      }
    },
    {
      "time": 15.586999997496605,
      "key": "duration",
      "value": 3603.756999
    },
    {
      "time": 32934.12399999797,
      "key": "event",
      "value": "kWebMediaPlayerDestroyed"
    },
    {
      "time": 32934.56999999285,
      "key": "pipeline_state",
      "value": "kStopping"
    },
    {
      "time": 32934.592999994755,
      "key": "pipeline_state",
      "value": "kStopped"
    }
  ]
}
```

### Frigate stats

```json
{
    "cameras": {
        "Backyard": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 249,
            "detection_enabled": 0,
            "detection_fps": 0,
            "ffmpeg_pid": 14726,
            "pid": 248,
            "process_fps": 5,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "78": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "93": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "105": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "112": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "2.9"
        },
        "122": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "144": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "146": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "222": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "226": {
            "cmdline": "frigate.recording_manager",
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.4"
        },
        "234": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(38)",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "235": {
            "cmdline": "frigate.detector.cpu ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "236": {
            "cmdline": "frigate.output       ",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "240": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "241": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "248": {
            "cmdline": "frigate.process:Backyard",
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.3"
        },
        "249": {
            "cmdline": "frigate.capture:Backyard",
            "cpu": "2.7",
            "cpu_average": "4",
            "mem": "0.3"
        },
        "257": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/Backyard-record -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Backyard@%Y%m%d%H%M%S%z.mp4",
            "cpu": "0.4",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "14726": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://127.0.0.1:8554/Backyard -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "6.6",
            "cpu_average": "7",
            "mem": "1.0"
        },
        "72774": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 0,
    "detectors": {
        "cpu": {
            "detection_start": 0,
            "inference_speed": 10,
            "pid": 235
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "0.0%",
            "mem": "-%"
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 93
        },
        "logger": {
            "pid": 222
        },
        "recording": {
            "pid": 226
        }
    },
    "service": {
        "last_updated": 1707198155,
        "latest_version": "0.13.1",
        "storage": {
            "/dev/shm": {
                "free": 95.2,
                "mount_type": "tmpfs",
                "total": 100,
                "used": 4.8
            },
            "/media/frigate/clips": {
                "free": 454475.6,
                "mount_type": "fuse.mergerfs",
                "total": 1371354.1,
                "used": 894074
            },
            "/media/frigate/recordings": {
                "free": 454475.6,
                "mount_type": "fuse.mergerfs",
                "total": 1371354.1,
                "used": 894074
            },
            "/tmp/cache": {
                "free": 953.2,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 0.5
            }
        },
        "temperatures": {},
        "uptime": 69700,
        "version": "0.13.1-34fb1c2"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
