### ISSUE TITLE
[Camera Support]: Onvif Error with Foscam Camera

### ISSUE THREAD

**Issue by Hans2004** [blakeblackshear/frigate#9706]
### Describe the problem you are having

If I enable onvif in the config file for fo Foscam PTZ camera as such:

```
    onvif:
      host: xxx.xxx.xxx.xxx
      port: 888
      user: xxx
      password: xxxxxx
```

Then on the camera page for that camera, a control panel appears, but no controls in it. The log view then shows:
`frigate.ptz.onvif  ERROR   : Unable to connect to camera: Binnen: Unknown error: Python int too large to convert to C int`

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
cameras:
  Binnen: #Name for your comment
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://xxx:xxxx@xxx.xxx.xxx.xxx:88/videoMain #The Stream you want to monitor
          roles:
            - detect
            - record
    onvif:
      host: xxx.xxx.xxx.xxx
      port: 888
      user: xxx
      password: xxxx
    motion:
      mask:
        - 0,53,240,48,241,0,0,0
    detect:
      enabled: True # Detection is disabled
      width: 1280 # The Cameras resolution
      height: 720 # The Cameras resolution
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 30
          mode: active_objects
        pre_capture: 5 # Number of seconds to record before event
        post_capture: 8 # Number of seconds to record after event
        objects:
          - person
          - dog
```

### Relevant log output

```shell
2024-02-06 11:48:14.669310703  [2024-02-06 11:48:14] frigate.ptz.onvif              ERROR   : Unable to connect to camera: Binnen: Unknown error: Python int too large to convert to C int
```

### FFprobe output from your camera

```shell
[{"return_code":1,"stderr":"","stdout":""}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Foscam FI9826W
