### ISSUE TITLE
[Support]: Go2RTC Error

### ISSUE THREAD

**Issue by grainsoflight** [blakeblackshear/frigate#9717]
### Describe the problem you are having

In version .12 the go2rtc link would take you a GUI for go2rtc, in .13 it leads to a page of unformatted text. Is this the intended behavior?

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: 2MCHouYnzpqN3&
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:BW5ynKNVLDhQyS@192.168.5.3:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://0.0.0.0:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    record:
      enabled: True
      retain:
        days: 14
    motion:
      mask:
        - 422,0,421,26,208,29,207,0
        - 222,112,293,45,436,51,453,123,442,279,218,302
    objects:
      filters:
        person:
          mask:
            - 301,0,0,0,0,480,230,480,229,100,265,99
            - 438,40,640,0,640,480,501,480,438,437
            - 234,102,305,21,440,52,445,187,228,185
    snapshots:
      enabled: True
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://0.0.0.0:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 8
    motion:
      mask:
        - 231,36,649,40,650,0,267,0,236,0
        - 444,53,453,270,377,296,350,67
        - 132,71,198,307,300,276,261,41
        - 578,0,567,185,509,205,509,0
        - 896,0,896,168,798,98,801,0
    record:
      enabled: True
      retain:
        days: 14
    snapshots:
      enabled: True
  backzoom:
    ffmpeg:
      inputs: 
        - path: rtsp://0.0.0.0:8554/backzoom
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: False
      retain: 
         days: 14
    snapshots:
      enabled: False
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://0.0.0.0:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
          objects:
            person: 14

go2rtc:
  streams:
    doorbell:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.3:554/h264Preview_01_main
      - "ffmpeg:doorbell#audio=opus"
    backyard:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_01_main
      - "ffmpeg:backyard#video=h264#audio=opus#hardware"
    backzoom:
      - rtsp://admin:BW5ynKNVLDhQyS@192.168.5.2:554/h264Preview_02_main
      - "ffmpeg:backzoom#video=h264#hardware"
    garage:
      - rtsp://jpfeifer14:wtdmhcbE13@192.168.5.4/live
      - "ffmpeg:garage"
  webrtc:
    candidates:
      - 192.168.0.11:8555
      - stun:8555

birdseye:
  enabled: True
  restream: True
  mode: continuous
```

### Relevant log output

```shell
This is what the link spits out 

{"backyard":{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:48286","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHH+KrTuiS7I=;sprop-pps=RAHAcvCcFAobJA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n","send":10678726,"senders":["96 H265, bytes=10430108, receivers=1","97 MPEG4-GENERIC/16000, bytes=112139, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://0.0.0.0:8554/backyard","user_agent":"FFmpeg Frigate/0.13.1-34fb1c2"}],"producers":[{"medias":["video, recvonly, H265","audio, recvonly, MPEG4-GENERIC/16000"],"receivers":["96 H265, bytes=10430108, senders=1","97 MPEG4-GENERIC/16000, bytes=112139, senders=1"],"recv":10649179,"remote_addr":"192.168.5.2:554","sdp":"v=0\r\no=- 1707033622191780 1 IN IP4 192.168.0.3\r\ns=Session streamed by \"preview\"\r\ni=h264Preview_01_main\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2020.08.12\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\na=x-qt-text-inf:h264Preview_01_main\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqAB4CACHH+KrTuiS7I=;sprop-pps=RAHAcvCcFAobJA==\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:track2\r\n","type":"RTSP active producer","url":"rtsp://192.168.5.2/h264Preview_01_main/","user_agent":"go2rtc/1.8.5"},{"url":"ffmpeg:backyard#video=h264#audio=opus#hardware"}]},"backzoom":{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:48280","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqADwIARB8uKrTuiS7I=;sprop-pps=RAHAcvAbJA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n","send":13929642,"senders":["96 H265, bytes=13657692, receivers=1","97 MPEG4-GENERIC/16000, bytes=112271, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://0.0.0.0:8554/backzoom","user_agent":"FFmpeg Frigate/0.13.1-34fb1c2"}],"producers":[{"medias":["video, recvonly, H265","audio, recvonly, MPEG4-GENERIC/16000"],"receivers":["96 H265, bytes=13657692, senders=1","97 MPEG4-GENERIC/16000, bytes=112271, senders=1"],"recv":13892579,"remote_addr":"192.168.5.2:554","sdp":"v=0\r\no=- 1707033622192596 1 IN IP4 192.168.0.3\r\ns=Session streamed by \"preview\"\r\ni=h264Preview_02_main\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2020.08.12\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\na=x-qt-text-inf:h264Preview_02_main\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=150;interop-constraints=000000000000;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqADwIARB8uKrTuiS7I=;sprop-pps=RAHAcvAbJA==\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:track2\r\n","type":"RTSP active producer","url":"rtsp://192.168.5.2/h264Preview_02_main/","user_agent":"go2rtc/1.8.5"},{"url":"ffmpeg:backzoom#video=h264#hardware"}]},"birdseye":{"consumers":null,"producers":[{"url":"exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -rtsp_transport tcp -f rtsp {output}"}]},"doorbell":{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:48266","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408;\r\na=control:trackID=1\r\n","send":13773160,"senders":["96 H264, bytes=13502727, receivers=1","97 MPEG4-GENERIC/16000, bytes=108881, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://0.0.0.0:8554/doorbell","user_agent":"FFmpeg Frigate/0.13.1-34fb1c2"},{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"],"remote_addr":"127.0.0.1:56274","send":4110072,"senders":["96 H264, bytes=4232635, receivers=1","97 MPEG4-GENERIC/16000, bytes=35332, receivers=1"],"type":"MSE/WebSocket active consumer","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0"}],"producers":[{"medias":["video, recvonly, H.264 High 5.1","audio, recvonly, MPEG4-GENERIC/16000","audio, sendonly, PCMU/8000"],"receivers":["96 H264, bytes=13502727, senders=2","97 MPEG4-GENERIC/16000, bytes=108881, senders=2"],"recv":13733396,"remote_addr":"192.168.5.3:554","sdp":"v=0\r\no=- 1707231842926369 1 IN IP4 192.168.5.3\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408;\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly","type":"RTSP active producer","url":"rtsp://192.168.5.3/Preview_01_main/","user_agent":"go2rtc/1.8.5"},{"url":"ffmpeg:doorbell#audio=opus"}]},"garage":{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:38164","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D4028;sprop-parameter-sets=Z01AKJ2oHgCJ+WEAAAMAAQAAAwAehA==,aO48gA==\r\na=control:trackID=0\r\n","send":169898,"senders":["96 H264, bytes=454760, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://0.0.0.0:8554/garage","user_agent":"FFmpeg Frigate/0.13.1-34fb1c2"}],"producers":[{"medias":["video, recvonly, H.264 Main 4.0","audio, recvonly, PCMA/8000"],"receivers":["96 H264, bytes=454760, senders=1","8 PCMA/8000, bytes=43520, senders=0"],"recv":503300,"remote_addr":"192.168.5.4:554","sdp":"v=0\r\no=- 1707274482103051 1 IN IP4 192.168.5.4\r\ns=Session streamed by the WYZE Media Server\r\ni=live\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2017.05.24\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:Session streamed by the WYZE Media Server\r\na=x-qt-text-inf:live\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:500\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D4028;sprop-parameter-sets=Z01AKJ2oHgCJ+WEAAAMAAQAAAwAehA==,aO48gA==\r\na=control:track1\r\nm=audio 0 RTP/AVP 8\r\nc=IN IP4 0.0.0.0\r\nb=AS:64\r\na=rtcp-mux\r\na=fmtp:0 PCMA/8000\r\na=ptime:10\r\na=control:track2\r\n","type":"RTSP active producer","url":"rtsp://192.168.5.4/live/","user_agent":"go2rtc/1.8.5"},{"url":"ffmpeg:garage"}]}}
```

### FFprobe output from your camera

```shell
No specific camera
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

no specific to camera
