### ISSUE TITLE
[Support]: PTZ for Sricam SP012

### ISSUE THREAD

**Issue by kakou-fr** [blakeblackshear/frigate#9724]
### Describe the problem you are having

Hi all,

PTZ and tracking support didn't work with SP012 camera

This is the script I use to move it since some month. Could support be added for this camera ?
Maybe add a possibility to call a script for moving the camera ?

```
import requests
import sys

XMAX = 1
XMIN = -1
YMAX = 1
YMIN = -1
class Camera:
    def __init__(self, ip='192.168.4.245', port='5000', user='', passwd=''):
        self.ptz_body = """<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsdl="http://www.onvif.org/ver20/ptz/wsdl" xmlns:sch="http://www.onvif.org/ver10/schema">
   <soap:Header/>
   <soap:Body>
      <wsdl:ContinuousMove>
         <wsdl:Velocity>
            <!--Optional:-->
            <sch:PanTilt x="{}" y="{}" space="{}"/>
         </wsdl:Velocity>
         <!--Optional:-->
      </wsdl:ContinuousMove>
   </soap:Body>
</soap:Envelope>"""
        self.headers = {'content-type': 'text/xml', 'passwd': passwd, 'port': port, 'user': user}
        self.url = 'http://{}:{}/'.format(ip, port)


    def move_up(self,  timeout=1):
        print('move up...')
        x = 0
        y = YMAX

        response = requests.post(self.url, data=self.ptz_body.format(x, y, '0'), headers=self.headers)
        print(response)

    def move_down(self,  timeout=1):
        print('move down...')
        x = 0
        y = YMIN

        response = requests.post(self.url, data=self.ptz_body.format(x, y, '0'), headers=self.headers)
        print(response)

    def move_right(self,  timeout=1):
        print('move right...')
        x = XMAX
        y = 0

        response = requests.post(self.url, data=self.ptz_body.format(x, y, '0'), headers=self.headers)
        print(response)

    def move_left(self,  timeout=1):
        print('move left...')
        x = XMIN
        y = 0
        response = requests.post(self.url, data=self.ptz_body.format(x, y, '0'), headers=self.headers)
        print(response)

ip = sys.argv[1]
port = sys.argv[2]
move = sys.argv[3]

cam = Camera(ip, port)
if move == "L":
	cam.move_left()
elif move == "R":
	cam.move_right()
elif move == "U":
	cam.move_up()
elif move == "D":
	cam.move_down()

```

### Version

0.13.0-01e2d20

### Frigate config file

```yaml
salon:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXXXXXX@192.168.4.245:554/onvif1
          roles:
            - detect
            - record
      input_args: preset-rtsp-udp
    motion:
      mask:
        - 0,71,746,74,742,0,0,0
    detect:
      enabled: true 
      width: 1280
      height: 720
    zones:  
      salon-in:
        coordinates: 0,720,1280,720,1280,45,0,48
        objects:
        - person
        - cat
        - dog
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.4.245
      # Optional: ONVIF port for device (default: shown below).
      port: 5000
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: XXXXXXXXXXXX
      # Optional: PTZ camera object autotracking. Keeps a moving object in
      # the center of the frame by automatically moving the PTZ camera.
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: False
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: False
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: disabled
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        zoom_factor: 0.3
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - salon-in
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 10
        # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
        #movement_weights: []
```

### Relevant log output

```shell
user@agentDVR:~/frigate$ docker exec -it 5dc79f86b56c /bin/bash
root@5dc79f86b56c:/opt/frigate# python3 /media/frigate/ptz.py 
Connected to ONVIF camera
Created media service object
Creating PTZ object
Created PTZ service object
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 153, in wrapped
    return call(params, callback)
  File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 140, in call
    ret = func(**params)
  File "/usr/local/lib/python3.9/dist-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/usr/local/lib/python3.9/dist-packages/zeep/wsdl/bindings/soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python3.9/dist-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
  File "/usr/local/lib/python3.9/dist-packages/zeep/wsdl/bindings/soap.py", line 391, in process_error
    raise Fault(
zeep.exceptions.Fault: Method 'ns0:GetConfigurations' not implemented: method name or namespace not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/frigate/ptz.py", line 38, in <module>
    configs = ptz.GetConfigurations(request)[0]
  File "/usr/local/lib/python3.9/dist-packages/onvif/client.py", line 26, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Method 'ns0:GetConfigurations' not implemented: method name or namespace not recognized
root@5dc79f86b56c:/opt/frigate#
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[h264 @ 0x564cf3823cc0] negative number of zero coeffs at 44 1
[h264 @ 0x564cf3823cc0] error while decoding MB 44 1
[h264 @ 0x564cf3823cc0] concealing 3525 DC, 3525 AC, 3525 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2664 DC, 2664 AC, 2664 MV errors in P frame
[h264 @ 0x564cf3823cc0] top block unavailable for requested intra mode
[h264 @ 0x564cf3823cc0] error while decoding MB 58 0
[h264 @ 0x564cf3823cc0] concealing 3591 DC, 3591 AC, 3591 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2680 DC, 2680 AC, 2680 MV errors in P frame
[h264 @ 0x564cf3823cc0] P sub_mb_type 32 out of range at 68 0
[h264 @ 0x564cf3823cc0] error while decoding MB 68 0
[h264 @ 0x564cf3823cc0] concealing 3581 DC, 3581 AC, 3581 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2680 DC, 2680 AC, 2680 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2709 DC, 2709 AC, 2709 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2680 DC, 2680 AC, 2680 MV errors in P frame
[h264 @ 0x564cf3823cc0] mb_type 112 in P slice too large at 57 0
[h264 @ 0x564cf3823cc0] error while decoding MB 57 0
[h264 @ 0x564cf3823cc0] concealing 3592 DC, 3592 AC, 3592 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2680 DC, 2680 AC, 2680 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 3039 DC, 3039 AC, 3039 MV errors in P frame
[h264 @ 0x564cf3823cc0] top block unavailable for requested intra mode
[h264 @ 0x564cf3823cc0] error while decoding MB 55 0
[h264 @ 0x564cf3823cc0] concealing 3594 DC, 3594 AC, 3594 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2680 DC, 2680 AC, 2680 MV errors in P frame
    Last message repeated 3 times
[h264 @ 0x564cf3823cc0] P sub_mb_type 5 out of range at 54 0
[h264 @ 0x564cf3823cc0] error while decoding MB 54 0
[h264 @ 0x564cf3823cc0] concealing 3595 DC, 3595 AC, 3595 MV errors in P frame
[h264 @ 0x564cf3823cc0] concealing 2680 DC, 2680 AC, 2680 MV errors in P frame
    Last message repeated 1 times
Input #0, rtsp, from 'rtsp://admin:888888@192.168.4.245:554/onvif1':
  Metadata:
    title           : H.264 Video, RtspServer_0.0.0.2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 640x360, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

SRICAM SP012
