### ISSUE TITLE
[Support]: go2rtc 1.8.5 streams info page

### ISSUE THREAD

**Issue by hmjgriffon1** [blakeblackshear/frigate#9726]
### Describe the problem you are having

When I click on streams info all I see is json. Is this related to this part of the breaking changes?

Removed direct access to the go2rtc http API to mitigate potential remote code execution via the exec source, you will need to map port 1984 and access directly if using go2rtc http api outside of frigate

Would I add it to this section of my frigate docker compose.yml?

    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      -"1984:1984/tcp" # go2rtc http API

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
ersion: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hmjgriffon/frigate/config/:/config/
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"6/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":480,"width":704},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision

### Any other information that may be helpful

this is what I see now when I go to http://10.0.0.2:5000/api/go2rtc/streams

{
    "living_room_cam": {
        "consumers": null,
        "producers": [
            {
                "url": "ffmpeg:rtsp://*:*@10.0.0.7:554/Streaming/Channels/101"
            },
            {
                "url": "ffmpeg:living_room_cam#audio=aac"
            }
        ]
    },
    "living_room_cam_sub": {
        "consumers": null,
        "producers": [
            {
                "url": "ffmpeg:rtsp://*:*@10.0.0.7:554/Streaming/Channels/102"
            },
            {
                "url": "ffmpeg:living_room_cam_sub#audio=aac"
            }
        ]
    },
    "office_cam": {
        "consumers": [
            {
                "medias": [
                    "video, sendonly, H264, H265",
                    "audio, sendonly, MPEG4-GENERIC"
                ],
                "remote_addr": "172.18.0.1:49318",
                "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=Z2QAKKwbGoB4AiflwFuAgICgAAB9AAAOph0MAH0Fd5caGAD6Cu8uFAA=,aO44MAA=\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/32000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1288\r\na=control:trackID=1\r\n",
                "send": 72455714,
                "senders": [
                    "96 H264, bytes=70440033, receivers=1",
                    "97 MPEG4-GENERIC/32000, bytes=1080993, receivers=1"
                ],
                "type": "RTSP passive consumer",
                "url": "rtsp://10.0.0.2:8554/office_cam",
                "user_agent": "FFmpeg Frigate/0.13.1-34fb1c2"
            }
        ],
        "producers": [
            {
                "medias": [
                    "video, recvonly, H.264 High 4.0",
                    "audio, recvonly, MPEG4-GENERIC/32000",
                    "application, recvonly, VND.ONVIF.METADATA"
                ],
                "receivers": [
                    "96 H264, bytes=70440033, senders=1",
                    "97 MPEG4-GENERIC/32000, bytes=1080993, senders=1"
                ],
                "recv": 72224506,
                "remote_addr": "10.0.0.12:554",
                "sdp": "v=0\r\no=- 2257436519 2257436519 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:15.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=Z2QAKKwbGoB4AiflwFuAgICgAAB9AAAOph0MAH0Fd5caGAD6Cu8uFAA=,aO44MAA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/32000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1288\r\na=recvonly\r\nm=application 0 RTP/AVP 107\r\na=control:trackID=4\r\na=rtpmap:107 vnd.onvif.metadata/90000\r\na=recvonly\r\n",
                "type": "RTSP active producer",
                "url": "rtsp://10.0.0.12:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/",
                "user_agent": "go2rtc/1.8.5"
            },
            {
                "url": "ffmpeg:office_cam#audio=opus"
            }
        ]
    },
    "office_cam_sub": {
        "consumers": [
            {
                "medias": [
                    "video, sendonly, H264, H265",
                    "audio, sendonly, MPEG4-GENERIC"
                ],
                "remote_addr": "172.18.0.1:49310",
                "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.5\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640016;sprop-parameter-sets=Z2QAFqwbGoCwPf//ACgAIW4MDAyAAAH0AAATiHQwD6V3lxoYB9K7y4UA,aO44MAA=\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:trackID=1\r\n",
                "send": 7456190,
                "senders": [
                    "96 H264, bytes=6773066, receivers=1",
                    "97 MPEG4-GENERIC/16000, bytes=539636, receivers=1"
                ],
                "type": "RTSP passive consumer",
                "url": "rtsp://10.0.0.2:8554/office_cam_sub",
                "user_agent": "FFmpeg Frigate/0.13.1-34fb1c2"
            }
        ],
        "producers": [
            {
                "medias": [
                    "video, recvonly, H.264 High 2.2",
                    "audio, recvonly, MPEG4-GENERIC/16000",
                    "application, recvonly, VND.ONVIF.METADATA"
                ],
                "receivers": [
                    "96 H264, bytes=6773066, senders=1",
                    "97 MPEG4-GENERIC/16000, bytes=539636, senders=1"
                ],
                "recv": 7422782,
                "remote_addr": "10.0.0.12:554",
                "sdp": "v=0\r\no=- 2257436519 2257436519 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:5.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640016;sprop-parameter-sets=Z2QAFqwbGoCwPf//ACgAIW4MDAyAAAH0AAATiHQwD6V3lxoYB9K7y4UA,aO44MAA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\nm=application 0 RTP/AVP 107\r\na=control:trackID=4\r\na=rtpmap:107 vnd.onvif.metadata/90000\r\na=recvonly\r\n",
                "type": "RTSP active producer",
                "url": "rtsp://10.0.0.12:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif/",
                "user_agent": "go2rtc/1.8.5"
            },
            {
                "url": "ffmpeg:office_cam_sub#audio=opus"
            }
        ]
    }
}
