### ISSUE TITLE
[Config Support]: adjusting brightness via ffmpeg

### ISSUE THREAD

**Issue by harrynorton8630** [blakeblackshear/frigate#9727]
### Describe the problem you are having

I've currently got a doorbell set up and working correctly via go2rtc and using the restreams and it's working great.

If possible, is there a way to get ffmpeg to alter the brightness of the feeds that are used for recording/detection? My camera faces into the street and 90% of the day is facing directly into sunlight. The auto-adjustment on the camera balances the contrast out, but it means that the sky/clouds are always bright, and anything that's in the foreground and shadows is dark. Unfortunately its the shadows and the darkness where all the action happens, so I'd like to try and find a way to increase either the brightness or the gamma of the feed using ffmpeg parameters, but i'm not sure where to start?

Suspected it might be using something along the lines of the exec command? (https://github.com/blakeblackshear/frigate/issues/9408#issuecomment-1904150992)

comined with passing parameters (found a website that gave an example of: "ffmpeg -i INPUT.MOV -vf eq=brightness=0.06:gamma=1.1 -c:a copy OUTPUT.MOV").

Do you know if there is any way to do this?

Thanks

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
go2rtc:
  streams:
    fd_main:
      - rtsp://frigate:*@192.168.0.4:554/Preview_01_main
      - "ffmpeg:fd_main#audio=opus"
    fd_sub:
      - rtsp://frigate:*@192.168.0.4:554/Preview_01_sub
      - "ffmpeg:fd_sub#audio=opus"
     
cameras:
  front_door:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/fd_sub 
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/fd_main 
        input_args: preset-rtsp-restream
        roles:
        - record
```

### Relevant log output

```shell
no logs.
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB
