### ISSUE TITLE
Poor motion detection when dark and mismatching object

### ISSUE THREAD

**Issue by woody4165** [blakeblackshear/frigate#9732]
### Describe the problem you are having

Hi all

During night, I have poor motion detection and most of the times it mismatches objects like in this snapshot

![snapshot-1707329221 905571-mghzsc](https://github.com/blakeblackshear/frigate/assets/6501444/ec02e8b9-dd07-42db-a1b1-242a27c068bd)

or like in this clip

https://github.com/blakeblackshear/frigate/assets/6501444/0600fd97-bf3e-4c4f-b308-5c53d99bcf0d

Is there a way to avoid these modifying the config.yml ?

My cam is a Imou Cruiser SE+ 4MP

Thanks

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse


database:
  path: /media/frigate/db/frigate.db

mqtt:
  host: 192.168.xx.xx
  user: user
  password: password
  topic_prefix: frigate


ffmpeg:
  global_args: -hide_banner -loglevel warning


  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p



detectors:
  coral:
    type: edgetpu
    device: usb


birdseye:
  enabled: True
  mode: continuous
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8



cameras:
  cancello:

    ffmpeg:
      inputs:
        - path: "rtsp://admin:pwd@192.168.xx.xx/cam/realmonitor?channel=1&subtype=1&authbasic=auth"
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
      min_initialized: 2
      # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25
    motion:
      threshold: 30
      lightning_threshold: 0.8
      contour_area: 20
      frame_alpha: 0.01
      improve_contrast: True
      # giorno
      mask: 0,259,114,224,186,194,478,200,704,194,913,297,1118,320,1197,109,1238,59,1280,0,0,0


    zones:
      # giorno
      lontano:
        coordinates: 0,425,313,347,299,200,144,174,95,234,56,239,0,246
      vicino:
        coordinates: 308,202,635,163,804,167,942,93,1280,122,1280,720,658,720,0,720,0,524,0,393,313,365

    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
      filters:
        person:
          min_area: 4000
          max_area: 100000
          min_ratio: 0.62
          max_ratio: 2.0
          min_score: 0.4
          threshold: 0.5
          mask:
            # giorno
            - 0,259,114,224,186,194,478,200,704,194,913,297,1118,320,1197,109,1238,59,1280,0,0,0

        car:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.3
          threshold: 0.5
          mask:
            # giorno
            - 0,259,114,224,186,194,478,200,704,194,913,297,1118,320,1197,109,1238,59,1280,0,0,0

        motorcycle:
          mask:
            # giorno
            - 0,259,114,224,186,194,478,200,704,194,913,297,1118,320,1197,109,1238,59,1280,0,0,0

        dog:
          mask:
            # giorno
            - 0,259,114,224,186,194,478,200,704,194,913,297,1118,320,1197,109,1238,59,1280,0,0,0
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.3
          threshold: 0.5

        cat:
          mask:
            # giorno
            - 0,259,114,224,186,194,478,200,704,194,913,297,1118,320,1197,109,1238,59,1280,0,0,0
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.3
          threshold: 0.5

    snapshots:
      required_zones:
        - lontano
        - vicino
      enabled: True
      bounding_box: True
      retain:
        default: 7
        mode: active_objects
        objects:
          dog: 1
          cat: 1
          car: 5
          motorcycle: 5
          person: 7


    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        pre_capture: 30
        post_capture: 60
        retain:
          default: 7
          mode: active_objects
          objects:
            dog: 1
            cat: 1
            car: 5
            motorcycle: 5
            person: 7
        required_zones:
          - lontano
          - vicino
```

### Relevant log output

```shell
none
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

I've installed Frigate on Proxmox 8.1.4 following the official documentation

**Comment by NickM-27** [comment]
For one I would suggest using preset-vaapi instead of manual args. 

Secondly, the docs have a guide on tuning motion detection. https://docs.frigate.video/configuration/motion_detection

**Comment by woody4165** [comment]
> For one I would suggest using preset-vaapi instead of manual args.
OK, thanks, I'll do now

> 
> Secondly, the docs have a guide on tuning motion detection. https://docs.frigate.video/configuration/motion_detection

I have checked and tried several settings, but without finding the right one when it's dark

During the day seems to be ok.

**Comment by NickM-27** [comment]
Things like headlights are always going to cause problems because that drastically changes the scene.

**Comment by woody4165** [comment]
I know, but at the moment I can't move the cam.

Do you think there is some settings that can be adjusted in this situation, with an headlight in the middle of the image?

Thanks

**Comment by woody4165** [comment]
I've tried with an automation done via Nodered after sunset

This is the configuration during day:

```
    motion:
      threshold: 30
      lightning_threshold: 0.8
      contour_area: 20
      frame_alpha: 0.01
      improve_contrast: False
```

and this one during night:


```
    motion:
      threshold: 10
      lightning_threshold: 0.8
      contour_area: 9
      frame_alpha: 0.01
      improve_contrast: True
```

I also activate HDR on the cam during night


Still no benefit...
