### ISSUE TITLE
[Config Support]: v13 and stationary objects

### ISSUE THREAD

**Issue by brandondb1** [blakeblackshear/frigate#9733]
### Describe the problem you are having

Running  Frigate on Truenas Scale.  I upgraded to v13.1 and noticed the processor utilization had immediately gone way up (previously 3-5%, now 20+%).  Digging into it, I noticed that Frigate is now constantly detecting the car parked in my driveway and recording it as an event (the car is not moving).  The same car was parked in the same place before I did the upgrade and Frigate didn't do this - Frigate has worked perfectly with detecting motion (cars and people) on the camera in question up until the upgrade.

Looking at the debug screen, it seems like every time a car drives by in the street (creating motion in the frame) Frigate re-detects the car in the driveway and records a new event.  This can be every few minutes (every time a car passes) and creates so many events that anything that would be of actual interest is buried in hundreds of these false positives.  I have a motion filter screening the street area, but motion there still causes the car in the driveway to be 'rediscovered' and Frigate doesn't seem to remember that it's there.

I'm assuming it's a configuration issue of some sort with the changes made to v13.1, so I'm hoping for some guidance on how to improve the recognition/retention of stationary objects.

Thanks in advance, and thanks for a great piece of software!

### Version

13

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.xx
  user: xxxxx
  password: xxxxx
birdseye:
  enabled: true
  mode: continuous
objects:
  track:
    - person
    - car
go2rtc:
  streams:
    Driveway:
      - "ffmpeg:http://192.168.1.94/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx"
    DrivewaySub:
      - "ffmpeg:http://192.168.1.94/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx"
    Porch:
      - "ffmpeg:http://192.168.1.92/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx"
    PorchSub:
      - "ffmpeg:http://192.168.1.92/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx"
    EastYard:
      - "ffmpeg:http://192.168.1.93/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx"
    EastYardSub:
      - "ffmpeg:http://192.168.1.93/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx"
    MainDeck:
      - rtsp://admin:m@ge11an@192.168.1.90/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46YWRtaW4=
    MainDeckSub:
      - rtsp://admin:m@ge11an@192.168.1.90/cam/realmonitor?channel=1&subtype=01&authbasic=YWRtaW46YWRtaW4=
    LivingRoom:
      - rtsp://admin:mage11an@192.168.1.95:554/h264Preview_01_main
    LivingRoomSub:
      - rtsp://admin:mage11an@192.168.1.95:554/h264Preview_01_sub


cameras:
  Porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/PorchSub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        retain:
          mode: active_objects
          default: 10
    birdseye:
      enabled: True
      mode: objects
    live:
      stream_name: Porch
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/DrivewaySub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car
    motion:
      mask:
        - 0,0,640,0,640,140,0,171
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        retain:
          mode: active_objects
          default: 10
    live:
      stream_name: Driveway
    birdseye:
      enabled: True
      mode: objects
  EastYard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/EastYard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/EastYardSub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    live:
      stream_name: EastYard
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
      
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        retain:
          mode: active_objects
          default: 10
    birdseye:
      enabled: True
      mode: objects
  LivingRoom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/LivingRoom?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/LivingRoomSub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          mode: active_objects
          default: 10
    birdseye:
      enabled: True
      mode: objects
    live:
      stream_name: LivingRoom
  MainDeck:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/MainDeck
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/MainDeckSub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        retain:
          mode: active_objects
          default: 10
    birdseye:
      enabled: True
      mode: objects
    live:
      stream_name: MainDeck
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
ui:
  timezone: America/New_York
```

### Relevant log output

```shell
n/a
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

Truenas Scale, AMD Ryzen 5 1600, 48 GB RAM.  No GPU or coral.
