### ISSUE TITLE
[Support]: Debug window / zone mask window size

### ISSUE THREAD

**Issue by paulcusick3** [blakeblackshear/frigate#9747]
### Describe the problem you are having

Since last update the camera debug size changed and all the zones are not aligned.  Same with the mask and zone creator.  The window size changes from live to debug.

![image](https://github.com/blakeblackshear/frigate/assets/46980268/7fe51b89-920b-402a-8714-527765552f59)

### Version

13.1

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.10
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: homeassistant
  password: ********************
  stats_interval: 60

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb
record:
  enabled: False
  retain:
    days: 3
    mode: active_objects
  events:
    retain:
      default: 3
      mode: active_objects
objects:
  track:
    - person
    - car
# ffmpeg:
  # input_args:
    # - -avoid_negative_ts
    # - make_zero
    # - -fflags
    # - nobuffer
    # - -flags
    # - low_delay
    # - -strict
    # - experimental
    # - -fflags
    # - +genpts+discardcorrupt
    # - -vsync
    # - drop
    # - -use_wallclock_as_timestamps
    # - '1'
cameras:
  Driveway: # <------ Name the camera
      ffmpeg:
        inputs:
          - path: rtsp://192.168.1.10:8554/driveway-sub # <----- The stream you want to use for detection
            roles:
              - detect
          # - path: rtsp://192.168.1.10:8554/driveway # <----- The stream you want to use for detection
          #   roles:
          #     - record
      detect:
        enabled: true
        stationary:
          interval: 60
          threshold: 50
      motion:
        mask:
          - 1109,720,1242,720,1242,669,1104,669
          - 466,720,562,482,565,239,282,277,32,404,0,720
          - 603,44,662,38,658,0,598,0
      zones:
        driveway_parking:
          coordinates: 529,669,1259,677,1280,552,1253,454,1186,300,1280,284,1230,214,1097,177,1030,228,574,270
          objects:
           - person
           - car
        driveway_moving:
          inertia: 1
          coordinates: 542,195,1015,217,953,0,388,0
          objects:
            - car
            - person

      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 7 
  Front: # <------ Name the camera
      ffmpeg:
        inputs:
          - path: rtsp://192.168.1.10:8554/front-sub # <----- The stream you want to use for detection
            roles:
              - detect
      detect:
        enabled: True # <---- disable detection until you have a working camera feed
        # width: 1280 # <---- update for your camera's resolution
        # height: 720 # <---- update for your camera's resolution
      motion:
        mask:
          - 1109,720,1242,720,1242,669,1104,669
          - 252,106,556,96,544,0,249,0
          - 259,720,1060,720,1010,577,691,394,472,343,165,358
          # - 882,271,1013,360,1046,251,925,183
          
      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 7 
  Front2: # <------ Name the camera
      ffmpeg:
        inputs:
          - path: rtsp://192.168.1.10:8554/front2-sub # <----- The stream you want to use for detection
            roles:
              - detect
      detect:
        enabled: True
      motion:
        mask:
          - 1113,720,1246,720,1244,671,1108,672
          - 0,144,313,87,733,77,1280,153,1280,0,0,0
      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 7 
  Garage:
    ffmpeg:
      inputs:
       - path: rtsp://192.168.1.10:8554/garage-sub
         roles:
          - detect
    detect:
      enabled: True
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 7
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
