### ISSUE TITLE
[Support]: Frigate loses recordings after re-pulling and re-deploying stack

### ISSUE THREAD

**Issue by cooljon22** [blakeblackshear/frigate#9755]
### Describe the problem you are having

I have Frigate running in a docker container created in Portainer with docker-compose. When I change the docker-compose script in Portainer and choose Update stack>Re-pull and Re-deploy, Frigate no longer shows any old recordings or events. The recordings are still in the file system, they just don't show up in Frigate. I'm a bit of a n00b when it comes to docker and Portainer. Thanks in advance for any help!

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.121
  user: frigate
  password: [password]
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  cpu1:
    type: cpu
    num_threads: 4

birdseye:
  enabled: false
  mode: continuous

go2rtc:
  webrtc:
    candidates:
      - 192.168.1.145:8555
      - stun:8555
  streams:
    garage:
      - rtsp://admin:[password]@192.168.1.105:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam#audio=aac"
    garage_sub:
      - rtsp://admin:[password]@192.168.1.105:554/cam/realmonitor?channel=1&subtype=1
    shedfront:
      - rtsp://admin:[password]@192.168.1.147:554/cam/realmonitor?channel=1&subtype=0
    shedfront_sub:
      - rtsp://admin:[password]@192.168.1.147:554/cam/realmonitor?channel=1&subtype=1
    condo:
      - rtsp://[user]:[password]@192.168.1.113:554/h264Preview_01_main
      - "ffmpeg:rtsp_cam#audio=aac"
    condo_sub:
      - rtsp://[user]:[password]@192.168.1.113:554/h264Preview_01_sub


timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: True
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

cameras:
  condo:
   ffmpeg:
    inputs:
     - path: rtsp://127.0.0.1:8554/condo
       input_args: preset-rtsp-restream
       roles:
         - record
     - path: rtsp://127.0.0.1:8554/condo_sub
       input_args: preset-rtsp-restream
       roles:
         - detect
   onvif:
    host: 192.168.1.113
    port: 8000
    user: [user]
    password: [password]
   detect:
    width: 640
    height: 352
    fps: 5
   objects:
     track:
       - person
       - cat
  garage:
   ffmpeg:
    inputs:
     - path: rtsp://127.0.0.1:8554/garage
       input_args: preset-rtsp-restream
       roles:
         - record
     - path: rtsp://127.0.0.1:8554/garage_sub
       input_args: preset-rtsp-restream
       roles:
         - detect
   detect:                 
     width: 640
     height: 480
     fps: 5
   objects:
     track:
       - person
      # - car
  shedfront:
   ffmpeg:
    inputs:
     - path: rtsp://127.0.0.1:8554/shedfront
       input_args: preset-rtsp-restream
       roles:
         - record
     - path: rtsp://127.0.0.1:8554/shedfront_sub
       input_args: preset-rtsp-restream
       roles:
         - detect
   detect:                 
     width: 640
     height: 480
     fps: 5
   objects:
     track:
       - person
      # - car
```

### Relevant log output

```shell
Not sure I have any relevant logs
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1072
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x352
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)

Copy
Close
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest and Reolink

### Any other information that may be helpful

_Portainer docker-compose_
version: "3.9"
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
# Added this section so that GPU stats will be visible
    cap_add:
      - CAP_PERFMON
    privileged: true
    restart: always
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /home/frigate/config.yml:/config/config.yml
     - /media/sda1/frigate:/media/frigate
    ports:
     - 5000:5000
     - 1935:1935
    environment:
     FRIGATE_RTSP_PASSWORD: "[password]"
     PLUS_API_KEY: "[key]"
