### ISSUE TITLE
[Config Support]: Events without snapshots

### ISSUE THREAD

**Issue by luzik** [blakeblackshear/frigate#9757]
### Describe the problem you are having

I have cameras that I want be notified about object detection motion and audio events (using HA), but without saving any image nor recordings on drive. I don't know how to achieve this with current configuration options.

With configuration below I can be notified about motion - and turn lights on, but can't detect objects. Now I want to be also notified about dog barks audio events, but those snapshots make my wife privacy concerns.
I do not care about events in frigate UI.

### Version

0.13.1

### Frigate config file

```yaml
audio:
  enabled: true
cameras:
  tablet:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tablet
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    objects:
      track: []
    record:
      enabled: False
####default config
#snapshots:
#  enabled: False
```

### Relevant log output

```shell
No logs
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe
