### ISSUE TITLE
[Support]: Duplicate events even after several hours since recording time

### ISSUE THREAD

**Issue by herrenP** [blakeblackshear/frigate#9764]
### Describe the problem you are having

In the list of events I see two items of the same recording. Well, they do differ 1 second according to the UI but the content is the same. A guy standing by his bike with his back against the camera fiddling with his backback, then throwing on the backpack before the video ends. I've seen the same behavior with duplicates on both cameras.

I've seen other issues here regarding duplicate events and as I understand it there's a cleanup job in Frigate that should run quite often (every 5 min or so?) to remove duplicates. But this recording was done about 6h ago (08:48 UTC+1) and Frigate has been running the whole period as far as I know.

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  enabled: False
birdseye:
  enabled: False
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  width: 300
  height: 300
  input_pixel_format: bgr
  input_tensor: nhwc
  model_type: ssd
database:
  path: /config/frigate.db
audio:
  enabled: False
  max_not_heard: 30
  min_volume: 500
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8
logger:
  default: info
  logs:
    frigate.event: debug
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: []
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac
    rtmp: preset-rtmp-generic
  retry_interval: 10
detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: True
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000
  annotation_offset: 0
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.7
motion:
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.01
  frame_height: 100
  improve_contrast: True
record:
  enabled: True
  expire_interval: 60
  sync_recordings: False
  retain:
    days: 0
    mode: all
  export:
    timelapse_args: "-vf setpts=0.04*PTS -r 30"
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones: [entre, uppfart]
    retain:
      default: 10
      mode: motion
      objects:
        person: 30
snapshots:
  enabled: False
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
  quality: 70
rtmp:
  enabled: False
live:
  stream_name: camera_name
  height: 720
  quality: 8
timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
cameras:
  Cam1:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@<obfuscated>:554/stream1
          roles:
            - audio
            - detect
            - record
    best_image_timeout: 60
    webui_url: ""
    zones:
      entre:
        coordinates: 1566,55,1101,0,680,36,470,0,0,0,0,1080,1920,1080,1920,111
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    motion:
      mask: 508,0,512,31,693,44,963,21,1615,55,1920,122,1920,0
    ui:
      order: 0
      dashboard: True
  Cam2:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@<obfuscated>:554/stream1
          roles:
            - audio
            - detect
            - record
    best_image_timeout: 60
    webui_url: ""
    zones:
      uppfart:
        coordinates: 1920,0,1920,1080,0,1080,0,603,109,539,157,440,239,293,0,0
        inertia: 3
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    motion:
      mask: 0,73,0,418,177,339,226,285,158,239,165,178,112,117
    ui:
      order: 1
      dashboard: True
ui:
  live_mode: mse
  use_experimental: False
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"
telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  stats:
    amd_gpu_stats: True
    intel_gpu_stats: True
    network_bandwidth: False
  version_check: True
```

### Relevant log output

```shell
2024-02-08 23:39:44.735302442  [INFO] Preparing Frigate...
2024-02-08 23:39:44.855059580  [INFO] Starting Frigate...
2024-02-08 23:39:53.228918480  [2024-02-08 23:39:53] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-08 23:39:53.359609179  [2024-02-08 23:39:53] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2024-02-08 23:39:53.397779055  [2024-02-08 23:39:53] peewee_migrate.logs            INFO    : Starting migrations
2024-02-08 23:39:53.445682112  [2024-02-08 23:39:53] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-08 23:39:53.452528791  [2024-02-08 23:39:53] frigate.app                    INFO    : Recording process started: 298
2024-02-08 23:39:53.456072247  [2024-02-08 23:39:53] frigate.app                    INFO    : go2rtc process pid: 89
2024-02-08 23:39:53.488476570  [2024-02-08 23:39:53] frigate.app                    INFO    : Output process started: 309
2024-02-08 23:39:53.496614078  [2024-02-08 23:39:53] detector.ov                    INFO    : Starting detection process: 307
2024-02-08 23:39:53.528347341  [2024-02-08 23:39:53] frigate.app                    INFO    : Camera processor started for Cam1: 314
2024-02-08 23:39:53.552732587  [2024-02-08 23:39:53] frigate.app                    INFO    : Camera processor started for Cam2: 315
2024-02-08 23:39:53.560088135  [2024-02-08 23:39:53] frigate.app                    INFO    : Capture process started for Cam1: 317
2024-02-08 23:39:53.576722505  [2024-02-08 23:39:53] frigate.app                    INFO    : Capture process started for Cam2: 318
2024-02-08 23:39:55.822581521  [2024-02-08 23:39:55] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,300,300,3]
2024-02-08 23:39:55.822695125  [2024-02-08 23:39:55] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,1,100,7]
2024-02-08 23:39:55.823276862  [2024-02-08 23:39:55] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
...next line is from docker container log...
2024-02-09 08:38:17.070684654  <obfuscated_ip> - - [09/Feb/2024:08:38:17 +0100] "GET /ws HTTP/1.1" 101 37917 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "-"
...remaining lines are also GET calls but later in the day...
```

### FFprobe output from your camera

```shell
Running ffprobe from the UI just results in an endless ffprobe spinner
```

### Frigate stats

```json
{
    "cameras": {
        "Cam2": {
            "audio_dBFS": 0.0,
            "audio_rms": 0.0,
            "camera_fps": 5.1,
            "capture_pid": 318,
            "detection_enabled": 1,
            "detection_fps": 0.0,
            "ffmpeg_pid": 331,
            "pid": 315,
            "process_fps": 5.1,
            "skipped_fps": 0.0
        },
        "Cam1": {
            "audio_dBFS": 0.0,
            "audio_rms": 0.0,
            "camera_fps": 5.0,
            "capture_pid": 317,
            "detection_enabled": 1,
            "detection_fps": 0.0,
            "ffmpeg_pid": 333,
            "pid": 314,
            "process_fps": 5.0,
            "skipped_fps": 0.0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "17": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "80": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "105": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "112": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "1.5",
            "cpu_average": "1",
            "mem": "3.1"
        },
        "116": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "137": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "138": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "160": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.3"
        },
        "161": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "167": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "296": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "298": {
            "cmdline": "frigate.recording_manager",
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "0.9"
        },
        "306": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(42)",
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "307": {
            "cmdline": "frigate.detector.ov  ",
            "cpu": "0.0",
            "cpu_average": "2",
            "mem": "1.1"
        },
        "309": {
            "cmdline": "frigate.output       ",
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.5"
        },
        "312": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "1.0"
        },
        "314": {
            "cmdline": "frigate.process:Cam1",
            "cpu": "2.0",
            "cpu_average": "2",
            "mem": "0.9"
        },
        "315": {
            "cmdline": "frigate.process:Cam2",
            "cpu": "2.0",
            "cpu_average": "2",
            "mem": "0.8"
        },
        "316": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "317": {
            "cmdline": "frigate.capture:Cam1",
            "cpu": "3.6",
            "cpu_average": "3",
            "mem": "0.9"
        },
        "318": {
            "cmdline": "frigate.capture:Cam2",
            "cpu": "3.8",
            "cpu_average": "3",
            "mem": "0.7"
        },
        "331": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@<obfuscated_ip>:<obfuscated_port>/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Cam2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "14.7",
            "cpu_average": "14",
            "mem": "1.1"
        },
        "333": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.91:<obfuscated_port>/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Cam1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1920:1080 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "14.8",
            "cpu_average": "15",
            "mem": "1.0"
        },
        "14033": {
            "cmdline": "bash",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "15008": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 0.0,
    "detectors": {
        "ov": {
            "detection_start": 0.0,
            "inference_speed": 26.82,
            "pid": 307
        }
    },
    "processes": {
        "go2rtc": {
            "pid": 89
        },
        "logger": {
            "pid": 296
        },
        "recording": {
            "pid": 298
        }
    },
    "service": {
        "last_updated": 1707488448,
        "latest_version": "0.13.1",
        "storage": {
            "/dev/shm": {
                "free": 120.6,
                "mount_type": "tmpfs",
                "total": 128.0,
                "used": 7.4
            },
            "/media/frigate/clips": {
                "free": 6159223.9,
                "mount_type": "btrfs",
                "total": 21946368.0,
                "used": 15787144.1
            },
            "/media/frigate/recordings": {
                "free": 6159223.9,
                "mount_type": "btrfs",
                "total": 21946368.0,
                "used": 15787144.1
            },
            "/tmp/cache": {
                "free": 951.4,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 2.3
            }
        },
        "temperatures": {},
        "uptime": 56455,
        "version": "0.13.1-34fb1c2"
    }
}
```

### Operating system

Some Linux derivate (Synology DSM 7.0)

### Install method

Docker compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo C310 - Hardware Revision 2
