### ISSUE TITLE
[Config Support]: Config input enabled is defined multiple times for the same field, this is not allowed.

### ISSUE THREAD

**Issue by cloudbr34k84** [blakeblackshear/frigate#9771]
### Describe the problem you are having

When updating frigate docker, it appears something has changed in this new release, and im not sure how to fix it. 
In the error log its says " Config input enabled is defined multiple times for the same field, this is not allowed. I ahvent changed my frigate config file so not sure how to fix this error? 

```
<html>
<body>
<!--StartFragment-->
02/10 08:57:18 | stderr | s6-rc: info: service s6rc-oneshot-runner successfully stopped
-- | -- | --
2024/02/10 08:57:18 | stderr | s6-rc: info: service s6rc-oneshot-runner: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service fix-attrs successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service fix-attrs: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-cont-init successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service s6rc-fdholder successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-cont-init: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service log-prepare successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service s6rc-fdholder: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service log-prepare: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-log successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-log: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.390994317  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate-log successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.385840748  exit with signal: terminated
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx-log successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate-log: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx-log: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.382233163  [INFO] Service NGINX exited with code 0 (by signal 0)
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-healthcheck successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.361900351  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-healthcheck: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-services successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-services: stopping
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.353511703  [INFO] Service Frigate exited with code 1 (by signal 0)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015532624  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015530966  ***    End Config Validation Errors                       ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015528555  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015417198
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015406567  ValueError: Config input enabled is defined multiple times for the same field, this is not allowed.
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015404723      raise ValueError(
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015403424    File "/opt/frigate/frigate/util/builtin.py", line 104, in map_constructor
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015401372      data = constructor(self, node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015391089    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015389233      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015387522    File "/opt/frigate/frigate/util/builtin.py", line 99, in <listcomp>
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015385387      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015383696    File "/opt/frigate/frigate/util/builtin.py", line 99, in map_constructor
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015382041      data = constructor(self, node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015380427    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015378090      data = self.construct_object(node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015362160    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 55, in construct_document
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015360278      return self.construct_document(node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015358016    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 51, in get_single_data
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015356125      return loader.get_single_data()
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015354761    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015353042      return yaml.load(raw_config, PreserveDuplicatesLoader)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015351492    File "/opt/frigate/frigate/util/builtin.py", line 114, in load_config_with_no_duplicates
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015349727      config = load_config_with_no_duplicates(raw_config)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015348169    File "/opt/frigate/frigate/config.py", line 1329, in parse_file
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015346562      user_config = FrigateConfig.parse_file(config_file)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015345054    File "/opt/frigate/frigate/app.py", line 112, in init_config
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015343424      self.init_config()
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015342096    File "/opt/frigate/frigate/app.py", line 645, in start
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015337630  Traceback (most recent call last):
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013859481  Config input enabled is defined multiple times for the same field, this is not allowed.
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013857698  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013855956  ***    Config Validation Errors                           ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013853710  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013851712  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013836055  ***    https://docs.frigate.video/configuration/index     ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013834087  ***    Please check the docs at                           ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013831443  ***    Your config file is not valid!                     ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013824680  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013818418  *************************************************************

<!--EndFragment-->
</body>
</html>
```

### Version

Cant access WEb UI

### Frigate config file

```yaml
mqtt:
  host: xxxxxxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxx
  password: xxxxxx
  stats_interval: 60
  enabled: true

birdseye:
  enabled: True
  mode: continuous
  restream: False
  width: 1920
  height: 1080
  quality: 6

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - car
    - cat

record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
    # Required: Default retention days (default: shown below)
      default: 2

# detect:
#   stationary:
#     interval: 0
#     threshold: 50
  fps: 5
  enabled: true
  width: 1280 #max 2560 min 1280 
  height: 720 #max 1920 min 720

snapshots:
  clean_copy: True
  enabled: true
  retain:
    default: 2

rtmp:
  enabled: false

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

go2rtc:
  streams:
    front_video_doorbell_frigate:
      - rtsp://viewer:xxxxxxxx/h264Preview_01_main
    front_video_doorbell_sub_frigate:
      - rtsp://viewer:xxxxxxx/h264Preview_01_sub

    frontyard_camera_frigate:
      - rtsp://viewer:xxxxx/h264Preview_01_main
    frontyard_camera_sub_frigate:
      - ftsp://viewer:xxxxxx/h264Preview_01_sub

    driveway_camera_frigate:
      - rtsp://viewer:xxxxx:554/h264Preview_01_main
    driveway_camera_sub_frigate:
      - rtsp://viewer:xxxxx:554/h264Preview_01_sub

    backyard_camera_frigate:
      - rtsp://viewer:xxxxx/h264Preview_01_main
    backyard_camera_sub_frigate:
      - rtsp://viewer:xxxx/h264Preview_01_sub
      
    front_top_camera_frigate:
      - rtsp://viewer:xxxx/h264Preview_01_main
    front_top_camera_sub_frigate:
      - rtsp://viewer:xxxx/h264Preview_01_sub

    back_top_camera_frigate:
      - rtsp://viewer:xxxxx/h264Preview_01_main
    back_top_camera_sub_frigate:
      - rtsp://viewer:xxx/h264Preview_01_sub

    laundry_camera_frigate:
      - rtsp://viewer:xxxxx/h264Preview_01_main
    laundry_camera_sub_frigate:
      - rtsp://viewer:xxxxx/h264Preview_01_sub

######## Camera Configuration ########
cameras:

######## Video Doorbell ########    
  front_video_doorbell_frigate:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://viewer:xxxxx/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record  
            - detect         
        - path: rtsp://viewer:xxxxxxx/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - rtmp
    # record:
    #   events:
    #     required_zones:


####### Frontyard Camera ########   
  frontyard_camera_frigate:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://viewer:xxxxxx/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://viewer:xxxxx/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    # record:
    #   events:
    #     required_zones:
    #       - frontyard_camera_frigate_zone_front_grass
    #       - frontyard_camera_frigate_zone_roadway
    # snapshots:
    #   required_zones:
    #       - frontyard_camera_frigate_zone_front_grass
    #       - frontyard_camera_frigate_zone_roadway
    # zones:
    #   frontyard_camera_frigate_zone_front_grass:
    #     coordinates: 720,493,683,398,1280,314,1280,720,933,720,768,720,637,720,0,720,65,478,437,429,439,536
    #     objects:
    #       - person
    #       - dog
    #   frontyard_camera_frigate_zone_roadway:
    #     coordinates: 714,394,1280,305,1280,172,822,195,0,291,0,465
    #     objects:
    #       - person
    #       - dog 

######## Driveway Camera ########
  driveway_camera_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:xxxxx/h264Preview_01_main
          roles:
            - record
        - path: rtsp://viewer:xxxx/h264Preview_01_sub
          roles:
            - rtmp
            - detect
    # record:
    #   events:
    #     required_zones:
    #       - driveway_camera_frigate_zone_driveway
    # snapshots:
    #   required_zones:
    #       - driveway_camera_frigate_zone_driveway

    # zones:
    #   driveway_camera_frigate_zone_driveway:
    #     coordinates: 0,720,838,720,1052,720,1280,400,1280,183,1280,0,605,0,0,178
    #     objects:
    #       - person
    #       - dog

####### Backyard Camera ########
  backyard_camera_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:xxxx/h264Preview_01_main
          roles:
            - record
        - path: rtsp://viewer:xxxxx/h264Preview_01_sub
          roles:
            - rtmp
            - detect
    # record:
    #   events:
    #     required_zones:
    # zones:
    #   backyard_camera_zone_frigate:
    #     coordinates: 0,1920,1197,1920,2560,1920,2560,961,1980,601,1928,697,0,929

######## Laundry  Camera ########
  laundry_camera_frigate:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://viewer:xxxx/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://viewer:xxxx/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    # record:
    #   events:
    #     required_zones:

######## Front Top  Camera ########
  front_top_camera_frigate:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://viewer:xxxxx/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://viewer:xxxxx/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    # record:
    #   events:
    #     required_zones:
    #       - front_top_camera_frigate_zone_pauls_house
    #       - front_top_camera_frigate_zone_frontyard
    #       - front_top_camera_frigate_zone_driveway
    #       - front_top_camera_frigate_zone_roadway

    # snapshots:
    #   required_zones:
    #       - front_top_camera_frigate_zone_pauls_house
    #       - front_top_camera_frigate_zone_frontyard
    #       - front_top_camera_frigate_zone_driveway
    #       - front_top_camera_frigate_zone_roadway

    # zones:
    #   front_top_camera_frigate_zone_pauls_house:
    #     coordinates: 107,169,190,70,102,82,29,175
    #   front_top_camera_frigate_zone_frontyard:
    #     coordinates: 240,240,257,283,318,298,314,331,336,390,331,408,227,504,508,636,807,287
    #     objects:
    #       - person
    #       - dog
    #   front_top_camera_frigate_zone_driveway:
    #     coordinates: 405,720,1165,720,1179,346,812,289
    #     objects:
    #       - person
    #       - dog
    #   front_top_camera_frigate_zone_roadway:
    #     coordinates: 687,273,1280,361,1280,148,902,79,602,69,393,91,245,237 

######## Back Top  Camera ########
  back_top_camera_frigate:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://viewer:xxxxx/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://viewer:xxxxx/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
    # record:
    #   events:
    #     required_zones:
    #       - back_top_camera_frigate_zone_footpath
    #       - back_top_camera_frigate_zone_beergarden
    #       - back_top_camera_frigate_zone_pool
    # snapshots:
    #   required_zones:
    #       - back_top_camera_frigate_zone_footpath
    #       - back_top_camera_frigate_zone_beergarden
    #       - back_top_camera_frigate_zone_pool
    # zones:
    #   back_top_camera_frigate_zone_footpath:
    #     coordinates: 317,140,303,107,143,165,153,211
    #     objects:
    #       - person
    #       - dog
    #   back_top_camera_frigate_zone_beergarden:
    #     coordinates: 87,720,845,720,859,695,709,560,477,341,48,543
    #     objects:
    #       - person
    #   back_top_camera_frigate_zone_pool:
    #     coordinates: 1050,685,1280,293,1048,167,618,370
    #     objects:
    #       - person
    #       - dog
```

### Relevant log output

```shell
<html>
<body>
<!--StartFragment-->
02/10 08:57:18 | stderr | s6-rc: info: service s6rc-oneshot-runner successfully stopped
-- | -- | --
2024/02/10 08:57:18 | stderr | s6-rc: info: service s6rc-oneshot-runner: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service fix-attrs successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service fix-attrs: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-cont-init successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service s6rc-fdholder successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-cont-init: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service log-prepare successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service s6rc-fdholder: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service log-prepare: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-log successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-log: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.390994317  [INFO] The go2rtc service exited with code 0 (by signal 0)
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate-log successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.385840748  exit with signal: terminated
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx-log successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate-log: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service frigate: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx-log: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.382233163  [INFO] Service NGINX exited with code 0 (by signal 0)
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-healthcheck successfully stopped
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.361900351  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024/02/10 08:57:18 | stderr | s6-rc: info: service go2rtc-healthcheck: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service nginx: stopping
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-services successfully stopped
2024/02/10 08:57:18 | stderr | s6-rc: info: service legacy-services: stopping
2024/02/10 08:57:18 | stdout | 2024-02-10 08:57:18.353511703  [INFO] Service Frigate exited with code 1 (by signal 0)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015532624  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015530966  ***    End Config Validation Errors                       ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015528555  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015417198
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015406567  ValueError: Config input enabled is defined multiple times for the same field, this is not allowed.
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015404723      raise ValueError(
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015403424    File "/opt/frigate/frigate/util/builtin.py", line 104, in map_constructor
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015401372      data = constructor(self, node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015391089    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015389233      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015387522    File "/opt/frigate/frigate/util/builtin.py", line 99, in <listcomp>
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015385387      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015383696    File "/opt/frigate/frigate/util/builtin.py", line 99, in map_constructor
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015382041      data = constructor(self, node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015380427    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015378090      data = self.construct_object(node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015362160    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 55, in construct_document
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015360278      return self.construct_document(node)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015358016    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 51, in get_single_data
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015356125      return loader.get_single_data()
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015354761    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015353042      return yaml.load(raw_config, PreserveDuplicatesLoader)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015351492    File "/opt/frigate/frigate/util/builtin.py", line 114, in load_config_with_no_duplicates
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015349727      config = load_config_with_no_duplicates(raw_config)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015348169    File "/opt/frigate/frigate/config.py", line 1329, in parse_file
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015346562      user_config = FrigateConfig.parse_file(config_file)
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015345054    File "/opt/frigate/frigate/app.py", line 112, in init_config
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015343424      self.init_config()
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015342096    File "/opt/frigate/frigate/app.py", line 645, in start
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.015337630  Traceback (most recent call last):
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013859481  Config input enabled is defined multiple times for the same field, this is not allowed.
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013857698  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013855956  ***    Config Validation Errors                           ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013853710  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013851712  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013836055  ***    https://docs.frigate.video/configuration/index     ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013834087  ***    Please check the docs at                           ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013831443  ***    Your config file is not valid!                     ***
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013824680  *************************************************************
2024/02/10 08:57:17 | stdout | 2024-02-10 08:57:17.013818418  *************************************************************

<!--EndFragment-->
</body>
</html>
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
