### ISSUE TITLE
[Config Support]: ptzcamera not accept in Frigate Config File

### ISSUE THREAD

**Issue by cloudbr34k84** [blakeblackshear/frigate#9773]
### Describe the problem you are having

It says ptzcamera : is not accepted?

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
frontyard_camera_frigate:
    ptzcamera:
      onvif:
        # Required: host of the camera being connected to.
        host: xxx.xxx.xx.xx
        # Optional: ONVIF port for device (default: shown below).
        port: 8000
        # Optional: username for login.
        # NOTE: Some devices require admin to access ONVIF.
        user: admin
        # Optional: password for login.
        password: xxxxx
        # Optional: PTZ camera object autotracking. Keeps a moving object in
        # the center of the frame by automatically moving the PTZ camera.
        autotracking:
          # Optional: enable/disable object autotracking. (default: shown below)
          enabled: True
          # Optional: calibrate the camera on startup (default: shown below)
          # A calibration will move the PTZ in increments and measure the time it takes to move.
          # The results are used to help estimate the position of tracked objects after a camera move.
          # Frigate will update your config file automatically after a calibration with
          # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
          calibrate_on_startup: True
          # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
          # Available options are: disabled, absolute, and relative
          #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
          #   absolute - use absolute zooming (supported by most PTZ capable cameras)
          #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
          zooming: disabled
          # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
          # A lower value will keep more of the scene in view around a tracked object.
          # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
          # The value should be between 0.1 and 0.75
          zoom_factor: 0.3
          # Optional: list of objects to track from labelmap.txt (default: shown below)
          track:
            - person
          # Required: Begin automatically tracking an object when it enters any of the listed zones.
          required_zones:
            - zone_name
          # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
          return_preset: home
          # Optional: Seconds to delay before returning to preset. (default: shown below)
          timeout: 10
          # Optional: Values generated automatically by a camera calibration. Do not modify these manually. (default: shown below)
          movement_weights: []
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://viewer:x@x:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://viewer:xxxxxx@x:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
```

### Relevant log output

```shell
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/http.py&#34;, line 1221, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1338, in parse_raw
    return cls.parse_obj(config)
  File &#34;pydantic/main.py&#34;, line 526, in pydantic.main.BaseModel.parse_obj
  File &#34;pydantic/main.py&#34;, line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -&gt; frontyard_camera_frigate -&gt; ptzcamera
  extra fields not permitted (type=value_error.extra)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
