### ISSUE TITLE
[Config Support]: TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by kronkinatorix** [blakeblackshear/frigate#9777]
### Describe the problem you are having

1.I'm getting the following error every time Home Assistant tries to connect with Frigate (see below)

Dealing with numerous issues but  the connection issue is probably the most pressing. 

2. Also: can only connect to mqtt if there's no username or password set. The logs don't seem to provide much useful information.  no idea how to troubleshoot this without being able to run an strace. 

3. The frigate page (@frigate:5000) doesn't load. 

Currently running frigate in a LXC in proxmox. 

1c. docker-compose.yml (note that I've tried with a couple different versions of the tensorrt package with similar issues). I've tried with network_mode: not there, in host, and on bridge (current). Mqtt actually finally connected after setting that but it wasn't the only thing I hanged so  I don't knownif that was it. 

```
 1 version: "3.9"
 2 services:
 3   frigate:
 4     container_name: frigate
 5     image: ghcr.io/blakeblackshear/frigate:dev-f6a4c2a-tensorrt
 6     network_mode: bridge
 7     deploy:
 8       resources:
 9         reservations:
10           devices:
11             - driver: nvidia
12               count: 1 # number of GPUs
13               capabilities: [gpu]
14     user: root
15     group_add:
16       - "109" # render
17       - "110" # render
18       - "44"  # video
19       - "46"  # plugdev
20     privileged: false
21     restart: unless-stopped
22     runtime: nvidia
23     shm_size: "512mb"
24     environment:
25       YOLO_MODELS: yolov7x-640
26     devices:
27       - /dev/nvidia-modeset:/dev/nvidia-modeset
28       - /dev/nvidia-uvm:/dev/nvidia-uvm
29       - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
30       - /dev/nvidia0:/dev/nvidia0
31       - /dev/nvidiactl:/dev/nvidiactl
32 #     - /dev/nvidia-caps/nvidia-cap1:/dev/nvidia-caps/nvidia-cap1
33 #     - /dev/nvidia-caps/nvidia-cap2:/dev/nvidia-caps/nvidia-cap2 
34     volumes:
35       - /etc/localtime:/etc/localtime:ro
36       - /opt/frigit/config:/config
37       - /opt/frigit/storage:/media/frigate
38       - type: tmpfs
39         target: /tmp/cache
40         tmpfs:
41           size: 1000000000
42     ports:
43       - "5000:5000"
44       - "5069:5069"
45       - "8554:8554" # RTSP feeds
46       - "8555:8555/tcp"
47       - "8555:8555/udp"
48     expose:
49       - "192.168.2.83:5000"
50       - "192.168.2.83:5069"
51       - "192.168.2.83:8555"
52       - "192.168.2.83:8554"
53
```

### Version

12,13.1,14

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.2.28
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *****
  password: ******
  stats_interval: 60
birdseye:
  restream: true
go2rtc:
  rtsp:
    username: ***
    pass: *****
  streams:
    bluecamrtsp:
      - rtsp://adminn:something11a@192.168.2.100:554/stream1
      - "ffmpeg:bluecamrtsp#video=h264#audio=aac#hardware=preset-nvidia-h264"
    bluecamsub:
      - rtsp://adminn:something11a@192.168.2.100:554/stream2
      - "ffmpeg:bluecamsub#video=h264#audio=aac#hardware=preset-nvidia-h264"
    camera1rtsp:
      - rtsp://adminn:something11a@192.168.2.101:554/stream1
      - "ffmpeg:camera1rtsp#video=h264audio=aac#hardware=preset-nvidia-h264"
  audio:
  enabled: True
  max_not_heard: 30
  min_volume: 500
  listen:
    - fire_alarm
    - scream
    - yell
  filters: null
logger:
  default: info
  logs:
    frigate.event: debug
    frigate.app: debug
    go2rtc: debug
    frigate.comms.mqtt: debug
model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
  labelmap_path: /labelmap.txt
  labelmap:
    '0': person
    '1': bicycle
    '2': car
    '3': motorcycle
    '4': airplane
    '5': bus
    '6': train
    '7': car
    '8': boat
    '9': traffic light
    '10': fire hydrant
    '11': street sign
    '12': stop sign
    '13': parking meter
    '14': bench
    '15': bird
    '16': cat
    '17': dog
    '18': horse
    '19': sheep
    '20': cow
    '21': elephant
    '22': bear
    '23': zebra
    '24': giraffe
    '25': hat
    '26': backpack
    '27': umbrella
    '28': shoe
    '29': eye glasses
    '30': handbag
    '31': tie
    '32': suitcase
    '33': frisbee
    '34': skis
    '35': snowboard
    '36': sports ball
    '37': kite
    '38': baseball bat
    '39': baseball glove
    '40': skateboard
    '41': surfboard
    '42': tennis racket
    '43': bottle
    '44': plate
    '45': wine glass
    '46': cup
    '47': fork
    '48': knife
    '49': spoon
    '50': bowl
    '51': banana
    '52': apple
    '53': sandwich
    '54': orange
    '55': broccoli
    '56': carrot
    '57': hot dog
    '58': pizza
    '59': donut
    '60': cake
    '61': chair
    '62': couch
    '63': potted plant
    '64': bed
    '65': mirror
    '66': dining table
    '67': window
    '68': desk
    '69': toilet
    '70': door
    '71': tv
    '72': laptop
    '73': mouse
    '74': remote
    '75': keyboard
    '76': cell phone
    '77': microwave
    '78': oven
    '79': toaster
    '80': sink
    '81': refrigerator
    '82': blender
    '83': book
    '84': clock
    '85': vase
    '86': scissors
    '87': teddy bear
    '88': hair drier
    '89': toothbrush
    '90': hair brush
ffmpeg:
  global_args: '-hide_banner -loglevel warning -threads 2'
  hwaccel_args: preset-nvidia-h264
  output_args:
    detect: '-threads 2 -f rawvideo -pix_fmt yuv420p'
    record: preset-record-generic-audio-aac
  retry_interval: 10
detectors:
  tensorrt:
    type: tensorrt
    device: 0

database:
  path: /config/frigate.db

detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: True
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000
  annotation_offset: 0
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce False positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a True positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      mask: 0,0,1000,0,1000,200,0,200

motion:
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.01
  frame_height: 100
  mask: '0,900,1080,900,1080,1920,0,1920'
  improve_contrast: True
  mqtt_off_delay: 30
record:
  enabled: True
  expire_interval: 60
  sync_recordings: False
  retain:
    days: 0
    mode: all
  export:
    timelapse_args: '-vf setpts=0.04*PTS -r 30'
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        person: 15
snapshots:
  enabled: False
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
  quality: 70


cameras:
  bluecamrtsp:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/bluecamrtsp
          input_args: preset-rtsp-restream
          roles:
            - record
  bluecamsub:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/bluecamsub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
  camera1rtsp:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1rtsp
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
root@frigate2:/opt/frigit#
```

### Relevant log output

```shell
| 2024-02-10 05:04:53.446142337  [2024-02-10 05:04:53] frigate.http                   ERROR   : Exception on /config [GET]
frigate  | 2024-02-10 05:04:53.446144435  Traceback (most recent call last):
frigate  | 2024-02-10 05:04:53.446145649    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
frigate  | 2024-02-10 05:04:53.446146583      response = self.full_dispatch_request()
frigate  | 2024-02-10 05:04:53.446147610    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
frigate  | 2024-02-10 05:04:53.446148453      rv = self.handle_user_exception(e)
frigate  | 2024-02-10 05:04:53.446149412    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
frigate  | 2024-02-10 05:04:53.446150191      rv = self.dispatch_request()
frigate  | 2024-02-10 05:04:53.446151162    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
frigate  | 2024-02-10 05:04:53.446152089      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate  | 2024-02-10 05:04:53.446152990    File "/opt/frigate/frigate/http.py", line 1382, in config
frigate  | 2024-02-10 05:04:53.446153759      return jsonify(config)
frigate  | 2024-02-10 05:04:53.446154737    File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 170, in jsonify
frigate  | 2024-02-10 05:04:53.446155577      return current_app.json.response(*args, **kwargs)
frigate  | 2024-02-10 05:04:53.446156576    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 215, in response
frigate  | 2024-02-10 05:04:53.446157456      f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
frigate  | 2024-02-10 05:04:53.446158433    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 180, in dumps
frigate  | 2024-02-10 05:04:53.446159257      return json.dumps(obj, **kwargs)
frigate  | 2024-02-10 05:04:53.446160095    File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
frigate  | 2024-02-10 05:04:53.446160836      return cls(
frigate  | 2024-02-10 05:04:53.446161696    File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
frigate  | 2024-02-10 05:04:53.446162511      chunks = self.iterencode(o, _one_shot=True)
frigate  | 2024-02-10 05:04:53.446163403    File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
frigate  | 2024-02-10 05:04:53.446164164      return _iterencode(o, 0)
frigate  | 2024-02-10 05:04:53.446165065  TypeError: '<' not supported between instances of 'str' and 'int'
frigate  | 2024-02-10 05:05:24.584732234  192.168.2.28 - - [10/Feb/2024:05:05:24 -0500] "GET /api/config HTTP/1.1" 500 265 "-" "HomeAssistant/2024.2.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-02-10 05:05:24.584815179  [2024-02-10 05:05:24] frigate.http                   ERROR   : Exception on /config [GET]
frigate  | 2024-02-10 05:05:24.584817656  Traceback (most recent call last):
frigate  | 2024-02-10 05:05:24.584819376    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
frigate  | 2024-02-10 05:05:24.584820760      response = self.full_dispatch_request()
frigate  | 2024-02-10 05:05:24.584822913    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
frigate  | 2024-02-10 05:05:24.584824190      rv = self.handle_user_exception(e)
frigate  | 2024-02-10 05:05:24.584825810    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
frigate  | 2024-02-10 05:05:24.584827093      rv = self.dispatch_request()
frigate  | 2024-02-10 05:05:24.584828776    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
frigate  | 2024-02-10 05:05:24.584830280      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate  | 2024-02-10 05:05:24.584831665    File "/opt/frigate/frigate/http.py", line 1382, in config
frigate  | 2024-02-10 05:05:24.584833021      return jsonify(config)
frigate  | 2024-02-10 05:05:24.584834758    File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 170, in jsonify
frigate  | 2024-02-10 05:05:24.584836051      return current_app.json.response(*args, **kwargs)
frigate  | 2024-02-10 05:05:24.584837871    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 215, in response
frigate  | 2024-02-10 05:05:24.584839296      f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
frigate  | 2024-02-10 05:05:24.584840977    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 180, in dumps
frigate  | 2024-02-10 05:05:24.584842327      return json.dumps(obj, **kwargs)
frigate  | 2024-02-10 05:05:24.584843816    File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
frigate  | 2024-02-10 05:05:24.584845088      return cls(
frigate  | 2024-02-10 05:05:24.584846580    File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
frigate  | 2024-02-10 05:05:24.584847813      chunks = self.iterencode(o, _one_shot=True)
frigate  | 2024-02-10 05:05:24.584849246    File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
frigate  | 2024-02-10 05:05:24.584850388      return _iterencode(o, 0)
frigate  | 2024-02-10 05:05:24.584851958  TypeError: '<' not supported between instances of 'str' and 'int'
frigate  | 2024-02-10 05:06:45.045344385  192.168.2.28 - - [10/Feb/2024:05:06:45 -0500] "GET /api/config HTTP/1.1" 500 265 "-" "HomeAssistant/2024.2.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-02-10 05:06:45.045494081  [2024-02-10 05:06:45] frigate.http                   ERROR   : Exception on /config [GET]
frigate  | 2024-02-10 05:06:45.045496186  Traceback (most recent call last):
frigate  | 2024-02-10 05:06:45.045497378    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
frigate  | 2024-02-10 05:06:45.045498296      response = self.full_dispatch_request()
frigate  | 2024-02-10 05:06:45.045499285    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
frigate  | 2024-02-10 05:06:45.045500117      rv = self.handle_user_exception(e)
frigate  | 2024-02-10 05:06:45.045501074    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
frigate  | 2024-02-10 05:06:45.045501844      rv = self.dispatch_request()
frigate  | 2024-02-10 05:06:45.045502793    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
frigate  | 2024-02-10 05:06:45.045503687      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate  | 2024-02-10 05:06:45.045504538    File "/opt/frigate/frigate/http.py", line 1382, in config
frigate  | 2024-02-10 05:06:45.045505301      return jsonify(config)
frigate  | 2024-02-10 05:06:45.045506266    File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 170, in jsonify
frigate  | 2024-02-10 05:06:45.045507096      return current_app.json.response(*args, **kwargs)
frigate  | 2024-02-10 05:06:45.045508063    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 215, in response
frigate  | 2024-02-10 05:06:45.045508920      f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
frigate  | 2024-02-10 05:06:45.045509844    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 180, in dumps
frigate  | 2024-02-10 05:06:45.045510629      return json.dumps(obj, **kwargs)
frigate  | 2024-02-10 05:06:45.045511461    File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
frigate  | 2024-02-10 05:06:45.045512167      return cls(
frigate  | 2024-02-10 05:06:45.045513008    File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
frigate  | 2024-02-10 05:06:45.045513801      chunks = self.iterencode(o, _one_shot=True)
frigate  | 2024-02-10 05:06:45.045514682    File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
frigate  | 2024-02-10 05:06:45.045515427      return _iterencode(o, 0)
frigate  | 2024-02-10 05:06:45.045516287  TypeError: '<' not supported between instances of 'str' and 'int'
frigate  | 2024-02-10 05:08:05.151048084  192.168.2.28 - - [10/Feb/2024:05:08:05 -0500] "GET /api/config HTTP/1.1" 500 265 "-" "HomeAssistant/2024.2.0 aiohttp/3.9.3 Python/3.12" "-"
frigate  | 2024-02-10 05:08:05.151249680  [2024-02-10 05:08:05] frigate.http                   ERROR   : Exception on /config [GET]
frigate  | 2024-02-10 05:08:05.151251781  Traceback (most recent call last):
frigate  | 2024-02-10 05:08:05.151252914    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
frigate  | 2024-02-10 05:08:05.151253864      response = self.full_dispatch_request()
frigate  | 2024-02-10 05:08:05.151254896    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
frigate  | 2024-02-10 05:08:05.151255729      rv = self.handle_user_exception(e)
frigate  | 2024-02-10 05:08:05.151256700    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
frigate  | 2024-02-10 05:08:05.151257455      rv = self.dispatch_request()
frigate  | 2024-02-10 05:08:05.151258434    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
frigate  | 2024-02-10 05:08:05.151259370      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate  | 2024-02-10 05:08:05.151260228    File "/opt/frigate/frigate/http.py", line 1382, in config
frigate  | 2024-02-10 05:08:05.151260986      return jsonify(config)
frigate  | 2024-02-10 05:08:05.151261946    File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 170, in jsonify
frigate  | 2024-02-10 05:08:05.151262800      return current_app.json.response(*args, **kwargs)
frigate  | 2024-02-10 05:08:05.151263789    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 215, in response
frigate  | 2024-02-10 05:08:05.151264672      f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
frigate  | 2024-02-10 05:08:05.151265629    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 180, in dumps
frigate  | 2024-02-10 05:08:05.151266448      return json.dumps(obj, **kwargs)
frigate  | 2024-02-10 05:08:05.151267280    File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
frigate  | 2024-02-10 05:08:05.151268014      return cls(
frigate  | 2024-02-10 05:08:05.151268854    File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
frigate  | 2024-02-10 05:08:05.151269663      chunks = self.iterencode(o, _one_shot=True)
frigate  | 2024-02-10 05:08:05.151270540    File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
frigate  | 2024-02-10 05:08:05.151271304      return _iterencode(o, 0)
frigate  | 2024-02-10 05:08:05.151272200  TypeError: '<' not supported between instances of 'str' and 'int'
frigate  | 2024-02-10 05:09:25.647877781  [2024-02-10 05:09:25] frigate.http                   ERROR   : Exception on /config [GET]
frigate  | 2024-02-10 05:09:25.647880759  Traceback (most recent call last):
frigate  | 2024-02-10 05:09:25.647881947    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
frigate  | 2024-02-10 05:09:25.647882836      response = self.full_dispatch_request()
frigate  | 2024-02-10 05:09:25.647883837    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
frigate  | 2024-02-10 05:09:25.647884678      rv = self.handle_user_exception(e)
frigate  | 2024-02-10 05:09:25.647885647    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
frigate  | 2024-02-10 05:09:25.647886446      rv = self.dispatch_request()
frigate  | 2024-02-10 05:09:25.647887417    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
frigate  | 2024-02-10 05:09:25.647888358      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate  | 2024-02-10 05:09:25.647889220    File "/opt/frigate/frigate/http.py", line 1382, in config
frigate  | 2024-02-10 05:09:25.647889989      return jsonify(config)
frigate  | 2024-02-10 05:09:25.647890960    File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 170, in jsonify
frigate  | 2024-02-10 05:09:25.647891864      return current_app.json.response(*args, **kwargs)
frigate  | 2024-02-10 05:09:25.647893632    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 215, in response
frigate  | 2024-02-10 05:09:25.647895238      f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
frigate  | 2024-02-10 05:09:25.647897029    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 180, in dumps
frigate  | 2024-02-10 05:09:25.647898364      return json.dumps(obj, **kwargs)
frigate  | 2024-02-10 05:09:25.647899853    File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
frigate  | 2024-02-10 05:09:25.647901037      return cls(
frigate  | 2024-02-10 05:09:25.647902584    File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
frigate  | 2024-02-10 05:09:25.647904101      chunks = self.iterencode(o, _one_shot=True)
frigate  | 2024-02-10 05:09:25.647905687    File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
frigate  | 2024-02-10 05:09:25.647907036      return _iterencode(o, 0)
frigate  | 2024-02-10 05:09:25.647908597  TypeError: '<' not supported between instances of 'str' and 'int'



frigate  | 2024-02-10 04:56:47.158250949  [INFO] Starting go2rtc healthcheck service...
frigate  | 2024-02-10 04:56:47.235338157  [2024-02-10 04:56:47] frigate.comms.mqtt             ERROR   : Unable to publish to camera1rtsp/all: client is not connected
frigate  | 2024-02-10 04:56:47.235341736  [2024-02-10 04:56:47] frigate.comms.mqtt             ERROR   : Unable to publish to camera1rtsp/motion: client is not connected
frigate  | 2024-02-10 04:56:49.446128997  [2024-02-10 04:56:49] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamsub/all: client is not connected
frigate  | 2024-02-10 04:56:49.446447662  [2024-02-10 04:56:49] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamsub/motion: client is not connected
frigate  | 2024-02-10 04:56:49.687789154  [2024-02-10 04:56:49] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/all: client is not connected
frigate  | 2024-02-10 04:56:49.687898864  [2024-02-10 04:56:49] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/motion: client is not connected
frigate  | 2024-02-10 04:57:04.992506883  [2024-02-10 04:57:04] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
frigate  | 2024-02-10 04:57:04.999067183  [2024-02-10 04:57:04] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/person/snapshot: client is not connected
frigate  | 2024-02-10 04:57:04.999117984  [2024-02-10 04:57:04] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/person: client is not connected
frigate  | 2024-02-10 04:57:04.999215736  [2024-02-10 04:57:04] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/all: client is not connected
frigate  | 2024-02-10 04:57:09.998198940  [2024-02-10 04:57:09] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
frigate  | 2024-02-10 04:57:10.400983530  [2024-02-10 04:57:10] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
frigate  | 2024-02-10 04:57:10.584521086  [2024-02-10 04:57:10] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/all: client is not connected
frigate  | 2024-02-10 04:57:10.584525257  [2024-02-10 04:57:10] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/person: client is not connected
frigate  | 2024-02-10 04:57:10.587429454  [2024-02-10 04:57:10] frigate.comms.mqtt             ERROR   : Unable to publish to bluecamrtsp/person/snapshot: client is not connected
frigate  | 2024-02-10 04:57:23.021420477  192.168.2.28 - - [10/Feb/2024:04:57:23 -0500] "GET /api/config HTTP/1.1" 500 265 "-" "HomeAssistant/2024.2.0 aiohttp/3.9.3 Python/3.12" "-"
```

### Frigate stats

```json
192.168.2.83:5000/api/stats
curl: (7) Failed to connect to 192.168.2.83 port 5000 after 0 ms: Connection refused
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

Other
