### ISSUE TITLE
[Support]:GUI Glitch? Mask & Zone Creator showing zones reaching outside of camera display

### ISSUE THREAD

**Issue by Porencephaly** [blakeblackshear/frigate#9784]
### Describe the problem you are having

I recently updated to 0.13.1-34FB1C2 and am having strange problems with the size of the displays from my cameras & a weird glitch where the zones & masks that I've created are reaching outside of the bounds of the actual camera feed. Pictures below. There are even some points all the way down in the boxes where the coordinates are. 

<img width="2560" alt="Screenshot 2024-02-10 at 2 53 48 PM" src="https://github.com/blakeblackshear/frigate/assets/75652194/21aa44ff-aa9d-4684-95f5-60992ce321bb">
<img width="2351" alt="Screenshot 2024-02-10 at 2 54 16 PM" src="https://github.com/blakeblackshear/frigate/assets/75652194/c6e75c2e-8e71-40c6-81f8-e55311b1db33">

Also, The video display itself shrinks disproportionately smaller in the x axis when i switch from the "Live" tab to the "Debug" tab. Pictures below. 
<img width="2544" alt="Screenshot 2024-02-10 at 2 57 41 PM" src="https://github.com/blakeblackshear/frigate/assets/75652194/9da3e9aa-3a2b-4590-9fe1-429b9238a4e0">
<img width="2547" alt="Screenshot 2024-02-10 at 2 58 15 PM" src="https://github.com/blakeblackshear/frigate/assets/75652194/37cfe81d-2c9f-448e-b73e-ff40be373199">

Also, since updating, the displays on my main "Cameras" page are different as well. The displays for all cameras are also squished in the y axis and much smaller than they were before. The GUI used to fit the cameras in a 2x2 grid and the dimensions seemed to be scaled such that the ratio between x & y was maintained (uniform scaling, ie. it actually looked good & not squished). Also, the display for the camera "Driveway" is shorter in the y axis such that it doesn't line up with the other cameras and the white portion where it has the camera name, "events" "recordings", etc. is bigger than others. Pictures below
<img width="1918" alt="Screenshot 2024-02-10 at 3 07 42 PM" src="https://github.com/blakeblackshear/frigate/assets/75652194/b8d74d7a-ca96-4bb0-85ea-b52ad62d0622">

I have tried using 3 different browsers (Safari, chrome, firefox) and 2 different computers and the result is the same.

I tried searching the issues and couldn't find any like this. 

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  host: [REDACTED]]
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: [REDACTED]]
  password: [REDACTED]]
  stats_interval: 60
  
# ffmpeg:
#   hwaccel_args: preset-vaapi

# detectors:
#   coral:
#     type: edgetpu
#     device: usb

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model: 
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


#Settings for Livestream via go2rtc 
go2rtc:
  streams:
    rtsp_Driveway:
      - rtsp://[REDACTED]]/cam/realmonitor?channel=1&subtype=0

    rtsp_Porch:
      - rtsp://[REDACTED]]/cam/realmonitor?channel=1&subtype=0
  
    rtsp_Backyard:
      - rtsp://[REDACTED]]/cam/realmonitor?channel=1&subtype=0

    rtsp_Playground:
      - rtsp://[REDACTED]]/cam/realmonitor?channel=1&subtype=0



# #Global Object Settings
# objects:
#   track:
#     - person
#   filters:
#     person:
#       min_area: 5000
#       max_area: 100000

cameras:
  driveway:
    ffmpeg:
      inputs:
        #High Res = subtype 0, low res = subtype 1
        - path: rtsp://[REDACTED]]/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            #- rtmp

        - path: rtsp://[REDACTED]]/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            # - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
        # rtmp: -c:v copy -c:a copy -f flv
    
    live:
      stream_name: rtsp_Driveway

    # rtmp:
    #   enabled: true

    # detect:
    #   width: 704
    #   height: 480
    #   #width: 800
    #   #height: 480

    objects:
      track:
        - person
        #- cell phone
        - car
        #- cat
        #- dog
        #- motorcycle

      filters:
        car:
          threshold: 0.7
          mask:
            - 0,0,1035,0,1204,0,1280,0,1280,153,667,137,114,144,72,143,79,218,85,302,70,423,45,544,0,639 #timestamp & gutter
            - 608,214,702,214,741,221,715,245,934,342,1280,489,1280,587,1060,720,514,720,494,486,497,388,512,330,529,275,516,240,456,218 #Entire Driveway

        person:
          threshold: 0.7
          mask: 
            - 890,387,988,527,1050,582,1079,635,1074,705,994,720,857,716,818,720,795,720,726,715,521,720,490,406 #motorycle parking spot
            - 0,0,1035,0,1204,0,1280,0,1280,153,667,137,114,144,72,143,79,218,85,302,70,423,45,544,0,639 #timestamp & gutter 

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30

    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        # required_zones: 
        #     - zone_1
        retain:
          default: 30
          mode: active_objects

      #Old Record
    # record:
    #   enabled: true
    #   retain_days: 0
    #   events:
    #     required_zones: 
    #         - zone_1
    #     retain:
    #       default: 3

    zones:
      zone_0:
        coordinates: 605,448,660,639,1062,720,1280,588,1195,501,1066,417,901,333,831,297,791,272,728,242,626,244,592,258,560,338
      zone_1:
        coordinates: 473,226,566,223,664,219,697,216,1280,263,1280,545,814,268,760,236,723,231,663,239,632,242,587,256,545,280,548,299,535,308,529,328,527,344,517,720,0,720,21,647,66,499,77,416,84,328,83,256,259,241
      # zone_mailbox:
      #   coordinates: 520,92,518,220,240,243,226,95
      street:
        coordinates: 333,75,713,69,1280,103,1280,266,840,231,697,219,472,221,455,241,283,260,68,266,61,84

    # zones:
    #   loft_zone:
    #     coordinates: 800,480,800,163,243,225,237,480

    motion:
      mask: 
        - 0,0,1035,0,1204,0,1280,0,1280,153,667,137,114,144,83,157,79,218,85,302,70,423,45,544,0,639 #timestamp & gutter
        - 906,324,1064,400,1197,501,1238,572,1166,659,1058,720,877,720,795,720,576,720,551,555,549,459,594,369 #motorcycle
    
    ui:
      order: 1

  Porch:
    ffmpeg:
      inputs:
        #High Res = subtype 0, low res = subtype 1
        - path: rtsp://[REDACTED]]/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

        - path: rtsp://[REDACTED]]cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            # - rtmp

      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
        # rtmp: -c:v copy -c:a copy -f flv

    live:
      stream_name: rtsp_Porch

    # rtmp:
    #   enabled: true

    # detect:
    #   width: 640
    #   height: 480

    objects:
      track:
        - person
        #- cell phone
        #- car
        #- cat
        #- dog
        #- motorcycle
      filters:
        person:
          threshold: 0.7
          mask:
            - 0,0,428,0,1280,0,1280,720,786,720,800,612,811,550,823,493,843,372,855,270,860,175,868,51,843,41,844,12,805,13,748,8,660,3,557,5,466,9,365,20,289,32,278,55,279,110,286,192,305,318,249,343,220,198,213,117,161,105,151,85,149,42,0,95

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30

    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects

    # record:
    #   enabled: true
    #   retain_days: 0
    #   events:
    #     retain:
    #       default: 3

    # zones:
    #   loft_zone:
    #     coordinates: 800,480,800,163,243,225,237,480

    motion:
      mask: 0,0,428,0,1280,0,1280,720,786,720,800,612,811,550,823,493,843,372,855,270,860,175,868,51,843,41,844,12,805,13,748,8,660,3,557,5,466,9,365,20,289,32,278,55,279,110,286,192,305,318,249,343,220,198,213,117,161,105,151,85,149,42,0,95
      
    ui:
      order: 3

  Backyard:
    ffmpeg:
      inputs:

        #High Res = subtype 0, low res = subtype 1
        - path: rtsp://[REDACTED]]cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

        - path: rtsp:/[REDACTED]]lmonitor?channel=1&subtype=0
          roles:
            - record
            # - rtmp

      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
        # rtmp: -c:v copy -c:a copy -f flv

    live:
      stream_name: rtsp_Backyard
  


    objects:
      track:
        - person
        #- cell phone
        - car
        #- cat
        #- dog
        #- motorcycle
      filters:
        person:
          threshold: 0.91

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30

    record:
      enabled: true
      retain:
        days: 4
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects

    # record:
    #   enabled: true
    #   retain_days: 0
    #   events:
    #     retain:
    #       default: 3

    # zones:
    #   loft_zone:
    #     coordinates: 800,480,800,163,243,225,237,480

    motion:
      mask: 109,332,265,223,354,165,447,115,532,74,626,34,826,23,1036,29,1048,58,1042,212,1015,452,977,632,947,720,1280,720,1280,203,1280,0,645,0,0,0,0,372,0,422 #dead areas

    ui:
      order: 4

  Playground:
    ffmpeg:
      inputs:
        #High Res = subtype 0, low res = subtype 1
        - path: rtsp://[REDACTED]]/realmonitor?channel=1&subtype=1
          roles:
            - detect

        - path: rtsp:/[REDACTED]]am/realmonitor?channel=1&subtype=0
          roles:
            - record
            # - rtmp

      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
        # rtmp: -c:v copy -c:a copy -f flv

    live:
      stream_name: rtsp_Playground

    # rtmp:
    #   enabled: true

    # detect:
    #   width: 640
    #   height: 480
    #   #800 x 480

    objects:
      track:
        - person
        #- cell phone
        #- car
        #- cat
        #- dog
        #- motorcycle
      filters:
        person:
          threshold: 0.91

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30

    record:
      enabled: true
      retain:
        days: 4
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects

    # record:
    #   enabled: true
    #   retain_days: 0
    #   events:
    #     retain:
    #       default: 3

    # zones:
    #   loft_zone:
    #     coordinates: 800,480,800,163,243,225,237,480

    motion:
      mask: 203,0,427,0,1280,0,1280,720,1189,720,1280,597,1280,475,1259,462,1220,447,1230,382,1234,349,1207,341,1224,261,1064,220,909,178,798,147,728,123,653,110,527,99,413,89,351,82,280,87,236,87,177,87,127,105,84,82,69,112,56,127,69,210,93,315,123,400,155,467,191,553,203,611,250,720,0,720,0,720,0,0

    ui:
      order: 5
```

### Relevant log output

```shell
None relevant but here's my logs:

2024-02-10 00:46:12.313979663  [INFO] Preparing Frigate...
2024-02-10 00:46:12.329099250  [INFO] Starting Frigate...
2024-02-10 00:46:13.456514638  [2024-02-10 00:46:13] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-10 00:46:39.658194914  [2024-02-10 00:46:39] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2024-02-10 00:46:39.673508584  [2024-02-10 00:46:39] peewee_migrate.logs            INFO    : Starting migrations
2024-02-10 00:46:39.677784729  [2024-02-10 00:46:39] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-10 00:46:39.684790343  [2024-02-10 00:46:39] frigate.app                    INFO    : Recording process started: 611
2024-02-10 00:46:39.686999203  [2024-02-10 00:46:39] frigate.app                    INFO    : go2rtc process pid: 89
2024-02-10 00:46:39.710341892  [2024-02-10 00:46:39] detector.ov                    INFO    : Starting detection process: 621
2024-02-10 00:46:39.715834225  [2024-02-10 00:46:39] frigate.app                    INFO    : Output process started: 623
2024-02-10 00:46:39.739385151  [2024-02-10 00:46:39] frigate.app                    INFO    : Camera processor started for driveway: 629
2024-02-10 00:46:39.746021216  [2024-02-10 00:46:39] frigate.app                    INFO    : Camera processor started for Porch: 631
2024-02-10 00:46:39.751928046  [2024-02-10 00:46:39] frigate.app                    INFO    : Camera processor started for Backyard: 632
2024-02-10 00:46:39.761514929  [2024-02-10 00:46:39] frigate.app                    INFO    : Camera processor started for Playground: 634
2024-02-10 00:46:39.769405772  [2024-02-10 00:46:39] frigate.app                    INFO    : Capture process started for driveway: 637
2024-02-10 00:46:39.777556439  [2024-02-10 00:46:39] frigate.app                    INFO    : Capture process started for Porch: 643
2024-02-10 00:46:39.786341416  [2024-02-10 00:46:39] frigate.app                    INFO    : Capture process started for Backyard: 655
2024-02-10 00:46:39.794091059  [2024-02-10 00:46:39] frigate.app                    INFO    : Capture process started for Playground: 660
2024-02-10 00:46:39.798803068  [35mE: [xLinkUsb] [    999798] [frigate.detecto] usb_find_device_with_bcd:266	Library has not been initialized when loaded[0m
2024-02-10 00:46:39.810191384  [35mE: [xLinkUsb] [    999810] [frigate.detecto] usb_find_device_with_bcd:266	Library has not been initialized when loaded[0m
2024-02-10 00:46:40.034634499  [2024-02-10 00:46:40] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,300,300,3]
2024-02-10 00:46:40.034759982  [2024-02-10 00:46:40] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,1,100,7]
2024-02-10 00:46:40.034762468  [2024-02-10 00:46:40] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2024-02-10 12:46:16.541125147  [2024-02-10 12:46:16] frigate.comms.dispatcher       INFO    : Turning off detection for Backyard
```

### FFprobe output from your camera

```shell
DRIVEWAY:
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 704x480
FPS: 5/1

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 3840x2160
FPS: 15/1


PORCH:
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: 5/1

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 30/1

BACKYARD:
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: 5/1

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 30/1

PLAYGROUND
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: Unknown

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: Unknown
```

### Frigate stats

```json
{"cameras":{"Backyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":655,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":661,"pid":632,"process_fps":5.0,"skipped_fps":0.0},"Playground":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":660,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":674,"pid":634,"process_fps":5.0,"skipped_fps":0.0},"Porch":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":643,"detection_enabled":1,"detection_fps":3.5,"ffmpeg_pid":669,"pid":631,"process_fps":5.0,"skipped_fps":0.0},"driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":637,"detection_enabled":1,"detection_fps":5.0,"ffmpeg_pid":656,"pid":629,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"78":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"0.0","cpu_average":"0","mem":"0.0"},"100":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"104":{"cmdline":"python3 -u -m frigate","cpu":"2.0","cpu_average":"1","mem":"0.2"},"126":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"135":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"136":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"137":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"138":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"139":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"140":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"141":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"143":{"cmdline":"nginx: worker process","cpu":"0.2","cpu_average":"0","mem":"0.0"},"144":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"555":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.1"},"611":{"cmdline":"frigate.recording_manager","cpu":"3.2","cpu_average":"1","mem":"0.1"},"620":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"621":{"cmdline":"frigate.detector.ov  ","cpu":"27.6","cpu_average":"15","mem":"0.2"},"623":{"cmdline":"frigate.output       ","cpu":"0.9","cpu_average":"0","mem":"0.1"},"626":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"628":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"629":{"cmdline":"frigate.process:driveway","cpu":"3.6","cpu_average":"2","mem":"0.1"},"630":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"631":{"cmdline":"frigate.process:Porch","cpu":"2.9","cpu_average":"2","mem":"0.1"},"632":{"cmdline":"frigate.process:Backyard","cpu":"1.1","cpu_average":"0","mem":"0.1"},"634":{"cmdline":"frigate.process:Playground","cpu":"0.7","cpu_average":"0","mem":"0.1"},"635":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"637":{"cmdline":"frigate.capture:driveway","cpu":"0.7","cpu_average":"0","mem":"0.1"},"638":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"643":{"cmdline":"frigate.capture:Porch","cpu":"0.5","cpu_average":"0","mem":"0.1"},"655":{"cmdline":"frigate.capture:Backyard","cpu":"0.5","cpu_average":"0","mem":"0.1"},"656":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@[REDACTED]/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=704:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.6","cpu_average":"1","mem":"0.0"},"660":{"cmdline":"frigate.capture:Playground","cpu":"0.5","cpu_average":"0","mem":"0.1"},"661":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@[REDACTED]/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.8","cpu_average":"1","mem":"0.0"},"669":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.32:554/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.8","cpu_average":"1","mem":"0.0"},"670":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*[REDACTED]/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/Backyard@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"0","mem":"0.0"},"671":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@1[REDACTED]/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4","cpu":"1.6","cpu_average":"1","mem":"0.0"},"674":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@[REDACTED]/cam/realmonitor?channel=1&subtype=1 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"1.1","cpu_average":"1","mem":"0.0"},"679":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.32:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/Porch@%Y%m%d%H%M%S%z.mp4","cpu":"1.1","cpu_average":"0","mem":"0.0"},"681":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.0.34:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/Playground@%Y%m%d%H%M%S%z.mp4","cpu":"2.2","cpu_average":"1","mem":"0.0"},"165527":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":8.5,"detectors":{"ov":{"detection_start":0.0,"inference_speed":12.91,"pid":621}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":555},"recording":{"pid":611}},"service":{"last_updated":1707596355,"latest_version":"0.13.1","storage":{"/dev/shm":{"free":123.0,"mount_type":"tmpfs","total":128.0,"used":5.0},"/media/frigate/clips":{"free":1741041.1,"mount_type":"zfs","total":1841660.2,"used":100619.1},"/media/frigate/recordings":{"free":1741041.1,"mount_type":"zfs","total":1841660.2,"used":100619.1},"/tmp/cache":{"free":943.4,"mount_type":"tmpfs","total":953.7,"used":10.2}},"temperatures":{},"uptime":52356,"version":"0.13.1-34fb1c2"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Armcrest IP8M-2496E, Armcrest IP2M-843E, (2) Armcrest IP2M-852E

### Any other information that may be helpful

Hardware: Lenovo p520 with W-2135 CPU. 
I'm running Proxmox and have a lxc with docker compose installed, which I use to run frigate. No GPU or coral
