### ISSUE TITLE
Global Snapshot settings

### ISSUE THREAD

**Issue by scho0ck** [blakeblackshear/frigate#979]
As of now it seems that the snapshot settings are set per camera is it possible to set it globally?

for example have this set for all cameras

```
  
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
 ```

**Comment by HITChris** [comment]
It seems it was left out of the new docs.... but at least at some point in the past, blake's code was configured to look out for a global-level snapshot config (before proceeding to camera-level snapshot configs)

```
# Optional: Global configuration for the jpg snapshots written to the clips directory for each event
snapshots:
  # Optional: Retention settings (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```

Have you given something like the above a shot?
