### ISSUE TITLE
[Support]: Objects moving in a single zone creating multiple events

### ISSUE THREAD

**Issue by boof-boof-boof** [blakeblackshear/frigate#9791]
### Describe the problem you are having

I've noticed that I'm getting a lot of instances where an object, e.g. a cat, is moving through my garden and I get two events. This happens with objects that are only detected in a single zone, and happens with both cameras pointing to outside spaces (garden and driveway). 

Some screenshot examples (ignore the fact one of them is clearly a fox and not a cat :) ). 

<img width="489" alt="Screenshot 2024-02-11 at 08 46 38" src="https://github.com/blakeblackshear/frigate/assets/98875349/423e1d59-e181-4df2-b8f8-39e13fcdd991">

<img width="456" alt="Screenshot 2024-02-11 at 08 41 11" src="https://github.com/blakeblackshear/frigate/assets/98875349/4c905126-1d94-4e8d-b96a-5f9c9179aac6">

<img width="467" alt="Screenshot 2024-02-11 at 08 47 11" src="https://github.com/blakeblackshear/frigate/assets/98875349/8ae97e8b-4d58-48ea-bdef-353d139da16f">

The start/end times and duration show overlap so I'd have expected a single event in these cases?

I'm not sure if this is an issue only since using Frigate+ model, as my cameras weren't very good at detecting cats (or foxes) with the previous model on 0.12.

My understanding is that stationary objects are always tracked now, so even if i.e. the cat stops moving for a bit, it should still be detected as the same object/event?

This isn't a major issue, just want to understand why there are multiple events instead of a single event.

### Version

0.13.1

### Frigate config file

```yaml
mqtt:
  host: *
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *
  password: *

###########################
# GLOBAL/DEFAULT SETTINGS #
###########################
detect:
  fps: 5
#
detectors:
  coral:
    type: edgetpu
    device: usb
#
model:
  path: plus://*
#
objects:
  track:
    - person
    - car
    - cat
    - dog
    - face
    - license_plate
    - amazon
    - package
#
birdseye:
  enabled: True
  mode: continuous
#
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 30
      mode: active_objects
      objects:
        person: 30
        car: 10
        cat: 7
        dog: 7
#
snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: false
  height: 1280
  retain:
    default: 30
    objects:
      person: 30
      car: 10
      cat: 7
      dog: 7
#
ffmpeg:
  hwaccel_args: preset-vaapi
#
go2rtc:
  streams:
    doorbell:
      - "ffmpeg:http://*"
      - rtsp://*
    doorbell_sub:
      - "ffmpeg:http://*"
    frontcam:
      - rtsp://*
    sidecam:
      - rtsp://*
    kitchen:
      - rtsp://*
  webrtc:
    candidates:
      - *:8555
      - *:8555
#
cameras:
##################################################
#                    FRONTCAM                    #
################################################## 
  frontcam:
    ui:
      order: 1
    birdseye:
      order: 1
    mqtt:
      bounding_box: False
      height: 720
      required_zones:
        - driveway
        - frontdoor
        - street
        - drive_entrance
    detect:
      width: 2592 # full stream width
      height: 1944 # full stream height
    objects:
      filters:
        person:
          mask:
            - 2592,761,2592,583,2463,444,2309,543,2385,717
        car: 
          mask:
            - 21,1202,0,531,406,134,910,55,1375,105,1665,309,1845,682,1382,809,845,1419
    record:
      events:
        required_zones:
          - driveway
          - frontdoor
          - street
          - drive_entrance
    snapshots:
      required_zones:
        - driveway
        - frontdoor
        - street
        - drive_entrance
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontcam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      driveway:
        coordinates: 0,1944,2239,1944,1875,862,2049,692,1777,252,1465,98,746,0,0,226 # full stream size
        objects:
          - person
          - face
          - dog
          - cat
        filters:
          person:
            min_area: 50000
            max_area: 250000
            min_score: 0.75
            threshold: 0.85
          face:
            min_score: 0.7
          cat:
            min_area: 4000
            max_area: 60000
            min_score: 0.75
            threshold: 0.85
          dog:
            min_area: 8000
            max_area: 60000
            min_score: 0.75
            threshold: 0.85
      drive_entrance:
        coordinates: 1947,252,2213,703,1973,679,1769,242
        objects:
          - car
          - license_plate
        filters:
          license_plate:
            min_score: 0.6
      frontdoor:
        coordinates: 2057,1331,2422,1214,2478,895,2240,574,1934,521,1993,647,1885,821 # full stream size
        objects:
          - person
          - face
          - dog
          - cat
        filters:
          person:
            min_area: 60000
            max_area: 250000
            min_score: 0.75
            threshold: 0.85
          face:
            min_score: 0.7
          cat:
            min_area: 4000
            max_area: 60000
            min_score: 0.75
            threshold: 0.85
          dog:
            min_area: 8000
            max_area: 60000
            min_score: 0.75
            threshold: 0.85
      street:
        coordinates: 1633,0,2285,701,2592,754,2592,294,1987,21 # full stream size
        objects:
          - person
        filters:
          person:
            min_area: 8000
            max_area: 60000
            min_score: 0.75
            threshold: 0.85
    motion:
      mask:
        - 0,142,789,142,780,0,0,0 # mask the clock
        - 0,1944,723,1944,771,1548,569,1260,189,1251,0,1289 # mask the stupid windy bush
        - 1047,1264,1252,993,1510,761,1730,691,1977,654,2071,678,2092,759,1806,953,1792,1182,1977,1410,1855,1587,1032,1622 # mask the stupid windy planter
##################################################
#                    SIDECAM                     #
################################################## 
  sidecam:
    ui:
      order: 3
    birdseye:
      order: 3
    mqtt:
      bounding_box: False
      height: 720
      required_zones:
        - garden
    detect:
      width: 2592 # full stream width
      height: 1944 # full stream height      
    objects:
      filters:
        person:
          mask:
            - 1865,861,2199,939,2241,542,1970,482 
    record:
      events:
        required_zones:
          - garden
    snapshots:
      required_zones:
        - garden
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sidecam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      garden:
        coordinates: 370,171,1562,290,1677,701,2592,771,2592,1944,0,1944,0,345 # full size stream coords
        objects:
          - person
          - face
          - cat
          - dog
        filters:
          person:
            min_area: 60000
            max_area: 160000
            min_score: 0.75
            threshold: 0.85
          face:
            min_score: 0.7
          cat:
            min_area: 5000
            max_area: 60000
            min_score: 0.7
            threshold: 0.75
          dog:
            min_area: 11000
            max_area: 60000
            min_score: 0.8
            threshold: 0.85
    motion:
      mask:
        - 0,142,789,142,780,0,0,0 # mask the clock
        - 2592,0,2592,393,2318,341,1947,147,1344,0
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5583d115d140] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/frontcam':
  Metadata:
    title           : go2rtc/1.8.5
  Duration: N/A, start: 0.070000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2592x1944, 15 fps, 20 tbr, 90k tbn
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW
