### ISSUE TITLE
Minimum motion duration before motion is triggered

### ISSUE THREAD

**Issue by coconup** [blakeblackshear/frigate#9792]
**Describe what you are trying to accomplish and why in non technical terms**
I'm using Frigate in order to support a surveillance and alarm system for camper vans, therefore the captured scenery will change all the time. I want to allow the user to trigger a notification when motion is detected, if they wish to do so. Right now, a lot of false positives occur which unnecessarily trigger the alarm.

**Describe the solution you'd like**
I would like to be able to set a `min_duration` config parameter under `motion`, which would result in the motion event to trigger only if motion is detected for longer than the provided value.

**Comment by coconup** [comment]
@blakeblackshear how would I do that? From the motion MQTT topic I only get an "ON" string and then an "OFF" string after 30s or so. How would I infer whether motion occurred for at least 5s, for example?

**Comment by blakeblackshear** [comment]
There are many examples here: https://www.home-assistant.io/docs/automation/trigger/ 

Something like this:

```yaml
automation:
  trigger:
    - platform: state
      entity_id:
        - sensor.camera_motion
      to: on
      # If given, will trigger when the condition has been true for X time; you can also use days and milliseconds.
      for:
        hours: 0
        minutes: 0
        seconds: 5 
```
