### ISSUE TITLE
[Config Support]: audio property is not allowed

### ISSUE THREAD

**Issue by carlo161** [blakeblackshear/frigate#9793]
### Describe the problem you are having

I am trying to activate audio for my streams but the config-schema does not include the "audio" property.
I tried to put it in the root of the yaml and on camera level wit the same results.

```
  ipcam-box:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ipcam-box
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: True
``` 
Am I missing something?

### Version

0.12.1-367D724

### Frigate config file

```yaml
ipcam-box:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ipcam-box
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: True
```

### Relevant log output

```shell
No log
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
