### ISSUE TITLE
[Config Support]: "No frames have been received, check Error logs"

### ISSUE THREAD

**Issue by Jautze82** [blakeblackshear/frigate#9803]
### Describe the problem you are having

with 3 Cameras (without Wintergarten) frigate running fine with very less "No frames have been received, check Error logs".

When I put in the 4 Camera I get "No frames have been received, check Error logs" all the time for the 4 Cameras.

### Version

latest 0.13.1-34FB1C2

### Frigate config file

```yaml
#detectors:
#  coral:
#    type: edgetpu
#    device: usb
mqtt:
  host: 192.168.1.138
  port: 1885
  client_id: frigate
  topic_prefix: frigate
birdseye:
  enabled: true
  restream: false
go2rtc:
  streams:
    Tuer:
      - rtsp://user:pw@192.168.1.109/live/ch0
    Pool:
      - rtsp://user:pw@192.168.1.184:554/live/ch0
    Wintergarten:
      - rtsp://user:pw@192.168.1.143:554/live/ch0
    Garage:
      - "ffmpeg:rtsp://user:pw@192.168.1.120:554/live/ch0#video=h264#audio=aac#hardware=vaapi"
cameras:  
  Tuer:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Tuer
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    mqtt:
      enabled: True
      timestamp: True
  Pool:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Pool
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    mqtt:
      enabled: True
      timestamp: True
  Wintergarten:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Wintergarten
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    mqtt:
      enabled: True
      timestamp: True
  Garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 2304
      height: 1296
    mqtt:
      enabled: True
      timestamp: True
objects:
  track:
    - person
    - car
    - dog
    - cat
  filters:
    person:
      min_area: 5000
      threshold: 0.7
    car:
      min_area: 5200
      threshold: 0.7
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
snapshots:
  enabled: True
  clean_copy: False
  timestamp: True
  bounding_box: True
  retain:
    default: 7
    objects:
      person: 14
      car: 14
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args: 
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
timestamp_style:
  position: "bl"
  color:
    red: 0
    green: 0
```

### Relevant log output

```shell
Frigatte Logs:
2024-02-11 17:28:36.855118210  [INFO] Preparing Frigate...
2024-02-11 17:28:36.886756923  [INFO] Starting Frigate...
2024-02-11 17:28:38.499380799  [2024-02-11 17:28:38] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-11 17:28:38.572955921  [2024-02-11 17:28:38] peewee_migrate.logs            INFO    : Starting migrations
2024-02-11 17:28:38.860951331  [2024-02-11 17:28:38] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-11 17:28:38.911216004  [2024-02-11 17:28:38] frigate.app                    INFO    : Recording process started: 297
2024-02-11 17:28:38.914782811  [2024-02-11 17:28:38] frigate.app                    INFO    : go2rtc process pid: 89
2024-02-11 17:28:38.960192622  [2024-02-11 17:28:38] frigate.app                    INFO    : Output process started: 308
2024-02-11 17:28:38.972067938  [2024-02-11 17:28:38] detector.cpu                   INFO    : Starting detection process: 307
2024-02-11 17:28:38.977124602  [2024-02-11 17:28:38] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-02-11 17:29:05.911159976  [2024-02-11 17:29:05] frigate.app                    INFO    : Camera processor started for Tuer: 366
2024-02-11 17:29:05.928637668  [2024-02-11 17:29:05] frigate.app                    INFO    : Camera processor started for Pool: 367
2024-02-11 17:29:05.938209486  [2024-02-11 17:29:05] frigate.app                    INFO    : Camera processor started for Wintergarten: 369
2024-02-11 17:29:05.947139235  [2024-02-11 17:29:05] frigate.app                    INFO    : Camera processor started for Garage: 371
2024-02-11 17:29:05.969306629  [2024-02-11 17:29:05] frigate.app                    INFO    : Capture process started for Tuer: 372
2024-02-11 17:29:06.024189016  [2024-02-11 17:29:06] frigate.app                    INFO    : Capture process started for Pool: 378
2024-02-11 17:29:06.025729242  [2024-02-11 17:29:06] frigate.app                    INFO    : Capture process started for Wintergarten: 379
2024-02-11 17:29:06.042921733  [2024-02-11 17:29:06] frigate.app                    INFO    : Capture process started for Garage: 380


GOTRC Log:
2024-02-11 17:28:36.855188983  [INFO] Preparing new go2rtc config...
2024-02-11 17:28:37.261522834  [INFO] Starting go2rtc...
2024-02-11 17:28:37.365840899  17:28:37.365 INF go2rtc version 1.8.4 linux/amd64
2024-02-11 17:28:37.366528784  17:28:37.366 INF [rtsp] listen addr=:8554
2024-02-11 17:28:37.366791155  17:28:37.366 INF [webrtc] listen addr=:8555
2024-02-11 17:28:37.367284975  17:28:37.367 INF [api] listen addr=:1984
2024-02-11 17:28:46.848765166  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"Garage":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":380,"detection_enabled":1,"detection_fps":2.7,"ffmpeg_pid":393,"pid":371,"process_fps":1.0,"skipped_fps":4.1},"Pool":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":378,"detection_enabled":1,"detection_fps":2.7,"ffmpeg_pid":388,"pid":367,"process_fps":2.2,"skipped_fps":2.8},"Tuer":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":372,"detection_enabled":1,"detection_fps":1.3,"ffmpeg_pid":377,"pid":366,"process_fps":3.3,"skipped_fps":1.9},"Wintergarten":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":379,"detection_enabled":1,"detection_fps":1.1,"ffmpeg_pid":387,"pid":369,"process_fps":3.9,"skipped_fps":1.1}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"1.8","cpu_average":"1","mem":"0.1"},"101":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"111":{"cmdline":"python3 -u -m frigate","cpu":"5.6","cpu_average":"6","mem":"1.7"},"121":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"135":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"136":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"137":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"138":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"139":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"295":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.3"},"297":{"cmdline":"frigate.recording_manager","cpu":"1.9","cpu_average":"1","mem":"0.4"},"306":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"307":{"cmdline":"frigate.detector.cpu ","cpu":"182.3","cpu_average":"139","mem":"0.4"},"308":{"cmdline":"frigate.output       ","cpu":"0.6","cpu_average":"0","mem":"0.4"},"312":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"313":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"314":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"315":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"316":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"366":{"cmdline":"frigate.process:Tuer ","cpu":"1.5","cpu_average":"0","mem":"0.5"},"367":{"cmdline":"frigate.process:Pool ","cpu":"1.6","cpu_average":"1","mem":"0.5"},"369":{"cmdline":"frigate.process:Wintergarten","cpu":"1.3","cpu_average":"0","mem":"0.5"},"371":{"cmdline":"frigate.process:Garage","cpu":"1.5","cpu_average":"1","mem":"0.5"},"372":{"cmdline":"frigate.capture:Tuer ","cpu":"2.5","cpu_average":"2","mem":"0.4"},"377":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Tuer -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Tuer@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"4","mem":"0.2"},"378":{"cmdline":"frigate.capture:Pool ","cpu":"2.5","cpu_average":"2","mem":"0.4"},"379":{"cmdline":"frigate.capture:Wintergarten","cpu":"2.4","cpu_average":"2","mem":"0.4"},"380":{"cmdline":"frigate.capture:Garage","cpu":"3.6","cpu_average":"3","mem":"0.4"},"387":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Wintergarten -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Wintergarten@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"4","mem":"0.2"},"388":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Pool -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Pool@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.9","cpu_average":"4","mem":"0.2"},"393":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2304:h=1296:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.3","cpu_average":"4","mem":"0.3"},"395":{"cmdline":"ffmpeg -hide_banner -v error -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags allow_profile_mismatch -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://*:*@192.168.1.120:554/live/ch0 -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -c:a aac -vf format=vaapi|nv12,hwupload,scale_vaapi=out_color_matrix=bt709:out_range=tv:format=nv12 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ca8dd701b892e5770e7c9af474bfadf1","cpu":"3.0","cpu_average":"3","mem":"0.1"},"3999":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":7.8,"detectors":{"cpu":{"detection_start":1707673463.59146,"inference_speed":125.97,"pid":307}},"gpu_usages":{"intel-vaapi":{"gpu":"15.95%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":295},"recording":{"pid":297}},"service":{"last_updated":1707673464,"latest_version":"0.13.1","storage":{"/dev/shm":{"free":212.6,"mount_type":"tmpfs","total":256.0,"used":43.4},"/media/frigate/clips":{"free":4612993.9,"mount_type":"nfs4","total":10974873.6,"used":6361879.7},"/media/frigate/recordings":{"free":4612993.9,"mount_type":"nfs4","total":10974873.6,"used":6361879.7},"/tmp/cache":{"free":948.3,"mount_type":"tmpfs","total":953.7,"used":5.4}},"temperatures":{},"uptime":918,"version":"0.13.1-34fb1c2"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # 126MB
    devices:
      - /dev/dri/renderD128 
#      - /dev/bus/usb/002/003:/dev/bus/usb/002/003
    volumes:
      #- /home/admin/config.yml:/config/config.yml
      - frigate_config:/config
      - frigate_media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "Password"
volumes:
  frigate_media:
    external: true
  frigate_config:
    external: true
