### ISSUE TITLE
[Support]: Configured UI timezone not considered in export

### ISSUE THREAD

**Issue by mike2307** [blakeblackshear/frigate#9806]
### Describe the problem you are having

The host where my frigate instance is running is configured to run in time zone UTC. This is a system-wide setting and is also used for the camera's internal time stamp overlay.
The machine where I am accessing the frigate instance is in time zone CET (browser time), later this year it will be in CEST.
I have configured the UI time zone in my config.yml to be in UTC as well to prevent any mix-up.

As far as I could check the source code of the web directory, the configured `ui.timezone` is not considered in the Export.jsx file.
Therefore I need to compensate the (currently) 1 hour difference before starting an export; meaning that I need to export a time range from 12:00 to 13:00 in order to get the 11:00 to 12:00 recorded export, even though I have configured  `ui.timezone` to match up.

I would expect that this configuration parameter is considered also in the Export section.

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  enabled: false

birdseye:
  enabled: true
  restream: false
  mode: continuous
  width: 1280
  height: 360

ui:
  live_mode: mse
  timezone: UTC
  date_style: medium

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  openvino:
    type: openvino
    device: GPU

model:
  path: /custom_models/yolov8s.xml
  labelmap_path: /custom_models/coco_80cl.txt
  width: 416
  height: 416
  input_pixel_format: bgr
  input_tensor: nchw
  model_type: yolov8

detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5

record:
  enabled: true
  retain:
    days: 30
    mode: all
  export:
    # fits 1 hour into 1 minute (1/60), 15 FPS
    timelapse_args: "-vf setpts=PTS/60 -r 15"
  events:
    retain:
      default: 365
      mode: motion
  sync_recordings: true

snapshots:
  enabled: true
  retain:
    default: 365

go2rtc:
  streams:
    Bach_HD:
    - rtsp://admin:--------@10.42.0.3:554/cam/realmonitor?channel=1&subtype=0
    Bach_SD:
    - rtsp://admin:--------@10.42.0.3:554/cam/realmonitor?channel=1&subtype=1
    Werkzeughuette_HD:
    - rtsp://admin:--------@10.42.0.4:554/cam/realmonitor?channel=1&subtype=0
    Werkzeughuette_SD:
    - rtsp://admin:--------@10.42.0.4:554/cam/realmonitor?channel=1&subtype=0

cameras:
  Bach:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Bach_HD
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    live:
      stream_name: Bach_SD
    record:
      retain:
        days: 15
    motion:
      mask:
      - 1280,469,880,356,728,331,564,320,470,309,471,260,675,245,878,241,974,177,1280,132,1280,0,0,0,0,720,1280,720
    objects:
      filters:
        person:
          mask:
          - 1200,280,1200,320,1170,320,1170,280
        dog:
          mask:
          - 1200,280,1200,320,1170,320,1170,280

  Werkzeughuette:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Werkzeughuette_HD
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    live:
      stream_name: Werkzeughuette_SD
    motion:
      mask:
      - 0,66,111,64,114,207,210,208,334,198,544,195,695,198,917,188,1066,206,1027,104,1084,63,1187,114,1221,223,1280,246,1280,0,0,0
    objects:
      filters:
        bear:
          mask:
          - 375,155,430,155,430,195,375,195
          - 25,345,150,345,150,490,25,490

objects:
  track:
  - person
  - car
  - bird
  - cat
  - dog
  - horse
  - sheep
  - cow
  - elephant
  - bear
  - zebra
  - giraffe
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wireless

### Camera make and model

n/a
