### ISSUE TITLE
Tesorrt not working

### ISSUE THREAD

**Issue by Cah1982** [blakeblackshear/frigate#9809]
### Describe the problem you are having

Im guessingt he new Frigate changed how some things are configured, and files are now located in different folders

I think i have adjusted the compose file and yml, but i get the below in logs

from terminal i can see the file

`/home/docker/frigate/config/model_cache/tensorrt# ls
8.5.3  yolov7-320.trt  yolov7-tiny-416.trt

### Version

latest docker image

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

 model:
  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### docker-compose file or Docker CLI command

```yaml
version: "3.6"
services:
  frigate:
    container_name: "frigate"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "YOLO_MODELS=yolov7-tiny-416"
      - "USE_FP16=false"
```

### Relevant log output

```shell
Error: bad file '/config/config.yml': yaml: line 8: did not find expected key
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

TP Link
