### ISSUE TITLE
[HW Accel Support]: Unsure if hardware acceleration actually working, or working as it should be

### ISSUE THREAD

**Issue by mintjberry** [blakeblackshear/frigate#9846]
### Describe the problem you are having

Frigate newby here. Apologies for any stupid questions/assumptions.

I have a N100 CPU computer (16GB RAM, Ubuntu Server, Kernel 6.5.0-17-generic, portainer) and am using around 40% of the CPU according to htop.
I have a PCIE coral installed. The only other thing running is pi-hole.
I'm using intel-vaapi, and it's reporting approx 1.3% GPU usage, so it's doing something, but I'd have thought that the CPU usage would be lower. I suspect that I should be setting my 'detect' width and height for each camera, but isn't the stream decode hardware accelerated, so should be using the GPU in my N100 CPU?
The only other thing I can think of is that it's all taken up by motion detection, if that's not hardware accelerated?
I do have a lot of cameras (10) and over half of them are 4k, all of them are H265 or H265+ I believe. The subchannel used for detect is set to 5 or 6 FPS in each camera, and is 720p or under for all cameras.

I think 40% is still pretty good considering this CPU only consumes several watts, but I have seen some skipped frames show up in the 'System' log, which I don't think is ideal (none showing in screenshots post reboot through). I have also read other users posts where they say they basically no load on their CPU when enabling hardware acceleration, so if I can do anything to drop the CPU load further that would be great.

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: True
  retain:
    days: 1
    mode: all

objects:
  track:
    - person
    # - dog
    # - car
    # - cat
        
snapshots:
  enabled: True
  retain:
    default: 30

detectors:
  coral_pci:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    Entrance_Left:
      - ffmpeg:rtsp://admin:password@10.1.1.51:554/Streaming/Channels/1
    Entrance_Right:
      - ffmpeg:rtsp://admin:password@10.1.1.65:554/Streaming/Channels/1 
    House_Front:
      - ffmpeg:rtsp://admin:password@10.1.1.92:554/Streaming/Channels/1
    Duck_Area_Tree:
      - ffmpeg:rtsp://admin:password@10.1.1.85:554/Streaming/Channels/1
    House_Garage:
      - ffmpeg:rtsp://admin:password@10.1.1.7:554/Streaming/Channels/1
    House_Lawn_Left:
      - ffmpeg:rtsp://admin:password@10.1.1.8:554/Streaming/Channels/1
    House_Lawn_Right:
       - ffmpeg:rtsp://admin:password@10.1.1.36:554/Streaming/Channels/1
    Garage_Garden_Bed:
      - ffmpeg:rtsp://admin:password@10.1.1.7:554/Streaming/Channels/1
    Shed_Lean_To:
       - ffmpeg:rtsp://admin:password@10.1.1.82:554/h264Preview_01_main
    Duck_House_Inside:
      - ffmpeg:rtsp://admin:password@10.1.1.60/avstream/channel=1/stream=0.sdp
    
cameras:
  Entrance_Left:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.51:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.51:554/Streaming/Channels/2
        roles:
        - detect

  Entrance_Right:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.65:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.65:554/Streaming/Channels/2
        roles:
        - detect

  House_Front:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.92:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.92:554/Streaming/Channels/2
        roles:
        - detect

  House_Garage:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.7:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.7:554/Streaming/Channels/2
        roles:
        - detect

  House_Lawn_Left:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.8:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.8:554/Streaming/Channels/2
        roles:
        - detect

  House_Lawn_Right:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.36:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.36:554/Streaming/Channels/2
        roles:
        - detect

  Garage_Garden_Bed:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.52:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.52:554/Streaming/Channels/2
        roles:
        - detect

  Duck_Area_Tree:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.85:554/Streaming/Channels/1
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.85:554/Streaming/Channels/2
        roles:
        - detect

  Duck_House_Inside:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.60/avstream/channel=1/stream=1.sdp
        roles:
        - record

  Shed_Lean_To:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@10.1.1.82:554/h264Preview_01_main
        roles:
        - record
      - path: rtsp://admin:password@10.1.1.82:554/h264Preview_01_sub
        roles:
        - detect
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2500mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /nvme/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear. Changed to 4GB
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
Here is the output for htop, sorted by CPU usage, am not sure if it will be formatted correctly. Further down you can see some warning flags. I don't know if this is important or not.

    PID USER       PRI  NI  VIRT   RES   SHR S  CPU%▽MEM%   TIME+  Command
  68323 root        20   0 1042M  132M 22964 R  27.5  0.8  1h02:51 frigate.detector.coral_pci
  68355 root        20   0 1149M  152M 18448 S   9.2  1.0 12:49.23 frigate.process:House_Lawn_Right
  68354 root        20   0 1129M  132M 17560 S   8.5  0.8 13:14.65 frigate.process:House_Lawn_Left
  68362 root        20   0 1131M  135M 17772 S   7.2  0.9 21:04.17 frigate.process:Duck_Area_Tree
  68344 root        20   0 1129M  132M 17176 S   6.5  0.8 20:00.01 frigate.process:Entrance_Left
  68345 root        20   0 1128M  131M 16904 S   6.5  0.8 20:31.33 frigate.process:Entrance_Right
  68349 root        20   0 1148M  151M 17016 S   6.5  1.0 15:16.20 frigate.process:House_Front
  68417 root        20   0  517M 56516 27648 S   6.5  0.4 18:44.50 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68314 root        20   0  990M  138M 20020 S   5.2  0.9  4:31.36 frigate.recording_manager
  68316 root        20   0  990M  138M 20020 S   5.2  0.9  4:26.85 frigate.recording_manager
  68383 root        20   0  518M 53560 27392 S   5.2  0.3 17:48.33 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  67919 root        20   0 2752M  271M 78164 S   4.6  1.7 11:14.47 python3 -u -m frigate
  68358 root        20   0 1128M  131M 17544 S   3.9  0.8 12:10.89 frigate.process:Garage_Garden_Bed
  68325 root        20   0 2346M  116M 11572 S   3.3  0.7  6:51.06 frigate.output
  68342 root        20   0 2752M  271M 78164 S   3.3  1.7  7:21.45 python3 -u -m frigate
  68350 root        20   0 1128M  131M 17252 S   3.3  0.8  9:36.02 frigate.process:House_Garage
  68365 root        20   0 1127M  130M 17044 S   3.3  0.8 11:38.85 frigate.process:Shed_Lean_To
  68429 root        20   0  511M 49044 28416 S   3.3  0.3 11:36.67 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68440 root        20   0  509M 47328 27776 S   3.3  0.3  8:27.78 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68464 root        20   0  127M 23192 16640 S   3.3  0.1  8:33.56 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68378 root        20   0  508M 46468 27264 S   2.6  0.3  5:28.34 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68391 root        20   0  127M 23004 16384 S   2.6  0.1  4:44.82 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68399 root        20   0 1134M  116M  7784 S   2.6  0.7  4:25.05 frigate.capture:House_Lawn_Right
  68419 root        20   0  128M 23088 16128 S   2.6  0.1  7:10.45 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1
  68461 root        20   0  128M 23168 15744 S   2.6  0.1  7:48.18 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68534 root        20   0 1149M  152M 18448 S   2.6  1.0  1:54.29 frigate.process:House_Lawn_Right
  68374 root        20   0  510M 47424 27776 S   2.0  0.3  7:23.53 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68408 root        20   0  128M 23708 15616 S   2.0  0.1  7:16.20 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68426 root        20   0 1134M  116M  7784 S   2.0  0.7  4:15.27 frigate.capture:House_Lawn_Right
  68442 root        20   0  508M 47160 27520 S   2.0  0.3  6:19.74 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68453 root        20   0  508M 50720 29056 S   2.0  0.3  4:37.07 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68459 root        20   0  129M 24684 15744 S   2.0  0.2  5:43.91 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68529 root        20   0  517M 56516 27648 S   2.0  0.4  5:06.16 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68533 root        20   0 1149M  152M 18448 S   2.0  1.0  1:58.57 frigate.process:House_Lawn_Right
  68535 root        20   0 1149M  152M 18448 S   2.0  1.0  1:55.25 frigate.process:House_Lawn_Right
  68543 root        20   0  518M 53560 27392 S   2.0  0.3  5:02.03 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68636 root        20   0 1131M  135M 17772 S   2.0  0.9  3:40.13 frigate.process:Duck_Area_Tree
  68637 root        20   0 1131M  135M 17772 R   2.0  0.9  3:38.82 frigate.process:Duck_Area_Tree
 188828 matt        20   0  9932  6144  3584 R   2.0  0.0  0:05.12 htop
  68333 root        20   0 1042M  132M 22964 S   1.3  0.8  4:06.22 frigate.detector.coral_pci
  68364 root        20   0 1126M  129M 17108 S   1.3  0.8  4:55.72 frigate.process:Duck_House_Inside
  68369 root        20   0 1124M  114M  7656 S   1.3  0.7  2:20.46 frigate.capture:Entrance_Left
  68377 root        20   0 1134M  116M  7656 S   1.3  0.7  4:24.40 frigate.capture:House_Front
  68385 root        20   0 1124M  114M  7656 S   1.3  0.7  2:09.83 frigate.capture:Entrance_Left
  68392 root        20   0 1124M  114M  7656 S   1.3  0.7  2:20.08 frigate.capture:House_Lawn_Left
  68394 root        20   0  126M 21324 15616 S   1.3  0.1  4:39.36 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68397 root        20   0 1134M  116M  7656 S   1.3  0.7  4:14.88 frigate.capture:House_Front
  68398 root        20   0  509M 49512 27520 S   1.3  0.3  4:26.40 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68401 root        20   0  509M 49076 27648 S   1.3  0.3  4:40.84 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68402 root        20   0  131M 26032 15488 S   1.3  0.2  4:31.02 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1  68403 root        20   0 1124M  114M  7656 S   1.3  0.7  2:08.38 frigate.capture:House_Lawn_Left
  68406 root        20   0 1124M  114M  7656 S   1.3  0.7  2:09.31 frigate.capture:Garage_Garden_Bed
  68454 root        20   0 1126M  114M  7656 S   1.3  0.7  2:22.28 frigate.capture:Duck_Area_Tree
  68501 root        20   0 1129M  132M 17176 S   1.3  0.8  3:51.45 frigate.process:Entrance_Left
  68548 root        20   0 1148M  151M 17016 S   1.3  1.0  2:30.73 frigate.process:House_Front
  68574 root        20   0  509M 47328 27776 S   1.3  0.3  1:50.64 ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD1
```

### FFprobe output from your camera

```shell
This is for the house_front cam:

ffprobe rtsp://admin:password@10.1.1.92:554/Streaming/Channels/2
ffprobe version 6.0-6ubuntu1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-2ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://admin:password@10.1.1.92:554/Streaming/Channels/2':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], 6 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Mostly Anpviz, which may be an unbranded hikvision, or a clone

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/26233071/24193afc-01cf-4c61-ba37-0757299709a3)

![image](https://github.com/blakeblackshear/frigate/assets/26233071/ef11bf94-dd83-4faf-bd7e-688095ea0b8e)

![image](https://github.com/blakeblackshear/frigate/assets/26233071/e73ffce3-2dd1-4adf-8c76-4db8513a3b87)

![image](https://github.com/blakeblackshear/frigate/assets/26233071/d67835b2-7d05-40be-a3ef-ced6a4420289)
