### ISSUE TITLE
[Support]: dev release after 0.14.0-f6a4c2a fails with go2rtc error

### ISSUE THREAD

**Issue by ashleyw-gh** [blakeblackshear/frigate#9847]
### Describe the problem you are having

hi, any amd64 dev release after 0.14.0-f6a4c2a fails with the error in the error log.
Reverting back to 0.14.0-f6a4c2a works fine.

### Version

any verison after 0.14.0-f6a4c2a

### Frigate config file

```yaml
database:
  path: /db/frigate.db
mqtt:
  host: 192.168.3.17
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: {FRIGATE_MQTT_PASSWORD}
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
  #cpu1:
  #  type: cpu
  #  num_threads: 2
model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal

go2rtc:
  streams:
    front:
      - rtsp://{FRIGATE_FRONT_AUTH}@{FRIGATE_FRONT_CAM}:554/h264Preview_01_main
      - "ffmpeg:front#audio=opus"
    front_sub:
      - rtsp://{FRIGATE_FRONT_AUTH}@{FRIGATE_FRONT_CAM}:554/h264Preview_01_sub
    back:
      - rtsp://{FRIGATE_BACK_AUTH}@{FRIGATE_BACK_CAM}:554/h264Preview_01_main
      - "ffmpeg:back#audio=opus"
    back_sub:
      - rtsp://{FRIGATE_BACK_AUTH}@{FRIGATE_BACK_CAM}:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.3.16:8555
      - stun:8555

cameras:
  front:
    birdseye:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: front
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 2
    motion:
      mask:
        - 196,0,196,26,0,27,0,0
    objects:
      filters:
        person:
          min_area: 700
          mask:
            - 230,230,352,229,353,288,235,294
      track:
        - person
        - animal
  back:
    birdseye:
      order: 2
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: back
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 2
    motion:
      mask:
        - 490,195,489,308,558,308,606,127,565,93,499,103
        - 640,0,640,73,320,87,226,107,130,142,91,275,78,328,0,330,0,0
    objects:
      filters:
        person:
          min_area: 700
          mask:
            - 488,283,592,285,594,312,492,312
      track:
        - person
        - animal
motion:
  improve_contrast: True
record:
  enabled: True
  events:
    retain:
      default: 2
      mode: all
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 2
birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
2024-02-14 16:20:11.775482070  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2024-02-14 16:20:11.800929724  [INFO] Starting go2rtc...
2024-02-14 16:20:11.853790332  16:20:11.853 INF go2rtc version 1.8.5 linux/amd64
2024-02-14 16:20:11.854277525  16:20:11.854 INF [api] listen addr=:1984
2024-02-14 16:20:11.854347696  16:20:11.854 INF [rtsp] listen addr=:8554
2024-02-14 16:20:11.854586854  16:20:11.854 INF [webrtc] listen addr=:8555
2024-02-14 16:20:12.514476243  Frigate 0.14 UNSTABLE - not for public use at this time. Please use Frigate stable
2024-02-14 16:20:12.514989654  [2024-02-14 16:20:12] frigate.app                    INFO    : Starting Frigate (0.14.0-f54cb21)
2024-02-14 16:20:13.691434069  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-02-14 16:20:13.699724241  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-02-14 16:20:13.748869949  [INFO] Service NGINX exited with code 0 (by signal 0)
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"back":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.1,"capture_pid":349,"detection_enabled":1,"detection_fps":12.3,"ffmpeg_pid":354,"pid":344,"process_fps":10.0,"skipped_fps":0.0},"front":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":10.0,"capture_pid":346,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":351,"pid":342,"process_fps":10.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"6.8","cpu_average":"6","mem":"0.3"},"105":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"112":{"cmdline":"python3 -u -m frigate","cpu":"0.6","cpu_average":"1","mem":"3.1"},"120":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"158":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"171":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"297":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"1.5"},"304":{"cmdline":"frigate.recording_manager","cpu":"1.2","cpu_average":"0","mem":"1.9"},"313":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(44)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"314":{"cmdline":"frigate.detector.coral1","cpu":"1.7","cpu_average":"1","mem":"1.8"},"318":{"cmdline":"frigate.detector.coral2","cpu":"1.6","cpu_average":"1","mem":"1.8"},"324":{"cmdline":"frigate.output       ","cpu":"0.5","cpu_average":"0","mem":"1.7"},"331":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"334":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"337":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"342":{"cmdline":"frigate.process:front","cpu":"1.0","cpu_average":"1","mem":"1.8"},"344":{"cmdline":"frigate.process:back ","cpu":"3.8","cpu_average":"3","mem":"1.8"},"346":{"cmdline":"frigate.capture:front","cpu":"0.7","cpu_average":"0","mem":"1.6"},"349":{"cmdline":"frigate.capture:back ","cpu":"0.7","cpu_average":"0","mem":"1.6"},"351":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-f6a4c2a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_sub -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.7","cpu_average":"0","mem":"0.4"},"354":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-f6a4c2a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_sub -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"0","mem":"0.4"},"359":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-f6a4c2a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.3"},"360":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.14.0-f6a4c2a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/back@%Y%m%d%H%M%S%z.mp4","cpu":"0.4","cpu_average":"0","mem":"0.3"},"1097":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":12.3,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":7.8,"pid":314},"coral2":{"detection_start":1707881369.473971,"inference_speed":7.79,"pid":318}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":297},"recording":{"pid":304}},"service":{"last_updated":1707881369,"latest_version":"0.13.1","storage":{"/dev/shm":{"free":3069.9,"mount_type":"tmpfs","total":3072.0,"used":2.1},"/media/frigate/clips":{"free":5345037.0,"mount_type":"nfs4","total":5586894.0,"used":241857.0},"/media/frigate/recordings":{"free":5345037.0,"mount_type":"nfs4","total":5586894.0,"used":241857.0},"/tmp/cache":{"free":927.1,"mount_type":"tmpfs","total":953.7,"used":26.6}},"temperatures":{},"uptime":352,"version":"0.14.0-f6a4c2a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink

### Any other information that may be helpful

the last tag to work fine was; ghcr.io/blakeblackshear/frigate:dev-f6a4c2a
anything after then does not work - system starts but then exits after a few seconds with the go2rtc error in the logs.
