### ISSUE TITLE
[Detector Support]: problem using coral 

### ISSUE THREAD

**Issue by dakotasoukup** [blakeblackshear/frigate#9871]
### Describe the problem you are having

When I try to run with coral I get this error. 

2024-02-15 16:04:49.073810807    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-02-15 16:04:49.073812275      self.run()
2024-02-15 16:04:49.073817236    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-02-15 16:04:49.073819756      self._target(*self._args, **self._kwargs)
2024-02-15 16:04:49.073827869    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2024-02-15 16:04:49.073839435      detections = object_detector.detect_raw(input_frame)
2024-02-15 16:04:49.073840967    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2024-02-15 16:04:49.073842755      return self.detect_api.detect_raw(tensor_input=tensor_input)
2024-02-15 16:04:49.073845304    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 59, in detect_raw
2024-02-15 16:04:49.073867554      self.interpreter.set_tensor(self.tensor_input_details[0]["index"], tensor_input)
2024-02-15 16:04:49.073871560    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 572, in set_tensor
2024-02-15 16:04:49.073873809      self._interpreter.SetTensor(tensor_index, value)
2024-02-15 16:04:49.073888745  ValueError: Cannot set tensor: Dimension mismatch. Got 300 but expected 320 for dimension 1 of input 7.

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.170
  port: 1883 # <---- same mqtt broker that home assistant uses
  user: dakota
  password: foster47290

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml  

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0
      
#Global Object Settings
objects:
  track:
    - person
    - car
    - dog


record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30


model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: True
  mode: continuous
  
cameras:
  Backyard: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456@192.168.0.14/media/video2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:123456@192.168.0.14/media/video1
          roles:
            - record  
    motion:
       mask:    
        - 0,0,0,85,355,79,361,0            
  front: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://Admin:123456@192.168.0.44/stream1?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://Admin:123456@192.168.0.44/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
          roles:
            - record 
    motion:
        mask:  
            - 754,720,743,620,1280,667,1280,720            

  front2: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:Foster47290@192.168.0.233:554/Streaming/channels/2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:Foster47290@192.168.0.233:554
          roles:
            - record   
    objects:
      filters:
        car:
          mask:
                 - 0,0,0,251,314,403,600,405,1163,156    
    motion:
         mask:
              - 0,267,0,0,1280,0,1280,511                       

  driveway: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456@192.168.0.22/media/video2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:123456@192.168.0.22/media/video1
          roles:
            - record   
    record:
      events:
        required_zones:
        - zone_2
    zones:
        zone_1:
          coordinates: 388,0,28,170,371,389,1099,300,1220,136
        zone_2:
          coordinates: 747,335,911,264,1057,341,1016,501,821,635,75,628
    objects:
        filters:
          car:
            mask:
             - 809,27,656,0,383,68,400,81,304,126,582,427,1000,195,1022,124    
    motion:
      mask:
        - 0,0,0,95,288,151,378,0
  garage: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456@192.168.0.23/media/video2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:123456@192.168.0.23/media/video1
          roles:
            - record 
    motion:
      mask:  
          - 0,0,0,78,314,79,322,0        
    
go2rtc:
  streams:
    front2:
      - rtsp://admin:Foster47290@192.168.0.233:554/Streaming/channels/2
    front:
     -  rtsp://Admin:123456@192.168.0.44/stream1?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
    Backyard:
     - rtsp://admin:123456@192.168.0.14/media/video2
    driveway:  
    -  rtsp://admin:123456@192.168.0.22/media/video2
    garage:
    - rtsp://admin:123456@192.168.0.23/media/video2




mqtt:
  host: 192.168.0.170
  port: 1883 # <---- same mqtt broker that home assistant uses
  user: dakota
  password: foster47290

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml  

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0
      
#Global Object Settings
objects:
  track:
    - person
    - car
    - dog


record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
  retain:
    default: 30


model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: True
  mode: continuous
  
cameras:
  Backyard: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456@192.168.0.14/media/video2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:123456@192.168.0.14/media/video1
          roles:
            - record  
    motion:
       mask:    
        - 0,0,0,85,355,79,361,0            
  front: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://Admin:123456@192.168.0.44/stream1?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://Admin:123456@192.168.0.44/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
          roles:
            - record 
    motion:
        mask:  
            - 754,720,743,620,1280,667,1280,720            

  front2: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:Foster47290@192.168.0.233:554/Streaming/channels/2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:Foster47290@192.168.0.233:554
          roles:
            - record   
    objects:
      filters:
        car:
          mask:
                 - 0,0,0,251,314,403,600,405,1163,156    
    motion:
         mask:
              - 0,267,0,0,1280,0,1280,511                       

  driveway: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456@192.168.0.22/media/video2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:123456@192.168.0.22/media/video1
          roles:
            - record   
    record:
      events:
        required_zones:
        - zone_2
    zones:
        zone_1:
          coordinates: 388,0,28,170,371,389,1099,300,1220,136
        zone_2:
          coordinates: 747,335,911,264,1057,341,1016,501,821,635,75,628
    objects:
        filters:
          car:
            mask:
             - 809,27,656,0,383,68,400,81,304,126,582,427,1000,195,1022,124    
    motion:
      mask:
        - 0,0,0,95,288,151,378,0
  garage: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456@192.168.0.23/media/video2
          roles:
            - detect
            - rtmp # <- deprecated, recommend using restream instead
        - path: rtsp://admin:123456@192.168.0.23/media/video1
          roles:
            - record 
    motion:
      mask:  
          - 0,0,0,78,314,79,322,0        
    
go2rtc:
  streams:
    front2:
      - rtsp://admin:Foster47290@192.168.0.233:554/Streaming/channels/2
    front:
     -  rtsp://Admin:123456@192.168.0.44/stream1?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
    Backyard:
     - rtsp://admin:123456@192.168.0.14/media/video2
    driveway:  
    -  rtsp://admin:123456@192.168.0.22/media/video2
    garage:
    - rtsp://admin:123456@192.168.0.23/media/video2
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "900mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/dakota/config/config.yml:/config/config.yml:ro
      - /media/dakota/storage2/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      LIBVA_DRIVER_NAME: i965
```

### Relevant log output

```shell
2024-02-15 16:09:05.499972527  Process detector:coral:
2024-02-15 16:09:05.500745446  Traceback (most recent call last):
2024-02-15 16:09:05.500792471    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-02-15 16:09:05.500795503      self.run()
2024-02-15 16:09:05.500798275    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-02-15 16:09:05.500804857      self._target(*self._args, **self._kwargs)
2024-02-15 16:09:05.500832755    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2024-02-15 16:09:05.500835454      detections = object_detector.detect_raw(input_frame)
2024-02-15 16:09:05.500837765    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2024-02-15 16:09:05.500839895      return self.detect_api.detect_raw(tensor_input=tensor_input)
2024-02-15 16:09:05.500842412    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 59, in detect_raw
2024-02-15 16:09:05.500868708      self.interpreter.set_tensor(self.tensor_input_details[0]["index"], tensor_input)
2024-02-15 16:09:05.500872154    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 572, in set_tensor
2024-02-15 16:09:05.500874214      self._interpreter.SetTensor(tensor_index, value)
2024-02-15 16:09:05.501002760  ValueError: Cannot set tensor: Dimension mismatch. Got 300 but expected 320 for dimension 1 of input 7.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
