### ISSUE TITLE
inactivity_threshold seems broken

### ISSUE THREAD

**Issue by CyberFlexie** [blakeblackshear/frigate#9878]
### Describe the problem you are having

Adding inactivity_threshold like mentioned in docs gives an error:

Property inactivity_threshold is not allowed.yaml-schema: BirdseyeConfig(0)

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
birdseye:
  enabled: True
  inactivity_threshold: 15
```

### Relevant log output

```shell
nothing
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
