### ISSUE TITLE
Nuc heats up

### ISSUE THREAD

**Issue by gieljnssns** [blakeblackshear/frigate#998]
**Describe the bug**
A clear and concise description of what your issue is.
My intel NUC gets real hot when starting up the frigate addon using a coral USB
Cpu doesn't go very high

**Version of frigate**
Output from `/api/version`
0.8.4-5043040
**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
{
  "cameras": {
    "tuin": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": [
          "person"
        ],
        "post_capture": 15,
        "pre_capture": 15,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://XXXXXX:XXXXXXXXXXX@192.168.89.132:554/cam/realmonitor?channel=1&subtype=2 -r 5 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://XXXX:XXXXXXXXXXXXXXXXX@192.168.89.132:554/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/tuin-%Y%m%d%H%M%S.mp4",
          "roles": [
            "clips"
          ]
        }
      ],
      "fps": 5,
      "frame_shape": [
        720,
        1280
      ],
      "height": 720,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 120,
        "mask": [
          "0,396,286,321,369,319,368,240,480,236,1280,242,1280,0,0,0",
          "1280,720,771,720,893,237,1280,244"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "tuin",
      "objects": {
        "filters": {
          "person": {
            "mask": [],
            "max_area": 100000,
            "min_area": 5000,
            "min_score": 0.5,
            "threshold": 0.65
          }
        },
        "mask": null,
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": true,
        "height": 175,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": true
      },
      "width": 1280,
      "zones": {
        "achterdeur": {
          "coordinates": "487,565,798,563,788,262,489,271",
          "filters": {
            "person": {
              "mask": [],
              "max_area": 100000,
              "min_area": 5000,
              "min_score": 0.5,
              "threshold": 0.7
            }
          }
        },
        "poort": {
          "coordinates": "487,439,330,431,348,245,482,241",
          "filters": {
            "person": {
              "mask": [],
              "max_area": 100000,
              "min_area": 5000,
              "min_score": 0.5,
              "threshold": 0.7
            }
          }
        }
      }
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "core-mosquitto.local.hass.io",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "hass"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for tuin: 46
detector.coral                 INFO    : Starting detection process: 44
frigate.app                    INFO    : Capture process started for tuin: 48
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
frigate.video                  INFO    : tuin: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : tuin: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : tuin: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : tuin: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : tuin: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : tuin: ffmpeg process is not running. exiting capture thread...
```

**Frigate stats**
```json
{
  "detection_fps": 0.0,
  "detectors": {
    "coral": {
      "detection_start": 0.0,
      "inference_speed": 8.26,
      "pid": 44
    }
  },
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 8325.2,
        "mount_type": "tmpfs",
        "total": 8327.1,
        "used": 1.9
      },
      "/media/frigate/clips": {
        "free": 369617.4,
        "mount_type": "ext4",
        "total": 491505.0,
        "used": 96902.4
      },
      "/media/frigate/recordings": {
        "free": 369617.4,
        "mount_type": "ext4",
        "total": 491505.0,
        "used": 96902.4
      },
      "/tmp/cache": {
        "free": 8254.9,
        "mount_type": "tmpfs",
        "total": 8327.1,
        "used": 72.2
      }
    },
    "uptime": 29046,
    "version": "0.8.4-5043040"
  },
  "tuin": {
    "camera_fps": 5.1,
    "capture_pid": 48,
    "detection_fps": 0.0,
    "pid": 46,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  }
}

```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>

    ~                                                                                                                                      4s 
❯ ffprobe rtsp://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.89.132:554/cam/realmonitor?channel=1&subtype=2
[1] 57904
zsh: no matches found: rtsp://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.89.132:554/cam/realmonitor?channel=1
[1]  + 57904 exit 1     ffprobe rtsp://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.89.132:554/cam/realmonitor?channel=1

    ~ 
❯ ffprobe rtsp://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.89.132:554/live
ffprobe version 4.3.2 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.2_4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.89.132:554/live':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.042000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 15 fps, 100 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

    ~ 

```
will do as soon as possible

**Screenshots**
![1](https://user-images.githubusercontent.com/17234951/114753056-5644d800-9d57-11eb-8d21-a50824e1e1f3.png)
![2](https://user-images.githubusercontent.com/17234951/114753074-59d85f00-9d57-11eb-97c9-8db17d906ff6.png)

**Computer Hardware**
 - OS: HAOS
 - Install method:  Addon
 - Virtualization:
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Dahua
 - Model: [e.g. IPC-HDBW5831E-Z5E]
 - Resolution:  720p
 - FPS:  5

**Additional context**
